### ISSUE TITLE
Support native envoy 

### ISSUE THREAD

**Issue by rverma-nikiai** [kiali/kiali#1006]
Aws app mesh also uses envoy proxy similar to Istio. Will it be possible to extend the implementation to support that.
I am willing to send a PR, please let me know. Also would be nice to provide a design doc so that contributors can quickly visualize the components.

**Comment by abonas** [comment]
Can you elaborate more? What does it mean to support native Envoy? Aws App mesh is also mentioned in the description, please clarify.
