### ISSUE TITLE
kiali floods prometheus with too many request 

### ISSUE THREAD

**Issue by ajitchahal** [kiali/kiali#1008]
**Describe the bug**
The load test on a vanilla kubernetes cluster, flooded Prometheus with too many distinct queries, which made it crash with out of memory error on 64GB AWS vm.

**Versions used**
Kiali: v0.16
Istio: 1.0.7
Kubernetes flavour and version: AWS custom install v1.12.3

**To Reproduce**
just enable kiali in istio(mtls enabled) 1.0.7 chart, 
 * monitor kiali 
 * monitor additional dashboards

![kiali](https://user-images.githubusercontent.com/1849411/56147158-fcfb1000-5fa7-11e9-8653-d6aca16a0655.png)

Yellow line designates when kiali was shut down.

**Comment by ajitchahal** [comment]
p.s. the graph displays memory utilization if Prometheus node (node affinity=only Prometheus running on the node)

**Comment by jmazzitelli** [comment]
Can you indicate what your Kiali UI's "Fetching" settings are? Look at the top right of the graph page.

I wonder how often you are asking Kiali to generate a graph - and how large your graph is.

Kiali has its own metrics - might be best to capture those for us as well (see the prometheus timeseries that start with "kiali_"

**Comment by lucasponce** [comment]
cc @gbaufake @hhovsepy

**Comment by jshaughn** [comment]
The Kiali metrics would be helpful.  It shouldn't really generate any significant load other than from UI requests.  Can you indicate how many client UIs may be operating and roughly what they may be doing?

**Comment by lucasponce** [comment]
@ajitchahal we would like to reproduce same scenario you are using.
I see @jmazzitelli @jshaughn prepared some questions that probably might help to understand your problem.
Could you help us with those ? 
Thanks

**Comment by gbaufake** [comment]
@lucasponce @jshaughn 

I think I am hitting the same scenario on KIALI-2643 and KIALI-2686
