### ISSUE TITLE
What to do with monitoring dashboard CRD and CRs?

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#1019]
cc @shawn-hurley @jotak @lucasponce @mwringe @gbaufake 

There is a problem in the operator SDK when operators want to install CRDs.

See: https://github.com/operator-framework/operator-sdk/issues/1330

The issue technically is going to be fixed - the PR is here: https://github.com/operator-framework/operator-sdk/pull/1329

However, @shawn-hurley has mentioned that operators really shouldn't be creating CRDs, especially when integrated with OLM and OperatorHub.io. @shawn-hurley - feel free to add more information that would be helpful to us in understanding the issue.

I would like to have a discussion here about how we want to handle this in the future. I know @jotak  and @lucasponce were asking the question about what do we want to do with our monitoring dashboards CRD (do we want to move them to a different place?).

Right now, the operator installs the CRD and the dashboard CRs with the rest of everything else.

**Comment by jotak** [comment]
@jmazzitelli depending on where the CRD file & associated resouces are actually hosted (I mean, which github repo), does it change anything about who is responsible to deploy them?
I mean, we had the idea in mind to move the files to another repo, but still it would be the oeprator's job, I think, to deploy the resources, no?

About the CRD more specifically: if the operator shouldn't manage it, then, who / what is in charge of that? (I mean, in general... for example, how istio does that?)

**Comment by dmesser** [comment]
In Operator Framework, OLM would be responsible for managing CRDs. OLM would deploy them for you and would also handle CRD versioning during Operator updates. This relieves you from adding cluster-wide permissions to create and read CRDs to your Operator which is considered a security risk.

**Comment by jmazzitelli** [comment]
@jotak Istio creates the CRDs itself in his helm chart stuff - but remember, Istio doesn't use operators (today)... though some operator stuff is starting to slowly enter the istio install framework (prometheus for example).

**Comment by jmazzitelli** [comment]
This has been dealt with. The CRDs (the operator and runtime dashboards CRDs) must be installed prior to deploying the operator itself. The deploy script now does this because the crd.yaml the deploy script uses now includes the dashboard CRD - https://github.com/kiali/kiali/blob/v0.21/operator/deploy/crd.yaml#L1-L17
