### ISSUE TITLE
Kiali Operator v0.18.0 does not work on Kubernetes

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#1020]
The Kiali Operator version 0.18.0 works on OpenShift. It does not work on Kubernetes.

The master branch current does support both. When we release the next version of the Kiali Operator, it will support both.

**Comment by jmazzitelli** [comment]
Workaround:

I published an operator image on my personal repo at quay.io that supports kubernetes. If you want to try the Kiali Operator on k8s, you should be able to run this:

```
OPERATOR_IMAGE_NAME=quay.io/jmazzitelli/kiali-operator OPERATOR_IMAGE_VERSION=pr1017 OPERATOR_VERSION_LABEL=v0.18.0 bash <(curl -L https://git.io/getLatestKialiOperator)
```

**Comment by pilhuhn** [comment]
Where do we stand here?

**Comment by gbaufake** [comment]
@jmazzitelli 
What is the problem when it runs with kubernetes?

**Comment by jmazzitelli** [comment]
We can close this - 0.18.1 operator works with k8s now.
