### ISSUE TITLE
hack: This script is no longer used to install Kiali. Instead, use the Kiali Operator

### ISSUE THREAD

**Issue by durandom** [kiali/kiali#1034]
When using `hack/cluster-openshift.sh --kiali-enabled true up` to install with kiali I get 

```
This script is no longer used to install Kiali. Instead, use the Kiali Operator.
For more details, see https://www.kiali.io/gettingstarted
```

Which is ok, but it would be great if the hack script could add the custom resources to deploy kiali via the operator

**Comment by jmazzitelli** [comment]
good catch... lemme see if I can fix that now.

**Comment by jmazzitelli** [comment]
try PR #1035 - should fix this.

**Comment by jmazzitelli** [comment]
PR is merged. This should be fixed now.
