### ISSUE TITLE
No traffic metrics, or service diagrams

### ISSUE THREAD

**Issue by PsychoSid** [kiali/kiali#1046]
**General remarks**

> Please delete this section including header before submitting
>
> This form is to report bugs. For general usage questions refer to 
>       [Kiali-users](https://groups.google.com/forum/#!forum/kiali-users) mailing list.
>
> For general Kiali-development questions refer to 
>       [Kiali-dev](https://groups.google.com/forum/#!forum/kiali-dev) mailing list.

**Describe the bug**
Saw no traffic stats, or graphs

**Versions used**
Kiali: Latest
Istio: 1.0.6
Kubernetes flavour and version: GKE 1.12

**To Reproduce**
I installed GKE cluster, and Istio as defined from GKE via terraform addon_configs parameters. This installs v1.0.6 os Istio.

The Prometheus instance service is called "promsd" in this instance. 

Kiali was deployed via the latest operator.

I amended the resultant configmap to change prometheus.istio-system to promsd.istio-system to fix that part up and I then the services appeared in Kiali.

I then generated a fair degree of load on the service and saw 200s returned and StackDriver saw incoming requests

**Expected behavior**
Traffic graphs and mesh diagrams.

I see some references to the Kiali version but wasn't sure how to deploy v0.16.2 (if this is what is needed) as OPERATOR_IMAGE_VERSION didn't exist on the same path as the current version.

Is it a version thing (if so how do I deploy a working version of kiali) or something I did wrong with this test deployment ?

**Comment by jshaughn** [comment]
The latest Kiali requires Istio 1.1 due to changes in the Istio telemetry.  I think Kiali 0.16 is the last version compatible with Istio 1.0.

**Comment by PsychoSid** [comment]
Thanks I suspected as much but the path with the latest script don’t match with that branch even setting the environment variable as I mentioned Is there a “best” way to install 0.16 that you know of ?

**Comment by israel-hdez** [comment]
@PsychoSid do you need Istio 1.0.x, or can you upgrade to 1.1.x?

The Kiali operator was introduced in Kiali v0.18.0, so it won't work for previous versions. If you require Istio 1.0.6, then try this to install Kiali 0.16:

```bash
IMAGE_VERSION=v0.16 bash <(curl -L https://raw.githubusercontent.com/kiali/kiali/v0.16.2/deploy/kubernetes/deploy-kiali-to-kubernetes.sh)
```

(I didn't test)

**Comment by PsychoSid** [comment]
Hi,

Probably can we are just dipping our toes into GKE, and 1.0.6 is the version that comes with that if you enable it via them.

Idea was to review/benchmark that with the latest from the repo so that would be 1.1.x so we can say wether to roll our own as it were rather than what Google give us.

Thanks so much for the help. Will close this and go from there.
