### ISSUE TITLE
LDAP integration

### ISSUE THREAD

**Issue by sujithvs74** [kiali/kiali#1053]
We are looking for an option to integrate LDAP with kiali-ui, which will enable us to share kiali to application team to view status of services. Is there any option for it.

**Comment by israel-hdez** [comment]
Hi, @sujithvs74 

Currently, Kiali does not support integration with LDAP. There are plans for supporting other authentication systems, but are for medium to long term. Also, we will be happy to accept PRs if you know and have the time to implement it.

Another user has previously asked something similar. See: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/kiali-dev/n1J07xRmMzQ/w3DoOBvwAQAJ. Apparently, his workaround was to put Kiali behind a reverse proxy capable of doing the authentication. I suggest you try that route if a reverse proxy is feasible for you and you need it soon.

**Comment by israel-hdez** [comment]
Hi, @sujithvs74 
I'm wondering if you would like to collaborate and implement this feature.
Nodbody in the team knows well LDAP. If you have the knowledge, I would like to know if you want to help for this.

**Comment by Maneshme** [comment]
I'm current have implemented this feature

**Comment by jmazzitelli** [comment]
I'm in the process of finalizing the two PRs (one server side, one UI side). Molecule tests show the feature working. So this should be ready to merge fairly soon.

**Comment by jmazzitelli** [comment]
PR with server-side changes: https://github.com/kiali/kiali/pull/1323
PR with UI changes: https://github.com/kiali/kiali-ui/pull/1335

**Comment by jmazzitelli** [comment]
This feature has been implemented and is now in master.
