### ISSUE TITLE
feature request: oidc authentication

### ISSUE THREAD

**Issue by mrparkers** [kiali/kiali#1071]
I looked around and did not see another issue for this request.  Apologies if one already exists or this work is already prioritized.

I'd like Kiali to support generic OIDC authentication using the authorization code flow for logging in to the dashboard.  This would be a good feature to add, as it will allow organizations with an SSO provider (auth0, okta, etc) to provide authentication for Kiali.

For configuration (at least within Kubernetes), a Secret could be configured with keys `oidcClientId`, `oidcClientSecret`, and `oidcIssuer`.  All of these values would be provided by an IDP.

When navigating to the dashboard for the first time, users could click a "Log in with SSO" button, which would redirect them to the configured IDP to start the authorization code flow.

I'd be willing to attempt a PR to get this feature implemented, but I may need some direction for where to start and what files I would be expected to touch.  I've seen other apps use [dexidp/dex](https://github.com/dexidp/dex) to handle OIDC, so I may gravitate towards that solution so I am not reinventing the wheel, unless I'm given some other direction.

Thanks!

**Comment by israel-hdez** [comment]
@mrparkers It would be nice if you try to implement the feature. Kiali maintainers may not have enough knowledge of OIDC. If you have the knowledge, just try.

If you need any direction, try the kiali-dev list for questions about getting started, setting up your env, etc.: https://groups.google.com/forum/#!forum/kiali-dev

Reserve this issue to give/receive feedback about the feature.

> what files I would be expected to touch

You can touch any file to get the feature implemented. At anytime you could open a draft/final PR and you will receive feedback if any code may be better placed.

**Comment by pilhuhn** [comment]
@mrparkers Are you making progress on this? @a-thaler is looking at the same thing in #1175 and I am sure he could at least help you testing

**Comment by jmazzitelli** [comment]
Just FYI if anyone wants to implement generic OAuth functionality - don't forget you will need to change the [Kiali Operator](https://github.com/kiali/kiali/blob/master/operator/roles/kiali-deploy/tasks/main.yml#L116-L133) and the kiali operator [deployment script](https://github.com/kiali/kiali/blob/master/operator/deploy/deploy-kiali-operator.sh#L424-L441).

**Comment by mrparkers** [comment]
Sorry @pilhuhn, I haven't had a chance to work on this yet.  I was able to use the [Keycloak Gatekeeper](https://github.com/keycloak/keycloak-gatekeeper) proxy as a temporary solution until I get time to work on this.

If someone else is interested in working on this instead they are more than welcome to - I am not quite sure when I will have the time to do it justice.

**Comment by jmazzitelli** [comment]
This is a dup of https://github.com/kiali/kiali/issues/2056
