### ISSUE TITLE
Feature Request: Adds support for zipkin

### ISSUE THREAD

**Issue by jcchavezs** [kiali/kiali#1079]
Currently kiali supports jaeger and grafana. I would like to use it with zipkin. Any chance we could add support for it or are you open for a PR including this feature?

**Comment by abonas** [comment]
jcchavezs thanks for opening this issue. What kind of support are you asking/proposing - how would this feature look in the UI, for example? configuration options? 
@theute @objectiser @pilhuhn

**Comment by israel-hdez** [comment]
Hi, @jcchavezs are you still interested in this feature?
From kiali side, this seems to be very low priority. So, if you have the time to prepare a PR, it will be welcome. Just first discuss here what is your idea, since this sounds a big change.

**Comment by lucasponce** [comment]
@jcchavezs I've marked this issue as "help wanted" as any contribution from the community is welcome.
As it's been discussed, perhaps it would be good to have some details about the proposal, but good if other teams would like to collaborate in Kiali.

**Comment by jcchavezs** [comment]
Hi there, thanks for replying. I will definitively come up with a PR for this.

**Comment by lucasponce** [comment]
With the current work in the replacement of Jaeger iFrame, now Kiali provides an abstraction layer to communicate with the tracing solution.

So, adding support for zipkin could be simplified, assuming that they provide similar queries to the backend for fetching traces and spans.

This is still interesting as a Istio community effort.
