### ISSUE TITLE
Feature request: Allow routing based on presence of headers

### ISSUE THREAD

**Issue by brianredbeard** [kiali/kiali#1085]
When using Kiali to configured matched routing it is possible to configure routing based on header pattern matching:

![image](https://user-images.githubusercontent.com/57542/58123113-f58ae000-7bbf-11e9-8b81-f9eaa6518671.png)

It is desirable to allow routing based on the mere presence (or lack thereof).  This is used with utilities like [oauth2 proxy][oa2p] in concert with tools like Jenkins to handle identity and access control.  A detailed example of what this looks like when used with nginx can be seen [here][nginx-config].

I would foresee this being configured in a boolean fashion: 
  - if header present, go to service A, if not go to service B

Curious as to other thoughts/insight folks may have.  I realize that this could be configured today with regex rules, though if we could provide a mechanism which is easier to understand this could be attractive to users.

[oa2p]: https://github.com/openshift/oauth-proxy
[nginx-config]: https://github.com/openshift/oauth-proxy#configuring-for-use-with-the-nginx-auth_request-directive

**Comment by lucasponce** [comment]
@brianredbeard thanks for the issue.
It's quite interesting.

This Wizard is basically matching the VirtualService/HTTPMatchRequest format
https://istio.io/docs/reference/config/networking/v1alpha3/virtual-service/#HTTPMatchRequest

So, as you point, the only way this can be configured is using a regex as the only available operators in the VS are "exact", "prefix", "regex".

From Kiali, the only option I see is to offer some high level option that simulates the "present" operator and that is "translated" into a regex in the resulting VS.

I will create a JIRA to follow this and investigate it.

**Comment by pilhuhn** [comment]
@lucasponce Yes, I think a "is present" could be internally be translated into `regex: .*`

**Comment by lucasponce** [comment]
https://issues.jboss.org/browse/KIALI-2989

**Comment by israel-hdez** [comment]
(Still under consideration. Please, see [KIALI-2989](https://issues.jboss.org/browse/KIALI-2989) for tracking)
