### ISSUE TITLE
Upgrade Kiali version

### ISSUE THREAD

**Issue by APuertaSales** [kiali/kiali#1086]
We are using Kiali installed via Istio. Latest Istio version is 1.1.7 and includes Kiali version 0.16
We would like to upgrade to version 0.20 to check new functionalities but just changing the version of the Kiali image to install is not enough as some components as ClusterRole must be updated.

How can we upgrade successfully Kiali when is installed via Istio Helm charts?
https://www.kiali.io/documentation/installation/
Thanks in advance!

**Comment by abonas** [comment]
@jmazzitelli I remember some thread about a similar topic, but I can't find it

**Comment by jmazzitelli** [comment]
We do not currently have official upgrade docs for moving up from upstream Istio helm charts.

What you can do is uninstall Kiali completely and then you can use the Kiali Operator to install the latest Kiali.

```
kubectl delete --ignore-not-found=true all,secrets,sa,templates,configmaps,deployments,clusterroles,clusterrolebindings,ingresses,customresourcedefinitions --selector="app=kiali" -n "istio-system"
```

If you are on OpenShift, do this too:

```
oc delete --ignore-not-found=true oauthclients.oauth.openshift.io --selector="app=kiali" -n "istio-system"
```

Once Kiali is removed, install the latest - see https://www.kiali.io/gettingstarted ... it is basically just running `bash <(curl -L https://git.io/getLatestKialiOperator)`

**Comment by APuertaSales** [comment]
Thanks for the info!
Then I think is better to not install Kiali by the Istio way from the beginning to avoid the extra work.
As you are including a lot of good functionalities almost each week is important for us be able to upgrade easily and check them.
Regards.

**Comment by jmazzitelli** [comment]
I need to go over to upstream Istio and upgrade the helm chart to pull in a later version of Kiali. On my TODO but haven't had a chance to do it yet.
