### ISSUE TITLE
Invalid subject name for viewing kiali on localhost

### ISSUE THREAD

**Issue by majelbstoat** [kiali/kiali#1132]
Kiali does not load correctly on localhost, owing to an invalid subject cert name.

Repro:

* Installed kiali per these instructions, choosing anonymous as the login option: https://www.kiali.io/documentation/getting-started/
* Forwarded the port with `kubectl port-forward svc/kiali 20001:20001 -n istio-system` which succeeded.
* Visited https://localhost:20001/kiali

Chrome refuses to connect with `NET::ERR_CERT_INVALID`

Inspecting the error shows:

<img width="982" alt="Screenshot 2019-06-11 11 25 32" src="https://user-images.githubusercontent.com/425787/59296804-a9214600-8c3b-11e9-93c2-2f81b6cc460f.png">

"Invalid certificate subject name"

The field appears to be blank when looking at the cert.

**Versions used**
Kiali Operator: 0.20
Istio: 1.1.3-gke.0
Kubernetes flavour and version: GKE 1.13.6-gke.5

**Expected behavior**

The dashboard displays correctly.

**Comment by lucasponce** [comment]
Yes, I suspect the certificate used is signed with the internal kiali service instead localhost.
Then this scenario will always fail.

I guess for demo scenarios like this, perhaps an option to expose the Kiali service in plain http could work.

In a real scenario, the idea is that you expose the service through a LoadBalancer / Ingress with a valid domain. If we use self-signed certificates we would have same message, too.

cc @jmazzitelli as we have discussed something similar.

I'll fill a JIRA for this.

**Comment by lucasponce** [comment]
https://issues.jboss.org/browse/KIALI-3010

**Comment by jmazzitelli** [comment]
> an option to expose the Kiali service in plain http could work

PR for KIALI-3010 is ready for review: https://github.com/kiali/kiali/pull/1136

**Comment by majelbstoat** [comment]
I've confirmed that the workaround works with kiali 0.21, when editing the spec to set empty string for cert and key. Thanks!
