### ISSUE TITLE
Kiali doesn't understand namespaced Gateway selector in VirtualService

### ISSUE THREAD

**Issue by sergeydeg** [kiali/kiali#1154]
**Describe the bug**
Gateways declaration inside VirtualService from different namespace, as recommended by Istio docs not recognized as valid.

![image](https://user-images.githubusercontent.com/6221680/59605567-bf397580-9117-11e9-9929-e58e54f49ab2.png)

![image](https://user-images.githubusercontent.com/6221680/59605721-0b84b580-9118-11e9-9e28-d2f748ee0aa8.png)

Also link to gateway is broken

![image](https://user-images.githubusercontent.com/6221680/59605865-6ae2c580-9118-11e9-8b94-0209301681b5.png)

gateway link pointed to 
.../console/namespaces/**_dmz_**/istio/gateways/istio-system/elieta-ingress-gateway

**Versions used**

> kiali-ui 0.16.0 (c2ce0549f3123889254bb303c49d783f16278d73)
> kiali v0.16.2 (dd6d04bd486ef1d56d0567f7cd8adcee31196867)
> Components
> Istio 1.1.8
> Prometheus 2.3.1
> Kubernetes v1.13.5

**To Reproduce**

1. Create Gateway in istio-system namespace
2. Create VirtualService in different namespace, and point to gateway  by istio-system/_gateway-name_

**Expected behavior**
Namespaced gateways declaration shall be valid, and crossreference to gateway shall be valid.

**Comment by abonas** [comment]
cc @lucasponce @xeviknal 
it sounds related to https://github.com/istio/istio/issues/11131
AFAIK it was supposed to be fixed recently, but it looks like @sergeydeg uses an earlier verison of Kiali, and I'm not sure whether it contains the fix.

**Comment by lucasponce** [comment]
Yes, this is due Kiali 0.16.
Please, try to update to Kiali 0.21 and I think this issues should be gone.
https://www.kiali.io/documentation/getting-started/ should contain how to update.

Also, there was another issue where I drafted some commands to help how to upgrade step by step:
https://github.com/kiali/kiali/issues/1153#issuecomment-502643729

**Comment by sergeydeg** [comment]
Thanks @lucasponce . Migration to latest Kiali solved issue.
