### ISSUE TITLE
Embedding jaeger ui inside kiali

### ISSUE THREAD

**Issue by varungbt** [kiali/kiali#1160]
I am using istio 1.1.7 and I would like to embed jaeger dashboards inside Kiali

![image](https://user-images.githubusercontent.com/4632477/59786127-2841fa00-928c-11e9-9ed2-846a8a1b09b2.png)

When I click on the distributed caching menu option, I do see a request being routed to external Jaeger URL. 
The response is 200 with some chunks related js files.

However the embedding of jaeger metrics is not successful

I see the messsage
`You need to enable JavaScript to run this app.`

Why is this happening ?

**Comment by aljesusg** [comment]
Hi @varungbt, Which version of Jaeger are you using? You need 1.9 or major for Embedded feature. The error in the iframe is from Jaeger so this is working.

Another test is try to open this endpoint in a new tab, Can you add a screenshot? 

Thanks

**Comment by varungbt** [comment]
@aljesusg  thanks for your reply. I do use istio 1.1.7,  with [ jaeger version set to 1.9 ].(https://github.com/istio/istio/blob/eec7a74473deee98cad0a996f41a32a47dd453c2/install/kubernetes/helm/istio/charts/tracing/values.yaml#L32
)
I tried to open the endpoint in a new tab, but it routes back to kiali webpage with no change.

**Comment by aljesusg** [comment]
I mean the Jaeger URL of the iframe no a new tab

**Comment by varungbt** [comment]
![image](https://user-images.githubusercontent.com/4632477/59793128-698dd600-929b-11e9-8e99-08944ad42451.png)

**Comment by varungbt** [comment]
I also tried to open the new tab from here but I see the same error webpage
![image](https://user-images.githubusercontent.com/4632477/59793536-719a4580-929c-11e9-8337-a54763b6aed5.png)

**Comment by varungbt** [comment]
I tried to open a new tab using the iframe url but I see the same error
![image](https://user-images.githubusercontent.com/4632477/59793736-e2d9f880-929c-11e9-9b70-683c0fe09f2b.png)

**Comment by varungbt** [comment]
I also tried to use istio 1.2 but I see the same error `You need to enable JavaScript to run this app.`

Is there a way to directly goto the jaeger url in a new tab on the click of distributed tracing without the embedding inside kiali ?

**Comment by aljesusg** [comment]
Where are you based? Maybe we can make a call to solve your problem, because I don't understand. 
I am in PTO until next Monday we can talk in the IRC freenode channel #kiali.

Anyway there is a troubleshooting website for Jaeger in https://www.kiali.io/documentation/distributed-tracing/#_help_to_debug_troubleshooting

**Comment by varungbt** [comment]
Sure @aljesusg. 
I am based out in Texas. I joined the channel but cannot find you ..

**Comment by lucasponce** [comment]
@varungbt I saw you but just I answered late :-)
Alberto is on PTO but I can try to help you.

**Comment by lucasponce** [comment]
I don't know if that helps but looking the issue, I wonder if it could be related about how you expose Jaeger externally and how to you pass that info to Kiali.

For example, Jaeger can be exposed in several ways (LoadBalancer IP, Proxy, or Ingress).

I follow the Istio recommendation an I normally use the Ingress way:

```
Expose the Telemetry add-ons.
    For the workshop we will use a insecure HTTP port.
    
 curl -L https://git.io/fj2rL | kubectl apply -f -
 
 # Verify Telemetry add-ons
 export INGRESS_HOST=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
 
 # Linux helper
 # xdg-open is a command to open a browser from the command line.
 # Mac users can use "open" command
 # Windows users can use "cmd" command
 # Otherwise, the check is just to confirm you can access addons from your browser

 export KIALI_URL="http://${INGRESS_HOST}:15029/kiali"
 export PROMETHEUS_URL="http://${INGRESS_HOST}:15030/" 
 export GRAFANA_URL="http://${INGRESS_HOST}:15031/"
 export JAEGER_URL="http://${INGRESS_HOST}:15032/jaeger"
 
 # Kiali, Prometheus, Grafana, Jaeger
 xdg-open ${KIALI_URL} && \
 xdg-open ${PROMETHEUS_URL} && \
 xdg-open ${GRAFANA_URL} && \
 xdg-open ${JAEGER_URL}
```

Then the JAEGER_URL I use is the Ingress with the default port opened by Istio.

Then next step is to install/update Kiali.

I use this Kiali CR:

```
apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
annotations:
  ansible.operator-sdk/reconcile-period: "0s"
spec:
  deployment:
    accessible_namespaces: [ "**" ]
  external_services:
    grafana:
      url: $GRAFANA_URL
    tracing:
      service: tracing
      url: $JAEGER_URL
  identity:
    cert_file: ""
    private_key_file: ""
```

Where I update the URLs from the variables (note, on this case, I use kiali latestrelease image - 0.21 - 
and I expose).

Then I update/install Kiali from the operator using

```
 bash <(curl -L https://git.io/getLatestKialiOperator) --kiali-cr $HOME/update-kiali-cr.yaml
```

where update-kiali-cr.yaml is the personalized yaml with the change in the variables.

Let me know if you resolve the problem you are seeing.

**Comment by aljesusg** [comment]
@varungbt @lucasponce if you have access via browser to that URL you shouldn't have problem via kiali

**Comment by lucasponce** [comment]
Ok, commented with @varungbt:

After adding "/jaeger" to the JAEGER_URL used, we can fix the problem.

**Comment by varungbt** [comment]
@lucasponce  thanks a lot ..

**Comment by aljesusg** [comment]
What environment are you using? Kubernetes? @varungbt

**Comment by varungbt** [comment]
Yes kubernetes

**Comment by aljesusg** [comment]
Ok thanks @varungbt this will be improved in https://github.com/kiali/kiali/pull/1155 , Kiali will look the deployment configuration of Jaeger to get the QUERY_BASE_PATH in kubernetes .

**Comment by aljesusg** [comment]
Can we close this @varungbt ?
