### ISSUE TITLE
UI:namespaces display is incomplete

### ISSUE THREAD

**Issue by sniperking1234** [kiali/kiali#1166]
Versions used: 
Kiali:0.21
Chrome:75
![ui](https://user-images.githubusercontent.com/7834655/59848330-709a0e80-9397-11e9-8e9b-57561153ada5.png)
When there are a lot of namespaces, some of them don't show up.
I think it's better to add a scroll bar.

**Comment by abonas** [comment]
cc @josejulio  @serenamarie125 fyi

**Comment by josejulio** [comment]
Wow, that's a lot of namespaces :). As a workaround you can filter them for now. I'll try to add a scrollbar when this happens
