### ISSUE TITLE
Set log level is not intuitive

### ISSUE THREAD

**Issue by pavolloffay** [kiali/kiali#1169]
Setting log level on kiali is not intuitive:

```
  -v value
    	log level for V logs
```

I would propose at least adding a message with possible values as now instead of a human readable levels `debug, trace...` it accepts numbers `1, 2...`
 
```
docker run -it --rm kiali/kiali -h                                                                                                          10:03 
Usage of /opt/kiali/kiali:
  -alsologtostderr
    	log to standard error as well as files
  -config string
    	Path to the YAML configuration file. If not specified, environment variables will be used for configuration.
  -log_backtrace_at value
    	when logging hits line file:N, emit a stack trace
  -log_dir string
    	If non-empty, write log files in this directory
  -logtostderr
    	log to standard error instead of files
  -stderrthreshold value
    	logs at or above this threshold go to stderr
  -v value
    	log level for V logs
  -vmodule value
    	comma-separated list of pattern=N settings for file-filtered logging
```

**Comment by jotak** [comment]
These command line args are not managed by Kiali but by third-party, here it's `glog` lib, so I fear this is something we don't have control on.

**Comment by pavolloffay** [comment]
There could be at least  a doc saying what is a valid value

**Comment by jmazzitelli** [comment]
> There could be at least a doc saying what is a valid value

This is the verbosity level setting. You change the verbosity level in Kiali by configuring it in the Kiali CR. All Kiali CR configuration settings are documented in the `kiali_cr.yaml` file here:

https://github.com/kiali/kiali/blob/v1.3.1/operator/deploy/kiali/kiali_cr.yaml#L171-L174

```
# Determines which priority levels of log messages Kiali will output.
# Typical values are "3" for INFO and higher priority, "4" for DEBUG and higher priority.
#    ---
#    verbose_mode: "3"
```

**Comment by jmazzitelli** [comment]
FWIW, this "log_level" is the standard Go log API - Kiali doesn't determine to use 3,4,etc versus "debug" or "info" - its just how the standard Go library works. The help text also comes from the standard Go library.
