### ISSUE TITLE
Upgrades intermittently fail due to race condition of namespace termination

### ISSUE THREAD

**Issue by majelbstoat** [kiali/kiali#1173]
**Describe the bug**

Running `bash <(curl -L https://git.io/getLatestKialiOperator)` on a cluster that has kiali installed often fails when choosing to uninstall the previous version.

Removal of the kiali-operator namespace is not immediate, and installation of the new version often fails with:

`Error from server (Forbidden): error when creating "STDIN": serviceaccounts "kiali-operator" is forbidden: unable to create new content in namespace kiali-operator because it is being terminated
ERROR: Failed to deploy Kiali operator. Aborting.`

**Versions used**
Kiali: e.g. 0.20 -> 0.21

**To Reproduce**
Run the installation twice, and choose to uninstall the existing installation the second time.

**Expected behavior**
The installer waits for the removal of the kiali-operator namespace before proceeding,

**Comment by jmazzitelli** [comment]
I wonder if this is related to https://github.com/operator-framework/operator-sdk/issues/1493

@majelbstoat What version of Kubernetes or OpenShift are you using?

**Comment by jmazzitelli** [comment]
I just ran the `bash` command three times in a row with no errors. The code that removes the namespace is here: https://github.com/kiali/kiali/blob/master/operator/deploy/deploy-kiali-operator.sh#L536-L543

```
  # Clean up the operator namespace entirely but only if there are no pods running in it.
  # This avoids removing a namespace in use for other things.
  local _pod_count=$(${CLIENT_EXE} get pods --no-headers -n ${OPERATOR_NAMESPACE} 2>/dev/null | wc -l)
  if [ "${_pod_count}" -eq "0" ]; then
    ${CLIENT_EXE} delete --ignore-not-found=true namespace "${OPERATOR_NAMESPACE}"
  else
    echo "There appears to be pods running in the operator namespace [${OPERATOR_NAMESPACE}]; namespace will not be deleted."
  fi
```

The deletion of the namespace should always block and never return until it is gone - AFAIK, that's the Kubernetes behavior.

Did you happen to see that message in your output about things still in the namespace?
```
    echo "There appears to be pods running in the operator namespace [${OPERATOR_NAMESPACE}]; namespace will not be deleted."
```

**Comment by majelbstoat** [comment]
This is on `GKE 1.13.6-gke.6`. Here's the full output of the failed run trying to move from 0.20 to 0.21. (Happened three times in a row, identically.)

```
=== UNINSTALL SETTINGS ===
UNINSTALL_EXISTING_KIALI=
UNINSTALL_EXISTING_OPERATOR=
UNINSTALL_MODE=
=== UNINSTALL SETTINGS ===
envsubst is here: /usr/local/bin/envsubst
Using downloader: curl -s
Will use the last Kiali operator release: v0.21.0
Will use the last Kiali operator release: v0.21.0
=== OPERATOR SETTINGS ===
OPERATOR_IMAGE_NAME=quay.io/kiali/kiali-operator
OPERATOR_IMAGE_PULL_POLICY=IfNotPresent
OPERATOR_IMAGE_VERSION=v0.21.0
OPERATOR_INSTALL_KIALI=true
OPERATOR_NAMESPACE=kiali-operator
OPERATOR_SKIP_WAIT=false
OPERATOR_VERSION_LABEL=v0.21.0
OPERATOR_WATCH_NAMESPACE=kiali-operator
OPERATOR_ROLE_CLUSTERROLES=# The operator does not have permission to manage cluster roles
OPERATOR_ROLE_CLUSTERROLEBINDINGS=# The operator does not have permission to manage cluster role bindings
=== OPERATOR SETTINGS ===
It appears Kiali has already been installed. Do you want to uninstall it? [Y/n]:
The existing Kiali will be uninstalled.
Deploying Kiali operator to namespace [kiali-operator]
Applying yaml from URL via: [curl -s https://raw.githubusercontent.com/kiali/kiali/v0.21.0/operator/deploy/namespace.yaml] to namespace [kiali-operator]
namespace "kiali-operator" configured
Applying yaml from URL via: [curl -s https://raw.githubusercontent.com/kiali/kiali/v0.21.0/operator/deploy/crd.yaml] to namespace [kiali-operator]
customresourcedefinition.apiextensions.k8s.io "monitoringdashboards.monitoring.kiali.io" created
customresourcedefinition.apiextensions.k8s.io "kialis.kiali.io" configured
Applying yaml from URL via: [curl -s https://raw.githubusercontent.com/kiali/kiali/v0.21.0/operator/deploy/service_account.yaml] to namespace [kiali-operator]
Error from server (Forbidden): error when creating "STDIN": serviceaccounts "kiali-operator" is forbidden: unable to create new content in namespace kiali-operator because it is being terminated
ERROR: Failed to deploy Kiali operator. Aborting.
```

Eventually, I ran with `--uninstall-mode true` to nuke everything. Since then, I've had it be successful three times in a row, reinstalling 0.21 over 0.21. Possibly some weird partial cleanup somewhere? Or maybe just a ghost in the machine :)

**Comment by majelbstoat** [comment]
Actually, it looks like no deletion took place, jumping straight to `Deploying Kiali operator to namespace [kiali-operator]`. Haven't looked at the script, but perhaps some previous run deleted some of the resources, and there aren't sufficient checks to trigger all the deletion necessary?
