### ISSUE TITLE
generic OAuth2 authentication strategy

### ISSUE THREAD

**Issue by a-thaler** [kiali/kiali#1175]
**Motivation**
In [Kyma](kyma-project.io) we are using istio and want to have an out-of-the-box integration of Kiali available too for a better debuggability (we will update to latest Kiali soon).
All authentication in Kyma, especially of the 3party tools like grafana and jaeger, is done via OAuth2 Authorization Grant using [Dex](https://github.com/dexidp/dex) as pluggable OAuth2 Provider. Dex allows to use different IDPs dependent on where Kyma is running.
We like to have the authentication with Kiali also running via OAuth2 against Dex.

**Details**
Kiali seems to support OAuth already as [authentication strategy](https://github.com/kiali/kiali/blob/master/operator/deploy/kiali/kiali_cr.yaml), but it seems it is [specific to openshift](https://github.com/kiali/kiali/blob/master/business/openshift_oauth.go) only. It will be great to have a generic support available, allowing to configure all URLs in a flexible way. See also [Grafanas OAuth2 support ](https://grafana.com/docs/auth/generic-oauth) for an example.

**Background**
This ticket is a follow up on this [twitter thread](https://twitter.com/KialiProject/status/1141737654700183553)

**Comment by pilhuhn** [comment]
@a-thaler Thanks for doing the write-up. 
#1071 also talks about using dex. And then there is #1053 , which is a bit related to.

**Comment by a-thaler** [comment]
@pilhuhn sorry, I have not seen the issues ...
Indeed #1071 will fix our problem, so feel free to close this one as a duplicate

**Comment by lucasponce** [comment]
Closing due duplicate with https://github.com/kiali/kiali/issues/1071
