### ISSUE TITLE
App mesh connections are not showing for all services

### ISSUE THREAD

**Issue by karkrish** [kiali/kiali#1188]
Hi Team,

We deployed kiali with istio in our EKS cluster. We are able to see the service mesh in kiali board. But its not showing all connections to the services. Many services are showing as separate containers. Here are the tools versions we are using.
EKS - 1.12
kiali-ui 0.16.0 (c2ce0549f3123889254bb303c49d783f16278d73)
kiali v0.16.2 (dd6d04bd486ef1d56d0567f7cd8adcee31196867)
Istio : 1.17

![image](https://user-images.githubusercontent.com/22123955/60132184-030c2a80-9769-11e9-8289-9963712f7cdd.png)

Connections to all other containers (the once without sidecar containers) are missing.

**Comment by jshaughn** [comment]
Although I don't think it's the problem you are using a fairly old version of Kiali with Istio 1.1.7 (not 1.17, right?)

As you mentioned, 3 of those services in the picture don't have sidecars (Istio proxies) and therefore can not generate telemetry.  Without telemetry Kiali can not show traffic because Kiali renders the graph based on traffic reported by istio (mixer) and stored into Prometheus.  Even the nodes with traffic are not showing any for the 1m interval in the screen shot, as noted by the grey edges.

Make sure you have sidecars injected in the services for which you want to see telemetry and then we can go from there.  Also, consider updating the Kiali version (see kiali.io Getting Started for install/update docs)

**Comment by karkrish** [comment]
Thanks for the update Jay.

Sorry for the typo error. We are using istio 1.1.7

The containers without the sidecar are not part of our application traffic flow. I think we should be good on that. Also, looking at the graph for "istio-system" namespace, we see all containers are connected with telemetry. We are not sure else is missing in the configurations. Can you provide your thoughts on this?

![image](https://user-images.githubusercontent.com/22123955/60133697-db6a9180-976b-11e9-8a56-c0ad1b87971d.png)

**Comment by jshaughn** [comment]
Connected to istio-telemetry does not necessarily mean that traffic telemetry is being generated.  Kiali generally represents what is found in Prometheus in the istio_requests_totals metric (for http, for tcp it's different).  It's almost a sure thing that the expected telemetry is not going to be found in Prometheus.  You can expose the prometheus service in istio-system and use the ui to inspect the metric directly.

As for why the data is not there I'm not sure.  Where is the traffic coming from?  Is it routed through an ingress gateway?   Is any of the missing traffic for requests being routed outside of the mesh?

**Comment by pilhuhn** [comment]
The original screenshot seems to not have any traffic on the agora-identitiy service, which leads me to the question if your services did get any traffic at all when you were creating the screenshot.

**Comment by karkrish** [comment]
Hi Jay/Heiko,

We did an end to end analysis with ptometheus logs. 
We found that, service shown in screenshot 1 is connected through kubernetes native services. All other services are connected with a load balancer and the traffic is directly to the container (even though it has the side car container). We suspect this could be the reason why the connections are displayed in graph. 
We are working in changing the traffic flow pattern. We will test it out and keep you posted. 

Do you have any other recommendations on this?

**Comment by jshaughn** [comment]
Only that requests must flow through the proxies to generate telemetry, and it seems as if that is not happening for all of the requests.

**Comment by lucasponce** [comment]
@karkrish any update on this Issue from your side ?

**Comment by karkrish** [comment]
Hi lucsaponce, We got the service graph working now. The root cause is, we had traffic routing on both load balancer and kubernetes internal services. After blocking the load balancer traffic, we see the service graph as expected.

**Comment by jshaughn** [comment]
@karkrish Thanks for the update, glad to hear you are now seeing the expected telemetry.
