### ISSUE TITLE
Traffic graph and Response Codes didn't match

### ISSUE THREAD

**Issue by sniperking1234** [kiali/kiali#1196]
**Describe the bug**
![no3xx](https://user-images.githubusercontent.com/7834655/60226055-1da2e880-98bc-11e9-98c2-dfc3ebb86484.png)
![no3xx2](https://user-images.githubusercontent.com/7834655/60226058-1f6cac00-98bc-11e9-95cb-072dfe2bfd04.png)
duration=21600s
And the percentage also seems incorrect

**Versions used**
Kiali: 0.21.0
Istio: 1.1.2

**Comment by pilhuhn** [comment]
Thanks for reporting this. Do you have a way, we can easily reproduce this? E.g. some specific VS/DR for bookinfo?

**Comment by lucasponce** [comment]
cc @israel-hdez

**Comment by sniperking1234** [comment]
@pilhuhn I think this is a problem of float precision when the traffic rates is very small.

**Comment by jshaughn** [comment]
Yes, when dealing with very low request rates the rate can get rounded to 0 as we do use a precision of 2 .  The response percentages have a precision of 1 but the numbers are relative to each other and only suffer a 0 if the slice is tiny.  I don't think there is much we can do here, luckily there is some detail to be found in the Responses.  We are likely going to introduce a FAQ for the graph, this would make a good entry.

**Comment by israel-hdez** [comment]
Ok, looking at the first image, I understand that the %success = 66% of the traffic tab is not close to the 72% of the 200 code of the Response codes tab, which is misleading.

What I see weird is that even when numbers in both tabs are being calculated from the same queries, numbers don't add up to a close value. So, yes, the floating point precision is causing quite bad results in this case.

I think it will be hard to make numbers in both tabs to match. But if the current deviation is a concern, I think there are ways to reduce the precision error to, at least, get numbers that are closer. Although, I'm not sure how much we can improve it.

**Comment by sniperking1234** [comment]
I tried to fix this problem @jshaughn @israel-hdez

**Comment by jshaughn** [comment]
Did this proposed code change solve your problem?  Do you have an "after" screenshot with this change applied?

**Comment by sniperking1234** [comment]
@josejulio I think the change can solve it.
![image](https://user-images.githubusercontent.com/7834655/60406430-5f979b80-9be8-11e9-98dc-ba486793261f.png)
![image](https://user-images.githubusercontent.com/7834655/60406438-6b835d80-9be8-11e9-867d-0f9314e858a7.png)
![image](https://user-images.githubusercontent.com/7834655/60406404-3c6cec00-9be8-11e9-85c8-e87ea6fc1070.png)

**Comment by jshaughn** [comment]
@sniperking1234 Your PR has been merged, thanks!  Please close this if you are satisfied.
