### ISSUE TITLE
[Documentation]: Namespace label selector

### ISSUE THREAD

**Issue by johscheuer** [kiali/kiali#1214]
Currently Kiali supports simple namespace management (https://www.kiali.io/documentation/getting-started/#_namespace_management) to include or exclude namespaces. It would be nice if Kiali would also support namespace label selectors in order to define which namespaces are accessible/excluded (the label selector could be used for both). Form my point of view both options should be "anded" e.g. the label selector must match (if given) and the `accessible_namespaces` pattern must match.

If you have an questions feel free to ask.

Thanks!

**Comment by pilhuhn** [comment]
Thanks for your suggestion, this sounds like a good idea.
Would you be able to help getting that into Kiali?

**Comment by johscheuer** [comment]
I just saw that this feature is already implement but not documented (at least I couldn't find some documentation).

Config code: https://github.com/kiali/kiali/blob/master/config/config.go#L79
Usage: https://github.com/kiali/kiali/blob/master/business/namespaces.go#L43

Thanks for your quick response. I will close this issue.

This option should probably be documented here: https://www.kiali.io/documentation/getting-started/#_namespace_management

**Comment by lucasponce** [comment]
Thanks @johscheuer.

If it's not document, it's still a valid bug so I will reopen the Issue.

**Comment by pilhuhn** [comment]
@johscheuer The documentation lives at https://github.com/kiali/kiali.io/tree/master/content/documentation/getting-started - could you perhaps submit a PR against it?

**Comment by johscheuer** [comment]
I can open a PR during the day.

**Comment by jmazzitelli** [comment]
Kiali Operator CR has this specific setting documented here:

https://github.com/kiali/kiali/blob/v1.0.0/operator/deploy/kiali/kiali_cr.yaml#L44-L53

We should make it more explicit in our getting started docs that users can refer to that kiali_cr.yaml for documentation on all available settings that you can configure in Kiali.
