### ISSUE TITLE
Kiali install failed

### ISSUE THREAD

**Issue by sniperking1234** [kiali/kiali#1217]
@jmazzitelli Kiali made errors in installation. Kiali operater looks like something's wrong and stuck in a loop. Ansible container has a lot of logs and If you want to see, I can paste it out. But there's no error in ansible logs and had errors in operator logs. 
This is a snippet of the operator logs .
Kubernetes vserion: 1.11.1
> {"level":"error","ts":1562244488.9314835,"logger":"kubebuilder.controller","msg":"Reconciler error","controller":"kiali-controller","request":"kiali-operator/kiali","error":"did not receive playbook_on_stats event","stacktrace":"github.com/operator-framework/operator-sdk/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\tsrc/github.com/operator-framework/operator-sdk/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/operator-framework/operator-sdk/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsrc/github.com/operator-framework/operator-sdk/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:217\ngithub.com/operator-framework/operator-sdk/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\tsrc/github.com/operator-framework/operator-sdk/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\ngithub.com/operator-framework/operator-sdk/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\tsrc/github.com/operator-framework/operator-sdk/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/operator-framework/operator-sdk/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tsrc/github.com/operator-framework/operator-sdk/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/operator-framework/operator-sdk/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\tsrc/github.com/operator-framework/operator-sdk/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}

**Update process：**
> bash <(curl -L https://git.io/getLatestKialiOperator)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:06 --:--:--     0
  4 43905    4  1921    0     0    146      0  0:05:00  0:00:13  0:04:47   412Using 'kubectl' located here: /usr/local/bin/kubectl
=== UNINSTALL SETTINGS ===
UNINSTALL_EXISTING_KIALI=
UNINSTALL_EXISTING_OPERATOR=
UNINSTALL_MODE=
=== UNINSTALL SETTINGS ===
envsubst is here: /usr/bin/envsubst
Using downloader: wget -q -O -
100 43905  100 43905    0     0   3173      0  0:00:13  0:00:13 --:--:-- 10069
Will use the last Kiali operator release: v1.1.0
Will use the last Kiali operator release: v1.1.0
=== OPERATOR SETTINGS ===
OPERATOR_IMAGE_NAME=quay.io/kiali/kiali-operator
OPERATOR_IMAGE_PULL_POLICY=IfNotPresent
OPERATOR_IMAGE_VERSION=v1.1.0
OPERATOR_INSTALL_KIALI=true
OPERATOR_NAMESPACE=kiali-operator
OPERATOR_SKIP_WAIT=false
OPERATOR_VERSION_LABEL=v1.1.0
OPERATOR_WATCH_NAMESPACE=kiali-operator
OPERATOR_ROLE_CLUSTERROLES=# The operator does not have permission to manage cluster roles
OPERATOR_ROLE_CLUSTERROLEBINDINGS=# The operator does not have permission to manage cluster role bindings
=== OPERATOR SETTINGS ===
It appears the operator has already been installed. Do you want to uninstall it? This will uninstall Kiali, too. [Y/n]: y
The existing operator will be uninstalled, along with any existing Kiali installation.
Deleting resources for any existing Kiali operator installation
customresourcedefinition.apiextensions.k8s.io "monitoringdashboards.monitoring.kiali.io" deleted
Deleting Kiali CR [kiali] in namespace [kiali-operator]
kiali.kiali.io/kiali patched
kiali.kiali.io "kiali" deleted
customresourcedefinition.apiextensions.k8s.io "kialis.kiali.io" deleted
pod "kiali-operator-5f7b8b6d74-269wr" deleted
deployment.apps "kiali-operator" deleted
replicaset.apps "kiali-operator-5f7b8b6d74" deleted
serviceaccount "kiali-operator" deleted
clusterrole.rbac.authorization.k8s.io "kiali-operator" deleted
clusterrolebinding.rbac.authorization.k8s.io "kiali-operator" deleted
namespace "kiali-operator" deleted
Deploying Kiali operator to namespace [kiali-operator]
Applying yaml from URL via: [wget -q -O - https://raw.githubusercontent.com/kiali/kiali/v1.1.0/operator/deploy/namespace.yaml] to namespace [kiali-operator]
namespace/kiali-operator created
Applying yaml from URL via: [wget -q -O - https://raw.githubusercontent.com/kiali/kiali/v1.1.0/operator/deploy/crd.yaml] to namespace [kiali-operator]
customresourcedefinition.apiextensions.k8s.io/monitoringdashboards.monitoring.kiali.io created
customresourcedefinition.apiextensions.k8s.io/kialis.kiali.io created
Applying yaml from URL via: [wget -q -O - https://raw.githubusercontent.com/kiali/kiali/v1.1.0/operator/deploy/service_account.yaml] to namespace [kiali-operator]
serviceaccount/kiali-operator created
Applying yaml from URL via: [wget -q -O - https://raw.githubusercontent.com/kiali/kiali/v1.1.0/operator/deploy/role.yaml] to namespace [kiali-operator]
clusterrole.rbac.authorization.k8s.io/kiali-operator created
Applying yaml from URL via: [wget -q -O - https://raw.githubusercontent.com/kiali/kiali/v1.1.0/operator/deploy/role_binding.yaml] to namespace [kiali-operator]
clusterrolebinding.rbac.authorization.k8s.io/kiali-operator created
Applying yaml from URL via: [wget -q -O - https://raw.githubusercontent.com/kiali/kiali/v1.1.0/operator/deploy/operator.yaml] to namespace [kiali-operator]
deployment.apps/kiali-operator created
Waiting for the operator to start..
The Kiali operator is installed!
Kiali will now be installed.
Choose a login strategy of either 'login' or 'anonymous'. Use 'anonymous' at your own risk. [login]: login
=== KIALI SETTINGS ===
ACCESSIBLE_NAMESPACES=
AUTH_STRATEGY=login
CREDENTIALS_CREATE_SECRET=false
GRAFANA_URL=
KIALI_CR=
KIALI_IMAGE_NAME=
KIALI_IMAGE_PULL_POLICY=
KIALI_IMAGE_VERSION=v1.1.0
ISTIO_NAMESPACE=
JAEGER_URL=
NAMESPACE=istio-system
SECRET_NAME=kiali
_SECRET_EXISTS=true
=== KIALI SETTINGS ===
Deleting resources for any existing Kiali installation
No resources found
error: the server doesn't have a resource type "routes"
error: the server doesn't have a resource type "oauthclients"
NOTE! A secret already exists. To log into Kiali, you must use the credentials found in that secret.
Deploying Kiali CR to namespace [kiali-operator]
kiali.kiali.io/kiali created
Done.

**Kiali CR:**
```
apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"kiali.io/v1alpha1","kind":"Kiali","metadata":{"annotations":{},"name":"kiali","namespace":"kiali-operator"},"spec":{"auth":{"strategy":"login"},"deployment":{"image_version":"v1.1.0","namespace":"istio-system","secret_name":"kiali"},"external_services":{"grafana":{"url":""},"jaeger":{"url":""}}}}
  creationTimestamp: 2019-07-04T12:22:12Z
  finalizers:
  - finalizer.kiali
  generation: 1
  name: kiali
  namespace: kiali-operator
  resourceVersion: "441673309"
  selfLink: /apis/kiali.io/v1alpha1/namespaces/kiali-operator/kialis/kiali
  uid: 59e7228d-9e56-11e9-bf4a-6c92bf7360cc
spec:
  auth:
    strategy: login
  deployment:
    image_version: v1.1.0
    namespace: istio-system
    secret_name: kiali
  external_services:
    grafana:
      url: ""
    jaeger:
      url: ""
status:
  conditions:
  - lastTransitionTime: 2019-07-04T12:22:12Z
    message: Running reconciliation
    reason: Running
    status: "True"
    type: Running
```

**Comment by jmazzitelli** [comment]
> operater looks like something's wrong and stuck in a loop.
> ...
> "error":"did not receive playbook_on_stats event"

This sounds like: https://github.com/operator-framework/operator-sdk/issues/729

I have never seen this happen, but I'm on a supported version of Kubernetes....

> Kubernetes vserion: 1.11.1

As per [Operator SDK requirements documented here](https://github.com/operator-framework/operator-sdk), your version of Kubernetes is not supported - Kubernetes operators are only supported on at least Kubernetes v1.11.3 or higher. I suspect this might be the cause of the issue, but I am not sure.

Have you seen this odd error/loop when using a supported version of Kubernetes?

**Comment by sniperking1234** [comment]
@jmazzitelli I have the same problem in Kubernetes vserion 1.12.1

**Comment by jmazzitelli** [comment]
@sniperking1234 can you provide some more clear replication procedures? For example, I assume you already have the Kiali Operator and Kiali installed (is that true?) What was the commands you used to originally install Kiali Operator (and what did the Kiali CR look like)? I assume you are using the defaults for things like where you installed Kiali operator (namespace: kiali-operator) and where Kiali is installed (istio-system) and where the Kiali CR is created (in the namespace "kiali-operator" ??).

Because we have not seen this before, we would need a specific set of instructions to help replicate this - so I think we will need to know how you originally installed the initial Kiali Operator to then debug this problem when upgrading.

**Comment by sniperking1234** [comment]
@jmazzitelli I used command `bash <(curl -L https://git.io/getLatestKialiOperator)` to update kiali in both environments.
In kubernetes1.12.1 version environment. Kiali was installed with Istio and version 0.14. Kiali operator is not installed in this environment.
In kubernetes1.11.1 version environment. I used `bash <(curl -L https://git.io/getLatestKialiOperator)` to install Kiali originally and succeed. 
The kiali and kiali-operator version was 0.21.0. Kiali operator installed in namespace "kiali-operator". Kiali is installed in namespace "istio-system".  Kiali CR is created in namespace "kiali-operator". But the original Kiali CR was deleted, I didn't know what's in it.
 I used the same command  `bash <(curl -L https://git.io/getLatestKialiOperator)` to update kiali yesterday but there was a mistake.

**Comment by sniperking1234** [comment]
This link may be helpful
https://github.com/operator-framework/operator-sdk/blob/master/doc/user-guide.md#reconcile-loop

**Comment by jmazzitelli** [comment]
> This link may be helpful
> https://github.com/operator-framework/operator-sdk/blob/master/doc/user-guide.md#reconcile-loop

That document is only relevant for operators implemented in Go, which the Kiali Operator is not. It is an ansible operator, and the ansible operator SDK should handle all of this.

**Comment by jmazzitelli** [comment]
@gbaufake have you seen anything like this in your testing? Might be something we need to add to the set of QE tests

**Comment by israel-hdez** [comment]
@sniperking1234 is this still an issue with the latest version of the operator?

**Comment by sniperking1234** [comment]
@israel-hdez Yes, operator still has problems

**Comment by lucasponce** [comment]
@jmazzitelli any update on this ?

**Comment by jmazzitelli** [comment]
no updates.. haven't seen this.

**Comment by jshaughn** [comment]
@sniperking1234 is this still an issue for you?

**Comment by jshaughn** [comment]
Closing as stale, please open a new issue as needed, thanks!
