### ISSUE TITLE
Unauthorized. Error in username or password

### ISSUE THREAD

**Issue by IamGabrielWu** [kiali/kiali#1218]
I have created a secret in my kubernetes cluster and i can see kiali pod is and running . The kiali was installed along with istio.
I check the deployment of kiali.
![image](https://user-images.githubusercontent.com/11718739/60702554-cfcc5700-9f31-11e9-8fbf-1ff8a533249d.png)
Get the path then i check username and password in pod. I can see username and password are successfully mounted.
![image](https://user-images.githubusercontent.com/11718739/60702637-0bffb780-9f32-11e9-92fe-98911ecf8b05.png)

But when i tried to login kiali console, i got access denied "Unauthorized. Error in username or password"
![image](https://user-images.githubusercontent.com/11718739/60702689-30f42a80-9f32-11e9-86aa-0c6dd22858c2.png)
I don't know what's the problem. There's no log or error output from kiali pod. 

And also another question, is there a default username and password for newly setup kiali ?

**Comment by lucasponce** [comment]
@IamGabrielWu thanks for opening the issue.
For the screenshot I think you are using Kiali 0.16 ? Based on Istio 1.1.x ? Or are you using a different version.

About the problem, did you try to re-start the Kiali Pod after changing the secret ?

These instructions [1] should be valid for Kiali 0.16, but note that newer versions of Kiali have been moved to use an operator for this process.

If you want to upgrade you can also take a look to [2].

[1] https://istio.io/docs/tasks/telemetry/kiali/
[2] https://www.kiali.io/documentation/getting-started/#_upgrade_the_istio_or_maistra_version_of_kiali

**Comment by IamGabrielWu** [comment]
Yes it's Kiali 0.16
![image](https://user-images.githubusercontent.com/11718739/60706797-d6140080-9f3c-11e9-9f25-a220fd78345e.png)
I killed a pod then retried login, still got the same error @lucasponce

**Comment by IamGabrielWu** [comment]
@lucasponce do i have to upgrade kiali to fix the issue ? and i don't see the documentation on how to upgrade kiali when kiali is installed in kubernetes as pod, not in a virtual host.

**Comment by pilhuhn** [comment]
@IamGabrielWu Did you base64 encode the password? See e.g. https://kubernetes.io/docs/concepts/configuration/secret/#creating-a-secret-manually

**Comment by IamGabrielWu** [comment]
@pilhuhn yes. i think it's created correctly and mounted correctly. You see 
![image](https://user-images.githubusercontent.com/11718739/60707772-0fe60680-9f3f-11e9-8c61-bcd60e1fb7d8.png)
This is my username and it's mounted and showing correctly.

**Comment by pilhuhn** [comment]
This looks different for me:

    $ echo -n "cicdapi_kiali" | base64
    Y2ljZGFwaV9raWFsaQ==

But I probably misunderstood you.

**Comment by lucasponce** [comment]
> @lucasponce do i have to upgrade kiali to fix the issue ?

No, it shouldn't.

Probably @pilhuhn comment is right.

What kubernetes environment do you use ? To try to reproduce this in a Kiali 0.16.

**Comment by lucasponce** [comment]
@IamGabrielWu 

I confirm @pilhuhn comment.
I had a kiali 0.16 deployed, default user/password should be "admin/admin".

After installation was finished I've modified the kiali secret with base64 encoded (hint: check if no \n or spaces included).

Then I scaled down/up kiali and I can see the user/password updated.

Note that *both* values username and password should be in base64.

**Comment by jmazzitelli** [comment]
Can you post the kiali logs so we can see if it found the secret? Your log image cut it off.

**Comment by IamGabrielWu** [comment]
@lucasponce @pilhuhn thanks a million.
I found out the reason i messed up with the secret. 
i used echo <my secret> | base64 , what i should use is echo -n <my secret> | base64.  Now i saw the difference. Thanks a lot.

**Comment by pilhuhn** [comment]
@IamGabrielWu Glad it works now.
