### ISSUE TITLE
Cannot access Kiali UI on GKE via Ingreess or port-forward.

### ISSUE THREAD

**Issue by Rukeith** [kiali/kiali#1226]
**Describe the bug**
I use Kiali Operator to install Kiali on GKE.
After run script 

`bash <(curl -L https://git.io/getLatestKialiOperator)`

I run this and open browser

`kubectl port-forward svc/kiali 20001:20001 -n istio-system`

I got this page.

![螢幕快照 2019-07-09 15 53 18](https://user-images.githubusercontent.com/7069605/60870131-d248ec80-a262-11e9-949e-9a36b9db1fe8.png)

Then I saw the ingress cannot be create 
![螢幕快照 2019-07-09 15 57 14](https://user-images.githubusercontent.com/7069605/60870122-ce1ccf00-a262-11e9-95a0-1489d3d3475c.png)

Pod and service are created and status is OK.

**Versions used**
Kiali: v1.1.0
Istio:
Kubernetes flavour and version: GKE 1.13.7-gke.8

**To Reproduce**
1. Run `bash <(curl -L https://git.io/getLatestKialiOperator)`
2. Run `kubectl port-forward svc/kiali 20001:20001 -n istio-system`
3. Open browser and tab `https://localhost:20001/kiali`

**Expected behavior**
I should see the kiali uI

**Comment by israel-hdez** [comment]
Hi, @Rukeith 

By following your steps in minikube, I get a good setup.
If you are using port-forwarding to access Kiali, the Ingress error may not be relevant.

I never have used GKE, but It's weird for me that you are seeing the nginx error. This means that you are reaching the ingress controller, but when using port-forwarding that shouldn't happen.

Anyway, can you please run the following command?:

`kubectl get all,configmaps,serviceaccounts,roles,clusterroles -n istio-system -l app=kiali`

If Kiali is properly installed, you should see a similar output to this:

```
NAME                        READY   STATUS    RESTARTS   AGE
pod/kiali-f94ffbd5d-z6j2w   1/1     Running   0          13m

NAME            TYPE       CLUSTER-IP       EXTERNAL-IP   PORT(S)           AGE
service/kiali   NodePort   10.103.183.142   <none>        20001:32012/TCP   13m

NAME                    READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/kiali   1/1     1            1           13m

NAME                              DESIRED   CURRENT   READY   AGE
replicaset.apps/kiali-f94ffbd5d   1         1         1       13m

NAME              DATA   AGE
configmap/kiali   1      13m

NAME                                   SECRETS   AGE
serviceaccount/kiali-service-account   1         13m

NAME                                          AGE
role.rbac.authorization.k8s.io/kiali          13m
role.rbac.authorization.k8s.io/kiali-viewer   13m
```

If your output is different, please paste yours start diagnosing your issue.

**Comment by lucasponce** [comment]
@Rukeith 
I confirm that this command

```
kubectl port-forward svc/kiali 20001:20001 -n istio-system
```

didn't work for me in GKE as well.

But I tried to workaround it using the pod:

```
kubectl port-forward kiali-559db54868-t2qhq 20001:20001 -n istio-system

```

This worked for me.

Also, for exposing the addons, we recommend to do it using the ingress as described in the telemetry doc:

https://istio.io/docs/tasks/telemetry/gateways/

Let us know if that helps.

**Comment by israel-hdez** [comment]
Closing as stale.
