### ISSUE TITLE
Pod health

### ISSUE THREAD

**Issue by alexanderbuhler** [kiali/kiali#1233]
**Describe the bug**
Maybe some recognition issue here. Kiali is showing me "Health: Failure – Pods Status: 0/2", without further explanation as it seems. Pods are perfectly healthy from k8s side (probing). It's a simple node app running on port 80.

Might be related to #643 . Unfortunately there was no more info provided there. 
With this issue, only one single deployment is affected. There are similar node app deployments here with exact same k8s healthchecks defined which are displayed as healthy.

**Versions used**
Kiali: 0.20.0
Istio: 1.2.2
Kubernetes flavour and version: 1.13.7

**Expected behavior**
Pods are seen as healthy according to k8s healthchecks.

Any ideas on why this might be happening or where to get more info on why kiali sees them as unhealthy?

**Comment by israel-hdez** [comment]
Hi @alexanderbuhler 
Thanks for reporting the issue.

It wil be very helpful if you can provide the screenshot of the workload page that involves the pod with the issue. I'm talking about this page:

![image](https://user-images.githubusercontent.com/23639005/60994203-acc8eb00-a315-11e9-838a-0ec31b614946.png)

Also, please provide the output of `kubectl describe pod {yourpod}`. Feel free to censure any sensitive data.

**Comment by lucasponce** [comment]
@alexanderbuhler can you test with a newer version ?
I remember we updated the pod status health in case of failures with more details.

As @israel-hdez comments, a screenshot would help us to understand the context.

**Comment by alexanderbuhler** [comment]
Whatever happened in the background, it is now displayed as healthy. I didn't change anything.
Just going to close this for now.

Thanks anyways! :-)
