### ISSUE TITLE
Add a link to documentation to UI

### ISSUE THREAD

**Issue by pilhuhn** [kiali/kiali#1243]
Add a link to the documentation on kiali.io to the about page. 
The link needs to be customisable.
The link should have a query-parameter `utm_source=kiali-app`
The link should have a `utm_content`query-parameter that shows the version of Kiali.

E.g. `<a href="https://www.kiali.io/documentation?utm_source=kiali-app&utm_content=v0.20.1">Documentation</a>`

Apparently one also needs to set `utm_campaign` and `utm_medium` (see https://support.google.com/analytics/answer/1033863 ) so we could also use the kiali-version in `utm_campaign`

**Comment by josejulio** [comment]
How about?
```
utm_source=kiali
utm_medium=app
utm_campaign=v0.20.1
utm_content=about-page
```

**Comment by pilhuhn** [comment]
Sounds good to me. The content could be different I guess, as this should be a separate entry under (?) and not only visible on the about page.
For downstream we can skip the `utm_*` stuff

**Comment by josejulio** [comment]
> Sounds good to me. The content could be different I guess, as this should be a separate entry under (?) and not only visible on the about page.

Right, will use "?-menu"

> For downstream we can skip the `utm_*` stuff

Sounds good

**Comment by pilhuhn** [comment]
This is now https://issues.jboss.org/browse/KIALI-3132
