### ISSUE TITLE
Kiali pod fails to start

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#1262]
**Describe the bug**
Kiali pods fails to start with error:
Error: container create failed: container_linux.go:336: starting container process caused "exec: \"/opt/kiali/kiali\": stat /opt/kiali/kiali: no such file or directory" 

**Versions used**
Kiali: latest master
Istio: TP12
OCP 4.1

**To Reproduce**
Install Kiali via operator.
Pod does not start.
Error is shown in events.

**Comment by gbaufake** [comment]
Same behavior of ->
https://issues.jboss.org/browse/KIALI-1529

**Comment by gbaufake** [comment]
@hhovsepy 
I think we can close this issue
