### ISSUE TITLE
[Troubleshooting] Show triggered alerts defined on a given workload

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#1270]
Assuming the user has already defined some alerts using Prometheus alert manager, and assuming they are labelled consistently to match mesh entities (app label, version label), we should be able to fetch triggered alerts at a given time.

This information could enrich the existing views we have in Kiali:
- Items health
- Metrics charts (e.g. as annotations on chart)
- Overview page (number of active alerts per namespace)

You can upvote/downvote/comment this feature request.

**Comment by jshaughn** [comment]
Closing this as it is superseded by https://github.com/kiali/kiali/issues/1416.  In short the idea of integrating alerts or other relevant signals/events is still on the table for Kiali, as it would enhance a correlated presentation of information.
