### ISSUE TITLE
Github rate-limiting when running installation script

### ISSUE THREAD

**Issue by eyeezzi** [kiali/kiali#1271]
**Is your feature request related to a problem? Please describe.**
Kiali installation sometimes fails because of hitting Github rate limit when running the shell command
`bash <(curl -L https://git.io/getLatestKialiOperator)`. In my case, the error results from downloading this file `https://api.github.com/repos/kiali/kiali/releases/latest`

**Describe the solution you'd like**
Because authenticated requests have a much higher rate limit, add an optional environment variable `GITHUB_PERSONAL_ACCESS_TOKEN` which will be used as the Authorization header for all Github requests made from the script.

**Describe alternatives you've considered**
I just wait for an indeterminate period of time before trying again.

**Additional context**
Add any other context or screenshots about the feature request here. If it is about a new design, please attach a drawing of a potential solution.
For backend changes also describe how one could test the new feature and how it impacts display on the UI.

**Comment by abonas** [comment]
@jmazzitelli is there any alternative? there is the operator hub, no?

**Comment by eyeezzi** [comment]
@abonas did not know such a thing existed. Will try it later today and reply back.

**Comment by gbaufake** [comment]
@eyeezzi  you can use the ``bash <(curl -L https://git.io/getLatestKialiOperator--dry-run example.yaml.`` and reuse the yaml

**Comment by eyeezzi** [comment]
@gbaufake Your command also can (and does) hit the rate limit too.

**Comment by jmazzitelli** [comment]
Workaround - specify the version directly to avoid having the script go to github to find out what version to use. For example:

`bash <(curl -L https://git.io/getLatestKialiOperator) -oiv v1.2.0 -kiv v1.2.0`

This issue has some merit though - we'll leave it open in case someone wants to implement this enhancement request.

**Comment by eyeezzi** [comment]
@abonas, your suggestion to install using [Operator Hub](https://operatorhub.io/operator/kiali) is undesirable because it introduces yet-another management layer AND it deviates from the [official documentation](https://www.kiali.io/documentation/getting-started/#_advanced_install_operator_only). 

Let me explain: it requires installing an _Operator Lifecycle Manager_ which is an operator that manages the Kiali Operator which then manages Kiali...Oh God! Secondly, this will install the Kiali Operator to some weird `olm` namespace which deviates from the docs which state that the Kiali Operator will be installed in the `kiali-operator` namespace by default. As a cluster admin, I want to have consistent knowledge and awareness of where everything is installed in my cluster.

## My current best solution

I found the most "reliable" way to install the Kiali Operator and Kiali itself is to directly run the _make_ commands in the release source code. Reliable is in quotes because there are quite some bugs with the scripts and perhaps I'd file an issue someday, but at least this avoids the rate limit problem.

1. Go to the release page and download the zip file for v1.0.3 (https://github.com/kiali/kiali/releases/tag/v1.0.3)

2. Extract and navigate to `kiali-1.0.3/operator/` and run the command below to install the operator.
    ```
    OPERATOR_IMAGE_VERSION=v1.0.3 make operator-create
    ```
3. Install Kiali with the following command
    ```
    KIALI_CR_FILE=deploy/kiali/kiali_cr.yaml make kiali-create
    ```

**Comment by jmazzitelli** [comment]
> I found the most "reliable" way to install the Kiali Operator and Kiali itself is to directly run the _make_ commands in the release source code.

or just do the workaround I specify above: https://github.com/kiali/kiali/issues/1271#issuecomment-518887432

Note that "make operator-create" merely calls the [same deploy script](https://github.com/kiali/kiali/blob/master/operator/Makefile#L94-L110) (compare to https://git.io/getLatestKialiOperator).

If you want to run that `bash <()` command with a specific version of the deploy script, you can do so via `bash <(curl -L https://raw.githubusercontent.com/kiali/kiali/v1.2.0/operator/deploy/deploy-kiali-operator.sh) -oiv v1.2.0 -kiv v1.2.0` where this invokes the v1.2.0 version of the script (https://git.io/getLatestKialiOperator points to the latest master version).

**Comment by lucasponce** [comment]
@jmazzitelli @eyeezzi any update on this issue ?

**Comment by eyeezzi** [comment]
@lucasponce I ended up using what @jmazzitelli recommended, that is specifying the version in the bash command. I did not see his/her comment when I left my previous reply.

As regards to resolving this issue, it is sufficient to update the documentation with @jmazzitelli's predictable installation command.

**Comment by lucasponce** [comment]
Operator scripts document a version parameter to install a specific version.
Closing this one.
Please, re-open if you think something is missing and an action is needed.
