### ISSUE TITLE
Cannot prohibit editing Istio configs via Kiali

### ISSUE THREAD

**Issue by angir** [kiali/kiali#1274]
**Describe the bug**
User account who has read-only rigths in a project OpenShift can edit Istio Configs via Kiali.

**Versions used**
Kiali: 0.16.2.redhat4
Istio: 1.1.2
Kubernetes flavour and version: v1.11.0+d4cacc0 (OpenShift v3.11.98)

**Steps to reproduce the behavior:**
1. Have default Kiali configuration - Kiali SA has the default role "Kiali", strategy: openshift.
2. Create user account and bind it to a project with read-only permissions;
3. Login user in Kiali. Try to edit objects in Istio Config section (Service Entries, Virtual Services and etc);
4. User can edit and save it.
5. Create new service account, add him the default role "kiali-viewer", edit Kiali deployment to replace the default service account with a new one. Restart Kiali's pod and try to change Istio Configs. Success. We can edit and save Istio Config with read-only permissions user accunt.

We need to prohibit editing configurations using accounts that don't have permissions to do its.

**Comment by gbaufake** [comment]
cc @hhovsepy

**Comment by jotak** [comment]
Is it using redhat service mesh / maistra?
It might be the same as this : https://issues.jboss.org/browse/MAISTRA-143

**Comment by pilhuhn** [comment]
@angir Thank you for filing this

**Comment by angir** [comment]
@jotak, thank you! It looks like our problem. We'll try to update the cluster.
