### ISSUE TITLE
Kiali Operator to support affinity and tolerations

### ISSUE THREAD

**Issue by clyang82** [kiali/kiali#1289]
**Is your feature request related to a problem? Please describe.**
I cannot specify `tolerations` and `affinity` in `spec/deployment` of `Kiali` CR. the `tolerations` and `affinity` are used in istio before. please check https://github.com/istio/istio/blob/7d93cb27fa3667a3762853979c72af29b166f833/install/kubernetes/helm/istio/charts/kiali/templates/deployment.yaml#L91

**Describe the solution you'd like**
we can define the `tolerations` and `affinity` just like https://github.com/istio/installer/blob/42a5c968caab16555ffc225780d421509542f743/istio-telemetry/kiali-operator/templates/kiali.yaml#L174

**Comment by jmazzitelli** [comment]
I just got back from vacation today - I will look at implementing this shortly.

**Comment by jmazzitelli** [comment]
This has been implemented in PR https://github.com/kiali/kiali/pull/1304
See the comment in that PR for an example of how you can define the different affinities and tolerations.

**Comment by clyang82** [comment]
very quick response. Thanks @jmazzitelli

**Comment by jmazzitelli** [comment]
PR has been merged. This enhancement request will be available in the next release.
