### ISSUE TITLE
Show helm release information for a workload/application

### ISSUE THREAD

**Issue by omerlh** [kiali/kiali#1297]
**Is your feature request related to a problem? Please describe.**
Currently, there is no UI showing Helm release information - history, status, version etc. It could be nice to view it on Kiali.

**Describe the solution you'd like**
Show per application/workload the relevant information from Helm.

**Comment by abonas** [comment]
@omerlh can you elaborate a bit where this info can be extracted from? 
Scope wise - is this per pod? how is it exposed - labels? api? any other form?

**Comment by omerlh** [comment]
It's exposed from tiller, see here an [example](https://github.com/sstarcher/helm-exporter/blob/master/main.go). With that being said, this will probably be changed in Helm 3, but I'm not familiar with the new design.

The data is per Helm release - which can contain a pod, deployment, service or any other Kubernetes object. On each object, you'll usually find a label with the chart name and the release.

**Comment by abonas** [comment]
@jmazzitelli @pilhuhn any thoughts on this?

**Comment by jotak** [comment]
If it's already set by tiller as labels on pods, we should already be able to see them, don't we?

Labels are displayed in workload details page. Note that it's the pod _template_ labels. So if they're set at another level we wouldn't see them.

**Comment by omerlh** [comment]
Yes, but what's missing is the ability to view release metadata - history,  status etc

**Comment by pilhuhn** [comment]
I wonder how much this is still in scope of Kiali. For displaying all the labels and annotations I fully agree. Making more sense out of them may be overkill (?)
@omerlh Can you show an example deployment and what exactly you would like to see here? Just from looking at the Go code you cited, it is not clear to me. Perhaps make a screen shot and paint your additions into it?

**Comment by omerlh** [comment]
Yeah, I get that. The reasoning is that when installing app via helm, it might be good information to add. But I do think this could be better supported by plugin - for example, a plugin that show service as unhealthy if the last helm deployment failed.

**Comment by lucasponce** [comment]
I think this is addressed in #1299 and #1564. 
I'm going to close this, let us know if that works for you.
