### ISSUE TITLE
Installer script fails with DRY_RUN set

### ISSUE THREAD

**Issue by jonmoter** [kiali/kiali#1302]
After I modified the installer script to fix #1300, I tried running it again, and got this result:

```
$ DRY_RUN=kiali_output.yaml ./deploy-kiali-operator.sh
Using 'kubectl' located here: /usr/local/bin/kubectl
=== UNINSTALL SETTINGS ===
UNINSTALL_EXISTING_KIALI=
UNINSTALL_EXISTING_OPERATOR=
UNINSTALL_MODE=
=== UNINSTALL SETTINGS ===
envsubst is here: /usr/local/bin/envsubst
Using downloader: curl -s
Will use the last Kiali operator release: v1.0.2
Will use the last Kiali release: v1.0.2
=== OPERATOR SETTINGS ===
OPERATOR_IMAGE_NAME=quay.io/kiali/kiali-operator
OPERATOR_IMAGE_PULL_POLICY=IfNotPresent
OPERATOR_IMAGE_VERSION=v1.0.2
OPERATOR_INSTALL_KIALI=true
OPERATOR_NAMESPACE=kiali-operator
OPERATOR_SKIP_WAIT=true
OPERATOR_VERSION_LABEL=v1.0.2
OPERATOR_WATCH_NAMESPACE=kiali-operator
OPERATOR_ROLE_CLUSTERROLES=# The operator does not have permission to manage cluster roles
OPERATOR_ROLE_CLUSTERROLEBINDINGS=# The operator does not have permission to manage cluster role bindings
=== OPERATOR SETTINGS ===
Deploying Kiali operator to namespace [kiali-operator]
Applying yaml from URL via: [curl -s https://raw.githubusercontent.com/kiali/kiali/v1.0.2/operator/deploy/namespace.yaml] to namespace [kiali-operator]
namespace/kiali-operator created (dry run)
Applying yaml from URL via: [curl -s https://raw.githubusercontent.com/kiali/kiali/v1.0.2/operator/deploy/crd.yaml] to namespace [kiali-operator]
customresourcedefinition.apiextensions.k8s.io/monitoringdashboards.monitoring.kiali.io created (dry run)
customresourcedefinition.apiextensions.k8s.io/kialis.kiali.io created (dry run)
Applying yaml from URL via: [curl -s https://raw.githubusercontent.com/kiali/kiali/v1.0.2/operator/deploy/service_account.yaml] to namespace [kiali-operator]
serviceaccount/kiali-operator created (dry run)
Applying yaml from URL via: [curl -s https://raw.githubusercontent.com/kiali/kiali/v1.0.2/operator/deploy/role.yaml] to namespace [kiali-operator]
clusterrole.rbac.authorization.k8s.io/kiali-operator created (dry run)
Applying yaml from URL via: [curl -s https://raw.githubusercontent.com/kiali/kiali/v1.0.2/operator/deploy/role_binding.yaml] to namespace [kiali-operator]
clusterrolebinding.rbac.authorization.k8s.io/kiali-operator created (dry run)
Applying yaml from URL via: [curl -s https://raw.githubusercontent.com/kiali/kiali/v1.0.2/operator/deploy/operator.yaml] to namespace [kiali-operator]
deployment.apps/kiali-operator created (dry run)
The Kiali operator has been created but you have opted not to wait for it to start. It will take some time for the image to be pulled and start.
Kiali will now be installed.
Choose a login strategy of either 'login' or 'anonymous'. Use 'anonymous' at your own risk. [login]: anonymous
Using auth strategy [anonymous] - a secret is not needed so none will be created.
=== KIALI SETTINGS ===
ACCESSIBLE_NAMESPACES=
AUTH_STRATEGY=anonymous
CREDENTIALS_CREATE_SECRET=false
GRAFANA_URL=
KIALI_CR=
KIALI_IMAGE_NAME=
KIALI_IMAGE_PULL_POLICY=
KIALI_IMAGE_VERSION=v1.0.2
ISTIO_NAMESPACE=
JAEGER_URL=
NAMESPACE=istio-system
SECRET_NAME=kiali
_SECRET_EXISTS=
=== KIALI SETTINGS ===
Deploying Kiali CR to namespace [kiali-operator]
error: unable to recognize "STDIN": no matches for kind "Kiali" in version "kiali.io/v1alpha1"
ERROR: Failed to deploy Kiali. Aborting.
```

Since the CRD wasn't created in the Kubernetes cluster, I think the `kubectl --dry-run ...` command fails, since it doesn't know what that resource is.

**Comment by jmazzitelli** [comment]
yeah, the dry run won't work if you ask the script to install Kiali itself because, as you say, dry run won't even install the CRD. So this is "to be expected". The dry run feature was really just to support spitting out the yaml to install the operator, not for kiali itself. We should have the script abort if its a dry run but you asked it to install kiali, since that clearly won't work.

**Comment by jmazzitelli** [comment]
This should work (with your fix to the sed problem, of course):

OPERATOR_INSTALL_KIALI=false DRY_RUN=kiali_output.yaml ./deploy-kiali-operator.sh

**Comment by jonmoter** [comment]
Also, I would assume that if I was executing the script in a DRY_RUN mode, I should be able to do that without connecting to a Kubernetes cluster at all. But it seems there's no way to run the script without being able to connect to a cluster. Is that on purpose?

**Comment by jmazzitelli** [comment]
> But it seems there's no way to run the script without being able to connect to a cluster. Is that on purpose?

That is correct, because the script is simply passing through the `--dry-run` option to the kubectl / oc client to use its dry run feature - which in turn will sometimes need to connect to the cluster (i.e. this is how kubectl and oc does `--dry-run` also). Try it with an example yaml but without a cluster:

```
$ kubectl apply --dry-run -f https://raw.githubusercontent.com/kubernetes/website/master/content/en/examples/controllers/nginx-deployment.yaml
error: unable to recognize "https://raw.githubusercontent.com/kubernetes/website/master/content/en/examples/controllers/nginx-deployment.yaml": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused
```

But with a cluster available that command should return successful results.

**Comment by jonmoter** [comment]
Okay.  I would prefer if there's an option to output the YAML files without needing to connect to a Kubernetes cluster.

For Istio, I've been following their [helm template install instructions](https://istio.io/docs/setup/kubernetes/install/helm/#option-1-install-with-helm-via-helm-template).  That allows me to generate the YAML files and review them while staying completely isolated from any Kubernetes cluster.  I'm a lot more comfortable with that.

If your install instructions are "download this 1,100 line bash script and execute it, and it needs to interact with your Kubernetes cluster", I get nervous.  I need to trust that you're not going to do anything unwanted with my cluster. That makes me nervous.

And looking at your install docs, I don't see any installation options that don't involve executing you bash script.

**Comment by jmazzitelli** [comment]
@jonmoter I think you want this : https://github.com/kiali/kiali/blob/master/operator/deploy/merge-operator-yaml.sh

**Comment by jonmoter** [comment]
Oh hey, that's great!  Thanks.

**Comment by israel-hdez** [comment]
@jonmoter Please, close this issue if it's solved.

**Comment by jonmoter** [comment]
I would recommend adding instructions to the "Getting started" docs on how you can generate the YAML files without needing access to a cluster, pointing to the script that John linked above.

But since there's a workaround and I'm unblocked, I'm fine with closing the issue.
