### ISSUE TITLE
External TCP services on graph and Traffic Inbound/Outbound lists

### ISSUE THREAD

**Issue by zarmin** [kiali/kiali#1314]
**General remarks**

**Describe the bug**
External TCP services not displayed on the graph and not found in Inbound/Outbound lists on the Traffic tab.

I have Oracle, MongoDB as an external service and I'd like to display them on the graph and also able to get network traffic info.

I've tried these methods w/o any success.
- ServiceEntry with hostname or IP and accessing them directly from the pods
- Using Service/ExternalName to access them combined with SE
- Using Endpoint targeted to the external service's ip address (also using SE for IP/endpoint service)

I've found this existing question, https://discuss.istio.io/t/include-external-services-in-kiali-graph/778/2
Are TCP services are implemented since then?

**Versions used**
Kiali: v0.20.0
Istio: 1.2.0
Kubernetes flavour and version: v1.14.1

**Comment by josejulio** [comment]
I have tried with ServiceEntry and it works for me, please take a look: https://medium.com/kialiproject/visualizing-istio-external-traffic-with-kiali-9cba75b337f4

We build the graph from the prometheus time-series stored by Istio, when using the ServiceEntry, you should see data querying `istio_tcp_sent_bytes_total`

If that doesn't work, please share your ServiceEntry configuration to see what could be wrong.

Also i noticed that your Kiali version is almost 2 months old, you could you try with a newer version? There were some changes on how the SE are handled some time ago.

**Comment by israel-hdez** [comment]
@zarmin do you have any additional feedback?

**Comment by zarmin** [comment]
Thanks for your answers, HTTP and HTTPS services are working properly, my issues are only with TCP services.
I've tried exactly something like that, with this SE config:
https://istio.io/blog/2018/egress-tcp/

my results are:
- I can see my SE on the graph
- If I select the 'Request per second' edge labelling, sometimes a random number appears on the edge (which is usually 1195.11), which has minimal correlation to the actual PPS or any network metric (measured with TCPdump). But usually the edge is empty.
- The application/Outbound metrics TCP send graph displaying irrelevant values, mostly 0, but sometimes between 3.0 and 3.5 kbit/sec, which has absolutely no correlation with the actual traffic. TCP receive graph is displaying the similar, but between 8 and 12 kbps.
- I can't see any traffic information elsewhere.
- I can't see any useful information in prometheus (e.g. istio_tcp_sent_bytes_total)

I'll try with an updated Kiali...

**Comment by jshaughn** [comment]
I'll be interested in any updates using a newer Kiali, although I'm maybe not hopeful of improvement.  If you continue to see TCP traffic (bytesPerSecond on the edges) that does not seem correct we need to take a close look at the istio_tcp_sent_bytes_total metric values being reported by Istio, as Kiali is likely just displaying data derived from that metric.

**Comment by zarmin** [comment]
I'll look into it more deeply, but I need to set up my own environment, because currently where I work, the 'infrastructure team' manages the K8S and the connected auxiliary services, and currently they have no time/capacity to help me in my issue or even upgrade the kiali.

**Comment by lucasponce** [comment]
@zarmin any update on this issue ?
Could you confirm if newest version of Kiali is also experimenting the behaviour you describe ?

**Comment by jshaughn** [comment]
Closing as stale, @zarmin you can re-open if you have any update, thanks.
