### ISSUE TITLE
Kiali to support istio ( new installer)

### ISSUE THREAD

**Issue by clyang82** [kiali/kiali#1315]
Istio new installer allows installing the istio components in different namespaces. refer to this readme - https://github.com/istio/installer/. so that I think a single "istio_namespace" setting in the Kiali configuration is not enough - See: https://github.com/kiali/kiali/blob/v1.1.0/operator/deploy/kiali/kiali_cr.yaml#L28-L32 

I have searched `istio_namespace`, it appears in the following places:

- discover Tracing Service if no defined in jaegerURL
- discover prometheus service if no defined in prometheusAddr
- graph related logic are using. e.g.: https://github.com/kiali/kiali/blob/82a3496fd62d7ae0756403e84676ee040c39acab/graph/telemetry/istio/appender/security_policy.go#L70
- handler related logic. e.g.: https://github.com/kiali/kiali/blob/master/handlers/threescale.go

As @jmazzitelli mentioned that
> This may require some thinking/changing on Kiali's part. Today, there is a single "istio_namespace" setting in the Kiali configuration - it is assumed Kiali components such as jaeger and prometheus by default are located here. See: https://github.com/kiali/kiali/blob/v1.1.0/operator/deploy/kiali/kiali_cr.yaml#L28-L32

> Though there are settings you can use to override them - like:

> Grafana: https://github.com/kiali/kiali/blob/v1.1.0/operator/deploy/kiali/kiali_cr.yaml#L178-L180
Prometheus: https://github.com/kiali/kiali/blob/v1.1.0/operator/deploy/kiali/kiali_cr.yaml#L223-L224
Jaeger: https://github.com/kiali/kiali/blob/v1.1.0/operator/deploy/kiali/kiali_cr.yaml#L255-L257

> That graph related logic is to filter out the graph all istio-related nodes so you don't get a very noisy graph of all the istio traffic going to the istio telemetry pods.

> I'm not familiar with the threescale usage of this istio_namespace setting.

**Comment by clyang82** [comment]
Maybe enhance from `istio_namespace` to `istio_namespaces` to support configure multiple namespaces. What changes will impact on threescale? Thanks.

**Comment by jmazzitelli** [comment]
we could add a section:

```yaml
istio_namespaces:
  grafana: <namespace where grafana is>
  prometheus: <namespace where prometheus is>
  tracing: <namespace where jaeger is>
  pilot: <namespace where pilot is>
  ... and any other component ...
```

For backwards compatibility, we would retain `istio_namespace`. If any component is not explicitly listed in the istio_namespaces, we could then default to the value specified in the istio_namespace setting.  This would also be useful for those people (like those installing the demo profile) that put all istio components in the same namespace - in that case, `istio_namespace` can just be used as it is today.

**Comment by clyang82** [comment]
That can meet the requirement ofs istio new installer. Thanks @jmazzitelli May I know when we can have this feature?

**Comment by jmazzitelli** [comment]
Let me talk to the team today and see how we can go about implementing this. This may involve getting a few people involved since it spans across a few featuresets.

FYI: I think a better name for the new config section would be `istio_component_namespaces`.

**Comment by israel-hdez** [comment]
Re-labeling as enhancement. It cannot be seen as a bug, because we don't support the istio installer yet.

**Comment by jshaughn** [comment]
non-operator/installer work tracked in https://issues.jboss.org/browse/KIALI-3195

**Comment by jmazzitelli** [comment]
We are actively researching this now. No timeframe as yet.

**Comment by jshaughn** [comment]
@clyang82 Do you actually have a multi-namespace Istio deployment working?  If so, in what environment?  Openshift, Kubernetes?

**Comment by jshaughn** [comment]
@clyang82 Kiali-3195 has been merged with initial multi-namespace support.  It would be great if you could evaluate the new support.

**Comment by clyang82** [comment]
@jshaughn sorry for late. I am just back from vacation. I will evaluate it and give update soon. Thanks.

**Comment by clyang82** [comment]
@jshaughn I deployed kiali v1.3.0. Cannot have graph data. the desired behaviour should have graph for bookinfo in default namespace.

Here is kiali configmap:
```
apiVersion: v1
data:
  config.yaml: "istio_component_namespaces:\n  grafana: istio-telemetry\n  tracing:
    istio-telemetry\n  pilot: istio-control\n  prometheus: istio-telemetry\nistio_namespace:
    istio-system \nserver:\n  port: 20001\n  web_root: /kiali\nexternal_services:\n
    \ istio:\n    url_service_version: http://istio-pilot.istio-control:8080/version\n
    \ jaeger:\n    url: \n  grafana:\n    url: \n"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"config.yaml":"istio_component_namespaces:\n  grafana: istio-telemetry\n  tracing: istio-telemetry\n  pilot: istio-control\n  prometheus: istio-telemetry\nistio_namespace: istio-system \nserver:\n  port: 20001\n  web_root: /kiali\nexternal_services:\n  istio:\n    url_service_version: http://istio-pilot.istio-control:8080/version\n  jaeger:\n    url: \n  grafana:\n    url: \n"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app":"kiali","release":"istio-telemetry-kiali"},"name":"kiali","namespace":"istio-telemetry"}}
  creationTimestamp: "2019-09-05T02:23:26Z"
  labels:
    app: kiali
    release: istio-telemetry-kiali
  name: kiali
  namespace: istio-telemetry
  resourceVersion: "25884"
  selfLink: /api/v1/namespaces/istio-telemetry/configmaps/kiali
  uid: 2438a47c-cf84-11e9-853b-0242ac110002
```
No more logs from kiali pod:
```
chunlins-mbp:installer clyang$ kubectl logs -f -n istio-telemetry kiali-57b54d84f6-l6bzn
I0905 07:54:56.438409       1 kiali.go:66] Kiali: Version: v1.3.0, Commit: af7f381bbbb51d89c544b382ee1119f1cfbc2eca
I0905 07:54:56.438870       1 kiali.go:201] Using authentication strategy [login]
I0905 07:54:56.438982       1 kiali.go:87] Kiali: Console version: 1.3.0
I0905 07:54:56.438988       1 kiali.go:261] Updating base URL in index.html with [/kiali]
I0905 07:54:56.439461       1 kiali.go:242] Generating env.js from config
I0905 07:54:56.471382       1 server.go:55] Server endpoint will start at [:20001/kiali]
I0905 07:54:56.471414       1 server.go:56] Server endpoint will serve static content from [/opt/kiali/console]
I0905 07:54:56.471421       1 metrics_server.go:18] Starting Metrics Server on [:9090]
I0905 07:54:56.471568       1 kiali.go:133] Secret is now available.
E0905 07:56:33.663819       1 grafana.go:35] grafana URL is not set in Kiali configuration
E0905 07:56:33.697340       1 jaeger.go:27] Jaeger URL is not set in Kiali configuration
E0905 07:56:46.081687       1 grafana.go:35] grafana URL is not set in Kiali configuration
E0905 07:56:46.106792       1 jaeger.go:27] Jaeger URL is not set in Kiali configuration
```

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/7711311/64323541-46033d80-cff7-11e9-8d57-cd8ec4bd734e.png">

**Comment by clyang82** [comment]
the above issue is caused of mixer telemetry. after install mixer telemetry with correct configurations, it is working now.
