### ISSUE TITLE
Constants defined for Workload and Service Dashboard patterns

### ISSUE THREAD

**Issue by ronakladhar** [kiali/kiali#1322]
In the earlier release V0.20 service_dashoard_pattern and workload_dashboard_pattern are configurable through kaili configmap.
But now with release V0.21 they are taken as an constants in grafana handler.

**Comment by jotak** [comment]
indeed ... were you customizing them?
we can put them back if needed. They was removed as part of a refactoring & simplification of the grafana config, as they were anyway poorly documented and it seemed to us that nobody was using it. We can take them back if needed.

**Comment by ronakladhar** [comment]
yes, we are customizing them to allow use of our custom grafana dashboards . 
Is there a possibility that these will again be made configurable in future releases of kiali ?

**Comment by jotak** [comment]
Sure, we can do that.

**Comment by jotak** [comment]
@ronakladhar were you also customizing the grafana variable names in Kiali config?
(as here: https://github.com/kiali/kiali/pull/1111/files#diff-3baf47c64847a8fb8aaa8cc2e088513bL136-L140 there's `var_namespace`, `var_service`, `var_workload`)

**Comment by ronakladhar** [comment]
Yes, we are customizing these variables depending upon the requirements.

**Comment by jotak** [comment]
For more control / customisation of links to grafana, I've created another task that we can work on: https://github.com/kiali/kiali/issues/1268

So this will supersede this one.

**Comment by jotak** [comment]
Hi @ronakladhar 
In pull-request https://github.com/kiali/kiali/pull/1678 I've implemented a new & more generic way to link to Grafana dashboards. Would you have a chance to take a look, and see if these settings could fulfil your needs?

**Comment by ronakladhar** [comment]
Thanks for update, i will definately view these changes and update you as soon as possible
