### ISSUE TITLE
Confusing output from Kiali operator install "Will use the last Kiali release:..."

### ISSUE THREAD

**Issue by travisrogers05** [kiali/kiali#1331]
During the install of the Kiali operator, I'm seeing a line printed out that may be confusing for end users.  I installed Kiali operator v1.0.0 as part of service mesh tp12.

I use this command:
`bash <(curl -L https://git.io/getLatestKialiOperator) --operator-image-version v1.0.0 --operator-watch-namespace '**' --accessible-namespaces '**' --operator-install-kiali false`

The operator is installed successfully, but I notice this line in the output:
`Will use the last Kiali release: v1.3.0`

I verified that the v1.0.0 version of the operator was actually installed.  However, this output line may cause confusion.  Best I can tell is that the environment variable KIALI_IMAGE_VERSION is not being set and this causes the line to be printed in the output.

https://github.com/kiali/kiali/blob/master/operator/deploy/deploy-kiali-operator.sh#L646-#L655

My output for reference:
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 45872  100 45872    0     0   100k      0 --:--:-- --:--:-- --:--:--  100k
Using 'oc' located here: /usr/bin/oc
=== UNINSTALL SETTINGS ===
UNINSTALL_EXISTING_KIALI=
UNINSTALL_EXISTING_OPERATOR=
UNINSTALL_MODE=
=== UNINSTALL SETTINGS ===
envsubst is here: /usr/bin/envsubst
Using downloader: wget -q -O -
Will use the last Kiali release: v1.3.0
IMPORTANT! The Kiali operator will be given permission to create cluster roles and
cluster role bindings in order to grant Kiali access to all namespaces in the cluster.
=== OPERATOR SETTINGS ===
OPERATOR_IMAGE_NAME=quay.io/kiali/kiali-operator
OPERATOR_IMAGE_PULL_POLICY=IfNotPresent
OPERATOR_IMAGE_VERSION=v1.0.0
OPERATOR_INSTALL_KIALI=false
OPERATOR_NAMESPACE=kiali-operator
OPERATOR_SKIP_WAIT=false
OPERATOR_VERSION_LABEL=v1.0.0
OPERATOR_WATCH_NAMESPACE=""
OPERATOR_ROLE_CLUSTERROLES=- clusterroles
OPERATOR_ROLE_CLUSTERROLEBINDINGS=- clusterrolebindings
=== OPERATOR SETTINGS ===
Deploying Kiali operator to namespace [kiali-operator]
Applying yaml from URL via: [wget -q -O - https://raw.githubusercontent.com/kiali/kiali/v1.0.0/operator/deploy/namespace.yaml] to namespace [kiali-operator]
namespace/kiali-operator created
Applying yaml from URL via: [wget -q -O - https://raw.githubusercontent.com/kiali/kiali/v1.0.0/operator/deploy/crd.yaml] to namespace [kiali-operator]
customresourcedefinition.apiextensions.k8s.io/monitoringdashboards.monitoring.kiali.io created
customresourcedefinition.apiextensions.k8s.io/kialis.kiali.io created
Applying yaml from URL via: [wget -q -O - https://raw.githubusercontent.com/kiali/kiali/v1.0.0/operator/deploy/service_account.yaml] to namespace [kiali-operator]
serviceaccount/kiali-operator created
Applying yaml from URL via: [wget -q -O - https://raw.githubusercontent.com/kiali/kiali/v1.0.0/operator/deploy/role.yaml] to namespace [kiali-operator]
clusterrole.rbac.authorization.k8s.io/kiali-operator created
Applying yaml from URL via: [wget -q -O - https://raw.githubusercontent.com/kiali/kiali/v1.0.0/operator/deploy/role_binding.yaml] to namespace [kiali-operator]
clusterrolebinding.rbac.authorization.k8s.io/kiali-operator created
Applying yaml from URL via: [wget -q -O - https://raw.githubusercontent.com/kiali/kiali/v1.0.0/operator/deploy/operator.yaml] to namespace [kiali-operator]
deployment.apps/kiali-operator created
Waiting for the operator to start..
The Kiali operator is installed!

**Comment by jotak** [comment]
@travisrogers05 , the operator version is not the same as the Kiali version. If I understand the issue, you would expect to use a specific Kiali version, am I understanding correctly? If so you should use the flag `--kiali-image-version`

**Comment by jmazzitelli** [comment]
I think I see the confusion. You specified `--operator-install-kiali false` so you would not expect to see messages dealing with Kiali (server) version.

What @jotak said is correct - the versions are different (you can install an operator version that is different than the version of kiali server that the operator installs.

But in this case, you told the script to not even install the Kiali server, so the script should probably not even spit out messages regarding that (such as the message you point out about ("Will use the last Kiali release")

**Comment by jmazzitelli** [comment]
This is a simple fix - just wrap [this script code](https://github.com/kiali/kiali/blob/v1.3/operator/deploy/deploy-kiali-operator.sh#L646-L655) with an if-stmt that skips it if the script is not to install kiali:

```
if [ "${OPERATOR_INSTALL_KIALI}" != "true" ]; then
   ...that original code here...
fi
```

**Comment by pilhuhn** [comment]
Actually I think what is a lot more confusing (iirc) is that the Kiali-Operator prints that message, but  the Maistra-Operator will later request a different version than the one that is printed at the above message.

I am following the instructions here: https://maistra.io/docs/getting_started/install/#_installing_the_kiali_operator

**Comment by jmazzitelli** [comment]
I think the solution is to just not spit out that message at all if you tell the deploy script not to install kiali. That solves the confusion because we shouldn't be telling you about a version that is not getting installed in the first place.

**Comment by travisrogers05** [comment]
> I think the solution is to just not spit out that message at all if you tell the deploy script not to install kiali. That solves the confusion because we shouldn't be telling you about a version that is not getting installed in the first place. That's what I suggest in my comment above: [#1331 (comment)](https://github.com/kiali/kiali/issues/1331#issuecomment-520813925)

+1

**Comment by jmazzitelli** [comment]
I left this one alone because it is tagged "good first issue" and is a good issue for a new contributor to fix. But since its assigned to me now, I can do this.
