### ISSUE TITLE
Make the graph can be embedded in other applications

### ISSUE THREAD

**Issue by DanielYWoo** [kiali/kiali#1341]
**Is your feature request related to a problem? Please describe.**
Kiali graph is very cool, but we already have a solid console for our Ops team.

**Describe the solution you'd like**
Is it possible to support embedded url so other applications can use an iframe to embed it? Just like grafana which supports embedded url without the header and the left pane.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by abonas** [comment]
Hi @DanielYWoo , thanks for opening this issue.
I think this might be relevant to your question and should provide the functionality you're looking for via kiosk=true parameter
https://github.com/kiali/kiali-ui/pull/812
Please let us know if indeed this is providing the solution you are looking for.

**Comment by DanielYWoo** [comment]
That should work, sorry I didn't find that PR. Many thanks.

**Comment by abonas** [comment]
> That should work, sorry I didn't find that PR. Many thanks.

This should have been documented. I'm checking whether it was added or not. if not, it should be :)
