### ISSUE TITLE
Inconsistent derivation of OPERATOR_VERSION_LABEL from OPERATOR_IMAGE_VERSION

### ISSUE THREAD

**Issue by kevchu3** [kiali/kiali#1343]
**Describe the bug**

The `kiali/operator/deploy/deploy-kiali-operator.sh` script will pull the `quay.io/repository/kiali/kiali-operator` image as well as resources found in `OPERATOR_VERSION_LABEL`.  The script has sufficient logic to determine whether the :latest image tag should pull from the master branch.  However, the tags listed in https://quay.io/repository/kiali/kiali-operator?tab=tags don't match up at all with the code branches of the https://github.com/kiali/kiali/ project (i.e. v1.3, v1.2, v1.1, etc...)

Since it's a rather tall task to relabel project branches, it would be better for specific image releases to be made to the `quay.io/repository/kiali/kiali-operator` image which follow the standard: v1.3, v1.2, v1.1, etc... Instead, I see v1.3.1 and v1.3.0 but no v1.3.  I looked at the comparable `kiali/kiali` image at https://quay.io/repository/kiali/kiali?tab=tags and it does make these shortened minor releases available: v1.3, v1.2, v1.1, etc...

As an alternative (and perhaps the simpler task), we could modify the script to take the OPERATOR_IMAGE_VERSION (i.e. v1.3.1), truncate the errata (down to v1.3), and derive the OPERATOR_VERSION_LABEL as a default behavior.

An example of where the OPERATOR_VERSION_LABEL is being used:

```
apply_operator_resource() {
  local yaml_file="${1}.yaml"
  local yaml_path="${_OP_YAML_DIR}/${yaml_file}"
  local yaml_url="https://raw.githubusercontent.com/kiali/kiali/${OPERATOR_VERSION_LABEL}/operator/deploy/${yaml_file}"
  apply_yaml ${yaml_path} ${yaml_url} ${OPERATOR_NAMESPACE}
}
```

OPERATOR_VERSION_LABEL = v1.3.1 (for the image)
However, only https://raw.githubusercontent.com/kiali/kiali/v1.3/operator/deploy/${yaml_file} will resolve.

**Versions used**
Kiali: v1.3.1
Kubernetes flavour and version: OpenShift 3.11

**To Reproduce**

bash deploy-kiali-operator.sh --operator-image-version v1.3 --kiali-image-version v1.3 --operator-watch-namespace '\*\*' --accessible-namespaces '\*\*' --operator-install-kiali false

**Comment by jmazzitelli** [comment]
This is a bug in the release process the kiali team is using to produce releases. I will let the appropriate people know. What should be happening is the v#.# tags should be produced (just like in the kiali repo). Everytime a patch version is released (v#.#.#) the v#.# should move to point to that latest patch release (so, for example, when v1.3.2 is released, there should be a v1.3 tag and it should refer to that v1.3.2 image).

But for some reason it seems like the release process is broken and those v#.# tags in quay.io are not being produced. We need to fix this.

**Comment by jmazzitelli** [comment]
Quay tags for v#.# have been created. So using `--operator-image-version v1.3` option should work now (and it will install the latest patched version of that minor version, i.e. that is 1.3.1 today).

We need to fix the release process so these tags are automatically generated.

**Comment by kevchu3** [comment]
> Quay tags for v#.# have been created. So using `--operator-image-version v1.3` option should work now (and it will install the latest patched version of that minor version, i.e. that is 1.3.1 today).
> 
> We need to fix the release process so these tags are automatically generated.

I see those image tags now in quay.io.  Since this issue is now resolved, I'll go ahead and close it out.
