### ISSUE TITLE
Developer-api documentation does not match the interface

### ISSUE THREAD

**Issue by sniperking1234** [kiali/kiali#1345]
In graph api's Responses
https://www.kiali.io/documentation/developer-api/#tag/graphs
![image](https://user-images.githubusercontent.com/7834655/63148650-71b48880-c034-11e9-978d-85d80a7e8217.png)
The actual Response is
![image](https://user-images.githubusercontent.com/7834655/63148711-a294bd80-c034-11e9-9f93-f4344a0ae6b8.png)
And I found this struct in the code
```
type Service struct {
	Namespace string `json:"namespace"`
	Name      string `json:"name"`
}
```

**Comment by jshaughn** [comment]
You are correct, the documentation is wrong.  I'm not sure why but it seems the generator is getting confused.  I'll have to investigate, but what you see in the actual response is the expected data.

**Comment by jshaughn** [comment]
I guess types aren't really namespaced in swagger, and because we have multiple "Service" types the last one processed wins.  I'll fix it by changing the name of the type in the graph code, it will be incorporared in the the work for https://issues.jboss.org/browse/KIALI-3195.

**Comment by jshaughn** [comment]
@sniperking1234 This has been resolved and the website API doc is now correct.
