### ISSUE TITLE
Installation Order

### ISSUE THREAD

**Issue by mavenir-labs** [kiali/kiali#1351]
Hi,

I wish to have a Kiali  with istio installed to have a clear view of my k8 environment .
it is not clear to me if these scripts will provide it and what is  installation order of the scripts. 

how can I verify the installation  (what is the expected results / svc / pods /etc...

Thanks in advance ,
 Avi.

**Comment by abonas** [comment]
Hi Avi, could you please specify which scripts do you refer to by "these scripts" and which environment/platform are you planning to install this on?

**Comment by abonas** [comment]
cc @jmazzitelli @pilhuhn

**Comment by jmazzitelli** [comment]
this is not a bug - removing the label. Might be best to send this to kiali-dev google group mailing list as this isn't an enhancement request or bug report.

**Comment by jmazzitelli** [comment]
The first place we'd suggest is https://www.kiali.io/documentation/getting-started - it talks about the steps to install and how to log in to see that it is working.

**Comment by mavenir-labs** [comment]
Hi,  I am refering to 'install-istio-kiali-via-helm.sh' .  It is not clear to me what is the result of this script .

this is the K8 svc's after running the script .  when I browse to the istio ingress gateway external IP , i get 404 .
![image](https://user-images.githubusercontent.com/30309611/63403201-f3b30180-c3e6-11e9-809e-6cbf98bb39fa.png)


Thanks, Avi.

**Comment by jmazzitelli** [comment]
@mavenir-labs That script [install-istio-kiali-via-helm.sh](https://github.com/kiali/kiali/blob/master/hack/istio/install-istio-kiali-via-helm.sh) is one of our "hack" scripts (as denoted by being located in the [hack/](https://github.com/kiali/kiali/blob/master/hack/) directory). It is purely for the use of the Kiali team and its developers _only_ so we can quickly install istio/bookinfo/kiali for doing our development work on our local machines. To be clear, it is **NOT** meant (nor is it documented) for use by end-users of Kiali. There is no guarantee this will work on any one particular cluster implementation.

So, just to reiterate my [earlier comment](https://github.com/kiali/kiali/issues/1351#issuecomment-523037023), for end users wanting to learn how to install Kiali, go to https://www.kiali.io/documentation/getting-started (I'm pretty sure that page will help you - for starters, if you are on k8s, the URL you use to access the Kiali UI needs to have the default context root path of `/kiali` - to learn how to access Kiali you should probably first read [this](https://www.kiali.io/documentation/getting-started/#_open_the_ui) and [this](https://www.kiali.io/documentation/getting-started/#_customize_the_kiali_ui_web_context_root))

To install Istio itself, end users should not be using that hack script - you should be using the documented and supported Istio installation mechanisms. For that, see the Istio website at: https://istio.io/docs/setup/kubernetes/

If you still can't get Kiali installed properly, feel free to submit questions to one of our user support channels here:
* [kiali-users google group](https://groups.google.com/forum/#!forum/kiali-users)
* [freenode IRC chat room #kiali](https://webchat.freenode.net/?channels=%23kiali)
* #kiali room in the [Istio Slack channel](https://istio.slack.com).

Thanks - hope that helps.
