### ISSUE TITLE
Configure External Services (Jaeger,Grafana),Does not support HTTPS?

### ISSUE THREAD

**Issue by zops** [kiali/kiali#1354]
Use the HTTP protocol in the official template. Does not support configuration private certificate?
----------------------------------------------------------------------------------------------
    external_services:
      tracing:
        url: https://jaeger-istio.test.com           # HTTPS
      grafana:
        url: https://grafana-istio.test.com         # HTTPS
      prometheus:
        url: http://prometheus:9090
----------------------------------------------------------------------------------------------
ERROR:
Get https://grafana-istio.test.com/api/search?query=Istio%20Service%20Dashboard: x509: certificate signed by unknown authority

Get https://jaeger-istio.test.com: x509: certificate signed by unknown authority

**Comment by lucasponce** [comment]
Did you check if this helps ?
https://github.com/kiali/kiali/blob/master/operator/deploy/kiali/kiali_cr.yaml#L278

**Comment by lucasponce** [comment]
I remember we tested several combination of scenarios to configure the external services.
If there is some limited scenarios, please, let us know and can try to add it.

Thanks !

**Comment by zops** [comment]
> 你检查一下这有用吗？
> https://github.com/kiali/kiali/blob/master/operator/deploy/kiali/kiali_cr.yaml#L278


https://github.com/kiali/kiali#configure-external-services

**Comment by zops** [comment]
> 你检查一下这有用吗？
> https://github.com/kiali/kiali/blob/master/operator/deploy/kiali/kiali_cr.yaml#L278

Verification passed, thank you for your answer.
