### ISSUE TITLE
Use runtime health in health checks

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1356]
"As a Kiali user, I want to see information about the health of my runtime included in the health calculations"

Epic: https://github.com/kiali/kiali/issues/1355

Issue migrated from JIRA:
https://issues.jboss.org/browse/KIALI-1248

Subtasks:
- [ ] Runtime monitoring: health check (backend) 
https://issues.jboss.org/browse/KIALI-2002
- [ ] Runtime monitoring: health check from prom query 
https://issues.jboss.org/browse/KIALI-2003
- [ ] Runtime monitoring: health check (frontend)
https://issues.jboss.org/browse/KIALI-2004

**Comment by jotak** [comment]
@lucasponce @abonas these tasks have been stalled for a long time as it is unclear if we want this (ie. more "runtimes monitoring" and here in case of health, that would be some new connections with prometheus alerting).

Should it be removed from backlog until we know exactly where we want to go?

**Comment by lucasponce** [comment]
If some issue like this is unclear we can change the label "backlog" with "future" label.
Just to mark that the scenario may be valid but not something we will work in short term.

**Comment by jotak** [comment]
ok!

**Comment by lucasponce** [comment]
To me having a "configurable" way to define what "health" is, still seem a nice area to develop.
But I think we can close this one, and re-open when in future scenarios.
