### ISSUE TITLE
Multitenancy with P8S and Grafana

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1360]
Right now Kiali provides links to Grafana to view dashboards there and we also have the assumption that p8s is also open to anyone.

We need to figure out how we are going to handle multitenancy with regards to Grafana and P8S. Even if this means we remove the links to grafana and assume p8s and Grafana are not open to everyone.

Epic: https://github.com/kiali/kiali/issues/1359

Issue migrated from JIRA:
https://issues.jboss.org/browse/KIALI-1196

**Comment by mwringe** [comment]
This issue has already been resolved. Closing.
