### ISSUE TITLE
Kiali Multitenancy

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1361]
Original Mulitenancy RS: https://issues.jboss.org/browse/KIALI-964

Presentation Recording: https://bluejeans.com/s/H3TUl/
Presentation Slides: https://docs.google.com/presentation/d/1hnYACq245lboqeN0sIeZO4RLAV_DXBZcF9Z91fz2tx4/edit?usp=sharing
Initial Document: https://docs.google.com/document/d/1Ph1sZ8X4EoRDpDCs1DpJCRrLdhLQXaGjVeQ-lkQf5WU/edit?usp=sharing
Proposal Document: https://docs.google.com/document/d/1kBrZp5tOLnU-jQfME3B7tyNiAfwAAig8Dv03E2YQ_oA/edit?usp=sharing

Epic: #1359

Issue migrated from JIRA:
https://issues.jboss.org/browse/KIALI-1184

**Comment by mwringe** [comment]
Closing as out of date.
