### ISSUE TITLE
NPM required for building Kiali but not mentioned in the readme prerequisites

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1375]
It seems that npm is required when doing 'make build' on Kiali main repo since it also fetches the UI, and without it the build fails. I looked through the main Kiali repo readme and didn't spot the requirement for npm. If this is correct, then I think it should be added there, since developers who reach the main repo won't necessarily enter the ui repo in addition.

JIRA:
https://issues.jboss.org/browse/KIALI-3033

**Comment by binayakbehera999** [comment]
Hi @lucasponce. I want to fix this issue. Could you suggest how to get started?

**Comment by jshaughn** [comment]
@mtho11 any comment on this?

**Comment by lucasponce** [comment]
@binayakbehera999 sure (and sorry for my delay). My suggestion is: try to fetch the repos and build them and as this issue seems, it looks in the README is missing that you would need to correctly install a npm dependency.

A PR updating the section about how to start developing on the project is what it should be expected.

Let us know if you would like to test it.

Thanks !

**Comment by swapnadeepmohapatra** [comment]
Hi, @lucasponce Is this issue not yet resolved? If it is not done then can I work on this?

Thanks,
Swapnadeep

**Comment by lucasponce** [comment]
@swapnadeepmohapatra I don't think it's resolved, feel free to give a try !

Thanks !
