### ISSUE TITLE
When Jaeger is down Kiali displays a long error failing to fetch service details

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1376]
When Jaeger is down, Kiali displays a long error failing to fetch service details.
Please see attached screenshot.
I'm wondering whether:
1. if Jaeger is down - why is Kiali failing to fetch service details? Kiali should be independent to operate without Jaeger too.
2. Perhaps the error message should be more user friendly (and converted to warning) - "Jaeger is down, tracing capabilities are not available" - something like that. Because, again, Kiali should be fully operational without Jaeger.

JIRA:
https://issues.jboss.org/browse/KIALI-3038

**Comment by aljesusg** [comment]
@lucasponce I think that this was solved. Can you check it?

**Comment by aljesusg** [comment]
Close after the new Jaeger Integration
