### ISSUE TITLE
Unify (and simplify) status of the application and url parameters

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1378]
Today status of the application (namespace selected, filters selected, sorting, pagination, tab selected, etc) is updated in the URLs of the application.
So, every status of the application has an linkable URL.

On the implementation side, some aspects of the state are stored in Redux, and others are handled page by page.

It could be good to study and try to refactor this logic to simplify it and make it more easy to maintain.

JIRA:
https://issues.jboss.org/browse/KIALI-1614

**Comment by israel-hdez** [comment]
This has been around for a little mor than a year.
I have the idea that we are happy the way we are handling the url and redux. Can we close this?

**Comment by jshaughn** [comment]
+1
