### ISSUE TITLE
Handle 500 errors more user friendly

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1379]
This is related/continuation of KIALI-2489.
I think Kiali-UI shows errors directly from backend and perhaps we can review a couple of things in the project:

Review/ensure in the backend all 500 errors come from valid 5xx and it's not hidding any 4xx that can be handled like KIALI-2489.
Review in the frontend, if it makes sense to parse some of these 500 errors to be more user friendly.

JIRA:
https://issues.jboss.org/browse/KIALI-2513

**Comment by jshaughn** [comment]
I think the graph code satisfies this request.  A while ago I reviewed the error handling and ensured correct distinction between 400 and 500 errors.  Also, it is making use of the new "detail" errors and handling.  The UI message center now supports messages that provide supplemental detail along with the notification message.  For example, the graph code provides stack traces as detail, for 500 errors.  See base.go:RespondWithDetailedError.

**Comment by israel-hdez** [comment]
There have been improvements on the error messages (the detailed errors from the back-end, no more "have your session expired?" messages, etc). Also, not all error messages can be handled in a friendly way, sometimes it's better to just show the stack trace.

I'm wondering if we should close this. IMO, it's too general and I'd prefer to fix the specific cases as feedback comes in.

**Comment by jshaughn** [comment]
+1
