### ISSUE TITLE
Support actions per namespace

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1380]
Today, Kiali operates at resource level granularity. 
To update or delete a resource, we should navigate to the resource and operate from there.

Also, with at service level, we can create configurations and update configurations per single service.

This JIRA is to research how we can extend operations to namespace level.

In any case, the goal of this JIRA is to investigate these potential features and what could be next steps.

JIRA:
https://issues.jboss.org/browse/KIALI-3003

Subtasks:
- [x] Extend permissions API per namespace for Istio objects
- [x] Add Gateway Form
- [x] Add Sidecar Form

**Comment by lucasponce** [comment]
Description updated to focus on "namespace" level first.
Also, added subtasks as it is necessary to extend the permission query but at namespace level.

**Comment by abonas** [comment]
is this issue about the ability to do an operation on a resource without the need to navigate to it, or about the ability for bulk operations? (an operation on multiple resources at the same time, e.g. delete 3 destination rules of namespace B)

**Comment by lucasponce** [comment]
Originally the idea was to cover: a) create a resource under a namespace that might not be related to a specific service, b) be able to run bulk operations, specially on delete, as probably update operation is tricky here.

At the moment I'm working in the first a) context as we have more clear use cases for it, b) is less priority I think and also it implies more changes (multiple selection, etc).
