### ISSUE TITLE
Add a notification that object has been modified by someone else

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1383]
emphasized textSuggestion for a feature that is similar to openshift's feature:
A notification indicating that the object has been modified by someone else when a user is standing in the yaml/overview tabs.
Based on @chrisshinn suggestion when discussing
https://github.com/kiali/kiali-design/issues/68
cc Lucas Ponce

JIRA:
https://issues.jboss.org/browse/KIALI-2121

**Comment by jshaughn** [comment]
@lucasponce I'm not sure this is doable in any near timeframe. Should we close as "Wontfix"?

**Comment by lucasponce** [comment]
@jshaughn well, this deserves some support, specially when editing an IstioConfig, it can start a listener for that config file just to warn user that resource has changed.
