### ISSUE TITLE
Introduce the concept of Revision/Snapshot in service graph

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1384]
Currently there's a missing link between request data and Istio objects associated with those data. For example, 2 hour old data is associated with routing rule v1, 30 min old with rule v2.

When new versions of the same service are introduced, Kiali continues to show previous ones (see attachment). Perhaps the graph should show only the latest revision of Istio objects and give users the ability to go back in time (by selecting previous revisions). 

Additional comments:

Probably this feature could be envision enabling some kind of "animation".
I.e. I want to compare what happened between Friday to Monday in the graph.
So from user I would like to select that time range interval, and some kind of snapshot rate (i.e. take info summarized by 1-2 hours), and then I could click a "play" button and Kiali could "build" an animation about what happened in the infrastructure.

For sure, this is a very high level description of the feature. Moved to [RS] to investigate more and potentially split it in more tasks if it's doable to implement.

JIRA:
https://issues.jboss.org/browse/KIALI-1076

**Comment by jshaughn** [comment]
Closing this as out of scope.  It's possible some sort of istio object crud events could show up on a future timeline view, but that is covered elsewhere.
