### ISSUE TITLE
Validate RH Istio Tutorial with Kiali

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1385]
We need to make sure the Red Hat developer istio tutorial works well with Kiali (https://github.com/redhat-developer-demos/istio-tutorial).

We need someone to go through the demo and fix any issues they encounter (whether its PRs to update things in the istio-tutorial or changes to how we do things in Kiali).

JIRA:
https://issues.jboss.org/browse/KIALI-2796

**Comment by jshaughn** [comment]
@lucasponce This either needs to be done at regular intervals or closed.

**Comment by lucasponce** [comment]
@lordofthejars if this https://github.com/redhat-developer-demos/istio-tutorial tutorial still valid ?
I'm not sure if evangelist are using different material, it looks a little bit outdated.

Thanks

**Comment by lucasponce** [comment]
I'm going to close it.
If it is worth, we can re-open it.

**Comment by lordofthejars** [comment]
Yes it is valid updated to Istio 1.3 so almost the last one version of
Istio (1.4) and Kiali works

**Comment by lucasponce** [comment]
@lordofthejars thanks.
Note that a similar and updated is also being published here:
https://istio.io/docs/tasks/observability/kiali/

So, from Kiali team we will try to keep updated that, perhaps the istio-tutorial could just link that to avoid having to maintain/update in two places.

Thanks.

**Comment by lordofthejars** [comment]
Great. Good idea.
