### ISSUE TITLE
Update other pages to use Redux instead of state

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1387]
Currently, only a few of the pages use Redux for state management.
These pages are Login, Message Center, user settings, and Service graph.

_Remember, Redux is what provides a reproducible application state.
_
I guess this would be the Master jira and individual jiras would assigned for each page.

JIRA:
https://issues.jboss.org/browse/KIALI-1301

**Comment by jshaughn** [comment]
Closing this as too broad.  Components should be evaluated individually, and addressed one by one as needed.
