### ISSUE TITLE
Convert our 'config.ts' file to a json or properties file

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1388]
It would be easier to alter environment settings (like for test, prod, dev) if we use property text files instead of javascript settings. Also easier for customers to alter.

Basically, replace https://github.com/kiali/kiali-ui/blob/master/src/config.ts

JIRA:
https://issues.jboss.org/browse/KIALI-1488

**Comment by israel-hdez** [comment]
The new location of the source file is https://github.com/kiali/kiali-ui/blob/master/src/config/Config.ts.

As commented in the original Jira, that file is not really end-user configs. It is a file storing constants. So, I don't think there is any improvement to do.

Closing for now. Please, reopen is there is a concrete use-case to cover.

**Comment by jotak** [comment]
+1 @israel-hdez 
If at some point we need environment-based configs, we would likely create some `xxx.env.json` files or such instead. Actually we already have that but for environment variables, `.env.downstream` and `.env.upstream`.
