### ISSUE TITLE
Remove Cola Layout from Layouts (due to poor performance rendering)

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1389]
I think now is the time to remove the Cola (#2 Layout) from layout options as it's performance is at least 3-5x longer than Cose-Bilkent (#1) and its layouts always look worse. With a large graph, Cola takes many seconds and as a user, I don't know if the application is hung or not (not the message we want to send).

This would also give us a more logical graph layout selection with one for directed graphs (Dagre) and one for Network type graphs. Just having two choices makes it easier to comprehend (since Cola and Cose-Bilkent are competing graph layouts).

JIRA:
https://issues.jboss.org/browse/KIALI-1677

**Comment by jshaughn** [comment]
This has been lying around for a longtime and it's a simple change.  If we are going to do it, let's do it.  If not let's close this.

**Comment by josejulio** [comment]
IMO `cola` looks better than `cose` (although i haven't tried on many setups)

**Comment by jshaughn** [comment]
Will not change.
