### ISSUE TITLE
Remove Annoying 'Flashing' of some Graph toolbar items

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1390]
This is especially annoying if the refresh rate is set to 5 seconds. Some, not all, but some of the items enable/disable while the fetching is occurring causing a Blinking effect.
We have no reason to do this. Why are we blocking the input? The user is free to change the settings even when the app is refreshing, it will queue up.

JIRA:
https://issues.jboss.org/browse/KIALI-1678

**Comment by jshaughn** [comment]
Unless this one gets some upvotes let's close it.

**Comment by israel-hdez** [comment]
Closing because lack of interest.
Please, comment and up-vote if this is really an issue. We can re-open if people agrees that this is an issue.
