### ISSUE TITLE
Indicate in UI in a different way the reserved word "mesh"

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1391]
There is a reserved word "mesh" that can be used in Virtual Service gateways section. 
It will be useful to users to see that it is a reserved word as opposed to a name of a gateway, so I propose to have a special indication (font + color, maybe in italic/bold) to indicate a reserved word.
Please see attached screenshot from Istio docs.

JIRA:
https://issues.jboss.org/browse/KIALI-1788

**Comment by lucasponce** [comment]
"mesh" is detected but not changed in the representation.
So, this sounds an easy fix.

```
          {host.service === 'mesh' || !isValid ? (
            host.service
          ) : (
            <Link to={`/namespaces/${host.namespace}/istio/gateways/${host.service}`}>{gateways[key]}</Link>
          )}
        </li>
```

**Comment by leandroberetta** [comment]
Hello, I looked into this change and the proposal, but the link to the "mesh" gateway is not found as it doesn't really exists as any other Gateway.

I think that an effort can be made to highlight in a different way the reserved word "mesh", and maybe a tooltip describing its meaning.

**Comment by lucasponce** [comment]
Closed by https://github.com/kiali/kiali-ui/pull/2164
