### ISSUE TITLE
Show the app label with the rest of the labels in the blue badges

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1392]
When looking at the labels in the summary panel, the "app" label is missing with the rest of the blue badges. I get it that it is inferred with the "app" title, but someone quickly looking at the blue badges trying to find out all the labels will be confused - it looks incorrect because there is no app blue badge to show there is an app label.

JIRA:
https://issues.jboss.org/browse/KIALI-1791

**Comment by serenamarie125** [comment]
I suggest we always show all labels.  Attaching what happens in OpenShift 4.2 today.

![ShowingLabels](https://user-images.githubusercontent.com/12504403/64308325-d9d8f900-cf66-11e9-9f75-6e035944d124.gif)

**Comment by lucasponce** [comment]
There are other locations (list and details) pages where Kiali shows label.
This recommendation applies there as well ?
Today labels are limited and there is a "more labels" link to show all the list.
![image](https://user-images.githubusercontent.com/1662329/64319690-41219800-cfbd-11e9-9201-2be1571db356.png)

This suggestion applies in those cases as well for consistency ?

**Comment by abonas** [comment]
It seems that the side panel in openshift has a few additional menus inside that need to be opened via clicks - that's not what Kiali has today. And the labels are not shown in the side panel before opening additional menus. There isn't also an edit labels functionality in Kiali, and afaik it is not planned to be added in the near future.
So I'm not sure the way it is done in openshift is currently a good fit here.

**Comment by jshaughn** [comment]
This issue was only about whether or not to filter away the app label in the graph side panel when we know it's an app node.  It does not have to do with editing, or even "more...".  UX is just saying show the app label, don't filter it.  I think we can just make the small change.

**Comment by jshaughn** [comment]
OK, after looking to make this change I see that there is some fundamental confusion here.  The side panel does not display the label set of the underlying object.  In fact we don't have the underlying object.  From the selected node we get from telemetry its namespace and when applicable, version.  We are displaying those values using *OS label styling*.  Namespace is not even a label.

The confusion stems from the styling, I think.  I think we need to remove the OS label styling in favor of a different look for the name-value pair.  For the updated style see:

https://github.com/kiali/kiali-ui/pull/1405
