### ISSUE TITLE
Add CPU and memory to metrics tab

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1394]
Add CPU and memory to Metrics tab where it is relevant (in workloads for example - that will require drill down a few levels)

How to get these types of metrics needs to be researched.

This may also be related to the runtime metrics, if cpu/memory are part of the metrics that it collects. See also https://kubernetes.io/docs/tasks/debug-application-cluster/resource-usage-monitoring/

JIRA:
https://issues.jboss.org/browse/KIALI-1854
https://issues.jboss.org/browse/KIALI-2137

**Comment by lucasponce** [comment]
I'd like to propose to use this one to study if we can introduce some kind of "overhead" metric more Istio related.

I mean, generic cpu/memory/traffic metrics are being handled by other tooling and Kiali has not short term goal to be-another-generic-tool-for-everything.

But, in the context of Istio, one of the worries of most users is to calculate the overhead of the proxies and the communication between data plane vs control plane.

That could add a lot of value and being used as a new signal for global health.

**Comment by jshaughn** [comment]
@lucasponce  I agree with what you are saying and offering insight into mesh overhead could be useful.  I would suggest closing this issue as out of scope and opening something dedicated to the idea you proposed.

**Comment by jotak** [comment]
CPU and memory overhead of istio-proxy seen in prometheus:

![Capture d’écran de 2020-12-04 17-36-26](https://user-images.githubusercontent.com/2153442/101189600-8d8fd380-3657-11eb-9f03-3b23b81c97ee.png)

![Capture d’écran de 2020-12-04 17-36-29](https://user-images.githubusercontent.com/2153442/101189618-92548780-3657-11eb-9571-2f6d93bd9f7c.png)

I installed the prometheus operator ( https://github.com/prometheus-operator/kube-prometheus ), I'm not sure if these metrics are available in other / "vanilla" setups.

**Comment by lucasponce** [comment]
Closing in favor of https://github.com/kiali/kiali/issues/3703
