### ISSUE TITLE
Create a common Refresh Component

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1395]
This is the follow-on task to 1887 which is a low-risk quick fix and this is the more final solution that unites the application with a single Refresh component.

JIRA:
https://issues.jboss.org/browse/KIALI-1929

**Comment by jshaughn** [comment]
Taking this as I think this could be relevant to https://github.com/kiali/kiali/issues/1421.  That PR has to do with graph replay, but it may make sense to use a common "TimeRange" component, used both by Overview and Graph.  Even if that doesn't happen this is an overdue refactor as we have multiple components doing nearly the same thing in different ways.
