### ISSUE TITLE
Update the graph legend to use html

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1396]
Right now the graph legend is an SVG.

This tends to work out ok, but it can be a bit tough to keep things aligned properly. Its easy for things to look a bit out of place or a bit more cramped.

Having the legend be more html should help to keep it looking cleaner.

It will also be required for the i18n effort and if we want to support responsive design.

JIRA:
https://issues.jboss.org/browse/KIALI-1990

**Comment by jshaughn** [comment]
This is already done as Kiali-3022.  Closing.
