### ISSUE TITLE
Update the complex test mesh to include mtls

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1397]
We should update the complex test mesh to include at least one connection being done over mtls, while the rest of the mesh is not using mtls.

See https://preliminary.istio.io/docs/reference/config/istio.networking.v1alpha3/#TLSSettings

JIRA:
https://issues.jboss.org/browse/KIALI-2007

**Comment by jshaughn** [comment]
Closing as stale, probably not needed at this point.
