### ISSUE TITLE
Graph layout: possibility to order app boxes manually

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1398]
When having several services deployed which interact to each other, the services graph become a bit messy and you cannot manually order any box at your desire. That is, if you want to move all the boxes belonging to the same "transaction" to the bottom of the screen, you cannot and you just have to stick to default layouts.
See attached file, while it is not even too complex, it becomes already a mess.

JIRA:
https://issues.jboss.org/browse/KIALI-2012

**Comment by jshaughn** [comment]
Closing as duplicate of https://github.com/kiali/kiali/issues/1342
