### ISSUE TITLE
Mesh Checkup Report

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1402]
"As a Kiali user, I want an option to be given a report about things in my mesh that might need my attention. I want to see where I might have health issues, errors, and missing recommended practises. I don't need this to be run constantly, this can just be something that is created when I manually click a button"

Things that could be included in this:

health issues in the mesh. If something has a failing health check, I should know about it.
errors in configurations.
missing sidecars
multiple workloads with the same app and version labels (its possible, but considered an anti-pattern)
missing the recommended app and version labels
active fault injection (should only be used in testing, let a user know if this is enabled somewhere in case they forgot to turn it off)
where mirroring is enabled
missing virtual services for scenarios where this might be expected [eg if I have 3 workloads behind a service without a virtual service]

JIRA:
https://issues.jboss.org/browse/KIALI-2139

**Comment by lucasponce** [comment]
I think there is room to validate best practices https://istio.io/docs/ops/best-practices/ with a mesh and provide that in a grouped report for 1..N namespaces.

**Comment by lucasponce** [comment]
@jshaughn I'm not sure about this one.
Personally, I see difficult to move to a report all the info, and graph and list pages have strong filtering to focus in important areas.

So, unless there is anything more specific I'm fine with closing this one and open a new one with more close/specific description.

**Comment by jshaughn** [comment]
+1 I think Kiali in general is already solving this problem.
