### ISSUE TITLE
Use Greenkeeper for updating UI libs

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1403]
If we add: https://greenkeeper.io/ it can automatically create a PR with the package updates and run tests.

JIRA:
https://issues.jboss.org/browse/KIALI-2140

**Comment by josejulio** [comment]
I tried greenkeeper on my fork, and it leads to many update PRs. I'm not really sure if this is what we want.
See: https://github.com/josejulio/swsui/pulls

**Comment by josejulio** [comment]
Closing, automatic updates might not be the best if we are fixing the dependencies in the patch version.
Lots of spam.
