### ISSUE TITLE
List hostnames of rejected external connections (and make it easy to accept them)	

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1405]
In an Istio mesh, external connections are rejected unless a serviceentry exists that explicitly grants access.

Right now in Kiali, if a workload tries to connect to an external host we show a red 'unknown' triangle. This isn't very helpful (and is likely confusing to users).

"As a Kiali user, I would like to see what host was attempted to be accessed and provided with an option to 'allow access' (eg create a serviceentry that would grant access). Knowing that some host was denied access is not that helpful"

Note: by default the metrics that we have do not provide this information. But Istio can be configured to start collecting the request.host which does give this information (https://istio.io/docs/reference/config/policy-and-telemetry/attribute-vocabulary/)

We might also want to discuss with UXD on the best way to visualise this in the mesh. Perhaps we need a new shape or something else to represent rejected connections.

JIRA:
https://issues.jboss.org/browse/KIALI-2167

**Comment by jshaughn** [comment]
We need to revisit the behavior with Istio 1.3 and changes with telemetry reporting for the PassthroughCluster,

**Comment by jshaughn** [comment]
> In an Istio mesh, external connections are rejected unless a serviceentry exists that explicitly grants access.

This is no longer true by default.  By default Istio sets `global.outboundTrafficPolicy.mode` to `ALLOW_ANY` for external requests.  In such case the request is allowed to exit the mesh, via the `PassthroughCluster`, which acts as sort of a default ServiceEntry. ` PassthroughCluster` is not an actual Service or ServiceEntry, but shows up in the telemetry.    When configured to `REGISTRY_ONLY` requests not routed through a ServiceEntry will be blocked.

Either way the actual requested host is not available unless, as the description points out, request.host is configured as an additional telemetry field.  The question is whether or not we want to try and collect these hosts (and possibly success/fail rates for each) if and when that additional information is present.

If so, I'd probably recommend that we just display the hosts in the side panel of the `PassthroughCluster `service (perhaps PC should be shown as a service entry?).  Also, we need to test in istio 1.3 the failed telemetry resulting from `REGISTRY_ONLY` and no matching ServiceEntry.  The hope would be that it shows a failed request for `PassthroughCluster`.

**Comment by jshaughn** [comment]
> Also, we need to test in istio 1.3 the failed telemetry resulting from REGISTRY_ONLY and no matching ServiceEntry. The hope would be that it shows a failed request for PassthroughCluster.

It does not.  The PassthroughCluster is set as the dest service only for requests that in fact leave the mesh.  When REGISTRY_ONLY is set and a service entry host does not match the request, the dest service is unknown.  But, the request_host is set and so it could be valuable to display the failed, requested, host.

**Comment by jshaughn** [comment]
OK, I'm going to assign this to myself and put it on the backlog.  I may start before 1.3.1 and use request_host to develop the feature.  But in 1.3.1 we should be seeing the following:

- PassthroughCluster destination for traffic successfully leaving the mesh
- BlackholeCluster destination for traffic blocked from leaving the mesh
- In both cases the destination_service should be set to request.host (when possible).

This means we should be seeing some consistent, non-unknown, nodes for egress and we don't need to require request_host be additionally configured to provide detailed endpoint information for serviceEntry, PassthroughCluster, and BlackholeCluster nodes.

**Comment by jshaughn** [comment]
When the PRs get merged we will be able to see the rejected hosts via the graph.  The second part of this, "(and make it easy to accept them)" should likely be a new, enhancement, issue.

**Comment by jshaughn** [comment]
@lucasponce The work to report the rejected external hosts is in (requires Istio 1.3.1+ to be effective).  As for part II of this issue, I think it merits a new enhancement issue and, that this can be closed.  What do you think?
