### ISSUE TITLE
YAML editor needs word wrapping

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1406]
When we display the YAML in the ACE Editor, certain lines are very long, such as kubernetes annotations which causes a slider to appear in the bottom section. This is quite cumbersome to use and completely unnecessary.

We should enable word wrapping in the ACE editor to show the whole contents without the need to scroll horizontally.

JIRA:
https://issues.jboss.org/browse/KIALI-2215

**Comment by israel-hdez** [comment]
Closing because it's resolved in kiali/kiali-ui#1655
