### ISSUE TITLE
Refresh and time options between pages

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1409]
We need to research how we want the time selectors and refresh rates synchronised between the various different views.

It might make sense that we want things like the graph and metric pages to have a synchronised time period (so when I move from the graph to the metric pages the same frame reference).

For the refresh rate, it likely that some components don't necessarily need the same refresh. A service detail list might be desirable to have a different refresh rate than say the the metrics or graph page.

We need to look into these areas a bit more and figure out what our plan should be going forward.

JIRA:
https://issues.jboss.org/browse/KIALI-2282

**Comment by jshaughn** [comment]
This is done.  Overview and Graph have synced settings because they aggregate similarly (longer durations often make sense).  Detail pages have synced settings because charts aggregate similarly (shorter durations make sense).
