### ISSUE TITLE
Add ability to save Graph Highlighting commands

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1410]
So I have carefully crafted my 'Graph Find' DSL and I regularly use the same highlighting. I want to be able to call up my favorite highlight command without having to type it in again.

I'm submitting this knowing that when we add filters to this it will be even more powerful.

This should include the capability to save/delete/modify existing highlights/filters to browser local storage.

JIRA:
https://issues.jboss.org/browse/KIALI-2283

**Comment by jshaughn** [comment]
@mtho11 , is there more to do here?  We have the browser suggestions and we don't lose value in session when navigating around.

**Comment by lucasponce** [comment]
Outdated, I think.
We can reopen with more details if needed.

**Comment by jshaughn** [comment]
Actually, duplicate of https://github.com/kiali/kiali/issues/1464, which is actually in progress.
