### ISSUE TITLE
Command completion on Graph Find/Hide

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1411]
When doing graph filtering I would like to be able to have it autocomplete or suggest a list valid commands so that I don't have to know the syntax (DSL) or have the Help screen up.

Suggested also by community: https://github.com/kiali/kiali/issues/1211

JIRA:
https://issues.jboss.org/browse/KIALI-2284

**Comment by lucasponce** [comment]
Lower priority. But I also think is a "nice to have" feature.
Interesting also for newcomers.

**Comment by jshaughn** [comment]
This has been sitting a while and the list of graph find operands has grown pretty large.  I think I can do something easy to at least get this started...

**Comment by jshaughn** [comment]
PR created, it's basic but it's a start that if someone wants to could be extended to start doing more intelligent things like helping with the entire expression.  But that could be a new issue.

For now, done analogous to CLIs, Tab key will loop through choices that start with the current input.
