### ISSUE TITLE
Remove Redux Persistence

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1412]
We have had some issues with this lately and we only have a couple of the smaller screens using this right now anyway. It loads previous settings and so if things break then you don't know it because it uses the previous settings. This could tend to hide a lot of issues in the future. For this reason, I think we should just take this out and explicitly use localStorage when you want to save something in the browsers db.

JIRA:
https://issues.jboss.org/browse/KIALI-2418

**Comment by jshaughn** [comment]
This is obsolete.
