### ISSUE TITLE
Explore ways to compare versions of a service

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1423]
Explore how we could show a summary of differences between 2 versions of a service (for instance, differences in response time, etc)

It might be from a whole page to a simple tooltip with very summarized information.

Find what could be relevant to display as such information.

JIRA:
https://issues.jboss.org/browse/KIALI-553

**Comment by jshaughn** [comment]
Perhaps itr8 is sufficient here?

**Comment by lucasponce** [comment]
@jshaughn +1 
So, closing in favor of #2007
