### ISSUE TITLE
Display apdex information in Kiali

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1427]
Apdex (https://en.wikipedia.org/wiki/Apdex) is a popular mechanism for monitoring applications.

"As a Kiali user I would like ot see Apdex information about my application and have this included as part of the health information. So that I can know how satisfied by customers are with their experiences"

Update: making this a RS for now to figure this out a bit better. We would also likely need to figure out how a user can specify what values they want to use here. Perhaps with an annotation on the service, or done some other way.

JIRA:
https://issues.jboss.org/browse/KIALI-1106

**Comment by jshaughn** [comment]
Closing as stale and no upvotes.
