### ISSUE TITLE
Graph in the service details page

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1429]
"As a Kiali user, I want to be able to see a graph when viewing information about a service or a workload. This graph would only show me information about what is directly communicating with the service/workload and not the whole graph. This is to allow me to have a more 'zoomed' in view of what I am looking at"

JIRA:
https://issues.jboss.org/browse/KIALI-1257

**Comment by jshaughn** [comment]
duplicate https://github.com/kiali/kiali/issues/1960
