### ISSUE TITLE
When user has few namespaces the overview page looks empty

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1441]
It needs some redesign/alternative look to handle this case.
also tracked in https://github.com/kiali/kiali-design/issues/57

JIRA:
https://issues.jboss.org/browse/KIALI-1815

**Comment by jshaughn** [comment]
Maybe it's just me, but this seems fine as is.

**Comment by mtho11** [comment]
This one seems fine to me as well.

**Comment by jshaughn** [comment]
Closing as Not a Problem.
