### ISSUE TITLE
Document Workload Graph Showing Service Nodes

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1442]
The workload graph is showing Service Nodes, when Display->Services is not selected

1) Navigate to Graph, and select bookinfo namespace
2) Select GrapyType->Workload
3) Ensure Display->Services is NOT checked

Note the Service node displayed, but should not be
Version tested:
kiali-ui 0.10.0 (996143d3f233cffd61dd682329aeb45c9cdda9d2)
kiali v0.10.0-SNAPSHOT (5c39202c1be439bede04f9c8d63fe05207b895d0)

JIRA:
https://issues.jboss.org/browse/KIALI-1844

**Comment by jshaughn** [comment]
Fixed by https://github.com/kiali/kiali.io/pull/165
