### ISSUE TITLE
Support multi language i18n

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1445]
Issue reported : https://github.com/kiali/kiali/issues/670

Technical terms (eg virtual service) should remain in English since they are the terms used by Istio (and the yaml configuration files).

Things like labels that we are using in the UI should be updated to support i18n.

We should start small and simple and only try to support a few languages at first. We should only be targeting LTR for the first implementation of this and ignore RTL.

This task is only for the front end. For the backend (eg things like errors) we should look at those after in a separate jira.

JIRA:
https://issues.jboss.org/browse/KIALI-1963

**Comment by lucasponce** [comment]
No short term plan to offer i18n support.
Kiali will remain in English as default, if there is community interest on this one please, let us know and we can revisit the priority of it.

**Comment by jshaughn** [comment]
new issue for this:  https://github.com/kiali/kiali/issues/2923
