### ISSUE TITLE
Service Detail - Add Text For Case Where Service Has No Labels

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1448]
Perhaps add text such as "None" for the case where a Service has no Labels, instead of leaving blank (see pic)

JIRA:
https://issues.jboss.org/browse/KIALI-2017

**Comment by lucasponce** [comment]
Interesting for newcomers.

**Comment by girishramnani** [comment]
if this is not taken, I can take a look at this. I will add the approach here before opening a PR for this.

**Comment by lucasponce** [comment]
@girishramnani feel free to review it is still valid, but thanks for jumping on this.

**Comment by lucasponce** [comment]
Outdated.
Service detail page has been refactored covering this scenario.
