### ISSUE TITLE
Determine how to get CPU/Memory metrics

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1451]
We might want to display things such as cpu and memory metrics somewhere in Kiali. But how to get these types of metrics needs to be researched.

This may also be related to the runtime metrics, if cpu/memory are part of the metrics that it collects.

See also https://kubernetes.io/docs/tasks/debug-application-cluster/resource-usage-monitoring/

JIRA:
https://issues.jboss.org/browse/KIALI-2137

**Comment by israel-hdez** [comment]
I'll close this one and unify in #1394.
