### ISSUE TITLE
DR Overview - Add Status Info

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1452]
Add the result of validation/status into Overview tab of Destination Rule page.

When opening DR overview page from Service detail's DR tab, in the Overview section there is not status information about the validation result of that DR.

JIRA:
https://issues.jboss.org/browse/KIALI-2152

**Comment by hhovsepy** [comment]
Currently it shows only Error status, Warning statuses are not shown in Overview page.

**Comment by lucasponce** [comment]
This is still valid as it's not implemented.

**Comment by lucasponce** [comment]
This one has changed the scope with the implementation in https://github.com/kiali/kiali-ui/pull/1904
