### ISSUE TITLE
Old namespace metrics are still used to generate the graph

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1460]
With KIALI-1714 we are suppose to only use metrics that come from a namespace after its been created (eg if I create namespace 'foo' and then delete it, someone else shouldn't be able to create a new namespace 'foo' and be able to get metrics from it).

But this doesn't always work out properly and some data can still be accessed from before the namespace was created.

Steps to reproduce:
1) deploy the istio bookinfo demo and access it via the gateway. You should be able to see the graph populated and that everything is working as expected.
2) delete the namespace you deployed the bookinfo demo into
3) create a namespace with the same name and deploy the istio bookinfo demo. But do not have anything access it.
4) notice that the graph is now displaying the relationship between components.

Expected results: the graph should be empty. The old namespace metrics shouldn't be used in this new namespace.

JIRA:
https://issues.jboss.org/browse/KIALI-2250

**Comment by infa-ddeore** [comment]
any updates on this? or is  there a workaround by deleting some selected prometheus metrics?

**Comment by jshaughn** [comment]
@infa-ddeore Not really.  There was a proposed code change in Kiali (see the original Jira) but it's not something we really want to implement due to the potential perf impact.  The best workaround is probably to not re-use namespace names, although that may not be feasible for particular users.  We did enhance the graph hide feature, you can type in "!traffic" in the hide box and the dead edges will disappear and now (by default) the graph will re-render.  As for deleting prom data, it's likely out of scope for Kiali but could be done using the prometheus API.  So, if you had a script that dropped a namespace it could possibly also wipe associated prom data.

**Comment by infa-ddeore** [comment]
@jshaughn do you know which metrics to delete from prometheus?
Because Kiali gets the data from prometheus so i think it should provide the information that which metrics can be deleted to cleanup the old data and let the user find how to do that prometheus.

**Comment by jshaughn** [comment]
The primary metrics used by Kiali at this time are:
- istio_requests_total
- istio_tcp_sent_bytes_total
- istio_request_duration_seconds_bucket (typically istio <= v1.4 i.e. telemetry V1)
- stio_request_duration_milliseconds_bucket (typically istio >= 1.5 i.e. telemetry V2)

**Comment by infa-ddeore** [comment]
i deleted all the metrics related to affected namespace, here is what worked in my case:

```
#!/bin/sh

NS=namespace-name
PROM=localhost:9090

# Kiali reads from default metrics - https://istio.io/docs/reference/config/policy-and-telemetry/metrics/
# Run all these default metrics query where the src or dest namespace label mateches the namespace

for METRIC in istio_requests_total istio_request_duration_seconds istio_request_bytes istio_response_bytes istio_tcp_sent_bytes_total istio_tcp_received_bytes_total istio_tcp_connections_opened_total istio_tcp_connections_closed_total; do 
    for LABEL in source_workload_namespace destination_workload_namespace destination_service_namespace; do 
        echo ===== Deleting $METRIC{$LABEL=\"$NS\"} =====
        #curl -s -g http://$PROM/api/v1/series? --data-urlencode 'match[]='"$METRIC"'{'"$LABEL"'="'"$NS"'"}'
	curl -X PUT http://$PROM/api/v1/admin/tsdb/delete_series? --data-urlencode 'match[]='"$METRIC"'{'"$LABEL"'="'"$NS"'"}'
    done
done
```

**Comment by lucasponce** [comment]
https://kiali.io/documentation/latest/faq/#prom-metrics
