### ISSUE TITLE
Provide Graph Highlighting History dropdown of previously used commands (persistent)

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1464]
I would like to access my history of Graph Highlighting commands to quickly use something I have already defined.

JIRA:
https://issues.jboss.org/browse/KIALI-2285

**Comment by abonas** [comment]
is having a history of previously typed text is not an integral part of the relevant components? like pf4 component that supports that? (could be not, I thought that it's worth to check before implement from scratch)
cc @aljesusg

**Comment by aljesusg** [comment]
Unfortunately there is not a PF4 component for this :(

**Comment by abonas** [comment]
@aljesusg ok thanks!

**Comment by mtho11** [comment]
After UX meeting yesterday looks like this one will go on hold as OS is discussing similar needs.

**Comment by lucasponce** [comment]
Please, all "waiting external" issues that have no progress should be removed from the Sprint.

**Comment by lwrigh** [comment]
@Veethika Hoping to get more feedback on how Openshift does this!

**Comment by mtho11** [comment]
@kiali/ux-reviewers Any movement here?

**Comment by lwrigh** [comment]
My first thought is to have a dropdown from the field that shows the previously used commands but I need more context for this ask.

**Comment by lwrigh** [comment]
Is there any more UX feedback that is needed for this issue? If not can the waiting label UX be removed?

**Comment by jshaughn** [comment]
Closing, see https://github.com/kiali/kiali/issues/2329.

**Comment by mtho11** [comment]
CC @beaumorley @jshaughn @lwrigh
