### ISSUE TITLE
Remove <div></div> in UI and replace by <></> to avoid dom depth

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1469]
Support for fragments from 16.2

https://reactjs.org/blog/2017/11/28/react-v16.2.0-fragment-support.html

Improve performance of the UI removing unnecessary layers in DOM

JIRA:
https://issues.jboss.org/browse/KIALI-2471

**Comment by israel-hdez** [comment]
This has been around since February. It was marked as low priority in Jira. I agree this is very, very, very low priority, because it does not affect functionality.

I think it's better to fix instances of this as we see them while doing other tasks.  So, I'll close as stale.
