### ISSUE TITLE
For Kiali-UI assets set the cache-control headers

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1473]
As part of an efficient web application the cache control for assets should be set:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control

JIRA:
https://issues.jboss.org/browse/KIALI-2508

**Comment by lucasponce** [comment]
This is open quite long without anyone taking it.
Is this just a change in the index.html to update the Meta for cache or does this need to update a new library for caching resources ?

**Comment by jshaughn** [comment]
I'm closing this as it is stale and the UI is not afaik suffering from any client-side perf issue.
