### ISSUE TITLE
Remove bottom link that is the same to the main one from overview cards

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1474]
The overview page cards have bottom links to topology, services, workloads, etc.
There is also a link in the middle of the card that is to apps/workloads/services based on what the user has selected.
This is creating duplicity, so if the main link is services, the link to services from bottom of the card should be removed. If the main link is workloads, the link to workloads from the bottom of the card should be removed, etc.

JIRA:
https://issues.jboss.org/browse/KIALI-2530

**Comment by israel-hdez** [comment]
@jshaughn this sounds simple. I'll self assign. If OK for you, please include in this or next sprint.
