### ISSUE TITLE
Make Hack scripts work with OS/X

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1475]
It would be nice if the hack scripts worked for OS/X.
Setting up everything manually is not a big deal – but this would be nice for the community.

JIRA:
https://issues.jboss.org/browse/KIALI-2569

**Comment by israel-hdez** [comment]
@mtho11 are the hack scripts still having issues?

**Comment by jshaughn** [comment]
Note that this would currently mean for both AWS and Minikube.  Also, there is this vague MacOS build issue that could be related: https://github.com/kiali/kiali/issues/2025

**Comment by mtho11** [comment]
@jshaughn the scripts still don't work on OS/X the last time I looked. I use Fedora for building the backend and OS/X for kiali-ui.

**Comment by israel-hdez** [comment]
@mtho11  The logs on the Jira are for the old `oc cluster up`. It will be great if we can have more recent logs to see where do we stand.

**Comment by mtho11** [comment]
@israel-hdez TBH the team has never decided to support OS/X. So I dropped interest a while back. Just labeling as **help wanted** at this point

**Comment by israel-hdez** [comment]
I see no interest from community for this issue.
Closing as stale.
