### ISSUE TITLE
Add to graph indicator for Kiali scenarios

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1477]
Similar to indicator that CB exists, show also FI
https://github.com/kiali/kiali-ui/pull/1077#issuecomment-474108138

JIRA:
https://issues.jboss.org/browse/KIALI-2596

**Comment by lucasponce** [comment]
This is still valid.
In theory it would be to add a new use case into the badges.

![image](https://user-images.githubusercontent.com/1662329/107940262-417eda80-6f88-11eb-9162-556f7bbc4a70.png)

Perhaps an improvement could be to detect the "Kiali" scenarios with badges.

Kiali supports 5 high level scenarios defined on services:

![image](https://user-images.githubusercontent.com/1662329/107940415-78ed8700-6f88-11eb-8049-76fd40bc9dd2.png)

That are easily detected, so the graph appender could extend this info, and put special badges if those are present.

If not, because Istio is regular, I think that perhaps could be enough just to mention that a service as a VS.

I'll add into the Project to not miss the priority and comment about it.

**Comment by lucasponce** [comment]
Also, Kiali collects Istio security info under the Workload details.

In particular *.security.istio.io config and/or sidecar/envoyfilters are described under a Workload.

This issue could study if graph could augment badges for workloads on those scenarios as well.

**Comment by lucasponce** [comment]
@jshaughn @nrfox this is an issue that I'd really like to see some progress and it can add a lot of value to the management use cases.

The first 5 high level scenarios (https://github.com/kiali/kiali/issues/1477#issuecomment-779157326) can be easily detected as those are annotated in the current VS, so the appender could add that info.

The security scenarios may take more work and perhaps it can be done in a separate effort, but this could be a nice task to increase visibility in the graph about the Istio configuration managed by Kiali as well.

**Comment by nrfox** [comment]
Just to make sure I understand the terminology in Kiali and how that maps to Istio VirtualService configuration, from the scenarios supported by Kiali (the ones defined in the action drop down for a service):

**Request Routing** corresponds to `spec.http.route` and `spec.http.match` i.e. "which destination to send traffic to"
**Fault Injection** corresponds to `spec.http.fault`
**Traffic Shifting** corresponds to `spec.http.route.weight`
**TCP Traffic Shifting** corresponds to `spec.tcp.route` and `spec.tcp.match`
**Request Timeouts** corresponds to `spec.http.timeout`

Is that correct?

**Comment by nrfox** [comment]
For surfacing these scenarios to the user from the graph view, it seems like the simplest thing to do would be to add additional graph badges for each one as has been mentioned. One reservation is that, if multiple scenarios are applied to the same service then there may end up being up to n+1 badges where n is the amount of scenarios we support + the VS badge itself.

In order to lesson the visual space taken up by the badges, another option would be to have some kind of "modifier" badge that is perhaps smaller than the existing badges or else included with the virtual service badge somehow (expands on hover?).

A third option is to implement the additional scenarios as some kind of animation like a flashing red around the node in case of fault injection. This option could be pretty noisy and be less clear to the user what is happening in addition possibly eating up more browser resources. Maybe this could be a toggle option in addition to the badges like the traffic animation is today.

**Comment by jshaughn** [comment]
A definite -1 to any sort of animation.  I'd start with just verbosely adding badges and see if it really turns out to be some sort of problem.  It's probably already done implicitly but badges should be strictly ordered so they don't move around positionally.

**Comment by nrfox** [comment]
IMO

Option 1 - adding additional graph badges, seems like the least amount of changes required but could potentially make the node label more cluttered.

Option 2 - adding some kind of "modifier badge", would probably require more work but could look nicer especially if additional routing scenarios are added to kiali in the future.

Option 3 - adding animation, should probably be an "extra" toggle-able option but not the only way the different routing scenarios are presented to the user.

I can make a prototype of option 1 to see how it looks to have multiple badges on the same node label. Probably the backend changes to add the additional node metadata would be the same regardless of which option was chosen.

@jshaughn @lucasponce what do you think?

**Comment by nrfox** [comment]
> A definite -1 to any sort of animation. I'd start with just verbosely adding badges and see if it really turns out to be some sort of problem. It's probably already done implicitly but badges should be strictly ordered so they don't move around positionally.

Sorry github didn't refresh till I added my comment. That sounds good to me!

**Comment by lucasponce** [comment]
> Just to make sure I understand the terminology in Kiali and how that maps to Istio VirtualService configuration, from the scenarios supported by Kiali (the ones defined in the action drop down for a service):
> 
> **Request Routing** corresponds to `spec.http.route` and `spec.http.match` i.e. "which destination to send traffic to"
> **Fault Injection** corresponds to `spec.http.fault`
> **Traffic Shifting** corresponds to `spec.http.route.weight`
> **TCP Traffic Shifting** corresponds to `spec.tcp.route` and `spec.tcp.match`
> **Request Timeouts** corresponds to `spec.http.timeout`
> 
> Is that correct?

Note that all scenarios created by kiali are proper labeled/annotated, so in the appender you will have the scenario, no need to check the internals of the Istio resources.

**Comment by lucasponce** [comment]
> Option 1 - adding additional graph badges, seems like the least amount of changes required but could potentially make the node label more cluttered.

My preference would be: if Kiali detects that a configuration comes from the Istio Wizard (because there is a label created) just use that badge.

Other cases should fall into the existing badges.

At least as a starting point.

**Comment by nrfox** [comment]
> Note that all scenarios created by kiali are proper labeled/annotated, so in the appender you will have the scenario, no need to check the internals of the Istio resources.

```
labels:
  kiali_wizard: request_routing
```

I hadn't noticed these before, thanks!

**Comment by nrfox** [comment]
I've opened draft PRs for the backend and frontend changes and wanted to get some feedback on the choice of icons before going further (especially with updating the legend). For some reason I wasn't able to get the patternfly (pf-icon) icons to display at all on the graph badge. Not sure if that is a known issue but it looks like all the existing badges use fontawesome (fa-icon) icons.

Here are the icons I chose. I'm really not married to these so any feedback is welcome.


**Request Routing:** <img src="https://user-images.githubusercontent.com/6226732/119377999-bbabb300-bc8b-11eb-8dec-6abba389fa0d.png" height="50" width="50">
**Request Timeouts:** <img src="https://user-images.githubusercontent.com/6226732/119378001-bbabb300-bc8b-11eb-9d65-357267a79d52.png" height="50" width="50">
**Faul Injection:** <img src="https://user-images.githubusercontent.com/6226732/119378002-bc444980-bc8b-11eb-8141-a83347496215.png" height="50" width="50">
**Traffic Shifting (both http and tcp)** <img src="https://user-images.githubusercontent.com/6226732/119378004-bc444980-bc8b-11eb-8178-1761bb386b1b.png" height="50" width="50">

**Comment by lucasponce** [comment]
cc @lwrigh

**Comment by jshaughn** [comment]
@lwrigh is out this week and next so I think we will need to continue without immediate UX feedback. I have a couple of comments for you and @lucasponce:

- Do we really need a Virtual Service badge and a Request Routing badge?
- If we have a badge for every feature of a VS then perhaps we should abandon the VS badge?  Or use it for Request Routing?
  - I don't really like the blocks for Request Routing (i think it's used already for kube pods), and the VS icon would not be bad for that feature, that's one reason I am asking.
- The Timeout and FI icons seems good.
- I don't like the Balance icon for Traffic Shifting, it's sort of busy and the first thing I think of is Load balancer.  Maybe just a % sign or something like that?  I don't have a great alternative, maybe [fa-share-alt](https://fontawesome.com/icons/share-alt?style=solid)?

**Comment by nrfox** [comment]
>     * Do we really need a Virtual Service badge and a Request Routing badge?

That's a good question. Are there scenarios where you would have a Virtual Service without any request routing? Even if there were, it might be better to not display it on the graph anyways since presumably it wouldn't be modifying traffic. Part of it also comes down to the implementation of this change. As it is, the additional badges added by this PR are only displayed on the graph when the user has used one of the kiali wizards to define the Virtual Service/Destination Rules. Specifically when the Virtual Service has the `kiali_wizard` label. The additional badges correspond to the traffic routing scenarios that kiali has wizards for. As a next step, instead of relying on the `kiali_wizard` label the presence of the different traffic routing scenarios could be parsed out of the Virtual Service spec in the graph appender. So combining the Virtual Service and Request Routing badges sounds good to me as long as the badges are meant to convey that "request routing is happening on your serivce" and not "you've setup request routing through the kiali wizard".

> I don't really like the blocks for Request Routing

If we can re-use the branch icon that's being used for VS that would be much better.

> I don't like the Balance icon for Traffic Shifting, it's sort of busy and the first thing I think of is Load balancer. Maybe just a % sign or something like that?

A `%` sign sounds good to me. The share-alt icon looks a similar to the branch icon to me and that might be a commonly used icon for opening up a menu to share things on social media or what not.

**Comment by lucasponce** [comment]
> @lwrigh is out this week and next so I think we will need to continue without immediate UX feedback. I have a couple of comments for you and @lucasponce:
> 
> * Do we really need a Virtual Service badge and a Request Routing badge?

No, I don't think we need both.
Note that Kiali allows to create a "Request Routing" scenario; a scenario will have a VS a DR and optionally other Istio resources.
When a Request Routing is present a VS badge is not necessary.
Another note, today we can't open all VS as Request Routing scenarios but that's something that will be possible soon.

So, when Kiali detects a VS that is not created/managed by Kiali, it's ok to keep the current VS badge.

> * If we have a badge for every feature of a VS then perhaps we should abandon the VS badge?  Or use it for Request Routing?
>   

Request Routing is a "generic" scenario, pretty similar as the VS, I mean, it's not a bad idea to reuse the same badge for same concept if you like.

But other scenarios are personalized tasks that may benefit of a different badge (even if at the end, those are implemented with a VS).

>   * I don't really like the blocks for Request Routing (i think it's used already for kube pods), and the VS icon would not be bad for that feature, that's one reason I am asking.

+1, to me it sounds ok to map Request Routing -> VS badge, that would make sense

> * The Timeout and FI icons seems good.

+1

> * I don't like the Balance icon for Traffic Shifting, it's sort of busy and the first thing I think of is Load balancer.  Maybe just a % sign or something like that?  I don't have a great alternative, maybe [fa-share-alt](https://fontawesome.com/icons/share-alt?style=solid)?

+1

**Comment by nrfox** [comment]
Alright I've updated the icons so that there's now a `%` symbol for the traffic shifting scenarios and the request routing scenario re-uses the code branch used for the virtual service.

![Screenshot from 2021-05-25 10-47-10](https://user-images.githubusercontent.com/6226732/119519093-2241d700-bd47-11eb-9791-08a32f8e1103.png)

**Comment by nrfox** [comment]
The `share-alt` icon looks pretty good too:
![Screenshot from 2021-05-25 10-54-25](https://user-images.githubusercontent.com/6226732/119520010-e6f3d800-bd47-11eb-9530-66cb9bce4443.png)

**Comment by nrfox** [comment]
Should there be additional display filters added for each scenario in the graph dropdown?

![Screenshot from 2021-05-26 10-22-00](https://user-images.githubusercontent.com/6226732/119677090-6a76fd00-be0c-11eb-9b8a-760d720d3024.png)

Right now the scenarios are tied to the VS filter so that checking/unchecking the VS filter will show/hide the scenario icons as well.

**Comment by jshaughn** [comment]
> Should there be additional display filters added for each scenario in the graph dropdown?

@nrfox Let's go with what we said on the sprint call.  Remove the Circuit Breakers option and just keep Virtual Services, which would then enable/disable all of the VS-related badging (which would include Circuit Breakers).  I like this grouped approach, it makes sense, and has the added benefit of dropping an option from this large menu.  It would remain enabled by default.

By the way, I thought of another touch point, Graph Find/Hide.  These new node flags should be added in as new operands.  I can walk you through it if you like, or I could generate a sub-PR if you prefer.  Or we could defer it to a separate issue.

**Comment by nrfox** [comment]
> @nrfox Let's go with what we said on the sprint call. Remove the Circuit Breakers option and just keep Virtual Services, which would then enable/disable all of the VS-related badging (which would include Circuit Breakers). I like this grouped approach, it makes sense, and has the added benefit of dropping an option from this large menu. It would remain enabled by default.

Looking back at this, Circuit Breakers are defined on the `Destination Rules` and not on the `Virtual Service`. Does that matter when grouping it together with the other options that are tied to the VS?

**Comment by jshaughn** [comment]
I'm still +1 on the grouping.  @lucasponce , any opinion?

**Comment by nrfox** [comment]
I went ahead and grouped the circuit breaker with the rest of the VS badges but that change can easily be reverted if that's not desired.

**Comment by lucasponce** [comment]
> Does that matter when grouping it together with the other options that are tied to the VS? Can't you have Circuit Breakers independent of Virtual Services?

> I'm still +1 on the grouping. @lucasponce , any opinion?

Grouping sound ok to me as well, from the Wizard, it will be tied to a VS, but those are defined in DR file, so it's possible that user may create them without a VS from a manual case (but as it happens today, if it's detected, it can be shown).

**Comment by nrfox** [comment]
Are there any followups to this? I can create separate issues for the security related scenarios as well as detecting the scenarios and appending the badges from the VS spec.
