### ISSUE TITLE
Add indicator for Istio's external traffic policy setting

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1484]
This emerged from https://github.com/kiali/kiali/issues/945, which is a question regarding external traffic.

Istio has had two policies for external traffic. Either allow all external traffic, or block it and only allow external traffic for hosts that are defined in ServiceEntries.

In Istio's documentation https://istio.io/docs/tasks/traffic-management/egress/egress-control/#envoy-passthrough-to-external-services it is noted that if external traffic is allowed by default, monitoring features are lost for external traffic.

Because of this, we should show what's the current Istio's traffic policy setting and, possibly, also show a warning to note that external traffic won't be shown in Kiali. Suggested place for the indicator is the "About" box, but any other suitable place can be considered.

—
UX issue: https://github.com/kiali/kiali-design/issues/122

JIRA:
https://issues.jboss.org/browse/KIALI-2646

**Comment by jshaughn** [comment]
@lucasponce The motivation for this hinged on Istio lacking telemetry when policy was ALLOW_ANY.  That is no longer true as PassthroughCluster is now used to represent the exiting requests.  I am closing this, re-open if you feel we need to show this config setting for purely informational purposes.
