### ISSUE TITLE
Server-side pagination

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1485]
Currently, pagination / filtering / sorting on list pages (Overview, Service List, Workloads List, Apps List) are performed client-side. Which means all items have to be loaded first.

Performances could be much improved if it's done server-side.

JIRA:
https://issues.jboss.org/browse/KIALI-2654

**Comment by jshaughn** [comment]
@lucasponce is this still true given the virtual scrolling?

**Comment by lucasponce** [comment]
I'm going to close this, as it's outdated.
Without proper filtering/sorting support from backend (k8s doesn't provide this), it doesn't make sense to make a server-side pagination on kiali.
The tradeoff is not positive.
