### ISSUE TITLE
Update the Maistra docs for the Kiali auth mechanism

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1487]
If Maistra is going to be moving towards using the OAuth security with Kiali we need to document what this change is and how users can configure it.

JIRA:
https://issues.jboss.org/browse/KIALI-2675

**Comment by jshaughn** [comment]
@JStickler Still valid?  If so can we do this for 1.1?

**Comment by JStickler** [comment]
@jshaughn Not sure what you mean by "still valid" but if this needs to get into the 1.1 docs, get the information to me and I'll make it happen.

**Comment by jshaughn** [comment]
@JStickler Uhm, that is what I was asking you :)  Can you point me to 1.1 docs so I can see what they may have to say about Kiali?

**Comment by JStickler** [comment]
Maistra docs -> https://maistra.io/

OpenShift docs -> https://docs.openshift.com/container-platform/4.5/service_mesh/servicemesh-release-notes.html 

Also here -> https://access.redhat.com/documentation/en-us/openshift_container_platform/4.5/html/service_mesh/index

**Comment by jshaughn** [comment]
@JStickler Please close this if you think the work is done.

**Comment by lucasponce** [comment]
No updates on this one.
