### ISSUE TITLE
Upstream istio should use kiali operator

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1489]
This was discussed here: https://github.com/istio/istio/issues/11836#issuecomment-482410057

JIRA:
https://issues.jboss.org/browse/KIALI-2706

**Comment by jmazzitelli** [comment]
Working on a couple upstream PRs for this:

* https://github.com/istio/installer/pull/556
* https://github.com/istio/operator/pull/622

**Comment by jmazzitelli** [comment]
Attended the Istio Environments WG on Jan 6, 2020. The Istio team is merging the istio/installer and istio/operator repos into istio/istio repo and hopefully that work will be done within a week (no guarantees). This work is required before we can go ahead and complete the work for this kiali issue.

**Comment by jmazzitelli** [comment]
The istio monorepo is completed - I'm looking into getting this work moving forward again.

**Comment by jmazzitelli** [comment]
Might need to wait for this istio PR (https://github.com/istio/istio/pull/20128) before being able to continue.

**Comment by jmazzitelli** [comment]
Upstream Istio is looking to remove third-party components and are not looking to install third-party operators. Discussion upstream is still on-going but until there is clarity, work on this issue has been paused.

**Comment by jmazzitelli** [comment]
I successfully modified and tested upstream "istioctl" installer to integrate the kiali operator with it. Just need it reviewed by upstream people and they need to determine if they want it or not. But the work is essentially done now.

PR: https://github.com/istio/istio/pull/20131

If that gets merged, we need to add a line to our hack script so it can install via the operator:

```diff
diff --git a/hack/istio/install-istio-via-istioctl.sh b/hack/istio/install-istio-via-istioctl.sh
index 7c13d211..cca0226d 100755
--- a/hack/istio/install-istio-via-istioctl.sh
+++ b/hack/istio/install-istio-via-istioctl.sh
@@ -285,6 +285,7 @@ fi
 
 for s in \
    "--set values.kiali.enabled=${KIALI_ENABLED}" \
+   "--set values.kiali.operator.enabled=${KIALI_ENABLED}" \
    "${_KIALI_TAG_ARG}" \
    "--set values.tracing.enabled=${DASHBOARDS_ENABLED}" \
    "--set values.grafana.enabled=${DASHBOARDS_ENABLED}" \
```

**Comment by jmazzitelli** [comment]
upgrade istio has changed how addons are integration. Kiali will be deployed using a simple all-in-one yaml - it will not install operator. closing this as obsolete.
