### ISSUE TITLE
Cache results of GetNamespaces()

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1494]
Recent performance review noted that the GetNamespaces() call could take nearly 5 seconds to finish and even the average (or median, can't remember) was around ~500ms. We could cache this call both for the k8s client as well as the Openshift's GetProjects().

What we need to do is replacing the RESTClient call with a typed from openshift/client-go which has the Project type. This should at least partially remove those odd slow calls to the underlying platform and allow concentrating on other performance issues later (such as caching the Istio objects).

JIRA:
https://issues.jboss.org/browse/KIALI-2782

**Comment by jshaughn** [comment]
@lucasponce this is done, right?

**Comment by lucasponce** [comment]
Correct, it can be configured using the CR
https://github.com/kiali/kiali/blob/master/operator/deploy/kiali/kiali_cr.yaml#L476
