### ISSUE TITLE
Create RBAC entities with wizards

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1497]
As Admin I would like to create both ServiceRoles and ServiceRoleBindings without leaving Kiali console.

I am thinking of using the existing wizards at Service level to create both entities.
It needs some research to clarify details:

- should I go to service level? (user might want to specify rules for more than one service)
[Sub-task] We might consider the idea of adding another tab into Service Details showing all the ServiceRoles referring to that specific service.

Here is the reference to Istio RBAC rules:
https://istio.io/docs/reference/config/authorization/istio.rbac.v1alpha1/

JIRA:
https://issues.jboss.org/browse/KIALI-2813

**Comment by xeviknal** [comment]
What do you think about an automatic RBAC rules creator for a given Namespace?
1. Define a ServiceRole for each service ([with basics](https://github.com/istio/istio/blob/master/samples/bookinfo/platform/kube/rbac/details-reviews-policy.yaml#L8))
2. Create a ServiceRoleBinding with all the services/serviceaccounts that are consuming[from telemetry] that ServiceRole ([with basics](https://github.com/istio/istio/blob/master/samples/bookinfo/platform/kube/rbac/details-reviews-policy-permissive.yaml#L18)).
3. More like default RBACize your app.

**Comment by xeviknal** [comment]
On the other side, we also would like to show the ServiceAccounts for each deployment. This should also help security users to better debug RBAC potential issues.

Why service accounts? ServiceRoleBinding has the subject field where users set the SPIFFE ID (strong identity) to identify who can use the ServiceRole attached. Example [here](https://github.com/istio/istio/blob/master/samples/bookinfo/platform/kube/rbac/details-reviews-policy.yaml#L18).
Preparing some demos related to security, I found myself going to deployment/pod yams to ensure I was building properly the spiffe id.

Where should we list the service account?
- Workload details page.
- Sidecar panel in topology graph.

**Comment by lucasponce** [comment]
Related to #1380

**Comment by lucasponce** [comment]
Probably the RBAC objects are deprecated and we need to move to the new Authorization* provided by Istio.
But it can be use it in the same issue.

**Comment by xeviknal** [comment]
Yes, the object to cover is the [AuthorizationPolicy](https://istio.io/docs/reference/config/security/authorization-policy/).

**Comment by abonas** [comment]
duplicate of #2041?

**Comment by lucasponce** [comment]
RBAC entities are deprecated in Istio 1.6.
We will review this scenario using AuthorizationPolicy objects.
