### ISSUE TITLE
Add search in logs

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1503]
Suggested at a meetup where I gave a talk: adding search in logs in Kiali UI

JIRA:
https://issues.jboss.org/browse/KIALI-2837

**Comment by jshaughn** [comment]
See relevant comment: https://github.com/kiali/kiali/issues/1559#issuecomment-558646012

**Comment by lucasponce** [comment]
Removed "discussion needed"
I think we have commented with @jshaughn that logs is an area where we want to progress.
This issue can be reconverted in an "epic" adding subtasks or linking other related issues.

**Comment by abonas** [comment]
I think we can close this one and create more specific ones regarding logging enhancements that are mesh related, general search is not something we would be pursuing now. @jshaughn @lucasponce ack?

**Comment by jshaughn** [comment]
I agree, other than the built-in browser search we're not looking to do any search/learning/analytics on the logstore.  We're mainly interested in correlated visualization.  We do still need a logging epic but it can be a new issue.
