### ISSUE TITLE
Create Kiali Traffic Split Video

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1504]
Create a video showing how to change virtual servcie traffic graphically.

JIRA:
https://issues.jboss.org/browse/KIALI-2862

**Comment by jshaughn** [comment]
Closing as stale and something will like;y be generated aroudn the iter8 work.

**Comment by mtho11** [comment]
Also, I'm doing this as part of https://github.com/kiali/kiali/issues/1582
