### ISSUE TITLE
Update Kiali Katacoda Scenarios

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1505]
They have not been updated since last June.

JIRA:
https://issues.jboss.org/browse/KIALI-2864

**Comment by mtho11** [comment]
I think this should be added soon so we can let people experience a Kiali tutorial without any setup. We could even link this from the home page as an easy way to give Kiali a try.

The current one is over a year old and obviously we can't really point to it now because it is so out of date.

**Comment by mtho11** [comment]
Not sure how this is affected by the recent purchase of Katacoda by O'Reilly: https://www.oreilly.com/ideas/oreilly-acquires-katacoda-and-a-new-way-for-2-5m-customers-to-learn

**Comment by jshaughn** [comment]
@mtho11 Can we close this?  If we want to revisit later we can close with a Future label.

**Comment by mtho11** [comment]
This is probably an @abonas @maltron decision.

**Comment by lucasponce** [comment]
Outdated, this should be filled in a different channel as it's more a marketing task for downstream products.
