### ISSUE TITLE
Graph Security Layer - show Security entities next to services nodes and sidepanel

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1507]
As we do with the virtual services, we should show the ServiceRoles next to each service.
In this way, It would be very easy for a user to determine which services don't have a role define it.
I am thinking that a Find/Hide filter would be useful too. Like: show me the services without role defined OR hide those services with role defined.
Listing all the roles is alright but having it visualized way easier for security teams.

JIRA:
https://issues.jboss.org/browse/KIALI-2867

**Comment by jshaughn** [comment]
If we get any enthusiasm for this it could probably be done in the graph like we do for the other badging (VS, CB, missingSC), optionally controlled by a display option.

**Comment by lucasponce** [comment]
I see interesting trying to enhance this, but also I have some doubts that if config are not hold in the same namespace, trying to find resources linked with a service in any namespace can be a performance penalty.

Anyway, put a label on it to discuss/investigate, as a feature is in the direction Kiali should go IMO.

**Comment by lucasponce** [comment]
I see two potential interesting tasks from here:
- One to add a badge in the graph, in a similar way as today it happens for VS.
- Second include the "link" with the security object under the service, for consistency, as it happens today with VirtualServices/DestinationRules.

**Comment by jshaughn** [comment]
@lucasponce It depends how easy it is to associate the security object (zero or one?) with the service, given the information we have in telemetry.  We do all of that work server-side during graph generation.  As long as it's not a performance issue it could be added in the same way as the VS/CB badging is done.  I'm not familiar with security objects so I need to know a bit more about them to say for sure.

**Comment by jshaughn** [comment]
@lucasponce, with the addition of source/destPolicy to the security appender (#2924) this work has advanced and can be revisited.

**Comment by jshaughn** [comment]
@lucasponce We now display the principals in the graph side-panel for edges.  is that sufficient?  If not what would be next?  Perhaps a graph find/hide like we have for mTLS?  Something like "has principal"?

**Comment by lucasponce** [comment]
> We now display the principals in the graph side-panel for edges. is that sufficient? If not what would be next? Perhaps a graph find/hide like we have for mTLS? Something like "has principal"?

I think from graph perspective it's fine, a "has principal" perhaps may help in some queries but it's not a first operation I would do.

As described in #2201 now I miss that info in the WorkloadInfo details.

**Comment by lucasponce** [comment]
Closing this one in favor of this discussion https://github.com/kiali/kiali/issues/1477#issuecomment-779174185
