### ISSUE TITLE
[operator] sometimes cannot create route

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1509]
I have seen a few times that when I do 'make openshift-deploy' that the route gets deleted and doesn't get recreated.

The logs for the route contains the following like:

fatal: [localhost]: FAILED! =>

{"attempts": 6, "changed": false, "error": 400, "msg": "Failed to create object: Could not determine if we should add owner ref\n", "reason": "Bad Request", "status": 400}

JIRA:
https://issues.jboss.org/browse/KIALI-2873

**Comment by jshaughn** [comment]
@jotak Is this still an issue or can we close?

**Comment by jotak** [comment]
not seen for a while
