### ISSUE TITLE
Detect services that are not correctly propagating trace context

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1510]
When a request is being handled by a sequence of service requests, e.g. A->B->C, if one of the services (e.g. B) does not propagate the context we get fragmented trace instances - such as A->B and B->C.

So a single request would result in two trace instances.

However Kiali would visualise the relationship between the three services correctly.

Traces typically start either outside or at the edge of the service mesh (ingress) - therefore we should try to detect situations where traces seem to begin at workloads in the middle of a service dependency graph, to generate an alert/warning for someone to investigate.

JIRA:
https://issues.jboss.org/browse/KIALI-2875

**Comment by jshaughn** [comment]
@lucasponce We may want to revisit this with the Jaeger guys given the recent integration work.

**Comment by lucasponce** [comment]
Yes, there are some situations that are well known and described in FAQ:
https://istio.io/faq/distributed-tracing/

But I think it's worth to see if some "detection logic" can be automated from Kiali, now that Kiali backend process tracing and has started some level of correlation.

I started to have some chat about this with @aljesusg but it makes sense to have it in an issue.

**Comment by jotak** [comment]
I don't see how we could detect that ... context propagation is purely a business knowledge that we can't know of, or am I missing something?

**Comment by lucasponce** [comment]
Well, I was not thinking in something complex, but @aljesusg introduced some logic to compare headers propagated by Jaeger that may detect if a trace has more jumps.
So, this issue is to explore possibilities at that level, as the info provided by the spans can help here.

**Comment by jshaughn** [comment]
The idea of overlaying trace info onto the graph may actually help in this sort of detection, depending how things work out.

**Comment by jotak** [comment]
I'm still curious to see how this could be made possible ... having some technical details would help.

**Comment by lucasponce** [comment]
Closing.

As discussed, Kiali doesn't have mechanism to detect if a A -> B -> C trace is not present in the system due a bad configuration of the tracing mechanism.

Propagating context depends on the application domain.

Kiali could add some configuration at Envoy config level, to detect and warn users in aspects similar as described to:
https://kiali.io/documentation/latest/tutorial/#01-request-routing

Like if a proxy config points to a wrong tracing server, or if something in that section is missing.

This is an area that's improving and probably some Istio config defined at Envoy level could be handled in Kiali, in particular, something like sampling trace could be visualized and modified from Kiali.

But the original goal of this issue is not possible without extra access into the application domain.
