### ISSUE TITLE
VirtualService validation should take into account gateway for duplicate validation

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1513]
VirtualHosts can share a host, if they don't share the same gateway also. We should add this to the duplicate validation's key.

JIRA:
https://issues.jboss.org/browse/KIALI-2882

**Comment by lucasponce** [comment]
@xeviknal do you remember if this one was already implemented ?

**Comment by xeviknal** [comment]
I think this one is not implemented yet.
Question here. This means that we should warn those scenarios where two VS points to the same host and gateway?
Warning:
reviews:istiogateway
reviews:istiogateway

Warning:
reviews: EMPTY
reviews: EMPTY

Not a warning:
reviews:istiogateway
reviews:bookinfogateway

Not a warning:
reviews:EMPTY
reviews:bookinfogateway

Perhaps I am misunderstanding this.

**Comment by lucasponce** [comment]
I think this is mentioned in the 
https://kiali.io/documentation/latest/validations/#_kia1106_more_than_one_virtual_service_for_same_host
as a particular case of this scenario.

I'm going to close it for now.
We can re-opened in case we may want to revisit this logic.
