### ISSUE TITLE
Graph Hover over group boxes has strange expansion issues

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1514]
The video explains this as it is hard to describe without it.
You can even see that it does it on some group boxes and not on others.

JIRA:
https://issues.jboss.org/browse/KIALI-2885

**Comment by jshaughn** [comment]
@mtho11 Is this still an issue for you?

**Comment by josejulio** [comment]
Overlapping was fixed by this PR: https://github.com/kiali/kiali-ui/pull/1469
