### ISSUE TITLE
Add the sidecar to Kiali for self monitoring

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1518]
Currently if you go to the Kiali workload detail pages, you will be able to get logs and runtime metrics.

What you wont be able to get is anything in traffic, or in the inbound/outbound metric pages. These pages will be blank.

It could be nice to get the traffic and inbound/outbound metric pages to show up about Kiali. And to have the graph show us how Kiali is interacting with things.

Just adding the side car to Kiali should grant us this information.

JIRA:
https://issues.jboss.org/browse/KIALI-2975

**Comment by lucasponce** [comment]
Around this issue I'd see two main tasks:
- Enable/Disable "extra" "self monitoring" options, that could be implemented adding connecting the sidecar to Kiali's pod.
- Also, to review the current "self monitoring" feature that looks not updated and a little bit abandoned:

![image](https://user-images.githubusercontent.com/1662329/73359620-8d89af00-42a1-11ea-98c4-cc0b039293cc.png)
![image](https://user-images.githubusercontent.com/1662329/73359633-967a8080-42a1-11ea-9c8e-238fd2f1d1f6.png)

**Comment by jshaughn** [comment]
Although not a bad thing I think that self-monitoring of Kiali is a low priority.

**Comment by lucasponce** [comment]
This is outdated as this feature is introduced as part of the Custom Dashboards feature, covering Kiali as well.
