### ISSUE TITLE
Investigate Integrations with SuperGloo

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1519]
Investigate what it would take to add SuperGloo (from Solo.io) to Kiali

JIRA:
https://issues.jboss.org/browse/KIALI-2978

**Comment by mtho11** [comment]
@jshaughn @abonas is this still relevant?

**Comment by jshaughn** [comment]
@mtho11 I don't really know much about SuperGloo. The original Jira was created by you, if you think this is still relevant maybe add some more detail about what might be done in this space.  Otherwise, I reckon we can close this issue.

**Comment by abonas** [comment]
I didn't see any progress of this, IMO can be closed.
