### ISSUE TITLE
Investigate Using PF4 Topology Component

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1524]
Investigate replacing the Cytoscape component with the Patternfly Topology component. At this point it would be to show a comparison of capabilities that Cytoscape has and capabilities that would be needed by PF Topology component for us to transition.
Deliverables include:

- Demo using current Kiali backend API json and rendered in PF4 Topology Component
- Document comparing Cytoscape/PF4 Topology Component
This would give us input into PF4 Topology component in its early stages and also identify shortcomings that might delay switching over.

JIRA:
https://issues.jboss.org/browse/KIALI-3009

**Comment by jshaughn** [comment]
@mtho11 I think this can probably be closed.  We have updated the graph with PF4 design input and there is no plan to migrate from cytoscape, unless you know otherwise.

**Comment by mtho11** [comment]
@jshaughn fine by me

**Comment by mtho11** [comment]
We can revisit this in 6 months by creating a new issue if need be.
