### ISSUE TITLE
Validation of VS converted from Knative channel is red due to weight =0

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1528]
In an environment with KNative, a Channel entity was (I'm assuming) converted by Knative into VirtualService Istio entity.
Kiali displays weight =0 as red validation.
it is not clear if weight = 0 is valid (it sounds not per Istio docs)
https://istio.io/docs/reference/config/networking/v1alpha3/virtual-service/#HTTPRouteDestination
so either KNative has some bug in conversion, or if in Istio this is a valid configuration, Kiali should not show an error in validation (remove it or at least reduce to warning)

Related:
https://github.com/istio/istio/issues/15157

JIRA:
https://issues.jboss.org/browse/KIALI-3037

**Comment by xeviknal** [comment]
This validation is not valid anymore. Galley allow users to put routes with 0 weight.

![Screen recording (22)](https://user-images.githubusercontent.com/613814/72520645-26f4a200-385a-11ea-83fb-54cc0c171970.gif)

In the case there is only one route, Istio warns that the weight [will be assumed to be 100](https://istio.io/docs/reference/config/networking/virtual-service/#HTTPRouteDestination).

Opening a PR to remove the scenarios Galley is taking care of and adding the warning above instead.
