### ISSUE TITLE
[0.20] Backport login screen colour fix

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1529]
We had an issue with the login screen not rendering correctly based on the browser that is being used.

See https://issues.jboss.org/browse/KIALI-2993

The version of Kiali shipped with Istio 1.2 has this issue and we might want to backport the fix to the 0.20 branch.

See also: https://github.com/istio/istio.io/issues/4400#issuecomment-501891328

JIRA:
https://issues.jboss.org/browse/KIALI-3040

**Comment by israel-hdez** [comment]
Closing manually, since GitHub doesn't close issues going to version branches.
