### ISSUE TITLE
Update Kiali screenshots on istio.io

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1530]
The screenshots of Kiali are old on https://istio.io/docs/tasks/telemetry/kiali/

We should update these screenshots.

JIRA:
https://issues.jboss.org/browse/KIALI-3043

**Comment by lucasponce** [comment]
Also, the instructions are old and those are causing some bad experience for newcomers:

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/kiali-users/wI_6oQVTVrM/T-pa2-uwAAAJ

So, I will raise priority on this one.

**Comment by mtho11** [comment]
I think this can be closed with the work that @jmazzitelli did on the documentation for Istio 1.4?

**Comment by jmazzitelli** [comment]
this is done: https://istio.io/docs/tasks/telemetry/kiali/
