### ISSUE TITLE
Research automatic updates

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1532]
It might be good to research what our options are that could make it really easy for users to get updated versions of Kiali.

This could be something like automatically deploying the latest version, or providing a notification in Kiali that a new version is available and to click a button to perform the update.

OLM might already provide some functionality here, but it would need to be looked into.

JIRA:
https://issues.jboss.org/browse/KIALI-3061

**Comment by israel-hdez** [comment]
@jmazzitelli Isn't this something that is already solved when using OLM?

I understand updating OperatorHub is manual, and we have been pushing updates randomly. Perhaps we should continuously push new versions to OperatorHub??, but I'm not sure if it is worth the effort. So, not sure if there is something actionable on this issue.

**Comment by jmazzitelli** [comment]
We now support auto-upgrades via OLM. That is our upgrade mechanism. We can close this.
