### ISSUE TITLE
Higlighted service on the graph is making the internal icon overlayed and not visible

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1534]
Higlighted service on the graph is making the internal icon overlayed and not visible

JIRA:
https://issues.jboss.org/browse/KIALI-3089

**Comment by mwringe** [comment]
Blocked by https://github.com/kiali/kiali/issues/1418

We might have this resolved with the new UX design that uses larger shapes in the graph

**Comment by jshaughn** [comment]
Closing this, the UX updates for https://github.com/kiali/kiali/issues/1418 have it fixed.

![image](https://user-images.githubusercontent.com/2104052/66345350-e5c92980-e91d-11e9-985f-13e1e03a3e2f.png)
