### ISSUE TITLE
Indentation is looking confusing in traffic page

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1535]
The indentation in traffic page is looking a bit confusing.
On the one hand it looks like not good formatting by mistake.
Or if looking at hierarchy, it looks like the opposite hierarchy than reality.
For example in the attached screenshot, productpage is under details and is in indentation, but in reality it is product page that is calling details and not the other way around.
I don't remember at this point what was the original idea (I remember there was some thought put into this), but at the moment IMO this is looking confusing.

JIRA:
https://issues.jboss.org/browse/KIALI-3099

**Comment by abonas** [comment]
![indentation](https://user-images.githubusercontent.com/6277245/69640231-b05fd300-1066-11ea-961f-44e50c0bb970.png)

**Comment by israel-hdez** [comment]
A more complete screenshot:

![](https://user-images.githubusercontent.com/23639005/66007979-1e7a8600-e47a-11e9-8620-d2a2f8926d10.png)

**Comment by mtho11** [comment]
We discussed this in the last UX meeting.  What were the final steps to resolve @israel-hdez?

**Comment by israel-hdez** [comment]
@mtho11 UXD was going to provide a proposal. I think that proposal is not ready yet.

**Comment by abonas** [comment]
is there a corresponding kiali-design issue?

**Comment by israel-hdez** [comment]
A recent screenshot of the traffic tab:

![image](https://user-images.githubusercontent.com/23639005/78192426-5b2d3700-7435-11ea-8ebf-fe9a57972c95.png)

**Comment by lwrigh** [comment]
Here are a couple different options that came to mind:

1. This one features a reverse indentation order based off of Lucas's comment about the hierarchy was  the reverse in actuality. 
![Reverse indentation order](https://user-images.githubusercontent.com/20227374/78592188-b33bb300-7812-11ea-888e-6aac5b2c4510.png)

2. This one gets rid of the indentation completely so there is no confusion about the hierarchy of it. 
![All left aligned](https://user-images.githubusercontent.com/20227374/78592193-b59e0d00-7812-11ea-95af-6bc948d370c3.png)

3. This one features a collapsable/expandable row so it's more apparent that there is a parent-child relationship without an indentation. 
![Collapsable rows 1](https://user-images.githubusercontent.com/20227374/78592190-b46ce000-7812-11ea-8450-0f8de14f584b.png)

4. This one features a collapsable/expandable row so it's more apparent that there is a parent-child relationship with an indentation.
![Collapsable rows 2](https://user-images.githubusercontent.com/20227374/78592195-b636a380-7812-11ea-98e9-ab38d924f905.png)

**Comment by israel-hdez** [comment]
If there is time in tomorrows call, I can clarify some things. I'm not sure there is enough improvement ;)

**Comment by israel-hdez** [comment]
@lwrigh 

I'm reusing the same screenshot I provided before of the traffic tab:

![image](https://user-images.githubusercontent.com/23639005/78192426-5b2d3700-7435-11ea-8ebf-fe9a57972c95.png)

Then, this is the related graph:

![image](https://user-images.githubusercontent.com/23639005/78720144-c28e2f80-78ea-11ea-8519-5baf2d37372b.png)

I hope in the last call I provided better context for this issue.

**Comment by lwrigh** [comment]
@israel-hdez Do you know if there is a limit on the number of branches the graph can show? I'm trying to see how we can potentially scale the table view when there are a bunch of branches. The indentations can only show so many branches before it starts to get confusing.

**Comment by israel-hdez** [comment]
@lwrigh In theory, there is no limit.

In practice, speaking about the "Outbound" I think for most people it's only one branch per service most of the time. So, in the traffic tab most of the time you would see only one indented item below each non-indented item, and having several non-indented items.

For "inbound", it's different. In the traffic tab it would be common that you see several indented items for each non-indented item. I think, for "inbound" the most common case would be one non-indented and several indented items below that one.

**Comment by lwrigh** [comment]
@israel-hdez Thank you for the clarification! I'm working on some different options for table visualizations so I'll post them once they are more complete.

**Comment by lwrigh** [comment]
Here are some wireframes that explore different ways to visualize the inbound and outbound traffic in the table view. What do you think? 
![Inbound traffic table v2](https://user-images.githubusercontent.com/20227374/80142786-bf956f00-8579-11ea-92b6-2a545e29ae9e.png)
![Outbound traffic table v2- Collapsed](https://user-images.githubusercontent.com/20227374/80142798-c3c18c80-8579-11ea-9518-ea933bf9f6d0.png)
![Outbound traffic table v2- Selected line](https://user-images.githubusercontent.com/20227374/80142794-c328f600-8579-11ea-9cd5-76107219fdaa.png)
![Outbound traffic table v2](https://user-images.githubusercontent.com/20227374/80142795-c3c18c80-8579-11ea-8631-bbec311bd2d8.png)

**Comment by israel-hdez** [comment]
@lwrigh About the "Inbound" comment I mentioned in the last UX meeting. Here is a graph of product page receiving traffic from two workloads:

![image](https://user-images.githubusercontent.com/23639005/80746471-9039b180-8ae7-11ea-802c-21e7a9c8ead7.png)

And the traffic tab currently looks like this for the "Inbound" section:

![image](https://user-images.githubusercontent.com/23639005/80746569-b5c6bb00-8ae7-11ea-9a68-e2e7e93a2230.png)

It scales easily, since it's possible to simply add rows below the "productpage" svc. In this case is just two rows below "productpage", but it can be any number. Not sure how we could achieve something similar using your proposal of the "reversed" order approach.

About the removed icons in your wireframes, remember that I told that we are loosing information about the kind of the element showed in the row, which is important information. But I also told you that removing the icon was fine since we already removed those icons and we are using "letters". This is how the services list looks currently:

![image](https://user-images.githubusercontent.com/23639005/80747155-98462100-8ae8-11ea-9e23-ab7eeb94a520.png)

Note the "S" and the "NS" labels. Those have replaced the icons that we used previously. We could use them in the Traffic tab as replacement of the icons, but if it's visually too cluttering, any other alternative is OK.

**Comment by israel-hdez** [comment]
@lwrigh I remember you also asked about the potential node types that exist. This is what we have and it's shape in the graph:

![image](https://user-images.githubusercontent.com/23639005/80748062-f7586580-8ae9-11ea-985f-3d0bab6c6cfb.png)

**Comment by lwrigh** [comment]
@israel-hdez I put together an updated design proposal of some of the updates we talked about last meeting: https://docs.google.com/document/d/16sFut7JiXch8mnsjOYVvXaJ6MXoyVGh058JcIziRErQ/edit?usp=sharing Feel free to check out the wireframes and notes there. I encourage everyone to take a look at it and leave any feedback or comments you have. I'm planning on sharing it again in our next meeting next week.

**Comment by lwrigh** [comment]
I added some further design iterations that featured more fleshed out to the design doc in the link above. Feel free to check it out.

**Comment by lwrigh** [comment]
From UXD we're considering this issue complete on our end for this phase. If we need to revisit it we can and provide more feedback.

**Comment by jshaughn** [comment]
@lwrigh Yes, at this point I think it's up to @israel-hdez to decide on an impl given the prior discussions, and consult again with UX if he feels the work needs any further review.

**Comment by lucasponce** [comment]
Moving to Sprint 43.
I remember there were some discussion about this, I suggest to revisit some of the approaches commented and check if there is an action to perform on this one.

**Comment by jshaughn** [comment]
@lucasponce Yes we talked about this one in our Friday sprint meeting.  @israel-hdez will resolve it this sprint, one way or the other :)

**Comment by jshaughn** [comment]
@israel-hdez If you can specify the final design choice perhaps this can be farmed to someone else, as your workload has been heavy.  Or, if you prefer, we can demote this to the general backlog.

**Comment by israel-hdez** [comment]
Final design:

For OUTGOING:

![image](https://user-images.githubusercontent.com/23639005/92042705-5d772280-ed40-11ea-980c-af97e56049ba.png)

For INCOMING:

![image](https://user-images.githubusercontent.com/23639005/92042842-a8913580-ed40-11ea-934b-c72829d4233e.png)

Notice there is a new sub-tab view for displaying inbound and outbound separately.

If the new design is not suitable, there was also the proposal of removing any hierarchy and using a plain list of workloads (i.e. so no new design; just stop showing service rows).

Finally, I'm open to the drastic option of removing this feature. It's probably underused and this view is not receiving not being complemented with any new features like other screens.

**Comment by jshaughn** [comment]
@lucasponce We may need to discuss what we want to do with this one.

**Comment by lucasponce** [comment]
I think that this issue evolved a lot and with the graph overview in the main tab, perhaps the graph representation is less interesting.

But this traffic is useful and it provides info that is not collected in other place.

My thought: let's do a small movement here, I propose to just align the current info using a table as part of the consistency work we are doing around that.

Let's put aside the graph elements on this page but let's user to sort by columns when possible.

**Comment by jshaughn** [comment]
OK, let's go with the simpler table view.  I'll give it a try, may not make it for this sprint but at least let's close out this issue...
