### ISSUE TITLE
See more information for Sidecar detail page

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1536]
When navigating to the details page of an IstioConfig: Sidecar resource, we only show the YAML.

It would be useful to see:

- The WorkloadSelector and the workloads that are selected by that rule.
- The Ingress / Egress rules, with details of what services are being referenced and a link to these resources.

JIRA:
https://issues.jboss.org/browse/KIALI-3100

**Comment by lucasponce** [comment]
In the IstioConfig Details page we don't have a consistency Overview / YAML tabs.

**Comment by PsychoSid** [comment]
I would also like to see this information surfaced in Kiali as per "istioctl proxy-config endpoints <foo>" as the graph pane is only visible when traffic is flowing and is not the golden source of information. Being able to see this information in Kiali (perhaps in a table) would be really useful IMHO.

**Comment by lucasponce** [comment]
Outdated.

This feature is being implemented as part of the "Show Envoy Details" where user can access to the raw config of the proxy as well to structured views combined with existing Istio config (i.e. links with existing VS/DR from the Envoy config).

![image](https://user-images.githubusercontent.com/1662329/107947044-21541900-6f92-11eb-95e0-dea662bca54e.png)

![image](https://user-images.githubusercontent.com/1662329/107947091-32048f00-6f92-11eb-91e4-ff5f02cdc5ae.png)
