### ISSUE TITLE
With new setup of KIALI-UI there is an error in yarn start

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1538]
Add to the README for developers this problem with watchers.

Need to change system's file watchers limit with echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

JIRA:
https://issues.jboss.org/browse/KIALI-3106

**Comment by jotak** [comment]
@mtho11 yes. I suggest to link to an external doc* instead of having platform-specific instructions 

* https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers#the-technical-details
