### ISSUE TITLE
Add option to lock-in current architecture

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1542]
When we have all traffic, we have enough information to know who talks with what service.

With this information it could be possible to do some sort of "Lock-in" current traffic to prevent unwanted traffic from flowing to a service we know (depending on the architecture) does not belong to.
e.g., in the context of Bookinfo's demo, we don't expect traffic from Productpage to ratings. As the flow is productpage -> reviews -> ratings.

This is doable with the Sidecar resource (or if enabled, network policy or istio's RBAC)

JIRA:
https://issues.jboss.org/browse/KIALI-3121

**Comment by lucasponce** [comment]
I see that probably a specific Sidecar could be created mapping existing communications.
But I have feeling tradeoff perhaps is too much complexity for this.
I mean, Kiali can detect that productpage talks with reviews and details services, and details service talks with ratings one.
That info comes from telemetry.

From that scenario, a Sidecar could be created to enforce that these relations and no different ones (i.e. productpage won't talk with ratings) may happen into the cluster.

**Comment by lucasponce** [comment]
Thinking on this, I guess we can narrow this feature as a Wizard placed on the Service Details level.
This wizard would read the existing traffic (similar source provided by the traffic tab) and would build a Sidecar with the egress and ingress routes defined by the traffic.
Also as part of this task Service Details should also be able to show the linked Istio Sidecars.

**Comment by jshaughn** [comment]
@lucasponce I like the idea of doing it on a server-specific basis.  If people like that feature we could look at a global application down the road.  I'm +1 for the backlog if you agree.

**Comment by lucasponce** [comment]
Closed in favor of #2924, both are basically describing same scenario but it may differ if using Security (AuthorizationPolicy) objects or Networking (Sidecar).

So, the resource would be an implementation detail but the use case is clear.
