### ISSUE TITLE
[operator] Kiali Operator is not returning from ** to accessible namespace list

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1543]
@jmazzitelli , on MT mode, after scaling with ** with kubeadmin user.
It does not come back when the service mesh member roll reconciles it.

JIRA:
https://issues.jboss.org/browse/KIALI-3122

**Comment by jmazzitelli** [comment]
We have a molecule test showing that this works (operator starts with **, then is changed to use a list of namespaces, then is changed back to **). See: https://github.com/kiali/kiali/blob/master/operator/molecule/accessible-namespaces-test/playbook.yml

We would need additional replication procedures illustrating a problem. Right now, AFAICS, the operator is working. I think we can close this issue.

**Comment by jmazzitelli** [comment]
@gbaufake can we close this? Our molecule tests show this kind of thing working now (see the JIRA for the details you originally wrote up).

**Comment by gbaufake** [comment]
@jmazzitelli We can close it because it is not valid anymore.
