### ISSUE TITLE
Metric graph fails to show a line graph for a timeseries

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1544]
I have a situation where one metric graph (request duration) has two timeseries - one being "average, response code=200" and the other being "average, response code=500".

I tried to filter the graph to only show the "average, response code=200" line (hiding the other line) but when I try that, the graph's line doesn't show up even though it should display. However, the actual data points appear to be there, they just are hidden. Watch the animated gif I attach - when the graph hides both lines (but when it should be showing the response code "200" line) and I hover the mouse over where the data points SHOULD be, you can see the tooltip pops up with the values of what the datapoints would have been if they were not hidden.

JIRA:
https://issues.jboss.org/browse/KIALI-3124

**Comment by mwringe** [comment]
@jotak Are you currently looking into this and should this issue be assigned to you?

**Comment by jotak** [comment]
(I'm back from PTO, now looking at this)

**Comment by jotak** [comment]
Actually this issue was created in July when we had PF3 charts. Now it's completely different, the legend is not clickable anymore with PF4 charts so the scenario is not valid anymore, however I'm still going to check that hidding metrics using the "Metrics Settings" dropdown is working as expected.

**Comment by jotak** [comment]
I confirm that the issue was specific to PF3 charts hence doesn't exist anymore.
