### ISSUE TITLE
Add slack/discuss as way of contacting us to kiali.io

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1548]
We are now also present on #kiali on istio.slack.com. we should add that to the header of kiali.io and also the contributing page.

The current "chat" could be renamed to "irc chat"

Also mention discuss.istio.io

JIRA:
https://issues.jboss.org/browse/KIALI-3134

**Comment by israel-hdez** [comment]
I won't add Istio's Slack, because it's not open to everyone.
Istio's Discuss is OK.

I'll also improve a little the text of the contributing page.

**Comment by jmazzitelli** [comment]
> I won't add Istio's Slack, because it's not open to everyone.

Istio's Slack is open to everyone now.

**Comment by israel-hdez** [comment]
@jmazzitelli OK, I wasn't aware of it. Then, I'll also add a mention.
