### ISSUE TITLE
Top right arrow icon is not vertically aligned to the username

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1549]
See:
https://issues.jboss.org/browse/KIALI-3137

**Comment by mwringe** [comment]
We might need to talk with UX about this and how it should be aligned.

**Comment by mwringe** [comment]
![image](https://user-images.githubusercontent.com/691166/64044676-67ff4a80-cb35-11e9-83c9-1e53d870f269.png)

**Comment by lucasponce** [comment]
Removed from the backlog.
If we need to get feedback from UX, engineer can't know how to fix this one, then it's not ready for backlog.

**Comment by aljesusg** [comment]
Mmm yes we need to talk with UX. This is the style.

```js
<Dropdown
              isPlain
              position="right"
              onSelect={this.onDropdownSelect}
              isOpen={isDropdownOpen}
              toggle={<DropdownToggle onToggle={this.onDropdownToggle}>Kyle Baker</DropdownToggle>}
              dropdownItems={userDropdownItems}
            />
```
Css applied icon **pf-c-dropdown__toggle-icon**
```css
vertical-align: -0.125em;
```

Demo: https://patternfly-react.surge.sh/patternfly-4/demos/pagelayout/pagelayoutsimplenav/

cc @serenamarie125 @abonas

**Comment by mwringe** [comment]
Did we ever get any update from @kiali/ux-reviewers about what should be done here?

**Comment by jshaughn** [comment]
I'm closing this, Kiali UI looks exactly like the [PF4 demo](https://patternfly-react.surge.sh/patternfly-4/demos/pagelayout/pagelayoutsimplenav/).

Demo;
![image](https://user-images.githubusercontent.com/2104052/66223397-60d1dc00-e6a1-11e9-8503-bb8601891eb4.png)

Kiali:
![image](https://user-images.githubusercontent.com/2104052/66223377-544d8380-e6a1-11e9-975b-1ba3de436d94.png)
