### ISSUE TITLE
Show which Istio configurations were added/deleted/updated during a specific time range

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1552]
Allow users seeing some sort of a configuration history report on a selected timeframe, also possibly for a specific entity (but as a first step, a general list per namespace will be really great).
For example, if user selected 10 minutes on graph/elsewhere, show something like:
- 11:00 a Virtual Service named A was created
- 11:15 Destination Rule B was updated
- 11:30 Destination Rule B was deleted.

If it's possible also to show the content (for delete would be more challenging), it will be good. that's how users might be able to correlate better errors that started at point X to some changes in configuration.

**Comment by lucasponce** [comment]
I'm not sure what we can do here, as a source can be modified from different ways (CLI, Kiali UI, others UI) and we need to investigate which information is available.

**Comment by lucasponce** [comment]
@jshaughn perhaps we can discuss this one in the next grooming.

**Comment by jshaughn** [comment]
+1, btw, here's something related to this area: https://github.com/salesforce/sloop

**Comment by lucasponce** [comment]
I don't think Kiali can progress on this area.
The historical collection and storage of kubernetes objects is outside of Kiali scope.

I think we can close this one in favor to study a future potential integration with some project in that area, but as part of the "extensions" mechanism defined in Kiali, not as part of the core features.
