### ISSUE TITLE
Update Kiali to use new PF4 icon

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1553]
Basically, use FontAwesome 5 instead of images.

See https://github.com/kiali/kiali-design/issues/140 for details.

JIRA:
https://issues.jboss.org/browse/KIALI-3149

**Comment by mtho11** [comment]
Isn't this one done via: https://github.com/kiali/kiali-ui/pull/1506

**Comment by israel-hdez** [comment]
@mtho11 Apparently, you are right.
I did `grep '<Icon' -R src/` on the kiali-ui code and I found no references to the PF3 <Icon> component.
I'll close this issue and also the related kiali/kiali-design#140 issue.
