### ISSUE TITLE
There are 2 pages on the validations feature

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1555]
There are 2 pages on the validations feature:
https://www.kiali.io/documentation/validations/
https://www.kiali.io/documentation/features/#_configuration_and_validation_features
it looks like a bug.
also, there is a sub menu from the features page that has only one entry - validations, see attached screenshot.

JIRA:
https://issues.jboss.org/browse/KIALI-3157

**Comment by xeviknal** [comment]
I think this issue can be closed. The validations subsection has become a section in the documentation menu.
The section in the features seems legit. There's explained the feature. In the validations page before mentioned all the validations are listed. No feature explanation present.

**Comment by lucasponce** [comment]
Outdated.
