### ISSUE TITLE
Add filtering by validation status on Istio Config page

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1557]
Add filtering by validation status on Istio Config page
so user can easily see all error/warnings without the need to navigate through multiple pages.
There is currently an option to filter it in the first dropdown, but that is not very intuitive because it is also filtering by object type, etc. So it's not clear it is adding more criterias to filter vs changing the filter criteria (and erasing previous one)

JIRA:
https://issues.jboss.org/browse/KIALI-3159

**Comment by aljesusg** [comment]
Now we can filter by configuration:

- Valid
- Warning
- Not Valid
- Not Validated 

![Screenshot from 2020-03-12 11-19-48](https://user-images.githubusercontent.com/3019213/76511386-6b17b380-6453-11ea-8e9f-0decfd170645.png)
