### ISSUE TITLE
Bump ansible operator base image and remove workaround

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1566]
The Kiali operator upstream is using ansible operator SDK 0.9 but Kiali can only productize on ansible operator SDK 0.7 (see KIALI-3133). This means we need to add a workaround to the productized kiali operator image.

Once ansible operator SDK is productized on the latest, we need to bump up the productized kiali operator to that new base image and we need to remember to remove that workaround (it just involves adding the ao-logs script to our image - that will come with the ansible operator SDK base image so we won't have to maintain our own).

JIRA:
https://issues.jboss.org/browse/KIALI-3201

**Comment by jshaughn** [comment]
We need to bump up a newer productized ansible image.

**Comment by jshaughn** [comment]
According to @jmazzitelli this has already been done.
