### ISSUE TITLE
Api Documentation - feature follow-up

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1567]
A couple of modifications were asked as a follow-up of a PR adding API Documentation to Kiali: https://github.com/kiali/kiali/pull/1266

I've noted the following:

Set a timeout on client calls when Kiali fetches external documentation
In UI, loading indicator is still displayed upon failure
In JS console I'm seeing several 404 not found about fonts
GRPC icon is too small
Add API logo on ApiDocumentation page too
Make Kiali self-serving its swagger doc using this feature
Document feature on website
Check sub-tasks for these points

—

Note: to test ApiDocumentation, we need to set a couple of annotations on a service, example:

oc annotate service istio-pilot -n istio-system kiali.io/api-type=grpc
oc annotate service istio-pilot -n istio-system kiali.io/api-spec=https://petstore.swagger.io/v2/swagger.json
Then see the result in Service List / Service Details pages

SubTasks:
- [ ] Set a timeout on client calls
- [ ] Loading indicator keeps being displayed
- [ ] Missing fonts
- [ ] Bigger GRPC icon
- [ ] Add API logo on doc pages
- [ ] Show Kiali swagger API
- [ ] Document feature on website

JIRA:
https://issues.jboss.org/browse/KIALI-3205

**Comment by couniojc** [comment]
I've been working on a component in React to display both Rest and Grpc and that would address the 404 on missing fonts and integrates better in the Kiali react and css
I'm little busy these days but I hope I can integrate  that with Kiali pretty soon.
I will address other issues as well.

**Comment by jotak** [comment]
Thanks @couniojc !

**Comment by couniojc** [comment]
This is a first change to fix those  issues, I'm working to integrate the new component but I have some dependency issues right now, hope fully I will be done in a few days, I will add a new PR

**Comment by jotak** [comment]
Thanks @couniojc , I was on holidays last week, I'm going to have a look

**Comment by jshaughn** [comment]
@couniojc @jotak Shall we keep this open?

**Comment by jotak** [comment]
I wonder if this could be simplified and have this feature "merged" with the custom annotation feature: https://github.com/kiali/kiali/issues/1564

The advantage is that we would re-use a quite generic feature that allows to display custom links ; but on the other side it's not as smart as this feature, as Kiali would only show external links to documentation without any fancy integration. But since the two are a bit similar it would reduce the surface for maintenance.

**Comment by jshaughn** [comment]
Looking at the laundry list of work items in this issue, if we get any of that for free by merging the feature into the addition_display stuff, I'm +1.
