### ISSUE TITLE
Document/implement the UI Dev process for using RH registry mirrors instead of npm registry

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1571]
This is an Issue to cover the messages last week about RH exceeding its quota from npm registry. Someone on the team needs to own this process and set this stuff and document for all team members.

JIRA:
https://issues.jboss.org/browse/KIALI-3225

**Comment by israel-hdez** [comment]
The custom NPM mirror was more related to the build in Jenkins, rather than a Dev process. So, for devs there is nothing to implement. Thus, I don't see anything actionable here.

I'll close. If I misunderstood, please re-open.
