### ISSUE TITLE
Add documentation to website/readme for kiosk mode

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1578]
Add documentation to website/readme for kiosk mode
https://github.com/kiali/kiali-ui/pull/812#issuecomment-521676681

JIRA:
https://issues.jboss.org/browse/KIALI-3229

**Comment by israel-hdez** [comment]
Since this is documentation for devs which want to integrate Kiali to other systems, I'll only add documentation to the README.md file in the kiali/kiali repo.
