### ISSUE TITLE
Remove all React PropTypes from Kiali

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1579]
With typescript, we get all the React Proptypes capability at compile time. No need for runtime violations. That said, let's get rid of proptypes unless someone has a special need for them.

JIRA:
https://issues.jboss.org/browse/KIALI-3231

**Comment by mtho11** [comment]
We should clean this up as it is a Typescript anti-pattern. It is meant for non-typescript React apps only.

Here is an example of proptypes:
```
MissingSidecar.propTypes = {
  text: PropTypes.string,
  textTooltip: PropTypes.string,
  tooltip: PropTypes.bool,
  type: PropTypes.string,
  name: PropTypes.string,
  color: PropTypes.string
};
```

Plus this will allow us to remove entirely the package:     "prop-types": "15.7.2",
