### ISSUE TITLE
Evicted Kiali Operator will not deploy Kiali

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1584]
Evicted Kiali Operator pods will be on hanging state until the evicted pods are up.

Kiali operator will have this log on the pod.

```
{"level": "info", "ts": 1566293874.0547807, "logger": "leader", "msg": "Not the leader. Waiting."
```

Logged this issue upstream some time ago: https://github.com/operator-framework/operator-sdk/issues/1305

JIRA:
https://issues.jboss.org/browse/KIALI-3239

**Comment by abonas** [comment]
@jmazzitelli fyi

**Comment by jmazzitelli** [comment]
This is a problem in the underlying operator SDK code - they plan on addressing it in a future release. See comments in https://github.com/operator-framework/operator-sdk/issues/1305

**Comment by abonas** [comment]
@jmazzitelli is there any AI/workaround in Kiali for that? in other words - should this issue remain open on Kiali side?

**Comment by jmazzitelli** [comment]
We should leave this open if for no other reason than we need to remember to keep tracking this issue up on the operator-sdk side of things and test the fix when they have one.

I know of no workaround.

**Comment by jmazzitelli** [comment]
I think this [SDK issue](https://github.com/operator-framework/operator-sdk/issues/1305) is fixed now - see https://github.com/operator-framework/operator-sdk/pull/2210

**Comment by jshaughn** [comment]
The fix is in but not in any release.  We are waiting for a release, probably 0.13, and then we will need to move to that version.

https://github.com/operator-framework/operator-sdk/releases

**Comment by jmazzitelli** [comment]
> The fix is in but not in any release. We are waiting for a release, probably 0.13, and then we will need to move to that version.

To be clear.. the fix is in but not in any release **of operator SDK**. We are waiting for a release, probably 0.13, **of operator SDK**, and then we will need to move to that as the operator's base image.

I asked the operator SDK team when this fix will be available in a release - see:

https://github.com/operator-framework/operator-sdk/pull/2210#issuecomment-564108920

**Comment by jshaughn** [comment]
@jmazzitelli , please proceed with the update to 0.13, which has the fix.

**Comment by jmazzitelli** [comment]
fixed here: https://github.com/kiali/kiali/pull/2076
