### ISSUE TITLE
Graph legend not adjusting to screen height

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1587]
On a screen size of 1366x768 (quite common in laptops) the graph legend runs out of the viewport.

JIRA:
https://issues.jboss.org/browse/KIALI-3252

**Comment by mwringe** [comment]
Duplicate of https://github.com/kiali/kiali/issues/1620

**Comment by mtho11** [comment]
closing, in favor of https://github.com/kiali/kiali/issues/1620 which will fix that
