### ISSUE TITLE
Link from Overview to Graph - Auto-select Graph Type

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#1589]
When clicking on "Go To Graph" link of a Namespace in Overview page, it always opens the "Workload Graph" type in Graph page, does not matter which Overview Type was selected in "Show health for" in Overview page.

[RFE] It should be better to open the appropriate Graph type in Graph page, depending to which Overview type was selected in Overview page.

Apps -> App graph
Workloads -> Workload graph
Service -> Service graph

**Comment by jshaughn** [comment]
> When clicking on "Go To Graph" link of a Namespace in Overview page, it always opens the "Workload Graph" type in Graph page

It doesn't actually always go to "workload" graph type but rather the last graph type used by the user, because we now persist that in the browser.   This is just a clarification, it does not change the validity of the issue, which makes sense to me and I think we should probably make the change.
