### ISSUE TITLE
[PF4] Overview Page

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1594]
Epic:
https://github.com/kiali/kiali/issues/1588

JIRA:
https://issues.jboss.org/browse/KIALI-2735

**Comment by aljesusg** [comment]
PRs:

https://github.com/kiali/kiali-ui/pull/1388
https://github.com/kiali/kiali-ui/pull/1383
https://github.com/kiali/kiali-ui/pull/1381
https://github.com/kiali/kiali-ui/pull/1378
