### ISSUE TITLE
UI - Move lists to virtual scrolls

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1596]
https://github.com/kiali/kiali-design/issues/76

Kiali introduced "pagination" controls on list since the beginning of the UI work.
I noticed that in OpenShift console pagination controls are not present there.

The UX recommendation is to have virtual scrolling, rather than paging.

There is a PF React component which does this now, although it is a very basic list view https://rawgit.com/patternfly/patternfly-react/gh-pages/patternfly-3/index.html?knob-Nav%20Toggle=true&knob-fluid=true&knob-ShowClearfix=true&knob-Bordered=true&knob-Selection%20Type=none&selectedKind=patternfly-react-extensions%2FContent%20Views%2FVirtualTableGrid&selectedStory=VirtualTableGrid&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs

so we need to move the lists displayed in the UI to virtual scroll

Epic:
https://github.com/kiali/kiali/issues/1588

JIRA:
https://issues.jboss.org/browse/KIALI-2229

**Comment by aljesusg** [comment]
Merged: https://github.com/kiali/kiali-ui/pull/1319
