### ISSUE TITLE
Update pf3 components on the graph page to pf4

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1597]
This task is not yet ready to be worked on. We will be waiting until the other pages have been redesigned and moved over to pf4.

Docs Topology: https://patternfly-react.surge.sh/patternfly-4/components/topology/

Epic:
#1588 

JIRA:
https://issues.jboss.org/browse/KIALI-3092

**Comment by mwringe** [comment]
Close this issue. Its being addressed in smaller steps as part of https://github.com/kiali/kiali/issues/1606 https://github.com/kiali/kiali/issues/1607 https://github.com/kiali/kiali/issues/1608
