### ISSUE TITLE
[PF4] Migrate the graph filter toolbar

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1607]
Migrate the graph filter toolbar (incl find/hide) to PF4.

Epic:
#1588 

JIRA:
https://issues.jboss.org/browse/KIALI-3145

**Comment by lucasponce** [comment]
Issues *should not* be moved to *in review*.
There should be a Pull Request that is added and linked into the project.
Then automatically the PR is shown under the *in review* column.

**Comment by mtho11** [comment]
ah right @lucasponce I forgot. Thanks for the reminder.
