### ISSUE TITLE
Qualify OLM installation of Kiali Operator

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1609]
JIRA:
https://issues.jboss.org/browse/KIALI-3216

**Comment by jmazzitelli** [comment]
I think we can close this. The Kiali operator can be installed via OLM.

I'm working on upgrades via OLM. But this issue is only for install, so I think this is done.

@gbaufake since this issue is tagged with "qe" I'll assume we need you to close this.

**Comment by gbaufake** [comment]
Tested 1.0.6 operator today via OLM and it worked as expected.
