### ISSUE TITLE
Operator images don't follow version Kiali images

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1619]
I.e. v1.0 is a valid image for Kiali but it should have a similar operator counter-part.
So, for operator full version name "v1.0.0" is needed.

https://github.com/kiali/kiali/blob/master/operator/deploy/deploy-kiali-operator.sh#L67

JIRA:
https://issues.jboss.org/browse/KIALI-3086

**Comment by mwringe** [comment]
This issue has already been fixed.

Fixed by https://github.com/kiali/kiali/pull/1349
