### ISSUE TITLE
Make graph legend ability to scroll more obvious

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1620]
The graph legend has scrolling but it is not entirely obvious that there is scrolling available. We need to make the scrollbars on the legend visible at all times.

JIRA:
https://issues.jboss.org/browse/KIALI-3224

**Comment by abonas** [comment]
@lucasponce Hi, why is this labeled as maintenance? this is a user facing change, more of an UX enhancement

**Comment by lucasponce** [comment]
@abonas In JIRA this is marked as "Dev Task". Those tasks will be moved as "maintenance".

**Comment by abonas** [comment]
thanks for clarification. I'm not sure why it was marked as dev task, but this is definitely not maintenance :)

**Comment by mwringe** [comment]
This issue might be dependent on the browser or OS being used. So we should be careful when testing.

**Comment by mtho11** [comment]
Design Issue: https://github.com/kiali/kiali-design/issues/145
