### ISSUE TITLE
[RS] Research Improvements and Optimizations for the Graph

### ISSUE THREAD

**Issue by cfcosta** [kiali/kiali#1623]
Our graph algorithms have grown over time, and features that we didn't require in the beginning now might make things less optimized than what we want and need, so this RS is to check our implementation, check the kind of problems that we are trying to solve (finding islands for faster namespace filtering, for instance) against the technical literature and best pratices to see how we can reduce our overhead and possibly make new features cheaper or even possible.

JIRA:
https://issues.jboss.org/browse/KIALI-3264

**Comment by lucasponce** [comment]
Minor adjustments for consistency with the use of labels and JIRA links.
Thanks.

**Comment by cfcosta** [comment]
I'm closing this as I could not find low-hanging fruits (besides #1637). In the end it's best that we improve the performance when we change stuff, specially because doing those changes right now might also make other changes harder in the future.
