### ISSUE TITLE
Service Details page - Error Notification - Traces not available

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#1624]
Each time Service Details page is opened, there is a Error in Notifications, saying that Traces is not available.
But in fact the Traces are available and shown.

![Screenshot from 2019-08-29 16-42-22](https://user-images.githubusercontent.com/604313/63956769-61b29500-ca87-11e9-8907-16591304a1ff.png)
![Screenshot from 2019-08-29 17-53-41](https://user-images.githubusercontent.com/604313/63956770-61b29500-ca87-11e9-86a9-595097a088de.png)

**Comment by aljesusg** [comment]
This is because kiali can't get the error Traces through the jaeger service so or Kiali service can't reach Jaeger or Kiali can't identify with jaeger to check the API

**Comment by aljesusg** [comment]
Ok It seems that the patch works.

Solutions:

1. Add the patch
2. Remove the warning message (Kiali works correctly and if you have not problem with jaeger you'll see the number of errorTraces, anyway you'll see the error traces in the iframe)
3. Remove the errorTraces number display from UI

I prefer the option 1 or 2


cc @xeviknal @lucasponce

**Comment by hhovsepy** [comment]
Verified that the parch works:
![Screenshot from 2019-08-30 12-09-30](https://user-images.githubusercontent.com/604313/64013303-c8838d00-cb1f-11e9-97d1-c50c8b8695dc.png)

**Comment by aljesusg** [comment]
Closed https://github.com/kiali/kiali/pull/1627 by  https://github.com/kiali/kiali/pull/1628 **Merged**

We need to push this changes to master.
### Waiting for

Maistra 1.0 => https://github.com/Maistra/istio-operator/pull/244
Maistra 1.1 => https://github.com/Maistra/istio-operator/pull/248

**Comment by jshaughn** [comment]
Added backport1.0 label by request of @gbaufake

**Comment by aljesusg** [comment]
Maistra 1.0 **Merged** => https://github.com/Maistra/istio-operator/pull/244

**Comment by hhovsepy** [comment]
Verified on Kiali 1.0.6 production bits.

**Comment by lucasponce** [comment]
I think this is already done.
