### ISSUE TITLE
UI won't render on Firefox version < 63

### ISSUE THREAD

**Issue by jshaughn** [kiali/kiali#1631]
On FF < 63 (which currently includes the latest esr release on windows, maybe other platforms) the Kiali UI won't render, showing only a blank white screen.

This is because FF < 63 does not support Windows.customElements.  See [here](https://developer.mozilla.org/en-US/docs/Web/API/Window/customElements).

I think it  can be worked around by altering an FF setting.

The use of customElements was added in the PR to support showing API doco.  It is used only in setupTests.ts.  I'm not sure why this file is included in a production build.

**Comment by mtho11** [comment]
ESR version of Firefox is 60, so this is an issue that should get solved.

**Comment by josejulio** [comment]
Maybe this would help? https://github.com/webcomponents/polyfills/tree/master/packages/custom-elements

**Comment by josejulio** [comment]
> It is used only in setupTests.ts

In the generated code is used elsewhere, maybe by libs?

```js
m=void 0!==window.customElements&&void 0!==window.customElements.polyfillWrapFlushCallback
```

```js
customElements.define("m-logo",function(e){function t(){return
```
etc

**Comment by josejulio** [comment]
I can see its usage in the dependency `rapidoc`
 
https://github.com/mrin9/RapiDoc/blob/master/src/rapidoc.js#L422
