### ISSUE TITLE
Get all health data for the graph on only one request

### ISSUE THREAD

**Issue by cfcosta** [kiali/kiali#1637]
Part of kiali/kiali#1623.

Every time that we do refresh on the graph, we do at least 5 HTTP requests, one for metrics, one for the nodes, and 3 for Health.

Those requests are done in parallel, but each take 40ms to reply (locally, OCP 3.11 with hack scripts), and joining them in just one request will make things faster. I did a small test that is really hard to show, but removing all 3 requests made the graph refresh close to 16ms faster, which is one "frame"/unit of time that you can wait.

In general, speed updates in JS run speed can only be done in increments of 16ms (or less if they do decide to stop forcing 60hz on the engine), so most small changes are not worth it.

Here's an example of the requests:

![](https://imgur.com/aEpYjAB.png)

**Comment by lucasponce** [comment]
Was this discussed in Saturn Scrum call as something to be added to Sprint 28 ?
cc @mwringe  

Also, I'd like to count with @jotak opinion on this work, as he was the original author of that logic, and any solution should be discussed first.

**Comment by jotak** [comment]
I see that the 3 health requests are for apps, services and workloads. I'm a bit surprised because, out of my head, I thought we would just query apps OR workloads OR services health depending on the type of graph being displayed. But maybe I'm forgetting something... need to look at the code.

**Comment by jotak** [comment]
@cfcosta @lucasponce I've no objection about this issue if it's granted that it provides better performances. Just I'd like to understand if the purpose is to group just the 3 health requests, or health+metrics, or everything ? As a reminder, having health (and eventually metrics) being loaded apart allows to dissociate graph backbone loading versus additional / decorating data, hence being able to visualize the graph even when health data isn't finished to fetch yet.

**Comment by lucasponce** [comment]
@jotak +1

**Comment by mwringe** [comment]
@lucasponce It was something that was discussed with @cfcosta We are looking to see if there are any performance improvements to how we generate the graph

**Comment by josejulio** [comment]
> @cfcosta @lucasponce I've no objection about this issue if it's granted that it provides better performances. Just I'd like to understand if the purpose is to group just the 3 health requests, or health+metrics, or everything ? As a reminder, having health (and eventually metrics) being loaded apart allows to dissociate graph backbone loading versus additional / decorating data, hence being able to visualize the graph even when health data isn't finished to fetch yet.

I understand that the purpose is to group only the health calls.

**Comment by josejulio** [comment]
After some research, the benefits of doing one call seems minimal compared to the problems.
In the 1 namespace scenario there is no benefit, when doing multiple namespaces the benefits starts showing up, but also the problems. Namespaces that take less time individually are not seen until all the namespaces finish the processing.

I'm closing this and in the future we can open other task if we want to revisit.
