### ISSUE TITLE
Support Keybindings on the Graph

### ISSUE THREAD

**Issue by cfcosta** [kiali/kiali#1638]
Currently there's no way to navigate, or at least interact with the graph in any ways using the keyboard.

Some keybindings would help for actions like:

- Zoom in/out
- Show/hide sidebar
- Show/hide toolbar
- focus namespace search
- toggle refresh

**Comment by lwrigh** [comment]
The dev console topology in Openshift features the keyboard shortcut information like this: 
<img width="1439" alt="Screen Shot 2020-03-06 at 11 29 56 AM" src="https://user-images.githubusercontent.com/20227374/76102478-116c4080-5f9e-11ea-8b38-e535fed0c33f.png">

We could consider doing something similar in Kiali.

**Comment by cfcosta** [comment]
Closing as it seems there is no interest on this feature.
