### ISSUE TITLE
[PF4] Migrate Message Center / NotificationDrawer

### ISSUE THREAD

**Issue by aljesusg** [kiali/kiali#1639]
Epic:
https://github.com/kiali/kiali/issues/1588

There is a PF4 Drawer but not the full component:

https://patternfly-react.surge.sh/patternfly-4/experimental/drawer/

**Comment by aljesusg** [comment]
Require : https://github.com/patternfly/patternfly-react/issues/2829
cc @jshaughn

**Comment by jshaughn** [comment]
I think the Kiali MessageCenter uses the PF3 NotificationDrawer, so migration may need a PF4 version of the same.

**Comment by jshaughn** [comment]
I'll at least temporarily look at this and see if there is any interim thing we can do to get away from PF3.

**Comment by mtho11** [comment]
Yeah, that looks to be our biggest blocker for getting rid of PF3.

**Comment by aljesusg** [comment]
As far as I know there are minor components to create the NotificationDrawer (Like we did with the filter), anyway Leslie told me that we can discuss this in the next meeting this wednesday
