### ISSUE TITLE
Problems reported in Jaeger integration for Istio 1.2.5

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1641]
Per discussion:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/kiali-users/9erUOM6WY1A/xxio_l5UAAAJ

It seems Jaeger config may need some revisit.

It seems that the step used for Kiali 1.0 that worked in Istio 1.1.9 have changed, so we need to revisit them.

Goal: To check/revisit if Kiali deploys correctly in minikube.

**Comment by aljesusg** [comment]
We can close this one
