### ISSUE TITLE
Response time is not shown for shadowed/mirrored services in graph

### ISSUE THREAD

**Issue by pavolloffay** [kiali/kiali#1649]
Response time is not shown for shadowed services in graph. It is pity because shadowed services are useful for new versions where we are not sure about performance characteristics. If I want to find out how the shadowed service behaves in term of response time I have to drill in into metrics dashboards.

Example: the response time for service reviews v3 is not shown. 

![Screenshot of Kiali  istio-system  (3)](https://user-images.githubusercontent.com/5618424/64532081-1c0c8c80-d311-11e9-8ea1-cd126f1dabab.png)

**Comment by jotak** [comment]
This is related to https://issues.jboss.org/browse/KIALI-2218?_sscc=t and https://github.com/istio/istio/issues/11093
At the moment considered here as an issue in Istio telemetry. However we could also do something in Kiali to select explicitly the reporter used to build the graph (or having the graph queries using both reporters: source & destination). I know we've already discussed this, but @jmazzitelli @jshaughn maybe we should consider that again?

**Comment by jshaughn** [comment]
@jotak With the promised addition of request service information in telemetry, I *think* we'll see source telemetry in the mirror-case, for all of the resulting requests.  I could be wrong, I'm going to ask explicitly in an upcoming P&T group meeting.

**Comment by abonas** [comment]
@jshaughn can we do something about that or this depends on some missing functionality in Istio and should be closed for now?

**Comment by jshaughn** [comment]
@abonas We can set to waiting external instead of future, but let's keep it open because when the feature becomes available we do want to look into this.

**Comment by jshaughn** [comment]
Closing as there is no upstream plan to flag mirrored requests.  If the feature becomes available we will open a new issue to leverage the information.
