### ISSUE TITLE
Make the links in about screen clickable

### ISSUE THREAD

**Issue by pavolloffay** [kiali/kiali#1652]
The links in the about screen are not clickable.

**Comment by abonas** [comment]
is this a regression?

**Comment by jotak** [comment]
@abonas I think this is about links to jaeger & grafana, not about Kiali website or social media, in which case it's not a regression

**Comment by pavolloffay** [comment]
I don't know if it is a regression or not. 

I am talking about these links:

![Screenshot of Kiali  istio-system  (4)](https://user-images.githubusercontent.com/5618424/64699530-3c6d5000-d4a5-11e9-951e-71e3e47c3385.png)
