### ISSUE TITLE
Add link to jaeger in distributed tracing screen and traces tab

### ISSUE THREAD

**Issue by pavolloffay** [kiali/kiali#1653]
Add view in Jaeger link to traces tab and distributed tracing screen.

The view in Jaeger link could be similar to "View in Grafana" link in the "Inbound Metrics".

**Comment by abonas** [comment]
Can you elaborate a bit more on why this is needed? 
I'm not sure I understand why a link to Jaeger is needed from an embedded Jaeger UI. Isn't this very similar?
Grafana is different from Kiali metrics tab where it's linked from, so I'm not sure this is comparable.
cc @aljesusg

**Comment by aljesusg** [comment]
In fact, inside the integrate UI, there is a button to the jaeger UI external in the integration
![1_zjxQBtPM9np5SGXH5PVNfQ](https://user-images.githubusercontent.com/3019213/64599673-1b7c0080-d3ba-11e9-9b26-94aa95c11117.png)

**Comment by lucasponce** [comment]
I wanted to comment similar as @aljesusg that there is already an integration to open Jaeger in a separate tab if the user wants more details.

In mid term, one of the areas to improve (we have commented in several times) is the opposite movement. I mean, Kiali should provide more "correlation" use cases with tracing info.

This use case was very primitive (just an iFrame where Kiali provide the higher level controls), but the plan is not to stop on it, but process this info in a meaningful way.

So I personally think that the link provided by Jaeger perhaps is enough for now.

**Comment by pavolloffay** [comment]
I could not find that button. Maybe we could do better and make it more visible and/or consistent with other links in the UI. Feel free to close, I felt like I can share my thoughts that It wasn't intuitive to navigate to full Jaeger UI from the Traces tab.

> Can you elaborate a bit more on why this is needed?

The embedded mode provides all the search capabilities as jaeger for a _single service_. However the layout is different and most importantly I could not change the service - which was needed in my case to do full root-case analysis.  

> In mid term, one of the areas to improve (we have commented in several times) is the opposite movement. I mean, Kiali should provide more "correlation" use cases with tracing info.

> This use case was very primitive (just an iFrame where Kiali provide the higher level controls), but the plan is not to stop on it, but process this info in a meaningful way.

I more than agree, fixing the link is however very easy short term.

**Comment by lucasponce** [comment]
I put in the backlog as probably adding the link is something easy for short term, but in the mid term our goal would be to improve the integration with Jaeger and remove the iframe with a kiali component.

**Comment by lucasponce** [comment]
Kiali provides now a better integration with Jaeger where external links are better located.
