### ISSUE TITLE
Improve empty table in list views

### ISSUE THREAD

**Issue by aljesusg** [kiali/kiali#1674]
When we have not results in list it seems that the list is empty

Use this design 
https://pf4.patternfly.org/demos/Table/examples-full/?component=Table%20-%20empty%20state%20demo

**Comment by abonas** [comment]
the PF link in the description here above goes to 404
But regardless - is this issue still relevant?

**Comment by aljesusg** [comment]
Yes please, this to show some kind of message where there is not workloads, apps or services in lists,  I did it for details but not for lists.
