### ISSUE TITLE
Support custom CA anchors in Docker image

### ISSUE THREAD

**Issue by stevehipwell** [kiali/kiali#1675]
**Is your feature request related to a problem? Please describe.**
The current documented support for self-signed certificates involves supplying a certificate for each endpoint via the `ca_file` setting and modifying each HTTP request to use it. This method isn't currently supported by the Istio Helm chart.

**Describe the solution you'd like**
Provide a way to mount ca certificates into _/etc/pki/ca-trust/source/anchors_ and run `update-ca-trust` as part of the Kiali startup command. For the helm chart this could be in the form of an optional secret.

**Describe alternatives you've considered**
There is currently no way to achieve this with the Kiali Istio Helm chart.

**Additional context**
N/A

**Comment by lucasponce** [comment]
Adding @jmazzitelli and @gbaufake for feedback on this.

**Comment by lucasponce** [comment]
Ping @jmazzitelli @gbaufake ?

**Comment by abonas** [comment]
@jmazzitelli @jshaughn is there any feedback/update on this?

**Comment by jmazzitelli** [comment]
would need more research. currently not on the roadmap.

**Comment by stevehipwell** [comment]
@jmazzitelli it's been a while since I looked at this, but off the top of my head a simple approach would be to have an ENV variable in the _Docker_ image trigger a call to `update-ca-trust`. With this the _Helm_ chart could expose a `caCerts` value that expects the name of a secret and if provided binds the secret to a directory under _/etc/pki/ca-trust/source/_ and sets the ENV variable.

**Comment by lucasponce** [comment]
Closed by https://github.com/kiali/kiali/issues/4050
