### ISSUE TITLE
Add links to Grafana from Graph right-click menu

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#1677]
This is a follow-up of #1268

**Comment by lucasponce** [comment]
I guess that adding Jaeger to this issue makes sense for Spans.

**Comment by abonas** [comment]
I'd like to undestand this issue better:
1. For which entity types this should be available in right click menu?
2. The link to Grafana is an external link - correct?
3. the link to Jaeger - will it be external to Jaeger UI or internal to the new tracing component @aljesusg has built?

**Comment by jotak** [comment]
So, about links to Jaeger, I don't remember exactly what I had in mind when I wrote this up, the links currently exist, maybe they didn't at that time. So we can consider it done. (To answer the question, links can be either internal or external depending on Jaeger config in Kiali - but again, there's nothing more to do here).

For Grafana, the idea was about external links to user-defined grafana dashboard, since we can define custom links to grafana dashboards in our dashboards CRD. But to be honest, to this date I haven't heard about anyone customizing a runtime dashboard, so I don't think it's worth it to do. I think we can close the issue - if later on we get more people paying attention to runtime monitoring then maybe we will reconsider. ok?

**Comment by aljesusg** [comment]
from jaeger @jotak @abonas now if you set the integration the link redirect you to the traces tab. If not it will be an external link.

**Comment by jshaughn** [comment]
Adding Future label and closing, based on comments of @jotak and @aljesusg.  Also updated title to reflect that Jaeger part was completed.

**Comment by abonas** [comment]
@jotak if you think it can be closed for now, please close
