### ISSUE TITLE
Config list warning icon too transparent

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#1686]
![Screenshot from 2019-09-18 09-03-47](https://user-images.githubusercontent.com/604313/65130732-4d1a4a80-d9fe-11e9-8f86-379f2572b5f3.png)

**Comment by xeviknal** [comment]
This is fixed in here: https://github.com/kiali/kiali-ui/pull/1423
All the validations icons for those popovers are migrated to PF4 system.
