### ISSUE TITLE
access to external grafana url is set correctly

### ISSUE THREAD

**Issue by guangbochen** [kiali/kiali#1692]
**Describe the bug**
1. set an external Grafana service url like "https://grafana.myorg.com/proxy/"
2. click `view in Grafana` in the kialia UI and it will generate the combination URL e.g., like 
`https://grafana.myorg.com/proxyd/UbsSZTDik/istio-workload-dashboard?var-namespace=cattle-prometheus&var-workload=exporter-kube-state-cluster-monitoring`

3. the generated URL is incorrect since `proxyd` should be `proxy/d`, it should append `/` at the end of my custom Grafana URL.

For UI issues please also add a screenshot that shows the issue.

**Versions used**
Kiali: v1.4.2
Istio: 1.3.0
Kubernetes flavour and version: (e.g. OpenShift Origin 3.9)

**Expected behavior**
the external Grafana url should keep `/` if is set by the user.

**Comment by jotak** [comment]
Hi @guangbochen 
Thanks for reporting this.
Do you mean that in spite of having a trailing `\` in your configured URL, Kiali is removing it hence generate a wrong URL?
It's a bit weird (and I'm surprised it works for me then), but I'm going to check.

**Comment by jotak** [comment]
@guangbochen the URL is built from Grafana URL + path to the dashboard.
As far as I've seen, the Grafana API returns absolute path to dashboards prefixed with `/`. So in Kiali, we remove the trailing slash of the URL (if any) then concatenate the dashboard path, e.g. `http://my-grafana` + `/d/xyz/my-dashboard`.

Now, maybe you have a different version or different settings with Grafana, and the API does not return paths formatted as expected in Kiali? To check that, can you check what is returned from there: `http://<grafana_server>/api/search?query=Istio` ? You should get a json array similar to that:

```
[{"id":1,"uid":"tLFBF65Wz","title":"istio","uri":"db/istio","url":"/dashboards/f/tLFBF65Wz/istio","slug":"","type":"dash-folder","tags":[],"isStarred":false},{"id":9,"uid":"zMVw2ecZk","title":"Istio App Dashboard","uri":"db/istio-app-dashboard","url":"/d/zMVw2ecZk/istio-app-dashboard","slug":"","type":"dash-db","tags":[],"isStarred":false,"folderId":1,"folderUid":"tLFBF65Wz","folderTitle":"istio","folderUrl":"/dashboards/f/tLFBF65Wz/istio"}] (etc)
```

Can you check in particular if the URL field doesn't start with `/` ?

Anyway I'll do a patch to manage both cases, with or without leading slash.

**Comment by guangbochen** [comment]
yes, Kiali will auto removing the trailing `/` and my `http://<grafana_server>/api/search?query=Istio` url didn't start with `/`, not sure Grafana v6.3.5 has made changes on its API format but would love to see a patch for both cases, thanks
```

{
id: 11,
uid: "tf8_X4tZz",
title: "istio",
uri: "db/istio",
url: "dashboards/f/tf8_X4tZz/istio",
slug: "",
type: "dash-folder",
tags: [ ],
isStarred: false
},
```

**Comment by jotak** [comment]
@guangbochen the PR is on its way
BTW I'm using Grafana 6.1.6 so maybe it's a difference with the newer version, however Grafana's doc still mentions a leading slash here, so it might be a bug in Grafana. Anyway Kiali will now be more flexible about that.
