### ISSUE TITLE
VS SingleHostChecker is not marking "*" as invalid if it's duplicate

### ISSUE THREAD

**Issue by burmanm** [kiali/kiali#1693]
**Describe the bug**

When duplicate VirtualHosts are found by SingleHostChecker, VS with "*" as host are not marked with validation warning even if they could be the real reason for duplicates. Only the other hosts are marked.

Since it's a warning, both hosts should be marked since we don't know which one is the correct one.

**To Reproduce**

```go
func TestWildcardisMarkedInvalid(t *testing.T) {
	vss := []kubernetes.IstioObject{
		buildVirtualService("virtual-1", "*"),
		buildVirtualService("virtual-2", "reviews"),
	}
	validations := SingleHostChecker{
		Namespace:       "bookinfo",
		VirtualServices: vss,
	}.Check()

	presentValidationTest(t, validations, "virtual-1")
	presentValidationTest(t, validations, "virtual-2")
}
```

**Expected behavior**

All affected VS are marked with validation warning.

**Comment by xeviknal** [comment]
Closing the issue because the fix is already in master (per https://github.com/kiali/kiali/pull/1551/commits/9eaadb41ae556ac6169bee6f3e70e1d3cb37c8f1)
