### ISSUE TITLE
Kiali.io link to maistra docs is not working

### ISSUE THREAD

**Issue by aljesusg** [kiali/kiali#1697]
In https://www.kiali.io/documentation/getting-started/
Step **Install Kiali via Istio or Maistra**

> To install Kiali as part of the Istio installation just follow the Istio Setup docs. If you are running on OpenShift and prefer Maistra, see **Maistra Setup docs**. You may then continue to Open the UI.

Maistra Setup docs => https://maistra.io/docs/getting_started/install/

Give a 404

The link should be https://maistra.io/docs/installation/

**Comment by josejulio** [comment]
The link should point to: https://maistra.io/docs/installation/
