### ISSUE TITLE
Logs pollution tls.go

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#1698]
My Kiali logs are full of the same following message:
`1 tls.go:56] GetMeshPolicies failed during a TLS validation. Probably Kiali doesn't have cluster permissions. Error: meshpolicies.authentication.istio.io is forbidden: User "system:serviceaccount:istio-system:kiali-service-account" cannot list meshpolicies.authentication.istio.io at the cluster scope: no RBAC policy matched`

We should avoid logging it again and again. Maybe just log it once then set a flag to not log it again?

Or even better: have a flag to disable permanently this periodic check, and that would be set by the operator when Kiali has no cluster permissions ?

**Comment by jotak** [comment]
WDYT @xeviknal @jmazzitelli ? Is that something the operator could do? Or already does? (to let Kiali knows if it has cluster permissions)

**Comment by lucasponce** [comment]
For the cluster objects, if we can get with a flag (from the operator) that service-account / user doesn't have permissions, that would save to make that query.

Perhaps the operator can add a flag in config and we can use this.

**Comment by xeviknal** [comment]
I think this could be useful. Knowing that, we could avoid printing that log all the time and print it only at one point.

**Comment by jshaughn** [comment]
assigning to @jmazzitelli for eval/fix/comment/close etc...

**Comment by jmazzitelli** [comment]
The operator can determine if kiali operator has certain permissions. It does something like this here:

https://github.com/kiali/kiali/blob/v1.8/operator/roles/kiali-deploy/tasks/main.yml#L304-L313

It can do something similar like this after it installs the roles, but before it installs the kiali deployment, if it wants to know the permissions it is giving kiali

**Comment by jshaughn** [comment]
Perhaps we can just do a poor-man's check here.   Add to config.go:

```
// HasClusterRole returns true if Kiali is assigned cluster role (by looking for accessible_namespaces **)
func HasClusterRole() {
	return configuration.Deployment.Namespace == "**"
}

```

Seems good enough for avoiding this check.  We could investigate an actual RBAC check if this is too weak.

**Comment by jmazzitelli** [comment]
I think what @jshaughn and @lucasponce said is the way to go - accessible namespaces = "**" is effectively the flag that we can look at. If that value is "**" then the operator gives kiali cluster roles - if it is not ** then kiali is not given cluster roles.
