### ISSUE TITLE
[PF4] Find alternative to current tooltips in charts

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#1702]
As explained here [ https://github.com/kiali/kiali-ui/pull/1354#issue-305602293 ] the current tooltip we have with victory charts have some drawbacks, being cut off on borders & charts having big padding as a kind-of workaround.

As a result, tooltips were disabled in Overview charts (because huge padding on tiny charts doesn't work well) and also cause issues for migrating side-panel charts ( https://github.com/kiali/kiali/issues/1608 ).

Potential alternative to investigate & implement in victory charts:
- Fixed-position tooltip?
- Snap-on-borders mechanism?

Also, check victory charts to make sure this hasn't already been fixed internally.

Epic: https://github.com/kiali/kiali/issues/1588

**Comment by jotak** [comment]
Good news: a new flag in `VictoryTooltip` allows to do exactly what we needed: `constrainToVisibleArea`. pf-charts is not already up-to-date with that property, but we can still use the underlying victory component here.

I'll do a patch in k-charted and pave the road in overview sparklines so that it can be used in side-panel as well.

**Comment by jshaughn** [comment]
Nice!
