### ISSUE TITLE
[PF4] Migrate the MessageCenter to PF4

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#1707]
**Is your feature request related to a problem? Please describe.**
Migrate the MessageCenter to PF4

Epic:
https://github.com/kiali/kiali/issues/1588

**Comment by aljesusg** [comment]
There is an issue for this [PF4] Migrate NotificationDrawer https://github.com/kiali/kiali/issues/1639

**Comment by mtho11** [comment]
Ah ok @aljesusg. I'll close this one then as a duplicate
