### ISSUE TITLE
[UI] Configuration column title not aligned with its values

### ISSUE THREAD

**Issue by xeviknal** [kiali/kiali#1710]
**General remarks**

Configuration column (and possibly all lasts columns) in List pages are not aligned with its values.

![](https://user-images.githubusercontent.com/604313/65325658-c0af8980-dbaf-11e9-86a5-858839dfa9fb.png)

![](https://user-images.githubusercontent.com/604313/65325659-c0af8980-dbaf-11e9-96fb-7b511e9cff31.png)

Bug found in https://github.com/kiali/kiali-ui/pull/1423
Behavior found in Firefox.

**Expected behavior**
All values for that columns should be better aligned with its title. At least, as it is in the other columns.

**Comment by hhovsepy** [comment]
Also, there are swallowed pixels in status icons.

**Comment by xeviknal** [comment]
@hhovsepy sorry, I can't see the pixels you mention in the screenshots. Could you please provide more info?

**Comment by hhovsepy** [comment]
For instance zoom this image and you could see that on the right side of each icon, there are a cut icons:
![65325659-c0af8980-dbaf-11e9-96fb-7b511e9cff31](https://user-images.githubusercontent.com/604313/65438419-beeefb80-de25-11e9-84fe-7c6ed650faca.png)

**Comment by jshaughn** [comment]
@cfcosta What are you planning to do here?  I'm not aware of anything we can do outside of what's previously been done, outside of PF4 solving the problem.

**Comment by cfcosta** [comment]
I'm literally taking screenshots to close this, could not replicate anywhere on Linux.
