### ISSUE TITLE
ServiceMeshApiDocumentation is returning 500

### ISSUE THREAD

**Issue by gbaufake** [kiali/kiali#1713]
**General remarks**

Installed Kiali and bookinfo queried the ServiceMeshApiDocumentation API with 
``api/namespaces/bookinfo/services/details/apispec``

Found by E2E #1712 

**Describe the bug**

It returned 500 instead of 200 with API description with ``error    "Internal error occurred: services \"details\" not found"``

**Versions used**
Kiali-ui: 1.6.0 (74a636489ef6b64d61a220cdd9215eb5851d6204)
Kiali: v1.6.0-SNAPSHOT (10aeec7358482f0d7a401d0c8bd5b9501e32b4a2)
Service Mesh: 1.0.0
Kubernetes flavour and version: Openshift 4.1

**To Reproduce**
1. Install Service Mesh, Kiali and Bookinfo
2. Query KIALI_URL/api/namespaces/bookinfo/services/details/apispec

**Expected behavior**
- Request should return 200.

**Comment by mwringe** [comment]
Are you sure you have the right URL here? I can't reproduce this problem.

I do get the error mentioned if I put a typo in the namespace name (eg 'api/namespaces/foo/services/details/apispec') or if I put a typo in the service name.

Even with the typos in the URL, we shouldn't be returning a 500 response but a 404

**Comment by gbaufake** [comment]
closed by #1769
