### ISSUE TITLE
[K-charted] Handle unit scaling when input already scaled

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#1715]
(This is an issue to be confirmed)
Related: https://github.com/kiali/kiali/pull/1711

I believe a unit in charts model set as "ms" for millisecond is going to be scaled as "kms" when x1000.

Solution: add a "scale" field in model that tells how it is already scaled in prometheus.
E.g. , instead of the current:

```
	{
		Chart: kmodel.Chart{
			Name:  "Request duration",
			Unit:  "ms",
 			Spans: 6,
		},
		refName: "request_duration_millis",
	},
```

we would have something like:

```
	{
		Chart: kmodel.Chart{
			Name:  "Request duration",
			Unit:  "seconds",
			Scale: 0.001,
 			Spans: 6,
		},
		refName: "request_duration_millis",
	},
```

**Comment by jotak** [comment]
cc @jshaughn

**Comment by jshaughn** [comment]
What I don't understand is the x1000 comment, because the numbers in prom are in ms, and it is passed to k-charted in ms, so where is the manual scaling coming into play?  In my local tests of the charts for https://github.com/kiali/kiali/pull/1711, the chart looked good to me.

**Comment by jotak** [comment]
But @jshaughn in your tests did you had some high response times, like over a second? That's the scenario where I think we will see this bug.
