### ISSUE TITLE
Use Patternfly mountOnEnter and unmountOnExit for Tabs

### ISSUE THREAD

**Issue by xeviknal** [kiali/kiali#1716]
Tabs in PF3 had a feature to mount and unmount the dom within each tab using the  mountOnEnter and unmountOnExit properties.

These properties right above weren't part of the new Tab components. https://github.com/patternfly/patternfly-react/pull/2902/files asked for the implementation of it.
Now, this issue is resolved. We should use those field in order to light down the logics of all the components using it.

Here we have to manage the currentTab in order to avoid rendering Tabs that are not open:
[Source Code](https://github.com/kiali/kiali-ui/blob/cea19d8d78059fc8f68320013e751670540fffed/src/pages/ServiceDetails/ServiceDetailsPage.tsx#L339)

The change should be quick. Mostly removing code.

Also this issue needs PF4 to release that new feature.

**Comment by mtho11** [comment]
So it looks like we need to upgrade PF4 versions to address this issue.

**Comment by mtho11** [comment]
If we don't address this we are loading all the components in all the tabs (even if those tabs were clicked on).

**Comment by jotak** [comment]
@mtho11 if i remember correctly there's a workaround implemented to avoid loading all the tabs. And this task is to remove the workaround once PF is upgraded.

Have you spotted some places where tabs are loaded even when they're not displayed?

**Comment by mtho11** [comment]
@jotak, If we upgrade, we don't need the workaround. Which is just creating technical debt which will need to be undone quite soon.
