### ISSUE TITLE
Workload page crashes - PV pod

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#1718]
Create this PVC:
`apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi`

And this pod:
`apiVersion: v1
kind: Pod
metadata:
  name: task-pv-pod
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: task-pv-claim
  containers:
    - name: task-pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: task-pv-storage`

Open Workload details page for created 'task-pv-pod'.
Page crashes: "Sorry, there was a problem. Try a refresh or navigate to a different page."
No Error in Kiali log.

**Comment by hhovsepy** [comment]
Pod in OC side:
![Screenshot from 2019-09-24 13-21-37](https://user-images.githubusercontent.com/604313/65507455-42fcbe00-dece-11e9-96eb-94c3dfceb0ea.png)

**Comment by lucasponce** [comment]
Ok, I can easily reproduce this in an old OS 3.11 platform.
So, I'm going to prepare a fix.

**Comment by hhovsepy** [comment]
Verified on Kiali 1.0.6 production bits.
