### ISSUE TITLE
Move HealthIndicator to MockUp UX

### ISSUE THREAD

**Issue by aljesusg** [kiali/kiali#1720]
Workload MockUp: https://marvelapp.com/i9h9g7j/screen/59315434
Service MockUp: https://marvelapp.com/i9h9g7j/screen/59315432

**Comment by xeviknal** [comment]
Assigning this. Prefer to migrate first the whole Workload page and wait for the service page to be migrated also.

**Comment by jotak** [comment]
I have some concerns about this flat display of the health. Health is designed as a hierarchical component with items and potentially sub-items. Currently the display matches the technical structure, but the mockup here doesn't seem aligned with the technical structure.

**Comment by jotak** [comment]
@aljesusg @lucasponce @xeviknal I'd like to do the pf4 migration of the health component but without changing the design at the moment, related to my comment above. So this task could be moved out of the PF4 migration epic and we can move on faster. WDYT?

**Comment by aljesusg** [comment]
I think that you can use this issue to move the component to PF4 and after we can talk with UX about the design, I think that they don't know all the use cases for this component and maybe they'll redo the design

**Comment by jotak** [comment]
@aljesusg , the PR has been merged, I think we can rename this ticket to keep track of UX mockup task but without PF4 migration mentioned

**Comment by israel-hdez** [comment]
Related design issue is: https://github.com/kiali/kiali-design/issues/131

**Comment by israel-hdez** [comment]
I'll discuss this with UXD at Nov 12th meeting.
Assigning `p2` priority, because this issue seems to be out of the scope of the sprint.

**Comment by serenamarie125** [comment]
This looks great! we have a few suggestions:
- change "Health" to "Overall Health"
- change "Pods Status" to "Pod Status"
- remove the colon after "Pods Status" & "Error Rate over last 5m"
- remove the icons from "Pods Status" & "Error Rate over last 5m".  Having an additional aggregation here causes alignment issues as well as is a bit overwhelming with so much visual information
