### ISSUE TITLE
REST API Error with namespaces/graph when using param injectServiceNodes=true

### ISSUE THREAD

**Issue by mattmahoneyrh** [kiali/kiali#1731]
The API call "namespaces/graph" when using param "injectServiceNodes=true" fails.

Error:
"Failed ID gen: namespace=[unknown] workload=[] app=[] version=[] service=[unknown] graphType=[versionedApp]"

Version tested:
Kiali-ui 1.6.0-edge (46a87e0bb20b5d33b21e179129a0e196661a8b08)
Kiali  latest (923bad14d4015e6a62abf916f698ced26babfce2)

**Comment by jshaughn** [comment]
This problem is introduced by recent work in the security_policy graph appender.  Until it is fixed the workaround is to uncheck the security display option.
