### ISSUE TITLE
Hide Expression Not Working

### ISSUE THREAD

**Issue by mattmahoneyrh** [kiali/kiali#1745]
Takes graph refresh to for Hide expression to completely work, in particular with Services

Ex:
1) Deploy bookinfo
2) Select Versioned app graph
3) Deselect Compress Hidden
4) Enter 'service=reviews' for Hide expression
    Note: Service 'reviews' still showing
![Selection_089](https://user-images.githubusercontent.com/7262987/65912083-9f168500-e39b-11e9-8088-7cb046d791db.jpg)

 5) Now click graph refresh button.
    Note: Service 'reviews' no longer showing, as expected
![Selection_091](https://user-images.githubusercontent.com/7262987/65912146-b8b7cc80-e39b-11e9-836a-f31e03afcd9a.jpg)

**Comment by mtho11** [comment]
@jshaughn I can take this one since I'm working on that component right now anyway?

**Comment by jshaughn** [comment]
I think it's independent of the PF4 work, or the non-PF4  refactoring you're doing (how is that going?).  I think I know what the issue is, so let me take a look.  I don't think it will conflict with anything you're doing.

**Comment by jshaughn** [comment]
After looking at this a bit I wonder if it's a cy bug wrt nodes with a visible parent, because I can't really see a reason for the node to stay, and I'm fairly sure this used to work.  Need to maybe work backwards and see if this is a regression and when it started.

**Comment by jshaughn** [comment]
OK, this was working in prior versions some investigation shows it started after the work for kiali-3240, which  now causes us to re-run the layout. After looking with Josejulio we think it's a side-effect of having to run our special layout code for group boxes.  Will look more into it...
