### ISSUE TITLE
Delete 3scale handler - Rule is still references in Service

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#1748]
Go to Service Details.
Click on Actions -> Create 3scale API Management Rule.
Create a Handler and Create the Rule.
Click Actions -> Update 3scale API Management Rule.
Delete the selected only Handler.
Cancel the wizard.

It does not refresh the Service Details page, so the Rule is still there linked. "Service linked with 3scale API Handler ...."
But it should mark the changes and refresh Service details page, like is happening when submitting the wizard.

**Comment by hhovsepy** [comment]
![Screenshot from 2019-10-01 13-08-33](https://user-images.githubusercontent.com/604313/65957760-fd03a500-e44d-11e9-86c8-9ddff3d8d0c6.png)

**Comment by hhovsepy** [comment]
When the Service details page is refreshed, then the deleted Rule is not shown anymore.

**Comment by lucasponce** [comment]
Ok, it seems Service Details page should refresh when Wizard is canceled, for some reason in this case something is missing.

**Comment by lucasponce** [comment]
Also I confirm that the Link note is broken after the Pf4 review.
I'll fix it on this work as well.
