### ISSUE TITLE
Add Graph Context menu to Graph Tour Help

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#1750]
**Is your feature request related to a problem? Please describe.**
It is not straightforward to know that a right-click on the graph pops up a context menu with further options. _Usually, the right click is reserved for the browser context menu._

**Describe the solution you'd like**
To highlight this capability, we should add this context menu capability to the graph help tour.

Design Issue: https://github.com/kiali/kiali-design/issues/144

**Comment by jshaughn** [comment]
It won't actually be easy to show an expanded right-click as part of the tour.  Just getting the tour to land on the graph itself is a bit of guesswork.  But we can enhance the text of the graph tour stop, it currently does not even mention the context menu.

**Comment by mtho11** [comment]
@jshaughn I couldn't figure out how to easily add the right-click context menu to the tour either. And maybe some explicit documentation wrt context menu would also help.
