### ISSUE TITLE
[RFE] kiali ui uses overlapping colors that make determining status difficult

### ISSUE THREAD

**Issue by thoraxe** [kiali/kiali#1754]
**Is your feature request related to a problem? Please describe.**
When observing the Kiali UI, if a service is experiencing HTTP errors (eg: 5xx), the colored statuses are confusing. Currently we use the same colors for both the error codes (4xx = orange, 5xx = red) and the % of requests with errors (red >= 20%).

This results in a node border and/or a line connecting services being the color red (>20% error) when the actual status code is orange (403 forbidden).

**Describe the solution you'd like**
Use different colors to represent one of the two (% requests errored, http status)

**Describe alternatives you've considered**
Color blindness is probably an issue, but using different shades of a different color family (eg: blue) for the HTTP status might work better than overlapping green/orange/red between the two types of indications.

**Comment by mtho11** [comment]
@thoraxe I have added this to the https://github.com/kiali/kiali-design where the @kiali/ux-reviewers are.

**Comment by jotak** [comment]
@jshaughn if I understand correctly, it's more specifically about this chart:

![_](https://user-images.githubusercontent.com/2153442/66934112-46511880-f03a-11e9-984b-d95c3132ad82.png)

Which uses different color codes than in other places, especially there's an overlap between 4xx defined here (orange) and degraded health.

**Comment by jshaughn** [comment]
@jotak I think he is talking about edges and nodes but this chart also comes into play.  I think here we should 1) change to use the PF4 colors for success(OK)/danger(5xx) but probably also change 4xx from warning to a different shade of red.  What do you think?

**Comment by jotak** [comment]
Well, that would be nice... except for accessibility / color blindness :-(

**Comment by jshaughn** [comment]
good point.  I may try it anyway, both 4xx and 5xx are errors and should reflect it in some way.

**Comment by jshaughn** [comment]
PR https://github.com/kiali/kiali/issues/1760 is in review and likely to be merged.  It contains a change in color (dark red (pf color danger-200)) for the 4xx chart value.  It also makes more consistent color and terminology; the legend mentions the edge colors as representing Danger/Warn/Success to help avoid an interpretation tied to response code values.

Feel free to review/comment on the PR.

**Comment by jshaughn** [comment]
PR https://github.com/kiali/kiali/issues/1760 has been merged and I think addresses this issue, at least to some extent.  @thoraxe , can this be closed?
