### ISSUE TITLE
kiosk mode is not working

### ISSUE THREAD

**Issue by dugouchet** [kiali/kiali#1758]
**General remarks**
![image](https://user-images.githubusercontent.com/23668183/66133641-4ba07300-e5f7-11e9-86e3-8b0440824b6c.png)

**Describe the bug**
kiali version : v1.4.0

I add the parameter &kiosk=true and the kiosk mode is not activated

For UI issues please also add a screenshot that shows the issue.

**Versions used**
Kiali: v1.4.0
Istio:1.2.5

**To Reproduce**
1. Go to 'https://********/console/overview?pi=15000&duration=60&kiosk=true'
4. See it changes nothing

**Expected behavior**

**Comment by dugouchet** [comment]
related PR of the feature : https://github.com/kiali/kiali-ui/pull/812#issuecomment-521676681

**Comment by israel-hdez** [comment]
Hi @dugouchet 

Thanks for reporting the issue. I'm fixing in PR https://github.com/kiali/kiali-ui/pull/1470.
Although Kiosk mode will work again, I'm seeing some general sizing issues which happen both in kiosk and normal mode. I'll open a new ticket with the sizing issues I'm seeing, but it's OK of you report other issues you find in Kiosk mode.
