### ISSUE TITLE
confusing menus - two "Names" - one grey, one white

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#1762]
![image](https://user-images.githubusercontent.com/2029470/66149148-77642e80-e5e0-11e9-812f-440f4fed0991.png)

This is confusing because there are two "Name" drop down menus. One is grey, one is white. There is no other identification on these so a user will be confused.

**Comment by jmazzitelli** [comment]
I think the answer for this would be some tool tips to show up when you hover to help explain further what these drop downs are for.

**Comment by mtho11** [comment]
@jmazzitelli should this be a kiali-design issue?

**Comment by jshaughn** [comment]
I don't really find it confusing.  The first one is clearly a filter and second one is clearly for sort (to me).  My only issue here is that the filter list has "Health" (which is good) and the sort list has "Status" (which is bad).  Both lists should be the same and include "Health".

**Comment by jmazzitelli** [comment]
It isn't clear to me. I've not been in the UI much lately - I saw two names, one grey and one white, and I immediately wondered if something was off.

You can close this and/or move it to kiali-design - whatever is appropriate. I thought we were putting issues all under kiali with the new way we have to report things.

**Comment by jshaughn** [comment]
@serenamarie125 Any comment on this one?

**Comment by abonas** [comment]
please add this to next UX meeting agenda

**Comment by lucasponce** [comment]
All,

Please, let's try to sync here.
If this is is a bug or a feature request, let's keep an issue.

It it's not and it's a issue where UX team should need to review, please, open a kiali-design issue.

We have an agreement with @serenamarie125 to try to start discussions on github, to not wait to a UX meeting just to open a topic. That will make things move smoothly and we can use meetings for followup topics.

Thanks.

**Comment by jmazzitelli** [comment]
Everyone is telling me this is either (a) in the wrong place or (b) it isn't confusing and is expected.

So I'm closing.
