### ISSUE TITLE
Graph Cola Layout Error "InternalError: "too much recursion""

### ISSUE THREAD

**Issue by mattmahoneyrh** [kiali/kiali#1764]
The below error happens consistently when selecting the graph Cola layout, with Firefox 69:

Kiali-ui: 1.7.0-edge (6bf6238783a5afe4dda2751b32ae47a82d42d934)
Kiali:  latest (0cc8ef64779ce4326d0e07ae88fc89adb315e79c)

Kiali Console Error:
 "There was an error when rendering the graph: too much recursion, please try a different layout"

**Comment by jmazzitelli** [comment]
I saw that today, too - with Google Chrome.
