### ISSUE TITLE
MonitoringDashboards: allow to display several metrics per chart

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#1778]
I wanted to avoid that at the beginning to keep things as simple as possible, but in some cases it really makes sense, like with Envoy metrics about "healthy vs total" members ; the two of them should likely go in a single chart.

The bad part is that it's probably going to be a breaking change in the dashboards CRD.

**Comment by lucasponce** [comment]
Hey @jotak 
Perhaps we can use this feature to test how multiple versions works.
I mean if we have MonitoringDashboard v1 and v2 (with this new change) probably we can make this compatible and only apply the feature if the CR is being created from a v1.

Or perhaps we can just to move to migrate all v1 -> v2 with something automatic (I guess with the design we have, probably it can be done automatically, I don't know).

**Comment by jotak** [comment]
@lucasponce Yes I think we'll be able to automatically build v2 objects out of v1 definitions. Good point to keep in mind while implementing this.

**Comment by jotak** [comment]
I'm thinking about prioritizing this one. It would also help for better dashboards in the production-scale scenario: https://github.com/kiali/kiali/issues/2518
