### ISSUE TITLE
Insufficient Permissions for kiali-service-account

### ISSUE THREAD

**Issue by OchiengEd** [kiali/kiali#1779]
**Describe the bug**

There are permission issues affecting Kiali. Specifically, the `kiali-service-account` does not have the proper roles to list `meshpolicies` and `namespaces`(see [1] below).

[1]
```
$ kubectl get po kiali-6d84cbc478-v8xs6 -o json | jq .spec.serviceAccount
"kiali-service-account"
$ kubectl logs kiali-6d84cbc478-v8xs6 -c kiali | tail -n 2
W1009 13:47:27.589202       1 tls.go:56] GetMeshPolicies failed during a TLS validation. Probably Kiali doesn't have cluster permissions. Error: meshpolicies.authentication.istio.io is forbidden: User "system:serviceaccount:default:kiali-service-account" cannot list resource "meshpolicies" in API group "authentication.istio.io" at the cluster scope
W1009 13:47:42.590305       1 tls.go:56] GetMeshPolicies failed during a TLS validation. Probably Kiali doesn't have cluster permissions. Error: meshpolicies.authentication.istio.io is forbidden: User "system:serviceaccount:default:kiali-service-account" cannot list resource "meshpolicies" in API group "authentication.istio.io" at the cluster scope
$
```
In addition, the console shows the errors[2] below in the message center:

[2]
```
Error fetching Mesh-wide mTLS status.
21 in 6 minutes
10/9/20198:37:26 AM

Could not fetch namespace list:
21 in 6 minutes
10/9/20198:37:26 AM
```

For UI issues please also add a screenshot that shows the issue.

![errors](https://user-images.githubusercontent.com/348078/66487614-3d78a980-ea72-11e9-8bd2-cf6e240e8d34.png)

**Versions used**
Kiali: 1.6.1
Istio: 1.1.2
Kubernetes flavour and version: Upstream Kubernetes v1.16.1

**To Reproduce**
1. Login into Kiali
2. The error will pop in the right side of the screen with with the error.
3. Click on the bell icon on the right for more verbose details on the errors

**Expected behavior**

- Kiali should be able to pull `meshpolicies` without returning permission errors.

**Comment by jmazzitelli** [comment]
@lucasponce would you like to take this one :)

**Comment by jmazzitelli** [comment]
related:

https://github.com/kiali/kiali/issues/1337
https://github.com/kiali/kiali/pull/1352
https://github.com/kiali/kiali/pull/1187

**Comment by OchiengEd** [comment]
When kiali is deployed by the kiali operator, the proper roles are not given to the `kiali-service-account`. A look at the Operator CSV shows the `kiali-operator` service account is given the roles that should belong to the kiali service account[1].

Roles defined in the operator CSV should be long to the operator and should not be what is required by the operand, in this case Kiali. Unless the operator and operand are intended to use the same service account which could potentially cause some security concerns/complexities.

[1]
https://github.com/operator-framework/community-operators/blob/master/upstream-community-operators/kiali/kiali.v1.4.2.clusterserviceversion.yaml#L388-L554

**Comment by lucasponce** [comment]
@OchiengEd @jmazzitelli is it possible there is a problem with the operator, or how versions are defined with the operator ?

The permission required showed in the log are in the operator 1.6.1 (or it should unless I missed something):
https://github.com/kiali/kiali/blob/v1.6.1/operator/roles/kiali-deploy/templates/kubernetes/role-viewer.yaml#L105

Like it sounds something is mistmatched here.

@OchiengEd if you try to remove the operator an install it again, do you resolve the issue ?

**Comment by OchiengEd** [comment]
@lucasponce Boom! That is it. There's the problem. The `meshpolicies` should be created as a `ClusterRole` as opposed to a `Role`[1]. 

[1]
```
$ kubectl get roles kiali-viewer -o json | jq .rules[6]
{
  "apiGroups": [
    "authentication.istio.io"
  ],
  "resources": [
    "meshpolicies",
    "policies"
  ],
  "verbs": [
    "get",
    "list",
    "watch"
  ]
}
```

During my testing, I was able to eliminate the permission errors by creating the clusterrole in [2] below and assigning it to the `kiali-service-account`.

[2]
```
$ cat kube/kiali-custom-roles.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: kiali-custom-roles
rules:
- apiGroups:
  - authentication.istio.io
  resources:
  - meshpolicies
  verbs:
  - get
  - list
  - watch
```

**Comment by jmazzitelli** [comment]
@lucasponce I thought we had code in the kiali server that checks this whole "cluster role" vs. "role" thing - I thought we just log a info msg somewhere when this happens (which happens when installing with accessible_namespaces not **). I haven't followed this whole 'meshpolicies' issue - but I know it keeps coming up.

FYI: We want to maintain a configuration scenario which does NOT require Kiali to have any clusterroles. There are use cases/users who do not want Kiali given full cluster access to things (think: soft multitenancy scenarios). So we are avoiding assigning any cluster roles to kiail for certain install scenarios (and setting accessible_namespaces to something other than `**` in the Kiali CR is how to get that scenario).

**Comment by lucasponce** [comment]
I'll try to reproduce.
The code is prepared to work with no cluster permissions.

The warning messages were normal but the UI shouldn't receive any error, so probably there is anything else related.

Also, the combination of Kiali: 1.6.1 and Istio: 1.1.2 probably is affecting here as well, and I think we have tested kiali and kiali operator this with Istio 1.2 onward, so @jmazzitelli don't discard that operator needs some changes if we want to work for any Istio version.
