### ISSUE TITLE
Filter by Istio Sidecar second time overrides itself

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#1780]
List Workloads. (or any other objects)
Filter by Istio Sidecar: "Present".
Now apply filter Istio Sidecar: "Not Present".
It will override the "Present" value by "Not Present" one.

Is this the expected behaviour?

**Comment by aljesusg** [comment]
I think that we talked about that because it's not make sense to filter by present and not present

**Comment by hhovsepy** [comment]
Right, from UX perspective it does not make sense.
Closing this issue.
