### ISSUE TITLE
Security scan issues/CVEs in images

### ISSUE THREAD

**Issue by kramvan1** [kiali/kiali#1781]
**General remarks**

**Describe the bug**

Security scan shows many issues, they don't seem to be getting resolved, why curious about policy for fixing those.

https://quay.io/repository/kiali/kiali?tag=v1.4&tab=tags

**Versions used**
Kiali:   >1.4
Istio:  n/a
Kubernetes flavour and version:  n/a

**To Reproduce**

**Expected behavior**

CVEs are fixed at some point, or at least doc why not.

**Comment by lucasponce** [comment]
Thanks @kramvan1 I guess most of vulnerabilities just depends on the base image used which probably needs to be reviewed.

**Comment by kramvan1** [comment]
@lucasponce yup, usually a base package update during the build does the trick.
