### ISSUE TITLE
Having issue in finding Jaeger Traces in Kiali

### ISSUE THREAD

**Issue by hatimkapadia2030** [kiali/kiali#1785]
Hello,
My Kiali is integrated with Jaeger, but when I search for traces related to a service it comes up as empty. I can find the traces for same service in Jaeger's UI though.

The issue seems to be with how Kiali searches for the trace. Below is the URL from Kiali
`http://X.X.X.X:32701/kiali/console/jaeger?namespaces=istio-system&start=1570777451028000&end=1570781051028000&limit=20&lookback=3600&maxDuration=&minDuration=&**service=istio-ingressgateway.istio-system**
`
And below is URL from JaegerUI for same service
`http://X.X.X.X:32704/search?end=1570715516395000&limit=20&lookback=2h&maxDuration&minDuration&service=**istio-ingressgateway**&start=1570708316395000`

If I remove the namespace name **.istio-system** from Kiali's URL it works correctly. Is there a way I can disable namespace addition in Kiali when it is searching for traces?

Thanks,
Hatim Kapadia

**Comment by aljesusg** [comment]
Hi @hatimkapadia2030 . Which version are you using ? From Istio 1.1 istio-sidecar-injector add the namespace in the traces, See https://github.com/istio/istio/pull/11587/files#diff-de5983fcb0f040db64cf0281f3b152c0

**Comment by aljesusg** [comment]
mmm In version of Istio 1.3 you can see this injection https://github.com/istio/istio/blob/release-1.3/install/kubernetes/helm/istio/files/injection-template.yaml#L93-L97

Now we can't disable this in kiali because we are aligned to Istio. we should check why your environment is not injection the traces correctly. Is your service labelled correctly?

**Comment by hatimkapadia2030** [comment]
Hello,
I agree that Istio Side-Car does inject the pod namespace correctly. Since this is an action performed by the side car, any pod that runs without a side car is not capable of injecting the pod namespace.

Our application uses the OpenTracing Libs to create custom spans and when such are captured by Jaeger they are referenced only with the <app-svc-name> and not in the format <app-svc-name>.<pod-namespace>.
Since Kiali only accepts <app-svc-name>.<pod-namespace> it hinders our ability to view traces of pod running without a sidecar.

If Kiali gains the ability to search using any format <app-svc-name>.<pod-namespace> or <app-svc-name>, then it will allow non Istio traces to also be available.

**Comment by objectiser** [comment]
@hatimkapadia2030 Are you using the Jaeger client when creating the custom spans? If so, how do you currently set the service name?

**Comment by hatimkapadia2030** [comment]
Hello,
I will need to verify this with my product team. Will get back to you. 

Regards,
Hatim Kapadia

**Comment by aljesusg** [comment]
Hi @hatimkapadia2030 we are going to add a parameter in the configuration to add this:
Config file https://github.com/kiali/kiali/pull/1801/files#diff-3baf47c64847a8fb8aaa8cc2e088513bR82
Operator https://github.com/kiali/kiali/pull/1801/files#diff-f8f6c9abc6c5969045b61451c949e922

Created backend PR: https://github.com/kiali/kiali/pull/1801
Created PR UI: https://github.com/kiali/kiali-ui/pull/1486
