### ISSUE TITLE
[operator] implement validating webhook to validate Kiali CR

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#1789]
There is a new proposal for the ansible operator SDK to introduce validating webhook functionality. See: https://github.com/operator-framework/operator-sdk/pull/2048

We can use this feature - in fact, the Kiali team wrote up a github issue that was part of the reason why the ansible operator group has proposed this new feature. See: https://github.com/operator-framework/operator-sdk/issues/1658

The Kiali Operator should use this new webhook functionality. Read that issue https://github.com/operator-framework/operator-sdk/issues/1658 for details as to what we need it for.

**Comment by jmazzitelli** [comment]
Some doc that might help: https://github.com/operator-framework/operator-sdk/pull/2685/files#diff-651d535987cd0384b3afc86791443942d6e1bb69aaa6928dcf26b4cd379b29af

**Comment by lucasponce** [comment]
@jmazzitelli is this one ready from the operator SDK side ?

**Comment by jmazzitelli** [comment]
Last I spoke to the operator-sdk people, they said this was more difficult than at first thought. Unless we have a demand for this feature, I suggest we leave this as-is for "future".

**Comment by jshaughn** [comment]
Possibly useful but closing as part of routine backlog maintenance.  Can be re-opened as needed.
