### ISSUE TITLE
PF4: migrate namespace selection dropdown

### ISSUE THREAD

**Issue by jshaughn** [kiali/kiali#1790]
@aljesusg , I didn't see an issue for this bit, if I missed it I apologize.  @mtho11 , this is probably similar to the Display drop down you just completed...

**Comment by mtho11** [comment]
So this one could be fixed the same way as the Graph Display dropdown for a quick fix. But it looks like the correct way to address this is with the Context Selector: https://patternfly-react.surge.sh/patternfly-4/documentation/react/components/contextselector

**Comment by jshaughn** [comment]
@mtho11 Is there a multi-select contextSelector?  I don't see it.  Unless I'm missing something I think we should move forward with the analogous "Display" solution but +1 to this component if it makes sense in the future.

**Comment by mtho11** [comment]
@jshaughn as we confirmed with Serena today there is not one but they are looking into the mulit-select so I think it is safe to proceed with short term solution and migrate the current custom solution to PF4.

**Comment by aljesusg** [comment]
Migrated in https://github.com/kiali/kiali-ui/pull/1523
