### ISSUE TITLE
Move localtimes to another style

### ISSUE THREAD

**Issue by aljesusg** [kiali/kiali#1793]
Move from
![Screenshot from 2019-10-14 13-39-35](https://user-images.githubusercontent.com/3019213/66748731-38f42c80-ee88-11e9-8782-61b0fa12ce40.png)

to

![Screenshot from 2019-10-14 13-39-45](https://user-images.githubusercontent.com/3019213/66748730-38f42c80-ee88-11e9-81a3-737cfa36192c.png)

with a tooptip with the full date in raw format

**Comment by abonas** [comment]
@aljesusg is the size change anticipated here? @serenamarie125 isn't this too small now?

**Comment by aljesusg** [comment]
I only changed the time output, the screenshots are kiali vs openshift console. They changes in Kiali are related in show a human readable date with the icon with a tooltip with the full date, I'll add a gif asap here FYI I'm still on my way home from San Francisco

**Comment by aljesusg** [comment]
Hi @abonas , here is the PR with the screenshots that i did. https://github.com/kiali/kiali-ui/pull/1508, I followed the pattern that the openshift team is using.


## before
![before](https://user-images.githubusercontent.com/3019213/67508064-90687880-f690-11e9-9e5b-a9ab6bd7e381.png)

## Now
![Screenshot from 2019-10-24 18-56-18](https://user-images.githubusercontent.com/3019213/67508071-952d2c80-f690-11e9-9cda-fe7173e3b6d6.png)

## Tooltip
![Screenshot from 2019-10-24 18-56-28](https://user-images.githubusercontent.com/3019213/67508067-92cad280-f690-11e9-9d80-3165f6c9459a.png)

cc @serenamarie125
