### ISSUE TITLE
Move the state phase to an icon

### ISSUE THREAD

**Issue by aljesusg** [kiali/kiali#1794]
Now
![Screenshot from 2019-10-14 13-40-09](https://user-images.githubusercontent.com/3019213/66748820-6ccf5200-ee88-11e9-90d9-0b7ea87acf6d.png)

The point is move this to a green, red, orange, gray.-..circle by status (stopped, running, warning, paused...))

**Comment by lwrigh** [comment]
<img width="328" alt="Screen Shot 2020-03-06 at 11 09 09 AM" src="https://user-images.githubusercontent.com/20227374/76100615-f0562080-5f9a-11ea-8f30-6cb52855555b.png">

Here are some examples of PatternFly 4 status icons. From left to right we could use these icons to represent paused, stopped, running, and warning. There is also PatternFly 4 icon options for up and down statuses if it is appropriate for this use case.

**Comment by lucasponce** [comment]
Note that perhaps this one can be impacted with the issue https://github.com/kiali/kiali/issues/3529 where we need to add extra info about containers status.

Today, if there is a problem in a container but Pod is ok, the phase is still in "Running" which could be misleading for the user.

In any case, the use of icons it sounds ok.

Added to the Project to not miss it from the radar.

**Comment by lucasponce** [comment]
it will be incorporated as part of https://github.com/kiali/kiali-ui/pull/2122 effort

**Comment by lucasponce** [comment]
Partially incorporated on https://github.com/kiali/kiali-ui/pull/2122
