### ISSUE TITLE
Advanced Search on Jaeger integration reloads the page

### ISSUE THREAD

**Issue by xeviknal** [kiali/kiali#1805]
See the video attached:

![Screen recording (10)](https://user-images.githubusercontent.com/613814/66845801-02461100-ef71-11e9-8ac0-a49963e07694.gif)

First time: Hitting the search button. Outcome: expected.
Second time: Return keystroke hit. Outcome: unexpected. Reloads the page. It should perform the exact action as the first time.

**Comment by xeviknal** [comment]
cc @aljesusg

**Comment by aljesusg** [comment]
I think that we can close this one
