### ISSUE TITLE
Service Details Traces tab - Refresh - Fails to load

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#1812]
Go to any service Details page, to Traces tab.
Refresh the browser page.

![Screenshot from 2019-10-17 11-09-04](https://user-images.githubusercontent.com/604313/66995056-a5606d00-f0ce-11e9-853a-83b58f929e82.png)

No error in Kiali pod.

**Comment by lucasponce** [comment]
I can reproduce it, as well.
![image](https://user-images.githubusercontent.com/1662329/67202368-c398d680-f408-11e9-9cf3-7171b9aaee9e.png)

I start to work on it.
