### ISSUE TITLE
Consolidate PF4 Icons

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#1813]
Consolidate the PF4 Icons into a single place so that each screen doesn't have to figure out which icons to use from where. Also, colors associated so that we get consistent colors for the icons.

To use:
```
<div>
            {pf4Icon(KialiIconType.Info)} Sparkline charts not supported for unknown node. Use edge for details.
            <hr />
</div>
```

**Comment by aljesusg** [comment]
src/config/icons is a good place for this.  Thanks @mtho11
