### ISSUE TITLE
Cannot use kiali with GKE

### ISSUE THREAD

**Issue by mholleville** [kiali/kiali#1818]
Hi I'm trying to use Kiali with GKE and add-on Istio. 

I have following the [documentation](https://www.kiali.io/documentation/getting-started/#_advanced_install_operator_only) and deploy Kiali. 

1. `kubectl label namespace default istio-injection=enabled`
2. `bash <(curl -L https://git.io/getLatestKialiOperator)`
3. `kubectl port-forward service/kiali 20001 -n istio-system`

I have this following error when I trying to curl `http://127.0.0.1:20001/` --> `Client sent an HTTP request to an HTTPS server.`

Can you help me ?

**Comment by jmazzitelli** [comment]
> http://127.0.0.1:20001/ --> Client sent an HTTP request to an HTTPS server.

Your URL is "http:" - the error message says you sent an HTTP request to an HTTPS server. So use `https:` (Kiali by default  is deployed behind https)

**Comment by mholleville** [comment]
Thank you for your reply. I cannot use https on my localhost --> NET::ERR_CERT_INVALID . I cannot use Kiali without https ?

**Comment by jmazzitelli** [comment]
You can ... you can configure kiali to use just http. You change the Kiali CR to remove its identity and http will be used. See: https://github.com/kiali/kiali/blob/master/operator/deploy/kiali/kiali_cr.yaml#L369-L382

This isn't a bug or enhancement request - but more of a user question. Recommended you go through the Google Group at https://groups.google.com/forum/#!forum/kiali-users or freenode IRC chat #kiali to discuss further.

**Comment by jmazzitelli** [comment]
(note: your cert error is because the kiali cert is not trusted by your client - you can force the client to trust the cert to avoid the error using the mechanism your client (browser) uses to trust certs)

**Comment by mholleville** [comment]
Thank you ! I have just add `chrome://flags/#allow-insecure-localhost` on my chrome and it's ok ! Thank you
