### ISSUE TITLE
Charts: legend items not triggering mouse over after they are clicked

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#1819]
Issue spotted from PR https://github.com/kiali/kiali-ui/pull/1491 :

In rate bars chart / summary panel: when clicking on a legend item to hide a bar, then click again to show, then the mouseover event (with styling effect) doesn't work anymore on that item.
Similar bug seen also on the response time chart.

**Comment by lucasponce** [comment]
Not sure if it's still active.
I've performed a couple of tests and at least it worked for me:

- Clicking on legends to hide ok -> Check that mouseover event work changing the style of the bars
- Click on legends to show ok -> Check that mouseover even work in the ok green bar and others.
- 
![image](https://user-images.githubusercontent.com/1662329/107637634-bc857f80-6c6e-11eb-9131-83a0926f1cc8.png)

So perhaps this is related to the dependency on the versions used for charts.

I'm going to close, feel free to reopen if it seems broken in other scenario.

I know there is an open issue with tippy, but I think this one seems gone.
