### ISSUE TITLE
[PF4] Replace all occurrences of Icon (PF3) to KialiIcon (PF4)

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#1825]
**Is your feature request related to a problem? Please describe.**
Now that we have a centralized PF4 Icon store `KialiIcon` we need to replace the PF3 based Icon with KialiIcon.

Related:
#1813

**Comment by aljesusg** [comment]
About this I think that we should move all the icons to this file to be consistent

**Comment by mtho11** [comment]
@aljesusg I agree.
