### ISSUE TITLE
Rendering Problems on Graph with Big Meshes

### ISSUE THREAD

**Issue by gbaufake** [kiali/kiali#1826]
**Describe the bug**
There is a rendering issue with big meshes. Geometric elements (services, app) are not being rendered.

The search  proved that the element was there but it was not displayed correctly.

**Versions used**
Kiali-ui
1.7.0 (406b17787425c2a7bedfb8f0eb932f18bceaece9)
Kiali
v1.7.0 (1dfbbba93ea272b01f5ee17eb6a72ec589bf9513)
Maistra: 1.0
Openshift: 4.2
Resolution: 2880 x 1800

**To Reproduce**
1. Deploy a big mesh (eg: 100 services). 

 > You can do it by deploying the Scale Mesh on Kiali Test Mesh https://github.com/kiali/kiali-test-mesh/pull/55 - (Clone this pull request, run `make deploy-operator` and then run `SCALE_MESH_NUMBER_SERVICES=100 SCALE_MESH_NUMBER_APPS=100 SCALE_MESH_NUMBER_VERSIONS=2 SCALE_MESH_NUMBER_NAMESPACES=1 SCALE_MESH_TYPE_OF_MESH=kiali-test-circle make deploy-scale-mesh`

2. Click on Zoom in twice fast.

3. The geometric figures will not be rendered( triangles, squares) - pictures below

<img width="1152" alt="Captura de Tela 2019-10-21 às 14 54 28" src="https://user-images.githubusercontent.com/2313749/67231846-80456480-f416-11e9-92ad-99f8b2cee450.png">
<img width="1156" alt="Captura de Tela 2019-10-21 às 14 55 01" src="https://user-images.githubusercontent.com/2313749/67231847-80456480-f416-11e9-8704-d02fe6cdec86.png">
<img width="726" alt="Captura de Tela 2019-10-21 às 14 55 20" src="https://user-images.githubusercontent.com/2313749/67231849-80456480-f416-11e9-9a39-fcb8f8f381a3.png">
<img width="873" alt="Captura de Tela 2019-10-21 às 14 58 12" src="https://user-images.githubusercontent.com/2313749/67231851-80456480-f416-11e9-9c5f-1bf836cc0b28.png">
<img width="1067" alt="Captura de Tela 2019-10-21 às 15 38 42" src="https://user-images.githubusercontent.com/2313749/67233048-e7fcaf00-f418-11e9-8285-e3dd66d04394.png">

**Expected behavior**
Elements of graph being correctly displayed.

cc @josejulio @jshaughn

**Comment by josejulio** [comment]
Could you include the graph.json? (or output of ?-menu -> Debug info)

**Comment by gbaufake** [comment]
cc @josejulio 
[debug.txt](https://github.com/kiali/kiali/files/3752786/debug.txt)

**Comment by gbaufake** [comment]
[debug2.txt](https://github.com/kiali/kiali/files/3752796/debug2.txt)

**Comment by lucasponce** [comment]
@josejulio
 
Completely side comment, is there a way to load Kiali Graph with a high dense json without a proper backend ?

In an unrelated conversation with @yurishkuro he asked me about that as they are studying if Kiali Graph can help them for their use cases and they would like to test just the graph component.

**Comment by lucasponce** [comment]
@gbaufake can you reproduce with the workload graph type ?

**Comment by josejulio** [comment]
> Completely side comment, is there a way to load Kiali Graph with a high dense json without a proper backend ?

One could implement a custom page (or a  Storyboard) with the `CytoscapeGraph` component, mocking away all the other requirements.

Other option would be to mock the server.
I configured a [talkback](https://github.com/ijpiantanida/talkback) server a while ago to do this on my own tests. Basically i run the Kiali server once, and configure my mock server to record the calls. After that i shutdown the server and update the cassettes as needed.
A sample of that can be found [here](https://github.com/josejulio/kiali-mock-server) it might require some tweaking.

**Comment by josejulio** [comment]
@gbaufake I couldn't reproduce when using above method and (mock server) and the graph that you sent. I think that this could be some problem with cytoscape due the large number of nodes, but not sure.
Did you see any error in your browser console?

**Comment by josejulio** [comment]
![Peek 2019-10-22 12-12](https://user-images.githubusercontent.com/3845764/67311495-51d29280-f4c5-11e9-9516-29743b997ea4.gif)

**Comment by gbaufake** [comment]
@lucasponce 
Happening with workload graph 
<img width="1010" alt="Captura de Tela 2019-10-22 às 14 33 50" src="https://user-images.githubusercontent.com/2313749/67313352-38d3dc80-f4d9-11e9-8c81-2ce834201a90.png">

**Comment by gbaufake** [comment]
@josejulio 
No console log issues 

<img width="1477" alt="Captura de Tela 2019-10-22 às 14 37 06" src="https://user-images.githubusercontent.com/2313749/67313509-746ea680-f4d9-11e9-8e5f-59ec2cce4551.png">

**Comment by gbaufake** [comment]
@josejulio 
Try clicking faster the zoom in (like spamming the button).
From your gif I noticed that you are waiting some time.

**Comment by josejulio** [comment]
> Try clicking faster the zoom in (like spamming the button).

I tried, in firefox latest, firefox ESR, chrome, my baby tried (she discovered that using the space bar after click the + works), i tried again with keyboard and mouse and no luck. I can't reproduce it.

Does the shapes appear when the graph loads? or they only disappear after spamming the zoom in? 
Do you have to spam it many times until it disappear or it happens on the first time?
What happens if you use your mouse to zoom-in?

**Comment by josejulio** [comment]
Ok, I was able to reproduce it on @gbaufake box, it looks like something related to cytoscape's cache. I'm going to ask there for leads.

**Comment by josejulio** [comment]
![Peek 2019-10-22 15-45](https://user-images.githubusercontent.com/3845764/67331146-06c77800-f4e3-11e9-9dbf-e6cc481ba50f.gif)

**Comment by gbaufake** [comment]
@josejulio 
So do we have a confirmation of the bug based on your last picture?

**Comment by jshaughn** [comment]
@gbaufake, @josejulio worked a bit with cytoscape in https://github.com/cytoscape/cytoscape.js/issues/2562.  Unfortunately they were not able to come up with anything conclusive although it is most likely a cy issue as it is definite that the node exist, they are just not rendering correctly.  If a smaller sample can show the same issue it will likely be helpful, until that time the investigation is likely stalled.

**Comment by josejulio** [comment]
Cytoscape has released version `3.15.0 ` that might solve this issue.
They are now using a different hashing algorithm 

see: https://github.com/cytoscape/cytoscape.js/issues/2636

**Comment by jshaughn** [comment]
@josejulio I don't think 3.15.0 is out yet.  But when released I'm +1 to updating.  If max has identified weaknesses in the current hashing it could explain some of the strange behavior we see intermittently.

**Comment by josejulio** [comment]
Ah, you are right. I didn't read it correctly. The fix is going to be on `3.15.0`  https://github.com/cytoscape/cytoscape.js/milestone/194 but not out yet.

**Comment by jshaughn** [comment]
@josejulio I'm not sure, the change may have made it into 1.14.2, i see some hash-related commits.

**Comment by josejulio** [comment]
I suppose you mean `3.14.2`, but i don't see the commit https://github.com/cytoscape/cytoscape.js/commit/0e01d5398931050c8f633f72693d8d3d2815d1ea in here: https://github.com/cytoscape/cytoscape.js/commits/v3.14.2

**Comment by jshaughn** [comment]
Yes, 3.14.2.  Hmm, I guess you are right, I must have been confused or looking at the wrong branch.  I'm glad actually because I tried 3.14.2 locally and didn't see any change for a problem case I was looking at.  Waiting for 3.15...

**Comment by jshaughn** [comment]
@josejulio Cytoscape 3.15.0 has been released.  I'll use this issue to perform the update.  Maybe it will help. it may also have an effect on https://github.com/kiali/kiali/issues/2514.  Or not...
