### ISSUE TITLE
Two unsimilar error messages

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#1828]
**General remarks**
The pictures says 1000 words. But there are two different sized messaging items depending on where the error came from.

![different-error-msg](https://user-images.githubusercontent.com/1312165/67249803-d10c8b80-f41d-11e9-96d2-34207a75b42b.png)

![Kiali_Console_-__Private_Browsing_](https://user-images.githubusercontent.com/1312165/67249912-46785c00-f41e-11e9-9437-060b43bcace8.png)

These should be consistent.

**Comment by mtho11** [comment]
Regardless of how much message text is in the box; they should all line up and text should just flow to the next line.

**Comment by lucasponce** [comment]
+1
I think is worth to have a fixed width and to grow in multiple-lines if necessary.

**Comment by aljesusg** [comment]
+1 We should show all errors with the same style

**Comment by jshaughn** [comment]
I'll take this, my PF4 MessageCenter work i think already uses a fixed width.
