### ISSUE TITLE
[operator] add new metadata to manifests regarding relatedImages

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#1829]
Read this: https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/contributors/design-proposals/related-images.md

We need to add relatedImages to our CSVs.

**Comment by jmazzitelli** [comment]
Evan Cordell says this is already implemented on the OLM side so we can work on this now

**Comment by jmazzitelli** [comment]
After talking to the OLM folks on Slack, I confirmed this feature is for disconnected environments (those environments that can't download from external repos like quay.io). And it also means the operator CSV should (if it can) specify the operand images as well as the operator image - this means the CSV should specify in relatedImages the kiali image. Of course, this will not work in disconnected mode if the user opts to install a different image than the default i.e. specifies a different hub or version in the kiali cr).

**Comment by jshaughn** [comment]
Waiting on how we are actually going to support disconnected. This is still being figured out by folks outside of our group.

**Comment by jmazzitelli** [comment]
this is done in the kiali-ossm manifest metadata, where it needs to be.
