### ISSUE TITLE
Security: Service out of SMMR are visible by URL and editble

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#1831]
Logged in to Kiali via kubeadmin.
Make sure that ServiceMeshMemberRoll does not include 'bookinfo' or any other namespace.
Go to Service list.
It will not show bookinfo services.
Open bookinfo/details Service by just typing the URL in browser.
It will open that service.
And the Actions is available too. So user can delete the routing.
Applications and Workloads as well are opened.

![Screenshot from 2019-10-22 18-58-05](https://user-images.githubusercontent.com/604313/67311005-0dfc7f00-f4ff-11e9-8ecf-7fc12d343774.png)
![Screenshot from 2019-10-22 18-53-32](https://user-images.githubusercontent.com/604313/67311006-0e951580-f4ff-11e9-8fee-de2dfafeabe3.png)
![Screenshot from 2019-10-22 18-53-42](https://user-images.githubusercontent.com/604313/67311007-0e951580-f4ff-11e9-9897-c94020be38e9.png)
![Screenshot from 2019-10-22 19-03-57](https://user-images.githubusercontent.com/604313/67311008-0e951580-f4ff-11e9-95dc-9a72a41b6af7.png)

**Comment by lucasponce** [comment]
But just to make sure.
Kiali doesn't add an extra security layer than RBAC.
It means, if kubeadmin user can access to an item via CLI, probably Kiali will have that access in OpenShift platform too.

So, basically Kiali aligns with RBAC here, another thing is that you can't perform an operation via CLI with user "a", but user "a" can do it in Kiali, then I consider that a security problem.

Perhaps we can filter every operation with the accessible namespaces, but I won't do it for 1.0 as cache is not enabled, and that would be create a performance impact.

**Comment by lucasponce** [comment]
Correction.
I see that we already do that in master when cache is enabled:

```
if _, err2 = in.businessLayer.Namespace.GetNamespace(namespace); err2 == nil {}
```

So, for consistency, I agree @hhovsepy it makes sense to also done when cache is not enabled, too.

I will update master and check the implications in the 1.0 branch, too.

**Comment by lucasponce** [comment]
@hhovsepy I'm thinking/working on this issue and I'm not sure what should be.
I mean, I think it can be correct to adjust the security filter with the accessibleNamespaces of Kiali:
https://github.com/kiali/kiali/blob/master/operator/deploy/kiali/kiali_cr.yaml#L51

But Kiali won't take any other source of "filter" for namespaces access but current RBAC system.

Note that in your example a modification on the ServiceMeshMemberRoll will be handled by maistra-operataor/kiali-operator combination to modify the list of namespaces visible.
