### ISSUE TITLE
Masthead disappears after scrolling on lists

### ISSUE THREAD

**Issue by israel-hdez** [kiali/kiali#1834]
**Versions used**
Kiali: v1.8.0-snapshot.0
This was seen in Chrome.

**To Reproduce**
1. Go to the workloads, services or apps list page. Make sure that the browser windows is small enough for scrollbars to appear.
2. Scroll down the list.
3. Use the main navigation at the left to go to another page.
  - The masthead will disappear.

**Note:** The Istio Config page doesn't show this behavior.

![Peek 2019-10-22 16-24](https://user-images.githubusercontent.com/23639005/67334895-80159980-f4e8-11e9-9040-b55a188dd708.gif)

**Expected behavior**

Masthead shouldn't hide.

**Comment by lucasponce** [comment]
Yeah. I cc @aljesusg as not sure if he has something WIP for updating the virtual lists, too.

**Comment by aljesusg** [comment]
Wow let me check it As far as I know there was a PR in PF about the Virtual scroll because there are some issues related with

**Comment by aljesusg** [comment]
I could not reproduce this error in FF or Chrome :(

**Comment by hhovsepy** [comment]
I can reproduce that on Chrome.
Make sure, that, when scrolling the upper line of the row matches with the bottom line of table header.
![Screenshot from 2019-10-24 09-05-12](https://user-images.githubusercontent.com/604313/67461384-7ea9b580-f63d-11e9-8c45-ab96a9a5bee8.png)
![Screenshot from 2019-10-24 09-03-23](https://user-images.githubusercontent.com/604313/67461383-7ea9b580-f63d-11e9-816a-efc876cb01f3.png)

**Comment by aljesusg** [comment]
@hhovsepy can you check if this happens in 
Kiali-ui 1.7.0 (406b17787425c2a7bedfb8f0eb932f18bceaece9)
Kiali v1.7.0 (1dfbbba93ea272b01f5ee17eb6a72ec589bf9513) ?

I have only been able to verify it in master so it seems that is related with the last upgrade

**Comment by aljesusg** [comment]
Ok after investigate this I found that the error is here https://github.com/kiali/kiali-ui/commit/56bee518473d4d318af327adec106b024f43fbbb#diff-a4e4fca5bb91e1f9189935465ecc48c7 I need to research about

**Comment by hhovsepy** [comment]
I can not reproduce that on v1.7.0.

**Comment by jshaughn** [comment]
I am seeing this in a new scenario, in a current PR of mine, not related to the list views.  I'm not sure if it's related.  I noticed that the Masthead isn't really gone, but rather the entire "root" div is shifted up such that the masthead is offscreen.  Something definitely gets screwed up and I have no idea what to do about it.  It seems related to the new Select component used in the new PF4 version of the graph Display selection.
