### ISSUE TITLE
Validate Kiali for Istio 1.4 release

### ISSUE THREAD

**Issue by jshaughn** [kiali/kiali#1838]
Kiali should be validated against the Istio 1.4 RC releases in preparation for the GA.

The Assignee is responsible for ensuring the validation happens but not necessarily for doing all the validation.

RC1 Validation
bits: https://gcsweb.istio.io/gcs/istio-release/releases/1.4.0-alpha.0/
docs: https://preliminary.istio.io/

- Is Kiali Installed?
- Is the Kiali version correct?
- Does this command work: > istioctl dashboard kiali 
- Did a smoke test of Kiali pass?
- Did a smoke test of Kiali pass using mixer-less telemetry?

Notes:
[jshaughn] There is some slack convo about potential breakage/oom issues in the RC, waiting before installing.

RC2 Validation

- Is Kiali Installed?
- Is the Kiali version correct?
- Does this command work: > istioctl dashboard kiali 
- Did a smoke test of Kiali pass?
- Did a smoke test of Kiali pass using mixer-less telemetry?

**Comment by jmazzitelli** [comment]
Installing Istio 1.4 using istioctl via new hack script found here: https://github.com/kiali/kiali/pull/1853

Istio not starting on my OS 4.2 cluster, so I am not getting as far as to even test kiali:

```
$ oc get pods
NAME                                      READY   STATUS              RESTARTS   AGE
grafana-6b58d744b6-95rdc                  1/1     Running             0          10m
istio-citadel-5d79889c58-txkvl            1/1     Running             0          10m
istio-egressgateway-7645d99dcf-r22zf      0/1     Running             0          10m
istio-galley-95c8c794f-d6pq2              0/1     ContainerCreating   0          10m
istio-ingressgateway-557898dff9-xb888     0/1     Running             0          10m
istio-pilot-7457565f64-6bzt2              0/1     Running             0          10m
istio-policy-994d94c66-d9t46              0/1     CrashLoopBackOff    7          10m
istio-sidecar-injector-866669d699-jzbds   0/1     ContainerCreating   0          10m
istio-telemetry-d76c7b87d-2twhr           0/1     CrashLoopBackOff    7          10m
istio-tracing-86cc56bcd4-xfc5b            1/1     Running             0          10m
kiali-567b6cbfdb-rnzs7                    1/1     Running             0          10m
prometheus-7c84fcfc59-krgvp               1/1     Running             0          10m
```

**Comment by jmazzitelli** [comment]
Can't use the new `istioctl manifest` installer - there is a bug that needs to be fixed and released in 1.4 beta2 before we can try it.

So I am using the helm installer. New hack script with CNI additions here: PR #1856 -- must use the "demo" profile (hack script opton "-ud true") because the default profile is also not successfully installing.

**Comment by israel-hdez** [comment]
Smoke testing on minikube with Istio 1.4
* Demo profile installs without issues. I get Kiali v1.4.2.
* `istioctl dashboard kiali` works
* Kiali mostly works without issues. Wizards are the only features that I could find that don't work (cc @lucasponce). All wizards fail with an error like this one:
```
VirtualService.networking.istio.io "reviews" is invalid: []: Invalid value: map[string]interface {}{"apiVersion":"networking.istio.io/v1alpha3", "kind":"VirtualService", "metadata":map[string]interface {}{"creationTimestamp":"2019-10-31T19:19:44Z", "generation":1, "labels":map[string]interface {}{"kiali_wizard":"matching_routing"}, "name":"reviews", "namespace":"bookinfo", "uid":"03104edb-a6bd-4d4a-bbbd-3b3de57f288b"}, "spec":map[string]interface {}{"gateways":interface {}(nil), "hosts":[]interface {}{"reviews"}, "http":[]interface {}{map[string]interface {}{"match":[]interface {}{map[string]interface {}{"uri":map[string]interface {}{"exact":"douh"}}}, "route":[]interface {}{map[string]interface {}{"destination":map[string]interface {}{"host":"reviews", "subset":"v1"}, "weight":34}, map[string]interface {}{"destination":map[string]interface {}{"host":"reviews", "subset":"v2"}, "weight":33}, map[string]interface {}{"destination":map[string]interface {}{"host":"reviews", "subset":"v3"}, "weight":33}}}}}}: validation failure list:
spec.gateways in body must be of type array: "null"
```
* I'm not sure if this is expected, but Kiali pod logs these warnings when visiting the "Istio Config" page:
```
W1031 19:26:50.020509       1 istio_rules_service.go:114] Querying adapter got an error: default doesn't return a stackdrivers list
W1031 19:26:50.020512       1 istio_rules_service.go:114] Querying adapter got an error: default doesn't return a stdios list
W1031 19:26:50.020516       1 istio_rules_service.go:114] Querying adapter got an error: default doesn't return a memquotas list
W1031 19:26:50.020519       1 istio_rules_service.go:114] Querying adapter got an error: default doesn't return a opas list
W1031 19:26:50.020522       1 istio_rules_service.go:114] Querying adapter got an error: default doesn't return a solarwindses list
[... etc ...]
```

**Comment by israel-hdez** [comment]
Smoke testing on minikube with Istio 1.4 with Kiali `master`... Same result as with v1.4.2 :disappointed:

**Comment by jshaughn** [comment]
@israel-hdez Excellent evaluation.  This is going to be a high priority issue.  We need to figure out if the validation problem is due to Istio or us, and get a fix into the responsible product.  If it's us then we need to decide whether to bump the Kiali version.  I think we should probably create an Istio issue for 1.4 so it can be tracked and to probably let them know independently as well, maybe on Slack test and release channel.

**Comment by israel-hdez** [comment]
I can successfully use the Wizards on Istio1.3 and Kiali master.

**Comment by israel-hdez** [comment]
Reported in istio repository so that they are aware: https://github.com/istio/istio/issues/18558

**Comment by lucasponce** [comment]
@israel-hdez ah !

```
W1031 19:26:50.020509       1 istio_rules_service.go:114] Querying adapter got an error: default doesn't return a stackdrivers list
W1031 19:26:50.020512       1 istio_rules_service.go:114] Querying adapter got an error: default doesn't return a stdios list
W1031 19:26:50.020516       1 istio_rules_service.go:114] Querying adapter got an error: default doesn't return a memquotas list
W1031 19:26:50.020519       1 istio_rules_service.go:114] Querying adapter got an error: default doesn't return a opas list
W1031 19:26:50.020522       1 istio_rules_service.go:114] Querying adapter got an error: default doesn't return a solarwindses list
[... etc ...]
```

That's a nice an expected news :-), yes, that means that finally an old rules format is gone in 1.4.
I need to adjust that code for it.

**Comment by jmazzitelli** [comment]
smoke tested on istio 1.4.beta2 and openshift 4.2, no new problems have been found.

**Comment by lucasponce** [comment]
Follow up of @israel-hdez work that needs to be merged:
https://github.com/kiali/kiali/pull/1888

**Comment by jmazzitelli** [comment]
Working on upgrading Kiali to latest release - see: https://github.com/istio/installer/pull/503
So far, tests look good.

**Comment by israel-hdez** [comment]
Since the Wizards issue looks properly fixed, I'm closing https://github.com/istio/istio/issues/18558.

**Comment by jmazzitelli** [comment]
I think we can close this. All testing appears good.

**Comment by jwendell** [comment]
Thanks folks!
