### ISSUE TITLE
Use Patternfly css variables or React Tokens instead of hard coded RGB colors

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#1839]
**Is your feature request related to a problem? Please describe.**
By moving to PatternFly css variables (ex: `--pf-c-about-modal-box__brand-image--Height`) or React Tokens (example: `c_about_modal_box__close_c_button_BackgroundColor`) instead of hard coded RGB values (example: `#F0F0F0`) we will be closer in alignment with PatternFly. **Also, any changes that PatternFly makes to the colors we will get for free.**

Reference:
https://patternfly-react.surge.sh/patternfly-4/documentation/global-css-variables

**Comment by mtho11** [comment]
We could begin by just changing the `PfColors` from RGB to React Tokens?
@aljesusg WDYT?

**Comment by mtho11** [comment]
My vote would be to use the React Tokens over the css variables.

**Comment by mtho11** [comment]
Also, `GraphStyles.ts` would be worthwhile updating.

**Comment by jshaughn** [comment]
This seems like it should fall under the PF4 conversion work, adding to backlog and sprint.

Related to https://github.com/kiali/kiali/issues/1588
