### ISSUE TITLE
UX: Edge tweaks: solid lines and increase traffic particle size

### ISSUE THREAD

**Issue by jshaughn** [kiali/kiali#1843]
Given the recent doubling of edge widths, the traffic animation particles should also double in size.  This addition was made after a recent UX review of the previously merged updates.

Edges should go back to solid lines.

From @serenamarie125 :
"please switch to using solid lines for traffic connections!  i just verified with Michael Celedonia.  We will do the same in OpenShift Dev Console!"

**Comment by mtho11** [comment]
Reminder to update the Legend as part of this.
