### ISSUE TITLE
Replace graph Display PF Dropdown with PF Grouped checkbox input

### ISSUE THREAD

**Issue by israel-hdez** [kiali/kiali#1849]
Currently, the graph page uses the PF Dropdown control for all dropdowns.
The _Display_ dropdown is using the "custom" pattern of that control. It looks like this in Kiali:

![](https://user-images.githubusercontent.com/23639005/66959567-40eed080-f030-11e9-9747-94ecd82a1b8d.png)

However, the [Grouped checkbox input of the PF Select control](https://patternfly-react.surge.sh/patternfly-4/documentation/react/components/select#grouped-checkbox-input) is a better control for the _Display_ case. It should be used to avoid using the free-form pattern of the Dropdown control.

**Comment by mtho11** [comment]
Now that we are on PF4, I agree. There are at least 3 places that use that pattern.

**Comment by mtho11** [comment]
One thing that comes to mind, is that if we should add an option to 'Clear All'. IMO it would be very useful to clear the slate instead of unchecking each one. The caveat being that the new Grouped Checkbox would not allow us to do that. Just something to think about.
