### ISSUE TITLE
Enable correlation between metrics and traces in Details Pages / Metrics Tab

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1854]
Details pages offer a tab for detailed view of metrics (Inbound, Outbound, Runtimes).

One interesting feature could be to correlate the results of these metrics with other signals that Kiali collects.

On this case, this issue propose to enable a new button / option on these pages to enable to show / correlate two different signals within same chart as described in the following mockup:

![image](https://user-images.githubusercontent.com/1662329/67855799-6d681980-fb13-11e9-8a82-bf2f0020c524.png)

A "Show/Hide Traces" feature may enrich the interpretation of the information and "correlate" in the sense to visualize together both scenarios for analysis.

This feature is just scoped to traces, as a similar calculation was made before for the traces tab title, where kiali fetched the number of errors for a particular service.

**Comment by lucasponce** [comment]
cc @jotak @aljesusg

**Comment by jshaughn** [comment]
cc Everybody :)

**Comment by jotak** [comment]
https://docs.google.com/document/d/1z2u1Kw7_WeHBL5aaR2hvKVbYr_qjdRRfoqQoKBtPOm4

**Comment by jotak** [comment]
I'm splitting the work, with some pre-requisite in k-charted: https://github.com/kiali/kiali/issues/1939

**Comment by lucasponce** [comment]
> I'm splitting the work, with some pre-requisite in k-charted: #1939

It's fine but also you can add subtasks in the same issue (without the need to create new issues).
Whatever it works .

There is no need to 1 issue per Pull Request and this could be an example where it can perfectly fit in a subtask (it that simplifies).

**Comment by jotak** [comment]
done (all merged)
