### ISSUE TITLE
"Could not fetch Namespaces list." error in browser back.

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#1863]
Go to Traffic tab of some Workload.
Click on any of outbound or inbound trace links.
In the opened object's page go to Traffic tab.
Then click browser Back two times to return back into original Workload page.
It shows error notification that "Could not fetch Namespaces list."
Happening not constantly, cache is off.

![Screenshot from 2019-11-01 10-45-53](https://user-images.githubusercontent.com/604313/68016879-c2cc3400-fc95-11e9-8f41-45e4942da300.png)

**Comment by lucasponce** [comment]
I can confirm some issues with the back button in the detail page.
I couldn't reproduce the exact issue you saw here @hhovsepy but I suspect it's related the the defect I'm seeing locally.

I will prepare a fix.

**Comment by lucasponce** [comment]
Fixes kiali/kiali#1911

@hhovsepy I think #1911 is addressed as well as it was the same problem.

Let me know if you can confirm.

Thanks
