### ISSUE TITLE
[UI internal] - use the same ID for all refresh buttons

### ISSUE THREAD

**Issue by FilipB** [kiali/kiali#1865]
Refresh button on Overview page has id=overview-refresh_btn. I also noticed id=overview-refresh on other page and also id=refresh_button.

Would it be possible to use id=refresh_button everywhere? It would make UI automation easier.

**Comment by mtho11** [comment]
@jshaughn can we close this now that you did: https://github.com/kiali/kiali-ui/pull/1559

**Comment by cfcosta** [comment]
This is merged already: https://github.com/kiali/kiali-ui/pull/1518

**Comment by jshaughn** [comment]
@cfcosta When you put "Fixes #1865" it doesn't get picked up.  You need to put in the full link.  That is why this did not get closed.
