### ISSUE TITLE
"Kiali secret is missing" but it's definitely there

### ISSUE THREAD

**Issue by CannibalKush** [kiali/kiali#1875]
My Kiali installation returns 520 when logging in. 

In my console is being printed:
```
W1105 08:23:28.238619       1 kiali.go:145] Kiali is missing a secret that contains both 'username' and 'passphrase'
E1105 08:23:34.142346       1 authentication.go:108] Credentials are missing. Create a secret. Please refer to the documentation for more details.
```

This is strange, because running

`kubectl describe secret kiali -n istio-system`

provides me with the following output:

```
Name:         kiali
Namespace:    istio-system
Labels:       app=kiali
              flux.weave.works/sync-gc-mark=sha256.ZNNGIdiNNcRZl-YCuc551EB3Edthk6kuz-PlDVn6U9k
Annotations:  flux.weave.works/sync-checksum: ae50afa268598e23696d4e980b1686829b3589e4

Type:  Opaque

Data
====
passphrase:  5 bytes
username:    6 bytes
```

restarting the pod does not solve the issue.

**Versions used**
Kiali: Version: v0.18.1, Commit: ef27faa49cf0e6c24e578519e6702e05e8b11cf4
Istio: 1.1.2
Kubernetes flavour and version: (e.g. OpenShift Origin 3.9): Azure AKS

**To Reproduce**
Deploy Istio to your AKS cluster using the following resource:
https://github.com/timfpark/fabrikate-cloud-native

**Expected behavior**
I want to be able to log in

**Comment by lucasponce** [comment]
Outdated.
