### ISSUE TITLE
'Created at' date of istio config is incorectly translated to browser timezone (pm vs am)

### ISSUE THREAD

**Issue by FilipB** [kiali/kiali#1878]
**Describe the bug**
I created a destination rule at following UTC date: 2019-11-05T11:38:10Z but it is incorrectly translated to browser timezone (CET – Central European Time: UTC +1) as Nov 5, 12:38 am.
It should be Nov 5, 12:38 pm

![created-at-screen](https://user-images.githubusercontent.com/328182/68206733-caf5dd80-ffcd-11e9-9f07-378940b045fc.png)

I did not test other variant of this issue with UTC date: 2019-11-05T23:38:10Z. I don't know if it's translated correctly to Nov 6, 12:38 am or if it's also incorrect.

**Versions used**
Kiali-ui
    1.9.0 (2a1525fff0cc8e1dfee38ab6f41e57effa2051d7)
Kiali
    v1.9.0-SNAPSHOT (7b683b646fc282121d1b421f85722dd509ce3dc7)
OpenShift Service Mesh
    1.0.2 
Kubernetes flavour and version: (e.g. OpenShift Origin 3.9)
OCP 4.2

**To Reproduce**
1. Create new destination rule between 11 and 12 UTC time e.g. 2019-11-05T11:38:10Z
2. Set your system(browser) timezone to CET – Central European Time: UTC +1
3. Open Kiali UI and navigate to created istio config
4. Created at time shows: Nov 5, 12:38 am

**Expected behavior**
Created at should be Nov 5, 12:38 pm
It's probably not problem only for istio configs but for all other resources showing 'Created at' date

**Comment by jotak** [comment]
Shouldn't we use a lib like `moment.js` to format time rather than having our own implementation? Also, I'm not sure why we force the use of am/pm notation instead of relying on user's locale?

**Comment by aljesusg** [comment]
This code is based  in how the openshift console deal with the dates and the UX design, I don't know if we should change the format or be aligned

**Comment by aljesusg** [comment]
Based in https://github.com/openshift/console/blob/b1d9ea400434fd22748bf3834f447a4411406be1/frontend/public/components/utils/timestamp.tsx

**Comment by jotak** [comment]
Doing some tests:

```javascript
var event = new Date(Date.UTC(2012, 11, 20, 3, 0, 0));
var options = { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' };
console.log(event.toLocaleString('en-US', options));
console.log(event.toLocaleString('fr-FR', options));
console.log(event.toLocaleString('es-ES', options));
```

output:

```
> "Dec 20, 4:00 AM"
> "20 déc. à 04:00"
> "20 dic. 4:00"
```

So one solution is to use `new Date(time).toLocaleString('en-US', { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' })` and we're almost on par with the current display (but with the current bug fixed).

The other solution is to use user locale (which personally I prefer to respect 12/24 locale standards) but it has the downside of mixing not-localized text (pretty much everything in Kiali) with localized dates so maybe could look less consistent if nitpicking.
