### ISSUE TITLE
Async load of SMMR causes failure of loading all objects

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#1886]
Happens on master.
Make sure SMMR has access to bookinfo.
Reinstall Maistra and Kiali so SMMR is recreated.
Add bookinfo into SMMR, but it takes some time load up all accessible namespaces.
There is kind a async load of accessible namespaces from SMMR between Namespace selector and the loading of for instance Workloads, which causes failure of loading of other accessible namespace items as well.
The namespaces names are shown in Namespace selector, but their items not in the list of objects, and this causes failing load of all other objects.
![Screenshot from 2019-11-06 10-45-59](https://user-images.githubusercontent.com/604313/68287607-4a91b400-0083-11ea-9fd1-c660b39a115f.png)

**Comment by lucasponce** [comment]
@hhovsepy let me see if I understand the scenario.

ServiceMeshMemberRoll has "bookinfo" as a member.
User kube:admin has access to "bookinfo"

Kiali shows an error about "bookinfo" is not accessible ?
Does Kiali recover when it is refreshed ? (Not to solve the issue but to check the impact).

**Comment by hhovsepy** [comment]
@lucasponce right, it takes up to a minute, then Kiali recovers and shows all accessible namespaces, including bookinfo.

**Comment by lucasponce** [comment]
Fixed by #1925
