### ISSUE TITLE
Istio page, message about not information loaded not centered

### ISSUE THREAD

**Issue by aljesusg** [kiali/kiali#1897]
![Screenshot from 2019-11-07 12-02-37](https://user-images.githubusercontent.com/3019213/68383775-95303080-0156-11ea-8230-7b569bb32c14.png)

**Comment by lucasponce** [comment]
please, Issues *should not* be moved to *in review*.
An Issue *in progress* should have a Pull Request added into the project, then automatically the PR will be shown under the *in review* column.

**Comment by cfcosta** [comment]
@lucasponce ok, TIL. Sorry about that.
