### ISSUE TITLE
Productization Automation Tracking Issue

### ISSUE THREAD

**Issue by cfcosta** [kiali/kiali#1900]
Tracking issue on github for the tasks related to release productization automation.

* [ ] https://issues.jboss.org/browse/OSSM-57
* [ ] https://issues.jboss.org/browse/OSSM-77

**Comment by lucasponce** [comment]
Minor comment.
Just a formality, the OSSM (product JIRA) should have the links to the upstream issue (this one).
Upstream -> downstream is not necessary.
If you can, please, update those OSSM, then Product and Program Manager can get details of the work here as well.

Also, any topic related to the downstream and not part of upstream should be tracked only in JIRA OSSM.

**Comment by lucasponce** [comment]
Please @cfcosta @israel-hdez, the OSSM issues related to this are part of the product and would need an update in case that we need to raise something into the Program Call.
Thanks.

**Comment by lucasponce** [comment]
Moved enhancement > maintenance as it's a pure development task (improve the build process) but not a new feature.

**Comment by lucasponce** [comment]
What is the status of this issue @israel-hdez @jshaughn ?

**Comment by israel-hdez** [comment]
@lucasponce I'm progressing quite slowly. It's secondary priority.
I'm still trying to do the pipeline setup.

**Comment by jshaughn** [comment]
@israel-hdez Should we perhaps make this into an Epic and add subtasks that may be able to be completed in a single sprint?

**Comment by jshaughn** [comment]
Closing as this is an ongoing task and not upstream work.  Work is followed up in https://issues.redhat.com/browse/OSSM-153.
