### ISSUE TITLE
Double Scrollbars in Listing views

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#1902]
**General remarks**
There are two scrollbars in the listing views now which looks strange when viewing in linux browsers.
OS: Fedora 30

![double-scrollbars](https://user-images.githubusercontent.com/1312165/68430627-4342d700-0165-11ea-8af2-65d225a6bb15.png)

**Comment by mtho11** [comment]
I know we have seen issues like this before.

**Comment by lucasponce** [comment]
PLEASE don't move issues to "In Review".
Issues should remain "In Progress" state.
A PR should be linked with the Issue and added to the project, then the PR will be shown under the "In Review" column
