### ISSUE TITLE
[Regression] Metric template not visible in kiali

### ISSUE THREAD

**Issue by FilipB** [kiali/kiali#1904]
**Describe the bug**
All following metrics: oc get metrics -n istio-system
NAME                   AGE
requestcount           9m8s
requestduration        9m12s
requestsize            9m13s
responsesize           9m12s
tcpbytereceived        9m15s
tcpbytesent            9m13s
tcpconnectionsclosed   9m10s
tcpconnectionsopened   9m7s

are not visible in kiali on Istio config page.
Note that this is a regression and those metrics are visible there in kiali 1.0.7

**Versions used**
Kiali-ui
    1.10.0 (b06127a595ce419e94a760b7d4d06be127e86bea)
Kiali
    v1.10.0-SNAPSHOT (404b107d0901e36726abdf89c90d4423004cb161)
OpenShift Service Mesh
    1.0.2 
Kubernetes flavour and version: (e.g. OpenShift Origin 3.9)
OCP 4.2
**To Reproduce**
1. Install OpenShift Service Mesh 1.0.2  with the latest kiali master build
2. run oc get metrics -n istio-system
3. in kiali UI, go to Istio config page

**Expected behavior**
Istio config page in kiali UI should show metrics printed in step 2.

**Comment by lucasponce** [comment]
It is not a regression as Kiali master (Kiali 1.9/1.10) it is expected to work with Istio based 1.3/1.4 distributions.

In Istio 1.3/1.4 these metrics from legacy adapters are now available as "instances" resources which are supported by Kiali.

As example:

```
http://localhost:8080/apis/config.istio.io/v1alpha2/namespaces/istio-system/instances/requestcount
```

And using Kiali:
![image](https://user-images.githubusercontent.com/1662329/68588963-0b9c9d80-048b-11ea-86ba-900f5fd0a021.png)
