### ISSUE TITLE
Incorrect Error Code Returned

### ISSUE THREAD

**Issue by mattmahoneyrh** [kiali/kiali#1906]
There are a few API automation tests that fail when run against the master branch due to the unexpected error codes being returned for some negative tests. The three examples below return the error of 404 in the 1.0 branch, though in master they return an error 500.

api/namespaces/invalid/workloads/details-v1
api/namespaces/invalid/apps/ratings
api/namespaces/invalid/istio/rules/promtcp

E2E Test:  test_api_methods -> test_engative_404

**Comment by lucasponce** [comment]
@mattmahoneyrh I'd need more info about environment

I've just tried master and all results seems ok:

```
GET http://admin:admin@localhost:8000/api/namespaces/invalid/workloads/details-v1

<> 2019-11-11T032814.404.json

###

GET http://admin:admin@localhost:8000/api/namespaces/invalid/apps/ratings

<> 2019-11-11T032837.404.json

###

GET http://admin:admin@localhost:8000/api/namespaces/invalid/istio/rules/promtcp

<> 2019-11-11T032855.404.json

###

```

**Comment by lucasponce** [comment]
I ran the same endpoints with @mattmahoneyrh environment using a kiali external process and a kubectl proxy to connect and kiali's logic seems ok:

```
GET http://admin:admin@localhost:8000/api/namespaces/invalid/workloads/details-v1

<> 2019-11-11T033757.404.json
<> 2019-11-11T032814.404.json

###

GET http://admin:admin@localhost:8000/api/namespaces/invalid/apps/ratings

<> 2019-11-11T033801.404.json
<> 2019-11-11T032837.404.json

###

GET http://admin:admin@localhost:8000/api/namespaces/invalid/istio/rules/promtcp

<> 2019-11-11T033806.404.json
<> 2019-11-11T032855.404.json

###

```

So, I guess that there was some error in the k8s API when Kiali tried to fetch the data.

**Comment by lucasponce** [comment]
Ok, found it, it seems that there is a wrong response type when the namespace is invalid

```
{"error":"Namespace [invalid] is not accessible for Kiali"}
```

Probably that error should return a 40X one instead of 500.

Going to work in a fix.
