### ISSUE TITLE
From VS to Gateway - Page not loaded

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#1911]
Happens on Kiali master.

Go to bookinfo-vs Virtual Service page.
Click on Gateway's 'bookinfo-gateway' link.
It opens Gateway YAML editor, but empty page.
Refresh loads correctly.

![Screenshot from 2019-11-11 12-49-41](https://user-images.githubusercontent.com/604313/68585278-1b63b400-0482-11ea-82be-0688e245c4dc.png)
![Screenshot from 2019-11-11 12-50-00](https://user-images.githubusercontent.com/604313/68585279-1bfc4a80-0482-11ea-8262-55931d3b8c3d.png)

**Comment by aljesusg** [comment]
I can't reproduce it. @lucasponce Did you test this?
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/3019213/68586715-8cf13180-0485-11ea-8ab7-2d42087aa226.gif)

**Comment by lucasponce** [comment]
Testing

**Comment by lucasponce** [comment]
Yes, I can reproduce this.

**Comment by aljesusg** [comment]
ok let me rebuild to check If I can reproduce it

**Comment by hhovsepy** [comment]
When clicking on YAML tab it shows the data.

**Comment by lucasponce** [comment]
I think is related to this https://github.com/kiali/kiali-ui/pull/1543

I'm going to validate it.

**Comment by hhovsepy** [comment]
Verified
