### ISSUE TITLE
Automate sprint creation/closure

### ISSUE THREAD

**Issue by israel-hdez** [kiali/kiali#1913]
Now that the new GitHub workflow looks stable, we could automate the creation of a new *Project* for the next sprint. Also, the previous one could be closed.

Moving unfinished tasks from the finished sprint to the starting one should also be automatic.

**Comment by lucasponce** [comment]
Not sure if I agree.
I prefer that team leads review this and close Sprints manually.

**Comment by lucasponce** [comment]
@israel-hdez we have commented in the grooming that we prefer to maintain this manually to not loose the flexibility we have today reviewing Sprints and adjusting if we need.

Perhaps I'm missing something related to the motivation, feel free to ping me if that's the case.

Thanks.

**Comment by israel-hdez** [comment]
No problem. I was trying to follow up this old Jira: https://issues.jboss.org/browse/KIALI-1382 (which is related, but not really what I exposed here)
If it's better to do it manually in the current workflow, that's quite fine.
