### ISSUE TITLE
How do I display traffic percentages

### ISSUE THREAD

**Issue by bibi520** [kiali/kiali#1921]
How do I get kiali graph to show percent traffic
![image](https://user-images.githubusercontent.com/42456284/68638419-778b0e80-053c-11ea-80ae-8c2dc33b09e4.png)

**Comment by lucasponce** [comment]
@bibi520 did you check "Edge Labels" options ? in the graph toolbar ?

**Comment by bibi520** [comment]
I'm sorry. I made a mistake. I saw it

**Comment by lucasponce** [comment]
@bibi520 nothing to sorry ! Thanks for contacting us for feedback, don't hesitate to open issues or even to access to our rooms to chat with us.

In Kiali.io there are some icons to "contact us" and open an IM tool, we are in FreeNode and also in slack.
