### ISSUE TITLE
Lists - Last row is not shown

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#1922]
Happens on master.
For all object lists, the last row is shown party and values are hidden:
![Screenshot from 2019-11-12 15-17-50](https://user-images.githubusercontent.com/604313/68679204-b54d5e80-055f-11ea-8088-1e3503be8c63.png)

**Comment by lucasponce** [comment]
PLEASE don't move issues to "In Review".
Issues should remain "In Progress" state.
A PR should be linked with the Issue and added to the project, then the PR will be shown under the "In Review" column
