### ISSUE TITLE
Adding an accessible namespace can cause GUI errors 

### ISSUE THREAD

**Issue by jshaughn** [kiali/kiali#1924]
Although I didn't test this on minikube, after some discussion with @lucasponce it is likely this issue occurs only on OpenShift.

To reproduce:
1. created OS 4.2 env on AWS with Istio 1.4
2. build/push/install Kiali operator/kiali built from master

At this point bookinfo doesn't exist and is not an accessible namespace

3, install bookinfo (but I think this could just be the creation of any new namespace)
4. leave kiali UI refreshing at 10s interval on Overview page
5. edit Kiali CR and add:
```
deployment:
  accessible_namespaces:
  - default
  - istio-system
  - bookinfo
```

Go back and watch overview page while kiali operator applies the CR change. Bookinfo card appears but is not filled in, errors generate/repeat for a while, then it settles down.

![image](https://user-images.githubusercontent.com/2104052/68680542-d39b6600-052f-11ea-9154-7b38449f01cc.png)

**Comment by lucasponce** [comment]
This comment from @jmazzitelli is also relevant:
https://github.com/kiali/kiali/pull/1916#issuecomment-552903137
