### ISSUE TITLE
Topic: about monitor redis, mysql,mq

### ISSUE THREAD

**Issue by flyer1212** [kiali/kiali#1926]
hi，sorry to trouble you!
when i deploy the latest kiali, I can see it can monitor  redis, mysql in it's  global graphy, but i can't see  redis ,mysql in jaeger or zipkin, is there any docs to introduce why it can monitor redis and mysql? 
Thank you for your answer!

**Comment by abonas** [comment]
Are you asking about the functionality documentation in Jaeger docs or in Kiali docs?

**Comment by flyer1212** [comment]
oh, i  want to know why Kiali can monitor mysql or mongo , redis  and show them  in the call trace graphy.  but zipkin can't show mysql  or redis in it's   call trace  graphy?

**Comment by abonas** [comment]
@flyer1212 it sounds like a question that should be asked at the Zipkin community. @objectiser any insights?

**Comment by jshaughn** [comment]
Kiali graph can show it because those services have Istio sidecars and so request traffic generates telemetry that Kiali can consume.  Tracing on the other hand may require some further instrumentation of the services such that necessary headers are propagated with the requests.

**Comment by objectiser** [comment]
@flyer1212 Envoy currently does not providing tracing data for these, e.g. see [redis](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/other_protocols/redis) page saying tracing is in the future plans.

Depending upon the language you are using for your service, you could add tracing instrumentation on the client calls. For example https://github.com/opentracing-contrib/java-redis-client.

**Comment by flyer1212** [comment]
ok, thanks for your help，really hope Zipkin can support  redis,mq and mysql soon.
