### ISSUE TITLE
Could not fetch service details with anonymous

### ISSUE THREAD

**Issue by aljesusg** [kiali/kiali#1929]
Could not fetch Service Details.
Kiali-ui 1.9.1 (83c6a25f96163c26b4959d5b89ac67a6a2b52da9)
Kiali v1.9.1 (2431f9b8844202e27ec1c92f404fe7485253ffec)
```bash
Get http://prometheus.istio-system:9090/api/v1/query?query=rate%28istio_requests_total%7Bdestination_service_name%3D%22details%22%2Cdestination_service_namespace%3D%22bookinfo%22%7D%5B60s%5D%29&time=2019-11-13T12%3A47%3A36.183760119Z: net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x00\x02\x02"
```

**Comment by lucasponce** [comment]
It's first time I see this.
Can you add more details about the environment ?

cc @jotak I remember something similar in the past, perhaps something related p8s is missing ?

**Comment by jotak** [comment]
Could be something like sending a http request to a https server?

**Comment by lucasponce** [comment]
@jotak it's what I thought, too.
Perhaps p8s server is protected as well and kiali is not configured properly.

**Comment by aljesusg** [comment]
This is happen when I launch the AWS cluster and I get the latest operator with authentication to anonymous, all other information load correctly but fails here by prometheus

**Comment by jmazzitelli** [comment]
Have you deployed ServiceMesh or upstream Istio? If ServiceMesh, then Prometheus is behind oauth proxy - you need to set up the password. This is what the Makefile does to set up Kiali when installed in a cluster that has Service Mesh:

https://github.com/kiali/kiali/blob/master/operator/Makefile#L152

which is used here:

https://github.com/kiali/kiali/blob/master/operator/deploy/kiali/kiali_cr_dev_servicemesh.yaml#L30-L32

**Comment by aljesusg** [comment]
ok so this happens after update the operator Thanks @jmazzitelli
