### ISSUE TITLE
Lists Order by Health - No Health Tooltip

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#1935]
Happens on master.
List Applications (Workloads, services).
Order by Health.
Mouse over to any of Health icons.
No health tooltip.
![Screenshot from 2019-11-14 13-13-11](https://user-images.githubusercontent.com/604313/68856529-0173dc80-06e1-11ea-9eed-6074c7c42327.png)

**Comment by mtho11** [comment]
I'm looking for tasks and don't see any team/saturn UI stuff so taking this one.

**Comment by mtho11** [comment]
This is a strange one. It is not reproducible in the dev (yarn start) environment. But I do see it in an OCP4 maistra build.

And stranger yet,  it doesn't apply to all health icons but only the first two rows for me.

**Comment by jotak** [comment]
Ah, that would explain why I didn't see it while quickly checking from a dev environment. Strange indeed; as sorting by health involves some async work, promises and the like, probably there's some racy thing

**Comment by mtho11** [comment]
This video shows exactly what is going on since you can't see it in the dev environment:

![tooltip](https://user-images.githubusercontent.com/1312165/69377635-8b7ff000-0c61-11ea-932a-2137c451000e.gif)

**Comment by mtho11** [comment]
At this point, I think it's an interaction thing between the virtual scrolls and the tooltip.

**Comment by mtho11** [comment]
Another interesting behaviour is that there doesn't seem to be any reasoning for which direction the tooltip will be -- sometimes it's on the top sometimes to the side.

![tooltip2](https://user-images.githubusercontent.com/1312165/69379625-a5233680-0c65-11ea-91ba-346e69aa7f04.gif)

**Comment by mtho11** [comment]
@jotak looks like you are correct, looks more like a race condition. My initial thoughts were incorrect about the virtual scrolls and tooltips.

**Comment by abonas** [comment]
@lucasponce I'd like to make sure I understand the process right here - if this was in progress in sprint 31, now it moved to backlog? shouldn't it be in progress in sprint 32 as well? or the work on it is paused?

**Comment by jshaughn** [comment]
@abonas When migrating to the new sprint, I think we just move things over and then adjust during the  sprint planning done with the subteams,

**Comment by lucasponce** [comment]
@mtho11 @jshaughn what is the status of this issue ?

Please, developers should try to update these issues correctly, it creates confusion when you see an issue open and moved from one Sprint to another without any explanation.
