### ISSUE TITLE
Missing Sidecar Icons in List/Detail pages is strange looking

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#1937]
**General remarks**
It looks like the Missing sidecar icons in the listing and detail pages are chopped (missing some pixels on the left). This is minor visual issue.

![Kiali_Console](https://user-images.githubusercontent.com/1312165/68901828-924fb580-06eb-11ea-965e-fbd4c377a5db.png)

![Kiali_Console](https://user-images.githubusercontent.com/1312165/68901803-806e1280-06eb-11ea-901a-0ddf1f5b0765.png)

**Expected Behaviour**
For comparison, see the Missing sidecar Icons in Service graph:
![Kiali_Console](https://user-images.githubusercontent.com/1312165/68901936-d0e57000-06eb-11ea-9063-ba3aac7ba796.png)

**Comment by hhovsepy** [comment]
@lucasponce can this issue be put in backlog of sprint 42?

**Comment by lucasponce** [comment]
@hhovsepy I'm reviewing this one.
You mean that in master (as there were some refactoring) what is broken is the "missin sidecar" icon on lists, isn't it ?

**Comment by lucasponce** [comment]
Ok, this issue was lost in the sea of the Github notifications.
It seems there is a CSS bug:
![image](https://user-images.githubusercontent.com/1662329/97710301-e057f780-1abb-11eb-8df4-faa15f8a10ec.png)

That is cutting the icon on the left, or at least it's what I understand.

**Comment by jshaughn** [comment]
@lucasponce @mtho11 I think this is just the way the icon is.  We use the Blueprint icon (I have no idea why, I don't like this icon for missing sidecar) but this probably is just the way it looks at a certain resolution.   https://www.patternfly.org/v4/guidelines/icons/

In my opinion we should use this issue to change the icon or otherwise just close it.

**Comment by jshaughn** [comment]
@lucasponce @mtho11 Closing as won't fix.  If we ever want to change the icon I'm +1, but more than likely we'll leave it as is for consistency.
