### ISSUE TITLE
Zoomed-in graph view shapes are not aligned with background

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#1938]
**General remarks**
When in the zoomed-in graph view the shape line is a bit skew from the background.

![zoomed](https://user-images.githubusercontent.com/1312165/68903970-7d762080-06f1-11ea-800f-facbaf6a00d2.png)

**Comment by jshaughn** [comment]
@mtho11 That shadow effect is intentional and part of the design.  I'm sure of it but we can get @josejulio to confirm.

**Comment by josejulio** [comment]
Right, that's the "shadow" and is part of the design.

Cytoscape no longer supports shadows for some performance or browser compatibility reason (can't remember which), instead they have this "ghost" effect.

To remove it, only remove the "ghost-*" attributes in the GraphStyle.

**Comment by jshaughn** [comment]
@mtho11 Can we close or did you want to propose removing the ghosting?  That would be a UX discussion.

**Comment by mtho11** [comment]
@jshaughn if it is intentional we can close yes
