### ISSUE TITLE
Support Node.js 12.x for UI builds

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#1946]
**Is your feature request related to a problem? Please describe.**
Now that Node.js 12.x is LTS we should support it for UI builds. 
Note: version 10.x is still LTS as well until April 2020.

![Releases___Node_js](https://user-images.githubusercontent.com/1312165/69106786-4d49bd00-0a24-11ea-872c-2ea2aa2863c2.png)

Anyone with new or updated LTS versions will be on 12.x which is not currently supported.

- [ ] Update Documentation for supported versions of Node.js

**Comment by mtho11** [comment]
The real question here is if we support Node.js 10 _and_ Node.js 12 _or_ if we just move to the latest LTS version 12.x?

CC: @abonas @lucasponce @jshaughn 

It will affect our library modules going forward (especially dependencies)

**Comment by lucasponce** [comment]
I think we have time.
Last time we perform an upgrade like this "react-scripts" we have huge PR with regressions in several areas of the project.

Unless, there is a good reason, I prefer if we release the kiali 1.10, and kiali.1.11 (targetting products) without introducing variables that may create problems.

We can target this for kiali 1.12.

**Comment by lucasponce** [comment]
Why this issue was added to the Sprint ?

**Comment by jshaughn** [comment]
@lucasponce, @mtho11 , +1, I'm not sure this should have been added to the sprint without any triage.  Upgrades can often have unexpected results so it's not something to just do quickly.  Having said that, given a thorough pass by a dev, a full QE sweep and some soak time I'm not against making updates to avoid a rush at a later time.  I'd be OK to have this done early in Sprint 32 but I also think it's reasonable to defer until after the 1.1 product release.

**Comment by cfcosta** [comment]
@lucasponce @jshaughn agree with the priority for the sprint, however the `react-scripts` was a full compiler swap with major code infra changes.

This is a lot less far reaching, and we changed it before (from node8 to node10) without much problems.

**Comment by mtho11** [comment]
I know @jmazzitelli ran into this issue this weekend and had to downgrade. Basically anyone doing javascript/node.js will have this issue trying to develop Kiali-ui. Most users will probably not downgrade. The current version is actually 13.x.
