### ISSUE TITLE
Remove patternfly library keeping RCUE

### ISSUE THREAD

**Issue by aljesusg** [kiali/kiali#1949]
EPIC https://github.com/kiali/kiali/issues/1588

**Comment by mtho11** [comment]
What is the plan for how RCUE works with PF4?

**Comment by aljesusg** [comment]
RCUE is not necessary with PF4 to achieve downstream branding since the changes should be achieved without an additional stylesheet.  Other products are just updating the variables for the product logotype and background image in the masthead.  Color changes and styling updates are not being made for this anymore.  

Anyway let me add you to the email
