### ISSUE TITLE
Scroll in Config YAML Edit page

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#1955]
YAML edit page got scroll back, but it was removed some time ago:
![Screenshot from 2019-11-19 15-56-47](https://user-images.githubusercontent.com/604313/69157545-61092800-0ae5-11ea-831b-861e8e56ace5.png)

**Comment by lucasponce** [comment]
Not a blocker but it's an important regression and usability is impacted.
I'll work on it.

**Comment by jshaughn** [comment]
@lucasponce I think I saw same in workload logs page.  Perhaps our window height calculation is off given greedy PF4.
