### ISSUE TITLE
Browser Crash

### ISSUE THREAD

**Issue by mattmahoneyrh** [kiali/kiali#1956]
Encountered browser crashes when clicking graph edges randomly. This has happened only a couple of times, and totally randomly (i.e. no specific reproduction steps).

"Sorry, there was a problem. Try a refresh or navigate to a different page."

Kiali version:
  Kiali-ui1.10.0 (03e090cd2652a45ed368590b67036837c948044e)
  Kiali v1.10.0-SNAPSHOT (69fdbe70b2c4a58686b5125a0890c11f8f716746)

Browser: Firefox  60.4.0esr  (older version) and 70.0.1

**Browser Console output:**

TypeError
columnNumber: 287178
fileName: "https://kiali-istio-system.apps.ocp43.com/static/js/main.06530e21.chunk.js"
lineNumber: 1
message: "e is null"
stack: "toVCLine@https://https://kiali-istio-system.apps.ocp43.com/static/js/main.06530e21.chunk.js:1:287178\n@https://https://kiali-istio-system.apps.ocp43.com/static/js/main.06530e21.chunk.js:1:398904\nvalue@https://https://kiali-istio-system.apps.ocp43.com/static/js/main.06530e21.chunk.js:1:399735\nba@https://https://kiali-istio-system.apps.ocp43.com/static/js/2.08214a14.chunk.js:1:4769429\nya@https://https://kiali-istio-system.apps.ocp43.com/static/js/2.08214a14.chunk.js:1:4769224\nQc@https://kiali-istio-system.apps.ocp43.com/static/js/2.08214a14.chunk.js:1:4803643\nWc@https://kiali-istio-system.apps.ocp43.com/static/js/2.08214a14.chunk.js:1:4787882\nHc@https://kiali-istio-system.apps.ocp43.com/static/js/2.08214a14.chunk.js:1:4784900\nDc@https://kiali-istio-system.apps.ocp43.com/static/js/2.08214a14.chunk.js:1:4783458\nmo/<@https://kiali-istio-system.apps.ocp43.com/static/js/2.08214a14.chunk.js:1:4745462\nt.unstable_runWithPriority@https://kiali-istio-system.apps.ocp43.com/static/js/2.08214a14.chunk.js:1:4819950\nho@https://kiali-istio-system.apps.ocp43.com/static/js/2.08214a14.chunk.js:1:4745190\nmo@https://kiali-istio-system.apps.ocp43.com/static/js/2.08214a14.chunk.js:1:4745407\ngo@https://kiali-istio-system.apps.ocp43.com/static/js/2.08214a14.chunk.js:1:4745342\nFc@https://kiali-istio-system.apps.ocp43.com/static/js/2.08214a14.chunk.js:1:4783787\nnotify@https://kiali-istio-system.apps.ocp43.com/static/js/2.08214a14.chunk.js:1:449080\nh</t.notifyNestedSubs@https://kiali-istio-system.apps.ocp43.com/static/js/2.08214a14.chunk.js:1:448635\nd</i.notifySubscribers@https://kiali-istio-system.apps.ocp43.com/static/js/2.08214a14.chunk.js:1:450504\nh</t.handleChangeWrapper@https://kiali-istio-system.apps.ocp43.com/static/js/2.08214a14.chunk.js:1:448713\ng@https://kiali-istio-system.apps.ocp43.com/static/js/2.08214a14.chunk.js:1:1975334\nr/</</<@https://kiali-istio-system.apps.ocp43.com/static/js/2.08214a14.chunk.js:1:4426809\nupdateSummary@https://kiali-istio-system.apps.ocp43.com/static/js/main.06530e21.chunk.js:1:352498\nt/a.handleTap@https:/kiali-istio-system.apps.ocp43.com/static/js/main.06530e21.chunk.js:1:340732\nvalue/</t.tapTimeout<@https://kiali-istio-system.apps.ocp43.com/static/js/main.06530e21.chunk.js:1:344917\n"

**Comment by israel-hdez** [comment]
Sounds related to https://github.com/kiali/kiali/issues/1933, which is already closed.
Indicated UI version is older than the fix. So, this may be fixed already.

**Comment by jotak** [comment]
I'm having a look too. `toVCLine` is something in k-charted

**Comment by jotak** [comment]
I've tried to reproduce on master in dev mode, without luck yet.

@israel-hdez @jshaughn I'm not sure, but I suspect that `null` could be here the datapoints provided from `reqRates` here: https://github.com/kiali/kiali-ui/blob/master/src/pages/Graph/SummaryPanelEdge.tsx#L36 (which indeed is nullable) although the commit pointed by Edgar is indeed changing several things in how data is processed. So maybe it's fixed, I'm not sure.

BTW I wonder if it still makes sense to have this `reqRates` nullable as it seems to me that the different reasons why it was so could be covered by state flags `loading` + `metricsLoadError`.

I've only investigated in `SummaryPanelEdge` but I assume the same can be true in the other variants.

**Comment by jshaughn** [comment]
@mattmahoneyrh As @israel-hdez pointed out, the UI version is prior to the fix made recently for crashes related to edge selection.  Unless this can be reproduced with a version post-fix we can assume it is fixed already.

@jotak I'll take a look and see if we can tighten up the handling.
