### ISSUE TITLE
(workflow) Some automation of issue/pr labeling

### ISSUE THREAD

**Issue by israel-hdez** [kiali/kiali#1969]
**Is your feature request related to a problem? Please describe.**
I keep *partially* forgetting to apply labels (it's partially because I usually realize that labels aren't right). 

**Describe the solution you'd like**
Some labeling could be automatic:
* New issues should have `triage` by default (this can be done using the github template)
* New bugs should have `bug` and `backlog` by default (this can be done using the github template)
* When an issue is assigned, the `team/*` label associated with the assignee should be applied.
* When an issue is assigned, the current Sprint project should be applied (or, at least, a warning msg could be generated).
* When a PR is opened, the `team/*` label associated with the opener should be applied.
* When a PR is opened, the assignee of the associated issue should be checked to match.
* When a PR is opened, the current sprint project should be applied.
* When a PR is opened, the `bug`, `enhancement`, `docs` or `maintenance` labels should be inherited from the associated issue.
* When assigning reviewers to a PR, the `team/*` label associated with the reviewer should be applied.

Most label automation would be happening when opening the issue/pr, so it's a one-time action, except for the `team/*` labels. In this case, automatic labeling of a particular `team/*` must become disabled for an issue/PR when a manual adjustment is done.

**Describe alternatives you've considered**
Try to not forget :)

**Comment by lucasponce** [comment]
Please, let's discuss workflow issues in the document we created:
https://docs.google.com/document/d/1ztlgTlUVtSbXioqO9bOFMeZdDInMPtu8iWEkjjitO8E/edit#heading=h.7qq70lsd7kyz

**Comment by jshaughn** [comment]
I agree with Lucas, let's discuss in the doc and reserve the github issue for anything actionable.  I have copied the proposal to the doc and added my comments.

**Comment by israel-hdez** [comment]
Closing as not worthwhile.
