### ISSUE TITLE
add security visualization

### ISSUE THREAD

**Issue by kasriniv** [kiali/kiali#197]
Add security details' visualization to:
a) the service itself
b) the pipe between 2 services
If not secured, mark as such.

**Comment by kasriniv** [comment]
@pilhuhn yes... quick listing of some random thoughts here 
- Mark edge/pipe between 2 edges for mutual TLS or variants
- Mark node for possibly what kind of authentication/authorization is enabled. (Is this redundant and the expectation that only OAuth/OIDC will be used in istio?)
- Mark with say an open lock if a service is not secured  
Hope the request makes sense?. If it does, I can think more about visualizations and revert..

**Comment by abonas** [comment]
created as https://issues.jboss.org/browse/KIALI-750

**Comment by jshaughn** [comment]
I think this is resolved.  We offer a 'Security' toggle in the graph display settings.  If the option is on we show a lock icon on edges with enabled security.  Currently this is working with mutual_tls.  Other security protocols could be added assuming Istio reports it in the telemetry.
