### ISSUE TITLE
Move to, at minimum, Go1.12.13

### ISSUE THREAD

**Issue by israel-hdez** [kiali/kiali#1970]
This issue is mainly for seeking consistency:

* In the README file (https://github.com/kiali/kiali#building) go 1.8.3 is being asked.
* In the Makefile (https://github.com/kiali/kiali/blob/master/Makefile#L26), also, go 1.8.3 is being required.

But:

* If the Jenkins box hasn't changed, the builds are using go 1.12.1.
* Travis is using go 1.12.1 (see https://github.com/kiali/kiali/blob/master/.travis.yml#L9)

The [Go Release Cycle](https://github.com/golang/go/wiki/Go-Release-Cycle#release-maintenance) gives the understanding that, currently, any version prior to go1.12 has reached EoL. So, we shouldn't be mentioning go1.8.

Additionally, since we have not been building Kiali with go 1.8, it even may no longer build with that version.

We should bump to go1.12.13 (which is the latest patch), but if we can move to 1.13 it would be great.

**Comment by jshaughn** [comment]
@israel-hdez This seems fine, I guess this may also be impacted with that issue regarding the Go/Kube versioning.  If we make version updates it should be as early in the sprint as possible.
