### ISSUE TITLE
Ability to invoke wizards from graph

### ISSUE THREAD

**Issue by israel-hdez** [kiali/kiali#1971]
Since the graph context menu has been around for a while, we could use it to invoke the wizards, which would be available only for Service nodes.

**Comment by lucasponce** [comment]
To me this is related to https://github.com/kiali/kiali/issues/1960 as well.

I think we need a global strategy here.

**Comment by lucasponce** [comment]
There are several issues related to actions that probably are involved for this.
As an action for this, I'm going to collect all issues that may affect to put it together for a UX discussion as well.
I will maintain the "discussion needed" and I will assign this to me to collect all info related to the actions.

**Comment by lucasponce** [comment]
Discussed with @jshaughn, today we have two points for entry new configuration: one if under Service Details with invokes the "contextual" wizards (wizards that may generate one or more Istio config, in an abstracted use case for the user), and under the Istio Config list, where user may create objects that don't belong to any specific service.
