### ISSUE TITLE
Details pages - Bottom is cut

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#1977]
Happens on Master.
The bottom side of Details pages (Service, Config, Workloads) seems to be cut and not shown, it feels like scrolling is not finishing there.
![Screenshot from 2019-11-25 10-58-32](https://user-images.githubusercontent.com/604313/69530923-4286af00-0f73-11ea-85d9-64d595fd5ae1.png)
![Screenshot from 2019-11-25 11-01-19](https://user-images.githubusercontent.com/604313/69530925-4286af00-0f73-11ea-98a1-8b88b274bc7a.png)

**Comment by hhovsepy** [comment]
on FF only

**Comment by pbajjuri20** [comment]
I have also faced same issue on Master.

**Comment by lucasponce** [comment]
Yes, there are some styles mixed that introduce this bug.
