### ISSUE TITLE
[UI] Add id for spinner

### ISSUE THREAD

**Issue by FilipB** [kiali/kiali#1978]
UI tests are using xpath (//*[contains(@d, "M304")]) to locate spinner which is working fine everywhere except Graph pages. It would be very helpful to have unique id for the spinner so we can easily test if it's visible.

**Comment by aljesusg** [comment]
@FilipB we can't add an id to the spinner but we can add a name prop. Is it works for you? If not we can check include the spinner inside to a div with the id.

**Comment by aljesusg** [comment]
forgot it we can add a id ^^

**Comment by FilipB** [comment]
Checked on master, updated our automation. It's working fine. Thank you!
