### ISSUE TITLE
Kiali Client Plugin for VS Code

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#1985]
**Is your feature request related to a problem? Please describe.**
It would be cool for developers to see graphs or istio config validations inside VS Code via a plugin. One driving use for this is to get the context of the whole application while working on a particular service. Possibly shift ctrl clicking on a service would take you out to service graph showing you how it is related, it's health, and what Istio configurations is set on those workloads.

More and more tools are being pulled into the VS Code ecosystem via plugins.

**Describe the solution you'd like**
This could be something as simple as just wrapping the kaili-ui and running in Kiosk mode to de-chrome the real-estate of headers/side menus/etc...

**Comment by abonas** [comment]
- Can you elaborate more? What Istio validations/topology do you expect to see in local IDE? it sounds like there is a need to configure remote env and authentication to connect to it?
- topics like would be good to discuss with Che /dev tools teams that are writing plugins.

**Comment by lucasponce** [comment]
And how different would this plugin vs just to have Kiali open with a browser plugin within the IDE ?
Is there any action/signal propagated from IDE to Kiali ?

**Comment by mtho11** [comment]
@lucasponce it is purely a convenience function as are 90% of the VS Code plugins. All of these CLI tools migrate to the IDE as plugins where it is more convenient for the developer. 
For new users or people that only use Kiali every once in a while the plugin could save them from having to know what the kiali url is.

**Comment by jshaughn** [comment]
I am marking this is a Future/Help wanted as I think it's outside of our scope.  @mtho11 this sounds like a Hack&Hustle thing for you :)

**Comment by jshaughn** [comment]
Too far out of scope.
