### ISSUE TITLE
Latest kiali master fails to start (Create resource [role] on [openshift])

### ISSUE THREAD

**Issue by FilipB** [kiali/kiali#1987]
**Describe the bug**
The latest kiali master (7bf520d2249566c607a8f7acadc97f588754b72d) fails to start on OpenShift 4.
Kiali pod is not created and there is following error in kiali operator log:
FAILED - RETRYING: Create resource [role] on [openshift] .....
"roles.rbac.authorization.k8s.io \\\\\\\"kiali\\\\\\\" is forbidden: user \\\\\\\"system:serviceaccount:kiali-operator:kiali-operator\\\\\\\" (groups=[\\\\\\\"system:serviceaccounts\\\\\\\" \\\\\\\"system:serviceaccounts:kiali-operator\\\\\\\" \\\\\\\"system:authenticated\\\\\\\"]) is attempting to grant RBAC permissions not currently held:\\\\n{APIGroups:

Full kiali operator log is attached.
[kiali-operator-768df78cc9-qbw8k-operator.log](https://github.com/kiali/kiali/files/3891703/kiali-operator-768df78cc9-qbw8k-operator.log)

**Versions used**
Kiali: 7bf520d2
Istio: Maistra 1.0.z (the latest)
Kubernetes flavour and version: (e.g. OpenShift Origin 3.9)
OCP 4.1/4.2

1. install kiali-operator
2. install jaeger-operator
3. install istio-operator
4. install control plane

**Expected behavior**
Kiali should be started

**Comment by FilipB** [comment]
Not that it's caused by some recent change, it was working fine yesterday.

**Comment by FilipB** [comment]
Also note that we are using 1.0.z which might be the cause as kiali master is targeting maistra 1.1.z (which is not yet available)

**Comment by jmazzitelli** [comment]
@FilipB How did you install the kiali operator?

We collapsed the resource list in the role now (we use "*" rather than individually specifying them) - this should have increased the number of permissions given. but this was changed yesterday.

**Comment by jmazzitelli** [comment]
NOTE: If you are using the Kiali Operator that is published with Service Mesh (i.e. Kiali Operator 1.0.7) and trying to install a master build of Kiali server, then I'm pretty sure it won't work and will fail with the error you are seeing.

**Comment by FilipB** [comment]
@jmazzitelli I checked our provisioning script and it's building kiali operator from master and using it in following template:
https://gitlab.cee.redhat.com/istio/kiali-qe/kiali-qe-jenkins-dsl/blob/master/src/jenkinsfiles/templates/kiali-operator/kiali-operator.yaml

I guess that's the problem right? We need to use template which is up to date.

**Comment by jmazzitelli** [comment]
@FilipB Yeah, you guys get bit with this all the time :) I'm not sure how, but you should automate this somehow - get your stuff to sync up with the master yaml.

**Comment by jmazzitelli** [comment]
This is due to user-defined operator yaml that was invalid. Nothing to be fixed.
