### ISSUE TITLE
Workload Details - Pods, Services table layout

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#1989]
Happens on master.
Pods and Services table columns layout is broken.
Pods status is not shown.
![Screenshot from 2019-11-27 12-42-14](https://user-images.githubusercontent.com/604313/69721237-b7451f00-1114-11ea-9f01-74fd2042d3fd.png)
![Screenshot from 2019-11-27 12-42-33](https://user-images.githubusercontent.com/604313/69721238-b7451f00-1114-11ea-90f8-b9c68820e6fd.png)

**Comment by lucasponce** [comment]
I'm having some difficulties to reproduce this one.
How it happens ? Which browser and which resolution ?
It's at 100% or any other zoom ?

**Comment by lucasponce** [comment]
Some screenshoots from my tests:
![image](https://user-images.githubusercontent.com/1662329/69814163-eb434180-11f3-11ea-9775-cc4de68ad184.png)

![image](https://user-images.githubusercontent.com/1662329/69814212-ff873e80-11f3-11ea-8365-c59cb970f7de.png)

In FF:

![image](https://user-images.githubusercontent.com/1662329/69814301-31000a00-11f4-11ea-863d-5e3512192e5b.png)

![image](https://user-images.githubusercontent.com/1662329/69814357-50973280-11f4-11ea-8b76-ef271bdb8b4e.png)

I see that when we re-size the window browser too fast there is some lag (expected) until the event is propagated and the the navigation menu is collapsed and current view updated. In some case, it looks like that the event and the resize can be "cancelled" for some reason, but resizing seems to be back to the normal size.

So, let me know if this one can be reproduced consistently and I can take a closer look.

**Comment by hhovsepy** [comment]
This happens constantly on FF and chrome, in 100% and full window, without resizing.
So there are two problems:
1. "Running" Phase.
2. Missing Status icon.

**Comment by lucasponce** [comment]
Ah, ok, thanks for clarification, I guess I misinterpreted the issue.
