### ISSUE TITLE
FF - Filter dropdown does not open

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#1997]
Happens on master and FF only.
Click on any dropdown, for instance "Workload Name" filter in Workloads page.
It does not open.

**Comment by lucasponce** [comment]
@hhovsepy not sure if I understand, "Workload Name" is not a dropdown, but an inputtext.
Others filter seem to work here.

**Comment by hhovsepy** [comment]
@lucasponce thanks, it seems some cache problem on my browser. Reinstalling kiali helped.
