### ISSUE TITLE
Search Traces button fixed

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#1999]
Happens on master.
Open Traces tab, search for some traces.
Scroll the page.
"Search Traces" button has a fixed position.
![Screenshot from 2019-12-02 17-43-29](https://user-images.githubusercontent.com/604313/69977739-a1c46080-152b-11ea-819c-853257195fb1.png)

**Comment by lucasponce** [comment]
@hhovsepy I think this one will be gone in the work @aljesusg is doing for this Sprint in #1855

**Comment by lucasponce** [comment]
@aljesusg I think this should be included in #1855 work for this Sprint.

**Comment by aljesusg** [comment]
This will be close by https://github.com/kiali/kiali-ui/pull/1577
