### ISSUE TITLE
hack/aws error in oc version

### ISSUE THREAD

**Issue by aljesusg** [kiali/kiali#2008]
```bash
HACK: ===== WARNING =====
HACK: You already have the OpenShift oc client but it does not match the version you want.
HACK: This appears incorrect: /home/aljesusg/openshift/4.2.4/oc
HACK: The version of the oc client is: 4.2.2
HACK: You asked for version: 4.2.4 (4.2.4)
HACK: ===== WARNING =====

```
But the version 4.2.4 says that version is **4.2.2** !!! 

```bash
aljesusg@localhost:~/Projects/kiali$ /home/aljesusg/openshift/4.2.4/oc version --client
Client Version: openshift-clients-4.2.2-201910250432
```

cc @jmazzitelli

**Comment by jmazzitelli** [comment]
known issue - this is why we ignore this warning by default. the way openshift installer is build and published, the versions are all different than what an end user will expect.

**Comment by jmazzitelli** [comment]
see: https://github.com/kiali/kiali/pull/1972 and https://github.com/kiali/kiali/pull/1964
there is a thread on slack with the openshift installer folks about this too - from a couple weeks ago. The version that oc reports is different than what you think you downloaded. It's weird, but that is the way it is.
