### ISSUE TITLE
Credential exposure in error responses

### ISSUE THREAD

**Issue by todkap** [kiali/kiali#201]
Prior to setting the appropriate ClusterRoles, I was receiving permission denied to some of the dashboard views.   In debugging this, I found that Kiali appears to be leaking the userid/password to the client.    Probably need to scrub/cleanse error responses in this case.

ServiceListComponent.tsx:237 {"config":{"transformRequest":{},"transformResponse":{},"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json;charset=utf-8","Authorization":"Basic YWRtaW46YWRtaW4="},"method":"get","url":"/api/namespaces/default/services","data":"{}","params":{},"auth":{"username":"admin","password":"admin"}},"request":{},"response":{"data":{"error":"deployments.apps is forbidden: User \"system:serviceaccount:istio-system:kiali\" cannot list deployments.apps in the namespace \"default\""},"status":500,"statusText":"Internal Server Error","headers":{"date":"Fri, 18 May 2018 19:03:56 GMT","content-length":"150","content-type":"application/json"},"config":{"transformRequest":{},"transformResponse":{},"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json;charset=utf-8","Authorization":"Basic YWRtaW46YWRtaW4="},"method":"get","url":"/api/namespaces/default/services","data":"{}","params":{},"auth":{"username":"admin","password":"admin"}},"request":{}}}

**Comment by lucasponce** [comment]
@todkap Thanks for reporting this.
I think is related to this issue https://issues.jboss.org/browse/KIALI-747

**Comment by pilhuhn** [comment]
I have opened https://issues.jboss.org/browse/KIALI-834 to track this, as this must not happen even if KIALI-747 is the culprit that is used to expose the issue.

**Comment by israel-hdez** [comment]
Closing because has been solved with kiali/kiali-ui#394
