### ISSUE TITLE
Application labeling should be based on app.kubernetes.io/part-of rather than "app"

### ISSUE THREAD

**Issue by serenamarie125** [kiali/kiali#2012]
Application labeling should be based on app.kubernetes.io/part-of rather than "app".  This will help with alignment with the Kubernetes application labeling recommendation (app.kubernetes.io/part-of), OpenShift console and odo (and other tools are starting to use it like VMware's Octant web ui)

**Comment by serenamarie125** [comment]
FYI @sspeiche

**Comment by jmazzitelli** [comment]
is there documentation about this "part-of"? I've seen `app.kubernetes.io/name` and we were eventually going to move to that, but "part-of" is new to me. Is that an additional label (additional to `app.kubernetes.io/name`) or does it take its place?

**Comment by sspeiche** [comment]
There is the main kubernetes documentation at https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#applications-and-instances-of-applications and some supplemental docs at https://github.com/gorkem/app-labels/blob/master/labels-annotation-for-openshift.adoc

**Comment by jshaughn** [comment]
I think the istio "app" label, and the way it is used, is more equivalent to app.kubernetes.io/name.  Having said that, Kiali allows you to configure your app label name to be  anything you like, including app.kubernetes.io/part-of.  The only gotcha is that we require consistent labeling across the definitions.

Maybe more important is [this current Istio proposal](https://docs.google.com/document/d/1EsKpYNW55-LqG08zdjp1tAd224T9IEG3CEnusmL-Joc).  It seems it will be approved and it means (iiuc) that a mixture or labels could be in play and will be used to populate a single "canonical service" label.  As such, consuming tooling (aka Kiali) should just be able to use the canonical label and not worry about the way it was populated.  The same canonical name would be used in telemetry, basically replacing "destination_app", for example.

I'm not sure we should take any action on this issue until we see the outcome of this canonical service proposal.

Actually displaying the part-of label should be a no-op, we already display labels.

**Comment by abonas** [comment]
@serenamarie125 @sspeiche I am not sure what is the exact ask here, as it can be interpreted in various ways. Let me try to elaborate how Kiali works with labels, maybe it will clarify this:

As noted above, Kiali is already displaying all labels of the objects.
Regarding the app label, the label name is set on Istio side. Shall it change, Kiali has the flexibility to adapt to it and consume the non default name as @jmazzitelli noted , but again - this has to also be done on Istio side as this is how it is used by Istio and reported to telemetry by Istio (from where Kiali is consuming the data).
A thread where @jmazzitelli  is explaining it in greater detail is here:
https://discuss.istio.io/t/ability-to-change-istio-app-version-labels/1139/2

From my perspective, as long as Istio is not adopting k8s labeling recommendation, for Kiali this is a no-op and this issue should be closed. I recommend taking this ask first to upstream Istio or via Maistra team.

**Comment by lucasponce** [comment]
I guess that we need to follow first what Istio recommends, as discussed not sure what we can do from Kiali.

I suggest to close this one and re-open when Istio upstream moves in some direction.
