### ISSUE TITLE
Enhance navigation in Istio Config / Validations

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#2014]
Maybe we can enhance the overall navigation experience with the istio config statuses.

When first we see a config issue from the Overview page, we need to change to another menu (Istio Config, or Services) to navigate to the issue. That could be more straightforward by clicking on the "Istio Config status" label and/or warning/error icon, jumping directly to something like `/console/istio?namespaces=bookinfo`.

Then, when we're on the Istio Config list page, here again we could make the icon clickable to bring us to the related page (same destination as the first-column item link, e.g. https://localhost:20001/kiali/console/namespaces/bookinfo/istio/gateways/bookinfo-gateway ) ; I think it's quite common that the user intents to click on error/warning icons to get more details.

**Comment by jotak** [comment]
ping @xeviknal @lucasponce

**Comment by xeviknal** [comment]
It sounds very natural/organic. I can take this one on. Good catch!

**Comment by lucasponce** [comment]
>Then, when we're on the Istio Config list page, here again we could make the icon clickable to bring us to the related page (same destination as the first-column item link, e.g. https://localhost:20001/kiali/console/namespaces/bookinfo/istio/gateways/bookinfo-gateway ) ; I think it's quite common that the user intents to click on error/warning icons to get more details.

You mean to click here the list and position in the details yaml page with the error line ?

First part of the issue is +1.

**Comment by jotak** [comment]
@lucasponce @xeviknal  sorry I'm seeing the replies only now.
I only mean having a link to the YAML page but not necessarily scrolled down to the error (that could be a bonus, but would raise the question of electing an error to scroll to among multiple ones, honestly I'm not sure it's worth it). So, just the exact same link as the name field would be nice IMO.
