### ISSUE TITLE
Console error on Istio Config page

### ISSUE THREAD

**Issue by cfcosta** [kiali/kiali#2018]
![console-error-istio-config-page](https://user-images.githubusercontent.com/14752/70547878-6d1a5f80-1b50-11ea-98f6-c7b85f9b9b21.png)

Steps to replicate the error:
1 - Use default bookinfo deploy (I'm using the one on `hack/k8s-minishift.sh`, but it shouldn't make a difference which one).
2 - On Kiali, click "Istio Config" and select the "bookinfo" Virtual Service.
3 - Press F12, check console output.

**Comment by pbajjuri20** [comment]
According to this PR, I am unable to replicate.
