### ISSUE TITLE
Console error on small charts

### ISSUE THREAD

**Issue by cfcosta** [kiali/kiali#2019]
This error happens when hovering the mouse over one of the points on the sparkline graphs in the Overview Page:

![error2](https://user-images.githubusercontent.com/14752/70548766-e36b9180-1b51-11ea-8fae-f6685648bb71.png)

It does not affect functionality, and the fixes mean to center manually the tooltip origin every time which is error-prone and not very reliable.

The setup is consistent on our side (open the overview page, mouse over the sparkline graph, check console), but I tried many ways to replicate the same error in smaller proportions both on Patternfly and Victory itself, with no success. Seems to be something related to the `constrainToVisibleArea` property on `ChartTooltip`, but could not pinpoint exactly where the error might be.

**Comment by jshaughn** [comment]
Another Victory issue, probably related to https://github.com/kiali/kiali/issues/2091.  Check after 2091 is reolved.

**Comment by israel-hdez** [comment]
I'm not seeing this. Closing...
