### ISSUE TITLE
why not show workloads for one app "statefulset"?

### ISSUE THREAD

**Issue by lwx294821** [kiali/kiali#2023]
Deploy kafka cluster  in k8s with StatefulSet resource, but  Kiali shows "No workloads found for this app",who can tell me the reason?

Kiali version: 1.9.1

**Comment by lucasponce** [comment]
Yes, it's a pure configuration for performance that you can change at:
https://github.com/kiali/kiali/blob/master/operator/deploy/kiali/kiali_cr.yaml#L478

To reduce the # of queries to the Kubernetes API, Kiali can configure the list of controllers to fetch (if we know that a namespace don't use stateful controllers).

It's configurable, just modify Kiali config and that should be done.

**Comment by lwx294821** [comment]
Thank you very much.
