### ISSUE TITLE
Build error on MacOS

### ISSUE THREAD

**Issue by liyork** [kiali/kiali#2025]
**Is your feature request related to a problem? Please describe.**
when i use  build kiali,i occur the error ,finally to find the build may not support maxos?

**Describe the solution you'd like**
maybe consider judge the os system ,and then support in
``
.download-operator-sdk-if-needed
``
using the flow
``
curl -L https://github.com/operator-framework/operator-sdk/releases/download/v0.12.0/operator-sdk-v0.12.0-x86_64-apple-darwin
``

**Describe alternatives you've considered**
may be i tech is low ,only the suggest.

**Additional context**
thanks for a lots.

i use the `docker for mac + k8s`，i pull the master seeing the refector！
if i show using the minikube?

**Comment by liyork** [comment]
i finally use setup an minikube in macos.thanks.

**Comment by lucasponce** [comment]
Thank you for the isssue.
Can you describe when you experiment the problem ?

If you could workaround the problem would you mind to post the steps here or also happy if you can help us with some PR to adjust / tweak some parameter for MacOS, we can comment on the code if necessary.

**Comment by liyork** [comment]
hi，this is my manual build.

######前置条件
go/git/docker/make
k8s+istio
参见mac安装docker+k8s
istio1.4简易安装.md

######build
1. kiali工程下载安装
export GOPATH=/Users/lichao30/goland_workspace/kiali
mkdir -p $GOPATH
cd GOPATH
mkdir -p src/github.com/kiali
git clone git@github.com:kiali/kiali
export PATH=$PATH:$GOPATH/bin

2. Install Glide - the Go dependency management tool that Kiali uses to build itself
cd ${GOPATH}/src/github.com/kiali/kiali
make dep-install

2-back. Tell the dependency manager tool to update the Kiali dependencies
Note:You should only run this command if you add, remove, or modify a dependency. 

cd ${GOPATH}/src/github.com/kiali/kiali
make dep-update

4. Build Kiali
cd ${GOPATH}/src/github.com/kiali/kiali
make build

5. run the Kiali tests

cd ${GOPATH}/src/github.com/kiali/kiali
make test

######Running on Kubernetes
1. Building the Container Image
builds the Kiali/Kiali operator image, too.

cd ${GOPATH}/src/github.com/kiali/kiali
make container-build

2. Running on OpenShift or Kubernetes/Minikube
minikube addons enable registry
minikube addons enable ingress
host配置 127.0.0.1 kiali

3. Pushing Kiali operator and Kiali images to your cluster

cd ${GOPATH}/src/github.com/kiali/kiali
--make cluster-push
IS_MINIKUBE=true make cluster-push

4. Deploying Kiali operator to your cluster
cd ${GOPATH}/src/github.com/kiali/kiali/operator
IS_MINIKUBE=true make operator-create

5. Deploying Kiali to your cluster
cd ${GOPATH}/src/github.com/kiali/kiali/operator
--make kiali-create
IS_MINIKUBE=true AUTH_STRATEGY=login make kiali-create

查看:kubectl get pods --all-namespaces |grep kiali

然后修改下kiali的svc为nodePort，访问：https://kiali:31000/kiali
输入admin/admin即可登录。

6. Removing Kiali from your cluster
cd ${GOPATH}/src/github.com/kiali/kiali/operator
make kiali-delete

或者using the oc/kubectl command to delete
cd ${GOPATH}/src/github.com/kiali/kiali/operator
make kiali-purge

6. Reloading Kiali image in Kubernetes
If you already have Kiali installed but you want to recreate the pod with a new container image, you can run the following command:

cd ${GOPATH}/src/github.com/kiali/kiali
make kiali-reload-image

6. Removing Kiali operator from your cluster
cd ${GOPATH}/src/github.com/kiali/kiali/operator
make operator-delete

5. Running Standalone
Rarely, yoou may want to run Kiali outside of any cluster environment, perhaps for debugging purposes
cd ${GOPATH}/src/github.com/kiali/kiali
make install
make run

The "install" target installs the Kiali executable in your GOPATH /bin directory so you can run it outside of the Makefile:
cd ${GOPATH}/src/github.com/kiali/kiali
make install
${GOPATH}/bin/kiali -config <your-config-file>

######Configuration
Many configuration settings can optionally be set within the Kiali Operator custom resource (CR) file. See this example Kiali CR file that has all the configuration settings documented.

1. Embedding Kiali
If you want to embed Kiali in other applications, Kiali offers a simple feature called Kiosk mode. 
In this mode, Kiali won’t show the main header, nor the main navigation bar.

To enable Kiosk mode, you only need to add a kiosk=true URL parameter. 
如：http://kiali_path/graph/namespaces?namespaces=bookinfo&kiosk=true.

2. Configure External Services
+. Jaeger
If you have Jaeger installed in a custom way that is not easily auto-detectable by Kiali, you need to change in the Kiali CR the value of the jaeger > url

apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
spec:
...
    external_services:
      jaeger:
        url: http://jaeger-query-istio-system.127.0.0.1.nip.io
...


+. Grafana
If you have Grafana installed in a custom way that is not easily auto-detectable by Kiali, you need to change in the Kiali CR the value of the grafana > url

apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
spec:
...
    external_services:
      grafana:
        url: http://grafana-istio-system.127.0.0.1.nip.io
...

2. Configure your services
Your services must be annotated with the type of API ('rest', 'grpc', 'graphql') and a URL to the spec of the API. 
If the API spec is served from the service itself, Kiali will infer the hostname and port :

apiVersion: v1
kind: Service
metadata:
  name: myservice
  annotations:
    kiali.io/api-type: rest
    kiali.io/api-spec: /v1/api-spec
spec:
...
The API spec can also be served from any http/s URL, internal or external to the cluster :

apiVersion: v1
kind: Service
metadata:
  name: petstore
  annotations:
    kiali.io/api-type: rest
    kiali.io/api-spec: https://petstore.swagger.io/v2/swagger.json
spec:
...
For now, only REST APIs have their spec displayed but we are working to support gRpc and GraphQL soon. 
A live console to test your APIs directly with Kiali is also being worked on.

2. Customize API docs annotations
You can configure Kiali to use your own annotation names with the Kiali CR

...
apidocs:
  annotations:
    api_spec_annotation_name: "my-annotation-for-api-spec"
    api_type_annotation_name: "my-annotation-for-api-type"
...

2. Customize the UI web context root
By default Kiali UI is deployed to the top level of https://kiali-istio-system.<your_cluster_domain_or_ip>/. 
In some situations such as when you want to serve Kiali UI along with other apps under the same host name, e.g., example.com/kiali, example.com/app1, 
you can edit Kiali Config Map and provide a different value for web_root. Note: the path must begin with a / and not end with / (e.g. /kiali).

An example of custom web root:
...
server:
  web_root: /kiali
...

2. Running the UI Outside the Core
When developing the Kiali UI you will find it useful to run it outside of the core to make it easier to update the UI code and see the changes without having to recompile. The prefered approach for this is to use a proxy on the UI to mount the core. The process is described here.

To connect with the backend and avoid the javascript prompt requesting authentication you need to send the requests with a specific header.

X-Auth-Type-Kiali-UI: 1
The response will contain the header

WWW-Authenticate: xBasic realm="Kiali"
Otherwise the header will be

WWW-Authenticate: Basic realm="Kiali"

3. Running A Locally Built UI Inside the Core
If you are developing the UI on your local machine but you want to see it deployed and running inside of the core server, 
you can do so by setting the environment variable CONSOLE_VERSION to the value "local" when building the container image via the docker-build target. 
By default, your UI’s build/ directory is assumed to be in a directory called kiali-ui that is a peer directory of the GOPATH root directory for the core server. 
If it is not, you can set the environment variable CONSOLE_LOCAL_DIR to the value of the path of the root directory for the UI such that $CONSOLE_LOCAL_DIR/build 
contains the generated build files for the UI.

For example, if your GOPATH directory for the Kiali project is /source/kiali/kiali and you have git cloned the Kiali UI repository in /source/kiali/kiali-ui 
then you do not need to set CONSOLE_LOCAL_DIR. You can embed your locally built console into the core container image via:
CONSOLE_VERSION=local make docker-build

If you git cloned the Kiali UI repository in directory /my/git/repo and have built the UI there (such that the build files are located at /my/git/repo/build) 
then you can embed that locally built console into the core container image via:
CONSOLE_VERSION=local CONSOLE_LOCAL_DIR=/my/git/repo make docker-build

4. Disabling SSL
In the provided Kubernetes templates, SSL is turned on by default. If you want to turn it off, you should:

Remove the "identity" block, with certificate paths, from the Kiali Config Map.

Optionally you can also remove the volume that is declared and mounted in Kiali Deployment 
(the name of the volume and mount are both "kiali-cert". If you don’t remove these, they will just be ignored.


######错误
1. IS_MINIKUBE=true make cluster-push时报错
Get https://192.168.64.7:5000/v2/: http: server gave HTTP response to HTTPS client
参见(docker私有镜像库.md)的错误

2. 
Warning: Failed to set locale category LC_NUMERIC to en_CN

3. make container-build可能遇到问题
需要修改curl路径。
使用https://github.com/operator-framework/operator-sdk/releases/download/v0.12.0/operator-sdk-v0.12.0-x86_64-apple-darwin

**Comment by jmazzitelli** [comment]
> Get https://192.168.64.7:5000/v2/: http: server gave HTTP response to HTTPS client

That error is most likely due to the fact you do not have your Minikube image registry endpoint (192.168.64.7:5000) listed as an "insecure registry" in your docker daemon configuration. You need to tell docker that the minikube registry is an insecure registry for this to work.

**Comment by liyork** [comment]
when i install kiali from the official manual without a hitch,only a little in macos error,
through the other searching fix it.
i wish kiali can support the mac better better,thanks .

**Comment by liyork** [comment]
> > Get https://192.168.64.7:5000/v2/: http: server gave HTTP response to HTTPS client
> 
> That error is most likely due to the fact you do not have your Minikube image registry endpoint (192.168.64.7:5000) listed as an "insecure registry" in your docker daemon configuration. You need to tell docker that the minikube registry is an insecure registry for this to work.

hi,thanks you to reply.
i may not explain the appropriate the section.
the `error` section is for the describing the error and fix processing.

**Comment by liyork** [comment]
may be effective/help for your team.

**Comment by jshaughn** [comment]
@liyork Are there any updatesto this?  is it still a problem?

**Comment by jshaughn** [comment]
@liyork  Assuming issue is resolved and closing. Please feel free to re-open if you have updates.
