### ISSUE TITLE
Is there a go client  API that can call kilai API to get json response?

### ISSUE THREAD

**Issue by lwx294821** [kiali/kiali#2027]
I  hope  a go client for calling kiali API,is there a ready-made client?

**Comment by lucasponce** [comment]
Hello,

If you mean a go client to wrap the REST Kiali API, not, there is not a client for that.
Kiali API is intended to be used with Kiali UI, it's not a "formal public API" in the sense that provides strong versioning on backward compatibility.

So, Kiali API endpoints may change between versions due Kiali UI changes.

I think we would need a kiali-client separated go package if we want to have something like that.

Would you be interested to collaborate to implement a kiali-api-client if maintainers decide that could be a good idea ?

**Comment by lwx294821** [comment]
I am a newer to know Kiali and I have the opportunity to cooperate in the future.Thank you very much.
Now I'm writing a little code to call Kiali API to see  Kiali internal data structure.

**Comment by cfcosta** [comment]
There was/is a python client that @gbaufake used for testing: https://github.com/kiali/kiali-client-python
But I'm not sure if it is up to date, the last commit was in June.

**Comment by jotak** [comment]
just thinking out loud, isn't it possible to auto-generate a go client from swagger? Looking at that: https://swagger.io/tools/swagger-codegen/

**Comment by lwx294821** [comment]
@cfcosta I know that python client,but I more likely need a go client .Thank you all the same.
