### ISSUE TITLE
3scale extension can be detected at startup only

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#2032]
Kiali implemented 3scale extension thinking that an adapter can be enabled dynamically at anytime.
It's reasonable to add a config flag that can be checked in a one time operation.

This would save some calls to the backend from the service details page.

So, if a 3scale adapter is deployed, Kiali config should be updated and pod restarted.

**Comment by abonas** [comment]
Is the case that 3scale is enabled when Kiali starts, but then disabled afterwards, taken into considered?

**Comment by lucasponce** [comment]
@abonas if the 3scale configuration is enabled/disabled from Maistra as recommended from the doc, yes, it should.

Kiali would save for querying dynamically on every service details page if this extension is enabled.

**Comment by lucasponce** [comment]
Closing in favor of #2146
