### ISSUE TITLE
What does this +Inf mean

### ISSUE THREAD

**Issue by sniperking1234** [kiali/kiali#2038]
**Describe the bug**
When I looked at the metrics interface, I found `+Inf` in the average values. What does this +Inf mean?
![image](https://user-images.githubusercontent.com/7834655/70957917-96883d80-20b2-11ea-958b-163f5488ae79.png)

**Versions used**
Kiali: v1.10.0
Istio: 1.1.2

**Comment by jmazzitelli** [comment]
What is the API endpoint you requested to get that JSON? I assume it was not a graph API, but probably something akin to what the Kiali metric detail pages request.

**Comment by sniperking1234** [comment]
@jmazzitelli This appears when I click on the line on the graph. 
`Request URL: http://10.110.25.71:28192/kiali/api/namespaces/iop/services/cir-api/metrics?queryTime=1576546588&duration=21600&step=720&rateInterval=720s&filters[]=request_count&filters[]=request_duration&filters[]=request_duration_millis&filters[]=request_error_count&quantiles[]=0.5&quantiles[]=0.95&quantiles[]=0.99&byLabels[]=source_workload&direction=inbound&reporter=source&requestProtocol=http`

**Comment by jmazzitelli** [comment]
> This appears when I click on the line on the graph

Are you saying when you click a line on the graph, you go to a page with that raw JSON that you show in your original description? That's weird. I didn't think our graph edges direct you to a raw JSON page - I thought it updates the right-side summary panel. 

Just so I'm clear - when you say "click on a line on a graph" - you mean clicking on one of the green edges on the graph - one of these lines?

![image](https://user-images.githubusercontent.com/2029470/70960598-7a9e8080-204d-11ea-872c-1dbff0b8746d.png)

Or do you mean "line on a graph" on one of the detail pages? Like something here (I didn't think you could click on these lines and get raw JSON either):

![image](https://user-images.githubusercontent.com/2029470/70960721-d0732880-204d-11ea-98d1-c2c75eec8b3d.png)

**Comment by sniperking1234** [comment]
@jmazzitelli It's not that complicated. I just clicked one of the edges on the graph and saw data through development tools.
![image](https://user-images.githubusercontent.com/7834655/70961161-f505e980-20bb-11ea-8fe5-04646218dad4.png)

**Comment by jotak** [comment]
`+Inf` means +infinite. It's the first time I see that in our context.
What happens under the hood here for this "avg" metric, is that we run this promql expression:

`sum(rate(istio_request_duration_seconds_sum{XXX}[720s])) by (source_workload) / sum(rate(istio_request_duration_seconds_count{XXX}[720s])) by (source_workload)`

with `XXX` being some labels to filter on your namespace and services.

I'm not sure when `+Inf` can be returned. I'd guess that a 0 divisor would result in `NaN` rather than `+Inf`. Maybe @simonpasquier has an idea?

**Comment by simonpasquier** [comment]
`+Inf` means that the result is greater than the maximum float64 value (e.g. `very big value / very small value`).

**Comment by jotak** [comment]
It makes sense

@sniperking1234 I'm not sure to understand if this is a problem that somehow breaks the UI, or you just asked out of curiosity?

**Comment by sniperking1234** [comment]
@jmazzitelli I just wonder why there is such a large response time when my service is normal.

**Comment by sniperking1234** [comment]
UI is normal.

**Comment by lucasponce** [comment]
Not sure if this issues requires an action.

**Comment by jshaughn** [comment]
@sniperking1234 Feel free to reopen if necessary, it was closed because we've been unable to reproduce.
