### ISSUE TITLE
Contributing guide is outdated

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#2040]
Kiali contributing guide is not updated and it is preventing other folks to jump into the project:

https://github.com/kiali/kiali/blob/master/CONTRIBUTING.md

**Comment by lucasponce** [comment]
<nttb> Hey, quick question. I want to build my own Kiali UI, so I cloned both the Kiali and the Kiali UI repo. I made some changes to the UI, and then went through the steps described on the github page regarding building kiali with the local UI (calling make docker-build with CONSOLE_VERSION=local). However, when I go through the rest of the steps to
<nttb> deploy kiali (deploy operator, create kiali) it doesn't seem to take my local version into consideration. I used Kiali-UI v1.10 and Kiali v.1.10, however the version description on the deployed Kiali UI doesn't match these versions. Am I missing anything simple?

**Comment by jotak** [comment]
Personally I do something like this now, to deploy to minikube:

`IS_MINIKUBE=true DORP=podman CONSOLE_LOCAL_DIR=/path/to/ui CONSOLE_VERSION=local make clean build cluster-push operator-create kiali-create`

(remove DORP=podman if you use docker)

**Comment by abonas** [comment]
@jotak can you provide a few specific points that need to be updated?

**Comment by jotak** [comment]
Actually I think it's more this section which is outdated: https://github.com/kiali/kiali#running-a-locally-built-ui-inside-the-core

(make docker-build doesn't exist anymore)

**Comment by jshaughn** [comment]
I assigned it to @jmazzitelli , he should be able to clear things up.

**Comment by jmazzitelli** [comment]
see PR #2042 for the changes to the README.
