### ISSUE TITLE
User Interface to apply authorization policy of Istio

### ISSUE THREAD

**Issue by matty111** [kiali/kiali#2041]
Is it possible to deploy authorization policy of Istio by kiali?

**Comment by lucasponce** [comment]
Not yet, it's limited but we are working to extend the actions on configuration scenarios that are beyond Services, like the authorization policy.

The main issue related to this is https://github.com/kiali/kiali/issues/1380 in case you want to track this.

When we resolve how to manage resources that don't belong to a service but a namespace we can open new scenarios like this.

**Comment by xeviknal** [comment]
@matty111 We are also working in https://github.com/kiali/kiali-ui/pull/1582. You will be able to browse, edit and delete AuthorizationPolicies once it is merged.

**Comment by matty111** [comment]
@xeviknal it will wonderful if from ui (link service-to-service), I can apply the policy. For example with policy deny-all applied, I can apply permissive policy with the mouse.
I suggest this feature and thank you  for the replay

**Comment by lucasponce** [comment]
@matty111 can you mock up your suggestion ? where you envision could be suitable to apply this feature ?

Service level or namespace level ?

Perhaps we can use your inputs in the current work we are doing.

Thanks !

Lucas

**Comment by matty111** [comment]
I don't know your code in the deep, but an authorization policy of istio work with the label and the policy allow at the serviceAccount (and i think all the service of this) in the namespace to access to workload  of services with that label.


I think kiali to act as middleware and with the user interface create the yaml file of policy and apply it. The level I thought was a problem of istio and not of kiali

**Comment by lucasponce** [comment]
So we are prototyping with namespace level of Istio objects.
Do you see something like this useful ?
![image](https://user-images.githubusercontent.com/1662329/71084875-8184da80-2196-11ea-8135-9a885d2e3808.png)
I mean, the Authorization Policy can be selected from there and we can define a high level driven use case with the common / more used scenarios.

Then yaml config would be created and also it would be available to users to be edited with details if needed.

**Comment by matty111** [comment]
Yes, this is useful and i think that the policy can to be applied also in the graph with a click on the arrow between the services

**Comment by lucasponce** [comment]
> Yes, this is useful and i think that the policy can to be applied also in the graph with a click on the arrow between the services

Thanks for the feedback.
We are re-organizing the Wizards.
At the moment, you need to go to Service Details to fetch context of the service (Service + Workloads + Istio Config attached + Validations).
Also, we have objects that don't belong/link to a service but are namespace oriented, that's current work.

When all of these use cases are addressed we plan to interact from the graph but that will be in a next step once we have consolidated all of these use cases first.

**Comment by kaz-33** [comment]
Hello, have you moved forward for this helpful feature?
I'm playing a bit with the authorization policy and the best way to define it is to select "from service account" and target "service".
The namespace is too highlevel, and it wouldn't make sense to create one namespace per Pod...

**Comment by kaz-33** [comment]
I remove  my previous message, i saw the 'menu' for the authorizationPolicy.
 But the question, because kiali see the traffic between the POD, kiali could  activate the Authorization Policy with manual validation?
We can imagine:
kiali monitor the traffic, 
Kiali display the traffic on a dedicate page, 
Human click (or modify) the rigth policy between POD
kiali apply to the network...

**Comment by lucasponce** [comment]
@kaz-33 Right now Kiali allows two modes to apply AuthorizationPolicy objects:
- From the namespace, where it detect the current traffic and create a set of AP objects for current workloads.
- Manually from the Istio Config, where user could define a full AP.

In any case those can be modifed later by the user to adjust them.

Perhaps you are suggesting to enable this feature i.e. per Service/Workload level as well ?

**Comment by kaz-33** [comment]
Idea are 
1) to have a full list of flow matrix
2) to export in text file or yaml file by connectivity (we can create manually the AP yaml file and apply by 'kubectl apply')
3) to apply the "Auhtorization Policy" from the full list with the UI

Pershap some features are implemented, but i didn't find it.


_>Perhaps you are suggesting to enable this feature i.e. per Service/Workload level as well ?_
From "service account" to "service"

**Comment by lucasponce** [comment]
> Pershap some features are implemented, but i didn't find it.

Perhaps you may try this feature:

https://github.com/kiali/kiali-ui/pull/1924

I agree that if per namespace is so "high" granularity, this is something we could do at Application/Service/Workload level.

Also the generated AP is just a suggestion based on the current telemetry traffic, user can modify/delete if it doesn't apply, similar what I think you are describing.

**Comment by lucasponce** [comment]
Better documented in Kiali.io, I forgot to add the comment:
https://kiali.io/documentation/latest/features/#_security_traffic_policies

**Comment by kaz-33** [comment]
On a kiali/kiali-ui#1924 i didn't see the wait to apply AP. (only the possibnility to modify/delete AP that exists)
if you have a list of flow matrix, we can imagine to offer the choice to admin guy to set Authorizatio Policy per flow.

**Comment by lucasponce** [comment]
Ok, so ideal flow perhaps would be to have a list of suggested AP to apply, where use can select/unselect some.

**Comment by kaz-33** [comment]
apply for all with one 'click'  on a namespace.
Imagine, 200 Pods, i don"t want to apply one by one :) 
but sometime Select and modifiy "one by one" could be necessary.

**Comment by lucasponce** [comment]
> apply for all with one 'click' on a namespace.
> Imagine, 200 Pods, i don"t want to apply one by one :)

But that's the current feature, or perhaps I'm missing something.

So, if in the current feature we put a previous step with the list of AP suggested where user may modify, isn't that address what you are suggesting ?

On top of that, the same feature could be added per App/Workload/Service level, so, only workloads involved on those would apply the AP.

Also, in both cases user would be able to modify them.

**Comment by kaz-33** [comment]
it works!

**Comment by lucasponce** [comment]
@kaz-33 nice.

As commented, from the current feature (apply AP from namespace) one next step would be to allow to apply it per app/workload/service.

But feedback is very valuable so, if we are missing some use case, happy to chat about it.
