### ISSUE TITLE
Workload Details Pod: Label column not aligned with row

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#2043]
**General remarks**
Workload Details Pod: Label column not aligned with the rest of the row -- it sits quite a bit above the top of the other columns.

![Kiali_Console_and_Kiali_UX_Design_Weekly_-_Google_Docs](https://user-images.githubusercontent.com/1312165/71019666-9cc8ea80-20af-11ea-8e37-9977597baf38.png)

Closeup:
![Kiali_Console](https://user-images.githubusercontent.com/1312165/71019882-047f3580-20b0-11ea-8e80-09dd83db2d4c.png)

**Comment by jshaughn** [comment]
This doesn't look very good, let's fix it. Adding to backlog.

**Comment by jshaughn** [comment]
This seems to have been fixed.
