### ISSUE TITLE
Add OCP style badging to Graph

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#2045]
**Is your feature request related to a problem? Please describe.**
To be more consistent with OCP we should use the OCP style badging for the Graph as well.

**Describe the solution you'd like**
Here is the design issue: https://github.com/kiali/kiali-design/issues/154
We may still need some clarity from UxD on exactly what should be done.

For reference:
![Add_OCP_style_badging_to_Graph_·_Issue__154_·_kiali_kiali-design](https://user-images.githubusercontent.com/1312165/71020954-2a0d3e80-20b2-11ea-8c45-a4b0355fd135.png)

**Comment by abonas** [comment]
please elaborate what badges should be changed in Kiali and to which other badges.
Keep in mind that Kiali's graph has in general many more nodes, and they are much smaller than the ones in openshift topology.

**Comment by jshaughn** [comment]
I don't think I'm a fan of this idea as it will increase label sizes and therefore overlap. Our node shapes already indicate the node type. Not sure about this one.

**Comment by mtho11** [comment]
@jshaughn TBH I'm not a big fan of it either this is more UxD driven from some of the conversations we have had in our meetings.

**Comment by mtho11** [comment]
@abonas I'm not totally sure exactly what needs to be changed. This should be driven by UxD.

**Comment by mtho11** [comment]
We had a meeting with UxD yesterday and have decided to ignore this for now: https://github.com/kiali/kiali-design/issues/154
