### ISSUE TITLE
Double-click focus-node  to navigate to detail

### ISSUE THREAD

**Issue by jshaughn** [kiali/kiali#2046]
This is an idea from @lucasponce that offers one more way to drill into node detail.

Today in the graph, a single click selects a node and a double-click drills down into the node focus graph (aka node graph, node detail graph).  On the node focus graph a double-click on the focus node has no effect because we are already drilled down.  A natural progression would be to have that double-click navigate to the relevant detail page.

**Comment by mtho11** [comment]
Is there a ux design issue for this? (before we go down a certain path)

**Comment by jshaughn** [comment]
There is no design issue, it's just our idea.  It just adds a nav shortcut where currently we do nothing.

**Comment by mtho11** [comment]
@cfcosta I'm going to take this one since you are going on PTO. You cool with that?

**Comment by cfcosta** [comment]
@mtho11 yes, go for it.
