### ISSUE TITLE
Namespaces overview should differentiate idle from failure apps

### ISSUE THREAD

**Issue by jshaughn** [kiali/kiali#2049]
As an active Kiali user, it looks a bit confusing to me when I see some of my apps which are just scaled down to zero marked/added in the list of failures.

I would like to see some differentiation between those apps that are really in some kind of failure state from those which are just idled (or scaled down to zero).

I have attached two images of how it looks like today (current-overview.png) and a quick draft of a what I tried to explain above (desired-overview.png).

Also, this is going to be much more relevant in serverless scenarios, when auto scale to zero will just happen and that doesn't mean that those apps are in a failure state.

Current:
![kiali-3270-current-overview](https://user-images.githubusercontent.com/2104052/71032635-bd129c80-20e3-11ea-9114-7dd2e271c336.png)

Desired:
![kiali-3270-desired-overview](https://user-images.githubusercontent.com/2104052/71032718-e6332d00-20e3-11ea-83fe-a52a6ac93dec.png)

Jira: https://issues.redhat.com/browse/KIALI-3270

cc @jotak

**Comment by lucasponce** [comment]
Interesting, but yes, I guess we have the information to draw this. If the desired replica of the controller is set to 0, I agree that doesn't sound an error if the user wanted to perform that action.

I wonder if there is some cornercase, but I think with the info we collect from workload:

```
			DesiredReplicas:   w.DesiredReplicas,
			CurrentReplicas:   w.CurrentReplicas,
			AvailableReplicas: w.AvailableReplicas
```

We could compute this.

**Comment by jotak** [comment]
+1 I think there's already some jira/ticket about that but we haven't done it so far. Let's keep this one as it's on our radar

**Comment by jshaughn** [comment]
@jotak I did look for an existing issue and couldn't identify one, but it may be hiding ;)  +1 to just using this one and we'll clean up duplicate if we find it.

**Comment by aljesusg** [comment]
Team I am confuse with some cases.
## Cases

1. Desired and current are 0   =>  Now is NA and is showed FAILURE (**New proposal is show like UNDESIRED**)  (I think that if this is an user error configuration it shouldn't be a FAILURE or UNDESIRED)
2.  desiredReplicas > 0 && currentReplicas > 0 && availableReplicas === 0 => FAILURE
3. desiredReplicas === availableReplicas && availableReplicas !== currentReplicas => FAILURE
4. currentReplicas < desiredReplicas => UNDESIRED **New state**
5. desiredReplicas === currentReplicas && currentReplicas === availableReplicas => HEALTHY
6.  Other DEGRADED

So in the 1º case is a FAILURE ? , the system response is OK but the workload has 0 pods defined by the user. Should we show here some kind of config icon ?


_IMO UNDESIRED should be a resources problems or something in the system that not let have the desired pods._

**Comment by lucasponce** [comment]
Perhaps, let's try to review the high level scenario, and let's see if the variables we have are ok or do we need anything else pulled from the workload.

- User has a workload marked to have 5 replicas and there are 5 pods -> healthy.
- User has a workload marked to have 5 replicas and there are <5 pods -> error.
- User has marked to scale down a workload -> New Iddle state.

Here there are perhaps two or three implementation data that could introduced noise:

DesiredReplicas is what user requests, and it's mapped with:
```
	// Number of desired pods. This is a pointer to distinguish between explicit
	// zero and not specified. Defaults to 1.
	// +optional
	Replicas *int32 `json:"replicas,omitempty" protobuf:"varint,1,opt,name=replicas"`
```

CurrentReplicas is mapped with:
```
	// Total number of non-terminated pods targeted by this deployment (their labels match the selector).
	// +optional
	Replicas int32 `json:"replicas,omitempty" protobuf:"varint,2,opt,name=replicas"`
```

And AvailableReplicas is also useful because it differentiates if some pod are up but not ready:
```
	// Total number of available pods (ready for at least minReadySeconds) targeted by this deployment.
	// +optional
	AvailableReplicas int32 `json:"availableReplicas,omitempty" protobuf:"varint,4,opt,name=availableReplicas"`

```

So, having said that, a suggestion I see is:

- If desired is 0, then user performed the action, and it shouldn't be an error condition.
- if desired > 0 && current > 0 && available == 0 that is a failure, some pods are up but not ready.
- if desired > 0 and current < desired, this is a failure, it's not a new state.
- if desired == current == vailable is a healthy condition.

I don't know if there is space for degraded on this scenario, perhaps I missed something.

But at least, this is my understanding about the business logic behind this issue.

@jotak @jshaughn feel free also to jump into the discussion, perhaps it's just a matter of interpretation (all views are ok) but we are flipping some terminology.

Better if we can sync on this.

**Comment by lucasponce** [comment]
And a side comment but related.
This issue should also cover the workload health not only in overview page to be consistent as well.
I mean, if in overview page a workload is marked as "iddle" that should be updated in other locations: list pages and details as well.
(I don't mean that it should be a single PR, but to subtasks that belong to this effort).

**Comment by jshaughn** [comment]
On 4/16/2020 5:39 AM, Lucas Ponce wrote:
>
> Perhaps, let's try to review the high level scenario, and let's see if 
> the variables we have are ok or do we need anything else pulled from 
> the workload.
>
>   * User has a workload marked to have 5 replicas and there are 5 pods
>     -> healthy.
>   * User has a workload marked to have 5 replicas and there are <5
>     pods -> error.
>   * User has marked to scale down a workload -> New Iddle state.
>
> Here there are perhaps two or three implementation data that could 
> introduced noise:
>
> DesiredReplicas is what user requests, and it's mapped with:
>
> |// Number of desired pods. This is a pointer to distinguish between 
> explicit // zero and not specified. Defaults to 1. // +optional 
> Replicas *int32 `json:"replicas,omitempty" 
> protobuf:"varint,1,opt,name=replicas"` |
>
> CurrentReplicas is mapped with:
>
> |// Total number of non-terminated pods targeted by this deployment 
> (their labels match the selector). // +optional Replicas int32 
> `json:"replicas,omitempty" protobuf:"varint,2,opt,name=replicas"` |
>
> And AvailableReplicas is also useful because it differentiates if some 
> pod are up but not ready:
>
> |// Total number of available pods (ready for at least 
> minReadySeconds) targeted by this deployment. // +optional 
> AvailableReplicas int32 `json:"availableReplicas,omitempty" 
> protobuf:"varint,4,opt,name=availableReplicas"` |
>
> So, having said that, a suggestion I see is:
>
>   * If desired is 0, then user performed the action, and it shouldn't
>     be an error condition.
>   * if desired > 0 && current > 0 && available == 0 that is a failure,
>     some pods are up but not ready.
>   * if desired > 0 and current < desired, this is a failure, it's not
>     a new state.
>   * if desired == current == vailable is a healthy condition.
>
> I don't know if there is space for degraded on this scenario, perhaps 
> I missed something.
>

This mostly makes sense to me. For completeness you may want a couple of 
changes:

  * if desired == current == available then healthy
  * If desired == 0 && current > 0 then Degraded? maybe this can be
    ignored but maybe a pod is hanging on terminate
  * if desired >  0 && (current == 0 || available == 0) then failure
  * if desired >  0 && current > 0 &&  available > 0 && (current <
    desired || available < desired) then degraded

Perhaps I missed something as well, not sure :)

**Comment by lucasponce** [comment]
Ok, I think we have reviewed this scenario and it seems we are on the same page.
Main goal of this is to introduce the "iddle"state which is mapping when user scales down a workload.

Perhaps main difference is when consider degraded/failure, but I'm fine which whatever criteria here, if there are 4 pods from desired 5 pods, degraded sounds also valid as service is not completely down. 

But this is more a terminology instead.

So, then just to help @aljesusg are we in agreement that the "idle" state is when user peforms a scale down and workload is in desired 0 ?

Are we missing any other scenario thay may affect here ?

**Comment by aljesusg** [comment]
Ok so it seems that we have an agreement and the cases will be like this

```ts
 /*
     IDDLE STATE
  */
  // User performed the action
  if (desiredReplicas === 0) {
    return IDDLE;
  }

  if (desiredReplicas > 0 && currentReplicas > 0 && availableReplicas > 0 && ( currentReplicas < desiredReplicas || availableReplicas < desiredReplicas)) {
    return IDDLE;
  }

  /*
     FAILURE STATE
  */
  if (desiredReplicas > 0 && (currentReplicas === 0 || availableReplicas === 0)) {
    return FAILURE;
  }

  // Some pods are up but not ready
  if (desiredReplicas > 0 && currentReplicas > 0 && availableReplicas === 0) {
    return FAILURE;
  }

  if (desiredReplicas > 0 && currentReplicas < desiredReplicas) {
    return FAILURE;
  }

  if (desiredReplicas === currentReplicas && availableReplicas > currentReplicas) {
    return FAILURE
  }

  // Pending Pods means problems
  if (desiredReplicas === availableReplicas && availableReplicas !== currentReplicas) {
    return FAILURE;
  }

  // No available Pods when there are desired and current means a Failure
  if (desiredReplicas > 0 && currentReplicas > 0 && availableReplicas === 0) {
    return FAILURE;
  }

  /*
     HEALTHY STATE
  */
  if (desiredReplicas === currentReplicas && currentReplicas === availableReplicas && availableReplicas === desiredReplicas) {
    return HEALTHY
  }


  // Other combination could mean a degraded situation
  return DEGRADED;
```

we agree?

**Comment by jshaughn** [comment]
@aljesusg Looks good.  Only minor comment is IDDLE -> IDLE.

**Comment by lucasponce** [comment]
```
  if (desiredReplicas > 0 && currentReplicas > 0 && availableReplicas > 0 && ( currentReplicas < desiredReplicas || availableReplicas < desiredReplicas)) {
    return IDDLE;
  }
```

That means a problem, I think it can be a FAILURE or DEGRADED, but why this situation should be IDLE ?

**Comment by aljesusg** [comment]
> ```
>   if (desiredReplicas > 0 && currentReplicas > 0 && availableReplicas > 0 && ( currentReplicas < desiredReplicas || availableReplicas < desiredReplicas)) {
>     return IDDLE;
>   }
> ```
> 
> That means a problem, I think it can be a FAILURE or DEGRADED, but why this situation should be IDLE ?
> 
> Also, remember that currentReplicas refers to the pods up, and availableReplicas are pods up and ready.

Oh yes error for me side ...I think that should be a DEGRADED

**Comment by aljesusg** [comment]
so here is the result

```ts
 /*
    IDLE STATE
 */
  // User performed the action
  if (desiredReplicas === 0) {
    return IDLE;
  }
  
  /*
   DEGRADED STATE
  */
  if (desiredReplicas > 0 && currentReplicas > 0 && availableReplicas > 0 && ( currentReplicas < desiredReplicas || availableReplicas < desiredReplicas)) {
    return DEGRADED;
  }

  /*
     FAILURE STATE
  */
  if (desiredReplicas > 0 && (currentReplicas === 0 || availableReplicas === 0)) {
    return FAILURE;
  }

  // Some pods are up but not ready
  if (desiredReplicas > 0 && currentReplicas > 0 && availableReplicas === 0) {
    return FAILURE;
  }

  if (desiredReplicas > 0 && currentReplicas < desiredReplicas) {
    return FAILURE;
  }

  if (desiredReplicas === currentReplicas && availableReplicas > currentReplicas) {
    return FAILURE
  }

  // Pending Pods means problems
  if (desiredReplicas === availableReplicas && availableReplicas !== currentReplicas) {
    return FAILURE;
  }

  // No available Pods when there are desired and current means a Failure
  if (desiredReplicas > 0 && currentReplicas > 0 && availableReplicas === 0) {
    return FAILURE;
  }

  /*
     HEALTHY STATE
  */
  if (desiredReplicas === currentReplicas && currentReplicas === availableReplicas && availableReplicas === desiredReplicas) {
    return HEALTHY
  }


  // Other combination could mean a degraded situation
  return DEGRADED;
```
