### ISSUE TITLE
Pass Container Version To Kiali Server

### ISSUE THREAD

**Issue by mattmahoneyrh** [kiali/kiali#2054]
Currently there Kiali does not display container version in Help About, which would be helpful when the container version changes, but the Kiali server version does not

Kiali-ui   1.0.4
Kiali        v1.0.8.redhat1

Add something like:
Kiali Container 1.0.9

**Comment by jmazzitelli** [comment]
We'd want to rename the label "Kiali" so it identifies it as the "Kiali Server" version... so we should have labels like this:

```
Kiali UI 1.0.4
Kiali Server v1.0.8.redhat1
Kiali Container 1.0.9
```

**Comment by jmazzitelli** [comment]
I'm gonna take a quick stab at this.

**Comment by jmazzitelli** [comment]
See the two PRs that will result in something like this:

![image](https://user-images.githubusercontent.com/2029470/71136996-ac8e1f00-21d4-11ea-814c-0acfc4bd88ab.png)

**Comment by jmazzitelli** [comment]
I'm going to explain how this works.

By default, the Kiali Container version will be the same major.minor.patch version of the Kiali Server.

If, however, the Kiali container image's Dockerfile gets an "ENV" added to it, and defines a KIALI_CONTAINER_VERSION environment variable, the value of the env var will be the value you see in the Kiali Container in the About box.

So, if you build a Kiali container, and you want to give it a separate version (separate from the Kiali Server version), add `ENV KIALI_CONTAINER_VERSION="x.y.z"` where x.y.z is the container version you want to see in the About box.

Right now, the project's Kiali Dockerfile does not define this, so the Kiali Container version will always be the same as the Kiali Server version for all project releases. But downstream projects are free to set their own container version in the Dockerfile they use to build the Kiali container.
