### ISSUE TITLE
Blog about traces & metrics correlation in Kiali

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#2058]
For openshift.com

cc @xeviknal @israel-hdez

**Comment by lucasponce** [comment]
Please, don't add these tasks to the project.
Blogs, conferences, or similar are NOT part of the Project issues.

**Comment by jotak** [comment]
@lucasponce I'd need to track this somehow. What do you suggest?

**Comment by jotak** [comment]
@lucasponce I don't want to have my personal backlog split in different places, we have to come up with a solution for that.

**Comment by lucasponce** [comment]
@jotak definetely not.
Kiali Issues is not people tracking tool is project tracking.
Tasks as blogs/conferences shoudln't be track here, but in your Weekly reports.

That's decision we took for Kiali.
