### ISSUE TITLE
Smooth out Kiali Charts

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#2060]
**Is your feature request related to a problem? Please describe.**
All of the line graphs in Kiali have a sawtooth structure to them (because there are not many points in the graph). This is displeasing to the eye. 

![Kiali_Console](https://user-images.githubusercontent.com/1312165/71220045-0695ef80-227c-11ea-8ad1-308e3350a3d9.png)

**Describe the solution you'd like**
Can we smooth out the line graphs so that they look more rounded instead of the sharp turns that result in sawtooth patterns?

Something more like this:

<img width="1287" alt="Starpaths_and_bash__Users_mithomps" src="https://user-images.githubusercontent.com/1312165/71220301-ea468280-227c-11ea-80f2-66d08c4f29f6.png">

I only included the graph on the overview but this would be for **all** line graphs in Kiali.

**Comment by lucasponce** [comment]
Perhaps it's a minimal change:
https://formidable.com/open-source/victory/gallery/interpolation -> select natural and I think it's what it refers here.

**Comment by mtho11** [comment]
@lucasponce I think **cardinal** looks slightly better. But yes, that should work!

**Comment by jshaughn** [comment]
@lucasponce If this is easy should we add to the backlog?
