### ISSUE TITLE
kiali sometimes connect kube-apiserver failed

### ISSUE THREAD

**Issue by lurenjia528** [kiali/kiali#2065]
E0103 14:36:34.516874       1 workloads.go:605] Workload istio-security-post-install-1.4.2 is not found as Job
E0103 14:36:34.517395       1 workloads.go:570] Workload prometheus-k8s is not found as StatefulSet
E0103 14:36:48.412904       1 graph.go:87] Get https://10.10.0.1:443/api/v1/namespaces: unexpected EOF: goroutine 1780 [running]:
runtime/debug.Stack(0x4000e38780, 0x3b, 0x40006ac920)
	/opt/go/src/runtime/debug/stack.go:24 +0x88
github.com/kiali/kiali/handlers.handlePanic(0x1143980, 0x40003a7c70)
	/root/gopath/src/github.com/kiali/kiali/handlers/graph.go:86 +0xf8
panic(0xcd9a60, 0x40006ac920)
	/opt/go/src/runtime/panic.go:679 +0x194
github.com/kiali/kiali/graph.CheckError(0x110c920, 0x40008aad50)
	/root/gopath/src/github.com/kiali/kiali/graph/util.go:38 +0x98
github.com/kiali/kiali/graph.getAccessibleNamespaces(0x4000362000, 0x38f, 0x10f0f80)
	/root/gopath/src/github.com/kiali/kiali/graph/options.go:278 +0x84
github.com/kiali/kiali/graph.NewOptions(0x4000ff4c00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/root/gopath/src/github.com/kiali/kiali/graph/options.go:190 +0x4e4
github.com/kiali/kiali/handlers.GraphNamespaces(0x1143980, 0x40003a7c70, 0x4000ff4c00)
	/root/gopath/src/github.com/kiali/kiali/handlers/graph.go:46 +0x68
net/http.HandlerFunc.ServeHTTP(0xf91228, 0x1143980, 0x40003a7c70, 0x4000ff4c00)
	/opt/go/src/net/http/server.go:2007 +0x40
github.com/kiali/kiali/handlers.AuthenticationHandler.Handle.func1(0x1143980, 0x40003a7c70, 0x4000ff4b00)
	/root/gopath/src/github.com/kiali/kiali/handlers/authentication.go:492 +0x1d8
net/http.HandlerFunc.ServeHTTP(0x40003dfa70, 0x1143980, 0x40003a7c70, 0x4000ff4b00)
	/opt/go/src/net/http/server.go:2007 +0x40
github.com/kiali/kiali/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0x400033a780, 0x1143980, 0x40003a7c70, 0x40001d5200)
	/root/gopath/src/github.com/kiali/kiali/vendor/github.com/gorilla/mux/mux.go:212 +0xb4
github.com/kiali/kiali/vendor/github.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1(0x11435c0, 0x4001004540, 0x40001d5200)
	/root/gopath/src/github.com/kiali/kiali/vendor/github.com/NYTimes/gziphandler/gzip.go:336 +0x1e8
net/http.HandlerFunc.ServeHTTP(0x40004aa120, 0x11435c0, 0x4001004540, 0x40001d5200)
	/opt/go/src/net/http/server.go:2007 +0x40
net/http.(*ServeMux).ServeHTTP(0x4000403040, 0x11435c0, 0x4001004540, 0x40001d5200)
	/opt/go/src/net/http/server.go:2387 +0x1a4
net/http.serverHandler.ServeHTTP(0x40004ac000, 0x11435c0, 0x4001004540, 0x40001d5200)
	/opt/go/src/net/http/server.go:2802 +0xc0
net/http.(*conn).serve(0x400014b040, 0x1149d00, 0x40007e6000)
	/opt/go/src/net/http/server.go:1890 +0x714
created by net/http.(*Server).Serve
	/opt/go/src/net/http/server.go:2927 +0x2f4
E0103 14:37:03.526116       1 workloads.go:570] Workload alertmanager-main is not found as StatefulSet
E0103 14:37:03.526511       1 workloads.go:605] Workload istio-init-crd-10-1.4.2 is not found as Job
E0103 14:37:03.526560       1 workloads.go:605] Workload istio-init-crd-11-1.4.2 is not found as Job
E0103 14:37:03.526591       1 workloads.go:605] Workload istio-init-crd-14-1.4.2 is not found as Job
E0103 14:37:03.526798       1 workloads.go:605] Workload istio-security-post-install-1.4.2 is not found as Job
E0103 14:37:03.527282       1 workloads.go:570] Workload prometheus-k8s is not found as StatefulSet
E0103 14:37:04.315440       1 workloads.go:570] Workload alertmanager-main is not found as StatefulSet
E0103 14:37:04.316163       1 workloads.go:605] Workload istio-security-post-install-1.4.2 is not found as Job
E0103 14:37:04.316782       1 workloads.go:570] Workload prometheus-k8s is not found as StatefulSet
E0103 14:37:04.323351       1 workloads.go:570] Workload alertmanager-main is not found as StatefulSet
E0103 14:37:04.328218       1 workloads.go:605] Workload istio-init-crd-10-1.4.2 is not found as Job
E0103 14:37:04.329390       1 workloads.go:605] Workload istio-init-crd-11-1.4.2 is not found as Job

kiali 1.11.0
kubernetes 1.14.2
istio 1.4.2

**Comment by lucasponce** [comment]
@lurenjia528 sorry for my delay, still catching up from the past break.
Reading the log, two comments:
- Stateful and Job are not by default queried by Kiali for performance reasons (In K8S API we can't query all controllers types in a single run, so, unusual types are disabled by default). These controllers can be enabled via Kiali CR:  https://github.com/kiali/kiali/blob/master/operator/deploy/kiali/kiali_cr.yaml#L477
- If the EOF error is not always there, it sounds that probably the K8S API is unresponsive for some reason. If that the case, perhaps we can review closer what is happening. There are further options like to enable a layer of caching from Kiali and K8S API as well. It may help in some way, but it's something that highly depend on your environment (resources, load, etc). Take a look at this https://github.com/kiali/kiali/blob/master/operator/deploy/kiali/kiali_cr.yaml#L456

Let me know if that helps. 
I'm interested to understand why it is failing.

**Comment by jshaughn** [comment]
@lurenjia528 Any updates?

**Comment by nnadig-ebsco** [comment]
@lucasponce we are seeing similar issue on v1.17.0 of Kiali we recently upgraded. is the suggestion to exclude workload here? https://github.com/kiali/kiali-operator/blob/master/deploy/kiali/kiali_cr.yaml#L585

log sample: 
I0519 12:48:13.347044       1 cache.go:174] Kiali cache for [namespace: cahaba-test-private] started
E0519 12:48:20.790447       1 workloads.go:605] Workload jinni-1589891400 is not found as Job
E0519 12:48:20.790461       1 workloads.go:605] Workload jinni-1589892300 is not found as Job
E0519 12:48:26.052760       1 workloads.go:605] Workload jinni-1589891400 is not found as Job
E0519 12:48:26.052777       1 workloads.go:605] Workload jinni-1589892300 is not found as Job
E0519 12:48:34.069436       1 workloads.go:605] Workload jaeger-cleaner-1589680800 is not found as Job
E0519 12:48:34.069455       1 workloads.go:605] Workload jaeger-cleaner-1589767200 is not found as Job
E0519 12:48:34.069492       1 workloads.go:605] Workload jaeger-cleaner-1589853600 is not found as Job
E0519 12:48:34.069560       1 workloads.go:605] Workload telemetry-restart-1589673600 is not found as Job

**Comment by lucasponce** [comment]
@nnadig-ebsco correct, if you update the Kiali CR to include Jobs it should give visibility.

Please, let me know if it works for you.

**Comment by nnadig-ebsco** [comment]
@lucasponce  thanks for your reply. i am not sure how to include Jobs as i assume its included by default unless the exclude_workloads is enabled.
#    ---
#    excluded_workloads:
#    - "CronJob"
#    - "DeploymentConfig"
#    - "Job"
#    - "ReplicationController"

please clarify.

**Comment by lucasponce** [comment]
@nnadig-ebsco yes, these values:

```
#    excluded_workloads:
#    - "CronJob"
#    - "DeploymentConfig"
#    - "Job"
#    - "ReplicationController"
```
are the default ones, if you want to not exclude anything just modify the "excluded_workloads" to an empty array, and Kiali will check if there are Pods with a higher parent based on those controllers.

I don't know your method of installation of Kiali, you can use the Kiali Operator or ConfigMap if you use a helm installation (default by istioctl I think).

**Comment by nnadig-ebsco** [comment]
@lucasponce that makes sense.. but curious on the error for replicasets in the logs as Deployment and ReplicaSet will be always queried as per documentation.
sample error:
E0519 15:03:11.562130       1 workloads.go:516] Workload ambassador-gateway-oa-setup-preview-blue-5848cb94f is not found as ReplicaSet

**Comment by lucasponce** [comment]
@nnadig-ebsco yes, that perhaps is something I'd like to test.
I wonder if you can guide me to prepare a scenario to test this.

I mean something simple that it doesn't take you time, like a bookinfo modified just to use one controller instead other and I can see the same error locally.

That would help me to investigate that log.

**Comment by lucasponce** [comment]
Outdated.
This topic was added to the FAQ
https://kiali.io/documentation/latest/faq/#workload-is-not-found

And I think most of the scenarios are well described.

Please, feel free to reopen if it seems the bug is still present.
