### ISSUE TITLE
Kiali Graphs show thin line(1px) when horizontal 2px otherwise

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#2069]
**Describe the bug**

The victory graphs show as thin (1px) lines when perfectly parallel with the x-axis (horizontal) everywhere else the lines show as thicker (2px) lines.

![Kiali_Console](https://user-images.githubusercontent.com/1312165/71930749-228d0280-3151-11ea-9732-08736612813b.png)

![Kiali_Console](https://user-images.githubusercontent.com/1312165/71940089-f5008300-3169-11ea-85a7-a240e346692b.png)

This occurs in multiple screens anywhere the victory charts _line graphs_ are used.

**Comment by jotak** [comment]
Yes ... looks like `VictoryVoronoiContainer` uses a clipPath boxing that is 1 pixel too small. Need to investigate.
https://formidable.com/open-source/victory/docs/victory-primitives/#clippath

**Comment by jotak** [comment]
Oh, there's a very easy workaround, adding `domainPadding: {y: 1}`, will do that by default in k-charted
