### ISSUE TITLE
Increase retention period in kiali to 12 hrs

### ISSUE THREAD

**Issue by suraj77foru** [kiali/kiali#2072]
Hi,

i wanted to increase the retention time in kiali ( currently 6 hrs) to 12 hrs. i changed in prometheus.retention  but still its not getting reflected in kiali. please help

**Comment by jotak** [comment]
Hi @suraj77foru 
In theory, you should only have to refresh your browser to see the retention period updated in Kiali UI.
You can open the dev console of your browser and check for network calls on page refresh. There should be a call to `config` endpoint, which provides in the response something called `storageTsdbRetention` . As per my screenshot:

![Capture d’écran de 2020-01-08 11-36-46](https://user-images.githubusercontent.com/2153442/71971841-bcb18100-320b-11ea-9300-0df273e88e1f.png)

Could you check that and see if the value is expected given your prometheus settings? The value is expressed in seconds.

**Comment by jotak** [comment]
Also, maybe I'm misunderstanding the problem. You said you changed `prometheus.retention`, but what is that exactly? Did you go through prometheus configuration as explained there: https://prometheus.io/docs/prometheus/latest/storage/#operational-aspects ?

**Comment by suraj77foru** [comment]
Hi jotak,

Thanks for the response. i checked in browser and the value matches with the value that was provided in storage.tsdb.retention.time, but the same is not seen in kiali ui. it is still showing 6 hrs. below is the image.

<img width="359" alt="kiali" src="https://user-images.githubusercontent.com/56642310/71973382-da471080-3234-11ea-9300-4c1087003972.PNG">

**Comment by jmazzitelli** [comment]
IIRC that drop down menu is limited to how much data you actually have. For example, if you do not have over 6 hours worth of telemetry data, you won't see anything higher than "6H" even if you retention setting is higher.

Let the system collect telemetry over a period of 24 hours and see what happens.

@jshaughn knows more about that drop down and why it might not show all the things you expect it to show.

**Comment by jshaughn** [comment]
@jmazzitelli No, I believe it's based on the Prometheus config.  But I don't think Kiali will update it dynamically, only at startup.   Have you restarted the Kiali pod?

**Comment by suraj77foru** [comment]
Hi jmazzitelli/jshaughn,

yes, i did restart the Kiali pod but no luck, its still showing max 6hrs of data.

**Comment by jshaughn** [comment]
@suraj77foru Can you look in the "View Debug Info" (click the ? icon on the Kiali masthead, left of the username) and check the Prometheus config being reported,

**Comment by jotak** [comment]
@jshaughn I can reproduce and confirm there's a bug. The server config is fetched but something must be wrong with how it's propagated with redux.

**Comment by suraj77foru** [comment]
Hi Jshaughn,

I looked into the view debug info. below is what i saw:

      "prometheus": {
        "globalScrapeInterval": 15,
        "storageTsdbRetention": 43200
      },
      "durations": {
        "60": "Last 1m",
        "300": "Last 5m",
        "600": "Last 10m",
        "1800": "Last 30m",
        "3600": "Last 1h",
        "10800": "Last 3h",
        "21600": "Last 6h"

can i add a line "43200" : "Last 12h"?

**Comment by jshaughn** [comment]
@suraj77foru with a config of 43200 you should see the 12h option in the dropdown.  @jotak says above that he reproduced an issue and is investigating, so it seems maybe you have hit a regression.  I'm sure he will update when he has more information, a fix and/or a workaround.  Thanks for reporting the issue.
