### ISSUE TITLE
Differentiate Kiali graph sidebar traffic colors more

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#2075]
**Is your feature request related to a problem? Please describe.**
On the graph side panel the 4xx and 5xx colors are very difficult to distinguish from each other.

We had a meeting with UxD yesterday and indeed the 4xx color should be orange.

![Graph_sidepanel_colors_for_4xx_and_5xx_too_close__hard_to_distinguish_·_Issue__165_·_kiali_kiali-design](https://user-images.githubusercontent.com/1312165/71990251-e6f14780-31e7-11ea-8aa8-1062be583348.png)

Reference:
https://github.com/kiali/kiali-design/issues/165

**Comment by mtho11** [comment]
This was discussed in Ux design review meeting today. And we have a solution: https://github.com/kiali/kiali-design/issues/165

**Comment by lucasponce** [comment]
Please, when an issue is clear and there is an agreement to put in into the Sprint, don't forget to add the "backlog" label on it.
