### ISSUE TITLE
Increase Kiali default retention time to >1m

### ISSUE THREAD

**Issue by GregHanson** [kiali/kiali#2077]
**General remarks**
Running through a security example and noticed that the padlock did not display on the service graph when mTLS was enabled with default retention and refresh intervals.  At the 1m interval, I got the service graph data, but in that 1m interval the corresponding security telemetry did not show up in time so no padlock displayed

**Versions used**
Kiali:
Istio: version 1.4.2
Kubernetes flavour and version: (e.g. OpenShift Origin 3.9)

**To Reproduce**

```bash
istioctl manifest apply --set profile=demo \
    --set values.global.mtls.enabled=true \
    --set values.global.mtls.auto=true \
    --set values.global.controlPlaneSecurityEnabled=true \
    --set values.global.hub=istio \
    --set values.global.tag="1.4.2" \
    --set values.kiali.enabled=true

kubectl apply -f samples/bookinfo/platform/kube/bookinfo.yaml 

export INGRESS_HOST=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
export INGRESS_PORT=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="http2")].port}')
export SECURE_INGRESS_PORT=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="https")].port}')
kubectl apply -f samples/bookinfo/networking/bookinfo-gateway.yaml
export GATEWAY_URL=$INGRESS_HOST:$INGRESS_PORT
#perform curl to generate traffic data
curl -s http://${GATEWAY_URL}/productpage | grep -o "<title>.*</title>"
istioctl dashboard kiali

#enable security badge from graph UI
```
![Screen Shot 2020-01-08 at 12 01 27 PM](https://user-images.githubusercontent.com/19473391/71999475-79f1a800-320f-11ea-993a-b9494f05c257.png)

**Expected behavior**
![Screen Shot 2020-01-08 at 12 03 20 PM](https://user-images.githubusercontent.com/19473391/71999498-81b14c80-320f-11ea-8634-d15a7580f5c1.png)

**Comment by jshaughn** [comment]
Clipped from a replay I made on the Slack thread...

- The protocol should still be HTTP. 
- The connection security badging for mTLS is separate from the protocol. 
- We show the lock badge only when global mTLS is not configured but at least some of the traffic on the edge, for the time period has mTLS.  
- We show the unlock badge when  global mTLS is configured and not all of the traffic for the time period has mTLS.
- When selecting an edge we show the lock badge and the % secure traffic when at least some of the traffic is secure (% omitted for 100%).
- As for the 1 minute default, it seems to be good in most cases as users generally like to see smaller granularity when examining the traffic, it captures changes well, as opposed to trends (at 15s scrape default you get ~4 data points per refresh).  I wouldn't really consider it a bug that a change of mTLS does not show up immediately, it will show up as soon as the metrics are scraped and stored.  And as mentioned above, we display % mTLS during a crossover period.

@GregHanson I'm not sure there is a bug actually in play here.  In your first snapshot, with the 1m duration, there is no traffic as evidenced by the grey edges.  Zero traffic means zero traffic with mTLS enabled.  I think maybe what you were expecting is for Kiali to show here on the graph that mTLS *is configured* for traffic on this edge.  But the traffic graph is generated from the actual traffic, and whether that traffic used mTLS, or not.  In other words, the traffic graph shows what actually happened to requests.  In this way it can be used to check expectations.

In the second snapshot, the expanded duration of 5 minutes was big enough to capture some actual traffic and in fact, it shows that all of the requests on the selected edge did in fact have mTLS.  So the reality matched your expectation.  For apps with very little traffic (< 1 request per minute) the 1-minute default for may be too small for your needs.  But most apps have far more traffic, making the 1 minute granularity useful.

**Comment by jshaughn** [comment]
@GregHanson Thanks for using Kiali and creating the issue, I hope the explanation above was helpful.  I don't really see a change to be made here and will close the issue.  Feel free to re-open if you think we missed the point.
