### ISSUE TITLE
Any applied filter hides scroll bottom part

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#2089]
Happens on master.
List Workloads or any other objects.
Filter by name or by any type.
The scrolling bottom part is broken and the end is hidden.
![Screenshot from 2020-01-13 13-01-45](https://user-images.githubusercontent.com/604313/72254671-113a6f00-3605-11ea-9373-cfec902e1c73.png)

**Comment by lucasponce** [comment]
Right, it's a clear bug.
Going to take it to work on it as there are some CSS adjustments that were in place for the scrolling.

**Comment by hhovsepy** [comment]
Happens on both FF and Chrome.
With all window heights.

**Comment by lucasponce** [comment]
We are discussing with @aljesusg to check if we can change this VirtualList and render all list at once.
Probably it'd simplify this, as we fetch all backend info at once.

**Comment by lucasponce** [comment]
I understand that ideal solution would be something like this (i.e. gmail):
![image](https://user-images.githubusercontent.com/1662329/72259689-5cf31580-3611-11ea-9839-b7fb64157517.png)
Where scroll is similar as window-scroll and the header is fixed.
Currently to do that in Kiali we should refactoring the layout
![image](https://user-images.githubusercontent.com/1662329/72259741-7d22d480-3611-11ea-9b51-0e832ab7ddc8.png)
As we would need to refine the layout.
