### ISSUE TITLE
Validation of app/service names in Graph find/hide

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#2093]
**Is your feature request related to a problem? Please describe.**
For instance, when I type the name of an invalid node/service in Kiali find/hide it doesn't know that the name is invalid even though it knows the list of valid nodes/services
**Describe the solution you'd like**
Kiali should alert an invalid node/service name when doing find/hide validations. The information is there to provide this validation. We currently provide validation services on improperly formed operations but not service/app names.

This video shows the situation:
![invalid-namnes](https://user-images.githubusercontent.com/1312165/72356237-c587d400-369d-11ea-96e4-1fa94c218a9e.gif)

**Comment by jshaughn** [comment]
@mtho11 Let's leave off assigments until it's on the backlog.  Maybe someone in the community wouldlike to do it before we could get to it.

**Comment by jshaughn** [comment]
I'm not sure about this one and how it differs from other expressions that don't have any hits.  The fact that nothing highlights may be enough.  Perhaps you're looking for something to prove it's not there.

**Comment by mtho11** [comment]
@jshaughn go ahead and close it if you feel it is not worth the effort.
