### ISSUE TITLE
Spark-Line HTTP Request Response Time Graph Not Showing Correct Color

### ISSUE THREAD

**Issue by mattmahoneyrh** [kiali/kiali#2097]
In the HTTP Request Response Time graph, clicking on the orange line results in displaying the wrong color (expected: orange, actual: green), when hover-over plotted line.

![Selection_120](https://user-images.githubusercontent.com/7262987/72358434-92a00900-36ba-11ea-88a8-e3d7aa1c4b53.jpg)

**Comment by jotak** [comment]
This was commented here: https://github.com/kiali/kiali/issues/2068#issuecomment-571939828

The issue is more that only one color is displayed whereas the data point is the same for several metrics (here p50, p95 and p99) hence there's three different colors that should be displayed.
