### ISSUE TITLE
Deploying a custom kiali image via Kubernetes, without OpenShift or Minikube, when following the Kiali readme building steps

### ISSUE THREAD

**Issue by Exzelsios** [kiali/kiali#2101]
Hello, 

**Is your feature request related to a problem? Please describe.**

I want to be able to deploy a Kiali image I locally built via Kubernetes. 
This does not seem to be possible currently, as apparently only OpenShift and Minikube are supported when following the steps described by the readme on Github.
Building the container image via `make container-build` works fine, but I am unable to use `make cluster-push` and `make operator-create`. 
Both fail at the `.prepare-ocp` step, or with the environment variable `IS_MINIKUBE=true` at `.prepare-minikube`. 

![make-cluster-push](https://user-images.githubusercontent.com/23435018/72422604-0efe1f00-3783-11ea-82a5-07614e3d407b.png)

**Describe the solution you'd like**
I'd like to build and deploy my own Kiali image via Kubernetes/kubectl. It used to be supported in older versions (v1.09 and down).

**Describe alternatives you've considered**
Downgrading to older versions where building and deploying via kubectl was still supported.

**Additional context**
Using the current master/v1.12. 
kubectl versions are v1.14 client, v1.13 server. 

This probably is a seperate issue, maybe a configuration mistake on my part: 
I've mentioned that I used older Kiali versions. However I've had issues with building it with my locally built UI, as it always used the default kiali UI, even when building with `CONSOLE_VERSION=local` and specifying the UI path via `CONSOLE_LOCAL_DIR`. I've developed my custom UI via proxying, but now I need to implement some backend methods. However, I currently can not build both the custom backend and custom frontend together in any way.

**Comment by lucasponce** [comment]
Thanks, adding @jmazzitelli if he can take a look and propose some ideas.

**Comment by jmazzitelli** [comment]
`cluster-push` is used to push the image to a remote cluster (in the current use-cases, a remote OpenShift or a minikube VM). What environment are you using? We may need to introduce a new environment variable to be able to tell the makefile about a different cluster environment that is to be used. Right now we have IS_MINIKUBE to help determine if you are using OpenShift or minikube - sounds like we need more than a boolean here.

Perhaps provide more information about the cluster environment you are using and how you used to work (it sounds like the old makefiles used to work for your environment).

**Comment by Exzelsios** [comment]
Sorry for the delayed response.

I currently am deploying on a Azure Kubernetes Service (AKS). Istio has been installed via Helm (Client and Server version 2.16). I'm using Kiali version 1.12 (current master) and a modified Kiali-UI version v1.11. For the containers I've been using Docker v19.03. Everything has been on a Linux VM (Linux Mint v19.3)

With previous versions of the Makefiles, building and deploying everything worked with this setup. There I've also been following the workflow described by the github readme: 

```
make docker-build
make operator-create
make kiali-create
```

But as I've described before, I can not build the operator and deploy my custom Kiali image with the current workflow - because I have neither OpenShift nor Minikube.

Of course another option would be to setup everything within Minikube, instead of a remote cluster like Azure, though I'd prefer the latter. 

If you need any other information I'm glad to provide it.

**Comment by jmazzitelli** [comment]
> With previous versions of the Makefiles, building and deploying everything worked with this setup. There I've also been following the workflow described by the github readme:
> 
> ```
> make docker-build
> make operator-create
> make kiali-create
> ```

OK, so based on those steps, you didn't push the image anywhere. Somehow either you manually pushed to a remote AKS cluster or it was able to pull from your local docker.

I'll try to get the make targets to not require minikube or OCP. This will be controlled via environment variables.
