### ISSUE TITLE
Kiali can't call API to draw graph.

### ISSUE THREAD

**Issue by lwx294821** [kiali/kiali#2105]
The  version of k8s cluster  is v1.11.1 and istio is v1.4.0. After I installed istio,I try to get graph and the result as follows:
![image](https://user-images.githubusercontent.com/28983979/72511200-b5324d80-3885-11ea-91ee-9ca29fa2c5f0.png)

the logs show 
![image](https://user-images.githubusercontent.com/28983979/72511305-e9a60980-3885-11ea-8bc8-950fa2bc780c.png)

but when the k8s is v1.15.3,everything is ok. If it is the version issue?

**Comment by jshaughn** [comment]
I may be a kubernetes version issue.  Istio 1.4 has only been tested with kubernetes v.13, 1.14, 1.15. See [this istio page](https://istio.io/docs/setup/platform-setup/).

Are you using the Kiali packaged with Istio 1.4, or did you install Kiali in a different way?

**Comment by jmazzitelli** [comment]
v1.11.1 is too old - not even supported by Istio now: https://istio.io/docs/setup/getting-started/#platform

**Comment by jshaughn** [comment]
@lwx294821 I am closing this issue based on the old kubernetes version being used with the newer istio version.  Feel free to re-open if you still have a problem after updating to a supported k8s version.
