### ISSUE TITLE
Hide/find on graph - when enabling display options the message is in error

### ISSUE THREAD

**Issue by abonas** [kiali/kiali#2106]
Related to https://github.com/kiali/kiali-ui/pull/1416

When auto enabling display options on graph as needed by the desired graph find/hide expression, there is a message generated to user explaining about auto enabling those options.
This seems to be the correct approach, except that the message is displayed in red and with "X", and it should be instead informational.

**Comment by jshaughn** [comment]
@abonas, It's actually in green.  That video was not the merged version of the PR.  I think this can be closed.
