### ISSUE TITLE
[Metrics] Clicking on a span should lead to Traces view

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#2107]
Spans in metrics page have a span id and (iirc) trace id associated with. So, when clicking on it, we could open the Traces page focused on that trace id.

What I'm unsure, is if it's ok to abruptly switch to trace view (might be too abrupt), or if we should display a contextual menu with a "View trace" option.

I think when Alberto's work is done, this is the next logical step in our Metrics & Traces work

cc @lucasponce @aljesusg

**Comment by jotak** [comment]
As a subtask, we must first make traceID being read from URL in the Traces component

(flow: click on a trace => set traceID in URL => show trace details panel)

**Comment by aljesusg** [comment]
First step sent @jotak  https://github.com/kiali/kiali-ui/pull/1642 ;)
