### ISSUE TITLE
Separate errorTraces call from services

### ISSUE THREAD

**Issue by aljesusg** [kiali/kiali#2109]
In a case that we have problems getting information from a service

Use Case that we found
**/api/threescale/namespaces/bookinfo/services/productpage**

the information returned is 
```json
{"error":"rules.config.istio.io \"threescale-bookinfo-productpage\" not found"}
```

Problems found:

1. We can't see this error in Kiali-Ui messageCenter. So the user can't know what is happening.
2. Should this error block all the information about the service? Can we create somekind of "error_found" in the json and return the information that we found?
3. ErrorTraces Icon is hidden because there is not information about them because kiali return this information in the same call and the user could see error Traces in the chart.

Impact https://github.com/kiali/kiali-ui/pull/1577

cc @xeviknal @lucasponce @jotak @hhovsepy

**Comment by lucasponce** [comment]
It sounds there is a bug somewhere in that area, as 3scale api shouldn't block the rest of the service details call.
(Another scenario is if the main k8s API fails).
Let me review, as I suspect a bug a regression could be introduced with all refactoring done in this area.

**Comment by aljesusg** [comment]
ok, anyway I am thinking about to separate the traces call from services detail to avoid this in the future, jaeger integration in another piece totally independent from the rest of the call, so to avoid have an errorTraces: undefined in the call when tracing is enabled or errorCall for another thing when tracing is enabled, I would separate the call. What do you think? Maybe I can do the separation in another issue while you check this "bug"

**Comment by lucasponce** [comment]
That may have other implications as well, as ServiceDetails today fetches health.
With that logic we should split Service in more than one element and not only for this use case.

**Comment by aljesusg** [comment]
Understood but the information related with health and details provide for the same origin. Am I right?

**Comment by lucasponce** [comment]
> Understood but the information related with health and details provide for the same origin. Am I right?

No, as health comes from Prometheus too.

**Comment by aljesusg** [comment]
ok anyway in this case that we have this error I think that we should show it in the Kiali UI  for the user

**Comment by lucasponce** [comment]
> ok anyway in this case that we have this error I think that we should show it in the Kiali UI for the user

Yes, that's a bug for sure, I think errors should be clear translated to the UI.
I'll take a look at it.

**Comment by lucasponce** [comment]
After investigated a bit I don't think this issue is a bug.
A 404 response error from this endpoint:
```
/api/threescale/namespaces/bookinfo/services/productpage
```

It's a valid response and it's documented in the UI as well:

```
              // Only log 500 errors. 404 response is a valid response on this composition case
              if (error.response && error.response.status >= 500) {
                AlertUtils.addError('Could not fetch ThreeScaleServiceRule.', error);
              }
```

But I see that there are some backlog traces like:

```
I0120 11:46:13.727084       1 spans.go:75] Found 27 spans in the 13 traces for service reviews
E0120 11:46:36.213355       1 errors.go:21] rules.config.istio.io "threescale-bookinfo-reviews" not found
E0120 12:06:13.405267       1 errors.go:21] rules.config.istio.io "threescale-bookinfo-reviews" not found
E0120 12:07:20.851493       1 errors.go:21] rules.config.istio.io "threescale-bookinfo-reviews" not found
E0120 12:07:23.638340       1 errors.go:21] rules.config.istio.io "threescale-bookinfo-reviews" not found
E0120 12:07:25.889655       1 errors.go:21] rules.config.istio.io "threescale-bookinfo-reviews" not found
E0120 12:07:30.854352       1 errors.go:21] rules.config.istio.io "threescale-bookinfo-reviews" not found
E0120 12:09:35.252404       1 errors.go:21] rules.config.istio.io "threescale-bookinfo-reviews" not found
E0120 12:10:40.808021       1 errors.go:21] rules.config.istio.io "threescale-bookinfo-reviews" not found
E0120 12:11:55.127162       1 errors.go:21] rules.config.istio.io "threescale-bookinfo-reviews" not found
E0120 12:12:30.470703       1 errors.go:21] rules.config.istio.io "threescale-bookinfo-reviews" not found
I0120 12:12:45.556660       1 spans.go:75] Found 33 spans in the 19 traces for service reviews
I0120 12:13:01.106124       1 spans.go:75] Found 4 spans in the 3 traces for service reviews
I0120 12:13:16.750003       1 spans.go:75] Found 2 spans in the 1 traces for service reviews
I0120 12:13:31.748616       1 spans.go:75] Found 2 spans in the 1 traces for service reviews
I0120 12:13:46.751392       1 spans.go:75] Found 2 spans in the 1 traces for service reviews
I0120 12:14:01.750221       1 spans.go:75] Found 2 spans in the 1 traces for service reviews
I0120 12:14:16.753539       1 spans.go:75] Found 2 spans in the 1 traces for service reviews
```

That create some false hints about a problem.
So, I'm going to fix these logs using this issue.

A side effect that I see is that when fetching service details the interval is relative to backend so it may generate a mismatch between error traces tag icon and the error query within the tab where the start, where in this case, the interval is calculated from the client. So, in case server and client are in different timezones, probably the error query used for the tab may hay a different query parameter than the used for the traces tab.

But I think this deserves a different issue.
