### ISSUE TITLE
Disabling ingress in Kiali custom resource does not delete ingress resource

### ISSUE THREAD

**Issue by tillig** [kiali/kiali#2112]
**Describe the bug**
After a default deploy of the Kiali operator there's an ingress in the `istio-system` namespace.

If you update the Kiali custom resource to set `ingress_enabled: false` then the ingress is still there after reconciliation.

**Versions used**
Kiali: 1.12.0
Istio: 1.4.3
Kubernetes flavour and version: Azure Kubernetes 1.13.12

**To Reproduce**
1. Follow the [quick install instructions](https://kiali.io/documentation/getting-started/#_quick_install).
2. Verify the ingress is deployed by default: `kubectl get ingress -n istio-system`
3. Edit the CR: `kubectl edit kiali/kiali -n kiali-operator`
4. Under `deployment` set `ingress_enabled: false`
5. Wait for the operator to finish reconciliation.
6. After reconciliation, note the ingress is still there though it's disabled: `kubectl get ingress -n istio-system`

**Expected behavior**
The Kiali operator should have removed the ingress once it was disabled.

**Comment by jmazzitelli** [comment]
I am not seeing this bug. When I first install on Kubernetes (I'm using minikube for this test), I see the ingress created in the operator logs. and I also confirmed the Ingress exists by looking at the k8s dashboard console. I also see the "delete ingress" task get skipped (this happens when deployment.ingress_enabled is set to true):

```
TASK [kiali-deploy : Delete Ingress on Kubernetes if disabled] *****************
task path: /opt/ansible/roles/kiali-deploy/tasks/kubernetes/k8s-main.yml:31
skipping: [localhost] => {
    "changed": false,
    "skip_reason": "Conditional result was False"
}
```

I then edit the Kiali CR and ensure I set the "spec.deployment.ingress_enabled" to "false". I see reconciliation happen and I see the delete of the Ingress in the logs. I also confirmed the ingress is now gone in the k8s dashboard console:

```
TASK [kiali-deploy : Delete Ingress on Kubernetes if disabled] *****************
task path: /opt/ansible/roles/kiali-deploy/tasks/kubernetes/k8s-main.yml:31
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: ansible-operator
<localhost> EXEC /bin/sh -c 'echo ~ansible-operator && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /opt/ansible/.ansible/tmp/ansible-tmp-1579279126.669516-106370149814362 `" && echo ansible-tmp-1579279126.669516-106370149814362="` echo /opt/ansible/.ansible/tmp/ansible-tmp-1579279126.669516-106370149814362 `" ) && sleep 0'
Using module file /usr/local/lib/python3.6/site-packages/ansible/modules/clustering/k8s/k8s.py
<localhost> PUT /opt/ansible/.ansible/tmp/ansible-local-879o4msi5pw/tmp2bua1yo7 TO /opt/ansible/.ansible/tmp/ansible-tmp-1579279126.669516-106370149814362/AnsiballZ_k8s.py
<localhost> EXEC /bin/sh -c 'chmod u+x /opt/ansible/.ansible/tmp/ansible-tmp-1579279126.669516-106370149814362/ /opt/ansible/.ansible/tmp/ansible-tmp-1579279126.669516-106370149814362/AnsiballZ_k8s.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python3.6 /opt/ansible/.ansible/tmp/ansible-tmp-1579279126.669516-106370149814362/AnsiballZ_k8s.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /opt/ansible/.ansible/tmp/ansible-tmp-1579279126.669516-106370149814362/ > /dev/null 2>&1 && sleep 0'
changed: [localhost] => {
    "changed": true,
    "invocation": {
        "module_args": {
        ...
        }
    },
    "method": "delete",
    "result": {
        "apiVersion": "v1",
        "details": {
            "group": "extensions",
            "kind": "ingresses",
            "name": "kiali",
            "uid": "3571b1d4-3947-11ea-8c88-0800273bd87f"
        },
        "kind": "Status",
        "metadata": {},
        "status": "Success"
    }
}
```

So, can you first tell me what your Kiali CR looks like exactly when you expect the ingress to be deleted? My setting in my Kiali CR looks like (make sure yours is spelled correctly and is under the deployment section):

```
spec:
  deployment:
    ingress_enabled: false
```

Also, look in your kiali operator pod's logs and look for this task "TASK [kiali-deploy : Delete Ingress on Kubernetes if disabled]" and see what the logs say.

**Comment by jmazzitelli** [comment]
Here's my commands - I show I had the ingress, I then edit the CR to set the flag to false, then I look at the date/time and see when the ingress goes away. Takes about a minute for the reconciliation to complete and the ingress to be deleted.

```
$ kubectl get ingress -n istio-system
NAME    HOSTS   ADDRESS          PORTS   AGE
kiali   *       192.168.99.100   80      3m5s
$ kubectl edit kiali/kiali -n kiali-operator
kiali.kiali.io/kiali edited
$ date ; kubectl get ingress -n istio-system
Fri Jan 17 11:56:36 EST 2020
NAME    HOSTS   ADDRESS          PORTS   AGE
kiali   *       192.168.99.100   80      3m57s
$ date ; kubectl get ingress -n istio-system
Fri Jan 17 11:56:57 EST 2020
NAME    HOSTS   ADDRESS          PORTS   AGE
kiali   *       192.168.99.100   80      4m18s
$ date ; kubectl get ingress -n istio-system
Fri Jan 17 11:57:12 EST 2020
No resources found in istio-system namespace.
```

**Comment by tillig** [comment]
I may need to trash the whole install and start over. It appears there are two installations of Kiali running - one in the `istio-system` namespace, and one in the `kiali-operator` namespace, though it's unclear how that happened given there's only one custom resource and it specifies `istio-system` as the deployment namespace.

Let me try doing a clean uninstall and reinstall of everything and try this again so I can verify what's up.

**Comment by tillig** [comment]
Seems the problem was the YAML being off by a space. It appears the CRD for a Kiali custom resource doesn't do much in the way of validation, so if you specify... basically arbitrary YAML, it just gets stored. Unclear how we ended up with two separate deployments of Kiali this way, but... anyway, it appears fixed now. Thanks for your help and patience!

**Comment by jmazzitelli** [comment]
> It appears the CRD for a Kiali custom resource doesn't do much in the way of validation, so if you specify... basically arbitrary YAML, it just gets stored

This is going to be fixed when we introduce CRD schemas - see https://github.com/kiali/kiali/pull/1920
