### ISSUE TITLE
Kiali graph not showing beyound passthrough cluster

### ISSUE THREAD

**Issue by raginireddy96** [kiali/kiali#2129]
I have installed istio 1.4.3 and configured kiali, grafana and jaeger. I have deployed few applications. In kiali graph i can see the graph only till it reaches cluster it is not showing beyond cluster.Please find the below attached screen shot and help m eto resolve this.
![Screenshot from 2020-01-22 09-53-31](https://user-images.githubuserc
![Screenshot from 2020-01-22 09-53-31](https://user-images.githubusercontent.com/33022246/72865383-a3c1c900-3cfd-11ea-882c-a39b81749cd2.png)
ontent.com/33022246/72865359-8ab91800-3cfd-11ea-965b-85ec058c4eb2.png)

**Comment by raginireddy96** [comment]
![image](https://user-images.githubusercontent.com/33022246/72892609-f2db1e80-3d3c-11ea-95fd-b26bdbeb8d89.png)
Above pods are running

**Comment by lucasponce** [comment]
I wonder if you could review if your deployments are following:
https://istio.io/docs/ops/deployment/requirements/

**Comment by raginireddy96** [comment]
yes i have followed those docs

**Comment by raginireddy96** [comment]
this is the sample virtual service
apiVersion: networking.istio.io/v1alpha3

kind: VirtualService

metadata:

  name: qa-stage1-external-vs
  
  namespace: stage1

spec:

  hosts:

  - "qaistio.lendingkart.com"

  gateways:

  - https-gateway                      

  http:

  - match:

    - uri:

        prefix: /auth/actuator

    route:

    - destination:

        host: stage1-auth-server

        port:

          number: 9026



  - match:

    - uri:

        prefix: /auth

    route:

    - destination:

        host: stage1-auth-server

        port:

          number: 80

**Comment by raginireddy96** [comment]
This is the gateway yaml
kind: Gateway
metadata:
  name: https-gateway
  namespace: stage1
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https-secure
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: "NAME"
    hosts:
    - "host-dns-name"

**Comment by jotak** [comment]
I suspect it's an issue with envoy proxies being out of sync and not handling routes as expected. You may read this, hopefully you could get some clues: https://istio.io/docs/ops/diagnostic-tools/proxy-cmd/

Try to run `istioctl proxy-status` to see if there proxy sync issues.

I doubt the issue really is with Kiali. Maybe you can find more help with istio community: https://discuss.istio.io/

**Comment by lucasponce** [comment]
I wonder if installing bookinfo may help to debug and compare "bookinfo" namespace (deployments & services) with the "stage1" artifacts.

**Comment by jshaughn** [comment]
When requests are going to PassthroughCluster it means those requests did not get routed to any in-mesh service and did not match any defined service entry host,  and have been routed out of the mesh.  It can also happen if a service tries sending a request to ingress, it effectively leaves and re-enters the mesh.  In my experience it means there is misconfigured routing, missing istio proxies (sidecars), or possibly there is something like @jotak says. a sync issue or something like that.  Kiali is only showing you what the telemetry is telling us, this is not likely a Kiali issue, or an Istio issue outside of configuration.   For more on PassthroughCluster and BlackHoleCluster this is a good, quick read:  https://istio.io/blog/2019/monitoring-external-service-traffic/

**Comment by raginireddy96** [comment]
Below is the out put for istioctl proxy-status
![image](https://user-images.githubusercontent.com/33022246/72957960-878c5d80-3dcb-11ea-8a7a-dc461586d9b3.png)

**Comment by lucasponce** [comment]
@raginireddy96 It sounds like an Istio problem, but I have interest to dig into the root cause of this.

I have two questions:
a) If you install the bookinfo demo, do you see the graph correctly or also is showing all workloads talking with PassthroughCluster
b) How services are invoked within the namespace ? Is using Kube DNS or perhaps is hiding something ?
c) If you could reproduce this example in some small example that we can take a look I'm happy to try to see locally if I can get the same situation.

In theory, Kiali is correct, as it's describing what it sees, but I'm interested to provide a FAQ for this scenario in the short term, and/or try to "explain" in Kiali (if possible) why this is happening.

Thanks.

**Comment by jshaughn** [comment]
The proxy status looks good.  I think it is a configuration issue.  You are seeing all requests be treated as TCP and routed out of the mesh.  By the way, in Kiali you can click on one of those edges and in the graph side panel select the "Hosts" tab.  This will show you the actual request host and maybe that will help you understand why your intended routing is not working.  I would suggest following up with Istio (Slack, Discuss, etc) for more help.

**Comment by lucasponce** [comment]
@raginireddy96 did our comments help you to spot the issue ?

**Comment by jshaughn** [comment]
@raginireddy96 Assuming issue is resolved and closing.  Please feel free to re-open if you have updates.
