### ISSUE TITLE
[Doc / kiali.io] incorrect wording about "Istio CRD"

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#2130]
On kiali.io front pages, in feature cards, one states: "Configuration - See and edit Istio CRD yaml"

This is incorrect, we see and edit Istio custom resources - not custom resource *definitions*

Suggestion: "See and edit Istio custom resources" or just "See and edit Istio resources"

**Comment by jotak** [comment]
(any preference among suggestions, or other suggestion?)

**Comment by jshaughn** [comment]
@jotak  I'm currently adding a FAQ entry, I'll fix this in there.

**Comment by jotak** [comment]
@jshaughn ah i already opened a pr, but feel free to take anyway (or jump in with discussion about the best wording :) )

**Comment by jshaughn** [comment]
@jotak sorry, I already put it in my PR and asked you top review.  I can revert that change if you like.  I went with  "custom resource YAML".  Just review https://github.com/kiali/kiali.io/pull/195 and tell me what to do with the change in there.
