### ISSUE TITLE
When using Openshift for AUTH_STRATEGY, any path on the URL is lost after sign in

### ISSUE THREAD

**Issue by cfcosta** [kiali/kiali#2131]
Steps to replicate:

* Open Kiali with an URL defined (such as the graph page for an specific namespace) and without being signed in to kiali.
* When you enter Kiali, it redirects you to the oAuth page for the cluster.
* After signing in, you should be redirected to the Overview page instead of the one sent on the URL.

This does not happen if the user is already in, just before being authenticated for the first time.

**Comment by jshaughn** [comment]
OK, I did some investigation into this and it's not really a bug, it's working as currently implemented.  With Oauth you need to register valid redirect URIs in the oauth client.  This is done up front, defined in oauth.yaml.  It is not intended to initially support bookmarking but instead to protect against attacks that redirect back to unintended pages.

There is a mechanism for supporting bookmarking by using the "state" param.  I'm just not sure whether we want to pursue that work unless this gets upvoted.  It may be a little tricky (at least for me)  I'm going to drop this from the sprint backlog and tag for further grooming.

**Comment by jshaughn** [comment]
I'm going to put this back on the backlog but it can likely wait for a community upvote.

**Comment by jshaughn** [comment]
This may need to be resolved for https://issues.redhat.com/browse/ODC-3697, adding to the sprint for more investigation.
