### ISSUE TITLE
Expanded Overview cards use too much space

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#2137]
**Is your feature request related to a problem? Please describe.**
The expanded overview cards utilize a lot of real estate with the graph to the right.

![Expanded_Overview_cards_use_too_much_space_·_Issue__167_·_kiali_kiali-design](https://user-images.githubusercontent.com/1312165/72938705-4c812000-3d20-11ea-972a-c3d0d44446a3.png)

**Describe the solution you'd like**
We discussed this is in the UX review last week and would like to play around with making the expanded view a single column with the graph shown under the status column. This should give room for more namespaces to be shown on the overview screen.

Design Issue Link:
https://github.com/kiali/kiali-design/issues/167

**Comment by mtho11** [comment]
Perhaps something like this: 
![Kiali_Console_-_Firefox_Developer_Edition](https://user-images.githubusercontent.com/1312165/72944321-6e34d400-3d2d-11ea-94ec-041cf8eabcf6.png)

**Comment by lucasponce** [comment]
Was a consensus to put this on Sprint / Backlog ? @jshaughn 
I guess I missed.

**Comment by jshaughn** [comment]
@lucasponce @mtho11 , new issues can not be assigned to backlog and/or the sprint without grooming or at least a discussing it with a team lead.   There is a "discussion needed" label that can be applied to get attention in the next grooming session (for higher prio just ping us as well as adding the label).

UX suggestions don't necessarily imply backlog work.   Current sprint backlog takes priority.  Followed by backlog.  Moving from backlog to print should be approved.   Assignments are usually not suggested for issues not on the sprint backlog.

**Comment by lwrigh** [comment]
Moving the spark line chart underneath the status bar makes sense to me. We could also decrease the height of the spark line chart so it's a closer height to the status bar so it does not occupy as much space.

**Comment by jshaughn** [comment]
We have removed the bar chart completely.  This is done as part of #2896.
