### ISSUE TITLE
eslint issues

### ISSUE THREAD

**Issue by jshaughn** [kiali/kiali#2141]
We are suffering some downstream build issues due to eslint. 

The first change is to limit linting to dev builds.  We don't need to do it in the prod build as the code has already been checked prior to those builds.  This has been changed already in this PR:

https://github.com/kiali/kiali-ui/pull/1623

Furthermore, we should not have to run the linter, for basically the same reason, in the postinstall step.

**Comment by mtho11** [comment]
@jshaughn can this be closed now?

**Comment by jshaughn** [comment]
Probably but @jmazzitelli should decide.

**Comment by jmazzitelli** [comment]
everything looks good to me
