### ISSUE TITLE
Remove tsconfig files

### ISSUE THREAD

**Issue by aljesusg** [kiali/kiali#2142]
We removed tsconfig by eslint but we have the tsconfig files in the project

**Comment by mtho11** [comment]
We can remove the `tsconfig.json.prod` and `tsconfig.test.json` and even scale back some of the properties in `tsconfig.json`, but we still have to have a single `tsconfig.json` Do you know different @aljesusg ?

**Comment by mtho11** [comment]
When I remove those files, it automatically creates a `tsconfig.json` for me then with default values:

```
We detected TypeScript in your project (src/index.tsx) and created a tsconfig.json file for you.

Your tsconfig.json has been populated with default values.
```

**Comment by mtho11** [comment]
Even a `npx create-react-app my-app --template typescript` creates a default `tsconfig.json`.

**Comment by aljesusg** [comment]
At least prod and Dev version I thought that @cfcosta forgot remove them in https://github.com/kiali/kiali-ui/commit/d45f92bc538c1027bf046de6d0d4ce957e95499c where the tasks Related with the lint used them

**Comment by cfcosta** [comment]
Afaik they are different, what I removed was tslint, not tsconfig. Tslint is for typescript-linter, tsconfig is for `tsc` itself.

**Comment by jshaughn** [comment]
The prod build is working so changes here don't have priority.  No need to make any change unless there is a good reason.

**Comment by jotak** [comment]
@cfcosta is right, tsconfig is still necessary afaik

**Comment by aljesusg** [comment]
I didn't see where we are using the tsconfig.prod in the build this is why I opened the issue to remove the tsconfig related with prod build in first step. If you think that we need it I'll close this but where are we using it?

**Comment by mtho11** [comment]
@israel-hdez @cfcosta do you guys know of any productization scripts the use `tsconfig.prod`?

**Comment by cfcosta** [comment]
@mtho11 Not that I'm aware of, but take my words with a grain of salt.

**Comment by israel-hdez** [comment]
@mtho11 that `tsconfig.prod.json` seems to be part of the scaffolded files when creating the app with create-react-app. So, I'd leave it there. It's useless, but someday it's presence may remind us that we can use it and it may become useful :D

**Comment by mtho11** [comment]
@israel-hdez I just did a create-react-app and there is no `tsconfig.prod.json` created. But, it isn't hurting anything, so given folks are nervous about the prod builds right now, it's probably best to leave it.

**Comment by lucasponce** [comment]
>  so given folks are nervous about the prod builds right now, it's probably best to leave it.

Specially on broken build :-).

Closing.
