### ISSUE TITLE
Make Heading fonts more consistent (size-wise)

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#2143]
**Is your feature request related to a problem? Please describe.**
Our Title/heading fonts are different sizes on the various pages.

This issue was discussed in UX meeting last week: https://github.com/kiali/kiali-design/issues/153

**Describe the solution you'd like**
From UX, sounds like heading/title should be 24pt (to match Openshift)

**Comment by abonas** [comment]
@mtho11 why is this labeled maintenance? this is a UX issue, user facing

**Comment by jshaughn** [comment]
@mtho11 @lucasponce It's Maintenenace because UX improvements are ongoing, and everything is user-facing to some degree :)   UX improvements need to be prioritized like everything else, and they don't always have the bang-for-the-buck we can get by spending time in other ways.

**Comment by lwrigh** [comment]
We can take a closer look at font sizes, spacing, wording, and other similar details when we do a design audit of the UI. Just want to make sure everything is consistent.

**Comment by jshaughn** [comment]
I believe this is done, our heading CSS has been made consistent.
