### ISSUE TITLE
Durations list wording

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#2145]
We recently changed the wording in Durations list to remove the "Last" word that was previously there.

The old "Last 10m", for instance, is now "10m Traffic".
The reason is the new graph replay feature for which the "Last" word isn't correct.

However there's now some cases where "Traffic" is weird. I'm thinking about the Logs screen, and the runtimes metrics screen:

![Capture d’écran de 2020-01-24 14-04-34](https://user-images.githubusercontent.com/2153442/73071483-22139c00-3eb3-11ea-810d-a95c7fead0a1.png)

Those kind of screens are not necessarily related to traffic.
My suggestion would be to change our `serverConfig.durations` to just `1m`, `5m`, `10m` etc. and leave interpretation to the caller who can inject any context appropriately. E.g. from Graph replay would be `durations[d] + ' Traffic'` and in logs we could keep `'Last ' + durations[d]`.

WDYT? 
cc @jshaughn

**Comment by jshaughn** [comment]
@jotak Argh, I looked around and it made sense to me everywhere I looked, but I failed to remember about the logs usage (and I wasn't smart enough to actually just search the code),  It doesn't work for logs at all (but to be honest, that is an overloaded/Incorrect use of MetricsDuration component).   I actually went around and around on this.  At one point I was close to your idea and had added "prefix" and "suffix" props to DurationDropdown.  I'm fine with whatever works, this clearly needs to change to better support all uses.

**Comment by jotak** [comment]
Yes it could work with suffix and prefix, or perhaps pass it a string format callback through props.

BTW you're correct about using MetricsDuration for logs, it's not just that the name doesn't make sense for logs but also because these durations used there are tailored for prometheus ttl which doesn't make sense for logs. Maybe we should tackle this as well.

**Comment by aljesusg** [comment]
I think that works for traces too, anyway we can add a prefix like Joel said and set it by default to traffic

**Comment by jotak** [comment]
> BTW you're correct about using MetricsDuration for logs, it's not just that the name doesn't make sense for logs but also because these durations used there are tailored for prometheus ttl which doesn't make sense for logs. Maybe we should tackle this as well.

=> for that, I've opened a "good first issue": https://github.com/kiali/kiali/issues/2154

**Comment by jshaughn** [comment]
@cfcosta See what you can come up with to make this good for the user in all scenarios.
