### ISSUE TITLE
Refactor 3scale integration: introduce a better structure for Kiali extensions

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#2146]
Kiali introduced a 3scale (API Management) integration in previous version.
This integration consisted in addition into the backend and frontend.
In Kiali backend, a specific handler linked with a threescale business logic was created; in the Kiali frontend a new Wizard was located under the Service details and activated when the 3scale adapter was detected in the cluster.

The end-to-end scenario is working and have been tested without major issues.

In the context of #2007, there is a need to re-organize this "extensions" logic in a better way to allow third party components to be integrated in Kiali in an easy way.

The goal of this issue are the following:
a) Incorporate the issue #2032 to improve how the 3scale is detected and activated.
b) Revisit the 3scale adapter and introduce a 3scale view that can be activated from config and it can handle the "3scale handlers" entities. Today the 3scale wizard performs two operations: b.1) create/update a 3scale handler, and b.2) assign/unassign a 3scale handler with a service. So, b.1) can be located in a separate page (list > details) pattern.
c) Structure the code in a way that can help as an example for #2007.

**Comment by lucasponce** [comment]
cc @PhilipGough @unleashed

FYI we are going to start refactoring this feature, we haven't followed up changes on the existing feature, but if we would like to add something for future Kiali versions (thinking on planning for SM 1.2).

**Comment by unleashed** [comment]
@lucasponce there has been little progress on this since we are focused on a different task - hopefully this would not make it any harder to change the existing feature, but open up new options instead.
