### ISSUE TITLE
Custom time search in other screens

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#2147]
Follow-up on https://github.com/kiali/kiali-ui/pull/1588
Goal is to align some other screens with Metrics pages for the custom time search feature

This should impact pages that leverage historical representation of data. I can see so far:

- Logs page
- Traces page

Others pages, such as graph, traffic, overview, entities lists/details (for health) don't really need this IMO as they represent aggregated-over-time data.

**Comment by jshaughn** [comment]
> Others pages, such as graph, traffic, overview, entities list/details (for health) don't really need this IMO as they represent aggregated-over-time data.

Although, when a user identifies a time range of interest I wonder if that time range should be able to be set globally, such that a user can move around and have a consistent historical view?  If not that then perhaps we should look more at a more horizontal page where users can consolidate a variety of selected views for correlation?

**Comment by jotak** [comment]
I don't know... clearly this could be linked somehow to graph replay (maybe, when a custom time period is set, we could have a link displayed saying "Show graph replay for that period" ?)
But having it set globally for Kiali? I don't know, for instance how would it work with listing pages? That would only impact the health calculation but not the list items themselves (we don't know if an entity was present or not at a given time) so I fear this could be confusing for the user. Even health would be screwed up because it's mixing time-based data (error rate) and live data (deployment status).

**Comment by lucasponce** [comment]
One clear area is the traces tab.
I think that deserves parity with metrics because also show now similar info.

**Comment by jotak** [comment]
Note: for traces, we can enable in-chart nav ( https://github.com/kiali/k-charted/pull/78 ) at the same time

**Comment by lucasponce** [comment]
I think with the recent changes, time selectors are consolidated per page and "logs" and "traces" enable the custom time selector.
