### ISSUE TITLE
Decouple data of CytoscapeGraph component from redux

### ISSUE THREAD

**Issue by israel-hdez** [kiali/kiali#2150]
This is a subtask of #1960.

In order for the `CytoscapeGraph` component to be re-usable, each instance of it needs to be data-independent. Currently, the elements of the graph are stored in redux. 

The idea is that the `CytoscapeGraph` component should no longer use redux to get the graph data. This does not necessarily mean that redux will no longer store the graph data. The data of the main graph may still be stored in redux. The main idea is to make possible that each instance of the `CytoscapeGraph` can have it's own data source.

**Comment by jshaughn** [comment]
Is this necessary if only one graph is displayed at any time?

**Comment by israel-hdez** [comment]
Most of my comment on the other issue applies here: https://github.com/kiali/kiali/issues/2151#issuecomment-578836570

This may not be completely necessary. But since I am already pulling the settings, I think it makes sense to also do this effort.
