### ISSUE TITLE
Decouple settings/props of CytoscapeGraph component from redux

### ISSUE THREAD

**Issue by israel-hdez** [kiali/kiali#2151]
This is a subtask of #1960.

In order for the `CytoscapeGraph` component to be re-usable, each instance of it needs to have it's own settings. Currently, the settings of the graph are stored in redux. Because of this, when creating multiple instances of the `CytoscapeGraph`, changing the settings of one of the instances has impact on the other instances.

The idea is that the CytoscapeGraph component should no longer use redux for it's settings. This does not necessarily mean that redux will no longer store them. The settings may still be stored in redux. The main idea is to make possible that each instance of the CytoscapeGraph can have it's own settings (display options, layout, etc).

**Comment by jshaughn** [comment]
Is this necessary if only one graph is displayed at any time?  And how does this play with the url/bookmarking?

**Comment by israel-hdez** [comment]
I think it's so, so necessary. Currently, since we are storing the settings in redux, it is possible to navigate to other pages and, when going back to the graph, settings are preserved. The problem is that for the mini-graph, we would need a fixed set of settings. Since settings are in redux, those settings would need some manipulation programatically. So, the "benefit" of preserving settings would be lost.

The alternative would be to build another graph component only for the mini-graph. But I would like to avoid this, because I would need to extract or duplicate a lot of the logic of `CytoscapeGraph`.

My idea is to pull the settings one level up. So, the `CytoscapeGraph` would no longer be connected to redux. It's the `GraphPage` the one that would be connected to redux (which is already connected anyway). 

URL bookmarking is mostly handled in the `GraphPage` component. So, that's mostly unaffected.
