### ISSUE TITLE
[Logs page] durations should not depend on prometheus retention

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#2154]
While the durations list in most Kiali screens are related to prometheus TTL (retention), it should not be the case for Logs page (and probably not for Traces as well).

As a suggestion, we could add a new flag-prop in `TimeRangeComponent` to tell whether we want TTL-based durations or static durations.

Opening as "good first issue", there's no urgent deadline or too harsh implication.

**Comment by lucasponce** [comment]
Logs tab implements a custom time range 
![image](https://user-images.githubusercontent.com/1662329/105810355-11f13980-5fab-11eb-8700-92d7de3667e4.png)

So, I guess this issue could be considered "done" in the current v1.29 version context.
