### ISSUE TITLE
Excessively long namespaces overflow title line and expand overview card height different

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#2162]
**General remarks**
If you have a very long namespace name (max is 63 chars) it overflows the line length makes that card taller than others.

For UI issues please also add a screenshot that shows the issue.
<img width="1141" alt="Kiali_Console_-_Firefox_Developer_Edition" src="https://user-images.githubusercontent.com/1312165/73235274-94e67680-4142-11ea-999d-31f420a28e85.png">

**Comment by lucasponce** [comment]
I don't think this is a bug.
The Card is showed and information is not lost.
If there is another UI recommendation about this (scrolling, to "cut" the name and put "..." or similar) that's another thing.

**Comment by lucasponce** [comment]
If there is any kiali-design about this, can we link them with the issues ?

Thanks

**Comment by mtho11** [comment]
@lucasponce  Here is the design issue:
https://github.com/kiali/kiali-design/issues/169

**Comment by israel-hdez** [comment]
Fixed in https://github.com/kiali/kiali/issues/2330
