### ISSUE TITLE
Overview N/A Health status font size seems excessive

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#2165]
**General remarks**
The Health status font in overview seems excessive in size compared to other fonts.

<img width="1133" alt="Kiali_Console_-_Firefox_Developer_Edition" src="https://user-images.githubusercontent.com/1312165/73235645-1f7ba580-4144-11ea-87aa-249098b66572.png">

Maybe this is fine, not sure. But when I look a the screen all I see is **N/A** 

Perhaps one or two font sizes smaller?

**Comment by abonas** [comment]
@mtho11 was this discussed with UX team? Currently there's no AI if/how to resolve this issue

**Comment by mtho11** [comment]
@abonas no it has not been discussed. I have created: https://github.com/kiali/kiali-design/issues/170

**Comment by jshaughn** [comment]
cc @lwrigh Do we need a change here?

**Comment by lwrigh** [comment]
@jshaughn Based off of PatternFly 4 text sizes I would suggest using the 16px size.

**Comment by serenamarie125** [comment]
@jshaugn @lwrigh we discussed this at a Kiali UX meeting, and Michael had added his response here: https://github.com/kiali/kiali/issues/2331#issuecomment-582002693

**Comment by cfcosta** [comment]
Is this still valid? Seems to be ok here:
![image](https://user-images.githubusercontent.com/14752/77034856-cc76df80-6989-11ea-9637-fa65b1e5925c.png)

**Comment by jshaughn** [comment]
No longer a problem. Closing.
