### ISSUE TITLE
Kiali does not recognise Jaeger under "/jaeger"

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#2167]
Happens on master.
Install upstream Istio via the hack script.
Jaeger is installed and routed correctly, but it contains "/jaeger" in URI, like: "http://jaeger-query-istio-system.apps.ocp.upshift.redhat.com/jaeger/search?service=details.bookinfo"

Kiali CR is configured to include that "/jeager":
![Screenshot from 2020-01-28 11-13-08](https://user-images.githubusercontent.com/604313/73255599-b423e900-41c0-11ea-9583-5f51bc2b019c.png)

But still, error is displayed that Jaeger is not available:
![Screenshot from 2020-01-28 11-16-19](https://user-images.githubusercontent.com/604313/73255636-c6058c00-41c0-11ea-9d1d-0b869915f86f.png)

But the external linking from Kiali Service Details Traces tab to Jaeger works correctly.
![Screenshot from 2020-01-28 11-26-25](https://user-images.githubusercontent.com/604313/73255788-1977da00-41c1-11ea-9e9f-0f1b19d1a297.png)

![Screenshot from 2020-01-28 11-27-21](https://user-images.githubusercontent.com/604313/73255822-2ac0e680-41c1-11ea-87b8-55bc23198e09.png)

**Comment by jotak** [comment]
@hhovsepy is it a CR file that you provide yourself?
For me, with upstream istio the in_cluster_url is provided automatically in configmap so I don't have to set it up from Kiali CR. It is: `    in_cluster_url: http://tracing.istio-system/jaeger`

**Comment by hhovsepy** [comment]
Yes the CR and configurations are provided during the installation.

**Comment by jotak** [comment]
@hhovsepy so i guess you need to update it. Actually you should even be able to remove the in_cluster_url config, the operator should be able to guess it correctly both in maistra & non-maistra scenario

**Comment by hhovsepy** [comment]
still the same error happens when in_cluster_url config is removed and only the "url" is set

**Comment by jotak** [comment]
Seen with Hayk: the `in_cluster_url` is actually correct and we can see in metrics pages that the span overlay can be displayed (which proves the url works).

However, there is this error message about unmarshalling error, which means that there's unexpected data returned by endpoint `api/services`.
I've created a PR to add more logs and try to understand what's wrong: https://github.com/kiali/kiali/pull/2168/files

**Comment by hhovsepy** [comment]
![Screenshot from 2020-01-28 15-12-59](https://user-images.githubusercontent.com/604313/73271649-40460880-41e1-11ea-9624-5335bdcd11d3.png)

**Comment by hhovsepy** [comment]
Still happens on Kiali master after PR merges, and Maistra 1.0.5 where Jaeger is deployed for instance with search: "https://jaeger-istio-system.apps.ocp.maistra.redhat.com/search?"

**Comment by aljesusg** [comment]
Fix https://github.com/kiali/kiali/pull/2179 & https://github.com/kiali/kiali/pull/2178
