### ISSUE TITLE
how to add a new user in kiali

### ISSUE THREAD

**Issue by harshul4274** [kiali/kiali#2183]
Hello All, Can somebody help me in kiali. I want to know how to add a new user in kiali and how to give a specific right to using kiali

**Comment by jmazzitelli** [comment]
questions like this are best asked on the kiali-users google forum or in freenode IRC #kiali or in Istio.io Slack room #kiali

See: https://kiali.io/contribute/#_talk_with_us

But in short, you don't add multiple users directly in Kiali. If you want multiple users to access it, you can opt to use the auth strategies of LDAP, or token or (if on OpenShift) the openshift strategy. See the docs here: https://kiali.io/documentation/getting-started/#_login_options
