### ISSUE TITLE
Avoid fetch spans when integration is disable

### ISSUE THREAD

**Issue by aljesusg** [kiali/kiali#2187]
If there is not integration with jaeger we should avoid the fetch spans and remove the errorMessage

 * We can control this in the UI or in the Backend like we did with fetchErrorTraces

**Comment by jotak** [comment]
So I talked a little bit with Xavi about that.
I've always been a bit reluctant with this "integration" flag because it means Kiali is turning off jaeger stuff definitively (until next restart) while jaeger could just be unavailable for some temporary reason. To me this is not the right way to proceed.

If people don't want to have kiali connected to jaeger, then they should turn it off via configuration (there's an "enabled" flag iirc). But having kiali deciding on behalf of the user is, IMO, not the right thing to do.

However I agree the situation with alerts constantly displayed is annoying. Afaik we have some mechanism in Alert center to avoid repeating alerts ... I should try to find out how to use it here.

**Comment by aljesusg** [comment]
No jotak, this info is checked Everytime UI fetch /API/Jaeger (every F5 , reload site, login UI). 

On the other hand I agree that user should be set this to disable if he doesn't want Jaeger.

Cc @lucasponce @xeviknal

**Comment by lucasponce** [comment]
To me if jaeger integration is set disabled in configuration it shouldn't fail.
If jaeger integration is enabled but it fails, then having the errors is the expected behaviour.

I understand that the context of this issue is that jaeger was disabled, but spans were queried.

**Comment by xeviknal** [comment]
My environment was messy. I had tracing `enabled: true` but jaeger wasn't properly working. Then we were running the scenario where tracing was enabled but jaeger wasn't available.
So I think I am quite aligned with Joel comment. If we could make this error not be popping all the time it should be better UX.

**Comment by jotak** [comment]
@lucasponce the trick is that there's two "enabling" flags: one coming from config, and one determined at runtime. The latter is set when Jaeger is enabled (from config), Kiali checking if it can be reached or not.

Maybe we could remove the second flag and have a smarter error management to avoid constantly poping errors. And keep only the flag from config as the only source of truth to know whether we want jaeger integration or not.

**Comment by jotak** [comment]
btw I'm going to test what happens when we disable jaeger from config, it's not something I remember to have tested

**Comment by lucasponce** [comment]
> Maybe we could remove the second flag and have a smarter error management to avoid constantly poping errors. And keep only the flag from config as the only source of truth to know whether we want jaeger integration or not.

+1

**Comment by aljesusg** [comment]
Ok, this is my fault, in https://github.com/kiali/kiali/blob/master/jaeger/info.go#L19 we have this control

```go
	if !jaegerConfig.Enabled {
		return nil, http.StatusNoContent, nil
	}
```
This return

```json
{"error":"jaeger is not available"}
```

and it should return 

```json
{"url":"","namespaceSelector":true,"integration":false,"integrationMessage":""}
```

instead an error....I'll do a PR

**Comment by aljesusg** [comment]
I opened the PR https://github.com/kiali/kiali/pull/2191 to fix this, another point is add the "enable" or let the power to the integration. 

I understand the @jotak point but my concern is about a "temporal" integration issue and 1000 messages in the messagecenter related with this

**Comment by aljesusg** [comment]
If jaegers is disabled the response is {"error":"jaeger is not available"} 

in the UI

```ts
 const getJaegerInfoPromise = API.getJaegerInfo()
        .then(response => this.setJaegerInfo(response.data))
        .catch(error => {
          this.props.setJaegerInfo(null);
          AlertUtils.addError(
            'Could not fetch Jaeger info. Turning off Jaeger integration.',
            error,
            'default',
            MessageType.INFO
          );
        });

```

then we call to this.props.setJaegerInfo(null)

```ts
private setJaegerInfo = (jaegerInfo: JaegerInfo) => {
    const jaegerState: JaegerState = {
      jaegerURL: jaegerInfo.url,
      integration: jaegerInfo.integration,
      namespaceSelector: jaegerInfo.namespaceSelector,
      integrationMessage: jaegerInfo.integrationMessage
    };

    if (jaegerState.integrationMessage !== '') {
      AlertUtils.addError(jaegerState.integrationMessage, undefined, 'default', MessageType.INFO);
    }
    this.props.setJaegerInfo(jaegerState);
  };
```

This method should fail in this case

**Comment by aljesusg** [comment]
On the other hand in backend we return a code 0 :( if not client when it should be 4XX

```go
func (in *JaegerService) GetJaegerInfo() (info *jaeger.JaegerInfo, code int, err error) {
	log.Error("Hello")
	client, err := in.client()
	if err != nil {
		return nil, 0, err
	}
	log.Error("Hello2")
	return client.GetJaegerInfo()
}

func (in *JaegerService) GetJaegerServices() (services []string, code int, err error) {
	client, err := in.client()
	if err != nil {
		return nil, 0, err
	}
	return client.GetJaegerServices()
}
```

**Comment by jotak** [comment]
To me, the scenarios to consider are:

1. If jaeger is disabled from config, integration is disabled and Kiali should not even try to do anything with Jaeger. No error displayed.

2. Jaeger enabled from config and available/correctly configured: Kiali shows tracing features

3. Jaeger enabled from config, unavailable or misconfigured (wrong url): Kiali tries to show tracing features, but it fails, so show errors. A mechanism must be in place to avoid too many errors being displayed, I think that can be done purely frontend-wise in AlertCenter (? to check ?)

4. Jaeger enable from config, available (=> works fine) then shut it down: Kiali consistently should show same behaviour as 3.

5. Jaeger enable from config, unavailable (=> same as 3.) then turn it on: Kiali should show working tracing features.

**Comment by jotak** [comment]
I'd like that we have a broader discussion about how to handle repeating messages in the UI. Involving saturn / @mtho11 as he did this commit : 708213e6759837f8efcfc166f4d2b0764c96b65c which afaict prevented messages to pile up in the notif list, but it doesn't prevent multiple popups. Not sure if it could be a behaviour to generalize: if same message is already in notifs list, do not alert on it (just increase the notif counter)
