### ISSUE TITLE
Align duration dropdown in Detail pages

### ISSUE THREAD

**Issue by xeviknal** [kiali/kiali#2188]
Align the dropdwon button on Detail pages.
Align it to tab-level (shifting it down) and align to the right, to the card border. See the image.

![Screenshot of Kiali Console - 2020-01-30T173901 105](https://user-images.githubusercontent.com/613814/73469942-6dccb680-4387-11ea-91f1-fa9c8c92a753.jpg)

**Comment by lucasponce** [comment]
These UX suggestions are not bugs.
Bugs have priority and bandwidth should be used for those, these ones are refinements of the UI (which is good) but it can be put in top of other bug == broken behaviours.

**Comment by jotak** [comment]
A side comment about this task: if we want to align details page with metrics page here, this is probably more than just a design/UX change and we need to think a little bit about code architecture / implementation details here. When we'll try to change the layout, we'll see that we will hit some troubles I think:

Details page is a "high level" component that encompasses Traffic component, Traces component, Metrics component, etc. They are not designed the same way, Metrics component "holds" its toolbar whereas the other pages are "delegating" their toolbar to the higher level component, the Details Page. And more than the component layout, it's also about API/backend fetching functions that are delegated to Service Page sometimes.

Personally I think it's better that the child components are autonomous and able to fetch / show toolbars by themselves. It will also allow to make ServiceDetailsPage, a 574-LOC file, quite thinner.

So this task is probably more than it looks at first sight :-)

**Comment by jotak** [comment]
@xeviknal maybe in task description you could make it clear it also concerns the metrics page? Since currently it handles toolbar differently.

**Comment by xeviknal** [comment]
@jotak It was a quick comment @serenamarie125 did in the last UX/UI meeting. She suggested to have the duration dropdowns aligned to bottom of the div and shifted to the right, aligned with the card right underneath. Though the suggestion didn't apply to dropdowns that aren't at tab level (i.e. metrics, logs).
Action is needed in: Service overview, traffic, traces; Workload overview and traffic; Application overview and traffic; Istio Config details page.

**Comment by lucasponce** [comment]
This can be closed.
Duration component was refactored to a common location for all pages.
