### ISSUE TITLE
Resource badge tooltip in graph side panel should be less transparent or moved aside

### ISSUE THREAD

**Issue by abonas** [kiali/kiali#2196]
Currently the resource badge tooltip in topology graph side panel is overlaying the resource badge.
It also has a high transparency, so its text is difficult to read since it overlaps the text underneath, and it blocks the currently selected badge.
It should either be displayed on the side and not on top of the badge, or at least reduce its transparency to have a more clear view of its text.

This is the current view:
![resourceBadge](https://user-images.githubusercontent.com/6277245/73640529-12484480-4677-11ea-9a71-042dfb3a3e8f.png)

**Comment by jshaughn** [comment]
I was unable to reproduce the transparency issue on Chrome and FF.  Not sure why you see that behavior.   The TT position is on top, it doesn't cover the hovered resource badge.  Although, it could be positioned left for less occlusion of the badges or info above.

**Comment by abonas** [comment]
@jshaughn this is a screenshot from the sprint demo so it was from your env :)

**Comment by jshaughn** [comment]
Perhaps you captured a fade out?  I don't know, it seems fine to me and I have no idea why it would be opaque.  We can change the tooltip position, though.

**Comment by jshaughn** [comment]
@abonas Created two Patternfly-react issues for the tootip weirdness.
cc @beaumorley @lwrigh 
https://github.com/patternfly/patternfly-react/issues/3808
https://github.com/patternfly/patternfly-react/issues/3809
