### ISSUE TITLE
External link not working in graph contextual menu

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#2202]
Hi,

While testing this PR https://github.com/kiali/kiali-ui/pull/1645 for jaeger links I'm seeing that the external links are not working in the graph contextual menu. They don't open a new window with the link as we would expect. 

As we can see here: https://github.com/kiali/kiali-ui/blob/master/src/pages/Graph/SummaryPanelNode.tsx#L383 it's pushing URL to history (which I guess involves react router?), ignoring some parameters set to the link such as the "external" specifier and "target: blank" (see also https://github.com/kiali/kiali-ui/blob/master/src/components/CytoscapeGraph/ContextMenu/NodeContextMenu.tsx#L161-L166 )

I'm not sure if it ever worked or if it's consecutive to the new contextual actions feature.

**Comment by jshaughn** [comment]
> https://github.com/kiali/kiali-ui/blob/master/src/pages/Graph/SummaryPanelNode.tsx#L383

@jotak That's in the new action kebab in the side panel (just as of last Friday), not the actual right-click context menu.  I thought I had seen it working but maybe it wasn't really correct.  If you get the chance can you check the actual context menu to see if that link is working?

**Comment by jotak** [comment]
you're right, the one from right-click menu works. I thought it was the same under the hood.

**Comment by jotak** [comment]
@jshaughn maybe you didn't see it failing because triggering an external link necessitates a special configuration, btw

You need to have an empty "in_cluster_url" for tracing, and a working "url".

**Comment by jotak** [comment]
@jshaughn I can try a fix, I've already kiali configured to reproduce

**Comment by jshaughn** [comment]
@jotak I think I already set things up to have the information needed for a correct link so maybe I just messed up the construction.  Please do have a go at it if you like.  Thanks!
