### ISSUE TITLE
Remove some Service Workloads - Routing wizard is broken and no error

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#2205]
Happens on master.
1. Create "bookinfo->reviews" service with v1,v2,v3,v4,v5,v6 workloads.
2. Got to "reviews" service details page and from Actions menu Create Weighted Routing (with evenly distributed traffic between 6 versions):
![Screenshot from 2020-02-04 18-23-57](https://user-images.githubusercontent.com/604313/73770069-10b47480-477c-11ea-89c0-24d00bd103a0.png)

3. Remove workloads v4,v5,v6.
4. Go to "reviews" service details page and from Actions menu Update Weighted Routing, it will show empty workloads:
![Screenshot from 2020-02-04 18-25-24](https://user-images.githubusercontent.com/604313/73770145-33df2400-477c-11ea-8465-16bd90141c05.png)
Update the routing. And it allows.

5. In service details page and in VS page no validation error is shown, which seems correct as the subsets are missing:
![Screenshot from 2020-02-04 18-26-24](https://user-images.githubusercontent.com/604313/73770277-6d179400-477c-11ea-9d23-70cfc1b7429a.png)

6. Try again to Update Weighted Routing:
![Screenshot from 2020-02-04 18-25-44](https://user-images.githubusercontent.com/604313/73770304-7a348300-477c-11ea-937c-45a66d397c07.png)

It seems the issue is in step 4. when it allows to update routing without existing workloads and removes the subset for them.

**Comment by lucasponce** [comment]
Good one, this is a corner case we didn't take into consideration.
I'll put in my backlog to address it on this Sprint.

**Comment by lucasponce** [comment]
I'm going to document the current flows as perhaps this issue may have different scenarios.

0) Initial situation:
![image](https://user-images.githubusercontent.com/1662329/74531101-089ec680-4f2c-11ea-9399-093466976a76.png)

We have a service with 3 workloads and user creates VS/DR from the wizard.
Note, than only VS/DR generated from the Wizard can be edited in the UI.
Configuration created via CLI can only be modified via YAML editor.

1) Remove one workload:
![image](https://user-images.githubusercontent.com/1662329/74531306-9975a200-4f2c-11ea-925f-914fd98e9bee.png)

We can see in the DestinationRule an error pointing that an existing configuration can't find a workload.
As VS/DR was generated from Kiali, Wizard is available but it's broken as it can't resolve the old workload.

Potential solutions:
1.a) Disable the Wizard on modification conditions (like if it was an external VS/DR created from CLI).
1.b) Reset the VS/DR generated, adding a warning to the user.
"This update will overwrite existing VS/DR"

2) Add a new worklkoad:
![image](https://user-images.githubusercontent.com/1662329/74531727-c6768480-4f2d-11ea-9d83-dcf5ac426be8.png)

We can see the new workload under the Service, but when updating the Wizard, the new workload is not visible (as it was not part of the original VS/DR).

Potential solutions:
2.a) Disable the Wizard on modification conditions (like if it was an external user).
2.b) Add the new workload with weight == 0, that would let user to update the DR.

3) Combined, remove some workload and add new one:
![image](https://user-images.githubusercontent.com/1662329/74531954-54eb0600-4f2e-11ea-8331-8a1d1816f35d.png)

We can see that DR validation in tab is ok, as is reporting a problem with a non existing Workload.
Also cases 1) and 2) are found.

Potential solutions:
3.a) Disable the Wizard on modification conditions.
3.b) Reset the current scenario, reset the weights, as in case 2) is easy to add new ones to 0, but in this 3) scenario removal of an old workload can create a bad weights sum.

**Comment by hhovsepy** [comment]
To document the solution from QE pov we discussed:
When new workload is added: the edit traffic wizard should show new workloads but with 0% weight.
When workload is removed: the edit traffic wizard should show warning icon and message on those non existing workloads, put 0% or empty weight on them (or even disable those lines), and as in this case the sum < 100% then disable Update button. Leaving a user to distribute the traffic between remaining workloads.
