### ISSUE TITLE
Overview - Config Status in N/A

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#2210]
Happens on master.
Overview Page "Istio Config status: N/A" always:
![Screenshot from 2020-02-05 12-49-34](https://user-images.githubusercontent.com/604313/73839495-69d0e680-4816-11ea-84d4-48d96534db14.png)
![Screenshot from 2020-02-05 12-51-31](https://user-images.githubusercontent.com/604313/73839500-6fc6c780-4816-11ea-94ea-736ac2b35979.png)

**Comment by lucasponce** [comment]
Please, check/confirm if this issue happen as well in v1.12 to see if it needs a backport.

**Comment by xeviknal** [comment]
@hhovsepy I can't reproduce the issue. My versions:
```
Kiali UI 1.14.0 (453492a60fd3c7825519cc06a79494d1e3386310)
Kiali Server local_branch (local_branch)
Kiali Container local_branch
```

![Screenshot of Kiali Console (5)](https://user-images.githubusercontent.com/613814/73858352-8bdb6080-4838-11ea-9096-cb1891a46e17.png)

**Comment by xeviknal** [comment]
Found the problem. It is not always that shows the N/A. The problem is for those namespaces with istio objects that are alright (no validations shown).
Good point @hhovsepy :clap:
