### ISSUE TITLE
In standard k8s service no spacing between sidepanel namespace/validation status

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#2217]
**Describe the bug**
If you view a standard k8s app (**no istio sidecars**) in the side panel, the namespace doesn't have a space between the namespace and validation status. It shows as 'my-namespaceN/A'

![Kiali_Console_-_Firefox_Developer_Edition_and_BlueJeans](https://user-images.githubusercontent.com/1312165/73971529-e83f8e00-48d3-11ea-80e2-7cb03e859281.png)

**Comment by lucasponce** [comment]
@mtho11 Please, don't put issues to "In Review"
Attach a PR with the Issue, and the PR will be in Review.

If this is done correctly, when PR is merged, both Issue and PR will move to the Done column.

**Comment by mtho11** [comment]
@lucasponce I believe this should be closed as the PR has been merged.
