### ISSUE TITLE
Graph Side panel validations click should take me to validations

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#2218]
**Is your feature request related to a problem? Please describe.**
When I'm on the graph page and I see validation warnings in the side panel. I want to click on that icon and have it take me to the screen where I can fix or at least get more detail on the validations causing the warning/error.

![Kiali_Console_-_Firefox_Developer_Edition](https://user-images.githubusercontent.com/1312165/73973422-62254680-48d7-11ea-8e30-f0b4928e8d99.png)

**Describe the solution you'd like**
I want the validations icon to be clickable...
1. If there is only a single validation error/warning then a click on that icon should take me to the Istio Config detail page with the YAML tab showing the validation issue, allowing one to easily correct it:

![Kiali_Console_-_Firefox_Developer_Edition](https://user-images.githubusercontent.com/1312165/73972962-8fbdc000-48d6-11ea-8cd9-b243f9870098.png)

2. If there are multiple validation warnings/failures then a click on that icon should take me to the listing page with 'Not Valid' and 'Warning' filters active:

![Kiali_Console_-_Firefox_Developer_Edition](https://user-images.githubusercontent.com/1312165/73972620-fabac700-48d5-11ea-8f6c-9bae973c29f4.png)

**Comment by lucasponce** [comment]
This issue is valid.

I think a link implementing the (2) point:

```
If there are multiple validation warnings/failures then a click on that icon should take me to the listing page with 'Not Valid' and 'Warning' filters active:
```

It's doable and it would benefit the graph with this shortcut.

Adding to the Project per priority purposes only.
