### ISSUE TITLE
Consider upgrading typescript to 3.7.x or above

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#2220]
3.7 brings, among others, a very nice feature, the optional chaining aka elvis operator: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#optional-chaining

That would deserve some checks & regression tests & perhaps other libs upgrades (tslint & such)

**Comment by jotak** [comment]
PS: i'm doing a try in k-charted and seems to go without problem so far...

**Comment by mtho11** [comment]
@jotak, @cfcosta and I have played with this before. It is not just an upgrade but requires some ui code refactoring as well.

**Comment by cfcosta** [comment]
I have it working on a separate branch, but still need to test. Compilation is ok, still need to check CI, will create a PR tomorrow.
