### ISSUE TITLE
Traces page: incremental refresh

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#2221]
It would be nice to have an incremental refresh in traces page. When number of traces fetched is limited, sometimes is only covers a small portion of the area (which is normal) but each refresh _replaces_ the last fetched traces instead of summing to them. IMO it would be better to keep track of the previously loaded ones.

This "incremental refresh" is implemented for spans / metrics correlation so the same algorithm could be used here.

WDYT @aljesusg @lucasponce ?

PS: maybe to not overload the screen, if the user selected a long period, we could hardcode a limit of traces to display (which is different from the fetching limit ; this one can be higher without impacting loading time since data was already fetched).

**Comment by jotak** [comment]
Showing some screenshots:

![Capture d’écran de 2020-02-07 11-10-08](https://user-images.githubusercontent.com/2153442/74021618-230cf900-499c-11ea-9032-df44edfce85b.png)
Here traces are always displayed within the red rectangle when we refresh, replacing the previously loaded ones

![Capture d’écran de 2020-02-07 11-10-08+](https://user-images.githubusercontent.com/2153442/74021674-3d46d700-499c-11ea-9f95-c9ea6211f5b1.png)
What I'd like is that the content in red rectangle is kept (shifted to the left as time goes on), and new data adds up.

**Comment by aljesusg** [comment]
Totally +1

**Comment by lucasponce** [comment]
I think I understand the feature but I need to share some details:
- User performs a query: Give me first 20 traces of last 10m (from timestamp1). (a)
- User performs a refresh: Give me first 20 traces of last 10m (from timestamp2 = timestamp1 + 5s). (b)

So, the suggestion here is to maintain in a state in UI the first result of (a) and accumulate it to (b) and iterate on this pattern.

It sounds ok to me.

**Comment by jotak** [comment]
@lucasponce exactly.
As a reference, this is how it's done for spans in metrics page: https://github.com/kiali/kiali-ui/blob/master/src/components/Metrics/SpanOverlay.ts#L10-L38 . Same logic can be applied.
