### ISSUE TITLE
AzureAD login

### ISSUE THREAD

**Issue by kobemtl** [kiali/kiali#2222]
**Is your feature request related to a problem? Please describe.**
Kiali is very powerful tools, thanks for creating that, so we just need to prevent it fall into wrong hands. Here is my organization we using AzureAD to segregate groups like Admin, Developer etc. But it seems like Kiali not supporting it for auth for the moment.  

**Describe the solution you'd like**
Let Kiali supports AzureAD

**Comment by israel-hdez** [comment]
Hi @kobemtl 

Looks like AzureAD supports OpenID Connect clients. See https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-protocols-oidc.

Starting Kiali v1.19 (to be relased today) there is a new _openid_ login strategy that you could use to "plug" Kiali to AzureAD. If your cluster is configured to accept tokens from AzureAD you should be able to use the new _openid_ strategy. Please, try this new feature.

I'm closing this issue as resolved. If the _openid_ implementation doesn't suit your needs, feel free to re-open or to create a new issue.

**Comment by kobemtl** [comment]
Thanks a lot I will try the new version for sure.

**Comment by lduparc** [comment]
Hi,

Dealing with openid config linked with AzureAD too.
What do you mean @israel-hdez  by :
```
 If your cluster is configured to accept tokens from AzureAD you should be able to use the new openid strategy
```

Thanks

**Comment by israel-hdez** [comment]
@lduparc A simple way I can think of explaining it:

When you authenticate on the OpenId Server (in your case, it's AzureAD), it issues an `id_token` tied to the authenticated user and hands it off to the application. If you, somehow, manage to get this `id_token` that the OpenId Server is issuing and giving to Kiali, try running a command like this one:

```
kubectl --token $YOUR_OPEN_ID_TOKEN get pods
```

If you can list the pods, then _your cluster is accepting the token issued by AzureAD_ (just keep in mind you need to give privileges to the user/token).
