### ISSUE TITLE
"Show on Graph" leaves dirty URL

### ISSUE THREAD

**Issue by jshaughn** [kiali/kiali#2228]
When a user navigates from a detail page to a graph view using "Show on Graph" it's done by navigating to a URL with special query params indicating the element on which to focus.  This is fine, but after rendering the URL needs to be cleaned of that one-time-use information.  Otherwise when navigating in the graph the node may highlight again unexpectedly, for example when starting replay.

**Comment by mtho11** [comment]
@jshaughn that was a good find!

**Comment by lucasponce** [comment]
@jshaughn Please, don't put issues to "In Review"
Attach a PR with the issue closing this one.
Then the PR will be the item to review and when merged, both Issue and PR will be moved to "Done" column.

**Comment by jshaughn** [comment]
@lucasponce yes, just a mistake.  You can always just change something you see as wrong.  The message will be implied.
