### ISSUE TITLE
Improve health calculation of workloads

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#2234]
There are scenarios where a user want to scale down a workload, then an "iddle" / 0 pods controller may be a valid scenario but Kial may mark it as an error/unhealthy condition.

This Epic is to review these potential scenarios and improve the flexibility to configure what healthy means in the context of Kiali:

- [x] Review valid iddle workload situations https://github.com/kiali/kiali/issues/2049
- [x] Add support to configure thresholds about healthy scenarios https://github.com/kiali/kiali/issues/1424

**Comment by aljesusg** [comment]
I have some ideas about this.

1. Create and improve health types and enable/disable them in config file.
2. Have a database :(
3. Related with #1424 . the request is control health of 4xx percentage....IMO it has more sense in a service than a workload, so Should we create "new healths" in workloads and services?
4. If user want a specific health, will it be for all workloads? Should we add in a config file some kind of regular expression for workloads that user want enable that health ?

**Comment by lucasponce** [comment]
This Epic should focus in two first subtasks, I know the topic could be bigger, but just to move in an iterative way:
- First, to show in a better way iddle conditions, defined in https://github.com/kiali/kiali/issues/2049.
- Next, a fstep could be to introduce health parameters at config level, that Kiali can read to compute the health.

But I would work first in those two directions in this Epic, from that we can review and improve.

**Comment by aljesusg** [comment]
I didn't see the #2049 related with this. Today I'll focus in labels and this. Thanks @lucasponce
