### ISSUE TITLE
How to apply and config the jaeger service via kiali

### ISSUE THREAD

**Issue by quzhixue-Kimi** [kiali/kiali#2241]
Hi there,

May I ask one question as below:

During testing the istio with kubectl, there is one configuration that I would like to confirm:

In the install/kubernest/istio-demo.yaml file, there is a configmap as below
**### What is the value of external_services tracing url?**

apiVersion: v1
kind: ConfigMap
metadata:
  name: kiali
  namespace: istio-system
  labels:
    app: kiali
    chart: kiali
    heritage: Tiller
    release: istio
data:
  config.yaml: |
    istio_namespace: istio-system
    deployment:
      accessible_namespaces: ['**']
    auth:
      strategy: login
    server:
      port: 20001
      web_root: /kiali
    external_services:
      tracing:
        url: ### **_what is the url shoud be???????_**
      grafana:
        url: http://grafana:3000
      prometheus:
        url: http://prometheus:9090

And, I just follow the https://istio.io/docs/tasks/observability/gateways/ . Is that external_services tracing url should be http://tracing:80/jaeger?
But, it seems that it is incorrect when I open the url via Kiali UI.
I wonder that why grafana and prometheus url are http://grafana:3000 and http://prometheus:9090

cat <<EOF | kubectl apply -f -
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: tracing-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 15032
      name: http-tracing
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: tracing-vs
  namespace: istio-system
spec:
  hosts:
  - "*"
  gateways:
  - tracing-gateway
  http:
  - match:
    - port: 15032
    route:
    - destination:
        host: tracing
        port:
          number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: tracing
  namespace: istio-system
spec:
  host: tracing
  trafficPolicy:
    tls:
      mode: DISABLE
---
EOF

cat <<EOF | kubectl apply -f -
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: prometheus-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 15030
      name: http-prom
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: prometheus-vs
  namespace: istio-system
spec:
  hosts:
  - "*"
  gateways:
  - prometheus-gateway
  http:
  - match:
    - port: 15030
    route:
    - destination:
        host: prometheus
        port:
          number: 9090
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: prometheus
  namespace: istio-system
spec:
  host: prometheus
  trafficPolicy:
    tls:
      mode: DISABLE
---
EOF

cat <<EOF | kubectl apply -f -
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: grafana-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 15031
      name: http-grafana
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grafana-vs
  namespace: istio-system
spec:
  hosts:
  - "*"
  gateways:
  - grafana-gateway
  http:
  - match:
    - port: 15031
    route:
    - destination:
        host: grafana
        port:
          number: 3000
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: grafana
  namespace: istio-system
spec:
  host: grafana
  trafficPolicy:
    tls:
      mode: DISABLE
---
EOF

**Comment by abonas** [comment]
@aljesusg ?

**Comment by jmazzitelli** [comment]
See the documented Kiali CR for details (note the settings are virtually the same for the configmap which is what you need to edit since you installed with istioctl and not the kiali operator): https://github.com/kiali/kiali/blob/v1.12/operator/deploy/kiali/kiali_cr.yaml#L378-L398 (note also that this link is for version 1.12 - look at the correct version of that file for the version of Kiali you are using)

Also see: https://kiali.io/faq/distributed-tracing/

**Comment by aljesusg** [comment]
Hi @quzhixue-Kimi thanks for open the issue.

This parameter is the Jaeger UI endpoint accesible by your browser so If you can't reach that endpoint by your browser you Won't reach through Kiali-UI.


So in your case in kubernetes you must set this parameter to the endpoint to Jaeger UI provided by the istio-ingress.

**Comment by quzhixue-Kimi** [comment]
Hi @aljesusg 
Copy, copy. Thank you for your feedback and, the issue has been closed.

Sorry for your inconvenience.
BR
Kimi
