### ISSUE TITLE
Overview graph Horizontal line thickness different than other angles

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#2244]
**General remarks**
On purely horizontal lines the thickness is different than on other angles.

![Kiali_Console_-_Firefox_Developer_Edition](https://user-images.githubusercontent.com/1312165/74493981-7b566600-4e88-11ea-9e67-4b1d682117f0.png)

Similar to this: https://github.com/kiali/kiali/issues/2069

**Versions used**
Kiali: current master

**Comment by lucasponce** [comment]
Perhaps this is related to this PR
https://github.com/kiali/kiali-ui/pull/1596

**Comment by lucasponce** [comment]
I think this one is not strictly a bug, but more a minor improvement.
So, I'm going to close it in favor of a future work on charts.
