### ISSUE TITLE
Smaller screen Traces tab layout issues

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#2245]
**General remarks**
On a 1600x900 (not very small) screen there are some issues with Distributed Tracing tab:

![Kiali_Console_-_Firefox_Developer_Edition_and_yarn__Users_mithomps_projects_kiali-ui_and_Kiali_Console](https://user-images.githubusercontent.com/1312165/74494630-61b61e00-4e8a-11ea-9bfb-3e252ccbf707.png)

**Versions used**
Kiali: current master

**Comment by lucasponce** [comment]
I agree that those style issues should be addressed.
Also the "All/Errors" is more a binary state that probably can be changed rather than a button.

**Comment by aljesusg** [comment]
working now
