### ISSUE TITLE
Slow down hover on charts rollover

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#2246]
**Is your feature request related to a problem? Please describe.**
There is no lag on the chart hovers which obstruct the actual values of the chart immediately.

![ScreenFlow](https://user-images.githubusercontent.com/1312165/74496122-95934280-4e8e-11ea-99f6-8b51ffd462bf.gif)

**Describe the solution you'd like**
This is a request originated from a UX meeting.
We need to add a 2 second lag to the hovers appearing.

**Comment by jotak** [comment]
2 seconds, really? That's a lot when you actually want to see details. Maybe something in-between?

**Comment by mtho11** [comment]
@jotak maybe 2 seconds is excessive. I'd be happy with any delay.

**Comment by lucasponce** [comment]
It seems valid to me.

I've added into the Project to work in the priorites later.

It seems minor/easy, so added the "help wanted" labels.

**Comment by jshaughn** [comment]
@lucasponce Is the any chart or just the overview sparklines?

**Comment by lucasponce** [comment]
> @lucasponce Is the any chart or just the overview sparklines?

Missed your comment @jshaughn, I guess it would apply to all charts used for consistency.

**Comment by nrfox** [comment]
Here's a sample of a 0.5 second delay on the overview page.

![withdelayoverview](https://user-images.githubusercontent.com/6226732/118181359-aae67c00-b405-11eb-9019-abca5a2f33f4.gif)

Anymore than that and you'd need to hover over the graph for what felt like a long time in order to see the details.

If a user is hovering over the sparklines, doesn't that mean they want to see more details?

**Comment by nrfox** [comment]
Here's some additional animations with just a 250ms delay.

With:
![with_delay_overview2](https://user-images.githubusercontent.com/6226732/118672346-2a899780-b7c6-11eb-8229-15e9619b5204.gif)

Without delay:
![without_delay_overview2](https://user-images.githubusercontent.com/6226732/118672276-1d6ca880-b7c6-11eb-91c7-12ef400156dd.gif)

With:
![without_delay_metrics](https://user-images.githubusercontent.com/6226732/118668391-d4672500-b7c2-11eb-87d8-4be1d687b1ba.gif)

Without:
![with_delay_metrics](https://user-images.githubusercontent.com/6226732/118668418-da5d0600-b7c2-11eb-9b41-a0ac303565a9.gif)


IMO adding the delay (even a very small one) does not improve the UX for a couple reasons:
1. The delay adds a bit of stutter to the tooltip. This makes the UI seem less responsive than without the delay.
2. Increases the feedback loop between a user mousing over a metric and seeing the tooltip appear. It's natural to hover over the sparklines with the mouse to see more details. Introducing a delay here increases the time between a user's action "hovering over the sparkline" and the feedback "the tooltip popping up". If a user is hovering over a sparkline, presumably they want to see more details. If they are not hovering over the sparkline then the tooltip is not blocking the chart which was the reason for adding the delay in this issue.

I'm in favor of closing this issue without implementing the delay.

What do you think @lucasponce @jshaughn?

**Comment by jmazzitelli** [comment]
I see no point to adding this delay. The only thing I could think of why we would want this is when you drag the mouse across the chart quickly (to move the pointer across the screen to the other side) and you don't want to see the tooltips flash as the mouse moves across the screen. But I really don't think even that matters much.

**Comment by jshaughn** [comment]
@nrfox Thanks for the investigation and the comparitive videos.  To me, the delay request was based mainly on Mike's opinion and I think your analysis-backed opinion trumps the original request.  I'm for closing.  @lucasponce , please close unless you feel strongly we should make the change.

**Comment by lucasponce** [comment]
I'm fine with closing.
