### ISSUE TITLE
kiali.io - Quick install page

### ISSUE THREAD

**Issue by xeviknal** [kiali/kiali#2251]
Bounce rate for the getting started page is really high (above the average).
We have a strong recommendation to have a shorten version of that with the necessary pre-requisites. This short version, aka Quick Install, should be linked to the more detailed "Getting started" page.

This will help us with two things:
1. Make easy the task of assess Kiali for a very first time. Thinking of those users installing istio for first time in sandboxes that they don't care about small details (LDAP, uninstall, login strategies). We do want to reduces at maximum the friction for them to install and try kiali.
2. We want to have a Goal page to setup `success goals` in our website. This will give a way to  to measure the effectiveness of channeling traffic to that page. That is an old good practice on internet for quite a while.

Suggestion from Ospo team

**Comment by lucasponce** [comment]
I agree with @xeviknal comments.
The experience to install Kiali is pretty deep and from a normal the first message/technical recommendation is about openshift.

**Comment by lucasponce** [comment]
Also, a side note, we should try to unify both experiences from istio.io and kiali.io.

https://istio.io/docs/tasks/observability/kiali/

**Comment by lucasponce** [comment]
I think this is discussed also in the kiali-dev
https://groups.google.com/forum/#!topic/kiali-dev/qIzIrSK_Xpg

**Comment by lucasponce** [comment]
@jshaughn I moved this to backlog, I guess there has been a good discussion on the thread and probably this is ready to put someone working on it.
