### ISSUE TITLE
Empty table in lists - Filters are gone

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#2259]
Happens on master, caught by UI automations.

List anything, for instance Apps. On all namespaces.
Filter by some value which returns empty result, for isntance "health = Degraded"
The Filters section is hidden alongside with empty table. - Bug
Refresh the page.
All Apps are loaded (unfiltered), applied Filter is there (without applying). - Bug.

Do we need to hide the Filters section at all? Because the namespace could not have a result for now, but the new pods are starting and auto refresh will bring results soon. Hiding filters section (with refresh) can confuse users.

My idea is to keep the Filters toolbar always, but show that "No applications found" when table is empty.

**Comment by hhovsepy** [comment]
![Screenshot from 2020-02-18 09-33-36](https://user-images.githubusercontent.com/604313/74718785-2cffe900-5233-11ea-83b4-9114255b1bb3.png)

![Screenshot from 2020-02-18 09-37-04](https://user-images.githubusercontent.com/604313/74718790-2ffad980-5233-11ea-8601-eb499d6b73e8.png)

**Comment by lucasponce** [comment]
A filter can show empty results.
But filter should be visible always.

It sounds a regression.
