### ISSUE TITLE
Be able to upload download IstioConfig Objects

### ISSUE THREAD

**Issue by aljesusg** [kiali/kiali#2267]
## Topic
It would be great if the user can upload (overwrite) or download the IstioObjects.

## Why
This provide to the user the possibility to download the files for backup or share, or upload the files to overwrite them (use case: the user make changes and he wants recover his system).

## How
Upload with https://patternfly-react.surge.sh/documentation/react/components/textinput (type = "file")
![upload](https://user-images.githubusercontent.com/3019213/74817072-9b5cae00-52fc-11ea-932e-d3e140a778b2.png)

After Upload we'll check if the file is correct with Kiali validations before enable the **save** button

Download with File download https://patternfly-react.surge.sh/icons
![download](https://user-images.githubusercontent.com/3019213/74817068-9a2b8100-52fc-11ea-9141-3d5c5040fa22.png)

## In a Future

Create IstioConfig Objects uploading files

**Comment by lucasponce** [comment]
https://github.com/kiali/kiali/issues/1502
