### ISSUE TITLE
Sunset k-charted-pf3

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#2271]
K-charted allows multiple frontend implementations, it started with pf3/react and then had pf4/react coexisting (as two separated modules). There is no usage of k-charted-pf3 now, so we could remove it. 

That would reduce the maintenance work (like snyk reporting vulnerabilities https://github.com/kiali/kiali/pull/2269 )

PS: @jshaughn  @lucasponce I was about to put it straight in backlog as I don't think it needs much discussion (so less triage for you) .. but rules vs common sense .. rules win this time

**Comment by jshaughn** [comment]
@jotak thanks for following the procedure.  +1 to adding to backlog.

**Comment by jotak** [comment]
Reopening, I guess the closing wasn't intentional?
