### ISSUE TITLE
On Kiali.io create a 'Latest Videos' section

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#2274]
Similar to the **Latest in our blog** section, a **Latest Videos** section would bring better visibility to the videos (especially if we start adding more). Currently, the videos are hidden at the bottom of the page under the Youtube icon:

<img width="1274" alt="Kiali__Service_mesh_observability_and_configuration" src="https://user-images.githubusercontent.com/1312165/74967458-dd095980-53cd-11ea-80f0-116a3992b864.png">

And certainly does nothing to highlight the latest videos (which should just be one click away)

There is also the **Check out our demo videos** button which could even be **removed** if we added the **Latest Videos** section:

<img width="1152" alt="Kiali__Service_mesh_observability_and_configuration" src="https://user-images.githubusercontent.com/1312165/74967997-eba44080-53ce-11ea-8d23-1f9c4e05b45d.png">

**Latest revision:**

![Kiali__Service_mesh_observability_and_configuration](https://user-images.githubusercontent.com/1312165/78197388-08a24980-743a-11ea-96d0-b23558b70b84.png)

**Comment by jshaughn** [comment]
Epic: #1582
