### ISSUE TITLE
Support canonical_service fields in Istio 1.5+ telemetry

### ISSUE THREAD

**Issue by jshaughn** [kiali/kiali#2276]
Istio 1.5 introduces destination_canonical_service and source_canonical_service into the telemetry metrics.   This is basically the solution to the problem of having different label approaches for specifying what Istio calls the "app" label.  The approach is basically to set the canonical_service field using a prioritized list of possible sources.  There should be new doco for this in Istio but I don't see it yet.  From the original proposal (may have changed) the order is:

1. The service.istio.io/canonical-name label.
2. The app.kubernetes.io/name label.
3. The [Istio] app label
4. The workload name (e.g. Deployment or Job name).

A canonical_revision is also proposed to replace 'version', but it is not included in 1.5.  I expect it has a good chance for 1.6.

UPDATE: canonical_revision is also included in 1.5.

**Comment by jshaughn** [comment]
Update:  Istio upstream has also added canonical_revision to metrics in the 1.5 release.  From the proposal the order is:

The service.istio.io/canonical-revision label.
The app.kubernetes.io/version label.
The [Istio] version label
"latest"

**Comment by jshaughn** [comment]
In the below blurb assume that each label reference would be prefixed with either `source_` or `_destination`:

With the introduction of `canonical_service` and `canonical_revision` the existing `app` and `version` labels are deprecated.  Note that when the [istio] `app` label is in use then `canonical_service` and `app` will be set to the same value.  The same is analogously true for version.   This is important because we need to be careful not to double-report.  In general the approach will be to use the canonical fields if available.  This will likely be done via version-specific conditionals in the code, like if (istioVersion >= 1.5) then useCanonical.   It can't really be done by altering queries.   There is a downside in the case of a user upgrading to 1.5; any existing time-series will be ignored for queries matching specifically, or aggregating on the canonical fields.   This will affect queries for data when the time range spans into the pre-1.5 data.  I'm not sure how much of a concern this is because I'm not sure istio makes any guarantees about old data when updating, they promise (I think) only to be backward compatible from a breakage perspective.

**Comment by mtho11** [comment]
I assume there could also be issues with downgrading, say from 1.5 to 1.4 because the user decided their stuff ran better on the previous version. But maybe we don't even need to worry about this?

**Comment by jshaughn** [comment]
> I assume there could also be issues with downgrading...

@mtho11 I think it's the same issue in reverse and there is not much we can do about it, so by taking the approach of version-conditional handling, and preferring the new fields, I think we at least guarantee compatibility.  Any telemetry that gets missed will be temporary as data rolls off the TTL cliff.
