### ISSUE TITLE
Add Focus Animation when using back arrow from zoomed graph view

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#2281]
**Is your feature request related to a problem? Please describe.**
It would be a nice feature if we showed the focus animation when hitting the 'Back to graph' arrow when returning from the zoomed graph view.

![Kiali_Console](https://user-images.githubusercontent.com/1312165/75074085-bf142580-54af-11ea-8491-afbe88338b15.png)

**Additional context**
This focus animation is done when navigating from Detail page 'Back to Graph'
Something like this:

![focus-animation](https://user-images.githubusercontent.com/1312165/75073982-7e1c1100-54af-11ea-819e-ad64818a6dbe.gif)

**Comment by lucasponce** [comment]
+1
This one was untouched for some time but it seems useful to me.
When user zoom in to an element and it returns to the main graph, it may benefit the "focus" animation to help to situate the zoomed element.

**Comment by jshaughn** [comment]
In addition to this change, while in Focus Animation are I want to remove the current behavior of enabling Idle Node Display.  This was originally done to ensure that the node was actually in the graph and available for selection, but when not needed this is an unexpected option and can litter the graph with orphaned idle nodes.  Instead, I think if the focus node is not foud we should just generate an information toast message.
