### ISSUE TITLE
How to deal with apps where only some workloads have a sidecar?

### ISSUE THREAD

**Issue by pilhuhn** [kiali/kiali#2287]
In this screenshot, _productpage_ is marked as having no sidecars.

![bildschirmfoto 2018-09-26 um 12 43 41](https://user-images.githubusercontent.com/208246/46078012-2468c780-c193-11e8-935e-cba97b57c860.png)

Hovering the health marker shows that only some of the workloads have no sidecar, but some do.
The information may be misleading to the user.

I could imagine to show only half of an Istio-ship here, to indicate this "mixed" mode. Also as some v-services point to the productpage app, we should perhaps also put a warning on the health, as apparently the user forgot to instrument the workload.

**Comment by lucasponce** [comment]
Outdated.
