### ISSUE TITLE
When user has very few namespaces the overview page needs an alternative look

### ISSUE THREAD

**Issue by abonas** [kiali/kiali#2288]
When user has very few namespaces the overview page needs an alternative look, otherwise most of the page is empty.

Example:
https://user-images.githubusercontent.com/604313/48913703-6f444a00-ee79-11e8-8342-8a64cdbb3024.png

**Comment by lucasponce** [comment]
Closing due lack of activity in +10 months.
If still valid, let's open a new one with more actionable items.
Transfered from kiali-design to not miss the discussion.
