### ISSUE TITLE
Improve visualization of labels validation

### ISSUE THREAD

**Issue by abonas** [kiali/kiali#2291]
relevant JIRA https://issues.jboss.org/browse/KIALI-2143
Presence of labels app, version is a recommended practice for Istio:
https://istio.io/docs/setup/kubernetes/spec-requirements/

We have some support of this (see below), but it should be enhanced and refined.
![labelvalidation](https://user-images.githubusercontent.com/6277245/49870241-7973bb80-fe1b-11e8-8a80-f4285d56bdb5.png)

When I read "label validation: app, version" it is not necessarily meaning "validating for presence of labels named app, version, they are both present, or 1 is missing". It could also potentially mean: "I've found 2 labels named X, Y, lets validate their content for Z based on some rule". And when there is a row with no statement at all for "label validation", it is impossible to understand that something is missing.
IMO it should be like with missing sidecar situation (after the redesign) - when it is missing, it says it's missing. and here's with the labels it's a mixed situation with no clear indication what is wrong.
For jaeger pod for instance there's only the app label, so it says "Label validation: app" - might be "validated the content of label app" (and the results/implications are nowhere to be seen).

So we need some new design around this that will indicate for every relevant entity:
1. If the labels app, version exist, if one/both are missing - which ones. should some icon/colors be used for that indication? (The label colors atm is grey and they are not the same as we present labels in other pages.). As the labels are a recommendation and not "a must", we should probably not use error/red for a missing one.
2. indication is needed for list view and object details view.

@serenamarie125 @cshinn fyi

**Comment by lucasponce** [comment]
This issue is still open and valid.
It has some recommmendations that weren't applied.
Added to the backlog.

**Comment by jshaughn** [comment]
Note that work in this area should likely be done assuming istio 1.5 or later, and the introduction of the new istio labels on workloads:
- service.istio.io/canonical-name
- service.istio.io/canonical-revision

These are now the preferred labels.  If unset explicitly, they will be populated using a prioritized list of options:
For service.istio.io/canonical-name:
- app.kubernetes.io/name label
- app label
- workload name

For service.istio.io/canonical-revision:
- app.kubernetes.io/version label
- version label
- "latest"

**Comment by jshaughn** [comment]
@lucasponce It's been a year on the backlog, still valid or obsolete?

**Comment by lucasponce** [comment]
This one was addressed and consolidated.
![image](https://user-images.githubusercontent.com/1662329/128163395-a096f0c2-0803-4540-ad60-4e23b84767e8.png)
