### ISSUE TITLE
Visualize VirtualService and DestinationRule relationships on Istio Config details

### ISSUE THREAD

**Issue by pilhuhn** [kiali/kiali#2292]
_Originally posted by @pilhuhn in https://github.com/kiali/kiali-design/issue_comments#issuecomment-446599565_

 Very often a VS or DR does not come alone, but they refer to each other. Suppose you edit a DR and change the subset name. This may by itself be no issue, but it may render the VS invalid.

We should change the design of editing page / editor in a way that we also show the linked counterpart
E.g.:

![design-72](https://user-images.githubusercontent.com/208246/49885473-9918dd00-fe37-11e8-80a4-94103138e984.png)

Here the subset 'a' in the left editor pane (editing a VirtualService) refers to the subset definition in the DestinationRule on the right.

Currently we don't show both and the user basically has to write down the content of the other item in order to get the right values while editing.

**Comment by lucasponce** [comment]
+1 on visualize the relationships between objects.
The first mechanism for this feature is already in place, used for Gateways, but we need to check if it cover VirtualServices <-> DestinationRules relationships.
If not, this issue can be used to extend those use cases.

**Comment by lucasponce** [comment]
References between objects will be addressed on https://github.com/kiali/kiali/issues/4241
So I'll close this one to consolidate the efforts in the newer one.
