### ISSUE TITLE
Error page design

### ISSUE THREAD

**Issue by xeviknal** [kiali/kiali#2293]
We show the following page when we have a problem on our React side:
![screenshot of kiali console 11](https://user-images.githubusercontent.com/613814/49885548-d0878980-fe37-11e8-8349-2b6c61462e9b.png)

Does patternfly have something to make this page a little bit prettier? I know, we don't want to show this page to anyone, but you know, sometime it happens. There is this issue that is breaking things in service details page: https://issues.jboss.org/browse/KIALI-2015

**Comment by lucasponce** [comment]
Kiali introduced an ErrorBoundary component implementing this pattern.
