### ISSUE TITLE
Review time range on graph

### ISSUE THREAD

**Issue by jshaughn** [kiali/kiali#2294]
This is just to ask for review of the new time range display on the graph.  It is the work for https://issues.jboss.org/browse/KIALI-565.   We now show the time range the graph represents, it updates on each graph refresh.  It is in the locale and TZ of the client:

![kiali-565](https://user-images.githubusercontent.com/2104052/50231697-631ab200-037d-11e9-9917-562cc9a0be28.png)

**Comment by lucasponce** [comment]
Outdated.
