### ISSUE TITLE
Not all checks passed error needs more details

### ISSUE THREAD

**Issue by abonas** [kiali/kiali#2297]
![notallcheckspassed](https://user-images.githubusercontent.com/6277245/51537264-b5586280-1e56-11e9-888d-aa1056e70100.png)
This error needs to have more guidance for user - why/which checks didn't pass, where can the errors be seen, etc.
cc @xeviknal

**Comment by lucasponce** [comment]
I think this one is still valid.
I also find useful that in the Overview tab of a Istio Config issues can be enumerated.

**Comment by lwrigh** [comment]
@abonas @lucasponce This is more of a general question around errors but do you know if any cryptic errors are surfaced to the user in any other parts of the UI? It would be great if we could take a UX approach towards error messages in both the UI and the CLI to try to make them clear and concise if there are any cryptic or gnarly messages.

**Comment by xeviknal** [comment]
@lwrigh the message shown here is for the validations of that specific Istio Object.
The validation icons are shown from the overview page (in each namespace level) to t both service and istio object list and details page. I think the experience is pretty unified.

However, this case is pretty raw. Users arrive here and only see the message without any other explanation. They can't see where the validation errors are until they are in the YAML editor.

I guess that we should be more clear with this specific copy and also using the usual component for listing the problems found for this specific object.

Let me paste you screenshots of the istio object drill down path:

![Screenshot of Kiali Console (27)](https://user-images.githubusercontent.com/613814/76105537-68d9d300-5fd5-11ea-9818-77b36a82a302.png)

![Screenshot of Kiali Console (28)](https://user-images.githubusercontent.com/613814/76105548-6d05f080-5fd5-11ea-9c58-684b8aaeb4b1.png)

![Screenshot of Kiali Console (29)](https://user-images.githubusercontent.com/613814/76105555-70997780-5fd5-11ea-882e-925bb90e7962.png)

![Screenshot of Kiali Console (30)](https://user-images.githubusercontent.com/613814/76105560-74c59500-5fd5-11ea-8903-2c1c407be2c2.png)

![Screenshot of Kiali Console (31)](https://user-images.githubusercontent.com/613814/76105578-7d1dd000-5fd5-11ea-9132-9860d2062e62.png)

![Screenshot of Kiali Console (26)](https://user-images.githubusercontent.com/613814/76105513-624b5b80-5fd5-11ea-989c-5cffc45d0126.png)

Besides that, the cryptic messages we have, mostly, are shown in the notification drawer. And there, we don't have it that much standardized. They are mostly like: "Notification message: copy-past from server".

Did it help? Don't hesitate to ask more questions plz.

**Comment by lwrigh** [comment]
@xeviknal Thank you for sharing these they are very helpful! The error messages in the screenshots do not look overly cryptic to me which is good. It might be useful to take a closer look at the writing of the notification drawer messages if those are more cryptic.

**Comment by xeviknal** [comment]
Closing this because it doesn't apply anymore after this change: https://github.com/kiali/kiali/issues/3161
