### ISSUE TITLE
Add small graph(zoomed-in neighbors) to service detail pages for better context

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#2298]
When working on editing Yaml or other Service Detail tasks, I often find myself forgetting what the piece of topology looks like. A read-only view of the zoomed-in topology (just showing the connected neighbors of the node) would provide a context for making better editing decisions. Seeing some of the badging would be helpful. And besides, we have plenty of room on those pages and the eye-candy couldn't hurt.

The zoomed-in graph part would like something like this:
![zoom](https://user-images.githubusercontent.com/1312165/52088422-9ea1c200-2560-11e9-8260-24974af010b8.png)

It could be made fairly small because its just there for context.

![service-info](https://user-images.githubusercontent.com/1312165/52088663-5a62f180-2561-11e9-9847-e39cefe1f8af.png)

And on the Yaml editing pages too:

![yaml-editing](https://user-images.githubusercontent.com/1312165/52088696-71a1df00-2561-11e9-95b1-1b6ce4bc8f3e.png)

Jira: https://issues.jboss.org/browse/KIALI-2345

**Comment by lucasponce** [comment]
Related to https://github.com/kiali/kiali/issues/1960
Closing for now, and we can review in the future if minigraph can be also extended to Istio Config section as well.
