### ISSUE TITLE
Details Page Redesign - Iteration 1

### ISSUE THREAD

**Issue by serenamarie125** [kiali/kiali#2300]
Create high fidelity mockups for the first iteration of the details page redesign
- Update Page title visuals (margins/font size)
- Update Tab visuals
- Change Info tab label to Overview
- Location of breadcrumbs
- Breadcrumb shouldn’t include the tab name
- Do not include badge in the first iteration

**Comment by lucasponce** [comment]
This issue can be considered completed.
