### ISSUE TITLE
Adding config validation for service list

### ISSUE THREAD

**Issue by burmanm** [kiali/kiali#2302]
There's a need (KIALI-2454) to add config validation for services and as the first case for ports between deployment and service.

This would require changes to the Services list as well as the Services overview. For the services list I would propose to add a column with the "Config" text and icon similar to the Istio Config list in a new column:

![service_config_validation](https://user-images.githubusercontent.com/562574/55904072-b4260e80-5bd7-11e9-8947-58022644578a.png)

For the service details we would need to show that same information as well, but how should this for ports be represented? Would a small icon next to the port in question be enough? Or would a yellow exclamation mark (or red icon) next to it be enough and we skip polluting the UI with green icons?

**Comment by lucasponce** [comment]
This is completed.
