### ISSUE TITLE
Soften the abruptness of 'Iniitializing' screen

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#2303]
Can we do something to soften the initializing screen that pops up around login. Deep linking screens will also see this even if they are authenticated. It flashes for usually < 1 second but is a bit jarring. Is there a PF standard around this kind of screen.
Just some softer touches, transparency, whatever...

![initializing](https://user-images.githubusercontent.com/1312165/56101172-28adc580-5ed6-11e9-961d-eddbf78e7422.png)

**Comment by lucasponce** [comment]
This issue is related to PF3.
Now with PF4 I'm not sure if it is still valid.
Closing, please, re-open with more details if there is any action around it.
