### ISSUE TITLE
Show external traffic policy setting

### ISSUE THREAD

**Issue by israel-hdez** [kiali/kiali#2304]
The JIRA motivating this is: https://issues.jboss.org/browse/KIALI-2646

In short: Istio has a "traffic policy" setting for traffic going out of the service mesh (aka "external traffic"). It allows to configure the default policy: either disable or enable external traffic by default. When external traffic is enabled by default, it has the side effect that monitoring of external traffic gets disabled (because it is not possible). So, we want to have an indicator showing what's the default external traffic policy.

When exchanging some comments with the team, we think we don't want to overload the masthead with indicators (we already have the mTLS indicator). Perhaps, it may be better to place another option under the '?' button of the masthead:

![image](https://user-images.githubusercontent.com/23639005/56519928-caea3080-6508-11e9-9c34-fdc575eacc31.png)

The debug dialog is too technical and the about box doesn't seem appropriate. So, perhaps a new dialog or any alternative way to show a list of server settings could be better.

The "traffic policy" is not the only setting we may show. In the Jira, some of the comments mentions other useful settings we may want to show:
* We may want to move the global mTLS indicator to the new control
* Prometheus data retention interval
* Prometheus data scrape interval
* The istio namespace name

We already show some of these configs in the "View debug info" dialog. Remember that the main point for this UX issue is to show what is the default traffic policy. So, if UX thinks that a new indicator in the masthead is OK, we can go that route (we would need a icon for the masthead).

**Comment by lucasponce** [comment]
Related to https://github.com/kiali/kiali/issues/1484
