### ISSUE TITLE
Proportion of Graph page relevant to graph is shrinking

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#2305]
The graph keeps shrinking as we add more things. Proportionately, the graph, which is the most important thing on the page, is losing geography to other less important things such as navigation and details sections. The topology should dominate the view.

![graph](https://user-images.githubusercontent.com/1312165/56550415-71025e80-653a-11e9-81b1-913a526f601e.jpg)

**Comment by lucasponce** [comment]
I'd say that with the effort to migrate to PF4 this issue was addressed.
I'm going to close it, but please, re-open with more details if it's still relevant.
