### ISSUE TITLE
Website needs to incorporate Kiali Versions better

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#2310]
We have no concept of Kiali versions on the documentation website. Especially now with operators install instructions are different based on versions.

How do we convey versions of Kiali that features were introduced?
This will even be more important with Productized stuff as the time lag increases between master and released versions.

**Comment by lucasponce** [comment]
This is still valid, but there are several efforts around it that should be tracked down in:
https://github.com/kiali/kiali/issues/2181

I'm going to close it to address this with a common strategy about re-org documentation.
