### ISSUE TITLE
Browser Size

### ISSUE THREAD

**Issue by mattmahoneyrh** [kiali/kiali#2315]
When shrinking the browser size, eventually the Legend becomes unusable.
Question is, what size browser window do we support? Tablets ?Cell Phones?

![Selection_092](https://user-images.githubusercontent.com/7262987/66079194-93f55d80-e531-11e9-8da8-3ba1a85b0f05.jpg)

**Comment by lucasponce** [comment]
I think this one is still valid.
I guess we don't have plans to tackle tablet / phone yet, but probably some confirmation around this could be good.

Please @kiali/ux-reviewers feel free to add comments.

**Comment by jshaughn** [comment]
Supporting tablets may be a goal at some point but I think we'd need a lot of upvotes from actual users.

**Comment by beaumorley** [comment]
Any chance we could find out the device a user is accessing from via logs? To get an idea as to what percentage this actually impacts? May help prioritize.

**Comment by lwrigh** [comment]
Just wanted to cross reference this issue: https://github.com/kiali/kiali/issues/2487

**Comment by lwrigh** [comment]
Here is one idea for having a modal pop up if the window size gets too small on the graph page.
![Too small window resolution](https://user-images.githubusercontent.com/20227374/80141578-c02d0600-8577-11ea-9196-724706315597.png)

**Comment by lwrigh** [comment]
Is there any more UX feedback that is needed for this issue? If not can the waiting label UX be removed?

**Comment by jshaughn** [comment]
@lwrigh I'm removing the waiting-ux label and setting this to a non-backlog enhancement.  If we get push to better support tablets then this would gain priority.  Until then the warning approach is valid if we want to move forward.

**Comment by lucasponce** [comment]
The original issue seems outdate.

Kiali was worked and improved small screen scenarios, supported 1024 widths for standard examples:
![image](https://user-images.githubusercontent.com/1662329/107951086-0f757480-6f98-11eb-81df-edb3d34519fc.png)

But I think there is not a clear action to follow from the discussion.

Kiali will start more tasks related to scalability of graph and rest of the features where we can revisit this.

Closing.
