### ISSUE TITLE
PF4 wastes space and causes users to needlessly scroll

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#2317]
Here is another example of why I think this entire PF4 migration is making the UI look worse. Take a look at this page and notice how much white space is in here. There is so much wasted space, that I am forced to scroll down to see the additional tabbed data at the bottom. This should not be. There is plenty of room on the screen for all of this to fit.

![wasted-space ogv](https://user-images.githubusercontent.com/2029470/68352366-31fdba00-00d4-11ea-94c0-6b4d1e4b2bdc.gif)

**Comment by lucasponce** [comment]
This issue is still valid and it has some recommendations for the Service Details page that are not yet implemented.
So, I moved to backlog to continue adding these suggestions to the details pages.

**Comment by lucasponce** [comment]
There has been some improvements related to this:
![image](https://user-images.githubusercontent.com/1662329/97708653-6d4d8180-1ab9-11eb-8959-5f32453cad1b.png)

Also introducing inner tabs inside cards to control the height and aspect of the main page:
![image](https://user-images.githubusercontent.com/1662329/97708744-90783100-1ab9-11eb-85b9-3ad095aac647.png)

As last comment is pretty old I'm going to close it.
