### ISSUE TITLE
Font Size Validation

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#2318]
Can we get some validation on the font sizes? IMO: The fonts seem quite large and limit the information density on a given page. Are we supposed to be using 16-20px fonts on the page?

![font-size-listing](https://user-images.githubusercontent.com/1312165/68432771-ef86bc80-0169-11ea-8b0e-f795cfd42237.png)

**Comment by lucasponce** [comment]
I remember @aljesusg has some WIP to clean some CSS styles.
Perhaps this is related to that task ?

**Comment by jshaughn** [comment]
Closing as @lwrigh indicated font size seems appropriate given current PF4 styling.  Overall PF4 space concerns are being tracked in #2317.

cc @beaumorley
