### ISSUE TITLE
Heading Fonts not Similar in Pages

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#2319]
The Headings for each page in Kiali in not very consistent. When you jump from page to page the heading sizes change from 14px to 36px so it doesn't really feel like the same application.

**Listing Pages:**
<img width="1611" alt="Kiali_Console_and_mtho11_on_freenode_IRC_Network_—__kiali__24_users____cnt_" src="https://user-images.githubusercontent.com/1312165/68434748-9a00de80-016e-11ea-82bc-3257b736b41e.png">

**Graph Page:**
<img width="1603" alt="Kiali_Console" src="https://user-images.githubusercontent.com/1312165/68434805-bbfa6100-016e-11ea-9596-0ff0d3f8a581.png">

Overview Page:
<img width="1560" alt="Kiali_Console_and_mtho11_on_freenode_IRC_Network_—__kiali__24_users____cnt__and_fish__Users_mithomps_projects_kiali-ui" src="https://user-images.githubusercontent.com/1312165/68434875-e5b38800-016e-11ea-81c5-f51abe338df3.png">

**Comment by lucasponce** [comment]
Added to backlog to: review that sizes are correct and also to add the "badge" to the title.

**Comment by aljesusg** [comment]
In fact when I remove the old patternfly library the sizes changes...so I think that we have some conflicts between pf3 and pf4...we'll address this soon

**Comment by lucasponce** [comment]
> In fact when I remove the old patternfly library the sizes changes...so I think that we have some conflicts between pf3 and pf4...we'll address this soon.

Please, update and link and issue for this to not miss it.

Thanks

**Comment by jshaughn** [comment]
This has been resolved in various PRs working to apply consistent CSS/l+f.
