### ISSUE TITLE
Validation references: better visualization

### ISSUE THREAD

**Issue by xeviknal** [kiali/kiali#2320]
At https://github.com/kiali/kiali-ui/pull/1522 we introduced the concept of "referenced objects" into Istio Object yaml page. The first iteration consisted in the following:

![Screen-recording-_14_](https://user-images.githubusercontent.com/613814/68133547-e1922b00-ff20-11e9-9664-13cd3c564cb9.gif)

1. If there are referenced objects, we list those objects on a box in the right side.
2. If there aren't referenced objects, the box is not present.

The goal of this issue is to revisit the implementation and adjust it to UX/UI criteria. I am mainly thinking in two aspects:
1. How the box is shown. Perhaps it should be expandable (show/hide actions). Should we show always the feature?
2. How the items within the box are represented. Should it be a list? How is represented every object? (e.g. `G namespace/servicename` is the format).

**Comment by lucasponce** [comment]
@kiali/ux-reviewers @xeviknal do we have more pending UX discussions around this ?
Is it clear for Eng to apply the UX suggestions ?

**Comment by xeviknal** [comment]
Brought to UX/UI meeting today. The output is:

1. Add a sidepanel as we have it in the topology graph.
2. Don't add the warning notification as a title. Keep it as standard title as in the B option (last Serena's comment).
3. Show the sidebar visible when there are reference present.
4. Hide the sidebar when there aren't references. And gray out the button (or perhaps set a copy into the sidebar saying 'no references found' for this config).

We can remove the 'waiting ux' label. When backlog added, ready to implement.
