### ISSUE TITLE
Adding validations to each namespace in Overview page

### ISSUE THREAD

**Issue by xeviknal** [kiali/kiali#2321]
https://github.com/kiali/kiali/issues/1556 issue is for adding a validation status into each namespace card in the Overview page.

What could be the best approach to add those validations?

![Screenshot of Kiali Console (84)](https://user-images.githubusercontent.com/613814/68868703-47886a80-06f8-11ea-9db1-81ff7d484feb.jpg)

We have three levels of information shown in the UI:
1. Summary: number of warnings/errors
![Screenshot of Kiali Console (85)](https://user-images.githubusercontent.com/613814/68868967-b665c380-06f8-11ea-9541-66c7bfc87e7f.jpg)

2. List of specific validations
![Screenshot of Kiali Console (86)](https://user-images.githubusercontent.com/613814/68868959-b36ad300-06f8-11ea-9c7a-c501e4b57506.jpg)

3. Validation within the YAML (located in a LOC).
![Screenshot of Kiali Console (87)](https://user-images.githubusercontent.com/613814/68869143-fcbb2280-06f8-11ea-95ab-328bcfab7558.jpg)

The idea it looks like more natural for the overview page is to show the errors/warnings count (no.1).

The goal of this issue is to define how the validations could be introduced in the overview page.
https://github.com/kiali/kiali-design/issues/57#issuecomment-447709719 the issue where the current overview page was discussed. Just in case it could be useful.

**Comment by lucasponce** [comment]
I understand that the pending action for this one is to place the validations icon at title level, instead to maintain the Istio Config: <Icon> as it's implemented.

Added to the backlog.
