### ISSUE TITLE
Should there be any Namespace Badging in Namespace Selector

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#2322]
In the theme of carrying the badges throughout the product. Should we be using any namespace badging in the Namespace Selector.

Here is what it currently looks like:

![Kiali_Console](https://user-images.githubusercontent.com/1312165/68902728-ef4c6b00-06ed-11ea-8c6a-ba3a2fb0d9bb.png)

**Comment by lucasponce** [comment]
This is valid.
I think it requires some feedback from @kiali/ux-reviewers.
It seems minor, so, don't hesitate to clarify it just with this issue.

**Comment by jshaughn** [comment]
Closing as there was no preference to add that badging in dropdown selections.

cc @beaumorley  @lwrigh
