### ISSUE TITLE
Graph Edge labels sometimes hard to read with line below showing through

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#2324]
Sometimes the graph edge labels can get difficult to read because the underlying edge line shows through the edge label font. Like this:

![Kiali_Console](https://user-images.githubusercontent.com/1312165/71220951-64780680-227f-11ea-8d25-4e16275eab37.png)

Should we put a background on the edge label to make it more readable? It could even have transparency so as to not make it too much.

**Comment by lucasponce** [comment]
It seems that the action is just to place the label with some offset from the edge.

**Comment by lwrigh** [comment]
We could increase the opacity of the label background so the line underneath of it is not as apparent.

**Comment by mtho11** [comment]
@lwrigh yes, that could work. It is even more evident when you have a complicated graph with lots of edge labels.

**Comment by jshaughn** [comment]
We've played with this before.  If we're going to make a change I suggest in a UX meeting that we do a live demo altering opacity levels and let UX pick a setting.  This is low priority, I will label as P1, we can do it when time permits.

**Comment by lwrigh** [comment]
That sounds good to me. Depending on the level of the design audit that we do we could take a closer look at details like these too.

**Comment by jshaughn** [comment]
Closing in favor of other issues involving UX, the graph, and scale.
