### ISSUE TITLE
Remove Kiali Application, Workload, Service Icons now that we have OCP badges for them

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#2325]
IMO: the Kiali UI is starting to feel a bit inconsistent with some places having Kiali icons for services, applications, workloads and other places using the OCP badges for these. Perhaps now is the time to remove those icons for good?

**Comment by lwrigh** [comment]
How much do we want to align with Openshift on the icons that are used?

**Comment by jshaughn** [comment]
@lwrigh , I'm not sure if you're asking Kiali or @serenamarie125.  For me it may be a nice to have but in general we're not looking to do much work that isn't tied to feature development.  Let us know if you have specific wants from UX.

**Comment by lwrigh** [comment]
Is there any more UX feedback that is needed for this issue? If not can the waiting label UX be removed?

**Comment by jshaughn** [comment]
@lwrigh I will close this broad issue and we can address any specific icon use in targeted issues.  The primary use of icon links is in the overview cards and we already have https://github.com/kiali/kiali/issues/2332.
