### ISSUE TITLE
Graph sidepanel colors for 4xx and 5xx too close, hard to distinguish

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#2326]
On the graph side panel the 4xx and 5xx colors are very difficult to distinguish from each other. I would think the 5xx would be red and the 4xx be orange or yellow.

Here is the image:
![Kiali_Console](https://user-images.githubusercontent.com/1312165/71858390-e352a900-309f-11ea-8772-a59504551b8f.png)

For tired eyes, this looks almost the same.

**Comment by jshaughn** [comment]
@mtho11 This is done, right?  If not re-open.
