### ISSUE TITLE
Consolidate Graph and Namespace selector to single line

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#2327]
Seems like we are wasting a lot of vertical screen real estate with the namespace selector on a separate line than the graph heading. Can we consolidate these two lines into one?

![Kiali_Console](https://user-images.githubusercontent.com/1312165/71858848-91ab1e00-30a1-11ea-926d-6c18e5b221d6.png)

**Comment by lucasponce** [comment]
Please, @kiali/ux-reviewers it seems we need feedback around this one.

**Comment by mtho11** [comment]
I think we can close this one now since the Graph title has been removed.
