### ISSUE TITLE
Expanded Overview cards use too much space

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#2328]
![Kiali_Console](https://user-images.githubusercontent.com/1312165/71860321-4431af80-30a7-11ea-863e-008a56d50a61.png)
Considering there could be many namespaces here, the traffic portion of the expanded overview card uses too much space. The traffic sparkline is intended to only show magnitude and trend (the magnitude can not really be inferred unless you hover over a point since there is no scale -- so really just trend).

Can we not just move the traffic portion under the previous column to conserve space? The traffic doesn't seem to warrant an entire section equal to the compact section.

![Kiali_Console](https://user-images.githubusercontent.com/1312165/71860518-27e24280-30a8-11ea-8bfe-5a5840f81d47.png)

**Comment by lucasponce** [comment]
I think this one is still being discussed.
I guess @kiali/ux-reviewers has the "action" here preparing a mockup for Eng ?

**Comment by lwrigh** [comment]
I can work on creating a mock up for this. I will add it to my to do list.

**Comment by lwrigh** [comment]
It would still be nice to see a screenshot with traffic in the current layout for comparison. First impression I prefer the narrower cards.

**Comment by mtho11** [comment]
@lwrigh maybe next week I can get back to that one

**Comment by lwrigh** [comment]
Is there any more UX feedback that is needed for this issue? If not can the waiting label UX be removed?

**Comment by jshaughn** [comment]
@lwrigh I don't think this was really resolved and I don't see any further mocks.  But I also don't want to pursue this specific issue.   Instead, I'd prefer that when the priority seem right we finally do a thorough review and overhaul of the Overview cards, such that UX has a chance to underastand and then mock the entire card, and page.  So, I'm closing this.  @lucasponce , if you disagree please re-open.
