### ISSUE TITLE
Graph Find/hide history

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#2329]
Adds a history dropdown for the graph find/hide commands so that previous commands can be executed without typing them in.

![hidefind-history2](https://user-images.githubusercontent.com/1312165/72764541-778f3680-3b9d-11ea-86a2-e5fcef2b0447.gif)

Questions:

1. History is currently limited to 5 entries. Should this be more?
2. We could provide a spacer and put some common predefined commands in the lower part of the menu?
3. Following the pattern for the find/hide clear (X) I don't show the find/hide until there actually are history items.

Issue:
https://github.com/kiali/kiali/issues/1464

PR:
https://github.com/kiali/kiali-ui/pull/1607

**Comment by lwrigh** [comment]
<img width="1440" alt="Screen Shot 2020-04-23 at 2 55 41 PM" src="https://user-images.githubusercontent.com/20227374/80138315-9f15e680-8572-11ea-98ca-34cea2d3ee8a.png">

Currently the topology view in Openshift adds an orange border around the found search term and decreases the opacity of the node(s) that do not contain the search term. Would we want to follow a similar pattern? How close do we want to follow Openshift with this behavior?

**Comment by mtho11** [comment]
@lwrigh why don't you create a separate issue specifically for what you are referring to in the above comment?

**Comment by jshaughn** [comment]
Personally, I like our highlighting, it's more bold and can be seen on denser topologies.  I'm not keen to make a change here.

**Comment by lwrigh** [comment]
Is there ay more UX feedback that is needed for this issue? If not can the waiting label UX be removed?

**Comment by jshaughn** [comment]
This issue has been dragging and I just haven't seen any user complaints in this area.  The standard autocomplete="true" will be sufficient until we get community requests or PF supplies an obvious component with the feature.  Closing this and the related issue and PR.
