### ISSUE TITLE
Is 'N/A' Health font size on Overview correct?

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#2331]
The Health status font in overview seems excessive in size compared to other fonts.

<img width="651" alt="Overview_N_A_Health_status_font_size_seems_excessive_·_Issue__2165_·_kiali_kiali" src="https://user-images.githubusercontent.com/1312165/73764142-4e3ae280-4727-11ea-93b6-4972178f3ad9.png">

Maybe this is fine, not sure. But when I look a the screen all I see is N/A

Perhaps one or two font sizes smaller?

Also are we planning to get rid of the icons and replace with text?

**Comment by israel-hdez** [comment]
@jshaughn You can assign to me and include in sprint if it's OK.

**Comment by jshaughn** [comment]
@israel-hdez See https://github.com/kiali/kiali/issues/2165, perhaps this issue should just be closed?  If not, assign yourself and fix away.

**Comment by israel-hdez** [comment]
@jshaughn I still see it. I'll self assign.

**Comment by israel-hdez** [comment]
This issue can be seen as "fixed" in a dev environment, but not fixed when container image is deployed. Behavior seems related to https://github.com/kiali/kiali/issues/2635. Looks like overview page is another instance of styling discrepancies.
