### ISSUE TITLE
Replace Overview Icon links with Text Links

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#2332]
In the overview screen, the Icon links at the bottom of the screen should be replaced with Text links so that they are more obvious as to what they are.

![Kiali_Console](https://user-images.githubusercontent.com/1312165/74966280-a29ebd00-53cb-11ea-8e97-f7ba6c30ff72.png)

**Comment by jshaughn** [comment]
cc @lwrigh I think this was mentioned in a UX meeting, did we decide there should be a change (action/kebob menu?) or was it OK as is?

**Comment by lwrigh** [comment]
@jshaughn I think the overview cards would be good candidates for doing a redesign pass of with the goal of making the links more obvious. 

cc: @beaumorley

**Comment by jshaughn** [comment]
@lwrigh Fine by me,  No real timetable here so perhaps think on it as you gain familiarity.

**Comment by lwrigh** [comment]
That sounds like a good plan to me! @jshaughn

**Comment by jshaughn** [comment]
This is done as part of #2896.
