### ISSUE TITLE
Question:   istio 0.8 support?

### ISSUE THREAD

**Issue by debianmaster** [kiali/kiali#242]
does kiali work with istio 0.8 as there are major breaking changes in 0.8 with its previous version.?

**Comment by jmazzitelli** [comment]
Once istio 0.8 is officially released (which is eminent), it will be supported soon after. We already have work done on supporting the new alpha3 API.

**Comment by jmazzitelli** [comment]
OK, I see the release finalized yesterday. I just wrote a JIRA to track the work we need to do to move to 0.8 - see here: https://issues.jboss.org/browse/KIALI-868

**Comment by debianmaster** [comment]
thanks
