### ISSUE TITLE
Remove ServiceRole and ServiceRoleBinding support

### ISSUE THREAD

**Issue by xeviknal** [kiali/kiali#2444]
Remove support to RBAC CRDs: ServiceRole, ServiceRoleBinding. They were deprecated in Istio 1.4. 

Per documentation, I would put this task on hold until Istio 1.6. To be consistent with upstream and help users with the migration to AuthorizationPolicy CRDs.

> Note: The v1alpha1 RBAC policy is deprecated by the v1beta1 Authorization policy. This page is kept for migration purpose and will be removed in Istio 1.6.

https://preliminary.istio.io/docs/reference/config/security/istio.rbac.v1alpha1/

**Comment by jmazzitelli** [comment]
Can be add more details to this issue?  What do you mean "remove RBAC CRDs"? We don't control what CRDs are installed in the Istio system.

**Comment by xeviknal** [comment]
yes, sorry, remove the support to browse, edit, delete and validate ServiceRole and  ServiceRoleBinding instances on kiali.
Not to remove the CRDs itself.

**Comment by xeviknal** [comment]
Closing this per https://github.com/kiali/kiali/issues/3341
