### ISSUE TITLE
Support other tracing tools

### ISSUE THREAD

**Issue by aljesusg** [kiali/kiali#2445]
## Is your feature request related to a problem? Please describe.

Istio support tracing tools like [zipkin](https://istio.io/docs/tasks/observability/distributed-tracing/zipkin/) and [LightStep](https://istio.io/docs/tasks/observability/distributed-tracing/lightstep/)
Istio information : https://istio.io/docs/tasks/observability/distributed-tracing/

Now Kiali has his own UI for traces so it would be nice if we support the other tools, there are users using Istio with zipkin or other tracing tools in the community.

## Describe the solution you'd like

Create an interface in Backend to transform the information for each provider for our UI.

**Comment by lucasponce** [comment]
I think it would be good if Kiali has support for other tracing backends.
Now, the UI has not a strong dependency with Jaeger, so it should be easier to add backend support for other options.

Also, I'd like to use this one as opportunity for other groups also to participate in Kiali, our role could be to adapt the backend to easy add new tracing support, but I'd ask for help for this task.

**Comment by pavolloffay** [comment]
Note that LightStep is a commercial tool, I am not sure if they have open query API. 

One thing that could help is to support OpenTelemetry query API. At the moment such API does not exist, however it would help to integrate tracing tools with other systems. Legacy systems could just transform their internal data model to OTEL and in addition to that we need to define a common set of query parameters (e.g. time, tags...). 

I can propose this in the OTEL community. To make something tangible would be for a longer run/

**Comment by lucasponce** [comment]
I think this is a duplicated (well, it mention LightStep) but original and similar effort is filled in

https://github.com/kiali/kiali/issues/1079

I'm going to close to keep one for same effort.
