### ISSUE TITLE
Istio 1.5-beta.3 pulls in Kiali 1.9.1 in demo profile

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#2449]
**General remarks**
The current Istio 1.5.beta.3 pulls an older version of Kiali 1.9.1 when installing with the demo profile.

![Kiali_Console_-_Firefox_Developer_Edition](https://user-images.githubusercontent.com/1312165/75365108-94401d80-5871-11ea-9159-d36f18af9246.png)

Also graphana and jaeger urls are not set (although I believe there is already an issue for this)

https://preliminary.istio.io/

Looks like Kiali version 1.13 should be getting pulled in via: https://github.com/istio/istio/pull/20866

**Comment by jmazzitelli** [comment]
this should be an istio issue - not a kiali issue - nothing to be done here in kiali repo. This needs to be fixed upstream in istio git repo somewhere:

https://github.com/istio/istio/issues

**Comment by mtho11** [comment]
@jmazzitelli oh yes, wrong issue repo
