### ISSUE TITLE
Bug in error route checking

### ISSUE THREAD

**Issue by pavolloffay** [kiali/kiali#245]
It seems that error checking does not work properly. See attached image. The route definition is from https://github.com/redhat-developer-demos/istio-tutorial/blob/master/istiofiles/route-rule-safari-recommendation-v2.yml.

istio 0.7.1
OC 3.9

![screenshot of kiali console](https://user-images.githubusercontent.com/5618424/40935365-2cc652da-6838-11e8-8b86-82769c5d9a94.jpg)

**Comment by pavolloffay** [comment]
The error message is that destination does not have a valid service

**Comment by lucasponce** [comment]
@pavolloffay thx for reporting this, let me check with the istio-tutorial set of examples.
It sounds some validation is missing.

**Comment by lucasponce** [comment]
https://issues.jboss.org/browse/KIALI-882

**Comment by lucasponce** [comment]
@pavolloffay this fix should solve the issue https://github.com/kiali/kiali/pull/246

**Comment by pavolloffay** [comment]
:+1: thanks @lucasponce

**Comment by pavolloffay** [comment]
Is the change available in Kiali docker image? If so can verify the patch.
