### ISSUE TITLE
Kiali dev install fails on Istio 1.5.0-beta.3

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#2455]
**General remarks**
Installing kiali via development install script:
`bash <(curl -L https://git.io/getLatestKialiOperator) --accessible-namespaces '**' `

Fails with Kiali staying in `ContainerCreating` status forever:
```
⋊> ~/istio-1.5.0-beta.3 k get pods -n istio-system                                                         
NAME                                    READY   STATUS              RESTARTS   AGE
grafana-556b649566-vltdn                1/1     Running             0          31m
istio-egressgateway-6844dd67b7-h4tl5    1/1     Running             0          31m
istio-ingressgateway-7948bdb87d-9wssq   1/1     Running             0          31m
istio-tracing-7cf5f46848-8zj6d          1/1     Running             0          31m
istiod-5c77bdfbb5-6l9lk                 1/1     Running             0          32m
kiali-87f989847-d5cg5                   0/1     ContainerCreating   0          27m
prometheus-58c74bcf7c-sghmg             2/2     Running             0          31m
```

**Versions used**
Kiali: 1.14
Istio: 1.5.0-beta.3
Minikube

**To Reproduce**
1. Install istio via demo profile 
`istioctl manifest apply --set profile=demo`
2. Reinstall the latest released version via dev install:
`bash <(curl -L https://git.io/getLatestKialiOperator) --accessible-namespaces '**' `

**Expected behavior**
Kiali should be in running status. It does this in Istio versions 1.4.x now.

**Comment by jmazzitelli** [comment]
what does the Events say in your OpenShift console for that pod?

**Comment by mtho11** [comment]
This is on minikube

**Comment by mtho11** [comment]
Two events:

1. MountVolume.SetUp failed for volume "kiali-cert" : secret "istio.kiali-service-account" not found
2. Unable to mount volumes for pod "kiali-87f989847-d5cg5_istio-system(b9688bbf-599e-11ea-91fb-0800271459a6)": timeout expired waiting for volumes to attach or mount for pod "istio-system"/"kiali-87f989847-d5cg5". list of unmounted volumes=[kiali-cert]. list of unattached volumes=[kiali-configuration kiali-cert kiali-secret kiali-service-account-token-j8vz6]

**Comment by mtho11** [comment]
Closing as duplicate.

**Comment by mtho11** [comment]
Just FYI: the workaround for now is:
`bash <(curl -L https://git.io/getLatestKialiOperator) --accessible-namespaces '**' -kiv latest -oiv latest ` which gets us the latest version of the operator that has the fix in it.

**Comment by vivekpd15** [comment]
@mtho11 This doesn't work. Facing the same with Istio 1.7 and your command.

**Comment by jshaughn** [comment]
@vivekpd15 that last comment was back in February, so pretty dated.    Please use the official docs on kiali.io and if you have an issue you can open a new issue.  Thanks.

**Comment by jmazzitelli** [comment]
Don't use the getLatestKialiOperator anymore. It might still work (probably still does) but not supported/recommended. Use the operator helm chart now. See: https://kiali.io/documentation/latest/installation-guide/

Note: if you are just installing kiali in a dev environment, Istio 1.7 now ships with the addons all-in-one yaml that you can use to install Kiali without an operator. It installs a basic Kiali Server installation for dev/demo purposes (has no configurable options like the Kiali helm chart does - but gets you up and running quickly with a basic install). See: https://kiali.io/documentation/latest/quick-start/ and https://preliminary.istio.io/latest/docs/ops/integrations/

**Comment by vivekpd15** [comment]
@jmazzitelli I used the latest helm chart as well. Getting the same issue with it. I am trying to deploy for a production environment. Have Kiali already running for Dev.

**Comment by jmazzitelli** [comment]
This original issue was from back in February. It had to do with the fact an older Kiali binary was being used with new YAML (or was it the reverse? I can't remember).

But the original issue was

```
MountVolume.SetUp failed for volume "kiali-cert" : secret "istio.kiali-service-account" not found
```

This had to do with the way Istio no longer generates certs. An older Kiali installation mechanism being used with a new Istio will fail because of this.

I suspect anyone still having this problem is due to mixing the wrong Kiali container image with Deployment yaml.

@vivekpd15 I would need to know (a) how you exactly tried to install (what helm chart? what exact command?) and (b) what are your k8s events occurring (i.e. what are the error messages). You should post your Kiali pod YAML and the Kiali ConfigMap YAML to see what the Kiali config is, also.

**Comment by vivekpd15** [comment]
@jmazzitelli Thanks. I fixed the issue. It was happening because of using an older version of Kiali.
