### ISSUE TITLE
TCP graph animation ignores tcp volumetry

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#2469]
The TCP traffic animation in graph seem constant regardless the throughput / volumetry. I would have imagined that it would impact how animation is displayed, like it is for HTTP traffic:

![Capture d’écran de 2020-03-02 17-26-22](https://user-images.githubusercontent.com/2153442/75696099-51d07380-5cab-11ea-840e-502c07ff1616.png)

In this picture, animation on both edge is similar (same amount of dots, same speed) although there's approx. 25x more traffic to the service entry.

I'm filing this as a bug because I thought it would work as I expected, but feel free to requalify as enhancement / reject if relevant.

@jshaughn @israel-hdez 

Kind-of part of Kafka epic: https://github.com/kiali/kiali/issues/2197

**Comment by jshaughn** [comment]
@josejulio Any comment on this one?

**Comment by jotak** [comment]
After some investigation, I'm requalifying this as an enhancement. The TCP rate is actually used for animations, but it is clamped with arbitrary values. My demo has a quite high volumetry and even low rates are still above the maximum.

See constant  `TCP_SETTINGS` in `TrafficRendered.ts`

I think if we want to continue to have Kiali looking pretty in real-world use cases we shouldn't base animation on arbitrary values, but perhaps have a moving "max" instead (that starts from the same constant as now, and adapts in time to loaded data?)

**Comment by jotak** [comment]
(actually, it's not that my values are above max, it's something different. Animation doesn't "grow" proportional to volumetry.

**Comment by jotak** [comment]
@jshaughn I had a closer look at this yesterday (as part of kafka epic), will open PR

**Comment by jshaughn** [comment]
@jotak great, thanks.  I think those constants were just set as a best guess early on and makes sense we need to make some changes.

**Comment by josejulio** [comment]
> @josejulio Any comment on this one?

Sorry, missed this notification.

> After some investigation, I'm requalifying this as an enhancement. The TCP rate is actually used for animations, but it is clamped with arbitrary values. My demo has a quite high volumetry and even low rates are still above the maximum.
> 
> See constant `TCP_SETTINGS` in `TrafficRendered.ts`

That's correct.

> 
> I think if we want to continue to have Kiali looking pretty in real-world use cases we shouldn't base animation on arbitrary values, but perhaps have a moving "max" instead (that starts from the same constant as now, and adapts in time to loaded data?)

I think we would like to tweak it to have better default values, making the max dynamic might be confusing (not sure), but is something that needs to be tested. Perhaps computing them from the overall graph values and documenting that the speed is relative to the current seen data. 
After all, the animation is fancy, but it would be good if people could benefit from it.

**Comment by jotak** [comment]
Hi @josejulio , thanks for your reply,

> > I think if we want to continue to have Kiali looking pretty in real-world use cases we shouldn't base animation on arbitrary values, but perhaps have a moving "max" instead (that starts from the same constant as now, and adapts in time to loaded data?)
> 
> I think we would like to tweak it to have better default values, making the max dynamic might be confusing (not sure), but is something that needs to be tested. Perhaps computing them from the overall graph values and documenting that the speed is relative to the current seen data.
> After all, the animation is fancy, but it would be good if people could benefit from it.

Moving max / amplitude is what I'm doing here: https://github.com/kiali/kiali-ui/pull/1694 . Basically, the amplitude stays unchanged until the max rate doubles. I think it's working fine, though I haven't tested in many scenarios.

**Comment by jshaughn** [comment]
I'm fine with the code changes although I'm not sure we quite have the settings we want.  For bookinfo with the traffic generator just sending 1 request per second we get a flood of tcp particles.  I would expect it to be more sparse. The video below  is the before/after.  It starts with master and then shows the pr.  What do you guys think?

![kiali#2469](https://user-images.githubusercontent.com/2104052/76889115-67bd6700-685b-11ea-8449-f1dcbaa4ec35.gif)
