### ISSUE TITLE
Percent in Slider in IstioWizard so small

### ISSUE THREAD

**Issue by aljesusg** [kiali/kiali#2475]
We need to increase this input

![slider](https://user-images.githubusercontent.com/3019213/75759348-ad474380-5d35-11ea-8e9f-50bea5009711.png)

**Comment by aljesusg** [comment]
I can address this in https://github.com/kiali/kiali-ui/pull/1673 if we progress here...

**Comment by hhovsepy** [comment]
Chrome specific issue.
