### ISSUE TITLE
Kiali CR removal gets sometimes stuck

### ISSUE THREAD

**Issue by FilipB** [kiali/kiali#2484]
**Describe the bug**
When removing a kiali CR the operation is sometimes stuck and reconciliation is running endlessly.

**Versions used**
Kiali: master 0d20c087b3da07ca9670fba0a830337089a2c274
Istio: 1.4.3
Kubernetes flavour and version: (e.g. OpenShift Origin 3.9)
OCP 4.4, 4.3

**To Reproduce**
1. install istio 1.4.3 via:
```
download-istio.sh -iv 1.4.3
install-istio-via-istioctl.sh -iee true -de true
```
2. install kiali via:
deploy-kiali-operator.sh
Operator and kiali was built from master 0d20c0 and images were passed to install script via OPERATOR_IMAGE_NAME and KIALI_IMAGE_NAME
3. Install bookinfo and add the namespace to the kiali cr accessible_namespaces
4. remove kiali cr
`oc delete kiali kiali -n kiali-operator`

**Actual behavior**
oc delete operation is sometimes stuck and reconciliation is running endlessly.
Kiali CR contains: deletionTimestamp: '2020-03-05T11:06:20Z'
Operator log:
```
{"level":"info","ts":1583405867.590792,"logger":"logging_event_handler","msg":"[playbook task]","name":"kiali","namespace":"kiali-operator","gvk":"kiali.io/v1alpha1, Kind=Kiali","event_type":"playbook_on_task_start","job":"1443635317331776148","EventData.Name":"default/kiali-deploy : Get namespace [bookinfo] that is to be labeled"}
{"level":"info","ts":1583405869.1712694,"logger":"logging_event_handler","msg":"[playbook task]","name":"kiali","namespace":"kiali-operator","gvk":"kiali.io/v1alpha1, Kind=Kiali","event_type":"playbook_on_task_start","job":"1443635317331776148","EventData.Name":"default/kiali-deploy : fail"}
```
When the operator pod is removed (new one is started automatically) the kiali CR is correclty removed and the stuck oc delete operation finishes.

Attaching
- kiali CR when it's stuck 
[kialiCR.txt](https://github.com/kiali/kiali/files/4292824/kialiCR.txt)
- operator log when it's stuck
[kiali-operator-896bc595c-ckfpb-operator.log](https://github.com/kiali/kiali/files/4292828/kiali-operator-896bc595c-ckfpb-operator.log)
- operator log from new operator pod
[kiali-operator-896bc595c-l55k4-operator.log](https://github.com/kiali/kiali/files/4292829/kiali-operator-896bc595c-l55k4-operator.log)

**Expected behavior**
Kiali CR is removed

**Comment by FilipB** [comment]
@jmazzitelli I'm not able to reproduce reliably. If you can provide any hint based on attached logs, it would be great.

**Comment by jmazzitelli** [comment]
I don't know why that would happen, but here is a way you can probably get it unstuck:

```
oc patch kiali kiali -n kiali-operator -p '{"metadata":{"finalizers": []}}' --type=merge ; true
```

**Comment by FilipB** [comment]
I can try that next time it happens. But considering that it's stuck in reconciliation, patching kiali cr might not take any effect. Deleting the operator pod is sufficient workaround for now.

**Comment by jmazzitelli** [comment]
> * operator log when it's stuck
>   [kiali-operator-896bc595c-ckfpb-operator.log](https://github.com/kiali/kiali/files/4292828/kiali-operator-896bc595c-ckfpb-operator.log)

This looks like it is in the middle of doing an install - the last message is just a message as its going through the list of namespaces and labeling them. That is just part of the install process.  It is as if the operator hung trying to do the labeling.

```
{"level":"info","ts":1583405872.724994,"logger":"logging_event_handler","msg":"[playbook task]","name":"kiali","namespace":"kiali-operator","gvk":"kiali.io/v1alpha1, Kind=Kiali","event_type":"playbook_on_task_start","job":"1443635317331776148","EventData.Name":"default/kiali-deploy : Saving label to namespace [default]"}
```

That happens here: https://github.com/kiali/kiali/blob/master/operator/roles/default/kiali-deploy/tasks/create-namespace-label.yml#L27-L30

Which is called in the middle of an install: https://github.com/kiali/kiali/blob/master/operator/roles/default/kiali-deploy/tasks/main.yml#L568-L578

So the master API appears hung trying to label a namespace for the operator during the middle of an install.

**Comment by jmazzitelli** [comment]
> I can try that next time it happens. But considering that it's stuck in reconciliation, patching kiali cr might not take any effect. Deleting the operator pod is sufficient workaround for now.

After looking at the logs (see my last comment), I think you are right that that suggestion might not help.

**Comment by FilipB** [comment]
> This looks like it is in the middle of doing an install - the last message is just a message as its going through the list of namespaces and labeling them. That is just part of the install process. It is as if the operator hung trying to do the labeling.

Probably not relevant but the "kiali-deploy : Saving label to namespace" msg is also logged when editing kiali cr accessible_namespaces. Last msg from attached log on which it hanged was logged when bookinfo namespace was added to the accessible_namespaces list.

> 
> So the master API appears hung trying to label a namespace for the operator during the middle of an install.

Cause of that might be some tmp issue in OCP cluster as I'm not able to reproduce it now.
Please keep this open for now. If I don't see this happening again I will close this issue after a few days.
Thank you

**Comment by FilipB** [comment]
One more idea to reproduce this which I want to try - delete kiali CR when the reconciliation is in progress.

**Comment by FilipB** [comment]
I'm not able to reproduce.

**Comment by FilipB** [comment]
Reopening as I hit the issue again. The issue seems to be caused by https://github.com/operator-framework/operator-sdk/issues/2112 which should be fixed in https://github.com/operator-framework/operator-sdk/releases/tag/v0.16.0

**Comment by jmazzitelli** [comment]
We should fix these:

https://github.com/kiali/kiali/blob/v1.15.0/operator/build/Dockerfile#L1

should be 0.16.0

and this:

https://github.com/kiali/kiali/blob/v1.15.0/make/Makefile.container.mk#L20

should be pulling the 0.16.0 version just to keep in sync

**Comment by FilipB** [comment]
@jmazzitelli Could you please fix this in master branch? We are seeing some strange issues so I would like to be sure it's not related to stuck kiali operator. I'm not sure about backporting, I have never noticed this problem in v1.12 branch which is used in SM 1.1

**Comment by jmazzitelli** [comment]
@FilipB I just created a draft PR: https://github.com/kiali/kiali/pull/2587
Let me do a bunch of testing before I merge it because I want to make sure this jump of 3 minor versions doesn't break anything.

**Comment by FilipB** [comment]
Thank you, I will be able to test the PR: #2587 tomorrow.

**Comment by jmazzitelli** [comment]
All molecule testing for PR #2587 is passing for me. It looks good on my end.
