### ISSUE TITLE
Graph: Namespace not aligned with Graph type

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#2486]
**General remarks**
Visually, the namespace dropdown should align with the graph type dropdown (and graph area).

![Kiali_Console_and_Firefox_Developer_Edition](https://user-images.githubusercontent.com/1312165/76031076-d6113980-5eeb-11ea-8e35-c09548697072.png)

**Comment by aljesusg** [comment]
Fixed in https://github.com/kiali/kiali-ui/pull/1673 by comment https://github.com/kiali/kiali-ui/pull/1673#pullrequestreview-369492950
