### ISSUE TITLE
Add a Message for Mobile devices that screen size is too small

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#2487]
**Is your feature request related to a problem? Please describe.**
This is an issue that we discussed today in UX call.

**Describe the solution you'd like**
When a device (or even when a screen size) becomes unusable because of the resolution. We should display a message instead of trying to show a mess of an application.

**Describe alternatives you've considered**
We can do a media query and then display a message.

**Additional context**
Questions are: 
1.  What devices or resolutions should be the minimum cutoff? (Patternfly or Openshift standards?)
2. What is the message that we should display?
3. Are there any a11y standards we should follow here?

**Comment by mtho11** [comment]
CC: @kiali/ux-reviewers

**Comment by lucasponce** [comment]
I think this is outdated.
No plan for specific mobile coverage.
