### ISSUE TITLE
kiali.io - slight changes to home to better connect kiali with istio 

### ISSUE THREAD

**Issue by xeviknal** [kiali/kiali#2493]
Kiali has got a website review recommending the following change:

> Very little traffic is finding the site through generic Service Mesh or Istio searches, from what we can see. It looks like most people arriving at the site are arriving while searching for project-specific terms (“kiali”, “kiali istio”, “kiali service mesh”, etc).
> 
> We recommend modifying the website to strengthen the link between Istio and Kiali - the two most important elements for this are the page title, and the first H1 in the age. We recommend something along the lines of “Kiali is a dashboard for Istio and other service mesh projects”.

The change is pretty small:
1. Change the home h1 to: "Istio dashboard for observability and configuration"
2. Change the home "about kiali" to include keywords like "istio, dashboard, console" and others. Just to increase visibility for istio searches.
3. Increase the presence of the word istio along the other web pages. For example, instead of only using "service mesh" use either "istio" alone or "istio service mesh".

**Comment by lucasponce** [comment]
I think this was addressed in a previous change from kiali.io
![image](https://user-images.githubusercontent.com/1662329/97710064-8b1be600-1abb-11eb-91e0-fe9da8f4e64c.png)
