### ISSUE TITLE
kiali.io - Split the feature pages into different pages

### ISSUE THREAD

**Issue by xeviknal** [kiali/kiali#2494]
Epic: #4118

The feature pages is too generic and kiali is losing some traffic regarding to traffic like "istio metrics", "istio configuration", "istio topology" and so on.
To split the features page will make kiali.io to have new pages with relevant content for those specific queries.

One proposal would be to have the following pages:
- kiali.io/features/istio-topology-graph
- kiali.io/features/istio-config-validation
- kiali.io/features/istio-config-wizards
- kiali.io/features/istio-metrics-tracing-correlation
- kiali.io/features/istio-multi-cluster

Again, this goes beyond the strategy done within istio.io or discuss.istio.io.
Anyway, this will help us in the long-term when other competitors appear. For SEO, time is pretty important.

**Comment by JStickler** [comment]
(Typo) wizards has one z

**Comment by lucasponce** [comment]
It can be part of https://github.com/kiali/kiali/issues/2494 effort

**Comment by lucasponce** [comment]
I'm going to take this, as other issues related kiali.io depend on how this one is implemented.

The scope of this would be to split the large "feature" page into minor subpages and update other sections that are not connected with the features section.

**Comment by abonas** [comment]
I don't have a lot of understanding in SEO so I can't say how it should be implemented, but it will be great that if users search for "istio UI" and "Istio visualization" they will reach Kiali as one of the first options. Currently it is suggesting istio.io (which does mention Kiali), and Kiali website is offered as 6th option, interestingly after Jaeger website and before Rancher website (which also mentions Kiali :))

**Comment by lucasponce** [comment]
To analyze and implement SEO capabilities are outside the scope of this issue or the capabilities of the team.
SEO consultants analyze the content and propose changes that may have a big impact in how algorithms work.

The scope of this issue is focused to re-organize the long "Features" page into a better set of smaller pages that can help to maintain them better.

That may help in some SEO scenarios (we don't know) but there is no expectation to have any change on that, meaning, that the results in Google are completely outside our scope and that's work for a different effort lead by other roles.

So, I'll update the title as it's confusing.

**Comment by xeviknal** [comment]
I think we should use the basic knowledge of SEO that we have in the team. Little changes that you already have implemented in the PR may have a big impact in the search engines. I think we don't have to do an exhaustive onpage effort though. Just minimal one, which are thinking good names for the urls of the new pages.
These changes might help what @abonas commented in the long term.
Actually, every change in every URL and word in a webpage affects the SEO.

However, it is pretty tough if not impossible to go before istio.io pages for searches with istio as the main object. However, we are building some relevance on the search engines wrt the relationship between istio and kiali. So we should be going not so far from istio.io entries.

So I guess that by splitting the features page and putting some common sense url and section titles we should be helping SEO and maintainability of the page.
