### ISSUE TITLE
Improve metrics dashboard when there's empty charts

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#2495]
Currently, in metrics dashboards (eg. Inbound / Outbound metrics, but could be runtimes metrics as well) when some charts are empty they still take a lot of space in the UI, despite they might not be relevant.

A typical example is when a workload emits TCP traffic only: user has to scroll down to pass http-related charts, before finally finding some data in the TCP-related charts:

![Capture d’écran de 2020-03-09 17-50-22](https://user-images.githubusercontent.com/2153442/76238565-51e2ed00-6230-11ea-99ed-618497a22d4b.png)
*First view of the page*

![Capture d’écran de 2020-03-09 17-50-25](https://user-images.githubusercontent.com/2153442/76238575-57403780-6230-11ea-8ca2-45ae69f91913.png)
*After scrolled down*

We don't necessarily want to completely hide the charts with no data, because fact that there no data for it is an information per se (means => this workload doesn't emit metrics of that kind).

However we might want to improve the UX to avoid too much scrolling, and to have good first impression of seeing data when the screen first comes in.

One option that comes to mind is to reorganize charts order to bring non-empty first. However, I don't like that too much because chart ordering might follow some "editorial" purpose which could then be broken (and that's more especially true in runtimes dashboards)

Another option is simply to reduce the size of empty blocks. This is what I've tried here:

![Capture d’écran de 2020-03-09 17-53-57](https://user-images.githubusercontent.com/2153442/76238849-c0c04600-6230-11ea-99d0-93a41337f999.png)
*First view immediately shows data (just some small text overlap that needs a fix here)*

I think that's a correct solution, but I'd like to get @kiali/ux-reviewers thoughts before...

Part of https://github.com/kiali/kiali/issues/2197

**Comment by lwrigh** [comment]
I would suggest adding an empty state to this since the gray box and info icon can make the graph look like it's broken. Here are some quick mock ups of using the PatternFly 4 empty state: 
![All empty state- no cards](https://user-images.githubusercontent.com/20227374/76244081-c48fa080-620f-11ea-862e-bfc9564d1841.png)
![Smaller empty state- no cards](https://user-images.githubusercontent.com/20227374/76244083-c5c0cd80-620f-11ea-891c-63ba4179b25c.png)

**Comment by jotak** [comment]
thanks @lwrigh 
This is actually already an "empty state" component (just the icon is different from what your mockup shows) but my point is precisely to make it smaller, to avoid giving the impression that *everything* is empty whereas there's some data when you scroll down.

**Comment by lwrigh** [comment]
@jotak That's correct, I definitely agree with making it smaller so users know that some of the graphs are filled in.
