### ISSUE TITLE
Show metrics to service entries in summary panel

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#2497]
Currently, we don't show any metrics to Service Entries in summary panel:

![Capture d’écran de 2020-03-10 17-26-59](https://user-images.githubusercontent.com/2153442/76335383-bc5d6100-62f4-11ea-9706-d2b21d580be0.png)

However, these metrics exist and we should be able to query them, with a `destination_service` being the service entry host(s). Perhaps it needs to forge specific prom queries for that, or add more metadata information to the service entry node. But it's probably doable.

Part of: https://github.com/kiali/kiali/issues/2197

**Comment by jshaughn** [comment]
@jotak I think the reason we don't show sparklines for service entry nodes is because service entries are aggregates.   I'd have to look more carefully at it but iirc it's not simple to do in a single query and that's why it's not currently presented.
