### ISSUE TITLE
Graph Edge Hosts Tab - Hosts Info Wraps

### ISSUE THREAD

**Issue by mattmahoneyrh** [kiali/kiali#2499]
The Graph Edge Hosts Tab, Hosts info wraps making it more difficult to read. Find way to compress the Hosts info so that it is contained on one line.

Kiali v1.15.0 example:

![Selection_136](https://user-images.githubusercontent.com/7262987/76342711-62996e80-62d5-11ea-9d80-5513c1b7fd92.jpg)

Kiali v1.12.3 example:

![Selection_137](https://user-images.githubusercontent.com/7262987/76342738-70e78a80-62d5-11ea-80dd-ae12ae070d4f.jpg)

**Comment by jshaughn** [comment]
+1, this should likely use ... instead of wrap, with a hover of the full host name.
