### ISSUE TITLE
kiali.io/readme - Add vulnerabilities protocol to contribute/readme page

### ISSUE THREAD

**Issue by xeviknal** [kiali/kiali#2502]
There was a user willing to privately submit a vulnerability for our project:
https://github.com/kiali/kiali/issues/2473

He asked where to report it. @jmazzitelli responded with the following URL:
https://access.redhat.com/security/team/contact

I think it should be a good idea to add a new section into the contributors page in kiali.io: Report a vulnerability

**Comment by jshaughn** [comment]
I think we can also add something on the github project.

**Comment by xeviknal** [comment]
I guess we can close this one per https://github.com/kiali/kiali.io/pull/219 and https://github.com/kiali/kiali/pull/2606
