### ISSUE TITLE
Security icon missing on Service Graph

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#2513]
Kiali UI
    1.15.0 (916d07b8015085dc23e8ec01f8550e43bb5c7431)
Kiali Server
    v1.15.0-SNAPSHOT (7232e728f24c2bdd20a1052b731cce813ca1d98e)
Istio
    1.5.0 

1. Enable mTLS namespace wide for bookinfo.
2. Install bookinfo with traffic generator.
3. Go to Service Graph.
4. Check 'Security' flag to be shown.

mTLS icon should be on graph, but squares displayed.
![Screenshot from 2020-03-12 15-16-17](https://user-images.githubusercontent.com/604313/76531216-2a309680-6475-11ea-8b5f-c6138d06a77a.png)

**Comment by jshaughn** [comment]
@lucasponce I set this to blocker because I think we should hold the 1.15 release until it's fixed.  It's a pretty severe regression as none of the edge or node label badging is working in the graph. @israel-hdez put a hold on the release generation.

It seems it went away with the CSS cleanup PR https://github.com/kiali/kiali-ui/pull/1673.  So, I'm re-assigning to @aljesusg to take a look.  I tried to fix it but failed, my PR for reference is https://github.com/kiali/kiali-ui/pull/1691.

Not sure how we didn't see this, but at least we can fix it before we release, so not terrible,

**Comment by lucasponce** [comment]
@jshaughn +1

**Comment by aljesusg** [comment]
Updated: I am 200% working on this and I am talking with patternfly team about.

The point here is that in PF4 they removed the "unicode" way to add the icons.

PF4: React-Icons get the SVGs (https://github.com/patternfly/patternfly-react/tree/master/packages/react-icons) You can check that the render is something like

```html
<svg fill="currentColor" height="1em" width="1em" viewBox="0 0 448 512" aria-hidden="true" role="img" style="vertical-align: -0.125em;"><path d="M400 224h-24v-72C376 68.2 307.8 0 224 0S72 68.2 72 152v72H48c-26.5 0-48 21.5-48 48v192c0 26.5 21.5 48 48 48h352c26.5 0 48-21.5 48-48V272c0-26.5-21.5-48-48-48zm-104 0H152v-72c0-39.7 32.3-72 72-72s72 32.3 72 72v72z" transform=""></path></svg>
```

In PF3 we loaded => https://raw.githubusercontent.com/patternfly/patternfly/master/src/fonts/PatternFlyIcons-webfont.svg

Where load all the icons with unicode like

```html
<glyph unicode="&#xe923;" glyph-name="locked" data-tags="pficon-locked" d="M952.32 512.951h-112.128v108.471c0 177.152-150.016 329.435-327.168 329.435s-329.435-152.283-329.435-329.435v-108.471h-112.128c-38.107 0-69.193-31.086-69.193-69.193v-444.27c0-38.107 31.086-73.728 69.193-71.461h880.859c38.107-2.267 69.193 33.353 69.193 71.461v444.27c0 38.107-31.086 69.193-69.193 69.193zM328.777 621.422c0.219 101.595 82.651 184.027 184.247 184.247 101.595 0 181.979-82.871 181.979-184.247v-108.471h-366.226v108.471zM904.558 72.923h-541.769c-25.088 0-34.231 11.41-34.231 36.498s9.143 36.498 34.231 36.498h541.769c25.088 0 45.641-11.41 45.641-36.498s-20.553-36.498-45.641-36.498v-0.073zM904.558 292.059h-541.769c-25.088 0-34.231 11.41-34.231 36.498s9.143 36.498 34.231 36.498h541.769c25.088 0 45.641-11.41 45.641-36.498s-20.553-36.498-45.641-36.498v-0.073z" />
```

This is render something like 
```html
<span class="pficon pficon-container-node">
::before
</span>
```
where in before we can see the contetn which reference to the asciicode in the css inspector of the browser


PF3 Icons https://www.patternfly.org/v3/styles/icons/index.html
PF4 Icons https://patternfly-react.surge.sh/icons/

**Comment by jshaughn** [comment]
@hhovsepy removing the backport label as this issue does not affect the 1.12 or any other release line.  It is being treated as a blocker for 1.15 (The sprint 36 release).

**Comment by hhovsepy** [comment]
@jshaughn there is a blocker OSSM issue logged for 1.12.3 https://issues.redhat.com/browse/OSSM-166

**Comment by aljesusg** [comment]
mmm weird in that version We had patternfly library.

I tested the actual master and sometimes the icon appear....and @xeviknal  had the same behaviour 

See GIF

![ezgif-6-635c0dbed76c](https://user-images.githubusercontent.com/3019213/76770848-cffa4300-679e-11ea-8ebb-5acca9dfeac8.gif)


This is weird and maybe is not related with PF4, I need to investigate about. Is there any change in cytoscape rendering from this version?

**Comment by jshaughn** [comment]
@hhovsepy @aljesusg That is a separate problem that I think is a cytoscape rendering issue.  I'm not sure it should be a blocker but I'll pursue that separately.

This current issue is a complete loss of webfont icon rendering and it should not be backported.

**Comment by aljesusg** [comment]
> @hhovsepy @aljesusg That is a separate problem that I think is a cytoscape rendering issue. I'm not sure it should be a blocker but I'll pursue that separately.
> 
> This current issue is a complete loss of webfont icon rendering and it should not be backported.

pfff this is so weird

**Comment by xeviknal** [comment]
It remembers me this issue we had in the past: [KIALI-2817](https://issues.redhat.com/browse/KIALI-2817)

And I don't know it if it is related to this change: 
https://github.com/kiali/kiali-ui/commit/2139f0f0555dd54be93770cdd27a9f03956f77e7#diff-38682f47b0cf12c516bc3714fc45d0fd

However, recovering those two lines don't sadly make the icons in the label working back.

**Comment by jshaughn** [comment]
@hhovsepy @xeviknal @aljesusg @mattmahoneyrh Although the issue in v1.12 branch (SM 1.1) isn't as severe as we had in master it seems similar.  Because we have PF4 already introduced in v1.12 I
tried backporting the fix.  With a few merge fixes I think it is OK.  It may solve the downstream issue although I can't always reproduce it, so I'll let QE give it a try.  So, I'm reversing what I said before and I'll re-label for backport.

**Comment by xeviknal** [comment]
@jshaughn I've tested that in my local machine and it works. Thanks!
