### ISSUE TITLE
Test Kiali with best-practice prometheus guide

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#2518]
Istio team released a guide to setup prometheus for production-scale monitoring, related to telemetry v2: https://istio.io/docs/ops/best-practices/observability/#using-prometheus-for-production-scale-monitoring

We should check if this setup affects Kiali and eventually take actions.

---
Related:

- [x] Allow to display several metrics per chart https://github.com/kiali/kiali/issues/1778

**Comment by jotak** [comment]
Repo to setup prometheus following this guide: https://github.com/jotak/istio-federated-prometheus

**Comment by jotak** [comment]
See also: https://discuss.istio.io/t/feedback-requested-production-monitoring-with-prometheus/5685

**Comment by lucasponce** [comment]
Also @jmazzitelli could be looking at it, so just to note it to coordinate but this is a good effort.
I've added to the sprint to raise priority.

**Comment by jotak** [comment]
I'm leaving here some findings, that perhaps should be put in a blog post.

To quickly summarize this best-practice guide, the problem is that with telemetry v2 there's an explosion of metrics cardinality, and the solution is to shorten istio's prometheus metrics retention a lot (a couple of hours, even less) and have a second prometheus instance that grabs pre-aggregated metrics from the former (hence, lower cardinality - less resource consumption) with a higher retention.

Two scenarios are given:

- Scenario 1: These pre-aggregated metrics are forged in a way that preserves compatibility with consumers, such as Kiali or existing Grafana dashboards. This scenario has a drawback / bug, as I'll explain below.

- Scenario 2: These pre-aggregated metrics are forged in a way that breaks compatibility with consumers.

The bug of Scenario 1 is, [as I explained here](https://discuss.istio.io/t/feedback-requested-production-monitoring-with-prometheus/5685), there will be some corrupted telemetry sometimes. [1].

For Kiali, I can see 3 options, none of them being perfect, so users will have to do some tradeoff anyway.

- Option 1: Keep Kiali pointing to Istio's Prometheus. Drawback: short retention.
- Option 2: Configure Kiali to use the 2nd Prometheus with Scenario 1. Drawback: corrupted telemetry sometimes and Kiali being less reactive to show data (because has two wait two prometheus scraper runs instead of only one).
- Option 3: Configure Kiali to use the 2nd Prometheus with Scenario 2. Drawback (quite serious): it's just not going to work because Kiali won't find the metrics it needs. Of course we could do some work to make Kiali more flexible to fetch new metrics, but that's not a short term solution.

I think it would be fair to consider both options 1 and 2, and write some blog post to guide users about that. They could even deploy 2 instances of Kiali, one using istio's prometheus and the second using the other one, more suitable for troubleshooting scenarios.

[1] About that corrupted telemetry, while writing this, I suspect this is actually the exact same kind of "corruption" that mixer was sometimes showing when pods are restarted (poke @jshaughn ), even if now the context is different. Mixer was summing metrics before we apply rate() on it. Same issue, so not an actual regression in that regard.

**Comment by jotak** [comment]
For information, what I have on this repo [1] plus this k-charted PR [2] allows to get the following result:

![Capture d’écran de 2020-04-10 16-00-58](https://user-images.githubusercontent.com/2153442/78996402-cfa65b00-7b44-11ea-8cf2-613ef6bb6425.png)

This is a dashboard dedicated to longer-term metrics, that otherwise Kiali would display with the best-practice / production-scale prometheus setup (scenario 2 described above).

So, in this context, Kiali would still work mainly with short-retention prometheus data (graph, standard metrics, etc.) and this dashboard allows to see data with longer retention.

[1] Repo for scenario setup: https://github.com/jotak/istio-federated-prometheus
[2] PR: https://github.com/kiali/k-charted/pull/87

**Comment by jshaughn** [comment]
@jotak I'm confused by this Epic.  It's open and there is an open epic subtask, but you moved it to Done, was that on purpose?

**Comment by jotak** [comment]
@jshaughn I didn't consider it as an epic, to me it was more about testing and writing blog post ... , but yes, I created some related tasks (perhaps improperly mentioned as subtasks). The one that is done was required for the scenario ... the one not done yet was more like a nice to have, not required. I still want to do it, but it doesn't prevent the whole thing to work fine.

Anyway, we can reopen if you want.

**Comment by jshaughn** [comment]
@jotak Sorry, this was never labeled as an Epic.  But what I find confusing is that this is both Open and Done.  That's a little weird from a book keeping perspective.  I think to keep it open we should likely label it as an Epic and move it to sprint 40, or just close it and move on.

**Comment by amenaafreen** [comment]
Hello,
When I try to use https://github.com/jotak/istio-federated-prometheus to deploy federated prometheus, what I am seeing is there are two istio-prometheus pods running and one master
```
kubectl get pods -n istio-system
NAME                                    READY   STATUS    RESTARTS   AGE
grafana-5dc4b4676c-xddxb                1/1     Running   0          18h
istio-egressgateway-6d98c888ff-tbz7g    1/1     Running   0          18h
istio-ingressgateway-6bff4c6896-7gn7q   1/1     Running   0          18h
istio-tracing-8584b4d7f9-nvmbl          1/1     Running   0          18h
istiod-587bbdc654-jv2fj                 1/1     Running   0          18h
kiali-6f457f5964-dn6kl                  1/1     Running   0          18h
master-prometheus-56c4d55fd4-gwnxc      1/1     Running   0          17h
prometheus-5db67458fb-d667n             2/2     Running   0          17h
prometheus-77bcfc6f6d-hkbs2             1/2     Running   0          17h
```
Could anyone please let me know why is it so??
