### ISSUE TITLE
First (left) section title in entity details page needs some refinement

### ISSUE THREAD

**Issue by abonas** [kiali/kiali#2521]
The section naming is a bit inconsistent, there are 3 sections now:
Entity type (like Application) overview
Graph overview
Health overview

All 3 are regarding the same entity and it should be clear what entity is that, the first one might need renaming, because second and third naming describes what is in the section (graph/health) but the first one's naming is very generic.
Maybe "properties" or "general info" or even something around "structure/components"?

![graphoverview](https://user-images.githubusercontent.com/6277245/76765914-dc32d000-679f-11ea-9795-25c303a71dfd.png)

**Comment by lucasponce** [comment]
This is also addressed on https://github.com/kiali/kiali/issues/2616
