### ISSUE TITLE
Edge labels on congested screens get difficult to read

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#2529]
**Is your feature request related to a problem? Please describe.**
When there are lots of interconnecting edges the edge labels get difficult to read.

![Kiali_Console](https://user-images.githubusercontent.com/1312165/76920597-17f59480-6889-11ea-99ba-aeb9dbb34cb4.png)

This is a very small graph and it can be seen.
Note: even the 'small' app is selected but doesn't seem to help.

![Kiali_Console](https://user-images.githubusercontent.com/1312165/76920556-001e1080-6889-11ea-9f19-9c71c1c2dd65.png)

**Describe the solution you'd like**
I don't know if UxD has any solutions...

**Comment by mtho11** [comment]
This is also exacerbated by the fact that you can't move anything around.

**Comment by jshaughn** [comment]
I agree this can be an issue but it somewhat feels like the nature of a graph.  We do offer the ability to turn off labels.  We have hover that emphasizes labeling on the hovered edge, and we have the side panel when it is selected.  We also have node drill-down to focus on a particular neighborhood.  I invite UX to think on this but for now I will leave this as a future.

**Comment by mtho11** [comment]
@jshaughn I just added this as maybe UxD has ideas that we have not thought about yet.

**Comment by lwrigh** [comment]
In this case it might be worth adding a white background card behind each of the numeral values. A card with a 90% opacity background might work too. It might also help to put boundary restrictions around the number values so few things overlap over the values. I'm not entirely if that would be feasible though.

**Comment by lucasponce** [comment]
I think this issue is now outdated.
User can move the elements of the graph and on dense scenarios opacity seems to work.
![image](https://user-images.githubusercontent.com/1662329/107959826-2a4de600-6fa4-11eb-805d-c79de3eaf950.png)

So, I don't think a change would help in all cases as a generic solution, but allowing to re-organize the elements for visualization seems correct in the current Kiali v1.30.
