### ISSUE TITLE
How to install Kiali backend in two different kubernetes cluster with istio and integrate with one kiali-ui 

### ISSUE THREAD

**Issue by Sas002** [kiali/kiali#2539]
**Is your feature request related to a problem? Please describe.**
Need to know if it is possible 
**Describe the solution you'd like**
I have two kubernetes cluster and istio control plane is installed separately due to some high availability design. Now while installing Kiali , I have to install Kiali on both kubernetes clusters . I want to know if it is possible to install kiali-backend on both kubernetes clusters and install kiali-ui on just one cluster or  may be outside two clusters. Goal is to have one UI interface to view two clusters services rather login to multiple kiali UI separately. 
**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. If it is about a new design, please attach a drawing of a potential solution.
For backend changes also describe how one could test the new feature and how it impacts display on the UI.

**Comment by israel-hdez** [comment]
@Sas002 It's not possible at the moment. Although front-end and back-end are developed as two separated components, they are bundled together in a release and the code assumes this.

**Comment by aljesusg** [comment]
Federation is comming :)

**Comment by israel-hdez** [comment]
@Sas002 If you think that you got all the information you need, please consider closing this issue.
