### ISSUE TITLE
Missing ServiceEntries in Graph

### ISSUE THREAD

**Issue by drcrees** [kiali/kiali#2548]
**Describe the bug**
After upgrading from Kiali v1.13.0 to v1.15.0 we noticed that traffic to external services is no longer displaying in graphs.

We are using Istio's `REGISTRY_ONLY` external traffic policy, with defined service entries.  

Could this no longer be the default behavior, and we're just missing a configuration setting?

**Versions used**
Kiali: v1.15.0
Istio: 1.3.5 & 1.4.6
Kubernetes flavour and version: (e.g. OpenShift Origin 3.9)
GCP 1.14.10-gke.17 

**To Reproduce**
1. Generate traffic to a registered external service from application in the mesh
2. Navigate to the graph in Kiali
3. See that the traffic to the external service does not show 

**Expected behavior**
After generating traffic to an external service from an application in the mesh, I would expect to see that traffic represented as a service entry in the graph like it does in v1.13.0.

**Comment by jshaughn** [comment]
That is strange considering there has not been a recent change to service entry detection code.  The only change has been kiali version from 1.13 to 1.15?  And now the the edges to service entry nodes (and the nodes) are not displayed?

**Comment by drcrees** [comment]
@jshaughn correct.  We have verified that the traffic is also making it to Prometheus.

The only other thing we did was disable `threescale`
```
... 

extensions:
  threescale:
    enabled: false
```

**Comment by jshaughn** [comment]
@drcrees I have one thought as to what may be happening, could you share one or two prometheus time-series that previously showed as service entry traffic?

**Comment by drcrees** [comment]
```
istio_tcp_sent_bytes_total{connection_security_policy="unknown",destination_app="unknown",destination_principal="unknown",destination_service="ldap.example.com",destination_service_name="ldap.example.com",destination_service_namespace="test-app",destination_version="unknown",destination_workload="unknown",destination_workload_namespace="unknown",instance="172.18.234.175:42422",job="istio-mesh",reporter="source",response_flags="-",source_app="test-app",source_principal="unknown",source_version="unknown",source_workload="test-app",source_workload_namespace="test-app"}
```

```
istio_tcp_sent_bytes_total{connection_security_policy="unknown",destination_app="unknown",destination_principal="unknown",destination_service="auth.example.com",destination_service_name="auth.example.com",destination_service_namespace="test-app",destination_version="unknown",destination_workload="unknown",destination_workload_namespace="unknown",instance="172.18.234.175:42422",job="istio-mesh",reporter="source",response_flags="-",source_app="test-app",source_principal="unknown",source_version="unknown",source_workload="test-app",source_workload_namespace="test-app"}
```

@jshaughn Is there any metric that you're looking for in particular?  These destinations show up in the graph, among others.

**Comment by koalaty-code** [comment]
@jshaughn It may also be worth mentioning that there is a huge performance improvement when loading the graph in `v1.15.0` compared to `v1.13.0`. Could this indicate that Kiali is no longer collecting the same metrics from Prometheus before rendering the Graph?

**Comment by jshaughn** [comment]
@koalaty-code We should be collecting the same metrics but we may not know exactly until we resolve this issue.  I expect the real benefit here is some awesome caching work we've done (especially @lucasponce) under the covers when querying the k8s API.  And there have been some other graph-specific perf enhancements as well.  Excellent news (assuming it's not bug-related)!

**Comment by jshaughn** [comment]
@drcrees @koalaty-code So, in the missing telemetry can you confirm that:

` destination_service_name=destination_service`

Assuming you say yes I think what is happening is due to code changes we put in to help visualize headless services.  I'll look into a way to resolve the regression while still maintaining the new feature.

**Comment by drcrees** [comment]
Yes, I just tested this out again with Kiali 1.15.0, the missing telemetry shows in Prometheus (`destination_service_name=destination_service`) for service entries.

I am not seeing any "bad telemetry" where `destination_service_name` or `destination_service` are IP addresses.  Granted I'm only looking at `istio_tcp_sent_bytes_total`, are there any other metrics that Kiali uses to build the Graph for outbound traffic?

**Comment by jshaughn** [comment]
@drcrees Thanks for confirming.  This is definitely a regression due to the work in https://github.com/kiali/kiali/pull/2511.   I'll try and get a fix out ASAP, until then using Kiali < 1.15 is the only workaround.   I definitely see bad telemetry in istio_requests_total using istio 1.5 (and telemetry V2) and so we have to play a balancing game between showing what we need to show and hiding stuff that will degrade the graph.  Thanks for your help identifying the issue and hopefully validating the fix...

**Comment by drcrees** [comment]
@jshaughn no problem, we will definitely be able to validate the fix 👍
Thank you for your help!

**Comment by jshaughn** [comment]
@drcrees FYI: I have generated https://github.com/kiali/kiali/pull/2571 for this issue if you want to track progress.

**Comment by jshaughn** [comment]
@drcrees The PR was merged.  If we generated a snapshot release would you be able to test it?  If not we should be generating a 1.16 release on Friday.

**Comment by jshaughn** [comment]
@drcrees Kiali 1.16.0 has been released, can you check to see if it solves your issue?  Thanks, -Jay

**Comment by nachomillangarcia** [comment]
@jshaughn I had the exact same problem and it's solved in 1.16.0. I can visualize traffic to service entries again.

Thanks!

**Comment by jshaughn** [comment]
@nachomillangarcia Excellent news, thanks for letting us know!

**Comment by koalaty-code** [comment]
@jshaughn I can also confirm the issue has been resolved in `1.16.0`.

Unrelated question, I had to add an environment variable for `LOGIN_TOKEN_SIGNING_KEY` to pass some [validation logic](https://github.com/kiali/kiali/blob/93f5cd0b6698e8fe8772afb8f35816f6c086aef1/config/token.go#L41-L44) in place. I am using the `anonymous` authentication strategy with Kiali and this new environment variable doesn't seem applicable for that strategy. Is this the intended behavior, or should I open a new issue to disable that validation logic when using an anonymous auth strategy?

**Comment by jmazzitelli** [comment]
> Unrelated question, I had to add an environment variable for `LOGIN_TOKEN_SIGNING_KEY` to pass some [validation logic](https://github.com/kiali/kiali/blob/93f5cd0b6698e8fe8772afb8f35816f6c086aef1/config/token.go#L41-L44) in place

How did you install Kiali? If you used istioctl from Istio 1.4.6 or earlier or from Istio 1.5.0, then this issue will happen (even if you overrode the kiali tag to be v1.16.0). Using istioctl from 1.4.7 or 1.5.1 this issue won't happen.

Another way around that is to set "login_token.signing_key" to some string value you assign in your Kiali ConfigMap. This way you don't have to mess with the Deployment yaml.

This is to ensure the JWT token is encrypted with a properly secured key. I believe we still want this even in "anonymous" mode. I thought JWT tokens are still sent back and forth even in anonymous mode - is that correct @israel-hdez ?

**Comment by israel-hdez** [comment]
@jmazzitelli Some long time ago, it was true that JWT tokens were being used even in anonymous mode. Nowdays, Kiali just let the request go in. See: https://github.com/kiali/kiali/blob/cdaa4b0ccbe9564e8494bab5c2f1616f700b61a1/handlers/authentication.go#L487-L489

@koalaty-code I think you should open a PR to disable that validation. The fix looks quite easy.
