### ISSUE TITLE
Graph Error when enabling Response time edges

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#2549]
**Describe the bug**
When selecting response time for the edges on Graph

<img width="1650" alt="Kiali_Console" src="https://user-images.githubusercontent.com/1312165/77369939-f67b2980-6d1c-11ea-87fb-406bafc0d7db.png">

![response-time-bug](https://user-images.githubusercontent.com/1312165/77370035-34784d80-6d1d-11ea-92c5-b3aba3678cf2.gif)

Kiali master branch

**To Reproduce**
1. Change graph edge to show Response time

**Expected behavior**
No error should occur

**Comment by mtho11** [comment]
@mattmahoneyrh  BTW I was using the Fault injection bookinfo data: https://istio.io/docs/tasks/traffic-management/fault-injection/

**Comment by jshaughn** [comment]
@mtho11 I have seen this occur a couple of times recently.  I'm not sure yet the issue.  Were you on Istio 1.5?  I have only seen it using 1.5, I think.

**Comment by mtho11** [comment]
@jshaughn yes I was on Istio 1.5.0
