### ISSUE TITLE
Filters for different kind of labels are mixed up

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#2559]
Following comment here: https://github.com/kiali/kiali/issues/1522#issuecomment-603713540

Filters defined for labels on different list pages + overview are mixed up. For instance, if we filter on "version=v1" in workloads list, the same filter is preserved in apps list page, service list page, and overview. When switching from a page to another, these filters are kept. It may or may not make sense depending on the case. Going from a non-empty workloads list with "version=v1" filter, to overview page would inevitably show an empty page that may appear like a bug.

- For workloads, we're using labels on templates or pods if I'm correct.
- For services, labels on services obviously
- For apps, labels on workloads + services
- For overview, labels on namespaces

There are several options. We could decorelate them all, or keep correlating just some of them. This is very subjective & dependent on use cases.

My opinion:
- It still makes sense to correlate Workloads and Apps labels because I believe they're the most overlapping ones.
- It doesn't make sense at all to correlate them with namespace labels (overview page), because there's very little chances that they overlap.
- And for services, it's less clear, I'm tempted to think we could keep the correlation because some typical labels can be set on services too ("app", "part-of", etc.). Of course it doesn't work with "version" label.

**Comment by aljesusg** [comment]
Related with https://github.com/kiali/kiali/issues/1269

**Comment by jotak** [comment]
PS: as said in the initial comment here https://github.com/kiali/kiali-ui/pull/1709#pullrequestreview-380954076 , I imagine the solution is as easy as having a different filter type for namespace filters, something like `filterType: FilterTypes.nsLabel`
