### ISSUE TITLE
Combining the edge labels dropdown with the display dropdown 

### ISSUE THREAD

**Issue by lwrigh** [kiali/kiali#2573]
Epic: https://github.com/kiali/kiali/issues/2314

**Current tool bar:** 
![Screen Shot 2020-03-24 at 3 13 53 PM](https://user-images.githubusercontent.com/20227374/77687873-82878e00-6f75-11ea-9092-11f3f470c00f.png)

**Is your feature request related to a problem? Please describe.**
This feature request is related to this epic: https://github.com/kiali/kiali/issues/2314

This design addresses just a small part of the current toolbar mainly the edge labels dropdown. This design features the edge labels dropdown getting combined with the display dropdown to try to save some of the horizontal space in the toolbar. This design keeps the traffic related fields right aligned, similar to what is currently implemented. 

**Here are the wireframes of this design proposal:** 
<img width="906" alt="Screen Shot 2020-03-26 at 6 25 14 PM" src="https://user-images.githubusercontent.com/20227374/77702557-2f223980-6f8f-11ea-95c9-a2a398ac1a60.png">
The display dropdown moves to the second spot in the second level of the toolbar. 
________________________________________________________________________

<img width="945" alt="Screen Shot 2020-03-26 at 6 29 28 PM" src="https://user-images.githubusercontent.com/20227374/77702838-c4253280-6f8f-11ea-841d-d3c69ae8123c.png">
To view the different display options, the user clicks on the display dropdown and the different options are revealed. The edge label options are the first options on the dropdown. Since the user can only select one type of edge label to display the toggle is a radio button. The other display options remain as checkbox since the user can select a variety of those. 

_________________________________________________________________________
<img width="937" alt="Screen Shot 2020-03-26 at 6 31 33 PM" src="https://user-images.githubusercontent.com/20227374/77702959-0d758200-6f90-11ea-9ecf-ca90b16c489a.png">
In this example, the user has selected requests per second as their edge label. The graph reacts and shows that edge label type and the total number of displayed options increases to 7. 

_________________________________________________________________________

<img width="831" alt="Screen Shot 2020-03-26 at 6 32 37 PM" src="https://user-images.githubusercontent.com/20227374/77703058-40b81100-6f90-11ea-8171-119c38a91b8e.png">
The dropdown collapses once the user has clicked away from it and the total number in the display dropdown increases to 7. 

__________________________________________________________________________

**Describe alternatives you've considered**
This is just one part of different design options we are starting to explore for improving the toolbar's use of space.

**Additional context**
Additional design work is going on related to this and I can update this issue if anything changes on that front.

**Comment by jshaughn** [comment]
@lwrigh I solved the radio button issue by working around the deficiency in the Select component.  I still think the Select component could be enhanced but it's not a blocker.

But now, given the extended height of the dropdown, I've noticed that it can get cropped without scroll bars if the browser window is too short.  And I'm not seeing a way around it just yet.  I'll keep looking.  But this may be another issue with Select in PF4.

**Comment by lwrigh** [comment]
@jshaughn Yay that's great to hear! I'm glad you were able to figure that bit out. I didn't get an immediate response when I asked the PF team about it so I'll keep you posted if they have any other suggestions on the component. 

If you can find a way to add a scrollbar to it when the viewport is shorter that would be great. Definitely from a usability perspective that way instead of having to scroll the whole page.

**Comment by jmazzitelli** [comment]
What if you made the drop down menu with columns? That would help shorten the height (though would increase the width, however, I'm sure the UI framework has the ability to shift the drop down's horizontal location to fit in the screen). I'm thinking something like:

![drop-down-columns](https://user-images.githubusercontent.com/2029470/78145107-7892de80-73fe-11ea-8469-d49195c74fb2.jpg)

**Comment by lwrigh** [comment]
It's easier to scan when it's just one single column instead of two so that's my one concern if the sections were split into two sections.
