### ISSUE TITLE
Enable Envoy dashboard by default

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#2582]
As per poll results: https://discuss.istio.io/t/poll-should-we-make-envoy-dashboards-in-kiali-more-visible/5267/4 , enable Envoy dashboards (make it opt-out instead of opt-in).

Note: a recent change (regression?) in Istio 1.5 makes this task more difficult if not obsolete. So, as a pre-requisite, this istio issue would need to be resolved first: https://github.com/istio/istio/issues/22584

**Comment by lucasponce** [comment]
It seems the labels required in envoy metric for correlation were back and probably this issue could be unblocked.

Please, @jotak let me know if you can confirm that.

I'm reviewing old issues and this one was interesting to revisit it.

I'm adding to the Project to discuss priorities as I'm running a global review of old issues in the backlog.

**Comment by jotak** [comment]
I'll take a look

**Comment by jotak** [comment]
indeed, the labels are there (testing with istio 1.8), we can enable it
