### ISSUE TITLE
Update Kiali UI to latest Node.js LTS version

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#2596]
**Is your feature request related to a problem? Please describe.**
Our policy has been to have our dev tools track with the LTS versions. For Node.js the current version 10 just went into maintenance mode. So the current LTS version is now 12 (from 10).

**Describe the solution you'd like**
We should now support just node versions 12+. Current version is 13/14.

<img width="773" alt="Releases___Node_js" src="https://user-images.githubusercontent.com/1312165/78148122-517de200-73e9-11ea-9d2d-14b0c720b775.png">

Obviously, this should be done at the beginning of a sprint.

**Comment by jshaughn** [comment]
@mtho11 Is this a simple update or is there work?  I seem to remember someone telling me we actually required node 10 and that node 12 didn't work for us.  Perhaps that is only for building V1.0, I'm not sure.

**Comment by mtho11** [comment]
@jshaughn we will know until we do it. That is the purpose of this issue.

**Comment by mtho11** [comment]
We also need to validate the downstream environments are capable of using Node.js 12.x

**Comment by jshaughn** [comment]
right, ok, so I agree that we need to move forward but it seems there could be issues.  I'll tag this for grooming to get figure out priority.

**Comment by mtho11** [comment]
Before we do anything we need to check if the Prod build environments can support Node.js 12? @israel-hdez do you know?

**Comment by israel-hdez** [comment]
@mtho11 I don't know. I'll check while I'm working on build automation.

**Comment by israel-hdez** [comment]
Prod build won work. I get

`Error: No Package found for rh-nodejs12`

I don't see nodejs12 in [Software Collections](https://www.softwarecollections.org/en/scls/?search=node&policy=&repo=&order_by=-create_date&per_page=10). I would need to ask around to find the right name of the package, if available.

**Comment by lucasponce** [comment]
Any update around this ?

**Comment by israel-hdez** [comment]
I still don't see nodejs12 in Software Collections. I added a `waiting external` label because we need nodejs12 support.

**Comment by jshaughn** [comment]
@israel-hdez Should we again check for nodejs12 support ?

**Comment by israel-hdez** [comment]
@jshaughn I think we should. From the chart, nodeJS 10 is going EOL soon. I think this is becoming a priority.
