### ISSUE TITLE
LDAP Integration (skipTLS)

### ISSUE THREAD

**Issue by angelbarrera92** [kiali/kiali#2599]
Hi team!

I faced an error while trying to test Kiali integration with LDAP.
I was trying to integrate an OpenLDAP server using `osixia/openldap:1.3.0` docker image with Kiali > 1.9 (I tried from 1.9 to latest version)

My LDAP Server is running without any kind of SSL/TLS mechanism (I know I should use it but I want to try it locally first without SSL/TLS)

The problem is that Kiali exposes some LDAP configuration parameters like:

```
auth:
  strategy: ldap
  ldap:
    ldap_host: "ldap-server.demo-ldap"
    ldap_port: 389
    ldap_use_ssl: false
    ldap_insecure_skip_verify: true
    ldap_base: "dc=sighup,dc=io"
    ldap_bind_dn: "cn={USERID},ou=people,dc=sighup,dc=io"
```

And trough the following error:

```bash
I0402 12:13:17.560793       1 ldap.go:22] DEBUG: Connecting to LDAP with config: {{dc=sighup,dc=io cn={USERID},ou=people,dc=sighup,dc=io true  ldap-server.demo-ldap   389     false} ldap}
I0402 12:13:17.560863       1 ldap.go:24] DEBUG: bindDN : cn=,ou=people,dc=sighup,dc=io
E0402 12:13:17.644868       1 ldap.go:59] Error authenticating user : LDAP Result Code 200 "Network Error": TLS handshake failed (EOF)
I0402 12:13:17.644936       1 ldap.go:48] DEBUG: Authentication failed with LDAP : LDAP Result Code 200 "Network Error": TLS handshake failed (EOF)
I0402 12:13:19.901040       1 ldap.go:22] DEBUG: Connecting to LDAP with config: {{dc=sighup,dc=io cn={USERID},ou=people,dc=sighup,dc=io true  ldap-server.demo-ldap   389     false} ldap}
I0402 12:13:19.901077       1 ldap.go:24] DEBUG: bindDN : cn=angel,ou=people,dc=sighup,dc=io
E0402 12:13:19.926779       1 ldap.go:59] Error authenticating user angel: LDAP Result Code 200 "Network Error": TLS handshake failed (EOF)
I0402 12:13:19.926810       1 ldap.go:48] DEBUG: Authentication failed with LDAP : LDAP Result Code 200 "Network Error": TLS handshake failed (EOF)
```

> **Code 200 "Network Error": TLS handshake failed**

I was debugging an i found the issue. Kiali is not exposing: [`SkipTLS` parameter from the go library you are using to interact with LDAP](https://github.com/jtblin/go-ldap-client/blob/master/ldap-client.go#L26).

Kiali code: https://github.com/kiali/kiali/blob/master/ldap/ldap.go#L27

So...
if you think is a good idea to expose this ldap parameter, let me know and i can work on that ;)

Thanks!

**Comment by lucasponce** [comment]
cc @israel-hdez what do you think ?

**Comment by jmazzitelli** [comment]
PRs welcome in this area of the LDAP integration. The entire original LDAP integration feature was contributed by a community member, who has not been around for a while.  But if someone else wants to update it with new features, feel free to submit a PR.

Note that we have a molecule test that tests the LDAP feature - you may want to update it to test any new features added. See: https://github.com/kiali/kiali/tree/master/operator/molecule/ldap-test

**Comment by israel-hdez** [comment]
@angelbarrera92 I second @jmazzitelli here. You already did all the debugging and I think should create a PR to fix the issue and get acknowledged. Would you like to prepare the fix?

**Comment by angelbarrera92** [comment]
I will try it :)

**Comment by angelbarrera92** [comment]
https://github.com/jtblin/go-ldap-client/compare/0.0.3...master

Seems like the upstream library didn't release a new version with latest master changes (including the skip-tls part we need) 🤦‍♂ 🤦‍♀ 

So...

I don't know what's your opinion about using `master` branches instead of tags/static-versions for external libraries... (I don't like at all)

In addition to that, that golang library seems to be... abandoned (last commit three years ago).

Should I continue with the `master` branch of the ldap library?

**Comment by israel-hdez** [comment]
Yes, as @jmazzitelli said, we'd prefer a released version. So, if there is a library that can be swapped with minimum changes, I'd say it's better to replace the current one.

Else... well... diff from 0.0.3 & master is small and looks OK for me, and we already have some other dependencies which we use from a non-released code. The Prometheus "common" dependency is an example (see https://github.com/kiali/kiali/blob/master/glide.yaml#L15-L16). So, if it is too much work to replace the LDAP library, I'd fallback to pointing to the specific commit rather than to `master`.

**Comment by angelbarrera92** [comment]
Hi guys
I will go with the latest SHA commit in the go-ldap-client library.
I will try to do it during the weekend!

**Comment by angelbarrera92** [comment]
Hi team.

I'm not an expert golang developer. But... I can not compile the project if I run the `dep-update` make target. *(at master branch without changes)*

```bash
$ make clean build
# Works
$ make clean dep-update build
# Fails
Building...
GOOS=darwin GOARCH=amd64 CGO_ENABLED=0  go build \
                -o /Users/angelbarrerasanchez-sighup/go/bin/kiali -ldflags "-X main.version=v1.16.0-SNAPSHOT -X main.commitHash=cbdfbffbe20e113e8a0285e3416daefd50058d56"
# github.com/kiali/kiali/vendor/github.com/prometheus/client_model/go
vendor/github.com/prometheus/client_model/go/metrics.pb.go:22:11: undefined: proto.ProtoPackageIsVersion3
make: *** [build] Error 2
```

I need to update the ldap go library and i have to run the `dep-update`... Am i right?
Maybe I am using the wrong make targets.

Thanks!

**Comment by israel-hdez** [comment]
@angelbarrera92 Sorry for late reply
Well... it also happens to me. I'll ask for @jotak help. He has been successfully changing dependencies without these issues. He may help with a suggestion.

**Comment by jotak** [comment]
I can reproduce, I'm seeing the same locally.
It looks like a version conflict on `github.com/golang/protobuf/proto`. The one pulled from `prometheus/client_model` is probably different from another one pulled elsewhere. Needs more investigation, I'm still looking at it...

**Comment by jotak** [comment]
@angelbarrera92 this is fixed, you should be able now to rebase & run dep-update again

**Comment by angelbarrera92** [comment]
> @angelbarrera92 this is fixed, you should be able now to rebase & run dep-update again

I can confirm the dependency problem is solved ;) Thanks for the PR!

**Comment by jmazzitelli** [comment]
For the record, the [LDAP auth strategy is being deprecated](https://github.com/kiali/kiali/issues/2863). Kiali now supports OpenID Connect, so in the future, you should put oidc in front of LDAP (or use the oidc feature in your LDAP implementation if it has one) in order to get Kiali to authenticate with LDAP.
