### ISSUE TITLE
Right-click on graph to add Default Traffic Generator (via GET)

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#2601]
**Is your feature request related to a problem? Please describe.**
We could have the ability to create traffic for endpoints (or elsewhere) at certain intervals/rates. This would make it easy for new service mesh newbies to test stuff (lowering the bar).

I realize this can get complicated quickly, but this basic GET with a wizard for params is a nice value add as this is a tedious task.

I'm just capturing a thought @maltron gave at our last water cooler meeting so we don't lose it (I have also thought this same thing).

**Comment by lucasponce** [comment]
I don't think I like Kiali providing a Default Traffic Generator.
That's out of the scope of Kiali.

It may work in very simple/example-driven scenarios, bookinfo, but it tends to get really complex in a minimal realistic scenario where there are several constraints in data model / security.

One thing that I like is to identify if there is a third party solid project that provides a similar feature, then I agree that could be a good candidate for an extension.

**Comment by lucasponce** [comment]
I'm going to close this issue.
As commented this feature could be captured as an extension integrating with some third party framework, but not something that it's in the radar of Kiali main core features.
