### ISSUE TITLE
Update the kind-of kiali-ui package from github security alert

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#2604]
**General remarks**
As alerted from Github.com: 

<img width="1261" alt="Alerts_·_kiali_kiali-ui" src="https://user-images.githubusercontent.com/1312165/78322545-e38a0580-7523-11ea-9c38-9c332fc96b3c.png">

**Comment by jshaughn** [comment]
@mtho11 Lib updates should still be triaged/prioritized.

**Comment by mtho11** [comment]
This was merged.
