### ISSUE TITLE
Enable me create Gateway, VirtualServices etc from Kiali Dashboard

### ISSUE THREAD

**Issue by gyliu513** [kiali/kiali#261]
Most of the open source projects are doing visualisation for istio, but seems no one is creating a dashboard which can do write operations for istio, such as creating gateway, virtualservices etc. Hope istio can have such feature.

@jmazzitelli

**Comment by lucasponce** [comment]
Hi, @gyliu513, write operations have been in the roadmap of Kiali.
We have created a JIRA to start with it that can be tracked here https://issues.jboss.org/browse/KIALI-938.

Feel free to add your comments as well, it could be interesting if there are some requeriments that can be incorporated on the task.
