### ISSUE TITLE
Stop publishing Kiali to DockerHub

### ISSUE THREAD

**Issue by israel-hdez** [kiali/kiali#2615]
It's been a while since we are releasing Kiali to Quay.io and it became our main registry to publish releases.

Istio versions currently maintained are, by default, pulling from Quay.io. In Kiali, it's been a long time since we no longer talk about pulling from DockerHub.

To simplify code and release process, I'd suggest to fully deprecate DockerHub images and stop publishing Kiali images to it.

**Comment by jmazzitelli** [comment]
I think we can do this now - none of the upstream Istio releases that are currently 'supported' by the upstream istio community are using helm charts that pull kiali from docker.io. As far back as Istio 1.2 they were pulling kiali from quay.io (Istio 1.1 appears to be the last that pulled from docker.io).
