### ISSUE TITLE
Kiali.io Automate Latest Videos Section

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#2617]
**Is your feature request related to a problem? Please describe.**
On Kiali.io website there is a section for 'Latest videos' that currently needs to be manually updated whenever new videos come out.

**Describe the solution you'd like**
We would like it if the videos would automatically update when a new video is put into the Kiali Youtube channel.

**Describe alternatives you've considered**
This could be done via a script calling the Youtube API.

**Comment by lucasponce** [comment]
Outdated.

Videos are not pulled from youtube tags, specially for Sprints.
