### ISSUE TITLE
Graph fails to show up with "Failed ID gen"

### ISSUE THREAD

**Issue by uncycler** [kiali/kiali#2622]
**Describe the bug**
Using Istio with mTLS enabled, I have a pod that post a metric on a prometheus-pushgateway located in a different namespace which is destroyed right after (it's a gitlab runner's helper). Somehow, this break Kiali graph with the following error:

```
graph.go:87] Failed ID gen: namespace=[gitlab] workload=[unknown] app=[unknown] version=[latest] service=[] graphType=[versionedApp]: goroutine 405 [running]:
runtime/debug.Stack(0xc0012e4408, 0x1240620, 0xc000959b10)
	/home/jmazzite/bin/go-install/go/src/runtime/debug/stack.go:24 +0x9d
github.com/kiali/kiali/handlers.handlePanic(0x1676940, 0xc001052460)
	/home/jmazzite/source/kiali/kiali/src/github.com/kiali/kiali/handlers/graph.go:86 +0x155
panic(0x1240620, 0xc000959b10)
	/home/jmazzite/bin/go-install/go/src/runtime/panic.go:967 +0x15d
```

The rogue prometheus query seems to be:
```
round(sum(rate(istio_requests_total{reporter="destination",source_workload="unknown",destination_workload_namespace="mynamespace"} [60s])) by (source_workload_namespace,source_workload,source_canonical_service,source_canonical_revision,destination_service_namespace,destination_service,destination_service_name,destination_workload_namespace,destination_workload,destination_canonical_service,destination_canonical_revision,request_protocol,response_code,grpc_response_status,response_flags),0.001)
```
I guess prometheus don't have time to scrap this pod to get full information.

**Versions used**
Kiali: 1.15.1
Istio: 1.5.1
Kubernetes flavour and version: AWS EKS 1.15

**To Reproduce**
1. Enable mutual TLS
2. Create two pod with the Istio sidecar in different namespaces
3. Do a post request from one pod to another and delete it.
4. Try to load kiali graph.

**Expected behavior**
Graph should just ignore those and show up.

**Comment by jshaughn** [comment]
@uncycler You are definitely hitting unexpected/incomplete telemetry being generated by Istio.  This is very likely a new corner-case in Istio's Telemetry V2, the new default for Istio 1.5.    The query you posted is fine, it's more rogue data than a rogue query.

From what I can see in your report you have data with a destination_workload_namespace but no actual destination_workload.  If you are still experiencing the problem and can access the Prometheus UI, can you please try the following prometheus query:

```
round(sum(rate(istio_requests_total{reporter="destination",destination_workload_namespace!="unknown",destination_workload="unknown"} [60s])) by (source_workload_namespace,source_workload,source_canonical_service,source_canonical_revision,destination_service_namespace,destination_service,destination_service_name,destination_workload_namespace,destination_workload,destination_canonical_service,destination_canonical_revision,request_protocol,response_code,grpc_response_status,response_flags),0.001)
```

If you get any results please let me know, I would not expect many bad time series of this sort.

**Comment by uncycler** [comment]
Your query return nothing while the one I reported return one metric with 0 as value. Actually, prometheus and grafana seems to work fine, I haven't encountered any glitch with those.

**Comment by jshaughn** [comment]
@uncycler OK, can you please post the one result you get from the query you posted (scrub any sensitive data).

**Comment by uncycler** [comment]
Sure, here it is:

```
{destination_canonical_revision="latest",destination_canonical_service="prometheus",destination_service="prometheus-pushgateway.mynamespace.svc.cluster.local",destination_service_name="prometheus-pushgateway",destination_service_namespace="mynamespace",destination_workload="prometheus-pushgateway",destination_workload_namespace="mynamespace",request_protocol="http",response_code="200",response_flags="-",source_canonical_revision="latest",source_canonical_service="unknown",source_workload="unknown",source_workload_namespace="gitlab"}
```

**Comment by jshaughn** [comment]
@uncycler OK, that is definitely the problem time-series.  It's not something we have seen before, where the source namespace is set, in this case "gitlab", but with no other source information.  There are two ways we could handle this situation.  Option (1) is that we discard the time-series as bad telemetry.  Option (2) is that we treat it as a valid request from "unknown".  In option (1) it just goes away as if it were never reported.  In option (2) it could show up in the graph as an edge from the "unknown" node to the destination (in this case mynamespace::prometheus-pushgateway).

Which would you have preferred?

**Comment by uncycler** [comment]
Well, in this particular case, I would prefer option 1, but some people might want it to show up. Let's say, when Istio will support sidecar in Job/CronJob (hopefully!), this kind of thing might happened more often.

**Comment by jshaughn** [comment]
@uncycler Thanks for the feedback, I agree and for now we will filter this as bad telemetry.   I expect the number of actual requests for this time-series is very small, likely indicating that it is not reflecting actual traffic (you could re-run the query using just `sum(` to get the raw request count).
