### ISSUE TITLE
Enhance baseline/candidate fields in Iter8 list page

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#2634]
In the Iter8 Experiments list page there are some fields defined:
- Name, Namespace, Phase of the Experiment, Status, Baseline and Candidate.

When an Iter8 Experiment is running, Iter8 controlling is shifting traffic from baseline version to candidate version to perform a computation to analyze which version is working better given a detailed criteria.

In the list, we show the % of the traffic shifting between versions as it's shown in the screenshot:

![image](https://user-images.githubusercontent.com/1662329/78805649-f6885400-79c1-11ea-9d55-b16a9b3fd733.png)

One minor question, could be identify how we want to print this %, perhaps some graphical / chart representation may help.

**Comment by jadeyliu939** [comment]
This is Iter8 team's prototype design. **Adding Service column** ( the service that the experiment ran on) 

**Option 1**:  Adding icon for phase ( green color for success, red color for fail )
<img width="1623" alt="listing1" src="https://user-images.githubusercontent.com/4615187/78841728-1fade200-79cc-11ea-882d-ece4c4ca8acd.png">

**Option 2**: Remove Status field, instead add to tooltip of the phase icon.

<img width="1621" alt="listing2" src="https://user-images.githubusercontent.com/4615187/78841737-28061d00-79cc-11ea-84ac-f5979b094e71.png">

**ToDo**: adding filter dropdown for Service

**Comment by lucasponce** [comment]
Thanks @jadeyliu939 !
Personally I really like the Option 2 with the details on the tooltip and if user needs more info, to move the previous status details column inside the Iter8 Experiment detail.

This looks more or less ready I think, if you have a PR just for this, I would be happy to review and consolidate it.

Note this could be separated from other efforts.

In general no need to send an all-together-pr, it's perfectly fine to enhance the list and we can separate that effort from the Experiment details or other subtasks.

Sorry for my delay, Easter break has impacted on my availability.

**Comment by lucasponce** [comment]
Fixed by https://github.com/kiali/kiali-ui/pull/1753
