### ISSUE TITLE
CSS difference between dev (yarn start) and prod builds

### ISSUE THREAD

**Issue by jshaughn** [kiali/kiali#2635]
In general yarn start provides the same behavior as yarn build.  But recently there have been discrepencies such that dev mode incorrectly renders some elements.  What I have seen most often is "top" alignment issues like this:

Dev Mode:
![image](https://user-images.githubusercontent.com/2104052/78816726-1e66c000-79a0-11ea-9adc-c13f25f8b9bd.png)

Prod Build:
![image](https://user-images.githubusercontent.com/2104052/78816816-39d1cb00-79a0-11ea-896d-212185f55e4c.png)

**Comment by israel-hdez** [comment]
While working on #2331, apparently all styles are there. The issue is that order of styles is different and that has impact on the final resolved styles :/

**Comment by lucasponce** [comment]
If no one is taking a look at it, I'm going to try to reproduce and check if we can fix it before we release.
Not a blocker, but it's really annoying.
