### ISSUE TITLE
Tabs below the fold on Services Details pages

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#2648]
**General remarks**
Even when using a large monitor, the tabs for Workloads/Virtual Services/Destination Rules are below the fold and I would not even know those tabs existed if I didn't scroll down (which the scrollbar doesn't even show unless you scroll down).

<img width="1834" alt="Kiali_Console" src="https://user-images.githubusercontent.com/1312165/79177706-59119380-7db8-11ea-9ecc-c64bfefef839.png">

This is probably due to the Health Overview tab:
<img width="1834" alt="Kiali_Console" src="https://user-images.githubusercontent.com/1312165/79177990-e05f0700-7db8-11ea-85a4-6ab3eaf65345.png">

But most importantly, when you do scroll down the VS/DR rules none of the information at the top even makes any sense:

<img width="1820" alt="Kiali_Console" src="https://user-images.githubusercontent.com/1312165/79178377-f1f4de80-7db9-11ea-8595-0095d2c50a4d.png">

**Comment by mtho11** [comment]
CC: @kiali/ux-reviewers

**Comment by lucasponce** [comment]
@mtho11 this one was in the radar as we have a pending suggestion from UX to apply but it has less priority due releases effort.

When the body is scrolling, I don't see the scroll bar in the left of your capture, can you confirm that is present ?

I don't think that cards should provide "floating titltes" when scrolling.

Remember, we are scrolling a canvas of cards and I haven't see that in the pf4 suggestions.

What is the bug exactly ? To me ux should not be involved in bugs but developers, ux are involved in re-designs.

Please, sync with the team is working on these pages first to involve UX thanks.

**Comment by mtho11** [comment]
@lucasponce I would consider this a bug because there is no because there is no indication that there are tabs below and those tabs are hidden below the fold. Many users will not even know they are there and they are very important tabs for functionality.

Perhaps a video will help illustrate:
![service-detail-tabs](https://user-images.githubusercontent.com/1312165/79255978-185b5e00-7e3c-11ea-8e76-974cfda0c857.gif)

**Comment by lucasponce** [comment]
Being discussed/proposed a workaround as part of #2616
