### ISSUE TITLE
BlackHoleCluster in Graph instead of ServiceEntry

### ISSUE THREAD

**Issue by mikaint** [kiali/kiali#2649]
I have created a ServiceEntry for external services (REGISTRY_ONLY option enabled) and requests are successful. However, in Kiali i don't see those services; just a BlalckHoleCluster (PassThroughCluster when ALLOW_ANY).

![blackhole](https://user-images.githubusercontent.com/1333203/79190801-d4615c80-7e2d-11ea-8ab5-6c2e700d2e48.PNG)

**Versions used**
Kiali: v1.15.1
Istio: 1.5.1
Kubernetes flavour and version: EKS 1.15

**Comment by jshaughn** [comment]
@mikaint I think this is a duplicate of https://github.com/kiali/kiali/issues/2548.  Please update to 1.15.2 and retest, thanks!

**Comment by mikaint** [comment]
Update resolved the issue. Thank you!
