### ISSUE TITLE
Service list - Filter by Label fails to load

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#2650]
Happens on Kiali master.

1. Go to Services.
2. Filter by Label: "app".
3. It fails to load services, error is shown in UI: "Could not fetch services list".
![Screenshot from 2020-04-14 09-51-58](https://user-images.githubusercontent.com/604313/79199899-ed6e0b80-7e35-11ea-9d45-811e9c68c201.png)

No Logs in Kiali pod.

**Comment by lucasponce** [comment]
Please @aljesusg, as you are working on this area, I've assigned you to this one.

**Comment by aljesusg** [comment]
Hi @hhovsepy which version are you testing? Can you share your env? I tested the actual master and it's working
![Screenshot from 2020-04-14 12-52-21](https://user-images.githubusercontent.com/3019213/79217263-d8ea3d00-7e4e-11ea-8b93-2701472e86dd.png)

**Comment by aljesusg** [comment]
Anyway it seems there is a bug releated with the lighted, There is an space bettwen the tag key and value and I am not testing this

![Screenshot from 2020-04-14 12-52-21](https://user-images.githubusercontent.com/3019213/79217446-29619a80-7e4f-11ea-87a9-ca7e99477644.png)
