### ISSUE TITLE
Install Kiali in plain k8s cluster

### ISSUE THREAD

**Issue by haf** [kiali/kiali#2651]
**Is your feature request related to a problem? Please describe.**
It's impossible to find installation instructions for Kiali that aren't wrapped with layers of indirection;

- Install via istioctl, and you get precisely that; a binary that takes care of things for you (badly)
- Deconstruct what istioctl does into a yaml files, and you end up with a lot of files you have to manually manage without docs
- Try reading the quickstart and you have a solution that recommends administrators running scripts fetched from the internet, in the production environments without the ability to verify them — or even when browsing the script source, it's too much stuff

**Describe the solution you'd like**
I want two lines; one that downloads the operator/kiali as an all-in-one YAML file, like this https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-quickstart.html#k8s-deploy-eck or https://github.com/jaegertracing/jaeger-operator#getting-started — not a script file

After having downloaded the all-in-one (or list of yaml files), I can customise them with kustomize before deploying them into my environment.

After having downloaded everything, I need to configure it; the docs in the commented yaml file are rather hard to read, and provide many mutually exclusive configuration items, without detailing which ones are pairwise mutexes.

(E.g. configuring the jaeger URL; I configure `http://jaeger-query.monitoring:16686`, but the error message in the browser uses the `url` and not the `in_cluster_url` and the error message in the log uses the above URL. Also, both fail; internally with a timeout (which is inherently very hard to debug))

Besides this, the docs are way too focused on OpenShift; I understand that the authors are pushing it as a competitive advantage, but at the very least, provide clear installation directions for both. Both the Jaeger operator and Elastic operator were much much easier to install, because they have clear docs.

**Describe alternatives you've considered**
- Stopping using Kiali, because the docs on what to configure where are lacking
- Running scripts from the internet locally; considered, but disregarded since it breaks my security model

**Additional context**

```
kiali-7d69fc5689-bxgdb kiali E0414 14:55:57.394353       1 jaeger_helper.go:64] Error fetching Jaeger Error Traces (0): Get http://jaeger-query.monitoring:16686/api/traces?end=1586876156393928&lookback=1h&service=prometheus.monitoring&start=1586872556393928&tags=%7B%22error%22%3A%22true%22%7D: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
kiali-7d69fc5689-bxgdb kiali E0414 15:09:05.367599       1 dashboards.go:305] runtimes discovery failed, cannot load dashboards in namespace fou. Error was: the server could not find the requested resource (get monitoringdashboards.monitoring.kiali.io)
kiali-7d69fc5689-bxgdb kiali E0414 15:09:05.372522       1 dashboards.go:286] runtimes discovery failed, cannot load metrics for labels: {namespace="fou",app="fou-web"}. Error was: Get http://prometheus.istio-system:9090/api/v1/series?end=2020-04-14T15%3A09%3A05.366488381Z&match%5B%5D=%7Bnamespace%3D%22fou%22%2Capp%3D%22fou-web%22%7D&start=2020-04-14T14%3A09%3A05.366488381Z: dial tcp: lookup prometheus.istio-system on 10.96.0.10:53: no such host
kiali-7d69fc5689-bxgdb kiali E0414 15:09:07.210897       1 dashboards.go:305] runtimes discovery failed, cannot load dashboards in namespace fou. Error was: the server could not find the requested resource (get monitoringdashboards.monitoring.kiali.io)
kiali-7d69fc5689-bxgdb kiali E0414 15:09:07.217861       1 dashboards.go:286] runtimes discovery failed, cannot load metrics for labels: {namespace="fou",app="fou-web"}. Error was: Get http://prometheus.istio-system:9090/api/v1/series?end=2020-04-14T15%3A09%3A07.209495764Z&match%5B%5D=%7Bnamespace%3D%22fou%22%2Capp%3D%22fou-web%22%7D&start=2020-04-14T14%3A09%3A07.209495764Z: dial tcp: lookup prometheus.istio-system on 10.96.0.10:53: no such host
```

In the above example, I have indeed configured Prometheus like so:

```
    istio_component_namespaces:
      prometheus: monitoring
      # ...

    external_services:
      # ...
      prometheus:
        url: http://prometheus.monitoring:9090
```

so it doesn't make sense that the error looks in `.istio-system` for it.

**Comment by jmazzitelli** [comment]
> one that downloads the operator/kiali as an all-in-one YAML file

Have you tried using the `--dry-run=<all-in-one-yaml-output-file>` option?

See: https://github.com/kiali/kiali/blob/v1.15.2/operator/deploy/deploy-kiali-operator.sh#L351-L354

```
bash <(curl -L https://git.io/getLatestKialiOperator) -dr /tmp/kiali-all-in-one.yaml
```

That should spit out an all-in-one file that you can then customize. That yaml would then be what you use to install.

If you don't want to run directly from the Internet, you can git clone kiali repo and run directly from the operator/deploy directory. In the end, the result is the same - you have an all-in-one yaml that you can use to install.

(Note: currently the `--dry-run` option will spit out a couple warning messages towards the end, this is due to some kubectl apply commands spitting out the errors when getting passed the `--dry-run` option to it - but these can be ignored. The all-in-one yaml should be correct.)

**Comment by jmazzitelli** [comment]
> so it doesn't make sense that the error looks in `.istio-system` for it.

That looks like a separate issue dealing with configuring Kiali to access your own Prometheus, not related to the need for an all-in-one yaml.

**Comment by jmazzitelli** [comment]
I also forgot to mention another obvious solution - use the `merge-operator-yaml.sh` script to build an all-in-one yaml to install just the operator. You would then need to create a Kiali CR for each Kiali you want installed (you could optionally add a Kiali CR to the all-in-one produced by this merge script as well).

See: https://github.com/kiali/kiali-operator/blob/master/deploy/merge-operator-yaml.sh

**Comment by haf** [comment]
This is really great input. I'll file a PR against docs; where would I do that?

**Comment by jmazzitelli** [comment]
The kiali docs are in [the kiali.io repo](https://github.com/kiali/kiali.io) - you can file a PR there.

**Comment by israel-hdez** [comment]
This had evolved a lot.
* There is no longer a script to install Kiali. Instead, helm is used.
* On Istio side, Kiali has been "pulled out". Now, you use addons and install via a regular `kubectl apply` command.
* Quick start docs had been improved.

I'm closing this issue as outdated.
