### ISSUE TITLE
Quarkus dashboard error

### ISSUE THREAD

**Issue by previousdeveloper** [kiali/kiali#2657]
**Versions used**
Kiali: 1.15.1
Istio: 1.15.1
Kubernetes flavor and version: on-prem

I want to show custom metric for java application,  (https://kiali.io/documentation/runtimes-monitoring/)
that does not work for me.

> kubectl get crds | grep -i kiali                                                                                                                                                                          
kialis.kiali.io                            2020-04-14T19:34:52Z
monitoringdashboards.monitoring.kiali.io   2020-04-14T20:07:24Z

**Error**
 cannot get dashboard quarkus in namespace browsing-team. Error was: the server could not find the requested resource (get monitoringdashboards.monitoring.kiali.io

Thanks

**Comment by jotak** [comment]
Hi @previousdeveloper ,

This message might not be the problem: Kiali is looking for dashboards in the application's namespace, and if not found it looks in istio-system namespace. Which is probably the case here if you didn't install your own dashboards (Kiali installed them in istio-system).

Can you elaborate about what you can and cannot see? Do you see no dashboard at all? Or an empty one?
Could you also check prometheus to make sure you have quarkus metrics in there?

Also, note that depending on your version of quarkus, the dashboard installed by Kiali might be a little bit outdated ; I've a pending PR about that: https://github.com/kiali/kiali/pull/2195

**Comment by jotak** [comment]
Closing this one.

For information, there's apparently going to be some changes in quarkus metrics. We want to create a quarkus dashboard that can be reasonably stable in time, so we're going to wait for that work to be done on quarkus side, but we're not going to maintain a dashboard for every single version of quarkus.

Users can still create their own dashboards for whatever version they're using (see doc https://kiali.io/documentation/latest/runtimes-monitoring/#_create_new_dashboards )
