### ISSUE TITLE
Fresh Minikube Istio cluster shouldn't report any errors

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#2658]
**Is your feature request related to a problem? Please describe.**
As a new user, starting up Kiali with a fresh cluster, I would expect no errors (warnings possibly). But the errors undermine my confidence in both Istio and Kiali.

<img width="1835" alt="Kiali_Console" src="https://user-images.githubusercontent.com/1312165/79279324-a21e2200-7e62-11ea-9f4d-8ca949b59a0e.png">

When I click on that red error exclamation point the detail I get is this:

<img width="1836" alt="Kiali_Console" src="https://user-images.githubusercontent.com/1312165/79279663-60da4200-7e63-11ea-9103-c962293de353.png">

and further drill-down: 

<img width="1844" alt="Kiali_Console" src="https://user-images.githubusercontent.com/1312165/79279800-b282cc80-7e63-11ea-8805-4cef87192fe7.png">

How do I fix this? I just installed my cluster -- Is it bad?!

Since I just installed Istio shouldn't everything be Green!

**Describe the solution you'd like**
With a fresh cluster I would expect Kiali to start up clean with no errors being reported about my Istio cluster.

**Comment by mtho11** [comment]
This was a fresh install with no book-info installed yet.
CC @xeviknal

**Comment by xeviknal** [comment]
Thanks for bringing this up.

Perhaps we should revisit the severity of the validation, but the validation itself seems legit. If you see the host of this virtual service points to a non-existing cluster.

Also we should see if there is a bug on this demo installation from Istio side.

btw, do you mind providing the istio installation method?

**Comment by mtho11** [comment]
Hi @xeviknal , 
I used `istioctl manifest apply --set profile=demo` to install Istio 1.4.7

**Comment by xeviknal** [comment]
I can reproduce this problem. I do agree with you @mtho11 that is quite unexpected to see a configuration error in a fresh environment.

What I see that is happening is that Istio has prepared on the demo installation a setup for multicluster communications. Those files are, if I am not wrong, all the configuration you need to send traffic to another cluster (using mTLS).
The feeling is that Istio team wants to ease the onboard to multiclustering to all its users by putting this prepared configs.

The status of the cluster right now is:
1. All the internal comms are working as expected.
2. All comms to an external service (Service Entry) are working.
3. All the comms to another cluster are not working. *.global hosts are captured and send to 'non.existent.cluster'.

Being said that, I think Kiali shows a legit validation problem.

One tricky solution could be to change severity of the validation to `info` [0] for this specific case (when host name is non.existent.cluster). The outcome would be:

1. Overview page would be in green.
2. User when browsing the object itself will see that Kiali knows about it and acknowledge the situation. The user won't have the feeling that Kiali validations are broken bc of a clear inexistent cluster.

Thoughts?

[0] https://user-images.githubusercontent.com/562574/57530077-1a20c580-733f-11e9-8ef5-d9e55faf77f2.png

**Comment by mtho11** [comment]
@jshaughn @jmazzitelli @lucasponce your thoughts?

**Comment by jmazzitelli** [comment]
The fact this was the Istio "demo" profile is important. As @xeviknal says, the Istio teams puts some stuff in the demo profile to ease onboarding but some demo profile stuff is not ready for production and may even have incomplete config.

I see nothing wrong with Kiali flagging an error here because something is wrong - traffic is failing to go to a (non-existent) cluster - that is an error I would think. And so, Kiali is actually detecting a non-operational configuration (even though it is in the out-of-box demo profile) - so it is legitimate to flag this.

@mtho11 try to install using Istio's "default" profile (and maybe also use `--set kiali.enabled=true` to install Kiali in that default profile). The "default" profile should not have all the bells and whistles - it is a more stripped down, default install of Istio. See if THAT shows any errors.

**Comment by jshaughn** [comment]
+1, it seems to be a real config issue, even if it's intentional due to partial configuration being defined.   @mtho11 I think we can close this unless you think a FAQ is needed for this issue.

**Comment by mtho11** [comment]
Thanks to @xeviknal explanation, I'm fine with closing this.
