### ISSUE TITLE
when not told what kiali image version to install, operator should use a good default

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#2666]
epic: https://github.com/kiali/kiali/issues/2618

Right now, when the operator is not told what Kiali image version to use for the "default" playbook, it will create a Kiali Deployment whose container pulls in the same version tag as that of the operator itself. In other words, the Kiali that is installed will be the same version as the operator. This is defined in `playbooks/default-supported-images.yml`:
```
default: {"image_name": "quay.io/kiali/kiali", "image_version": "operator_version"}
```

`operator_version` tells the operator to use its own version as the default image for Kiali.

This used to work perfect fine because in the past, each operator was released in lock step with Kiali (so Kiali v1.0 was released with Operator v1.0, Kiali v.15 was released with Operator v1.15) - so there was always a one-to-one mapping.

That is not the case anymore.

So what is a good default?

One option is to use the major.minor version. We do not have this as a feature yet, it would need to be implemented. But the idea is that if the operator is v1.15.8, it can be told to install Kiali v1.15 (no patch version, just using major.minor). Note that quay.io already has these major.minor (with no patch) images (e.g. there is a v1.15 image that is the same as the latest Kiali patch version - say, 1.15.2). If the operator installs Kiali with major.minor tag (v1.15) that would give the user an up-to-date Kiali v1.15. However! Even that isn't really right because the operator version does not even have to be associated with a specific minor version of Kiali (we could release operator 1.18, 1.19, 1.20, 2.0, then 3.0, but still be releasing Kiali on the 1.x stream that doesn't match the operator even at the minor version level. The operator versioning is independent of Kiali).

So the thought is we go back to how we did it before many moons ago - the default is the latest release as found on github (`lastrelease`). So the operator will query github and find out what the version is that corresponds to the latest release of Kiali - that version will be the one that the operator installs.

So I think the easiest change to make here is:
```
default: {"image_name": "quay.io/kiali/kiali", "image_version": "lastrelease"}
```

This default can be overridden by the user if the user simply supplies his own "deployment.image_version" value in the Kiali CR, as usual (this has always been a feature).

**Comment by jshaughn** [comment]
Note that this "last release" approach is OK for now, but I never really liked this approach.  The problem is that the most recent github release can jump from latest upstream like 1.17.0 to a patch release like 1.0.10.   So a user really has no idea what they will end up with.   I realize the user can say what they want explicitly, but for me a better default would be the latest upstream release.  I'm not sure if that's doable.  Can you specify a major version and get the highest min.patch for that major?

**Comment by jmazzitelli** [comment]
> The problem is that the most recent github release can jump from latest upstream like 1.17.0 to a patch release like 1.0.10. So a user really has no idea what they will end up with. I realize the user can say what they want explicitly, but for me a better default would be the latest upstream release. I'm not sure if that's doable.

It is doable and how we have been doing it for a long time :) It USED TO BE what you said you do not like, but we fixed that a while ago - we sort the list of releases and use the highest one.

So what you want, is what we have :)

**Comment by jmazzitelli** [comment]
For the record, do this and you'll see (this is essentially what the code does now):

```
curl -s https://api.github.com/repos/kiali/kiali-operator/releases | grep  "tag_name" | sed -e 's/.*://' -e 's/ *"//' -e 's/",//' | grep -v "snapshot" |  sort -t "." -k 1.2g,1 -k 2g,2 -k 3g | tail -n 1
```

Notice the `sort`.

**Comment by jshaughn** [comment]
Oh, cool.  we smart is.
