### ISSUE TITLE
Graph Replay Date/time field getting cut-off

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#2668]
**General remarks**
The Graph Replay Date/time field getting cut-off by left nav bar:

![Kiali_Console_and_ossm_-_3min53_mp4_-_Google_Drive_and_fish__Users_mithomps_projects_kiali-ui](https://user-images.githubusercontent.com/1312165/79470048-cb02fc00-7fb5-11ea-9c03-a9a45494642c.png)

**Comment by lucasponce** [comment]
It seems fixed
![image](https://user-images.githubusercontent.com/1662329/107651499-dc716f00-6c7f-11eb-8339-31e1432a604c.png)
