### ISSUE TITLE
Kiali fails if Telemetry V1 is used with Istio 1.5+

### ISSUE THREAD

**Issue by jshaughn** [kiali/kiali#2669]
Istio 1.5 introduced istiod and Telemetry V2 (aka "mixerless" telemetry).  Kiali supports V2 telemetry for Istio v1.5.  Kiali supports V1 or V2 telemetry in v1.4.  But it no longer supports V1 telemetry for Istio 1.5+ users, and this is a problem as V1 telemetry, no longer the default, is still configurable and potentially necessary for users using helm install (as I understand things).

The reason for this is that we based on a version check of istio we now default to using the new "canonical" fields in the metrics, but they don't exist in Telemetry V1.  We need to improve our check to be based on the Telemetry version, not the product version.  Or, make this configurable in Kiali (i.e. set Telemetry version in CR, defaulting the correct way based on istio version).

cc @seeruk

**Comment by jshaughn** [comment]
The problem here relates back to the work to support the new "canonical" fields in V2 telemetry, introduced in v1.5 (see https://github.com/kiali/kiali/issues/2276).   To support these fields we needed a way to know they were supported.   There is no easy way to query Istio API to know which version of telemetry is being run.  So, the solution was to query the Istio version via the API, and if the version is >= 1.5 then use the canonical fields.  The problem results from the fact that Istio did not provide backward compatibility for V1 telemetry, the canonical fields don't exist.

Although not the default, V1 telemetry can be configured in V1.5 (scheduled to be fully removed in Istio 1.7).  So, the version check is insufficient.  It means only that the canonical fields will exist if V2 telemetry is being used.

As mentioned above, there is no way [afaik] to query Istio to explicitly determine the telemetry version.  As such I see two ways of doing this, we could query prometheus for a sample time-series and check for the presence of the canonical fields.  Or, we could add Kiali config to specify the telemetry version (it would default to V1 for istio < v1.5, otherwise V2.

I think for cleanliness I'm leaning towards the config change.  Most users would use the default.  The time-series approach requires a special prom-query, and may not be deterministic if there is not yet any traffic, or may have a corner case in an upgrade scenario.

**Comment by israel-hdez** [comment]
@jshaughn I haven't moved to Istio 1.5, so I cannot see how telemetry v2 is setup.
What I see from Istio docs is that Telemetry V2 has a very different implementation and also is less customizable. Even when I never customized Istio metrics, I think it's a missable feature. Telemetry V2 is also configurable (see https://github.com/istio/istio/wiki/Configurable-V2-Metrics), but that is done in a very different way.

So, I think we can actually detect presence of Telemetry V1 vs V2. Telemetry V1 has a [configuration model](https://istio.io/docs/reference/config/policy-and-telemetry/mixer-overview/#configuration-model). In my Istio 1.4 installation I see these related Istio CRDs:

```bash
$ oc get crds -L app | grep mixer   
adapters.config.istio.io                                    2020-04-17T14:42:57Z   mixer
attributemanifests.config.istio.io                          2020-04-17T14:42:57Z   mixer
handlers.config.istio.io                                    2020-04-17T14:42:59Z   mixer
httpapispecbindings.config.istio.io                         2020-04-17T14:42:59Z   istio-mixer
httpapispecs.config.istio.io                                2020-04-17T14:42:59Z   istio-mixer
instances.config.istio.io                                   2020-04-17T14:42:59Z   mixer
quotaspecbindings.config.istio.io                           2020-04-17T14:43:00Z   istio-mixer
quotaspecs.config.istio.io                                  2020-04-17T14:43:00Z   istio-mixer
rbacconfigs.rbac.istio.io                                   2020-04-17T14:43:00Z   mixer
rules.config.istio.io                                       2020-04-17T14:43:01Z   mixer
servicerolebindings.rbac.istio.io                           2020-04-17T14:43:01Z   mixer
serviceroles.rbac.istio.io                                  2020-04-17T14:43:01Z   mixer
templates.config.istio.io                                   2020-04-17T14:43:02Z   mixer
```

The CRDs related to the config model are handlers, instances and rules. I bet these three CRDs are absent if you use Telemetry V2. This may be another idea to check what Telemetry is being used. If this is not suitable, I'm OK with adding a Kiali config to avoid doing an automated wrong choice :-)

**Comment by jmazzitelli** [comment]
I agree with @israel-hdez that that is how you should detect this. Don't look at istio version, look for a specific CRD or object that exists in v1 but not in v2... looks like edgar has a bead on some of these to look for.

**Comment by jshaughn** [comment]
@jmazzitelli @israel-hdez Are you sure the V2 CRDs won't exist if they configure V1 telemetry using V1.5?  They would be there at install because V2 is the default.  They would then have to go away when configuring for mixer.  In short, if V1 and V2 CRDs exist at the same time then this approach won't work.

**Comment by jmazzitelli** [comment]
> I bet these three CRDs are absent if you use Telemetry V2.

I was basing my comment on that comment from @israel-hdez ... it sounds like there may be some CRDs that are NOT present when using telemetry V2 but ARE present when using telemetry V1. We just need to research this and get a solid answer if that is true or not. Ask folks like @douglas-reid - he might know.

**Comment by jshaughn** [comment]
Although this may be a cleaner solution I honestly don't know if it's easier for us, especially if the CRD solution has any chance of being vague.  Mixer is deprecated and honestly, I just want a simple solution until we can get rid of this use case completely.  Maybe I could just look for mixer, it has to exist for v1 and it should not be there for v2.

**Comment by israel-hdez** [comment]
> Maybe I could just look for mixer, it has to exist for v1 and it should not be there for v2.

Yes, I think this is also a good way to detect it. It also goes inline with Mazz idea about checking for something present for one version but not for the other.

**Comment by jotak** [comment]
> Maybe I could just look for mixer, it has to exist for v1 and it should not be there for v2.

Hmm, but how does mixer look like when active in istio 1.5? Isn't it something that is packed in the all-in-one monolith istiod?

**Comment by seeruk** [comment]
> > Maybe I could just look for mixer, it has to exist for v1 and it should not be there for v2.
> 
> Hmm, but how does mixer look like when active in istio 1.5? Isn't it something that is packed in the all-in-one monolith istiod?

This is the crux of the issue - you can be running Istio 1.5 without using istiod (as I am). If you install Istio with Helm, you have no choice. There's no choice to use Telemetry V2, and no choice to use istiod.

**Comment by jotak** [comment]
Ok, good to know, so looking for a `mixer` service should be good

**Comment by jotak** [comment]
@jshaughn , this should be coordinated with @xeviknal , see here https://github.com/kiali/kiali/pull/2598#discussion_r411462279 : I think what Xavi is doing can be the single source of truth about what "kind" of istio is installed

**Comment by israel-hdez** [comment]
CRDs are present even if Telemetry V2 is on.
I'll determine if the feature is on/off by querying Istio's ConfigMap.

**Comment by xeviknal** [comment]
@jotak yes, I agree. We should find out which are the extra deployments that imply the fact of enabling telemetry v1 into Istio 1.5 installation. Knowing that, we might refine  https://github.com/kiali/kiali/pull/2598 including the call to this method and check health of needed components.
