### ISSUE TITLE
For Login Strategy : token , not able to login using any other token other than admin token

### ISSUE THREAD

**Issue by forumsheth15** [kiali/kiali#2678]
I have installed kiali over istio using this https://kiali.io/documentation/getting-started/#_install_kiali_latest with login strategy as token.
After deployment able to login using admin token but when created a new service account and applied rbac by giving all access, still not able to login using that service account token.
Do I need to make any other changes?

**Comment by israel-hdez** [comment]
@forumsheth15 Please read issue #2569, starting at comment: https://github.com/kiali/kiali/pull/2569#issuecomment-605130293. It's probably the same issue as yours.

**Comment by israel-hdez** [comment]
Closing as `stale`
