### ISSUE TITLE
Spinner doesn't spin

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#2679]
The spinner in Kiali top header doesn't rotate, it stays frozen while backend queries are being loaded.

Problem was seen both with Chrome and Firefox. I think it has been broken for a while.

**Comment by mtho11** [comment]
@jotak I see it spinning for me (on latest master) in Chrome 80.0.3987.163

**Comment by mtho11** [comment]
This is interesting I just did a Chrome update to version: 81.0.4044.122 and now it is not spinning!

However, switching to Firefox version: 76.0b4 (64-bit) it is spinning.

**Comment by jotak** [comment]
This is weird.. @xeviknal noticed it as well when I asked him to check. My Firefox version is 75, Chrome 81.

**Comment by xeviknal** [comment]
Just tried again, and not spinning either.

Chrome: Version 75.0.3770.142 (Official Build) (64-bit)
Firefox Quantum - 67.0.4 (64-bit)

Fedora 30

**Comment by hhovsepy** [comment]
Reproduced on:
FF 75.0 (64-bit)
Chrome Version 81.0.4044.122 (Official Build) (64-bit)
Fedora 31 latest updates.

**Comment by jotak** [comment]
By the way shouldn't we use patternfly's spinner?
https://www.patternfly.org/v4/documentation/core/components/spinner

(ping @mtho11 @aljesusg @lwrigh )

**Comment by mtho11** [comment]
good catch @jotak. I didn't see the part where it was experimental...

**Comment by jotak** [comment]
@mtho11 no actually the experimental one is not the one we use, it's a new one

**Comment by lucasponce** [comment]
I'm reviewing this one. It was pending from Sprint 39, put in the backlog and without clear owner.
@jotak I put it this on you if you can take a look.
It sounds pure UI component issue I think.

**Comment by jotak** [comment]
I'll try with the PF experimental spinner
