### ISSUE TITLE
[Next PF Release] Button prop isActive will be removed

### ISSUE THREAD

**Issue by aljesusg** [kiali/kiali#2683]
# When ?

Release June

# What happen?

PF team are considering removing that as it was never intended to be used to note that something is “active,” and instead was just to mimic the :active pseudo class in CSS

# What component?

The component Button use a isActive method that change some style to the inside components like the icons that we have in the Overview Page (https://github.com/kiali/kiali-ui/blob/master/src/pages/Overview/OverviewToolbar.tsx#L170-L197)

```ts
   <Button
      onClick={() => this.props.setDisplayMode(OverviewDisplayMode.EXPAND)}
      variant="plain"
      isActive={this.props.displayMode === OverviewDisplayMode.EXPAND}
      style={{ padding: '0 4px 0 4px' }}
    >
       <ThLargeIcon />
    </Button>
```

## Examples:
https://github.com/kiali/kiali-ui/blob/master/src/components/Time/Replay.tsx#L406-L422
Overview view buttons
...

# Solution

it be possible to change the component to apply a custom class when the user clicks on it (ie, className="button--isActive") and apply our own styling - something like  .button--isActive { color: var(--pf-global--Color--100);} 

or in style and add the css if is active

PF Issue: https://github.com/patternfly/patternfly/issues/2601

**Comment by lucasponce** [comment]
This is valid, I've created global one for PF migrations
#4260

I'll close this, as probably it will be part of a subtask of the generic one.
