### ISSUE TITLE
[Next PF Release] New IstioConfig Page use TextInputBase instead TextInput

### ISSUE THREAD

**Issue by aljesusg** [kiali/kiali#2684]
# What?

After upgrade to release 2020.04 we found an issue related with the tables when they render a TextInput inside his row. The use lost the focus when try to change the value.

See codeandbox => https://codesandbox.io/s/texinput-table-ggx1l?file=/index.js

# What happen?

Using TextInputBase causes typing in the input to only update TextInputBase inside the <Table>. However, using React.forwardRef on TextInputBase causes the whole <RowWrapper> (and maybe even higher up the tree?) to rerender, and so the <input> loses focus. I assume this has to do internally with how React implements forwardRef when diff-checking. However, the fault is in our Table since <div>{this.rows()[0].cells}</div> works just fine.

# Solution that we did

Change TextInput by TextInputBase

The key implementation takeaway for TextInputBase vs TextInput is that TextInputBase is a normal React Component (that is typeof TextInputBase === 'function'), while TextInput is a special React object (that is typeof TextInput === 'object') with a .render prop.

# Docs/issues
Issue Opened in PF4 and comments: https://github.com/patternfly/patternfly-react/issues/4072

# TODO

Replace the TextInputBase by TextInput again

**Comment by lucasponce** [comment]
This is valid, I've created global one for PF migrations 
https://github.com/kiali/kiali/issues/2684

I'll close this, as probably it will be part of a subtask of the generic one.
