### ISSUE TITLE
Message center 'Show Details' notification text extends beyond notification box

### ISSUE THREAD

**Issue by skondkar** [kiali/kiali#2685]
Message center notifications when have a long text, the 'Show Details' link shows the text extending beyond the notification box

Version:
Happens on Kiali master.

Kiali UI:  1.17.0 (74ffde1b2997f72726e3be3d02ee46c9096b566f)
Kiali Server:  v1.17.0-SNAPSHOT (b5827b8de5033ceb49ef88bbdf11ffd852a887ea)

Steps to reproduce:

1-Navigate to 'Istio Config'->Actions->Create New Istio Config
2-Select Istio Resource 'Sidecar', Enter some name
3-Enter some invalid FQDN host like example.com
4-Click on 'Add Egress Host'
5-Click Create
6-There will be a message 'Could not create Istio Sidecar object'
7-Open message center and click 'Show Details' link of the message.

![Screenshot-MessageCenter-Text](https://user-images.githubusercontent.com/6614472/79976117-bf359f00-84b9-11ea-989b-8c5746fcaa84.png)

**Comment by lucasponce** [comment]
Ok, I took #2635 which is related to styles.
I'm going to take a look at it.
