### ISSUE TITLE
Kiali's brand repositioning 

### ISSUE THREAD

**Issue by maltron** [kiali/kiali#2689]
Since its inception, Kiali started as a simple visualization tool for Istio with a moto "Service Mesh Observability and Configuration" and evolve into something much more. 

As a today, Kiali is literally Istio's frontend and all its capabilities spans from Observability, Configuration, Validations, Tracing, Metrics and much more. 

In order to easy communicate and position Kiali across different teams and explain what Kiali is all about, I would like to propose a change in how we communicate on Kiali's WebSite:

Some ideas that comes to my mind would be:

Kiali: Istio's Console 
Kiali: Service Mesh Visualization 
Kiali: Service Mesh Management Dashboard

Of course, I'm open to ideas

**Comment by lucasponce** [comment]
I know it can be open to several options - all correct -.

Personally I like the "Kiali: Service Mesh Management Dashboard".

In a second line it can be added "based on Istio" but as it covers other services meshes (Maistra, technically it's another service mesh based on Istio, but it's not Istio purely speaking) it sounds good to me.
