### ISSUE TITLE
Istio workloads showing 'Missing Version Label'

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#2690]
**Is your feature request related to a problem? Please describe.**
This is technically correct about the Istio workloads not having a versions label. 

**Describe the solution you'd like**
I don't think we should show the 'Missing version label' for these Istio workloads because it is not relevant to these particular workloads.

![Kiali_Console](https://user-images.githubusercontent.com/1312165/80034364-2d229c00-84a3-11ea-94dd-ff6de6740bec.png)

**Comment by jshaughn** [comment]
Just a thought, not having the 'version' label may be OK if you instead supply  app.kubernetes.io/version.  Telemetry V2 In 1.5+now handles both to set canonical_revision in the metrics.

**Comment by jshaughn** [comment]
I'd prefer not to special case control-plane workloads.
