### ISSUE TITLE
Create New AuthPolicies - allow_all and deny_all are not Istio recommended ones

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#2695]
According to Istio documentation, allow_all and deny_all AuthorizationPolicies should have:
"apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-all
  namespace: default
spec:
  action: ALLOW
  rules:
  - {}"

and 
"apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: deny-all
  namespace: admin
spec:
  {}"

Described here: https://istio.io/docs/concepts/security/#allow-all-and-default-deny-all-authorization-policies

But in fact they are:
![Screenshot from 2020-04-24 14-13-14](https://user-images.githubusercontent.com/604313/80211524-2d06d580-8636-11ea-992a-6bc0051674c9.png)
![Screenshot from 2020-04-24 14-13-33](https://user-images.githubusercontent.com/604313/80211525-2d9f6c00-8636-11ea-990c-1d9350e42ef7.png)

**Comment by lucasponce** [comment]
Thanks @hhovsepy good one. 
Yes, those are flipped.
Perhaps I introduced the regression in my last commit.
I'll fix it.

**Comment by lucasponce** [comment]
Mmm, side question, I think objects are created correctly but problem is that when reading the raw yaml from the backend, it tried to populated the spec as default.

Can you confirm if that's the case ?

**Comment by hhovsepy** [comment]
With deny-all, yes, the yaml file itself is correct, as described in Istio. The difference is only in Kiali UI, which is acceptable.
But the allow-all does not contain "action: ALLOW" which seems is not default "ALLOW":

`oc get AuthorizationPolicy allowall -n bookinfo -o yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  creationTimestamp: "2020-04-24T11:52:56Z"
  generation: 1
  labels:
    kiali_wizard: AuthorizationPolicy
  name: allowall
  namespace: bookinfo
  resourceVersion: "1648926"
  selfLink: /apis/security.istio.io/v1beta1/namespaces/bookinfo/authorizationpolicies/allowall
  uid: 32951532-5c2d-4217-96c9-6717033cebbb
spec:
  rules:
  - {}`
