### ISSUE TITLE
VirtualService Validation Errors For Partially-Qualified Gateway Names

### ISSUE THREAD

**Issue by armsnyder** [kiali/kiali#2698]
**Describe the bug**

The VirtualService validation in Kiali generates a false positive error `VirtualService is pointing to a non-existent gateway` when the VirtualService configuration includes a partially-qualified gateway name. This is a common way of specifying a gateway in the Istio documentation.

This VirtualService configuration has the validation error:

<img width="453" alt="Screen Shot 2020-04-24 at 2 26 00 PM" src="https://user-images.githubusercontent.com/9969202/80258790-eb2b5e80-8638-11ea-97db-c70a036c2760.png">

This one has no validation errors:

<img width="431" alt="Screen Shot 2020-04-24 at 2 26 38 PM" src="https://user-images.githubusercontent.com/9969202/80258805-f3839980-8638-11ea-89fe-0ea91a4adab2.png">

But they should be equivalent, since both are legal ways of specifying the gateway.

There was a similar issue with this validation error in the past, but the fix only corrected the error for a fully-qualified gateway reference and did not capture this use case. https://github.com/kiali/kiali/issues/767

**Versions used**
Kiali: v1.9.1 (2431f9b8844202e27ec1c92f404fe7485253ffec)
Istio: 1.4.6
Kubernetes flavour and version: EKS v1.14.9

**To Reproduce**
1. Create a Gateway called `gateway` in namespace `foo`.
1. Create a Service and VirtualService in namespace `bar`, referencing the gateway as `gateway.foo`.

**Expected behavior**
Kiali should treat a gateway reference in the form `<name>.<namespace>` as valid.

**Comment by lucasponce** [comment]
Thanks @armsnyder.

This issue sounds familiar, @xeviknal would you mind to check if we worked on this in one of the following versions ?

Adam,

did you check if one of the following Kiali versions resolves this ? kiali 1.9.1 sounds old as we are releasing 1.17.

In any case, probably Xavi will confirm.

**Comment by xeviknal** [comment]
@armsnyder I can reproduce the error you described. 

I think there are two problems here:

1. The way to refer to Gateways into a VirtualService is using the following nomenclature (extracted from Istio documentation):

> The names of gateways and sidecars that should apply these routes. Gateways in other namespaces may be referred to by `<gateway namespace>/<gateway name>;`

I see you mentioned that FQDN and two part domains are legit ways to refer to gateways though. It might work, however you should be aware that this might be unsupported on the future. Or, have you seen in the documentation any reference to this notation?

If I am not wrong, this notation was allowed in Istio 1.0 but started to officially use the / notation on Istio 1.1.

2. You are right, Kiali should be consistent and remove the false positive. 

One extra question popped into my head: Should we warn people that they are using an outdated nomenclature for referencing gateways?
