### ISSUE TITLE
Align styles in Health and Configuration Tooltips

### ISSUE THREAD

**Issue by aljesusg** [kiali/kiali#2706]
# Tooltips in list are not with the same style 

![tooltip2](https://user-images.githubusercontent.com/3019213/80475706-92fea000-8949-11ea-8f30-3cd554e71d48.png) 

![tooltip1](https://user-images.githubusercontent.com/3019213/80475699-8ed28280-8949-11ea-88b6-a9e172ec0bba.png)

**Comment by lucasponce** [comment]
I can take this one as I'm doing some CSS sync. 
This one is related, too.

**Comment by lucasponce** [comment]
I think health can be changed to same CSS style used in tooltips and also in IstioStatus.
The latest uses also similar icons:
![image](https://user-images.githubusercontent.com/1662329/80728050-c76b8b00-8b06-11ea-813f-1ea617443be6.png)

**Comment by aljesusg** [comment]
We should merge both components to have only one...to avoid different styles

**Comment by lucasponce** [comment]
> We should merge both components to have only one...to avoid different styles

Not yet. That was exactly one of the reasons of multiple problems in CSS styles.

Components that we think we are going to re-use but at the end they have/need different styles and a small CSS change in one of them creates a non-desired style change in other.

I'm going to avoid early optimizations on the UI until we identify clearse these situations.
Meanwhile a little of duplication is safe.
