### ISSUE TITLE
Link from traces to workload logs can be wrong

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#2712]
In traces view, links are generated from spans to workload logs. See screenshot:

![Capture d’écran de 2020-04-29 12-11-32](https://user-images.githubusercontent.com/2153442/80585024-e852b400-8a12-11ea-9cf1-b2c018f1cf32.png)

Here my workload is "ai-visitors" and the whole `node_id` is `sidecar~172.17.0.22~ai-visitors-779956ddf8-s78gr.default~default.svc.cluster.local`

I can see the regexp that we use makes a wrong assumption that the workload name has to include version in the form of "v" + numbers.

**Comment by jotak** [comment]
cc @aljesusg

**Comment by aljesusg** [comment]
Yes, we need to improve the regex for all the use cases we should assume or check that could be a -vX or not (like your case). This was done for the bookinfo example. I need to investigate mor about how to check correctly this... Thanks @jotak

**Comment by jotak** [comment]
I think `/^([a-z0-9-\.]+)-[a-z0-9]+-[a-z0-9]+\.[a-z0-9-]+$/` would be a good regex, if we first split on `~`. Kube accepts alphanumeric characters + `.` and `-` in usual names, so that should work in general.

We could add a couple of unit tests on that.

**Comment by aljesusg** [comment]
I am thinking about provide this information from backend like a new field in the object and check if the workload exist and have this logic in kiali/kiali

**Comment by lucasponce** [comment]
@jotak @aljesusg reading the comments I put this on Alberto and moved to the Sprint 40.
