### ISSUE TITLE
Test randomly fails on CI

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#2718]
There's a non-deterministic test in `client_factory_test.go` that sometimes fail. Most of the time it seems ok, so it hasn't harmed so much and would be low priority at first glance... but it would be nice to see if there's a better way to write that.

Incriminated code line 54 I think:

```go
time.Sleep(time.Millisecond * 100)
```

Example of failure: https://travis-ci.org/github/kiali/kiali/jobs/681367806

**Comment by jshaughn** [comment]
Sleep in tests is always scary, especially when the sleeps are so short, I see a 25ms, 100ms sleeps in there.  Remember that those are minimums, not guarantees.  Most likely we need to use some more tolerant sleep durations.

**Comment by jotak** [comment]
@jshaughn or with some retries mechanism, so that it's still fast on our machines

**Comment by lucasponce** [comment]
I've removed the "bug" label, it's not compatible with the "good first issue" :) just to avoid that something is broken on purpose.

But +1, this one can be a good starter for new comer to get familiar with the codebase and starting to send minor PRs.

**Comment by RammasEchor** [comment]
Hi! I'm new to kiali, and I would love to work on this.

**Comment by lucasponce** [comment]
I think this issue seems outdated.
