### ISSUE TITLE
Traces duplication on tooltip

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#2720]
I saw this in https://github.com/kiali/kiali/issues/1778 but it happens in master.

I have locally (out of the cluster) a master branch of backend/frontend, querying a bookinfo example.

How to reproduce:
1.- Go to applications > productpage
2.- Go to Outbound Metrics tab
3.- Enable spans
4.- Click on a span to jump into tracing page.

![image](https://user-images.githubusercontent.com/1662329/80718497-82415c00-8afa-11ea-9b4f-be4bb2e837ca.png)
![image](https://user-images.githubusercontent.com/1662329/80718516-88cfd380-8afa-11ea-8e4c-5b36b3bcd335.png)

Note, if user goes directly through Services without jumping from application, then tracing page works as expected:
![image](https://user-images.githubusercontent.com/1662329/80718604-a7ce6580-8afa-11ea-9e8e-5d65891a52d0.png)

So not sure why, it deserves some investigation on it.

Probably it's unrelated to work done for #1778.

**Comment by jotak** [comment]
@lucasponce do you see it for every spans (or let's say, a lot of them?)
I've been able to see this as well but it happens only for a small proportion, something like 1-5%.
I'm still investigating...

**Comment by lucasponce** [comment]
> @lucasponce do you see it for every spans (or let's say, a lot of them?)

In the example I used I was seeing them in all of the spams, but as commented, in the use case of jumping from the metrics page -> tracing.

Entering directly in the tracing page from the service details didn't show (at least in a first attempt) this duplication.

I can try to repeat it in other moment but I didn't perform anything special, just bookinfo with a watcher on productpage from the gateway.

**Comment by jotak** [comment]
I started to look at it, sometimes traces are fetched twice. Reviewing the fetch process brings me to consider this task as well, which anyway we need to do rather sooner than later: https://github.com/kiali/kiali/issues/2732 . So I'm going to do it and check that it's fixing this traces duplication issue at the same time.
