### ISSUE TITLE
gracefully ignore missing Policy CRD

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#2727]
Upstream Istio removed the Policy CRD in 1.6. Kiali expects it to exist. Kiali should assume this is "optional" so it supports older versions of Istio but yet won't spit out errors if its missing.

See: https://github.com/istio/istio/issues/23484

**Comment by lucasponce** [comment]
@xeviknal I put this on you, but let me know if you want me to take it.

**Comment by xeviknal** [comment]
The way to properly fix this bug is to cover https://github.com/kiali/kiali/issues/2520. I think that covering the first 3 bullets, could be a good start. I can approach them.

**Comment by xeviknal** [comment]
That error message is not displayed anymore. Fixed in #2738
