### ISSUE TITLE
Links to grafana dashboards from overview page

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#2731]
Currently, Grafana dashboards are assumed to be per service/workload, hence links lies in the service/workload details (metrics) pages.

However some dashboards are more general / mesh-wide. So links to these should go under the Overview page. The same customizable configuration can be used for them.

With the default config, we should have a link to the Istio Mesh Dashboard:
![Capture d’écran de 2020-04-30 09-21-59](https://user-images.githubusercontent.com/2153442/81041009-0013b780-8ead-11ea-9be2-6eeee491d949.png)

**Comment by lucasponce** [comment]
This is valid.
If Kiali has enabled a public URL to grafana, a link to the Istio Mesh Dashboard can complement the Kiali Overview page.
