### ISSUE TITLE
Istio 1.6.0-beta.0 - stuck in login page - strategy method missing

### ISSUE THREAD

**Issue by xeviknal** [kiali/kiali#2733]
I've just installed the `istio-1.6.0-beta.0` and I got stuck into the pre-login page. Nothing happened after clicking to Log in button.

![Screenshot of Kiali Console (53)](https://user-images.githubusercontent.com/613814/81048707-1cb7eb80-8ebd-11ea-8d37-9e0b0081661d.png)

Installation steps:

```
./k8s-minikube.sh up -kdr kvm2 -v
cd istio-1.6.0-beta.0
export PATH=~/code/istio-lab/istio-1.6.0-beta.0/bin:$PATH
istioctl manifest apply --set profile=demo
Detected that your cluster does not support third party JWT authentication. Falling back to less secure first party JWT. See https://istio.io/docs/ops/best-practices/security/#configure-third-party-service-account-tokens for details.
✔ Component Base installed                                                                                                                                                                            
✔ Component Pilot installed                                                                                                                                                                           
✔ Component EgressGateways installed                                                                                                                                                                  
✔ Component IngressGateways installed                                                                                                                                                                 
✔ Component AddonComponents installed                                                                                                                                                                 
✔ Installation complete
```

The config map has the strategy method missing:

![strategy-missing](https://user-images.githubusercontent.com/613814/81048800-4b35c680-8ebd-11ea-8a8b-0e12b11ff6df.png)

Adding the login strategy makes everything back to normal.

cc/ @jmazzitelli @lucasponce 
If it's true, I think it should be a blocker

**Comment by lucasponce** [comment]
Can we add it to the epic for Istio 1.6 ?

https://github.com/kiali/kiali/issues/2226

**Comment by jmazzitelli** [comment]
This was already reported in Istio and John Howard should have already fixed it. I'll search for the istio issue and report back here.

**Comment by jmazzitelli** [comment]
See:

- https://github.com/istio/istio/issues/23199
- https://github.com/istio/istio/pull/23320
- https://github.com/istio/istio/pull/23325

**Comment by xeviknal** [comment]
Fixed on Istio master:
istio/istio#23199
istio/istio#23320
istio/istio#23325
