### ISSUE TITLE
Labels filtering: "all of" / "any of" switch

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#2734]
Currently here's how labels filtering looks like:
![Capture d’écran de 2020-05-05 11-05-47](https://user-images.githubusercontent.com/2153442/81051743-93a3b300-8ec2-11ea-9426-c9d30fa627d7.png)

It's not obvious what is the boolean operation performed with filter on multiple labels: OR or AND ? So, the screenshot above shows it's a OR. Which is good to widen the search space but not to narrow it. Perhaps we could show a small switch in the UI, showing "all of" / "any of", to leave this choice to the user?

**Comment by aljesusg** [comment]
about this. We were talking about if you set version:v1 and after version:v2 the second will be replace the first one.(This now is not replacing it, I want to do it now) 

Now if you set version:v2,v3 this is going to look for version with v2 or v3 so in this case.

So example:

app:details version:v2:v3   

AND => is it going to apply if label (app:details && (version:v2 || version:v3))
OR => is it going to apply if label (app:details || (version:v2 || version:v3))

-------------------------------
AND => is it going to apply if label (app:details && (version:v2 && version:v3))
OR => Same case

The point is how to deal with the multiple values

**Comment by jotak** [comment]
I think what you put first is correct, because indeed with multiple values per label the "AND' doesn't make sense, a label can't have several values.

So, the AND/OR switch would only concern logic between different labels ; but within a label, different values can only use OR; would it make sense?

**Comment by aljesusg** [comment]
Yes It makes more sense for me. I am going to do it like this and overwrite the label if you set a new value.

**Comment by aljesusg** [comment]
hey @jotak i can't see another way to apply to the filters a and/or operation than create a new filter for this :(.

I think that we should store this in query params too
