### ISSUE TITLE
Labels filtering: click on labels to filter

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#2735]
Currently here's how labels filtering looks like:
![Capture d’écran de 2020-05-05 11-05-47](https://user-images.githubusercontent.com/2153442/81051743-93a3b300-8ec2-11ea-9426-c9d30fa627d7.png)

It would be really nice if one could just click on a label from the list to automatically add it to the filters. If you ever used Kibana for instance, it's a simple yet powerful way to navigate in data & refine searches.

**Comment by aljesusg** [comment]
@jotak I was thinking about this...I don't know how to perform the updateFilters/addfilter of the StatefulFilter Component from the renderer of our VirtualList :) I need to investigate more if we don't want to reorganize the code
