### ISSUE TITLE
Possible whitespace alignment issues on Details pages

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#2744]
**Is your feature request related to a problem? Please describe.**
A picture is worth 1000 words here:
![Kiali_Console_and_3scale_-_Istio_Integration_using_Kiali_-_YouTube](https://user-images.githubusercontent.com/1312165/81238831-e743f880-8fb7-11ea-85d3-95c44629a8dc.png)

Maybe easier to see without the red lines in the way:
![Kiali_Console_and_3scale_-_Istio_Integration_using_Kiali_-_YouTube](https://user-images.githubusercontent.com/1312165/81239048-8cf76780-8fb8-11ea-8f64-16346626d52a.png)

Some might be valid and some not.

**Comment by lucasponce** [comment]
@mtho11 I can take a look.
The tabs and header controls are aligned with other pages, and I'd prefer to not touch them.
But yes, reducing the padding of the main cards containers may work.

**Comment by lucasponce** [comment]
I'm going to take this. It looks part of the whole CSS adjustments we performed this Sprint.
