### ISSUE TITLE
Allow running as non-root user with web root specified

### ISSUE THREAD

**Issue by nhinds** [kiali/kiali#2745]
**Is your feature request related to a problem? Please describe.**
Kiali fails to run as a non-root user (specifying e.g. `runAsUser: 1001` in its k8s `securityContext`) when it has a web root specified. It seems to require write access to its deploy directory `/opt/kiali/console` in order to rewrite index.html and env.js: https://github.com/kiali/kiali/blob/5a8587c1adfd2bfd0d6e7476cf34ed84b6686661/kiali.go#L94

When launching as non-root, errors are logged but Kiali ignores them and continues to start. Loading Kiali in the browser then returns 404s.
```
I0507 00:10:51.469287       1 kiali.go:286] Updating base URL in index.html with [/kiali]
E0507 00:10:51.469404       1 kiali.go:312] File I/O error [open /opt/kiali/console/index.html: permission denied]
I0507 00:10:51.469430       1 kiali.go:267] Generating env.js from config
E0507 00:10:51.469464       1 kiali.go:312] File I/O error [open /opt/kiali/console/env.js: permission denied]
```

**Describe the solution you'd like**
Kiali should allow being run as a non-root user. Perhaps by one of the following:
* Running as a non-root user by default, and chowning /opt/kiali to that user in its `Dockerfile`
* Writing `index.html` and `env.js` out to a temporary directory that non-root users have access to, and serving these 2 files from that directory as an overlay
* Serving the modified `index.html` and `env.js` files from memory instead of writing them out to disk and serving them from there

**Describe alternatives you've considered**
For now I'm using `/` as my web root, which appears to stop Kiali from trying to write to disk. This confuses Istio a little (`istioctl dashboard kiali` sends me to `/kiali` and not `/`) but Kiali does appear to work.

**Additional context**
Testing with this container `securityContext`, although if a non-root user is created in the Dockerfile then the `runAsUser` and `runAsGroup` IDs would need to be changed/removed:
```
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        runAsGroup: 1001
        runAsNonRoot: true
        runAsUser: 1001
```

**Comment by israel-hdez** [comment]
@jshaughn This doesn't sound hard to do, in theory. And I agree with @nhinds that Kiali should be capable to run without root privileges. IMHO, Kiali should run by default without root privileges. As it is, it deviates from the best practice about containers running as regular user.

This, probably, should have some priority in the backlog.

**Comment by jshaughn** [comment]
@nhinds , thanks for the issue and the ideas for solving the problem. @israel-hdez , I agree and am adding to the backlog.  If I recall we've had some prior issues around this index.html rewrite w/ custom web root, it wouldbe nice to have a final solution.  I think @jmazzitelli was involved a while back.

**Comment by jmazzitelli** [comment]
We could just chown the files to the non-root user we'd create in the Dockerfile. This shouldn't be hard to change.

**Comment by israel-hdez** [comment]
@nhinds Kiali v1.18.1 now runs under a regular user by default. So, no need to use  `securityContext` anymore.

**Comment by nhinds** [comment]
Thanks!
