### ISSUE TITLE
[istio 1.6] change to version endpoint

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#2754]
It used to be the Istio endpoint to obtain its version comes from istio-pilot, now it comes from istiod.

The new endpoint is: `http://istiod.istio-system:15014/version`

Probably change in the operator is required.

epic: https://github.com/kiali/kiali/issues/2226

**Comment by jmazzitelli** [comment]
I just confirmed that Istio 1.5.2 does have an istio-pilot service with the /version endpoint but its istiod does NOT have an analogous endpoint.

Istio 1.6 will NOT have an istio-pilot service - the version endpoint (on the http-monitoring port - 15014) is now on the istiod service.

The operator could try to figure out what default to set - but it can't even probe those endpoints because the operator may not even be given access to those endpoints (the operator can be installed in a different namespace and thus is not guaranteed access). I guess it can TRY and if it does have access, determine what to use.

Or, we should probably leave this empty and let the Kiali Server itself figure out what to do - the Kiali Server should have access to this endpoint (after all, it needs to call it to get the version string) - so it should try istio-pilot and if that fails try the istiod endpoint. We can still keep the configuration setting in case it needs to be overridden by the user for some reason.

**Comment by jshaughn** [comment]
I think it should try the istiod endpoint first, and then istio-pilot.  istiod will exist going forward, also, i'm afraid what the istio-pilot endpoint may return if both are active is some sort of frankenstien updated end.  I'm glad I tried the about box when we were dorking around...

**Comment by jmazzitelli** [comment]
> it should try

What is "it" - because, as I mentioned, the operator may not even have access because it will be in another namespace most likely.

Can we confirm this istiod and istio-pilot endpoints are always accessible outside their namespaces? If they are, then the operator can do this. If not, we will need another solution.

**Comment by jshaughn** [comment]
@jmazzitelli , @lucasponce has proposed that v1.18 require v1.6 of Istio due to other changes that are hard to handle in a backward compatible way. "Require" may be the wrong word, as I don't think we should crash with 1.4 or 1.5.  But features may not work as expected.  If we go with this approach we may just be able to use the new API and be done with it.

**Comment by jmazzitelli** [comment]
I'm thinking about this more, and I may be "overthinking" this. As it is today, we know the pilot endpoint is accessible even if the operator is in another namespace (obviously - because we work today and the operator is almost always installed in a different namespace). Thus, I have to believe the same will be true of this same endpoint that was integrated into istiod.

So, I think it would be easy enough for the operator to first try the istiod endpoint, if that fails, try the pilot endpoint. If both fail, I'll just have the operator default to something (probably the istiod endpoint) and hope the kiali pod will be able to reach it.

I'll try to code this up in a PR this weekend.

**Comment by jshaughn** [comment]
So if I understand what you're saying, the operator won't actually set the version somewhere, it will set the endpoint to use to determine the version?  What if there is no Kiali operator?  I guess in that's true only when we are packaged with istio upstream, and in that case we just need the packaged version to have the correct endpoint set statically, so for 1.18 we need to set it to the new istiod endpoint.

**Comment by jmazzitelli** [comment]
> I understand what you're saying, the operator won't actually set the version somewhere, it will set the endpoint to use to determine the version?

Yes. It is what we do today, also.



> What if there is no Kiali operator?

What if there is no Kiali operator today? It's the same thing. The user has to configure the ConfigMap appropriate, with the Kiali Server falling back to some hardcoded default. Today, that is the pilot endpoint (so if you create a ConfigMap but don't set this value, Kiali Server will assume the pilot endpoint) : https://github.com/kiali/kiali/blob/v1.18/config/config.go#L332

We should change that default.

Upstream Istio needs to change its default here: https://github.com/istio/istio/blob/master/manifests/charts/istio-telemetry/kiali/templates/configmap.yaml#L36

**Comment by jmazzitelli** [comment]
I created an Istio issue to track the need to update the Kiali configmap over there.

**Comment by jmazzitelli** [comment]
Upstream Istio PR to have its kiali helm chart switch over to the new istiod version endpoint is here: https://github.com/istio/istio/pull/23678

**Comment by jmazzitelli** [comment]
> (so if you create a ConfigMap but don't set this value, Kiali Server will assume the pilot endpoint) : https://github.com/kiali/kiali/blob/v1.18/config/config.go#L332
> 
> We should change that default.

This is now done in this PR: https://github.com/kiali/kiali/pull/2760
