### ISSUE TITLE
Improve documentation for the reduced permissions case

### ISSUE THREAD

**Issue by israel-hdez** [kiali/kiali#2771]
For OpenShift, we have the following section in the website:
https://kiali.io/documentation/getting-started/#_reducing_permissions_in_openshift

While testing kiali/kiali#2743, those instructions weren't enough. Also, looks like that section hasn't been updated in a long time.

The commands on that section still work, but only if you are using "login" strategy, which is not the default strategy for OpenShift. If another login strategy is used, those commands won't work, but may give some idea about what to do.

That section about "Reducing permissions" should be improved to reflect how to setup a reduced permissions scenario depending on the login strategy being used (both for OpenShift and plain Kubernetes).

**Comment by lucasponce** [comment]
@israel-hdez +1 from my side, I have nothing to discuss on it.
I'll put in the backlog.
