### ISSUE TITLE
Overview: Istio config validation inconsistency (Istio 1.6)

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#2773]
Happens on Kiali master with istio 1.6.0.
When Auto mTLS is true.
In Overview page, for namespace 'istio-system', the Istio Config Status is shown as "N/A".
But in fact it is healthy, if you click on list istio config items it shows 1 Healthy config and the rest are N/A.

![Screenshot from 2020-05-13 11-41-00](https://user-images.githubusercontent.com/604313/81797448-19e97600-950f-11ea-9c79-7d2e179055fe.png)
![Screenshot from 2020-05-13 11-41-26](https://user-images.githubusercontent.com/604313/81797450-1bb33980-950f-11ea-8b86-4d5021be3b38.png)

**Comment by xeviknal** [comment]
Confirmed. This happens after the replace of Policies by PeerAuthn. Good catch :)
