### ISSUE TITLE
Metrics page: more details & links from spans

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#2775]
Currently, beside showing spans on the charts, metrics page shows very few details about spans:

![Capture d’écran de 2020-05-13 12-27-28](https://user-images.githubusercontent.com/2153442/81801733-2c66ae00-9515-11ea-890d-7c50414dac11.png)

=> In the tooltip, we can show more: operation name, http.method etc.

Clicking on a span brings us to traces details. Instead, we could show a menu with more navigation offered:

- Show full trace
- Go to parent
- Go to child 1
- ...

“Go to …” leads to the same metrics page but for another service. This would be a way to navigate between metrics pages of different services by following the sequence of a trace.

**Comment by jotak** [comment]
sure, no problem!
I wasn't sure how to handle it though. Something like displaying a menu, like the tippy.js we have in graph, when we click on a span? any idea about that?

**Comment by aljesusg** [comment]
Yes, i am trying to replicate the same that we have in graph, 
onthe other hand I saw a PF4 menu component but it seems taht we need upgrade :(

**Comment by aljesusg** [comment]
After some reseach with victory chart I tried to customize the labelComponent to have this "menu" but we can't do it so...the proposal is

1- Update tippy library to same version patternfly from 3.x to 5.1.2 (Tippy supports 5.X and 6.X now)
2- Create this tippy menu for this issue

**Comment by lucasponce** [comment]
There is a pending issue related to tippy.
In short is complex, https://github.com/kiali/kiali/issues/3583, as tippy is used in several components.

But it can be worth to analyze if it can be bumped and aligned as it will create conflicts sooner than later, but then that should be a different task from this one.

So, if you want to work in that area, I'm ok if you take #3583, but it will require to analyze the others uses to avoid any regression and problem.

If you want to do so, I suggest to move this one to backlog and take the #3583 with that context.

Note, that first part of the task can be to see if it's doable, I'm afraid it can trigger some hidden task like break a component that may require a complete refactoring, before that happens we would like to see if it's worth to do it.

But I'm +1 to spend some cycles on this.

**Comment by aljesusg** [comment]
I am checking and I downloaded the branch for the tippy version that we have, maybe we don't need to upgrade it for this tasks.

on the other hand let me check https://github.com/kiali/kiali/issues/3583 too.

**Comment by aljesusg** [comment]
Closed by https://github.com/kiali/kiali-ui/pull/2096
