### ISSUE TITLE
Correlation dashboard

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#2777]
The idea here is to bring together several relevant signals for troubleshooting / analysis in the same dashboard.

For all signals of a given service/workload/app, a "score" for being potentially relevant is computed, based on trend analysis, by comparing short-term data to a longer-term baseline (so two time frames as input). The algorithm would differ depending on signal types, example:

- Logs => based on some short-listed words occurrences, such as "error"
- Metrics => looking at stddev as suggested in #1981
  - But for a couple of known metrics we could have a more specific detection, e.g. with `istio_requests_total` there are relevant labels to look at such as response code / flag
- Traces => high rate of traces in error, high latencies

The door must be opened for other data sources; perhaps provided by external analyzers such as iter8's.

It is actually a bit similar to our health component (aggregating health from heterogeneous sources), but a difference is that as it's going to be more time consuming, this analysis would probably have to be performed on-demand, triggered from user action, unlike in health.

(Note, for performances, even if we could imagine to store trend baselines to avoid recomputing, it's probably not going to happen, we want to keep Kiali stateless and without storage)

The scores computed would determine what to show on the dashboard. See next comment below.

**Comment by jotak** [comment]
Here's a quick mockup:

![Correlation Dashboard](https://user-images.githubusercontent.com/2153442/81815042-ce909100-9529-11ea-897d-f5ed2d9e5848.png)

**Comment by jotak** [comment]
A small remark, perhaps Kiali is more than others in a sweet spot for this: we not only have access to all these signals, we have them as part of a service mesh, and so we know the relationships between services.

If a first step could be to have this correlation based on an unique service, it could also be extended to the surrounding services (since root cause analysis isn't limited to a service boundaries). So, the analysis could be triggered not only on a given service, but also on that service neighbours.

**Comment by jotak** [comment]
Related to this topic: this is a must-read: https://www.infoq.com/articles/observability-tools-future/ (thanks @jpkrohling )
In particular, in chapter "Presenting the right data to the Troubleshooter", the first suggested visualization is pretty much a correlation dashboard. An interesting aspect is the author insists on "visual pattern recognition" that must be leveraged in such a visualization.

**Comment by lucasponce** [comment]
To me this article (and other similar in the same direction) sounds related to the same area:
https://www.hawkular.org/blog/2017/08/alerts-nelson-rules.html

Which have all basically some points in common:
- Transform data into information, with the heuristic of the domain context.
- Recognize patterns that are interested for the user, because in our domain, means a potential problem.

It's interesting, some days the techniques to recognize patterns and tooling to apply is what it changes here (if neural algorithms are applied, with/without training) but it's all related.

To me, the interesting ideas that can land into our project is how good we can provide heuristics from our business domain (in Kiali case, ServiceMesh/Istio, that the data -> info and pattern matching has a good quality).

**Comment by jshaughn** [comment]
Ha, I had forgotten about the native Nelson Rule alerting in hAlerts, 
that is a neat feature.   Of course I agree with what is generally being 
said in this blog, and this issue.  Continuing to work on how Kiali can 
help identify, notify, investigate and resolve issues is a priority.  A 
timeline view, I think, will be important for us.

**Comment by lucasponce** [comment]
This research task is also related to the roadmap discussion https://github.com/kiali/kiali/discussions/4080

In some comments:
https://github.com/kiali/kiali/discussions/4080#discussioncomment-911067

In short yes, this high level task is still relevant but also would need to be put in the context of scalability

**Comment by jshaughn** [comment]
Useful idea but closing as part of routine backlog maintenance.  Can be re-opened as needed.
