### ISSUE TITLE
Add Ability to Hide specific lines in the logs

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#2778]
**Is your feature request related to a problem? Please describe.**
Many times the logs are filled with stuff I'm not interested in. Lots of junk just spewing in my logs.

**Describe the solution you'd like**
I would like a way to eliminate (hide) log lines containing certain strings

**Comment by mtho11** [comment]
Here is the latest in being able to hide/ignore certain strings(noise) from the logs:

![hide-log](https://user-images.githubusercontent.com/1312165/81997154-d02e8780-9603-11ea-8f80-b448c7c0fd9f.gif)

**Comment by jshaughn** [comment]
I like it.  Maybe "log entry" as opposed to log line?  Also, maybe add a little info icon explaining how it works, is it regex ot literal substring?  maybe later we should add a regex toggle, that could be cool.
