### ISSUE TITLE
Navigation to other detail pages using Graph Overview (mini-graph)

### ISSUE THREAD

**Issue by israel-hdez** [kiali/kiali#2790]
In detail pages, there is a _Graph Overview_ card (aka mini-graph)

![minigraph](https://user-images.githubusercontent.com/23639005/73033086-95130900-3e06-11ea-9165-27f7010815be.png)

Currently, the graph overview accepts only pan and zoom actions. It would be great if it's enhanced with click or double-click actions to go to the details page of the chosen node.

**Describe alternatives you've considered**
The current alternative is to find the link on the other available cards in the details page, but you need to do a small additional effort to locate the link.

**Comment by lucasponce** [comment]
From the graph overview perspective, it's sounds really good to be able to click (or double click) in a minigraph element and be able to move between details pages.

I think that enhancement can boost the user experience when navigating into the details.

Also, I think that the icon to go back to the main graph is "too hidden", I suggest to add a minigraph more visible to back to main graph.

I.e. in a similar way as graph has the legend buttons:

![image](https://user-images.githubusercontent.com/1662329/82215645-09266f00-9918-11ea-9dd5-1c80fb4dc32a.png)

A similar style button with the icon used in overview for navigating into the graph:

![image](https://user-images.githubusercontent.com/1662329/82215711-1cd1d580-9918-11ea-9e93-4e2ad497491d.png)


I think would make sense than enter in the menu and click.

**Comment by jshaughn** [comment]
> Also, I think that the icon to go back to the main graph is "too hidden", I suggest to add a minigraph more visible to back to main graph.

I am +1 on the detail to detail nav via double-click.  But I am -1 on a change to the "full graph" navigation.  The kebab menu is standard and already UX approved as the mechanism for navigating back to the full graph.  A change would need to involve UX, and I think it's unnecessary.

**Comment by lucasponce** [comment]
> I am +1 on the detail to detail nav via double-click. 

I'm +1 if we start working on that. 
The suggestion to change the "full graph" navigation can be discussed separately.

Perhaps in minigraph we can play with single-click vs double-click.

But that's a detail, I'm ok if there is movement on this.

**Comment by jshaughn** [comment]
> Perhaps in minigraph we can play with single-click vs double-click.

Whichever seems better when we have something working.

**Comment by lucasponce** [comment]
To me this is fine to put in backlog, it seems we have discussed on the PR.
