### ISSUE TITLE
getLatestKialiOperator doesn't get right version

### ISSUE THREAD

**Issue by sergeydeg** [kiali/kiali#2793]
**Describe the bug**
today getting https://kiali.io/getLatestKialiOperator
and running it  like
./getLatestKialiOperator -an '**'

Kiali version not determined

need to run with 
-kiv 'lastrelease'
flag.

Error because of before this block KIALI_IMAGE_VERSION environment not set if not given by param
if [ "${OPERATOR_INSTALL_KIALI}" == "true" ]; then
  if [ "${KIALI_IMAGE_VERSION}" == "lastrelease" ]; then

**Expected behavior**
If -kiv parameter not set, KIALI_IMAGE_VERSION is set to "lastrelease" by default

**Comment by jmazzitelli** [comment]
What should have happened is no image_version should have been placed in the Kiali CR and the operator should be installing the default version (which should be the latest). See where the KIALI_IMAGE_VERSION env var is used:


```
     $(build_spec_value image_version KIALI_IMAGE_VERSION)
```

That results in an empty line by default - so Kiali CR won't set image_version. This is because that version should not really be set anymore explicitly (unless you have a really good reason to set it). The operator determines what version of Kiali to install via the "spec.version" value now in Kiali CR. That spec.version is set to "default" by this script, which tells the operator to install the default Kiali CR.

I will run this again to make sure it is working as expected (as described above).

**Comment by jmazzitelli** [comment]
@sergeydeg can you post the exact full output you get from running that command?

**Comment by jmazzitelli** [comment]
Generally I would run `bash <(curl -L https://kiali.io/getLatestKialiOperator) -an '**'`), but I ran these commands to more accurately run what the issue description says:

```
cd /tmp
curl -L https://kiali.io/getLatestKialiOperator > getLatestKialiOperator
chmod +x getLatestKialiOperator
./getLatestKialiOperator -an '**'
```

At the prompt for the login strategy, I just entered "anonymous" for simplicity:

```
Choose a login strategy of either 'login', 'openshift', 'token', 'ldap' or 'anonymous'. Use 'anonymous' at your own risk. [openshift]: anonymous
```

And the script ran fine. When I look at the Kiali CR that was generated, I see no `deployment.image_version` set as expected, with `spec.version` set to `default`, again, as expected:

```
$ oc get kiali kiali -n kiali-operator -o yaml
apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
...
  name: kiali
  namespace: kiali-operator
spec:
  auth:
    strategy: anonymous
  deployment:
    accessible_namespaces:
    - '**'
    namespace: istio-system
    secret_name: kiali
    view_only_mode: false
  external_services:
    grafana:
      url: ""
    tracing:
      url: ""
  version: default
...
```

At this point, I wait for Kiali to deploy. I then look at the Kiali pod to make sure it is running and I take note that it is the latest release as of today which is v1.18.0 (the latest release is the default since I didn't specify `-kiv` option when running the deploy script):

```
$ oc get pods -n istio-system
NAME                                    READY   STATUS    RESTARTS   AGE
istio-egressgateway-65795cf5dd-rfdnk    1/1     Running   0          5d15h
istio-ingressgateway-678bc5fcbc-gqcs5   1/1     Running   0          5d15h
istiod-577d69d9f8-5llrh                 1/1     Running   0          5d15h
kiali-65c5b58785-jsfzn                  1/1     Running   0          2m5s
prometheus-785f9d667d-5vgm8             2/2     Running   0          4d
```

```
$ oc get pod kiali-65c5b58785-jsfzn -n istio-system -o yaml
apiVersion: v1
kind: Pod
metadata:
...
  labels:
    app: kiali
    version: v1.18.0
  name: kiali-65c5b58785-jsfzn
  namespace: istio-system
...
spec:
  containers:
...
    image: quay.io/kiali/kiali:v1.18.0
...
```

So this is working as expected. I would need replication procedures to confirm a bug exists, because I cannot reproduce it.

**Comment by sergeydeg** [comment]
I runned it like You, download first then chmod

output (cropped)

> The Kiali operator is installed!
Kiali will now be installed.
Choose a login strategy of either 'login', 'token', 'ldap' or 'anonymous'. Use 'anonymous' at your own risk. [login]: 
What do you want to use for the Kiali Username: admin
What do you want to use for the Kiali Passphrase: 
=== KIALI SETTINGS ===
ACCESSIBLE_NAMESPACES=**
AUTH_STRATEGY=login
CREDENTIALS_CREATE_SECRET=true
GRAFANA_URL=
KIALI_CR=
KIALI_IMAGE_NAME=
KIALI_IMAGE_PULL_POLICY=
KIALI_IMAGE_VERSION=
ISTIO_NAMESPACE=
JAEGER_URL=
NAMESPACE=istio-system
SECRET_NAME=kiali
_SECRET_EXISTS=
VERSION=default
=== KIALI SETTINGS ===
secret/kiali created
A secret named [kiali] in namespace [istio-system] was created.
secret/kiali labeled
Deploying Kiali CR to namespace [kiali-operator]
kiali.kiali.io/kiali created
Done.

Then no kiali pod created, and in operator log I found this:
`{"level":"error","ts":1589540075.5974236,"logger":"controller-runtime.controller","msg":"Reconciler error","controller":"kiali-controller","request":"kiali-operator/kiali","error":"event runner on failed","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tpkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:258\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\tpkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tpkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\tpkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:88"}
{"level":"info","ts":1589540081.150277,"logger":"logging_event_handler","msg":"[playbook task]","name":"kiali","namespace":"kiali-operator","gvk":"kiali.io/v1alpha1, Kind=Kiali","event_type":"playbook_on_task_start","job":"6263450610539110790","EventData.Name":"Determine the default playbook"}`

`TASK [default/kiali-deploy : fail] *********************************************
task path: /opt/ansible/roles/default/kiali-deploy/tasks/main.yml:350
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Could not determine what the image version should be. Set deployment.image_version to a valid value"}`

**Comment by jmazzitelli** [comment]
```
"Could not determine what the image version should be. Set deployment.image_version to a valid value"
```
I think I know what this is, I've seen this before when a cluster cannot get out to the Internet to ask the github API what the latest release is (or, in the case that github.com is down). That's how the script and the operator determines that the last release it makes a call to the github.com API. See:

https://github.com/kiali/kiali-operator/blob/v1.18.0/roles/default/kiali-deploy/tasks/main.yml#L335

```
  shell: echo -n $(curl -s https://api.github.com/repos/kiali/kiali-operator/releases 2> /dev/null | grep "tag_name" | sed -e 's/.*://' -e 's/ *"//' -e 's/",//' | grep -v "snapshot" | sort -t "." -k 1.2g,1 -k 2g,2 -k 3g | tail -n 1)
```
If your cluster for some reason cannot send requests to github.com, you cannot rely on this feature of using "lastrelease" and you will need to use "-kiv" option and directly indicate the version.

If you run that command you see above, the github API should return the proper releases - this is what I get:

```
$ curl -s https://api.github.com/repos/kiali/kiali-operator/releases 2> /dev/null | grep "tag_name" | sed -e 's/.*://' -e 's/ *"//' -e 's/",//' | grep -v "snapshot" | sort -t "." -k 1.2g,1 -k 2g,2 -k 3g | tail -n 1
v1.18.0
```

**Comment by sergeydeg** [comment]
Thanks for your suggestion, 
I think it could be a problem with my proxy settings for Internet access from inside of container
