### ISSUE TITLE
top menu items always link to master copy

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#2803]
Go to an archive of the docs, say 1.16. You end up with pages that have 1.16 in the URL:

https://kiali.io/documentation/archive/v1.16/

Now I want to go to the "Getting Started" page that was for that version v1.16. So I click "Getting Started" in the top menu, and it takes me here:

https://kiali.io/documentation/getting-started/

Which is the master copy (latest) and not the v1.16 archive one I want.

The top menu items should be "sticky" - they should link to the archive version you are on.

This goes with epic: https://github.com/kiali/kiali/issues/2181

**Comment by cfcosta** [comment]
This is not a bug but a feature enhancement, imho.

There is no way to do that on Hugo, as the layouts are one and the same for every page. The only way would be to do that on Javascript.

**Comment by jmazzitelli** [comment]
Maybe we should take off the top menu items for archive views - otherwise, I can very easily see someone get confused. They are going to click on an archive (go to Documentation, then click Archive, then click a version), then in the page that shows up, they will then navigate to where they want to go most likely via the top menu items - and without realizing it (they have to look at the URL in the address bar) they will be back to the master copy. Whether we call it bug or enhancement, from a user's perspective, it will be very confusing. The question that will next be asked will be, "OK, then, how do I get to the Getting Started page for v1.16? (or whatever page for whatever version)".

**Comment by jshaughn** [comment]
I think we need to wait and gather more feedback about the usability.   Given that it's not easy to do in Hugo we're not going to bend obver backwards to make this sort of change without some consensus.   One potentially easy thing we could do would be to add some text to the archive selection page explaining how it works.

**Comment by jmazzitelli** [comment]
Apparently, I'm on an island thinking that the top links should be pointing to the version of docs that are currently being viewed. Closing.
