### ISSUE TITLE
Istio 1.5 - Can't access to Policy/MeshPolicy details page

### ISSUE THREAD

**Issue by xeviknal** [kiali/kiali#2812]
Fresh installation of Istio 1.5.4 has a Policy installed into istio-system namespace. Listing the Policy works alright, seeing the details doesnt:

![Screenshot of Kiali Console (82)](https://user-images.githubusercontent.com/613814/82588177-ae507a00-9b9a-11ea-83ad-1de5a239284d.png)

**Comment by lucasponce** [comment]
@xeviknal are you testing master with Istio 1.5.4 ?
I mean the default user running istioctl dashboard kiali won't hit this one because he/she is using kiali 1.14.

This is to keep (best we can) compatibility with 1.5.x.

**Comment by xeviknal** [comment]
Yes, I moved to Istio 1.5.4 for a second to check out something. I saw this.
I decided to fix it because I understood that we were keeping support of Policies and Meshpolicies for people usting prior versions to 1.6. Therefore, they should be able to see those objects. Otherwise it doesn't make much sense.
