### ISSUE TITLE
Support different mesh implementations

### ISSUE THREAD

**Issue by asubmani** [kiali/kiali#2823]
**Is your feature request related to a problem? Please describe.**
We would love to use this with other service meshes like Linkerd and Maesh which we have to manage for different teams.

**Describe the solution you'd like**
Integrate with SMI (service mesh initiative) using an adapter (like Consul) or directly with the SMI API (like Linkerd).

**Describe alternatives you've considered**
SPLUNK,Azure Monitor, AppDynamics, Sysdig. We do not want to change our service mesh for the monitoring tool.

**Additional context**

N/A

**Comment by jshaughn** [comment]
@asubmani Kiali for other service meshes would be great, and in some places we do have an extendable architecture, but it would still be a large effort. Given the team size and the effort necessary just to match pace with Istio, it's unlikely that other mesh will be supported unless that support is contributed.   We could probably help guide such an effort if a serious effort was proposed.  I'm adding the Help Wanted label to make it clear that it's not on the current roadmap.

**Comment by lucasponce** [comment]
Closing this in favor of the same discussion https://github.com/kiali/kiali/discussions/4166

Roadmap discussion will be moved in that section instead of issues.
