### ISSUE TITLE
check memory consumption of the kiali pod

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#2843]
We should perform some memory profiling on Kiali to ensure we are judicious in our use of memory. 

```
judicious: (adjective) having, showing, or done with good judgment or sense.
```
:-)

**Comment by lucasponce** [comment]
I think @FilipB is currently working and planning performance testing where we can collect more information about sizing.

With those results we can study and analyze potential optimizations but having such generic issue open overlaps with the work of Filip.

When we find a specific problem, we can open a new one to handle a specific scenario.
