### ISSUE TITLE
upload images to docker hub in addition to quay.io

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#2844]
There have been a couple major outages of quay.io in the past couple weeks, causing some in the upstream Istio community to be unable to install Kiali.

We should go back to uploading kiali to docker hub (while keep uploading to quay.io). We should also upload the operator to docker hub as well (again, keep uploading it to quay.io as we have been).

Doing this will provide a backup in case one or the other goes down (if quay goes down, people can switch to docker; if docker goes down, people can use quay).

**Comment by israel-hdez** [comment]
Does this still stands?
I'm wanting to close this as I haven't seen a new outage in all this time.

Services fail, and people can live with occasional outages...

**Comment by jmazzitelli** [comment]
If we don't want to do that, I'm find with closing.

**Comment by israel-hdez** [comment]
Well, I don't. But it's me :)
You opened this. If you are stepping back, I can close ;)

**Comment by jmazzitelli** [comment]
We can close. I'll just blame you if people yell at us when quay.io blows up again ;-)
