### ISSUE TITLE
unable to view service graphs with istio-1.5.2

### ISSUE THREAD

**Issue by dinesh4747** [kiali/kiali#2859]
**General remarks**

we are facing issues in rendering the service graph in Kiali with mesh/istio version 1.5.2

**Rest of the features/tabs works fine, But we would also see that for the bookinfo app the graphs are being rendered.**

**Versions used**
Kiali: v1.18  (quay.io/kiali/kiali:v1.18)
Istio: 1.5.2
Kubernetes flavour and version: 1.15.11-gke.5 (GKE)

**Expected behavior**
we should be able to render/construct the service graph for all the namespace which we select with istio-1.5.2 

**Below screenshots would depict the condition where we are unable to render service graph for any of the namespace but only _bookinfo_ (default app from Kiali) has graphs being rendered**

![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/23452852/83567288-fe3a2400-a53e-11ea-97bb-f3618c7e0b1e.png)
![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/23452852/83567297-02664180-a53f-11ea-8401-7ad3cd93657a.png)
![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/23452852/83567302-04300500-a53f-11ea-88af-109cada6ca08.png)

**Comment by jshaughn** [comment]
@dinesh4747 Thanks for using Kiali and reporting a possible issue. Is it only the Service graph that gives you an empty graph for the brewery namespace?  Could you try graphType=workload?  If that renders a graph please post a screen shot.  If it does not then try the "Display Unused Nodes" option to see if you at least see your services with no traffic.

**Comment by tkishore1192** [comment]
@jshaughn - Thank you for your response, Dinesh and I are from the same team. I can provide you with the information required.
![image](https://user-images.githubusercontent.com/46791529/83572974-36923000-a548-11ea-8f22-4fc3c0ce0f22.png)

![image](https://user-images.githubusercontent.com/46791529/83573044-5a557600-a548-11ea-9e3b-6d2ca7f755e2.png)

Only the unused nodes renders a graph.

**Comment by tkishore1192** [comment]
![image](https://user-images.githubusercontent.com/46791529/83573127-807b1600-a548-11ea-9148-2d05f1cab94d.png)

**Comment by tkishore1192** [comment]
I did check prometheus for the metrics. They are available. I'm attaching the screenshot for your reference.
![image](https://user-images.githubusercontent.com/46791529/83803729-adefcd00-a6ca-11ea-9e4c-54ac5e7b715e.png)

**Comment by tkishore1192** [comment]
Here is some interesting observation. While I was reviewing the networking while I'm on the graph page. I see there are no queries being fired for metrics.
![image](https://user-images.githubusercontent.com/46791529/83804781-4d618f80-a6cc-11ea-939c-1240fa822463.png)
But when switch the namespace to default. I can see the queries for metrics on the network activity.
![image](https://user-images.githubusercontent.com/46791529/83804899-839f0f00-a6cc-11ea-8807-5dd57463f4f7.png)

**Comment by israel-hdez** [comment]
@tkishore1192 about the absence of metric queries, it's expected if graph is empty.

OK, one more request. I see you have selected "Last 1 minute" in the graph range dropdown. Can you please, do again the prometheus queries and specify the range modifier? Like:

* `istio_requests_total{source_workload_namespace="brewery"}[1m]`
* `istio_requests_total{destination_workload_namespace="brewery"}[1m]`

If there is no output, it means you don't have traffic in the last minute and no graph will be generated. You may need to choose a greater range. If you get results, please paste the timeseries. Some text is cut in the screenshot and I'm interested in seeing all labels present in the timeseries.

**Comment by courcelm** [comment]
Facing the same issue with Istio 1.5.8 and rancher/kiali-kiali:v1.15 docker image

**Comment by jshaughn** [comment]
@courcelm Are you using Telemetry V1 (mixer) or Telemetry V2 (experimental im Istio 1.5).  Also, are you seeing any errors in the Kiali pod logs?

**Comment by courcelm** [comment]
missing expected TS labels errors in Kiali pod logs .

**Comment by jshaughn** [comment]
@courcelm @tkishore1192 , This issue results from running Mixer (Telemetry V1) with Istio 1.5.  It is resolved in Kiali 1.17, which should be totally compatible with Istio 1.5.  Are you able to update?   If you must stay on the Kiali 1.15 line then we could perhaps backport the fix and release 1.15.3.

**Comment by courcelm** [comment]
It is working fine with quay.io/kiali/kiali:v1.17 . Thanks!

**Comment by jshaughn** [comment]
Great news!  I will close this issue, please re-open if you feel the need.
