### ISSUE TITLE
operator should no longer create OpenShift ApplicationMenu ConsoleLink resources

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#2861]
The operator should no longer create ConsoleLink resources with `location: ApplicationMenu` - the links should no longer be installed in the OpenShift masthead.

To do this, these lines should be removed from the operator: https://github.com/kiali/kiali-operator/blob/v1.18.2/roles/default/kiali-deploy/templates/openshift/console-links.yaml#L1-L12

cc @maltron

**Comment by jshaughn** [comment]
cc @maltron This should link to a dev console Jira and likely be part of the 4.6 dev console integrtion work.   I'm not against it because it makes sense to avoid multiple links, But let's not make a change w/o an actual DC jira for 4.6 planning.  Can you handle that?
