### ISSUE TITLE
Idle status objects missing on Overview's Compact View

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#2867]
Happens on Kiali master and Istio 1.6.0.
Kiali v1.19.0-SNAPSHOT (0cb2115bd98142040edee559172ae4a328232095)

Idle status App/Workloads are shown on Expand and List views of Overview page, but missing on Compact view (is it because it is compact?).
Anyway this causes confusion.

![Screenshot from 2020-06-04 11-29-35](https://user-images.githubusercontent.com/604313/83741675-cb844e80-a658-11ea-9d89-183f2569f033.png)
![Screenshot from 2020-06-04 11-30-09](https://user-images.githubusercontent.com/604313/83741679-ccb57b80-a658-11ea-9f93-4e828c393ba0.png)

**Comment by jotak** [comment]
@hhovsepy @aljesusg it also seems to be missing in Filters

**Comment by lucasponce** [comment]
Not a blocker but it seems more like a bug.
I agree it should be consistent in all views + filters.
