### ISSUE TITLE
 visualization graph issue

### ISSUE THREAD

**Issue by zqwlai** [kiali/kiali#2869]
my  visualization graph is like this:
![image](https://user-images.githubusercontent.com/10241840/83857573-c6ed9200-a74d-11ea-9098-fd05e60dc0df.png)

this is bookinfo example, i have configured such as virtualservices、destinationrules etc.
and i can find metric in prometheus like istio_request_bytes、istio_response_bytes、istio_request_duration_seconds、istio_requests_total

so why my graph dosen't show some Related connecting lines？

**Comment by jmazzitelli** [comment]
Edges between details, productpage and ratings are all http. So if you sent requests through to the productpage main endpoint, you should be seeing istio_requests_total metrics for the bookinfo.



> i can find metric in prometheus like istio_request_bytes、istio_response_bytes、istio_request_duration_seconds、istio_requests_total

So the question is - did you sent requests through to your bookinfo (either through the browser or curl or some client) and if so do you see those in your `istio_requests_total` timeseries? Remember that timeseries called "istio_requests_total" is the metric family or timeseries for all your apps. You have to look at the labels. Look at things like the destination_app or source_app labels and see if you see the bookinfo apps. Without that telemetry, you will see what you are seeing.

**Comment by zqwlai** [comment]
i use curl to send request （watch -n 1 curl -o /dev/null -s -w %{http_code} http://10.20.0.10:30074/productpage）

in overview page,  it shows like this:
![image](https://user-images.githubusercontent.com/10241840/83864837-e5f12180-a757-11ea-857d-210c896083f2.png)

but in workload page, it shows like this:
![image](https://user-images.githubusercontent.com/10241840/83864966-15a02980-a758-11ea-957d-8860b9512a23.png)

there is no  inbound traffic and outbound traffic

**Comment by jmazzitelli** [comment]
> i use curl to send request （watch -n 1 curl -o /dev/null -s -w %{http_code} [http://10.20.0.10:30074/productpage）](http://10.20.0.10:30074/productpage%EF%BC%89)

And what is the result of that curl? Are you getting the productpage HTML back or some error?

Did you look at your istio_requests_total data in Prometheus and look for those label values? I suspect you don't have any data.

See the red circle with the "!"? That means there is some error condition. I bet this is causing a problem with the app and probably telemetry collection, too. Find out what that error is and correct it and then see what happens.

This just sounds like your bookinfo is not deployed correctly.

**Comment by zqwlai** [comment]
i'am sure my command return "200" and i can see the pageproduct page through browser, and in prometheus, it shows like this:
![image](https://user-images.githubusercontent.com/10241840/83866992-3a49d080-a75b-11ea-90b2-e7ff59c25160.png)

**Comment by zqwlai** [comment]
i I suspect it's the timezone problem

**Comment by israel-hdez** [comment]
Could you, please, post your Istio and Kiali versions?

**Comment by israel-hdez** [comment]
Probably, same issue as in #2859 .

**Comment by jshaughn** [comment]
The graph is based on traffic, actually traffic rates.  One request will generate a delta of 0, so no traffic.    You need to generate a continuous stream of traffic and/or increase the time range you are looking at.  Your graph is set to a duration of 1m, so only traffic generated in that last minute.  The chart you posted was looking at the last 1 hour of traffic and so picked up your curl, I think.

**Comment by zqwlai** [comment]
> Could you, please, post your Istio and Kiali versions?

#istioctl version
client version: 1.5.2
control plane version: 1.5.2
data plane version: 1.5.2 (8 proxies)

#k8s version
v1.16

#kiali version
v1.15

**Comment by zqwlai** [comment]
> Probably, same issue as in #2859 .

i try to upgrade kiali from v1.15 to v1.18 and the graph works fine immediately
<img width="956" alt="9e3c3b13742d2a0e9996ad2f28c53b5" src="https://user-images.githubusercontent.com/10241840/83931988-5046a800-a7d2-11ea-9526-038c0ec7a7d3.png">
![image](https://user-images.githubusercontent.com/10241840/83932004-694f5900-a7d2-11ea-8866-b76b88a9fbb1.png)

the graph also can show traffic, that's good！thank you very much！
