### ISSUE TITLE
Can kiali add permission management function

### ISSUE THREAD

**Issue by shinynz** [kiali/kiali#2877]
Can kiali consider adding permission management, such as operating user or read-only user

**Comment by jmazzitelli** [comment]
I'm not sure what this enhancement request is asking for exactly - however, if you are asking to have multiple users that can log into Kiali using different credentials, and some of those users need to be restricted to read-only, then that capability already exists.

You can use either:

* The "token" login strategy (in which case you log into Kiali using a Kubernetes token for a particular user or service account - similar in the way the Kubernetes Console works)
* The "openshift" login strategy (in which case you log into Kiali using your OpenShift user credentials - this is limited to OpenShift clusters)
* The new "openid" strategy that integrates with your third-party OpenID Connect implementation.

For details, see: https://kiali.io/documentation/getting-started/#_login_options

The OpenID auth strategy is very new - documentation is forthcoming, but you can see the new openid documentation in this PR: https://github.com/kiali/kiali.io/pull/243/files
