### ISSUE TITLE
istio canary upgrade breaking kiali dashboard. 

### ISSUE THREAD

**Issue by dileep-p** [kiali/kiali#2883]
**General remarks**

> Please delete this section including header before submitting
>
> This form is to report bugs. For general usage questions refer to 
>       [Kiali-users](https://groups.google.com/forum/#!forum/kiali-users) mailing list.
>
> For general Kiali-development questions refer to 
>       [Kiali-dev](https://groups.google.com/forum/#!forum/kiali-dev) mailing list.
>
> If you want to propose an enhancement or feature request, please use the feature request template.

**Describe the bug**

when upgrading the istio with canary version the service name for istiod will be something like istiod-${canary-name}. however in the kiali config i am not able to find any option to modify this value 
```
external_services:
  istio:
    url_service_version: http://istiod.istio-system:15014/version
```
This need to be like 
```
external_services:
  istio:
    url_service_version: http://istiod-canary.istio-system:15014/version
```

For UI issues please also add a screenshot that shows the issue.

**Versions used**
Kiali: 1.18
Istio: 1.6.0
Kubernetes flavour and version: (e.g. OpenShift Origin 3.9) EKS 1.16

**To Reproduce**

**Expected behavior**

**Comment by dileep-p** [comment]
https://github.com/istio/istio/pull/24560

**Comment by jmazzitelli** [comment]
If your Istio has a specific endpoint different from the default, you simply define it in the Kiali CR - the Kiali Operator will handle installing or updating Kiali to use your specific URL.

See: https://github.com/kiali/kiali-operator/blob/v1.18.0/deploy/kiali/kiali_cr.yaml#L436-L443

```
spec:
  external_services:
    istio:
      url_service_version: http://istiod-canary.istio-system:15014/version
```

**Comment by acnot** [comment]
@jmazzitelli when Istio is deployed as a canary even ConfigMap's which Kiali reads have different names. I get these messages in Kiali logs:
```
configmaps "istio" not found
GetIstioConfigMap: Cannot retrieve Istio ConfigMap
IsMixerDisabled: Cannot read Istio mesh configuration
```
Is there a way around that?

**Comment by jmazzitelli** [comment]
Ok, there is definitely some work I think that needs to get done for Kiali to work with this new Istio 1.6 canary update mechanism. I created a issue here for the Kiali team to look into: https://github.com/kiali/kiali/issues/2884

**Comment by jshaughn** [comment]
@dileep-p thanks for the question, Closing this issue in favor of #2884 .
