### ISSUE TITLE
how to handle istio canary updates (multiple control planes in the same namespace)

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#2884]
There is a new feature in Istio 1.6 that allows Istio itself to be upgraded in a "canary" fashion - multiple control planes in the same namespace.

See:
* https://istio.io/blog/2020/multiple-control-planes/
* https://istio.io/docs/setup/upgrade/

I do not believe that Kiali today can handle this (at least, we haven't done anything wrt handling a use case where multiple Kialis are installed in a single namespace OR that Kiali can run with multiple Isitos in the same control plane namespace).

We need to figure out how to handle this gracefully.

**Comment by lucasponce** [comment]
Related:
https://github.com/kiali/kiali/blob/master/kubernetes/istio_details_service.go#L24

**Comment by xeviknal** [comment]
Related: when having two control planes, the about modal gets a bit crazy too.

![Screenshot of Kiali Console - 2020-06-10T122933 328](https://user-images.githubusercontent.com/613814/84257713-11885900-ab16-11ea-8e6e-17c6dec9de1a.png)

**Comment by jshaughn** [comment]
@lucasponce @jmazzitelli I think maybe we should hold off work here until we see better what happens in Istio 1.7 and their changes re: installation and add-ons.

**Comment by xeviknal** [comment]
I think it is time to move this one to backlog. Maistra uses the `rev` label to provide the soft multitenancy:

![Screenshot of istiod-basic-install · Details · Red Hat OpenShift Container Platform](https://user-images.githubusercontent.com/613814/92477382-cb0fcc80-f1e0-11ea-8274-3232b8904242.png)

![Screenshot of istiod-basic-install-79c775b54d-xzpm5 · Details · Red Hat OpenShift Container Platform](https://user-images.githubusercontent.com/613814/92477387-cd722680-f1e0-11ea-984e-99d568bc8a68.png)

However, I think that the main change for Kiali is only to allow users specify either the `rev` name (which will be the suffix of CM name) or the configmap name. I guess that the first one is the most appropriate.
With that new setting, kiali will be able to accurately look up the correct configmap.

@lucasponce @jshaughn

**Comment by jmazzitelli** [comment]
This is also going to have to involve the operator/helm charts because I think we are going to need to be able to install the Kiali components with additional labels. In the same way Istio is using the `istio.io/rev` label - we'll probably want a `kiali.io/rev` label in the kiali components (the kiali Deployment, its ConfigMap, its ServiceAccount, its Roles, etc. etc.). And when we uninstall, the operator will need to know which rev to uninstall (so the Kiali CR will probably need a new deployment.XYZ setting (`deployment.rev` perhaps?). This is going to need to involve some thinking in how we do the install/uninstall.

**Comment by jshaughn** [comment]
I moved ths to the sprint backlog.   To be clear, I don't think we need to worry about the Istio 1.6 canary upgrade, that can be known problem.  Instead, let's concentrate on 1.7 and with Kiali as an add-on.  So, instead of multiple Kialis, the single Kiali solution would be preferable.

**Comment by jmazzitelli** [comment]
> So, instead of multiple Kialis, the single Kiali solution would be preferable.

Oh, in that case, it probably won't touch the operator/helm stuff much - probably only need to add a new setting to the Kiali CR to tell Kiali which Istio components to look at.

**Comment by jmazzitelli** [comment]
I just did a little research on how we can implement a deployment.rev setting in the Kiali CR - thus we could have multiple kiali installs in the same namespace. Given a value `deployment.rev` in the Kiali CR we can make sure all the resources are uniquely named (so the service account could be `kiali-v1` and `kiali-v2` for example).

A couple things to note:

1) The dashboard resources (MonitoringDashboards CRs) are named things like "envoy", "go", "vertx-server", etc. If we install multiple Kialis in the same namespace, we'll have multiples of these. It is easy enough to rename these based on which Kiali owns them (e.g. "envoy-kiali-v1"... "envoy-kiali-v2" ...) but is this OK? Does it matter what these are named? How does the Kiali Server process these resources? Is it OK to have duplicates just with different names in the same namespace?

2) When installed with a fixed set of accessible namespaces (NOT `**`) each namespace is assigned a label `kiali.io/home` whose value is the namespace where Kiali is installed. Basically, it tells you which Kiali has been given access to that namespace. But if we support multiple Kialis per namespace, this brings up a problem as to who owns that namespace label. Because when Kiali is uninstalled, it removes those labels. But if you have 2 or more Kialis installed in the same namespace and they all have access to that external namespace, you can't uninstall one of those Kialis and expect to be able to remove that label because the second Kiali is going to need that label. I believe the label is used by the operator in order to know what namespaces have Kiali roles associated with them. We need to figure out what to do here (do we keep those labels? Do we introduce a different label, one per Kiali install?)

**Comment by jmazzitelli** [comment]
IMO, we should not support running mulitple Kialis in the same namespace. Now that Kiali is not within the Istio Operator itself we don't have to worry about the user installing multiple kialis in the same namespace as the multiple istio control planes (the only thing upstream istio has is the "demo" addon scripts - but those are example demos only and not meant to support complex deployments like these canary production deployment scenarios).

What I believe we can support is installing Kiali in separate namespaces (e.g. kiali-ns1, kiali-ns2) - the kiali operator can very easily support this (this is how it handles multi-tenancy for example). You just configure the Kiali CR in each of the namespaces where kiali is to be installed, making sure to point Kiali to the Istio in question.

In theory, you should be able to point multiple Kiali instances to the same control plane - but of course, we need to test to see what breaks in this scenario - there are several things that won't work today that would need to be fixed. For one, you would need to tell Kiali to query the correct prometheus instance for the different Istio installs (this should be simple - the `spec.external_services.prometheus` setting lets you tell Kiali which specific proimetheus to query - so you can point each Kiali to either the canary deployment's prometheus or the old deployment's prometheus).

Second, what to do with the namespace labels when the `spec.deployment.accessible_namespaces` is not `[**]`. Perhaps in the first implementation of this, we just don't support that non-`**` value when installing mulitple kialis to point to the same control plane namespace. To support it, we need to change the label name and/or value so it is unique across kiali installs (today the values are unique because we only support one kiali per control plane namespace). Supporting non-`**` value means we also have to make sure the roles/rolebindings that are created for each kiali do not step on the others (I suspect today that they will - we would need to do something like create them with different names which may make managing them/removing them more difficult - I'm not sure).

Third, the same kind of problem with the labels exist with the OpenShift Console Links (I explain in more detail in an earlier comment) - we would have to come up with a solution for this (easiest thing for now, as a first implementation, is to not install a Console Link resource if we see one that already exists - I don't like this as a solution, but it's just an idea).

There might be other problems that we would have to fix. These are just some of the things I can think of without actually trying it.

**Comment by xeviknal** [comment]
I think the first task to do to support the canary updates is to support the installation of istio CP when comes from an upgrade.
As I saw in a today's user, the istiod deployment has a suffix with the revision added e.g. `istiod-1-9-0`. This might result in a multi-cluster problem as it need to access to it. On the other hand, istio also renames the istio config map with a suffix too.

So as of today, we this task should stask with making sure that Kiali with one istio installation coming from an upgrade.

**Comment by xeviknal** [comment]
@jmazzitelli @lucasponce @jshaughn Do you agree to start working with this task? Perhaps with a subset of the whole description of this (should this issue be an epic maybe?).

A [hardcoded reference to istiod](https://github.com/kiali/kiali/blob/6610f85f967faa5c51865bfbcb7d53d38a6bfed7/business/mesh.go#L161) was added after the introduction of the multi-cluster effort. Meaning that, now, people using one single Control Plane that comes from an upgrade they can't just browse kiali. Before the multi-mesh, they could use canary installations.

IMO, this is a big way to lose users and traction. My proposal would be to start just supporting one CP without checking which namespaces are part of the current istiod.

**Comment by jmazzitelli** [comment]
> A [hardcoded reference to istiod](https://github.com/kiali/kiali/blob/6610f85f967faa5c51865bfbcb7d53d38a6bfed7/business/mesh.go#L161) was added after the introduction of the multi-cluster effort.

This is a bug IMO. We know it isn't called `istiod` in all use-cases (it isn't called that in OSSM in fact - so this is broke with OSSM out of box).

**Comment by jmazzitelli** [comment]
> My proposal would be to start just supporting one CP

That's a necessary requirement IMO - if we do NOT "support on CP" that we have a bug(s).

**Comment by jshaughn** [comment]
Adding @israel-hdez to the discussion, Edgar, please read back.  We will need to remove this `istiod` assumption.

**Comment by israel-hdez** [comment]
> A [hardcoded reference to istiod](https://github.com/kiali/kiali/blob/6610f85f967faa5c51865bfbcb7d53d38a6bfed7/business/mesh.go#L161) was added after the introduction of the multi-cluster effort. Meaning that, now, people using one single Control Plane that comes from an upgrade they can't just browse kiali. Before the multi-mesh, they could use canary installations.

I tend to temble with fear when I use a hard coded for which I cannot find a corresponding setting in the ConfigMap :-(

> This is a bug IMO. We know it isn't called `istiod` in all use-cases (it isn't called that in OSSM in fact - so this is broke with OSSM out of box).

@xeviknal @jmazzitelli is it really that badly broken? It's expected that "istiod" cannot be found some times. I think we fail gracefully in most cases (i.e. processing continues rather than stopping). 

Anyway, if the value shouldn't be hard-coded, I agree it's a bug.

**Comment by israel-hdez** [comment]
Oh, I just saw #3782 and I see that it's broken...
I think I failed to catch the `404 Not found` error from the cluster API.

**Comment by jshaughn** [comment]
@israel-hdez It sounds like a bug, if appropriate assign yourself to this issue and fix for this release.  If not this issue then please create a new issue.  Thanks.

**Comment by xeviknal** [comment]
@jshaughn @israel-hdez I took the liberty of assigning the task to myself. Since I was investigating the scenario, I have an Istio canary deployment already installed and should be quite straightforward to approach it. I'll re-open the #3782 to fix it. wdyt?

@jmazzitelli have you tried it with OSSM? Because what I recall they were using is the istio config map using the canary deployment's nomenclature. Not the deployment.

**Comment by xeviknal** [comment]
Re-opening issue due to automatic closing.

**Comment by jmazzitelli** [comment]
We are going to start small and say we support canary upgrades by simply pointing the Kiali to the upgraded control plane (so there will still be only a single Kiali instance, but you just point it to the newly upgraded control plane).

We have three settings in the Kiali CR to support a control  plane that was produced by a canary upgrade. These three are in the `spec.external_services.istio` section of the Kiali CR and they are:

* [config_map_name](https://github.com/kiali/kiali-operator/blob/130841a7c448bf72b5bdea78df7b6927ad5adb0d/deploy/kiali/kiali_cr.yaml#L539)
* [istiod_deployment_name](https://github.com/kiali/kiali-operator/blob/130841a7c448bf72b5bdea78df7b6927ad5adb0d/deploy/kiali/kiali_cr.yaml#L545)
* [istio_sidecar_injector_config_map_name](https://github.com/kiali/kiali-operator/blob/130841a7c448bf72b5bdea78df7b6927ad5adb0d/deploy/kiali/kiali_cr.yaml#L543)

**Comment by nrfox** [comment]
Docs have been updated in https://github.com/kiali/kiali.io/pull/370 explaining how to update Kiali during an Istio canary upgrade. Is there anything else that needs to be done for this issue?

**Comment by jshaughn** [comment]
> Docs have been updated in kiali/kiali.io#370 explaining how to update Kiali during an Istio canary upgrade. Is there anything else that needs to be done for this issue?

Not that I know of, deferring to you and @jmazzitelli.

**Comment by nrfox** [comment]
Closing since this is now documented on [kiali.io](https://kiali.io/documentation/latest/installation-guide/#_canary).
