### ISSUE TITLE
Provide meaningful "Ready" status for kubectl wait when using operator

### ISSUE THREAD

**Issue by howardjohn** [kiali/kiali#2885]
**Is your feature request related to a problem? Please describe.**
I would like a programatic way to determine when Kiali has been deployed. With other operators or resources I can use `kubectl wait` on some status, but Kiali does not expose this as far as I can tell

**Describe the solution you'd like**
Kiali exposes a status field "Ready", that is set to true on the Kiali resource once it has been fully reconciled and deployed

**Describe alternatives you've considered**
`kubectl wait` on the `kiali` deployment that I expect to be created eventually. However this is painful due to https://github.com/kubernetes/kubernetes/issues/83242

**Comment by jmazzitelli** [comment]
Same thing asked for here: https://github.com/kiali/kiali/issues/2212

**Comment by lucasponce** [comment]
@jmazzitelli last comment was +1 year, is this issue still open ?

**Comment by jmazzitelli** [comment]
Just as with https://github.com/kiali/kiali/issues/2212 - without periodic reconciliation enabled in the operator (which we do not do) there is nothing much we can do to let the user know the POD is ready. You can know when the operator has finished but that does not guarantee the kiali pod is ready.

**Comment by lucasponce** [comment]
Closed per Closed per https://github.com/kiali/kiali/issues/2212#issuecomment-892685034
