### ISSUE TITLE
Kiali operator does not recreate removed deployment

### ISSUE THREAD

**Issue by howardjohn** [kiali/kiali#2886]
**Describe the bug**
I deployed Kiali operator + a Kiali resource. I then deleted the created Kiali deployment. I expected the operator to reconcile this and recreate it. I waited 5 minutes, and nothing happened. I am not 100% sure if it would have ever happened as I gave up after 5min.

**Versions used**
Kiali: v1.19.0
Kubernetes flavour and version: GKE 1.16

**To Reproduce**
`kubectl apply -f samples/addons/kiali.yaml` from Istio repo, then a bit later `kubectl delete deployment kiali`

**Expected behavior**
Reconcile happens quickly.

**Comment by israel-hdez** [comment]
The operator is now capable of doing continuous reconciliation.
So, I think this is done. Closing.
