### ISSUE TITLE
allow operator to detect and fix unauthorized changes to resources it creates and manages

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#2889]
Right now, the operator only runs a reconciliation when something changes in the Kiali CR.

This works nicely because it means the Kiali Operator puts almost no load on the cluster unless and until Kiali needs to be changed (installed, modified, uninstalled).

However, it also means some things cannot be done - such as:

1. Updating the status of the Kiali deployment (though you could look at the Kiali pod to obtain the status) See: https://github.com/kiali/kiali/issues/2212 and https://github.com/kiali/kiali/issues/2885

2. Detecting when some Kiali component was deleted erroneously - the operator cannot reconcile that and resurrect the component. See: https://github.com/kiali/kiali/issues/2886

We should investigate how difficult it would be to implement something like this, while at the same time not putting unnecessary load on the cluster (e.g. I don't think we want the Kiali Operator running reconciliation every 5 seconds - but perhaps on the order of minute(s) would be acceptable).

**Comment by jmazzitelli** [comment]
Just a note - to turn on periodic reconciliation, this can be done today by adding this annotation to the Kiali CR:

```
ansible.operator-sdk/reconcile-period: "120s"
```

The user, therefore, has control over how often to run reconciliation. By default (today) the operator does not run periodic reconciliations because this is in the `watches.yaml` file:

```
reconcilePeriod: 0
```

**Comment by jmazzitelli** [comment]
I'm looking into using dependent resource watches rather than periodic loops. All molecule tests pass when I try this. I will need to see the pros and cons of using dependent watches versus periodic executions.

to use the watches, this needs to be in watches.yaml:

```
  reconcilePeriod: 0
  watchDependentResources: True
  watchClusterScopedResources: True
```

**Comment by jmazzitelli** [comment]
When using dependent resource watches:

- PROS
-- playbook only runs when it has to
-- if a managed resource is altered or removed, playbook will immediately be triggered to revert the unauthorized change
- CONS
-- behavior cannot be overridden by the user
-- playbook might get triggered when no work really has to be done. For example, when initially installing a Kiali CR, the playbook runs twice. The first time through it creates everything, but then is triggered again at which time no real work needs to be done (all the resources remain as-is). I think it is because an event such as the pod coming up is triggering the playbook again, unfortunately, no log messages are emitted from the operator SDK to indicate what resource/event caused the playbook to run again, so I can't be sure what causes this second run.

When using periodic reconciliation:

- PROS
-- Behavior can be controlled/overriden by the user by simply annotating the CR with `ansible.operator-sdk/reconcile-period: "120s"` - user can define how often the playbook is run by specifying the time duration.
-- Will only run one time when the reconciliation duration timer is triggered
- CONS
-- Will not trigger immediately when a dependent resource is touched - so if for example the Kiali Deployment is deleted, that unauthorized modification will only be undone once the reconciliation duration timer triggers the playbook as opposed to having the playbook triggered immediately when the event occurred.
-- Playbook is run repeatedly even if no work needs to be done. Because this is a simple timer loop, the playbook is blindly triggered every X minutes whether or not work needs to be done or not. So the Kiali Operator will be consuming CPU/memory continually (consider the fact that once Kiali is installed, the operator rarely needs to do anything else).

**Comment by jmazzitelli** [comment]
I'm thinking we initially try the watch-dependent-resources thing - I believe the pros/cons of it outweigh the pros/cons of the periodic solution.

**Comment by jmazzitelli** [comment]
I wrote a description of my research in [this operator-sdk enhancement request](https://github.com/operator-framework/operator-sdk/issues/3364#issuecomment-656640932). I'm copy-n-pasting it here because it essentially describes what I found while working on this issue:

=====

In my particular case - the Kiali Operator - the operator works perfectly fine without any periodic reconciliation (reconcilePeriod=0) and without any dependent-resource watching (watchDependentResources=false, watchClusterScopedResources=false). In other words, the Kiali Operator does not require those features in order for the Kiali Operator to function properly. The Kiali Operator sits dormant for the vast majority of the time (taking up very little cluster resources) until someone creates or modifies a Kiali CR. I like Kiali Operator not having to consume resources when it doesn't have to.

However, I had a user that wanted the operator to run a reconciliation when, say, someone accidentally/purposefully deleted the Kiali Deployment - he wanted the Deployment to get resurrected by the operator automatically. A perfect reason to turn on either periodic reconciliation or dependent-resource-watching. Because of this feature request, I wrote up this issue [here](https://github.com/kiali/kiali/issues/2889).

But I noticed that when I turned on periodic reconciliation in watches.yaml (e.g. "reconcilePeriod=60s"), obviously my operator's playbook is run EVERY 60 seconds, even when it doesn't need to (and remember, Kiali Operator works fine without periodic reconciliation). So my operator immediately went from using almost no cluster resources (e.g. CPU/memory) the vast majority of time to needing resources every minute; and this is bad especially considering that each run of the Kiali Operator's playbook could take 30 seconds or even a minute to complete (thus the Kiali Operator would effectively be continually running its playbook non-stop). So I did not want to enable that by default. I could tell the user to turn on periodic reconciliation via the CR annotation, but that would mean that user would be seeing the Kiali Operator take up those resources every minute and I didn't think that would be good. The alternative would be to change it to something like 5 minutes, but.. meh...

OK, so then I said to myself, "why not try this dependent-resource-watch feature?" So I went back and set reconcilePeriod back to "0" but enabled watchDependentResources=true and watchClusterScopedResources=true (note: my operator does create and manage cluster-scoped resources). And that worked better. Now the operator stays dormant until either the CR is created or modified OR one of the resources that operator creates is touched. That's exactly what the user wanted.

However, there is one thing that bugs me about how that feature works. I noticed that every time a new CR is created (i.e. a Kiali CR is created to indicate that the operator needs to install an operand - the Kiali Server) my playbook is invoked twice. I talked to fabianvf about this to see if I can find out what event causes this second invocation with the hope of being able to quickly abort the playbook run if I can determine it is an unimportant event that doesn't require the playbook to re-run, but he told me the SDK does not even log what event or dependent resource triggered the playbook invocation. So I cannot tell you exactly why this immediate second invocation happens, but it happens, and the operator has no way of determining if it should circumvent the full playbook reconciliation run. And notice that my playbook takes about 30 to 60 seconds to fully complete (even when it changes nothing). So it is annoying to effectively have the Kiali Operator playbook run twice when a Kiali CR is created, rather than just the one time that is necessary in order to install the operand at CR creation time.

So - the solution to this would be - I'll turn off dependent-resource watch by default. Only if a user WANTS this capability to reconcile changes to dependent resources (with the negative side effect of having the playbook triggered multiple times, thus the operator taking more time and resources before going "dormant" again), then the user merely has to annotate his CR with these annotations we are talking about: ansible.operator-sdk/watch-dependent-resources and
ansible.operator-sdk/watch-cluster-scoped-resources.

Thus the best of both worlds - the operator can be configured, by default, to use very little cluster resources and will only run when absolutely necessary (at CR creation or modification time) but the user can configure the operator to do reconciliation of dependent resources if they want that additional capability (at the expense of having the operator use more resources). This trade-off is why I would like the flexibility of being able to turn on and off the dependent-resource-watching feature by the user.

**Comment by jshaughn** [comment]
@jmazzitelli I only wonder the default should be, "On".   The user may not know he has to turn it on to get the behavior he expects.  If resources are an issue due to a few unexpected runs then it could be turned off.  Meanwhile, maybe there willbe improvements that will eliminate the extra events that trigger the unwanted runs.

But I defer to your expertise, so choose what you like.

**Comment by jmazzitelli** [comment]
> I only wonder the default should be, "On". The user may not know he has to turn it on to get the behavior he expects. If resources are an issue due to a few unexpected runs then it could be turned off.

Valid points.

Captain Jay.... I shall consider it!

**Comment by jmazzitelli** [comment]
These PRs address this issue:
* https://github.com/kiali/kiali/pull/2976
* https://github.com/kiali/kiali-operator/pull/71
