### ISSUE TITLE
Remove unnecessary "istio namespace" prom queries in graph generation

### ISSUE THREAD

**Issue by jshaughn** [kiali/kiali#2891]
In telem V2, and actually I think in later versions of mixer, Istio telemetry no longer generates intra-istio service traffic telemetry.  In graph generation we had special-case support to capture this telemetry when the user selected the istio-system namespace (or whichever ns was configured for the control plane).

We can remove this support, simplify the code, and make the slight perf improvement.

**Comment by jshaughn** [comment]
I am wondering now whether our support for istio component namespaces is still useful...

**Comment by jshaughn** [comment]
After some investigation the support for istio component namespaces can also be removed.  This support was in place for when Istio was supporting deployment of the components [of a single control plane] into multiple namespaces.  But then the arch shifted to consolidating into istiod.  The support was only used in graph gen code, and it is now technical debt.

**Comment by jmazzitelli** [comment]
> Because I'm not 100% sure about its use outside of the graph I think we should keep the config/operator support.
I will close the associated operator PR - this one: https://github.com/kiali/kiali-operator/pull/54
