### ISSUE TITLE
Display throughput on the graph edges

### ISSUE THREAD

**Issue by sebcrozet** [kiali/kiali#2897]
**Is your feature request related to a problem? Please describe.**
My distributed system follows a producer-consumer logic. In order to identify the bottlenecks, I need to be able to visualize the throughput of each service (in kB/sec, the request rate is not relevant in my case).

**Describe the solution you'd like**
Right now Kiali allows the display of the number of requests per second on the graph edges. An option to display the throughput (kB per second) instead would be great.

**Describe alternatives you've considered**
I can go into the details of each service to see their inbound/outbound metrics but this makes it difficult to get a global view of the system.

**Comment by jshaughn** [comment]
@sebcrozet Note that the request rates for HTTP/GRPC edges are requestsPerSecond but for TCP edges the request rates are in bytesPerSecond (for bytes sent).  

Does that help you in any way?  Or are you trying to get response data size information?

**Comment by jotak** [comment]
@jshaughn this is indeed something that we don't query from prometheus but it's available to us. That's valid for graph stats as well as for metrics details pages.

Currently we only use the `istio_request_bytes` metric to get histogram distribution, which gives us the average / median / percentiles of request sizes. However these metrics can also provide throughput:

- For histogram distribution, as we currently do, it's queried as something like: `histogram_quantile(0.99, sum(rate(istio_request_bytes_bucket[1m])) by (le))`

- For throughput, we could query something like: `rate(istio_request_bytes_sum[1m])`

So, +1 for me to add these stats, both in graph and metrics pages

**Comment by jotak** [comment]
I did a quick capture of how it would be in Metrics page:

![Capture d’écran de 2020-06-15 14-38-50](https://user-images.githubusercontent.com/2153442/84658974-fe5efa00-af16-11ea-853b-038f77fcad1a.png)

**Comment by jshaughn** [comment]
@jotak This could be done for graph edges by adding a new appender and a display option to toggle its use (the same as we do for response time).  Let's also wait for @sebcrozet to be specific about request/response data throughput.  When it's well-defined we can add to the backlog.  Of course a contribution would be welcome as well.

**Comment by lucasponce** [comment]
I think this is valid.
Adding an optional appender to show request and response throughput in the graph to be in parity of metrics info is useful.

Perhaps that may need also to update the sidepanel charts that are also focused on operations per sec in http+gRPC.

TCP traffic already provides a similar info.

**Comment by jshaughn** [comment]
@sebcrozet Are you still out there?  Is this something you would still like to see?

**Comment by sebcrozet** [comment]
@jshaughn Sorry, I have a different job now so I've not been using Kiali (or anything related to distributed systems) for a while now. So I no longer have any needs regarding this issue.

**Comment by jshaughn** [comment]
@sebcrozet No problem, it's still a valid enhancement, just looking at priorities at the moment.  Good luck with the new position.

**Comment by jshaughn** [comment]
I'd feel better about this if I'd seen at least one more community member asking for this.  But it does seem like it could be useful.  @lucasponce , if you are still +1 I can look at this.

**Comment by lucasponce** [comment]
+1 from my side, it's a nice one
