### ISSUE TITLE
UI: Keep selection of namespaces active

### ISSUE THREAD

**Issue by pavolloffay** [kiali/kiali#290]
I would like to select namespaces by arrows on keyboard. At the moment when I select a namespace the focus goes away and I have to click back on namespace to activate the dropdown.

The duration dropdown behaves fine. I can use arrows to select durations and the focus stays on the dropdown.

**Comment by pilhuhn** [comment]
Is that still an issue with the new and new-new namespace dropdown?

**Comment by pavolloffay** [comment]
Feel free to close it, I haven't run this for quite some time.
