### ISSUE TITLE
kiali-ui How to start , after yarn start  prompt there is no  KIALI_ENV  

### ISSUE THREAD

**Issue by yanghong1995220** [kiali/kiali#2901]
kiali-ui How to start , after yarn start prompt there is no KIALI_ENV ?

**Comment by cfcosta** [comment]
This is a little bit better, but not enough. What exactly are you trying to do, and how are you installing and running kiali, in what platform, what are the steps you took and what was your goal?

Please elaborate so we can help you.

**Comment by yanghong1995220** [comment]
I want to run kiali-ui project locally,I'll npm i&nbsp; &nbsp;,after&nbsp; yarn start&nbsp; but&nbsp; tip me&nbsp; (&nbsp;$ if [ "${KIALI_ENV}" = "production" ]; then npm run start:prod; else npm run start:dev; fi&nbsp; &nbsp;It shouldn't be&nbsp;${KIALI_ENV})






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Cainã Costa"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月12日(星期五) 上午9:13
收件人:&nbsp;"kiali/kiali"<kiali@noreply.github.com&gt;;
抄送:&nbsp;"》花落无语、"<1026834806@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [kiali/kiali] kiali-ui How to start , after yarn start  prompt there is no  KIALI_ENV   (#2901)





 
This is a little bit better, but not enough. What exactly are you trying to do, and how are you installing and running kiali, in what platform, what are the steps you took and what was your goal?
 
Please elaborate so we can help you.

**Comment by cfcosta** [comment]
Ok, do you have a Kubernetes/Openshift cluster running and with Istio? You’ll need it to develop/test.

**Comment by yanghong1995220** [comment]
yes,i have, I want to run kiali-ui




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Cain&amp;#xE3; Costa"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月12日(星期五) 上午9:27
收件人:&nbsp;"kiali/kiali"<kiali@noreply.github.com&gt;;
抄送:&nbsp;"》花落无语、"<1026834806@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [kiali/kiali] kiali-ui How to start , after yarn start  prompt there is no  KIALI_ENV   (#2901)





 
Ok, do you have a Kubernetes/Openshift cluster running and with Istio? You’ll need it to develop/test.

**Comment by cfcosta** [comment]
Cool, the UI is part of the distribution by default, so if you have Kiali installed on your cluster, the UI should be available. In general you do not want to run it with yarn on production, because of many reasons, including performance and security.

For development, you can do a port-forward on the service itself, and add a “proxy” directive on the `package.json`, something like this:

```json
{
  “proxy”: “http://localhost:20001/kiali”
}
```

This is the default url if you use the port-forward from the hack scripts.

**Comment by yanghong1995220** [comment]
I am in v1.19branch&nbsp; ,A startup error is shown in the figure below,&nbsp; &nbsp; &nbsp; &nbsp;
(此时不应有)===It shouldn't be




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Cain&amp;#xE3; Costa"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月12日(星期五) 上午10:55
收件人:&nbsp;"kiali/kiali"<kiali@noreply.github.com&gt;;
抄送:&nbsp;"》花落无语、"<1026834806@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [kiali/kiali] kiali-ui How to start , after yarn start  prompt there is no  KIALI_ENV   (#2901)





 
Cool, the UI is part of the distribution by default, so if you have Kiali installed on your cluster, the UI should be available. In general you do not want to run it with yarn on production, because of many reasons, including performance and security.
 
For development, you can do a port-forward on the service itself, and add a “proxy” directive on the package.json, something like this:
 {   “proxy” : “http://localhost:20001/kiali” }
 
This is the default url if you use the port-forward from the hack scripts.

**Comment by yanghong1995220** [comment]
I mean run with source code&nbsp;&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Cain&amp;#xE3; Costa"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月12日(星期五) 上午10:55
收件人:&nbsp;"kiali/kiali"<kiali@noreply.github.com&gt;;
抄送:&nbsp;"》花落无语、"<1026834806@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [kiali/kiali] kiali-ui How to start , after yarn start  prompt there is no  KIALI_ENV   (#2901)





 
Cool, the UI is part of the distribution by default, so if you have Kiali installed on your cluster, the UI should be available. In general you do not want to run it with yarn on production, because of many reasons, including performance and security.
 
For development, you can do a port-forward on the service itself, and add a “proxy” directive on the package.json, something like this:
 {   “proxy” : “http://localhost:20001/kiali” }
 
This is the default url if you use the port-forward from the hack scripts.

**Comment by jmazzitelli** [comment]
The description of this issue is just the github issue template with no information. Please provide details in the description.

**Comment by jmazzitelli** [comment]
some links that might help:

https://github.com/kiali/kiali#running-a-locally-built-ui-inside-the-core
https://github.com/kiali/kiali-ui#quick-start

**Comment by mtho11** [comment]
@yanghong1995220 Here is a detailed video on how to setup kiali-ui for development: https://www.youtube.com/watch?time_continue=3&v=v4MN04nQNCU&feature=emb_logo

Other videos: https://www.youtube.com/playlist?list=PLgwrCYrAkQYNSMhQv1JEbCC6M88GpE0kF

**Comment by mosakashaka** [comment]
same issure. no idea where the variable `KIALI_ENV` is from...

**Comment by jshaughn** [comment]
@mosakashaka , if you are still having an issue visit us on #kiali channel on Istio Slack and we will help.
