### ISSUE TITLE
developer API link is broken

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#2902]
Go to the kiali.io masthead - hover over "Documentation", click "Developer API", see problem.

This link: https://kiali.io/documentation/latest/developer-api

**Comment by jotak** [comment]
Looks like https://kiali.io/documentation/edge/developer-api/ is working, though I don't know what "edge" stands for here.

**Comment by jotak** [comment]
@cfcosta is this "edge" link supposed to be the good one?

**Comment by cfcosta** [comment]
@jotak sorry about the delay, just woke up. I can take a look at it if you want, but if not, "edge" is master, and "latest" is the latest released version.
