### ISSUE TITLE
Kiali cannot access after using openid login port mapping

### ISSUE THREAD

**Issue by shinynz** [kiali/kiali#2903]
**Describe the bug**
My domain name has been mapped from kubernetes to port 80, but after using keyclock, the original port 20001 has been brought back and cannot be accessed

**Versions used**
Kiali:  v1.19.
Istio:  v1.6.1
Kubernetes flavour and version: kubernetes 1.18.2

**Expected behavior**
After k8s port mapping, kiali can use the mapped port instead of taking out the original port

![image](https://user-images.githubusercontent.com/15795798/84510297-88c91300-acf7-11ea-8476-488907ac93f5.png)

**Comment by shinynz** [comment]
After using keyclock authentication, the return port of kiali should be the address exit port, not the internal port of the kiali container

**Comment by shinynz** [comment]
kiali for keycloak login error
![image](https://user-images.githubusercontent.com/15795798/84638752-f6f51c00-af29-11ea-8f6d-a46d914e3c12.png)

**Comment by lucasponce** [comment]
Thanks for the reporting @shinynz.

I cc our colleague @israel-hdez which has been working on this area.

**Comment by jmazzitelli** [comment]
I think this means "keycloak" right? If so, please change the title of this issue as it is confusing :)

**Comment by jmazzitelli** [comment]
@shinynz We are going to need more information. I assume you are using the new auth strategy of "openid" - is that correct?

If so, we will need to see your Kiali CR configuration, particularly the "auth" section so we can see how you configured Kiali to integrate with your OpenID Connect implementation of KeyCloak.

In addition, please provide the logs messages found in the Kiali pod. Please do not provide screenshots of the logs, as we will need to see more lines than a screenshot can provide, and we would need to search the logs for relevant details. Feel free to scrub the logs of sensitive domain names and things like that if you wish.

Thanks!

**Comment by israel-hdez** [comment]
@shinynz I also would like to see your Kiali CR configuration.
Also, what cloud provider are you using for your Kubernetes cluster?

**Comment by shinynz** [comment]
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{},"labels":{"app":"kiali","install.operator.istio.io/owning-resource":"installed-state","operator.istio.io/component":"AddonComponents","operator.istio.io/managed":"Reconcile","operator.istio.io/version":"1.6.0","release":"istio"},"name":"kiali"},"rules":[{"apiGroups":[""],"resources":["configmaps","endpoints","namespaces","nodes","pods","pods/log","replicationcontrollers","services"],"verbs":["get","list","watch"]},{"apiGroups":["extensions","apps"],"resources":["deployments","replicasets","statefulsets"],"verbs":["get","list","watch"]},{"apiGroups":["autoscaling"],"resources":["horizontalpodautoscalers"],"verbs":["get","list","watch"]},{"apiGroups":["batch"],"resources":["cronjobs","jobs"],"verbs":["get","list","watch"]},{"apiGroups":["config.istio.io","networking.istio.io","authentication.istio.io","rbac.istio.io","security.istio.io"],"resources":["*"],"verbs":["create","delete","get","list","patch","watch"]},{"apiGroups":["monitoring.kiali.io"],"resources":["monitoringdashboards"],"verbs":["get","list"]}]}
  creationTimestamp: "2020-04-16T02:11:07Z"
  labels:
    app: kiali
    install.operator.istio.io/owning-resource: installed-state
    operator.istio.io/component: AddonComponents
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.6.0
    release: istio
  managedFields:
  - apiVersion: rbac.authorization.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations: {}
        f:labels:
          .: {}
          f:app: {}
          f:operator.istio.io/component: {}
          f:operator.istio.io/managed: {}
          f:release: {}
      f:rules: {}
    manager: kubectl
    operation: Update
    time: "2020-05-15T03:38:38Z"
  - apiVersion: rbac.authorization.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          f:install.operator.istio.io/owning-resource: {}
          f:operator.istio.io/version: {}
    manager: istioctl
    operation: Update
    time: "2020-05-22T03:06:31Z"
  name: kiali
  resourceVersion: "9776332"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/kiali
  uid: 36db20b6-7e8e-48b6-a024-d93611a85984
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - namespaces
  - nodes
  - pods
  - pods/log
  - replicationcontrollers
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  - apps
  resources:
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.istio.io
  - networking.istio.io
  - authentication.istio.io
  - rbac.istio.io
  - security.istio.io
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
- apiGroups:
  - monitoring.kiali.io
  resources:
  - monitoringdashboards
  verbs:
  - get
  - list

**Comment by shinynz** [comment]
kind: ClusterRole
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{},"labels":{"app":"kiali","install.operator.istio.io/owning-resource":"installed-state","operator.istio.io/component":"AddonComponents","operator.istio.io/managed":"Reconcile","operator.istio.io/version":"1.6.0","release":"istio"},"name":"kiali-viewer"},"rules":[{"apiGroups":[""],"resources":["configmaps","endpoints","namespaces","nodes","pods","pods/log","replicationcontrollers","services"],"verbs":["get","list","watch"]},{"apiGroups":["extensions","apps"],"resources":["deployments","replicasets","statefulsets"],"verbs":["get","list","watch"]},{"apiGroups":["autoscaling"],"resources":["horizontalpodautoscalers"],"verbs":["get","list","watch"]},{"apiGroups":["batch"],"resources":["cronjobs","jobs"],"verbs":["get","list","watch"]},{"apiGroups":["config.istio.io","networking.istio.io","authentication.istio.io","rbac.istio.io","security.istio.io"],"resources":["*"],"verbs":["get","list","watch"]},{"apiGroups":["monitoring.kiali.io"],"resources":["monitoringdashboards"],"verbs":["get","list"]}]}
  creationTimestamp: "2020-04-16T02:11:07Z"
  labels:
    app: kiali
    install.operator.istio.io/owning-resource: installed-state
    operator.istio.io/component: AddonComponents
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.6.0
    release: istio
  managedFields:
  - apiVersion: rbac.authorization.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations: {}
        f:labels:
          .: {}
          f:app: {}
          f:operator.istio.io/component: {}
          f:operator.istio.io/managed: {}
          f:release: {}
      f:rules: {}
    manager: kubectl
    operation: Update
    time: "2020-05-15T03:38:39Z"
  - apiVersion: rbac.authorization.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          f:install.operator.istio.io/owning-resource: {}
          f:operator.istio.io/version: {}
    manager: istioctl
    operation: Update
    time: "2020-05-22T03:06:31Z"
  name: kiali-viewer
  resourceVersion: "9776341"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/kiali-viewer
  uid: 1c30b95d-799e-47a0-b1c5-f923ccd42c1e
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - namespaces
  - nodes
  - pods
  - pods/log
  - replicationcontrollers
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  - apps
  resources:
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.istio.io
  - networking.istio.io
  - authentication.istio.io
  - rbac.istio.io
  - security.istio.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.kiali.io
  resources:
  - monitoringdashboards
  verbs:
  - get
  - list

**Comment by shinynz** [comment]
I0617 06:58:07.436157       1 kiali.go:66] Kiali: Version: latest, Commit: 1f7edad56004e2ec317d58dc845a7f7dbf6166ba
I0617 06:58:07.437164       1 kiali.go:205] Using authentication strategy [openid]
I0617 06:58:07.437232       1 kiali.go:87] Kiali: Console version: 1.20.0-edge
I0617 06:58:07.437264       1 kiali.go:284] Updating base URL in index.html with [/kiali]
I0617 06:58:07.437815       1 kiali.go:265] Generating env.js from config
I0617 06:58:07.444278       1 server.go:67] Server endpoint will start at [:20001/kiali]
I0617 06:58:07.444311       1 server.go:68] Server endpoint will serve static content from [/opt/kiali/console]
I0617 06:58:07.444337       1 metrics_server.go:18] Starting Metrics Server on [:9090]

**Comment by jmazzitelli** [comment]
@shinynz I think you misunderstood what we asked for. When we say "Kiali CR" we do NOT mean the cluster role. We are looking for the custom resource that configures Kiali - the resource that tells the Kiali Operator how to configure Kiali (including the OpenID configuration). An [example of a Kiali CR is this](https://github.com/kiali/kiali-operator/blob/v1.18.0/deploy/kiali/kiali_cr.yaml). Usually it is found in the `kiali-operator` namespace if you installed the Kiali operator using the [Getting Started instructions](https://kiali.io/documentation/latest/getting-started/#_quick_install).

Since you did not indicate how you installed Kiali in your description, we can only assume you used the Kiali Operator and thus the Kiali CR would be the place where your configuration is located. If, however, you installed Kiali using the upstream Istio istioctl installer, you should attach your Kiali ConfigMap yaml which is located in the Istio control plane namespace (e.g. `istio-system`) - but in that case, I wonder how OpenID integration can work because the OpenID configuration is not integrated in the istioctl installer's kiali helm charts. This is why I think you installed Kiali using the Kiali Operator (though, again, you did not mention it in the description, so I am guessing here).

Also, this is just to point out a discrepency in your description -- you say you have Kiali 1.19, however, in the logs, it shows you are running a "latest" build from master branch (see the log messages "Kiali: Version: latest, Commit: 1f7edad" and "Kiali: Console version: 1.20.0-edge"). Not sure if that will matter, but this is something for the devs to know when trying to analyze the problem.

**Comment by shinynz** [comment]
Oh, I deployed kiali with istio, just updated the image version of kiali to the latest

**Comment by shinynz** [comment]
kiali configmap

{
	"config.yaml": "istio_component_namespaces:
		  grafana: istio-system
		  tracing: istio-system
		  istiod: istio-system
		  prometheus: istio-system
		istio_namespace: istio-system
		auth:
		  strategy: openid
		  openid:
		    client_id: \"kubernetes\"
		    issuer_uri: \"https://keycloak.xxx.com/auth/realms/xxx\"
		deployment:
		  accessible_namespaces: ['**']
		login_token:
		  signing_key: \"5OkTaYeNIv\"
		server:
		  web_root: /kiali
		external_services:
		  istio:
		    url_service_version: http://istiod.istio-system:15014/version
		  tracing:
		    url: http://tracing.xxx.com
		    in_cluster_url: http://tracing/jaeger
		  grafana:
		    url: http://grafana.xxx.com
		    in_cluster_url: http://grafana:3000
		  prometheus:
		    url: http://prometheus.istio-system:9090"
}

**Comment by jmazzitelli** [comment]
I don't see the indentation in your ConfigMap post - but double check that. (note, in github, you can maintain indentation by wrapping code in "triple-`" characters... like this:
```
we_need:
  to_see:
    your_indentation:
```

Specifically, make sure the "openid" section is UNDER the "auth" section, not at the same level ... should look something like this:

```
  auth:
    strategy: openid
    openid:
      client_id: kubernetes
      ...and the rest here...
```

**Comment by israel-hdez** [comment]
@shinynz Make sure to change your `signing_key` in the Kiali CR. That value is supposed to be secret and you just exposed it ;)

**Comment by israel-hdez** [comment]
@jmazzitelli Like with the `web_root`, `web_schema` and `web_port` [configs](https://github.com/kiali/kiali-operator/blob/master/deploy/kiali/kiali_cr.yaml#L694-L712) which are meant to setup "public facing" values, we may need a `web_port` config value to avoid bad guessing. I think a wrong port guessing the issue in this case. Also, we could change the [GuessKialiURL function](https://github.com/kiali/kiali/blob/master/util/httputil/http_util.go#L124-L132) to use default ports (80 or 443) when the port is absent in the request.

**Comment by jmazzitelli** [comment]
@israel-hdez hmmm... ok.

**Comment by israel-hdez** [comment]
@shinynz My suggestion, for now, is that you configure your load balance to add an `X-Forwarded-Port` HTTP header with the right port value.

**Comment by jmazzitelli** [comment]
@israel-hdez looks like we have a community PR submission that might fix this - see: https://github.com/kiali/kiali/pull/2919

**Comment by israel-hdez** [comment]
@shinynz A fix was just merged. Since you are using `latest` force a pull on your cluster to get the fix and check if it works for your case.

By the way, `latest` is a development image. I recommend you to not use `latest` and, instead, use a tagged version.

**Comment by shinynz** [comment]
@israel-hdez  How to set up x-forward-port with istio

**Comment by israel-hdez** [comment]
@shinynz I don't think Istio needs to be involved, but if  you are really using Istio to route traffic to Kiali, read https://istio.io/latest/docs/reference/config/networking/virtual-service/#HTTPRouteDestination.
