### ISSUE TITLE
Click on namespace labels crashes

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#2904]
Enable overview table view:
![image](https://user-images.githubusercontent.com/1662329/84647414-b5ea1100-af03-11ea-8824-c147e8a2d478.png)

Click on a label:
![image](https://user-images.githubusercontent.com/1662329/84647439-bedae280-af03-11ea-98d6-4b96f89f12f3.png)

**Comment by hhovsepy** [comment]
@lucasponce you mean the Kiali page crashes when clicking or it does nothing and error is displayed in console?

**Comment by lucasponce** [comment]
> @lucasponce you mean the Kiali page crashes when clicking or it does nothing and error is displayed in console?

I click in a label, and after a couple of seconds it crashes. Is the same behaviour you see ?

**Comment by hhovsepy** [comment]
What is see is only error in console:
"TypeError: i.current is nullmain.eb6cb550.chunk.js:1:122984"
