### ISSUE TITLE
Replace Glide with GoModules

### ISSUE THREAD

**Issue by israel-hdez** [kiali/kiali#2909]
At the beginning of the Kiali project, it was chosen to use [Glide](https://github.com/Masterminds/glide) as the dependency management tool. The other available option was [dep](https://github.com/golang/dep) and [godep](https://github.com/tools/godep).

When this decision of using Glide was done, the official kubernetes go client didn't support dep, godep was old, and glide was quite popular (see [kubernetes go client install instructions of those days](https://github.com/kubernetes/client-go/blob/c8e76297e14d9bd6b03caf5f280ece32e6be7cee/INSTALL.md)).  So, Glide was an easy choice (see [Jira KIALI-79](https://issues.redhat.com/browse/KIALI-79))

Nowadays, [glide is _mostly_ unmaintained (last commit July 2019)](https://github.com/Masterminds/glide#go-modules), godep project is archived/abandoned, and [dep apparently never graduated from being an experiment](https://github.com/golang/dep#dep). 

[Golang's wiki states that GoModules are production-ready since go1.14](https://github.com/golang/go/wiki/Modules), and both Glide and dep state in their repository readmes that the Go community has adopted GoModules for dependency management. Additionally, the [current install instructions of the official kubernetes go client](https://github.com/kubernetes/client-go/blob/31e286ee1926a84e0bfd4c8c8c77b3816f98244a/INSTALL.md) no longer mentions depencency tools other than GoModules.

Migration to GoModules looks quite fair to do when looking at how the dependency management has evolved through these two years of Kiali since Glide was chosen. Also, regarding our CI tools, Snyk is supporting only GoModules and migrating to that system will help on better dependency analysis.

**Comment by jotak** [comment]
Do you know what go modules can offer and that would be interesting for us?
One thing that comes to my mind, for instance, is it able to fetch just a subtree of dependency and/or manages exclusion of subtrees? I'm thinking about how we import k-charted into kiali, as k-charted is monorepo, we end up having frontend code in backend vendoring. Same for Jaeger dependency.

**Comment by jshaughn** [comment]
> we end up having frontend code in backend vendoring. Same for Jaeger dependency.

+1, just recently we got a security violation for th jaeger dep, but it's in the UI code and has nothing to do with our backend needs.

I'd be +1 for a move to GoModules if it can solve these sorts of issues (which would also reduce the size of our vendor deps I guess).

**Comment by israel-hdez** [comment]
I think it's subjective, but talking about my thoughts, this is what I like:
* GoModules is integrated with the go tools. You just download the framework and you have all what you need. No need to install 3rd party tools.
  * Because it's integrated, `go get` will automatically update the dependencies file.
  * You event don't need to invoke `go get` in advance. You could just import the dependency in the code and when building go will automatically resolve the dep and add it to the dependency file.
* The need to adhere to the `$GOPATH` structure is suppressed. It will be possible to checkout the Kiali code in whatever directory is preferred.
* Vendorizing dependencies is no longer needed because GoModules records a hash when dependencies are added ensuring that other people will fetch the same code by comparing the hash of the fetched dependency against what is stored in the checksums file. 
  * The downside is that this for the builds we are assuming the existence of `vendor/`.
* The possibility to check which dependencies are unused and remove them. 
* Looks like GoModules resolves dependencies mainly from the dependency file, while glide does it mostly from looking at `import` statements (apparently also true when resolving sub-dependencies). So, probably, there is less "guessing" about what version of sub-deps to fecth.

About sub-trees, I don't think that's possible because I see  that when resolving deps it checks out all the code; but this seems to be true only about the local "cache". When creating the `vendor/` folder, apparently the `go mod vendor` command is adding only referenced code, so it probably won't include the front-end code -- and that would also mean that if a big module is imported, only a subset of it may be added to the `vendor/` folder. Obviously, If we choose to no longer check-in the `vendor/` folder, we are already getting rid of the unwanted front-end code from the Kiali repo :-)

**Comment by jshaughn** [comment]
Seems like a lot of good reasons to change.  I'm +1.

**Comment by israel-hdez** [comment]
Starting this sprint, but targeting for merge on 1st week for sprint #42.
