### ISSUE TITLE
Service "box" is not shown correctly

### ISSUE THREAD

**Issue by pavolloffay** [kiali/kiali#291]
I have deployed https://github.com/redhat-developer-demos/istio-tutorial with istio 0.7.1.

Deploy all servies - customer, preference, recommendation - in both versions.  Do not create requests to customer! Go to kiali console to show the service graph. The box for the recommendation service is not shown correctly. 

If you fail to reproduce, try to remove p8s pod and go to Kiali UI. The error should be present.

![screenshot of kiali console 1](https://user-images.githubusercontent.com/5618424/41473236-f86dd100-70b8-11e8-944f-824e27a03ed9.jpg)

**Comment by jshaughn** [comment]
Ho @pavolloffay , this does look strange.  If you see this again can you try and capture the backend JSON and send it to me?  To do that:

<host>/api/namespaces/<namespace>/graph

You can also use a duration queryParam, So, for the above you'd have;

<host>/api/namespaces/tutorial/graph?duration=7d

**Comment by pavolloffay** [comment]
Another strange box view when I deleted p8s pod.

![fmdw6oz](https://user-images.githubusercontent.com/5618424/41624597-832eb93e-7416-11e8-86b5-0848320e81cc.jpg)

```json
{
  "timestamp": 1529442573,
  "elements": {
    "nodes": [
      {
        "data": {
          "id": "80c2e74be9c24effcaf63df866f8f02d",
          "service": "customer.tutorial.svc.cluster.local",
          "version": "v1",
          "isUnused": "true"
        }
      },
      {
        "data": {
          "id": "3a6f44d451df1f5a243e1f362c3e8913",
          "service": "preference.tutorial.svc.cluster.local",
          "version": "v1",
          "isUnused": "true"
        }
      },
      {
        "data": {
          "id": "8597eddc2177038ad2c4e10f77cf0a5c",
          "service": "recommendation.tutorial.svc.cluster.local",
          "isGroup": "version"
        }
      },
      {
        "data": {
          "id": "b9f6ecceebe39b36572e0a82b53f5884",
          "parent": "8597eddc2177038ad2c4e10f77cf0a5c",
          "service": "recommendation.tutorial.svc.cluster.local",
          "version": "v1",
          "isUnused": "true"
        }
      },
      {
        "data": {
          "id": "4e61b3319af876649637307cca33b19b",
          "parent": "8597eddc2177038ad2c4e10f77cf0a5c",
          "service": "recommendation.tutorial.svc.cluster.local",
          "version": "v2",
          "isUnused": "true"
        }
      }
    ],
    "edges": []
  }
}
```

**Comment by jmazzitelli** [comment]
this will be fixed when this is: https://issues.jboss.org/browse/KIALI-1258

**Comment by jmazzitelli** [comment]
This should be fixed by this: https://github.com/kiali/kiali/pull/381

**Comment by pilhuhn** [comment]
@pavolloffay Can you check with v0.6.0 image of Kiali?

**Comment by jshaughn** [comment]
@pilhuhn I'm quite sure this is resolved.
