### ISSUE TITLE
FAQ docs are not versioned

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#2910]
Go to the masthead of kiali.io, and notice there is an FAQ link. As per previous discussions, I understand the masthead links are only ever supposed to go to the "latest" docs.

However, I do not see the FAQ archived. If I go to https://kiali.io/documentation/ and click a version (say, [v1.18](https://kiali.io/documentation/v1.18/)) I do not see a way to get to the older FAQs.

We need a way to version FAQs so we can deprecate/remove FAQ entries that are no longer valid for a new version, but yet retain history for older version references.

**Comment by jshaughn** [comment]
This was proving difficult and I don't think it's worth the time given that we have never removed a FAQ entry.  If anyone thinks they can solve this quickly please feel free to re-open.
