### ISSUE TITLE
Add custom label aggregation in metrics tab

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#2911]
Similar to https://github.com/kiali/kiali/issues/2854 , but for metrics pages.
These would just be new labels to aggregate on in metrics pages.

Actually, we could allow to configure any list of custom labels to aggregate on, in addition to the pre-configured static ones. In terms of implementation, much of the mechanisms are already in place, we would just have to add a little bit of mapping between config and k-charted dashboard generation.

**Comment by jshaughn** [comment]
> Actually, we could allow to configure any list of custom labels to aggregate on

Yes, I think this will be a really nice feature for the metric charts and I think can be added independently of the graph work.

**Comment by lucasponce** [comment]
As it's commented on https://github.com/kiali/kiali/issues/2911#issue-640199767 the labels used by aggregation in istio metrics tabs are static and defined in code:

```
func buildIstioAggregations(local, remote string) []Aggregation {
	aggs := []Aggregation{
		{
			Label:       fmt.Sprintf("%s_canonical_revision", local),
			DisplayName: "Local version",
		},
		{
			Label:       fmt.Sprintf("%s_workload_namespace", remote),
			DisplayName: "Remote namespace",
		},
	}
	if remote == "destination" {
		aggs = append(aggs, Aggregation{
			Label:       "destination_service_name",
			DisplayName: "Remote service",
		})
	}
	aggs = append(aggs, []Aggregation{
		{
			Label:       fmt.Sprintf("%s_canonical_service", remote),
			DisplayName: "Remote app",
		},
		{
			Label:       fmt.Sprintf("%s_canonical_revision", remote),
			DisplayName: "Remote version",
		},
		{
			Label:       "response_code",
			DisplayName: "Response code",
		},
		{
			Label:       "grpc_response_status",
			DisplayName: "GRPC status",
		},
		{
			Label:       "response_flags",
			DisplayName: "Response flags",
		},
	}...)
	return aggs
}
```

These labels are good, also the metrics tab is an opinionated dashboard and it's not expected that user can personalize it (other tools as grafana are better for that task).

But I agree that these static labels can be extended, so, this issue could be used to add a new section in the configuration to support additional label aggregations. 

Then user may filter some metrics by an additional criteria (i.e. "istio_io_rev" to get the control plane when user is performing some canary A/B upgrade or similar).

So the goal of this task could be:
- Add a new section in the config (+operator) to add this new labels.
- Update the static section to read the aggregated labels defined in the config.
- Validate that this new label can be used from the "Show metrics by" control in the metrics tab.

![image](https://user-images.githubusercontent.com/1662329/128347970-3c4d4a2c-91c0-4379-9f4d-f30f4ab97a01.png)
