### ISSUE TITLE
Separate graph nodes for service entries that refer to the same hostname

### ISSUE THREAD

**Issue by jwurm** [kiali/kiali#2914]
This refers to this issue: https://groups.google.com/forum/#!topic/kiali-dev/4MpqIbN8IaA

Use case: 
ServiceEntries are being used to enable connections to resources outside of the mesh.
Several of these resouces use the same hostname, they only differ by their port. 

E.g. 
ServiceEntry MyWebService: example.com:443
ServiceEntry MyPostgresDB: example.com:5432
ServiceEntry MyMongoDB:   example.com:27017

Those serviceentries may refer to e.g. a loadbalancer that forwards the traffic to different backend applications based on the port.

Kiali (v1.19) currently displays those as only a single ServiceEntry graph node, apparently because they all share the same host name, and cycles through the names of the associated ServiceEntry objects with every refresh of the graph display.

It would be nice to have one graph node per serviceEntry object instead of one graph node per hostname, as these represent distinct resources outside of the mesh.

Thank you!

**Comment by jshaughn** [comment]
@jwurm I think the problem we have here is the lack of port information in the istio metrics.  Without the port we can't narrow down the exact match.  Can you confirm that the port is not available in the telemetry?  Do you know how to look at Prometheus?  You can ususally bring up the Prom UI via:

`> istioctl dashboard prometheus`

From there you can try a query like:

`sum(istio_requests_total{destination_service=~"^.*example\\.com.*$"}) by (destination_service, destination_service_name)`

Unless the destination_service provides the port I'm not exactly sure what we can do. Let me know what you see, thanks.

**Comment by jwurm** [comment]
Hello!

The result looks like this, it doesn't seem to contain port information:

{destination_service="example.com",destination_service_name="example.com"}	59

:-(

Thanks for you help!

**Comment by jshaughn** [comment]
@jwurm I'm going to ask about this in Istio Slack to see if they have a suggestion...

**Comment by jshaughn** [comment]
@jwurm So the destination_port information is available with a little extra configuration to add it to the metrics.  If provided Kiali could possible delive what you are looking for.  Would you be willing to do the extra configuration if Kiali used the port info?

**Comment by jwurm** [comment]
@jshaughn Thanks so much for your help! What do i have to configure?

**Comment by jshaughn** [comment]
@jwurm To be clear, even if you configure it Kiali won't currently use the information.  But if you want to try and see if the port information gets reported correctly, see [here](https://istio.io/latest/docs/tasks/observability/metrics/customize-metrics/).   The example actually shows the destination_port being added (just ignore the request_host part).  If you get it working let me know...

**Comment by jwurm** [comment]
I didnt get to this yet, but it's not forgotten.

**Comment by jshaughn** [comment]
@jwurm No problem, it's the same on this side, I have not yet done anything to utilize the destination_port information if it is configured.  When you do get the chance let me know if it is getting reported correctly, and if so I can take a look at using it.

**Comment by jshaughn** [comment]
I did a little bit of research into this one and, assuming the destination_port information is correctly supplied by Istio,  it is a decent amount of work to get this in.  I think it would roughly mean:
- capturing destination_port in the request queries
- Either:
  - adding port into service nodes as part of their key, as it would now be a defining characteristic
    - namespace-a:serviceName-a:port-1 is different than namespace-a:serviceName-a:port-2
  - collecting all of the ports used with the service and storing with the service
     - namespace-a:serviceName-a, ports=[1,2]
- using the port info in the service_entry appender to potentially generate distinct service entries

**Comment by erSitzt** [comment]
Would be nice to have this information in the graph if istio supplies the destination_port.
I can't currently test the custom metrics i guess, as i'll be stuck on istio 1.5.9 for a little while until i'm ready to upgrade rancher to 2.5.x

**Comment by jshaughn** [comment]
This hasn't seen any follow-up, although potentially useful, closing as stale.  Can be re-opened by request.
