### ISSUE TITLE
Label operation - Refresh resets the value

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#2920]
Happens on Kiali master.

List workloads.
Filter by 2 labels.
Select "Label Operation" value "and".
Refresh the page via browser refresh.
The Label Operation is reset, because of params are updated wrongly in browser address bar.

![Screenshot from 2020-06-19 18-10-33](https://user-images.githubusercontent.com/604313/85155105-a0088300-b258-11ea-963c-385b706a180a.png)

**Comment by lucasponce** [comment]
cc @aljesusg
