### ISSUE TITLE
Wizard to create AuthorizationPolicy based on the graph of the current traffic

### ISSUE THREAD

**Issue by olaf-meyer** [kiali/kiali#2924]
**Is your feature request related to a problem? Please describe.**
From my experience, AuthorizationPolicies are usually created to match the traffic at a certain time between services and deny all other traffic. 

**Describe the solution you'd like**
Would it be possible to create a wizard for AuthorizationPolicy that is based on the graph in Kiali? By this, the manual mapping of the graph can be skipped and a user only needs to adjust the resources instead of creating them from scratch.

**Describe alternatives you've considered**
Creating a way to export the graph in a text form as YAML or JSON, so that it can be transformed into other resources like AuthorizationPolicy

**Additional context**

**Comment by lucasponce** [comment]
Thanks @olaf-meyer.
We have had some discussions in a very similar topic and it makes all of sense.

Also, we are looking for feedback like this for more high level additions on the Wizards area.

**Comment by jshaughn** [comment]
@olaf-meyer @lucasponce This is a good idea, it sounds similar to https://github.com/kiali/kiali/issues/1542.

**Comment by olaf-meyer** [comment]
Please let me know, if you need a tester.

**Comment by lucasponce** [comment]
@olaf-meyer count on it :-) thanks 

We are actively working on Wizards area on these sprints, so, I will update the issue soon.

**Comment by jshaughn** [comment]
@lucasponce Assigning you and adding to backlog just to keep on the radar.

**Comment by lucasponce** [comment]
I'm actively working on this one, but I guess we need to propagate a couple of fields coming from the Istio prometheus.
Basically from the graph, Kiali should have access to the "source_principal" and "destination_principal" fields.

![image](https://user-images.githubusercontent.com/1662329/93124901-a036e400-f6ca-11ea-9992-f2589cfe1ad0.png)
With those fields, from the telemetry we could generate AuthorizationPolicy resources per namespace "lock-in" the current traffic.

I guess most straightforward way is to add those fields in the graph (even if those are not used), other alternatives, like using Sidecars or trying to lock by IPs are costly and less standard.

So, goal would be to have those fields mapped into the "GraphDefinition" object used to fetch telemetry in the UI.

cc @jshaughn

**Comment by jshaughn** [comment]
I don't love the idea of always pulling info into the graph data that may infrequently, or never get used.  When we have this sort of situation we often add an option, or something to trigger the additional info server-side, like we do for response time info, security info, etc.  Perhaps we could do something similar for this, and when the user actually needs this information and activates the feature, we pull graph data that includes what's needed.  Does that sound reasonable?  If so we could potentially add an appender to to append on this extra information on-demand.

**Comment by lucasponce** [comment]
> Does that sound reasonable? If so we could potentially add an appender to to append on this extra information on-demand.

Perhaps this should be part of the security appender and being invoked when showSecurity flag is on.

If that works, perfect, but yes, a flag to pull this info it's ok.
