### ISSUE TITLE
OpenId authorization with Auth0

### ISSUE THREAD

**Issue by mikolajwrzesinski** [kiali/kiali#2925]
**Describe the bug**

I'm trying to configure openid authorization using Auth0. I'm already using Auth0 to authorize a cluster. Kiali has been set to openid auth strategy with the same data as the cluster. It looks like Auth0 implicit flow doesn't return all the data Kiali wants. 

https://auth0.com/docs/flows/concepts/implicit

![104439120_570255956992565_1761605522059263736_n](https://user-images.githubusercontent.com/8101457/85363543-815e0100-b564-11ea-8a39-51bdcfd6aa0c.png)

Auth0 returns only `id_token` after successfull login but `OAuthLogin` service expects `access_token` hash parameter.
```
if (window.location.hash.startsWith('#access_token')) {
  return AuthResult.CONTINUE;
} else {
  return AuthResult.HOLD;
}
```
It is possible for Auth0 to return both `id_token` and `access_token`, but then different `response_type` must be used.

![104768864_266348537924540_2134122429249052415_n](https://user-images.githubusercontent.com/8101457/85364370-55437f80-b566-11ea-822e-5afec6adc5e3.png)

Going deeper into code I can see that this parameter is hardcoded in the backend `handers/authentication.go` 

```
redirectUri := fmt.Sprintf("%s?client_id=%s&response_type=id_token&redirect_uri=%s&scope=%s&nonce=%s",
	authorizationEndpoint,
	url.QueryEscape(conf.Auth.OpenId.ClientId),
	url.QueryEscape(httputil.GuessKialiURL(r)),
	url.QueryEscape(scopes),
	url.QueryEscape(fmt.Sprintf("%x", nonceHash)),
)
```

**Versions used**
Kiali: 1.19
Istio: 1.6.3
Kubernetes flavour and version: vanilla 1.18.3

**To Reproduce**
Setup Kiali to use openid auth startegy with Auth0 provider.

**Expected behavior**
Kiali shoud authenticate the user only with `id_token`, just like Kubernetes cluster.

**Comment by jshaughn** [comment]
cc @israel-hdez , @jmazzitelli

**Comment by israel-hdez** [comment]
Essentially, the front-end is blocking the authentication because of the missing `access_token`, which shouldn't be required for OpenId.

OK, I'll fix this.

**Comment by israel-hdez** [comment]
@mikolajwrzesinski The fix is going to be released today in Kiali v1.20.

**Comment by mikolajwrzesinski** [comment]
That's great news. Thank you :)

**Comment by mikolajwrzesinski** [comment]
I tested the patch and the error was not resolved completely. The process went on, but now there is one more thing in the backend. Auth0 returns only one parameter `id_token` in the callback when you use `response_type=id_token`. Kiali backend expects one more parameter: `expires_in` in the `/authenticate` call. This parameter by spec is related to `access_token`, so if we are asking only for `id_token`, it shouldn't be taken into account.
Since the `id_token` is decoded anyway, why don't you use `exp` claim to validate?

**Comment by mikolajwrzesinski** [comment]
I tested the fix using Keycloak and there is the same issue. Authentication response only includes `id_token` and optionally `session_state`. There is no field `expires_in`.

**Comment by israel-hdez** [comment]
Hi, @mikolajwrzesinski 
I just created issue #2954.

You are right that `expires_in` parameter shouldn't be required. Sorry for the headache. I'll fix the problem this week so that you can try again using this fridays snapshot (in case you are comfortable with snapshot releases).

**Comment by mikolajwrzesinski** [comment]
No worries. I'm glad I could help.
