### ISSUE TITLE
Have the same semantics when return data

### ISSUE THREAD

**Issue by aljesusg** [kiali/kiali#2926]
https://github.com/kiali/kiali/blob/master/handlers/config.go  VS https://github.com/kiali/kiali/blob/master/config/config.go

```go
type PublicConfig struct {
	Extensions               Extensions                      `json:"extensions,omitempty"`
	HealthConfig	         config.HealthConfig             `json:"healthConfig,omitempty"`
	InstallationTag          string                          `json:"installationTag,omitempty"`
	IstioStatusEnabled       bool                            `json:"istioStatusEnabled,omitempty"`
	IstioIdentityDomain      string                          `json:"istioIdentityDomain,omitempty"`
	IstioNamespace           string                          `json:"istioNamespace,omitempty"`
	IstioComponentNamespaces config.IstioComponentNamespaces `json:"istioComponentNamespaces,omitempty"`
	IstioLabels              config.IstioLabels              `json:"istioLabels,omitempty"`
	IstioTelemetryV2         bool                            `json:"istioTelemetryV2"`
	Prometheus               PrometheusConfig                `json:"prometheus,omitempty"`
}
```

vs 

```go
type Config struct {
	AdditionalDisplayDetails []AdditionalDisplayItem  `yaml:"additional_display_details,omitempty"`
	API                      ApiConfig                `yaml:"api,omitempty"`
	Auth                     AuthConfig               `yaml:"auth,omitempty"`
	Deployment               DeploymentConfig         `yaml:"deployment,omitempty"`
	Extensions               Extensions               `yaml:"extensions,omitempty"`
	ExternalServices         ExternalServices         `yaml:"external_services,omitempty"`
	HealthConfig             HealthConfig             `yaml:"health_config,omitempty"`
	Identity                 security.Identity        `yaml:",omitempty"`
	InCluster                bool                     `yaml:"in_cluster,omitempty"`
	InstallationTag          string                   `yaml:"installation_tag,omitempty"`
	IstioComponentNamespaces IstioComponentNamespaces `yaml:"istio_component_namespaces,omitempty"`
	IstioLabels              IstioLabels              `yaml:"istio_labels,omitempty"`
	IstioNamespace           string                   `yaml:"istio_namespace,omitempty"` // default component namespace
	KubernetesConfig         KubernetesConfig         `yaml:"kubernetes_config,omitempty"`
	LoginToken               LoginToken               `yaml:"login_token,omitempty"`
	Server                   Server                   `yaml:",omitempty"`
}
```

We return with a bar to separate words in somePlaces
`LoginToken               LoginToken               `yaml:"login_token,omitempty"`` and in others upperCase
`IstioNamespace           string                          `json:"istioNamespace,omitempty"``

We should return items with the same style

**Comment by lucasponce** [comment]
I think this is due some format is used for 'yaml' and other for 'json' formats.

Having that difference doesn't sound as bad, specially as json responses are parsed directly into objects in the UI, and otherwise there would need additional parsing logic.

**Comment by aljesusg** [comment]
the point is that in the UI we are parsing yaml and json so...Are we ok with this difference?

**Comment by lucasponce** [comment]
I'm ok to use this issue as a maintenance task to review this.

For sure there are areas to improve this, but there are some automatic parsing from/to yaml/json to the models and that was the root of this differences.

**Comment by jmazzitelli** [comment]
This is the difference between camelCase and snake_case.. and I can tell you it isn't trivial to expect the Kiali CR (and hence the ConfigMap) to use camelCase because the operator SDK converts everything to snake_case when running the Ansible playbook. This actually causes some issues that we had to work around and I was surprised that this snake_case conversion happened, but suffice it to say, Kiali CR and the ConfigMap should remain snake_case, or else some major refactoring will have to be done in the operator in order to workaround what is in effect a feature of the ansible operator SDK (the conversion of all settings to use snake_case).

**Comment by jmazzitelli** [comment]
See:

https://docs.openshift.com/container-platform/4.4/operators/operator_sdk/osdk-ansible.html#osdk-building-ansible-operator_osdk-ansible

```
The names of all variables in the spec field are converted to snake case
(lowercase with an underscore) by the Operator before running Ansible.
For example, serviceAccount in the spec becomes service_account
in Ansible.
```

**Comment by jotak** [comment]
@jmazzitelli I don't think we want to change all our config YAML anyway :-) We just stick to the conventions.

So, should we close this issue, or are there some places where there is actually a problem? (for the example given here about config, it seems everything is fine?)

**Comment by lucasponce** [comment]
Outdated.
Closing in favor to open a new one for more specific case if needed.
