### ISSUE TITLE
Display information about Jaeger Traces in Span Chart

### ISSUE THREAD

**Issue by aljesusg** [kiali/kiali#2927]
We want to display information about the span in the scatterplot . So we can let personalize the tooltip in mouseover to show this information.

Related with https://github.com/kiali/k-charted/issues/65

**Comment by lucasponce** [comment]
Outdated.
There was some work on the tooltip of the span, showing # spans, average and correlation with istio metrics:
![image](https://user-images.githubusercontent.com/1662329/128351624-67aa1c85-0591-437a-9ca0-c25b916e3237.png)
