### ISSUE TITLE
[RS] k-charted edition mode

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#2928]
(was previously https://github.com/kiali/k-charted/issues/46 )

An "edit view" could be added to k-charted to allow metrics exploration and customization without having to write a CR (à la Grafana).

When permissions are granted, this could also be saved as a CR. It could be a more intuitive way to create monitoringdashboard resources.

**Comment by lucasponce** [comment]
I don't think in the short term Kiali is going to explore to compose custom dashboards from the UI.
I guess that scenario could be delegated in Grafana.

But I think that we'll keep adding pre-defined scenarios putting together multiple signals in the context of the ServiceMesh domain.

I put the "future" label, but in the context of the revision I'm going to close it for now.
We can revisit in future planning.
