### ISSUE TITLE
Let Threshold Chart in k-charted. it would be great for new healthConfigs

### ISSUE THREAD

**Issue by aljesusg** [kiali/kiali#2929]
Storybook: https://patternfly-react.surge.sh/documentation/react/charts/chartthreshold

**Comment by lucasponce** [comment]
Related to scalability https://github.com/kiali/kiali/discussions/4080

When model is consolidated in the backend, probably we can open the user experience to configure the health from a graphical view, but today there are open topics around this.

So, I'll close this and consider this part of the generic discussion.
