### ISSUE TITLE
Invalid OIDC "/authorize" request due to missing state param

### ISSUE THREAD

**Issue by asmith60** [kiali/kiali#2933]
**Describe the bug**
When using the `openid` auth strategy I receive the following error from my IDP (Okta):

```error=invalid_request&error_description=The+authentication+request+has+an+invalid+%27state%27+parameter```

I see in the `/authorize` request that the `state` parameter is not included. Many IDPs (including Okta) require the `state` parameter to be present. See [Okta's docs](https://developer.okta.com/docs/reference/api/oidc/#parameter-details) for their explanation (scroll down to the `state parameter description`).

**Versions used**
Kiali: v1.19
Istio: v1.6.2
Kubernetes flavour and version: Kops on AWS v1.17.6

**To Reproduce**
1. Configure auth strategy to `openid` with appropriate supporting properties
2. Navigate to Kiali console in browser and click on "Log In With OpenID"

**Expected behavior**
Be logged in via OIDC without error

**Comment by israel-hdez** [comment]
@asmith60 is it possible for you to post the metadata of your IdP? I want to learn if the provider exposes in the metadata that `state` is required.

You can download it by going to `https://{your_issuer_uri}/.well-known/openid-configuration`.
Metadata should be public, so it should be safe to post. But if you are using a private IdP, feel free to mask any private data.

**Comment by asmith60** [comment]
I scrubbed some of the info, but I believe all of the relevant stuff should be there.

```json
{
    "response_types_supported": [
        "code",
        "id_token",
        "code id_token",
        "code token",
        "id_token token",
        "code id_token token"
    ],
    "response_modes_supported": [
        "query",
        "fragment",
        "form_post",
        "okta_post_message"
    ],
    "grant_types_supported": [
        "authorization_code",
        "implicit",
        "refresh_token",
        "password"
    ],
    "subject_types_supported": [
        "public"
    ],
    "id_token_signing_alg_values_supported": [
        "RS256"
    ],
    "scopes_supported": [
        "openid",
        "email",
        "profile",
        "address",
        "phone",
        "offline_access",
        "groups"
    ],
    "token_endpoint_auth_methods_supported": [
        "client_secret_basic",
        "client_secret_post",
        "client_secret_jwt",
        "private_key_jwt",
        "none"
    ],
    "claims_supported": [
        "iss",
        "ver",
        "sub",
        "aud",
        "iat",
        "exp",
        "jti",
        "auth_time",
        "amr",
        "idp",
        "nonce",
        "name",
        "nickname",
        "preferred_username",
        "given_name",
        "middle_name",
        "family_name",
        "email",
        "email_verified",
        "profile",
        "zoneinfo",
        "locale",
        "address",
        "phone_number",
        "picture",
        "website",
        "gender",
        "birthdate",
        "updated_at",
        "at_hash",
        "c_hash"
    ],
    "code_challenge_methods_supported": [
        "S256"
    ],
    "introspection_endpoint_auth_methods_supported": [
        "client_secret_basic",
        "client_secret_post",
        "client_secret_jwt",
        "private_key_jwt",
        "none"
    ],
    "revocation_endpoint_auth_methods_supported": [
        "client_secret_basic",
        "client_secret_post",
        "client_secret_jwt",
        "private_key_jwt",
        "none"
    ],
    "request_parameter_supported": true,
    "request_object_signing_alg_values_supported": [
        "HS256",
        "HS384",
        "HS512",
        "RS256",
        "RS384",
        "RS512",
        "ES256",
        "ES384",
        "ES512"
    ]
}
```

**Comment by israel-hdez** [comment]
@asmith60 OK, I see your IdP metadata does not have any indication of `state` parameter being required.

In the OpenID spec, I see it is a **recommended** value, but not mandatory (see https://openid.net/specs/openid-connect-core-1_0-final.html#AuthRequest). So, I think requiring `state` parameter was more an Okta's implementation decision.

It's anyway a recommended parameter, so I'll add it to fix your case.

**Comment by israel-hdez** [comment]
Re-labeling from `bug` to `enhancement` because the `state` parameter is not mandatory in the OpenID spec.

**Comment by asmith60** [comment]
Sounds good 👍 . Thanks @israel-hdez!

**Comment by danquack** [comment]
@asmith60 were you able to find a work around for this?

**Comment by asmith60** [comment]
@danquack I was not. I don't know that it is currently possible to use the OIDC auth strategy with an IdP that requires the `state` parameter

**Comment by israel-hdez** [comment]
This is fixed.
If you want to try straight away, use the image tag `latest` which is the *edge* build.
You could also wait until Friday for a snapshot, or wait until July 17th when version 1.21 should be released.

Please, note that there is also issue https://github.com/kiali/kiali/issues/2954, which may also prevent a successful authentication.
