### ISSUE TITLE
for ppc64le the travis build 

### ISSUE THREAD

**Issue by PradipPanigrahi** [kiali/kiali#2935]
**Is your feature request related to a problem? Please describe.**
The Travis ci build was failed due to the linter ppc64le .
make lint is not responding . 
make swagger-travis is also failed not responding during the build .
I am using the master branch of Kiali source code. 
your suggestion will help me more.

**Additional context**
I have added the log from the travis build for reference
$ make lint
golangci-lint run --skip-files "doc\.go" --tests --timeout 5m
level=warning msg="[runner] Can't run linter unused: buildssa: analysis skipped: errors in package: [/home/travis/gopath/src/github.com/PradipPanigrahi/kiali/doc.go:7:2: could not import github.com/kiali/kiali/business (doc.go:7:2: cannot find package \"github.com/kiali/kiali/business\" in any

**Comment by israel-hdez** [comment]
Hi @PradipPanigrahi 
One issue I see is that you are checking out Kiali code under `$GOPATH/src/github.com/PradipPanigrahi/kiali`. That's not right, it should be under `$GOPATH/src/github.com/kiali/kiali`. Most likely, this is the reason why it generates the `cannot find package "github.com/kiali/kiali/business"` error.

We will soon switch using go modules, and this constraint about where to checkout the code will be relaxed. But until then, you need to use that path.

**Comment by israel-hdez** [comment]
Closing as stale.

**Comment by israel-hdez** [comment]
...additionally, we no longer use Travis.
