### ISSUE TITLE
Show principals in topology graph

### ISSUE THREAD

**Issue by xeviknal** [kiali/kiali#2939]
At the moment you are wearing the security hat, and specially, building all the Authorization Policies it is really necessary to deal with principals (or spiffe IDs / service accounts).

It would be useful to show the 'source principal' for each item in the graph. Like what we have for hosts and codes in the sidepanel.
It is getting really crowded right there though.

![Screenshot of Kiali Console (5)](https://user-images.githubusercontent.com/613814/85873678-be7afb00-b7d1-11ea-859e-d506a66c6098.png)

![Screenshot of Kiali Console (6)](https://user-images.githubusercontent.com/613814/85873664-b7ec8380-b7d1-11ea-8cdb-c9ed819c01b9.png)

Prometheus already has the data:

```
istio_requests_total{connection_security_policy="mutual_tls",destination_app="details",destination_canonical_revision="v1",destination_canonical_service="details",destination_principal="spiffe://cluster.local/ns/bookinfo/sa/bookinfo-details",destination_service="details.bookinfo.svc.cluster.local",destination_service_name="details",destination_service_namespace="bookinfo",destination_version="v1",destination_workload="details-v1",destination_workload_namespace="bookinfo",instance="172.17.0.15:15090",job="envoy-stats",namespace="bookinfo",pod_name="details-v1-6fc55d65c9-j4hkc",reporter="destination",request_protocol="http",response_code="403",response_flags="-",source_app="productpage",source_canonical_revision="v1",source_canonical_service="productpage",source_principal="spiffe://cluster.local/ns/bookinfo/sa/bookinfo-productpage",source_version="v1",source_workload="productpage-v1",source_workload_namespace="bookinfo"}
```

**Comment by jshaughn** [comment]
@lucasponce With the Principals now added to the security appender this one should be pretty easy.

**Comment by jshaughn** [comment]
@xeviknal @lucasponce Looking at this one more closely, I'm a little confused.  In Xavi's mock it seems he is suggesting that a single edge could have multiple source principals, is that true?  In our recent work for auth policy we are assuming an edge (unique source+dest+protocol) has a unique source and dest principal.  Is that a valid assumption?

**Comment by xeviknal** [comment]
@jshaughn you are right, there is only one principal per edge. The mock above is pretty wrong as I see it now. I thought it could make sense to show the error code split with the principal, but at the end, it would be exactly the same table as in the traffic tab + duplicated principals. So it doesn't make any sense.

Does it make sense then to show the source and destination principals in the edge panel and the principal in the node panel?
I am thinking the scenario where users are designing an AuthorizationPolicy and they want to know which principal has an specific service.

**Comment by jshaughn** [comment]
> Does it make sense then to show the source and destination principals in the edge panel and the principal in the node panel?

It absolutely makes sense, although I think we can limit to the edge side panel, showing both the source and destination principal.  I will add it to the sprint.
