### ISSUE TITLE
In kiosk mode，the main header should not be shown

### ISSUE THREAD

**Issue by gpscode** [kiali/kiali#2946]
**Describe the bug**
In kiosk mode，the main header should not be shown.

**Versions used**
Kiali: 1.18.2
Istio: 1.16.3
Kubernetes : 1.16.0

**To Reproduce**
In Chrome browser，open the url ： http://ip:port/kiali/console/services?kiosk=true，
like this：
![mainheader](https://user-images.githubusercontent.com/28925838/85979950-0b4e1400-ba14-11ea-9471-eea97689cbe2.png)
The main header is shown.

**Expected behavior**
Refering “Embedding Kiali” content，“If you want to embed Kiali in other applications, Kiali offers a simple feature called Kiosk mode. In this mode, **Kiali won’t show the main header**, nor the main navigation bar.”
The main header should not be shown.

**Comment by aljesusg** [comment]
Does it happen on the Graph page too?

**Comment by gpscode** [comment]
> Does it happen on the Graph page too?

Yes，it happen on the Graph、Application、Workload page and other page too

**Comment by aljesusg** [comment]
Ok let me address this
