### ISSUE TITLE
Add SRE style metrics in the Overview namespace chart

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#2947]
Reading https://www.openshift.com/blog/monitoring-services-like-an-sre-in-openshift-servicemesh , which gives some interesting promQL queries from istio metrics.

**Comment by maltron** [comment]
Giving Kiali is currently "Service Mesh Management for Istio", it's makes alot of sense to provide capabilities for SRE.

**Comment by aljesusg** [comment]
+100 for SRE !!!

**Comment by lucasponce** [comment]
The whole SRE concept is pretty open, but I share that we could add some changes in the Overview page to adapt some of the information that today is collected into the way that a SRE engineer may expect.

The Kiali Overview page is the main entry point and it shows the list of namespaces providing a summary of the state.
It has three views (expanded, compact and table), and the expanded and table view offer a chart with operations.

This chart is focused in the Requests per second, and it also adds information about the status of applications/workload/services:

![image](https://user-images.githubusercontent.com/1662329/128479952-fcb5d8c5-51b1-43ee-bb3b-0dcc78af5650.png)

I think we can use this issue to perform a couple of changes on this chart:

- Introduce another series in the existing chart, then we may have the global "Request Per Second" and we can introduce a 5xx series. Typically Global Success Rate or Global Service Indicator are some predefined ratio between these two. Instead to put an percentage, I think Kiali can show this serie in a first option.
- Introduce another chart with the latency of the requests, with two series (i.e. average and percentile 95), as the RPS is not enough for a summary and a user may want to identify any peak.

All this info is available in Kiali in other pages, but not used yet in the Overview, then with this information, the user may know which namespace(s) are candidate to perform the next step which could be to examine the Graph or a specific list of workloads.

Another task that can be done in this issue:
- Enable the y-axis in these charts with the units for reference, as the charts renders today in a relative way and when there are several namespaces the data tends to unify, then users may miss which magnitude is reading (they need to use the tooltip).

![image](https://user-images.githubusercontent.com/1662329/128480976-ba2d9b0f-1abb-49e6-b3ae-e460ffe3595e.png)
