### ISSUE TITLE
Health: show workloads as idle when there's no request

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#2949]
This is a suggestion: recently a new health status was introduced, IDLE. It's displayed for non-running workloads (e.g. with knative, pod temporarily shut down).

Perhaps it could also be interesting to use the same for workloads (or app or services) without any request. Currently, a workload that doesn't perform / receive any request is still displayed as "successful".

In this capture, for instance, I see everything being successful, in spite of having no traffic:

![Capture d’écran de 2020-06-30 14-34-02](https://user-images.githubusercontent.com/2153442/86127008-87f9f480-badf-11ea-87e9-18b710389383.png)

It turns out I have actually something broken in pods/cluster. It's hard to see from Kiali because Istio doesn't report anything wrong. But at least, it would help if this was reported as IDLE instead of SUCCESS.

On the flip side, marking as IDLE workloads that don't generate network traffic is debatable because there might be workloads with few network interaction but for instance heavy CPU task ... and such a workload wouldn't be really idling. But perhaps we can consider, given what Kiali is (network traffic console), that IDLE for us is purely in terms of network.

WDYT?

**Comment by maltron** [comment]
I love it. I usually create a simple script to generate some load in order to see things happening in Kiali and this gives me some feedback when there is no traffic at all.

**Comment by jshaughn** [comment]
I don't love IDLE as a health value.  I know we added it in the UI to represent this special-case but I still think of IDLE as an annotation on HEALTHY, as health may involve a variety of contributing checks.  I'd rather see the Healthy icon and a detail note perhaps.  The graph view is another way to see things without traffic now, or with Unused Nodes, without traffic ever.  I don't feel that strongly about it, though, so I'm OK with it if others like it.

**Comment by jotak** [comment]
@jshaughn but is a workload without any request really healthy? Perhaps it is, perhaps not, it's very hard to tell. The healthy status can be false-negative here, giving a fake impression that everything is fine. Although as you say, having an empty graph is also a clue that something is wrong .. but is it enough?

**Comment by lucasponce** [comment]
In #3576 we plan to revisit some of the expressions used between "Idle" / "Not Ready".
I'll take this one as it may have some discussion around it.

**Comment by lucasponce** [comment]
Closing in favor of https://github.com/kiali/kiali/issues/3576#issuecomment-760241754 to unify the work in a single issue.

Basically it's being discussed similar topic.
