### ISSUE TITLE
Documentation on how to contribute with Kiali

### ISSUE THREAD

**Issue by maltron** [kiali/kiali#2952]
Most of the documentation in Kiali.io is related on how to use Kiali and seamless integrated with Istio. However, I wonder if some documentation is needed in order to describe the steps for contribution with some tutorial, how-to guides and what the benefits of contribution brings to a Developer. 

Thoughts ?

**Comment by jshaughn** [comment]
It's hard to know whether this would increase contribution.  I think I'd rather wait for someone to tell us they want to contriute but don't know where to start.

**Comment by cfcosta** [comment]
I like the idea. Should come from someone that is not using kiali everyday, we're too biased for that.

**Comment by jotak** [comment]
By the way: we have a [Contribute](https://kiali.io/contribute/) page on the website, and [CONTRIBUTING.md](https://github.com/kiali/kiali/blob/master/CONTRIBUTING.md) on github. Perhaps we should merge them.

**Comment by jshaughn** [comment]
> By the way: we have a Contribute page on the website, and CONTRIBUTING.md on github. Perhaps we should merge them.

Good idea, what do you think, point kiali.io to github or the other way around?

**Comment by jotak** [comment]
I'd say keep the GH one as the main reference, as it's the place to be for developers & contributors ?

**Comment by lucasponce** [comment]
This issue has not activity for some time.

I think that now that Kiali discussions are available, an open topic "How to contribute to Kiali?" with more Q/A format would work.

I guess the current contribute docs in both main repo and kiali.io are still valid.

So, I'm going to mark this issue as closed.
