### ISSUE TITLE
On first refresh, graph loses node context

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#2957]
When the graph was loaded for the first time and a refresh is triggered, selected node context is lost.

Reproducing steps:
- Navigate to the graph, hit F5
- Select a node
- Click on graph refresh button (or wait for auto-refresh)

Problem: the previously selected node isn't selected anymore
Expectation: node selection is preserved across refresh

Note that it's only broken for the first refresh after the graph was initially loaded. In subsequent refreshes, selection is kept as expected.

**Comment by jotak** [comment]
ping @jshaughn did you see this issue? I find that quite annoying while testing in-graph tracing...

**Comment by jotak** [comment]
I take it, after all I've gained some xp in graph now :)

**Comment by jshaughn** [comment]
@jotak I was just going to look at that today, but have at it.
