### ISSUE TITLE
Difference in styles between build/dev

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#2958]
See draft PR where the problem happens (all explained there): https://github.com/kiali/kiali-ui/pull/1839

**Comment by lucasponce** [comment]
Is this issue still valid ?

**Comment by jotak** [comment]
yes

**Comment by jotak** [comment]
(there's no urgency, it's a problem that may continue to happen when some styles are changed in a PR, so until it's fixed we need to be more careful about potential differences between build and dev modes)

**Comment by lucasponce** [comment]
I'm sorry but I don't see this one at least in the context of iali/kiali-ui#1839
![image](https://user-images.githubusercontent.com/1662329/94000118-ff65ba00-fd96-11ea-87be-82bdcc81f0bf.png)

I'm not feel comfortable having such a generic issue for 3-4 Sprints without actions.

My suggestion:
- I'm going to close this one.
- If the problem persist let's fill a new one with a better scope.

I understand that there are differences in how yarn start process the css vs the build one, but as this is not critical, I prefer to act in that way for better tracking.
