### ISSUE TITLE
Breadcrumb - 3scale "Adapter" and "Template" names are not shown

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#2960]
Happens on master.

![Screenshot from 2020-07-02 21-00-51](https://user-images.githubusercontent.com/604313/86399435-8da23680-bca7-11ea-91b6-bc058f607060.png)
![Screenshot from 2020-07-02 21-00-32](https://user-images.githubusercontent.com/604313/86399447-909d2700-bca7-11ea-9670-b7b63d02cf94.png)

**Comment by lucasponce** [comment]
Good one, it's a regression. Thanks !
