### ISSUE TITLE
is there any other project like kiali which not base on istio or k8s

### ISSUE THREAD

**Issue by thinkin** [kiali/kiali#2962]
**Is your feature request related to a problem? Please describe.**
not install istio

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by lucasponce** [comment]
Hi @thinkin,

Actually the Kiali 1.x is focused on Istio, no plans to change that in the short term.

But I'm interested to learn about your scenario and what feature of Kiali would you like to see in other contexts.

That can give us inputs for future long-term ideas.

Thanks,
Lucas

**Comment by thinkin** [comment]
goal: to achieve "Architecture auto awareness"，our system has very complicated topology，so we want having a project liike kiali
feature：Double-layer structure：**center** which collects metric data from instance；**Proprietary protocol probe** which base on code or sidecar

**Comment by jotak** [comment]
@thinkin Kiali is indeed very focused on Istio. For something more generic, perhaps you could have a look at Apache Skydive? https://github.com/skydive-project/skydive ; would it work for you?

**Comment by thinkin** [comment]
@jotak thank u
but it seems unuseful for us, we want service or app's topology, not network

**Comment by thinkin** [comment]
basing on istio is actually a good solution

**Comment by jshaughn** [comment]
@thinkin I'm affaid a non-Istio impl of Kiali is out of scope given our current plans and manpower.  This is still an interesting topic and we'd be interested to hear about how you approach a solution.  From what you have written above it sounds like you are not currently using a service mesh (and possibly not k8s).

From a purely issue-mgmt perspective I'm going to label this as "Future" and close the issue.  "Future" means it is still a topic of interest, can be discussed further, and could be re-opened, but that it is not in scope for our current backlog.
