### ISSUE TITLE
Snyk reports in backend kiali repo are misleading

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#2965]
Just an example of a PR I'm working on:
https://github.com/kiali/kiali/pull/2936

Tracis CI is ok but the Snyk reports are out-of-sync/wrong.

I think our repos should try to be clean, I mean, I prefer a no-report than a false-positive-report that we need to ignore to progress.

So, with this issue I open the discussion what we want to do with this tool (continue using in both backend/frontend, only frontend, etc).

**Comment by jotak** [comment]
I think the maintenance cost with snyk has been pretty low until now, and this problem here is due to the move to go module. I am in the middle of fixing this (deactivating the sub-projects in vendoring that are not relevant anymore).

IMO snyk is still valuable and we can continue with it.

**Comment by lucasponce** [comment]
I'm +1 with your comments @jotak 

Thanks for putting this on the radar.

**Comment by israel-hdez** [comment]
I have a opened a support ticket: http://support.snyk.io/hc/requests/5825
Their CLI client is never ending the analysis. We need a fix for that before we can solve the issue on our repos.
