### ISSUE TITLE
Properly handle invalid regular expression in workload log querying

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#2973]
**Is your feature request related to a problem? Please describe.**
Provide a user friendly way to present regular expression errors when querying workload logs.

**Describe the solution you'd like**
Add some fields that display additional information about which field (show/hide) and what the error is in the regular expression.

*Issues
Epic: #2232

**Comment by jshaughn** [comment]
Setting to P1, could be useful but I'd like to see other logging features take precedence.

**Comment by mtho11** [comment]
@jshaughn right, it is not totally necessary.

**Comment by mtho11** [comment]
Just to be clear, there are zero messages that appear (in merged master) about invalid Regex syntax. No alert messages (like is coded to show). So you can type in a bunch of garbage and the result no resulting logs, but no syntax validation messages. The try/catch blocks do not appear to work with the Regex.text stuff -- no exception is ever thrown. Even in the debugger, I can't get the catch block to be entered.

**Comment by jshaughn** [comment]
I tested it multiple times in the PR branch.  I'll check it again tomorrow.

**Comment by jshaughn** [comment]
@mtho11 It worked for me in master, do we have an issue on Safari with alerts?   I just go to logs and enter a show value of `[` and hit return.  This is fine as a substring.  Then I toggle regex.  I immediately get an alert:

![image](https://user-images.githubusercontent.com/2104052/87159095-c7b69e00-c28e-11ea-9c3d-06a08aa2096a.png)

Is this not happening for you?

**Comment by mtho11** [comment]
No, I don't see that. Must be a platform-specific bug.

**Comment by mtho11** [comment]
@jshaughn there is no issue with the messages/alerts not being seen -- that works. The issue is that the `regex.test()` doesn't fire an exception on OS/X so the catch block is never executed in an erroneous regex. So it's a platform specific error with regex exceptions.

**Comment by jshaughn** [comment]
@mtho11 I have not seen `regexp.test()` throw an exception, it really shouldn't.  It's the constructor `new Regexp(pattern)` which will catch the bad patterns and throw.

**Comment by mtho11** [comment]
@jshaughn I didn't see an exception in the constructor interface:
```
interface RegExpConstructor {
    new (pattern: RegExp | string, flags?: string): RegExp;
    (pattern: RegExp | string, flags?: string): RegExp;
}

interface RegExp {
    /**
     * Returns a string indicating the flags of the regular expression in question. This field is read-only.
     * The characters in this string are sequenced and concatenated in the following order:
     *
     *    - "g" for global
     *    - "i" for ignoreCase
     *    - "m" for multiline
     *    - "u" for unicode
     *    - "y" for sticky
     *
     * If no flags are set, the value is the empty string.
     */
    readonly flags: string;

    /**
     * Returns a Boolean value indicating the state of the sticky flag (y) used with a regular
     * expression. Default is false. Read-only.
     */
    readonly sticky: boolean;

    /**
     * Returns a Boolean value indicating the state of the Unicode flag (u) used with a regular
     * expression. Default is false. Read-only.
     */
    readonly unicode: boolean;
}
```

Regardless of where it is we still have a platform specific issue.

**Comment by jshaughn** [comment]
@mtho11 Let's finish this one before starting anything else for the Epic.  My understanding is that the use of the Alert/MessageCenter will go away as it was a temporary solution, and we should display the error under the input box, basically consistent with PF4 and the way it's done in Graph Find/Hide.

FWIW it's definititely the  `new Regexp(pattern)` that throws the error as it's compiling the pattern in the constructor.

**Comment by jshaughn** [comment]
@mtho11 I'm going to take this one, it's analogous to the graph find/hide handling.  As for the try/catch issue you may have on mac, this is not going to solve that issue.  That must be something else.
