### ISSUE TITLE
Renamed k8s services are persisted within the Graph UI

### ISSUE THREAD

**Issue by robert-blackman** [kiali/kiali#2982]
**General remarks**

Similar to [this](https://github.com/kiali/kiali/issues/2783#issuecomment-647266321) issue. 

Same repro steps. Except when renaming the k8s service. i.e. `my-svc-v1` -> `my-svc-v2`.

Same expected behaviours.

**Versions used**
Kiali: 1.19.0
Istio: 1.6.3
Kubernetes flavour and version: AWS EKS 1.15

Happy to provide debug info if requested. Thanks

**Comment by jshaughn** [comment]
@robert-blackman So it's the same situation where you have a service node in the graph, with no incoming or outgoing edges?

**Comment by robert-blackman** [comment]
@jshaughn I can confirm it is the same situation, when there is no incoming or outgoing traffic. This is with the old service name. So `my-svc-v1` renamed to `my-svc-v2` the `v1` is persisted. Additionally, i've noticed that there appears to be some discrepancies when faceting using different durations, whereby the old nodes exist within some time periods but not others. Perhaps this indicates that the old nodes are only visible when there is no traffic going to the new nodes?

**Comment by jshaughn** [comment]
@robert-blackman With the exception of "Unused Nodes" I'm fairly sure you should never see an orphan node, especially a service node.  (Unused nodes are those that have never seen traffic but seem to be validly defined, displayed only when the option is enabled.  They are rendered using a dashed border).   But the fact is that any metrics reported into Prometheus will be there until the time that they are dropped via a time-to-live setting or are somehow cleaned out in some other fashion (Kiali does not do any cleaning).  And so given a time-period that extends into the past, it's quite possible that there could be metrics for both the old and new service.  It may have something to do with that sort of scenario, I'll need to investigate.

**Comment by robert-blackman** [comment]
@jshaughn Also, the application itself is not renamed, only the k8s service. I should also mention that when I say "old nodes", I mean _all_ of the old nodes, going back many weeks. Thanks a lot for looking into this!

**Comment by jshaughn** [comment]
@robert-blackman I'm a little bit stumped here.  It's not obvious how an orphan node could make it into the graph unless you had enabled the "Unused Nodes" Display option, but I'm fairly certain that's not the case.  Do you have a Graph-Hide expression in place?  If you enter the Graph-Find expression: `dead` do the orphans get highlighted?  And finally, what exactly do you mean when you say "renamed" service.  K8s service name are immutable, right? so do you mean you export the existing service yaml, then delete the existing service, and re-create changing only the service name?

**Comment by robert-blackman** [comment]
@jshaughn I can confirm I have the `Unused Nodes` option **disabled**, I don't have any Graph-Find expressions enabled, and when I use `dead` as a find expression, none the service nodes in question are highlighted. Oh sorry, yes I should clarify, the service objects are re-created with new names. There is also _always_ a service associated with the application, so:

App: `my-app`
svc: `my-app-svc` <- never changed
svc2: `my-app-svc2` <- when this svc is deleted it remains in the UI.

**Comment by jshaughn** [comment]
OK, so the app labeling remains the same for both services.   And, I assume so does the pod selector (app=my-app).  This may have something to do with it, because the service definition is missing but pods are still found for the deleted service, because the new service has the same pod selector.  I'll keep looking...

**Comment by robert-blackman** [comment]
@jshaughn So each k8s svc will use the `app=my-app` selector, but match additional selectors such as `version`, `release` etc. Basically each k8s svc is mapped to a set of pods via selectors, i.e.`my-svc-stable` => `app:my-app,release:stable`, `my-svc-develop` => `app:my-app,release:develop` etc. There are no two k8s services that have the exact same pod selectors.

That Find expression does **not** highlight the orphaned nodes.

We are definitely talking about service nodes.

![Screen Shot 2020-07-28 at 4 27 02 pm](https://user-images.githubusercontent.com/57333677/88627191-4153e600-d0ef-11ea-99e8-9719fc18baee.png)

Thanks! 👍

**Comment by jshaughn** [comment]
OK, as is often the case, a picture is worth a thousand words :)   Our definition of "orphan" is different.   For me "orphan" meant no incoming or outgoing edges, like in the original issue (see the screenshot [here](https://github.com/kiali/kiali/issues/2783#issue-617835527).   What you are seeing is the result of an existing time-series (meaning there was traffic in the past) but with no traffic for the current time period.

The problem with removing these edges/nodes is that it could be useful at time to see that there is no traffic when traffoc is expected.  Having said that, a terminal service node with no traffic is not likely useful and perhaps we should filter those away.  

Until then the immediate workaround is to enter "! traffic" in the graph hide.  That should wipe out all of these sorts of nodes.  Let me know.

**Comment by jshaughn** [comment]
OK, after thinking about this further I can't think of a good reason to keep leaf service nodes with no traffic.  Most likely these were injected service nodes (i.e. The `Service Nodes` display option is enabled) leading to a leaf workload/app node that saw no traffic.

I will add this use case to the dead node filtering.

**Comment by robert-blackman** [comment]
@jshaughn Thanks.

**Comment by jshaughn** [comment]
@robert-blackman The change will be in the next release If you have the flexibility to update give it a try and let me know if we've nailed it down.

**Comment by robert-blackman** [comment]
@jshaughn More than happy to do so 👍

**Comment by robert-blackman** [comment]
@jshaughn I can confirm this is resolved in `1.22.0` thanks 🍻

**Comment by jshaughn** [comment]
@robert-blackman Thanks for the feedback, happy to hear it!
