### ISSUE TITLE
A 404 on API resource shouldn't be an error

### ISSUE THREAD

**Issue by mikaint** [kiali/kiali#2991]
I have a restful api service and when trying to get a resource that does not exist it returns a 404. This however will affect the kiali graph and the line will become red, indicating an issue, however this is not an issue, is normal behaviour. Is there a way to avoid this?

**Comment by jotak** [comment]
Hi @mikaint 

Thanks for your feedback. We understand 4xx errors should not always be reported as errors, it may depends on expectations for a service (e.g. if a service is exposed to a closed & known network perhaps 4xx needs to be reported as errors, as opposed to when it's exposed to an opened network with uncontrolled consumers).

There is pending work about that, to allow more configuration: https://github.com/kiali/kiali/issues/1424 ; as a first step, this will be made configurable for the health indicators ; and after that for the graph edge colors.

**Comment by mikaint** [comment]
thank you for information @jotak and i'm glad this is already a wip!
