### ISSUE TITLE
FAQ links are all broken

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#2994]
1. https://kiali.io/
2. Click FAQ in the main masthead: https://kiali.io/documentation/latest/faq/
3. Notice the breadcrumbs say 1.19
4. Click anything in General section - all pages are blank
5. Click anything in Distributed Tracing - all pages are blank
6. Click anything in Validations section - all pages are blank.
7. Click anything in Graph section - some main paragraph shows up - same for all links.

**Comment by cfcosta** [comment]
To track this correctly:

- [ ] Breadcrumbs say 1.19.
      This is on purpose, unfortunately. The automatic release process is happening in the end of the week, so I am creating 1.20 directly. The PR is on its way.
- [ ] 4 to 6: The header links on the faq link to an empty page: this was like this before the versioning, but will fix it.
- [ ] 7: No idea what the problem is, will investigate.
