### ISSUE TITLE
Observe Remote Cluster

### ISSUE THREAD

**Issue by PatrickDuncan** [kiali/kiali#3002]
**Is your feature request related to a problem? Please describe.**
https://github.com/istio/istio/wiki/Central-Istiod-single-cluster-steps
There's a use case where there are 2 clusters integrated with the Istio service mesh:
- One is the Control Plane with istiod and Istio addons (Prometheus, Kiali, etc.)
- The other is the Data Plane which just has an istio-ingressgateway

Applications will only be deployed to the Data Plane and we want the Control Plane's addons to observe them. Hopefully I'm incorrect, but right now Kiali can only observe the cluster it's deployed to.

This is not multi-cluster, this is just remote cluster. I just want to see the Data Plane's networking.

The `istio_requests_total` metrics will be in the Control Plane's Prometheus via `envoyMetricsService` in the Data Plane's envoys. All labels will be preserved (this is working now)

**Describe the solution you'd like**
There would need to be an option to specify the remote FQDN/IP of the cluster. I think you would also need to read from a secret to gain access to the remote cluster. The secret will be created in the control plane and it originates from the remote plane's serviceaccount/clusterrole. https://istio.io/latest/docs/reference/commands/istioctl/#istioctl-experimental-create-remote-secret

As a MVP Kiali could be forced into **view** mode when observing a remote cluster. (Assuming getting `create delete patch` access is harder)

**Describe alternatives you've considered**
I do not want Kiali to run in the Data Plane, so I don't believe there's an alternative

**Additional context**
Add any other context or screenshots about the feature request here. If it is about a new design, please attach a drawing of a potential solution.
For backend changes also describe how one could test the new feature and how it impacts display on the UI.

**Comment by jmazzitelli** [comment]
See these Prometheus settings: https://github.com/kiali/kiali-operator/blob/v1.20.0/deploy/kiali/kiali_cr.yaml#L490-L519

I would have thought the settings there let you point Kiali to whatever Prometheus you want. Perhaps I misunderstand the use-case. I guess the question would be: what settings are missing in that section that would help with this?

**Comment by PatrickDuncan** [comment]
@jmazzitelli Hi, so in this use case Kiali and Prometheus are running in the same cluster. So those settings are not necessary.

This ticket is about Kiali observing a remote cluster, instead of the cluster it is deployed to. For example, Cluster A will have `istiod, kiali, istio-ingressgateway, and prometheus`. Cluster B will just have `istio-ingressgateway` and is controlled by Cluster A. Kiali in Cluster A needs to observe the networking happening in Cluster B. Cluster B's workloads will have to push the sidecar/envoy metrics (`istio_request_total`) to Cluster A. That's fine, the problem is having Kiali in Cluster A grab resources (namespaces, configmaps, etc.) from Cluster B. 

Here's a diagram:
![3002](https://user-images.githubusercontent.com/6889074/87819080-ad099980-c839-11ea-834b-56eec038ce4d.png)

**Comment by jmazzitelli** [comment]
Ah.. right.. accessing the k8s resources cross-cluster.

> basically shared-control-plane multi-cluster support

> It is not "cluster-aware", only "namespace-aware", it assumes the configuration is in the local cluster. We support multi-cluster only with Kiali deployed in each control-plane.

I think we actually have this request documented in another issue somewhere, IIRC. This all has to do with the multi-cluster research that @israel-hdez did a while back.

**Comment by PatrickDuncan** [comment]
I was looking at #1833 and the other one @jmazzitelli  just mentioned.

Some of the tasks in that ticket are relevant to this one, but I don't believe they're exactly the same. I don't want to display information about multiple clusters. Just the 1 Data Plane cluster.

Right, the feature request is for having the configuration be in a remote cluster. I see that there's a future label, what's the outlook on this feature? Thanks!

This shouldn't require a front-end change, just a back-end change to change the cluster Kiali manipulates

**Comment by jshaughn** [comment]
@israel-hdez Any comments?

**Comment by israel-hdez** [comment]
I haven't read all the details of the setup, but I this sounds too similar with the multi-cluster setup.
It depends on how much data we need to read from the Control Plane cluster and the Data Plane cluster.

In this scenario, if and only if:
  * We access ONLY the prometheus, jaeger and (optionally) grafana.
  * Everything else is fetched from the remote Data Plane through regular cluster API calls

then, this may be doable with a small effort. But note that we will be using prometheus, jaeger and grafana as *services* (the kiali-operator already supports specifying the URL of these services). Then, it would be a matter of adding some configuration options to make Kiali to use the API of Data plane cluster, rather than the API of the local cluster.

But I don't think it is that easy.

With multi-cluster, the issue is that configuration is dispersed across clusters: services, deployments,  replicasets, etc. are stored in remote clusters (and can also be in the main cluster); while VirtualServices, Policies, Gateways, and in general all Istio CRs are stored only in the main cluster. So, in order to have the full view, data from both clusters is needed.

If the "*Central Istiod*" feature shares that multi-cluster pattern about the dispersed config then that would require a large effort because Kiali would need to collect data from both clusters to work correctly. I'd even see "*Central Istiod*" feature as a subset of multi-cluster where if implementing this, then it would be a small effort to add support for multi-cluster.

@PatrickDuncan A simple question that can help to clarify: If you want to create a VirtualService, in which cluster do you create it? If it is in the Control Plane cluster, then this will require a large effort. If it is in the Data Plane cluster this *may* be solved with a small effort and we could discuss it :)

**Comment by PatrickDuncan** [comment]
@israel-hdez It is a subset of the multi-cluster setup, but has enough differences where it may be easier to implement. Or a stepping stone for multi-cluster.

There were discussions around having the Istio resources (VirtualServices, Gateways, etc.) in the Data Plane. But with the Istio 1.6 they have to be applied to the Control Plane. @linsun would know more.

Certain resources will always exist in a specific cluster and there's only ever 2 clusters with this setup. So the implementation on Kiali's end needs to know where specific resources are (supposed to be) located. I don't believe it has to be overly granular, it could just fetch Istio resources from Control and normal resources (pods, deployments, etc.) from Data.

I do agree that the setup needs to be solidified.

**Comment by linsun** [comment]
Sorry for chiming in late here.  Note this setup is just single cluster setup where the single cluster provides config and data plane, the key difference from the usual single cluster setup is that we run istiod outside of the single cluster, with a kubeconfig point to the single cluster when launching istiod.

All istio resources would reside in the single cluster that provides configs for istiod.

Essentially, what we are looking at is launching kiali by pointing to a kubeconfig that is different than the current k8s cluster, similar as how we support this in istiod.  I'd imagine you 'd use this setup for testing Kiali on your laptop and point to a local k8s or a k8s in the cloud.

**Comment by PatrickDuncan** [comment]
I'm currently working on enabling this.

**Comment by israel-hdez** [comment]
> the key difference from the usual single cluster setup is that we run istiod outside of the single cluster, with a kubeconfig point to the single cluster when launching istiod.
> 
> All istio resources would reside in the single cluster that provides configs for istiod.

This part confuses me a little.
Does this means that _currently_ in Istio 1.6 the Istio resources (like VirtualServices, Gateways, etc) live in the Data Plane cluster? or are there in the Control Plane Cluster? or this is the planned?

I just want to understand it clearly :)

**Comment by PatrickDuncan** [comment]
@israel-hdez With Istio 1.6, that I have running now, VirtualServices, Gateways, etc. live in the Control Plane.

With 1.7 I believe Lin enabled the Istio CRDs to live in the Data Plane. If it's not in 1.7, then it will be enabled in the future.

---

I'm working on having the Data Plane create the Kiali CR, CRB, SA beforehand and then have the secret from that SA applied to the Control Plane. Kiali would then use the server, port, bearer token and CA from that remote secret instead of the Control Plane's master.

**Comment by israel-hdez** [comment]
@PatrickDuncan @linsun I'm wondering if this kind of setup is going to be a recommendation?
I see it's experimental. And I note Lin mentioned this more for Kiali testing purposes.

So, I'm wondering if this is really for users wanting to test Kiali, or if you already have a good number of users that want this kind of Istio setup.

**Comment by PatrickDuncan** [comment]
@israel-hdez Hi, I believe Lin's comment was just saying that you guys probably point to a remote cluster when testing so this is similar. Not that this change is for testing. (Though I believe you guys test by just changing the image in the deployment).

The single remote cluster setup will be a proper use case for using Istio and we will be using it internally! The diagram is a simplified/focused version of what we're doing.

**Comment by linsun** [comment]
@israel-hdez Yes, to answer your question, the Istio community is interested in supporting running istiod outside of data plane cluster, and also possibly different cluster than the config cluster.  We'll start introducing this in 1.7, and intend to stabilize this function in 1.8 or 1.8+.
