### ISSUE TITLE
In-graph tracing: show trace details

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#3010]
Epic: #2677

The idea is:
- When a trace is selected, split the side panel with a bottom panel to show contextual information
- When a node is selected in graph:
  - If node is part of the selected trace, fill that side-bottom panel with spans information (possibly multiple spans)
  - If node isn't part of the trace, use normal behaviour: deselect trace and show usual traffic data in side panel

Span information includes:
- Operation name
- Duration
- Tags / process (perhaps we don't want to show them all? That's to be experimented)
- Link to Trace/Span details in Tracing page

**Comment by jotak** [comment]
@jshaughn we should have a quick discussion about that

**Comment by jshaughn** [comment]
@jotak just ping me anytime...
