### ISSUE TITLE
Refactor refresh controls in Log tab

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#3011]
The log tabs is missing the consistency across other tabs with the refresh controls:

![image](https://user-images.githubusercontent.com/1662329/88048300-6080cf80-cb53-11ea-8c6f-c4b8d0f1d03a.png)

**Comment by mtho11** [comment]
Ah ok @lucasponce +1

**Comment by lucasponce** [comment]
It's not only for consistency, with a PR in the way:
https://github.com/kiali/kiali-ui/pull/1833#issue-439918927
we need to refactor a little bit how the refresh in logs work because it will change the containers after an update operation.

@mtho11, if you prepare the the refactoring I can work in the refresh way, but I didn't want to change your code as you are actively working on this tab.

**Comment by jshaughn** [comment]
I added this to the backlog and unassigned @mtho11 for now.  I think this can be done outside of his current work on the logs window and as it depends on the 3scale work/refactor it likely needs to wait until that work is merged.  I will add a wait label for now.  We can assign as makes sense when that label is removed.

**Comment by lucasponce** [comment]
I removed the "waiting eng" and added a "bug". 
As it creates a consistency problem in the details pages being the only tab that have different location of these controls.

I don't have bandwidth to work on this week, but it's something we need to fix.

**Comment by jshaughn** [comment]
Assigning @mtho11 , Mike, prio this one as a bug, let's see if we can get it fixed up for 1.22.1 (Aug 7).  Ask @lucasponce for details, if necessary.
