### ISSUE TITLE
Better link Istio configuration under Workload and Service details.

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#3015]
Kiali links DestinationRules and VirtualServices object under Kiali Service details page.

This scenario can be extended as there are more networking and security objects that are linked directly at workload and/or service details level.

This issue is to work on:
- [x] Join "Virtual Services" and "Destination Rules" tabs into a single "Istio" tab under Service Details.
-  ~~Extend "Istio" tabs with other Istio objects related with a Service (Networking: Gateway, Security).~~
- [x] Extend "Istio" tabs under Workload details to link specific Istio objects linked with workload selectors only.
- ~~Revisit "Delete all" action to avoid conflicts with shared objects (i.e. do not delete a Gateway, probably it's already done but it would require to check potential regressions)~~

Update:
- Security objects are linked under the Workload details.
- "Delete All" action under Service Details may need more thinking as there are some scenarios which may include new Gateway and PeerAuthentication, so at the moment it will be related to the direct VS/DR objects created, rest of the Istio resources are deleted individually from Istio Config details.

**Comment by lucasponce** [comment]
One option I was thinking about is to have a single tab called "Istio" and put all objects there and have a list of DR, VS, Peer, etc.
In that case, we could normalize the same tab under all App/Workload/Service details.
Also, we have some inconsistencies in the tab as in the VR we only show basic fields meanwhile in the DR there are some sort of mini-summary in the row, that's also an aspect that could be good to normalize.

It doesn't seem a pretty big effort, but something cheap that can help user to understand all Istio configuration related for an element.

In practice is like to have a Istio Config list filtered by the element (app, workload, service).

**Comment by xeviknal** [comment]
I like the idea. However, I do have one concern: there aren't much space in that page for all the filtering and pagination capabilities.
I do like also the fact of standardizing the columns of each row in there. I don't know if the details in there are helping that much.

**Comment by jshaughn** [comment]
> One option I was thinking about is to have a single tab called "Istio"

A complete side-comment, but the idea of compartmentalizing mesh-specific handling could be useful for setting a "vendor" mode across Kiali.

**Comment by lucasponce** [comment]
> A complete side-comment, but the idea of compartmentalizing mesh-specific handling could be useful for setting a "vendor" mode across Kiali.

+1 Yes, in practice is something we address today, for example, specific forms for Istio are located in the "Istio Config" -> "New" objects, meanwhile under the Services the "Wizards" use an abstract layer.

Putting together "Virtual Services" + "Destination Rules" in a single "Istio" tab will help to add more new types of objects that are linked with a specific service/workload and also to have a better structure to make sure what depends of the "Service Mesh" scenario.

**Comment by lucasponce** [comment]
I'm going to start doing minor changes around this epic. Starting putting together an "Istio" tab under Service Details to see VR/DR under a single place.
Potentially we can add more objects linked with a Service, and as following subtasks (to be added to the epic) under the workload and/or application.
