### ISSUE TITLE
remove login and ldap auth strategy

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#3017]
We have already deprecated the login auth strategy. We should remove it soon. This would involve removing it from the deploy script, the makefile, the operator playbook, and the docs (and I might be missing other places, too).

Same with ldap, now that openid can replace it.

**Comment by jmazzitelli** [comment]
@israel-hdez knows where the touch points are - particularly on the frontend and backend. I also know where they are on the operator side.

**Comment by jshaughn** [comment]
Adding to the sprint as it was deprecated 2 releases ago and we need it removed prior to the next downstream release.

**Comment by jmazzitelli** [comment]
The following PRs implement this fix:
* backend: https://github.com/kiali/kiali/pull/3044
* frontend: https://github.com/kiali/kiali-ui/pull/1861
* operator: https://github.com/kiali/kiali-operator/pull/99
* docs: https://github.com/kiali/kiali.io/pull/270

NOTE: the backend, operator, and docs PRs are all rebased on [the recent helm work](https://github.com/kiali/kiali/issues/195) - do not merge any of the above until that helm work is merged first.

**Comment by jshaughn** [comment]
I want to hold off on this until we ensure OpenID is working for folks.  Setting as wait-for-eng until https://github.com/kiali/kiali/issues/3042 is resolved.

**Comment by jmazzitelli** [comment]
We also want to hold off until we fix the `handlers/authentication_test.go` unit tests - see my comment: https://github.com/kiali/kiali/pull/3044#issuecomment-665266568

**Comment by jmazzitelli** [comment]
I'm assigning this to @israel-hdez for him to look at the tests in authorization_test.go.

**Comment by jmazzitelli** [comment]
@israel-hdez I changed all the PRs from "draft" to "open" (they are now ready for review). I made you a reviewer on all of them (there are 4 PRs - see the PR list in https://github.com/kiali/kiali/issues/3017#issuecomment-665273600)

**Comment by israel-hdez** [comment]
@jmazzitelli OK, I'll start the reviews.

**Comment by jmazzitelli** [comment]
all work done and PRs merged. Au revoir, ldap and login.
