### ISSUE TITLE
Overview tiles sometimes not aligned(bottom)

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#3018]
**General remarks**
The overview tiles sometimes are not bottom aligned:

![Kiali_Console](https://user-images.githubusercontent.com/1312165/88198136-40571c00-cbf8-11ea-87a1-ff5e525374ba.png)

Browser: Firefox

**Comment by lucasponce** [comment]
Fixed by https://github.com/kiali/kiali-ui/pull/1874
