### ISSUE TITLE
kiali api documentation link - adjust to versioned documentation

### ISSUE THREAD

**Issue by xeviknal** [kiali/kiali#3026]
Kiali workload page has the API documentation link. Right now, It points to a generic kiali.io link: https://kiali.io/api
I think that now that we have versions in our documentation, we should revisit this and add the current installation version into that link.

As of now, that generic link forwards users to v1.9, not event the latest version.

![Screenshot of Kiali Console (12)](https://user-images.githubusercontent.com/613814/88284589-f5b7cb80-cced-11ea-9f51-c3a62717893f.png)

This link should point to a non-dynamic URL with the fixed version of the current kiali installation.

**Comment by jotak** [comment]
I'm looking into it, but note that it seems part of the issue was already fixed in kiali.io : link kiali.io/api now redirects to the latest. At least this is what I'm seeing right now, I am redirected to https://kiali.io/documentation/v1.22/developer-api/

**Comment by xeviknal** [comment]
I think the main problem in here is to change the url depending on the kiali version. If you install Kiali v1.20, you will probably see the same API link (kiali.io/api) that would point you to the incorrect version. Instead, it should have the kiali.io/documentation/v1.20/developer-api.

**Comment by lucasponce** [comment]
A lot of activity on this one :-).
I think is kiali.io/api is working, point to the specific version is a minor detail, personally I don't think it has priority.
Kiali.io site is evolving and I wouldn't process the links to the side more than it's today.

Personally I'd close the bug and don't add it to the backlog.

**Comment by jotak** [comment]
@lucasponce I don't really see why closing this, it is truly a bug (though minor one) that the link to the documentation doesn't point to the actual versioned doc. Priority is something different. It seems technically feasible to do that (although I would have a couple of questions to @jmazzitelli about how to infer version in templates).
If we expect changes in kiali.io URLs then, it's ok to wait for this change .. but do we expect such change? Is there a filed ticket about that?

**Comment by lucasponce** [comment]
I don't see a bug because, kiali.io may change the links structure, so I don't want to add a "builder" logic inside Kiali to detect the right Kiali.io link.

Pointing to a generic kiali.io/api doesn't sound bad, because in the future kiali.io can handle the versioning in a different way (a dropdown in the very same page, for example, as openshift has).

So, I don't expect any logic to fetch the kiali.io info and templates and build dynamically the right url on that.

**Comment by lucasponce** [comment]
This is still valid.
The operator has some defaults for these URLs which are incorrect.

I'd use this bug, just to remove them (with a comment is enough) in the operator, there is a pending task to provide an API in the main kiali github repo and then it can be restored them.
