### ISSUE TITLE
[Istio 1.7] Istio sub-component health: adjust names to new addons system

### ISSUE THREAD

**Issue by xeviknal** [kiali/kiali#3027]
Istio upstream has been working on a new way of installing addons. This has a direct impact on the istio component health check.

I've followed the steps below to install the whole istio + addons environment (use to be profile=demo):

```
istioctl install --set profile=demo # doesn't install any add-on anymore
kubectl apply -f samples/addons -n istio-system
istioctl dashboard kiali
```
I see the following difference:

![Screenshot of Kiali Console (13)](https://user-images.githubusercontent.com/613814/88285029-b9389f80-ccee-11ea-9bca-b077ce52d445.png)

My proposal is to add for each component a set of possible deployment names. e.g. Tracing service: istio-tracing (v1.6), jaeger (v1.7).,

**Comment by jshaughn** [comment]
@xeviknal maybe useful to post what you've learned about testing 1.7 on kiali dev-list...
