### ISSUE TITLE
add molecule test to test Jaeger integration

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#3028]
We should have a molecule test that tests things around the Kial-Jaeger integration.

(an idea brought up by @objectiser)

**Comment by lucasponce** [comment]
This issue seems valid.

**Comment by lucasponce** [comment]
This one shouldn't be complex, perhaps @leandroberetta could take a look and having @jmazzitelli for support him to setup the molecule scenario ?

I'd tentative assign to him, but if there was some previous job on this, feel free to update it.

Thanks.
