### ISSUE TITLE
"Kiail Graph Load Failure With Istio 1.7"

### ISSUE THREAD

**Issue by pbajjuri20** [kiali/kiali#3030]
Steps to reproduce the issue:

1) Install - Istio 1.7.0-alpha.1
2) Install - Bookinfo 
3) Navigate to Kiali - UI
4) Click on Graphs
5) Select Namespace: Bookinfo

It cannot load the Graph

error: Cannot load the graph: Post "http:///api/v1/query": http: no Host in request URL

![istio 1 7 5](https://user-images.githubusercontent.com/55099523/88308714-5c7fb980-ccdb-11ea-8cbe-59ed3dbee54f.png)

**Comment by xeviknal** [comment]
@pbajjuri20 have you install prometheus before? With the new way of installing add-ons, there is the need to manually install prometheus, jaeger and grafana manually. Check it out in here: https://github.com/istio/istio/tree/master/samples/addons

Here my way of installing istio with addons:
```
istioctl install --set profile=demo # doesn't install any add-on anymore
kubectl apply -f samples/addons -n istio-system
istioctl dashboard kiali
```

**Comment by xeviknal** [comment]
In any case, I've installed also the bookinfo (using the hack script for minikube) and I can't see any traffic flowing even without prom warnings.

![Screenshot of Kiali Console (14)](https://user-images.githubusercontent.com/613814/88369031-737fe380-cd8f-11ea-8935-cb328357e9df.png)

I do have the traffic-generator in the app, a chrome tab with the productpage and a watch curling the page.

**Comment by xeviknal** [comment]
I can't see this problem anymore. Istio 1.7 with addons.

![Screenshot of Kiali Console (15)](https://user-images.githubusercontent.com/613814/88676701-b245ce80-d0ec-11ea-8089-6fc5bf123a98.png)
