### ISSUE TITLE
Istio 1.7 testing: Wrong Istio version in About

### ISSUE THREAD

**Issue by pbajjuri20** [kiali/kiali#3032]
Steps to reproduce this issue: 

1) Install - Istio 1.7.0-alpha.1
2) Navigate to Kiali - UI
3) Click on the help section (?) on the top right panel 
4) Click on the About

In the Kiali about, It shows the wrong Istio version.

![Istio-1 7 about](https://user-images.githubusercontent.com/55099523/88313025-ef6f2280-cce0-11ea-98d1-32f5a902a34e.png)

**Comment by jmazzitelli** [comment]
lemme guess - Istio changed, yet again, the format of the version string?

Can you do this and see what you get?

`oc exec -n istio-system $(oc get pod -n istio-system -l app=kiali -o name) -- curl -L http://istiod.istio-system:15014/version`

**Comment by mattmahoneyrh** [comment]
@mazz: 1.7.0-alpha.1-cd46a166947eac363380c3aa3523b26a8c391f98-dirty-Modified

**Comment by jmazzitelli** [comment]
cc @jshaughn

**Comment by jshaughn** [comment]
OK, although we are accepting as a valid version we're not capturing the detail correctly.  Minor but we can fix it.
