### ISSUE TITLE
K-charted tooltip on legend is confusing

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#3035]
The tooltip on charts shows information about the closest datapoint, which is fine in general, however when mouse pointer is over the legend (off-chart), it still shows the closest data point (on-chart) which here is a little bit confusing because we would expect information related to the legend item we're pointing on.

E.g. :
![Capture d’écran de 2020-07-24 10-30-01](https://user-images.githubusercontent.com/2153442/88374359-ed1ccf00-cd99-11ea-9b71-3915d4649c29.png)

Here mouse pointer is on the green "non-heap", but tooltip shows the blue "heap" because it's the line at the bottom, hence closer to mouse pointer.

At best, it would be nice to show instead information related to the pointed legend item.
Or at least, just show no tooltip at all in this situation (over legend items).

**Comment by lucasponce** [comment]
This issue is still happening.
![image](https://user-images.githubusercontent.com/1662329/107665570-dda99880-6c8d-11eb-96e9-dca826293c8a.png)

I'll add to the Sprint just to not forget
