### ISSUE TITLE
Kiali not working with OIDC for 1.19 

### ISSUE THREAD

**Issue by widdix123** [kiali/kiali#3042]
**Describe the bug**
Configuring OIDC with Kiali configmap , i am not able to login to UI 

![image](https://user-images.githubusercontent.com/38529736/88658608-529df200-d0f1-11ea-9dde-1d1128fe65ac.png)

**Versions used**
Kiali: 1.19
Istio: 1.65 
Kubernetes flavour and version: (e.g. OpenShift Origin 3.9) - 1.17 EKS

**To Reproduce**
1. Configure Configmap of Kiali to point to dex 

```
auth:
  strategy: openid
  openid:
    client_id: example-app
    issuer_uri: https://dex.xxxx.xxxxx.com/dex
    username_claim: email
    scopes: ["openid", "profile", "email", "groups"]

```

2. Create a ClusterRoleBinding to add user to have access to Kiali 

3. Login to Kiali Console and Click on "LogIn with OpenId"

4. It will throw error as "Unauthorised"

**Expected behavior**

I should be able to login to the UI console with OIDC

**Comment by jmazzitelli** [comment]
Can you provide the kiali pod logs so we can see what the error is?

**Comment by widdix123** [comment]
@jmazzitelli  - I dont see much in the logs as it does not seem to update even on errors

```
I0728 11:25:01.105204       1 kiali.go:66] Kiali: Version: v1.19.0, Commit: 000642e202cb61f49b65c5077bd05b3cb6274135
I0728 11:25:01.105893       1 kiali.go:205] Using authentication strategy [openid]
I0728 11:25:01.105957       1 kiali.go:87] Kiali: Console version: 1.19.0
I0728 11:25:01.105974       1 kiali.go:284] Updating base URL in index.html with [/kiali]
I0728 11:25:01.106473       1 kiali.go:265] Generating env.js from config
I0728 11:25:01.110513       1 server.go:67] Server endpoint will start at [:20001/kiali]
I0728 11:25:01.110552       1 server.go:68] Server endpoint will serve static content from [/opt/kiali/console]
I0728 11:25:01.110591       1 metrics_server.go:18] Starting Metrics Server on [:9090]
```

**Comment by jmazzitelli** [comment]
We run a nightly integration test using Dex on minikube and it runs successfully so I wonder if there is something in your Dex setup? Have you been able to install a test app (outside of Kiali) that can perform an OIDC login with it?

Also, I believe the browser javascript logs might also provide some insight, if you want to check there to see what the requests going to and fro are and what errors you see?

**Comment by widdix123** [comment]
@jmazzitelli  - We are using dex for Grafana, Minio, Kubernetes dashboard and everything seems to be working fine on the same cluster

Logs that i see in Chrome Browser

```
2.0a25de2f.chunk.js:2 POST http://localhost:20001/kiali/api/authenticate 401 (Unauthorized)
(anonymous) @ 2.0a25de2f.chunk.js:2
e.exports @ 2.0a25de2f.chunk.js:2
e.exports @ 2.0a25de2f.chunk.js:2
Promise.then (async)
s.request @ 2.0a25de2f.chunk.js:2
(anonymous) @ 2.0a25de2f.chunk.js:2
Ha @ main.77cea60e.chunk.js:1
(anonymous) @ main.77cea60e.chunk.js:1
s @ 2.0a25de2f.chunk.js:2
(anonymous) @ 2.0a25de2f.chunk.js:2
forEach.e.<computed> @ 2.0a25de2f.chunk.js:2
r @ 2.0a25de2f.chunk.js:2
c @ 2.0a25de2f.chunk.js:2
(anonymous) @ 2.0a25de2f.chunk.js:2
(anonymous) @ 2.0a25de2f.chunk.js:2
(anonymous) @ main.77cea60e.chunk.js:1
(anonymous) @ main.77cea60e.chunk.js:1
s @ 2.0a25de2f.chunk.js:2
(anonymous) @ 2.0a25de2f.chunk.js:2
forEach.e.<computed> @ 2.0a25de2f.chunk.js:2
r @ 2.0a25de2f.chunk.js:2
c @ 2.0a25de2f.chunk.js:2
(anonymous) @ 2.0a25de2f.chunk.js:2
(anonymous) @ 2.0a25de2f.chunk.js:2
(anonymous) @ main.77cea60e.chunk.js:1
(anonymous) @ main.77cea60e.chunk.js:1
s @ 2.0a25de2f.chunk.js:2
(anonymous) @ 2.0a25de2f.chunk.js:2
forEach.e.<computed> @ 2.0a25de2f.chunk.js:2
r @ 2.0a25de2f.chunk.js:2
c @ 2.0a25de2f.chunk.js:2
(anonymous) @ 2.0a25de2f.chunk.js:2
(anonymous) @ 2.0a25de2f.chunk.js:2
(anonymous) @ main.77cea60e.chunk.js:1
(anonymous) @ main.77cea60e.chunk.js:1
Promise.then (async)
_S @ main.77cea60e.chunk.js:1
(anonymous) @ main.77cea60e.chunk.js:1
(anonymous) @ 2.0a25de2f.chunk.js:2
checkCredentials @ main.77cea60e.chunk.js:1
value @ main.77cea60e.chunk.js:1
ic @ 2.0a25de2f.chunk.js:2
ds @ 2.0a25de2f.chunk.js:2
t.unstable_runWithPriority @ 2.0a25de2f.chunk.js:2
Wo @ 2.0a25de2f.chunk.js:2
hs @ 2.0a25de2f.chunk.js:2
Zc @ 2.0a25de2f.chunk.js:2
(anonymous) @ 2.0a25de2f.chunk.js:2
t.unstable_runWithPriority @ 2.0a25de2f.chunk.js:2
Wo @ 2.0a25de2f.chunk.js:2
qo @ 2.0a25de2f.chunk.js:2
Go @ 2.0a25de2f.chunk.js:2
Yc @ 2.0a25de2f.chunk.js:2
enqueueSetState @ 2.0a25de2f.chunk.js:2
O.setState @ 2.0a25de2f.chunk.js:2
n.initializationFinishedHandler @ main.77cea60e.chunk.js:1
(anonymous) @ main.77cea60e.chunk.js:1
s @ 2.0a25de2f.chunk.js:2
(anonymous) @ 2.0a25de2f.chunk.js:2
forEach.e.<computed> @ 2.0a25de2f.chunk.js:2
r @ 2.0a25de2f.chunk.js:2
c @ 2.0a25de2f.chunk.js:2
Promise.then (async)
r @ 2.0a25de2f.chunk.js:2
c @ 2.0a25de2f.chunk.js:2
(anonymous) @ 2.0a25de2f.chunk.js:2
(anonymous) @ 2.0a25de2f.chunk.js:2
value @ main.77cea60e.chunk.js:1
ic @ 2.0a25de2f.chunk.js:2
ds @ 2.0a25de2f.chunk.js:2
t.unstable_runWithPriority @ 2.0a25de2f.chunk.js:2
Wo @ 2.0a25de2f.chunk.js:2
hs @ 2.0a25de2f.chunk.js:2
Zc @ 2.0a25de2f.chunk.js:2
(anonymous) @ 2.0a25de2f.chunk.js:2
t.unstable_runWithPriority @ 2.0a25de2f.chunk.js:2
Wo @ 2.0a25de2f.chunk.js:2
qo @ 2.0a25de2f.chunk.js:2
Go @ 2.0a25de2f.chunk.js:2
Yc @ 2.0a25de2f.chunk.js:2
enqueueSetState @ 2.0a25de2f.chunk.js:2
O.setState @ 2.0a25de2f.chunk.js:2
r.handlePersistorState @ 2.0a25de2f.chunk.js:2
g @ 2.0a25de2f.chunk.js:2
h @ 2.0a25de2f.chunk.js:2
E @ 2.0a25de2f.chunk.js:2
(anonymous) @ 2.0a25de2f.chunk.js:2
Promise.then (async)
(anonymous) @ 2.0a25de2f.chunk.js:2
Promise.then (async)
(anonymous) @ 2.0a25de2f.chunk.js:2
g @ 2.0a25de2f.chunk.js:2
(anonymous) @ 2.0a25de2f.chunk.js:2
persist @ 2.0a25de2f.chunk.js:2
j @ 2.0a25de2f.chunk.js:2
1584 @ main.77cea60e.chunk.js:1
u @ (index):1
1103 @ main.77cea60e.chunk.js:1
u @ (index):1
t @ (index):1
r @ (index):1
(anonymous) @ main.77cea60e.chunk.js:1

```

**Comment by widdix123** [comment]
@jmazzitelli  - Any inputs will be very helpful as we want to get this integrated and roll out in production

**Comment by jmazzitelli** [comment]
Are you really on OpenShift 3.9?

**Comment by jmazzitelli** [comment]
I know a couple of bug fixes went into the OpenID auth strategy implementation recently. You are on Kiali 1.19 and those bug fixes are not in that version. See if Kiali v1.21 shows the same behavior.

The error you are getting (paired with the fact there are no system errors in any logs) makes it seem to be its just a misconfiguration somewhere. But I would run with the latest Kiali release and see if you get the same thing - perhaps this is caused by one of the issues that was recently fixed.

**Comment by widdix123** [comment]
@jmazzitelli  - Adding further inputs ( the token generated by dex is valid) but i still get this error

Generated JWT Token

```
{
  "iss": "https://dex.demo.xxxxxx.com/dex",
  "sub": "ddddddddd",
  "aud": "example-app",
  "exp": 1595940939,
  "iat": 1595937339,
  "nonce": "sdfsdfsd",
  "at_hash": "LU-O-Uy7tgf_8jZGULO19Q",
  "email": "agupta@xxxxx.com",
  "email_verified": true,
  "groups": [
    "a468f8ad-2564-49f6-83b3-971f389fbda6"
  ],
  "name": "abhi@xxxx.com"
}


```

Snapshot of Network tab

![image](https://user-images.githubusercontent.com/38529736/88665373-26d43980-d0fc-11ea-809f-785045730535.png)

**Comment by widdix123** [comment]
@jmazzitelli  - same error on 1.21 also .  i am using groups in dex

**Comment by jmazzitelli** [comment]
OK, I think I know what this is. Looks like a misconfiguration of the ServiceAccount/Role assigned to your user.

Here's the [code](https://github.com/kiali/kiali/blob/v1.21/handlers/authentication.go) - search for that error "Token is not valid or is expired". Three hits. One deals with OpenShift, which you are not on. Two are the same - Kiali needs to confirm if the token is valid and on Kubernetes, one of the few nice ways to do this is to make a call to get the list of namespaces, which is what Kiali does to confirm the validity of the token:

```
	// Using the namespaces API to check if token is valid. In Kubernetes, the version API seems to allow
	// anonymous access, so it's not feasible to use the version API for token verification.
	nsList, err := business.Namespace.GetNamespaces()
	if err != nil {
		RespondWithDetailedError(w, http.StatusUnauthorized, "Token is not valid or is expired", err.Error())
		return false
	}
```

So your user's RBAC needs to include at minimum the ability to get some namespaces (at minimum that k8s getNamespaces API needs to be successful).

I suspect this is the problem - your user doesn't have the correct minimum permissions.

**Comment by widdix123** [comment]
@jmazzitelli 

Nope , still not working I have given it cluster admin role for now , so it should be able to do anything on the cluster

RoleBinding giving access to cluster

```
kubectl create clusterrolebinding openid-clusterbinding --clusterrole=cluster-admin --user="abhi@xxxxxx.com"
kubectl  auth can-i list ns --as abhi@xxxxxxx.com ( i get yes)

```


JWT payload

```
  "iss": "https://dex.demo.xxxxxx.com/dex",
  "sub": "Cis3a3lDVTUtbkpCdF9SM1FibTdGWlRtVlg2QXN5THg5NVFHanZuYmRKTVpzEgRzYW1s",
  "aud": "example-app",
  "exp": 1595944068,
  "iat": 1595940468,
  "nonce": "5af095070c447fa6fc651a09513daac12be8cddedd3d37e1db782768",
  "at_hash": "2dLssY4MCKYL4jKyNT7HKg",
  "email": "agupta@xxxxxx.com",
  "email_verified": true,
  "groups": [
    "a468f8ad-1234-47f6-83b3-971f389fbda6"
  ],
  "name": "abhi@xxxxx.com"
}

```

**Comment by jmazzitelli** [comment]
It is definitely this line of code that causes the failure:

https://github.com/kiali/kiali/blob/5a08687654ec843c5cbc7be43ec5a1ec5a49b40e/handlers/authentication.go#L319-L322

(side note, I need to find out why the "err" error message is not being logged here - that would have helped a lot).

That's the check that is failing when processing OpenID tokens. There is [no other place here](https://github.com/kiali/kiali/search?q=%22Token+is+not+valid+or+is+expired%22&unscoped_q=%22Token+is+not+valid+or+is+expired%22) that responds with `"Token is not valid or is expired"`

There is something in the user's permissions that is cause this GetNamespaces() to fail, which is this code: 

https://github.com/kiali/kiali/blob/5a08687654ec843c5cbc7be43ec5a1ec5a49b40e/business/namespaces.go#L61

**Comment by widdix123** [comment]
@jmazzitelli  - Do you have a sample config file for dex and kiali ? It would be helpful for me to debug it  as user permissions is not an issue as it has a admin role

**Comment by jmazzitelli** [comment]
This is how the integration test [sets up Dex on minikube](https://github.com/kiali/kiali/blob/v1.21/hack/k8s-minikube.sh#L96-L256).

The test configures Kiali [here](https://github.com/kiali/kiali-operator/blob/v1.21/molecule/openid-test/kiali-cr.yaml#L8-L14) and [here](https://github.com/kiali/kiali-operator/blob/v1.21/molecule/openid-test/molecule.yml#L27-L32).

**Comment by jmazzitelli** [comment]
If you are on Chrome, use F12 and use the Network debug section to inspect the call that fails - try to get the Error JSON - the details of the error should be in there. The Error that is returned is being sent back to the client with this call:

```
RespondWithJSON(w, code, responseError{Error: message, Detail: detail})
```

It would be nice to find out what that "Detail" message is - that's going to tell you why k8s failed to look up the namespaces.

**Comment by widdix123** [comment]
@jmazzitelli  - This is the error

{"error":"Token is not valid or is expired","detail":"Unauthorized"}

**Comment by jmazzitelli** [comment]
OK. Well, that doesn't help much LOL. Yeah, it just thinks that user token doesn't have permissions to get the list of namespaces.

**Comment by cfcosta** [comment]
@widdix123 Just to make sure, can you verify if this still happens on 1.21? From what I've seen, and that might not be it, your oidc request is not sending the expiration Params, which is required on 1.19 but not on 1.21.

**Comment by jmazzitelli** [comment]
> Just to make sure, can you verify if this still happens on 1.21?

He already did -- see earlier comment above

**Comment by widdix123** [comment]
@jmazzitelli  - I checked the setup and the only thing i am using different is SAML connector in dex instead of github . Dex is able to authenticate me and gives me a JWT token that is valid

This is the redirect url, do you see anything wrong here ? 

```
http://localhost:20001/kiali/#access_token=xxxxxxxxxx&state=xxxxxxxxxxxz&token_type=bearer
```

**Comment by jmazzitelli** [comment]
I am afraid once we get down into the weeds of the OIDC protocol, I'm lost. The guy who actually implemented this Kiali "openid" stuff (@israel-hdez) is away until next Monday (otherwise, I would ask him to chime in). What I can say is this is the code that does the authentication using the openid strategy: 

https://github.com/kiali/kiali/blob/5a08687654ec843c5cbc7be43ec5a1ec5a49b40e/handlers/authentication.go#L214

and here is how we test the openid protocol in the integration test (this tests with Dex on minikube using an Ansible test script):

https://github.com/kiali/kiali-operator/blob/master/molecule/openid-test/converge.yml#L51-L181

Maybe something in there will help.

**Comment by widdix123** [comment]
@jmazzitelli  - I still dont see anything that could cause problem .

**Comment by khankth** [comment]
Hi,
I have similar config to what @widdix123 has, but I instead of dex I am using keycloak as IdP. I am getting a wrong authorization endpoint after redirect.
My config:
Version: v1.21.0
```
auth:
  strategy: openid
  openid:
    client_id: "kubernetes"
    issuer_uri: "https://y.x.x.x.com/auth/realms/master"
    username_claim: "groups"
    insecure_skip_verify_tls: true
    scopes: ["openid", "profile", "email", "groups"]
```

**expected behaviour:**

1. Configure configmap of kiali with above config
2. Create a ClusterRoleBinding to add **group** to have access to Kiali
3. Login to Kiali Console(https://x.x.x.x.x.com) and Click on "LogIn with OpenId"
4. It should redirect to **issue_uri**(https://y.x.x.x.com/auth/realms/master) in order to login(as per docs, if authorization_endpoint is not specified, issuer_uri is used, I even tried with authorization_endpoint but got same behaviour) 

**Actual behaviour**
At step 4,(instead of redirecting to issuer_uri or authorization_endpoint) it redirects to:
 "https://x.x.x.x.x.com:20001/kiali/api/auth/openid_redirect"

With F12 devloper tools in Chrome, even before clicking on "Log in with OpenId", I see the wrong **authorization_endpoint** in _Network-> XHR -> preview_
```
authorizationEndpoint: "https://x.x.x.x.x.com:20001/kiali/api/auth/openid_redirect"
sessionInfo: {}
strategy: "openid"
```
Please consider this scenario as well.

**Comment by jmazzitelli** [comment]
We are going to have to wait for @israel-hdez to get back - he's the most familiar with this code. Unless someone else wants to dig into the code and debug this.

**Comment by jshaughn** [comment]
@israel-hdez I've added this to the sprint, please take a look as soon as possible, thanks.

**Comment by israel-hdez** [comment]
@widdix123 

> This is the redirect url, do you see anything wrong here ?
> 
> ```
> http://localhost:20001/kiali/#access_token=xxxxxxxxxx&state=xxxxxxxxxxxz&token_type=bearer
> ```

What I see wrong is that the callback redirection does not include the "id_token" parameter. The callback should be something like:

```
http://localhost:20001/kiali/#access_token=xxxxxxxxxx&state=xxxxxxxxxxxz&token_type=bearer&id_token=xyz
```

The `id_token` is what Kiali uses to query Kubernetes.
But it's weird, if it were missing, you should get a different error: a "Token is empty or invalid." error should be.

I see that you were able to capture the callback url. I also see that `kubectl auth can-i` command is returning `yes` for your user. You will need to make sure that the token generated by Dex is valid within Kubernetes. To check, run:

```
export KUBECONFIG=/path/to/empty/kubeconfig
kubectl --token=$ID_TOKEN get namespaces
```

Where $ID_TOKEN is set to the `id_token` parameter of the callback url. The empty KUBECONFIG file is just to make sure that the credentials in the _kubeconfig_ file won't override the token (sometimes I have seen that if the token is invalid, _kubectl_ may fallback to using credentials in the kubeconfig file). 

If `kubectl` fails with unauthorized status, that means that the token is being rejected by Kubernetes explaining why Kiali does not work. If it works, well... I'll need to think more what can be wrong.

Can you try, please?

**Comment by israel-hdez** [comment]
@khankth 

> **Actual behaviour**
> At step 4,(instead of redirecting to issuer_uri or authorization_endpoint) it redirects to:
> "https://x.x.x.x.x.com:20001/kiali/api/auth/openid_redirect"

This is by design. It's an intermediary endpoint.
That is a Kiali endpoint that generates some codes to mitigate CSRF and authentication replay attacks. After generating the codes, that endpoint should then redirect the browser to the Keycloak endpoint.

So, I see nothing wrong. If you see the Keycloak login page after pressing the "Log in with OpenId", all is good. 
If Kiali fails to authenticate after entering credentials in Keycloak, then that's an issue. You will need to find what's the message  that Kiali is returning after the Keycloak redirection (You will need to find it in the developer console).

**Comment by widdix123** [comment]
@israel-hdez  - i am pretty sure the ID token is valid as i am using the kube-oidc-proxy that works . There are also other services like grafana using OIDC that works with the same token

**Comment by israel-hdez** [comment]
@widdix123 It can be valid, but it doesn't mean it will be accepted by the Kubernetes API Server.

I'm reading this blog post: https://blog.jetstack.io/blog/kube-oidc-proxy/. There is an important part under the **How kube-oidc-proxy works** section:

```
[...] we can set up a reverse proxy in front of the API sever to do the authentication. The kube-oidc-proxy typically sits inside the cluster, and securely serves to the outside world. Once its discovery has been successful, the proxy is ready to take user requests.

Once they are received, the proxy server will authenticate the token in the request’s header using the same internals as the Kubernetes API server. 

[...]

The request then gets sent on to the API server, it being a clone of the original, plus the authenticated, impersonated headers. The request’s authentication is also replaced with the kube-oidc-proxy’s chosen authentication method to the API server, typically a bearer token linked to a Kubernetes Service Account. The Service Account will need RBAC permissions to impersonate any user or group, cluster-wide.
```

In that blog post, I see that they modify the `kubeconfig` file to point to the proxy, instead of directly connecting to the Kubernetes API Server. **This is the key part that I see** to make things work.

What I understand is that you do NOT have your Kubernetes cluster configured for OpenID. Instead, you have a service (in your case it is `kube-oidc-proxy`) that handles OpenID authentication and **forwards** the requests it receives to the Kubernetes API Server. If this is true, this is the reason why Kiali's OpenId authentication is failing.

A difference between Kiali and (for example) Grafana, is that Grafana does not require access to the Kubernetes API. Grafana can even work as a standalone application. In contrast, Kiali requires access to the Kubernetes API Server to query namespaces, Istio resources, services, deployments, etc. But Kiali is doing direct calls to the Kubernetes API Server, and most likely you cluster is not configured to accept OpenID tokens making Kiali's OpenID implementation to fail.

So, I think that Kiali's OpenID is working OK. I think that what you really need is a way to setup Kiali so that it makes API calls through the `kube-oidc-proxy`, instead of contacting the Kubernetes API Server directly. Such config option is currently not available in Kiali.

**Comment by israel-hdez** [comment]
@widdix123 The requirement to setup Kubernetes with OpenID integration is noted in Kiali docs: https://kiali.io/documentation/latest/installation-guide/#_openid_connect

```
The openid strategy requires that your Kubernetes cluster is configured to accept tokens generated
by your identity provider. If your cluster is not properly configured, authentication will fail and users
won’t be able to log in to Kiali. Because of this, the value of client-id, issuer_uri and username_claim
configuration options in Kiali are required to match the --oidc-client-id, --oidc-issuer-url and
--oidc-username-claim flags used to start the cluster API server. If one or more of these values don’t
match, users might fail to log in to Kiali.
```

**Comment by israel-hdez** [comment]
@widdix123 Probably, there is a workaround.
How did you install Kiali? Using `istioctl` or using the Kiali operator?

**Comment by widdix123** [comment]
@israel-hdez  - Istioctl .

**Comment by israel-hdez** [comment]
@widdix123 

Try this patch of the Kiali deployment (replace `127.0.0.1` with the hostname of the proxy):
```
kubectl patch deploy -n istio-system kiali --patch {"spec": {"template": {"spec": {"containers": [{"name": "kiali", "env": [{"name": "KUBERNETES_SERVICE_HOST", "value": "127.0.0.1"}]}]}}}}
```

If you also need to specify the port, then also add an KUBERNETES_SERVICE_PORT environment variable.
Then, restart the pod. If it works, you are lucky. Else, we will need to do changes in Kiali to support your setup.


> Does it mean Kiali OIDC does not support EKS ?

I'd say that, in general, Kiali does not *like* proxies (in some cases, they work) -- it could be AKS or GKS and it will fail when using `kube-oidc-proxy`. It's quite hard to think in all possible setups. We learn about specific cases as we get feedback.

But I think we can make the effort to properly support your setup. We don't want EKS users blocked. I'll discuss with the team.

**Comment by israel-hdez** [comment]
Reclassifying as enhancement, because of the specific environment.
It's going to be scheduled for Kiali v1.23 if workaround does not work.

**Comment by widdix123** [comment]
@israel-hdez  - I checked and i think it would not work . When is planned date for `1.23`

**Comment by israel-hdez** [comment]
@widdix123 Kiali v1.23 is planned for August 28th.

**Comment by israel-hdez** [comment]
Hi @widdix123 

I've created a PR fixing this issue in #3142.
Assuming you still have a cluster with this `kube-oidc-proxy` setup. Would you help me to try the fix?

I would upload a patched Kiali image to my personal Quay.io account to let you try and confirm that works correctly.

**Comment by widdix123** [comment]
@israel-hdez  - sure would love to try it ..

**Comment by israel-hdez** [comment]
Here is the image: https://quay.io/repository/edgarhz/kiali?tab=tags
Use the one tagged as `iss3042`:

`docker pull quay.io/edgarhz/kiali:iss3042`

Since you are installing via `istioctl` you will need to edit the openid section of the Kiali configmap. It should look like the following:

```yaml
auth:                                                                                                                                                                                  [178/1000]
  openid:                   
    api_proxy: https://proxy_host:port
    api_proxy_ca_data: {ca-data-file in base64}
    client_id: {your-client-id}
    issuer_uri: {your-openid-issuer}
    [...other options...]
```

The new settings are `api_proxy` which should contain the URL of `kube-oidc-proxy` and `api_proxy_ca_data` which should contain the certificate-authority file of the proxy (you can find it in your kubeconfig file).

**Comment by widdix123** [comment]
@israel-hdez  - I am getting this error now 

```
{"error":"Error instantiating the business layer","detail":"Invalid remote API server URL"}
```

**Configmap changes**
```
strategy: openid
openid:
   api_proxy: https://kube-apiserver-oidc-proxy.demo.xxxxxx.com
   api_proxy_ca_data:  xxxxxx (baseencoded) 
   client_id: example-app+    
   issuer_uri: https://dex.demo.xxxxx.com/dex
```

**Comment by israel-hdez** [comment]
@widdix123 could you add the port part?
It would be `api_proxy: https://kube-apiserver-oidc-proxy.demo.xxxxxx.com:433`.

I know it's the default port for HTTPS. If it works OK, I'll make changes so that you can omit it.

**Comment by widdix123** [comment]
Now i get this , what access do i need  ? Also , is there a way to add `--oidc-username-claim` and `--oidc-groups-claim` to configmap ? 

```
{"error":"Not enough privileges to login"}

```

**Comment by israel-hdez** [comment]
> Now i get this , what access do i need ? Also , is there a way to add `--oidc-username-claim` and `--oidc-groups-claim` to configmap ?
> 
> ```
> {"error":"Not enough privileges to login"}
> ```

So, I think the remaining config is to add privileges to your service account. If I understand correctly, `kube-oidc-proxy` maps the openid credentials to a service account in kubernetes. Add the privileges to that service account, for example, for cluster wide access:

`kubectl create clusterrolebinding acme-account-clusterbinding --clusterrole=kiali --serviceaccount=acme:myopenidSA`

For `--oidc-username-claim` you add `username_claim: {your-claim}` option inside the `openid` section. For the groups claim, it's not used.

**Comment by widdix123** [comment]
@israel-hdez  - I am using groups claim in dex as it is important for us to use groups .. So it should be there

**Comment by israel-hdez** [comment]
> @israel-hdez - I am using groups claim in dex as it is important for us to use groups .. So it should be there

Yes. I mean, groups are not used in Kiali, so we don't need a setting for that claim. But Kiali will pass them, so group privileges should be applied when doing the API calls.

**Comment by widdix123** [comment]
@israel-hdez  - This works fine with username. But it would not work for us as we use `allowedGroups` in dex. 

When dex has `allowedGroups` set in configmap

![image](https://user-images.githubusercontent.com/38529736/91077026-009fac00-e65e-11ea-9ba8-9f40d532ce90.png)


Dex without `allowedGroups` 

![image](https://user-images.githubusercontent.com/38529736/91076552-4f991180-e65d-11ea-97db-224b98407a2d.png)

**Comment by widdix123** [comment]
Also, as my kube-oidc-proxy as groups claim set, it is mandatory for me that everywhere i set claim as "Groups" instead of username-claim

**Comment by israel-hdez** [comment]
> @israel-hdez - Also, as my kube-oidc-proxy as groups claim set, it is mandatory for me that everywhere i set claim as "Groups" instead of username-claim .
> 
> Grafana, Minio , Kubernetes dashboard etc .
> 
> Can something like this be set in Kiali ?
> 
> ```
>                        , "scopes=groups,openid,profile,email"
>                         , "claim-name=groups"
> ```

You can set the scopes. In case you didn't set the scopes, the default config is:

```yaml
auth:                                                                                                                                                                                                      
  openid:                                                                                                                                                                                                      
    scopes:                                                                                          
    - openid                                                                                         
    - profile                 
    - email   
```

About the groups claim, we choose to omit it because it's unused in Kiali. I think the problem is not there.

> This works fine with username. But it would not work for us as we use allowedGroups in dex.

Reading the Dex docs in https://github.com/dexidp/dex/blob/master/Documentation/connectors/saml.md#group-filtering, I see this is more a Dex configuration for the SAML 2.0 connector.

Most likely, the login failure with `allowedGroups` turned on is not because of Kiali. I think the user you are using to log-in is NOT member of any of the groups you are configuring in the `allowedGroups` directive. So, I think you must check group membership in the external authentication system.

**Comment by widdix123** [comment]
@israel-hdez - i think it is working as expected in port-forwarding 

However, i needed one other input on kiali . I am hosting it as a service in another dashboard and when i access kiali it redirects me to "Login with OpenId". I click and it  redirects me to https url with port 20001 `https://demo.xxxxx.com:20001/kiali/api/auth/openid_redirect `

If i remove 20001 from the URL , it goes to dex . Is there a solution for this fix ( i know it is not related to this ticket )

**Comment by jmazzitelli** [comment]
> If i remove 20001 from the URL , it goes to dex . Is there a solution for this fix ( i know it is not related to this ticket )

I think this is what you want: https://kiali.io/documentation/staging/faq/#x-forwarded-port

**Comment by widdix123** [comment]
@jmazzitelli - Does not work on 1.6.5 .

My use case is little different 

i have a dashboard hosting many internal services like kiali, jeager, grafana etc. The dashboard is accessed externally via Istio Gateway and Virtual Service . 

I created a Virtual Service for kiali in istio-system namespace but the dashboard on different namespace still redirects to 20001 port instead of 443

**Comment by israel-hdez** [comment]
@widdix123 So, first, I would like to confirm that OpenID is now working OK for your setup (despite the port issue). If it's working, I'll move forward the fix and make sure it is included in the upcoming v1.23 release.

> i have a dashboard hosting many internal services like kiali, jeager, grafana etc. The dashboard is accessed externally via Istio Gateway and Virtual Service .

The FAQ entry that @jmazzitelli provided should give some direction about what to do. In short, you should configure your exposure method to inject the `X-Forwarded-Port` header with the wanted port.

So, whatever object or service you setup to access Kiali through the `https://demo.xxxxx.com:20001/kiali` URL, most likely, that's the object/service you should modify to inject the `X-Forwarded-Port` header.

**Comment by widdix123** [comment]
@israel-hdez  -Yes the fix works with add 443 to the `kube-oidc-proxy` api url . As stated , once that is fixed it is good to go on 1.23 release

**Comment by widdix123** [comment]
@israel-hdez - It works with Groups as you stated . I have no issue at all with the fix :) . Nice work !!!! 

I will check on `X-Forwarded-Port` separately .

**Comment by christianlafleur** [comment]
I have the same issue. Can i use Istio envoy as API Proxy ?
