### ISSUE TITLE
Add Filtering to new Full-screen Log view

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#3049]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to filter in the new Full-screen log view just as one can do in the normal split log view.

**Describe the solution you'd like**
Add a Filter to Full-screen log view just like split log view. 

**Describe alternatives you've considered**
This would entail componentizing the filtering so it could be used under both views.

**Issues**
Epic: https://github.com/kiali/kiali/issues/2232

**Comment by jshaughn** [comment]
Closing as the log view is being actively evaluated as part of https://github.com/kiali/kiali/issues/3499.
