### ISSUE TITLE
Clean up kiali.io

### ISSUE THREAD

**Issue by cfcosta** [kiali/kiali#3051]
These are some tasks that need to be done to make the website easier for people to contribute, as well as making the build process cleaner and more reliable.

- [x] Remove any instructions of running hugo and asciidoctor locally
- [x] Clean up Dockerfile to remove non-docker make targets
- [x] Stop using bundler in favor of system installed gems
- [x] Rename `edge` to `staging` to make it more clear
- [x] Add documentation about versioned documentation on the README
- [ ] Verify how much work we need to do if we want to use htmlproofer https://github.com/kiali/kiali.io/pull/227

**Comment by lucasponce** [comment]
All topics seem ok, but I miss a review of the README with simple instructions about "how to write documentation".
Today, to add/update documentation it requires a huge implicit knowledge about where are located things.

I think that a paragraph target new contributors would definitely help.
Things that I would include (where to locate content - i.e. for a new version, for an existing one -, any special trick needed for a local link, etc).

I mean, I expect just two/three lines paragraph with these questions clarified (no need to provide an extended/detailed description of the technology used or anything else, just if someone wants to document a new feature, how he/she should do it).

Thanks !

**Comment by jshaughn** [comment]
@cfcosta One super minor change that may be useful, where it says, "Older Versions" in the Documentation menu items, perhaps it should be "Other Versions" because not all versions may older.

**Comment by cfcosta** [comment]
@lucasponce @jshaughn sounds good!

**Comment by jshaughn** [comment]
@cfcosta I think this issue needs to be updated?  I think last Friday you mentioned most if not all of this was complete?

**Comment by cfcosta** [comment]
@jshaughn I was finishing rewriting the README, should be ok now.
