### ISSUE TITLE
[Istio 1.7] Missing some response time edge labels

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#3053]
Testing with Istio 1.7 (note, I haven't tested with 1.6 - if problem appears there too, we can requalify issue as a general bug in $title)

When showing response time edge labels , some of the edges do not show any label :
![Capture d’écran de 2020-07-30 11-16-02](https://user-images.githubusercontent.com/2153442/88905596-b5f56480-d256-11ea-92bd-ce8bea19737b.png)

It seems to concern workload-to-service edges only, or versioned_app-to-service in versioned app graph type.
Note that the response time metric exists, as it is displayed in the summary panel. They are also visible in Metrics page (for both source & destination reporters). So there must be something wrong in graph queries?

**Comment by jshaughn** [comment]
@jotak This is working as expected.  We don't show response-time for edges leading into service nodes.  This is stated in the "info" associated with the Response Time Display option (you can hover on the info icon).

This has to do with the fact that we can't calculate the RT properly/easily from the individual traffic TS that make up the requests.  Remember that that edge is a logical aggregation of all requests for the service and as such to properly determine the quantiles you need to query that set as a whole.  We do that in the side-panel.

**Comment by jotak** [comment]
oops, ok, my bad!
