### ISSUE TITLE
Support rootNamespace: administrative namespace for istio config

### ISSUE THREAD

**Issue by xeviknal** [kiali/kiali#3062]
Istio has an option to specify a `rootNamespace`

> The namespace to treat as the administrative root namespace for Istio configuration. When processing a leaf namespace Istio will search for declarations in that namespace first and if none are found it will search in the root namespace. Any matching declaration found in the root namespace is processed as if it were declared in the leaf namespace.The precise semantics of this processing are documented on each resource type

In the `rootNamespace` will go the typical mesh-wide configurations (i.e. PeerAuthentications, Sidecars, DestinationRules) and other fall-back objects.

This adjustment should be performed, at least, in the validations and mutual TLS status endpoints. This shouldn't be a big change because it should be a replacement of istio-system by rootNamespace.

**Comment by lucasponce** [comment]
This seems valid in the context of the validations logic.

Added to the Project as part of the revision process of the backlog.

**Comment by jmazzitelli** [comment]
Is this rootNamespace potentially different than, or the same as, the control plane namespace? (as defined [here](https://github.com/kiali/kiali-operator/blob/v1.34.0/deploy/kiali/kiali_cr.yaml#L60-L66) -- `spec.istio_namespace`)?

**Comment by xeviknal** [comment]
@jmazzitelli I understand the `rootNamespace` as the place where to put the default configs (those configs that are subject to inheritance such as PeerAuthn) not where you deploy the control plane.

Check out the first two snippets in the sidecar doc page: https://istio.io/latest/docs/reference/config/networking/sidecar/ 
There is one default sidecar config (without workloadSelector) that applies to all sidecars in the mesh and lives in a namespace called `istio-config`. The second snippet is the definition of a sidecar for a set of workloads. This second sidecar inherits behavior from the first one.

By default, the `rootNamespace` is the `istio-system`. Our validations system need to know this rootNamespace in order to fetch this defaults from there instead of the control-plane namespace.

So yes, this `rootNamespace` might potentially point to a different namespace than the control plane.

Hope it answers the question :sweat_smile:

**Comment by lucasponce** [comment]
@xeviknal I think this one would be nice to update it, now that we see that users are expanding the typical deployments in istio.

**Comment by leandroberetta** [comment]
Closing this epic as its sub tasks are completed and merged.
