### ISSUE TITLE
Create a simple kiali helm installer

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#3066]
Collecting feedback from the community, it seems that for some basic scenarios people don't want to use the kiali-operator to install Kiali.

This issue is open to study the possibility to write a very simple way to have an instance of Kiali installed in Istio without using the operator.

Note, this is not in any way, any change in the strategy to use the operator, that is designed to manage multiple and complex scenarios.

Finally, the simple kiali helm installer should have a very limited demo scope, it shouldn't be a recommended way to install Kiali in production scenarios where operator should be the way to go.

**Comment by jmazzitelli** [comment]
I agree we could produce and publish a basic "demo" kiali server helm chart. There are some things people will lose if they opt-out of the operator:

1. You lose the ability for multi-tenancy support like Kiali has for Maistra
2. You lose the ability to auto-detect and correct unauthorized changes to the Kiali resources (e.g. if someone deletes the Kiali Deployment or edits the Kiali ConfigMap, the operator is no longer there to auto-revert - it is on you to detect those changes and manually revert)
3. You lose the ability to change the accessible namespaces on the fly (the operator today can force Kiali to have cluster roles given to it only for the namespaces in the mesh - thus added a level of security). The basic helm chart will have accessible_namespaces=** thus allowing Kiali to see everything. That's how it is with the upstream Istio release, so this is no different than how people are used to using it, but I bring it up anyway.
4. You lose the OpenShift Console Links (operator creates those on the fly as namespaces are added to the accessible namespaces list).

There are probably other things I'm forgetting, those are just off the top of my head.
