### ISSUE TITLE
[Tracing] Tracing tab in Service page

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#3071]
The trace tab is being removed from the Service page, because it actually relates to App, not Service: https://github.com/kiali/kiali/issues/3045
But this doesn't mean it cannot be under Services as well ; just that some adjustments are necessary [1]. And we need to fetch the app label related to the service prior to querying jaeger.

So, as an enhancement, add it (back) to the Service Details page as a tab.

[1] post-filtering of Service name, based on operation name?

**Comment by aljesusg** [comment]
Pfff For this ...we can query jaeger to check if "service name" is in the list /api/services that jaeger provides. In that case we can show the tab

**Comment by jotak** [comment]
but this would still be matching against the jaeger service name which corresponds in reality to kiali's app. Whereas Kiali service name is actually visible in jaeger in operation name.

**Comment by jotak** [comment]
I mean, perhaps yes we can do as you suggest and consider it's "good enough".
But we would still miss the services that are != from app names.
