### ISSUE TITLE
Popup message in AlertCenter for Error conditions only

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#3074]
Discussed with @xeviknal that validations have several warnings that are populating the AlertCenter.

The warnings make sense because are valid specially in potential conflicts in Istio Config, but we think it could be good to relax the "popup" of the AlertCenter only on errors situations.

**Comment by lucasponce** [comment]
I think only the INFO messages have no AlertToast

**Comment by jshaughn** [comment]
FWIW, I really dislike arriving on the IstioConfig page and immediately getting toast errors.  I never really understood the approach as the list entries already make clear that there are problems and I think we can just let the user drill in.
