### ISSUE TITLE
Kiali CR fails to deploy due to Github release check - Offline Installation

### ISSUE THREAD

**Issue by robotica72** [kiali/kiali#3079]
I need to deploy Kiali without Internet connectivity - I have the deployment for the Operator and the CR all configured for what I need, and it's close to working, but when the CR is deployed, it has a single failure when it attempts to check the releases on Git, which of course, will fail since I do not have Internet access for pods.  I do have all images pulling from my Local registry.

The same issue happens with the "old" Deployment method or using the Helm Charts (which makes sense).

Is there a setting to disable this check?

---------------
TASK [default/kiali-deploy : Confirm the cluster can access github.com when it needs to determine the last release of Kiali] ***

fatal: [localhost]: FAILED! => {"changed": false, "content": "", "elapsed": 0, "msg": "Status code was -1 and not [200]: Request failed: <urlopen error [Errno -2] Name or service not known>", "redirected": false, "status": -1, "url": "https://api.github.com/repos/kiali/kiali-operator/releases"}

 

PLAY RECAP *********************************************************************

localhost                  : ok=35   changed=0    unreachable=0    failed=1    skipped=29   rescued=0    ignored=0

 -------------------------------------------------------------------------------

{"level":"error","ts":1596547680.6754906,"logger":"controller-runtime.controller","msg":"Reconciler error","controller":"kiali-controller","request":"istio-system/kiali","error":"event runner on failed","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tpkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:258\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\tpkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tpkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\tpkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:88"}

{"level":"info","ts":1596547684.802377,"logger":"logging_event_handler","msg":"[playbook debug]","name":"kiali","namespace":"istio-system","gvk":"kiali.io/v1alpha1, Kind=Kiali","event_type":"runner_on_ok","job":"3328451335138149956","EventData.TaskArgs":""}

 ----------------------------

**Describe the bug**
No Internet access, I need to disable the release check that attempts to access Git.

 **Versions used**
Kiali: 1.22.0
Istio: 1.6.6
Kubernetes flavour and version: (e.g. OpenShift Origin 3.9) - GKE on-prem (K8s 1.16)

 
**To Reproduce**
Disconnect from the Internet, attempt to deploy a Kiali CR.

 
**Expected behavior**
A successful deployment of Kiali

**Comment by jmazzitelli** [comment]
Just set the version you want to use explicitly rather than rely on the default of "lastrelease".

See: https://github.com/kiali/kiali-operator/blob/v1.22.0/deploy/kiali/kiali_cr.yaml#L273-L286

**Comment by robotica72** [comment]
Thanks @jmazzitelli  -  I was trying some of those options and was still running into issues.  In the CR spec, I do have image_version set to v1.22.0 but it wasnt working - Of course, I was looking too quickly - I had that set under the main spec rather than the deployment.spec, moved it and the error stopped.

Cant believe I didnt see that originally - Thanks for the prompt reply.

**Comment by jmazzitelli** [comment]
> Is there a way by which kiali-operator print all the received values?

kiali-operator pod logs - near the top it should emit the values it received in the CR. The usual reason why this doesn't work for people is they did not specify the setting correctly. The value you want to specify is `spec.deployment.image_version`.

Note also the latest version of the operator will, by default, not allow you to set this image_version field (as a security measure). You can tell the operator to allow for this by setting the `allowAdHocKialiImage` helm chart field to `true`. See the [kiali helm chart values yaml](https://github.com/kiali/helm-charts/blob/master/kiali-operator/values.yaml) and [this](https://kiali.io/documentation/staging/installation-guide/#_versioning) for details.
