### ISSUE TITLE
Graphic policy

### ISSUE THREAD

**Issue by matty111** [kiali/kiali#3091]
Is it possible create/remove authoritation policy or deny all from the graph? 
For example, I select two service and after I apply the policy. Now i can create policy only by form in Menu Istio Config

**Comment by lucasponce** [comment]
@matty111 There is an issue in the roadmap for a similar feature, let me find it.

**Comment by lucasponce** [comment]
@matty111 I think you may refer to this https://github.com/kiali/kiali/issues/2924

**Comment by jshaughn** [comment]
I think this is close enough tp #2924 to be closed as a duplicate.  This will be referenced in that issue and I'm going to ask that the other issue be discussed for prioritization.
