### ISSUE TITLE
Tracing page reworking

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#3095]
Summary of discussed changes:

Globally this reworking aims to increase crossing data with other info available from kiali.

- Trace and span details to leverage more envoy-specific data, which is where Kiali adds value compared to jaeger UI
- Add link to trace view in graph (it's actually https://github.com/kiali/kiali/issues/2842 ) **done**
- Include metrics-based comparison / trends for span's duration info
- Remove (or make less apparent?) tags details / raw jaeger data
- Remove the single selection of spans grouped by service; instead, make services buttons be like filters, spans being ordered by timestamps to better understand the timeline
- Fix some links that are not always valid (cf https://github.com/kiali/kiali/issues/3095#issuecomment-691857960)
- Links not only to app details but workloads as well (and service?)
- Improve table layout (cf https://github.com/kiali/kiali/issues/3095#issuecomment-682390528 )
- When a trace is selected, it should be visualized differently on chart **done**

(initial post moved there: https://github.com/kiali/kiali/issues/3095#issuecomment-691857960 )

**Comment by jotak** [comment]
Oh, and also, the column "App" does actually show the Operation name, this is also wrong

**Comment by lucasponce** [comment]
I'm +1 with the changes commented.
I think now that we are working closer with the integration we can review how this information is being showed:

- The first hearder seems correct to me, I see the trace and the span
![image](https://user-images.githubusercontent.com/1662329/91536680-59e53500-e915-11ea-80b7-9f3d52e91256.png)

- When I click in the "span group" I guess there are some improvements on top of the previous comments:
![image](https://user-images.githubusercontent.com/1662329/91536778-8a2cd380-e915-11ea-97e5-d6f1fcc8bdf6.png)

Like adjust the tittles to save more space, perhaps let's use a table format more aligned with other inner tabs in App/Workload/Service details.

I know that we decided to show the details of the span in a way of expanded item with a tab for tags and processed tags.

Personally I think it's time to delegate this info to Jaeger but Kiali should process the relevant info from this in the context of correlation (i.e. instead to show the tags, Kiali can extract some important fields like verb of the operation, code, etc, instead to offer the user to browse on the tags).

And also, in the future I'd like to combine this span info, with other Kiali info (i.e. a span is below an average according with the metrics info).

Also, I think there is some bug in the links to metrics, in some cases it doesn't load the metrics tab, probably some missing update with the refresh.

**Comment by jotak** [comment]
I'm fine with your ideas. Also, I think it would be nice if that screen allowed to better show the sequence of spans. So, instead of grouping them per service (the buttons on first line: "details.default", "reviews.default" ...) perhaps we could show all the spans listed for all services, ordered by timestamp. We can keep however the top buttons, but they would be filters to turn on/off, each independently; all being "on" by default.

That's because a problem I see in that page is that it hides the sequence of spans.

Also .. throwing ideas around: what about a new trace mini-graph component? It would be showing only nodes that are part of the trace (but, it's not for this task, if you like the idea we could open a new dedicated task)

**Comment by lucasponce** [comment]
+1 on all your suggestions, it's perfectly in-line with what we are discussing.

Perhaps better to move some of this ideas to the EPIC about enhancements just for clarity and we can add details on them.

**Comment by jotak** [comment]
Yes it's growing bigger than primarily intended

**Comment by jotak** [comment]
(FTR: initial issues was: )
I think there's a couple of issues to fix. From the screenshot below:

![Capture d’écran de 2020-08-06 16-39-57](https://user-images.githubusercontent.com/2153442/89545744-098e2200-d804-11ea-9068-0e118e9ebde5.png)

(1) shows the application name
(2) and (3) show the operation name

(1) looks fine and its link is correct (links to /console/namespaces/default/applications/ball)

- But (2) links to the exact same item, whereas the operation name is related to the Kiali service, not the Kiali application. So instead of linking to /console/namespaces/default/applications/ball, it should link to /console/namespaces/default/**services**/ball

- Moreover, as you can see in (3), the operation name might not always be related to a service, essentially because the user can create his own traces with his own operations, as I'm showing here. There is an easy way to see if the span originates from Envoy (and in that case, it's OK to interpret operation name as service name) : in case of Envoy, the span has a tag "component" that is set to "proxy". So I think we should not even try to create a link to service from operation names, when tags[component] != "proxy".

- Next thing, I don't think it's a good idea to modify the operation name as here: "ball.default.(etc)" is changed to "ball(default)". So, it's not really the operation name as it was defined... I don't see any good reason for altering this.

- And finally, the links to metrics are also making some confusion between app & service. They use the operation name ( = kiali service) to build a link to application metrics. What we could do instead, is to extract the workload, and link to workload metrics, similar as what is done for logs (and which works well afaict).

**Comment by jotak** [comment]
I've reworked this issue first post to summarize the discussion. I've also added two items:

- When a trace is selected, it should be visualized differently on chart
- I think we should name Jaeger "Jaeger", rather than "Tracing" or "the Tracing tool". Kiali itself is now a tracing tool as well, isn't it?

Please let me know if more things should be discussed / added.

**Comment by lucasponce** [comment]
> I think we should name Jaeger "Jaeger", rather than "Tracing" or "the Tracing tool". Kiali itself is now a tracing tool as well, isn't it?

No.

Tracing is being used in Istio, we moved from jaeger to tracing as we have in the roadmap at some point to support zipkin.

**Comment by jotak** [comment]
> > I think we should name Jaeger "Jaeger", rather than "Tracing" or "the Tracing tool". Kiali itself is now a tracing tool as well, isn't it?
> 
> No.
> 
> Tracing is being used in Istio, we moved from jaeger to tracing as we have in the roadmap at some point to support zipkin.

Today it's not. And if Zipkin is used, we will call zipkin "zipkin". Where's the problem?
Referring to "Tracing" really sounds weird and even incorrect English to me. At least "Go to Tracing UI" sounds more correct, but still, I don't understand why not we name it more accurately.

**Comment by lucasponce** [comment]
@jotak We decided to call it "Tracing" because was the same term used by Istio to refer to the Tracing tool

So, please don't refactoring the wording on this scenario.

**Comment by jotak** [comment]
@lucasponce I've removed it from the task summary until we can agree on something.
But I don't know where you see that Istio is referring to "Tracing", I see it's naming "Jaeger" wherever it makes sense. All istio's doc is full of references to jaeger. Everything the user faces seems to name it accurately. Not us in Kiali.

**Comment by jotak** [comment]
or perhaps you refer to the service name, which indeed is "tracing" ? I don't see that's very relevant compared to all other places where it's named accurately. Docs, helm charts, pod / deployment are "jaeger"... And even without that, Kiali is the user interface, we need to be more user-focused and don't add useless abstractions to the users when we can be clear, I think.

**Comment by lucasponce** [comment]
Please, don't refer that the work of your colleagues are "useless abstractions".

Kiali decided to use the wording "Distributed Tracing" and "Tracing" to build the links.

In the first step we used "Jaeger" but we moved to this "abstraction" and we perfectly documented:

https://kiali.io/documentation/latest/distributed-tracing/

Again, this was part of a strategy to support more than Jaeger.

**Comment by jotak** [comment]
Hey @lucasponce @aljesusg do you think we should use a `VirtualList` component here, for spans?
If we use a list component, similar to what we have in workloads/services/app list pages, with also a toolbar for sorting / filtering (e.g. sort by duration time, filter spans in error, etc.), that seems to be interesting.
Also, I have some big traces with many spans, currently it takes time to display, I believe the VirtualList has some lazy loading that would fix this as well.

**Comment by lucasponce** [comment]
@jotak I'd start by the Simple table, with provides sorting unless you want to address filtering there.

I don't think you can provide lazy loading in the current VirtualList, there is no pagination on backend, so when you want to sort, basically it fetches all and sorts on client.

**Comment by jotak** [comment]
I'm reading the code in VirtualList, I thought it was doing lazy loading but I'm not sure (and not sure if it's in our code or in patternfly's). Actually I should say "lazy displaying", I know it doesn't paginate from the backend, but I thought it wouldn't put everything in DOM at once, but would add items as long as we're scrolling .. is that correct? Because the performance problem I get with big traces is clearly about the DOM, not data fetching.

**Comment by jotak** [comment]
Here it's about fetching all *spans* at once for a single trace, not all *traces* at once, so fetching is not a problem (actually the spans are already contained in the selected trace so there's 0 fetch).
But sometimes there's traces with hundred of spans, these ones show display latency.
Perhaps just the fact that we'll remove the tags list will fix that problem.
