### ISSUE TITLE
helmv3 install fails with zsh on mac

### ISSUE THREAD

**Issue by ishankhare07** [kiali/kiali#3108]
The current installation docs provide the following command for installation through helmv3
```shell
helm install \                                                  
  --namespace istio-system \
  --set auth.strategy="anonymous" \
  --set deployment.accessible_namespaces\[0\]="**" \
  --repo https://kiali.org/helm-charts \
  kiali-server \
  kiali-server
```

This however fails with the following error:
```shell
zsh: no matches found: deployment.accessible_namespaces[0]=**
```

This is caused because `[` and `]` are metacharacters in zsh and need to be properly escaped.

**Versions used**
Kiali: v1.22.1
Istio: 1.6
Kubernetes flavour and version: v1.15.12-gke.2

**To Reproduce**
Run the installation instructions mentioned above or on the official docs for helmv3 on mac with zsh.

**Expected behavior**
Should result in the following output
```
NAME: kiali-server
LAST DEPLOYED: Mon Aug 10 15:48:26 2020
NAMESPACE: istio-system
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Welcome to Kiali! For more details on Kiali, see: https://kiali.io

The Kiali Server [v1.22.1] has been installed in namespace [istio-system]. It will be ready soon.

(Helm: Chart=[kiali-server], Release=[kiali-server], Version=[1.22.1])
```

**Fix**
The fix for this issue is to update the docs with the following:
```
helm install \                                             
  --namespace istio-system \
  --set auth.strategy="anonymous" \
  --set deployment.accessible_namespaces\[0\]="**" \
  --repo https://kiali.org/helm-charts \
  kiali-server \
  kiali-server
```

**Comment by jmazzitelli** [comment]
I'm going to check something - I *think* the default is already `**` for accessible_namespaces. If that is true, I'll change the docs to remove that line entirely - thus we'll have one documented command that would work on Mac (zsh) as well as other shells like bash.

**Comment by jmazzitelli** [comment]
Yes. OK, I was right - the default value is already `**` so there is no reason to have this in the docs. So I'm going to change this to say:

```
helm install \                                             
  --namespace istio-system \
  --set auth.strategy="anonymous" \
  --repo https://kiali.org/helm-charts \
  kiali-server \
  kiali-server
```
