### ISSUE TITLE
travis produced a test-race failure

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#3110]
https://travis-ci.org/github/kiali/kiali/jobs/716650144#L304

Main error appears to be:

```
E0810 17:57:16.283934 11816 dashboards.go:327] runtimes discovery failed, cannot load dashboards in namespace Namespace. Error was: cannot initialize Kubernetes Client: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined

```

===

$ git clone --depth=50 https://github.com/kiali/kiali.git kiali/kiali
$ travis_export_go 1.14.5 github.com/kiali/kiali
0.01s5.25s$ travis_setup_go
go version go1.14.5 linux/amd64
$ export GOPATH="/home/travis/gopath"
$ export PATH="/home/travis/gopath/bin:/home/travis/.gimme/versions/go1.14.5.linux.amd64/bin:/home/travis/bin:/home/travis/bin:/home/travis/.local/bin:/usr/local/lib/jvm/openjdk11/bin:/opt/pyenv/shims:/home/travis/.phpenv/shims:/home/travis/perl5/perlbrew/bin:/home/travis/.nvm/versions/node/v8.12.0/bin:/home/travis/.rvm/gems/ruby-2.5.3/bin:/home/travis/.rvm/gems/ruby-2.5.3@global/bin:/home/travis/.rvm/rubies/ruby-2.5.3/bin:/home/travis/gopath/bin:/home/travis/.gimme/versions/go1.11.1.linux.amd64/bin:/usr/local/maven-3.6.3/bin:/usr/local/cmake-3.12.4/bin:/usr/local/clang-7.0.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/home/travis/.rvm/bin:/home/travis/.phpenv/bin:/opt/pyenv/bin:/home/travis/.yarn/bin"
$ export GO111MODULE="auto"
cache.1
Setting up build cache
$ gimme version
v1.5.4
$ go version
go version go1.14.5 linux/amd64
go.env
$ go env
install.1
0.74s$ make swagger-install
install.2
2.06s$ make lint-install
before_script
0.01s$ GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)
0.26s$ if [ ! -z "$(gofmt -l ${GO_FILES})" ]; then echo "These files need to be formatted:" "$(gofmt -l ${GO_FILES})";echo "Diff files:"; gofmt -d ${GO_FILES}; exit 1; fi
The command "if [ ! -z "$(gofmt -l ${GO_FILES})" ]; then echo "These files need to be formatted:" "$(gofmt -l ${GO_FILES})";echo "Diff files:"; gofmt -d ${GO_FILES}; exit 1; fi" exited with 0.
91.42s$ make lint
golangci-lint run --skip-files "doc\.go" --tests --timeout 5m
The command "make lint" exited with 0.
12.44s$ make swagger-travis
2020/08/10 17:55:35 
The swagger spec at "./swagger.json" is valid against swagger specification 2.0
The command "make swagger-travis" exited with 0.
135.19s$ make clean build test-race
Cleaning...
Building...
GOOS=linux GOARCH=amd64 CGO_ENABLED=0  go build \
	-o /home/travis/gopath/bin/kiali -ldflags "-X main.version=v1.23.0-SNAPSHOT -X main.commitHash=996d4a4f650568b7f10c97916279ea3ddbfd4ae8"
go: downloading github.com/dgrijalva/jwt-go v3.2.0+incompatible
go: downloading github.com/jaegertracing/jaeger v1.15.1
go: downloading github.com/prometheus/common v0.4.1
go: downloading github.com/openshift/api v0.0.0-20200221181648-8ce0047d664f
go: downloading github.com/NYTimes/gziphandler v1.1.1
go: downloading github.com/gorilla/mux v1.7.4
go: downloading github.com/prometheus/client_golang v0.9.4
go: downloading k8s.io/apimachinery v0.0.0-20190816221834-a9f1d8a9c101
go: downloading gopkg.in/yaml.v2 v2.2.8
go: downloading gopkg.in/ldap.v2 v2.5.1-0.20190417171812-9f0d712775a0
go: downloading github.com/hashicorp/go-version v0.0.0-20180322230233-23480c066577
go: downloading github.com/kiali/k-charted v0.6.1
go: downloading k8s.io/api v0.0.0-20190313235455-40a48860b5ab
go: downloading github.com/stretchr/testify v1.4.0
go: downloading github.com/jtblin/go-ldap-client v0.0.0-20161205001958-ad9f2ea47a83
go: downloading github.com/prometheus/procfs v0.0.10
go: downloading github.com/stretchr/objx v0.1.1
go: downloading k8s.io/client-go v11.0.1-0.20190820062731-7e43eff7c80a+incompatible
go: downloading gopkg.in/asn1-ber.v1 v1.0.0-20181015200546-f715ec2f112d
go: downloading github.com/prometheus/client_model v0.2.0
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.2-0.20181231171920-c182affec369
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading github.com/pmezard/go-difflib v1.0.0
go: downloading github.com/beorn7/perks v1.0.1
go: downloading github.com/golang/protobuf v1.3.5
go: downloading github.com/gogo/protobuf v1.1.1
go: downloading k8s.io/klog v1.0.0
go: downloading github.com/golang/glog v0.0.0-20160126235308-23def4e6c14b
go: downloading gopkg.in/inf.v0 v0.9.1
go: downloading github.com/google/gofuzz v1.1.0
go: downloading sigs.k8s.io/yaml v1.2.0
go: downloading github.com/modern-go/reflect2 v1.0.1
go: downloading github.com/json-iterator/go v1.1.6
go: downloading golang.org/x/net v0.0.0-20190603091049-60506f45cf65
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: downloading k8s.io/utils v0.0.0-20200720150651-0bdb4ca86cbc
go: downloading golang.org/x/oauth2 v0.0.0-20200107190931-bf48bf16ab8d
go: downloading golang.org/x/time v0.0.0-20200630173020-3af7569d3a1e
go: downloading github.com/hashicorp/golang-lru v0.5.4
go: downloading golang.org/x/crypto v0.0.0-20190308221718-c2843e01d9a2
go: downloading github.com/googleapis/gnostic v0.4.0
go: downloading k8s.io/klog/v2 v2.0.0
go: downloading github.com/go-logr/logr v0.1.0
go: downloading golang.org/x/sys v0.0.0-20190215142949-d0b11bdaac8a
go: downloading golang.org/x/text v0.3.3
Running tests with race detection, excluding third party tests under vendor
go test -race github.com/kiali/kiali github.com/kiali/kiali/appstate github.com/kiali/kiali/business github.com/kiali/kiali/business/checkers github.com/kiali/kiali/business/checkers/authorization github.com/kiali/kiali/business/checkers/common github.com/kiali/kiali/business/checkers/destinationrules github.com/kiali/kiali/business/checkers/gateways github.com/kiali/kiali/business/checkers/peerauthentications github.com/kiali/kiali/business/checkers/serviceentries github.com/kiali/kiali/business/checkers/services github.com/kiali/kiali/business/checkers/sidecars github.com/kiali/kiali/business/checkers/virtual_services github.com/kiali/kiali/config github.com/kiali/kiali/config/security github.com/kiali/kiali/graph github.com/kiali/kiali/graph/api github.com/kiali/kiali/graph/config/cytoscape github.com/kiali/kiali/graph/telemetry github.com/kiali/kiali/graph/telemetry/istio github.com/kiali/kiali/graph/telemetry/istio/appender github.com/kiali/kiali/graph/telemetry/istio/util github.com/kiali/kiali/handlers github.com/kiali/kiali/jaeger github.com/kiali/kiali/jaeger/jaegertest github.com/kiali/kiali/kubernetes github.com/kiali/kiali/kubernetes/cache github.com/kiali/kiali/kubernetes/kubetest github.com/kiali/kiali/ldap github.com/kiali/kiali/log github.com/kiali/kiali/models github.com/kiali/kiali/prometheus github.com/kiali/kiali/prometheus/internalmetrics github.com/kiali/kiali/prometheus/prometheustest github.com/kiali/kiali/routing github.com/kiali/kiali/server github.com/kiali/kiali/status github.com/kiali/kiali/tests/data github.com/kiali/kiali/tests/data/validations github.com/kiali/kiali/util github.com/kiali/kiali/util/httputil github.com/kiali/kiali/util/intutil github.com/kiali/kiali/util/mtls
ok  	github.com/kiali/kiali	0.072s
?   	github.com/kiali/kiali/appstate	[no test files]
E0810 17:57:16.283934   11816 dashboards.go:327] runtimes discovery failed, cannot load dashboards in namespace Namespace. Error was: cannot initialize Kubernetes Client: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
E0810 17:57:16.305978   11816 dashboards.go:327] runtimes discovery failed, cannot load dashboards in namespace Namespace. Error was: cannot initialize Kubernetes Client: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
E0810 17:57:16.323692   11816 dashboards.go:308] runtimes discovery failed, cannot load metrics for labels: {kubernetes_namespace="Namespace",app="httpbin"}. Error was: Get "http://prometheus.istio-system:9090/api/v1/series?end=2020-08-10T17%3A57%3A16.30610963Z&match%5B%5D=%7Bkubernetes_namespace%3D%22Namespace%22%2Capp%3D%22httpbin%22%7D&start=2020-08-10T16%3A57%3A16.30610963Z": dial tcp: lookup prometheus.istio-system on 169.254.169.254:53: no such host
E0810 17:57:16.323936   11816 dashboards.go:308] runtimes discovery failed, cannot load metrics for labels: {kubernetes_namespace="Namespace",app="httpbin"}. Error was: Get "http://prometheus.istio-system:9090/api/v1/series?end=2020-08-10T17%3A57%3A16.284101683Z&match%5B%5D=%7Bkubernetes_namespace%3D%22Namespace%22%2Capp%3D%22httpbin%22%7D&start=2020-08-10T16%3A57%3A16.284101683Z": dial tcp: lookup prometheus.istio-system on 169.254.169.254:53: no such host
panic: sync: negative WaitGroup counter
goroutine 466 [running]:
sync.(*WaitGroup).Add(0xc0003b8a20, 0xffffffffffffffff)
	/home/travis/.gimme/versions/go1.14.5.linux.amd64/src/sync/waitgroup.go:74 +0x2c0
sync.(*WaitGroup).Done(0xc0003b8a20)
	/home/travis/.gimme/versions/go1.14.5.linux.amd64/src/sync/waitgroup.go:99 +0x42
github.com/kiali/kiali/business.(*IstioStatusService).getComponentNamespacesWorkloads.func1(0xc0003b8a20, 0xc0003b14e0, 0x1b4a3f7, 0xc, 0xc00055e960, 0xc00055e9c0)
	/home/travis/gopath/src/github.com/kiali/kiali/business/istio_status.go:83 +0x1b7
created by github.com/kiali/kiali/business.(*IstioStatusService).getComponentNamespacesWorkloads
	/home/travis/gopath/src/github.com/kiali/kiali/business/istio_status.go:78 +0x356
FAIL	github.com/kiali/kiali/business	0.288s
ok  	github.com/kiali/kiali/business/checkers	0.043s
ok  	github.com/kiali/kiali/business/checkers/authorization	0.095s
ok  	github.com/kiali/kiali/business/checkers/common	0.064s
ok  	github.com/kiali/kiali/business/checkers/destinationrules	0.099s
ok  	github.com/kiali/kiali/business/checkers/gateways	0.069s
ok  	github.com/kiali/kiali/business/checkers/peerauthentications	0.063s
ok  	github.com/kiali/kiali/business/checkers/serviceentries	0.062s
ok  	github.com/kiali/kiali/business/checkers/services	0.054s
ok  	github.com/kiali/kiali/business/checkers/sidecars	0.064s
ok  	github.com/kiali/kiali/business/checkers/virtual_services	0.134s
ok  	github.com/kiali/kiali/config	0.072s
ok  	github.com/kiali/kiali/config/security	0.032s
?   	github.com/kiali/kiali/graph	[no test files]
ok  	github.com/kiali/kiali/graph/api	0.284s
ok  	github.com/kiali/kiali/graph/config/cytoscape	0.069s
?   	github.com/kiali/kiali/graph/telemetry	[no test files]
?   	github.com/kiali/kiali/graph/telemetry/istio	[no test files]
ok  	github.com/kiali/kiali/graph/telemetry/istio/appender	0.136s
?   	github.com/kiali/kiali/graph/telemetry/istio/util	[no test files]
ok  	github.com/kiali/kiali/handlers	0.366s
?   	github.com/kiali/kiali/jaeger	[no test files]
?   	github.com/kiali/kiali/jaeger/jaegertest	[no test files]
ok  	github.com/kiali/kiali/kubernetes	0.336s
ok  	github.com/kiali/kiali/kubernetes/cache	0.043s
?   	github.com/kiali/kiali/kubernetes/kubetest	[no test files]
?   	github.com/kiali/kiali/ldap	[no test files]
?   	github.com/kiali/kiali/log	[no test files]
ok  	github.com/kiali/kiali/models	0.072s
?   	github.com/kiali/kiali/prometheus	[no test files]
ok  	github.com/kiali/kiali/prometheus/internalmetrics	1.033s
ok  	github.com/kiali/kiali/prometheus/prometheustest	0.179s
ok  	github.com/kiali/kiali/routing	0.076s
ok  	github.com/kiali/kiali/server	0.917s
ok  	github.com/kiali/kiali/status	0.059s
ok  	github.com/kiali/kiali/tests/data	0.042s
?   	github.com/kiali/kiali/tests/data/validations	[no test files]
ok  	github.com/kiali/kiali/util	0.027s
ok  	github.com/kiali/kiali/util/httputil	0.030s
?   	github.com/kiali/kiali/util/intutil	[no test files]
?   	github.com/kiali/kiali/util/mtls	[no test files]
FAIL
make/Makefile.build.mk:65: recipe for target 'test-race' failed
make: *** [test-race] Error 1

**Comment by jotak** [comment]
@jmazzitelli @xeviknal is it still happening? I'm not sure if it's related to custom dashboards, but if so, I can take a look

**Comment by xeviknal** [comment]
@jotak I couldn't track it bc I was out of office for 2 weeks. Though, I thought it was because of the Istio Components feature. Tbh, I haven't put my hands on it yet.

```
panic: sync: negative WaitGroup counter
goroutine 466 [running]:
sync.(*WaitGroup).Add(0xc0003b8a20, 0xffffffffffffffff)
/home/travis/.gimme/versions/go1.14.5.linux.amd64/src/sync/waitgroup.go:74 +0x2c0
sync.(*WaitGroup).Done(0xc0003b8a20)
/home/travis/.gimme/versions/go1.14.5.linux.amd64/src/sync/waitgroup.go:99 +0x42
github.com/kiali/kiali/business.(*IstioStatusService).getComponentNamespacesWorkloads.func1(0xc0003b8a20, 0xc0003b14e0, 0x1b4a3f7, 0xc, 0xc00055e960, 0xc00055e9c0)
/home/travis/gopath/src/github.com/kiali/kiali/business/istio_status.go:83 +0x1b7
created by github.com/kiali/kiali/business.(*IstioStatusService).getComponentNamespacesWorkloads
/home/travis/gopath/src/github.com/kiali/kiali/business/istio_status.go:78 +0x356
FAIL github.com/kiali/kiali/business 0.288s
```
