### ISSUE TITLE
Namespace Enable/Disable Auto Injection - Fails on OCP cluster

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#3119]
Tested on OpenShift Version 4.5.4.

Any action to Enable or Disable Auto Injection on namespace fails with error:
"Project.project.openshift.io "bookinfo" is invalid: metadata.labels[istio-injection]: Invalid value: "disabled": field is immutable, try updating the namespace"
![Screenshot from 2020-08-12 13-56-36](https://user-images.githubusercontent.com/604313/90013384-77739700-dca5-11ea-8636-039923858f42.png)

Manual injection of "oc label namespace bookinfo istio-injection=enabled --overwrite" works for the same user.

![Screenshot from 2020-08-12 14-13-25](https://user-images.githubusercontent.com/604313/90013697-126c7100-dca6-11ea-8abd-8c09481a51f8.png)

[configmap-kiali.txt](https://github.com/kiali/kiali/files/5062549/configmap-kiali.txt)

**Comment by lucasponce** [comment]
> Manual injection of "oc label namespace bookinfo istio-injection=enabled --overwrite" works for the same user.

Ok, I used the "project" resource in OpenShift resources but it seems it's better to use in an uniform way the "namespace" one.

I'll apply the changes.

Thanks @hhovsepy
