### ISSUE TITLE
Alignment issue on Status column being top aligned to the others middle aligned

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#3122]
**General remarks**
In the listing view there is an alignment issue with the status column being top aligned to the rest of the columns being middle aligned.

![Kiali_Console](https://user-images.githubusercontent.com/1312165/90075249-c9221e80-dcb1-11ea-9d61-bf75c9ae3126.png)

**To Reproduce**
1. From Overview page click on a Label:
![Kiali_Console](https://user-images.githubusercontent.com/1312165/90075067-6466c400-dcb1-11ea-8771-14b6fa9b551c.png)

2. Observe the listing page alignment issue

**Comment by lucasponce** [comment]
I'm not sure if I understand the aligned problem.
The status is representing the apps/services/workload status + traffic AND the N Application + Icons is designed to be aligned to the right.

Please, on cases like this where it can be some ambiguity / interpretation, don't you think is better to ping on the IRC ?

If we fill bugs and add them into the Sprint we increase the grooming when perhaps we can just comment this to see if it's a real bug or something different.

I'm going to close it, as I don't see a bug on it, the component is consistent with the other overview namespaces views.

**Comment by jshaughn** [comment]
Removing from Sprint as there was no work here and it should not be in the release notes.
