### ISSUE TITLE
Url doesn't change when clicking on Overview label link

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#3123]
**Describe the bug**
When clicking on the label link on the overview page I am taken to the listing page but my URL remains the same; of the overview page.

**To Reproduce**
1. Go to  Overview page and click on a label:
![Kiali_Console](https://user-images.githubusercontent.com/1312165/90076804-85311880-dcb5-11ea-8d7b-dd1497778a0f.png)

2. The page has changed to a listing page but the URL still reads as the overview page
<img width="2331" alt="Banners_and_Alerts_and_Kiali_Console" src="https://user-images.githubusercontent.com/1312165/90077071-11434000-dcb6-11ea-94c0-b250978b9f26.png">

**Comment by lucasponce** [comment]
I don't think it's a bug as it's described.
It's the SAME page but it has several views for the namespaces: compact, expanded and table.
What I'm not sure if all filters and sorting are added to the url, probably that's something to enhance, but I don't see a bug on this.

**Comment by jshaughn** [comment]
@mtho11 I think the better process here would be to report the issue but please don't add to the backlog or sprint backlog.  Instead, you can add Discussion Needed so that we take a look.   Also, I think some of these could be asked about more informally in IRC or something like that and maybe we could avoid an issue altogether.

**Comment by aljesusg** [comment]
We decided to link to the list view to see all labels instead show them on that view.... it's hard have More than 5 labels in that view and keep the size. If I remember there is a tooltip with the labels and when you click you go to the list view of the overview page.
