### ISSUE TITLE
When namespace contains 'istio-injection=disabled' label, Kiali recognizes that as Enabled

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#3125]
On OCP side. manually set a label on namespace: 'istio-injection=disabled'.
In Kiali UI, Overview page, it will suggest to "Disable Auto Injection."

**Comment by lucasponce** [comment]
Right, it's a bug, it should also check the content of the label.
I think it stops in "istio-injection" presence which is incorrect.
