### ISSUE TITLE
i build kiali 1.15.1 on arm64 plantform

### ISSUE THREAD

**Issue by DrowringMan** [kiali/kiali#3131]
i build kiali and istio on arm64 success，istio everything be ok，but my kiali unable to display traffic graph and monitoring
```
kiali error:
 Unknown Istio implementation version 9d07e185b0dd50e6fb1418caa4b4d879788807e3-dirty-9d07e185b0dd50e6fb1418caa4b4d879788807e3-dirty-Modified is not recognized, thus not supported.
```

istio version: 1.5.1
kiali version: 1.15.1

**Comment by jmazzitelli** [comment]
That message is just informational and to be expected when you build your own Istio. It is just saying "you have an Istio that is one that Kiali doesn't know about." This is probably because you built your own Istio. The Istio you installed is not an Istio that was released by the Istio team.

Kiali should still work. If it does not, there might be something wrong with that custom Istio build. We would need more details about "kiali unable to display traffic graph and monitoring" to know what could be wrong.

**Comment by DrowringMan** [comment]
The error report of kiali has been resolved, but now I still can’t see the route, I still can’t see the connection in the graph of kiali when I request the service on the physical machine

**Comment by jmazzitelli** [comment]
> I still can’t see the route, I still can’t see the connection in the graph of kiali when I request the service on the physical machine

I do not think we know how to answer your question. It is not clear what you are expecting. Can you provide more details on what you are doing and seeing?

**Comment by DrowringMan** [comment]
```
root@Kylin:/etc/kubernetes/cert# kubectl get pod -o wide -n istio-system
NAME                                    READY   STATUS    RESTARTS   AGE     IP              NODE           NOMINATED NODE
grafana-7bd688998d-4tcgq                1/1     Running   0          5h56m   172.20.20.191   192.168.1.22   <none>
istio-egressgateway-f4594cd6d-cwv2b     1/1     Running   0          5h57m   172.20.20.189   192.168.1.22   <none>
istio-ingressgateway-744d79d5d6-g4rj8   1/1     Running   0          5h57m   172.20.20.190   192.168.1.22   <none>
istio-tracing-6d58457848-vctnr          1/1     Running   0          5h56m   172.20.20.193   192.168.1.22   <none>
istiod-86f8c97f54-mlx6l                 1/1     Running   0          5h57m   172.20.20.188   192.168.1.22   <none>
kiali-867df89f88-hgl9t                  1/1     Running   0          5h56m   172.20.20.192   192.168.1.22   <none>
prometheus-d6cbcfd8b-qch76              2/2     Running   0          5h56m   172.20.20.194   192.168.1.22   <none>
```
kiali running and Access page is normal
now, curl my svc nginx,  kiali diagram cannot display the connection of the request to the nginx route

**Comment by DrowringMan** [comment]
I want to know whether the connection of kiali reads Prometheus or which component, in order to solve this problem

**Comment by jmazzitelli** [comment]
> I want to know whether the connection of kiali reads Prometheus

Kiali connects to Prometheus to read the metrics from the Istio telemetry stored in Prometheus. See this for more details: 

https://kiali.io/documentation/staging/faq/#prometheus

**Comment by jshaughn** [comment]
It is most likely that you are not generating Istio metrics, so yes, check that FAQ.  Ensure your app pod has the istio proxy injected.

**Comment by DrowringMan** [comment]
> It is most likely that you are not generating Istio metrics, so yes, check that FAQ. Ensure your app pod has the istio proxy injected.

my pod  istio proxy injected.
```
root@Kylin:~# istioctl ps
NAME                                                   CDS        LDS        EDS        RDS          PILOT                       VERSION
istio-egressgateway-f4594cd6d-cwv2b.istio-system       SYNCED     SYNCED     SYNCED     NOT SENT     istiod-86f8c97f54-mlx6l     *
istio-ingressgateway-744d79d5d6-g4rj8.istio-system     SYNCED     SYNCED     SYNCED     SYNCED       istiod-86f8c97f54-mlx6l     *
nginx-v1-654b89bf85-nn2tg.default                      SYNCED     SYNCED     SYNCED     SYNCED       istiod-86f8c97f54-mlx6l     *
nginx-v2-6b99b75b9d-rkhsn.default                      SYNCED     SYNCED     SYNCED     SYNCED       istiod-86f8c97f54-mlx6l     *
prometheus-d6cbcfd8b-qch76.istio-system                SYNCED     SYNCED     SYNCED     SYNCED       istiod-86f8c97f54-mlx6l     *
root@Kylin:~# kubectl get pods
NAME                        READY   STATUS    RESTARTS   AGE
nginx-v1-654b89bf85-nn2tg   2/2     Running   0          22h
nginx-v2-6b99b75b9d-rkhsn   2/2     Running   0          22h
```

**Comment by DrowringMan** [comment]
my kiali graph   "edges": []，Which component is the edge data from?

**Comment by DrowringMan** [comment]
Used Prometheus to access the following two official interfaces are empty
istio_requests_total{reporter="source", destination_service_name="httpbin"}
sum(istio_requests_total{reporter="source", destination_service_name="httpbin"}) by (source_workload, destination_workload)

**Comment by DrowringMan** [comment]
The problem has been solved, it is a proxy problem,thany you @jshaughn,@jmazzitelli
