### ISSUE TITLE
Address refresh inconsistency on Workload details

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#3133]
There ~~are two~~ is one inconsistency in the details pages:
~~- Now that all tabs are sharing time and refresh controls, duration should be correctly propagated into the metrics and tracing tabs.~~
- Workload details have an incosistency when an action provokes an update of the workload, state is not properly shared across other tabs, and it creates a bug in the logs tab (i.e. pointing to a non-existence pod).

**Comment by jotak** [comment]
Taking a short break on my holiday-break here as I feel I need to jump in :-)

The reason why we had two different durations is that they address different situations: the graph or traffic tab is showing more snapshot-like data, non-historical, aggregated in time, hence where the shorter duration will provide the most recent data (so, user will prefer to set duration to something like "last 1 minute").

Whereas on the other hand, metrics / traces / logs show historical data, and having the "last 1 minute" there would provide on the contrary very low value.

That was the reason of this difference.

**Comment by lucasponce** [comment]
I think we are in an agreement, but this is more a UI consistency issue.
Basically now all tabs are sharing the controls, and it sounds weird to have different durations when moving.

So, the propose for this is that if user is coming from other tab with a duration, just to keep that duration in a first place in metrics/tracing tabs for consistency, even all given commented is true, and let user change it, as we have a single shared component that is changing when moving from one tab and another.

**Comment by lucasponce** [comment]
Ok, I'll update the issue to cover only the workload refresh.
It has more implications, specially with the custom selection in metrics tab.

**Comment by jshaughn** [comment]
@lucasponce , @jotak A lot of discussion between two people on PTO :)   I am ambivalent on the subject, but for simplicity I am leaning towards all pages/tabs just using the globally set duration in redux.  It is true that for logs/metrics/traces a short duration, like 1m may not be an optimal experience.  If the user were to arrive at one of these tabs (in workload detail or other detail pages), and the duration is below some minimum (say 10m), here are some options:

1. nothing, just let the user change it as desired
2. pop up a message toast saying that the duration is not optimal and let the user manually change it (max one time for the detail page)
3. pop up a message toast saying that the duration is not optimal and set it automatically to the minimum
4. automatically change it to the minimum

**Comment by lucasponce** [comment]
I think that this requires more thinking because it's not the same control but apparently it is.
I removed from this issue to not cross-post and get lost with the scope of ths issue.

I tend to think that UI consistency should prevail (same control, modified in one page, click to go another, ok, keep the same value).

But all said it makes sense, the only caveat is that user would need to change from 1m to 10m if it's that what he/she wants to do.

I don't like other options: creating a specific control for metrics is in the opposite direction, adding additional toast messages just for this is not enough reason IMO.

So, I think that unify and use the same component should be good, BUT metrics component allows custom timerange which is not supported in others.

Then, there is more side effects here, so I prefer to open a dedicated issue for that. 

T
