### ISSUE TITLE
system:serviceaccount:istio-system:kiali-service-account cannot list resource "servicemeshpolicies"

### ISSUE THREAD

**Issue by pantianying** [kiali/kiali#3136]
Could not fetch Istio objects list: servicemeshpolicies.authentication.maistra.io is forbidden: User "system:serviceaccount:istio-system:kiali-service-account" cannot list resource "servicemeshpolicies" in API group "authentication.maistra.io" in the namespace "istio-project"

version 1.18.3 and version 1.22 both have this issue. pls help me

env : openshift 4.5 istio 1.6.7

**Comment by pantianying** [comment]
W0820 03:57:19.648622       1 tls.go:73] GetServiceMeshPolicies failed during a TLS validation. Probably user can't access to istio-system namespace. Error: servicemeshpolicies.authentication.maistra.io is forbidden: User "system:serviceaccount:istio-system:kiali-service-account" cannot list resource "servicemeshpolicies" in API group "authentication.maistra.io" in the namespace "istio-system"

**Comment by lucasponce** [comment]
@pantianying mmm you mention Maistra, but are you installing Istio 1.6.7 or a Maistra distribution ?

How are you granting users to access to the namespaces ?
