### ISSUE TITLE
kiali telemetry failed

### ISSUE THREAD

**Issue by pantianying** [kiali/kiali#3138]
Kiali telemetry failed, succeeded in one openshift cluster and failed in another openshift cluster(which has 400 namespace). Both clusters adopt istio 1.6.7. We tested it with istio bookinfo.
try operator productpage:
![image](https://user-images.githubusercontent.com/20589945/90727809-74585680-e2f6-11ea-968f-03464a391359.png)
we got this：
![image](https://user-images.githubusercontent.com/20589945/90727783-660a3a80-e2f6-11ea-9175-afc115fb7b6a.png)
maybe this is istio problem,but i don't kwon how to  position problem.

**Comment by lucasponce** [comment]
@pantianying the graph you are showing typically means that there is no telemetry collected on Istio's prometheus.
Would you mind to check if that's the case ?

Also, it seems you are installing Istio 1.6.7 upstream on OpenShift (version?), would you mind to give some details of how did you install it ?

Thanks

**Comment by jmazzitelli** [comment]
> the graph you are showing typically means that there is no telemetry collected on Istio's prometheus.
> Would you mind to check if that's the case ?

We have staged an FAQ to help you check this kind of thing - please see this for details (this will be merged into the latest documentation on the next release - but here's the link to staging for this FAQ that should help): https://kiali.io/documentation/staging/faq/#prometheus

**Comment by jmazzitelli** [comment]
One thing I noticed - you put bookinfo demo in the `istio-system` namespace. Typically, you do not put applications in the control plane namespace (`istio-system`) - I don't think that namespace auto-injects proxies into its pods by default. Put the bookinfo demo in its own namespace (e.g. `default` or `bookinfo`) and see what happens.

See the bookinfo demo instructions here: https://istio.io/latest/docs/examples/bookinfo/#start-the-application-services

**Comment by jshaughn** [comment]
@jmazzitelli Actually, the namespaces says "istio-project", not "istio-system".   So that may not be the issue.  I do see the namespace health is red. See the red icon in the graph side-panel, hover over that to get more information.  Or, alternatively, go to the Overview page.  Something is wrong, you're not generating telemetry.  You selected the "Unused Nodes" display option, that is why you are seeing the app nodes (with dashed borders), but no traffic edges.

**Comment by pantianying** [comment]
> @pantianying the graph you are showing typically means that there is no telemetry collected on Istio's prometheus.
> Would you mind to check if that's the case ?
> 
> Also, it seems you are installing Istio 1.6.7 upstream on OpenShift (version?), would you mind to give some details of how did you install it ?
> 
> Thanks

i follow the istio doc:https://istio.io/latest/docs/tasks/observability/kiali,use `istioctl isntall --profile=demo` to install. yes, my istio version is 1.6.7,on the openshift

**Comment by pantianying** [comment]
> @jmazzitelli Actually, the namespaces says "istio-project", not "istio-system". So that may not be the issue. I do see the namespace health is red. See the red icon in the graph side-panel, hover over that to get more information. Or, alternatively, go to the Overview page. Something is wrong, you're not generating telemetry. You selected the "Unused Nodes" display option, that is why you are seeing the app nodes (with dashed borders), but no traffic edges.


     The reason for the red alarm is that the bookinfo demo has configured a service that does not exist. This has nothing to do with the bug we discussed. When I delete the service configuration, the red alarm does not exist.
    I did select the "unused nodes". Now the problem is that I have successfully operated the page of bookinfo, and there is traffic arriving at the services in the diagram (such as details), but the traffic is not displayed on the kiali page. This has been troubling for a long time.
ths for reply

**Comment by pantianying** [comment]
oh! I find something maybe userful. I configure istio configmap and add rootnamespace:istio-project cause this problem. but why?  
![image](https://user-images.githubusercontent.com/20589945/90849941-0f0e6f00-e3a3-11ea-8a2d-7b870d5bb59c.png)

The purpose of this configuration is to reduce the need for sidecar to monitor other redundant services of the namespace, and why the telemetry function is affected. My Prometheus is deployed in isto system namespace

**Comment by pantianying** [comment]
ths for reply , it seem when didn't adjust rootNamespace , the default rootnamespace is istio-system. when I adjust the rootNamespace, then these default configurations in istio sysytem fail.

**Comment by jshaughn** [comment]
@pantianying If you simply edited the name of the root namespace in the config map, after the original installation, then that would be a problem as supporting defitions will not get updated.  The root namespace should be set at install time.

**Comment by jshaughn** [comment]
@pantianying Hopefully your question has been resolved.  If not, feel free to re-open.
