### ISSUE TITLE
cluster-openshift.sh should default to "darwin" for Mac users

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#314]
The hack script https://github.com/kiali/kiali/blob/master/hack/cluster-openshift.sh assumes you want the Linux binary of istiooc. See: https://github.com/kiali/kiali/blob/master/hack/cluster-openshift.sh#L176

Mac users are required to override this by always passing in the `--istiooc-platform darwin` command line option.

Would be nice for Mac users to have cluster-openshift.sh default to `darwin` without requiring them to explicitly declare that option.

**Comment by pilhuhn** [comment]
Actually that script many need some more tuning

```
+ grep 'OPTIONS=.*--insecure-registry' /etc/sysconfig/docker
+ '[' 2 '!=' 0 ']'
+ grep insecure-registries /etc/docker/daemon.json
+ '[' 2 '!=' 0 ']'
+ echo 'WARNING: You must run Docker with the --insecure-registry argument with an appropriate value (usually "--insecure-registry 172.30.0.0/16"). See the OpenShift Origin documentation for more details: https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md#linux'
WARNING: You must run Docker with the --insecure-registry argument with an appropriate value (usually "--insecure-registry 172.30.0.0/16"). See the OpenShift Origin documentation for more details: https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md#linux
+ echo 'SUDO ACCESS: Determine status of firewalld'
SUDO ACCESS: Determine status of firewalld
+ sudo systemctl status firewalld

```
does not look like OSX style as well

**Comment by mmurphy** [comment]
Not sure if these should be separate issues, or if this issue should be renamed to a general fix ```cluster-openshift.sh``` for MacOS. Any thoughts?

```ip``` command is not available on mine
https://github.com/kiali/kiali/blob/b35f72020c215190b487b11041e8a51c49263f6d/hack/cluster-openshift.sh#L171
this could use ```ifconfig``` or prompt the user if ```ip``` is not available.

Also I use "curl" and not "wget"
https://github.com/kiali/kiali/blob/b35f72020c215190b487b11041e8a51c49263f6d/hack/cluster-openshift.sh#L275
Could check if ```wget``` or ```curl``` are on the path, and use either ```wget -O...``` or ```curl -o...```, or list it as a prerequisite.

**Comment by mmurphy** [comment]
In addition need to fix the ```xargs``` command at https://github.com/kiali/kiali/blob/b35f72020c215190b487b11041e8a51c49263f6d/hack/cluster-openshift.sh#L353
however that probably also requires checking the semantics of mount/umount and openshift volumes on OSX too

**Comment by pilhuhn** [comment]
Hello @mmurphy sorry for not getting back earlier.
I think doing and describing whatever is needed is good.
For curl vs wget, curl is available in the default macOS developer tools, while wget needs to be installed. As we already need to install the envsubst from e.g. homebrew, I think it is also valid to ask the user to install wget. This does not imply I favour wget over curl here, if curl works as well.

I have described a way of installing via `istiooc` here: https://medium.com/@pilhuhn/running-openshift-with-istio-on-os-x-1d4e5014bd01 -- but this just installs the kiali and istio version that comes with istiooc, so this does not really apply here

**Comment by mmurphy** [comment]
Hi @pilhuhn, no problem.
either ````curl``` or ```wget``` can work, I have a fork of this repo which will use either, I'll modify it to exit and prompt the user to install one of them if neither is found.

I don't believe it can be in in the Makefile like ```envsubst``` is, since ```cluster-openshift.sh``` is for non-developers who don't want to build anything.

I don't have solutions yet for the ```ip``` and ```xargs``` problems.

My original question was whether this issue should be a general "fix cluster-openshift.sh for macOS" or if there should be separate GitHub issues for each of these problems

**Comment by jmazzitelli** [comment]
IMO, single issue to fix everything to get it to work on MacOS. One issue, one PR to get MacOS support.

**Comment by mmurphy** [comment]
Hi @jmazzitelli, that seems fine, can it be renamed it to something like "get cluster-openshift.sh working on the current macOS (High Sierra)"

**Comment by jmazzitelli** [comment]
@aljesusg that seems unrelated to the cluster-openshift.sh. I think this issue can be closed because the PR was merged and AFAIK the script can successfully bring up and down the cluster. I'll let @mmurphy chime in - if it works for me on MacOS, and it works for me on Linux, I would say we close this unless someone sees a bug in the script.

**Comment by aljesusg** [comment]
I have all the environment up after use the script but I don't know why I have this error, but it's running , for me is OK, so we can close this.
