### ISSUE TITLE
Add an entry in the FAQ about when a namespace is not listed in Kiali

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#3145]
Kiali has several configuration settings to add and exclude namespaces, plus there is a cache in place that may create some cases when a namespace is not visible (not in accessible list, excluded, or not yet refreshed).

It would be nice to have a FAQ entry about this, there are some info in the installation guide and perhaps in other places, but having a better FAQ entry would help users.

cc @kambei

**Comment by kambei** [comment]
My case appears on CodeReady Containers with OpenShift Service Mesh:

I created a project named "microservices-openshift-example" and in Kiali it is not visible.
Everything works but the namespace isn't showed... When I make the calls from istio-ingressgateway the apps are showed (only in graph view) inside the project istio-system and not in their namespace! Moreover the apps are marked as in "Restricted Namespace".

After creating an other project named "test" and deployed the apps, everything is fine!

**Comment by lucasponce** [comment]
Yes, a test confirm your scenario:

```
package main

import (
	"fmt"
	"regexp"
)

func main() {
	regex := "openshift.*"
	name := "microservices-openshift-example"
	if match, _ := regexp.MatchString(regex, name); match {
		fmt.Printf("%s, %s MATCH \n", regex, name)
	} else {
		fmt.Printf("%s, %s NO MATCH \n", regex, name)
	}

	regex = "^openshift.*"
	name = "microservices-openshift-example"
	if match, _ := regexp.MatchString(regex, name); match {
		fmt.Printf("%s, %s MATCH \n", regex, name)
	} else {
		fmt.Printf("%s, %s NO MATCH \n", regex, name)
	}

	regex = "^openshift.*"
	name = "openshift-example"
	if match, _ := regexp.MatchString(regex, name); match {
		fmt.Printf("%s, %s MATCH \n", regex, name)
	} else {
		fmt.Printf("%s, %s NO MATCH \n", regex, name)
	}
}
```

```
openshift.*, microservices-openshift-example MATCH 
^openshift.*, microservices-openshift-example NO MATCH 
^openshift.*, openshift-example MATCH 
```

So, in case that user want to use the default exclude patterns in
https://github.com/kiali/kiali-operator/blob/master/roles/default/kiali-deploy/defaults/main.yml#L26

He should change that for the `*^openshift.*` instead.

In any case, I wouldn't change the defaults just now but adding an entry in the doc to make this more visible in case other user falls on it.

Thanks @kambei

**Comment by jshaughn** [comment]
@lucasponce Did we ever add the FAQ?

**Comment by tumido** [comment]
Hi all, I've just noticed this issue when I was trying to understand why a `kubeflow` namespace is not showing up in Kiali when the rest of the Service Mesh is able to trace it... Is there any easy way to change these default excludes from within the `ServiceMeshControlPlane` resource?

**Comment by jmazzitelli** [comment]
> Is there any easy way to change these default excludes from within the `ServiceMeshControlPlane` resource?

As far as I understand, you have to directly edit the Kiali CR that OSSM created - I don't think the OSSM Operator can pass down settings from the SMCP to its generated Kiali CR (aside from the very limited options like spec.version and spec.deployment.accessible_namespaces which are managed by the OSSM Operator)

**Comment by jshaughn** [comment]
@nrfox  Please add an FAQ entry in the `General` section.  Something like, "Why isn't my namespace in the Namespace Selection dropdown?"

You could reference accessible namespaces and excluded namespaces as defined in the Kiali CR or config map.  Both are discussed in the install section here, but an FAQ can still be helpful.   And also have a blurb that is specific to OSSM installs (see above).  There may also be some cache-related aspect that I'm not aware of, you may need to ask @lucasponce about how that may affect things.
