### ISSUE TITLE
Include Kiali Configuration in kiali.io

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#3148]
The source of the Kiali configuration options is stored under the operator code:
https://github.com/kiali/kiali-operator/blob/master/deploy/kiali/kiali_cr.yaml

I find more users asking about it and at the end we need to reference to this file much more often than expected.

Perhaps we should include a FAQ or better "Modify Config" section under the FAQ/Installation Guide to make this more explicit.

I don't mean to clone the config, but at least to re-arrange this section

https://kiali.io/documentation/latest/installation-guide/#_create_or_edit_the_kiali_cr

In something more explicit/obvious.

**Comment by jshaughn** [comment]
Closing in favor of #3858.
