### ISSUE TITLE
Upgrade prometheus/client_golang

### ISSUE THREAD

**Issue by huanggze** [kiali/kiali#3153]
Is there any plan to upgrade prometheus/client_golang?

**Comment by lucasponce** [comment]
@huanggze it's something we have discussed. No blockers but it's something we need to check as there are other third party dependencies that use the client_golang and we didn't bump to avoid potential conflicts.

Is there any specific feature/aspect for the bump ? Just to put more context the request ?

**Comment by huanggze** [comment]
Thanks for your reply.

We import kiali into our project KubeSphere. We'd like to adopt client_golang of v1.x for new enhancement and features, but see dependency conflict due to kiali using an older version.

No blockers so far, just curious about if there is a plan to bump client_golang from kiali side.

**Comment by lucasponce** [comment]
Thanks for the visibility @huanggze it's a valueable input for us.

I don't have on top of my mind a "stopper" for this, perhaps we can use this opportunity to invite you to jump into the project, if you can prepare a couple of PRs in the kiali backend and k-charted repos we can review them.
