### ISSUE TITLE
Improve the zoom out behavior when graph is refreshing

### ISSUE THREAD

**Issue by vvavepacket** [kiali/kiali#3158]
**Is your feature request related to a problem? Please describe.**
I'm frustrated whenever I'm on a versioned graph in Kiali and I'm zoomed in (i got a very big graph), then when the graph refreshes every 10 seconds or so, the graphs just zooms out, and then I need to zoom in and find the view where I left off. It could be because there are changes in the graph so it will require a reload or redraw and zooming out.

I got a video here describing the issue.. noticed that im just browsing the graph,, and after some time, it justs zooms out.. so annoying.. is there anyway to avoid that?  issue occurs at 0:42 and 1:02

[Video Link](https://youtu.be/QtWrJIwoM7s)

**Describe the solution you'd like**
It would be a good user experience if the current zoom just stays on wherever it is (instead of zooming out). I noticed a lot of customers also being frustrated

**Describe alternatives you've considered**
We can increase the time so that it doesn't refresh, or even hit pause with the expense of a stale graph

**Additional context**
I understand even if the graph is changing due to number of services being up or down, there needs to be a redraw so its zooming out. But its a lot better of UX if it just stays in place, somehow just store the current coordinates and zoom level is and just stay there.

**Comment by jshaughn** [comment]
@vvavepacket Let us know if Kiali v1.24 solves your problem, releasing soon.

**Comment by vvavepacket** [comment]
It is working. Thank you.

**Comment by jshaughn** [comment]
@vvavepacket Thanks for the feedback!  By the way, if you have not noticed, you can now also manually drag nodes when needed.  It works best when the graph is paused, the position can change when the graph refreshes.
