### ISSUE TITLE
Could not fetch Istio objects list. 

### ISSUE THREAD

**Issue by wansuiye** [kiali/kiali#316]
istioConfig report error
Could not fetch Istio objects list. Error: [ gateways.networking.istio.io is forbidden: User "system:serviceaccount:istio-system:kiali" cannot list gateways.networking.istio.io in the namespace "default" ]

**Comment by lucasponce** [comment]
Thanks for reporting this.
This has been filed https://issues.jboss.org/browse/KIALI-1046 and a patch has been merged.
Please, can you test in latest master ?
Thanks.

**Comment by pilhuhn** [comment]
Just for reference, the patch is in #315

**Comment by pilhuhn** [comment]
Closing, as this was fixed long ago.
