### ISSUE TITLE
Request for `manifest.json` fails behind reverse proxy

### ISSUE THREAD

**Issue by taisph** [kiali/kiali#3162]
**Describe the bug**
When initially accessing Kiali behind a reverse proxy, a request is made for a `/manifest.json` file which gets redirected to an external login server by the proxy due to missing auth data.

Other requests, such as for `/health` and `/metrics`, contain the necessary cookies to authenticate at the proxy. These cookies seem to be missing in the request for `/manifest.json`.

It does not seem to break the Kiali UI though, so it is likely just a minor issue.

**Versions used**
Kiali: v1.22.1
Istio: 1.4.9
Kubernetes flavour and version: v1.16.11-gke.5

**To Reproduce**
1. Setup kiali behind a reverse proxy with oauth authentication.
2. Go to kiali.
3. Check network tab in browser for errors.

**Comment by lucasponce** [comment]
Sorry to not update this issue.
For some reason it escaped to our regular reviews.

I think that the work on the PR https://github.com/kiali/kiali/pull/3568 address the reverse proxy aspects mentioned.

Please let us know if that works.

Thanks.
