### ISSUE TITLE
On Kiali.io video section add horizontal scrolling and titles to videos

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#3164]
**Is your feature request related to a problem? Please describe.**
As we add more videos, the videos section becomes overpowering to the page.

**Describe the solution you'd like**
The ability to horizontal scroll through multiple videos will give us just one row of videos and not dominate the page. Also adding titles to the videos will aid in understanding what the videos are about.

**Comment by mtho11** [comment]
Additionally, we want to automate the feeds to youtube RSS feeds.

**Comment by jshaughn** [comment]
@mtho11 An RSS feed would be nice but do that only if it's an easy add-on to the primary work.

**Comment by mtho11** [comment]
@jshaughn ok well, the RSS is custom so this one will take a bit more work. I will create a different PR for that.

**Comment by mtho11** [comment]
@jshaughn @lucasponce Just realized that the sprint demos playlist is way out of date: 
https://www.youtube.com/playlist?list=PLgwrCYrAkQYOHIeGukEZUmNRGbqI9uwpi

Nothing has been added to this list since sprint 32. Not sure who is supposed to update this?

**Comment by jshaughn** [comment]
@mtho11 No one is likely responsible for updating youtube itself, I think.  I'd rather we get rid of the playlist than have one that is unmaintained.  And to be honest, I see no value in keeping all of the old videos, I'd rather we limit it to maybe just the last 10 at most.

**Comment by mtho11** [comment]
@jshaughn if we intend on automating the publishing of videos we will need playlists to facilitate that effort. So we don't require playlists now but will need them to organize later.

**Comment by lucasponce** [comment]
> @jshaughn if we intend on automating the publishing of videos we will need playlists to facilitate that effort. So we don't require playlists now but will need them to organize later.

Let's not over-arch in the automation of content, to me having some manual step to update the videos every sprint is not bad:
- It forces that someone review the content and avoid pitfall to add some not desired.
- If the effort is low, we can change the format at any time: I mean, today we have 3 sections, tomorrow we may want to join them, etc. I woudln't put too much effort here because if that creates more rigid structure that we can't change when we want.

Just my 2 cents.

**Comment by mtho11** [comment]
Closed via https://github.com/kiali/kiali.io/pull/298
