### ISSUE TITLE
latest kiali.io docs are still 1.22 when they should be 1.23

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#3172]
https://kiali.io/documentation/latest --> should point to v1.23 now, but it points to v1.22

v1.23 was released about a week ago. But the docs are still at 1.22 for latest. We need staging promoted to v1.23.

**Comment by israel-hdez** [comment]
Fixed in https://github.com/kiali/kiali.io/pull/301 and manually triggering the build.
