### ISSUE TITLE
Please allow traffic to be sortable in the traffic tab

### ISSUE THREAD

**Issue by ceastman-ibm** [kiali/kiali#3176]
**Is your feature request related to a problem? Please describe.**
Trying to find which microservice is consuming the most traffic to a service.

**Describe the solution you'd like**
Allow traffic to be sortable in this view so we can find the service consuming the most traffic

<img width="1565" alt="Screen Shot 2020-09-04 at 10 43 15 AM" src="https://user-images.githubusercontent.com/25593207/92258256-2c136980-ee9c-11ea-92be-beabca8a536b.png">

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. If it is about a new design, please attach a drawing of a potential solution.
For backend changes also describe how one could test the new feature and how it impacts display on the UI.

**Comment by jshaughn** [comment]
This will likely be fixed as part of https://github.com/kiali/kiali/issues/1535.
