### ISSUE TITLE
Trace mini-graph

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#3182]
We could show in Trace details page, a new "Trace mini-graph" component.
This mini-graph would be built from Trace's spans (for a single selected trace), instead of metrics as we usually do.

Not sure if we can reuse / adapt the existing mini-graph component for that (i guess we can) cc @israel-hdez

**Comment by jshaughn** [comment]
@jotak This may be a nice way of testing out the "vendor" architecture server-side for graph generation.  By implementing a new vendor (maybe vendor="jaeger" or vendor="trace") you can have a completely different graph-gen impl.  It generates the same TrafficMap data structure so the cytoscape config gets generated the same way.

**Comment by lucasponce** [comment]
I agree that the left section of the "trace details" summary:
![image](https://user-images.githubusercontent.com/1662329/105820229-91860500-5fb9-11eb-89ec-e2345a26c710.png)

would be better represented in a graph diagram, and probably in that mini-graph can be enhanced with the metrics comparison in a next step, basically to tell the user "this connection is what is suspected to be slow compared with other traces and telemetry data".

**Comment by lucasponce** [comment]
I'm planning in future work and this one comes to my radar.

I was thinking that instead to build a mini-graph from the spans, I guess from Kiali context, it would be better to also apply a similar pattern used in the main graph:

![image](https://user-images.githubusercontent.com/1662329/107493816-588b8a00-6b8e-11eb-95af-70b0d3eaded8.png)

So my proposal would be to use the minigraph for a specific application, workload and service, but augment it with a trace.

In that case we will continue not missing the main story: to give the user the context about how a particular trace is working on the particular context.

I don't see correlate tracing in the overview tab, but as discussed, the "Trace Details" tab looks ideal to replace this summary with this new component.

**Comment by lucasponce** [comment]
This issue should incorporate ideas/discussion introduced on https://github.com/kiali/kiali/issues/3441

**Comment by lucasponce** [comment]
I'm revisiting this one.
As discussed https://github.com/kiali/kiali/issues/3182#issuecomment-776590518, the main graph and the minigraph in the overview tab of the detail pages are consolidating the visualization of the relationships between elements.

So, the main direction would be to improve that features and probably to create a new component to represent only traces are more far from the scope of Kiali.

There are some ideas of improvements in the traces correlation but they will be added with additional issues.
