### ISSUE TITLE
update kiali-ui to use nodejs 12

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#3195]
We should move kiali-ui to NodeJS version 12.

**Comment by mtho11** [comment]
I have been using node.js 12 for some time now in my local dev environment. Without issue.

And travis.yml is already using version 12
```
node_js:
  - '12'
```

So we just need the CI/CD pipeline stuff to be upgraded.

**Comment by mtho11** [comment]
I'm not sure if we would want to change in package.json:

```
"engines": {
    "node": ">=10.0.0 && <13",
    "npm": ">=6.0.0 ",
    "yarn": ">=1.0.0 "
  },
```
I would say probably not; only if there were issues.

**Comment by jshaughn** [comment]
@mtho11 @jmazzitelli As I understand it there is nothing to do for this other than for folks to change their dev envs?  If so can we close?

**Comment by mtho11** [comment]
@jmazzitelli don't you still need to do your special build with v12 once you finish the UBI 8 stuff?
If so I guess this should be assigned to you.

**Comment by mtho11** [comment]
@jmazzitelli or you were going to have Ryan setup an environment?

**Comment by jmazzitelli** [comment]
Yeah, leave this just as a reminder. I'll eventually get our prod build env moved, but i'm having much difficulties as it is, so that will wait until we get a stable build.

**Comment by jmazzitelli** [comment]
We have a stable build now. What should we do here?

**Comment by jshaughn** [comment]
er, close?

**Comment by jshaughn** [comment]
re-open if necessary but I think this done.
