### ISSUE TITLE
Envoy config dump

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#3203]
It would be fairly easy, and I think quite interesting, to allow per-pod config dump of envoy configuration.

From pods list in workload details:
![Capture d’écran de 2020-09-11 11-06-51](https://user-images.githubusercontent.com/2153442/92899483-2202e500-f41f-11ea-9fb6-efca8f76a848.png)

There could be a new column like "config" with a "dump" button per pod. Clicking on it would show up dialog with the dump or provide dump file to download.

From Kiali backend, it's just an http GET on `http://istiod.istio-system:15014/debug/config_dump?proxyID=<podname>.<namespace>`

This is quite helpful for debugging envoy

**Comment by lucasponce** [comment]
I think that this is duplicated to some issue that @xeviknal is investigating, perhaps it's filled with a different description, but I'm sure that it's related to fetch status of the proxies.

**Comment by xeviknal** [comment]
@lucasponce @jotak in the scope of the https://github.com/kiali/kiali/issues/1615 and https://github.com/kiali/kiali/pull/3126 I had the idea of showing the diff between istiod and envoy config in order to make the debugging task easier.

However, I didn't thought about the feature of show the whole config. Good point. Nevertheless, this would share most of the code developed to get the proxy-status and the diff because it is fetch from the same source: `istiod`.

**Comment by jotak** [comment]
Yes perhaps it can be merged into the same task, I don't know, do as you wish.
The "diff" is interesting to troubleshoot out-of-sync issues, but sometimes it's not enough, when playing with envoy filters I've come several times to debug by looking at the whole filters config which I found only in the full dump.

**Comment by xeviknal** [comment]
After some research, the next good step should be to show the envoy config (and config diff) at workload level (taking advantage of the kiali actions in the workload details page).

The feature should provide a high level view where users could either see the full envoy config dump or the diff between the istiod version and the actual envoy config dump per each pod.

As next steps, users might have the ability to:
- see the cluster, listeners, routes or endpoints at pod level.
- inspect the virtual listeners for both inbound and outbound traffic.
- inspect routes for given ports.
- Check the connectivity between the envoy and the istiod pod.

**Comment by abonas** [comment]
In indeed sounds very helpful to get this info.
I'm wondering if generating the dump is a heavy action that might influence the proxy?
If several users, or even the same user click, say, 3 times in a row on "generate dump", will it have impact on the proxy, or it's such a light and fast action (and a tiny dump) that it won't influence anything?

**Comment by xeviknal** [comment]
There isn't any other action to get an small portion of this information atm. Envoy admin has other endpoints but not triggering the same information.

on the other hand, I think that we will give the same impact on the envoy(s) as the istioctl command would do. At the end, we are using the same strategy as the istioctl: fetching the /config_dump and process it.
