### ISSUE TITLE
graph nodes are healthy  with gray color

### ISSUE THREAD

**Issue by aljesusg** [kiali/kiali#3209]
When a node is healthy the node is with gray border color
![Screenshot from 2020-09-15 10-29-44](https://user-images.githubusercontent.com/3019213/93186023-6b647480-f73e-11ea-9408-a76a862a95df.png)

**Comment by aljesusg** [comment]
mm I check that we are not using the HEALTHY color in graph. Any reason @jshaughn ?

https://github.com/kiali/kiali-ui/blob/master/src/components/CytoscapeGraph/CytoscapeGraph.tsx#L805-L816

```ts
if (this.isElementValid(ele)) {
          const health = nsHealth[key];
          if (health) {
            const status = health.getGlobalStatus();
            ele.removeClass(H.DEGRADED.name + ' ' + H.FAILURE.name);
            if (status === H.DEGRADED || status === H.FAILURE) {
              ele.addClass(status.name);
            }
          } else {
            ele.removeClass(`${H.DEGRADED.name}  ${H.FAILURE.name} ${H.HEALTHY.name}`);
            console.debug(`No health found for [${ele.data(CyNode.nodeType)}] [${key}]`);
          }
        }
```

**Comment by aljesusg** [comment]
ok i saw why...maybe we should remove the HEALTHY class here

 ele.removeClass(`${H.DEGRADED.name}  ${H.FAILURE.name} ${H.HEALTHY.name}`);

**Comment by jshaughn** [comment]
@aljesusg The default/healthy color for nodes goes back to the original color design by UX.  It is a complete set of border/fill colors for unselected and selected.  I think the idea for healthy is to sort of de-emphasize them and emphasize the traffic itself.  If they were green the graph may look a bit too bold and edges may get somewhat de-emphasized.  Having said that, if you feel it could be better we could always check with UX to see if an update is appropriate.  I think this is the current color chart: https://github.com/kiali/kiali/issues/2435#issuecomment-404640317
