### ISSUE TITLE
Feature request: Configurable Context Root

### ISSUE THREAD

**Issue by sbueringer** [kiali/kiali#321]
Hi,

I'm deploying Istio together with various addons like Grafana/Jager .. and Kiali . Because I didn't want to host all those addons on different hostnames on context root, I tried to deploy Kiali behind an Ingress controller (in this case Traefik) under /kiali. Obviously, because Kiali is listening on context root, I only get 404s. 

Is there any way to configure the context root on which Kiali is listening on?

**Comment by jotak** [comment]
I fear it is not possible at the moment. I opened a feature request about that: https://issues.jboss.org/browse/KIALI-1059

**Comment by vnugent** [comment]
@sbueringer the feature has been merged. Can you have a look when you get a chance?

**Comment by sbueringer** [comment]
@vnugent I deployed the latest image on our environment with `/kiali` and it works perfectly. Thanks :)
