### ISSUE TITLE
[UI]: kiali-ui script add cross platform

### ISSUE THREAD

**Issue by PmcFizz** [kiali/kiali#3216]
**Is your feature request related to a problem? Please describe.**
when I run `yarn start` on local what ubuntu system , the error happen in page
![image](https://user-images.githubusercontent.com/13403284/93288592-c8c7f680-f80e-11ea-8f64-decc979f1fc7.png)

when I run build 
![image](https://user-images.githubusercontent.com/13403284/93288962-aa162f80-f80f-11ea-9eb2-ca509f627209.png)

**Describe the solution you'd like**
Adding Custom Environment Variables can use [office way](https://create-react-app.dev/docs/adding-custom-environment-variables )

the way use `source ./.env.upstream` don't  cross platform
  

**Describe alternatives you've considered**
useing shell  `if`  `then`  `else`  `source`  in package.json script is a good way. I suggest modify

**Comment by lucasponce** [comment]
Thanks @PmcFizz, would you mind to try to send a PR for this one ?

Not sure if our team has ubuntu to test, so if you'd like to become a committer of Kiali this one sounds an easy one to start with.

**Comment by jshaughn** [comment]
Feel free to re-open for a contribution.
