### ISSUE TITLE
Tooltip span not available

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#3221]
Go to Metrics:
![image](https://user-images.githubusercontent.com/1662329/93448381-d2676200-f8d3-11ea-8908-b2bddb3a2b79.png)

Enable Spans:
![image](https://user-images.githubusercontent.com/1662329/93448424-e1e6ab00-f8d3-11ea-8089-1b8519800097.png)

On the first "enable" tooltips on spans are not available.

Workaround:

- Go to another chart:
![image](https://user-images.githubusercontent.com/1662329/93448492-f6c33e80-f8d3-11ea-9fd2-25ad3485d195.png)

- Back to the original chart:
![image](https://user-images.githubusercontent.com/1662329/93448525-ffb41000-f8d3-11ea-9067-bf2dc60811bb.png)

Then tooltip is enabled and clickable.

**Comment by jotak** [comment]
I'm not sure that this issue happens necessarily right after you enabled spans. I've also seen in from time to time, seems to occur quite randomly. It's like Victory charts are sometimes loosing the mouse focus and events aren't triggered as expected.
Perhaps a lib upgrade could fix that? Need to investigate ...

**Comment by lucasponce** [comment]
I'm reviewing opening bugs.
Yes, this is not breaking the feature but sometimes the mouse tooltip is not shown as well:
![image](https://user-images.githubusercontent.com/1662329/107667407-d5525d00-6c8f-11eb-9daf-e99e3c85925b.png)

**Comment by jshaughn** [comment]
This is something to maybe re-visit/re-test if and when https://github.com/kiali/kiali/issues/4035 is completed.

**Comment by lucasponce** [comment]
I think this issue is improved.
I don't see it as it was originally reported.

There is some behaviour that is expected, on high population of spans, after a refresh, the svg of the chart needs to re-enter the area to trigger again the hover event, but that's expected.

In pause, it works reasonable well.

So, I consider to close this, and create a new one with a clear way to reproduce if it makes sense.
