### ISSUE TITLE
Use tracing semantic conventions for Service Entry detection in traces

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#3226]
Some experimental detection of service entry was introduced in tracing graph overlay (see this PR: https://github.com/kiali/kiali-ui/pull/1914 ). This allows to show Kafka as part of a trace.
I did that without knowing the existing semantic conventions for that purpose: https://github.com/opentracing/specification/blob/master/semantic_conventions.md

So, we should replace the current service-entry detection with something based on these conventions. Example, by order of priority:
- If `peer.hostname` tag is set, try to match with service entry hostnames
- If `peer.address` tag is set, try to match with service entry hostnames
- If `peer.service` tag is set, try to match with service entry name

**Comment by lucasponce** [comment]
+1
I think is aligned with the comment we discussed https://github.com/kiali/kiali/issues/3095#issuecomment-682390528
