### ISSUE TITLE
After kiali1.24.0 upgrade, istio proxy sidecar no istio proxy for the pod, or proxy logs for the time period

### ISSUE THREAD

**Issue by shinynz** [kiali/kiali#3245]
After kiali1.24.0 upgrade, istio proxy sidecar no istio proxy for the pod, or proxy logs for the time period
![TIM截图20200924105614](https://user-images.githubusercontent.com/15795798/94095907-4dd98e00-fe55-11ea-8007-dba06d4ec0a6.png)

**Comment by lucasponce** [comment]
Hi @shinynz can you share more info about your environment ?
Also it seems there are some warnings in the components:
![image](https://user-images.githubusercontent.com/1662329/94111424-51b0e480-fe44-11ea-8e51-b143ac306eae.png)

Can you verify that workload has an injected sidecar ?
Also try to check if the pod 
![image](https://user-images.githubusercontent.com/1662329/94111506-76a55780-fe44-11ea-97f1-db35d18e909e.png)
is still valid, I've noticed a bug in 1.23 that some pods were not properly updated, but I think I fixed that in 1.24.

Just to confirm, if you refresh the Overview tab and go back into the logs, you get the same problem ?

Thanks

**Comment by jshaughn** [comment]
Closing as stale.
