### ISSUE TITLE
Remove ServiceMeshPolicies and ServiceRbacConfig usage

### ISSUE THREAD

**Issue by xeviknal** [kiali/kiali#3257]
Maistra is based in istio 1.6 and there is no need to use SMPolicies and SRbacConfig.

Kiali still looks for those objects in the current version (1.24) so there are some validations that are not accurate and giving false positives.

For example, https://kiali.io/documentation/v1.24/validations/#_kia0208_peerauthentication_enabling_mtls_found_permissive_mode_needed

This task aims to

- remove the usage of those two objects from validations and mtls features
- remove from istio config list

**Comment by jshaughn** [comment]
For what it's worth, our docs specify that for Istio versions < 1.6 we recommend Kiali 1.17 and that later versions of Kiali may not offer the best experience.  So, I think it's totally reasonable to remove the propsed items.

**Comment by lucasponce** [comment]
> For what it's worth, our docs specify that for Istio versions < 1.6 we recommend Kiali 1.17 and that later versions of Kiali may not offer the best experience. So, I think it's totally reasonable to remove the proposed items.

Note that these objects have nothing to do with Istio :-).

So for Istio it's transparent change.
