### ISSUE TITLE
[operator] Create two new golden copies of community and upstream OLM CSV metadata for next release

### ISSUE THREAD

**Issue by xeviknal** [kiali/kiali#3258]
This task is a [reminder](https://github.com/kiali/kiali-operator/pull/144#pullrequestreview-496370579) to 
- create two new golden copies for new versions of community and upstream
- Update the role permissions (this PR remove a couple of permissions: https://github.com/kiali/kiali/pull/3256)

Root: 
The issue https://github.com/kiali/kiali/issues/3257 (implemented in https://github.com/kiali/kiali/pull/3256) needed to update the clusterrole files.

**Comment by jmazzitelli** [comment]
I'm going to create the v1.25 versions... we can then use those to make these changes and any future changes before our next release.
