### ISSUE TITLE
Embed kiali in openshift console using webgui customizations

### ISSUE THREAD

**Issue by e-minguez** [kiali/kiali#326]
AFAIK this can be done by modifying the ocp webgui using this https://docs.openshift.com/container-platform/3.9/install_config/web_console_customization.html#web-console-project-left-navigation

**Comment by abonas** [comment]
@e-minguez thanks for this FR.
We have a research task planned around this :)
https://issues.jboss.org/browse/KIALI-1020
@pilhuhn @theute @mwringe @kiali/ux-reviewers fyi

**Comment by lucasponce** [comment]
JIRA:
https://issues.jboss.org/browse/KIALI-1020
