### ISSUE TITLE
Fail to login with OpenID Connect as "failure when retrieving user identity"

### ISSUE THREAD

**Issue by Ayden-Franklin** [kiali/kiali#3262]
**Describe the bug**
Thanks for supporting "Authentication code" flow. I tried the version 1.24.0 but got a result 
```
{
  "error":"failure when retrieving user identity",
  "detail":"request failed (HTTP response status = 401 Unauthorized)"
}
```
![image](https://user-images.githubusercontent.com/10723556/94363349-44218600-00f4-11eb-85e0-66c43e5bb490.png)
 Here is my configuation
```
    auth:
      openid:
        authentication_timeout: 300
        authorization_endpoint: ""
        client_id: "kubernetes-xxxx"
        insecure_skip_verify_tls: false
        issuer_uri: "https://oidc.xxxxxxx.com/auth/realms/aaaaa"
        scopes:
        - openid
        - profile
        - email
        username_claim: email
      openshift:
        client_id_prefix: kiali
      #strategy: anonymous
      strategy: openid

```

**Versions used**
Kiali: 1.24.0 
Istio: 1.7.2
Kubernetes flavour and version:  v1.18.4

**To Reproduce**
1. Configure the `auth` section for openId
2. Click on 'Log In With OpenID '
3. Authenticate with my username and password. 

**Expected behavior**
Show the authenticated main page.

**Comment by neolunar7** [comment]
I'm using OIDC and having google as IdP, but am facing the error of `{"error":"failure when retrieving user identity","detail":"request failed (HTTP response status = 400 Bad Request)"}`
```
spec:
  auth:
    strategy: openid
    openid:
      client_id: <My ID>
      issuer_uri: https://accounts.google.com
      scopes:
      - "openid"
      - "email"
      - "profile"
      username_claim: "sub"
```

**Comment by israel-hdez** [comment]
The `Unauthorized` response may indicate that you didn't create the openid client secret. Please, check that you created the secret. If you installed using the operator, command should be something like:

`kubectl get secret kiali -n $KIALI_INSTALL_NAMESPACE`

If you get nothing, you need to create the secret as explained in OpenID set-up instructions in https://kiali.io/documentation/latest/configuration/authentication/openid/#_set_up.

If you have a secret in place, can you check that it's correctly mounted in Kiali? Command should be similar to:

`kubectl exec $KIALI_POD_NAME -n $KIALI_INSTALL_NAMESPACE -- cat /kiali-secret/oidc-secret`

The output should be the openid secret in plain text.

**Comment by israel-hdez** [comment]
@Macrame Any feedback after my reply?

**Comment by israel-hdez** [comment]
@neolunar7 Perhaps, could you provide the logs of the Kiali pod? (Please, enable debug level messages.)

**Comment by Tanbouz** [comment]
I was missing the secret as you suggested.

Then ran into another issue while using `kube-oidc-proxy`, don't think it is related to the original issue.

`{"error":"Token is not valid or is expired","detail":"the server has asked for the client to provide credentials (get namespaces)"}`

**Comment by israel-hdez** [comment]
@Tanbouz That sounds like `kube-oidc-proxy` can't communicate with the Kubernetes API.
Can you check the logs of `kube-oidc-proxy`? You may be missing some RoleBindings or ClusterRoleBindings. Or, perhaps, some certificates issue, or simply `kube-oidc-proxy` is unable to connect to Kubernetes.

**Comment by Macrame** [comment]
Sorry for my late, in fact I had a long holiday. Anyway, I created the secret and checked the content. As you said, it equals the openid client-secret exactly. The issue is still stuck. Could you help me to resolve it? Thanks very much.

**Comment by israel-hdez** [comment]
@Macrame Is the error message still the same? I see you posted this error 

```
{
  "error":"failure when retrieving user identity",
  "detail":"request failed (HTTP response status = 401 Unauthorized)"
}
```

If it is, can you please [enable debug level messages in Kiali](https://github.com/kiali/kiali-operator/blob/7dafc469c95d4307ebd03c515a87c7f84eb64da7/deploy/kiali/kiali_cr.yaml#L355-L358) and provide the logs of the Kiali pod?

**Comment by Macrame** [comment]
I can sign in successfully after I re-created the pod. Now the error message is `{"error":"Cannot view any namespaces. Please read Kiali's RBAC documentation for more details."}` although I bound my user to the clusterrole `kiali` using `kubectl create clusterrolebinding ayden-admin-binding --clusterrole=kiali --user="ayden.franklin@xxxxxx.com"`.
By the way,  Kiali pod can print INFO log regardless of that I changed the `verbose_mode` to 4 in the ConfigMap.
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: kiali
  namespace: istio-system
  labels:
    helm.sh/chart: kiali-server-1.24.0
...
    deployment:
      verbose_mode: "4"
```

**Comment by israel-hdez** [comment]
> I can sign in successfully after I re-created the pod. Now the error message is `{"error":"Cannot view any namespaces. Please read Kiali's RBAC documentation for more details."}`

Just as sanity check, please make sure that the `kiali` clusterrole exists.

If it does exist, I would think that your kubernetes cluster is looking for another username. Check the API Server startup flags, specifically, the `--oidc-username-claim` flag. By default, it's `sub`, so you may need to use the userID rather than the e-mail to give privileges, or whatever token claim was configured.

> By the way, Kiali pod can print INFO log regardless of that I changed the `verbose_mode` to 4 in the ConfigMap.

Yes, I was looking for DEBUG lines. The detailed response from the IdP is only logged when debug mode is on.

**Comment by Macrame** [comment]
I tried again after I specified the `--oidc-username-claim` flag to `--oidc-username-claim=preferred_username` for API Server and `username_claim:preferred_username for Kiali. Certainly, I bound the `clusterrolebinding` to my **preferred_username**:
```
kubectl create rolebinding ayden-openid-binding --clusterrole=kiali --user="ayden.franklin" --namespace=<MY NAMESPACE>
```
And, the `kiali` clusterrole exists absolutely.
```
# kubectl describe clusterrole kiali
Name:                                            kiali
Labels:                                          app=kiali
                                                 app.kubernetes.io/instance=kiali-server
                                                 app.kubernetes.io/managed-by=Helm
                                                 app.kubernetes.io/name=kiali
                                                 app.kubernetes.io/version=v1.24.0
                                                 helm.sh/chart=kiali-server-1.24.0
                                                 version=v1.24.0
Annotations:                                     PolicyRule:
  Resources                                      Non-Resource URLs  Resource Names  Verbs
  ---------                                      -----------------  --------------  -----
  *.authentication.istio.io                      []                 []              [create delete get list patch watch]
  servicemeshpolicies.authentication.maistra.io  []                 []              [create delete get list patch watch]
  *.config.istio.io                              []                 []              [create delete get list patch watch]
  experiments.iter8.tools                        []                 []              [create delete get list patch watch]
  *.networking.istio.io                          []                 []              [create delete get list patch watch]
  *.rbac.istio.io                                []                 []              [create delete get list patch watch]
  servicemeshrbacconfigs.rbac.maistra.io         []                 []              [create delete get list patch watch]
  *.security.istio.io                            []                 []              [create delete get list patch watch]
  configmaps                                     []                 []              [get list patch watch]
  endpoints                                      []                 []              [get list patch watch]
  namespaces                                     []                 []              [get list patch watch]
  nodes                                          []                 []              [get list patch watch]
  pods/log                                       []                 []              [get list patch watch]
  pods                                           []                 []              [get list patch watch]
  replicationcontrollers                         []                 []              [get list patch watch]
  services                                       []                 []              [get list patch watch]
  deploymentconfigs.apps.openshift.io            []                 []              [get list patch watch]
  deployments.apps                               []                 []              [get list patch watch]
  replicasets.apps                               []                 []              [get list patch watch]
  statefulsets.apps                              []                 []              [get list patch watch]
  cronjobs.batch                                 []                 []              [get list patch watch]
  jobs.batch                                     []                 []              [get list patch watch]
  deployments.extensions                         []                 []              [get list patch watch]
  replicasets.extensions                         []                 []              [get list patch watch]
  statefulsets.extensions                        []                 []              [get list patch watch]
  horizontalpodautoscalers.autoscaling           []                 []              [get list watch]
  monitoringdashboards.monitoring.kiali.io       []                 []              [get list]
  projects.project.openshift.io                  []                 []              [get]
  routes.route.openshift.io                      []                 []              [get]
```
--- 
Kiali pod can only print INFO log regardless of that I changed the verbose_mode to 4 in the ConfigMap. I can not see any DEBUG log.

**Comment by israel-hdez** [comment]
@Macrame There was an error in the docs. Docs were telling users to register Kiali as a new App in the OpenId Server. This was an error, and you should share the same app both for Kubernetes and Kiali. So, please make sure that the same OpenId app is shared.

**Comment by Macrame** [comment]
Yes, I knew that. My `client_id` for Kiali equals the one for Kubernetes.  I want to see the DEBUG log to check the detail information actualy but it can only print INFO log no mater what the `verbose_mode`  is, though I had restarted the pod several times after change the ConfigMap.
Thanks for your help:)

**Comment by Macrame** [comment]
I reinstalled my Kubernetes cluster and Istio for the latest version, kiali version is 1.25.0. Now the error is same. Kiali prints some logs:
```
Kiali Cache is active for namespaces [.*]
```
@israel-hdez Could you help me to check is there any wrong?

**Comment by israel-hdez** [comment]
> I reinstalled my Kubernetes cluster and Istio for the latest version, kiali version is 1.25.0. Now the error is same. Kiali prints some logs:
> 
> ```
> Kiali Cache is active for namespaces [.*]
> ```
> 

This log message is normal.

> @israel-hdez Could you help me to check is there any wrong?

What's the message now that you re-created the cluster?
Is it `Cannot view any namespaces.`? or is it `failure when retrieving user identity`? or something else?

**Comment by Macrame** [comment]
The error message is {"error":"Cannot view any namespaces. Please read Kiali's RBAC documentation for more details."}

**Comment by israel-hdez** [comment]
@Macrame do you have the ability to get a token from your OpenId Server and inspect its claims?
I think we are somewhat blind and trying to guess what's the username string.

The command you previously tried to assign privileges should had worked:

`kubectl create rolebinding ayden-openid-binding --clusterrole=kiali --user="ayden.franklin" --namespace=<MY NAMESPACE>`

If it does not work, I can only recommend you to try creating a `clusterrolebinding` rather than a `rolebinding`. Otherwise, we really need to get a token from your OpenId Server to see what's the username string.

**Comment by Macrame** [comment]
Yes, I had tried to create a `clusterrolebinding` but it still didn't work. I really has confirmed the username. 

```
Here is your accees token :
eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJvd0NQS1Y5aDRnTXNIQW83Y05qTWYzdnhEM2NBeXNPM1ZsQ09rdTRVdXJzIn0.eyJleHAiOjE2MDM0MjY1MDcsImlhdCI6MTYwMzQyNjIwNywiYXV0aF90aW1lIjoxNjAzNDI1MjAyLCJqdGkiOiJiMGRjZDg2Yy03ZDkxLTQ5YzItODVhZS0yNTE3YjAwYTMzM2UiLCJpc3MiOiJodHRwczovL29pZGMuaW1hZ2Vnby5jb20vYXV0aC9yZWFsbXMvZ2FsYXh5IiwiYXVkIjoiYWNjb3VudCIsInN1YiI6ImNhNDQ2NmU0LTEwNTUtNGIyMS1hN2RlLWU2Y2Y5YjY2ZGI1NCIsInR5cCI6IkJlYXJlciIsImF6cCI6ImdhbGF4eS1vYXV0aDItYXBwIiwibm9uY2UiOiJJNDRhR0hJLXlJU3ZpVlZKdmt4dkxqaFhzX1RUdkdaUlUwYlRZd2hJVnNzIiwic2Vzc2lvbl9zdGF0ZSI6IjE0NzQwZWJhLTBmMWEtNGM0My04YjA5LWMxMDRmNmI3ZmVkNyIsImFjciI6IjAiLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJBeWRlbiBGcmFua2xpbiIsInByZWZlcnJlZF91c2VybmFtZSI6ImF5ZGVuLmZyYW5rbGluIiwiZ2l2ZW5fbmFtZSI6IkF5ZGVuIiwiZmFtaWx5X25hbWUiOiJGcmFua2xpbiIsImVtYWlsIjoiYXlkZW4uemhhbmdAaW1hZ2Vnby5jb20ifQ.K61bwex3LvNdqglikxxFkwvSXbw3y1EPds_B9aJsxCghLdj3a2yheiKL2FhOWD4WOg8D8vUiwnzEDNdJlfBo4SNdRn7zcAITWDyLQ-qkZo38WiHS3JviC4Ft_Si8cS26ggGBtDtsMwR_BQ50pP6L6H-dwpUiTufPZ4SQ4em3lwpJmV6YOzavUw8jwOY5JhEOl2EDnVoW1BPttEsscilIQ2CpYoMeOdeM_Ip-f-6okKwlNbcpynlOdznONkk_Op9ZlpX2zC6rnb73ZzDebxoGFODzVlXTKs6NXzNzimbGs51xnOwFGqzh3g3UL22usTakMB6W0_ir8BZWSmPzspJ1yA
Here is your accees token attributes :
{at_hash=ZAw3zycjY2SSczIc7g9U6g, sub=ca4466e4-1055-4b21-a7de-e6cf9b66db54, email_verified=false, iss=https://oidc.imagego.com/auth/realms/galaxy, typ=ID, preferred_username=ayden.franklin, given_name=Ayden, nonce=I44aGHI-yIXXXXXXXXXXXXXXXXhIVss, aud=[galaxy-oauth2-app], acr=0, azp=galaxy-oauth2-app, auth_time=2020-10-23T03:53:22Z, name=Ayden Franklin, exp=2020-10-23T04:15:07Z, session_state=14740eba-0f1a-4c43-8b09-c104f6b7fed7, family_name=Franklin, iat=2020-10-23T04:10:07Z, email=ayden.franklin@xxxxxx.com, jti=f2a70f5c-4a58-421a-ab5c-601c7f310e06}
```

** preferred_username=ayden.franklin**, and the Kubernetes API server args: `--oidc-client-id=kubernetes-******* --oidc-username-claim=preferred_username`, and the kiali configuration:
```
    auth:
      openid:
        authentication_timeout: 300
        authorization_endpoint: "https:/xxxxxxxx/protocol/openid-connect/auth"
        client_id: "kubernetes-*******"
        insecure_skip_verify_tls: false
        issuer_uri: "https://xxxxxxx"
        scopes:
        - openid
        - profile
        - email
        username_claim: preferred_username
```

**Comment by israel-hdez** [comment]
@Macrame Can you run the following command and post the result?

`kubectl cluster-info dump | grep authorization-mode`

**Comment by Macrame** [comment]
The result of `kubectl cluster-info dump | grep authorization-mode` is nothing though kube-apiserver is running with Options `--authorization-mode=Node,RBAC`.

There is the output of `kubectl api-versions`:
```
...
rbac.authorization.k8s.io/v1
rbac.authorization.k8s.io/v1beta1
...
```

**Comment by israel-hdez** [comment]
Hi, @Macrame 

To be honest, I'm not sure what could be the problem.
From your messages, I see everything is good. So, I'm unsure why the rolebinding is not working.

If you *do not* need RBAC, I can only suggest to update to Kiali v1.26 and disable RBAC -- this is something new in version 1.26 (see https://kiali.io/documentation/latest/configuration/authentication/openid/#_set_up_with_no_rbac_support).

If you need RBAC, well, I'm not sure if I'll be able to provide more help. The only thing that comes into my head is to check the api server logs and see if there is something that may give some idea about what is the issue. But from your messages I really cannot spot any misconfiguration.

**Comment by Ayden-Franklin** [comment]
Thank you. I need RBAC in fact. So I can't use OIDC in this version. Maybe it can work well in the future:)

**Comment by cfcosta** [comment]
So, I've did some testing here, both with DeX and Google OIDC and could not replicate the problems here. I did get a `{"error":"Cannot view any namespaces. Please read Kiali's RBAC documentation for more details."}`, which I resolved just creating a role binding.

I'll keep this open in case you or someone else finds a small, reproducible test case that we can check again.

**Comment by jshaughn** [comment]
Closing as stale, please re-open as needed.
