### ISSUE TITLE
Performance Tuning Guide

### ISSUE THREAD

**Issue by feuyeux** [kiali/kiali#3263]
**Is your feature request related to a problem? Please describe.**
In metrices retrieving, when the rt is very slow, there's no graceful way to find out the root cause and how to do the Performance Turning.

**Describe the solution you'd like**
It's better to provide a performance tuning guide at this moment, which could tell us that kiali server should config something, or figure out it's prometheus side or istiod side issue.

**Describe alternatives you've considered**
Automatically detect the root cause and alert the message and the solution  for that.

**Additional context**

**Comment by lucasponce** [comment]
Hi @feuyeux, I agree that currently a better section about performance tuning in Kiali would help.

Perhaps I can draft some quick checks that I would do if I start a performance investigation:

- Kiali has not a storage, it relies in APIs from different systems: Kubernetes API, Prometheus Server, Jaeger Tracing. A first check would be to see if the overall cluster is overloaded.
- Check if the Kubernetes API is healthy, try to fetch access to controllers (deployments, replicasets) and workloads (pods) and see if the API responds quickly.
- I'd check if the Prometheus server is healthy, also in the same way, you can try to query directly raw metrics from the promnetheus UI and check if the response time looks good.
- Similar for Jaeger service.
- Also I would check if there is something suspicious in the istio-system namespace, i.e., check if there is an unusual number of restarts in the pods, that may lead to some runout situation of resources.
- In Kiali, would be interesting to check which element is slower (i.e. graph generation, or details page).

Also, if you can add some details about which version of Istio and Kiali you are using we could get more hints.

Having said that, Kiali config allow some "tweaks" about performance, like "burst" in K8S connection or cache duration, etc, but I wouldn't blindly chage that without better reasons.

In our internal performance tests we saw that a bad performance in Kiali is directly linked with an overloaded cluster in general, but I'd like to get more data to understand your scenario.

**Comment by feuyeux** [comment]
Your plan is very exciting for me! And I wish that going well. Furthermore, I hope the config.yaml would provide more wonderful setting for performance tuning. 

More infomation for my scenario. 
1. Prometheus works well, including retrive from UI.
2. Kiali version is the latest(1.24).
3. But the istio I used is special, it's a managed version from alibabacloud. That means the istiod is not located with kiali in the same kubernetes. And I want to find if tyring to connect istiod is the root cause, but I have no idea to do that.

**Comment by lucasponce** [comment]
I'm revisiting this one.
Kiali is working in severañ directions here:

- From one side, it's improving the internal metrics (available under Kiali workload) identifying latency of specific features to help to collect information in slow scenarios https://github.com/kiali/kiali/issues/3244.
- As an on-going process, recommendations are being added as part of the https://kiali.io/documentation/latest/faq/.
- Also, as a low level info, the Kiali operator is being documented indicating the configuration settings that may affect into performance (cache, client, etc) https://github.com/kiali/kiali-operator/blob/master/deploy/kiali/kiali_cr.yaml#L789

So, all of these lines of work are in WIP and they are being updated, also note that there are open some discussions around scalability and performance that may be related as well https://github.com/kiali/kiali/discussions/4080.
