### ISSUE TITLE
Implement some "Enable" config flag for custom dashboards

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#3269]
Implement "Enable" config flag so that people who don't want custom dashboards discovery can turn it off.

**Comment by jmazzitelli** [comment]
We can do interesting adjustments in the operator and helm charts with the addition to a external_services.custom_dashboards.enabled flag. If false, the operator and helm charts don't have to install the CRD nor any of the custom dashboards themselves. If using the operator, all a user has to do it flip the flag to "True" and the operator will install everything at that time (in case the user decides later to introduce custom dashboards).
