### ISSUE TITLE
Find/Hide broken style on validation errors

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#3275]
![image](https://user-images.githubusercontent.com/1662329/94682690-9990a980-0325-11eb-9d90-713e848675f9.png)

**Comment by jshaughn** [comment]
@lucasponce This is as expected given that the error message(s) exist inside the toolbar.

**Comment by lucasponce** [comment]
It breaks the style, the error message is expected but it shouldn't change the layout of the Display component.

**Comment by jshaughn** [comment]
The PF pattern of red error messages placed below the input is met.  I think in general the PF design is assuming more of a stacked form such that adding the message just pushes down the rest of the form and no one notices.  But in the toolbar this is more what you get, the height of the input div simply gets higher while all toolbar items remain centered.

I agree it looks a bit unusual but I don't think it breaks the design pattern and a change is not straightforward (at least not for me) and I simply don't think it's worth the time.  The error message goes away as soon as you correct your input.

**Comment by lucasponce** [comment]
Mmm what about this 
![image](https://user-images.githubusercontent.com/1662329/96164655-d19a0e00-0f1b-11eb-8958-8e6c264f3514.png)

Just nested the GraphFindContainer I haven't seen any side effects but you'd admit it's a better presentation.
