### ISSUE TITLE
Consider showing traces comparisons with charts

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#3279]
In the work ongoing here [1] traces are being compared with simple colored text:

![image](https://user-images.githubusercontent.com/1662329/94676041-fa66b480-031a-11eb-8410-b773ea1e9e0d.png)

It's suggested [2] (@lucasponce ) that we could use some charts instead:
![image](https://user-images.githubusercontent.com/1662329/94675955-dc00b900-031a-11eb-876c-f096a598e437.png)

So, we can discuss about it.
I think the current form with colored text is already quite visual and concise, but charts would make it *even more visual*. The downsides I can see with charts is that it impacts the reactivity of the browser, and perhaps will take more space on screen.

So, I don't know at that point, I'm setting the "discussion needed" label here.

[1] https://github.com/kiali/kiali-ui/pull/1945
[2] https://github.com/kiali/kiali-ui/pull/1945#issuecomment-701313333

**Comment by lucasponce** [comment]
The screenshot is from other feature that uses multiple charts per rows.
In my suggestion I think we could use a single chart in the traces tab with the main subject and the comparison.

Note that similar patter is being used in other places as well, like routes comparison in the Istio Config:
![image](https://user-images.githubusercontent.com/1662329/94790330-69edaa00-03d6-11eb-851a-c775fdb74c43.png)

**Comment by lucasponce** [comment]
@jotak as probably this pattern is new perhaps here is a good candidate to involve @lwrigh next week in the UX meetings.

**Comment by lwrigh** [comment]
Some comments for the screenshots above, I would add some space in between the 'Full duration' and 'Spans average duration' sections just to separate them a bit more. I would also use a smaller scale for the bar graphs since it's kind of hard to guess what the value is with such a large gap in between the numbers that are marked on it.

**Comment by jotak** [comment]
Considering the work that has been done with the metrics-based comparison on spans and the heatmap, perhaps we can revisit this task.

In another discussion, @lucasponce suggested to have a comparison heatmap per trace, directly in the chart tooltip.
I guess it ties up with the comparison chart that we want here.

So my proposal is:
- To create a heatmap per trace that would replace or complement [1] the textual comparisons
- To show it in chart tooltip in addition to trace details

[1] There's a difference / drawback however : metrics-based comparisons won't allow to compare to *similar* traces. So perhaps we should still keep them, or build a second chart/heatmap out of them.

**Comment by jotak** [comment]
(starting to investigate on this...)

**Comment by lucasponce** [comment]
> So my proposal is:
> 
> * To create a heatmap per trace that would replace or complement [1] the textual comparisons
> * To show it in chart tooltip in addition to trace details

+1 to both

**Comment by jotak** [comment]
I'm in the middle of the process, I'd appreciate to get some feedback before going further.

So far I have the metrics-based comparison matrix similar to the one in the spans table.
And I've added a 2x2 matrix that replaces the current textual information that we have, comparing the selected trace with all traces displayed on screen, including a subset of similar traces (here's two examples) :

![Capture d’écran de 2020-11-25 16-10-14](https://user-images.githubusercontent.com/2153442/100246171-211b2300-2f39-11eb-8f34-ae73c74997f6.png)

![Capture d’écran de 2020-11-25 16-18-39](https://user-images.githubusercontent.com/2153442/100246952-11e8a500-2f3a-11eb-967f-5cfecf061f8c.png)

(There's some CSS glitches that need to be fixed, please ignore them at the moment)

So, what do you think about these heatmaps, especially the small one? Is it better than the textual info?
I think it is still relevant to show, as heatmap or as text, since it can be more relevant comparisons, with the similarity algorithm that takes into account stuff like the span's operation, etc.

Note also that we can improve the layout, perhaps put the two matrices side by side, or stuff like that.

ping @aljesusg @lucasponce @xeviknal

**Comment by lucasponce** [comment]
> So, what do you think about these heatmaps, especially the small one? Is it better than the textual info?
> I think it is still relevant to show, as heatmap or as text, since it can be more relevant comparisons, with the similarity algorithm > that takes into account stuff like the span's operation, etc.

> Note also that we can improve the layout, perhaps put the two matrices side by side, or stuff like that.

+1 

To me it looks good, as a user the steps to get here are:
- I review the timeline chart and one trace is bringing my attention for some reason (latency or a different pattern comapred with others).
- When selected, first tab is this "trace details" summary which shows a first comparson with other traces and also with metrics.

There are a couple of CSS issues in the screenshots (text alignment as far I can see), but those can be commented in a PR.

**Comment by aljesusg** [comment]
> I'm in the middle of the process, I'd appreciate to get some feedback before going further.
> 
> So far I have the metrics-based comparison matrix similar to the one in the spans table.
> And I've added a 2x2 matrix that replaces the current textual information that we have, comparing the selected trace with all traces displayed on screen, including a subset of similar traces (here's two examples) :
> 
> ![Capture d’écran de 2020-11-25 16-10-14](https://user-images.githubusercontent.com/2153442/100246171-211b2300-2f39-11eb-8f34-ae73c74997f6.png)
> 
> ![Capture d’écran de 2020-11-25 16-18-39](https://user-images.githubusercontent.com/2153442/100246952-11e8a500-2f3a-11eb-967f-5cfecf061f8c.png)
> 
> (There's some CSS glitches that need to be fixed, please ignore them at the moment)
> 
> So, what do you think about these heatmaps, especially the small one? Is it better than the textual info?
> I think it is still relevant to show, as heatmap or as text, since it can be more relevant comparisons, with the similarity algorithm that takes into account stuff like the span's operation, etc.
> 
> Note also that we can improve the layout, perhaps put the two matrices side by side, or stuff like that.
> 
> ping @aljesusg @lucasponce @xeviknal

looks great form me @jotak theheatmaps. 

I don't know if we can improve the information about the simialr traces, I don't like to see N "Display" maybe set a link in the identifier with a tooltip. What do you think ?

**Comment by jotak** [comment]
@aljesusg thanks! Lucas had actually the same remark and it's implemented already
