### ISSUE TITLE
Align VirtualService Hosts with Gateway when Add Gateway is used in Kiali Wizard

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#3280]
By default, Kiali Wizard populates VirtualServices Hosts with the internal service name.
When adding a new Gateway by default a wildcard is used and it would be interesting to align both VS hosts and Gateway hosts.

Also, this issue comes from Maistra.io when ior_enabled is activated:
https://maistra.io/docs/comparison-with-istio/ior/

**Comment by maltron** [comment]
Environment: OpenShift 4.5/OpenShift Service Mesh 1.1.9. 
SMCP: https://pastebin.pl/view/88fba88d  SMMR: https://pastebin.pl/view/8741afd3

After creating 3 miicroservices and deploying with a sidecar, I wanted to use Kialii to automatcally created a Gateway, VirtualServices and DestinationRule. So, I went to the Service section and try to use a Wizard to make it happen: Kiali -> Services -> Actions -> Create Matching

The generated resources by Kiali were:
Gateway: https://pastebin.pl/view/e2be6dba
ViirtualService: https://pastebin.pl/view/276d361a
DestinationRule: https://pastebin.pl/view/784f9755

Giving the SMCP has a property "ior_enabled" as described here: https://maistra.io/docs/installation/controlplane/
This will automatically create a OpenShift's Route for me on istio-system namespace: https://pastebin.pl/view/2f4c9064

So far so good....however, when I curl my microservice: 
```
curl -v http://one-microservice-a-gateway-wph2d-istio-system.apps.cluster-b078.b078.example.opentlc.com
*   Trying 18.159.24.10...
* TCP_NODELAY set
* Connected to one-microservice-a-gateway-wph2d-istio-system.apps.cluster-b078.b078.example.opentlc.com (18.159.24.10) port 80 (#0)
> GET / HTTP/1.1
> Host: one-microservice-a-gateway-wph2d-istio-system.apps.cluster-b078.b078.example.opentlc.com
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< date: Thu, 01 Oct 2020 19:53:07 GMT
< server: istio-envoy
< content-length: 0
< set-cookie: b2cf1f8cbd4f91ed393490678c059be7=8b4e990161f8ed2f4854d73ff2bc9199; path=/; HttpOnly
< cache-control: private
< 
* Connection #0 to host one-microservice-a-gateway-wph2d-istio-system.apps.cluster-b078.b078.example.opentlc.com left intact
* Closing connection 0
```

If I do change manually the hosts section on both of my Gateway AND VirtualService: 
```
 - hosts:
    - test.apps.cluster-b078.b078.example.opentlc.com
```

I am able to get the desired effect:
```
*   Trying 18.159.24.10...
* TCP_NODELAY set
* Connected to test.apps.cluster-b078.b078.example.opentlc.com (18.159.24.10) port 80 (#0)
> GET / HTTP/1.1
> Host: test.apps.cluster-b078.b078.example.opentlc.com
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< date: Thu, 01 Oct 2020 19:55:36 GMT
< content-length: 19
< content-type: text/plain; charset=utf-8
< x-envoy-upstream-service-time: 11
< server: istio-envoy
< set-cookie: c84d399a2e87de25ffdd2c081ccc65bd=8b4e990161f8ed2f4854d73ff2bc9199; path=/; HttpOnly
< cache-control: private
< 
* Connection #0 to host test.apps.cluster-b078.b078.example.opentlc.com left intact
A(blue) --> B --> C* Closing connection 0
```

So I wonder if Kiali is generating the wrong configuration resources or something is actively needed from the user to make all work out-of-the-box.

**Comment by lucasponce** [comment]
> So I wonder if Kiali is generating the wrong configuration resources or something is actively needed from the user to make all work out-of-the-box.

It's due a limitation of Maistra with wildcards for IOR feature:

https://maistra.io/docs/comparison-with-istio/ior/

```
Catch-all domains ("*") are not supported. If one is found in the Gateway definition, Maistra will create the route, but will rely on OpenShift to create a default hostname. This means that the newly created route will not be a catch all ("*") route, instead it will have a hostname in the form <route-name>[-<project>].<suffix>. Refer to the OpenShift documentation for more information about how default hostnames work and how a cluster administrator can customize it.
```

**Comment by lucasponce** [comment]
Also, what from Kiali we can do, it's to sync the Gateway host used with the VS host used.
Then in this scenario, when Gateway is detected, Maistra would create the Route with the host populated and synced.

Wizard could add extra details to the user on this case as well.

**Comment by lucasponce** [comment]
Ok, confirmed that the "bug" here is basically that when Wizard adds a Gateway, it would be good to sync the VS host, and by default both can be the wildcard all host.
