### ISSUE TITLE
operator should not install dashboard resources if the enabled flag is false

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#3285]
We can do interesting adjustments in the operator and helm charts with the addition of the new [external_services.custom_dashboards.enabled flag](https://github.com/kiali/kiali/issues/3269). If false, the operator and helm charts don't have to install the CRD nor any of the custom dashboards themselves. If using the operator, all a user has to do it flip the flag to "True" and the operator will install everything at that time (in case the user decides later to introduce custom dashboards).

**Comment by jmazzitelli** [comment]
Note: we have to be careful with the CRD. I think we still want the operator to install it always because in a multi-tenant situation, one kiali may not care, but another kiali installation might want to show custom dashboards. If we delete the CRD, EVERY dashboard resource across the cluster will be deleted.

**Comment by jotak** [comment]
@jmazzitelli or perhaps, do not install it if *this* Kiali doesn't need it, but never remove it ?

**Comment by jmazzitelli** [comment]
> @jmazzitelli or perhaps, do not install it if _this_ Kiali doesn't need it, but never remove it ?

Yes, that's a good way to do it.

**Comment by jmazzitelli** [comment]
Two PRs:

* https://github.com/kiali/kiali-operator/pull/154
* https://github.com/kiali/helm-charts/pull/8
