### ISSUE TITLE
[operator] molecule test 'openid-test' should test auth flow

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#3287]
Right now the openid-test molecule test only tests the implicit flow. We should add a test for the auth flow.

See: https://github.com/kiali/kiali-operator/tree/master/molecule/openid-test

The initial test starts off with a signing key that will enable implicit flow: https://github.com/kiali/kiali-operator/blob/v1.24.0/molecule/openid-test/kiali-cr.yaml#L25-L27 

We will want to add a second set of tasks to https://github.com/kiali/kiali-operator/blob/v1.24.0/molecule/openid-test/converge.yml to change the signing key, add a secret, and then test auth flow.

**Comment by jshaughn** [comment]
@cfcosta If you can solve https://github.com/kiali/kiali/issues/3541, you could take a crack at adding this test.

**Comment by lucasponce** [comment]
@jmazzitelli is this issues still valid ?

**Comment by jmazzitelli** [comment]
still valid - one day someone will do this. Might be a good one for a community person to contribute.

**Comment by jshaughn** [comment]
Useful but closing as part of routine backlog maintenance.  Can be re-opened as needed by a contributor.
