### ISSUE TITLE
Use metrics-based comparison / trends for span's duration info

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#3293]
Follow-up on #3095

In Trace Page, Span table, next to duration cell: add some comparison value with metrics avg/percentiles over last X min/hour. (E.g. one comparison versus last 30 min, and another versus last 3 hours)
This would apply only to envoy spans. Metric must be selected for same source and same destination as the span.

An informative tooltip needs to be added about that, because it's important that the user understands the bias in this comparison, given the span granularity is higher that the metric's.

**Comment by lucasponce** [comment]
This is good, but we are missing the tracking of this effort.
Please, @jotak would you mind to update the main epic https://github.com/orgs/kiali/projects/19 with this one as a subtask ?

**Comment by jotak** [comment]
FYI I'm doing a first iteration reusing our existing API for metrics.
But given the number of queries perhaps we'll have to introduce some new "batch" endpoint for metrics.

**Comment by jotak** [comment]
So, I'm hesitating with the approach to have, between something more generic or something more opinionated.
The existing API in any case isn't sufficient to deal with the needs here because it's designed to query datapoints in a range, and we want here a single value from a rate interval (like what is done in health & graph edges). Moreover as said above we will probably want to avoid to many front->back queries.

In the details, we want to query stats for:
- several apps and/or workloads (since each span may relate to a different app/workload)
- grouped and not grouped by peer
- with several time intervals (e.g. stats for last 30m and stats for last 3 hours)
- several histogram functions: e.g. avg, p90... (on this point, the current API was fine)

All these points multiply, so that's many queries.
At the moment my preference is for something quite opinionated, with a single grouped "stats" query, through perhaps a new endpoint like `/stats/metrics`, and query params for `apps` / `workloads`, `intervals`, `percentiles` . Perhaps even some POST for that, as the parameters could grow more complex (e.g. what if the apps are across several namespaces? more structured params needed?).

Perhaps that would clear the path for future features like `stats/traces` and so on, that would share the same idea.

@aljesusg , @xeviknal , @lucasponce , does it sound good to you?

**Comment by jotak** [comment]
Note: the new endpoint to be created might eventually be reused by https://github.com/kiali/kiali/issues/2708

**Comment by jotak** [comment]
So, to track some progress here: I have a working draft with back & front:

![Capture d’écran de 2020-10-27 13-53-58](https://user-images.githubusercontent.com/2153442/97304644-4f371580-185c-11eb-87e3-d76ed4744904.png)

In terms of data I think this is good, but we can improve in terms of visualization.
I'm thinking of:
- using a comparison chart as it was suggested in https://github.com/kiali/kiali/issues/3279 (but perhaps that can be a second iteration)
- instead of showing data for last 30m + last 3h, put a duration selector in the table toolbar just for stats comparison
- in toolbar, add a percentile multi-selector
- the stats are loaded asynchronously so they don't impact the display of other elements, however, I think it would be better to display them only on demand. For instance, a small link/button in the Statistics cell for each line, to load stats just for that line; and in the header a similar one to load all stats.

Feedback is welcome!

**Comment by jotak** [comment]
perhaps this is a place where a heatmap would make sense...

**Comment by jotak** [comment]
Following my previous comments, I'm doing some tries with a heatmap, and to be frank I like it :)
Heatmaps allow to show condensed 3-dim data probably better than any other chart. They might be less intuitive to read at first, but we quickly get used to it.

Here's an example I'm doing:
![Capture d’écran de 2020-10-29 14-05-36](https://user-images.githubusercontent.com/2153442/97578152-b2f24780-19f0-11eb-845e-30c25c247d77.png)

I've added a verbose explanation as tooltip to help users understand really what those numbers are.

As said in my last comment I still think this should be displayed on demand.
