### ISSUE TITLE
When no Traces - Empty Traces details tabs in bottom

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#3299]
Happens on istio-system applications.
![Screenshot from 2020-10-07 14-30-49](https://user-images.githubusercontent.com/604313/95331214-f3efb400-08a9-11eb-80bf-7b2bad9ae997.png)

**Comment by jotak** [comment]
@lucasponce I'll take this one if you don't mind, I was fixing it anyway via another PR, but will send a separate PR

(As I understand this is different from the bottom padding you're dealing with)

**Comment by lucasponce** [comment]
> (As I understand this is different from the bottom padding you're dealing with)

Yes, this is more about conditional rendering the tabs if there is no results.

The issue I'm working on is generic for all layout.
