### ISSUE TITLE
Inform user about jaeger URL not configured

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#3304]
In-app, inform user via an icon/tooltip on tracing page that Kiali can offer more integration with jaeger when the external URL is configured.
Obviously this icon would not be displayed when the url is configured.

**Comment by lucasponce** [comment]
There is already a couple of messages in the MessageCenter in this situation.
Just a note to review them as well in this context.

**Comment by lucasponce** [comment]
Outdated.
Already addressed in the message center.
