### ISSUE TITLE
Fullscreen mode for graphs

### ISSUE THREAD

**Issue by thearegee** [kiali/kiali#3309]
**Problem**

I want to include in our documentation and our out of hours support application a quick architecture / topology diagram of our stack. There are various tools available but they go out of date quickly. Kiali graph generates a dynamic an realtime snapshot of our infrastructure, simple example shown below:

![image](https://user-images.githubusercontent.com/8751165/95484724-b9a91400-0988-11eb-8650-8748b140f813.png)

However this is embedded within Kiali, I would like to be able to use this elsewhere.

**Solution**
I would like Kiali to offer a fullscreen mode that is acessible via a URL (query param option maybe), this could offer the following user flows:
1) Embedded the page with an iframe or portal into developers other tools
2) Display Kiali on dashboards and monitors
3) Use tools like puppeteer to screenshot the diagram to keep documentation upto date 

I think this would be a really simple yet powerful big for the platform.

**Comment by jshaughn** [comment]
Hi @thearegee, we are looking at having fullscreen options for pages in the UI.  Also, we do already offer "kiosk mode" for embedding kiali into other places.  See [Embedding Kiali](https://github.com/kiali/kiali/blob/819c84fa73e29e7daabcd84d28c244df90c59c72/README.adoc#embedding-kiali), maybe this is what you are looking for.

**Comment by mtho11** [comment]
@thearegee I'm currently working the fullscreen options (full monitor dimensions) right now: https://github.com/kiali/kiali/issues/3155

**Comment by thearegee** [comment]
@jshaughn thank you for sending me that, I never saw that in the documentation. It is pretty close to what I want and a great start for my project. It would be good if I could toggle the header off:

![image](https://user-images.githubusercontent.com/8751165/95565009-7c3f9780-0a17-11eb-8ec4-a1cd1d4d1fe4.png)

It would also be powerful if we could select display options:
![image](https://user-images.githubusercontent.com/8751165/95565149-aabd7280-0a17-11eb-8688-c997436b5069.png)

With query params, so I could embed this into a dashboard with animations on and other options.
I feel like these and with @mtho11 - I could achieve exactly what I want and I think might be useful to other people.

By the way, we love Kiali at YNAP 😃

**Comment by jshaughn** [comment]
> By the way, we love Kiali at YNAP

Thanks, @thearegee!   As for the header, I thought we fixed that in v1.21 *(see https://github.com/kiali/kiali/issues/2946).   Are you using an older version?
