### ISSUE TITLE
Split/Join strategy on Tracing queries

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#3311]
This is related to EPIC https://github.com/kiali/kiali/issues/2776

In short interval the correlation works well:
![image](https://user-images.githubusercontent.com/1662329/95577605-c71ad880-0a32-11eb-8042-757167f475fa.png)
![image](https://user-images.githubusercontent.com/1662329/95577640-d863e500-0a32-11eb-9f78-c232136324b7.png)

But when we open the interval we find always the following pattern due the nature of tracing info:
![image](https://user-images.githubusercontent.com/1662329/95577699-f598b380-0a32-11eb-836d-7f49a93f2caa.png)

As I can't fetch all, I need to limit the number of results, then on this case using correlation is less effective.

This issue is to discuss a proposal to apply a new pattern on large intervals.

For example, we can "split" the interval and perform several queries (with limits) and then put them together as single result.

Then, I would have a better overview picture of what happened.

This is always configurable, but at some point if I'm selecting 3h check, instead to get the latest 20 traces of that interval (that would always return the latest 20 traces in last 5 minutes) it can split the 3h interval in several queries to give a better picture during that timeline.

Note, this is just an approach with the given API and without using other external mechanisms.

**Comment by lucasponce** [comment]
cc @aljesusg @jotak

**Comment by jotak** [comment]
Good point, I often have the same frustration when looking back in past.

I didn't think about a split/join strategy but it is definitely interesting, yes.

A different possibility (or complementary) could be to load more data as a kind of background job: continuing to populate the chart after the initial load, with small batches. Perhaps with a couple of control buttons, to start and stop loading more traces.
