### ISSUE TITLE
Make "Create Traffic Policies" viewing configurable

### ISSUE THREAD

**Issue by BoOgatti** [kiali/kiali#3333]
**Is your feature request related to a problem? Please describe.**
![изображение](https://user-images.githubusercontent.com/28646170/96593220-e991d900-12f1-11eb-87be-ae598cfa920d.png)

I use kiali (v1.25.0) in anonymous mode for read-only purposes. I already can to hide action for sidecar injection with option in my CR:
```
  kiali_feature_flags:
    istio_injection_action: false
```
Because kiali's SA is read-only account this action unusable and make error:
```
authorizationpolicies.security.istio.io is forbidden: User "system:serviceaccount:kiali-system:kiali-service-account" cannot create resource "authorizationpolicies" in API group "security.istio.io" in the namespace "testing-ns"
```
**Describe the solution you'd like**
It will be good to have similar option for hiding "Create Traffic Policies" action as for sidecar injection

**Comment by lucasponce** [comment]
Thanks for reporting this @BoOgatti 

Yes, it should add that feature flag, at least showed disabled.

**Comment by jshaughn** [comment]
+1 on disabled.
