### ISSUE TITLE
Multi-cluster: replicated control-planes with single prometheus

### ISSUE THREAD

**Issue by harpratap** [kiali/kiali#3335]
**Is your feature request related to a problem? Please describe.**
Based on the [multi-cluster description here](https://kiali.io/documentation/latest/features/#_multi_cluster_support) Kiali works with replicated control planes (different istio and k8s control plane per cluster) but this also implicitly assumes the metrics collected by prometheus are also isolated. So we would like to know if it's possible to let kiali fetch metrics only from it's respective cluster metrics (we add labels to all our prom jobs to include something like cluster_id=abc-123)

**Describe the solution you'd like**
Kiali be able to fetch metrics of it's respective control plane

**Additional context**
For testing this one could use cortex, and push metrics from different kubernetes and istio control planes to a single cortex source

**Comment by israel-hdez** [comment]
We are trying to figure out how to support multi-cluster in Kiali, there is still no clear path but we are working on it.

Focusing on your particular request, I understand you still have one Kiali per Istio control plane and the only _request_ is to be able to use one central prometheus where metrics are _logically partitioned_ using a label. Is this right?

**Comment by harpratap** [comment]
@israel-hdez Yes, correct. 
In think in our case it would be enough if we could configure kiali to always append extra labels when making a prom query.

**Comment by israel-hdez** [comment]
I'll look at this as part of the Multi-cluster effort.
So, don't expect this to be solved quickly.

**Comment by jshaughn** [comment]
@israel-hdez If we have captured this in the overall MC epic then this may be something we can close, with a reference to the epic.  Assigning and leaving up to you.

**Comment by lucasponce** [comment]
Closing it in favor of global discussion https://github.com/kiali/kiali/discussions/4081
