### ISSUE TITLE
DR - No labels on subset - Error in list but not in overview

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#3336]
Remove label in DR's subset.
In Istio config list of Service details it shows invalid config, but in DR Overview page no error is displayed.
It seems issue is in config list.

![Screenshot from 2020-10-21 11-03-48](https://user-images.githubusercontent.com/604313/96698599-9a00eb00-138d-11eb-8abe-ace159bd6c75.png)
![Screenshot from 2020-10-21 11-03-30](https://user-images.githubusercontent.com/604313/96698606-9bcaae80-138d-11eb-9600-0c1926a4e300.png)

**Comment by lucasponce** [comment]
Yes, there is a missing corner case here.
Basically in Service Details we see the problem due the validations happen in the context of all info fetched for a Service: Service details, Workloads, VirtualServices, Destination Rules.

But in the DestinationRule details a missing labels in the DR destination is not triggering at least a warning.

So I think we can add this warning/error there.

**Comment by lucasponce** [comment]
It's closed but it requires an update in the Docs, so a PR is on the way.
