### ISSUE TITLE
Add the show/hide feature to expanded log screen

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#3337]
**Is your feature request related to a problem? Please describe.**
As a Kiali user viewing the logs in expanded log mode I would like to be able filter the logs like I can do on workload log tab.
The screen where it is probably more important to have the show/hide feature is on the expanded logs screen where one is sifting through more of the logs in detail.

This feature was raised by @maltron at the last Kiali User experience meeting.

**Describe the solution you'd like**
The same show/hide/regex controls should also be added to the expanded log screen.

**Comment by jshaughn** [comment]
In general I think an expanded view that includes whole page view would be useful.  By "whole page view" I mean the area right of the left accordion menu and below the masthead, so including toolbars/filters, etc.

**Comment by mtho11** [comment]
@jshaughn right, I know it would useful for the graph for sure.

**Comment by mtho11** [comment]
If what I'm doing with the fullscreen by element stuff works out then this expanded log dialog is mute (and will be deleted). So I will close this issue then.

**Comment by jshaughn** [comment]
@mtho11 Perhaps we should ask UX to understand whether we want to fullscreen just the TextBox or allow fullscreen for the entire log page.

**Comment by jshaughn** [comment]
@mtho11 @lucasponce, I realize now that what I was talking about is very close to kiosk mode + F11.  If you add &kiosk to the URL, and then F11, you are getting fullscreen on the [content] page view.   This should be sufficient and given that we have not had an explicit request for this I don't think we need to pursue it further.   If in the future we see value to fullscreen a specific component we now have the example given the logs textbox.

**Comment by lucasponce** [comment]
> @mtho11 @lucasponce, I realize now that what I was talking about is very close to kiosk mode + F11. If you add &kiosk to the URL, and then F11, you are getting fullscreen on the [content] page view. This should be sufficient and given that we have not had an explicit request for this I don't think we need to pursue it further. If in the future we see value to fullscreen a specific component we now have the example given the logs textbox.

If we want to add a couple of minor links/buttom that doesn't affect to the current layout to enter/exit to this "non distraction mode" it's +1 from my side.

My comments about this issue were only to clarify my concerns about potential relayout when I tried to catch up with the whole discussion (i.e. expand a tab would require a much more work than expected).
