### ISSUE TITLE
istioctl proxy-status migration

### ISSUE THREAD

**Issue by xeviknal** [kiali/kiali#3342]
Kiali proxy status is based in the information provided by the `/debug/syncz` in the istiod pod.
I have recently realized that this endpoint (and others under the /debug prefix) are going to be deprecated soon (asking for specific dates).

The new implementation of the istio-status is using the experimental flag (`istioctl x proxy-status`) and it will output nearly the same information as the current one. It looks like they retrieve the information using the xDS/ADAS [1].

Therefore, there is the need to adapt the backend to fetch the information as they are doing in the experimental version.

The starting to where to look at is: https://github.com/istio/istio/blob/master/istioctl/cmd/proxystatus.go#L148

The consequences for this PR shouldn't impact in the UI though. It is just a change on the implementation detail at fetching moment.

Endpoint end of life date: TBD (asking for it - update the PR with the dates).

Sources: 
- https://youtu.be/qZiMcf_AU4c?t=2005
- https://docs.google.com/document/d/16M6ItjYl5M8ppLlJ5JYTfrcXBrtSQlYKIUgOk31wXdQ/edit

[1] https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/operations/dynamic_configuration

**Comment by jshaughn** [comment]
@xeviknal Do we need to raise priority or is this still OK as Future?

**Comment by xeviknal** [comment]
Updates: Istio team wants to release the new approach in 1.10. The approach won't deprecate the `/debug/` endpoint yet.
They said that replacing the proxy-status is not an easy task, so I assume that we still have `/debug/` for a couple more of major releases.

See the UX/UI meeting:
- recording: https://youtu.be/8ngSstEhFmA?t=1646
- document (January 26, 2021): https://docs.google.com/document/d/1raZOoeYz3APZdQRlJlFA-zgfmEJu2YLaGa4_3KwbNRs/edit#heading=h.tuso7cm8ksjy

**Comment by lucasponce** [comment]
I guess this is outdated and there was recent work on https://github.com/kiali/kiali/pull/4108 so closing this.
