### ISSUE TITLE
[Helm charts] Building with helm v3.3.4 fails with "templates/ingess.yaml: the kind "extensions/v1beta1 Ingress" is deprecated in favor of "networking.k8s.io/v1beta1"

### ISSUE THREAD

**Issue by FilipB** [kiali/kiali#3343]
**Describe the bug**
Building with helm v3.3.4 fails with:
templates/ingess.yaml: the kind "extensions/v1beta1 Ingress" is deprecated in favor of "networking.k8s.io/v1beta1

It's working fine with helm version downloaded by make step .download-helm-if-needed.

**Versions used**
helm version
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}

**To Reproduce**
1. install helm v3.3.4
2. run 'make build-helm-charts'

Result:
Will use this helm executable: helm
Building Helm Chart for Kiali operator
==> Linting /home/fbrychta/work/repo/helm-charts/_output/charts/kiali-operator

1 chart(s) linted, 0 chart(s) failed
Successfully packaged chart and saved it to: /home/fbrychta/work/repo/helm-charts/_output/charts/kiali-operator-1.26.0-SNAPSHOT.tgz
Building Helm Chart for Kiali server
==> Linting /home/fbrychta/work/repo/helm-charts/_output/charts/kiali-server
[ERROR] templates/ingess.yaml: the kind "extensions/v1beta1 Ingress" is deprecated in favor of "networking.k8s.io/v1beta1 Ingress"

Error: 1 chart(s) linted, 1 chart(s) failed
make: *** [Makefile:66: .build-helm-chart-server] Error 1

**Expected behavior**
No errors

**Comment by jmazzitelli** [comment]
FYI: all tests and Makefile use helm v3.2.4.

**Comment by jmazzitelli** [comment]
See: https://github.com/helm/helm/issues/8596 and specifically someone mentions this exact "error" with Ingress: https://github.com/helm/helm/issues/8596#issuecomment-675305111

**Comment by jmazzitelli** [comment]
the helm chart is fixed in PR https://github.com/kiali/helm-charts/pull/11 and the operator is fixed in this PR https://github.com/kiali/kiali-operator/pull/174
