### ISSUE TITLE
Graph usability: hidden edges labels on dense traffic

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#3349]
![image](https://user-images.githubusercontent.com/1662329/97009794-d75ba900-1544-11eb-807c-418c96803298.png)

I wonder if perhaps it's worth to visit some of this scenarios, now we have more demos with different use cases that may help to spot minor usability issues like this one.

**Comment by jshaughn** [comment]
We've not really seen a better alternative than the inline edge label positions.  Perhaps in this situation we can play with z-axis or opacity of the animation, which probably would be better under the label.

**Comment by lucasponce** [comment]
> Perhaps in this situation we can play with z-axis or opacity of the animation, which probably would be better under the label.

+1

Set positions on vectorial maps have a lot of corner cases, I was thinking the same, to put the legend on the front with some z-level or opacity in the animation as well.

**Comment by jshaughn** [comment]
The edge label can not be assigned a different z-index than the edge itself.  And so there is no way I see to have the animation particles go under the text and stay above the edge.   And I don't think having the particles completely under the edge is a good option.  

I think one easy thing we could do is to just stop the animation when the user hovers the mouse over the edge, thus allowing the user to get a clear view of the edge label for this corner case:

![kiali#3349](https://user-images.githubusercontent.com/2104052/97484885-ba055100-192f-11eb-9485-32fa11c384c0.gif)

What do you think @lucasponce ?

**Comment by lucasponce** [comment]
@jshaughn it looks ok to me, it solves the main issue: on high density animations user can't read the edge label, stopping the animation for this sounds a reasonable workaround.

+1
