### ISSUE TITLE
remove explicit v1.0 support

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#3351]
The operator has explicit v1.0 support in the form of the v1.0 Ansible playbook.

When 1.0 is EOL (very soon) we should remove that and all things related (such as the comment in the kiali_cr.yaml that mentions it and the line in the [default-supported-images.yml](https://github.com/kiali/kiali-operator/blob/master/playbooks/default-supported-images.yml#L2))

**Comment by jshaughn** [comment]
I'm adding this to the sprint but before we actually do anything we need confirmation from kevin that we really don't have any need to support a 1.0 install, be it a support exception or whatever.

**Comment by jmazzitelli** [comment]
I believe we are EOL on all supported OpenShift clusters for 1.0 - so I think we can do this at the same time we introduce the new supported version.

cc @jshaughn can you confirm?

**Comment by jmazzitelli** [comment]
We are going to do this during this sprint.
