### ISSUE TITLE
Configurable web port (http_util.GuessKialiURL)

### ISSUE THREAD

**Issue by jvanmalder** [kiali/kiali#3357]
**Is your feature request related to a problem? Please describe.**
Kiali is accessible through an external load balancer running on port 443, which forwards the requests to the Kiali pod on port 20001.
However, when using OpenID authentication with Kiali, the redirect URI that was guessed by Kiali contains the internal port (20001) instead of the external port (443) - see [here](https://github.com/kiali/kiali/blob/9fce924a0c82cf2f1c694feef877a56d5b4bc85a/handlers/authentication.go#L657) and [here](https://github.com/kiali/kiali/blob/9fce924a0c82cf2f1c694feef877a56d5b4bc85a/util/httputil/http_util.go#L95).
This of course stops users from completing their login flow.

**Describe the solution you'd like**
I'm using the Kiali Operator to deploy Kiali, but since the same spec is used as the Kiali configuration, I will use that as an example here.

Similarly to `spec.server.web_fqdn` and `spec.server.web_schema`, allow one to configure the port with `spec.server.web_port`:
```
apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
spec:
  server:
    web_fqdn: example.org
    web_schema: https
    web_port: 443
```

**Describe alternatives you've considered**
I tried setting `spec.server.port` to `443` but that didn't work as the Kiali user doesn't have the required permissions to bind to that port.
As a workaround I'm setting the HTTP header `X-Forwarded-Port` to `443`, which seems to work as intended.

**Additional context**
None

**Comment by jshaughn** [comment]
cc @israel-hdez

**Comment by jmazzitelli** [comment]
I think we already have this documented in another issue. I do remember @israel-hdez talking about adding this recently.

**Comment by jvanmalder** [comment]
Sorry, should have searched the existing issues.
It's indeed a duplicate of #3111.

**Comment by jshaughn** [comment]
Closing in favor of https://github.com/kiali/kiali/issues/3111.
