### ISSUE TITLE
"Show Traces" button text in graph is misleading

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#3365]
In the graph side panel, there's a button allowing to navigate to the traces details page :
![Capture d’écran de 2020-10-28 13-05-26](https://user-images.githubusercontent.com/2153442/97433931-8c63dc00-191e-11eb-95bd-3b38ee70045e.png)

But it is a bit misleading, because we may think clicking on it would actually show traces *within the graph/side panel*, not navigating to another page. Which is quite frustrating when you don't expect that. (we experienced this yesterday while working with @mattmahoneyrh ).

Initially, the text was on purpose more explicit: "Go to Tracing". I'm not sure if it's the best wording or not, but IMO anyway we should be more explicit.
It was changed later to be identical to other similar texts, but I think that was ignoring the context.

**Comment by jotak** [comment]
@lucasponce @jshaughn I think I was on holydays during your discussion there :-) https://github.com/kiali/kiali-ui/pull/1892
wdyt? To me, the new wording fails to tell that the user is going to move to another page, which isn't obvious in this context

**Comment by lucasponce** [comment]
![image](https://user-images.githubusercontent.com/1662329/97436973-1ada5c80-1923-11eb-9f01-78e7473b28c9.png)

Main discussion is to use the same verb / expression for same action.

It's a no go to mix Show / Go / Move / View in the same context.

I'm fine if it's a better wording (i.e. Show Traces details) but we need to align all of these expression to make sure that all pages / tabs have a consistent wording.

I'm not married with the specific verb, my concern is to not introduce different expressions.

**Comment by lucasponce** [comment]
Note that my comment is not only for this subtab, perhaps there are other links that have the same context.
If we want to use this opportunity to review the wording for these scenarios I'm +1 for that.

**Comment by lucasponce** [comment]
This one can be closed. It looks outdated.
