### ISSUE TITLE
duration drop down is "behind" the horizontal bar separating the logs in the log tab

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#3369]
Look at the "Last 1d" option - its "behind" the horizontal grab bar:

![image](https://user-images.githubusercontent.com/2029470/97484840-ad80f880-192f-11eb-8958-f90433225db9.png)

**Comment by jshaughn** [comment]
we don't have much control over that splitter bar, so we may have to live with this minor issue, or increase the z-axis of the dropdown.

**Comment by jshaughn** [comment]
This seems to be resolved, perhaps after the recent time controls refactor, or possibly some other work, or browser update.  But looking for for me on chrome:

![image](https://user-images.githubusercontent.com/2104052/102662026-fabd6180-414b-11eb-86fb-6ed22adb9d80.png)
