### ISSUE TITLE
services "jaeger-query" not found

### ISSUE THREAD

**Issue by elvizlai** [kiali/kiali#337]
using istio helm installer with `--set tracing.enabled=true`

**Comment by elvizlai** [comment]
but now with error `Could not fetch Jaeger info Error: [ Unable to find Jaeger URL: no route defined. ExternalIPs not defined on service 'jaeger' ]`, can kiali work with svc ip or nodeport mode?

**Comment by objectiser** [comment]
What version of istio are you using? Not sure why it is complaining about service 'jaeger'.

**Comment by elvizlai** [comment]
@objectiser 0.8.0 LTS. Looks like jaeger has no LoadBalancer IP. So, can kiali using NodePort or ClusterIP to conn?

**Comment by objectiser** [comment]
Ah - looks like they have disabled the load balancer by default. You need to also specify `--set tracing.ingress.enabled=true`, which is a pain.

**Comment by jotak** [comment]
@objectiser is it something that can be set by default in kiali helm chart?

**Comment by objectiser** [comment]
@jotak don't think so - I don't think one chart can override values in another.

**Comment by elvizlai** [comment]
@objectiser The cloud do not support LoadBalancer or somehow.

**Comment by objectiser** [comment]
Looks like it may need to be defined using an ingress, same as the [kiali helm chart](https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/charts/kiali/templates/ingress.yaml). Would be good if you could raise an issue on the [istio repo](https://github.com/istio/istio) outlining the issue you are having with the current tracing helm chart when using `LoadBalancer`.

**Comment by pilhuhn** [comment]
Where do we stand here?
