### ISSUE TITLE
Add more controls on span stats

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#3379]
This is a follow-up on https://github.com/kiali/kiali/issues/3293
In that previous task, comparison stats are added to span list. It uses a default set of parameters that cannot be modified at the moment (durations, percentiles etc.)
These parameters should be actionable from the table toolbar.

**Comment by jotak** [comment]
Suggestion from @mtho11 : to use a slider, similar to the one in Graph Replay. As a substitute for the options of enabled intervals? Or as a way to "edit" an interval directly in the heatmap? ( https://github.com/kiali/kiali-ui/pull/1987#issuecomment-723321723 )

**Comment by lucasponce** [comment]
Kiali is unifying the controls to query per percentile in similar escenarios: graph, metrics and trace:
![image](https://user-images.githubusercontent.com/1662329/128505385-f579f656-8260-4630-b31d-b4f80565a201.png)
![image](https://user-images.githubusercontent.com/1662329/128505411-e52353f9-cc9c-4eea-91b8-d5f8a750485b.png)
![image](https://user-images.githubusercontent.com/1662329/128505445-5b1e5114-9e55-4a69-934b-e6b24de5becc.png)

So, probably in the future we may unify all these controls, but I think we'd like to keep this consistency and to not change the same controls.
