### ISSUE TITLE
Link Interval trace query with Telemetry percentiles

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#3380]
Now that we are progressing on the Telemetry + Tracing correlation I'd like also to propose this issue.

One of the major problems with tracing info is the lack of histograms, and hence, to understand which info is interested for the user and in which context.

Also, tracing in real scenarios has a high density, so in other words, as a user is not easy to identify "which trace I should look ?"

In that context, metrics allows to correlate spans:

![image](https://user-images.githubusercontent.com/1662329/97703043-3c1c8380-1ab0-11eb-994f-ab8934c0bea2.png)

But I think that the tracing tab could also benefit with the controls, instead to have the current time interval, Kiali may also reuse the same telemetry interval used in metrics and allow also to identify which percentile is linked with a time, and allow search for that.

Instead to have this interval trace, it could be changed with same percentile labels and then Kiali would perform the query for that instead to know which absolute numbers are required.

![image](https://user-images.githubusercontent.com/1662329/97703087-4c346300-1ab0-11eb-886b-9cf82d6dedf0.png)

**Comment by lucasponce** [comment]
Note, that I also see fit to put it together with this other proposal to extend how Kiali is querying tracing:
https://github.com/kiali/kiali/issues/3311

**Comment by jotak** [comment]
+1, sounds interesting
Just to make sure if I understand correctly the idea: we would change the "Interval" toolbar control to display something like traces in:
- 99th percentile
- 90th percentile
- etc

When the user selects something, it triggers first a telemetry query to know the response time at the demanded percentile, and then a second query to jaeger to pick traces above that percentile.
Am I understanding correctly?

**Comment by lucasponce** [comment]
> When the user selects something, it triggers first a telemetry query to know the response time at the demanded percentile, and then a second query to jaeger to pick traces above that response time.

Yes, the telemetry query may give information about the current interesting intervals that can be used in that box to select a better label of "99th percentile" instead to choose an absolute value as we have today.

Also, linked with the split/join it can play better with limitation of results in large intervals.

To me the main context of this is "from all number of traces I have, which is the interesting one".
