### ISSUE TITLE
Add Sidecars on  "Create Traffic Policies" namespace action

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#3394]
We have discussed with @howardjohn to have a feature in Kiali to add security based on current telemetry.

Kiali already implements this feature using AuthorizationPolicy objects:

https://github.com/kiali/kiali/issues/2924

And documented in

https://kiali.io/documentation/latest/features/#_security_traffic_policies

But also it seems that it makes sense to offer an action to perform a similar task using Sidecar per performance reasons.

So this issue is to enable a similar action "Create Traffic Sidecars" but using networking Istio resources instead of security ones.

**Comment by jshaughn** [comment]
@lucasponce What do you think of raising the priority on this one.  I was thinking it could be interesting for Nick to become familiar  more with Istio, Sidecar config, and the UI code?

**Comment by howardjohn** [comment]
I played around with adding an (incomplete) version of this to istioctl if it helps at all: https://github.com/howardjohn/istio/tree/istioctl/sidecar-gen. Feel free to copy any of it that is useful

**Comment by jshaughn** [comment]
Thanks, @howardjohn .  To me this still seems like a useful feature.  I think users would like to be able to lock down definitions and then perhaps add them to their CI/CD definitions.

**Comment by lucasponce** [comment]
I had this issue out of the backlog on purpose as the sidecar has some limitations.
The egress traffic is easy to secure (I guess I have a draft in my local env) but the ingress traffic can't be filtered in the same way that an AuthorizationPolicy does.

From user perspective the feature is available, if @howardjohn has some suggestion in that way we can reconsider, but I'm looking into his code and more or less I had the same code on my side as well.

I guess we'll need to perform this using Envoy config if user may want to protect the inbound traffic (or use the AuthorizationPolicy as defined in the current implementation).

**Comment by howardjohn** [comment]
Just to clarify, my change in Istioctl was never merged or submitted as a PR. Its just a branch on my fork.

> but the ingress traffic can't be filtered in the same way that an AuthorizationPolicy does.

Right, they serve different purposes really. AuthorizationPolicy is for securing inbound traffic, Sidecar is mostly a performance optimization to avoid getting config for the entire mesh when you only send traffic to a few services

**Comment by lucasponce** [comment]
> AuthorizationPolicy is for securing inbound traffic, Sidecar is mostly a performance optimization to avoid getting config for the entire mesh when you only send traffic to a few services.

Yeah, then perhaps we can place this action under Workload level, as you point the AuthorizationPolicy is intended for "secure" and we can enable this as the on-going work we're doing around Sidecar config and manipulation.

**Comment by lucasponce** [comment]
I'm just reviewing this one.
I think this issue could move forward, instead to choose AuthorizationPolicies or Sidecards, the "Create Traffic Policies" can combine both.

Then from one side, AuthorizationPolicy would secure inbound traffic and the Sidecar may optimize the Envoy upstream destinations.

Both objects can be managed by the users and the goal is to help them to put them in place in their scenarios.

So, goal of this issue could be to add a "Sidecar" generated by Kiali following same logic of the "AuthorizationPolicy" but to optimize the outbound connections.

**Comment by lucasponce** [comment]
This may require to update the "Security" chapter in the kiali.io Tutorial
