### ISSUE TITLE
Use client / server timeouts (potential leaks)

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#3406]
This is a follow-up on https://github.com/kiali/kiali/issues/2905 : a missing connection timeout was added to fix a specific case.
But there's other missing connection timeouts in our codebase that could result in the same bugs.

I don't think we necessarily have to see the bug happen before fixing it; using client connections without timeout is a known risk [1] that we should tackle via code best practices IMO.

- I identified just one place in the code where it is missing: `versions.go` / `istioVersion()`
- Similarly, server timeouts need to be defined to avoid file descriptors leaks [2]. To fix in `server.go`

[1] https://medium.com/@nate510/don-t-use-go-s-default-http-client-4804cb19f779
[2] https://blog.cloudflare.com/the-complete-guide-to-golang-net-http-timeouts/

**Comment by jotak** [comment]
Personally I think it would be wise to backport these fixes asap.

**Comment by lucasponce** [comment]
Note that k8s API and Kiali uses a extensive use of watches [1]

I wonder if a generic timeout can solve some scenarios but it can add some problem on these calls.

These are connections that are kept open.

In other words, this issue looks good, but it will need more close review to avoid side effects.

[1] https://kubernetes.io/docs/reference/using-api/api-concepts/#efficient-detection-of-changes

**Comment by jotak** [comment]
@lucasponce I was not thinking of a generic timeout (not sure if it's even possible), but per client connection, as we do in many of our client calls, there's just one that is missing.

**Comment by jshaughn** [comment]
Probably a separate concern, but we may also want to look at our calls to prometheus.  I think we use only context.Background and that context does not have a timeout and isn't cancelable. We may want to take a look there...
