### ISSUE TITLE
Support Gateways workloads in user namespaces

### ISSUE THREAD

**Issue by xeviknal** [kiali/kiali#3408]
There has been a new RFC into Istio Upstream to introduce a `Gateway Injection`.

https://docs.google.com/document/d/1Rmp9B3DDypgMCau-YAqidx_r3qvKLZj6jUX-t22zj84/edit?ts=5fa4a68e#heading=h.muhie2k8j6yh

In Maistra side: https://issues.redhat.com/browse/MAISTRA-1874

Kiali probably will need to add new Istio Objects and/or validations.

**Comment by lucasponce** [comment]
Reviewed the specification in https://docs.google.com/document/d/1Rmp9B3DDypgMCau-YAqidx_r3qvKLZj6jUX-t22zj84/edit# and https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/#custom-templates-experimental I think we can refine the scope of this issue.

The main goal of this requests is that users may deploy new Istio Gateway workloads in any namespace, instead to only use the standard ones defined in the control plane namespace (typically the "istio-system").

So, Kiali could start to identify those workloads and treat them correctly, so, probably the same scheme of "app/version" labellling won't apply and also it needs to be marked properly in Kiali (i.e. this workload is an Istio Gateway).

Also, the Gateway validation https://istio.io/latest/docs/reference/config/networking/gateway/#Gateway should be updated to cover these use cases (i.e. a Istio Gateway resource can point to a non existing gateway deployment).
