### ISSUE TITLE
Span rows: expandable mode

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#3420]
This is a follow-up on https://github.com/kiali/kiali/issues/3293

Implement an expandable mode on span rows.
The goal is to show smaller rows hence more rows on screen. So, each table cell may have a "full" and "summary" display mode.

Suggestion:
- The "full" (expanded) mode looks the same as what it is currently:

![Capture d’écran de 2020-11-09 13-47-45 (copie)](https://user-images.githubusercontent.com/2153442/98658692-9edd0d00-2343-11eb-902d-61be3bbede0e.png)

- For the "summary" mode:
  - cell 1 (timeline) unchanged
  - cell 2 (app/workload) would not show the pod
  - cell 3 (summary) would show only operation name and perhaps the component or the request summary
  - cell 4 (stats) would show duration + a reduced version of the heatmap, without labels and with smaller cells
  - cell 5 (links) unchanged

**Comment by lucasponce** [comment]
cc @lwrigh
