### ISSUE TITLE
Consolidate k-charted into kiali repo

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#3422]
Proposal discussed here:
https://groups.google.com/g/kiali-dev/c/vI-Kg8gXBgs

**Comment by jotak** [comment]
Hi @jadeyliu939 ,
So our k-charted lib will be moved, integrated into Kiali. Can you just confirm it will have no impact on iter8 (said differently, you are not consuming directly the k-charted lib) ? As far as I know there shouldn't be any impact.
