### ISSUE TITLE
[multi-cluster] Investigate graphical mesh view

### ISSUE THREAD

**Issue by jshaughn** [kiali/kiali#3430]
Epic: https://github.com/kiali/kiali/issues/1833

A mesh can involve multiple networks, clusters, namespaces, and services.  #3413 involves the discovery of the mesh components.  Kiali needs to expose that information in at least one, but possibly mutiple ways (list view, graphical view, embedded within other pages...).  This is to investigate the feasibility and usefulness of a graphical view.

The initial idea is to explore something analogous to the traffic graph, but based more on mesh topology config, allowing users to visualize the mesh, and potentially navigate, or drill into, it.

**Comment by jshaughn** [comment]
I don't think this has any immediate priority.  Unassigning and resetting as Future.

**Comment by lucasponce** [comment]
I'm going to close this one in favor to the main discussion about this topic 
https://github.com/kiali/kiali/discussions/4081

From the discussion new epics can be created with a closer scope.

Note that the topic is quite active in Kiali, this is just a consolidation of the talks into a single discussion.
