### ISSUE TITLE
UI bug : Distributed Tracing Arrow is Overlapped by Right side panel 

### ISSUE THREAD

**Issue by pbajjuri20** [kiali/kiali#3431]
UP-arrow inside the square box is overlapped by the Right side panel in the Kiali-UI.

It is the right side of "Distribution Tracing" (left panel)  in Kiali- UI

Bug screen-shot:

![ui bug](https://user-images.githubusercontent.com/55099523/99113821-dfe05600-25bd-11eb-8c88-c1cf8025c63b.png)

Expected:

![ui bug 2](https://user-images.githubusercontent.com/55099523/99113902-fc7c8e00-25bd-11eb-8b2c-cbff859fb944.png)

**Comment by pbajjuri20** [comment]
Versions used: 

Kiali UI - 1.27.0-edge (52b209295635272440fd0e32f7ff958a8315a2e1)

Istio - 1.7.4

**Comment by jshaughn** [comment]
Closing as this was identified as an environmental issue for @pbajjuri20 .  It was not otherwise reproducible.
