### ISSUE TITLE
ServiceEntry does not appear in Graph for Nginx proxy_pass

### ISSUE THREAD

**Issue by fai555** [kiali/kiali#3434]
I am not sure if this is some new feature request or it's already available.

I deployed an Nginx as a Deployment. This Nginx contains hundreds of proxy_pass rules for a variety of internal and external services. The kubernetes cluster also contains Istio 1.7.3 and it routes traffic to the Nginx deployment. In this case Nginx is just proxy_ passing.

Since the Nginx was proxy_passing to other services using the service URLs, I thought if I create a ServiceEntry with Egress TLS Origination I can observe the traffic leaving the cluster and also track the percentage of traffic that is failing.

I initially setup the httpbin.org application in the Istio docs and made cURL requests from the Sleep container and that worked just fine.

But when I tried applying the same configs to the Nginx app, the ServiceEntry does not appear in the Graph.

My hunch is that Nginx proxy_pass may behave differently than a redirect. And ServiceEntry may only work if the service inside the cluster is making a call to the external service directly.

I am not sure how to get this working.

**Comment by jshaughn** [comment]
There are a variety of things that could be an issue.  First, ensure the service entry is defined in a namespace accessible to the user. 
 Second, ensure that istio is generating the telemetry you expect in prometheus.  And third, it's simply possible that you you've hit on a use-case not yet handled, as the host-based discovery of service entries is not always straighforward.

**Comment by jshaughn** [comment]
@fai555 is this still an issue for you?

**Comment by jshaughn** [comment]
@fai555 Please retest this using v1.29 or later (to be released later this month).  If still an issue please re-open.
