### ISSUE TITLE
Align List pages with Namespace selector logic on empty selection

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#3437]
Graph and List pages differ in semantic of namespace selection.

When no namespace selected, graph shows an empty page meanwhile that list pages perform a "select all".

Now that "select all" is a explicit option due https://github.com/kiali/kiali/issues/3173 it makes sense to align that with list pages.

So, nothing will change, the user will be able to "select all" but behaviour will be the same in graph + list pages, so when no namespace is selected on list pages will show an empty result.

Note, Overview page is out of the scope of this issue on purpose.

**Comment by jshaughn** [comment]
I think this is a good behavioral change.  This will protect users from an unwanted query of all namespaces when arriving on a list page no namespaces selected.   And for when namespaces are selected the behavior will be unchanged from today.

**Comment by lucasponce** [comment]
Once that https://github.com/kiali/kiali-ui/pull/1992 is merged, I think this one is very minor and can be added easily within the current Sprint.

So, then it will consolidate the change in the same https://github.com/kiali/kiali/issues/3173 release.
