### ISSUE TITLE
[multi-cluster] incorporate *_cluster_name attributes into graph

### ISSUE THREAD

**Issue by jshaughn** [kiali/kiali#3439]
Epic: #1833

Istio has introduces source_cluster_name and destination_cluster_name to better identify cross-cluster request traffic.  These attributes are set when the cluster is explicitly identified in the mesh.   For example, when istalling istio, if you use istioctl, set these flags to the values that make sense:

--set values.global.meshID="mesh1"
--set values.global.multiCluster.clusterName="cluster1"
--set values.global.network="network1"

Using these attributes Kiali should be able to better identify cross-cluster traffic.

**Comment by jmazzitelli** [comment]
As part of this, we should add those optional settings to our install-istio-via-istioctl hack script.

**Comment by jshaughn** [comment]
@israel-hdez Closing this sub-task as completed, will add follow-up subtasks based on review comments in the PRs.

**Comment by israel-hdez** [comment]
Per the last comment, this is done.
Closing...
