### ISSUE TITLE
Represent spans relationships

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#3441]
**Problem to solve**

Currently, spans are displayed as a flat list in the tracing view.

Since spans can have run in parallel and have multiple children, it is not obvious from that view to know which span results from which other one. In fact it is sometimes impossible.

In this example, I drew an arrow to show a relationship:
![Capture d’écran de 2020-11-18 09-36-24](https://user-images.githubusercontent.com/2153442/99506356-48468300-2982-11eb-8578-0e8a5f7c899b.png)

Knowing this relationship can be important when troubleshooting. For example in this case, we can see that a request did not perform well (lot of red in heatmap). We might want to know if the problem happened client-side or server-side. The red heatmap corresponds to a client request from workload "ai". So, we need to know if the corresponding server-side span is red as well. It would be nice to be able to quickly localise that server-side span.

**Proposal**

I don't have a clear proposal yet, it's open for ideas & discussion. It could be for instance actionable button/links per row to highlight parent/children (similar to our "focus" feature in graph). Or at a minimum, write span ids & child/parent ids on each row.

**Comment by lucasponce** [comment]
I think this representation could be also linked with https://github.com/kiali/kiali/issues/3182.

The idea of introducing a minigraph in the traces tab with a zoom in the application/workload/service may help to correlate that info.

In any case, I don't see progressing more deep but perhaps allowing user to examine the traces/span in Jaeger.

**Comment by lucasponce** [comment]
I'm going to close this one to consolidate the discussion and actions on #3182 

Probably #3182 should be moved to an Epic with a list of subtasks, we are in phase of defining the scope.
