### ISSUE TITLE
Traffic tab crash for service and workload for error-rates project

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#3449]
Happens only when deploying error-rates project.
Go to alpha or beta namespace's any workload or service details.
Click on Traffic tab. Page crashes. No error in logs.

**Comment by lucasponce** [comment]
I can't see it on master right now, perhaps it's due some testing in other WIP branch ?

**Comment by hhovsepy** [comment]
Cannot see this anymore after recent merges to master.
