### ISSUE TITLE
Kiali.io links to videos need some refactoring

### ISSUE THREAD

**Issue by abonas** [kiali/kiali#3455]
Epic: https://github.com/kiali/kiali/issues/4118

Kiali.io website currently has 3 sections with videos:
Getting started videos, latest videos, sprint demo videos.
Seeing those 3 sections requires a lot of scrolling and I doubt if users get to see all of the sections. (and there is a big white space between them as well).
also, Latest videos probably doesn't contain correctly the latest videos because sprint demos from say November/October don't show up there, and the latest video there is from August. So it looks strange when looking at that section and seeing more recent videos in Sprint demos section.
I suggest reducing those 3 sections into one or two.
I would put "sprint demos" as the first one, and then perhaps "quick tutorials" or "getting started".
Latest is something that would include both demo/tutorials and is a bit of a duplicate with the two other sections.

**Comment by lucasponce** [comment]
I plan to update Kiali.io in https://github.com/kiali/kiali/issues/4118 that may include this issue too.

> I suggest reducing those 3 sections into one or two.

+1 to have only 1 section and let user to jump into the Youtube section of Kiali where that "Home" can be used to add better categories, but adding to many video sections is not helping the user and also it's making more difficult to attend.

**Comment by lucasponce** [comment]
The task #4118 is a big one and it should be addressed by more people, but it could be a good opportunity to review the doc for Kiali 1.36 and 1.37.
