### ISSUE TITLE
multi-arch builds for the operator

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#3460]
Similar to what was just [done for the server (PR 3405)](https://github.com/kiali/kiali/pull/3405), we would like the operator makefile infrastructure to produce a multi-arch build. We do not want to publish multi-arch images until we have all of Kiali (server and operator) available with multi-arch images.

We did some preliminary work in this area a few months ago when we got the makefile infrastructure to be able to produce [ARM64](https://github.com/kiali/kiali-operator/pull/6) and [ppc64le](https://github.com/kiali/kiali-operator/pull/72) builds. This issue is to take that further and have multi-arch builds produced via `docker buildx` and product images for the same hardware produced by PR #3405.

**Comment by jmazzitelli** [comment]
_(Note: the Kiali team is currently not prepared to support users of these multi-arch images on anything other than amd64 hardware. Users will be able to look to the community for this support.)_

**Comment by morlay** [comment]
@jmazzitelli I create a PR to support this.

 really hope kiali official could publish multi arch images. just for release.
