### ISSUE TITLE
Traces query failed from Graph

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#3461]
![image](https://user-images.githubusercontent.com/1662329/100110572-670ab500-2e6d-11eb-9d97-5a3fc6cacb31.png)

How to reproduce, follow the istio.io task with minikube + Istio 1.8 on [1].

I guess it's related to ServiceEntry use here, so I suspect if perhaps traces should be disabled in that scenario or simply to not fail in a 404 not found on this case.

[1] https://istio.io/latest/docs/tasks/traffic-management/egress/egress-control/

**Comment by jotak** [comment]
I'll run this scenario, not sure why it would fail to query (instead of just showing 0 trace). That's the first issue.
And I don't know about showing the traces tab when a service entry is selected. Probably most of the time it won't show anything... unless the user happens to create traces with the same service name as this service entry.

**Comment by lucasponce** [comment]
> I'll run this scenario, not sure why it would fail to query (instead of just showing 0 trace). That's the first issue.
> And I don't know about showing the traces tab when a service entry is selected. Probably most of the time it won't show anything... unless the user happens to create traces with the same service name as this service entry.

Yes, my expectation would be to not fail on empty traces, I can reproduce with the electronic-shop demo as well:

![image](https://user-images.githubusercontent.com/1662329/100207008-5e66bd00-2f07-11eb-8137-088bce38b21a.png)

Perhaps here user would expect to deal with the 404 in a silent way, because it's not an error per se, just empty results, I think.

**Comment by jshaughn** [comment]
@lucasponce Perhaps this should be added to the sprint?
