### ISSUE TITLE
publish multi-arch server and operator images to quay.io

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#3463]
Two community contributions were made recently that provide the ability for the makefile infrastructure to build and push to quay.io multi-arch images of both the [server](https://github.com/kiali/kiali/pull/3405) and the [operator](https://github.com/kiali/kiali/pull/3462).

We need to confirm we can build these multi-arch images successfully via Jenkins and if so push them to quay.io during our release process via our Jenkins pipeline.

(For the record, I am unable to build for any arch other than amd64 on my own laptop, but I suspect that is a limitation on my own machine. We do need to confirm that the Jenkins machine doesn't have similar limitations).

The commands to use would be something like this:

```
# Build and push the server multi-arch image
make -e DOCKER_CLI_EXPERIMENTAL=enabled build-linux-multi-arch container-multi-arch-push-kiali-quay

# Build and push the operator multi-arch image
make -e DOCKER_CLI_EXPERIMENTAL=enabled container-multi-arch-push-kiali-operator-quay
```

Obviously, we can alternatively do it all in one command via:

```
make -e DOCKER_CLI_EXPERIMENTAL=enabled build-linux-multi-arch container-multi-arch-push-kiali-quay container-multi-arch-push-kiali-operator-quay
```

**Comment by jmazzitelli** [comment]
I briefly looked at the Jenkins build script, and I think these are places we need to touch.

1. https://github.com/kiali/kiali/blob/v1.27.0/deploy/jenkins-ci/Makefile#L139
Should call the two new targets to build and push the multi-arch image:
```
make -e DOCKER_CLI_EXPERIMENTAL=enabled build-linux-multi-arch container-multi-arch-push-kiali-quay
```
2. https://github.com/kiali/kiali/blob/v1.27.0/deploy/jenkins-ci/Makefile.operator.jenkins#L103
Should call the new target to push the multi-arch image:
```
make -e DOCKER_CLI_EXPERIMENTAL=enabled container-multi-arch-push-kiali-operator-quay
```

**Comment by morlay** [comment]
instead of `docker tag && push`, multi tags could be pass

https://github.com/kiali/kiali/blob/v1.27.0/deploy/jenkins-ci/Makefile#L143-L145
```
QUAY_TAG=$(QUAY_NAME):$(VERSION_TAG) $(QUAY_NAME):v$(OPERATOR_VERSION_BRANCH)
```

https://github.com/kiali/kiali/blob/v1.27.0/deploy/jenkins-ci/Makefile.operator.jenkins#L107-L109
```
OPERATOR_QUAY_TAG=$(QUAY_OPERATOR_NAME):$(VERSION_TAG) $(QUAY_OPERATOR_NAME):v$(OPERATOR_VERSION_BRANCH)
```
