### ISSUE TITLE
[a11y] Color-blind heatmaps

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#3470]
Investigate a solution for colorblind-friendly heatmaps.
Could be a setting in pages where heatmaps are displayed, to turn-on colorblind mode (and store that in local storage); when the mode is active, heatmaps are in greyscale or other color sets

see also https://wistia.com/learn/culture/heatmaps-for-colorblindness

cc @lwrigh

**Comment by lucasponce** [comment]
Outdated, I think this issue is more related to get a design guideline from https://www.patternfly.org/v4/guidelines/colors for these kind of components.

When framework has better specific support we can create a task for it.
