### ISSUE TITLE
Weird percentage in Graph edges

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#3477]
When selecting "request per second" option, there are a couple of "%" messages that are not very clear what they mean.

![image](https://user-images.githubusercontent.com/1662329/100448128-23ed5380-30b2-11eb-9cf5-5fff090744c5.png)

Not sure if it's a bug (it looks so) or if it may need some extra documentation in the legend or similar.

This issue has been spotted in the context of mirror traffic: https://github.com/kiali/kiali/issues/3476

Which in general it looks a little bit odd:

![image](https://user-images.githubusercontent.com/1662329/100448933-5cd9f800-30b3-11eb-86de-451aa73053b8.png)

I guess it may be related it has only traffic from destination workload meanwhile source workload is empty.

**Comment by jshaughn** [comment]
When requesting "Requests Per Second" if you see a percentage below the rate it's the percentage of requests with errors.  I'll add a help blurb on the menu item.

**Comment by jshaughn** [comment]
As for mirror traffic, this is a longstanding issue with istio telemetry.  The mirrored request is not reported, and so you see you don't see that initial request, but if it generates susequent upstream requests those will show up.   There are actually a coupld of Istio issues for this, and some other related issues:

https://github.com/istio/istio/issues/11093  // mazz wrote this one up almost two years ago
https://github.com/istio/istio/issues/23496
