### ISSUE TITLE
Publish the Kiali API docs to Github Pages

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#3491]
**Is your feature request related to a problem? Please describe.**
The Kiali.io API documentation pages were broken because of swagger-ui javascript issues. 

**Describe the solution you'd like**
We wish to publish a static API document (in asciidoc) to GH pages and then link from Kiali.io back to this

**Comment by jshaughn** [comment]
@mtho11 I don't think we need to link from kiali.io to the new adoc on github.  That can be reached directly bt gh users.

**Comment by mtho11** [comment]
@jshaughn ok

**Comment by jshaughn** [comment]
@mtho11 Thinking on this a bit more and looking back at the original issue, https://github.com/kiali/kiali/issues/3290, I think we can actually dial back what we do here.  The goal is to have a readable version of the dev doco on github, that is up to date.  We already force devs to run `make swagger-gen` as part of PRs that affect the swagger/api documentation.  That generates swagger.json.  Could we at that point also generate something like `kialii-api.adoc` and just keep it at the top level, as a sibling to swagger.json?   I think it will render nicely on github if a user clicks on it, like README.adoc.  And then it would be versioned as well, like any other commit.  Let me know what you think, sorry for the late feedback but I'm hoping this can simplify things.

**Comment by jshaughn** [comment]
@mtho11 If you have anything to add to this please let @cfcosta know, I'm reassigning to him.  Thanks!

**Comment by jshaughn** [comment]
@cfcosta a blurb from Mike...

> Here is the API doc issue that I was working on. I better hand this off before I completely forget what I was doing ;D I have not really done anything with it lately — you know, because I’m a lazy retired guy :}

> So this is an npm package that I published so you can run it like this: ’npx swagger2adoc’ it takes the standard defaults or you can override see: https://github.com/mtho11/swagger2adoc for documentation. So this command just needs to be added to CI or at least the Makefile depending on what you want it to do.

> The main file is: https://github.com/mtho11/swagger2adoc/blob/master/src/index.ts

> To play with it in dev mode ‘/bin/run’ to generate the api-doc.adoc file.

**Comment by cfcosta** [comment]
@jshaughn perfect, will take a look at it.
