### ISSUE TITLE
Idle status taking precedence over degraded health status

### ISSUE THREAD

**Issue by israel-hdez** [kiali/kiali#3493]
**General remarks**

Applications list page show "Idle" status when there are Idle and unhealthy pods for an application <ins>with multiple versions</ins>:

![image](https://user-images.githubusercontent.com/23639005/100788967-717ffe00-33db-11eb-90f5-b67027a28275.png)

Notice there is only one unhealthy version and the other versions are idle. Notice the resolved overall health is "Idle" rather than "degraded", and the Idle icon is present in the Apps list.

Similar behavior is seen with Idle + Healthy versions: it shows "Idle" instead of a green checkmark.

Additional note: I noticed that also the Overview page it not giving any warning status. The issue may be related.

Workloads list page works as expected.

**Versions used**
Kiali: Latest master
Istio: 1.8-alpha.0
Kubernetes flavour and version: Kubernetes 1.18

**To Reproduce**
1. Deploy an application with multiple versions.
2. Kill a pod on one of the versions and go to the applications list page (making sure you do it before the killed pod is replaced).

You will see the Idle indicator instead of the Unhealthy status.

**Expected behavior**

* For case 1 (an unhealthy pod) I would expect to see the unhealthy status rather than an Idle status. I think, definitely, that the unhealthy status should take priority.
* For case 2 (idle versions and healthy versions) I'm not sure what to expect really. I would say "healthy" is the correct status to show, as the idle deployments are most likely intentional. But this is subject to discussion.

**Comment by lucasponce** [comment]
@israel-hdez I agree, this is a bug, it seems "iddle" workloads are not computed right on the App case.

**Comment by jshaughn** [comment]
@cfcosta if you run out of things to do during the break, take a look at this one.  If you can't get to it we can re-assign after the break, as typically this would probably be for jupiter.

**Comment by jshaughn** [comment]
@lucasponce , I'm unassigning @cfcosta as he was not able to get to this one during the shutdown.  Opening it up to be taken by anyone...

**Comment by jmazzitelli** [comment]
> * For case 2 (idle versions and healthy versions) I'm not sure what to expect really. I would say "healthy" is the correct status to show, as the idle deployments are most likely intentional. But this is subject to discussion.

Just to show what happens now, I see this:
![Screenshot from 2021-01-12 13-30-01](https://user-images.githubusercontent.com/2029470/104356851-722baa00-54da-11eb-8ce7-bf7e7f931922.png)

**Comment by jmazzitelli** [comment]
I have a feeling this is wrong - why is Idle and Failure both priority 3? Shouldn't Idle be a lower priority (lower than even Healthy? But certainly lower than Degraded and Failure (not equal to it). No?)

https://github.com/kiali/kiali-ui/blob/v1.28.0/src/types/Health.ts#L84-L98

**Comment by lucasponce** [comment]
> For case 2 (idle versions and healthy versions) I'm not sure what to expect really. I would say "healthy" is the correct status to show, as the idle deployments are most likely intentional. But this is subject to discussion.

I certainly I don't have a strong opinion on this case, I *personally* think that showing Idle is good, as it's the relevant info in an App that is not 100% healthy (all versions healthy).

Before to enter in terms discussions, to me goal is to give that info to the user ("hey, you have here an application with 3 controllers, but two of them don't have pods, perhaps it's intentional -> Idle").

**Comment by jmazzitelli** [comment]
See the PR I just submitted - the PR's description explains in further detail what fix is being proposed: https://github.com/kiali/kiali-ui/pull/2050

**Comment by jmazzitelli** [comment]
> showing Idle is good, as it's the relevant info in an App that is not 100% healthy (all versions healthy).

The proposed fix in [the PR](https://github.com/kiali/kiali-ui/pull/2050) will do this. Idle will still be above (in priority) "Healthy" (so if you have 3 that are healthy but one idle, then the global status will be considered idle). However, the fix will also ensure idle is NOT higher in priority than degraded or failure (so it fixes the original problem shown in the screenshots in this issue's description).
