### ISSUE TITLE
Building operator/helm fails to "git pull"

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#3500]
Probably for @jmazzitelli :

While I'm trying to pull @xeviknal 's work that spans across multiple repos (operator, helm-charts, core and ui), I get an error when running our make targets.

What I'm running:

```
CLUSTER_TYPE=minikube DORP=podman CONSOLE_LOCAL_DIR=/work/swsui CONSOLE_VERSION=local make clean build cluster-push operator-create kiali-create
```

At some point, a `git pull` is performed (see target `.ensure-helm-charts-repo-exists` in `Makefile.helm.mk`). This throws an error:

```
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>
```

Not sure if it's because of my version of git (it's 2.28.0), or because I have several remotes on this repo (as I always do, a `origin` and a `upstream`), but the build stops there. There's no problem when I'm on `master`.

I removed the `git pull` from the makefile and it works well. To be honest, it feels strange to pull code during a local build process, don't you think?

**Comment by jmazzitelli** [comment]
This is making sure your helm charts are up to date.

The solution is simple - just set your upstream in your helm-chart repo's PR branch - something like this:

```
git branch --set-upstream-to=jotak/your-helm-branch your-helm-branch
```

**Comment by jotak** [comment]
hmm that's still a problem. What if I need to get back to an old version and rebuild? It will pull master... that's a problem, no?

**Comment by jotak** [comment]
I mean, I understand the intent to have this as a convenience, but on the other hand it's really something I don't expect, while I'm building from my local files, that the build script will change my git state. Or perhaps there should be two different make targets (or env var), one for helm update and another for untouched helm.

**Comment by jmazzitelli** [comment]
I won't pull master - it only pulls the local branch (i.e. it doesn't checkout anything).

We can remove that `git pull` - I just fully expect people to complain "why isn't my stuff installing correctly?" - but I'll just point to this github issue :)

**Comment by jmazzitelli** [comment]
You know what we could do - instead of pulling, just check to see if you match what it up on the remote repo. If it doesn't match (or there is no upstream repo set), we can spit out a warning message, but continue with the build.

**Comment by jmazzitelli** [comment]
See PR https://github.com/kiali/kiali/pull/3501 that attempts to make this better.
