### ISSUE TITLE
Migrate Travis CI to Github Actions

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#3502]
**Is your feature request related to a problem? Please describe.**
We are currently facing issues with Travis CI (slow and go through our credits quickly)

**Describe the solution you'd like**
A clear option to try out is Github Actions for CI/CD. So this task would be to migrate our CI/CD to use Github Actions instead.

https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/migrating-from-travis-ci-to-github-actions

- [x] _Merged_ Add Github Actions CI to Kiali-ui repo
- [ ] _Review_ Add Github Actions CI to Kiali repo

**Comment by lucasponce** [comment]
This is a blocker task.
What's the status ?
