### ISSUE TITLE
The logs tab in Kiali 1.26 produces an error at istio 1.8

### ISSUE THREAD

**Issue by YuriyKrasilnikov** [kiali/kiali#3504]
If i install `kiali` with the recommended settings for `istio 1.8` it causes an error in the `logs` tab of any pod, if its logs are empty.

**Kiali Installation:**
`kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.8/samples/addons/kiali.yaml`

**Error:**
> TypeError: Cannot read property 'length' of undefined
    at a.n.hasEntries (main.45aa7d55.chunk.js:1)
    at a.n.getAppDiv (main.45aa7d55.chunk.js:1)
    at a.n.getSplitter (main.45aa7d55.chunk.js:1)
    at a.value (main.45aa7d55.chunk.js:1)
    at Fa (2.45dcf362.chunk.js:2)
    at Na (2.45dcf362.chunk.js:2)
    at gc (2.45dcf362.chunk.js:2)
    at us (2.45dcf362.chunk.js:2)
    at cs (2.45dcf362.chunk.js:2)
    at Zc (2.45dcf362.chunk.js:2)

**Versions used**
Kiali: 1.26-1.27
Istio: 1.8
Minikube: v1.15.1 on Microsoft Windows 10 Pro 10.0.19042 Build 19042
Kubernetes: v1.19.4 
Docker: 19.03.13

![Screenshot 2020-12-06 174954](https://user-images.githubusercontent.com/30294585/101330559-cb713f80-3883-11eb-8777-85c4583a5803.png)

**Comment by GabrielLasso** [comment]
I just realized that it happens here too

**Comment by jshaughn** [comment]
Thanks for reporting, we'll look into this one shortly.

**Comment by jshaughn** [comment]
The workaround is to update to a newer Kiali, it is fixed already in 1.27+.  The fix will be made to 1.26 and we will make a patch release such that 1.8 users will get the fix.

**Comment by jshaughn** [comment]
We have released Kiali v1.26.2 with the fix.   Istio 1.8 users installing Kiali as an addon should now be getting the updated version.
