### ISSUE TITLE
[operator] make istiod version endpoint configurable

### ISSUE THREAD

**Issue by BoOgatti** [kiali/kiali#3506]
**Is your feature request related to a problem? Please describe.**
As I found oprator have [hardcoded](https://github.com/kiali/kiali-operator/blob/master/roles/default/kiali-deploy/tasks/main.yml#L245) isiod name in URL, so if it not `istiod` endpoint checks will fail

**Describe the solution you'd like**
Make it configurable

**Comment by jmazzitelli** [comment]
> Make it configurable

It already is:

https://github.com/kiali/kiali-operator/blob/master/roles/default/kiali-deploy/tasks/main.yml#L251-L252

https://github.com/kiali/kiali-operator/blob/master/deploy/kiali/kiali_cr.yaml#L473

**Comment by BoOgatti** [comment]
Doh! My bad, excuse me
