### ISSUE TITLE
kiali integration  keycloak  authentication  failed

### ISSUE THREAD

**Issue by mengxifl** [kiali/kiali#3512]
**Versions used**
Kiali: v1.27.0
Istio: N/A
Kubernetes: 1.19

**To Reproduce**
1. about openid authentication 

2. I had a keycloak service . Had a realm name is Keycloak  Create a user test password 123456.  other screen 

![图片](https://user-images.githubusercontent.com/48743664/101499300-11272880-39a8-11eb-8b98-cbf75a4b6383.png)

![图片](https://user-images.githubusercontent.com/48743664/101502065-7892a780-39ab-11eb-9d42-d6bec6c4e993.png)

3.I  set a client 

![图片](https://user-images.githubusercontent.com/48743664/101499516-521f3d00-39a8-11eb-82da-1bf0eab50cd4.png)

![图片](https://user-images.githubusercontent.com/48743664/101499567-619e8600-39a8-11eb-89d8-3cdbec550e6e.png)

![图片](https://user-images.githubusercontent.com/48743664/101499683-8266db80-39a8-11eb-8b25-eac2cfbb766c.png)

4.  I run command 
```
curl --location \
--request POST 'http://10.130.147.239:8180/auth/realms/keycloak/protocol/openid-connect/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'client_id=user-token' \
--data-urlencode 'client_secret=1c302469-bf6d-4152-ad61-0964e158f55a' \
--data-urlencode 'grant_type=client_credentials'
```
show me 

```
{
    "access_token":"xxxxxx.........Too long to ignore content",
    "expires_in":300,
    "refresh_expires_in":1800,
    "refresh_token":"xxxxx.........Too long to ignore content",
    "token_type":"bearer",
    "not-before-policy":0,
    "session_state":"44f2d71c-f59e-4b10-939f-8e5e1fbd6761",
    "scope":"email profile"
}
```

5、I add a secret in k8s 
```
kubectl create secret generic kiali --from-literal="oidc-secret=1c302469-bf6d-4152-ad61-0964e158f55a" -n istio-system
```
config.yaml   file  content 

```
    auth:
      strategy: openid
      openid: 
        insecure_skip_verify_tls: true
        client_id: "user-token"
        disable_rbac: true
        issuer_uri: "http://10.130.147.239:8180/auth/realms/keycloak"
        scopes: ["openid", "profile", "email"]
```

```
kubectl exec -it kiali-7bcbdcbbf-887fs -n istio-system -- /bin/sh -c "cat /kiali-secret/oidc-secret"
1c302469-bf6d-4152-ad61-0964e158f55a
kubectl exec -it kiali-7bcbdcbbf-887fs -n istio-system -- /bin/sh -c "cat /kiali-configuration/config.yaml"
auth:
  strategy: openid
  openid:
    insecure_skip_verify_tls: true
    client_id: "user-token"
    disable_rbac: true
    issuer_uri: "http://10.130.147.239:8180/auth/realms/keycloak"
    scopes: ["openid", "profile", "email"]
....
....
kubectl delete pod/`kubectl get pods --all-namespaces | grep "kiali" | awk '{print $2}'` -n `kubectl get pods --all-namespaces | grep "kiali" | awk '{print $1}'`

wait kiali running
```

6、when I click login with OpenID
![图片](https://user-images.githubusercontent.com/48743664/101501309-8c89d980-39aa-11eb-91b9-3aab2ea17251.png)

```
http://10.130.147.239:8180/auth/realms/keycloak/protocol/openid-connect/auth?client_id=user-token&response_type=id_token&redirect_uri=http%3A%2F%2F10.130.147.180%3A20001%2Fkiali&scope=openid+profile+email&nonce=8cc3b7183c72982b8c14f5093aa0abc60ecd526d629462a1ed8f654e&state=bb04dc1e9b793fda726c842cb99b04634121319f6abd1a08c1a40954-201208151100
```

![图片](https://user-images.githubusercontent.com/48743664/101501459-b9d68780-39aa-11eb-928d-2b8e3492664b.png)

It not work . Is a bug ? Or do I have something unconfigured ？

Is there any  kiali integration  keycloak   tutorial  ？I found every where.

**Comment by lucasponce** [comment]
cc @israel-hdez

**Comment by jshaughn** [comment]
cc @cfcosta

**Comment by israel-hdez** [comment]
In the client settings, I see that the **Valid Redirect URIs** field has the KeyCloak URL. That looks wrong. I think it should be the Kiali URL.

**Comment by mengxifl** [comment]
> 
> 
> In the client settings, I see that the **Valid Redirect URIs** field has the KeyCloak URL. That looks wrong. I think it should be the Kiali URL.

Your mean I need set like this ?

![图片](https://user-images.githubusercontent.com/48743664/101715555-a3c5e580-3ad6-11eb-91c8-e7fba42937ff.png)


-----------------------------
```
My kiali url is 
http://10.130.147.180:20001/
```
![图片](https://user-images.githubusercontent.com/48743664/101716824-12a43e00-3ad9-11eb-8919-cd538a924f7e.png)
-----------------------------
same error again
-----------------------------
![图片](https://user-images.githubusercontent.com/48743664/101718093-80ea0000-3adb-11eb-98ec-09297b54c2e6.png)
-----------------------------
if I set like this  
-----------------------------
![图片](https://user-images.githubusercontent.com/48743664/101716930-4717fa00-3ad9-11eb-9d4e-11e9172369a8.png)
-----------------------------
or this  set like this
-----------------------------
![图片](https://user-images.githubusercontent.com/48743664/101717086-98c08480-3ad9-11eb-92ce-a289916cb325.png)
-----------------------------
web jump to a new URL 
To make it easier to watch, I've cut this URL into rows by parameter

```
http://10.130.147.239:8180/auth/realms/keycloak/protocol/openid-connect/auth?client_id=user-token
&response_type=id_token
&redirect_uri=http%3A%2F%2F10.130.147.180%3A20001%2Fkiali
&scope=openid
&nonce=0c2ee35a022ba5eecfbc3f659ae6ef71f5a6d41260a7634650ffa881
&state=58803f848d68ca529f37becb29ab919918b947b1bed277407b03a755-201210031359
```

And I  some found error when I click  <Login In With OpenID> butten.
-----------------------------
![图片](https://user-images.githubusercontent.com/48743664/101717486-50ee2d00-3ada-11eb-9840-bfb35f134d23.png)
-----------------------------
there are some error in keycloak 
-----------------------------
![图片](https://user-images.githubusercontent.com/48743664/101717635-a0345d80-3ada-11eb-9ac2-d91caa8cb685.png)
----------------
Sorry . I forgot to tell you about my kubernetes info. Maybe it doesn't matter

1、I buid k8s with kubeadm
2、k8s RBAC is enabled
3、I run calico CNI and BPG IPINIP modle.

**Comment by israel-hdez** [comment]
@mengxifl How did you install Kiali?

I see that Keycloak is logging an error about "implicit flow" is disabled, which is right, because in the client settings I see this:

![image](https://user-images.githubusercontent.com/23639005/101810575-94e33100-3ade-11eb-9338-4998888b729a.png)

Apparently, given your current Kiali configuration, you need to turn on that option.

**Comment by israel-hdez** [comment]
@mengxifl Also, I'm unsure if Keycloak will accept a non-secure url (i.e. a plain HTTP url rather than HTTPS). I'm not familiar with Keycloak. I think you may find this information on Keycloak docs.

**Comment by mengxifl** [comment]
> 
> 
> @mengxifl How did you install Kiali?
> 
> I see that Keycloak is logging an error about "implicit flow" is disabled, which is right, because in the client settings I see this:
> 
> ![image](https://user-images.githubusercontent.com/23639005/101810575-94e33100-3ade-11eb-9338-4998888b729a.png)
> 
> Apparently, given your current Kiali configuration, you need to turn on that option.

It done . I will give some screen in this issue holp they can help other .  thank you .

**Comment by mengxifl** [comment]
Last is config setp .

------------------
1、First you need setup a  keycloak . then use docker run it . In my evn ,I found a some error . Probably due to a storage problem .So  recommended that you use external storage

ps: This assumes that you have a mysql database .  create a  db name keycloak .and you had power access this db

command
```
docker run -d -p 0.0.0.0:8180:8080 --name=keycloak \
-e KEYCLOAK_USER=admin \
-e KEYCLOAK_PASSWORD=admin \
-e DB_VENDOR=mariadb \
-e DB_ADDR=<mysqlhost> \
-e DB_PORT=<mysqlport> \
-e DB_DATABASE=keycloak \
-e DB_USER=<user> \
-e DB_PASSWORD='<password>' \
jboss/keycloak
```

2、access keycloak running host IP with 8180 port .
2.1 create a test realm named Keycloak

![图片](https://user-images.githubusercontent.com/48743664/101856801-01beff80-3ba1-11eb-9139-ccb0ad2d27be.png)

2.2 create a client that client kiali will use . 

![图片](https://user-images.githubusercontent.com/48743664/101856946-56fb1100-3ba1-11eb-9539-a06615efda7b.png)

2.3 Write down the Secret

![图片](https://user-images.githubusercontent.com/48743664/101857029-8c076380-3ba1-11eb-8db1-3ca68890045b.png)

2.4 create a user  

![图片](https://user-images.githubusercontent.com/48743664/101857155-d688e000-3ba1-11eb-9420-095eb89f4708.png)

change password 

![图片](https://user-images.githubusercontent.com/48743664/101857232-03d58e00-3ba2-11eb-8250-f6caca1bed46.png)

3、edit kiali.yaml file . I use istio 1.8.0  unzip  istio package . this file in
 
istio_unzip_dir/samples/addons/kiali.yaml

find code near . 
```
strategy: anonymous
````
change block code to your evn 

![图片](https://user-images.githubusercontent.com/48743664/101858186-0b963200-3ba4-11eb-93bf-fdb159bae217.png)

4、I'm just testing it, so I edit this file service .

![图片](https://user-images.githubusercontent.com/48743664/101858366-6c256f00-3ba4-11eb-94d8-1a2a4d337b2a.png)

5、kubectl apply --filename=istio_unzip_dir/samples/addons/

6、access your k8s node IP with 20001 .

![图片](https://user-images.githubusercontent.com/48743664/101858465-9ecf6780-3ba4-11eb-9b78-a7a369f4e539.png)

7、click this butten . 

8 、input you set username and password 

![图片](https://user-images.githubusercontent.com/48743664/101858544-c58d9e00-3ba4-11eb-8f22-04866eb2e7f5.png)

enjoy

**Comment by sergiomacedo** [comment]
Hello  @mengxifl. I did all of your very detailed configuration but what I got was:

Login unsuccessful: Token is not valid or is expired

I saw a related issue at 

https://github.com/kiali/kiali/issues/3042

but, as far as I understood, it doesn't apply to my case because kiali's service account is able to list the namespaces...

$ k auth can-i get namespaces --as=system:serviceaccount:istio-system:kiali  -n keycloak
Warning: resource 'namespaces' is not namespace scoped
yes

Do you have any suggestion on this scenario?

Thanks in advance.

**Comment by subodh-net** [comment]
I tried all the steps mentioned as above and it was failed after userid and passwor
![Kiali page 1](https://user-images.githubusercontent.com/61268073/124393851-25eb5500-dd1a-11eb-88dd-eed93ecd72e1.JPG)
![Kiali page 2](https://user-images.githubusercontent.com/61268073/124393852-271c8200-dd1a-11eb-8464-89f0ed21edf9.JPG)
![Kiali page 3](https://user-images.githubusercontent.com/61268073/124393853-27b51880-dd1a-11eb-8d69-e07434600295.JPG)
![Kiali page 4](https://user-images.githubusercontent.com/61268073/124393854-27b51880-dd1a-11eb-9cbb-1654b8591534.JPG)
![Kiali page 5](https://user-images.githubusercontent.com/61268073/124393855-284daf00-dd1a-11eb-9d0b-3fa5254b1b4c.JPG)
![Kiali page 6](https://user-images.githubusercontent.com/61268073/124393856-28e64580-dd1a-11eb-8ef3-5a381b2e464a.JPG)
d

**Comment by subodh-net** [comment]
kubectl create secret generic kiali --from-literal="oidc-secret=45b18d43-e599-4ee3-b39d-b28197d089f2" -n istio-system

**Comment by subodh-net** [comment]
auth:
     # openid: {}
     # openshift:
     # client_id_prefix: kiali
      strategy: openid
      openid:
        client_id: "kiali-client"
        insecure_skip_verify_tls: false
        disable_rbac: true
        issuer_uri: "https://192.168.1.240/auth/realms/Kiali"
        scopes: ["openid","email"]
        username_claim: "sub"

**Comment by subodh-net** [comment]
![Uploading JWT 1.JPG…]()

**Comment by subodh-net** [comment]
![JWT 1](https://user-images.githubusercontent.com/61268073/124393959-c477b600-dd1a-11eb-8d02-3cf1d0e7e626.JPG)

**Comment by israel-hdez** [comment]
@subodh-net This issue is half-a-year old. Preferably, open a new discussion: https://github.com/kiali/kiali/discussions/new

Please, tell what Kiali version you are using.

**Comment by ramesh-krishnan-metro** [comment]
In 2022, I tried to configure kiali with keycloak. it worked with the same configurations as @subodh-net
