### ISSUE TITLE
Jaeger client: switch to gRPC/protobuf

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#3514]
See https://www.jaegertracing.io/docs/1.19/apis/#grpcprotobuf-stable

I hope to see better perfs when switching to grpc (to be measured). If this is the case, it could probably enable a couple of enhancements (e.g. spreading traces over more interval via split/join, see https://github.com/kiali/kiali/issues/3311 )

By the way, the currently used HTTP/json api is supposed to be for jaeger internal use only.

**Comment by aljesusg** [comment]
I thought about that....and about moving kiali api to grpc (throw a ball ;)) to improve it... +1 on this if we can do it

**Comment by lucasponce** [comment]
I'm not against to introduce gRPC clients in the backend Kiali query, but I won't mix that with the other backends (prometheus, kubernetes).

> By the way, the currently used HTTP/json api is supposed to be for jaeger internal use only.

Yes, this was somehow discussed with Jaeger team, being Kiali responsible to adapt potential changes.

**Comment by aljesusg** [comment]
> I'm not against to introduce gRPC clients in the backend that Kiali queries, but I won't mix that with the other backends (prometheus, kubernetes).
> 
> > By the way, the currently used HTTP/json api is supposed to be for jaeger internal use only.
> 
> Yes, this was somehow discussed with Jaeger team, being Kiali responsible to adapt potential changes.

That's right...maybe we should create somekind of check fro that...I am thinking in a github action to check if jaeger https endpoints and model that we are using change...
