### ISSUE TITLE
Error while loading workloads from istio-system

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#3515]
Happens on Kiali master.

Open any worload details page from istio-system, errors are shown in toolbar.
![Screenshot from 2020-12-09 13-52-38](https://user-images.githubusercontent.com/604313/101632295-feebcf80-3a25-11eb-8901-0ffdbf0eb0e4.png)

**Comment by jotak** [comment]
@xeviknal is it expected that the config_dump is performed while entering on workload details page? so without explicitly asking to see the dump?

**Comment by xeviknal** [comment]
@jotak that is the point, nope. It should be triggered only when opening the modal, not before.
The bug is that the component is rendered when rendering the details page but is not shown. It has to trigger the fetch on opening the modal.
