### ISSUE TITLE
Graph should make show 'idle' edges a display option (default = false)

### ISSUE THREAD

**Issue by jshaughn** [kiali/kiali#3519]
The Kiali graph opts to show idle edges (i.e. edges with no traffic for the time period), as long as the source and destination nodes are valid (i.e. are backed by Istio config).   The rationale for doing it this way is the belief that it's beneficial for users to see pathways that have had traffic in the past but for some reason no longer have traffic, as maybe that could indicate an issue.  But the reality is, far more often than not, that these idle edges represent obsolete pathways, or bad edges generated by unexpected telemetry.  And these edges can significantly degrade the graph layout.

I think the default behavior should be to show cleaner graphs by default.  This RFE is to make the rendering of idle edges configurable, and by default to not show them.  We do already have the ability to hide idle edges using a `!traffic` graph hide.  This would be like having that hide feature built in.   Going forward the !traffic show/hide expression would be useful only when `show idle edges` is enabled.

**Comment by jmazzitelli** [comment]
That sounds reasonable.
