### ISSUE TITLE
Pod table should reflect any container crash

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#3529]
There is some gap/bug in the Pod status.

Health is calculated correct as information comes from the controller in an accurate way:

![image](https://user-images.githubusercontent.com/1662329/102208952-64c9d280-3ed0-11eb-8484-8d08811f2db5.png)

But Pod table it seems incorrect and it should also reflect some sort of sync status with the controller one.

```
$ kubectl get pods -n travel-portal
NAME                            READY   STATUS             RESTARTS   AGE
loadbalancer-6b8786664c-rnxcj   1/2     CrashLoopBackOff   4          3m
travels-55c99f4cd8-vn7n6        2/2     Running            2          10m
viaggi-58f74fd7b-z8sbg          2/2     Running            1          10m
voyages-5d6fd69f9f-j4smx        2/2     Running            2          10m
```

We are getting the Pod Phase, which is ok, but it should check if any of the containers have a problem.

Kiali shouldn't dig too much, health information is ok, but this gap between health (pod status - correct) and pod table is a bug.

**Comment by lucasponce** [comment]
I changed from "bug" to "enhancement" but it's still valid.
Workload's pod table shouldn't add too much details but I think the summary of the containers (and perhaps the restarts) can be collected in the same operation and that would add more info in such scenarios.

**Comment by lucasponce** [comment]
Incorporated by https://github.com/kiali/kiali-ui/pull/2122

**Comment by lucasponce** [comment]
@hhovsepy this issues is still valid, but scope should be adapted to the recent changes.

So goal should be to reflect a warning in the pod status in case that a pod has a N/M container status where N < M, typically the pod is in "running" phase but is not healthy.

I think this should be reflected with a tooltip in the Pod table:

![image](https://user-images.githubusercontent.com/1662329/120181621-9e3b9380-c20d-11eb-98f0-9818d4437665.png)

I wouldn't go too far, as Pod/Workload management is a primary feature of kubernetes consoles, but at least to show in Kiali that a Pod may have problem (typically the app container is healthy but not the sidecar container, or similar).

We can comment the details of the scope, but this one could be a good one to start looking at the backend + frontend model.

**Comment by hhovsepy** [comment]
PRs merged.
