### ISSUE TITLE
Sorry, there was a problem. Try a refresh or navigate to a different page. - with Argo Rollouts

### ISSUE THREAD

**Issue by arturrez** [kiali/kiali#3532]
**Describe the bug**
I am getting "Sorry, there was a problem. Try a refresh or navigate to a different page." when click on ArgoRollouts object in Kiali UI

**Versions used**
Kiali UI 1.27.0 (8f8d4c0730857d7a25bd2ae613f0bff419e50e28)
Kiali Server v1.27.0 (f78420fc6e0cf565944d714ee92523e0642ca3e8)
Kiali Container v1.27.0
Components
Istio 1.7.4
Prometheus 2.22.1
Kubernetes v1.17.13-gke.2001

**To Reproduce**
1. Go to Workloads
2. Click on some Rollou Object
3. See error above

**Expected behavior**
I expect to see details for Rollout object similar what I see for deployment object

**Screenshots
![2020-12-15_18-14](https://user-images.githubusercontent.com/56270896/102296517-57c5d700-3f02-11eb-8712-e10c16602b8a.png)
![2020-12-15_18-19](https://user-images.githubusercontent.com/56270896/102296520-598f9a80-3f02-11eb-8758-64b7f471523d.png)

**
![2020-12-15_18-13](https://user-images.githubusercontent.com/56270896/102296482-48df2480-3f02-11eb-83d5-7c12a27480fc.png)

**Comment by lucasponce** [comment]
Thanks @arturrez for the issue.
Yes, probably it's a bug when the controller is in rollout status.

**Comment by lucasponce** [comment]
Ok, "Argo Rollout" [1] is a custom controller provided by Argo api "argoproj.io/v1alpha1" so, Kiali can't get details of this controller at the moment. On this case, the controller info is infered from the Pod and probably can't get all details that a Deployment should provide (i.e. status of desired controllers).

I will review if in this case what is the best strategy, but yes, we will fix this error, as minimum it shouldn't fail when accessing to the details.

[1] https://argoproj.github.io/argo-rollouts/#how-does-it-work

**Comment by ahsanqaisar** [comment]
Hi there - I recently deployed Kiali v1.31. The workload is appearing fine but it is giving the same issue under the Application tab. 

![image](https://user-images.githubusercontent.com/73361295/111342324-bb21eb00-8650-11eb-906d-d37a64822e44.png)

Thought anyone?

**Comment by jmazzitelli** [comment]
> Thought anyone?

Suggest you start a new Discussion, as this issue has been closed and you provided no detailed description so we don't want to assume it is related to this issue.
Create [a Discussion here](https://github.com/kiali/kiali/discussions) and provide all details that you think are important (what application? what cluster type? any logs in the Kiali server pod? etc etc etc)

**Comment by ahsanqaisar** [comment]
Absolutely! let me do that. Thanks!

**Comment by pantianying** [comment]
The same problems still exist when we use our own controller 
![image](https://user-images.githubusercontent.com/20589945/140287799-65d65017-422d-44ea-8917-d7b44b676abc.png)
![image](https://user-images.githubusercontent.com/20589945/140287834-7a3977b1-a2b7-4dea-9a8f-2090e4552d70.png)

**Comment by lucasponce** [comment]
@pantianying could you test with master or Kiali 1.41 ?
There was a couple of related PR https://github.com/kiali/kiali/pull/4360 that addressed the problems with custom controllers that probably won't be available in Kiali 1.36.

**Comment by jshaughn** [comment]
@pantianying Any results?
