### ISSUE TITLE
Add tooltip on "Missing Sidecar" message

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#3535]
Istio uses annotations to add additional info related Envoy config or update status of the proxy [1].

Kiali uses these annotations to detect some of the status, one scenario is to check if the proxy sidecar was succesfully injected (and connected with the control plane).

It happens that if an external webhook overwrites these annotations, it may cause side effects into the proxy and Kiali (i.e. showing a "missing sidecar" message in Kiali, or just ignoring some annotations in the control plane).

So, Kiali can't dig if there are other webhooks in place doing this, but probably it can be an easy step to add a tooltip with extra information about this potential problem.

[1] https://istio.io/latest/docs/reference/config/annotations/

**Comment by jshaughn** [comment]
Very much like this sort of help, similar to what @xeviknal did recently with respect to giving a tip to the user when no Istio components are found.  Adding to backlog.

**Comment by jshaughn** [comment]
Adding to sprint for someone to pick up, should be easy and potentially useful.
