### ISSUE TITLE
Kiali Release Notification Messages hard to read on OS/X

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#3538]
**General remarks**
The Kiali-bot Notification messages are barely readable on a OS/X Mac.
Seems readable elsewhere.

![image](https://user-images.githubusercontent.com/1312165/102640749-d17ee000-410f-11eb-8851-034baf426ea3.png)

Thanks Tiago for finding this.

**Comment by mtho11** [comment]
This is where the notification message is created: Here is the HTML for the release: https://github.com/kiali/kiali-bot/blob/master/src/data/ReleaseNotificationMessages.ts#L19-L72

Thanks @israel-hdez for the tip

**Comment by jshaughn** [comment]
Closing as stale.
