### ISSUE TITLE
Proxy status not reporting when cache is disabled

### ISSUE THREAD

**Issue by bougyman** [kiali/kiali#3539]
Due to an issue with our kiali (https://github.com/kiali/kiali/issues/3537), we have to deploy with cache disabled. Once doing so, we noticed that all of our applications are showing unsynced proxy status / degraded in the UI. In the logs, I see
```
2020-12-18T18:00:10Z WRN Kiali has not [istio-system] namespace cached. It is required to fetch Istio Status correctly
```
Which leads me to believe that disabling the cache is reponsible for the misreporting status of the proxies.

I also found #3318 and #3508 which have the same proxy status issue, but we do not seem to meet either of those conditions.

**Versions used**
Kiali: 1.28.0
Istio: 1.6.9
Kubernetes flavour and version: GKE 1.17

**To Reproduce**
1. Disable cache in the kiali cr with
```
kubernetes_config:
  cache_enabled: false
```
2. Go to the UI after this cr has deployed
3. Click on 'Applications'
4. In the 'Health' column, apps should have a yellow yield sign, hover over that to see that the proxy status shows unsynced

**Expected behavior**
As istioctl ps shows all proxies synced, these degraded icons and messages should not show up, it should be green and show the proper proxy status.

**Comment by jmazzitelli** [comment]
cc @lucasponce
