### ISSUE TITLE
All apps are degraded due to unsynced proxies when using different istio labels than app/version

### ISSUE THREAD

**Issue by xeviknal** [kiali/kiali#3543]
>I have the same issue[1] because I changed the istio_labels config parameter to use app.kubernetes.io/name instead of app for the app label key.
>
>The issue occurs because Kiali now expects the istiod pod to have the app.kubernetes.io/name=istiod label. However, istiod is deployed with app=istiod and there is no way to change that configuration using the Istio operator.

from https://github.com/kiali/kiali/issues/3508#issuecomment-748057812

[1] All apps are degraded due to unsynced proxies

**Comment by xeviknal** [comment]
@jshaughn you mentioned that this is an issue for the istio operator. What do we expect from istio to change? As a final result, do we want the istio deployments to have an custom `app` label there?

I am having two ideas for a workaround in kiali:
1. Hardcode the app_label to "app".
2. Add a new config in kiali: "spec.external_components.istio.app_label" where the "app" label is defined for the istio components.

Wdyt?

**Comment by jshaughn** [comment]
> What do we expect from istio to change?

I guess I thought that Istio should be more flexible and let the user configure the label, or possibly apply both the 'app' and the standard k8s label.  I don't think they want to force the use of the `app` label for istiod.   But that won't solve the issue in the near-term.

I guess the hardest thing is knowing when we need to ignore our configured app label name and use either the hard coding or the proposed new config.  I guess I'd suggest we take the easier route, hard code it for this use case, and possible backport to 1.28 and make an upstream release to help these users immediately.  At the same time, create an Istio issue (or PR) to resolve the problem on their side.

**Comment by xeviknal** [comment]
Closing the issue per https://github.com/kiali/kiali/pull/3544
