### ISSUE TITLE
Kiali setup in Istio Multi primary setup

### ISSUE THREAD

**Issue by chaitanyasaig** [kiali/kiali#3553]
**Is your feature request related to a problem? Please describe.**
In Multi primary setup of Istio1.8 version, as all the clusters will have the primary component of istio, We want to see graphs from edge cluster using the Kiali dashboard on Primary cluster

**Describe the solution you'd like**
If we can see the graphs of edge cluster from the primary cluster Kiali dashboard, flexibilty, ease of use, and edge will be more reliable. 

**Describe alternatives you've considered**
In our current setup, Istio Multi Primary setup, We have installed the Kiali on each and every cluster and individually accessing the Kiali dashboard seperately.

**Additional context**
What we have done in brief is,

> Step1 : From Rancher We have Setup the kubernetes clusters.

Step2 : On Two clusters, Istio multi primary is setup is done with version 1.8

[https://istio.io/latest/docs/setup/install/multicluster/multi-primary_multi-network/](url)

Step3 : Installed rancher monitoring and Kiali on both clusters, We are able to see the graphs of the application which is installed on individual clusters in Kiali dashboard.
Kiali Documentation: [https://kiali.io/documentation/latest/features/#_multi_cluster_support](url)

Now the issue is, We are not able to view the details related to second cluster from the first cluster’s Kiali dashboard.

Does anyone tried this use case to view all the application graphs from neighbour clusters using one Kiali dashboard.

If So, Could you please help me to achieve this 

>

**Comment by jmazzitelli** [comment]
I think this would be better placed in our new Kiali Github Discussions: https://github.com/kiali/kiali/discussions

**Comment by israel-hdez** [comment]
Answering on e-mail thread: https://groups.google.com/g/kiali-users/c/3zp_leFUxQk/m/P8qCnoFUCAAJ.

Sorry for replying late. Most of the team took an end-of-year break.
