### ISSUE TITLE
Phone icon

### ISSUE THREAD

**Issue by carlosmonzon2008** [kiali/kiali#3560]
Hello, 

I have been trying out Istio. I see a phone icon that is not mentioned in the legend of Kiali, and after a while investigating on Internet I haven't found what does it mean.

![image](https://user-images.githubusercontent.com/13509588/103698658-f09bbf80-4fa1-11eb-86ad-4b4f564bdea7.png)

I have contacted Kiali on Twitter first, and they told me to open an issue here, because it appears to be a bug.

Thank you very much.

**Comment by jmazzitelli** [comment]
That's pretty funny. Probably something to do with ASCII codes or something not mapped to what is expected.

What is your browser, operating system, and locale/language you are using to run the Kiali UI?

**Comment by jshaughn** [comment]
To be clear, the phone icon is not used in Kiali, it has no meaning.  It seems like a rendering issue and probably should be a lock or unlock icon, representing mTLS or no mTLS and is probably linked to the `Security` display option.  Try clearing your browser cache.

**Comment by carlosmonzon2008** [comment]
> That's pretty funny. Probably something to do with ASCII codes or something not mapped to what is expected.
> 
> What is your browser, operating system, and locale/language you are using to run the Kiali UI?

Yes, that's really funny.

My browser:
Firefox 78.6.0esr (64-bit)

Operating System:
Linux debian 4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64 GNU/Linux

Locale:
$ **locale -a**
C
C.UTF-8
es_ES.utf8
POSIX

The language is spanish.

**Comment by jmazzitelli** [comment]
FWIW: here's the mTLS lock icon stuff that I could find - I suspect something here is not rendering properly??

https://github.com/kiali/kiali-ui/blob/v1.28.0/src/components/CytoscapeGraph/graphs/GraphStyles.ts#L381

https://github.com/kiali/kiali-ui/blob/v1.28.0/src/components/CytoscapeGraph/graphs/GraphStyles.ts#L36-L37

**Comment by jmazzitelli** [comment]
@carlosmonzon2008  go here and search for "pf-icon-locked" - see what your browser shows you: https://pf4.patternfly.org/icons/

**Comment by carlosmonzon2008** [comment]
> locked

![image](https://user-images.githubusercontent.com/13509588/103701989-d7494200-4fa6-11eb-84ee-bf0634c9c91e.png)
![image](https://user-images.githubusercontent.com/13509588/103702176-e3cd9a80-4fa6-11eb-9163-0e72eb10997e.png)


Despite this proof that you have asked me appears to be fine in my browser, it does seem to be a problem with my Firefox. 
I tried in Chromium [Version 87.0.4280.88 (Build for developers) built on Debian 10.7, running on Debian 10.7 (64 bits)], and I don't see the phone icon.

**Comment by carlosmonzon2008** [comment]
It is a problem with my Firefox that for some reason it not showing the right icon in Kiali, despite that it shows the right icons on this website:
https://pf4.patternfly.org/icons/
