### ISSUE TITLE
Allow the client_id for OpenID auth to be set in the same secret as the client_secret

### ISSUE THREAD

**Issue by diranged** [kiali/kiali#3563]
**Is your feature request related to a problem? Please describe.**
It's inconsistent right now that we must set the Oauth2 Client ID in the `spec.auth.openid.client_id` field, but we set the Client Secret in a special Secret resource. 

**Describe the solution you'd like**
If we're creating a Secret resource anyways (and there are lots of secure ways for people to store these values in outside datastores or do things like encrypt them with KMS or Vault), we would like to see the client_id and client_secret values both pulled from a single Secret.

**Describe alternatives you've considered**
For now we are hard-coding the client-id in the Kiali CR - but it's not ideal because we are now storing this value in two places (our secret management service, AND the template for our Kiali CR).

**Comment by israel-hdez** [comment]
The `client_id` is in the Kiali CR because it's public. So, it didn't make sense to put it in a secret.

What we currently have is OK, so I don't think this will be implemented soon. So, I encourage you to contribute with the code to implement this, if you need it sooner than later.

**Comment by jshaughn** [comment]
Closing as stale.
