### ISSUE TITLE
Unable to fetch app details for cronjob

### ISSUE THREAD

**Issue by kevin-shelaga** [kiali/kiali#3569]
**Describe the bug**
Cronjobs show correctly in graph, but no corresponding workload captured. Right clicking -> Details from graph results in "Could not fetch App Details." App.Kiali "my-cronjob" not found

**Versions used**
Kiali: v1.28.1
Istio: 1.8.1
Kubernetes flavour and version: v1.17.14-gke.400

**Comment by jshaughn** [comment]
This is configurable, See 
https://github.com/kiali/kiali-operator/blob/master/deploy/kiali/kiali_cr.yaml#L685-L694

**Comment by kevin-shelaga** [comment]
@jshaughn since the values are all commented out by default, and uncommenting them would definitely exclude them, or am i missing the intent of the setting? It seems like by default cronjob an job details should be collected.

```yml
# List of controllers that won't be used for Workload calculation.
# Kiali queries Deployment,ReplicaSet,ReplicationController,DeploymentConfig,StatefulSet,Job and CronJob controllers.
# Deployment and ReplicaSet will be always queried, but ReplicationController,DeploymentConfig,StatefulSet,Job and CronJobs
# can be skipped from Kiali workloads query if they are present in this list.
#    ---
#    excluded_workloads:
#    - "CronJob"
#    - "DeploymentConfig"
#    - "Job"
#    - "ReplicationController"
```

**Comment by jshaughn** [comment]
Those commented out values show the default setting.  You'd likely want to set to:
excluded_workloads:
- "DeploymentConfig"
- "Job"
- "ReplicationController"

**Comment by jmazzitelli** [comment]
> since the values are all commented out by default

To understand this example CR file, see the comment at the top: https://github.com/kiali/kiali-operator/blob/master/deploy/kiali/kiali_cr.yaml#L14-L19

```
# This is actually an empty Kiali CR, however, it provides
# documentation on all available settings.
# In each documented section, you will see a "---" marker;
# below that marker you will see the names of the settings along
# with their default values. If the setting is not defined by
# default, its name will be prefixed with "#".

So the values you see are the defaults - in other words, the default for this `excluded_workloads` setting will exclude those you see in the example CR (and that includes CronJob).
```

**Comment by kevin-shelaga** [comment]
Ok, I understand now. Thank you. I have updated my configmap and restarted the pod. Still no details are returned.

```yml
kubernetes_config:
  cache_enabled: false
  excluded_workloads:
  - "DeploymentConfig"
  - "Job"
  - "ReplicationController"
```

note: cache disbaled due to [3494](https://github.com/kiali/kiali/issues/3494)

**Comment by lucasponce** [comment]
Note that "CronJob" also is the parent of "Job", so both should be included.

**Comment by kevin-shelaga** [comment]
@lucasponce Thank you, that did the trick!

**Comment by jshaughn** [comment]
@lucasponce Recommend we generate a FAQ entry for this relatively common question.
