### ISSUE TITLE
More friendly error messages in OIDC authorization-code flow

### ISSUE THREAD

**Issue by israel-hdez** [kiali/kiali#3574]
When Kiali is using the `authorization code` flow, authentication errors are outputted as raw JSON to the browser. This should be displayed in a more user-friendly way, probably by booting the UI and showing the error message next to the "Log in" button, as happens with other auth methods and even as happens with openid auth with `implicit flow`.

This was noted in the following GitHub discussion: https://github.com/kiali/kiali/discussions/3557#discussioncomment-265913_

**Comment by jshaughn** [comment]
@israel-hdez Is this still something you want to do?  If so feel free to assign yourself and add to sprint.

**Comment by israel-hdez** [comment]
@jshaughn Yes, adding it.
