### ISSUE TITLE
confusing "idle" UI components

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#3576]
I just wasted 30 minutes of time trying to figure out why my UI was behaving "wrong" - and it turns out it is "as expected" but is very confusing. I suggest we get a UX discussion around this because if it confuses me, it will confuse users.

I'm working on this [issue](https://github.com/kiali/kiali/issues/3493). I need to get some idle components in my mesh. I was looking at my graph in the graph UI page and I did have both idle nodes and idle edges showing in the graph. Great! That's what I need. So I then went to the Apps and Workload list pages and to my surprise I did not see any "Idle" components. I could not figure why the UI was showing different statuses in different pages.

Well, it turns out (after talking to some people) that the word "idle" is overloaded and means different things *depending on which UI page you are looking at*. This is extremely confusing. On the graph page, an "idle" component means there is no traffic (i.e. based on Istio telemetry). In the App and Workload pages, "idle" component means a Deployment has been scaled down to 0 (i.e. based on kubernetes config). To be specific (and to illustrate my confusion), if a Deployment is scaled to 1 pod, but that pod has no telemetry, it is considered "idle" in the graph but is NOT considered "idle" in the app or workload screen.

This is a problem because we are calling a component idle in one UI page but not calling it idle in other UI pages - thus, this is confusing to a user who may not understand what is going on (as I can personally attest because it confused me).

We need to move away from overloading the word "idle" here. My suggestion is to reword the "idle" options in the graph to be "quiet". In other words, call them "quiet nodes" and "quiet edges". This will move away from using the word "idle" that has a different definition in the graph page versus everywhere else.

Screenshots:

Here's the graph, app, and workload images - the graph shows all grey "idle" edges/nodes but the apps and workloads are all green.

![3-graph](https://user-images.githubusercontent.com/2029470/104359108-4958e400-54dd-11eb-943f-2130604a4069.png)
![2-workloads](https://user-images.githubusercontent.com/2029470/104359109-4958e400-54dd-11eb-95b3-f7b44986e3cc.png)
![1-apps](https://user-images.githubusercontent.com/2029470/104359111-49f17a80-54dd-11eb-9bcc-e53a2328a3b9.png)

But now if I scale down the deployment for reviews, the health shows "idle". The problem I have is the term being used here ("idle") is the same as that of the graph, but they clearly mean two very different things ("a deployment is scaled down to 0 pods" vs. "pods exist but have no telemetry associated with them").

![image](https://user-images.githubusercontent.com/2029470/104359385-976de780-54dd-11eb-9fc2-6d99ad012544.png)
![image](https://user-images.githubusercontent.com/2029470/104359446-abb1e480-54dd-11eb-8a23-a86ee6a1db29.png)
![image](https://user-images.githubusercontent.com/2029470/104359519-c3896880-54dd-11eb-9bb8-5eef59cce10a.png)

**Comment by jotak** [comment]
hey @jmazzitelli , I opened this issue a while ago, I think this is pretty much the same thing (except I didn't notice the inconsistency with the graph) : https://github.com/kiali/kiali/issues/2949

**Comment by jotak** [comment]
well, your suggestion is to use a different name, whereas what I suggested would be more to align the two concepts between graph and health. So, there's different possible solutions for the issue.

**Comment by jmazzitelli** [comment]
I am not married to a particular solution - my main point is simply we have an inconsistency in the Kiali UI with how we define "idle" that I think should be fixed. In one page, it means one thing; but in another page, it means something different and the UI becomes confusing due to this inconsistency. We need to either (a) make the "idle" components consistent across all UI pages or (b) simply change the names so one is called "idle" and the other is called something different.

I suggested (b) because it is the simplest solution that can be done in an hour - just change the category name string from "idle" to something else (e.g. "quiet") in the graph. But if we want to do something more like what you suggest in https://github.com/kiali/kiali/issues/2949 then that is good, too. As long as we are consistent with what we mean when we say "component X is idle" - that is what my concern was here in this issue.

**Comment by lucasponce** [comment]
I think this discussion happened as well between @jshaughn and me when discussing Health Config work.

I agree, we are mixing some concepts and we need to first to address the feature (same term, same meaning across all pages).

> To be specific (and to illustrate my confusion), if a Deployment is scaled to 1 pod, but that pod has no telemetry, it is considered "idle" in the graph but is NOT considered "idle" in the app or workload screen.

I don't know if a scaled 0 term is equivalent to a non-traffic term, which I guess is the main root discussion here.

First we could discuss those terms, and next we could add UX for better translate outputs into UI recommendations.

I personally thing that those are two different situations, but I have concerns to introduce new terminology "quiet" that is only used by us, and probably between team member it may refer to different things.

My take on this: marking non-traffic nodes as "grey" sounds good, marking them as "blue" on iddle applications, looks logical as a user's experience.

**Comment by jotak** [comment]
@lucasponce there's also the terminology in the "Show idle nodes" that you can see in graph display options. Here "idle" means nodes that never received traffic, regardless their deployment status. I think this is also what @jmazzitelli wanted to point out.

**Comment by lucasponce** [comment]
> @lucasponce there's also the terminology in the "Show idle nodes" option that you can see in graph display options. Here "idle" means nodes that never received traffic, regardless their deployment status. I think this is also what @jmazzitelli wanted to point out.

Right, I guess it's also related to this discussion:
https://github.com/kiali/kiali/issues/3232#issuecomment-748338913

**Comment by jmazzitelli** [comment]
> there's also the terminology in the "Show idle nodes" option that you can see in graph display options. Here "idle" means nodes that never received traffic, regardless their deployment status. I think this is also what @jmazzitelli wanted to point out.

> I don't know if a scaled 0 term is equivalent to a non-traffic term, which I guess is the main root discussion here.

Yes. They are not equivalent (as proof they are not equivalent - we do not show them identically depending on the UI page you are looking at; e.g. a non-traffic app with scale=1 is "idle" in the graph but "healthy" in the app list).

Consider:

* In the graph UI page, the non-traffic edges/nodes (regardless of scale which is the main point) are referred to as "Idle Edges" and "Idle Nodes" in the drop down menu "Show Idle Edges" and "Show Idle Nodes" 
* In the App and Workload list UI pages, the scaled-0 components are referred to as "Idle":

![image](https://user-images.githubusercontent.com/2029470/104577047-0440c900-5627-11eb-92a5-3d3be3ba9e5e.png)

So an app with scale=1 and no traffic shows as "Idle" in the graph but NOT Idle in the app list - this is the confusing part.

**Comment by lucasponce** [comment]
> So an app with scale=1 and no traffic shows as "Idle" in the graph but NOT Idle in the app list - this is the confusing part.

Perhaps we can reserve "Idle" for non traffic workloads, and introduce another "non pods" term.

Personally "Idle" for "0 Pods" doesn't suit well to me, at least from grammar perspective (even translated to other languages).

**Comment by jmazzitelli** [comment]
> Is there any well known used term for 0 pods controllers/deployments ?

Looking at the [Kubernetes documentation for "Deployment"](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/), notice the fields displayed by `kubectl get`:

```
When you inspect the Deployments in your cluster, the following fields are displayed:

NAME lists the names of the Deployments in the namespace.
READY displays how many replicas of the application are available to your users. It follows the pattern ready/desired.
UP-TO-DATE displays the number of replicas that have been updated to achieve the desired state.
AVAILABLE displays how many replicas of the application are available to your users.
AGE displays the amount of time that the application has been running.
``` 

I checked, and the same fields show for "DaemonSets" too.

For ReplicaSets, the documentation states:

```
ReplicaSet output shows the following fields:

NAME lists the names of the ReplicaSets in the namespace.
DESIRED displays the desired number of replicas of the application, which you define when you create the Deployment. This is the desired state.
CURRENT displays how many replicas are currently running.
READY displays how many replicas of the application are available to your users.
AGE displays the amount of time that the application has been running.
```

The wide display for StatefulSets contains "READY" also - so that term is well-known for StatefulSets as well:
```
kubectl get statefulsets.apps -n foo -o wide
NAME    READY   AGE     CONTAINERS   IMAGES
...
```

Based on these well-known Kubernetes terms, I can see two options that we could use: either "Not Ready" or "Unavailable".

Because Kubernetes displays the field "READY" for at least Deployment, DaemonSets, StatefulSets, and ReplicaSets, I think the first option should be "Not Ready" since "ready" is a well-known term for all of them. I think "Unavailable" would be understandable to users, too, as a second option.

**Comment by lucasponce** [comment]
"Not Ready" sounds good to me for this scenario.

**Comment by lucasponce** [comment]
I think we can use this issue to keep "Idle" in the context of no traffic elements and rename to "Not Ready" those health scenarios with no pods.

I guess a rename should be enough but as there are filters that can be affected, it may need some review.

Also, note that Health is an area of active development and there are other PRs that may be synced on this.

**Comment by lucasponce** [comment]
I'll put this one on my todo list for next sprint.
