### ISSUE TITLE
Introduce "preview" mode in Istio Config actions

### ISSUE THREAD

**Issue by joaquinfll** [kiali/kiali#3577]
**SCOPE UPDATE**

The same idea of this issue was recently discussed in https://github.com/kiali/kiali/discussions/4084#discussioncomment-931465 so I think it was good to consolidate it with this request as basically it describes the same scenario.

So the scope of this task would be:
- Introduce a new flow step into the Kiali actions called "preview" (namespace actions under "Overview" page, wizard actions under service details page, new configuration under Istio Config page).
- The "Create" action should be moved to a "Preview" view, where the user could see the yaml of the resource(s) that Kiali would like to create for a particular scenario.
- The "Preview" view should work for all users (read-only and read-write rights), and in this view, Kiali should check if user may perform that action and enable to continue with the "Create".
- Users can modify the resulting yaml in the "Preview" view.
- The "Preview" view should allow user to copy/download the resulting yaml to be used in other environment.
- It's pending to discuss as part of this work how to migrate the existing "Update" actions under service details.

Original issue description:

**Is your feature request related to a problem? Please describe.**
Create IstioConfig/Actions only works with enough permissions.

**Describe the solution you'd like**
Provide a Show button to render the policy artifact.

**Describe alternatives you've considered**
None

**Additional context**
In environments where configuration of the Kubernetes cluster is handled by GitOps Kiali might be deployed in read-only mode. this disables the policy creation functionality. Kiali doesn't need to apply changes directly to the cluster, it can provide a rendered policy ready to copy/paste or save as a file.

**Comment by lucasponce** [comment]
Thanks @nodanero for the issue.

When you say 
> Provide a Show button to render the policy artifact.

What "policy" artifact you refer, the ServiceAccount used for the user on this case ?

This comment:
> Kiali doesn't need to apply changes directly to the cluster, it can provide a rendered policy ready to copy/paste or save as a file.

You mean that you would like that Kiali generates the yaml config in some way that can be "copied/exported" to be applied via a kubectl command ?

**Comment by nodanero** [comment]
> Thanks @nodanero for the issue.
> 
> When you say
> 
> > Provide a Show button to render the policy artifact.
> 
> What "policy" artifact you refer, the ServiceAccount used for the user on this case ?
> 
@lucasponce when I used policy I meant the code generated by "Create New Istio Config" and "Actions" button options.
"Action" doesn't need to be disable, just generate the code and provide a way to see it or download it.

> This comment:
> 
> > Kiali doesn't need to apply changes directly to the cluster, it can provide a rendered policy ready to copy/paste or save as a file.
> 
> You mean that you would like that Kiali generates the yaml config in some way that can be "copied/exported" to be applied via a kubectl command ?

Correct. Kubernetes configuration is being applied externally by a tool following GitOps (FluxCD/ArgoCD). People following this practice would deploy Kiali with read-only permissions and they would still benefit of having a way to generate valid configuration in Kiali to later commit to the git repository.

**Comment by lucasponce** [comment]
> I used policy I meant the code generated by "Create New Istio Config" and "Actions" button options.
"Action" doesn't need to be disable, just generate the code and provide a way to see it or download it.

Ok, I understand now the feature thanks for clarifying, I'll leave here to discuss it more about it in the future.

I understand that perhaps some kind of optional "preview" of the generated config can be shown before to be applied.

We'll think on it, thanks for the feedback.

**Comment by aljesusg** [comment]
Epic done
