### ISSUE TITLE
Kiali graph is not showing when the prometheus sidecars are enabled

### ISSUE THREAD

**Issue by chaitanyasaig** [kiali/kiali#3578]
**General remarks**

Our Kubernetes clusters are created in rancher, We are trying to view the application graphs in kiali dashboard.

 **For prometheus** 
      -- when the istio sidecars are enabled, graphs are not visible (with label istio-injection=enabled on cattle-monitoring-system namespace)
      -- when the istio sidecars are not there, graphs are visible. (with label istio-injection=disabled on cattle-monitoring-system namespace)

**Describe the bug**
**Versions used**
Kiali: 1.26.0
Istio: 1.8
Kubernetes flavour and version: (e.g. OpenShift Origin 3.9)  1.18

**To Reproduce**
1. Create namespace cattle-monitoring-system
2. Give the label to namespace Istio-injection=enabled
3. Install the Prometheus from the Apps and Marketplace of rancher dashboard.
4. Install sample application in sample namespace
5. Try to view the graph of sample application in Kiali dashboard.

But, here graphs will not be visible if the istio-injection=enabled label is there on cattle-monitoring-system namespace.

**Expected behavior**
Application related graphs should be visible, when the istio sidecrs are present for the prometheus.

**Comment by lucasponce** [comment]
> -- when the istio sidecars are enabled, graphs are not visible (with label istio-injection=enabled on cattle-monitoring-system namespace)
> -- when the istio sidecars are not there, graphs are visible. (with label istio-injection=disabled on cattle-monitoring-system namespace)

Is it possible that you have two prometheus instances (Istio one plus the Prometheus you installed from the Apps/Marketplace) tnat are in conflict ?

**Comment by jshaughn** [comment]
This is not a Kiali issue/bug. Kiali will show graphs when configured correctly and Prometheus is populated correctly with Istio metrics.  This sort of problem is more suited to our Github Discussions, #kiali on IRC, or the #kiali channel on Istio slack.  Or perhaps rancher.  I'm closing this issue, please pick up the discussion in one of the suggested chanels.  Thanks.
