### ISSUE TITLE
Service Trace are showing error in Jaeger 

### ISSUE THREAD

**Issue by pbajjuri20** [kiali/kiali#3589]
Reproducing steps:

Select Namespace = Bookinfo

1. Click on the "Services" tab
2. Click on "details"
3. Click on the "Trace" tab
4. Click on "View in Tracing"

Result:
Jaeger is showing an error.

![Jaeger_issue1](https://user-images.githubusercontent.com/55099523/104936332-6167b200-597a-11eb-84ab-0c183349fc61.gif)

**Comment by jotak** [comment]
Hi @pbajjuri20 ,
The animation goes too fast for me to see the jaeger URL. Can you write it here please?

**Comment by pbajjuri20** [comment]
Hi @jotak 

Kiali UI 1.29.0 (b8038df067afc90cf2238fcc858efadc9c0727e8)
Kiali Server v1.29.0-SNAPSHOT (5fcb792faf5ea99e9048b90bcc0d8fac4ddafbbc)
Kiali Container   v1.29.0-SNAPSHOT


Here is the Jaeger URL: http://tracing-istio-system.apps.pbajjuri-47332.devcluster.openshift.com/search?service=details.bookinfo&start=1610987202342000&limit=20


![Jaeger_error](https://user-images.githubusercontent.com/55099523/104942188-1a7dba80-5982-11eb-9fc9-ee3391395c5e.png)

**Comment by jotak** [comment]
This is working fine on my setup, are you sure your configuration is correct? This is typical of a badly configured URL. For instance, Jaeger is often reached behind a `/jaeger` subpath, can you try to append `/jaeger` to your configured URL ?

**Comment by pbajjuri20** [comment]
@jotak Thank you for the Clarification.

It is Kiali CR issue with the Kiali-qe: latest build.
Missing the /jaeger in the Kiali CR :spec -> URL

url: >-
        http://tracing-istio-system.apps.pbajjuri-473325.devcluster.openshift.com/jaeger

Expected 
url: >-
        http://tracing-istio-system.apps.pbajjuri-473325.devcluster.openshift.com/jaeger

**Comment by pbajjuri20** [comment]
This issue is fixed with the Kiali-qe: latest build: https://quay.io/repository/kiali-qe/kiali?tab=tags


![Jaeger_issue_fixed](https://user-images.githubusercontent.com/55099523/105080220-803f7480-5a5e-11eb-95d5-988781dafbb4.gif)

**Comment by pbajjuri20** [comment]
Closing this issue, because it is a Kiali-qe build issue, It is fixed with the latest build.
