### ISSUE TITLE
Error authenticating (getting business layer) - authInfo missing from the request context

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#3591]
Either I didn't build things correctly, or the openshift auth strategy is now broken due to the changes made in the header-auth strategy PRs that just went in.
I'm pretty sure this is broken and not due to a wrong build or old cookies in my browser - this is bad - openshift deployments are now broken.

**Comment by jmazzitelli** [comment]
@mlbiam I'm seeing this when I try to log in while deployed on OpenShift using openshift auth strategy - perhaps you know the place to fix this:

![image](https://user-images.githubusercontent.com/2029470/104959169-94706c80-599f-11eb-88f4-fdc87170fc98.png)

**Comment by mlbiam** [comment]
The error it's self is because the `authInfo` variable wasn't present when getting the business layer, so it didn't know how to talk to openshift (this replaced the `token` variable in the request).  Is this on authentication or afterwards?  what happens when you hit /kiali/api/authenticate?

**Comment by jmazzitelli** [comment]
It is on authenication - trying to login (enter user/pass in the openshift openid login screen) and I immediately get the above.

**Comment by jmazzitelli** [comment]
The problem is here:

https://github.com/kiali/kiali/blob/master/handlers/authentication.go#L654

**Comment by mlbiam** [comment]
My guess is line 147 in business/authentication.go - `business, err := getBusiness(r)`.  `r` doesn't have the `authInfo` in there.  I'm guessing you're trying to get the business object using the kiali service account, similar to we validate the header token using the kiali service account?  Try: `business, err := business.Get(&api.AuthInfo{Token: kialiToken})` ?

**Comment by jmazzitelli** [comment]
> My guess is line 147 in business/authentication.go - `business, err := getBusiness(r)`. `r` doesn't have the `authInfo` in there. I'm guessing you're trying to get the business object using the kiali service account, similar to we validate the header token using the kiali service account? Try: `business, err := business.Get(&api.AuthInfo{Token: kialiToken})` ?

I did try that already. Didn't work. Same behavior (had to use `token` in this context. there is no `kialiToken`)

**Comment by mlbiam** [comment]
is `/auth/info` called after authenticating?  so the user should already be authenticated, right?

**Comment by jmazzitelli** [comment]
Now that I pay closer attention, I'm not even getting to the login screen. Something is happening even before I get challenged with the openshift login page.

**Comment by jmazzitelli** [comment]
@israel-hdez can you build master for everything and try to log into openshift? I'm crossing my fingers I am just doing something wrong in my environment, but it doesn't look like it. I'm even trying with an incognito browser window to make sure I don't have any outdated cache or cookies that could be causing this - but it still won't work for me.

**Comment by jmazzitelli** [comment]
The bug is somewhere in either of these PRs:
* https://github.com/kiali/kiali/pull/3568/files
* https://github.com/kiali/kiali-ui/pull/2048/files

**Comment by jmazzitelli** [comment]
I think I see a problem:
https://github.com/kiali/kiali/blob/master/handlers/authentication.go#L620
We need to check the code base and make sure we are passing in the new context variable "authInfo" not with the old "token" key name.

**Comment by jmazzitelli** [comment]
This should fix it. Openshift auth is now working with this: https://github.com/kiali/kiali/pull/3594

I'm going to run some more testing JUST to be sure the other auth strategies still work - I think it's all good though.
