### ISSUE TITLE
Metrics page: select all/none filter

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#3596]
In metrics page, it becomes handy to have a select all/none option in the metrics filters when the number of available options grows substantially.

E.g. here, for Kiali internal metrics, having to deselect options one by one is cumbersome. 
![Capture d’écran de 2021-01-19 09-47-16](https://user-images.githubusercontent.com/2153442/105010203-b3244100-5a3b-11eb-82b2-dd645ce3323e.png)

This is also relevant for istio metrics when a high number of versions are available, for instance.

**Comment by lucasponce** [comment]
I think this pattern is already implemented in the namespace selector:
![image](https://user-images.githubusercontent.com/1662329/107927047-c2cd7180-6f76-11eb-8caf-7dc61b5262a2.png)

Not 100% similar, but I guess same action should more or less mimic/follow same UI here.

**Comment by lucasponce** [comment]
Closed by https://github.com/kiali/kiali-ui/pull/2185

Friendly reminder, please, use the link feature on the PR to close automatically the issues when PR are merged.
