### ISSUE TITLE
Tracing page toolbar redesign

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#3604]
_Discussion around this task started initially in https://github.com/kiali/kiali/issues/2776#issuecomment-740605636._
_Here's a copy of the initial comment:_

There's two tasks currently to add or change options from the traces chart toolbar:

- The one to have percentile-based filtering instead of the current response time slices: https://github.com/kiali/kiali/issues/3380
- The one to introduce spans average duration in chart: https://github.com/kiali/kiali/issues/3399

Perhaps it's the opportunity to redesign the toolbar and make it more alike what we have in other pages? In Graph or Metrics, most display options are grouped inside a single dropdown. Is it the way to go here? (should be discussed with @lwrigh )

I've built this quick mockup to show how it could be like:
![Capture d’écran de 2020-12-08 12-45-19](https://user-images.githubusercontent.com/2153442/101485733-dc8d7f80-395b-11eb-9790-f27a87c26f88.png)

Here I removed the "response code" filter, and decreased a lot the options on query limit (I don't think it's very useful to have so many limits, what do you think?).

About the response code, I'd like to know your thoughts. Currently we can filter only by individual response code (200, 403, 404, etc.). It's an arbitrary list that we have. Ideally, we would certainly prefer to be able to filter with coarser granularity (4xx, 5xx) but Jaeger doesn't allow to query tags using a regex, hence we have this flat-list selection per individual response code. Now the question is: how useful is it? Personally I've never used it, I rely more on the "error" tag when I need to filter for errors, although it's less accurate I find it more interesting to get all the traces with errors at once, not having to iterate through different error codes. So, given my own experience, I'd be in favour of removing this filter, but of course i'd like to hear from other's experiences.

Last thing: I'd like to add a new filter by operation name. Probably it wouldn't fit in the new display dropdown, so would be displayed next to it.

**Comment by jotak** [comment]
As part of this, we should probably change the wording about fetch limit, because on the backend, the fetching strategy has evolved, and the resulting number of spans may not be exactly limited by what is demanded from the UI. So perhaps we should use something more vague and qualitative like: "Fetch size: low / medium / high / very high" ?

**Comment by lucasponce** [comment]
+1 from my side

I was thinking loud if we would like to separate from the "Display" the "Filtering" as I see two main concepts: business queries, and how those are displayed visualized, but at this point I'm not even sure, so any change on what you propose sounds ok.

>  "Fetch size: low / medium / high / very high" 

Yes, I guess absolute numbers on this context has less sense, also that opens that queries may evolve without touching the UI

**Comment by lwrigh** [comment]
@jotak That direction sounds good to me. The mock up looks great! I think having the 'Display' dropdown options all in one place makes total sense since that's what's going on with the 'Display' dropdown in the topology view. If there are filtering options that seem extraneous and are not too commonly used I think it makes perfect sense to get rid of them so the 'Display' dropdown isn't too overwhelming.

**Comment by jotak** [comment]
Hey @lucasponce @aljesusg , what do you think about removing the option to adapt x-axis to data ? I think the original reason why we have that is gone, with the "split and join" fetch strategy, traces are now distributed all over the x axis and this functionality makes less sense now.
Removing it would allow to simplify the UI (less options => easier to use)

**Comment by lucasponce** [comment]
>  I think the original reason why we have that is gone, with the "split and join" fetch strategy, traces are now distributed all over the x axis and this functionality makes less sense now.

It sounds ok. I think that feature was more a tactical option, now I think there is a better integration with the time controls, so perhaps if the interval is too short it can be valid to propose some controls (like select the interval dragging in the charts, lilke it happens in the metrics chart).
