### ISSUE TITLE
Additional Istiod Pod Causes Unhealthy Pod Sync Status For Kiali

### ISSUE THREAD

**Issue by asummers** [kiali/kiali#3605]
**Describe the bug**
Having two `istiod` pods causes `unhealthy` status to be reported in Kiali with reason `proxy not synced`, when `istioctl proxy-status` reports synced due to different read targets.  

**Versions used**
Kiali: 1.28.1
Istio: 1.7.2
Kubernetes flavour and version: (e.g. OpenShift Origin 3.9) Rancher On Prem 1.18.6

**To Reproduce**
1. In my case a hardware issue caused the second istiod to exist, but anything that creates a second istiod should be able to reproduce.
2. Run `istioctl proxy-status` and notice SYNCED status because it is reading from new istiod
3. Go to Kiali and notice all applications have unhealthy yellow border 
4. Drill into any and notice pod status unsynced because it is reading from old istiod
5. Remove extra istiod
6. Notice situation resolved in Kiali

**Expected behavior**
Kiali more gracefully handles duplicate istiod.

**Comment by jshaughn** [comment]
I guess if Kiali could detect and report on this situation specifically it would be good.

**Comment by xeviknal** [comment]
Also adding this info:

> `replicas: 2` is the default number when using ASM[1]
When running the ASM, the istiod deployment have 2 replicas.
We should cover this scenario too.

[1] ASM (Anthos Service Mesh)

**Comment by gfthybridlabs** [comment]
Thanks @xeviknal this is certainly the case for the embedded ASM Operator profiles in istioctl (asm-gcp, asm-multicloud etc.) not in the "usual" profiles (default, demo).

The ASM profiles setup an HPA for the istiod pod:-
 ```
$ k get hpa -n istio-system
NAME                   REFERENCE                         TARGETS   MINPODS   MAXPODS   REPLICAS   AGE
istio-egressgateway    Deployment/istio-egressgateway    5%/80%    1         4         1          5h12m
istio-ingressgateway   Deployment/istio-ingressgateway   6%/80%    2         5         2          5h12m
istiocoredns           Deployment/istiocoredns           40%/80%   1         5         1          5h12m
istiod-asm-176-1       Deployment/istiod-asm-176-1       2%/80%    2         5         2          5h12m
```

**Comment by xeviknal** [comment]
Complimenting the description, the additional pod in the environment was in an unhealthy state. Meaning that it was called to get the proxy-status but wasn't responding.

@gfthybridlabs Does your current kiali installation have problems?
And one thing for me to gather some more info of you env. Does the ASM installation label the pods like the upstream is doing?

To check it out, could you run this for me?
`k get pods -n istio-system --selector app=istiod`

Thank you

**Comment by gfthybridlabs** [comment]
@xeviknal Hi, I don't think it's having problems seems a little slower to respond but it's entirely possible it's just my perception.

Yes the pods are labeled with the app as per upstream
```
$ k get pods -n istio-system --selector app=istiod --show-labels 
NAME                               READY   STATUS    RESTARTS   AGE   LABELS
istiod-asm-176-1-56f466648-hw4zg   1/1     Running   0          43h   app=istiod,istio.io/rev=asm-176-1,istio=istiod,pod-template-hash=56f466648
istiod-asm-176-1-56f466648-r4q2m   1/1     Running   0          43h   app=istiod,istio.io/rev=asm-176-1,istio=istiod,pod-template-hash=56f466648
```

**Comment by xeviknal** [comment]
@gfthybridlabs thank you very much. I am preparing one PR that should improve the response time for that scenario. 

@asummers I have one question regarding this scenario, do you have the istio component status enabled? (it is by default).
If so, do you remember if you had the red light in the mast-head? It should be something like this:

![Screenshot of Kiali (3)](https://user-images.githubusercontent.com/613814/106280895-c5be2780-623e-11eb-8638-b8f6925a27d6.png)

On the other side, do you remember what was the status of the pod? 'Running', 'Terminating'?
I am saying this because Kiali can check the pod status as the easy solution. However checking whether the pod is actually serving content may reduce the performance. I'd rather avoid this scenario.

I am preparing a PR that will return always any proxy-status information gathered. This is how istioctl handles non-responding `istiod` pods. Hence, Kiali will behave similarly to the `istioctl`.

**Comment by asummers** [comment]
@xeviknal 

I don't recall there being an unhealthy status. While I don't have evidence I did not, I feel like I would have noticed the red state. 

The pod in my case had status Evicted originally caused by node disk pressure.

**Comment by xeviknal** [comment]
Thank you both!

I've also deployed an ASM cluster in GKE (default installation) and everything worked as expected.
Once #3654 is merge, this issue will be closed.
