### ISSUE TITLE
Log in Kiali：You are logged in, but there was a problem when fetching some required server configurations

### ISSUE THREAD

**Issue by vickyhui** [kiali/kiali#3606]
kiali logged:You are logged in, but there was a problem when fetching some required server configurations
![image](https://user-images.githubusercontent.com/13129044/105321243-2d062700-5c02-11eb-82b8-7fee51d11bd3.png)
so,I don't know what happend

**Comment by jotak** [comment]
I think you should have additional information if you open the javascript console, would you mind refreshing the page checking that console?

**Comment by jshaughn** [comment]
I have seen this happen in response to losing the back-end cluster.  @vickyhui is that what happened to you, any updates?

**Comment by lucasponce** [comment]
Outdated.
Closing due lack of followup updates or additional information.

Please, reopen it with more info if this is still a problem.

**Comment by liangsqrt** [comment]
there is no error or other info in console

**Comment by Polyipnus** [comment]
in my case, I reinstalled istio, and the secret key was created before,  i just removed the secret key `kiali` in default namespace, and problem solved.  You can logged pod `kaili` for detail info, ` dial tcp 10.254.0.1:443: i/o timeout`

```
kubectl delete secret kiali -n default
```
the secret was created by following [the tutorial](https://istio.io/latest/zh/docs/tasks/observability/kiali/)
```
