### ISSUE TITLE
Operator Helm chart contains invalid image tag and therefore cannot be installed

### ISSUE THREAD

**Issue by owetterau** [kiali/kiali#3616]
When trying to install the latest operator Helm chart, the kiali-operator pod cannot be installed, because it tries to download

quay.io/kiali/kiali-operator:1.29.0

which leads to an "unknown manifest" error, because the "v" in the tag is missing.

The correct image would be

quay.io/kiali/kiali-operator:**v**1.29.0

**Comment by jmazzitelli** [comment]
@owetterau @lucasponce where are we pulling in "1.29.0" ? This was reported this morning and I didn't notice the missing "v". Yes, all our versions are prefixed with "v". I wonder if we have something wrong in a script or config file somewhere?

**Comment by jmazzitelli** [comment]
I found it .

@israel-hdez something is wrong in the new release stuff we did -- we are missing the "v" here:

https://github.com/kiali/helm-charts/pull/31/files#diff-e885ccbd5f8281c4fa3940b644f3d1abe5335fe80713952467908931f7d233b0R5

**Comment by jmazzitelli** [comment]
@israel-hdez we need to fix that so the helm index is generated correctly and then re-do the v1.29.0 helm release.

**Comment by jmazzitelli** [comment]
The Jenkinsfile (or whoever does it) needs to pass in a VERSION with "v" prefix - or the makefile should check if the version doesn't have a "v" then it should add it:

https://github.com/kiali/helm-charts/blob/master/Makefile#L67

https://github.com/kiali/helm-charts/blob/master/Makefile#L76

**Comment by lucasponce** [comment]
This requires a change on the CI to fix the existing helm-charts ? or helm-charts can be fixed for v1.29.0 with a manual fix ?

**Comment by jmazzitelli** [comment]
This has been manually fixed for now. For those having this problem, you will probably need to run a helm refresh to pick up the change:

```
helm repo update
```

If you have not attempted to install the latest Kiali yet, that command will not be necessary

**Comment by eperdeme** [comment]
Just a heads up, but it would have been kinder to have created 1.29.1 or some other version than overriding a pushed release.

Especially for us that mirror the helm repos, it means we need to go and clear mirrors pulls internally to get the overridden tag.

**Comment by jshaughn** [comment]
@eperdeme sorry about that, we'll keep that in mind for the future, but hopefully we won't actually have to deal with this sort of thing again.
