### ISSUE TITLE
Migrate front-end to Yarn 2

### ISSUE THREAD

**Issue by israel-hdez** [kiali/kiali#3622]
Yarn docs state that versions prior to Yarn 2.0 are in maintenance mode since January 2020 and some day will reach EoL. Probably, Kiali UI should move to using Yarn 2.0.

**Comment by lucasponce** [comment]
+1

**Comment by israel-hdez** [comment]
I'm dropping this task.

Some benefits of migration are listed here: https://yarnpkg.com/getting-started/migration#why-should-you-migrate.

The following are my conclusions. I may be wrong with what I'm writing, but anyway here it is my opinion...

Apparently, the main feature of Yarn v2 is `Plug'n'Play`. Kiali cannot fully take advantage of this feature. Probably, it would be only at build/test time when it may be used. So, it would be mainly a feature used when developing. Then, after we run `yarn build` the benefit ends because we get an already optimized build for running in the browser. The `Plug'n'Play` feature seems to be targeted mainly for NodeJS apps. Notice that Kiai is _not_ a NodeJS app. We are using NodeJS only as part of our development stack. So, the `Plug'n'Play` feature is a weak reason to migrate. The other features mentioned in YarnV2 docs are, IMO, also weak reasons to migrate.

Migration seems to be simple and can be accomplished following the steps in https://yarnpkg.com/getting-started/migration#step-by-step. I tried and running those steps is OK, but our `yarn start`, `yarn build`, etc commands are broken. I found that YarnV2 ships a "normalized shell" (see: https://dev.to/arcanis/introducing-yarn-2-4eh1#normalized-shell). Our [scripts in package.json](https://github.com/kiali/kiali-ui/blob/a8b04c5f868dedb2b830b8e222ccc7240798b171/package.json#L35-L53) are not compatible, so we would need to adapt them. I couldn't find docs for this shell, so I don't know what's available in this normalized shell. But I learnt that the simple if/then/else control flows that we are using are not compatible :-/ I really didn't try to fix this issue (without the shell docs, this is, mostly, trial&error).

I found github issues about past incompatibilities with YarnV2 for some tooling. For example: https://github.com/facebook/create-react-app/issues/10002. Since we are using some old versions of dev tooling, not everything may be compatible. I didn't really check this, but it's a potential issue when transitioning to YarnV2.

We would be losing compatibility with `npm`. Simply, because YarnV2 does not offer this backwards compat. I'm not sure if this is really a thing, but it's probably worth to mention.

Since YarnV1 has some backward compatibility with NPM, It's not a big deal if it becomes deprecated. We could, simply, go back to `npm`.

I couldn't find any hard date about when it will be deprecated, so V1 may still be maintained for some time. If it suddently becomes deprecated, we could, simply go back to `npm`. 

---

At the end, as much as I would love to migrate to YarnV2, I'm not sure Kiali will get any real benefit. We are using Yarn mostly as a simple package manager. It works fine. So, I don't think the time to do the migration and to fix any future related issues is worth it at the moment... Probably in the future it.

 I'm closing this for now.

`won't fix`

**Comment by jshaughn** [comment]
Thanks for the investigation @israel-hdez, and I agree with your conclusion.
