### ISSUE TITLE
Namespace boxes needs a different internal layout

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#3623]
I don't think the current layout that Kiali offers when enable namespace boxes is good.

For example, I have two namespaces and the standard layout is correct/expected:

![image](https://user-images.githubusercontent.com/1662329/105814446-b8403d80-5fb1-11eb-8416-2a4130aa5dad.png)

But when enabling namespace boxes:

![image](https://user-images.githubusercontent.com/1662329/105814553-df970a80-5fb1-11eb-8f75-aae9624eeace.png)

What should be expected:

![image](https://user-images.githubusercontent.com/1662329/105814810-38ff3980-5fb2-11eb-8b22-bb111a8c9515.png)

Otherwise this option should be hard to use.

Changing the standard layout offer other possibilities, but it's not satisfactory, I guess that at least Kiali should try to wrap inside as presented in the suggested capture.

**Comment by jshaughn** [comment]
hmm, I'm a little surprised at that.  I'll revisit the box code again...

**Comment by lucasponce** [comment]
If it helps to reproduce:
- Using error-rates app https://github.com/kiali/demos/tree/master/error-rates
- Install alpha and beta and select both on the graph

I was using a fresh fetch from master this morning.
