### ISSUE TITLE
Several links from graph are broken

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#3624]
- In the tippy.js menu, the URL seem broken just for the application (groups) link, with a double-slash at the end:

![Capture d’écran de 2021-01-26 09-32-45](https://user-images.githubusercontent.com/2153442/105820266-a4003e80-5fb9-11eb-8f7a-589d6db69a71.png)

- Perhaps the same issue from the side-panel links, still with application-focused node, the links all redirect to the overview page

**Comment by lucasponce** [comment]
Yeah, thanks for opening this one, I was also noticing the same bug:
![image](https://user-images.githubusercontent.com/1662329/105821081-b9c23380-5fba-11eb-9c15-171b606b400b.png)

**Comment by jshaughn** [comment]
@jotak I added the 1.29 backport label, please backport this after you merge. Thanks!
