### ISSUE TITLE
Istio "config_map_name" not used

### ISSUE THREAD

**Issue by joscha-alisch** [kiali/kiali#3634]
**Describe the bug**
When installing kiali via the kiali-operator, it looks like the configuration option `external_services.istio.config_map_name` is not used. We get the following log message when starting up
```
Failure when checking if mesh-id is configured: configmaps "istio" not found
```
even though we set the following configuration in the kiali CR:
```yaml
external_services:
  istio:
    config_map_name: istio-ver-1
```

I made sure that this is indeed the name of the ConfigMap resource in istio-system and that in the actual kiali configmap this setting is configured. Lastly, I enabled trace logging which shows the kiali config on startup and also there it says `config_map_name: istio-ver-1`. 

It might be important for debugging that kiali is running in a different namespace than istio, but I tried it in the same namespace as well with the same error.

**Versions used**
Kiali: v1.29.0
Istio: 1.7.3
Kubernetes flavour and version: GKE v.1.19.6-gke.600

**To Reproduce**
1. Install istio, see that the configmap is named "istio-ver-1"
2. Install kiali with the configuration option `external_services.istio.config_map_name` set to `istio-ver-1` 
3. Open the kiali UI 
4. See error in the log output of the kiali server `Failure when checking if mesh-id is configured: configmaps "istio" not found`

**Comment by joscha-alisch** [comment]
I now also tried to disable the kubernetes caching in case that has anything to do with it, with no improvement.

**Comment by jmazzitelli** [comment]
The code does appear to at least attempt to use that setting: https://github.com/kiali/kiali/blob/v1.29.0/business/mesh.go#L97

**Comment by joscha-alisch** [comment]
Yes, this is what I found as well which confuses me immensely. I think that `configmaps "istio" not found` is the error returned by the native kubernetes clientset, which suggests that for some reason `config.IstioConfigMapName` is `istio` in that line you posted. I.e. not what I actually configured 😕

**Comment by jmazzitelli** [comment]
what do you see if you curl the /api/config endpoint? It will tell you what it thinks the config_map_name is. In my case, I set `spec.external_services.istio.config_map_name` to `mazzwashere` and this is what I see:

```
$ curl -k http://localhost:20001/kiali/api/config
{
  "clusterInfo": {
    "name": "cluster-default",
    "network": "network-default"
  },
...
  "istioConfigMap": "mazzwashere",
...
  }

The interesting thing is - even with that, I do not see any errors in my logs (note: I do NOT have a configmap anywhere with that name - I was expecting an error in the kiali logs).

**Comment by jmazzitelli** [comment]
Oh, shoot! Well, duh.. yeah, that config.IstioConfigMapName is a constant. This code is wrong. It is not using the value in the Kiali ConfigMap -> https://github.com/kiali/kiali/blob/v1.29.0/config/config.go#L58

I'll see if I can submit a PR for those. I assume it is an easy fix.

**Comment by jmazzitelli** [comment]
I'm pretty sure its a simple one line fix to [this line](https://github.com/kiali/kiali/blob/v1.29.0/business/mesh.go#L97) - something like:

```
	istioConfig, err := in.k8s.GetConfigMap(cfg.IstioNamespace, cfg.ExternalServices.Istio.ConfigMapName)
```

**Comment by jmazzitelli** [comment]
Yup - that fixes it. I'll submit a PR right now.

```
2021-01-27T11:40:57Z WRN Failure when checking if mesh-id is configured: configmaps "mazzwashere" not found
```

**Comment by joscha-alisch** [comment]
Oh nice, good spot. I completely missed it when looking at it myself

**Comment by joscha-alisch** [comment]
Thanks for the quick action on this @jmazzitelli :+1:

I'm not familiar with your release process, will this be published as a bugfix soonish?

**Comment by jmazzitelli** [comment]
It'll be published "soonish" - in about 2 weeks time... It will be in the v1.30 release on February 12.

**Comment by win5923** [comment]
Is this issue has been solved? I'm still encountering the same situation.
``` yaml
external_services:
  custom_dashboards:
    enabled: true
  istio:
    root_namespace: aks-istio-system
    config_map_name: istio-asm-1-17
```

**kiali log:**
```
2024-02-01T01:18:53Z ERR Will not process discoverySelectors due to a failure to parse the Istio ConfigMap: configmap "istio" not found
```

**Version:**
kiali: v1.79.0
kiali operator: v1.79.0

**Comment by jmazzitelli** [comment]
@win5923  should be fixed: https://github.com/kiali/kiali/blob/v1.79.0/business/namespaces.go#L98-L106

You didn't mention what version of Istio you are using, but based on the "config_map_name" you posted, looks like 1.17. If you are using Istio 1.17, that's not compatible with Kiali 1.79. See: https://staging.kiali.io/docs/installation/installation-guide/prerequisites/#version-compatibility

If you cannot figure this out, please [start another Q&A Discussion](https://github.com/kiali/kiali/discussions/new?category=q-a) - this issue was closed 3 years old and your issue is probably different.

**Comment by win5923** [comment]
thx!
