### ISSUE TITLE
Structure the subview in the Envoy Config modal

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#3635]
The Envoy Config modal is becoming a very useful feature located under the Workload.

I think that the current "Resources" options could be better organized in a different pattern:
![image](https://user-images.githubusercontent.com/1662329/105978135-7a671600-6092-11eb-8303-7cd68e7b1e60.png)

I guess that show/group them re-using a pretty similar pattern used in other modal, would help to the user to navigate on them:
![image](https://user-images.githubusercontent.com/1662329/105978382-c2863880-6092-11eb-854c-85acf362642d.png)

So a way to group the sections in a tab with "All | Bootstrap | Clusters | Listeners | Routes" will help user to identify that each section may have a different structure ("all" and "bootstrat" are raw yaml editors, but "clusters", "listeneres", "routes" are tables).

Also, I'm trying to consolidate the pattern used in modals to not diverge and more or less to apply similar designs to same features.

**Comment by abonas** [comment]
I'm not sure that modal is the right term here.
Also it is not very clear what is the relation between envoy to host/cluster/etc and what user can do here?
(I am not that informed about this feature so my lack of understanding could be  because of that)
Did UX review it?

**Comment by lucasponce** [comment]
I don't understand the last comment.

This issue is to re-organize several categories that are existing in a feature to follow same patter used in other places.
I don't think it requires UX review it.

**Comment by lucasponce** [comment]
@xeviknal will be on leave for some weeks.
I'm going to take this one as I've already discussed with Xavi about the scope and context.
