### ISSUE TITLE
Services are filtered based on Selectors and not on Labels

### ISSUE THREAD

**Issue by daur88** [kiali/kiali#3656]
**Describe the bug**
When fetching `fetchNamespaceApps`, services are collected based on wrong filter. 

**Expected behavior**
Kiali should not inspect `labelSelector` of the Services, but should inspect `labels` of the Services instead.

**Comment by lucasponce** [comment]
Service's labels may be different from workload/pod labels, and hence, potentially create more misunderstanding when a service is not linked with a particular app.

I know that there is some duplication in the models used, Kiali decided to tie to the selector to have a strong connection with the pods -> workload which is the source of the telemetry in Istio.

Could you describe an example of your use case, just trying to learn how we can solve this gap without breaking any logical connection between application/service/workload.

Thanks !

**Comment by daur88** [comment]
I see, now that i've learned a bit more, my initial decision does not seem that right, either. A little backstory here, i have a controller (workload) with label `app: myapp`, pods with label `app: myapp`, and a service with label `app: myapp`. However my service does not target pods based on the `app` label, for that i use my labels of my own. `app: myapp` is there merely to conform with Kiali's requirements. Right now, without this entry in my services' selectors, UI responds as if my application does not have any services (http://localhost:20001/kiali/console/namespaces/default/applications/whatever-app). That is the problem i want to solve.

Right now i assume, we can track services down if we start from pods. If we filter out from all pods, those with label `app: myapp`, then we can perform an inner join of this list with the list of available endpoints. This will give us a reduced list of endpoints that are attached to the services we want. This way we then can lift the requirements of having `app: maypp` in both service's selectors and labels - only pods' and workloads' label will matter.

**Comment by jotak** [comment]
Filtering from pods, then tying pods to services also has a drawback: it only works when you have some pods. There's a number of situations where you wouldn't have any (serverless, failing to start, etc.)

What about this alternative: filter from selector **and** from labels? @lucasponce , do you see any drawback doing this?

**Comment by jshaughn** [comment]
Note that using the `app` label is not really "Kiali's requirement" but is inherited from Istio.

**Comment by lucasponce** [comment]
> What about this alternative: filter from selector and from labels? @lucasponce , do you see any drawback doing this?

I think we can augment the use of labels in that direction, but using the label selector is something we will need in one or another way.

**Comment by daur88** [comment]
> Note that using the `app` label is not really "Kiali's requirement" but is inherited from Istio.

Thanks for correcting on that :+1:

> What about this alternative: filter from selector and from labels?

And :+1:  on this. Works for my case.

**Comment by lucasponce** [comment]
So, just to be on the same page.
The goal is to include under the logical "Application" services have "app" label on their selector but may have "app" label on service label as well.

I don't see a problem, but some side effects:
- If the new Service doesn't have also the "app" label on the selector, or if that service points to other workloads that don't have the "app" label, the telemetry won't collect all grouped information for an "app".

Remember, telemetry comes from pods, and "app" is just a logical term implemented with labels, so it's not defined with any kubernetes object.

**Comment by jshaughn** [comment]
@daur88 @lucasponce This one has been dormant for a while, is it still relevant?

**Comment by lucasponce** [comment]
I think this one has more implications that it seems, so not something it will be addressed in a short time without proper re-design.
