### ISSUE TITLE
Inherit resource names from Kiali CR in operator

### ISSUE THREAD

**Issue by joscha-alisch** [kiali/kiali#3665]
**Is your feature request related to a problem? Please describe.**
When installing multiple kialis in the same namespace, we have naming clashes because the operator hard-codes the resource names as "kiali", e.g. for the Deployment and Service resources. 

**Describe the solution you'd like**
The names of the k8s resources should either be configurable, or inherit from the name of the Kiali CR.

**Describe alternatives you've considered**

- *Don't deploy into the same namespace*
This is a workaround for now, but not being restricted (for no good reason) in that sense would make life easier :)

**Comment by jmazzitelli** [comment]
It is not supported that you install multiple Kiali instances in the same namespace. There is likely other things that will go wrong - either within the Operator or within the Server itself. The Kiali Operator is designed to managed multiple Kiali instances each installed in their own namespaces (e.g. to support multi-tenancy) - it is NOT designed manage multiple Kiali Servers in the same namespace.

**Comment by jmazzitelli** [comment]
one workaround you could try (but, again, this is not supported if trying to install multiple instances in the same namespace - I don't even know if it will work, and I wouldn't expect it to work though I never tried it) is use the Kiali Server Helm Chart and use the [name value overrides](https://github.com/kiali/helm-charts/blob/master/kiali-server/values.yaml#L1-L2).

**Comment by jshaughn** [comment]
@joscha-alisch Can you explain your use case for having multiple Kiali instances in the same workspace?  It could help us understand better what we may want to support going forward.

**Comment by joscha-alisch** [comment]
Thank @jmazzitelli, @jshaughn :) 

Our use-case is as follows:
we maintain a PaaS in K8s that uses istio under the hood. We would like to give users the possibility to deploy their own Kiali instances that they can configure for their teams' specific needs. Now we might have people with apps in the same namespace but the need for different kiali config (different prometheus and jaeger for example).

The workaround would probably be to create one namespace per kiali config now :+1: (if you choose to not support this - which I can completely understand given your explanation)

**Comment by jmazzitelli** [comment]
It sounds like you want a kind of multi-tenant solution. This is what Maistra/Istio is all about and what Kiali Operator/Kiali works nicely with. But that requires each user with their own namespaces.

I'm not quite sure how your set up would work - different teams with different apps IN THE SAME NAMESPACE with the same Istio/control plane but with different Kiali instances?? What differences in the Kiali configuration do you make to get that to work the way you want (i.e. what settings in the Kiali CR do you modify to get Kiali to see one set of apps but not another set of apps in the same namespace?)

**Comment by jshaughn** [comment]
@joscha-alisch @jmazzitelli , Looking back at the last few responses, I'm not sure this is something we will likely support, and I think the namespace-per-kiali is likely the way to go.  Unless you think we should keep this RFE open I'm inclined to close it.
