### ISSUE TITLE
Kiali deployed using customized full name with kiali-server helm chart uses wrong role name

### ISSUE THREAD

**Issue by ethernoy** [kiali/kiali#3667]
**Describe the bug**
I used kiali-server helm chart to deploy kiali 1.29 with overridden fullname "kiali-test". The chart generated a role named "kiali-test-controlplane" on istio namespace. However the deployed kiali application seemed to be using the hardcoded "kiali-controlplane" role to gain access to istio secret resources, which resulted in rbac access denied due to invalid role binding when I was trying to see istio config from kiali.

**Versions used**
Kiali: 1.29.0
Istio: 1.8.1
Kubernetes flavour and version: 1.18.5 (vmware tanzu)

**To Reproduce**
1. Deploy kiali using full name different than "kiali" with kiali-server helm chart
2. Check from kiali console

**Expected behavior**
Correct role binding is generated, istio config can be viewed from kiali when using deploy full name other than "kiali"

**Comment by jmazzitelli** [comment]
@ethernoy can you provide the actual helm command you used to install?

**Comment by jmazzitelli** [comment]
Fixed in PR: https://github.com/kiali/helm-charts/pull/34
