### ISSUE TITLE
[regression] Graph Replay broken

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#3684]
I've tested on a separated PR but I can confirm that is broken in master too:

![image](https://user-images.githubusercontent.com/1662329/107363947-1fdea880-6adb-11eb-8608-6eb5233df1ee.png)

I've used the error-rates app.

Perhaps it's related to the recent work with new boxing for cluster + namespace, I haven't debugged more.

**Comment by jshaughn** [comment]
A regression in v1.29 release, investigating...
