### ISSUE TITLE
doing a patch release build did not build helm charts

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#3687]
We did a 1.29.1 patch build -- everything worked except the helm charts did not get built. Need to update Jenkinsfiles so helm charts are built with patch builds.

**Comment by israel-hdez** [comment]
I don't think this is a bug. Patch releases weren't supported even in the first iteration.
I'm re-tagging as enhancement, but yes I'll give this some priority.

**Comment by jmazzitelli** [comment]
First, we need to change the Makefile so the update targets do NOT do a build automatically. We only want the update targets to update the index metadata. If you want it to build another set of helm chart tarballs, you now must explicitly ask for it by specifically running the build targets. Here's the diff:

```diff
-.update-helm-repo-server: .build-helm-chart-server
+.update-helm-repo-server: .download-helm-if-needed
 
-.update-helm-repo-operator: .build-helm-chart-operator
+.update-helm-repo-operator: .download-helm-if-needed
```

Now to build a patch build, do this (this assumes `git fetch --all --tags` has been run and the `master` and `vX.Y` local branches have been pulled and are up to date with origin - if not, just make sure you do things like `git checkout -b vX.Y origin/vX.Y`):

```
git checkout vX.Y
make -e VERSION=vX.Y.Z clean build-helm-charts
git checkout master
make -e VERSION=vX.Y.Z update-helm-repos
git add -A
git commit -m "vX.Y.Z patch build"
git push origin/master
git tag vX.Y.Z origin/vX.Y
git push origin vX.Y.Z
```

**Comment by jmazzitelli** [comment]
@israel-hdez see the above comment for the commands the Jenkinsfile needs to run in order to build the patch build. First, we need this merged: https://github.com/kiali/helm-charts/pull/40

**Comment by jmazzitelli** [comment]
Re-opening. Still need Jenkinsfile changes.
