### ISSUE TITLE
Kiali operator with flux

### ISSUE THREAD

**Issue by rajivchirania** [kiali/kiali#3694]
I am trying to install kiali operator using flux which needs a helm release.
However the pod keeps failing to start with the below error:

Usage of /opt/kiali/kiali:
  -alsologtostderr
    	log to standard error as well as files
  -config string
    	Path to the YAML configuration file. If not specified, environment variables will be used for configuration.
  -log_backtrace_at value
    	when logging hits line file:N, emit a stack trace
  -log_dir string
    	If non-empty, write log files in this directory
  -logtostderr
    	log to standard error instead of files
  -stderrthreshold value
    	logs at or above this threshold go to stderr
  -v value
    	log level for V logs
  -vmodule value
    	comma-separated list of pattern=N settings for file-filtered logging

Below is my helm release file:

---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kiali-operator
  namespace: services
  annotations:
    fluxcd.io/automated: "false"
spec:
  helmVersion: v3
  releaseName: kiali-operator
  chart:
    git: ssh://blabla@bla.com
    path: bla
    ref: bla
  rollback:
    enable: false
  wait: true
  timeout: 600
  values:
    replicaCount: 1
    metrics:
      enabled: true
    debug:
      enabled: true
      verbosity: "1"
    image:
      repo: quay.io/kiali/kiali
      tag: "v1.22.0"
      pullPolicy: IfNotPresent
      pullSecrets: []

    watchNamespace: ""

    clusterRoleCreator: true

    cr:
      create: true
      name: kiali
      namespace: services
      spec:
        istio_component_namespaces: "istio-system"
        image_version: "v1.22.0"
        strategy: "anonymous"
        deployment:
          accessible_namespaces:
          - "**"
        ingress_enabled: true
        override_ingress_yaml:
          metadata:
            annotations:
              kubernetes.io/ingress.class: "nginx"
              cert-manager.io/cluster-issuer: "letsencrypt-production"
              cert-manager.io/acme-challenge-type: "dns01"
              cert-manager.io/acme-dns01-provider: "route53"
          spec:
            rules:
            - http:
                paths:
                - path: /kiali
                  backend:
                    serviceName: kiali
                    servicePort: 20001%

I am running istio version 1.6.0
Can someone help what i am doing wrong..

**Comment by jmazzitelli** [comment]
This isn't a bug - please discuss something like this in our [Discussions](https://github.com/kiali/kiali/discussions) page or [one of our other many user forums](https://kiali.io/contribute/#_talk_with_us) (googlegroup, IRC, Slack, etc).
