### ISSUE TITLE
Link to Application's Full Screen Graph From Application Page

### ISSUE THREAD

**Issue by asummers** [kiali/kiali#3696]
**Is your feature request related to a problem? Please describe.**
In the larger application graph, double clicking on an application brings you to a fully zoomed in view with all services that application talks to, for JUST that individual application. As one person on my team asked me yesterday: "How do I find that view? It's _by far_ the most useful view!". 

When on an individual application's overview from the Applications nav, there should be a way to get back to this view. While it has the mini graph in the middle pane, this tiny graph is (frankly) useless past 2-3 nodes even on larger monitors due to being 1/3 width minus menu, padding, margins, etc. The hamburger menu there has a "Show Full Graph" but this takes you to the same destination as `Graph` in the left hand nav (with many unrelated applications in larger clusters). 

From a UX perspective, I should not have to "zoom out" from the individual application's overview pane to the full graph to be able to navigate to a detail pane for the application whose overview I was just on. On a very large cluster graph, there may be hundreds of nodes in that view, so finding the application you were just on can be a real burden.

**Describe the solution you'd like**
Having some way to get full screen graph for the individual application graph from the individual application's overview would be much more ergonomic to users. 

I have no preference whatsoever how this is worked in, but since the "Show full graph" is already in the hamburger menu, an opt like "Show full screen graph" could maybe be added? I just think that being able to "stay with the application" would be useful here. 

To remove ambiguity with the other button, I additionally suggest "Show Namespace Graph" or similar change in verbiage; "Show Full Graph"'s behavior here feels non-intuitive to users in my experience; they expected the zoomed in graph from that considering the location of the button.  Since the graph is available on the left hand nav, I think the button could be removed entirely, but I do not wish to argue that point too much; more just posing it here as its general utility seems related to the issue at hand.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by lucasponce** [comment]
+1 on that, added to backlog.
I think the navigation between minigraph and main graph can be improved and play with the zoom and focus on a specific element.
