### ISSUE TITLE
mTLS locks confusion when mTLS is strict at mesh-level

### ISSUE THREAD

**Issue by xeviknal** [kiali/kiali#3707]
There has been an issue in Istio discuss about the mTLS lock on graph edges + masthead[1] 

It is not the first time that users don't get the following idea:
- when you have mTLS enabled at mesh-level
- then you don't have locks on every edge of the graph
- you only have broken locks on edges that mTLS is disabled on purpose

Lin sun has suggested a UX revision bc it seems a little bit confusing.

My proposal would be to just keep ONE lock display strategy: show the lock when one edge has mTLS traffic flowing. Remove the logic of showing broken locks when mesh-mtls is enabled.

[1] https://discuss.istio.io/t/mtls-is-not-working-between-services-istio-1-9-0/9710/9

**Comment by lucasponce** [comment]
> My proposal would be to just keep ONE lock display strategy: show the lock when one edge has mTLS traffic flowing. Remove the logic of showing broken locks when mesh-mtls is enabled.

+1

And play with the filters, perhaps when locks are showed, to improve the visualization of no locks.
I think the find/hide implements this, but it's not obvious for an early user.

I also think that the find/hide feature would benefit to have some "shortcuts", easy buttons to populate common expressions.

i.e. show me the edges that have no locks enabled, without forcing the user to learn new expressions

But that's a secondary discussion, probably off this issue.
