### ISSUE TITLE
Introduce Graph Find/Hide preset expressions

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#3708]
Graph Find/Hide feature is not adding all the potential if its capabilities due the present usability.

In the current form it requires a high learning curve for the user
![image](https://user-images.githubusercontent.com/1662329/108058015-b2d78f80-7053-11eb-997e-9dbea0b01f12.png)

In addition to the feature, Kiali would benefit to have a "shorcut" section where in a 1-click, user can populate the find/hide fields with correct expressions and let user to use more this feature.

As an example, a expression could be "Show unhealthy" in a single link/buttom placed [to be discussed with UX] and then as result the find/hide would be populated with expressions that user can edit later like:

![image](https://user-images.githubusercontent.com/1662329/108058782-ce8f6580-7054-11eb-9859-fdb097fe3051.png)

As similar as "Show unhealthy" there could be a set of well known/most used expressions that can be available with 1-click.

Today user needs to browse on the all tabs, read the text, copy it, try it, adjust, etc.

Not arguing to change that, but a pre-built feature can help here.

This feature is too "hidden" meaning it has a lot of potential.

**Comment by jshaughn** [comment]
Now that we have the UIDefaults server-side config I think this could be a more interesting feature.  We could pre-define some expressions but also users could configure their own and they would show up for all of the users.  I will add to the backlog.  Also, with this we may want to disable the browser "suggestions", not sure.  We'll have to see how things look.

**Comment by jshaughn** [comment]
I wasted some time dorking with the input boxes, trying to bring controls into the box, but it's not really worth it.  I think we can do this in a fairly straighforward way.  I'll promote this to the sprint backlog.
