### ISSUE TITLE
Install Istio Hack script is broken with Namespace parameter

### ISSUE THREAD

**Issue by pbajjuri20** [kiali/kiali#3714]
https://github.com/kiali/kiali/blob/master/hack/istio/install-istio-via-istioctl.sh

It has the default namespace: istio-system

running this command to install into a different namespace

./install-istio-via-istioctl.sh -n istio-system2

**Comment by jmazzitelli** [comment]
I can fix our script, but it won't matter because there is a bug in istioctl where it also cannot install in any other namespace other than istio-system! See: https://github.com/istio/istio/issues/30897
