### ISSUE TITLE
Curious why /vendor/* is not ignored in .gitignore?

### ISSUE THREAD

**Issue by christian-posta** [kiali/kiali#372]

**Comment by christian-posta** [comment]
I guess why i'm asking, whenever I do a build, it seems to change the entire vendor tree (lots of files) and becomes lots of noise.. would love to do a PR, but not sure what vendor changes to commit or exclude

**Comment by jmazzitelli** [comment]
To ensure consistent and fast builds, even for those just git-cloning and building. We had discussed this - could have gone either way - we decided to commit vendor files for 100% consistency and no need for someone to pull down deps.

If your vendor files are changing, I would have to ask why. There should be no need to run the "dep-update" or even "dep-install" make targets. The vendor/ files should not change.

Perhaps you can comment in here the commands you are running to build.

**Comment by christian-posta** [comment]
yah, not hitting that. thanks for the heads up on that thought!
