### ISSUE TITLE
Istio gateway not found when deployed as DaemonSet

### ISSUE THREAD

**Issue by hitman99** [kiali/kiali#3725]
**General remarks**

We switched from kubernetes deployment to daemonset for istio gateway(s) and Kiali is not able to find them since.

**Describe the bug**
Kiali is not able to detect any traffic coming in our out of the mesh for any service.

In UI it shows "Not Found" for all Istio ingress gateways

**Versions used**
Kiali: v1.27.0
Istio: 1.6.5
Kubernetes flavour and version: (AWS EKS v1.16.15)

**To Reproduce**
1. Change istio ingress gateway from deployment to daemonset
2. See error

**Expected behavior**
Kiali should also try to retrieve statuses for istio components deployed as daemonsets (primarily the ingress gateways)

**Comment by lucasponce** [comment]
@hitman99 take a look to this FAQ
https://kiali.io/documentation/latest/faq/#workload-is-not-found

But yes, probably Kiali is expecting to see it as a deployment rather than a daemonset for internal troubleshooting.

That case probably is not well covered.

cc @xeviknal

**Comment by hitman99** [comment]
I've checked the code and it looks like for Istio Core Components Kiali only queries `[]apps_v1.Deployment`: https://github.com/kiali/kiali/blob/master/business/istio_status.go#L90

**Comment by xeviknal** [comment]
yes, you are right. We only cover deployments. We can easily tackle this one. Thanks for opening the issue.

**Comment by xeviknal** [comment]
hi @hitman99,

I am approaching this one. Could you please show me your way to install the ingress as a DaemonSet? I'd like to make sure we are covering your needs. Thanks.
