### ISSUE TITLE
Consider using tcp_received telemetry for graph generation

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#3730]
It's something I often struggle with when testing with kafka. Wrt. TCP, the graph uses only tcp_sent metric, not tcp_received. I think both of them should be used.

To understand better, let's consider this screenshot:
![Capture d’écran de 2021-02-23 11-07-24](https://user-images.githubusercontent.com/2153442/108828660-6a761f80-75c7-11eb-82c4-bdaea123d4e9.png)

It shows TCP telemetry of my workload "ball", which connects to Kafka, and subscribes to a topic.
As you can see, it emits very few data to kafka (must be some kind of ping) but however receives a lot. When choosing a narrow time frame in the graph, like last 1 min, there is good chances that there was no telemetry on "tcp_send". Because my kafka is off mesh, it's a service entry, it doesn't generate telemetry of its own. So the parity that exists between "send" and "receive" when all workloads are in the mesh, doesn't exist here when a service entry is used. Because of that, often I don't see the edges between Kafka and its consumers, I have to increase the time span in order to see them.

![Capture d’écran de 2021-02-23 11-16-40](https://user-images.githubusercontent.com/2153442/108829621-af4e8600-75c8-11eb-9ee5-0efda2376b60.png)

So perhaps it's possible to consider using tcp_receive for graph building, even if it's often (but not always) redundant with "tcp"send".

**Comment by jshaughn** [comment]
@jotak  It's a trade-off between potentially incomplete data and the cost of ensuring complete data.  We already need to make 3 TCP queries per namespace for the main graph-generation.  And potentially more depending on the appenders that need to run.  The idea of doubling the queries is not very attractive.    I suppose it could always be made configurable.   If using a single metric I do wonder if we should be using received_bytes as opposed to sent_bytes, as perhaps there is more received data than sent data, in general.  I suppose an argument could be made that we'd just be reversing the problem.   Still, I don't think I'd like to see us double the TCP query load (which would increase the total queries by a third) on every graph generation.

**Comment by jotak** [comment]
Sure, I understand. The workaround for users facing this issue would be, whenever possible, to move the external service inside the mesh (obviously it won't always be possible).

**Comment by jshaughn** [comment]
@jotak What do you think about switching to received_bytes as our default metric and possibly also making it configurable to use sent_bytes OR received_bytes?  And then, if users demand it, potentially an option for both?

**Comment by jotak** [comment]
It would be nice if it can be configurable, yes.
Though for the default, I'm not sure if received_bytes is better. For instance it could then miss requests to databases, which is probably the most common use case.

**Comment by jshaughn** [comment]
related: https://github.com/istio/istio/issues/32399

**Comment by jshaughn** [comment]
A similar thread is in progress in https://github.com/kiali/kiali/issues/4070 regarding gRPC.  The issue there is that streaming gRPC requests can be long-running and as such the request rates can be very small, in effect not showing up at all for a shorter period.  There are additional gRPC metrics for message counts, which are typically much higher.

The way Kiali deals with graph generation works well when there is a single rate for the edge.  In the issue we talk about sent-bytes vs received-bytes.  This may be the time to add options in kiali graph generation that allows the rate to be more flexible (and also to potentially omit unwanted protocols from a particular graph generation).   For TCP we could generate the rate based on:

sent bytes
received bytes
total bytes (sent+received)
none (no tcp edges requested)

The advantage of the `total` option is that it would pick up all of the traffic, the rate is less granular but would show all active edges.

I may play with this approach a little.   An analogous approach may be useful for gRPC.
