### ISSUE TITLE
[QE] This is only a test

### ISSUE THREAD

**Issue by mattmahoneyrh** [kiali/kiali#3749]

**Comment by mattmahoneyrh** [comment]
Comment-1

**Comment by jshaughn** [comment]
@lucasponce I believe this can be deleted in the Notifications area but I don't seem to have privs, maybe you can do it.

**Comment by lucasponce** [comment]
No need to delete :).
Github has a policy to store all what we store.

What I typically do for github testing is to use a pet project in my user
https://github.com/lucasponce/pet-backend

For basic learning and check, once it's ok, I can apply those changes into Kiali repo.
