### ISSUE TITLE
Support for Istio prelim 1.0

### ISSUE THREAD

**Issue by dcberg** [kiali/kiali#375]
The docs state that kiali supports Istio version 0.8+. I'm using a daily build of Istio. 

https://gcsweb.istio.io/gcs/istio-prerelease/daily-build/release-1.0-20180716-12-45/

I see the following error in the kiali UI.

Istio version root@8d0ac395dc73-docker.io/istio-release-1.0-20180716-12-45-6a7623f34d960de1e74f0cb1868abe73ee635ee7-dirty-Modified is not recognized, thus not supported.

How can I test kiali against istio prelim 1.0?

**Comment by jmazzitelli** [comment]
Istio v0.5.0 and master branch supports 0.8.0 only. If you are running a nightly istio 1.0 release, build and test with the istio-1.0 branch of both kiali and kiali-ui repos ... istio 1.0 isn't fully supported yet, we are actively working on getting kiali to work with istio 1.0 - currently that work is being done in the istio-1.0 branches:

kiali: https://github.com/kiali/kiali/tree/istio-1.0
kiali-ui: https://github.com/kiali/kiali-ui/tree/istio-1.0

**Comment by gyliu513** [comment]
@jmazzitelli Does this can catch up Istio 1.0 release?

**Comment by jmazzitelli** [comment]
@gyliu513 it is very close. Still working on some issues getting the graph correct with the new telemetry. The details pages can show the new istio 1.0 objects. If you build those two branches you should be able to at least run it with istio 1.0 and it not blow up and it will show (mostly) valid data :)

**Comment by gyliu513** [comment]
Thanks @jmazzitelli , hope we can update the Kiali version before Istio 1.0 release, only two days left :-)

**Comment by sebastien-prudhomme** [comment]
@jmazzitelli As defaults dashboards have changed in Istio 1.0, can you look at this istio/istio#7498 

Either Kiali changes its default configuration, or i keep the Istio PR. What do you prefer?

**Comment by jmazzitelli** [comment]
@sebastien-prudhomme I think that istio PR is fine - even if Kiali changes the default config, that istio PR is still a good addition as it would allow for customization in the future in case this kind of thing comes up again.

**Comment by denniseffing** [comment]
Latest dev build supports Istio v1.0. See #408.

Any update on an upcoming official release for Istio v1.0 support?

**Comment by pilhuhn** [comment]
@denniseffing We are testing this build to make sure there is no (obvious) breakage.
Once things look good, we will release.
So if you are brave, grab the `:latest` image from https://hub.docker.com/r/kiali/kiali/tags/ and help us testing (and report back your findings).

**Comment by pilhuhn** [comment]
We have released v 0.6.0 on Friday and after additional testing also tagged it as 'istio-release-1.0'. The helm charts in Istio should now install that (you may need to re-run), so I see this issue as resolved.

If you find issues with the released bits, please open a new issue.
