### ISSUE TITLE
Traffic Animation missed when switched from Graph type

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#3755]
I could see in master some glitch in the traffic animation:

![image](https://user-images.githubusercontent.com/1662329/110466959-b3a19580-80d6-11eb-86dd-b448fd2c9005.png)

The steps to reproduce were:
- Enable traffic animation -> graph renders correctly the animation
- Change to a different page or change the graph type -> in some cases animation looks "broken" as showed in the capture

**Comment by jshaughn** [comment]
Seems like something maybe doesn't get initialized.  Workaround is to disable/enable.  I'll take a look unless someone grabs it before me.

**Comment by jshaughn** [comment]
I've been playing with this for a while and I can't pin down the problem.  Very strange, starting to think it's a cytoscape issue.
