### ISSUE TITLE
Overview Health Filter Broken

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#3757]
Happens on master.

In Overview page, filtering by health is broken.
Filter by Healthy should show namespaces with healthy apps only, but it show all:
![Screenshot from 2021-03-09 17-35-02](https://user-images.githubusercontent.com/604313/110505199-35f18000-80fe-11eb-8fd8-831c889a1b7e.png)

Filter by Failure, shows also healthy namespaces:
![Screenshot from 2021-03-09 17-35-45](https://user-images.githubusercontent.com/604313/110505290-4e619a80-80fe-11eb-97e3-f9c3c9033f86.png)

**Comment by lucasponce** [comment]
Ouch, a regression ? I think we fixed that a couple of PRs before.

Thanks @hhovsepy I'll take a look.
