### ISSUE TITLE
[operator] conversion of node_selector to snake_case prevents us from targeting specific nodes

### ISSUE THREAD

**Issue by mrtnfchs** [kiali/kiali#3760]
I've come across multiple issues, most (if not all) of them already closed as a `won't do` but I was wondering if that's true for all use-cases or do you still consider making exceptions. In our case, we've tagged our nodes with `worker-class` label and depending on the label Kiali should land on a given set of nodes. Unfortunately due to the auto-conversion to snake_case the Kiali deployment will search for nodes with the label `worker_class` which doesn't exist and as a result the pods will never start. Is there a way to work around this problem, just like was done for the annotations ? (eg: https://github.com/kiali/kiali/issues/2243, https://github.com/kiali/kiali/pull/2248) or does it fall under `won't do` similar to issues like https://github.com/kiali/kiali/issues/3000 ?

**Comment by mrtnfchs** [comment]
We are provisioning the kiali-operator via it's helm chart and we are deploying the Kiali CR as part of it. Below you can find the  configuration we currently use.

```
nodeSelector:
  worker-class: private
podAnnotations: {}
env: []
tolerations: []
resources: {}
affinity: {}
replicaCount: 1
priorityClassName: ""

metrics:
  enabled: true

debug:
  enabled: true
  verbosity: "1"
  enableProfiler: false

watchNamespace: ""
clusterRoleCreator: true
onlyViewOnlyMode: false

cr:
  create: true
  name: kiali
  namespace: istio-system
  spec:
    istio_namespace:  istio-system
    istio_component_namespaces:
      prometheus: kube-prometheus-stack
    auth:
      strategy: "anonymous"
    deployment:
      node_selector:
        worker-class: private
      replicas: 2
      accessible_namespaces: ["**"]
      namespace: istio-system
      ingress_enabled: false
    server:
      web_fqdn: https://internal.example.com/kiali
    external_services:
      grafana:
        enabled: false        
      istio:
        component_status:
          enabled: true
          components:
          - app_label: istiod
            is_core: true
          - app_label: istio-egressgateway
            is_core: true
        config_map_name: "istio"
        istio_identity_domain: "svc.cluster.local"
        istio_injection_annotation: "sidecar.istio.io/inject"
        istio_sidecar_annotation: "sidecar.istio.io/status"
        url_service_version: ""
      prometheus:
        component_status:
          app_label: "prometheus"
          namespace: kube-prometheus-stack
          is_core: true
        url: http://kube-prometheus-stack-prometheus.kube-prometheus-stack.svc.cluster.local:9090
      tracing:
        enabled: false
```

The Ansible SDK is auto-converting `deployment.node_selector.worker-class` to snake_case and as a result the deployment spec looks for `spec.nodeSelector.worker_class: private` and as a result it can't find a node that matches the node selector nor can it autoscale and add nodes because it will never be able to meet the criteria. Thanks

**Comment by jmazzitelli** [comment]
Good catch. We can fix this. I'll put it on the backlog for this sprint.

**Comment by jmazzitelli** [comment]
Note: The workaround for now is to use labels used by node_selector to not include separators such that the conversion to snake_case is essentially a no-op.
