### ISSUE TITLE
Add support for ServiceEntry objects from Create New Istio Config form

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#3763]
ServiceEntry is not supported from 
![image](https://user-images.githubusercontent.com/1662329/110650860-33a12b80-81bb-11eb-90ab-4b53fcc0fa33.png)

As similar use case as Gateways, Kiali should add a minimum support to generate this type of objects.

Other Istio resources as VirtualServices/DestinationRules are generated from Kiali as part of the high level scenario driven by Wizards.

**Comment by lautou** [comment]
Any update of this?

**Comment by jshaughn** [comment]
@lautou no work started.  if you have any desire to contribute we could help guide you.  Given the current backlog this likely won't be done in the very near-term.

**Comment by lautou** [comment]
Opportunity to implement this in PR kiali/kiali-ui#2109 ?

**Comment by lucasponce** [comment]
@lautou that refactoring was also designed to add new objects easily, re-using existing patterns.
I have something drafted that I'll try to consolidate, but in a separate PR as it needs also backend work.

I'll take this on my todo as I may have something for reviewing soon.
