### ISSUE TITLE
Allow Kiali Graphs to show EgressGateway traffic to ServiceEntry

### ISSUE THREAD

**Issue by alvarogomez93** [kiali/kiali#3765]
**Is your feature request related to a problem? Please describe.**
Right now Kiali graph's don't have a way to show traffic going to ServiceEntry from the Implicitly stated EgressGateway. 

**Describe the solution you'd like**
EgressGateway should appear as an app in Kiali graph with outbound traffic to the ServiceEntry

**Additional context**
Example of expected workflow:

![Diagrama en blanco(1)](https://user-images.githubusercontent.com/2835834/110783580-eda2a100-8268-11eb-873a-c2e9cd8ce9c7.png)

**Comment by lautou** [comment]
Please note this enhancement will allow to bring coherence when displaying the gateways in the mesh.
Currently we can see flow from the istio-ingressgateway but not to the egressgateway. This is confusing.

**Comment by jmazzitelli** [comment]
Did you check if the Istio telemetry exists? Kiali visualizes the telemetry that Istio provides (Kiali cannot produce that telemetry between egress and service entries if none exists) - if there is no telemetry here, then you will need to create a bug report on upstream Istio project, not kiali. If you *do* see Istio telemetry that is *NOT* visualized by Kiali, then this bug report can remain.

For more details on how to investigate the Istio telemetry see https://kiali.io/documentation/latest/faq/#prometheus

Please check that - if there is no telemetry at all between those components (egress and serviceentry) then we should close this issue and you should create an issue in upstream Istio to let them know about the missing telemetry.

**Comment by jmazzitelli** [comment]
cc @jshaughn

**Comment by jshaughn** [comment]
@lautou Do you have a small example mesh for the configuration you're asking about?  As mentioned above, the first question is whether Istio is generating the necessary telemetry, and that can very much depend on the version of Istio, are we talking about the latest istio (1.9)?

**Comment by lucasponce** [comment]
I've talked with @jmazzitelli yesterday about this one.
By default it seems that Istio telemetry doesn't collect the egress workload when there is outbound traffic through a ServiceEntry.

So, that would be something to address first, otherwise perhaps Kiali could show the correct flow per request if tracing is instrumented.

But I think that this feature would need at lest that change in the backend telemetry.

**Comment by lautou** [comment]
@jshaughn Issue was raised in RHOSM 2.0.2 (Istio 1.6).

**Comment by lautou** [comment]
@jshaughn @alvarogomez93 has mentionned [above](https://github.com/kiali/kiali/issues/3765#issue-829076890) the target we are expecting.

**Comment by lucasponce** [comment]
@lautou @alvarogomez93 also a side note that this is an upstream issue to discuss about a feature request.
Any product / customer information about environment or context, please use the JIRA OSSM system.

As this discussion is interesting for any Istio / Kiali user in general was raised here :-).

**Comment by rtttech** [comment]
include ingress gateway to service entry traffic

**Comment by jshaughn** [comment]
> include ingress gateway to service entry traffic

@rtttech Are you sure ingress->serviceEntry is not already working?  If you aren't seeing in your current version please try with https://github.com/kiali/kiali/releases/tag/v1.32.0-snapshot.0.

**Comment by rtttech** [comment]
> > include ingress gateway to service entry traffic
> 
> @rtttech Are you sure ingress->serviceEntry is not already working? If you aren't seeing in your current version please try with https://github.com/kiali/kiali/releases/tag/v1.32.0-snapshot.0.

The release we used is the version packaged with istio 1.8. We will try the v1.32.0

**Comment by jshaughn** [comment]
@rtttech Any feedback on this with v1.32 or later?

**Comment by lucasponce** [comment]
I've been revisiting this one and I think it could move forward.
Indeed it sounds more a use case of the recent work done for the ingress traffic.

Let's take an example from typical bookinfo and https://istio.io/latest/docs/tasks/traffic-management/egress/egress-gateway/:
![image](https://user-images.githubusercontent.com/1662329/128855338-b1e21fbe-eacf-4a26-9035-d9813e1f87a7.png)

So, we could use this issue to implement the counterpart of the "ingress" flow, but for the "egress":

- The "egress" workload may have a badge with the same "hosts" resolution defined in the Gateway.
- ServiceEntry nodes may have a VS badge when present.

I think these two features are doable and should be an extension of the current work, perhaps I may miss some cornercase but implement those it will help to identify the requested scenario without need to check in the telemetry if a SE is under a GW or not.

**Comment by israel-hdez** [comment]
@lucasponce I think the feature requested in the main comment, and also the hosts list and the badging can be done on the same effort. 

Although, I will need to re-check the telemetry that is generated for these cases. If I understand correctly previous comments, Istio can hide the Egress gateway from telemetry if there is a ServiceEntry. So, if it is hidden, we won't be able to show it :-/

Anyway, feel free to assign it to me and add it to the sprint, and I will check what can be done.

**Comment by lucasponce** [comment]
> Although, I will need to re-check the telemetry that is generated for these cases. If I understand correctly previous comments, Istio can hide the Egress gateway from telemetry if there is a ServiceEntry. So, if it is hidden, we won't be able to show it :-/

Yes, I think telemetry has this limitation, but extending the work for the ingress use cases to the egress ones will add visibilty.
Also, as there are ServiceEntry that may be affected for a VS, it could be good to extend the badge as well.

With those changes it will answer "which egress workload" routed a particular ServiceEntry.

Thanks for the clarification, I've added this to the backlog to confirm that it doesn't have a blocker to progress.
