### ISSUE TITLE
Deployment models: to support managed control plane

### ISSUE THREAD

**Issue by feuyeux** [kiali/kiali#3772]
**Is your feature request related to a problem? Please describe.**
Thinking about the Kiali topoloy, it's strong dependency with istiod and assumed that Kiali deploy with istiod in a same kubernetes cluster. And the interfaces, client and cache are not decoupled from kube for data plane cluster and mesh for control plane cluster.
Indeed, ASM([Alibabacloud ServiceMesh](https://www.alibabacloud.com/product/servicemesh)) has a different topology, which is illustrated below. 
![image](https://user-images.githubusercontent.com/769711/111264187-0abce280-8662-11eb-93bc-a48fa823af98.png)

Like istio1.8+ primary-remote, we provided a managed control plane to our customers, and,  in the managed cluster(primary cluster), considering security and scalability, it's not recommended to let the components to access external network. So, Kiali should not be deployed on primary cluster, and it should be deployed in users' data plane(remote cluster). Furthermore,  we cannot collect user's data, so prometheus should be deployed on remote. Therefore, kiali and prometheus are deployed in a same cluster with users' pods and services.

**Describe the solution you'd like**
To let kiali support this topology, we need a set of decouping interfaces defined clearly to separate accessing primary(istio) and remote(kubernetes). We should use mesh_interfaces to visit primary cluster to CRUD service mesh api, and use kube_interfaces to visit remote cluster to CRUD kubernetes api. In addtion, we need to use mesh_client and mesh_cache in network layer to connect to primary api-server, and to use kube_client and kube_cache to talk with remote cluster.

**Comment by lucasponce** [comment]
Thanks @feuyeux for your inputs.
Indeed, this is an area of active development and it helps us to drive the multicluster/federation epics which we are working on.

Technically speaking, when developing it's normal to have a external Kiali decoupled from the control plane, just telling Kiali where to connect.

Side comment, would you like to actively collaborate on this effort from ASM perspective ?

Perhaps it's a nice area where we can join forces and work together in these efforts as well.

**Comment by feuyeux** [comment]
Thanks @lucasponce for your reply.
I like to learn more about that. If our community starts this work, please let me know more details, e.g. which branch developing.
I did some changes from branch v1.31, which were passed all tests by executing the below script:
```bash
export PRIMARY_KUBE_CONFIG=$HOME/shop_config/kubeconfig/asm_production
export REMOTE_KUBE_CONFIG=$HOME/shop_config/kubeconfig/ack_production
export HTTP_TIMEOUT=3
export K8S_TIMEOUT=5
make test
```
And these changes work well basically on my development PC, to talk with the production Kubernetes(ack) cluster and ServiceMesh(asm) cluster.
There's a specific implmentation, when kiali is in cluster, to obtain service mesh cluster's kubeconfig, I used alibabacloud special api. I wish community should design a better api to let vendors implment how to retrieve and load the kubeconfig.
Here's [my commit](https://github.com/kiali/kiali/pull/3773)

**Comment by lucasponce** [comment]
Update:
This issue is pretty valid, it's being discussed under the link https://github.com/kiali/kiali/discussions/4081 and @feuyeux work will be taken as a model as well.

The discussion is not yet finished as the design needs to solve some aspects proposed.
I'll keep this one open, but probably soon we'll create a new epic that will incorporate this one.

**Comment by jshaughn** [comment]
Closing this in favor of the current work for working (in a more limited way) without istiod access.  And also Multi-cluster support:

See #5626 
See #5618
