### ISSUE TITLE
move our demo images to quay.io

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#3777]
We should be publishing all our demo images to quay.io and have our example scripts and instructions pull from quay.io.

Putting stuff on docker.io is now causing problems due to their rate limiting. I just tried to install the travel agency demo and got this:

```
 Failed to pull image "kiali/demo_travels_travels:v1": rpc error: code = Unknown desc = Error initializing source
docker://kiali/demo_travels_travels:v1: Error reading manifest v1 in
docker.io/kiali/demo_travels_travels: toomanyrequests: You have reached your pull rate limit.
You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```

Moving to quay.io will solve this problem.

The same is true of the error rates demo. And probably other demos as well - but those two for sure I know need to be moved to quay.io.

**Comment by lucasponce** [comment]
The rate limits are per user ?
AFAIK the same will happen to any other Istio addon or component, or are they being pulled from a different repo ?

**Comment by lucasponce** [comment]
> Anonymous and Free Docker Hub users are limited to 100 and 200 container image pull requests per six hours.

Does an eventual user need to increase that ?

It sounds that you are hitting this in the context of a CI/CD scenario perhaps ?

**Comment by jmazzitelli** [comment]
As I understand it, you (the user) have to pay a subscription fee in order to pull more than 200 images per six hours if you authenticated with docker.io when you do the "docker pull". If your cluster is pulling them directly (i.e. you create a Deployment and its pods pull the images down directly from docker.io) then it is even worse -- it is 100 images because you most likely did not set up your cluster to pull via your docker.io authenticated user account (so it is pulling as an anonymous user) - see https://blog.container-solutions.com/dealing-with-docker-hub-rate-limiting for details

Yes, the same thing can happen with other Istio addons/components but this is why our hack script explicitly pulls from gcr now (and not the default docker.io) - see: https://github.com/kiali/kiali/blob/v1.31.0/hack/istio/install-istio-via-istioctl.sh#L30 -- upstream Istio publishes the images on both docker.io and gcr - we elect to pull from gcr. Upstream Istio may opt to not publish on docker.io in the future.
