### ISSUE TITLE
Kiali for non istio based service mesh or for vanila envoy configured through customized xds.

### ISSUE THREAD

**Issue by rajeevtech** [kiali/kiali#3778]
**Is your feature request related to a problem? Please describe.**
 We have created servicemesh without using istio create our own control plane as per organization need but for better visualization of call flow we are very impressed with a Kiali so is there any chance we can use it without istio.

**Additional context**
Add any other context or screenshots about the feature request here. If it is about a new design, please attach a drawing of a potential solution.
For backend changes also describe how one could test the new feature and how it impacts display on the UI.

**Comment by jmazzitelli** [comment]
> is there any chance we can use it without istio.

This has actually been requested before - see https://github.com/kiali/kiali/issues/1679

The short answer is "no"

Kiali is specifically tied to Istio - it requires specific Istio telemetry and specific Istio resources to work.
