### ISSUE TITLE
Cannot load the graph: deployments.apps "istiod" not found

### ISSUE THREAD

**Issue by ahsanqaisar** [kiali/kiali#3782]
Describe the bug
I am getting "Sorry, there was a problem. Try a refresh or navigate to a different page." when click on object under Application Tab in Kiali UI

Kiali UI
1.31.0 (faa0a96400cd1b712a13a29f65cc34c270eed386)

Kiali Server
v1.31.0 (26ce458)

Kiali Container
v1.31.0

Components
Istio
1.8.1

Prometheus
2.22.0

Kubernetes
v1.18.12-gke.1210

Deployment Tool: Helm v3.5

I am using kiali-operator v1.31 for deployment 

Here is my external service configuration of Istio in kiali CR 

```    
external_services:
  istio:
    component_status:
      enabled: true
      components:
        - app_label: istiod
          is_core: true
          namespace: istio-system
        - app_label: istio-ingressgateway
          is_core: true
          namespace: istio-system
        - app_label: istio-egressgateway
          is_core: false
          namespace: istio-system
    config_map_name: istio-1-8-1
    url_service_version: http://istiod-1-8-1.istio-system:15014/version
    envoy_admin_local_port: 15000
    istio_identity_domain: "svc.cluster.local"
    istio_injection_annotation: "sidecar.istio.io/inject"
    istio_sidecar_annotation: "sidecar.istio.io/status"
```

Kiali Console complains about component status of the istio-egressgateway which is expected because we are using egress gateway.

<img width="547" alt="Screen Shot 2021-03-17 at 12 31 41 PM" src="https://user-images.githubusercontent.com/73361295/111503065-cb9f9780-871c-11eb-8e61-d46bf2070c2d.png">

I can see that kiali recognizes the Istio version i.e. 1.8.1 which means that istio version url config is working but whenever I try to access the Graph on Kiali console, it triggers this exception in the logs 

```
2021-03-17T16:32:57Z DBG Skipping unexpected log line []
2021-03-17T16:32:57Z DBG Skipping unexpected log line []
2021-03-17T16:33:02Z ERR deployments.apps "istiod" not found: goroutine 3130953 [running]:
runtime/debug.Stack(0xc000a20960, 0x23, 0xc0034cc4a0)
/usr/local/go/src/runtime/debug/stack.go:24 +0x9f
github.com/kiali/kiali/handlers.handlePanic(0x1d61a20, 0xc0001efe30)
/home/fedora/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/handlers/graph.go:86 +0x159
panic(0x18455a0, 0xc0034cc4a0)
/usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/kiali/kiali/graph.CheckError(0x1d1e060, 0xc0003e8aa0)
/home/fedora/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/graph/util.go:38 +0x9a
github.com/kiali/kiali/graph/telemetry/istio/appender.IdleNodeAppender.AppendGraph(0xc00267211a, 0x8, 0xc00ca9af86fe0001, 0xc0011fdf50, 0xc000528fa0, 0xc001e37400)
/home/fedora/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/graph/telemetry/istio/appender/idle_node.go:58 +0x3d7
github.com/kiali/kiali/graph/telemetry/istio.BuildNamespacesTrafficMap(0xc0011fd920, 0x0, 0xc0026ab620, 0x6, 0x6, 0x100, 0xc0011fd500, 0x13a52453c000, 0xc00267211a, 0x8, ...)
/home/fedora/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/graph/telemetry/istio/istio.go:48 +0x282
github.com/kiali/kiali/graph/api.graphNamespacesIstio(0xc0024a0780, 0xc0016e8e80, 0x1b03e15, 0x9, 0x1afec47, 0x5, 0x1afe07c, 0x4, 0x13a52453c000, 0xc00267211a, ...)
/home/fedora/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/graph/api/api.go:44 +0xb8
github.com/kiali/kiali/graph/api.GraphNamespaces(0xc0024a0780, 0x1b03e15, 0x9, 0x1afec47, 0x5, 0x1afe07c, 0x4, 0x13a52453c000, 0xc00267211a, 0x8, ...)
/home/fedora/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/graph/api/api.go:26 +0x178
github.com/kiali/kiali/handlers.GraphNamespaces(0x1d61a20, 0xc0001efe30, 0xc000eb5900)
/home/fedora/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/handlers/graph.go:51 +0x158
net/http.HandlerFunc.ServeHTTP(0x1bcde48, 0x1d61a20, 0xc0001efe30, 0xc000eb5900)
/usr/local/go/src/net/http/server.go:2042 +0x44
github.com/kiali/kiali/routing.metricHandler.func1(0x1d61a20, 0xc0001efe30, 0xc000eb5900)
/home/fedora/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/routing/router.go:90 +0xa3
net/http.HandlerFunc.ServeHTTP(0xc0002def00, 0x1d61a20, 0xc0001efe30, 0xc000eb5900)
/usr/local/go/src/net/http/server.go:2042 +0x44
github.com/kiali/kiali/handlers.AuthenticationHandler.Handle.func1(0x1d61a20, 0xc0001efe30, 0xc000eb4900)
/home/fedora/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/handlers/authentication.go:622 +0x1ee
net/http.HandlerFunc.ServeHTTP(0xc000150de0, 0x1d61a20, 0xc0001efe30, 0xc000eb4900)
/usr/local/go/src/net/http/server.go:2042 +0x44
github.com/kiali/kiali/server.plainHttpMiddleware.func1(0x1d61a20, 0xc0001efe30, 0xc000eb4900)
/home/fedora/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/server/server.go:127 +0x6c
net/http.HandlerFunc.ServeHTTP(0xc000528f60, 0x1d61a20, 0xc0001efe30, 0xc000eb4900)
/usr/local/go/src/net/http/server.go:2042 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000434840, 0x1d61a20, 0xc0001efe30, 0xc000eb4500)
/home/fedora/workspace/kiali-workflow/kiali-release/pkg/mod/github.com/gorilla/mux@v1.7.4/mux.go:210 +0xd3
github.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1(0x1d61660, 0xc0003d0700, 0xc000eb4500)
/home/fedora/workspace/kiali-workflow/kiali-release/pkg/mod/github.com/!n!y!times/gziphandler@v1.1.1/gzip.go:336 +0x225
net/http.HandlerFunc.ServeHTTP(0xc0002a0720, 0x1d61660, 0xc0003d0700, 0xc000eb4500)
/usr/local/go/src/net/http/server.go:2042 +0x44
net/http.(*ServeMux).ServeHTTP(0xc00014f380, 0x1d61660, 0xc0003d0700, 0xc000eb4500)
/usr/local/go/src/net/http/server.go:2417 +0x1ad
net/http.serverHandler.ServeHTTP(0xc0004480e0, 0x1d61660, 0xc0003d0700, 0xc000eb4500)
/usr/local/go/src/net/http/server.go:2843 +0xa3
net/http.(*conn).serve(0xc002514500, 0x1d660e0, 0xc00277c640)
/usr/local/go/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
/usr/local/go/src/net/http/server.go:2969 +0x36c
2021-03-17T16:33:08Z ERR container istio-proxy is not valid for pod kiali-855f6647c7-qtnv8
```

and at the same time,  this is what I get on the console

<img width="1733" alt="Screen Shot 2021-03-17 at 12 32 28 PM" src="https://user-images.githubusercontent.com/73361295/111503137-df4afe00-871c-11eb-85ec-237fffd6d762.png">

**Comment by jshaughn** [comment]
Will look at this but it seems related to the Idle Node detection.  If you disable that Display option you may be able to proceed.

**Comment by xeviknal** [comment]
@ahsanqaisar are you running an istio canary deployment? I see you are using the:
```
config_map_name: istio-1-8-1
```

The support of the istio canary deployments is still in progress. There will be updates pretty soon on this field.
Check this issue: https://github.com/kiali/kiali/issues/2884

I might be guessing too much :sweat_smile: Let me know if I missed something please.

**Comment by ahsanqaisar** [comment]
Yes @xeviknal that is correct! we are using a custom Istio version reason we do not have deployment named as istiod. Our Istio deployment is istiod-1-8-1

**Comment by xeviknal** [comment]
@ahsanqaisar thanks to confirm my hypothesis. I'll re-prior this one since it starts to be more and more people using the canary deployments. Thanks again

**Comment by ahsanqaisar** [comment]
Hey @xeviknal isn't this going to solve the issue of a custom revision? https://github.com/kiali/kiali-operator/pull/126/commits/afb65418cdf56e01c7134922d8f0328762ceab4f

**Comment by xeviknal** [comment]
No, it won't. The code fixing this scenario doesn't exist just yet. That line of code was never released. It was part of a daily job prior kiali 1.24 (and didn't fix your scenario).

**Comment by ahsanqaisar** [comment]
yeah that correct! I see that the code is part of the snapshot and never got merged in any release. 

Thanks for the info @xeviknal. Hoping for a quick resolution.

**Comment by jshaughn** [comment]
OK, catching up on this one and I see that the graph generation problem is just a symptom of the fact that we don't yet support canary releases.  This isn't really a bug and so I will close the issue.  Please track the progress of #2884.

cc @jmazzitelli , please take a look at the comment history here.

**Comment by xeviknal** [comment]
@ahsanqaisar Do you have the 'idle nodes' option in the graph dropdown selected? This option triggers a fetch on the deployments (looking up for the `istiod` deployment). If you disable the option, it might help.
Anyway, this just a workaround and shouldn't definitely be a solution. We'll work on that.

**Comment by ahsanqaisar** [comment]
@xeviknal spot on! It was selected by default. When I removed it, It worked. Is there a way to turn it off by default? because when I remove the option, it displays the full graph rather than showing the selected workload.

**Comment by jmazzitelli** [comment]
> Is there a way to turn it off by default?

There isn't (unless its a query string parameter and you bookmark it (I'm not sure if that setting is a query string or not))

But that sounds like a good enhancement to what [we already have](https://github.com/kiali/kiali-operator/blob/master/deploy/kiali/kiali_cr.yaml#L672-L674). There is a way to show only certain namespaces by default. I think we should expand that to support any option that has a default - it would be nice to override all defaults for just this reason.

@jshaughn how hard would it be to expand that feature? We should have it by just specifying, say, the redux name in the  Kiali CR and define the defaults like that (this is probably a separate issue we should write up).

I'm thinking something like:

```
ui_defaults:
  redux:
    the_redux_name: default1value
    anotherReduxProperty: "some default override"
```

**Comment by jshaughn** [comment]
@jmazzitelli the Idle Nodes Display option is already off by default.  Perhaps @ahsanqaisar had it enabled in a bookmarked URL.  I don't think anyone would like it on by default, and so I don't think we need to add it to UI defaults.

**Comment by ahsanqaisar** [comment]
No I haven't bookmarked it. It is ON by default for me 

![image](https://user-images.githubusercontent.com/73361295/112013534-7b4f7d80-8b00-11eb-8e35-ca4e56513ea7.png)

**Comment by ahsanqaisar** [comment]
@jshaughn you are right! it is not ON by default when you navigate to Graph from the home page through the left pane but If I navigate it from the individual workload, it is ON by default. Here is the snippet for your reference. 

![image](https://user-images.githubusercontent.com/73361295/112014486-50b1f480-8b01-11eb-80c3-56418c1a2a8d.png)

**Comment by jshaughn** [comment]
@ahsanqaisar Ah, you are right!  We did that because we were afraid the node may not be visible in the graph w/o if it was "idle".  Hmmm.  We may need to change that behavior, I don't think many folks want to see the idle nodes as a side-effect.  Probably better to just throw an informational message if the node is not in the graph.

**Comment by ahsanqaisar** [comment]
yeah make sense! 

sorry but just a quick question - which node are you referring to? cluster node or Istiod pod ?

**Comment by xeviknal** [comment]
Re-opening the issue since we can consider this is a bug not a "canary upgrade" scenario support case.

**Comment by jshaughn** [comment]
@xeviknal, what's the bug and what's your plan?

**Comment by xeviknal** [comment]
The bug is that kiali refers to `istiod` deployment: 

> Cannot load the graph: deployments.apps "istiod" not found

And this breaks more than one scenario: OSSM, canary upgrades.
And also per theses comments:
- https://github.com/kiali/kiali/issues/2884#issuecomment-802902501
- https://github.com/kiali/kiali/issues/2884#issuecomment-802907753
- https://github.com/kiali/kiali/issues/2884#issuecomment-804066520

The discussion in https://github.com/kiali/kiali/issues/2884 is a mix between the issue here and the canary upgrade scenario, IMO. But the part discussing about the bug, should be part of this issue.
At the beginning I considered this was a problem of not supporting the istio canary upgrade (https://github.com/kiali/kiali/issues/3782#issuecomment-801775917), that is why I triggered comments in that issue.

**Comment by jshaughn** [comment]
@xeviknal OK, I was getting confused between the two issues.  If necessary you can talk with @israel-hdez .  I'm assuming what you are doing is completely separate from the "idle nodes" activation I had been talking about above.

**Comment by xeviknal** [comment]
@jshaughn no, not to the activation part. However, the "idle nodes" appender consume the `mesh`-related work which needs the change. See the work in here: https://github.com/kiali/kiali/pull/3796

**Comment by jshaughn** [comment]
@xeviknal yes, i had noted that in my original comment above (https://github.com/kiali/kiali/issues/3782#issuecomment-801518374).  I may pursue changing that idle nodes activation in a separate issue, thanks!

**Comment by ahsanqaisar** [comment]
Thanks guys for all the help!

**Comment by xeviknal** [comment]
@ahsanqaisar a PR approaching the original problem of deployment not found has been merged: https://github.com/kiali/kiali/pull/3796. You'll find one new config for placing the deployment name.

@jshaughn Do you think we can close this issue? Or do you want to keep it open to track other changes?
