### ISSUE TITLE
Include an explanation about the lack of health information for TCP services (like a database)

### ISSUE THREAD

**Issue by soukron** [kiali/kiali#3786]
**Is your feature request related to a problem? Please describe.**
Protocols other than HTTP/GRPC can't be analyzied and therefore there won't never be a green Health report in the service page.

**Describe the solution you'd like**
Include in the documentation/FAQ a brief paragraph to explain the fact that they won't be never green to settle the users expecations in a clear way.

**Comment by lucasponce** [comment]
+1

**Comment by lucasponce** [comment]
This should be part of https://github.com/kiali/kiali/issues/4118 at least it deserves a FAQ entry.
