### ISSUE TITLE
Span detail can't be open when navigating from Graph

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#3814]
Starting a navigation from the Side panel -> Traces -> Trace detail -> Select Span -> Show span
![image](https://user-images.githubusercontent.com/1662329/112592420-39774d80-8e06-11eb-9a00-1b3161cb9726.png)

It navigates to the Span focused tab:
![image](https://user-images.githubusercontent.com/1662329/112592528-688dbf00-8e06-11eb-8394-5dad7b4c4089.png)

But Span can't be collapsed, selecting other trace from the main timeline control doesn't fix it as well:
![image](https://user-images.githubusercontent.com/1662329/112592617-8c510500-8e06-11eb-95b8-24862a3c937c.png)

To workaround this, user needs to navigate to a different tab and come back to traces tab to open/expand the details.

**Comment by lucasponce** [comment]
Also, there are more things broken:
![image](https://user-images.githubusercontent.com/1662329/112598570-100eef80-8e0f-11eb-8bb9-9472237cd403.png)

When spans are enabled, in some cases "hovering" on the "Span duration" legend hides the spans correlation.

cc @hhovsepy please, give a look, if you also see this broken. thx.

**Comment by aljesusg** [comment]
> Also, there are more things broken:
> ![image](https://user-images.githubusercontent.com/1662329/112598570-100eef80-8e0f-11eb-8bb9-9472237cd403.png)
> 
> When spans are enabled, in some cases "hovering" on the "Span duration" legend hides the spans correlation.
> 
> cc @hhovsepy please, give a look, if you also see this broken. thx.

Let me check the problem with span focused, about this comment I'll address it in another one because is not related with the last changes, I started yesterday trying to fix these problems with victory

**Comment by lucasponce** [comment]
> Let me check the problem with span focused, about this comment I'll address it in another one because is not related with the last changes, I started yesterday trying to fix these problems with victory

This problem was introduced in the last changes.
Testing the commit before in the UI

```
commit deb570fe1e67f96acc2a4d110897850d45ca4e1b
```

The problem is not there.

**Comment by hhovsepy** [comment]
@lucasponce yes I see the problem if hiding spans.

**Comment by aljesusg** [comment]
> > Let me check the problem with span focused, about this comment I'll address it in another one because is not related with the last changes, I started yesterday trying to fix these problems with victory
> 
> This problem was introduced in the lastest changes.
> Testing the commit before in the UI
> 
> ```
> commit deb570fe1e67f96acc2a4d110897850d45ca4e1b
> ```
> 
> The problem is not there.

The problem about "When spans are enabled, in some cases "hovering" on the "Span duration" legend hides the spans correlation." ? weird...in charts I only changed the address to add spanId. let me check it

**Comment by aljesusg** [comment]
I opened the Pr to fix the link with label not merge until we check this (https://github.com/kiali/kiali-ui/pull/2112)

I can reproduce it in [c8af2f7161b54e966a47568ea0c3f5a8d3ee2740](https://github.com/kiali/kiali-ui/commit/c8af2f7161b54e966a47568ea0c3f5a8d3ee2740) I can check this but is in master before these changes @lucasponce 

Should I address this in this PR too?

**Comment by lucasponce** [comment]
If you can add a fix on the hovering problem would be nice.
If it's too much work, we can split.

To me, the important is to have caught that problem and address it.

**Comment by aljesusg** [comment]
of course, but I need to do some research to check why is happen this

**Comment by aljesusg** [comment]
> Also, there are more things broken:
> ![image](https://user-images.githubusercontent.com/1662329/112598570-100eef80-8e0f-11eb-8bb9-9472237cd403.png)
> 
> When spans are enabled, in some cases "hovering" on the "Span duration" legend hides the spans correlation.
> 
> cc @hhovsepy please, give a look, if you also see this broken. thx.

Opened https://github.com/kiali/kiali/issues/3844 for address this, I found the problem in legend
