### ISSUE TITLE
Workload/Service Overview tabs: Move subtables to cards

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#3817]
Today Service Overview and Workload Overview tabs present some nested subtabs for Workload(Pods),Services and Istio Config that can be improved:

![image](https://user-images.githubusercontent.com/1662329/112624191-94706b00-8e2d-11eb-8336-700509bfda8a.png)
![image](https://user-images.githubusercontent.com/1662329/112624232-a520e100-8e2d-11eb-961f-a099a0df9f8a.png)

When user performs actions, typically he/she wants to check the Istio Config generated:

![image](https://user-images.githubusercontent.com/1662329/112624534-09dc3b80-8e2e-11eb-871d-d1d5c2787a9b.png)

Also happens in the Workload detail view, where probably user want to check in a first view Pod status, Service and Istio Config.

The fields presented are not modified since this feature were introduced

![image](https://user-images.githubusercontent.com/1662329/112624698-3d1eca80-8e2e-11eb-930d-b3c8a1274976.png)

So, discussed with @lwrigh that we could adjust these subtable like cards to have an uniform Overview tab.

Also there are some duplications with the links on IstioConfig that were not updated (two different links pointing to the same destination: Istio Config details) that can be reduced as well.

This issue will propose a change on the overview tab to uniform all elements in cards as discussed with UX.

**Comment by lucasponce** [comment]
I'm going to propose some prototype around this to discuss with @lwrigh, in the backlog we have some minor issues related to changes on these tables that may be related to this.

**Comment by abonas** [comment]
not sure if this is covered or not, but perhaps the upper part can have some darker separator because when scrolling, because it's white, it blends with the main section
![tabs](https://user-images.githubusercontent.com/6277245/114304629-e75c4a80-9adc-11eb-8d18-d0816fac711d.png)

**Comment by lucasponce** [comment]
> not sure if this is covered or not, but perhaps the upper part can have some darker separator because when scrolling, because it's white, it blends with the main section. or maybe make it fixed when scrolled?

I don't understand the question.

The upper part is not focus of this work and it was defined ina previous work with UX.

In general behaviour, the tab content will scroll when overload, in this tab and others.

**Comment by abonas** [comment]
> > not sure if this is covered or not, but perhaps the upper part can have some darker separator because when scrolling, because it's white, it blends with the main section. or maybe make it fixed when scrolled?
> 
> I don't understand the question.
> 
> The upper part is not focus of this work and it was defined ina previous work with UX.

ok
> 
> In general behaviour, the tab content will scroll when overload, in this tab and others.
