### ISSUE TITLE
Workload_health_replica_set endpoint error

### ISSUE THREAD

**Issue by pbajjuri20** [kiali/kiali#3830]
Workload_health_replica_set endpoint:

**query  param** 
rateInterval: 60s
type: ReplicaSet

https:/{kiali.hostname.com}/api/namespaces/bookinfo/workloads/kiali-traffic-generator/health?rateInterval=60s&type=ReplicaSet

bug:

Replacing the **type: ReplicaSet with type: invalid**

**query  param** 
rateInterval: 60s
type: invalid

https:/{kiali.hostname.com}/api/namespaces/bookinfo/workloads/kiali-traffic-generator/health?rateInterval=60s&**type=invalid**

Instead of an error, It is getting a **200 Status code**.

**Comment by pbajjuri20** [comment]
Here is the list of workload_types:

![List of workload types](https://user-images.githubusercontent.com/55099523/112909933-5d65b800-90c0-11eb-944a-fdecb5f3279a.png)

**Comment by lucasponce** [comment]
I don't think this is 100% a bug.

if you have this query:

```
https:/{kiali.hostname.com}/api/namespaces/bookinfo/workloads/kiali-traffic-generator/health?rateInterval=60s&type=invalid
```

Kiali will find a workload of name "kiali-traffic-generator" in all types of workloads.

Could you confirm if is that the case for this test ?
