### ISSUE TITLE
Increase visibility of communication options for Kiali on the website

### ISSUE THREAD

**Issue by abonas** [kiali/kiali#3835]
Epic: #4118

I suggest 2 potential options to tackle this (there could be more..)
1. Move the links to twitter, youtube, ggl groups, etc to the top of the website, most of users won't scroll to bottom to discover them
2. Make bottom part where those options are specified as "static" and always visible and not dependent on scrolling

**Comment by lucasponce** [comment]
I would prefer to have a template pretty standard and avoid personalizations and focused in the content itself.
Perhaps it's just a matter of wording and change "Contribute" that people tend to not use with something like "Contact".

But modifying the template has side effects in the style and I think we should try to keep something standard here.
If the current template is outdated and there is another design that is clean and better, that's also another option but outside scope of this one.

**Comment by abonas** [comment]
> I would prefer to have a template pretty standard and avoid personalizations and focused in the content itself.
> Perhaps it's just a matter of wording and change "Contribute" that people tend to not use with something like "Contact".
> 
> But modifying the template has side effects in the style and I think we should try to keep something standard here.
> If the current template is outdated and there is another design that is clean and better, that's also another option but outside scope of this one.

I understand your reasoning. Looking at a few os project websites, all have that communication option part at the bottom of the page, and not as an "always visible / static", which IMO is interesting because often users won't reach it. 
It will be good to hear @andrew-ronaldson thoughts on what's the best practice these days in that regard

**Comment by lucasponce** [comment]
A change that wouldn't modify the template could be to add a couple of icons at the main menu.
Inspired from Jaeger site:
![image](https://user-images.githubusercontent.com/1662329/129153843-068988e6-712b-4d18-9554-157be6cf8a6b.png)

With the Twitter + Github + Slack icons could be enough.

That would avoid to make changes in the template.

**Comment by abonas** [comment]
that sounds good to me, do we know if Jaeger template is applicable to Kiali website?
