### ISSUE TITLE
Workload filter for Istio Config not working correctly

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#3837]
During the work on #3817 I notice that the fetch IstioConfig related for a given workload is not working correctly.
It seems that the workload selector check is skipping some use case.

**Comment by jshaughn** [comment]
Hi @lucasponce , can you either assign yourself to this one or add some detail such that someone else could solve this one?  Might be a good one for a new person to learn some things...

**Comment by lucasponce** [comment]
I think this issue could be interesting for @nrfox, it can also help to start playing with Sidecars and Kiali.

**Comment by lucasponce** [comment]
Thanks @nrfox, yes, I think the flawn is in the backend endpoint, the filter logic with the labels selector is missing some case to make that the proper sidecar (or any other supported Istio object linked with the workload label) are linked in that box.

Feel free to ping me if you need more context for this one.

**Comment by lucasponce** [comment]
Thanks @nrfox for the findings, yes, you're right. It seems that TODO line was needed and this bug was introduced before.
Indeed, the resourceType is passed in non-cache scenarios https://github.com/kiali/kiali/blob/master/kubernetes/istio.go#L159 but for some reason it seems I introduced the regression.
