### ISSUE TITLE
Some graph settings do not have query parms - can't bookmark pages

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#3840]
Some settings in the graph do not have corresponding query params - so there is no way to, for example, bookmark a graph page that displays the cluster boxes (several of the display options are like this - cluster boxes is just an example).

**Comment by jshaughn** [comment]
This is true, I'm just not sure what the priority is to add all of the options.  Waiting to add to backlog for some upvotes.

**Comment by lucasponce** [comment]
I think this should be in the backlog.
In a separated issue there is a discussion to share the Graph view https://github.com/kiali/kiali/issues/3727#issuecomment-895322676, it's not directly related, but having a valid URL with support for all parameters will help in any case.

**Comment by jshaughn** [comment]
This comment is to just make explicit which graph options are and are not bookmarkable:

option | supports bookmarking
--------------------- | ----------------------
duration | yes
edge labels | yes
graphType | yes
layout | yes
namespaces | yes
refresh period | yes
replay | no
show idle edges | yes
show idle nodes | yes
show operation nodes | yes
show service nodes | yes
traffic rates | yes
find/hide expr | no
show animation | no
show cluster box | no
show badge security | no
show badge sidecar | no
show badge vs | no
show namespace box | no

The understanding is that all graph options should support bookmarking, if reasonably feasible.
