### ISSUE TITLE
Block icon is displayed when standing on the info for display options

### ISSUE THREAD

**Issue by abonas** [kiali/kiali#3861]
Is this the expected behavior that block icon is displayed when user stands on info options?
![blockicon](https://user-images.githubusercontent.com/6277245/114305126-7ec29d00-9adf-11eb-84b0-d5318d009c73.jpg)

**Comment by jshaughn** [comment]
> Is this the expected behavior that block icon is displayed when user stands on info options?

@abonas no, it's not desired, it's just been sort of a lingering behavior.
