### ISSUE TITLE
Incoming/Outgoing traffic seems incorrect on NS detail

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#3873]
On my example "travel-portal" namespace only has ongoing traffic but sidepanel are generated for "incoming/ongoing"

![image](https://user-images.githubusercontent.com/1662329/114552963-6da39880-9c65-11eb-9b1c-5ac771fb0a34.png)

Minor, but I'd align terminology "incoming/outgoing" -> "inbound/outbound" as used in other elements for same concept (unless I missed if there are other meaning at namespace level).

**Comment by jshaughn** [comment]
@lucasponce "Outgoing" is the standard term, where did you see "Ongoing".  Also, the screenshot above shows only Outgoing, and that seems correct looking at the screenshot.  I'm missing the problem being reported.

**Comment by lucasponce** [comment]
Sorry, there was a typo, I've reported two things:
- "Incoming" / "Outgoing" traffic in sidebar didn't seem to honor the traffic in my example.
- "Incoming" / "Outgoing" terminology is used for namespace but in other elements, it's used "inbound/outbound".

**Comment by jshaughn** [comment]
Ah, OK, yes, I can see changing to Inbound/Outbound for consistency with the chart tabs, etc.

As for the reported rate, it would have been helpful to see the rate edge labels, otherwise I can only assume that the 0.81 is the valid sum for the three edges leaving the namespace.

**Comment by lucasponce** [comment]
> As for the reported rate, it would have been helpful to see the rate edge labels, otherwise I can only assume that the 0.81 is the valid sum for the three edges leaving the namespace.

There was no "incoming" traffic and it seems the sidebar was replicating same data in "incoming/outgoing" tabs.

**Comment by jshaughn** [comment]
OK, I'll take a look, thanks.

**Comment by jshaughn** [comment]
@lucasponce Waiting on your feedback, let me know when you get the chance...

**Comment by lucasponce** [comment]
> The question is whether the design is correct or confusing. When looking at the Travel Portal Namespace, the Inbound traffic is the sum of the traffic entering or originating in the namespace.

Not sure if I understand that: traffic originated in the travel-portal namespace should be considered "outbound", isn't it ?

In my demo the sceanrio was: travel-portal had no inbound traffic (traffic-control was not calling any of the portals) but when I click in the travel-portal namespace both "inbound/outbound" showed same traffic for the whole NS, then as I know that no one is calling any workload inside the namespace, it sounded very weird.

My first thought was perhaps some glitch in the UI, like some old data re-used or something like that, but not sure if that was an intentional design.

(Perhaps I had to write this long description in the first comment, I admit I could create more noise on it)

**Comment by jshaughn** [comment]
It's because we consider all originating traffic as 'inbound' traffic.  It's mainly due to inbound traffic originating in ingress gateways, but "traffic generators" will be treated the same way.  The travel portal workloads are generating/originating traffic, not unlike the kiali-traffic-generator we add to the bookinfo demo.  If you look at that you'll see it's being handled the same way.  I'm not opposed to revisiting the handling because it's clearly not obvious.  If we eliminate treating generated traffic as inbound traffic, I think you will have the behavior you expect, and maybe that is what others would find more obvious.

**Comment by lucasponce** [comment]
> If we eliminate treating generated traffic as inbound traffic, I think you will have the behavior you expect, and maybe that is what others would find more obvious.

Interesting discussion, I didn't realize that.

Yes, I think it's terminology, personally to me is more clear to consider "inbound" as any traffic that comes from other namespace "travel-control" to "travel-portal" and the traffic that a workload generates should be considered as "outbound".

I mean, otherwise, this terminology is not sync with other pages in kiali (traffic or metrics), you won't see "inbound" metrics for a namespace, and that perhaps it's what triggered my comment as well.

**Comment by jshaughn** [comment]
I think it's worth making the change as it will help reinforce consistency with the terminology.  I'm not sure anyone has really questioned this in the past so most likely a change is fine.   I'll add the change to the PR.
