### ISSUE TITLE
does Kiali need patch permission for pods/proxy?

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#3878]
As part of [our security audit](https://github.com/kiali/kiali/issues/3871) of our Kiali SA permissions, I came across the fact that we give "patch" permission to "pods/proxy". I looked at the PRs that introduced this and found https://github.com/kiali/kiali/pull/3126

The only thing I see that might have to do with editing the proxy is the "SetProxyStatus" function, but I don't think this actually edits anything in the k8s resource (I'm not sure).

I'm assigningn to @xeviknal since he wrote that PR - so I would like to ask for confirmation from @xeviknal - does this code need "patch" permissions on "pods/proxy"?

**Comment by xeviknal** [comment]
I'll double check this one, but I remember that the 'pods/proxy' sub-resource needed the "patch" permission because it is a more nuanced feature.
I'll keep this issue posted.

**Comment by jmazzitelli** [comment]
Rather than use the PRs created specifically for this, I corporated those changes in https://github.com/kiali/helm-charts/pull/62 and https://github.com/kiali/kiali-operator/pull/287 to avoid conflicts (we now have a separate apiGroup for `""` that is for read-only permissions - I moved `pods/proxy` to that... it goes along with things like `pods/log` and `configmaps`).
