### ISSUE TITLE
Explore tracing for multicluster/federated environments

### ISSUE THREAD

**Issue by israel-hdez** [kiali/kiali#3881]
Tracing features are misbehaving for multicluster/federated environments.

Jaeger is, apparently, working fine and properly collecting traces. However, in multicluster/federated environments, Jaeger setup is uncertain. It could be that we have one Jaeger instance on each cluster. Jaeger storage could be independent causing the data to be sharded. It also may be the case that storage is shared and is made available to all clusters.... or any other kind of setup?

Tracing deserves a dedicated exploration to learn how Kiali will work with traces in multicluster/federated environments.

**Comment by lucasponce** [comment]
@israel-hdez you are open new issues for the multicluster/federation issues but as I commented in previous issues (similar for the actions/management) I really miss a sync here to discuss this before that we put it in any backlog.

To me some of these issues require some discussion about direction, capabilities that we want to support.

In particular, I think that this will depend about the deployment strategy for the addons (one prometheus/jaeger per cluster, one shared instance per "mesh", etc) and from that, things can be developed/ellaborated in multiple directions.

I encourage you to define a sync meeting where we can discuss these things from a top-down strategy.

**Comment by jshaughn** [comment]
@lucasponce Yesterday when looking at the latest MC behavior we were unsure about trace behavior, what happens now, what we want to happen.  So we just wanted to get an issue in place to mark exactly what you are saying, we need to talk about (i.e. "explore") the tracing behavior.  There is no work being done.

**Comment by lucasponce** [comment]
Closing in favor of the main discussion https://github.com/kiali/kiali/discussions/4081 which is consolidating all topics.
