### ISSUE TITLE
Update "Visualizing your Mesh" Istio documentation

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#3888]
Reported by @esnible

That doc is using some old captures that are not synced with the Kiali version shipped by default in the Istio 1.9 and future 1.10

cc @jmazzitelli

**Comment by jshaughn** [comment]
The page in question: https://istio.io/latest/docs/tasks/observability/kiali/

The source: https://github.com/istio/istio.io/tree/master/content/en/docs/tasks/observability/kiali

**Comment by esnible** [comment]
@jshaughn I started working on the test.  https://github.com/istio/istio.io/pull/9570 .  Let me know if the approach makes sense.
