### ISSUE TITLE
Phase out publication of kiali-ui to NPM

### ISSUE THREAD

**Issue by israel-hdez** [kiali/kiali#3891]
The Kiali UI is being published to NPM: https://www.npmjs.com/package/@kiali/kiali-ui

When it was chosen to publish to NPM, the idea was that 3rd parties could re-use the components of the Kiali UI. However, everything is too tightly coupled to the point that major components are not re-usable. Probably, only the small ones can be re-used.

If front-end components are hard to re-use, and there are no plans to re-architect the UI with reusability in mind, it's probably better to stop publishing to NPM a package that is not suited for consumption. This could simplify a little our release process.

**Comment by lucasponce** [comment]
+1

**Comment by aljesusg** [comment]
It makes no sense to publish it, I think it was done by an attempt to export the graph

**Comment by israel-hdez** [comment]
All done. Closing.
