### ISSUE TITLE
Kiali is using deprecated resources which will be removed in k8s v1.22

### ISSUE THREAD

**Issue by FilipB** [kiali/kiali#3893]
**Describe the bug**
Not really a bug but a warning that Kiali is using deprecated resources which will be removed in k8s v1.22 which will be released soon.
I saw following in kiali operator log:
`W0416 07:05:45.343550       7 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition`

For UI issues please also add a screenshot that shows the issue.

**Versions used**
Kiali UI
1.33.0 (3fee4558a3a4f606828768407038dbf6f412196a)
Kiali Server
v1.33.0-SNAPSHOT (60ecd61)
Istio: 1.9.3
Kubernetes flavour and version: (e.g. OpenShift Origin 3.9)
OCP 4.7

**Comment by lucasponce** [comment]
Thanks @FilipB

**Comment by jmazzitelli** [comment]
This should have already been done. How did you install Kiali?

See: https://github.com/kiali/kiali-operator/pull/246/files and https://github.com/kiali/kiali-operator/pull/247/files

But see: https://github.com/kiali/kiali-operator/pull/269

I suspect you installed via OSSM - in which case, this is known. We can't do this until we no longer support OS 4.4.

**Comment by FilipB** [comment]
It was installed via helm using the latest helm charts and kiali operator. I will check on Monday if our build and install jobs are really using the latest.

**Comment by jmazzitelli** [comment]
> It was installed via helm using the latest helm charts

Helm charts were also changed 2 months ago - so I don't think you have the latest helm charts. See: https://github.com/kiali/helm-charts/pull/35

**Comment by FilipB** [comment]
> > It was installed via helm using the latest helm charts
> 
> Helm charts were also changed 2 months ago - so I don't think you have the latest helm charts. See: [kiali/helm-charts#35](https://github.com/kiali/helm-charts/pull/35)

We are always building the latest helm charts - https://gitlab.cee.redhat.com/istio/servicemesh-qe/jenkins-csb-declaration/-/blob/master/jenkinsfiles/kiali/install-jobs/install-istio.jenkinsfile#L24
But as I said, I will double check that everything is working as expected.

**Comment by FilipB** [comment]
It seems to be caused by this - https://github.com/kiali/kiali-operator/blob/master/roles/default/kiali-deploy/tasks/main.yml#L798

Here is a relevant part of kiali operator log:
```
TASK [default/kiali-deploy : Wait for Monitoring Dashboards CRD to be ready] ***

-------------------------------------------------------------------------------
{"level":"info","ts":1618842049.1699958,"logger":"logging_event_handler","msg":"[playbook task]","name":"kiali","namespace":"kiali-operator","gvk":"kiali.io/v1alpha1, Kind=Kiali","event_type":"playbook_on_task_start","job":"6129484611666145821","EventData.Name":"default/kiali-deploy : Wait for Monitoring Dashboards CRD to be ready"}
{"level":"info","ts":1618842049.7546244,"logger":"proxy","msg":"Skipping cache lookup","resource":{"IsResourceRequest":false,"Path":"/version","Verb":"get","APIPrefix":"","APIGroup":"","APIVersion":"","Namespace":"","Resource":"","Subresource":"","Name":"","Parts":null}}
{"level":"info","ts":1618842049.7580955,"logger":"proxy","msg":"Skipping cache lookup","resource":{"IsResourceRequest":false,"Path":"/version/openshift","Verb":"get","APIPrefix":"","APIGroup":"","APIVersion":"","Namespace":"","Resource":"","Subresource":"","Name":"","Parts":null}}
{"level":"info","ts":1618842049.7635624,"logger":"proxy","msg":"Skipping cache lookup","resource":{"IsResourceRequest":false,"Path":"/apis","Verb":"get","APIPrefix":"","APIGroup":"","APIVersion":"","Namespace":"","Resource":"","Subresource":"","Name":"","Parts":null}}
{"level":"info","ts":1618842049.7772627,"logger":"proxy","msg":"Skipping cache lookup","resource":{"IsResourceRequest":false,"Path":"/apis/apiextensions.k8s.io/v1beta1","Verb":"get","APIPrefix":"apis","APIGroup":"","APIVersion":"","Namespace":"","Resource":"","Subresource":"","Name":"","Parts":null}}
W0419 14:20:49.872645       7 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0419 14:20:49.988821       7 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
{"level":"info","ts":1618842050.084437,"logger":"proxy","msg":"Read object from cache","resource":{"IsResourceRequest":true,"Path":"/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/monitoringdashboards.monitoring.kiali.io","Verb":"get","APIPrefix":"apis","APIGroup":"apiextensions.k8s.io","APIVersion":"v1beta1","Namespace":"","Resource":"customresourcedefinitions","Subresource":"","Name":"monitoringdashboards.monitoring.kiali.io","Parts":["customresourcedefinitions","monitoringdashboards.monitoring.kiali.io"]}}
```

**Comment by jmazzitelli** [comment]
Ah. I forgot about that one! Good catch. I'll have to change that in `master` branch - we'll need to remember to change it in the production branches when we move those to v1, too.
