### ISSUE TITLE
[molecule] run molecule tests using a KinD cluster

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#3895]
PRs:
* https://github.com/kiali/kiali/pull/3894
* https://github.com/kiali/kiali-operator/pull/291

**Comment by jmazzitelli** [comment]
This is currently a WIP. With the two PRs I'm close, but I need to figure out how to get the molecule docker container (which runs the molecule tests) to be able to access the Kiali service in the KinD cluster - currently getting a "Host unreachable" error. I'm pretty sure this can be done, but at the moment I do not know how.

**Comment by jmazzitelli** [comment]
Here is the state of the 2 PRs.

Running this command to test:
```
hack/ci-kind-molecule-tests.sh -kof jmazzitelli -kob ci-kind -kf jmazzitelli -kb ci-kind -ir '' -udi true -at default
```
Will start running the "default" molecule scenario. But this fails at the task:
```
    TASK [Wait for Kiali to be running and accepting requests] *********************^M
```
with this error:
```
Status code was -1 and not [200]: Request failed: <urlopen error [Errno 113] Host is unreachable>
```
It is trying to get to the correct url (in this case, `"url": "https://172.18.255.71/kiali/api"`) but that IP is not reachable. I can confirm also by just getting inside the container and trying to curl that URL:
```
$ docker ps | grep kiali-molecule
752ef46da58a   kiali-molecule:latest   "molecule --debug te…"   3 minutes ago   Up 3 minutes   sharp_bardeen

$ docker exec -it sharp_bardeen bash
bash-5.1# curl https://172.18.255.71/kiali/api
curl: (7) Failed to connect to 172.18.255.71 port 443: Host is unreachable
```

We need to figure out how to open up the network from the molecule container to the Kind container because the molecule tests need to send requests to the server-under-test running in Kind.

**Comment by jmazzitelli** [comment]
I no longer have a machine that can run KinD (I'm on RHEL8 that has podman only and it cannot run kind.) So I'm putting this effort on pause. If someone can pick up the work and complete this, it would be appreciated.

**Comment by jshaughn** [comment]
> I'm on RHEL8 that has podman only and it cannot run kind.

Are you saying Kind requires Docker and Podman to run?

**Comment by jmazzitelli** [comment]
I'm saying Kind neither either docker OR podman, but not all podmans are created equal. My podman installation (for reasons unknown to me) is not good enough to work with the experimental podman support in Kind:

```
$ kind create cluster
enabling experimental podman provider
Creating cluster "kind" ...
podman provider does not work properly in rootless mode
```

**Comment by jmazzitelli** [comment]
Looks like KinD v0.11 will get us closer - they should have rootless podman support:

* https://kind.sigs.k8s.io/docs/user/rootless/
* https://github.com/kubernetes-sigs/kind/milestone/14
* https://github.com/kubernetes-sigs/kind/pull/1935

**Comment by jshaughn** [comment]
This was done, see above merged PRs.
