### ISSUE TITLE
Refine message for remote Kiali

### ISSUE THREAD

**Issue by abonas** [kiali/kiali#3907]
The message when remote Kiali URL is not set might be misleading. It currently says "no remote links, Kiali is not available on the .... cluster", but it could be that Kiali *is* available there, but the link was not configured. So the message needs some refinement to indicate that to user.
![remoteKiali](https://user-images.githubusercontent.com/6277245/115238246-22d2c680-a126-11eb-9087-cdfcf4e492c5.png)

**Comment by jshaughn** [comment]
@abonas, @israel-hdez , how about one of these?
1)  Remote links unavailable.  No Kiali configured for \<name\> cluster.
2)  No remote links.  Kiali not configured for \<name\> cluster.
3)  For remote links annotate the Kiali Service on \<name\> cluster with kiali.io/external-url.

Something else?

**Comment by lucasponce** [comment]
I think there is already a "standard" message when a external link is not available.

```
Could not fetch XXX info. Turning off links to XXX
```

I don't adovocate for any specific wording but let's keep consistency on messages for similar use cases (here or there).

**Comment by lucasponce** [comment]
> I like consistency. However, I remember that this is usually logged in the message center. IMO, it would be weird to see this message in the context menu. Perhaps, we could log this message to the message center and, then show a simple "(No options)" legend in the context menu (or no context menu at all?) ??

+1
