### ISSUE TITLE
Cannot read property 'Kubernetes' of undefined in UI

### ISSUE THREAD

**Issue by vsychov** [kiali/kiali#3913]
**General remarks**

**Describe the bug**

For UI issues please also add a screenshot that shows the issue.
<img src="https://sctn.io/MyYopp63L2.png" />

**Versions used**
Kiali: Version: v1.33.0, Commit: 857b657226aca379bfeed8b2a30e660557abfd16
Istio: 1.9.2
Kubernetes flavour and version: v1.18.10

**To Reproduce**
1. Setup Kiali (in my case by Kiali operator)
2. Go to the "Full Graph" page
3. Click to any edge of a graph or any node

**Expected behavior**
No error expected

**Comment by lucasponce** [comment]
I suspect is similar to https://github.com/kiali/kiali/issues/3911

**Comment by jshaughn** [comment]
@vsychov How did you install Kiali?

**Comment by crhuber** [comment]
Also getting the same when installed by operator

```
Kiali UI
1.33.0 (cd8cea7bafdb193c662c034f728e4c914af46d88)
Kiali Server
v1.33.0 (857b657226aca379bfeed8b2a30e660557abfd16)
Kiali Container
v1.33.0
Components
Prometheus
2.19.2
Kubernetes
v1.19.6-eks-49a6c0
```

**Comment by jshaughn** [comment]
OK, the problem occurs when the installed Istio is not given a cluster-name.  Working on a fix and we will publish a 1.33.1 patch release when it is ready.

**Comment by jshaughn** [comment]
@vsychov Kiali v1.33.1 has been released and should resolve your issue.

**Comment by vsychov** [comment]
@jshaughn , thanks, my issue was resolved by this fix.

**Comment by hsmade** [comment]
Can the kiali-server chart please be updated/released as well?

**Comment by jshaughn** [comment]
@hsmade This is usually automatic in the release process, I'll check into the issue and get back to you, thanks for reporting.

**Comment by jshaughn** [comment]
@hsmade The 1.33.1 helm charts are released. Sorry for the delay.

**Comment by hsmade** [comment]
Thx! And no worries!
