### ISSUE TITLE
Idle nodes are not synced with traffic nodes

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#3917]
This looks very confusing to me:

![image](https://user-images.githubusercontent.com/1662329/115528046-f3d96380-a291-11eb-8f0a-c26139c59047.png)

It seems that "idle" nodes (generated from kubernetes definitions) and "traffic" nodes are not joined in the graph.

I understand that there should be some kind of "sync" here (if an idle node is present as a traffic node, don't show).

Otherwise it creates a lot of noise and in examples as showed it makes the graph hard to use.

This is the business scenario I'm running: in a moment of the time, I have a workload that is out of the graph (i.e. missing sidecar or simply scaled down/not ready), I'd expect I can see those in the graph combined with the existing one.

**Comment by jshaughn** [comment]
@lucasponce The screenshot is maybe not high-res enough for me to understand what you are saying.  Are you saying that we are generating duplicate boxes that separate idle and active nodes?

**Comment by lucasponce** [comment]
@jshaughn yes (sorry, I don't have my local env prepared to repeat the picture now, but I'll update). 
Duplicated apps are confusing, because it's the same app, from user perspective I guess that if an app from the idle group is present in the traffic group is should be removed from that list.

Also, as you can see it basically duplicates the graph and make it more difficult to manage.

**Comment by jshaughn** [comment]
OK, I can imagine that the idle nodes appender is not taking the time to assign the proper parent link.  This sounds like a good one for @nrfox to get more familiar with the graph generation code...

**Comment by nrfox** [comment]
This seems to be caused by the idle node appender setting the cluster for idle nodes to `unknown`: https://github.com/kiali/kiali/blob/master/graph/telemetry/istio/appender/idle_node.go#L74.

If there's a service with v1, v2, and v3 in cluster `cluster-default` and v1 and v2 are idle, the idle nodes v1 and v2 would be in the `unknown` cluster while v3 would be in the `cluster-default` cluster. This is why they currently are being boxed separately even though they should be boxed together.

**Comment by jshaughn** [comment]
Good detective work, that makes total sense.  So, here is what I think you can do about it: instead of setting to unknown , try setting to the "home" cluster.  The AppenderGlobalInfo should contain the home cluster name.  Try using that for the idle node.
