### ISSUE TITLE
Traces do not work when app label does not match JAEGER_SERVICE_NAME

### ISSUE THREAD

**Issue by samirmajen** [kiali/kiali#3919]
**General remarks**

Its possible to define a different jaeger service name to the name of the app using the "JAEGER_SERVICE_NAME" environment variable which libraries then use to send traces to jaeger.

**Describe the bug**

Setting JAEGER_SERVICE_NAME to something different to app label breaks the traces tab on all sections as kiali is assuming the app label matches the jaeger service name which is not always the case. As a workaround could a label or annotation be added that defines what the jaeger name is for kiali to use?

**Versions used**
Kiali: v1.29.1
Istio: v1.9.1
Kubernetes flavour and version: 1.18

**To Reproduce**

Deploy a Jaeger enabled app with label=name-1
Define an environment variable JAEGER_SERVICE_NAME=name-2
Open Kiali and navigate to any traces tab

**Expected behavior**
Traces should be available when the app label is different to JAEGER_SERVICE_NAME

**Comment by samirmajen** [comment]
Note, this is similar to https://github.com/kiali/kiali/issues/2664 and https://github.com/kiali/kiali/issues/3045 but the resolutions there do not work

**Comment by lucasponce** [comment]
@samirmajen could share an example about your configuration with us ?

Note that this jaeger integration is mostly focused as a followup of the tracing integration available in Envoy.

So, at the moment that user personalizes service names with Istio/Envoy convention for apps, services and versions it is possible that some tweak may introduce some empty query (or broken one).

Please, give us more info about a end-to-end example what we may follow to fix/enhance the existing scenario.

P.S.: feel free to use bookinfo or one of these https://github.com/kiali/demos that we can easily "tweak" into the codebase to simulate a similar case as you are facing.
