### ISSUE TITLE
The istio-sidecar-injector config map name should be configurable

### ISSUE THREAD

**Issue by bougyman** [kiali/kiali#3923]
**Describe the bug**

**Versions used**
Kiali:
Istio:
Kubernetes flavour and version: (e.g. OpenShift Origin 3.9)

**To Reproduce**
1. Install istio with a revision: tag set to 1-9
2. Deploy kiali with external_services.istio.deployment_name as istiod-1-9 and external_services.istio.config_map_name as istio-1-9
3. Check logs on the deployed kiali instance
4. You will see the error: 2021-04-21T15:55:03Z WRN Cannot resolve the network ID of the cluster where Kiali is hosted: cannot get the sidecar injector config map :configmaps "istio-sidecar-injector"     not found

**Expected behavior**
The config map for istio-sidecar-injector would be configurable to find the istio-sidecar-injector-1-9 config map

**Comment by israel-hdez** [comment]
Closing, because you already helped us with this issue :-)

**Comment by lir2002** [comment]
Hope everyone can find the answer here:
https://kiali.io/docs/configuration/istio/#sidecar-injection-canary-upgrade-management-and-istio-revisions
