### ISSUE TITLE
Kiali Login error when Prometheus fails to start

### ISSUE THREAD

**Issue by mattmahoneyrh** [kiali/kiali#3927]
Encountered a Kiali login error, that occurred when Prometheus failed to start. This prevents being able to login to Kiali:

Build:
Kiali UI: 1.33.0 (cd8cea7bafdb193c662c034f728e4c914af46d88)
Kiali Server: v1.33.0 (857b657226aca379bfeed8b2a30e660557abfd16)
Kiali Container:  v1.33.0

Kiali pod log:
2021-04-21T20:31:41Z ERR Failed to fetch Prometheus configuration: Get "http://prometheus.istio-system:9090/api/v1/status/config": dial tcp 172.30.222.151:9090: i/o timeout 2021-04-21T20:31:58Z ERR Failed to fetch Prometheus flags: Get "http://prometheus.istio-system:9090/api/v1/status/flags": dial tcp 172.30.222.151:9090: i/o timeout

![image](https://user-images.githubusercontent.com/7262987/115626295-4d11b900-a2cb-11eb-985f-404ee54d2d33.png)

**Comment by jshaughn** [comment]
What should be the proper behavior?

**Comment by jshaughn** [comment]
@mattmahoneyrh , so let me take a stab at answering my own question...  I definitely don't like the "You are logged in..." message and approach.  If it's going to leave you on the Log In page I think the user should be logged out immediately.  And I think perhaps the actual error message should be displayed, something like:

Kiali failed to initialize due to:

<error msg>

Your session has been closed.  Please log in again after the problem has been resolved.

**Comment by mattmahoneyrh** [comment]
@jshaughn This issue has not again been encountered. Would say that the message suggestion change would be fine.

**Comment by jshaughn** [comment]
@jmazzitelli We should clean this up, prioritize as you see fit.

**Comment by jmazzitelli** [comment]
Here's the message stored in a class constant: https://github.com/kiali/kiali-ui/blob/v1.37.0/src/app/AuthenticationController.tsx#L65-L67

Here's where it is used - only in the render() method: https://github.com/kiali/kiali-ui/blob/v1.37.0/src/app/AuthenticationController.tsx#L135-L157

Just reading the code, it seems like you ARE still logged in at this point. So if you want to be logged out, you need to do "something" to do that - I do not know what javascript "gobbly-goop" needs to be done to get the UI to log you out.

**Comment by nrfox** [comment]
I'm unable to reproduce this. Under what circumstances does the error login message appear? When kiali --> prom request timeout occurs during login?

**Comment by nrfox** [comment]
Was able to reproduce adding a delay to the prom service. Will work on the proposed fix:

> @mattmahoneyrh , so let me take a stab at answering my own question... I definitely don't like the "You are logged in..." message and approach. If it's going to leave you on the Log In page I think the user should be logged out immediately. And I think perhaps the actual error message should be displayed, something like:
> 
> Kiali failed to initialize due to:
> 
> Your session has been closed. Please log in again after the problem has been resolved.

It would be helpful to also surface what service is causing the issue if that's possible. In this case, requests Kiali --> Prom are timing out.

Another thing I noticed is that if you are already logged in and Kiali --> Prom requests are taking awhile then you will be stuck on a loading page until something changed with the request. That raises a couple of questions:

1. Can you succesfully login to Kiali if Prom is down (either unreachable or requests are hanging)?
2. Does Kiali have request timeouts configured for requests made to Prom or other services? Should you just run a sidecar Proxy with your Kiali deployment and configure those there?

**Comment by jshaughn** [comment]
> Can you succesfully login to Kiali if Prom is down (either unreachable or requests are hanging)?

I thought that maybe that's when you end up in this scenario.  If Prom is unreachable there isn't much reason to run Kiali.  Best would likely be to prevent login (or auto-logout) and display a decent message.

> Does Kiali have request timeouts configured for requests made to Prom or other services? Should you just run a sidecar Proxy with your Kiali deployment and configure those there?

I believe there are timeouts for all of the prom requests, although I don't think they are short because we don't want to abort a valid, large query for metrics.  I'd prefer not to see a need for us to run a sidecar.

This issue is unusual and we do need to clean it up, but the solution can still be fairly blunt.

**Comment by nrfox** [comment]
> I thought that maybe that's when you end up in this scenario. If Prom is unreachable there isn't much reason to run Kiali. Best would likely be to prevent login (or auto-logout) and display a decent message.

Sorry I asked the wrong question. I meant _should_ you be able to login to Kiali if Prom is down? Or use Kiali at all if Prom is down? If you are already logged in, you refresh your page, and Kiali --> Prom request is stuck, you will be stuck at this loading page until something happens with the request.

![Screenshot from 2021-07-28 10-39-45](https://user-images.githubusercontent.com/6226732/127343151-8c8c88c1-3522-43af-af21-98eb7651266a.png)

Should Kiali logout the user in both cases or just when the user is on the login page and Prom is hanging or down?


> I believe there are timeouts for all of the prom requests, although I don't think they are short because we don't want to abort a valid, large query for metrics. I'd prefer not to see a need for us to run a sidecar.

:+1:

**Comment by jshaughn** [comment]
I'm fairly sure it will time out eventually and then perhaps the user can log out.   I wouldn't try to log them out automatically in this case.  I think it's just this unusual login case we need to clean up.
