### ISSUE TITLE
Kiali reconciliation is very slow when doing bulk remove of namespaces from accessible_namespaces

### ISSUE THREAD

**Issue by FilipB** [kiali/kiali#3928]
**Describe the bug**
When removing existing 200 namespaces from accessible_namespaces it takes much longer to reconcile compared to how long it takes when adding new 200 namespaces.

**Versions used**
Kiali UI
1.33.0 (3fee4558a3a4f606828768407038dbf6f412196a)
Kiali Server
v1.33.0-SNAPSHOT (60ecd61)
Kiali operator from https://github.com/kiali/kiali-operator/pull/293
Istio: 1.9.3
Kubernetes flavour and version: (e.g. OpenShift Origin 3.9)
OCP 4.7

**To Reproduce**
1. install clean istio + kiali
2. enable a profiler (oc set env deploy/kiali-operator -n kiali-operator -e ANSIBLE_CONFIG=/opt/ansible/ansible-profiler.cfg)
3. wait for reconciliation to finish
4. create 200 empty namespaces
5. update spec.deployment.accessible_namespaces in kiali CR to contain all 200 namespaces
6. wait for reconciliation to finish
7. remove all 200 namespaces from spec.deployment.accessible_namespaces
8. wait for reconciliation to finish

**Expected behavior**
Reconciliation should be finished in reasonable time.

**Actual behavior**
It takes 653s to finish the reconciliation.
```
TASK [Log reconciliation processing time] **************************************
Wednesday 21 April 2021  16:17:32 +0000 (0:00:00.033)       0:10:53.523 *******
�[0;32mok: [localhost] => {�[0m
�[0;32m    "msg": "Processing time: [653] seconds"�[0m
�[0;32m}�[0m

TASK [debug] *******************************************************************
Wednesday 21 April 2021  16:17:32 +0000 (0:00:00.040)       0:10:53.563 *******
�[0;32mok: [localhost] => {�[0m
�[0;32m    "msg": "KIALI RECONCILIATION IS DONE."�[0m
�[0;32m}�[0m

PLAY RECAP *********************************************************************
�[0;33mlocalhost�[0m                  : �[0;32mok=1451�[0m �[0;33mchanged=85  �[0m unreachable=0    failed=0    �[0;36mskipped=596 �[0m rescued=0    ignored=0

Wednesday 21 April 2021  16:17:32 +0000 (0:00:00.031)       0:10:53.595 *******
===============================================================================
default/kiali-deploy : Delete all ConsoleLinks for namespaces that are no longer accessible - 155.89s
default/kiali-deploy : Delete unused Kiali roles from previously accessible namespaces --- 8.61s
default/kiali-deploy : Remove Kiali label from namespaces that Kiali no longer has access to --- 2.94s
default/kiali-deploy : Delete unused Kiali roles from previously accessible namespaces --- 2.15s
default/kiali-deploy : Create the Monitoring Dashboards ----------------- 2.14s
default/kiali-deploy : Delete unused Kiali roles from previously accessible namespaces --- 2.14s
default/kiali-deploy : Delete unused Kiali roles from previously accessible namespaces --- 2.13s
default/kiali-deploy : Delete unused Kiali roles from previously accessible namespaces --- 2.13s
default/kiali-deploy : Delete unused Kiali roles from previously accessible namespaces --- 2.12s
default/kiali-deploy : Delete unused Kiali roles from previously accessible namespaces --- 2.11s
default/kiali-deploy : Delete unused Kiali roles from previously accessible namespaces --- 2.11s
default/kiali-deploy : Delete unused Kiali roles from previously accessible namespaces --- 2.10s
default/kiali-deploy : Delete unused Kiali roles from previously accessible namespaces --- 2.10s
default/kiali-deploy : Delete unused Kiali roles from previously accessible namespaces --- 2.09s
default/kiali-deploy : Delete unused Kiali roles from previously accessible namespaces --- 2.09s
default/kiali-deploy : Delete unused Kiali roles from previously accessible namespaces --- 2.08s
default/kiali-deploy : Delete unused Kiali roles from previously accessible namespaces --- 2.06s
default/kiali-deploy : Delete unused Kiali roles from previously accessible namespaces --- 2.05s
default/kiali-deploy : Delete unused Kiali roles from previously accessible namespaces --- 2.05s
default/kiali-deploy : Delete unused Kiali roles from previously accessible namespaces --- 2.04s
```

**Comment by jmazzitelli** [comment]
As for the OS console links deletion -- Here's [the "delete OS console links" loop](https://github.com/kiali/kiali-operator/blob/v1.33.0/roles/default/kiali-deploy/tasks/openshift/os-main.yml#L105-L116) - we need to do the same thing we did for deleting namespace labels - and that is we need to loop and just build a large single yaml of all the OS console links and then in a single bulk `k8s` task we ask it to delete all the resources in that single yaml.

**Comment by jmazzitelli** [comment]
As for the deleting of unused roles from previously accessible namespaces, here's [the loop where that is done](https://github.com/kiali/kiali-operator/blob/v1.33.0/roles/default/kiali-deploy/tasks/main.yml#L665-L671) - same kind of fix we need to do here, too.

**Comment by jmazzitelli** [comment]
And here is [the deleting of the namespace labels from previously accessible namespaces](https://github.com/kiali/kiali-operator/blob/v1.33.0/roles/default/kiali-deploy/tasks/main.yml#L703-L712) - again, same kind of fix.

**Comment by jmazzitelli** [comment]
Please test the latest PR https://github.com/kiali/kiali-operator/pull/293. A refactoring of a lot of this code is done - all major areas of slowness have been addressed (major things addressed was creating roles, role bindings, console links, and then deleting the same. There were other things fixed, too.)

At this point in time, I don't see anything (that was previously reported slow) that has not been addressed. I think I got all the touch points that needed to be fixed.

QE should run their tests and again see if anything is wrong. The only thing I have a question on is memory usage. I suspect the memory usage should be much better now that this new code is utilizing the k8s collection tasks and ansible build-in templating, but I don't know.
