### ISSUE TITLE
Ability to disable logout / add custom logout url

### ISSUE THREAD

**Issue by psibi** [kiali/kiali#3934]
**Is your feature request related to a problem? Please describe.**

This is how my kiali setup looks like:

- I use [header authentication](https://kiali.io/documentation/latest/configuration/authentication/header/) strategy
- I have a SSO based setup for authentication.
- With the header based authentication strategy, I have a logout displayed in the kiali menu.
- Clicking the logout menu, now actually takes me to the login page of the kiali. But this is clearly wrong: Because if I do a refresh - it shows the kiali dashboard. So the logout link actually doesn't do the logout (which is fine, since it's handled by the SSO setup)

**Describe the solution you'd like**

There are two ways this can be solved:

- Have the ability to disable the logout link. (Same behavior when anonymous authentication strategy is used)
- Ability to provide custom logout link. (Similar to custom health check urls)

**Describe alternatives you've considered**

I have provided two alternative solutions above. I guess any one of them could solve it, although having both of them would be nice!

**Additional context**

No additional context needed for this issue IMO. But let me know if anything is needed.

**Comment by israel-hdez** [comment]
@psibi I think the solution will be to hide the logout option. That's what the Kubernetes Dashboard is doing, so I think we will follow that pattern.

**Comment by psibi** [comment]
@israel-hdez Thanks, that sounds good to me. :-)
