### ISSUE TITLE
Service entries should be assigned to the same cluster as the relevant service

### ISSUE THREAD

**Issue by jshaughn** [kiali/kiali#3938]
This originated in but really isn't related to #3879.  @lucasponce had this comment:

... I see this weird:
![image](https://user-images.githubusercontent.com/1662329/115883069-ab66a500-a44d-11eb-875f-6878219b5db0.png)

I understand it, as I created that example, and I see that ServiceEntry belongs to that namespace because is where the definition lives, but to move it to an unknown cluster sounds weird. I understand that is because it comes from telemetry, but I wonder if there is a different possibility of wording.

My reply and the source of this issue:

@lucasponce Service Entry handling is a constant work in progress. Looking at this I agree with you, a service entry should not have an unknown cluster as it's supposed to be associated with a service, which itself is in a cluster. It may be exported to 1..N namespaces, but those namespaces should all be within a cluster. We need to figure out if why this is "unknown", it could be a problem in Istio as part of the SE definitions returned from k8s, or it could be a problem in Kiali making a proper assignment of the cluster. I'd probably lean towards the latter case and maybe a missed case in the recent cluster work on our side.

**Comment by jshaughn** [comment]
@nrfox I'm assigning this one to you because it's in the same ball park as your last fix, it likely has to do with a graph appender, `service_entry.go`, and also cluster assignment for a node.  Please start by spending time learning about Istio service entries and then you can start looking at what we try to do in order to understand if a service request is actually handled by a service entry, in which case the appender massages the traffic map.  It's a bit tricky and it's not unlikely that we still don't have it completely right, but this specific problem may be a reasonable blatant.

**Comment by nrfox** [comment]
@jshaughn it does look similar to the idle node cluster bug where we are just created a node an an unknown cluster: https://github.com/kiali/kiali/blob/master/graph/telemetry/istio/appender/service_entry.go#L94. We might want to display Service Entries differently based on their location though? If the service entry is `MESH_INTERNAL` then we'll add the node to the home cluster but if it's `MESH_EXTERNAL` add it to the `unknown` cluster?

**Comment by jshaughn** [comment]
>  If the service entry is MESH_INTERNAL then add the node to the home cluster but if it's MESH_EXTERNAL add it to the unknown cluster?

I don't think that MESH_INTERNAL vs MESH_EXTERNAL will play into the cluster assignment.  If I understand it, those values are more declaring whether the actual, requested service, resides in mesh or outside of mesh.  The service entry is sort of the facade representing the destination service, when that destination service isn't a typically declarable endpoint.  And so I think what we want here is to assign a cluster to the service entry itself.  A service entry definition is exported, by default, to every namespace on the cluster, or it can be limited to specific namespaces using the exportTo attribute.  But either way, I think it would all be on the home cluster.   To maybe be more correct it should have the cluster of the "se-service" node, meaning the original service node that is being replaced by the service entry node.  But, since several se-service nodes can be replaced by the same "se-aggregate" there may be a chance that cluster could differ.  But, that is not a concern for now because all of the service entry definitions are coming from the home cluster.  For now I think it would be surfficient to just use home-cluster, but if you want to try and handle creating different se-aggregate nodes based on the cluster of the se-service node, it may be more future-proof for when we potentially deal with more unified multi-cluster views.  Personally, I'm in favor of an incremental approach and for now, the simple solution should satisfy the issue.

**Comment by nrfox** [comment]
> I don't think that MESH_INTERNAL vs MESH_EXTERNAL will play into the cluster assignment. If I understand it, those values are more declaring whether the actual, requested service, resides in mesh or outside of mesh. The service entry is sort of the facade representing the destination service, when that destination service isn't a typically declarable endpoint. And so I think what we want here is to assign a cluster to the service entry itself.

That's my understanding as well. I was thinking that if you've got a workload talking to `api.dropboxapi.com` and there's a service entry for that external host, that service entry node should be outside of the homecluster since `api.dropboxapi.com` actually exists outside of the cluster that your workload is in. Otherwise it might appear that `api.dropboxapi.com` is a service that is running inside of your cluster. Whereas if you've got a service entry for something inside of the mesh then that would presumably be a service that's running inside of the homecluster.

> For now I think it would be surfficient to just use home-cluster, but if you want to try and handle creating different se-aggregate nodes based on the cluster of the se-service node, it may be more future-proof for when we potentially deal with more unified multi-cluster views. Personally, I'm in favor of an incremental approach and for now, the simple solution should satisfy the issue.

An incremental/smaller change now sounds good!

**Comment by jshaughn** [comment]
> That's my understanding as well. I was thinking that if you've got a workload talking to api.dropboxapi.com and there's a service entry for that external host, that service entry node should be outside of the homecluster since api.dropboxapi.com actually exists outside of the cluster

That approach could be justified but this goes to the root of this created issue.  The graph above was confusing, or at least unexpected.  Service entries are associated with a namespace.  And namespaces are within a cluster.  In the diagram, it isstrange to see a namespace in the "unknown" cluster.  Despite the requested host being out in the wild, I think it does make sense to pull the node into the cluster.  A small change now will resolve this issue and we may get more user feedback as more people try out multi-cluster and/or cluster boxing.

One note, if you omit a service entry your request will likely be handled by either the PassthroughCluster (allow the request) to or the BlackHoleCluster (block the request).  These are default request handlers in Istio and they will show up with namespace="unknown" and cluster="unknown".   So, having the service entry within a ns and cluster also distinguises it from these default handlers.

**Comment by nrfox** [comment]
> The graph above was confusing, or at least unexpected. Service entries are associated with a namespace. And namespaces are within a cluster. In the diagram, it isstrange to see a namespace in the "unknown" cluster. Despite the requested host being out in the wild, I think it does make sense to pull the node into the cluster.

That's a good point that service entries are associated with a namespace and that's what makes the graph above confusing. Agreed, I'll go ahead and make the change.
