### ISSUE TITLE
Service tracing tab display options resulting in error 

### ISSUE THREAD

**Issue by brendarearden** [kiali/kiali#3939]
**Describe the bug**
When attempting to change the Display value on a service's tracing page, an error occurs saying `cannot not parse minDuration: time: missing unit duration "49265"` After this error shows on the page, the the display dropdown becomes disabled. Sometimes the error stays until you re-deploy the pod, sometimes the error corrects itself by navigating to a different serve and then back.

I am able to see the tracing information if I do not touch the display drop down at all. 

![Screen Shot 2021-04-23 at 4 50 36 PM](https://user-images.githubusercontent.com/19455540/115940029-f801ae80-a454-11eb-9e90-ead0467d780b.png)

**Versions used**
Kiali: v1.32.0
Istio: v1.9.3
Kubernetes flavour and version: (e.g. OpenShift Origin 3.9): k3d

**To Reproduce**
1. Install Istio v1.9.3 by installing the latest istioctl and running `istioctl install --set profile=demo
3. Install jaeger using the https://istio.io/latest/docs/ops/integrations/jaeger/#option-1-quick-start instructions - or deploy the jaeger all in one docker container https://www.jaegertracing.io/docs/1.22/getting-started/#all-in-one 
2. Use Helm 3 to install Kiali v1.32.0 kiali-server helm chart from https://github.com/kiali/helm-charts/tree/master/kiali-server 
  - when installing kiali, configure the external_services.tracing.in_cluster_url=<your in_cluster jaeger url>. Do not set the url, or any auth stuff: 
 Example: 
```
  external_services:
    tracing:
      in_cluster_url: "http://tracing.istio-system.svc:16686/jaeger"
```
3. Deploy a sample application that has several services that you can create traffic to view in kiali (I used the istio bookinfo application https://istio.io/latest/docs/examples/bookinfo/#start-the-application-services) 
4. After generating enough traffic to be picked up by kiali, navigate to a service  and then click on the tracing tab
5. Click on the display drop down and select a different display percentile. 
6. See error

**Expected behavior**
The display percentile call should work or should fail gracefully if the data is not available. 

**Additional Notes**
https://github.com/kiali/kiali/blob/f548b562303ebd7d4dc82ec3f24ae1336b5bccd8/jaeger/traces.go#L53 << it does look like you have recently made changes to functionality that is currently erroring 

I set up the core of the jaeger api function that is erroring here: https://play.golang.org/p/FDEW-fKAB8R  Based on the erroring that I am seeing occasionally, I think something is happening with how you are setting the query param so the units are not making it to jaeger.

**Comment by lucasponce** [comment]
Thanks @brendarearden and sorry for the delay, I remember seeing a similar error, I assigned to me to investigate.
