### ISSUE TITLE
Kiali is overloading OCP API when having 2000 namespaces in the mesh

### ISSUE THREAD

**Issue by FilipB** [kiali/kiali#3957]
**Describe the bug**
When having 2000 namespaces in accessible_namespaces following is visible in kiali.log:
`request.go:655] Throttling request took 4m30.536504894s, request: POST:https://172.30.0.1:443/apis/authorization.k8s.io/v1/selfsubjectaccessreviews`

Note that namespaces are empty as we can't have so many real apps in our cluster.

**Versions used**
Kiali UI
    1.34.0 (6bdefa08b66623eaf5bf26a27fc5706ab949ff14)
Kiali Server
    v1.34.0-SNAPSHOT (c24921a1455842413a304535aa414513dc7ce64b)
Istio: 1.9.3 
Kubernetes flavour and version: (e.g. OpenShift Origin 3.9)
OCP 4.7

**To Reproduce**
1. create 2000 empty namespaces
2. update accessible_namespaces in kiali CR
3. wait for reconciliation
4. See error in kiali.log

**Comment by sergiomacedo** [comment]
@FilipB we seem to be facing similar problems. Do you have monitoring enabled for apiserver errors?

**Comment by FilipB** [comment]
> @FilipB we seem to be facing similar problems. Do you have monitoring enabled for apiserver errors?

Not yet. This was just first quick test. We plan to do more scalability testing during next month. Goal is to find and fix similar issues.

**Comment by lucasponce** [comment]
Scalability discussion https://github.com/kiali/kiali/discussions/4080

**Comment by lucasponce** [comment]
This https://github.com/kiali/kiali/issues/4678 is related.
Under a high number of namespaces, I don't think the current design is scalable for keeping one informer x type x namespace.

We'd need to grant cluster permissions to Kiali to (at least) fetch Kubernetes API with the --all-namespaces syntax.

I'm sure that will improve the situation in these cases.

**Comment by nrfox** [comment]
Note the error here is from `/selfsubjectaccessreviews`: which is a `POST` request and can't benefit from caching: https://github.com/kiali/kiali/blob/fd32c400240cc5d01fc3eadfb74fe8e120a11b9f/kubernetes/kubernetes.go#L499-L507 It looks like Kiali sends at least 2 requests per namespace when the `/api/istio/permissions` route is hit: https://github.com/kiali/kiali/blob/fd32c400240cc5d01fc3eadfb74fe8e120a11b9f/business/istio_config.go#L736-L774 Similar to what was discussed in the [health appender parallelization PR](https://github.com/kiali/kiali/pull/4816), this is another area that could benefit from a request pool rather than firing off all the requests at once.

**Comment by lucasponce** [comment]
>  looks like Kiali sends at least 2 requests per namespace when the /api/istio/permissions route is hit

But this query has been removed from the page, it should only happen when the user opens a specific actions menu or detail.

My comment was more related that having 2000xN informers is not scalable, that's it, those are 2000xN open connections to the k8s API.

In such cases is not a matter of parallelization but using some approach as done for the Istio calls, but for that, it would require cluster rights.

**Comment by lucasponce** [comment]
This effort is still valid, but the original issue 

```
Throttling request took 4m30.536504894s, request: POST:https://172.30.0.1:443/apis/authorization.k8s.io/v1/selfsubjectaccessreviews
```

is addressed as the use of the "SelfSubjectAccessReviews" is improved in recent versions.

I'm going to close this one in favor of https://github.com/kiali/kiali/issues/4678 and recent issues and discussions around scalability on large namespaces scenarios.
