### ISSUE TITLE
No edges from service to istio engressgateway

### ISSUE THREAD

**Issue by pandagodyyy** [kiali/kiali#3959]
https://github.com/istio/istio/issues/32196
the same issue already reported in Istio community.

And I checked in Prometheus, actually there are telemetries which from service to egreegateway.
`stio_requests_total{app="sleep",connection_security_policy="unknown",destination_app="unknown",destination_canonical_revision="latest",destination_canonical_service="istio-egressgateway",destination_cluster="unknown",destination_principal="spiffe://cluster.local/ns/istio-system/sa/istio-egressgateway-service-account",destination_service="istio-egressgateway.istio-system.svc.cluster.local",destination_service_name="istio-egressgateway",destination_service_namespace="istio-system",destination_version="unknown",destination_workload="istio-egressgateway",destination_workload_namespace="istio-system",instance="100.96.0.150:15020",istio_io_rev="default",job="kubernetes-pods",kubernetes_namespace="main",kubernetes_pod_name="sleep-584bd5c57b-4h5rc",pod_template_hash="584bd5c57b",reporter="source",request_protocol="http",response_code="200",response_flags="-",security_istio_io_tlsMode="istio",service_istio_io_canonical_name="sleep",service_istio_io_canonical_revision="40.0.1-SNAPSHOT-20210428091309_4d6883eab3e2438cb03cdcd64d989bf9",source_app="sleep",source_canonical_revision="40.0.1-SNAPSHOT-20210428091309_4d6883eab3e2438cb03cdcd64d989bf9",source_canonical_service="sleep",source_cluster="Kubernetes",source_principal="spiffe://cluster.local/ns/main/sa/default",source_version="40.0.1-SNAPSHOT-20210428091309_4d6883eab3e2438cb03cdcd64d989bf9",source_workload="sleep",source_workload_namespace="main",version="40.0.1-SNAPSHOT-20210428091309_4d6883eab3e2438cb03cdcd64d989bf9"}`

**Comment by jmazzitelli** [comment]
Is this a bug in Kiali? Seems to me Kiali is just graphing what telemetry exists. If this is a bug in the way Istio telemetry is collected, then this is not a kiali bug - nothing Kiali can do since the data is missing from telemetry.

**Comment by jshaughn** [comment]
@pandagodyyy It's not easy to know if there is an issue here.   The telemetry you provided in the description would indicate that at some point in time there was http traffic from `main:sleep` to `istio-system:istio-egressgateway`.  But I can't confirm there was traffic for the time period you were graphing.  Do you have a screenshot of your issue?   Try generating a workload graph and enable service nodes, idle edges and idle nodes in the Display options.  Make sure to select the `main` namespace in the namespace selector.
