### ISSUE TITLE
fatal error: concurrent map read and map write on IsNamespaceCached

### ISSUE THREAD

**Issue by juliantaylor** [kiali/kiali#3964]
in our larger clusters kiali crashes constantly with:

```
2021-04-29T12:20:24Z INF Kiali: Version: v1.32.0, Commit: 166ffcc9edfc6fdd8c6ce8e74eb5670414b949f5

2021-04-29T12:20:24Z INF Using authentication strategy [anonymous]
2021-04-29T12:20:24Z WRN Kiali auth strategy is configured for anonymous access - users will not be authenticated.
2021-04-29T12:20:24Z INF Kiali: Console version: 1.32.0
2021-04-29T12:20:24Z INF Generating env.js from config
2021-04-29T12:20:24Z INF Server endpoint will start at [:20001/]
2021-04-29T12:20:24Z INF Server endpoint will serve static content from [/opt/kiali/console]
2021-04-29T12:20:24Z INF Starting Metrics Server on [:9090]
2021-04-29T12:20:40Z INF Kiali Cache is active for namespaces [.*]
2021-04-29T12:20:40Z INF [Prom Cache] Enabled

2021-04-29T12:20:40Z INF Waiting for Kiali cache for [namespace: mynamespace] to sync
2021-04-29T12:20:41Z INF Kiali cache for [namespace: mynamespace] started
fatal error: concurrent map read and map write

goroutine 2377 [running]:
runtime.throw(0x1b0b984, 0x21)
        /usr/local/go/src/runtime/panic.go:1117 +0x72 fp=0xc003848e08 sp=0xc003848dd8 pc=0x437072
runtime.mapaccess2_faststr(0x18ae760, 0xc00061c210, 0xc002275d64, 0x6, 0x0, 0x0)
        /usr/local/go/src/runtime/map_faststr.go:116 +0x4a5 fp=0xc003848e78 sp=0xc003848e08 pc=0x414265
github.com/kiali/kiali/kubernetes/cache.(*kialiCacheImpl).CheckNamespace(0xc000269a40, 0xc002275d64, 0x6, 0x0)
        /home/fedora/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/kubernetes/cache/cache.go:200 +0x9b fp=0xc003848ed0 sp=0xc003848e78 pc=0x165287b
github.com/kiali/kiali/business.IsNamespaceCached(...)
        /home/fedora/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/business/layer.go:59
github.com/kiali/kiali/business.IsResourceCached(0xc002275d64, 0x6, 0x1af3340, 0x10, 0x0)
        /home/fedora/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/business/layer.go:64 +0xa2 fp=0xc003848f00 sp=0xc003848ed0 pc=0x16a8842
github.com/kiali/kiali/business.(*TLSService).getAllDestinationRules.func1(0xc0020762a0, 0xc0008cc338, 0xc002f93e60, 0xc002f93e00, 0xc002275d64, 0x6)
        /home/fedora/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/business/tls.go:76 +0x96 fp=0xc003848fb0 sp=0xc003848f00 pc=0x16d21f6
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc003848fb8 sp=0xc003848fb0 pc=0x46d3a1
created by github.com/kiali/kiali/business.(*TLSService).getAllDestinationRules
        /home/fedora/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/business/tls.go:70 +0x13f

```

The clusters have more than 3000 pods in them, we have not yet identified what kind of change is causing this, but it looks like some locking is not correct in kiali.
We are using the dockerhub image kiali/kiali:v1.32.0 on x86_64

This issue appeared after updating from 1.15.1 to 1.32.0.

**Versions used**
Kiali:v1.32.0
Istio: 1.8.4

**Comment by lucasponce** [comment]
Thanks, did you see this error before ? or just when some upgrade in the kiali image ?

**Comment by juliantaylor** [comment]
Yes sorry I forgot, this issue appeared after updating from 1.15.1 to 1.32.0.

**Comment by juliantaylor** [comment]
do you need the whole log output? it are 2500 goroutines so the full log is rather large

**Comment by lucasponce** [comment]
@juliantaylor thanks, unfortunately I don't have a 3000 pods cluster to test in real time but I'll try to simulate with some mockups.
How many namespaces do you have ?

> do you need the whole log output? it are 2500 goroutines so the full log is rather large

I can ask you later if I don't get a clear picture.

How did you upgrade ? Just to check if this error is via some side effect in the upgrade.

**Comment by juliantaylor** [comment]
a gist actually seems to accept the full log:
https://gist.github.com/juliantaylor/7736550423ccb65e5b00fded706aeb26

the cluster it currently happens in has 640 namespaces.

We updated the charts to your latest helm charts with some minor modifications which should not be related and applied with kubectl apply.

The crash to me indicates that you are trying to concurrently access a shared resources from multiple goroutines without locks. I dont think that can be related to the way it was upgraded.

**Comment by juliantaylor** [comment]
I don't know go very much but as it is throwing here:
https://github.com/kiali/kiali/blob/master/kubernetes/cache/cache.go#L200
I think the lock should be outside of the condition as checking a key existance is reading the map which apparently cannot be done at the same time another routine is writing to it.

**Comment by lucasponce** [comment]
> I don't know go very much but as it is throwing here:
https://github.com/kiali/kiali/blob/master/kubernetes/cache/cache.go#L200
I think the lock should be outside of the condition as checking a key existance is reading the map which apparently cannot be done at the same time another routine is writing to it.

Yes, it seems that missed our testing at scale.

I'll take a look, I'll ping you when I have something ready to help me to test it :).

Thanks for the details.

**Comment by lucasponce** [comment]
@juliantaylor a workaround that you can test until we resolve this issue.

Cache is configurable, you may disable all (but I suspect performance may suffer a severe hit):

https://github.com/kiali/kiali-operator/blob/master/deploy/kiali/kiali_cr.yaml#L727

Or play with caching only certain namespaces:

https://github.com/kiali/kiali-operator/blob/master/deploy/kiali/kiali_cr.yaml#L744

If your cluster has a kinda fixed number of namespaces (instead of a lot of creation) you may increase the cache that is failing:

https://github.com/kiali/kiali-operator/blob/master/deploy/kiali/kiali_cr.yaml#L751

But this is just a workaround to avoid the fail you get until we prepare a fix.

**Comment by juliantaylor** [comment]
Disabling the cache fixed the crashing, but it is slower and uses a lot of cpu (about 3 cpus constantly) which is probably not unexpected with a disabled cache. I can do some tests with disabling namespaces for testing tomorrow, but I expect it will just make the crash less likely.

**Comment by lucasponce** [comment]
> Disabling the cache fixed the crashing, but it is slower and uses a lot of cpu (about 3 cpus constantly) which is probably not unexpected with a disabled cache. 

I know, it's a big scenario, also check this know perf issue:

https://kiali.io/documentation/latest/faq/#dashboards-discovery-perf

> I can do some tests with disabling namespaces for testing tomorrow, but I expect it will just make the crash less likely.

Thanks, I've started to take a look, I'll update the issue when I have some progress.

**Comment by juliantaylor** [comment]
A better workaround is setting GOMAXPROCS to 1 in the deployments environment. Our machines have 40 physical cpus (80 "threads") so it defaulted to 80 GOMAXPROCS which is far too high for pretty much any deployment.

a value of one serializes the cpu running code so it should not hit the race condition. Our cpu pod limit is set to 1 anyway so performance is not really impacted.
