### ISSUE TITLE
Application details - Workloads are shown wrongly

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#3973]
Happens on master with bookinfo with mysqldb:

Go to 'ratings' app details.
The list of workloads shows 'rating-v2' twice, the second should be 'ratings-v2-mysqldb':
![Screenshot from 2021-05-03 08-32-00](https://user-images.githubusercontent.com/604313/116847687-582de880-abeb-11eb-9521-9d1bbf5bd89d.png)
![Screenshot from 2021-05-03 08-31-28](https://user-images.githubusercontent.com/604313/116847694-5bc16f80-abeb-11eb-81c8-e4f181251593.png)

**Comment by lucasponce** [comment]
Nice catch.

**Comment by lucasponce** [comment]
@hhovsepy can you show me the list of workload ?

I have this

![image](https://user-images.githubusercontent.com/1662329/116851359-8531c980-abf2-11eb-9d34-9b0c1e553989.png)

But I can't reproduce that error:

![image](https://user-images.githubusercontent.com/1662329/116851386-8f53c800-abf2-11eb-8c26-72daeb1f1dfc.png)

I suspect I'm missing some scenario you used in your demo.

**Comment by lucasponce** [comment]
Ok, my bad, I have the same error now:

![image](https://user-images.githubusercontent.com/1662329/116852513-b9a68500-abf4-11eb-8fd6-2c7067e96f7e.png)
