### ISSUE TITLE
Istio gateway pod logs are not treated as Envoy proxy logs

### ISSUE THREAD

**Issue by jshaughn** [kiali/kiali#3977]
This may be a bug, or it may be expected, it depends on what our expectation is for Pod.IstioContainers.  My thinking was that Pod.IstioContainers was really just equivalent to "Pod.IstioProxy", as the expectation seems to be that this will always be empty or just hold one container, the proxy.  If that is the case then for istio-ingressgateway and istio-egressgateway the container should be returned in  Pod.IstioContainers and not Pod.Containers, as the container IS a proxy.

The problem currently is that despite ingress and egress generating envoy proxy logs, the new workload pod logs view is not treating them that way, and so it doesn't offer the parsed logs.

This problem could also be solved on the client, but I wrote this up because a server-side change may be the correct thing to do, as it would then apply to any client caller.  Looking for an opinion from @lucasponce or anyone else.

**Comment by jshaughn** [comment]
@lucasponce Did you have an opinion on this?  I have a server-side fix local on my box but waiting for feedback.

**Comment by lucasponce** [comment]
> Pod.IstioContainers and not Pod.Containers, as the container IS a proxy.

Not sure if this will work in all cases, but +1 to see in the PR and test.
I understand that the workload logs tab doesn't work well in those cases so a edge case is perfectly valid to address that.

(Sorry, I completely missed this notification in github)
