### ISSUE TITLE
Support for custom istio injection labels and values

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#3988]
Hi all,

By default,  the Kiali UI add/remove the _istio-injection_ label then set to _enabled/disabled_ values to setup a namespace for sidecar injection.

With Istio's canary control plane support,  this label is deprecated in favor of the **istio.io/rev** label set to the Istio control plane release value (set by the admin).  I.e.  istio.io/rev=1-9-4

I believe the Kiali CR can set a custom label for injection as defined here: https://github.com/kiali/kiali-operator/blob/master/deploy/kiali/kiali_cr.yaml#L679

But what about the value ?   Or is this ^^^ not doing what I think ?

thanks !

_Originally posted by @somejfn in https://github.com/kiali/kiali/discussions/3985_

[1] https://istio.io/latest/docs/setup/upgrade/canary/

**Comment by jmazzitelli** [comment]
Can I ask for a discussion around the names of the new settings being introduced. I supplied a couple suggestions in the operator PR but figured start a discussion here.

The two new settings `istio_current_revision` and `istio_upgrade_revision` aren't clearly related to each other - by that I mean it isn't clear to the user they are part of the same feature AND that if you set on you need to set the other.

I suggested we rename these and put them inside a struct like:

```
istio_canary_revision:
  current: "1.8"
  upgrade: "1.9"
```

This makes it more clear that (a) these involve canary version numbers and (b) you need to set both together.

**Comment by lucasponce** [comment]
> This makes it more clear that (a) these involve canary version numbers and (b) you need to set both together.

+1

**Comment by hhovsepy** [comment]
Question to community:
wdyt, should "Enable/Disable/Remove Auto Injection" functionality still be available on Overview Page when Canary upgrade functionality is enabled?
Because if can cause mess in labeling on namespace. I think it is better to hide "Enable/Disable/Remove" actions when Canary upgrade is enabled.

**Comment by lucasponce** [comment]
> Because if can cause mess in labeling on namespace. I think it is better to hide "Enable/Disable/Remove" actions when Canary upgrade is enabled.

It sounds ok to me, as both features have feature flags to enable/disable is good to choose one approach, to document/describe/demo the feature to collect feedback and iterate on it.

The feature itself doesn't add additional value (i.e. just adding labels at namespace level) but the context of identifying the dataplane namespaces that are pointing to one version or another of the control plane can be very useful.

So, as you're working on the area, I suggest you to take the approach that makes more sense and let's iterate.

**Comment by lucasponce** [comment]
This first work for this feature is consolidated:
![image](https://user-images.githubusercontent.com/1662329/125269663-35196680-e309-11eb-9545-25781815e428.png)

There will be more iterations but with additional issues.
