### ISSUE TITLE
Feature request: mesh-status view

### ISSUE THREAD

**Issue by liamawhite** [kiali/kiali#400]
Kiali should have a dashboard view that allows a user to visualise the status of their mesh using the `/debug/syncz` information that can be retrieved from each Pilot. For an example of this see this `proxy-status` output [here](https://istio.io/help/ops/traffic-management/proxy-cmd/#get-an-overview-of-your-mesh).

This would give users a high level view of where potential issues with their mesh may be and where things may be out of sync.

I wrote the syncz code so if you have any questions or requests for extra information from this endpoint let me know. 🙂

**Comment by jmazzitelli** [comment]
Interesting - we currently have been going through some design discussions on this kind of "overview" page. See: https://github.com/kiali/kiali-design/issues/22 - feel free to inject yourself in that discussion :)

**Comment by liamawhite** [comment]
Potentially yes, maybe displaying a warning if something is stale. 

Bonus points if you can click through and get a diff like [this](https://istio.io/help/ops/traffic-management/proxy-cmd/#retrieve-diffs-between-envoy-and-istio-pilot). That's slightly more involved and I wouldn't recommend calling this endpoint constantly as it regenerates the routes for that proxy, so stick to it as a click through maybe.

It does not respond in tabular format, [here](https://github.com/istio/istio/blob/master/pilot/pkg/proxy/envoy/v2/debug.go#L85) is the struct that is used. Also you will need to call each Pilot and merge the responses.

**Comment by abonas** [comment]
this is a great idea, thanks for raising this @liamawhite . 
Indeed we've been discussing [here](https://github.com/kiali/kiali-design/issues/22) and [here](https://github.com/kiali/kiali-design/pull/21) the overview concept showing the mesh status.
I think that the concept suggested here with syncz is more about Istio configuration level, while the concept which we are discussing is more of a health overview on applicative level (which of course can be influenced by lack of sync :) ) 
I think both have a well needed place in Kiali, but we need to think further how to combine them.
@liamawhite  - feel free to correct me if I got it wrong.
cc @cshinn @serenamarie125

**Comment by liamawhite** [comment]
Yes, this is about Istio health. Specifically each proxy.

If the proxies aren't healthy your application won't be though 🙁

**Comment by pilhuhn** [comment]
+1 @liamawhite This is why I said it should be part of the overall health computation and the result of the computation should end up in the overview card. If health is deteriorated, then the user an drill in to find the problem.

**Comment by abonas** [comment]
@jotak ^^ wdyt to include this in the health calculations/additional health properties?

**Comment by jotak** [comment]
Looks like a good addition to health indeed. So if we take the proxy-status overview it gives sync state for all proxies (hence pods). We currently don't provide pod-level health but that can be aggregated into workload-level and app-level health.

And for the future overview page, aggregated in namespace-level health.

The other capabilities of `proxy-status` sound more like debugging information that wouldn't come in health but eventually in workload details pages, I guess.

**Comment by abonas** [comment]
@liamawhite can you please point me to documentation about CDS,LDS,EDS and RDS that are the columns in proxy-status command?

**Comment by liamawhite** [comment]
Those are all envoy concepts. https://www.envoyproxy.io/docs/envoy/v1.7.1/intro/arch_overview/dynamic_configuration

**Comment by jshaughn** [comment]
See https://issues.jboss.org/browse/KIALI-2959 for activity related to this issue.

**Comment by jshaughn** [comment]
@liamawhite A question about  CDS, LDS, EDS, RDS.   Are the values for all of these services relevant to the proxy pod health?  Any moreso than others?  And is STALE basically the problem-scenario?

**Comment by liamawhite** [comment]
These values show that Pilot has sent (and Envoy has ACKed) config to each Envoy. Assuming that you have collected responses from every Pilot in the mesh the possible permutations are as follows (assuming Kube for the sake of terminology):

**Service not in this list**
This means that it's Envoy is not connected to any Pilots currently. This has two permutations. One, the Envoy has lost connection but has synced previous config. In this case, the pod could still be successfully serving traffic but won't know about any new updates such as new pods or deleted pods. The longer this goes on the more unhealthy the pod will get. Two, the Envoy has never synced and will definitely be failing if it is sent any requests. In this case, it has no idea about the world outside its pod.

** STALE **
This is the same outcome as the first permutation above just manifested differently. This is likely to be caused by invalid config being sent to Envoy (probably Istio bug), an overloaded Pilot (user should scale up Pilot) or we just managed to hit a timing window where it's waiting on an ack from Envoy. I would recommend you make a second request if you see any STALE in the response and if a pod is STALE in both only then consider it STALE.

** STALE (NEVER ACKNOWLEDGED) **
This is the same outcome as the second permutation above just manifested differently. This is likely to be caused by invalid config being sent to Envoy (probably Istio bug).

** SYNCED **
As far as Pilot is concerned the pod is healthy.

**Comment by jshaughn** [comment]
This is now tied to epic #2235 and so I'm removing discussion-needed.  Epic owner can decide on how to handle this.

**Comment by jshaughn** [comment]
Some work in this area has been merged, see https://github.com/kiali/kiali/issues/1377.

**Comment by xeviknal** [comment]
Closing the issue per https://github.com/kiali/kiali/pull/3126
I guess that the issue evolved to be slightly incorporated to kiali feats (health so far).
