### ISSUE TITLE
Using source/destination service principal in hide expressions

### ISSUE THREAD

**Issue by dsabsay** [kiali/kiali#4000]
**Is your feature request related to a problem? Please describe.**
When using Prometheus to collect application metrics over mTLS (using injected Istio certs), Promethues shows up as an `unknown` node on the Kiali graph.

**Describe the solution you'd like**
In #2939, source/destination principals were added to each edge. Since Prometheus is using Istio's certs, it has a service principal that identifies it. It would be great if one could hide edges/nodes based on principal. For example, `source_principal = spiffe://cluster.local/ns/monitoring/sa/prometheus`.

**Describe alternatives you've considered**
I'm aware I can hide this with `node = unknown` in the `Hide` panel, but I'd rather be more selective, so the graph still potentially shows me other traffic I don't know about yet.

I'm also aware you can tell Istio to omit metrics based on User-Agent, but again, I'd rather see everything and selectively filter things out.

**Comment by jmazzitelli** [comment]
cc @jshaughn - something to add to the show/hide feature.

**Comment by jshaughn** [comment]
I'll take a look at this, I think it would be an easy addition to Find/Hide to add principal as an operand.  My only concern is whether that information is supplied on an "unknown" source or destination.  @dsabsay , are you sure it's there?  Either way this is still a reasonable addition to Find/Hide.

**Comment by dsabsay** [comment]
![Screen Shot 2021-05-12 at 11 36 19 AM](https://user-images.githubusercontent.com/11727932/118027042-57493500-b316-11eb-9b09-9549105ea82c.png)

@jshaughn Awesome! It's there when the **Security** display option is enabled.

**Comment by jshaughn** [comment]
@dsabsay PR created, will be in the 1.35 release.  Note that you can use any string operator, like contains, startswith, etc  (or the short forms *=, ^=, etc)
