### ISSUE TITLE
Difference between App and Workload healths - causing inconsistency in Overview

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#4009]
Happens on master.
Workload and Service details are showing status as Failure because of Traffic.
![Screenshot from 2021-05-13 11-49-49](https://user-images.githubusercontent.com/604313/118116258-5a155a00-b3ea-11eb-9167-a6f907d3bd8e.png)
![Screenshot from 2021-05-13 11-49-58](https://user-images.githubusercontent.com/604313/118116261-5aadf080-b3ea-11eb-8ce4-7bdd823a8ef0.png)

But in Application details status is shown as Healthy:
![Screenshot from 2021-05-13 11-50-04](https://user-images.githubusercontent.com/604313/118116316-6ef1ed80-b3ea-11eb-85a6-cb9471b64058.png)

Another inconsistency is in Overview page, where the application is shown as Failure:
![Screenshot from 2021-05-13 11-50-27](https://user-images.githubusercontent.com/604313/118116506-a496d680-b3ea-11eb-8e2b-9707e56a5e93.png)
But linking to Apps does not show that failure app:
![Screenshot from 2021-05-13 11-50-35](https://user-images.githubusercontent.com/604313/118116592-bf694b00-b3ea-11eb-8c96-ab2036206fd4.png)

**Comment by lucasponce** [comment]
Ah, I think I saw something similar, there should be a linked issue, let me find it.

**Comment by lucasponce** [comment]
It sounds similar as this one https://github.com/kiali/kiali/issues/3904

Because I can see this feature working as expected in other namespaces:
![image](https://user-images.githubusercontent.com/1662329/118117299-bfb61600-b3eb-11eb-97f2-86c757eef1c3.png)

So, I suspect it may be related.

I question from my side, time selectors are not yet synced across all tabs, so logs, metrics and traces may have a different time duration compared with overview or graph (this comes from a technical debt that we haven't yet addressed as in the past, the feature worked in that sense that every tab could select its own state).

**Comment by lucasponce** [comment]
Co-asigned this issue to @hhovsepy and @lucasponce
This one can a good one for Hayk to catch up with the code and getting familiar with this logic.

**Comment by jshaughn** [comment]
> time selectors are not yet synced across all tabs, so logs, metrics and traces may have a different time duration compared with overview or graph (this comes from a technical debt...

The disparity in time range is intentional due to the different nature of metrics and graph/overview.  Metrics provide a better view over an extended time whereas graph and overview are more often looking at near-term state.

**Comment by hhovsepy** [comment]
It seems that for broken application, the rest api returns empty health requests, which are causing App details to ignore the inbound error rate and show healthy.

**Comment by lucasponce** [comment]
> It seems that for broken application

Perhaps I introduced this regression in the details refactoring, which is a broken app ? pod errors or traffic errors ?

**Comment by hhovsepy** [comment]
> > It seems that for broken application
> 
> Perhaps I introduced this regression in the details refactoring, which is a broken app ? pod errors or traffic errors ?

Traffic errors of 'productpage' app, happened after too much tests run on environment, non constantly reproducible.

**Comment by hhovsepy** [comment]
VS and DR created on productpage service:
`spec:
  hosts:
    - bookinfo-istio-system.apps.ocp4-kqe1.maistra.upshift.redhat.com
  gateways:
    - bookinfo-gateway
  http:
    - match:
        - uri:
            exact: /productpage
        - uri:
            prefix: /static
        - uri:
            exact: /login
        - uri:
            exact: /logout
        - uri:
            prefix: /api/v1/products
      route:
        - destination:
            host: productpage
            port:
              number: 9080
`
DR:
`spec:
  host: productpage
  subsets:
    - labels:
        version: v1
      name: v1`

**Comment by hhovsepy** [comment]
Cannot reproduce this issue anymore. After fixing of https://github.com/kiali/kiali/issues/3904
