### ISSUE TITLE
Sparkline tooltip hovering issues

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#4011]
There seems to be some odd behavior with the sparkline tooltip when a refresh happens.

1. When a refresh happens (time snapshot moves forward by the interval), I would expect the tooltip to "follow" where my mouse is currently hovering. Instead the tooltip follows the last point that was highlighted that has now moved to the left since the time window has changed.
2. The tooltip disappears and does not reappear until navigating outside the sparkline after a refresh.

Both issues are illustrated here:
![tooltipmissing](https://user-images.githubusercontent.com/6226732/118185888-1121cd80-b40b-11eb-83cc-3c8e5244006e.gif)

The first issue is more obvious from this screenshot where the tooltip is referring to a point that is "off screen" after a refresh.

![Screenshot from 2021-05-13 16-22-13](https://user-images.githubusercontent.com/6226732/118186053-43332f80-b40b-11eb-8d39-34ec69f4ddc9.png)

3. The data point is not highlighted on the sparkline. I'm not sure if this a bug or it was removed intentionally but from this: https://user-images.githubusercontent.com/1312165/74496122-95934280-4e8e-11ea-99f6-8b51ffd462bf.gif it looks like the sparkline datapoints were once "highlighted" when hovered over and no longer are.

**Comment by lucasponce** [comment]
I'm sure there is a related issue for this, the root case is some conflict with the tippy dependency in the UI.

**Comment by lucasponce** [comment]
Related https://github.com/kiali/kiali/issues/3583

**Comment by nrfox** [comment]
Ah it seems like this is a duplicate of that one then. At least resolving that issue would probably fix one or all of these. I'll close this as a duplicate and we can re-open if resolving that issue doesn't fix these.
