### ISSUE TITLE
Cache EnvoyFilter objects

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#4015]
The Kiali server does not currently cache `EnvoyFilter` objects and instead gets these directly from the kube API. `EnvoyFilters` are a low traffic object and adding them to the cache probably wouldn't help much with performance right now but it could have more of an impact in the future.

**Comment by lucasponce** [comment]
Revisiting this in #4024, not having all Istio resources on caching may cause some cornercase scenario on OpenShift, where user token are propagated.
