### ISSUE TITLE
Add Ability To Pass In  web_fqdn and the web_schema Into HelmCharts

### ISSUE THREAD

**Issue by mattmahoneyrh** [kiali/kiali#4016]
When deploying multi-cluster's using install-everything.sh, the following Kiali warning happens:

"Context menus are disabled for remote cluster nodes if a Kiali instance is not discovered, or if the remote Kiali is not configured with an external URL."

Will need the ability to add web_fqdn and the web_schema when running install-everything.sh

**Comment by jmazzitelli** [comment]
The purpose of this is to be able to configure the new kiali.io/external-url annotation on the kiali service:

https://github.com/kiali/helm-charts/blob/master/kiali-server/templates/service.yaml#L14-L17
