### ISSUE TITLE
kiali.io has bad link to new istio.io docs

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#4029]
Istio changed their website - so the kiali.io job that verifies links is not finding a link that used to be there:

```
- ./public/documentation/latest/tutorial/index.html
  *  External link https://istio.io/latest/docs/concepts/what-is-istio/#why-use-istio failed: https://istio.io/latest/about/service-mesh/ exists, but the hash 'why-use-istio' does not
```

We need to fix kiali.io docs so this link is correct - looks like the old link redirects to: https://istio.io/latest/about/service-mesh/

**Comment by jshaughn** [comment]
@israel-hdez Did you recently run a tool to identify bad links?  If so, could we do it again?

**Comment by israel-hdez** [comment]
@jshaughn It's on the CI. It should run on every PR.
Or do you mean to run it manually?

**Comment by jshaughn** [comment]
@israel-hdez OK, so I guess this issue was generated from a CI failure when it ran.  So maybe this is the only issue unless it fails and stops on the first fail.  Anyway, I guess then that the way to proceed is just to fix this and let the CI run on the PR.   I'll just assign to myself.
