### ISSUE TITLE
Kiali UI - Request Routing Wizard does not update weights

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#4031]
The Request Routing Wizard does not update the weights for the selected VS routes.

Steps to reproduce:
1. Deploy bookinfo
2. Create a VS for Reviews
3. Services --> Namespace: bookinfo --> reviews
4. Select "Update Routing" under "Actions" dropdown
5. Change the weights from the default 33%
6. Notice that weights remain at their previous values after successful update

Expected weights to be updated with their new values. Opening up the network tab in the browser dev console shows that the PATCH request to update the weights is sending the old value of 33% instead of the new value.

Versions used:
Kiali: master
Istio: 1.9.5
Kubernetes: 1.20.2

**Comment by nrfox** [comment]
Actually I misunderstood how this worked. In the Request Routing wizard I adjusted the weight sliders and then hit "Update" and expected to see the weights adjusted for an existing rule. What I needed to do was remove the existing rule and add a new rule with the new weights. In other words, in order to update an existing rule in the Request Routing wizard you must remove it then add it back with the changes. Is that right @lucasponce?

I don't think this is a bug, just user error on my part.

**Comment by lucasponce** [comment]
Yes, you're right.

The "Request Routing" wizard generates rules, the "update" allows to add/remove rules, but not modifying existing ones.
As this Wizard is the "complex" one, allow to update an existing rule would require a different design (I experimented with that idea at the creation of the current design, but I thought that focused on the rules would help the user on this case).

For example, when there is a single rule, like the "Traffic Shifting" then yes, the "update" will work as you describe.
