### ISSUE TITLE
Instrument Kiali server with Jaeger

### ISSUE THREAD

**Issue by leandroberetta** [kiali/kiali#4036]
During the revisiting of #3244 the idea of replace some internal metrics with instrumented code arose.

The motivation is to have more information in cases of performance issues reported by users.

The traces will be shown in the Traces tab at App/Workload/Service level as for any other microservice.

**Comment by lucasponce** [comment]
This one is valid.
It doesn't have high priority, but backend server code would benefit to move into spans.
The internal metrics are ok and they provide some visibility, but instrumenting the code with Jaeger may help to get deep into particular scenarios.

**Comment by nrfox** [comment]
I'd like to revisit this one since I believe it will greatly help in pinpointing some of the scalability/perf issues. It will most likely require plumbing the request context through various parts of the backend services/business logic that call external APIs.
