### ISSUE TITLE
Graph is empty when waiting for health response

### ISSUE THREAD

**Issue by LeslieKuo** [kiali/kiali#4046]
**Describe the bug**
The `health` requests are requested by namespace. If there are many namespaces in multiclusters, there will be a lot of `health` requests. Sometimes `health` response may need to be waiting for a long time.
However kiali begin to draw the graph only when fetch all the `health` responses. So the graph will be empty for a long time.
![image](https://user-images.githubusercontent.com/18239311/119614951-70330980-be31-11eb-8045-a6681cd2f817.png)

I read the kiali-ui source code and find that the graph is basicly composed by two parts —— the graph components and graph color. The graph components are nodes and edges. The graph color includes edge color and node color. And **ONLY** node color is from `health` request. 
![image](https://user-images.githubusercontent.com/18239311/119617529-868e9480-be34-11eb-9614-062f70366e35.png)
So could we optimize it from two ways. 
1. Loading the graph firstly as soon as getting the `graph` response. And then dynamicly loading the node color which is get from `health` request.
2. Squash all the `health` requests by namespace into **one** `health` request and fetch all the namespace at once.

**Versions used**
Kiali: 1.33
Istio: 1.8
Kubernetes flavour and version: 1.21.0

**Comment by lucasponce** [comment]
Hi @LeslieKuo,

This is one of the topics that we're discussing internally to change the architecture of how health is fetched and also related to how caching information can help.

I'm curious, can you share some details in terms of sizing of your cluster when you experiment this lag ?

Thanks.

**Comment by jshaughn** [comment]
For some history, the current behavior was debated at length in https://github.com/kiali/kiali/issues/3252, and we knew waiting on Health prior to graph rendering could possibly result in the performance issue you are reporting.  But without waiting we can't reliably perform a graph hide/find based on Health.   As @lucasponce says, we are again looking at alternatives.

**Comment by jshaughn** [comment]
@LeslieKuo , In addition to the sizing questins asked above, can you say how long it is taking for the graph to render?

**Comment by jmazzitelli** [comment]
> how long it is taking for the graph to render?

You can take a look at the kiali timeseries metric in Prometheus for a more exact number for this - there is a kiali graph generation timeseries that should be collected and stored in Prometheus.

**Comment by LeslieKuo** [comment]
@lucasponce @jshaughn  I really want to share the info about the cluster size. However it's about the business confidential.  
And about the health request waiting time，it tooks a few seconds. I figure out that it mostly based on the prometheus request time. Something wrong in our prometheus in that time. Now it looks good. Thank you so much.

**Comment by LeslieKuo** [comment]
Sorry @jshaughn, I‘m just beginning to get into Kiali. I dont understand `"But without waiting we can't reliably perform a graph hide/find based on Health."  ` Is it a feature? Could we  dynamicly loading the health status.

**Comment by lucasponce** [comment]
@LeslieKuo thanks for the feedback and we understand the confidential situation.

In any case, we are receiving feedback from users with sizing in the terms of thousands of workloads, so the design changes will be address those scalability challenges in multiples areas (backend and also frontend and visualization).

I think how the graph is built is more an implementation detail from user perspective, there was a synchronization to collect graph+health info, in order to enable "find/hide" queries, but I don't think it will be relevant to an end user, but more from our side to understand that in high density/sizing it can be a source of potential delays.

**Comment by jshaughn** [comment]
@LeslieKuo , again, thanks for the feedback and I'm glad the issue could be resolved via Prometheus.   Just to be clear, `Graph Find+Hide` is a feature that llows you to either highlight (Find) or remove (hide) nodes and/or edges in the graph.  To do so you enter expressions in the text boxes on the graph toolbar.  The expression language can be seen by clicking the associated Info icon.  One of the expression "operands" is `healthy`.  You can also use `! healthy`.   It is a nice feature, especially if you want to focus on unhealthy nodes.   But, for the feature to work the health must already be associated with the nodes, and so we must wait to render the graph until we have the health.  But, in general it also just presents a more valid graph, without asynchronous health information being applied incrementally.

**Comment by LeslieKuo** [comment]
@jshaughn Got it. Thank you so much.
