### ISSUE TITLE
Investigate Troubleshooting scenarios

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#4066]
One of the goals of Kiali is to provide good information to an Istio end user about why a traffic scenario is not working as expected.

I have read in the community an scenario like this:

```
[...]
I use to have a simple scenario like:

- internet -> aws lb -> gw -> vs -> k8s service working.. 

but when changing things, that has broken somewhere.

I can verify that port forwarding to:
- The pod works
- The service works

Not sure how to debug virtual service -> service or gateway -> virtual service ?
[...]
```

I think it's very representative of potential scenarios where Kiali would need to improve the information that it provides.

Probably, Kiali has all the information (proxy logs from ingress and workloads, istiod registry information, validation of the Istio configuration, telemetry and traces) but next step is to investigate how to "connect" the pieces offering a better experience to the end user.

This task is open as the goal is to research these scenarios identifying how to debug these problems and what information is missing from Kiali to help users.

**Comment by lucasponce** [comment]
Thanks for the feedback @Geethree ! We have also an open/public discussion about it https://github.com/kiali/kiali/discussions/4082 and collecting usecases as you describe help us to drive these features.

Currently Kiali offers some capabilites to troubleshoot, but the direction of the project is to connect all the low level info in something that a non-expert Envoy user can easily use to spot "hey, I need to check this or to change that".

**Comment by lucasponce** [comment]
Moving to backlog.
This issue is a "research", the scope should be to identify scenarios like proposed:

>  Basically, istio/envoy is complex and tools like Kiali are excellent tools in figuring out what is going in with the mesh. So some method of quickly debugging (tracing?) packets coming into the mesh and getting lost would be rad.

And study them to see if a design proposal could be added to Kiali.

Not in the scope to implement a design proposal, but identify these use cases and how (manually) a user can debug them in order to propose new enhancements in Kiali.

**Comment by jmazzitelli** [comment]
here's a .pdf I wrote up with a couple simple things

[Troubleshooting with Kiali.pdf](https://github.com/kiali/kiali/files/9557362/Troubleshooting.with.Kiali.pdf)

**Comment by jshaughn** [comment]
Closing as completed.
