### ISSUE TITLE
New badge/visualization for hostnames in Graph

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#4068]
One of the missing pieces I find in the Graph is to tell the user the hostname used when a specific traffic is routing from a Gateway.

In the example:
![image](https://user-images.githubusercontent.com/1662329/120791652-c2141780-c534-11eb-8a38-2ffa288c92b7.png)

The "control" service shows that is invoked from the "ingress", but it's missing which hostname DNS is being used.

This is particulary relevant for "ingress" scenarios where I may have a single gateway pod, with multiple gateways definitions resolving traffic for different applications.

So, this issue proposes to enable a new "Display" option in the Graph to populate the hostname.

In term of implementation, we could start just populating the hostname used for the VS, so, when the VS is present there should be one or more entries like:

```
    - hosts:
        - control.travel-control.istio-cluster.org
```

that are linked with the service.

This information could be the main one used to understand why traffic is not flowing so a display option that enables the hostname close to the service would help (additionally it can be populated in the side panel as well, but I think it should be present in the graph as well).

Also, these display can be used for ingress/egress traffic, in other words, no need to apply it for traffic inside the mesh and it will match (typically) the kubernetes service.

So, this can be enabled on those VS that have a GW linked, which is the main use case from user perspective.

**Comment by jshaughn** [comment]
@lucasponce , How is this different than what is currently displayed in the  `Hosts` tab in the side panel?

**Comment by lucasponce** [comment]
Yes, the "hosts" in the tab panel doesn't look into the host resolution:
![image](https://user-images.githubusercontent.com/1662329/120810639-85074f80-c54b-11eb-9c6f-d29590211a95.png)
In this case it refers that the ingress pod is talking to the kubernetes service host.

But the traffic from the user perspective is that there is a "control.traffic-control.istio-cluster.org" host resolved from the gateway and that's the discriminator for the VS to resolve into the "control.travel-control.svc.cluster.local" (internal service).

So, when a service has a badge (AND linked with a Gateway) typically it will have a host (wildcards are possible, but in real scenarios you want to discriminate by hosts in Gateway and/or VirtualService), and that's very useful information to the user to understand why the request flows to a particular destination.

**Comment by lucasponce** [comment]
You'll see it clear in the proxy log:

```
[2021-06-04T13:57:37.971Z] "GET /status HTTP/1.1" 200 - via_upstream - "-" 0 25579 2 2 "172.17.0.1" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0" "7625b36f-1b80-9bc5-aa22-c18bb92ad6d7" "control.travel-control.istio-cluster.org" "172.17.0.28:8080" inbound|8080|| 127.0.0.6:39039 172.17.0.28:8080 172.17.0.1:0 outbound_.8080_.v1_.control.travel-control.svc.cluster.local default
```

It's another "source" to get the "runtime" hostname of the request even if that request is resolved to that specific service.

**Comment by jshaughn** [comment]
Perhaps this info can be supplied with an addition to the `istio` badging appender.

**Comment by lucasponce** [comment]
> Perhaps this info can be supplied with an addition to the `istio` badging appender.

+1 also as it typically happens on "ingress" scenarios, no need to add additional info in every VS badge, but a display option to see it in the graph would be really nice to show what is the "real request".

Today that info is available, of course, within the proxy logs and in the Istio config, but I think we need to make it more visible.

**Comment by lucasponce** [comment]
Also note that in production scenarios there can be multiple ingress/egress workloads, so DNS can be "resolved" from one or another Gateways.

It's also related to this issue as well https://github.com/kiali/kiali/issues/3765

So, when a DNS/hostname is entering the cluster, which gateway/ingress is handling it, to which VS is being routed ? And also the opposite scenario, when an external entry is being invoked, which gateway/egress is handling it.

In demo profiles typically there are a single workload per ingress/egress, but that's only for these small scenarios.
Using the Gateway selectors can be a strategy here as well.

There are more steps from here, that probably can be defined in following issues, but I think these comments help to describe the whole context of the issue and why it can be important for Kiali to start adding more visibility on these hostname resolutions.

**Comment by israel-hdez** [comment]
Regarding UX, my initial proposal would be to convert the ingress gateway node to a compound node, if the option is enabled. Something like:

![image](https://user-images.githubusercontent.com/23639005/123000116-c2097980-d374-11eb-81b2-062df06c5a72.png)

I think it's better to avoid edge labels, because hostnames can be large, and the same service can be responding to multiple hostnames, thus potentially introducing a weird look to edge labels.

Anyway, I think this can be an initial proposal so that we can ask for feedback to UX.

**Comment by jshaughn** [comment]
OK, I've read through this more carefully than before I now I see that the general idea here is to try and help the user understand the gateway routing from a requested host to the destination host/service.  This is sort of the classic desire to be able to enhance the graph's "what happened" view with a bit of "why it happened" information.  I talked to Edgar about this and I think it could be useful show just the static host definitions for the gateway and let the user decipher why traffic was routed in a particuar way.  What would be difficult for us to do is to try and recreate the host resolution that is already performed by Envoy/Istio.  Another possibility would be to present the relevant logs, or possible even parse them to determine requested-to-resulting routing.  But that may be a lot of logs and the logging may have to be enabled.  It would be better to do on-demand, I think, as opposed to part of the back-end processing.  Another approach may be to show the static config by default, but if Istio telemetry for the gateway [is configured](https://istio.io/latest/docs/tasks/observability/metrics/customize-metrics/#enable-custom-metrics) with `request_host`, we could get the most robust requested-to-resulting mapping, and make it available in the side panel.  The danger there may be a poorly configured gateway, using wildcards, could be subject to a cardinality issue.   For this approach we may have to add some documentation around ensuring things are configured properly.

Edgar was going to do some testing, enabling `request_host`.

**Comment by lucasponce** [comment]
The scope of this issue is to show the host resolution defined per Gateway and potentially per VirtualService.
Note that this will be linked with https://github.com/kiali/kiali/issues/4067 so, it has be synced.

Yes, when wildcard are used it would require an additional processing from several sources that is not part of this effort nor with https://github.com/kiali/kiali/issues/4067

About the UX, I don't like the compound nodes either, those are not consistent with the rest of graph elements, any solution adding tooltips under a Gateway badge would be initially nice.

**Comment by israel-hdez** [comment]
So, no new intermediate nodes, nor nothing from the `request_host` from telemetry. This should be inferred purely from GW and VS config.

I think a badge can make sense to explicitly denote that a node represents an Istio ingress gateway. I guess that GW badge should replace that generic "incoming traffic" badge that we currently have:

![image](https://user-images.githubusercontent.com/23639005/123817348-b0b4f580-d8bd-11eb-8ad2-b977b53f5c93.png)

However, I don't agree that we should display hostnames inside a tooltip. Here I agree with Jay that this should go into the side-panel. A tool-tip over a badge would be a new pattern (at least when speaking solely about what the graph is currently offering). Also, IMO, a tooltip is more hidden when compared to the side panel.

**Comment by lucasponce** [comment]
The Graph should indicate that there are nodes with Gateway and VirtualServices that resolve hosts.
And it should resolve that information graphically, it's more important to me that show some of the data that currently shows.

So, let's not hide this on the sidepanel. 

I'm fine to refine the UX but this information is important.

Also note that #4067 will add same information on the Networking card, so it would need to be synced to not show different data.

**Comment by lucasponce** [comment]
>  So, let's not hide this on the sidepanel.

Meaning:
![image](https://user-images.githubusercontent.com/1662329/123819725-48383980-d8fa-11eb-9bce-87c6d734d83b.png)

This information is more important than traffic and/or traces, so I'd expect to see it always in the sidebar rather than add a new tab that can be forgotten.

**Comment by jshaughn** [comment]
I think I agree with at least part of everything :-)

I think a new Gateway badge could be nice.   I'm not sure it should replace the TrafficSource badge, we'd have to see how it looks.  If we did replace it then we'd need to limit that replacement only to ingress gateways.  But it would help identify gateways visually.  As it stands today we don't identify Gateway nodes as gateways in the graph.  A new IsGateway field on nodes could be useful, and could also be added to graph find/hide.

Displaying the defined hosts could be deferred to the side panel but it does not need to be hidden.  It could be quite prominent.  Today, in the side panel we list in the header the special characterstics of a node, like "Has Virtual Service".   We could place the information right there, either verbosely or with some text and an associated tooltip (formatted with the same look as in  #4067).

As a more advance option we may want to try generating that requested-host-->resolved-destination map from proxy logs.  This could be a separate effort, maybe an enhancement to the side-panel Host tab for edges related to a gateway or VS.

The more I think about enabling `request_host` for gateways the more I worry about the cardinality issue.
