### ISSUE TITLE
Trace graph tooltip truncates long hostnames

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#4087]
The text for the trace graph's (workloads --> traces tab) tooltips is truncated for longer hostnames:

![Screenshot from 2021-06-08 17-36-13](https://user-images.githubusercontent.com/6226732/121261422-ba2fdc80-c880-11eb-97d8-c7f8268abe8a.png)

Instead the text could wrap so as to fit inside the tooltip:

![Screenshot from 2021-06-08 17-43-31](https://user-images.githubusercontent.com/6226732/121361301-28b57e80-c903-11eb-93c7-44612cf3ffeb.png)

**Comment by lucasponce** [comment]
And more, it's missing the heatmap attached.

So, this is a regression introduced in https://github.com/kiali/kiali-ui/pull/2132

**Comment by nrfox** [comment]
> And more, it's missing the heatmap attached.
> 
> So, this is a regression introduced in [kiali/kiali-ui#2132](https://github.com/kiali/kiali-ui/pull/2132)

Ah it did seem like there was a lot of blank space on the tooltip and maybe there was some missing text there.

**Comment by nrfox** [comment]
If it's helpful this is the style I adjusted for the screenshot so the heatmap bug might be in that `<TraceLabel>` component: https://github.com/kiali/kiali-ui/blob/master/src/components/JaegerIntegration/TraceTooltip.tsx#L39-L43

**Comment by nrfox** [comment]
When the heatmap info is present on the tooltip, wrapping the title text probably won't look right.

**Comment by lucasponce** [comment]
The goal is to get back to 
![image](https://user-images.githubusercontent.com/1662329/121389391-a356bc00-c94c-11eb-8267-7c51e551740a.png)

The feature is to answer to the user if one trace of the chart is relevant compared with the telemetry metrics (used in the heatmap), the long wording of the trace is ok, so, when user click on the trace the details are updated on the subtabs.

**Comment by lucasponce** [comment]
Fixed on https://github.com/kiali/kiali-ui/pull/2176
