### ISSUE TITLE
Display traffic scenario badges when present

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#4090]
This is a follow up to #1477.

The current implementation only displays the traffic routing badges if they were created through the Kiali wizard. The badges should be displayed on the nodes if they are present on the virtual service or destination rule regardless of how they were created.

This would involve updating the backend appender to check the virtual service spec for the supported traffic routing scenarios similar to how badging is added for circuit breakers. In addition ensuring the front end displays the badges correctly when multiple scenarios are active at once.

The following scenarios need to be covered:
- Request Timeouts
- Traffic Shifting
- TCP Traffic Shifting
- Request Routing
- Fault Injection

Since the two traffic shifting scenarios share a single icon, only 1 badge can be displayed when both are present.

**Comment by jshaughn** [comment]
@lucasponce To me this seems like a high priority item, as users could find it confusing to be missing expected badges just because the definitions were made outside of Kiali.  What do you think?   Alternatively, should we try and have Kiali wizards work better with externally defined definitions?

**Comment by lucasponce** [comment]
+1

To make work any Istio definition with the Wizard is part of the ongoing effort we are doing on that area but yes, we can use the same strategy on badging.

This is what I had brainstormed for the feature in the Wizards and can be applied in the badges in a direct 1:1 way:

- If a VS is present under a service, by default it will be consider a "Request Routing" (that will be the more complex Wizard that will try to fit the corner cases).

- If the VS has the presence of "Request Timeouts" and/or "Fault Injection", it can enable these badges.

- If there is only one rule with multiple destination it can use the "Traffic Shifting" / "TCP Traffic Shifting" depending on the type of destination (we don't support yet the SSL destination, but that can be addressed in the future).

In cases of multiple combinations or some ambiguity, I'd use the "Request Routing" as it allows to combine the previous situations.
