### ISSUE TITLE
 make openshift-deploy fails due to namespaces "istio-system" not found

### ISSUE THREAD

**Issue by abonas** [kiali/kiali#41]
make openshift-deploy
Undeploying from OpenShift
oc delete all,secrets,sa,templates,configmaps,daemonsets,clusterroles,clusterrolebindings --selector=app=sws -n istio-system
No resources found
Deploying to OpenShift
oc create -f deploy/openshift/sws-configmap.yaml -n istio-system
Error from server (NotFound): error when creating "deploy/openshift/sws-configmap.yaml": namespaces "istio-system" not found
make: *** [Makefile:89: openshift-deploy] Error 1

**Comment by abonas** [comment]
@jmazzitelli @lucasponce is this related to the latest merged istio related PRs? 
I did not see any change in readme in setup instructions

**Comment by abonas** [comment]
I ran the scripts in hack folder and now rerunning make openshift-deploy runs ok. 
but that is not something that should happen.
a hack is a hack :) so either those deps should be auto installed or the readme should clearly mention it as a step.

**Comment by jmazzitelli** [comment]
@abonas  the makefile makes no decision on what namespace to deploy to. It does, however, default to istio-system. If you want to put it in another namespace, pass the env var NAMESPACE like this:

`NAMESPACE=default make openshift-deploy`

For the makefile, it is assumed you are both logged in (via oc login) and the user has access to the namespace you want to deploy in. Thus, this frees the developer to be able to use whatever user they wish and deploy in whatever namespace they wish.

That said, if we want to force developers to use the namespace istio-system, we can add "oc new-project istio-system" or something like that to the Makefile.

On Monday I will review the README, it is possible we need to change it.

**Comment by jmazzitelli** [comment]
And to be clear, the hack files ARE NOT REQUIRED. Devs do not need to use them. But devs DO need to log in as a user with access to the namespace/project they plan to deploy to (again, the default is assumed istio-system).

**Comment by abonas** [comment]
I don't want to deploy to another namespace. 
as the error says above "namespaces "istio-system" not found" - this was the output of the make deploy command, I did not specify anything in any command that is not in the readme. 
isn't it caused by this?
https://github.com/swift-sunshine/swscore/blob/master/deploy/openshift/sws.yaml#L17

**Comment by lucasponce** [comment]
> Error from server (NotFound): error when creating "deploy/openshift/sws-configmap.yaml": namespaces "istio-system" not found

This sounds you don't have istio properly deployed.

As @jmazzitelli commented and as we discussed with @jmazzitelli the script shouldn't enforce how you install and deploy istio and demo apps, that's reason we have these helpers as a hack folder.

Personally I don't use them either as I have my own local setup.

Also, if you find something weird related to your environment, don't hesitate to send a PR too, we can't count that al environments are configured as same way, so official fixes should be taking as premise that openshift, istio and demo apps are properly installed.

I'd personally get familiar with this setup
https://blog.openshift.com/evaluate-istio-openshift/
and from here you can choose if to use the hack/ helpers or create your own ones (my case) just for faster clean and prepare the dev environment.

**Comment by abonas** [comment]
@lucasponce isn't the main config assuming the istio-system ns exists?
https://github.com/swift-sunshine/swscore/blob/master/deploy/openshift/sws.yaml#L17

**Comment by lucasponce** [comment]
It assumes you have istio deployed, yes.
And you have access to it from the user you are deploying sws.

**Comment by abonas** [comment]
@lucasponce that is exactly my point. it is impossible to know from the readme that istio is a prerequisite and has to be deployed.

**Comment by lucasponce** [comment]
@abonas yes, in the building note it is only defined the Openshift.
Please, could you send a quick PR for it ?
Thanks

**Comment by jmazzitelli** [comment]
> @lucasponce isn't the main config assuming the istio-system ns exists?
> https://github.com/swift-sunshine/swscore/blob/master/deploy/openshift/sws.yaml#L17

This is a openshift parameter defined in sws.yaml line 17 - you see the default there is istio-system, but the name of the parameter NAMESPACE can be defined from the environment variable which overrides that default.

IMO, now that we have a "real" integration with istio, we should not allow someone to override the namespace. It should always be istio-system and we should create it if it doesn't exist  (then again, if it doesn't exist, it means istio isn't deployed yet, and so sws won't work anyway). So at minimum we should make the Makefile check for the existence of istio-system namespace and fail if it does not.

**Comment by lucasponce** [comment]
> IMO, now that we have a "real" integration with istio, we should not allow someone to override the namespace. It should always be istio-system and we should create it if it doesn't exist (then again, if it doesn't exist, it means istio isn't deployed yet, and so sws won't work anyway). So at minimum we should make the Makefile check for the existence of istio-system namespace and fail if it does not.

+1

**Comment by jmazzitelli** [comment]
See PR #44 - if the namespace does not exist, make openshift-deploy will fail.

**Comment by pilhuhn** [comment]
#44 was merged - is this issue still valid?

**Comment by jmazzitelli** [comment]
IMO, this should be closed now. The namespace must exist, if it does not, the Makefile will check in the validate target which will fail letting you know the namespace is missing. Before running make, you must oc login with the user that is to be the one to deploy/undeploy to OS, and that user must have access to the namespaces.
