### ISSUE TITLE
remove istio_component_namespaces config

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#4109]
There was once a need for the [istio_component_namespaces](https://github.com/kiali/kiali-operator/blob/v1.35.0/deploy/kiali/kiali_cr.yaml#L50-L61) setting but that need has long since gone. This setting confuses people and isn't even used (doesn't work) when using the server helm chart.

And we do not mention it anywhere in our kiali.io docs (only mentioned in that kiali_cr.yaml example as linked above).

We should remove it.

PRs:
* server: https://github.com/kiali/kiali/pull/4110
* ui: https://github.com/kiali/kiali-ui/pull/2180
* operator: https://github.com/kiali/kiali-operator/pull/332

doesn't appear this config was used in the helm charts (which was part of the confusion :) so no PRs for helm repo needed.

**Comment by jmazzitelli** [comment]
@xeviknal can you review the three PRs for this issue? @jshaughn seemed to think you might know of a reason why we shouldn't remove this old config setting. Please review and comment on the PRs. Thanks.

**Comment by xeviknal** [comment]
@jmazzitelli I thought @jshaughn needed this config for some reason. Thanks for breaking this eternal loop of confusion and bring peace to community.
