### ISSUE TITLE
clean up upstream istio kiali addon install doc

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#4111]
Now that we removed the monitoringdashboards CRD from Kiali, once we release the next sprint release (tomorrow), we should update the istio docs here:

https://istio.io/latest/docs/ops/integrations/kiali/

There is no more need for that green box with the warning - that was there due to the fact the monitoringdashboard CRD wouldn't get initialized fast enough and would cause the dashboards to fail to install. Now that the dashboards are no longer installed in that manner and the CRD is removed there is no need for that warning message.

NOTE: we actually can't update this until Istio updates the addons yaml so it doesn't include the CRD and dashboards - so I guess we should wait until istio updates the samples addon with the next kiali release.

**Comment by jmazzitelli** [comment]
I'm adding this to the the v1.38 sprint because I think Istio is going to release soon - so we should update the istio addon to use 1.37 and thus we can complete this issue, too. If my assumption is wrong, then we can remove this out of this sprint and we'll do it next sprint.

**Comment by jmazzitelli** [comment]
FYI: here's what the previous upstream PR looked like for the addons - just for reference: https://github.com/istio/istio/pull/32754

**Comment by jshaughn** [comment]
>  I think Istio is going to release soon

https://github.com/istio/istio/wiki/Istio-Release-1.11

Aug 03/10 scheduled for 1.11 freeze/release, so I think Kiali 1.38 (Jul 30th release) would be the target release.

**Comment by jmazzitelli** [comment]
upstream already updated to v1.36: https://github.com/istio/istio/pull/33695/files

We can bump to v1.38 when we release it. But since we upstream is now on v1.36, we can implement this issue. Which I am doing right now.

**Comment by jmazzitelli** [comment]
This issue will be closed once this is merged: https://github.com/istio/istio.io/pull/10081
