### ISSUE TITLE
[perf] pr #3975 introduced perf regression for /api/namespaces/bookinfo/services/details/graph endpoint

### ISSUE THREAD

**Issue by FilipB** [kiali/kiali#4120]
**Describe the bug**
pr #3975 improved overall performance but introduced perf regression for /api/namespaces/bookinfo/services/details/graph endpoint.

Tested endpoints are visible in https://gitlab.cee.redhat.com/istio/servicemesh-qe/jenkins-csb-declaration/-/blob/master/resources/kiali/performance/gatling/ServicesSim.scala#L46

 Overall/combined mean response time for all tested endpoints was improved but RT for `/api/namespaces/bookinfo/services/details/graph?duration=60s&graphType=workload&includeIdleEdges=false&injectServiceNodes=true&appenders=deadNode,sidecarsCheck,serviceEntry,istio,healthConfig` was 78ms before this change and 306ms after.

On the other hand `/api/namespaces/bookinfo/services/details?validate=true` was significantly improved.

Question is if those changes in RTs make sense and are expected.
This is low severity as overall perf was improved and only one endpoint is worse after that PR.

**Comment by lucasponce** [comment]
I'll take it, basically when Istio Config query is used from the appender, permissions should not happen, it seems the PR introduced that regression.

**Comment by lucasponce** [comment]
Hi @FilipB, I've reviewed the changes on https://github.com/kiali/kiali/pull/3975 and mostly affects to `GetIstioConfigPermissions` and `GetService` which both are not used for the query:

```
GET http://localhost:8000/api/namespaces/travel-agency/services/travels/graph?duration=60s&graphType=workload&includeIdleEdges=false&injectServiceNodes=true&appenders=deadNode,sidecarsCheck,serviceEntry,istio,healthConfig
```

In addition, locally I have results in this order from both commits:

```
# From 88ded0e1827fc3a419b27a46fcc4d9aaf74442fe ~ AVERAGE 76 ms

<> 2021-06-24T120549.200.json # Response code: 200 (OK); Time: 33ms; Content length: 8235 bytes
<> 2021-06-24T120521.200.json # Response code: 200 (OK); Time: 30ms; Content length: 8235 bytes
<> 2021-06-24T120444.200.json # Response code: 200 (OK); Time: 30ms; Content length: 8235 bytes
<> 2021-06-24T120433.200.json # Response code: 200 (OK); Time: 132ms; Content length: 8235 bytes
<> 2021-06-24T120358.200.json # Response code: 200 (OK); Time: 36ms; Content length: 8235 bytes
<> 2021-06-24T120347.200.json # Response code: 200 (OK); Time: 139ms; Content length: 8235 bytes
<> 2021-06-24T120337.200.json # Response code: 200 (OK); Time: 78ms; Content length: 8235 bytes
<> 2021-06-24T120308.200.json # Response code: 200 (OK); Time: 61ms; Content length: 8235 bytes
<> 2021-06-24T120250.200.json # Response code: 200 (OK); Time: 61ms; Content length: 8235 bytes
<> 2021-06-24T120241.200.json # Response code: 200 (OK); Time: 39ms; Content length: 8235 bytes
<> 2021-06-24T120233.200.json # Response code: 200 (OK); Time: 35ms; Content length: 8235 bytes
<> 2021-06-24T120213.200.json # Response code: 200 (OK); Time: 242ms; Content length: 8235 bytes

# From 26bd3db19caaac94f739bf60d44c32c22a2c70b6 ~ AVERAGE 87ms

<> 2021-06-24T120055.200.json # Response code: 200 (OK); Time: 73ms; Content length: 8235 bytes
<> 2021-06-24T120045.200.json # Response code: 200 (OK); Time: 24ms; Content length: 8235 bytes
<> 2021-06-24T120037.200.json # Response code: 200 (OK); Time: 89ms; Content length: 8235 bytes
<> 2021-06-24T120025.200.json # Response code: 200 (OK); Time: 95ms; Content length: 8235 bytes
<> 2021-06-24T120016.200.json # Response code: 200 (OK); Time: 62ms; Content length: 8235 bytes
<> 2021-06-24T120001.200.json # Response code: 200 (OK); Time: 75ms; Content length: 8235 bytes
<> 2021-06-24T115947.200.json # Response code: 200 (OK); Time: 66ms; Content length: 8235 bytes
<> 2021-06-24T115935.200.json # Response code: 200 (OK); Time: 93ms; Content length: 8235 bytes
<> 2021-06-24T115926.200.json # Response code: 200 (OK); Time: 99ms; Content length: 8235 bytes
<> 2021-06-24T115917.200.json # Response code: 200 (OK); Time: 192ms; Content length: 8235 bytes
<> 2021-06-24T115906.200.json # Response code: 200 (OK); Time: 98ms; Content length: 8235 bytes
```

I mean, the PR with that query works in similar order (or a little bit better).

So, I have a feeling that it should be something else.

I don't know, from here we can try to create a particular test for this case, or just keep this in the radar in case that it degrades but I don't see an inmediate fix for those PR's changes.

**Comment by lucasponce** [comment]
@FilipB do we want to keep this one open or perhaps close it and reopen if we find new evidences of perf problems ?

**Comment by FilipB** [comment]
Closing as not a bug. Turned out that reported response times for different endpoints are not accurate when hitting them sequentially probably due to caching. The overall mean response time for given set of endpoints was improved so we can close this.
