### ISSUE TITLE
[operator] move playbooks to use the new kubernetes.core collection

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#4121]
When the ansible operator base images are released with the new kubernetes.core collection, we should update the playbooks to use it.

See https://github.com/kiali/kiali/issues/4119 for more details

Currently the 4.7.0 base image has 0.11.1 of community.kubernetes:

```
$ docker run -it --rm  --entrypoint ''  quay.io/openshift/origin-ansible-operator:4.7.0 cat /opt/ansible/.ansible/collections/ansible_collections/community/kubernetes/MANIFEST.json | grep version
  "version": "0.11.1",
```

We can only implement this enhancement when kubernetes.core 2.0 is available... so when this returns a 2.0 version, that is when we know the time has come to do this:

```
BASE_IMAGE_VERSION="4.9.0" && docker run -it --rm  --entrypoint ''  quay.io/openshift/origin-ansible-operator:${BASE_IMAGE_VERSION} cat /opt/ansible/.ansible/collections/ansible_collections/kubernetes/core/MANIFEST.json | grep version
```

**Comment by jmazzitelli** [comment]
Some places to change `community.kubernetes` to `kubernetes.core`

* https://github.com/kiali/kiali-operator/blob/master/requirements.yml
* https://github.com/kiali/kiali-operator/search?l=YAML&q=community.kubernetes (the roles and playbooks)
* Using 'k8s' lookup should now specify `kubernetes.core.k8s` to avoid picking up the old lookup plugin (look for `query('k8s', ...)` and `lookup('k8s', ...)` and replace the "k8s" with `kubernetes.core.k8s`. Make sure behavior did not change (may need to switch from `query` to `lookup` in some cases, for example).

**Comment by jmazzitelli** [comment]
Pay close attention to the behavior changes in lookup and query when using the k8s plugin. I found a few gotchas that I reported here: https://github.com/ansible-collections/kubernetes.core/issues/147 -- we need to check the progress of that issue. This is important and affects a lot of code - the behavior of lookup and query with the k8s plugin is wonky and definitely has changed from the builtin k8s plugin that we have been using.

**Comment by lucasponce** [comment]
The referenced issue https://github.com/ansible-collections/kubernetes.core/issues/147 is closed.
Should this issue moved into backlog or updated ?

**Comment by jmazzitelli** [comment]
> The referenced issue [ansible-collections/kubernetes.core#147](https://github.com/ansible-collections/kubernetes.core/issues/147) is closed.
> Should this issue moved into backlog or updated ?

The [PR for that issue](https://github.com/ansible-collections/kubernetes.core/commit/04f227e9b952b9de12a8cc3a5e0a85d46cc335fd) was merged on July 8, 2021 but does not appear to have been released yet (I see [no releases after June 2021](https://github.com/ansible-collections/kubernetes.core/releases)). This means we likely have a long way to wait before it is available - see [this comment that talks about what we should look for](https://github.com/kiali/kiali/issues/3949#issuecomment-896086201) to know when we can use it.

We may be able to implement this move to kubernetes.core without that [issue](https://github.com/ansible-collections/kubernetes.core/issues/147) but at minimum we need the ansible operator base image to provide kubernetes.core (currently no productized ansible operator base image release does provide it). Again, see [this comment that talks about what we should look for](https://github.com/kiali/kiali/issues/3949#issuecomment-896086201) to know when we can use kubernetes.core. It could be many months (up to a year) from now.

**Comment by jmazzitelli** [comment]
taking off the waiting-for-external label - i think this is ready to be done now. Will be done as part of https://github.com/kiali/kiali/issues/4540
