### ISSUE TITLE
Add help for Graph shortcuts

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#4133]
Graph has some operations/events that are not well documented, so it depends of the users' dexterity to find them.

Some are easier to find:
- Drag and drop.
- Single click.

Others are harder:
- Mouse wheel for zoom in/out
- Double click.
- Right buttom for contextual buttom.

Some events are not really obvious:
- Shift+Drag and drop.

In a first step I think it could be good to have them documented, similar as the legend, but something that user may understand what is available. Inspired in other similar tool, something in this style would help (an "events" buttom close to the "legend" one):

![image](https://user-images.githubusercontent.com/1662329/123921270-1faa5100-d987-11eb-96a5-04942d96a4a8.png)

In a future step we may revisit if shapes may have some visual indicator that when user has select an item, some actions are available (not 100% convince but leaving here my note as it think it's related).

**Comment by jshaughn** [comment]
Some of the things you mention are covered in the Graph Tour.  We could also dedicate a section like this (graph "cheat sheet") to the tour, or to the legend.  Not sure I'd like to see another button given that the cytoscape toolbar can cover the actual graph nodes.  In fact, I'd like to see that toolbar reduced if possible.  I personally don't think the zoom buttons are at all useful.

**Comment by jshaughn** [comment]
Bumping priority by adding to Backlog, but this should wait for some of the current graph enhancements, and then we should have some design done before breaking ground on this one.

**Comment by lucasponce** [comment]
Seeing in OS, I think this is basically what I'd like to see

![image](https://user-images.githubusercontent.com/1662329/129549183-d389531e-176b-456c-8d5b-ae1d5bf10f09.png)
