### ISSUE TITLE
Improve Metric charts page when there are no metrics

### ISSUE THREAD

**Issue by jshaughn** [kiali/kiali#4135]
The revised metric charts page is very nice, with the exception of when there is no metric data.  This is admittedly a minor issue but I find this sort of page hard to visually parse:

![image](https://user-images.githubusercontent.com/2104052/123967383-42873600-d984-11eb-9729-2ea52d67a265.png)

**Comment by lucasponce** [comment]
The original design had an empty icon:

![image](https://user-images.githubusercontent.com/1662329/123968467-88112680-d9b7-11eb-8a2d-fd145dab3589.png)

That is only showed today on maximized status.

On narrow pages tend to work better without icon:

![image](https://user-images.githubusercontent.com/1662329/123968604-a7a84f00-d9b7-11eb-929e-ec24ed3e01c9.png)

But perhaps it's something it can be conditional rendered on width/height, or using a vectorial icon to adjust when resizing..

**Comment by jshaughn** [comment]
+1, I don't like the icon.  As I mentioned, this is minor and maybe not worth any change.   Maybe if the "No Data Available" was position in the top left of the chart area, so that it lined up with the title.  Things look fine when there are only a couple of missing charts, it's when there is no traffic at all, and all of them are missing it's kind of yucky.  Maybe not worth any effort.

**Comment by lucasponce** [comment]
This was addressed in a previous work where metric tabs were updated:
![image](https://user-images.githubusercontent.com/1662329/129003113-0ff180b0-62d6-4292-85d9-ef3ac133eb86.png)
