### ISSUE TITLE
Workloads flap between OK and Not Ready w/ Argo Rollout CR

### ISSUE THREAD

**Issue by kmai** [kiali/kiali#4141]
### General remarks
Workloads intermittently show as `OK` or `Not Ready`

### Describe the bug
While using Argo Rollouts, the `Rollout` appears to flap between the `OK` and `Not Ready` statuses.

This happens even though the pods from the deployment/rollout are running without issues.

The UI says that there are no available pods from one time to another, even though there is one synced proxy.

### Versions used
**Kiali UI** 1.36.0 (ceb2b93f33f1c0445b51518691dcb48c2c801f8a)
**Kiali Server** v1.36.0 (48c624aa9950b62b96c3c43591900b0291d483cf)
**Kiali Container** v1.36.0

### Components
**Istio** 1.9.0
**Prometheus** 2.26.0
**Kubernetes** v1.19.8-eks-96780e
**Grafana URL** N/A
**Jaeger URL** N/A

### To Reproduce
1. Deploy a working Rollout
2. Click on "Workloads" within the UI
3. See error

There's no output from the kiali deployment that could hint to a polling issue of any sort.

### Expected behavior
Kiali should represent the state appropiately and consistently, or there should be a way to determine the actual reason of this behavior (troubleshooting, documentation, logs, etc).

**Comment by Yorkerrr** [comment]
Related to this issue, noticed that this occurs if old replicaset (with scale set to 0) is remained in kuberrnetes. In this case responses to: http://<kiali_ip>/kiali/api/namespaces/example-dev/workloads/example call returns either live replicaset or old one and this causes that workload is flap between and Not READY.
Here is a difference in responses:

<img width="1164" alt="Screen Shot 2021-07-23 at 2 21 50 PM" src="https://user-images.githubusercontent.com/1927829/126842808-6fb8f216-3212-4226-ac99-0be424a8e12c.png">

**Comment by marsblkm** [comment]
> Related to this issue, noticed that this occurs if old replicaset (with scale set to 0) is remained in kuberrnetes. In this case responses to: http://<kiali_ip>/kiali/api/namespaces/example-dev/workloads/example call returns either live replicaset or old one and this causes that workload is flap between and Not READY.
> Here is a difference in responses:
> 
> <img alt="Screen Shot 2021-07-23 at 2 21 50 PM" width="1164" src="https://user-images.githubusercontent.com/1927829/126842808-6fb8f216-3212-4226-ac99-0be424a8e12c.png">

We bumped into pretty much the same problem and your solution worked like a charm!

**Comment by marsblkm** [comment]
It seems like removing old replicaSet is not a default behaviour according to argo roll - you need explicitly configure it.
https://github.com/argoproj/argo-cd/issues/2639

**Comment by Yorkerrr** [comment]
@marsblkm  revisionHistoryLimit to 0 should help, but still, the issue that argo-rollout does not show workloads state correctly with argo Rollout object, so I think the bug still should be opened

**Comment by jshaughn** [comment]
cc @xeviknal Any thoughts on this one?

**Comment by lucasponce** [comment]
It sounds a bug in how custom controllers are managed.
The Argo Rollout parent controller creates a ReplicaSet one and that one is what Kiali tries to use to check the state.

Also, if there are some old child controller not updated, it's possible that Kiali is picking one or another and that may explain that behaviour.

In any case, worth to investigate.

**Comment by jshaughn** [comment]
Kiali identifies workloads using sort-of a bottom-up approach that starts with Pods and looks for thir owners.  The owner can be a ReplicaSet.  Our list of Pods is cached (as is our list of ReplicaSets) and I think what happens is that we get a cached pod for an old ReplicaSet.  Our list of ReplicaSets contains all the ReplicaSets for the namespace, both active and inactive (not that inactive RS can result from Deployments that have revisionHistoryLimit > 0).  So we can get a cached pod that is owned by an inactive ReplicaSet.  For Kiali, I don't think old ReplicaSets for the same owner (Deployment) are useful.  If we filter them away I think the issue will be resolved.
