### ISSUE TITLE
Operator should abort if it can detect overlapping accessible namespaces

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#4144]
You should not give access to one namespace across multiple Kiali instances (i.e. spec.deployment.accessible_namespaces in one Kiali CR should not have a namespace that is found in any other Kiali CR).

Consider having the operator do a check to see if any namespace in accessible_namespaces has already granted access to another Kiali - if so, abort. I don't know how this can be achieved, but I think we can look at all the namespaces labels - if you see a [kiali label on the namespace](https://github.com/kiali/kiali-operator/blob/v1.36.0/deploy/kiali/kiali_cr.yaml#L88-L99) (whose value is different than the one currently being installed), that would mean another Kiali was given access to that namespace.

(note: while I have not tested this, I believe it is OK for multiple Kiali CRs to have accessible_namespaces set to "**" - that means they all share the cluster role)

We need to be extremely careful implementing this - we have use-cases where Kiali can be given access to literally thousands of namespaces. In the past we have had to fix the operator because of performance problems when processing all of those namespaces. So any solution for this issue must ensure that it does not degrade performance when accessible namespaces has thousands of namespaces.

**Comment by lucasponce** [comment]
> You should not give access to one namespace across multiple Kiali instances (i.e. spec.deployment.accessible_namespaces in one Kiali CR should not have a namespace that is found in any other Kiali CR).

Interesting, in a previous issue there was an usecase to basically do this, to basically that two instances of Kiali may share a namespace. No action to perform in the short term, but something to discuss.

> We need to be extremely careful implementing this - we have use-cases where Kiali can be given access to literally thousands of namespaces. 

Personally I think that we should change the rules here, under an scenario like this, user should consider to grant cluster permissions to Kiali as they should do with other kubernetes admin console.

Not only the operator, there are other aspects that will literally fail under this scenario, but anyway, I'm not adding anything that may help on this issue, just sharing somet thoughts that probably belongs to https://github.com/kiali/kiali/discussions/4080 discussion and https://github.com/kiali/kiali/discussions/4081

**Comment by jshaughn** [comment]
@jmazzitelli Any updates here wrt recent changes, clusterwide access, or MC work?

**Comment by jmazzitelli** [comment]
The issue here is for single cluster. When accessible_namespaces is a list of namespaces, in each namespace the operator will create a Role that will be bound to the Kiali SA. Presumably, installing multiple Kialis with access to the same namespace will also install Role with the same name mulitple times. Then if you try to uninstall one Kiali, that Role will be deleted, thus breaking the other Kialis that still want to access that namespace.

About the same time this issue was created (or just before) we added the instance_name feature - see https://github.com/kiali/kiali-operator/commit/b6f243cc70136657d7f19209312790f51ce9a221

So I think if you want to give access to the same namespace across Kiali instances, just install each Kiali instance with their own `deployment.instance_name`. That would prevent uninstalling one Kiali from removing the Role that the other Kiali still uses.

So we can probably close this issue as "wontfix" - we do not necessarily have to prevent this entirely - but you do need to carefully install the  Kialis with different instance_names in order to avoid the problem that this issue mentions.

**Comment by jshaughn** [comment]
Closing,see info above from @jmazzitelli .  No further actions identified.
