### ISSUE TITLE
Remote cluster functionality should be configurable

### ISSUE THREAD

**Issue by fbsb** [kiali/kiali#4147]
**Is your feature request related to a problem? Please describe.**

The remote cluster discovery in kiali requires list permissions for secrets in istio namespace and while kiali only reads secrets that have a specific label i.e. `istio/multiCluster=true` it introduces unnecessary additional risk when the feature is not needed and the istio namespaces contains sensitive secrets like istio root/intermediate ca certificate and private key.

**Describe the solution you'd like**

Ideally this feature should be configurable in the chart which when disabling would also remove list permission for secrets in rbac roles and disable the mechanism server-side as well.

**Describe alternatives you've considered**

Removing the permission in rbac by patching the chart renders kiali unusable due to being unable to list secrets.

**Comment by jshaughn** [comment]
cc @israel-hdez

**Comment by jmazzitelli** [comment]
fyi: is the secret Kiali reads always the same name? If so, we can restrict the role permission to that via the "resourceNames" setting in the Role's rule.

**Comment by fbsb** [comment]
I don't think restricting the permission via `resourceNames` would work. In a multicluster scenario with remote clusters there would be a secret per cluster containing kubeconfig for each remote cluster. Kiali reads all secrets it can find in istio namespace having `istio/multiCluster=true` label set. 

I think the only way this could work is to make the whole multi/remote cluster functionality configurable.

**Comment by israel-hdez** [comment]
Hi @fbsb 
For the remote cluster features, we were trying to fail gracefully.

I'll check if that can be done for this case. Else, well, a config option can help.

**Comment by israel-hdez** [comment]
@fbsb I'm unable to reproduce.

By deleting the `kiali-controlplane` role and rolebinding I get a working setup. The only difference is that there are some errors in the notifications pane when accessing the "Mesh" page. But all other pages work normally.

Perhaps, could you provide more info about your setup, including versions you are using?

**Comment by israel-hdez** [comment]
@fbsb Do you have any additional feedback?

**Comment by fbsb** [comment]
Hi, thank you for looking into this. Yes, removing the `kiali-controlplane` rolebinding appears to be working, though there are a lot of errors in the logs that kiali can't list clusters in the mesh due to not being able to list secrets. 

For some reason there were also a lot of errors appearing in the UI last time I checked and that was the main drive for opening this issue.

At the moment we are on v1.35.0 and we are using the kiali-server chart to install. We would like to stay as close to upstream as possible, that's why I think a proper fix for this would be to make the feature configurable.

Please let me know if I can help with anything.

**Comment by israel-hdez** [comment]
@fbsb 

So, I have this PR for the Kiali back-end: https://github.com/kiali/kiali/pull/4269
It replaces the Warning logs with Trace logs, when Kiali has no privileges to list secrets. This should avoid noisy logs, as long as you don't enable logs up to trace level.

I also have these other two PRs:
* Operator: https://github.com/kiali/kiali-operator/pull/395
* Helm charts: https://github.com/kiali/helm-charts/pull/97

which are adding a feature flag for clustering/federation. These new flags will allow or prevent creation of the Role and RoleBinding for reading secrets (default is to create them). The new flag has no other effect. The Kiali back-end should already be failing gracefully. I think this should be OK.

Hopefully, this solves your issue.
