### ISSUE TITLE
Display runtime dashboards as sub tabs grouped by a runtimes tab

### ISSUE THREAD

**Issue by leandroberetta** [kiali/kiali#4155]
Similar to how Envoy tab is managed, containing it's custom metrics dashboard inside it as a sub tab, the runtimes dashboards can be handled the same way grouping them as sub tabs under the "Runtimes metrics" tabs.

Example of Envoy:

![envoy_tab](https://user-images.githubusercontent.com/1286393/124609011-9fcc2d00-de45-11eb-8f7c-9699c429c9dc.png)

**Comment by lucasponce** [comment]
Perhaps with this comment in mind https://github.com/kiali/kiali/issues/4057#issuecomment-873415952 the grouping could be "optional" and defined per user.

I can get that some users may have it, and perhaps others would prefer to keep it in top level.

Just an idea, probably it's easier to support both cases.

**Comment by lucasponce** [comment]
Adding "future" label to collect some feedback about custom dashboards.
With the https://github.com/kiali/kiali/issues/4057#issuecomment-873415952 and the recent changes to support annotations, this feature is more flexible.

One idea is that customdashboards may incorporate another field called "GroupName" and then a new tab can be created per group, and this could be personalized by the user, but this also would create some challenges in the UI (as how to navigate to them).

By default, customdashboards should work as they work today.

**Comment by jshaughn** [comment]
Closing as out of scope and deferring to possible UX input such that any change here works well for OSSMC.
