### ISSUE TITLE
Display custom dashboards with more than two rows of graphs inside the card

### ISSUE THREAD

**Issue by leandroberetta** [kiali/kiali#4156]
Custom dashboards are supposed to be place in two rows, to display all the information without scrolling, but the user might want to place graphs in rows > 2, for example:

![custom_envoy](https://user-images.githubusercontent.com/1286393/124613484-a8266700-de49-11eb-9fdc-66fc6e8c01ce.png)

So this issue propose to include more rows in the white card.

**Comment by lucasponce** [comment]
When Metrics tab were refactored it used a fixed rows layout, the columns were flexible, but due the charts are rendered with absolute sizing, limiting the rows was somehow needed to fit the size.

But I think we could be more flexible and combine both approaches, user may define the number of rows from the dashboard.

It can easily introduce some regressions as it may need some changes in the previous implementation, but I'm going to take a look on it.
