### ISSUE TITLE
test the session timeout

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#4164]
We should test the session timeout feature. ~We can easily add that to the [openid-test](https://github.com/kiali/kiali-operator/tree/master/molecule/openid-test) molecule test.~ maybe not so easy for openid.

Maybe consider just testing the [token-test](https://github.com/kiali/kiali-operator/tree/master/molecule/token-test) but do the same kind of thing https://github.com/kiali/kiali-operator/pull/354 tried to do

**Comment by jshaughn** [comment]
@jmazzitelli the session timeout has had a history of issues, a test will be good but I think there are also some corner cases.

**Comment by jmazzitelli** [comment]
here's the login token timeout setting: https://github.com/kiali/kiali-operator/blob/v1.36.0/deploy/kiali/kiali_cr.yaml#L815-L817

**Comment by jmazzitelli** [comment]
I have the timeout set to 15 seconds, the test sleeps for 20 seconds, and yet the test does not get an error. Unless I misunderstand how this session timeout stuff works, I believe the [PR with the new molecule test](https://github.com/kiali/kiali-operator/pull/354) is showing a problem.
