### ISSUE TITLE
Display Envoy tab for workloads running Istio Proxy without Sidecar

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#4165]
For workloads that are running the Istio Proxy but not as a sidecar, Kiali does not display the envoy tab for the workload.

![Screenshot from 2021-07-12 09-58-31](https://user-images.githubusercontent.com/6226732/125300312-e6af9c00-e2f7-11eb-9bdf-f5015fc6513b.png)

For processes such as gateways, providing the envoy details can be very useful in debugging the envoy configuration. Kiali should display the envoy tab for workloads running the Istio Proxy alone the same as it does for workloads running the proxy as a sidecar:

![Screenshot from 2021-07-12 09-57-53](https://user-images.githubusercontent.com/6226732/125301177-b3b9d800-e2f8-11eb-87a3-f4f7fc12df4d.png)

**Comment by jshaughn** [comment]
@nrfox That makes sense to me, I think this is for workloads that are themselves a proxy?

**Comment by nrfox** [comment]
> I think this is for workloads that are themselves a proxy? I think I added something to support this same scenario in the Logs tab, because we wanted to make sure that we treated Envoy logs properly, even if it wasn't the istio-proxy container.

Yep, exactly that. Sounds the same as the logs scenario. There may be other relevant workloads that run the envoy proxy but gateways in particular I noticed did not have the envoy tab but that would be useful in debugging where the gateway is routing your traffic.

**Comment by jshaughn** [comment]
> Yep, exactly that. Sounds the same as the logs scenario...

I believe I added ContainerInfo.IsProxy, so if you have the container you can make the decision.

**Comment by lucasponce** [comment]
+1 I've checked that the backend API should work correct for ingress/egress workloads

A query like this is valid:
```
http://localhost:8000/api/namespaces/istio-system/pods/istio-ingressgateway-569f64cdf8-jhj6t/config_dump
```

So, probably updating the case in the UI when rendering the workload details may be the approach to address this one:

```
 if (this.state.workload && this.hasIstioSidecars(this.state.workload))
```
