### ISSUE TITLE
[small refactor] Remove double keys for validations

### ISSUE THREAD

**Issue by xeviknal** [kiali/kiali#4173]
In development, when adding/removing/updating validations there is a redundancy that makes dev a little bit harder some time: the usage of two different ids for the same validation. Here one example of the two ids for one validation:

https://github.com/kiali/kiali/blob/dae08cbfed82b4766115b5b3ea93432ae4071c9b/models/istio_validation.go#L226-L241

The first key is the ide for the associative map: `virtualservices.gateway.oldnomenclature`
The second key is the validation reference id: `KIA1108`.

I remember we wanted to keep the associative hash ids sorted alphabetically. For easing the task of dev to add/remove/modify validations. This might leave with some inconsistencies: the hash ids are sorted but the validation reference ids not (the case above).

On the other side, the existence of this intermediate id, the hast ids, makes the dev harder to troubleshoot. When devs get an issue saying `KIA1108` gives false positives, the devs need to find the ID in the hash (the validation message) look for the hash id and then look where the hash id is in the code base. Which could be pretty much direct.

I do propose to have the validation ref. id as the hash id (and keep it as it is as part of the validation message). Something like that:

```go
 "KIA1101": { 
 	Message:  "DestinationWeight on route doesn't have a valid service (host not found)", 
 	Severity: ErrorSeverity, 
 },
 "KIA1102": { 
 	Message:  "VirtualService is pointing to a non-existent gateway", 
 	Severity: ErrorSeverity, 
 },
```

Last point to consider: validation ref ids shouldn't change otherwise users would get different messages for same IDs depending on which kiali version they have installed. We want to keep the same id as long as the validation life.

This should be quite small change but would improve devs life a bit.

**Comment by jmazzitelli** [comment]
> I do propose to have the validation ref. id as the hash id (and keep it as it is as part of the validation message). Something like that:
> 
> ```go
>  "KIA1101": { 
>  	Message:  "DestinationWeight on route doesn't have a valid service (host not found)", 
>  	Severity: ErrorSeverity, 

This is "kind of" implemented here: https://github.com/kiali/kiali/pull/4205

Well, it doesn't do what this issue wants :) which is remove the duplicate keys. But what it does do is this (adds a code field):

```
	"destinationrules.mtls.nspolicymissing": {
		Code:     "KIA0206",
		Message:  "PeerAuthentication enabling namespace-wide mTLS is missing",
		Severity: ErrorSeverity,
```

I don't think we can get away from having 2 keys if we want an easy-to-remember and easy-to-lookup-in-the-docs ref ID (`KIALI####`) but yet have a more human-readable code for devs to be able to use (`destinationrules.mtls.nspolicymissing`). I think its fine to keep the human-readable hash key and just associate it with a code inside the IstioCheck object because I agree with you that keeping that makes it easier for devs to troubleshoot. The only alternative I can think of is "mash together" the two concepts and take away the code but make the hash key something like "DR.MTLS.NPMISSING" - but I think that makes the situation worse (doesn't make it easy to remember for users, and still isn't very human-readable for devs) so that really isn't a viable option IMO.

However, if you want me to do what you suggest in this issue (remove the hash key and replace it with the ref ID code), I can do it as part of that existing PR (which needed the ref ID code separated out anyway).

**Comment by xeviknal** [comment]
I am closing this because I think the current changes in the #4205 make sense. And, yep, at the end having a human readable hash key makes it easy for devs preventing them for remembering which KIAXX00 was from which istio object.
