### ISSUE TITLE
Editable Istio config annotations for workloads and services

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#4179]
Istio can be configured for an individual resource using [annotations](https://istio.io/latest/docs/reference/config/annotations/). As an example, enabling/disabling sidecar injection can be accomplished by adding the `sidecar.istio.io/inject` annotation to a pod's metadata. There are many different configuration options available as annotations and the schema for these varies depending on the option. Some are simple `key: value` such as sidecar injection: `sidecar.istio.io/inject: "true"` and some are more complex values: `proxy.istio.io/config: '{"proxyMetadata": {"ISTIO_META_DNS_CAPTURE": "true"}}'`.

Kiali can make adding these config annotations easier for users by:
1. Providing a way to easily view and edit config annotations for resources (workloads/services)
2. Having placeholder text that shows the user what the schema for the annotation should look like

This would allow users to quickly know what config options are available, what the schema is when adding new annotations, and what options are currently applied to that resource.

**Comment by lucasponce** [comment]
Good topic, the original plan on this was to have these annotations as part of the "implementation" side but from Kiali to allow to "drive" some high level actions on them.

Otherwise, it's just to enable to edit a Workload/Deployment from Kiali which is more a kubernetes admin task.

Today, there are some actions in that direction, as pointed, as inject a sidecar.

Other areas could be to allow to map some "high level" scenario into the "Istio config", one areas in the radar could be to adjust the "tracing" config (sampling or specific features).

Perhaps, it could be a good idea to allow to edit partially the annotations that are relative to Istio and/or Kiali and just send a patch to them.

Thanks for bringing this one @nrfox it's good to brainstorm on them, definitely a good topic.

**Comment by nrfox** [comment]
> Good topic, the original plan on this was to have these annotations as part of the "implementation" side but from Kiali to allow to "drive" some high level actions on them.
> 
> Otherwise, it's just to enable to edit a Workload/Deployment from Kiali which is more a kubernetes admin task, and probably it's out of the scope of Kiali itself but more other admin tooling.

Thanks for the context. Agreed that just having Kiali be a YAML editor for kube objects is out of scope.

> Perhaps, it could be a good idea to allow to edit partially the annotations that are relative to Istio and/or Kiali and just send a patch to them.

That's exactly what I was thinking of. If a user wants to apply one of these annotations to their workload, they probably are testing or debugging the effect of changing one of these settings for that particular workload. The friction that I think Kiali could make easier is 1. knowing exactly which settings can be configured this way without having to search for the right reference page 2. getting the formatting correctly for the "value". It might also be helpful to display the global settings with the annotations overriding those since these annotations basically act as overrides for the individual workloads they are applied to.

The actions selector seems like a natural place for this but there may be a large amount of actions if each setting was its own action the same way that the sidecar injection works today. The actions selector also makes it a bit harder to find this functionality. Maybe "istio configuration options" could be a separate card on the workload details page? The naming needs some work since it conflates with "istio config" which is the istio objects that apply to that particular workload.

**Comment by lucasponce** [comment]
> The actions selector seems like a natural place for this but there may be a large amount of actions if each setting was its own action the same way that the sidecar injection works today. The actions selector also makes it a bit harder to find this functionality. Maybe "istio configuration options" could be a separate card on the workload details page? The naming needs some work since it conflates with "istio config" which is the istio objects that apply to that particular workload.

Yes, it's something to be discussed.
Some high level actions make sense as "change the sampling of tracing for a particular workload", user shouldn't need to deal with schema or yaml edition.
But in others perhaps the user may benefit to have a new tab with these "Istio Annotations" in a yaml format that can be edited and sent as a patch.

**Comment by lucasponce** [comment]
On this one I think it still requires some discussion but it's close to define a scope.
As it's not in the scope to have a yaml editor for the deployment, perhaps a modal with a table where user can add/edit/delete annotations could work.

I think annotations may be restricted to the Istio/Kiali ones, and this should be combined with the actions that see annotations as "part of the implementation", as we will have other "high level actions" that would create annotations.

With this way, annotations would be able to be editable.

**Comment by nrfox** [comment]
> As it's not in the scope to have a yaml editor for the deployment, perhaps a modal with a table where user can add/edit/delete annotations could work.
> 
> I think annotations may be restricted to the Istio/Kiali ones, and this should be combined with the actions that see annotations as "part of the implementation", as we will have other "high level actions" that would create annotations.
> 
> With this way, annotations would be able to be editable.
> 
> This should be discussed with @andrew-ronaldson / UX but I was also thinking in a flow similar as this but restricted for Istio/Kiali scope - as previously discussed -:

That sounds great! By restricting the editable annotations in the modal to Istio/Kiali you can provide richer validation and autocomplete to help guide the user to the correct usage.

**Comment by jshaughn** [comment]
Hi @aljesusg , I see you revived this recently and are working on it, do you want to provide any detail about the approach you are taking, do we need UX input?
