### ISSUE TITLE
Add graph Factory Reset button

### ISSUE THREAD

**Issue by mattmahoneyrh** [kiali/kiali#4184]
With the growing number of graph display options, it would be helpful to have a button that would reset all display options to default values (aka Factory Reset button).

**Comment by lucasponce** [comment]
I understand that the scope of this feature would be mostly the new traffic options:
![image](https://user-images.githubusercontent.com/1662329/129159909-c917095c-e500-4328-97e7-9bdde2704512.png)

The display options:
![image](https://user-images.githubusercontent.com/1662329/129159952-12b09e74-e422-4e05-92d0-6748e69a4534.png)

And the type of graph:
![image](https://user-images.githubusercontent.com/1662329/129160042-f4e62035-7176-47ca-b7e5-73cd881e8a06.png)

But this button should keep the namespace(s) selected and the time component as those may be shared by other pages.

It sounds doable.
