### ISSUE TITLE
ERR GetAppTraces, Jaeger GRPC client error: rpc error: code = Unavailable desc = connection closed

### ISSUE THREAD

**Issue by samene** [kiali/kiali#4192]
**Describe the bug**

Kiali Operator
```
external_services:
  tracing:
    in_cluster_url: http://tracing-query.istio-system:16686/jaeger
```
In the Kiali app when I try to navigate to the traces get ```503``` with below error in pod log.

```
ERR GetAppTraces, Jaeger GRPC client error: rpc error: code = Unavailable desc = connection closed
```

But I am able to open jaeger UI and also do a curl
```
curl http://tracing-query.istio-system:16686/jaeger/api/traces

{"data":null,"total":0,"limit":0,"offset":0,"errors":[{"code":400,"msg":"parameter 'service' is required"}]}
```

**Versions used**
Kiali 1.37.0, Jaeger 1.24.0 and istio 1.10.2
Kubernetes 1.21.1 (kubeadm bare-metal)

**Comment by xeviknal** [comment]
Have you had the chance to go through the [tracing settings](https://github.com/kiali/kiali-operator/blob/master/deploy/kiali/kiali_cr.yaml#L615-L642) into the kiali-cr?

Another thing you can try is to disable the [grpc](https://github.com/kiali/kiali-operator/blob/master/deploy/kiali/kiali_cr.yaml#L639). It fallbacks to a regular HTTP calls.
