### ISSUE TITLE
readme is missing instructions how to open the app

### ISSUE THREAD

**Issue by abonas** [kiali/kiali#42]
- accessing the sws route from oc get routes, it outputs "unable to connect"
- accessing the sws service (host and port) outpus "forbidden"

**Comment by jmazzitelli** [comment]
The "forbidden" means you didn't give the proper credentials. Right now, its simply  "jdoe" username and "password" password.

When I access the route from oc get routes, it works for me (I get the UI console's error page about not having javascript - which of course curl does not have):

```
$ curl -u jdoe:password http://$(oc get route sws -o jsonpath='{.spec.host}{"\n"}')

<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport"
 content="width=device-width,initial-scale=1,shrink-to-fit=no"><meta name="theme-color"
 content="#000000"><link rel="manifest" href="/manifest.json"><link rel="shortcut icon" 
href="/favicon.ico"><title>SWS UI</title><link href="/static/css/main.29266132.css" rel="stylesheet">
</head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div>
<script type="text/javascript" src="/static/js/main.60e3476d.js"></script></body></html>
```

**Comment by abonas** [comment]
> The "forbidden" means you didn't give the proper credentials. Right now, its simply "jdoe" username and "password" password.

correct only I would expect a dialog to enter credentials to popup, which did not happen (in browser of course, not in curl)
> 
> When I access the route from oc get routes, it works for me (I get the UI console's error page about not having javascript - which of course curl does not have):
> 
> $ curl -u jdoe:password http://$(oc get route sws -o jsonpath='{.spec.host}{"\n"}')
> 
> <!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport"
>  content="width=device-width,initial-scale=1,shrink-to-fit=no"><meta name="theme-color"
>  content="#000000"><link rel="manifest" href="/manifest.json"><link rel="shortcut icon" 
> href="/favicon.ico"><title>SWS UI</title><link href="/static/css/main.29266132.css" rel="stylesheet">
> </head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div>
> <script type="text/javascript" src="/static/js/main.60e3476d.js"></script></body></html>

**Comment by abonas** [comment]
tried several things.
now accessing via service host:port yields the react default page which I assume at this point is ok
however accessing the route including your suggestion with curl still results with Connection refused

**Comment by jmazzitelli** [comment]
> correct, only I would expect a dialog to enter credentials to popup, which did not happen (in browser of
> course, not in curl)

I don't know what to say about that. You should be getting back a 401. In my case, I do see get that and I do see the dialog. I am using Google Chrome:

![login](https://user-images.githubusercontent.com/2029470/36357524-4527e5f0-14cd-11e8-86b6-96fe648468f0.png)

**Comment by pilhuhn** [comment]
Is this solved? 
The README points to kiali.org for further instructions. Is that good enough?

**Comment by abonas** [comment]
@pilhuhn it is better now.
