### ISSUE TITLE
Workload's page Actions dropdown is clickable in view_only_mode 

### ISSUE THREAD

**Issue by linjmeyer** [kiali/kiali#4202]
**Describe the bug**

When deploying Kiali with `view_only_mode: true` the Actions drop down with options like "Disable Istio Injection" is not clickable on the Services page, but is clickable on the Workloads page.  This seems to be a UI only bug as when you click it, you will get an HTTP 500 and Kiali logs show a permissions error.

For UI issues please also add a screenshot that shows the issue.

**Versions used**
Kiali: v1.36
Istio: v1.10
Kubernetes flavour and version: GKE

**To Reproduce**
1. Deploy Kiali (for me this is using the Operator)
2. set deployment.view_only_mode: true
3. Navigate to a workloads page
4. Hover/Click the "Actions" drop down on the top right

**Expected behavior**
Button should be disabled like on other pages.  For example on the Services page the button is greyed out and not clickable.

**Comment by xeviknal** [comment]
I have to mention @lucasponce for this one.
