### ISSUE TITLE
Add missing warning on VirtualService "exportTo" field.

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#4203]
According to [Istio documentation](https://istio.io/latest/docs/reference/config/networking/virtual-service/), "NOTE: in the current release, the exportTo value is restricted to “.” or “*” (i.e., the current namespace or all namespaces)." for VirtualService.

So it needs to modify the "exportTo" field's validation for VirtualService only and show warning when it uses any "namespace" besides "*" or ".".

**Comment by xeviknal** [comment]
@hhovsepy I've just realized that the `notice` message on the VS is gone for istio 1.11. So I'd not consider applying this exception in the validations. 

See the removal: https://preliminary.istio.io/latest/docs/reference/config/networking/virtual-service/

I didn't see that before. I guess that validation won't perfectly work for istio 1.10.x but I guess it is an small price to pay.

**Comment by hhovsepy** [comment]
fixed now
