### ISSUE TITLE
ERR GetAppTraces, Jaeger GRPC client error: rpc error: code = Unavailable desc = connection closed

### ISSUE THREAD

**Issue by xeviknal** [kiali/kiali#4207]
### Discussed in https://github.com/kiali/kiali/discussions/4193

<div type='discussions-op-text'>

<sup>Originally posted by **samene** July 20, 2021</sup>
**Describe the bug**

Kiali Operator
```
external_services:
  tracing:
    in_cluster_url: http://tracing-query.istio-system:16686/jaeger
```
In the Kiali app when I try to navigate to the traces get ```503``` with below error in pod log.

```
ERR GetAppTraces, Jaeger GRPC client error: rpc error: code = Unavailable desc = connection closed
```

But I am able to open jaeger UI and also do a curl
```
curl http://tracing-query.istio-system:16686/jaeger/api/traces

{"data":null,"total":0,"limit":0,"offset":0,"errors":[{"code":400,"msg":"parameter 'service' is required"}]}
```

**Versions used**
Kiali 1.37.0, Jaeger 1.24.0 and istio 1.10.2
Kubernetes 1.21.1 (kubeadm bare-metal)
</div>

@samene has commented that he is not using any reverse-proxy so this should work properly.

**Comment by jmazzitelli** [comment]
Just FYI that upstream Istio 1.11 is moving to Jaeger 1.22 - it looks like this will hit people when they move to 1.11 and they use the jaeger addon. See: https://github.com/istio/istio/pull/32681

**Comment by xeviknal** [comment]
Here my findings about this issue:

> Separate Ports for GRPC and HTTP requests in Query Server (#2387, @rjs211) https://github.com/jaegertracing/jaeger/releases/tag/v1.20.0

Therefore, all the jaeger installation greater than 1.20 will fail while using gRPC and the port 80.
I am preparing a fix to change the default port. I guess that when people have troubles with gRPC (for the reverse-proxy known issues, they will have to be aware of this change). Besides that, I think that kiali can't do more.

**Comment by xeviknal** [comment]
@jmazzitelli @jshaughn changing the default port for gRPC will break default kiali installations with jaegers prior to 1.20. Should this be a problem? We might have some users upgrading kiali which doesn't have the `in_cluster_url` manually defined in their kiali-cr who will see problems with the tracing integration. The approach though is easy: define the `in_cluster_url`.
Do you think we can do better? Should we parse the `jaeger` service see where's the gRPC port and take it from there? I don't think so.

**Comment by jshaughn** [comment]
@xeviknal @jmazzitelli I think it's fine to change the default port for gRPC starting with the 1.38 release, to support Istio 1.11's move to Jaeger 1.22.  We want that to work out-of-the-box.   For the `in_cluster_url` would it make sense to add some documentation in the example CR, indicating the default port change for Jaeger?

**Comment by jmazzitelli** [comment]
> For the `in_cluster_url` would it make sense to add some documentation in the example CR, indicating the default port change for Jaeger?

Yeah, I think a small sentence in the kiali_cr example that mention this would be best.
