### ISSUE TITLE
How to configure user info endpoint to get the user details in implicit code flow?

### ISSUE THREAD

**Issue by sskmail14** [kiali/kiali#4211]
**Is your feature request related to a problem? Please describe.**
Is there any way to get the user info with user info endpoint to show the user details in implicit code flow
**Describe the solution you'd like**
Am trying to show the user details as part if implicit code flow as its recommended. I have tried the below config but still didn't work. It shows me as `OpenId User`
```
    auth:
      strategy: openid
      openid:
        username_claim: "email"
        .....
        .....
```
**Describe alternatives you've considered**
Do we have any documentation on this to get the detais from user info endpoint?
**Additional context**
NA

**Comment by jmazzitelli** [comment]
This is a question - moving to github discussion as a "Q&A" topic.
