### ISSUE TITLE
WorkloadEntry workload graph nodes have broken link

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#4219]
**Describe the bug**
`WorkloadEntry` workload graph nodes have a broken link to the Workloads tab. These workloads do not run within Kubernetes and won't show up on the Workloads tab. 

**Versions used**
Kiali: 1.37
Istio: 1.10
Kubernetes flavour and version: 1.21

**To Reproduce**
1. Deploy a mesh with `WorkloadEntry` workloads
2. Click on a `WorkloadEntry` node on the graph
3. Click the link in the node summary panel
4. See the broken link to the Workloads tab

**Expected behavior**
`WorkloadEntry` graph nodes should link to their Istio Config the same way that `ServiceEntry` graph nodes link to their Istio Config.

**Comment by nrfox** [comment]
This is blocked by #4223 because without knowing which workload nodes are `WorkloadEntries`, it's unknown which workloads to fix the link for.

**Comment by nrfox** [comment]
Now that #4223 has been fixed this can be worked on.

**Comment by nrfox** [comment]
Workloads can have more than one `WorkloadEntry` so linking to a single `WorkloadEntry` will not work. If there are multiple, which one should be linked to?

In addition, workload nodes can represent **both** pods and workload entries. In this case, how can Kiali know if the workload node on the graph represents a workload with a workload entry **and** a deployment or just a workload entry without the deployment?

I'm still in favor of fixing the broken link but I propose that the workload nodes that have workload entries link to the istio config summary page filtering on the `WorkloadEntry` type rather than a specific `WorkloadEntry` or a specific `Workload`.

@jshaughn wdyt?

**Comment by jshaughn** [comment]
@nrfox I think probably more is better.  I'm not against multiple links in the side panel, so if it's easy enough to determine I'm fine with seeing multiple WE links.  I'm also fine just deferring to a filtered Istio Config page and having a single link.  We just need to ensure no broken links.  I thought all workload nodes, whether they are badged as a WE or not, would show up in the Workloads list, and have an associated workload detail page, am I confused?  Maybe that's untrue if it's only a WE.  If so we can't offer the detail page link, and I'm not exactly sure how we can figure that out, maybe we need to atually ask for all the workloads?  Note that we may also need this PR to ensure the context menu is correct and robust.

**Comment by nrfox** [comment]
> Maybe that's untrue if it's only a WE. If so we can't offer the detail page link, and I'm not exactly sure how we can figure that out, maybe we need to atually ask for all the workloads? Note that we may also need this PR to ensure the context menu is correct and robust.

That's exactly right. Workloads that are only WE do not show up in the Workloads list today. The workloads list is effectively only the Kubernetes workloads (deployments, etc.) of a mesh. [This issue](https://github.com/kiali/kiali/issues/4169) proposes adding solely VM based workloads to the workloads list and has more context in there. Today, in order to offer both a link for the workload entries and a deployment, kiali would need to determine both "does this workload node have workload entries" **and** "does this workload node have kube workloads (deployments)".

I'd rather do as you proposed and just offer links for the individual workload entries for now and later do #4169. Then Kiali wouldn't need to know whether a workload was a kube workload or not. It would treat each the same way.
