### ISSUE TITLE
Distinguish between VM based workloads and pod based workloads on the graph

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#4220]
Kiali does not currently distinguish between VM based workloads and pod based workloads on the graph. Both workloads will show up as a "workload" icon. Being able to easily distinguish between the two on the graph could be helpful in understanding exactly how workloads in a mesh are configured. Kiali already distinguishes between a `Service` and `ServiceEntry` by having separate nodes for each on the graph. The distinction between workloads could be a number of things such as a separate icon or special bordering/labeling.

**Comment by lucasponce** [comment]
I think this one can be moved to backlog.
If task sounds big or depend of other previous work, don't hesitate to split it in other issues if necessary.

**Comment by nrfox** [comment]
Once https://github.com/kiali/kiali/pull/4284 is merged, this should be a straightforward change. It only needs to be decided what the visualization should be for workload VMs.

A few options are:
- Separate Icon similar to ServiceEntry vs. Service
- Special border or coloring around workload icon
- Graph badge similar to the VS badges

Personally I don't prefer a separate icon because a single workload node can represent *both* pods and VMs and having a separate icon when the workload has a WorkloadEntry makes it seems like the workload is _only_ VMs. I'm not sure there's much precedent for the special bordering/coloring so I prefer the graph badge.

**Comment by nrfox** [comment]
The icon may need to change but this is what it'd look like with a badge on the workload. A potential concern is that users confuse this badge with the VS badges and see the workloads as services at first glance but the workload node shape remains unchanged.

![Screenshot from 2021-08-18 16-18-58](https://user-images.githubusercontent.com/6226732/129966525-b4c63718-ff55-437c-ba7c-cb507143e62a.png)

**Comment by jshaughn** [comment]
@nrfox I'm also -1 on a new icon/shape.  The App or Workload node is still applicable, I think, regardless of whether that workload is a VM or a Pod.  I'm also -1 on changing the node color, or really any sort of change to the rendering, for the same reasons, it's fundamentally still an app or a workload.  users are already used to seeing us decorate nodes with badges.  I would suggest placing the badge at the leftmost position after TrafficSource or Gateway.  Which icon to use is really the question.  The one you have above is the way to go, it's literally the PF VM icon.  It does look a bit similar to the MissingSidecar badge but whatever.  One question we may want to pursue with UX is whether we should introduce different background colors for different badges.  For example, all of the request-routing badges could remain purple, but maybe we use a different color to help distinguish non-request-routing badges.  Just a thought.

**Comment by nrfox** [comment]
> One question we may want to pursue with UX is whether we should introduce different background colors for different badges. For example, all of the request-routing badges could remain purple, but maybe we use a different color to help distinguish non-request-routing badges. Just a thought.

That's interesting, I like that idea. I wonder if there's ever a situation where you'd end up with both colors.
