### ISSUE TITLE
Issues with clustering discovery

### ISSUE THREAD

**Issue by israel-hdez** [kiali/kiali#4221]
There are a few issues with _clustering discovery_ when Istio is installed with a revision (usually for canary upgrades).

The root cause are missing configurations in Kiali, because when using revisions (or custom names in the resources) the customized/versioned resource names need to be specified in Kiali configuration.

In any case, Kiali should have better defaults or fail gracefully:

* Although local cluster discovery fails gracefully, the local cluster is assigned the "unknown" name. This results with a graph with `unknown` cluster label for idle nodes, and `Kubernetes` cluster labels for nodes found through telemetry. This is caused because the [Istio deployment name is not specified in the KialiCR](https://github.com/kiali/kiali-operator/blob/15e1aaea57b887b10386c3c04fd424d431809a87/deploy/kiali/kiali_cr.yaml#L574).
  * Idle nodes should fallback to using `Kubernetes` for it's cluster name.
  * Relevant line to fix: https://github.com/kiali/kiali/blob/f754e63bd224d8e5e13eaec1d6cae230955b82a7/business/mesh.go#L450
* If the Istio deployment name is specified correctly, BUT the [sidecar injector config map name is unset](https://github.com/kiali/kiali-operator/blob/15e1aaea57b887b10386c3c04fd424d431809a87/deploy/kiali/kiali_cr.yaml#L573) there is a crash when Kiali tries to discover the network of the home cluster. Kiali should fail gracefully.
  * Possible location of the crash: https://github.com/kiali/kiali/blob/f754e63bd224d8e5e13eaec1d6cae230955b82a7/business/mesh.go#L234-L237

**Comment by jshaughn** [comment]
@israel-hdez That looks good.  In addition look for the three occurrences of `globalInfo.HomeCluster = "unknown"` in the grap appenders.   We don't want the default cluster name to every be "unknown", if anything it should be "Kubernetes" to match Istio.

**Comment by israel-hdez** [comment]
@jshaughn OK, I'll do that search&replace.
