### ISSUE TITLE
default PR merge to squash

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#4222]
Can I ask that we have github do a "squash" merge by default?
I was looking at the history of kiali/kiali repo for something and the history is very noisy with all merge commits and individual PR commits. We should "squash" merge by default to avoid this.

**Comment by jshaughn** [comment]
I thought it was already like this.  I always get "Squash and Merge" as the default button.   People should also take care to compose a nice, squashed commit message.

**Comment by xeviknal** [comment]
I found this: 
https://docs.github.com/en/github/administering-a-repository/configuring-pull-request-merges/configuring-commit-squashing-for-pull-requests

In the settings you can say to only allow squashing strategy.

+1 to force the squeeze. Don't like merge.

AFAIR, once you choose squash for one project, GH remembers that. But the default option if you don't configure the repo is a plain merge.
