### ISSUE TITLE
Improve the side panel in the Istio Config editor

### ISSUE THREAD

**Issue by xeviknal** [kiali/kiali#4241]
Original comment: https://github.com/kiali/kiali/issues/2447#issuecomment-878051784

> Today is used in some resources but I think it could be used in a more general way covering:
> - References of the workloads linked with a resource (using workload selectors).
> - References of the internal services linked with a resource.
> - References of the external destinations defined through ServiceEntry (a destination in a VirtualService can point to a ServiceEntry host, so the side panel could include these cases as well).
>
> Perhaps the current decorators for the VirtualService / DestinationRules can be revisited if they are adding value.
In particular I'd say more interesting to help user to understand how a matching rule is performed rather than to show visually the distribution, in other words, in the context of this effort if some of those looks outdated I'd be ok to remove it.

**Comment by lucasponce** [comment]
I've modified the title of this issue/epic as I think this effort can be used to re-design/refactor the current side panel used in the Istio config editor to add more value to the users.

Today, the side panel:
- Is used only on a limited set of resources.
- It has some outdated features (i.e. VS route visualization is not adding real value).

We could use this effort to:
- Add the side panel in a generic way to all resources managed by the Istio editor.
- Add meaninful references to other services/resources.
- Add meaninful status (Kiali validations, Istio status errors, reconcile status).
- Add a new section to help the user about the meaning of the Istio resources fields.

"Add a new section to help the user about the meaning of the Istio resources fields." 

What does this mean ?

The Istio config resources are complex, the side panel can work as a helper to give more meaninful information about some sections. In that way, we can introduce some "hovers" events, that would populate some information in the side panel about what a field should be used for what.

For example, let's combine the example of [1] with the information provided by [2], so, what I would propose is that the user is editing some Istio resource, Kiali can detect some sections of the resource and provide some meaningful information.

It's not a validation, but a helper that could be turn on/off by the user, but it would help them to provide some of the information defined in the reference [2] into the editor. In the example [1] this information is showed in a floating tooltip, but in the Kiali case it could be shown in the side panel (it can be simple in a first iteration, but setting the basis to provide this information).

(It can be seen like a schema validation/helper, but not sure if I'd like to see it like a pure syntax helper here, I guess that Kiali can add value and help the user to understand better this complexities when they are editing the resources, that would be also an added-value compared with any generic kubernetes/yaml editor).

[1] https://codepen.io/oatssss/pen/oYxJQV
[2] https://istio.io/latest/docs/reference/config/networking/virtual-service/

**Comment by leandroberetta** [comment]
Tasks for this epic:

- https://github.com/kiali/kiali/issues/4552
- https://github.com/kiali/kiali/issues/4553
- https://github.com/kiali/kiali/issues/4554
- https://github.com/kiali/kiali/issues/4555
- https://github.com/kiali/kiali/issues/4556
- https://github.com/kiali/kiali/issues/4557
- https://github.com/kiali/kiali/issues/4558
- https://github.com/kiali/kiali/issues/4559
- https://github.com/kiali/kiali/issues/4560
- https://github.com/kiali/kiali/issues/4561
- https://github.com/kiali/kiali/issues/4562
- https://github.com/kiali/kiali/issues/4563
- https://github.com/kiali/kiali/issues/4564

**Comment by jshaughn** [comment]
This looks good.  Given an example impl this could be farmed out for the different config, and may also serve well for contrbutions.

**Comment by leandroberetta** [comment]
> This looks good. Given an example impl this could be farmed out for the different config, and may also serve well for contrbutions.

Exactly, I will get that example implemenation and see if we have interested users to help completing all the resources!. By now I'm having fun with the editor and the dynamic markers.

**Comment by leandroberetta** [comment]
Closing as all sub tasks are completed and merged into master.
