### ISSUE TITLE
Docs and scripts regarding secrets and service accounts might need to be updated

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#4259]
OpenShift 4.8 no longer have secrets underneath service accounts (I don't know what versions of Kubernetes this affects, if any).

See: https://docs.openshift.com/container-platform/4.8/release_notes/ocp-4-8-release-notes.html#ocp-4-8-notable-technical-changes

```
Previously, service account tokens were secrets that were mounted into pods. Starting
with OpenShift Container Platform 4.8, projected volumes are used instead. As a result
of this change, service account tokens no longer have an underlying corresponding secret.
```

We have some docs (and maybe even some hack scripts) that expect SA tokens to be in secrets. We will have to change or modify them to support this new token storage. For example, see: https://kiali.io/documentation/latest/faq/#token-strategy

I don't know what other docs or scripts are affected. Need to look around.

**Comment by jmazzitelli** [comment]
We use this in our makefile to obtain the credentials for the addons when deploying in maistra: https://github.com/kiali/kiali/blob/v1.38.0/make/Makefile.operator.mk#L60

We use this for our molecule tests to, again, get the addon credentials when running tests in maistra environment: https://github.com/kiali/kiali-operator/blob/v1.38.0/molecule/default/prepare.yml#L25-L33

**Comment by lucasponce** [comment]
Would this apply to Kiali 1.36.x and ServiceMesh 2.1 in any mean ? or Maistra would handle this in that scenario ?
If yes then this issue should be added to the project as documentation for Kiali 1.36.x and newer should have priority to help downstream releases as well.

**Comment by jmazzitelli** [comment]
> Would this apply to Kiali 1.36.x and ServiceMesh 2.1 in any mean ?

I do not think this will affect those.
