### ISSUE TITLE
Kiali.io docs have bad links - causing CI to fail checks

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#4266]
We have some bad links in the kiali.io docs - all our doc PRs are failing the verify test because of this. We need to fix the links.

for example, see https://github.com/kiali/kiali.io/runs/3245355679

**Comment by lucasponce** [comment]
Raising priority.

**Comment by jmazzitelli** [comment]
I think this was just fixed a couple days ago. https://github.com/kiali/kiali.io/pull/399
