### ISSUE TITLE
Support the new istio injection label

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#4268]
We currently can be told what the sidecar injection _annotation_ is:

https://github.com/kiali/kiali-operator/blob/v1.38.0/deploy/kiali/kiali_cr.yaml#L571

But this annotation is deprecated (though is still supported in upstream Istio). The way that this should be done now is via a _label_ with the same name -- see https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/#controlling-the-injection-policy

We need to support the injection label, too, in addition to the annotation.

Server PR: https://github.com/kiali/kiali/pull/4309
UI PR: https://github.com/kiali/kiali-ui/pull/2230
Operator PR: https://github.com/kiali/kiali-operator/pull/413

**Comment by lucasponce** [comment]
Good to know, yes, it seems that not all doc is being updated
https://istio.io/latest/docs/reference/config/annotations/

I think this would only apply to the Workload actions I guess, as detection of sidecars is done directly through Pod containers.

**Comment by jmazzitelli** [comment]
More clarification from the upstream Istio team:

QUESTION: what happens if both are set? I assume when you say Label > Annotation that the label takes precedence. I just want to confirm that. If both label and annotation are set - I will assume annotation is ignored and label is used. Correct?

ANSWER: actually no, [if] either one is false it will not be injected

**Comment by jmazzitelli** [comment]
One weird thing is I don't see annotations working in 1.11:

```
$ _output/istio-1.11.0/bin/istioctl version
client version: 1.11.0
control plane version: 1.11.0
data plane version: 1.11.0 (3 proxies)

$ kubectl get pods -n simple-mesh 
NAME                            READY   STATUS    RESTARTS   AGE
simple-client-5f54f4b59-5hjvz   2/2     Running   0          12m
simple-server-7957d875-s4jtz    1/1     Running   0          12m

$ kubectl get pods -n simple-mesh simple-client-5f54f4b59-5hjvz -o jsonpath='{"annotation-->"}{.metadata.annotations.sidecar\.istio\.io/inject}{"\nlabel-->"}{.metadata.labels.sidecar\.istio\.io/inject}{"\n"}'
annotation-->
label-->true

$ kubectl get pods -n simple-mesh simple-server-7957d875-s4jtz -o jsonpath='{"annotation-->"}{.metadata.annotations.sidecar\.istio\.io/inject}{"\nlabel-->"}{.metadata.labels.sidecar\.istio\.io/inject}{"\n"}'
annotation-->true
label-->
```

You can see the `simple-client` has the sidecar - its label is `true` - the annotation does not exist.
`simple-server` does NOT have the sidecar - its annotation is `true` - the label does not exist.
I can't explain that - looks like the annotation didn't take effect.

**Comment by jmazzitelli** [comment]
I just found out (this is new to me) that the sidecar pod annotation can only OPT OUT of injection. It cannot opt in. In other words, the sidecar annotation value of "true" is meaningless -- the annotation only takes effect if the namespace label "istio-injection" is set to "true". So a value of "false" is the only meaningful value for the annotation.
