### ISSUE TITLE
How to scale kiali

### ISSUE THREAD

**Issue by chris530** [kiali/kiali#4271]
Kiali works great for us on our smaller clusters,  but  generating graphs fails on our larger namespaces with 1k nodes.    Any suggestions on scaling kiali ?   I have tried the obvious things like increase resources and replicas.

**Comment by jmazzitelli** [comment]
Good question that is actively under discussion - https://github.com/kiali/kiali/discussions/4080

**Comment by israel-hdez** [comment]
I wonder if you could tell:
* How many namespaces do you have?
* How many workloads do you have?
* Are you trying to get a graph of the whole cluster, or a graph of a (some) specific namespace(s)?
* What failure are you seeing in Kiali? (perhaps provide the error message in the UI or errors in logs?)

**Comment by lucasponce** [comment]
> Kiali works great for us on our smaller clusters, but generating graphs fails on our larger namespaces with 1k nodes. Any suggestions on scaling kiali ? I have tried the obvious things like increase resources and replicas.

Thanks @chris530, also worth to mention which version are you using.
There are some performance improvements that may vary depending of it.

But yes, I guess your comment is directly related to the https://github.com/kiali/kiali/discussions/4080 discussion
