### ISSUE TITLE
Mesh internal ServiceEntry should be grouped in app box with workloads

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#4295]
**General remarks**

Service nodes are grouped with their workloads on the "versioned app" graph. But internal ServiceEntries are not despite being a part of the same "app".

**Describe the bug**
In this screenshot, on the left is a Service without a ServiceEntry that is properly boxed with the workloads. On the right is a Service with a ServiceEntry that is excluded from the box with the workloads.

![Screenshot from 2021-08-20 15-55-46](https://user-images.githubusercontent.com/6226732/130287146-c4841169-c8da-4964-823b-decd47dfaf66.png)

**Versions used**
Kiali: 1.39
Istio: 1.11
Kubernetes flavour and version: upstream 1.21

**To Reproduce**
1. Deploy bookinfo
2. Create a ServiceEntry using the same selectors as one of the existing bookinfo app's Service.
3. On the versioned app graph, observe that the ServiceEntry does not get boxed with the app workloads.

**Expected behavior**
Expected internal ServiceEntry to be boxed with the app workloads that it corresponds to on the versioned app graph.

**Comment by jshaughn** [comment]
Hmm, that's interesting.  I guess the "se-aggregate" node must not be getting the "app" assigned.  Is it always true that the aggregated "se-service" nodes have the same "app" value, or is it possible to have "se-service" nodes with different apps, getting aggregated together?   If we safely aggregate, and assign the "app" value to the new serviceEntry node, it should get boxed.  Adding to the backlog.
