### ISSUE TITLE
Kiali Istio dashboards incompatible with thanos-query

### ISSUE THREAD

**Issue by vbergbauer** [kiali/kiali#4303]
**General remarks**

To reduce the load on the Prometheus server, we are directing Grafana and Kiali to a Thanos querier.
This works fine with Grafana, and mostly works with Kiali, as seen on:
- the graph:
  ![image](https://user-images.githubusercontent.com/8659572/131010698-e775da36-8443-42ab-9b49-22f96a9e907e.png)
- this custom dashboard:
   ![image](https://user-images.githubusercontent.com/8659572/131009951-6090cf6e-3d35-479e-bad3-480763604e0c.png)

**Bug**
The Istio dashboards do not show any data:
![image](https://user-images.githubusercontent.com/8659572/131010274-64552837-5075-4746-8414-4951adfab86d.png)

Looking at the Kiali logs, I see the following error:
```bash
kubectl kubectl -n observability logs -lapp=kiali | grep ' ERR '
2021-08-26T17:24:52Z ERR Failed to fetch Prometheus configuration: client_error: client error: 404
```
Indeed, the Thanos querier does not implement Prometheus's API `api/v1/status/config`.

However this **should not prevent Kiali from calling the query APIs** (as shown in the successful Istio Kiali graph and custom dashboards). Even if Kiali picks up information from the Prometheus config (like the default refresh), it should be able to fall back to some safe default value.

**Workaround**
I can use an Istio virtual service to route thanos-query:9090/api/v1/status/config to Prometheus (or to a static file server)
```bash
# Create Virtual Service to route /api/v1/status/config to Prometheus
cat <<EOF | kubectl apply -f -
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: thanos-query
  namespace: observability
spec:
  hosts:
  - thanos-query
  http:
  - match:
    - uri:
        exact: /api/v1/status/config
    route:
    - destination:
        port:
          number: 9090
        host: prometheus-prometheus
  - route:
    - destination:
        port:
          number: 9090
        host: thanos-query
EOF

# Inject the Istio sidecar into the Kiali deployment
kubectl -n observability patch deploy kiali --patch '{"spec":{"template":{"metadata":{"labels":{"sidecar.istio.io/inject": "true"}}}}}'
```

Then the dashboard works correctly:
![image](https://user-images.githubusercontent.com/8659572/131011569-8f9b6463-e6c1-4ce6-a54c-563c5916348e.png)

**Versions used**
Kiali: 1.38.1
Istio: 1.10.3 
Kubernetes flavour and version: KinD 0.11.1, GKE 1.20.8-gke.900, etc.

**Comment by aljesusg** [comment]
@vbergbauer what version of thanos are you using? I am trying to deploy the environment in gke to replicate the error

**Comment by vbergbauer** [comment]
Hi @aljesusg , I am using the latest released Thanos (0.22).

Thanos [query](https://thanos.io/tip/components/query.md/)  and [query frontend](https://thanos.io/tip/components/query-frontend.md/)  do not implement the Prometheus API `/api/v1/status/config`, because they don't  use a config file...

**Comment by jmazzitelli** [comment]
> What information from the Prometheus configuration are you using in your queries?

See: https://github.com/kiali/kiali/blob/v1.40.0/handlers/config.go#L176-L196

Kiali gets things like retention period and global scrape interval. IIRC, it does this to help the UI determine what options to give the user in things like the refresh drop down menu.

**Comment by vbergbauer** [comment]
@jmazzitelli, then we can have a cascade of settings
- New optional settings in the Kiali configuration (Prometheus retention period and global scrape interval): use them if specified
- Try to use `/api/v1/status/config` if the configuration entries are not defined.
- Maybe fall back to some default values if the API is not available?

**Comment by jmazzitelli** [comment]
Sounds like we'll need a special setting for Thanos proxy anyway - perhaps we do something in there. Like:

```
spec:
  external_services:
    prometheus:
      thanos_proxy:
        enabled: true
        retention_period: "7d"
        scrape_interval: "30s"
```

If `thanos_proxy.enabled` is `true` then we don't attempt to call the prometheus config API and we just use the hardcoded values found here in this `thanos_proxy` section.
