### ISSUE TITLE
bring Dapr service into Kiali

### ISSUE THREAD

**Issue by RobberPhex** [kiali/kiali#4310]
**Is your feature request related to a problem? Please describe.**

When using Dapr, there is no dashboard like Kiali to display service graph, app list with metric/trace.

**Describe the solution you'd like**
* In application detail, workload detail, service detail page, show Dapr traffic in traffic tab, show Dapr metrics in metrics tabs.
* At service graph, show Istio and Dapr in one graph.

**Describe alternatives you've considered**
Dapr can develop this kind of dashboard(I guess), but cannot interoperate with Istio service. For example, show Dapr service call and Istio service call at one graph.

**Additional context**

[Dapr](https://dapr.io/) is Distributed Application Runtime, which is a portable, event-driven runtime.

**Comment by RobberPhex** [comment]
I'm working on this way, but I'm not sure there is an alternative way or a better way.

**Comment by jmazzitelli** [comment]
Can you explain what Dapr is?

If this is asking for Kiali to support additional non-Istio service mesh implementations, that's already been requested several times in the past and declined. See:
* https://github.com/kiali/kiali/issues/2823
* https://github.com/kiali/kiali/issues/1679
* https://github.com/kiali/kiali/issues/3778

But I cannot tell if that is what this enhancement request is asking for - need details on what "Dapr" is.

**Comment by jmazzitelli** [comment]
* https://docs.dapr.io/concepts/overview/
* https://docs.dapr.io/concepts/service-mesh/

@lucasponce I wonder if there is room here to do an integration with Dapr in the same way we did with iter8?
