### ISSUE TITLE
Docker copy fails with permission denied

### ISSUE THREAD

**Issue by prary** [kiali/kiali#4319]
Running ```CLUSTER_TYPE=minikube MINIKUBE_PROFILE=ci MOLECULE_USE_DEV_IMAGES=true MOLECULE_SCENARIO="jaeger-test" make  molecule-test```
fails with following error.
'''
docker cp "/home/arya/.kube/config" molecule-volume-helper:/data/kubeconfig
ERRO[0000] Can't add file /home/arya/.kube/config to tar: open /home/arya/.kube/config: permission denied 
'''

https://github.com/kiali/kiali/blob/2c22b05724f967a95f3204130ce5327c6e9b4a0b/make/Makefile.molecule.mk#L149

Temporary fix for me was to copy 
```
cp .kube/config ~/config
docker cp config molecule-volume-helper:/data/kubeconfig
```

**Comment by jmazzitelli** [comment]
Looks like you just have a permissions restriction on your `/home/arya/.kube/config` file.

**Comment by prary** [comment]
That's what I thought, have tried with chmod+777 but it fails with same error. Not sure why?

**Comment by jmazzitelli** [comment]
https://github.com/docker/for-linux/issues/564

Moving this to "Discussions" - doesn't seem to be an issue with anything in Kiali
