### ISSUE TITLE
Metrics charts can be too thin

### ISSUE THREAD

**Issue by israel-hdez** [kiali/kiali#4325]
**General remarks**

Metrics charts look like this in my laptop screen:

![image](https://user-images.githubusercontent.com/23639005/131926090-32807861-ceb5-4ef5-9015-db1aaca5a4dc.png)

Laptop's maximum screen resolution is 1366x768, which is still a very common resolution:

![StatCounter-resolution-ww-monthly-202007-202108](https://user-images.githubusercontent.com/23639005/131926961-dcf098b0-c192-49c4-8520-76dcf9f86a48.png)

Reference: https://gs.statcounter.com/screen-resolution-stats/desktop/worldwide

**Comment by lucasponce** [comment]
Yes, on heights < 800 px with 2 rows it worked well, but when we introduced the TCP row it pushes this a little bit on narrow resolutions.

Additionally to the design, I see a bug in the screenshot that can be addressed.
