### ISSUE TITLE
Show gateway in istio config

### ISSUE THREAD

**Issue by zackzhangkai** [kiali/kiali#4326]
Create a gateway in *Request Routing* - *advanced options*. Then it will create a Virtualservice resource , a DestinationRule resource and a Gateway resource.
In the *istio config*, it just shows *virtualservice* and *destinationrule*.

I think *gateway* resource should also be displayed.

![image](https://user-images.githubusercontent.com/20178386/131968160-82c75033-9c62-400b-a4e1-eb4e78836843.png)

**Comment by lucasponce** [comment]
Thanks @zackzhangkai for the feedback.
Yes, I agree, it's not linked due the VirtualService and DestinationRule are linked only with the direct services.
But I think it could be a nice enhancement to add under the service others related Gateways that are linked with the VirtualService.

I'll put it in the backlog.

**Comment by hhovsepy** [comment]
This epic requires two subtasks to be implemented:

- [ ] Add Gateways in Istio Config list of Service details
- [ ] Add Gateways in Details column of Service List. Add it's support in Filters.
