### ISSUE TITLE
istio_config.go code need refactor, it's ugly.

### ISSUE THREAD

**Issue by YUNZHONGTAN** [kiali/kiali#4330]
**Is your feature request related to a problem? Please describe.**
the istio_config.go code need refactor,  it's not elegant.

**Describe the solution you'd like**
so, I refactor some functions.

**Describe alternatives you've considered**
not other considered.

**Additional context**

**Comment by jmazzitelli** [comment]
The description of this issue is completely the template. Please enter a description so we know what the issue is. Having the full template is not helpful.

**Comment by YUNZHONGTAN** [comment]
I just refactor the istio_config.go code, because it too long.

**Comment by jmazzitelli** [comment]
Does this fix any problems? "too long" and "ugly" is subjective. What issues is this fixing? Refactoring code for the sole purpose of making it shorter or pretty is not usually something we would do - the risk of introducing bugs is now introduced. i.e. "If it works, don't fix it"

@lucasponce @jshaughn - I'll let you decide.

**Comment by YUNZHONGTAN** [comment]
just work? Copy and paste？ok, i get u.
