### ISSUE TITLE
Publish release notes at the same time a release is generated

### ISSUE THREAD

**Issue by israel-hdez** [kiali/kiali#4336]
This is a follow-up of https://github.com/kiali/kiali/issues/4287.

Since we have deprecated release notifications, the only option left for community to receive release notifications is to subscribe to [Kiali's GitHub release page](https://github.com/kiali/kiali/releases) (unless somebody is going to manually post messages about new releases in other channels).

Ideally, release entries should have a description. We could use the description to post release notes and subscribed community will receive the notification together with release notes.

However, we are currently posting release notes in the website: https://kiali.io/news/release-notes/. So, at minimum, the release entry in GitHub should contain a link to the release notes in the website. But this also implies that release notes should be made available at the same time a release is created.

**Comment by lucasponce** [comment]
I think it could be interesting to make more robust the github releases page:
https://github.com/kiali/kiali/releases

As it seems to be an standard way, and then, perhaps in the website it can "echo" the release notes at a different time.

I would prefer to not add more dependencies/complexities in the pipeline I think.

**Comment by israel-hdez** [comment]
> I would prefer to not add more dependencies/complexities in the pipeline I think.

I know. It makes the pipeline more complex :-/ But it has the benefit that you relief some manual work. I don't know if there is a real trade off.

**Comment by jshaughn** [comment]
Minimally it would be nice if releases (probably could limit to non-pre-release .0 releases) at least had a link to the release notes page on kiali.io.  This has been done manually, and sporadically, (by me).  Looking now I see the last update was for 1.35 :-(

As for automating the actual release notes, it would be nice but we would have to do some work.  I don't know that we need the content in the gh release description, but it may be nice.   We do have a script but the way it works today is manual:
1. run script, which pulls closed issues from our gh project and forms the notes as output to stdout
2. manually clip the output and add it to the release-notes .adoc
3. edit away entries that aren't appropriate/useful for general consumption
4. submit/merge a kiali,io pr

To do that editing automatically we could use a gh label like "release-notes-skip" (easier to label the exclusions than the inclusions, I think).

**Comment by israel-hdez** [comment]
> Minimally it would be nice if releases (probably could limit to non-pre-release .0 releases) at least had a link to the release notes page on kiali.io.

That can be done easily by changing these lines: https://github.com/kiali/kiali/blob/9ad4aff742ce58462d03701d51da0e70360a436c/deploy/jenkins-ci/Makefile#L163-L166

According to [GitHub docs](https://docs.github.com/en/rest/reference/repos#create-a-release), it's as simply as adding a `body` attribute with the desired text to the JSON in that curl command.

**Comment by israel-hdez** [comment]
> As for automating the actual release notes, it would be nice but we would have to do some work. I don't know that we need the content in the gh release description, but it may be nice. We do have a script but the way it works today is manual:

I was thinking partial automation... Having the kiali-bot to create an issue with the release notes and only _add_ entries as PRs/issues are merged/closed. You can edit the text at any time. Then, at the release time, the bot does copy-paste of the text.

**Comment by jshaughn** [comment]
> I was thinking partial automation... Having the kiali-bot to create an issue with the release notes and only add entries as PRs/issues are merged/closed. You can edit the text at any time. Then, at the release time, the bot does copy-paste of the text.

Are the entries added automatically, when the issue is closed, or manually?  I'd be against a manual update and would prefer leveraging the existing script in some way.

**Comment by israel-hdez** [comment]
> Are the entries added automatically, when the issue is closed, or manually? I'd be against a manual update and would prefer leveraging the existing script in some way.

It can be automatically....

I see there already are exist tools that do this. For example, this one creates a draft directly in the release page (rather than an issue): https://github.com/release-drafter/release-drafter

It supports a label to skip from release notes (what you mentioned).

**Comment by israel-hdez** [comment]
Looks like release notes are being pushed to the repo on Fridays and then the release is being generated on Mondays.
Despite release notes are still generated partially manually, the final outcome is what is described in this issue: release notes go live together with the release.

The part about posting release notes in the GitHub release entry is not covered because release entries have a generic link. Since we haven't received any feedback or ask from community about it, probably it is very minor.

So, I'm closing this as done, given our current workflow.
