### ISSUE TITLE
Tracing Error: Request failed with status code 503

### ISSUE THREAD

**Issue by mattmahoneyrh** [kiali/kiali#4348]
Tracing is failing with Error: Request failed with status code 503

Kiali pod log:

2021-09-13T19:08:27Z INF Kiali cache for [namespace: default] started
2021-09-13T19:08:42Z ERR Error fetching availability of the tracing service: rpc error: code = Unavailable desc = connection closed
2021-09-13T19:08:57Z ERR Error fetching availability of the tracing service: rpc error: code = Unavailable desc = connection closed
2021-09-13T19:09:12Z ERR Error fetching availability of the tracing service: rpc error: code = Unavailable desc = connection closed
2021-09-13T19:09:36Z ERR GetAppTraces, Jaeger GRPC client error: rpc error: code = Unavailable desc = connection closed
2021-09-13T19:09:51Z ERR GetAppTraces, Jaeger GRPC client error: rpc error: code = Unavailable desc = connection closed
2021-09-13T19:09:51Z ERR Error fetching availability of the tracing service: rpc error: code = Unavailable desc = connection closed

Tested on OCP 4.8 and 4.9

**Comment by jshaughn** [comment]
I was unable to reproduce using kiali master, Istio 1.11.0 with the standard jaeger addon, and OpenShift 4.8.3.

Kiali UI 1.41.0 (3f28b9b31fe1a43432dc0e1b521f835c57acf9c9)
Kiali Server v1.41.0-SNAPSHOT (b3e167c2e063b4f4eb094d8784e95a07a71f6e31)

@mattmahoneyrh Any ideas what may be the difference?

**Comment by lucasponce** [comment]
Are we talking here of Istio upstream and Kiali upstream ? Or a different version.

This issue needs more data.

**Comment by lucasponce** [comment]
I ran a smoke test using OpenShift ServiceMesh 2.1 on OpenShift 4.8 (CRC) (to discard a blocker bug) and it looks ok:
![image](https://user-images.githubusercontent.com/1662329/133234944-e8b34b45-0b50-4eb3-aa84-5430983fff8e.png)
![image](https://user-images.githubusercontent.com/1662329/133234975-82499870-9e2f-4d28-842e-7879d4c355c7.png)

@mattmahoneyrh I guess there is a mix of versions here, also note that in Istio 1.11 there was a change in the health endpoint to check jaeger, it sounds familiar to that scenario but we need more info to investigate if this is a bug or a misconfiguration of the test environment.

**Comment by jshaughn** [comment]
> Are we talking here of Istio upstream and Kiali upstream

@lucasponce, Considering this is in githib and not Jira I think we can assume it's being reported against kiali master.  But would be good to know the Istio version.

**Comment by mattmahoneyrh** [comment]
The config is upstream Kiali built from master + istio 1.11.2
![image](https://user-images.githubusercontent.com/7262987/133266531-b9bafbcc-489b-47f4-a873-2b3ae6866fbb.png)

**Comment by lucasponce** [comment]
I guess it may be related to this 
https://github.com/kiali/kiali/pull/4240#issuecomment-889883601

Perhaps the Job that @mattmahoneyrh used has some step not updated related the default values ?

**Comment by lucasponce** [comment]
It seems the installation personalize the tracing "in_cluster_url", note that the default value should be:
"http://tracing.istio-system:16685/jaeger"

Pointing to that value:
https://github.com/kiali/kiali/blob/master/config/config.go#L525

**Comment by FilipB** [comment]
This can be closed. Our istio installation script did not reflect new defaults. It's fixed.
