### ISSUE TITLE
Validation: warn about workloads that are not protected by any AuthorizationPolicy

### ISSUE THREAD

**Issue by shireenf-ibm** [kiali/kiali#4368]
Istio: When no AuthorizationPolicies select a workload, all requests are allowed , a thing that may cause security issues.
so a warning on uncovered workloads may help the user to improve the access control on his resources

**Comment by lucasponce** [comment]
Nice feature proposal.
It suits pretty well in the work that Kiali is performing under workload details.
As it's a "negative" validation, meaning that it will warn when there is no presence of an AuthorizationPolicy under a workload, perhaps it needs to be located as a "missing sidecar" category workload, or perhaps, better, as a warning per "Pod".

Thanks for the issue @shireenf-ibm, if you'd like to approach an implementation, we can help you to get familiar with the code and also to coordiante how a design can be. A first catchup task would be to get familiar with the current structure of validations logic, mainly located under:

https://github.com/kiali/kiali/blob/master/business/istio_validations.go
https://github.com/kiali/kiali/tree/master/business/checkers

Feel free to ping us for any comment.

**Comment by shireenf-ibm** [comment]
Hi,
Thanks for your comment, it was very helpful.
before starting with implementation, I would like to share my plan with you and get your review/confirmation:
* to add a new checker under business/checkers/authorization directory,  that gets both authorizationPolicies list and models.workloadsList 
and for each workload it checks if it is covered by at least one authorizationPolicy.
if not, a warning on the workload will "be printed"
* add the new checker to the "Group validations" of the authorization policies checker. (business/checkers/authorization_policies_checker.go)

**Comment by lucasponce** [comment]
Thanks @shireenf-ibm,

I guess the main parent checker has all that you'd need:
![image](https://user-images.githubusercontent.com/1662329/134891435-ee51c451-9a76-4ec2-8ceb-e72e2084243a.png)

So, I think you could add a new checker under the business/checkers/authorization/ folder covering this new case.

I think in the PR we can get into more details, this area is also in active development and probably some of the others pending PRs may affect here, but we'll be actively working with you to minimize any side effect.

But, thank you for proposing this and jumping into the code, I think every checker has tests that you can take as an example to validate your proposal.
