### ISSUE TITLE
Ability to pass custom headers to httputil.Post

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#4377]
Add the ability to pass in custom http headers to `httputil.Post` the same way that it is supported for `httputil.Get`.

Follow up from: https://github.com/kiali/kiali/pull/4375

**Comment by jshaughn** [comment]
@nrfox Is this a required to support an existing feature or request, or a potential nice-to-have?   Not sure if this is appropriate for Backlog or Future labeling.

**Comment by jmazzitelli** [comment]
This would be potential nice-to-have so we can use it later. We just added the custom headers to the HttpGet function - so to remain consistent and support the same thing as HttpGet does, the idea is to add the capability to handle headers in the new HttpPost also.

**Comment by jshaughn** [comment]
@jmazzitelli, If you think it's best to do now then add it to the backlog (and possibly the sprint backlog to just get it done immediately, as part of the current work), otherwise just set it to Future.

**Comment by jmazzitelli** [comment]
adding to backlog. We can do this now. It is really easy to add and won't cause any changes to the way things work now.

**Comment by nrfox** [comment]
> adding to backlog. We can do this now. It is really easy to add and won't cause any changes to the way things work now.

+1 I think it'll just be updating functions and call sites
