### ISSUE TITLE
Refactor Kiali Validations to better use the Istio registry information

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#4382]
The Kiali validations fetch workloads, services, pods and Istio resources to perform "semantic validations". 
The term "semantic validation" refers to validate that a hostname or a resource referenced in a Istio object exists in the cluster, for example, an internal hostname should match a kubernetes service, a workload selector should have a workload in the namespace that is defined, etc.

Recently, Kiali introduced the Istio registry as another source of information, but the Istio registry overlaps some of the information collected fetching directly Kubernetes services and workloads.

This Epic is a proposal to refactor the existing Istio Validations to reduce the number of fetches and use the Istio registry as main source of information for services and workloads.

The proposal have several advantages: cross-namespace validations can be calculated in a uniform way as the registry fetches all the cluster/mesh visibility; another advantage is that validation logic will use less fetches and it will simplify the code.

The istio registry has several APIs, today is used the "registryz", but for this work it may be necessary to use the "endpointz" one.

The endpoints can give the list of workloads and labels, so validations as label selector can be calculated with this information.

In terms of feature, this is a refactoring, meaning that there should be not regression in the existing logic.

This is a brief list of potentital changes in the validation logic, probably it's not 100% complete, but it would give an idea about the changes in the existing checkers:

```
1.- istio_validations.go

#GetValidations

Service can be validated against the registry, instead to fetch the kubernetes service

Workloads used in the validations can be replaced by the registry endpoints, which links all workloads with services.
That could be enough for the validation logic, as the registry has the proper labels information.

Potentially the list of namespaces could be infered from the registry ?

2.- no_service_checker.go

Service names and service hosts can be used from the Istio registry.

3.- no_host_checker.go

#checkDestination can unify the host check and consolidate/simplify the fqdn and cross validation logic using the registry only.
No service names, service entries or namespaces should be necessary using the registry.

4.- no_gateway_checker.go

+1 Valid, no changes as this validations iterates between Istio Gateways and VirtualServices

5.- no_dest_checker.go

Host logic can be checked against registry.

The #HasMatchingWorkloads logic could be replaced with the endpoints as they contain the list of pods with the workload identified.
The #HasMatchingServices and #HasMatchingServiceEntries logic could be replaced in a similar way.

6.- route_checker.go

+1 Valid

7.- subset_presence_checker.go

+1 Valid

8.- export_to_namespace_checker.go

The Istio registry may have access to all namespaces from the mesh, so perhaps for the validations it can be used this list.
Validations only check "namespace" names, and also, all envoy sidecars have access to the same information.

9.- destination_rules_checker.go

#ServiceEntryHostnames could be replaced by registry information

10.- multi_match_checker.go

#GetHost logic may be updated as probably the "cluster domain" may vary on federation scenarios when building FQDN

ServiceEntries variable looks unused

11.- disabled_namespacewide_mtls_checker.go

+1 Valid (from registry perspective)

12.- disabled_meshwide_mtls_checker.go

+1 Valid

13.- gateway_checker.go

WorkloadsPerNamespace could be replaced by registry/endpoints information.

14.- selector_checker.go

#hasMatchingWorkload can be run against the endpoints from the registry as endpoints have the labels used for selector from the pods.

15.- peer_authentication_checker.go

WorkloadList could be replaced by the list of endpoints.

16.- multimatch_selector_checker.go

#multiMatchSubjects could use the labels provided by the registry's endpoints.

17.- workload_selector_checker.go

WorkloadList could be replaced by the list of endpoints.

18.- disabled_meshwide_checker.go

+1 Valid

19.- disabled_namespacewide_checker.go

+1 Valid

20.- service_entry_checker.go

The Istio registry may have access to all namespaces from the mesh, so perhaps for the validations it can be used this list.
Validations only check "namespace" names, and also, all envoy sidecars have access to the same information.

21.- authorization_policies_checker.go

Namespaces can be collected from the Istio registry information.
Services and WorkloadList can be collected from registry and endpoints information.

22.- namespace_method_checker.go

+1 Valid

23.- request_authentication_checker.go

WorkloadList could be replaced by the list of endpoints.

```

Also, this is an example of endpoint entry from the registry:

```
  {
    "svc": "reviews.default.svc.cluster.local:http",
    "ep": [
      {
        "service": {
          "Attributes": {
            "ServiceRegistry": "Kubernetes",
            "Name": "reviews",
            "Namespace": "default",
            "Labels": {
              "app": "reviews",
              "service": "reviews"
            },
            "UID": "istio://default/services/reviews",
            "ExportTo": null,
            "LabelSelectors": {
              "app": "reviews"
            },
            "ClusterExternalAddresses": null,
            "ClusterExternalPorts": null
          },
          "ports": [
            {
              "name": "http",
              "port": 9080,
              "protocol": "HTTP"
            }
          ],
          "creationTime": "2021-09-21T07:37:09Z",
          "hostname": "reviews.default.svc.cluster.local",
          "address": "10.109.180.200",
          "Mutex": {},
          "cluster-vips": {
            "Kubernetes": "10.109.180.200"
          },
          "Resolution": 0,
          "MeshExternal": false
        },
        "servicePort": {
          "name": "http",
          "port": 9080,
          "protocol": "HTTP"
        },
        "endpoint": {
          "Labels": {
            "app": "reviews",
            "pod-template-hash": "7bf8c9648f",
            "security.istio.io/tlsMode": "istio",
            "service.istio.io/canonical-name": "reviews",
            "service.istio.io/canonical-revision": "v2",
            "topology.istio.io/cluster": "Kubernetes",
            "topology.istio.io/network": "",
            "version": "v2"
          },
          "Address": "172.17.0.11",
          "ServicePortName": "http",
          "EnvoyEndpoint": null,
          "ServiceAccount": "spiffe://cluster.local/ns/default/sa/bookinfo-reviews",
          "Network": "",
          "Locality": {
            "Label": "",
            "ClusterID": "Kubernetes"
          },
          "EndpointPort": 9080,
          "LbWeight": 0,
          "TLSMode": "istio",
          "Namespace": "default",
          "WorkloadName": "reviews-v2",
          "HostName": "",
          "SubDomain": "",
          "TunnelAbility": 0
        }
      },
. . . 
```

The registry is being queried from the control plane (istiod) and it's typically cached, so, it can be easily reused across all the validation logic.

I think this Epic will require coordination of several folks as is going to touch several areas that are being worked at the moment.

I suggest this walkthrough to progress on it:
- [x] A) Refactor the Services layer to build the Services List/Details from the Registry #4426
- [x] #4528
- [x] #4546
- [x] D) The TLS validation https://github.com/kiali/kiali/issues/4224 can be a case of the B) task, in any case, worth to mention here as it would be part of this effort.

**Comment by lucasponce** [comment]
> +1 on getting information about the mesh directly from Istio itself rather than from Kubernetes. In addition to the validations, I think there's other places in the Kiali server that would be greatly simplified such as fetching the workload info. Rather than needing to correlate or infer information about the mesh from the kube objects, it would be much simpler to get the mesh view from Istio itself.
> 

Well, I see your point and probably there will be some optimization available but today Kiali covers the workloads that are part of the mesh and those that not, as hybrid scenarios are very common during migrations to the mesh.

> A few questions that come to mind wrt using the debug endpoints:
> 
> 1. Are the Istio API endpoints stable? iirc these endpoints are only exposed via localhost on the istiod pod and they begin with `/debug/...`. Can Kiali rely on the responses/endpoints to remain somewhat stable across Istio releases?

No. Those are apis that are available from the debug enpoint of envoy and istiod, it's not a strong api, so we need to keep this during releases. Well, not a big deal, it's something we've been doing for Jaeger for ~3 years so doable.

> 2. Is pod proxying expected to be available in all Kiali deployments?

Not sure if I understand this question, yes, port-forwarding is a mechanism to communicate from the Kiali pod to the Istio pods, so that's expected to be available (similar as the dataplane's sidecar should communicate with the control plane).

> 3. Are these endpoints also available in Maistra?

Yes. Maistra protects some of the administrative ones, but the registry ones should be open (at least that was discussion we had when I brought that topic).

> 4. How scalable are these endpoints? Do they support filtering of some kind like through query params or do they support pagination? What are the response times like for large meshes? Will querying these endpoints frequently affect istiod performance? One nice thing about the kube APIs is that all of this is handled already.

Right, today this information is cached to not overload the istiod, and I think we'll need to keep that pattern to rely in the cache we use. The main benefit is that it implements the all-namespace pattern, so in a single query we have all info in memory.

I think the validations logic will be the first benefit from this approach but once consolidated I'm sure it has potential to save some other queries.

Some but not all, as I commented, there will be always scenarios that we need to keep the current model: workloads that are not part of the mesh, or workloads with problems (i.e. wrong number of pods vs desired, or empty workloads) that is used as part of the health logic.

**Comment by nrfox** [comment]
> Not sure if I understand this question, yes, port-forwarding is a mechanism to communicate from the Kiali pod to the Istio pods, so that's expected to be available (similar as the dataplane's sidecar should communicate with the control plane).

Is the istiod pod always reachable by Kiali? If so, will Kiali always have permissions to proxy into the istiod pod? It sounds like yes to both. It is a requirement for deploying and running Kiali to be able to proxy into the controlplane istiod pod.

**Comment by lucasponce** [comment]
> Is the istiod pod always reachable by Kiali? If so, will Kiali always have permissions to proxy into the istiod pod? It sounds like yes to both. It is a requirement for deploying and running Kiali to be able to proxy into the controlplane istiod pod.

Yes, the istiod pod should be reachable by any pod in the dataplane, so I don't see a major concern here, also it's the same mechanism used by the `istioctl` command to extract the same info. And note that TODAY is a requeriment as this mechanism is being used from long time ago to extract the proxy status info, the approach here is to fetch more information that can be useful for validations, and potentially as the source of the truth for the services and endpoints deployed in the mesh/cluster.

```
kubectl get services -n istio-system -l app=istiod
NAME     TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                                 AGE
istiod   ClusterIP   10.101.26.146   <none>        15010/TCP,15012/TCP,443/TCP,15014/TCP   37m
```

**Comment by hhovsepy** [comment]
@lucasponce about the idea of getting registry endpoints or directly getting any information from RegistryStatus in validation methods such as "no_dest_checker.go's method .hasMatchingService". Is it still actual? .Because in current structure we get all information from registry in "istio_validations" and then pass it to particular validations.

**Comment by lucasponce** [comment]
> @lucasponce about the idea of getting registry endpoints or directly getting any information from RegistryStatus in validation methods such as "no_dest_checker.go's method .hasMatchingService". Is it still actual? .Because in current structure we get all information from registry in "istio_validations" and then pass it to particular validations.

In the initial assestment it looked a good idea but I thought that when the lead of the effort start to work on the topic he/she could decide which is the best approach.

So, @hhovsepy as you are working on the area, you may be in a better position which approach could be most interesting.

Registry endpoints are interesting because they have all labels from the workloads.

But in the other side, they have the limitation that workload clients are not covered and I haven't reviewed if some validation may be affected, probably not.

**Comment by hhovsepy** [comment]
Note: "authorization/NoHostChecker" needs to be modified to use Exported VS and SE.
