### ISSUE TITLE
Improve errors message in the UI

### ISSUE THREAD

**Issue by aljesusg** [kiali/kiali#4385]
Hi, working in another PR I saw an annoying bug, after change the configuration, the error displayed in the kiali login is this one
![error_if_config](https://user-images.githubusercontent.com/3019213/134301830-0e903298-2a79-4b68-9379-3c261e8d4b3f.png)
but if you inspect the networking the error is this one
![error_trace](https://user-images.githubusercontent.com/3019213/134301827-43ce13e8-4ead-4c8d-a335-c6e2c6bc6dcd.png)

So...Maybe we could show this "error parsing" configuration instead that error, on the other hand the error was the prometheus url. Kiali should work without prometheus metrics, we can show some information.

What do you think?

**Comment by nrfox** [comment]
@aljesusg that's frustrating, the error messages should've been made better by: https://github.com/kiali/kiali/issues/3927 and https://github.com/kiali/kiali-ui/pull/2215. Are you running off of an older branch perhaps? If not, then you may have a hit a bug where the improved error message is not displaying.

**Comment by aljesusg** [comment]
mmmm I don't remember the version that I used, let me try to reproduce this with the last one maybe is an old version

**Comment by jshaughn** [comment]
@aljesusg Re-open if you like but I'm going to assume that you hit this using an older version.
