### ISSUE TITLE
Migrate to Docsy for kiali.io theme

### ISSUE THREAD

**Issue by jshaughn** [kiali/kiali#4395]
Epic #4118 

A downside of our current kiali.io custom theme is that we often spend a lot of time on the site itself as opposed to content for the site.   Look at Docsy as a pre-built theme to help us focus on content.

**Comment by jshaughn** [comment]
I've spent some time playing with Docsy and overall I think it could be a viable theme for kiali.io, but it does have pros and cons.  I have a little more investigation to do, especially around versioning, but wanted to get some thoughts down.

**pros**

- it works, it's active and is being used for several popular sites
- it would likely let us focus on content over theme
- it has left and right side navigation
- it does allow for some customization 
- supports .adoc (see cons)

**cons**

- we may need to accept some changes to conform to the landing page structure
  -  or work a bit to maintain our current landing page, this may be easier than I think if someone more suited takes a look at this part.
- Although .adoc files are supported, and I was able to get our current content rendered, there seem to be two big issues:
  - The left nav is currently snapping back to the top when clicked (may or may not be related to adoc)
  - The right nav doesn't work, it seems to require markdown to get populated
- We currently use magnific for the nifty image sizing/expansion, this would be lost unless we do work to migrate that ability.

**current thoughts**

I like the idea of using an external theme like this, and I wouldn't mind it being Docsy.   The biggest pain point would probably be a migration of our current docs from .adoc to .md, in order to get the right nav support.   We could ignore the right nav but it would be a loss.

If we were to migrate I'd suggest we freeze kiali.io submissions and use sort of an all-hands-on-deck approach to the migration.

Here are a couple of screen shots

**Comment by lucasponce** [comment]
> The biggest pain point would probably be a migration of our current docs from .adoc to .md, in order to get the right nav support.

Note that there are converters to .adoc => .md, and Markdown is native in many templates so it would give us flexibility after all.

**Comment by jshaughn** [comment]
A note on doc versioning, Docsy has a mechanism that adds a "Releases" dropdown in the main nav.  It drives off entries in the config.toml that tie a version label to a URL.

**Comment by jshaughn** [comment]
@israel-hdez I think for versioning we can leverage the support in Netlify.  If I understand it correctly, it looks like what we can do is to publish all branches.  I think we could do something like this:

1. create an `archive` branch off of master.  It will serve up all of the old versions because they are all available in the branch.
2. temporarily set Netlify to the `archive` branch
3. merge the `docsy` branch to master (effectively replacing master).
    - in docsy's config.toml we will have defined the versions as needed to refer to the archive branch
4. delete the old, non-publish branches we have
5. create a `latest` branch from master and use it as the default branch
6. configure netlify to publish all branches

So, we end up with kiali.io pointing to `latest`.  The `master` branch becomes the new `staging`.  On each release I guess we need to do a little work, hopefully automated, to do something like:
1. append a new entry to config.toml
2. move `latest` to a versioned branch
3. move master to `latest`

**Comment by jshaughn** [comment]
New Site is Up!
