### ISSUE TITLE
migrate to golang-jwt v3.2.1

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#4396]
we use jwt-go. We should migrate to golang-jwt v3.2.1+

As of today:
```
$ grep -Rl dgrijalva * | grep .go
business/openid_auth.go
config/token.go
handlers/authentication_test.go
handlers/authentication.go
kubernetes/kubetest/mock.go
```

Note, prometheus client 1.9 uses it too - we'll need to upgrade the prom client as well.

```
github.com/prometheus/client_golang@v1.9.0 -> github.com/prometheus/common@v0.15.0
github.com/prometheus/common@v0.15.0 -> github.com/go-kit/kit@v0.10.0
github.com/go-kit/kit@v0.10.0 -> github.com/dgrijalva/jwt-go@v3.2.0+incompatible
```

**Comment by jshaughn** [comment]
This was in reponse [a CVE](https://github.com/kiali/kiali/security/dependabot/go.sum/github.com%2Fdgrijalva%2Fjwt-go/closed) which has been determined to not affect Kiali.  It may still be useful to migrate away from this unmaintained project, but I'm going to remove the Bug label and add it as a Future.

**Comment by jshaughn** [comment]
Closing this as it is superseded by the current work on https://github.com/kiali/kiali/issues/4542.
