### ISSUE TITLE
Kiali console: Loads Empty Graph

### ISSUE THREAD

**Issue by leegin** [kiali/kiali#4399]
Kiali console isn't loading any graph even though there is a ton of traffic flowing in the istio mesh.

![image](https://user-images.githubusercontent.com/18220135/135441540-1589e233-0b24-4284-8362-ddc9ab8a470b.png)

On checking the logs of the kiali pod, I can see the below error.

---
2021-09-30T09:01:43Z ERR configmaps "istio" not found
---

There is no configmap in the istio-system namespace with the name "istio". The same works in a different cluster with the same config running kiali v1.37.0.

![image](https://user-images.githubusercontent.com/18220135/135442373-7009189d-b797-4c5c-9339-37ecab315ab3.png)

**Versions used**
Kiali: v1.40.0
Istio: 1.8.3
Kubernetes flavor and version: GKE v1.20.9-gke.1001

**Comment by lucasponce** [comment]
Note that it seems you are installing Kiali 1.40 with Istio 1.8 which is not a compatible combination:
![image](https://user-images.githubusercontent.com/1662329/135448106-a30e0c90-7aea-4be8-8980-06dc033fc968.png)

[1] https://kiali.io/documentation/latest/installation-guide/#_version_compatibility

**Comment by leegin** [comment]
@lucasponce The other cluster I was talking about is running 1.37.0. I tried to install the same here and it worked. Thanks for directing me to the solution. I appreciate your help.
