### ISSUE TITLE
Add hostAliases field to kiali deployment manifests

### ISSUE THREAD

**Issue by ethernoy** [kiali/kiali#4403]
**Is your feature request related to a problem? Please describe.**

I encountered a problem that DNS server in my working environment are not customizable but I still need to connect to dex server from Kiali with a hostname. I therefore seek to customize the hostalies entries in Kiali deployment to achieve this goal. But I however find that this field is not included in kiali-server helm chart and hence I need to do the customization on deployment level, which is not preferred.

**Describe the solution you'd like**

Add hostalies customization field to kiali-server helm chart and Kiali CRD used by operator. I am happy to submit a PR for this :)

**Comment by lucasponce** [comment]
If it's an optional customization it sounds reasonable.
Perhaps a PR would help to get into the details and check if there could be any issue, so, thanks @ethernoy, feel free to send a PR and we can review it and comment on it.

**Comment by ethernoy** [comment]
> If it's an optional customization it sounds reasonable. Perhaps a PR would help to get into the details and check if there could be any issue, so, thanks @ethernoy, feel free to send a PR and we can review it and comment on it.

Hi, created a PR wrt this issue: https://github.com/kiali/helm-charts/pull/109

**Comment by jmazzitelli** [comment]
The two PRs were reviewed and tested by me - all pass (including the molecule test). I assigned the PRs to QE folks to give them a chance to do a review if they so choose. The PRs are:

* https://github.com/kiali/helm-charts/pull/109
* https://github.com/kiali/kiali-operator/pull/432

Test procedures are documented here: https://github.com/kiali/helm-charts/pull/109#issuecomment-934400281

cc @mattmahoneyrh @pbajjuri20

**Comment by jmazzitelli** [comment]
PRs merged.
