### ISSUE TITLE
kiali is not loading the graph (the server could not find the requested resource (get workloadentries.networking.istio.io))

### ISSUE THREAD

**Issue by anup1384** [kiali/kiali#4406]
I'm getting an issue while opening kiali dashboard, the graph is not loading and in logs it's showing some permission issue.
Error- E1002 16:05:03.869034 1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.1/tools/cache/reflector.go:167: Failed to watch *kubernetes.GenericIstioObject: failed to list *kubernetes.GenericIstioObject: the server could not find the requested resource (get workloadentries.networking.istio.io)

Cluster role permission is there.

λ istioctl version
client version: 1.11.2
control plane version: 1.12-alpha.d70cd277f4f001461324f989de605487894d95ca
data plane version: 1.12-alpha.27e28972ff1b1229ddd603ba8363827a3f99fad3 (3 proxies), 1.12-alpha.d70cd277f4f001461324f989de605487894d95ca (3 proxies)

λ kubectl version --short
Client Version: v1.21.2
Server Version: v1.21.2-eks-0389ca3

**Comment by lucasponce** [comment]
Hi @anup1384, thanks for opening the issue.
Which version of Kiali ?

Can you share how did you install & configure the addons (and Kiali CR/Config) ?

Thx

**Comment by lucasponce** [comment]
Thanks @anup1384 

are there other error for others istio objects ?

```
*kubernetes.GenericIstioObject: failed to list *kubernetes.GenericIstioObject: the server could not find the requested resource (get workloadentries.networking.istio.io
```

That error may indicate that there is an error in the Kube API for the workloadentries, if you haev workloadentries installed as an istio api (which is the usual) typically those errors mean some connectivity issue.

But just I guess I'd need more data to confirm this.

Is this something that you get always, or just with some specific examples / conditions ?

If you could provide us a way to reproduce I can investigate further.

**Comment by prary** [comment]
Hi @lucasponce, I am facing similiar error but on quite a few resources

```
E1108 11:25:15.034273       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.1/tools/cache/reflector.go:167: Failed to watch *v1.Deployment: failed to list *v1.Deployment: deployments.app
s is forbidden: User "system:serviceaccount:bookinfo-dev:kiali-service-account" cannot list resource "deployments" in API group "apps" in the namespace "istio-system"
E1108 11:25:15.541341       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.1/tools/cache/reflector.go:167: Failed to watch *v1.StatefulSet: failed to list *v1.StatefulSet: statefulsets.
apps is forbidden: User "system:serviceaccount:bookinfo-dev:kiali-service-account" cannot list resource "statefulsets" in API group "apps" in the namespace "istio-system"
E1108 11:25:16.261334       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.1/tools/cache/reflector.go:167: Failed to watch *kubernetes.GenericIstioObject: failed to list *kubernetes.Gen
ericIstioObject: envoyfilters.networking.istio.io is forbidden: User "system:serviceaccount:bookinfo-dev:kiali-service-account" cannot list resource "envoyfilters" in API gro
up "networking.istio.io" in the namespace "istio-system"
E1108 11:25:16.541024       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.1/tools/cache/reflector.go:167: Failed to watch *v1.Pod: failed to list *v1.Pod: pods is forbidden: User "syst
em:serviceaccount:bookinfo-dev:kiali-service-account" cannot list resource "pods" in API group "" in the namespace "istio-system"
E1108 11:25:16.642684       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.1/tools/cache/reflector.go:167: Failed to watch *kubernetes.GenericIstioObject: failed to list *kubernetes.Gen
ericIstioObject: authorizationpolicies.security.istio.io is forbidden: User "system:serviceaccount:bookinfo-dev:kiali-service-account" cannot list resource "authorizationpoli
cies" in API group "security.istio.io" in the namespace "istio-system"
E1108 11:25:16.936129       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.1/tools/cache/reflector.go:167: Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: configmaps is for
bidden: User "system:serviceaccount:bookinfo-dev:kiali-service-account" cannot list resource "configmaps" in API group "" in the namespace "istio-system"
E1108 11:25:18.304639       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.1/tools/cache/reflector.go:167: Failed to watch *kubernetes.GenericIstioObject: failed to list *kubernetes.Gen
ericIstioObject: workloadgroups.networking.istio.io is forbidden: User "system:serviceaccount:bookinfo-dev:kiali-service-account" cannot list resource "workloadgroups" in API
 group "networking.istio.io" in the namespace "istio-system"
2021-11-08T11:25:18Z WRN Failure when checking if mesh-id is configured: configmaps "istio-1-11" is forbidden: User "system:serviceaccount:bookinfo-dev:kiali-service-account"
 cannot get resource "configmaps" in API group "" in the namespace "istio-system"
E1108 11:25:19.358636       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.1/tools/cache/reflector.go:167: Failed to watch *kubernetes.GenericIstioObject: failed to list *kubernetes.Gen
ericIstioObject: virtualservices.networking.istio.io is forbidden: User "system:serviceaccount:bookinfo-dev:kiali-service-account" cannot list resource "virtualservices" in A
PI group "networking.istio.io" in the namespace "istio-system"
```

**Comment by jshaughn** [comment]
@prary Are you also seeing a graph failure, or other page failures?  Can you also post your Kiali version, Istio version, and install method?

**Comment by jshaughn** [comment]
This discussion may be relevant: https://github.com/kiali/kiali/discussions/4487

**Comment by jshaughn** [comment]
@prary Did you ever resolve your issue?

**Comment by jshaughn** [comment]
Closing as stale.  Please re-open as needed.

**Comment by prary** [comment]
Hi @jshaughn , Still facing the issue. On Unchecking the istio namespace, not seeing the graph failure.

Kiali version - v1.32.0
Istio Version - v.1.11.2
Install Method- Kiali-Operator v1.32.0

**Comment by jshaughn** [comment]
I'm not sure but you may be hitting https://github.com/kiali/kiali/issues/3896, this was fixed in 1.33.1, I believe.

**Comment by jshaughn** [comment]
Note that for Istio 1.11 the recommended Kiali versions are 1.38 - 1.41.  See https://kiali.io/docs/installation/installation-guide/prerequisites/#service-mesh-compatibility

**Comment by prary** [comment]
Seen thia with 1.36 & 1.40 as well

**Comment by jshaughn** [comment]
@prary OK.  It's unclear to me why the istio namespace is a problem.  Are you using the default, `istio-system`?  From the logs it seems you are, but just checking.

**Comment by jshaughn** [comment]
@prary One more question, what exactly was the graph failure on the UI?  Was there a console message when the failure occurred (f12/console tab) ?
