### ISSUE TITLE
URL parameters not persisted in inbound/outbound metric tabs

### ISSUE THREAD

**Issue by israel-hdez** [kiali/kiali#4420]
As found when testing this PR: https://github.com/kiali/kiali-ui/pull/2253, metric tabs allow setting some options. The URL is changed to reflect the selected options.

However, when switching from the inbound metric tab to the outbound metric tab (or vice-versa), the settings are lost from the URL. Although the UI still works as expected, page bookmarking is inconsistent.

**Comment by lucasponce** [comment]
>  I think we either need to keep the URL correct, or ensure the option reverts to the default when changing tabs.

I think this is the existing behaviour between the tabs.

When the user is located into the tab and set some parameters:
![image](https://user-images.githubusercontent.com/1662329/138085611-de9ce5b0-bc5f-4cec-8cbb-e3473c16d2a3.png)

The URL is correctly updated, so, using the url from other browser:

```
http://localhost:3000/console/namespaces/travel-agency/workloads/cars-v1?tab=in_metrics&rangeDuration=600&refresh=0&avg=true&bylbl=destination_canonical_revision%3Dv1&bylbl=source_workload_namespace%3Dtravel-agency&bylbl=source_canonical_service%3Dtravels&bylbl=source_canonical_revision%3Dv1%2Cv2%2Cv3&bylbl=response_code%3D200%2C500&bylbl=grpc_response_status&bylbl=response_flags&quantiles=0.999+0.99+0.95+0.5
```

will show the user to the same parameters selection:
![image](https://user-images.githubusercontent.com/1662329/138085716-41a2821a-1b55-4db8-8fd7-20b5e4abe138.png)

But when the user moves to other tab, the parameters that belongs to the tab are reset:
![image](https://user-images.githubusercontent.com/1662329/138085798-ce7ad957-c5a4-46b0-a739-017c5134a4d1.png)

And this is expected, only the global parameters from the time controls are supposed to be propagated between tabs.

We have some technical debt across the URLs and certainly I'd like to have this unified, but I don't think it's worth to do it on this bug.

Perhaps a refactoring/maintenance task in the future to put all the parameters used in Redux and treat them globally, today there is a mix per component.

This refactoring may be not 100% trivial, but I guess it's something worth to invest in the future.

**Comment by jshaughn** [comment]
@lucasponce I think there is a misunderstanding here.  Let me give specific reproduction steps to what I think is a problem.

1. Go to a workload detail 
2. Click on Outbound Metrics
3. Enable `Trendlines` checkbox

Checkbox is set and URL params are correct:  `?tab=out_metrics&rangeDuration=300&refresh=15000&trendlines=true`

4. Click on Inbound Metrics

Checkbox is still set and URL params are incorrect:  `?tab=out_metrics&rangeDuration=300&refresh=15000`

So, at this point if you bookmark the URL it will not correctly re-establish the page.  If this still seems fine to you then we can close this issue.   This was not a request for any sort of major change, sticky settings, or full bookmarking.   It just seemed like an inconsistency to me, such that the enabled setting should not carry over between tabs, or the URL should be correct.

**Comment by lucasponce** [comment]
> Click on Inbound Metrics
> Checkbox is still set and URL params are incorrect: ?tab=out_metrics&rangeDuration=300&refresh=15000

Ah, thanks for giving the example, let me see if this is something worth to file like a bug or better to wait if it's better to be done with a major refactor (the metrics component have some technical debt related to how the state is being managed).
