### ISSUE TITLE
Kiali website the section title "latest videos" is misleading 

### ISSUE THREAD

**Issue by abonas** [kiali/kiali#4422]
Epic https://github.com/kiali/kiali/issues/4118

The website homepage has a section "latest videos", but the videos listed there are mixed with older ones so it's not really representing "latest".
For example - Sept2021, then April 2020, then April 2021, then August 2020
I suggest either the videos should be sorted or the title should be renamed.

**Comment by jshaughn** [comment]
This seems fixed in the new site.
