### ISSUE TITLE
validation: authorization policy validation, principals not found

### ISSUE THREAD

**Issue by shireenf-ibm** [kiali/kiali#4424]
Add validation to AuthPolicy object. check the existence of peers listed into  **principals** field for each [Rule.From.Source](https://istio.io/latest/docs/reference/config/security/authorization-policy/#Sourcehttps://istio.io/latest/docs/reference/config/security/authorization-policy/#Source)

**Comment by shireenf-ibm** [comment]
> 
> 
> @shireenf-ibm hi! I agree with lucasponce with the registry in place this might be easier.
> 
> however, where did you think of getting the principals? Listing all the service accounts? Is there a way to get the all complete list of possible principles?

Hi, 
The idea is to find Matching services (listing services accounts)

**Comment by jshaughn** [comment]
@lucasponce , The registry work is there, is this something we should revisit?
