### ISSUE TITLE
Broken scale in Overview page Y axis

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#4425]
Happens on Kiali master on Istio 1.11.3.

The scale of Y axis on Overview page.

![Screenshot from 2021-10-15 11-56-19](https://user-images.githubusercontent.com/604313/137470877-656a17fe-cf08-4545-b2d4-4b83bb92ad87.png)

**Comment by jshaughn** [comment]
I'm not sure I understand but it's quite possible for an existing time-series to have 0 requests for the time period and reflect a request count rate of 0, but still have many previous requests.

**Comment by leandroberetta** [comment]
@jshaughn thanks, yes, I guess I had some confussion around that, now it's clear.

The fix I'm proposing is to say "No incoming traffic" when requests_count = 0 for the entire query, with that, we avoid the strange ticks values very close to 0, and also don't show a graph with just 0 dots.
