### ISSUE TITLE
Refactor business/services.go to be the API to fetch services information

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#4426]
This is a preliminary task in the context of the discussions in:
https://github.com/kiali/kiali/pull/4389
https://github.com/kiali/kiali/issues/4410

and also needed for 
https://github.com/kiali/kiali/issues/4382

The goal of this task is to introduce a minor refactoring in the business package: today validation, health, workloads logic call directly to the kubernetes api to fetch the service information, the proposed change is that these calls use the business.SvcService instead. That will consolidate the check of the cache for services in a single place (business/services.go) and it will help to have the business package better structured to introduce new changes as use the Istio registry to build the Service lists.

From feature/user point perspective, it will be transparent.

**Comment by xeviknal** [comment]
I like @nrfox idea and I think I commented that before. It hides how the cache implementation is for the developer. Pretty elegant and reducing casuistics (if/elses) in many places in the business logic.

@lucasponce you are right that the business logic is the one in charge of chosing which backend should build the response with (cache, no-cache). However, wouldn't it work to defaulty use the `CachingClient` and puntually use the ClientInterface when cache was not needed?

For example,

```
type CachingClient struct {
	kubernetes.ClientInterface
}

func (cc *CachingClient) GetPods(namespace, labels string) ([]core_v1.Pod, error) {
	if IsNamespaceCached(namespace) {
		return kialiCache.GetPods(namespace, labels)
	}
	return cc.ClientInterface.GetPods(namespace, labels)
}

type IstioValidationsService struct {
	k8s           CachingClient
	businessLayer *Layer
}

// business/istio_validations.go -> using cache (default)
func (in *IstioValidationsService) fetchPods(rValue *[]core_v1.Pod, namespace string, errChan chan error, wg *sync.WaitGroup) {
	defer wg.Done()
	if len(errChan) == 0 {
		// k8s defaults to cache.
		pods, err := in.k8s.GetPods(namespace, "")
		if err != nil {
			select {
			case errChan <- err:
			default:
			}
		} else {
			*rValue = pods
		}
	}
}

// Not using cache for scenarios where you manually want to avoid it because of race conditions or relying in real-time data
func (in *IstioValidationsService) fetchUncachedPods(rValue *[]core_v1.Pod, namespace string, errChan chan error, wg *sync.WaitGroup) {
	defer wg.Done()
	if len(errChan) == 0 {
		// it bypasses the cache, manually.
		pods, err := in.k8s.ClientInterface.GetPods(namespace, "")
		if err != nil {
			select {
			case errChan <- err:
			default:
			}
		} else {
			*rValue = pods
		}
	}
}
```

This way, you clean out all the if-else's in the code. In general, Kiali wants to use cached data. There are few places in the project where we rely on non-cached information. In those places, you still have access to the in.k8s.ClientInterface to access to non-cached information.

I understand that we want to tend to one single source of true via using the business services, right? If one service in the business wants to fetch services, it should call to the ServiceService to get them; if another one wants the namespaces, it should call the NamespaceService; for workloads, fetch them from the WorkloadService; and so on. I am thinking, and perhaps I miss something, that this enhance doesn't prevent to keep going to that direction.

**Comment by lucasponce** [comment]
Closed by https://github.com/kiali/kiali/pull/4456
