### ISSUE TITLE
[docs] documentation issue link is wrong

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#4427]
In the new docsy website, the right menu has an item "Create documentation issue" that takes you to https://github.com/kiali/kiali.io/issues/new?title=Quick%20Start which is a 404 - we do not support issues in that kiali.io project.

We need to either have it refer to the kiali repo issues page or hide that link.

**Comment by jshaughn** [comment]
OK, so we've decided to open kiali/kiali.io/issues, but we'd actually have preferred to keep all of our issues consolidated.  As such, I've created a docsy issue asking for the configuration option we need:

https://github.com/google/docsy/issues/731

But, for now the 404 issue is resolved.  If the issue above is resolved, and we update, then we could make a change back to consolidated issues.
