### ISSUE TITLE
Issue on Kiali UI, need to refresh page 

### ISSUE THREAD

**Issue by morvencao** [kiali/kiali#443]
**General remarks**

**Describe the bug**
With latest Kiali v0.6.0 combine d with Istio 1.0.0, always get message `Sorry, there was a problem. Try a refresh or navigate to a different page.` when first login the UI.
Also find some error message in chrome console:
```
main.504d399b.js:1 TypeError: Cannot read property 'split' of undefined
...
TypeError: Cannot read property 'map' of undefined
...
```

After a refresh on the page, it will be all right.

For UI issues please also add a screenshot that shows the issue.
![image](https://user-images.githubusercontent.com/5468682/44382214-ae938f80-a546-11e8-9272-2a2eb78ea275.png)

**Versions used**
Kiali
kiali-ui 0.2.10 (d706a7b93d55c8f9089bf65c20359dd7e5b2f67f)
kiali v0.6.0 (23643f7f6a099041692205ba5affa7b3a91cabdd)
Components
Istio 1.0.0
Prometheus 2.3.1
Kubernetes v1.11.1+icp-ee

**To Reproduce**
1. Login Kiali UI with google chrome.
2. You will see the mesage: `Sorry, there was a problem. Try a refresh or navigate to a different page.`
3. Open chrome console, see error messages.

**Expected behavior**
We should see complete working graph without refreshing page after logging int the Kiali UI.

**Comment by morvencao** [comment]
Also seems that `jaeger` in `Kiali` still can't be accessed:

This should be related to https://github.com/kiali/kiali/issues/222

**Comment by morvencao** [comment]
`jaeger` in `kiali` is still not working:
`jaeger` in `kiali` is still not working:
![image](https://user-images.githubusercontent.com/5468682/44382642-53fb3300-a548-11e8-9f15-df818405449f.png)

This shoud be related to https://github.com/kiali/kiali/issues/222

**Comment by emmayang** [comment]
@morvencao I found your `kiali-ui` version from "about" is quite old, and I deployed mine last week and the version number looks like: 

kiali-ui 0.6.0 (d648775e7a4378efdbc7da59d413847038578d4b)
kiali v0.5.1-SNAPSHOT (5d782cc08c1d03859496bd31dd2ec58ae195a123)

Did you try remove the pod and redeploy?

**Comment by morvencao** [comment]
@emmayang It's weird, community has just released `v0.6.0` last Friday and after additional testing also tagged it as `istio-release-1.0`
I have that version in my env.

**Comment by emmayang** [comment]
@morvencao did redeploy fixed your problem?

**Comment by morvencao** [comment]
@emmayang Yes, thanks. Removing the pod works for me. It's maybe just browser cache issue?
