### ISSUE TITLE
Make "Control Plane" explicit in Kiali

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#4435]
Default configuration in Kiali treat control plane namespace as any other namespace in the mesh [1].
In the other side, Kiali has a Mesh page to describe the cluster configuration in the multi-cluster active-active scenario.

Also, the "control plane" state is implicit and Kiali shows this information in the masthead.

There are an increasing number of scenarios that would benefit to have a page listing the control planes (istiod instances), for example:

- In a single mesh, a user may have a canary deployment with version A and version B, some workloads pointing to A and other workloads to B, today we can't show that information.
- Every istiod may have state and specific telemetry, today users need to navigate into the istio-system (or the proper namespace) and browse into the workload, I think that a mesh would help to consolidate this information as well.
- The state of the control plane today is showed in the masthead, but when there are a different situation, the user would benefit to see that information under a "control plane" info, also, in canary deployments situations, this page can help to show what is the progress of the migration from one version to another (i.e. 60% of the workloads point to the control plane A, 40% point to the B).
- This page can be foundation to better support federated and/or multicluster scenarios where the user would like to see the control planes (again, here control plane means the istiod instances that form a mesh) that have visibility.

This epic is to discuss the scope and next steps for this effort, ideally it would be nice to have an iterative progress and develop the ideas discussed on https://github.com/kiali/kiali/discussions/4081#discussioncomment-866773 that can be moved into actionable tasks.

[1] There is a minor exception to this sentence, the specific control plane views defined in Grafana are linked into the Overview page:

![image](https://user-images.githubusercontent.com/1662329/137736322-bc81f7a6-f381-4b96-92ab-0587aa0dee3a.png)

**Comment by jshaughn** [comment]
For the sprint this is still just for discussion and research, not an impl task at this time.  How does this play with the new control plane card on Overview.

**Comment by leandroberetta** [comment]
I think this epic has lots of multi cluster topics that needs to be defined, but there is some point where we can work in the near future:

> * The state of the control plane today is showed in the masthead, but when there are a different situation, the user would benefit to see that information under a "control plane" info, also, in canary deployments situations, this page can help to show what is the progress of the migration from one version to another (i.e. 60% of the workloads point to the control plane A, 40% point to the B).

We can look for this information in the masthead and move it into the new control plane card. The info around canary installations is also a good one.

**Comment by leandroberetta** [comment]
After a series of sessions with @israel-hdez where we discuss the next steps for this epic, we thought that the following issues should be ready to implement without entering on the on going discussion about multi cluster support but also pointing that these issues are aligned for the future issues regarding this epic:

- Indicate the status of the canary upgrade in the control plane card
  - Indicate the existence of the canary and the status of it
    - Simple indication if it's ready (pod status?)
- Indicate the percentage of workloads that still in the stable version and the percentage of workloads that already migrated
- Migrate the control plane related information from the masthead to the control plane card
  - These information can be showed with color coded icons
    - For example, if Prometheus is in a bad state, show its icon red, otherwise green (we should look for icons for Prometheus, Grafana, Jaeger, gateways)

After this issues are resolved, we should have a good and complete card for the control plane, that eventually can be replicated for multiple controlplanes and moved to another section (for example the mesh section, or simply the "Control Planes" section) when we decide to move forward to mc support.

**Comment by jshaughn** [comment]
@israel-hdez @leandroberetta , I like all of these ideas.   More insight into the state of a canary update of the control plane should prove valuable.  Migrating non-standalone-kiali information out of the masthead is more useful for Kiosk mode (although I do wonder if we should additionally decorate the "Overview" menu item with something like today's masthead indicator, so that no matter where you are you may see an immediate reflection of an infra problem).

**Comment by israel-hdez** [comment]
I've created the following subtasks based in the previous comment:
* #5524
* #5525

**Comment by israel-hdez** [comment]
Just to add, these are some points that I just remembered we touched, yet aren't very well defined:

* When a canary upgrade is in progress, somehow show in the graph which workloads are still in the old version, and which ones are migrated.
* If _ambient_ is active, show the status of the ztunnels/waypoints.

Commenting to not forget these.

**Comment by israel-hdez** [comment]
Removing from project until we can revisit.

**Comment by jshaughn** [comment]
Closing as the original work is completed.  Further enhancements for canary upgrades, or for Ambient support, can be treated with new issues.
