### ISSUE TITLE
GH workflow build - CI gives a green light even when the gofmt says in not well formated

### ISSUE THREAD

**Issue by xeviknal** [kiali/kiali#4442]
Is it only me that have this bunch of modification after running the make format command (gofmt) in master?

I see this problem for example:

Pipeline:
https://github.com/kiali/kiali/runs/3938401801?check_suite_focus=true#step:6:1

PR with unsorted imports:
https://github.com/kiali/kiali/pull/4439/files#diff-3b471dbe35509f564d7f4429405e67504bc12fdd1d69b374077f7090519f1550R9

**Comment by nrfox** [comment]
It looks like  `gofmt` will sort the imports within the existing groups but won't change the grouping. `goimports` will do everything that `gofmt` does in addition to grouping the imports. Something like `goimports -format-only -local github.com/kiali/kiali` might be more what we're looking for.

From `goimports --help`:
```
  -format-only
        if true, don't fix imports and only format. In this mode, goimports is effectively gofmt, with the addition that imports are grouped into sections.
  -local string
        put imports beginning with this string after 3rd-party packages; comma-separated list
```

**Comment by nrfox** [comment]
@xeviknal @lucasponce have a look at the output of: https://github.com/kiali/kiali/runs/4178833212?check_suite_focus=true. It seems like this closer to the import grouping that we want?
