### ISSUE TITLE
KIA1105: Virtual service routes may not point to any subset

### ISSUE THREAD

**Issue by xeviknal** [kiali/kiali#4458]
In Virtual services the subset destination is not mandatory. You might be sending traffic to different services without specifiying any subset (labeling). 

Therefore, `KIA1105` is not accurate enough and throws a warning. The validation it should include the pair of host+subset instead of only considering the subset.

See one example:
![Screenshot of Kiali Console (29)](https://user-images.githubusercontent.com/613814/139106377-d0596451-f8a3-4885-b1b7-409cec745ca0.png)

Here's the response. The validation points to a field that doesn't exist.
![Screenshot of localhost_20001_kiali_api_namespaces_default_istio_virtualservices_rollouts-demo-vsvc2_validate=true](https://user-images.githubusercontent.com/613814/139106342-0e30c6e7-9031-40ad-84b4-8669b2b93e5c.png)

**Comment by lucasponce** [comment]
Closed by https://github.com/kiali/kiali/pull/4520
