### ISSUE TITLE
[Feature Request] Support mounting existing secret into Kiali Pod

### ISSUE THREAD

**Issue by ethernoy** [kiali/kiali#4468]
From time to time we may need to mount existing K8S secret into Kiali pod for various reasons. For example, I need to mount a secret that contains a .crt file, which Kiali will use as the ca_file of external tracing service endpoint. Is it possible to add a field like `.deployment.secrets` to allow Kiali to mount existing secret into deployment?

**Comment by jmazzitelli** [comment]
@ethernoy Nothing exists today to be able to inject custom secrets into the deployment. Can you provide some details? How would you expect this custom secret to be used by Kiali?

**Comment by ethernoy** [comment]
@jmazzitelli 

A possible use case is we inject a `tls.crt` file into Kiali from an existing secret, then provide it in this [line](https://github.com/kiali/kiali-operator/blob/bf60c14154a60ad87c76a907ff1b389813ddf488/deploy/kiali/kiali_cr.yaml#L690) to enable Kiali to trust a tracing service endpoint.

**Comment by ethernoy** [comment]
@jmazzitelli yes this is definitely solving my issue! I will try your workaround ASAP, but I believe it can only serve one custom secret. In my ideal configuration, Kiali needs 3 secrets, namely
- a ca secret for connecting to remote tracing service
- a certificate with key for enabling HTTPS on Kiali. This secret is managed by cert-manager
- a ca secret for connecting to Dex (for enabling OpenID authn)

I believe this can only be achieved by the enhancement you raised.

**Comment by jshaughn** [comment]
Adding to sprint backlog to help with this user need.

**Comment by jmazzitelli** [comment]
work being done in these PRs... rough manual testing shows it working, but I'm trying to get an automated test to pass. PRs are still in draft mode.
* https://github.com/kiali/helm-charts/pull/115
* https://github.com/kiali/kiali-operator/pull/444

**Comment by ethernoy** [comment]
> @ethernoy the PRs are ready. Could you test it out to make sure this actually does what you need it to do? You don't have to test both PRs - both are doing the same exact thing to the Kiali Deployment - mounting additonal secrets that you have created. So it might be easiest just to test the server helm chart PR: [kiali/helm-charts#115](https://github.com/kiali/helm-charts/pull/115) but feel free to test the operator if you so choose.
> 
> I want to make sure you can use this to mount a secret AND use it for the other cert settings in the Kiali config. I did not fully test that - was assuming you will be able to do that since you have all the infrastructure in place (all the cert and secret generation stuff).
> 
> To test:
> 
> 1. Pull the PR: [support mounting custom secrets in the kiali pod helm-charts#115](https://github.com/kiali/helm-charts/pull/115)
> 2. Run `make clean build-helm-charts`
> 3. Install Kiali using the server helm chart. Example (note that because you are using a local snapshot of the helm chart, you have to explicit give a image_version with a tag that is in quay.io - `latest` should work):
> 
> ```
> helm install -n istio-system kiali-server _output/charts/kiali-server-*-SNAPSHOT.tgz \
>    --set deployment.image_version=latest \
>    --set deployment.custom_secrets[0].name=your-first-secret-name \
>    --set deployment.custom_secrets[0].mount=/where-you-want-the-first-secret-mounted \
>    --set deployment.custom_secrets[1].name=your-second-secret-name \
>    --set deployment.custom_secrets[1].mount=/where-you-want-the-second-secret-mounted \
> ```
> 
> Obviously pass as many `--set` options for as many custom_secrets[*] as you need (or use a values file - however you want to install the server via this helm chart). You should also set the proper settings for your external_services.tracing so the certs are used successfully.
> 
> Please put your review comments and results in the PR or in this issue.
> 
> Thanks.

Great to hear! Will test it as soon as possible, thx so much

**Comment by jmazzitelli** [comment]
> Great to hear! Will test it as soon as possible, thx so much

@ethernoy FYI: this Friday we will release the next version of Kiali. If you can test and verify the correctness of this stuff for your use-case before Friday, we will be able to merge this and get it in that next release (which will be 1.43.0).

**Comment by ethernoy** [comment]
> > Great to hear! Will test it as soon as possible, thx so much
> 
> @ethernoy FYI: this Friday we will release the next version of Kiali. If you can test and verify the correctness of this stuff for your use-case before Friday, we will be able to merge this and get it in that next release (which will be 1.43.0).

Just test with the following setting
```
 jaeger-ca.crt
       │
       │
       │
   ┌───▼───┐ HTTPS ┌───────────────┐ HTTP ┌──────┐
   │ Kiali ├───────►HAProxy (HTTPS)├──────►Jaeger│
   └───────┘       └───────────────┘      └──────┘
```
It works as expected:
![image](https://user-images.githubusercontent.com/15870761/140848971-d081293b-ed96-449e-b3fb-51ec7c133edd.png)

**Comment by jmazzitelli** [comment]
> It works as expected:

@ethernoy What does your Kiali CR look like when you tested? Specifically, the `deployment.custom_secrets` and `external_services.tracing.auth` settings? I want to make sure they are what I think they would be.

**Comment by ethernoy** [comment]
@jmazzitelli I tested with kiali-server. Just updated the comment above with my values.yaml.

**Comment by jmazzitelli** [comment]
> Just updated the comment above with my values.yaml.

OK, great. That's how I was hoping it would work for you. Things look good then to get this in for the upcoming release.
