### ISSUE TITLE
same name deploy

### ISSUE THREAD

**Issue by willgo-cn** [kiali/kiali#4476]
i hava same name deploy, one is deployment, one is statefulset, but i just find the deployment in the kiali ui workloads tabs

Kiali UI: 1.24.3
Kiali Server:  v1.24.5.redhat1

**Comment by lucasponce** [comment]
Hi @willgo-cn thanks for opening an issue, but could you describe in detail the problem you are seeing ?

I guess you mean that you have a "Deployment" with "workload-A" name and also a "StatefulSet" with same "workload-A" name, isn't it ?

Is that a valid scenario ?

Take also into consideration that Istio telemetry is stored per "workload" so, even if that's a valid kubernetes deployment, telemetry is mixed in prometheus for both controllers and probably the data you're seeing can't be distinguished between them.

Could you add more details from your scenario ?

Thanks

**Comment by jshaughn** [comment]
@willgo-cn , without more information there isn't much we can do here and will be forced to close the issue.

**Comment by jshaughn** [comment]
Please re-open as you see fit.
