### ISSUE TITLE
Kiali Documentation link from Master Head seems broken

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#4478]
![image](https://user-images.githubusercontent.com/1662329/140304888-268cdb0c-dfa6-4e06-b0ab-aca929534edb.png)

Redirects to:

![image](https://user-images.githubusercontent.com/1662329/140304858-37c38c0e-0b06-4337-ad32-6a5eaad15b31.png)

**Comment by jmazzitelli** [comment]
that link should now just go to https://kiali.io
