### ISSUE TITLE
Can not run on arm

### ISSUE THREAD

**Issue by zackzhangkai** [kiali/kiali#4483]
Same problem as this  https://github.com/kiali/kiali/issues/3561 

Image operator v1.41.0  v1.34.1 same errors.

**Comment by jmazzitelli** [comment]
I thought we had ARM64 already working. At the moment, we don't have ARM64 hardware to test - community contributions welcome to address this.

**Comment by whoever42** [comment]
a dependency - openshift/origin-ansible-operator seems to have only x86_64 builds
https://github.com/kiali/kiali-operator/blob/17076a7d038d8a84f8d6dd66fe6d8dda0af6f377/build/Dockerfile#L2

**Comment by jmazzitelli** [comment]
Looks like you need to request multi-arch support for this: https://quay.io/repository/openshift/origin-ansible-operator?tab=tags
The Kiali team doesn't have control over the production of that image.

**Comment by whoever42** [comment]
Well, Kiala previously used quay.io/operator-framework/ansible-operator instead (Kiala v1.31 being the last properly running arm64 image).
Cloned the Kiala master.git, switched openshift to operator-framework:v1.4 in Dockerfile and it built Kiala image without errors.

**Comment by jmazzitelli** [comment]
Yes, but we want to use openshift/origin-ansible-operator.

You can fork and build with the operator-framework for now if you'd like. I'm trying to track down those responsible for the openshift/origin image to get them to fix it - I haven't found an answer yet why it is like that.

**Comment by jmazzitelli** [comment]
I'm putting this on the backlog and assigned it to me - I'm currently researching how to get that dependent image fixed, if possible.

**Comment by jmazzitelli** [comment]
https://issues.redhat.com/browse/DPTP-2630

**Comment by jmazzitelli** [comment]
The `quay.io/openshift/origin-ansible-operator` image does not support multiarch and will not support it any time soon. So we need to abandon its use for now and go back to using the other community image `quay.io/operator-framework/ansible-operator`.

To know the version of the operator-framework that is packaged in the origin-ansible-operator we were using (tag=`4.8`), you can just run the image via `podman run`:

```
podman run -it --rm quay.io/openshift/origin-ansible-operator:4.8
```

This results in:
```
{"level":"info","ts":1637613409.5255513,"logger":"cmd","msg":"Version","Go Version":"go1.16.6","GOOS":"linux","GOARCH":"amd64","ansible-operator":"v1.8.2-ocp","commit":"b35596fa3f0bb432063443ece7d12d71fb43ebdf"}
...
```

So we can see this is based on v1.8.2 of the operator SDK. Therefore, we will want to revert back to `quay.io/operator-framework/ansible-operator:v1.8.2`

**Comment by jmazzitelli** [comment]
If we want to move to the SDK found in the 4.9 origin image, that would be v1.10.1:

```
$ podman run -it --rm quay.io/openshift/origin-ansible-operator:4.9

{"level":"info","ts":1637614864.1394799,"logger":"cmd","msg":"Version","Go Version":"go1.16.6","GOOS":"linux","GOARCH":"amd64","ansible-operator":"v1.10.1-ocp","commit":"972fd59bb3a4cdb2e5102fc37fc3afa32f6c066f"}
```

**Comment by jmazzitelli** [comment]
Reverted back to the operator-framework image since it supports multiarch and the other image (as of today) does not.
