### ISSUE TITLE
[operator] implement best practice guidelines to support multi-tenant installations

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#4485]
I believe these are the tasks needed in order to complete this issue:

- [x] support custom labels on the kiali route
- [x] ship with resource requests on the operator Deployment
- [x] ship with resource request defaults on the kiali pod

_NOTE: We are going to want to backport these changes to the 1.36 playbook and branch._

Running operators in multi-tenant OpenShift clusters - there are best practice guidelines to include these aspects:

Here's a distilled version of this:
* if your operator creates `Routes` it should allow users to specify custom labels so they can employ router sharding (very popular in larger multi-tenant clusters)
** WE NEED TO ADD THIS FEATURE TO THE OPERATOR and SERVER HELM CHART

* if your operator creates `NetworkPolicies` it should be possible to disable that or at least not create "accept traffic from everywhere" policies
** I don't think we create NetworkPolicies (we rely on OSSM to create those when needed), but we should confirm.

* your operator should ship with resource requests on its own `Deployment` (enables ResourceQuotas to be used)
** We support the user providing resource requests on the Kiali server, but not the operator itself. WE NEED TO ADD THIS ON THE OPERATOR ITSELF

* your operator should apply at least resource requests on all `Pods` it creates (enables ResourceQuotas and HorizontalPodAutoscalers to be used)
** We support being able to add HPAs and resources on the Kiali server. Therefore I think we support this already. But I do not think we set this by default on Kiali pods - I believe we need some defaults.

===

### Create resource requests

* for your operator's own `Pods`
* for `Pods` your operator creates / manages

The reasoning behind this is, to allow `ResourceQuota` configuration ([docs](https://kubernetes.io/docs/concepts/policy/resource-quotas/)) to work. This is something that every production cluster will follow as a best practice, to prevents tenants from being able to consume all resources on the cluster and block other worklaods from being scheduled. `ResourceQuota` in a namespace will cause all pods without `requests` ([docs](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#requests-and-limits)) for CPU and RAM to be rejected.

Therefore, **always ship your operator `Deployment` with resource requests**. 

The concepts above also apply to tenant workloads which are managed by your operator. Cluster administrators will typically set a `ResourceQuota` for each tenant's namespace / project as part of the onboarding. If your operator creates `Pods` inside tenant namespace which do not specify at least resource requests for CPU and RAM, those pods will fail to schedule and tenants will not be able to use your operator. Therefore your operator should **always apply at least resource requests for CPU and RAM** for `Pods` that it creates as part of reconcilication. Ideally your operator also applies limits to those `Pods`. Resource requests are also needed for horizontal pod autoscaling to work ([docs](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#support-for-resource-metrics)).

### If your operator creates `Route` objects

* allow users to supply custom labels to `Routes` to allow for router sharding

This is a popular configuration option for dense multi-tenant clusters, where several `IngressController` configuration have been deployed. The goal is to split ingress traffic from e.g. production and development, ending up on different routers. These routers are `Pods` inside a `Deployment` that carry a specific label to receive traffic from certain ingress controllers. The label is applied at the `Route` level and there is no pre-defined convention here, so users set these custom labels in accordance to how they configured their `IngressController` instances. See here for our [docs](https://docs.openshift.com/container-platform/4.9/networking/ingress-operator.html#nw-ingress-sharding-route-labels_configuring-ingress) and this [blog](https://rcarrata.com/openshift/ocp4_route_sharding/) for an end-to-end example. **Your operator should allow the user to specify custom labels for any `Route` that it manages**.

### If your operator creates `NetworkPolicy` objects

* apply fine-grained network policies to the extent that is required for your managed application to function properly
* apply fine-grained network policies to enable your managed application internal components to communicate among each other
* allow users to disable network policy management (your operator doesn't deploy `NetworkPolicy` instances at all)
* do not create "allow traffic from everywhere in the cluster" type policies

Usage of `NetworkPolicy` ([docs](https://docs.openshift.com/container-platform/4.9/networking/network_policy/about-network-policy.html)) is popular in multi-tenant cluster to provide an extra layer of segregation among tenants within the OpenShift SDN. Customers typically costumize this extensively with goal to disallow network traffic among among unrelated tenants. Operators that deploy a "accept all traffic from anywhere in the cluster" style policy, are creating an obstacle in pursuing this goal, especially if it cannot be disabled. In security-conscious environments policies like these are not allowed in production. In such cases your operator should minimally **have the option to prevent `NetworkPolicy` objects from being created** and leave these to the user. In more advanced cases, your operator should create `NetworkPolicy` configurations that follow the least-privilege principle as well implement deny-all-allow-some rules.

**Comment by jmazzitelli** [comment]
See: https://github.com/kubernetes-sigs/kubebuilder/pull/2368/files

Based on that and the best practices suggestions, we should default the operator with:

```yaml
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
```

**Comment by jmazzitelli** [comment]
I tested the federation demo with Kiali 1.36.6 on IBM Cloud OpenShift 4.8 and the operator does spike memory usage during reconciliation to 400MB. It drops down when not reconciling. The operator will reconcile one CR at a time (see https://github.com/kiali/kiali-operator/blob/v1.43.0/manifests/kiali-ossm/manifests/kiali.clusterserviceversion.yaml#L234-L239 where we do not define `max-worker` and its default is 1: https://v0-18-x.sdk.operatorframework.io/docs/ansible/reference/advanced_options/#max-workers).

So perhaps we should create a memory limit of 500MB to be on the safe side.

The Kiali Server pod in that same install never gets above 40MB but I still want to do some more testing because I'm not sure but I think the number of namespaces in the mesh may dictate how much memory the server pod might need (for generating large graphs or validating config across the mesh for example).

**Comment by jmazzitelli** [comment]
After learning a few things, I'm going to not set the resources.memory.limits for the operator. The operator will, by default, have a max-workers equal to the number of CPUs. That means the number of concurrent CRs it can reconcile will be different depending on the cluster and how many CPUs there are. So the max memory usage will be different based on the number of CPUs.

If, in the future, we wish to add memory limits to the operator, do this:

HELM CHARTS REPO:

```diff
$ git diff --cached 
diff --git a/kiali-operator/values.yaml b/kiali-operator/values.yaml
index 53914eb..a0f2878 100644
--- a/kiali-operator/values.yaml
+++ b/kiali-operator/values.yaml
@@ -17,6 +17,8 @@ resources:
   requests:
     cpu: "10m"
     memory: "64Mi"
+  limits:
+    memory: "1Gi"
 affinity: {}
 replicaCount: 1
 priorityClassName: ""
```

OPERATOR REPO:

Update the manifests:
* `manifests/kiali-{upstream,community)/x.y.z/manifests/kiali.vx.y.z.clusterserviceversion.yaml` where x.y.z is the version where the change should be made 
* `manifests/kiali-ossm/manifests/kiali.clusterserviceversion.yaml`

so they are changed like this:

```yaml
@@ -243,6 +243,8 @@ spec:
                   requests:
                     cpu: "10m"
                     memory: "64Mi"
+                  limits:
+                    memory: "1Gi"
               volumes:
               - name: runner
                 emptyDir: {}
```
```

**Comment by jmazzitelli** [comment]
I'm going to set the Kiali server pod with a max limit of 1Gi. If we go over that, the cluster will kill the server pod and restart it. I don't think we need close to 1Gi, but we can always lower it later.

**Comment by jmazzitelli** [comment]
@jshaughn I put this down as "backport/1.36" but maybe we don't need to backport these changes. Thoughts?

**Comment by jshaughn** [comment]
@jmazzitelli , We don't need to backport new features and I'd say this is probably not a bug fix, at least not until someone files a complaint.  So, for now I'd say we just roll forward and let this show up in the next downstream operator.  If that sounds right to you then remove the label.  If anyone disagrees we can add it back.
