### ISSUE TITLE
k8s service appProtocol is no reflected in config checks

### ISSUE THREAD

**Issue by frankconrad** [kiali/kiali#4486]
k8s service appProtocol is no reflected in config checks (KIA0601)

For this nned to add the support of service appProtocol in config checks.
To match istio support there.

KIA0601 is related to IST0118.

**Comment by szelenka** [comment]
I'm also running into this issue. Where the services have appProtocol defined, according to Istio's documentation:
https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/#explicit-protocol-selection

But Kiali marks the config as invalid:
https://kiali.io/docs/features/validations/#kia0601---port-name-must-follow-protocol-suffix-form

The Istio services still work, it's just an oversight in the Kiali checks AFAIK

**Comment by nrfox** [comment]
> The Istio services still work, it's just an oversight in the Kiali checks AFAIK

Agreed I'll let @xeviknal weigh in but it looks like the service validation checks don't currently support the `appProtocol` field and just look at the suffix.

**Comment by hhovsepy** [comment]
This issue is resolved in Kiali v1.44.
