### ISSUE TITLE
Error fetching OpenID provider metadata "failed to create http client to fetch OpenId Metadata: supplied OpenId CA file cannot be parsed"

### ISSUE THREAD

**Issue by dirkckau** [kiali/kiali#4492]
Hi all, 

Similar to this [issue](https://github.com/kiali/kiali/issues/2978), I am stuck with the openID error and I could find any relevant samples in the Internet. 

error":"Error fetching OpenID provider metadata.","detail":"failed to create http client to fetch OpenId Metadata: supplied OpenId CA file cannot be parsed"

From the official documentation, it states that the below configMap is required. 

        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: kiali-cabundle
          namespace: istio-system # This is Kiali's install namespace
        data:
          openid-server-ca.crt: <the public component of your CA root certificate encoded in base64>

However, no matter how I amend the data, it can't be parsed. 
Is it "base64" encoding the .pem file? 

Any sample that can someone share as reference to me? 
What is **<the public component of your CA root certificate encoded in base64>** ?

Thanks a lot. 
Dirk

**Comment by dirkckau** [comment]
what is the public component of your CA root certificate encoded in base64

**Comment by israel-hdez** [comment]
> However, no matter how I amend the data, it can't be parsed.
> Is it "base64" encoding the .pem file?

Yes. Probably, run a command like the following in your terminal and copy-paste the resulting string to the ConfigMap yaml, then apply it with `kubectl apply`.

```
cat your_pem_file | base64 -w0
```

**Comment by dirkckau** [comment]
Is there any sample file that can share to us? 
We want to confirm the format. 

From my side, i always go the error:"Error fetching OpenID provider metadata." and hence that i cannot proceed my development on Kiali.

Here attached with my ca-bundle configMap file FYI. 
[kiali-cabundle.zip](https://github.com/kiali/kiali/files/7586246/kiali-cabundle.zip)


Or do we need any custom overwrite in the values.yaml to specify the openid configMap that we add? 
Below with our values.yaml FYI. (hashed some sensitive info)

_____________________________________________________________

# Default values for istio.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  cluster:
    domain: bk1.dev0.paas.xxx.com

kiali-server:
  nameOverride: "kiali"
  fullnameOverride: "kiali"
  istio_namespace: "istio-system"
  deployment:
    readinessProbe:
      httpGet:
        path: /svc/kiali/healthz
    livenessProbe:
      httpGet:
        path: /svc/kiali/healthz
    accessible_namespaces:
    - "**"
    image_name: xxx.com/kiali
    image_pull_secrets:
    - secretName
    image_version: v1.39.0
    # ingress_enabled: false
    # logger:
    #   log_level: "info"
    replicas: 2
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 400m
        memory: 1Gi
    secret_name: "kiali"
    service_type: "ClusterIP"
    version_label: v1.39.0
    view_only_mode: true
    custom_secrets:
    - name: obs-cluster-ingress-cacert
      mount: "/kiali-trace-cert"
      optional: false
  external_services:
    tracing:
      enabled: true
      in_cluster_url: "https://metric.obs.cld.internal/jaeger-query" # no need to override this anymore
      use_grpc: false
      auth:
        ca_file: "/kiali-trace-cert/ca.crt"
    prometheus:
      url: "http://istio-prometheus.observability:9090"
    grafana:
      enabled: false
  auth:
    strategy: openid
    openid:
      issuer_uri: "https://xxx.com/svc/dex"
      insecure_skip_verify_tls: true
      client_id: "kiali-client"
      disable_rbac: true
      scopes: 
      - "openid"
      - "email"
      - "groups"
      username_claim: email
      authentication_timeout: 60
      additional_request_params:
        prompt: login
        redirect_uri: "https://xxx.com/svc/kiali"
    restartPolicy: Never
  server:
    web_port: 443
    web_root: /svc/kiali

**Comment by jmazzitelli** [comment]
Your yaml in the above comment is hard to read. To format yaml in these github comments, surround the yaml with triple-tick marks (```): Example:

\`\`\`yaml
... put your yaml here ...
\`\`\`

e.g.
```yaml
your: yaml
  goes: here
```

**Comment by israel-hdez** [comment]
@dirkckau I parsed your cert and it does parses correctly (I'm not getting the "supplied OpenId CA file cannot be parsed" error)

You may want to check that the crt file is mounted correctly to the Kiali pod. These commands may help:

```
# KIALI_POD=$(kubectl get pod -n istio-system -l app=kiali --no-headers -o custom-columns=":metadata.name")
# kubectl exec -n istio-system $KIALI_POD -- cat /kiali-cabundle/openid-server-ca.crt
```

If the output of the last command prints the original certificate file, all should be good. If it still fails, please provide the detailed error message. Several errors print that "Error fetching OpenID provider metadata." to the logs, but more details should be provided on the same log line.

I have to ask how are you installing Kiali? Despite the formatting issue that Mazz mentioned, I'm reading some lines that are not familiar to me.

**Comment by Morriz** [comment]
We are also experiencing this issue. Even though we use the same mechanism successfully for our cluster workloads, we keep hitting the parser error. We tried 2 ways:
- root CA only
- root CA with intermediate chain

Both don't parse.

**Comment by israel-hdez** [comment]
@Morriz As I requested to the other user, please provide the log line that you are seeing from the Kiali pod, so that we can better understand at what point the problem happens.

Also, provide your Kiali version.

**Comment by Morriz** [comment]
after updating to 1.49 we don't experience this issue any more...

**Comment by israel-hdez** [comment]
No feedback. Closing as stale.

**Comment by jacob-kuder** [comment]
For those who are trying to get this working, please make sure you only include your root CA, and if utilizing Helm, make sure the formatting is correct (appropriate line breaks, no double quotes, etc.). Also, we at first were trying to use base64 encoding, however, it does not appear to be appropriate/needed. We setup the config map to JUST have the root CA, in normal certificate text/formatting, with no encoding, and this worked for us.

**Comment by keliansb** [comment]
Just had the same issue, and indeed creating the ConfigMap without base64 encoded certificate solved it. Could you please update the documentation [here](https://kiali.io/docs/configuration/authentication/openid/#using-an-openid-provider-with-a-self-signed-certificate) to remove the need of having a base64 encoded certificate?

**Comment by jmazzitelli** [comment]
@keliansb you can create a [doc github issue here](https://github.com/kiali/kiali/issues/new?assignees=&labels=docs&projects=&template=documentation.md) and fill in the template with that link and what you think should change.
