### ISSUE TITLE
Launch Kiali wizard scenarios from graph nodes

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#4505]
Based on part of [this discussion](https://github.com/kiali/kiali/discussions/4084#discussioncomment-937881), users can launch the Kiali wizards directly from the graph nodes.

I propose that right clicking a graph node brings up the appropriate wizards in the context menu based on the node type e.g. right clicking on a service node would bring up the context menu with the "create request routing" option. Clicking on "create request routing" would bring up the request routing wizard. In addition, clicking the kebab on the node summary panel would also have a wizard options appropriate to the node type.

Current context menu:
![Screenshot from 2021-11-17 13-24-49](https://user-images.githubusercontent.com/6226732/142260563-59a7363b-a6b5-4639-a76c-9f7dcde5182c.png)

Node summary panel kebab:
![Screenshot from 2021-11-17 13-25-08](https://user-images.githubusercontent.com/6226732/142260809-8de56dcc-cca4-43bc-8a55-5f0beff04624.png)

Some additional considerations:
- Passthrough/Blackhole cluster should probably be exceptions
- What happens if the graph data refreshes and the node the wizard was being applied to disappears? Perhaps the graph refresh should be paused while the wizard is open and resumed to it's previous value after being closed?

**Comment by lucasponce** [comment]
I'm going to add this epic to the backlog.
I think makes sense to launch the actions that are under the Service details:
![image](https://user-images.githubusercontent.com/1662329/177525147-f5b8418b-6cb9-4869-9d69-4d10dc0a9526.png)

From the graph, both from the sidepanel actions menu and the context menu.

The functional scope of the epic would be to launch the Wizards, but the experience should be similar even if the user operates the Wizard from the graph and from the service details.

There are some technical aspects to face, to consider, the Service Wizards take the assumption that the service details are loaded and passed to the wizard (to evaluate if it's a create/update, and to populate workloads).

To avoid architectural changes, from the graph this could be done in two steps when the user clicks in an "open wizards" action under a service, when the service details operation may happen (that would prevent to not load unnecessary information from the graph), and with that "open wizard" step, the user can select the regular menu. This is a high-level idea but this epic shouldn't impact the graph architecture (i.e. do not populate in the graph what the wizard needs).

**Comment by jshaughn** [comment]
Is this work really worth the effort?  A user can just navigate to the service detail and continue with the wizards from there, no?

**Comment by israel-hdez** [comment]
@jshaughn I think from the OS plugin perspective, it makes sense.
Also, IMHO, from a UX perspective, it also does makes sense.

From a maintainability perspective, it does not.
