### ISSUE TITLE
access ingress_enabled for now to support older CRs

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#4510]
We made a backward-incompatible change recently regarding the ingress settings. See https://github.com/kiali/kiali/issues/4342

The setting `spec.deployment.ingress_enabled` was removed and replaced with `spec.deployment.ingress.enabled`. Some older CRs may still be using that older setting (specifically, the Maistra operator will set that value when creating the Kiali CR). To avoid having to ask the Maistra operator to update its code so when installing a CR for 1.24 it uses the old setting but for 1.36 it uses the new setting, let's put some code in the kiali operator to accept `spec.deployment.ingress_enabled`. That's the only setting that is created by Maistra operator, so it the only one we need to worry about.

We can rip out this change later when we no longer support those older versions.

**Comment by jshaughn** [comment]
Yes, we should have made it backward compatible given that 1.24 (OSSM 2.0) will be supported for quite a while, and past 2.2 when the original change will make it into the product operator.  There could also be some analogous upstream user.
