### ISSUE TITLE
Hide graph labels that are too small to read

### ISSUE THREAD

**Issue by jshaughn** [kiali/kiali#4521]
Related to Discussion https://github.com/kiali/kiali/discussions/4518.

It's been mentioned in a variety of places and basically, if the graph is zoomed to a degree that labels are unreadable, it would probably be better to hide the labels such that the graph may get an improved, cleaner layout.

**Comment by lucasponce** [comment]
One aspect that I really like and I commented in several forums is that these kind of problems are very well known in other spaces (like GIS or vectorial maps).

No need to go deep, but using some automatic display of labelling if user is in the proper zoom sounds a good approach.

Cytoscape has an example that shows this feature:
https://js.cytoscape.org/demos/tokyo-railways/

But it's not straightforward in Kiali due some implementation decisions, but I guess from feature perspective that example is valid to showcase how a progressive labelling could work on zooming.

**Comment by jshaughn** [comment]
A technical note.  Cytoscape supports something called "min-zoomed-font-size", which is a way to configure the minimum font for node or edge labels, before cytoscape hides the label automatically.  On the surface this seems like the perfect thing to address this issue, but unfortunately we can't easily use this approach.  Our nodes use use html labels (via the cytoscape-node-html-label extension), and this feature does not extend.  Also, we wanted to use progressive labeling (remove text before badges, for example), and that is also not a natural fit.  Finally, hiding labels is only half of the issue, the other half is being able to identify nodes without labels (i.e. via hover).
