### ISSUE TITLE
Not able to load graphs on kiali.

### ISSUE THREAD

**Issue by bj-1795** [kiali/kiali#4538]

**Comment by bj-1795** [comment]
I have installed kiali via operator .

KialiCR.yml

**Comment by lucasponce** [comment]
Can you add details of the Istio version, the platform/cluster and more details ?

The error in the log means that the workloadgroups api of Istio is not present and that could mean that you're trying to install Kiali in an old (non supported) Istio version.

**Comment by bj-1795** [comment]
@jshaughn @lucasponce I am able to get metrics in prometheus.

istio version - 1.7.2 on AWS EKS

**Comment by jmazzitelli** [comment]
1.  Can you wrap the yaml in github triple-ticks so the yaml is formatted. Your description shows yaml but is not formatted so it is hard to read.
2. I'll convert this to a discussion - so far this does not warrant a bug report. If it is truly a bug, we can convert back to bug/issue.
