### ISSUE TITLE
Auth: Phase out usage of JWTs

### ISSUE THREAD

**Issue by israel-hdez** [kiali/kiali#4542]
Most Kiali's authentication mechanisms are using own JWTs.

In the past, usage of JWTs was introduced as a mechanism to avoid credential forging. The UI stored the token and it was handy to have some data in plain text form because the UI could extract by its own means some data of the token (like the username) to display on the UI or for any purposes. Then, the signature of the JWT prevented credential forging. However, using javascript mechanisms to save the token and persist the session had a few problems at the moment of killing or starting sessions which were solved by moving session persistence to cookies.

Today, the UI does not have access to the token. So, it needs to make a request to the back-end to check if there is any active session and the back-end will reply with the data that the UI used to resolved by its own in the past. Also, the JWT library that Kiali is using is now unmaintained. So, current usage of JWTs to persist the session is mainly because of historical reasons and can be seen as technical debt. It is probably desirable to move away from the unmaintained JWT library.

The proposed alternative would be to use native golang crypto packages to set an encrypted cookie, like in [the OpenID authorization code strategy](https://github.com/kiali/kiali/blob/cef36d4f69f06ea05db766027084d00d3cd31da9/handlers/authentication.go#L980-L1064). It has the added benefit that session data will no longer be transferred in plain text and can be used to store sensitive data (which is already being done for some auth strategies). Session data will be readable only at the back-end side, provided that users keep secured the `signing_key`.

**Comment by jshaughn** [comment]
This has been a source of security concern, adding to the backlog.
