### ISSUE TITLE
Read openid.client_id value from existing k8s secret in kiali-operator helm chart

### ISSUE THREAD

**Issue by Nizar-opt** [kiali/kiali#4551]
In kiali-operator helm chart, we have the option to set sensitive values as `"secret:<secretName>:<secretKey>"` only in the external_services auth section as mentioned [here](https://github.com/kiali/kiali-operator/blob/cd0259d84beb382a9532b7e444e7eff08a0715e6/deploy/kiali/kiali_cr.yaml#L493).
However, It would be helpful to be able to use the same format to set [auth.openid.client_id](https://github.com/kiali/kiali-operator/blob/cd0259d84beb382a9532b7e444e7eff08a0715e6/deploy/kiali/kiali_cr.yaml#L143) value.

**Comment by israel-hdez** [comment]
Duplicate of #3563

**Comment by jshaughn** [comment]
closing as duplicate
