### ISSUE TITLE
target Namespace is not considered when validating Gateway host duplicates

### ISSUE THREAD

**Issue by maxbischoff** [kiali/kiali#4586]
The duplicate Gateway Host Validation only considers Ports and Selectors for separating the Comparison Spaces for Gateways. No special consideration was given for Hosts in the namespace/host Syntax (see [hosts in Gateway.spec.servers](https://istio.io/latest/docs/reference/config/networking/gateway/#Server) for a detailed description of this syntax).

This causes false Negatives when a host is given for the Gateways namespace (`./<host>`) as well as the specific namespace (`<gateway-namespace>/<host>`). 

Additionally, the comparison is very inefficient for cases, where hosts are defined for multiple target namespaces, e.g.

```yaml
    hosts:
    - "ns1/example.com"
    - "ns2/example.com"
    - "ns3/example.com"
    - "ns4/example.com"
```

, since all of these hosts are compared textually using regex, despite them not being able to conflict since they are restricted to separate namespaces.

I already provided a fix for this in https://github.com/kiali/kiali/pull/4578

**Comment by lucasponce** [comment]
cc-ing @hhovsepy
