### ISSUE TITLE
Add pprof endpoints for debugging perf issues

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#4597]
Taking inspiration from https://github.com/maxbischoff/kiali/commit/69865f05f7b5247e256b5dc82d145e6bbd708f1f, having pprof endpoints will help in diagnosing perf issues.

The debug handlers can be optionally added at runtime when a config option is enabled, something like `config.Server.Debug = true`, but disabled by default.

**Comment by jmazzitelli** [comment]
I'm going to play with this today to see how easy and un-intrusive we can implement this.

**Comment by jshaughn** [comment]
@hhovsepy , @jmazzitelli I added this to the perf Epic to tie in with our current priorities.
