### ISSUE TITLE
Kiali should check the Istio version and throws a warning about compatibility

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#4604]
I wonder if it's worth to develop a self message in Kiali checking the Istio version used.

That would help users to be aware if they are trying to deploy Kiali in a non compatible Istio version and save some time while troobleshooting.

**Comment by lucasponce** [comment]
@Xunzhuo has expressed interest to work on this issue, it seems it has a minor size to work on it.
Any comment from @kiali/maintainers?

**Comment by jshaughn** [comment]
I'm +1 for @Xunzhuo to take this issue.  @Xunzhuo, please first use the issue comments to talk about the approach or ask questions.  When the design is good then proceed to implementation.  That will help minimize PR review time. Thanks for contributing!
