### ISSUE TITLE
Documentation: App Labeling requirements

### ISSUE THREAD

**Issue by EronWright** [kiali/kiali#4609]
I observe that Kiali has an undocumented requirement to correctly identify linkages between applications and services.  It requires that the configured app label be present in the _service selectors_.  Kiali primarily requires the app label be present on the workload, consistent with Istio itself, but I'm not aware of any labeling requirements on services from Istio.

For example, here's en embodiment of the requirement:
https://github.com/kiali/kiali/blob/01b90b0ee80189f9d5daacf93a60007e746e7f3c/business/services.go#L543-L560

**Comment by jshaughn** [comment]
I think this is only with respect to determining jaeger spans from an app name.  @EronWright , where would you like to see this documented?  Or, even better, do you want to submit a PR for kiali.io?
