### ISSUE TITLE
Offer possibility to export the Graph in different formats

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#4615]
This issue captures a community discussion on twitter:
https://twitter.com/Julien_Lau/status/1471781817686573061

The scope and request should be better defined but Github is a better place to work on it rather than Twitter.

**Comment by julienlau** [comment]
Is there a tool to parse/convert the JSON graph given by Istio (for example the workload graph) to the standard DOT format that can be more easily manipulated with graphviz and rendered / analyzed ? 

That could provide automatic update of graph in manuals... and ease the onboarding on new projects

In addition :  
- in this blog post from Petr Ruzicka there seem to have a dotviz converter, but I cannot retrieve the source code
https://medium.com/@petr.ruzicka/istio-in-amazon-eks-23704aef4f28
- I am not familiar with how these two projects are splitted, but at first I was thinking that the converter available in https://github.com/istio/tools/blob/master/isotope/convert/pkg/graphviz/graphviz.go could be reused somehow, but I think it only takes yaml from istio test as input.

**Comment by jshaughn** [comment]
The JSON graph generated by Kiali is in Cytoscape format, and is rendered in the UI via Cytoscape.  We have not looked into any sort of import/export, but a quick search reveals this:  graphhttps://apps.cytoscape.org/apps/dotapp.   Is that something that may be relevant?

**Comment by julienlau** [comment]
absolutely !
I'll give it a try https://apps.cytoscape.org/apps/dotapp
DOT is one of the most standard graph format. I was not aware of cytoscape.

Export feature would be nice even using as is format.

Thanks

**Comment by jshaughn** [comment]
Closing as out-of-scope
