### ISSUE TITLE
BUG: unexpected error when fetching prometheus config 

### ISSUE THREAD

**Issue by Xunzhuo** [kiali/kiali#4624]
I config prometheus url in external service (prometheus is deployed remotely and can be access)
In kiali-ui, graph can be computed which means metrics can be fetched from prometheus.
But sometimes, kiali logs that ERR Failed to fetch Prometheus configuration: client_error: client error: 404,which confused me a lot.
Can forks help me to figure it out why and how to deal with it? :)

**Comment by Xunzhuo** [comment]
BTW, `Prometheus` is deployed with `Thanos`, I do not know if this is the reason may caused the error.

**Comment by jshaughn** [comment]
If you are using Thanos you need to configure Kiali to use Thanos.  See https://github.com/kiali/kiali-operator/blob/master/deploy/kiali/kiali_cr.yaml#L687-L691

Closing, re-open if you feel there is still a problem.
