### ISSUE TITLE
Support single cluster traces view when using Jaeger with multi-cluster storage backend

### ISSUE THREAD

**Issue by yeya24** [kiali/kiali#4635]
# Use Case
We have over 80+ edge clusters and each cluster deploys an Istio and Kiali. At the beginning, we deploy one Jaeger instance with Badger backend at each cluster so that Kiali can query Jaeger directly and get the single cluster trace view.

Now we plan to switch our Jaeger storage backend to a central Elasticsearch deployment, which means all the traces from 80+ clusters will go into ES now. However, in this case, Kiali won't work properly because now it will get traces from all the clusters that matched the requested service.

To solve this, right now we have to deploy another jaeger instance for single-cluster-level query only. This is not sufficient.

## Possible solution
Right now, all the traces contain a tag to indicate the cluster name, for example `cluster.name=us-east`. I hope Kiali can support this to do some traces filtering for such multi-cluster deployment.

## Alternative solution 
https://github.com/jaegertracing/jaeger/pull/3412 is going on the Jaeger side so once that is ready this issue can be solved as well.

**Comment by lucasponce** [comment]
The "query.proto" API allows to filter via "tags" so this parameter could be added to the query used to fetch the data:

![image](https://user-images.githubusercontent.com/1662329/148036800-fb79c6f0-8698-4f5b-bd60-23d4d9ac2b31.png)

One aspect to sync is that the "cluster.name" used in Jaeger matches with the "cluster ID" used in the mesh as this one is relevant in other Kiali areas.

**Comment by jshaughn** [comment]
@lucasponce , We recently added `queryScope` to the prometheus configuration, to handle unified metrics.  It sounds like we need the same thing as part of the Jaeger/Tracing config.  See https://github.com/kiali/kiali/issues/4664.

**Comment by jshaughn** [comment]
@yeya24 Is this still a problem for you?  It sounds like we could do something similar to the `queryScope` support we have for querying a unified Prometheus, and leverage the query.proto API mentioned above.

**Comment by yeya24** [comment]
@jshaughn I haven't followed the same topic for a while now. And now Jaeger seems to support storage tenancy already. I need to double check.

**Comment by jshaughn** [comment]
@yeya24 Thanks for the reply.  If you find out any more information please let me know if this is still a problem for your Kiali deployment model.

**Comment by jshaughn** [comment]
I think it makes sense to add the same support here as we did for Prometheus queries.  If traces are unified it seems this could be a problem, and the solution seems straightforward if we support adding static tags to each query.
