### ISSUE TITLE
fast click `Idle Nodes` (or other graph display options) can break UI

### ISSUE THREAD

**Issue by Xunzhuo** [kiali/kiali#4638]
If I repeated clicking the `Idle Nodes` fast for 3 times, page will break down

![image](https://user-images.githubusercontent.com/48784001/148360801-2edf9c83-ddf6-4ce8-8a0f-8374e07782a5.png)

Each time I try to reproduce this bug, pages will always be broken in the third time.

Steps:

1. click to choose the `Idle Nodes` button
2. click to cancel the `Idle Nodes` button
3. click to choose the `Idle Nodes` button
4. click to cancel the `Idle Nodes` button
5. click to choose the `Idle Nodes` button
6. break

After occurring this error in kiali-ui, sometimes it can recover by itself, but most of time page will be just frozen to show this error log, front-end will stop to send request to `/api/namespaces/graph` to compute topology.

![image](https://user-images.githubusercontent.com/48784001/148360455-35023d9d-ac8f-4b14-9584-cacd9733798b.png)

**Comment by jshaughn** [comment]
Were you trying to break the UI or did this happen naturally, because that seems like an odd thing to do?

Can you capture any errors in the browser console?

**Comment by Xunzhuo** [comment]
This happen naturally when I try to set different show modes, this is the steps to reproduce the bug.

**Comment by jshaughn** [comment]
I guess I'm a little surprised no one has reported this sort of fast-click issue in the past.  It's not super easy to crash things, but there does seem to be a short window during layout where things can get confused.  The safest option is probably to disable the menu options while the graph is refreshing.
