### ISSUE TITLE
Adopt a decoupled model for extensions

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#4642]
Kiali introduced a guideline of "how to add extensions code" to help third party components to add features on top of Kiali:
https://github.com/kiali/kiali.io/blob/v1.36.0/content/documentation/v1.36/extensions/index.adoc

This guideline had requirements to introduce backend code to support custom APIs and also frontend code to support custom forms and other logic to integrate third-party code into Kiali.

This approach was ok for the short term but after some time it looks that we'd need a different approach and more decoupled.

Probably Kiali backend may offer a generic proxy for typeless API and in the frontend, most of the third-party code could come in the way of a JS dependency, reducing the integration code and making it easier to maintain for third-party developers.

This would need research to identify where third-party logic can add more value to Kiali features (graph, charts, details) and make it more robust.

**Comment by lucasponce** [comment]
Cc @fabolive as part of the lead of the Iter8 integration; I'd like to collect your inputs if you think this could be a good idea or if the  Iter8 team has thoughts about how to work in these integrations efficiently.

Two goals of this new approach:
- Reduce the maintenance time in third-party API changes.
- Allow decoupling of specific third-party code outside of the Kiali repo that the specific team could maintain.
- Kiali repo could concentrate on more added-value logic focused on the integration and reduce the boilerplate code required to keep an external API up-to-date.

**Comment by Hronom** [comment]
Interested in possibility to extend functionality of Kiali. So for example companies can extend functionality of Kiali. I see there [was possibility to build extensions](https://github.com/kiali/kiali.io/blob/v1.36.0/content/documentation/v1.36/extensions/index.adoc), but now seems like its removed from the documentation. How we can extend Kiali now?

**Comment by jshaughn** [comment]
Hi @Hronom , The extensions framework was an early attempt at identifying various touchpoints in the code such that an optionally enabled feature may be easier to add.  It was not a way to support runtime plugins, for example, just optional but hard-coded extensions.  It was hard to maintain and underused, and so we removed the support.  Outside of custom dashboards (additional, custom chart tabs on pages like Workload details), Kiali does not have any sort of buit-in support for extensibility, as the maintainers really haven't found the time to support anything other than Istio itself.   But, we'd be interested in knowing what you had in mind, and maybe we can help identify some sort of path forward.

**Comment by jshaughn** [comment]
@Hronom I'm going to close this issue because there isn't really any actio item.  But, if you'd like to explore more about what youd be looking for, or what sort of extnsion(s) you had in mind, please open a Discussion (not an issue), we'd be happy to talk more about it.
