### ISSUE TITLE
Namespace Selector - Uncheck all other namespaces apart one

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#4660]
In Namespace selector, in a case of many namespaces checked and user wants to leave only one.
Have a new functionality to uncheck all other namespaces besides the particular checked one.

**Comment by lucasponce** [comment]
I perform this operation in two steps, "unselecting" and just selecting the single namespace.
I think this comes from the native PF component.

**Comment by jshaughn** [comment]
I think this could be closed or set to Help Wanted.

**Comment by jshaughn** [comment]
Closing as unnecessary.
