### ISSUE TITLE
Not all remote clusters have reachable Kiali instances

### ISSUE THREAD

**Issue by cloudcafetech** [kiali/kiali#4670]
I am getting following error 

**Not all remote clusters have reachable Kiali instances.
Context menus are disabled for remote cluster nodes if a Kiali instance is not discovered, or if the remote Kiali is not configured with an external URL.**

My env : Onprem 2 K8S (1.20) clusters on rancher, istio version 1.10.1, Kiali 1.34

From Kiali pod to both Cluster API I can do telnet, not sure what is causing 

![image](https://user-images.githubusercontent.com/68260844/150799712-9a1ccb51-725f-4e8a-b153-aca5d912036c.png)

![image](https://user-images.githubusercontent.com/68260844/150773224-4a26deda-75b4-4b3d-860e-87bf8ca4a413.png)

As issue close to https://github.com/kiali/kiali/issues/4039 so tried web_fqdn options also but no luck :(

**Comment by israel-hdez** [comment]
@cloudcafetech Both Kialis should be reachable between them.
Open a bash session to one of the Kiali pods. Then check that the remote Kiali is reachable (and replies correctly) by using the `web_fqdn` address that you are configuring in the remote one.

**Comment by cloudcafetech** [comment]
>Open a bash session to one of the Kiali pods. Then check that the remote Kiali is reachable (and replies correctly) by using the web_fqdn address that you are configuring in the remote one.

I am able to do that using curl telnet.

```
[test-server]$ oc get po,ing -n istio-system --context dev | grep kiali                                               
pod/kiali-85c8cdd5b5-6j5jn                   1/1     Running   0          18m
ingress.networking.k8s.io/kiali   <none>   kiali.172.25.80.139.nip.io   10.43.156.104   80      18m
[test-server]$
[test-server]$
[test-server]$ oc get po,ing -n istio-system --context stage | grep kiali
pod/kiali-85c8cdd5b5-89rwp                   1/1     Running   0          18m
ingress.networking.k8s.io/kiali   <none>   kiali.172.25.80.177.nip.io   10.43.149.127   80      18m
[test-server]$
[test-server]$
[test-server]$ oc exec -it kiali-85c8cdd5b5-6j5jn -n istio-system  --context dev -- curl -v telnet://kiali.172.25.80.177.nip.io:80
* Rebuilt URL to: telnet://kiali.172.25.80.177.nip.io:80/
*   Trying 172.25.80.177...
* TCP_NODELAY set
* Connected to kiali.172.25.80.177.nip.io (172.25.80.177) port 80 (#0)
^Ccommand terminated with exit code 130
[test-server]$
[test-server]$
[test-server]$ oc exec -it kiali-85c8cdd5b5-89rwp -n istio-system  --context stage -- curl -v telnet://kiali.172.25.80.139.nip.io:80
* Rebuilt URL to: telnet://kiali.172.25.80.139.nip.io:80/
*   Trying 172.25.80.139...
* TCP_NODELAY set
* Connected to kiali.172.25.80.139.nip.io (172.25.80.139) port 80 (#0)
^Ccommand terminated with exit code 130
[test-server]$
```

I have annotated both kiali services with external url and set ```web_fqdn``` & ```web_schema``` in configmap.

![image](https://user-images.githubusercontent.com/68260844/150890859-bd3a00b6-d41a-46bd-8a9e-572dc349fb73.png)

The error gone after annotated both kiali services with external url and set ```web_fqdn``` & ```web_schema``` in configmap

```
Not all remote clusters have reachable Kiali instances.
Context menus are disabled for remote cluster nodes if a Kiali instance is not discovered, or if the remote Kiali is not configured with an external URL
```


**But unfortunately after that also both clusters not visible**


![image](https://user-images.githubusercontent.com/68260844/150891588-6aecda2a-7233-4c08-902a-30f1c462d57a.png)

**Comment by cloudcafetech** [comment]
@israel-hdez 

Issue got fixed, looks like for verify sample apps not for multi cluster visibility. After deploying google Bootique app now I can see both cluster visibility.

Thanks for your help 👍
