### ISSUE TITLE
Optimize the Kiali Cache design under cluster rights presence

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#4678]
This is a follow-up issue started in https://github.com/kiali/kiali/issues/4502#issuecomment-1021162055

Kiali uses k8s Informers to access k8s APIs (workload, services, and Istio configuration).
The current design creates an Informer per namespace+API, and the Informer is responsible to handle all low-level events and provide a cache for the API objects.

This design works reasonably well, but in clusters with a high level of namespaces, the number of informers can add a significant overhead to the Kiali backend (an Informer requires a connection with the API and its own memory).

If the Kiali ServiceAccount doesn't have cluster rights, this design can't change (unless Informers are removed, but then, Kiali would need to query all low-level APIs and keep them updated).

But, if the ServiceAccount has cluster rights (or accessibleNamespaces == "**") then this design could be optimized and it can change to use a single informer per API that watches all namespaces.

This could be an optional enhancement in the Kiali backend, it shouldn't change the business behavior, but under this scenario, the Kiali Cache could be optimized.

**Comment by nrfox** [comment]
This has come up a few different times wrt scalability and it seems like an issue that needs to be addressed. Is this ready to be worked on?
