### ISSUE TITLE
auth is broken according to molecule tests

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#4682]
The `openid-test`, `header-auth-test` and `token-test` are all failing now. I suspect it is due to either [this](https://github.com/kiali/kiali/pull/4596) or [this](https://github.com/kiali/kiali/pull/4655) recent change.

To see it fail, from your dev env in the kiali repo run this:

```
hack/ci-minikube-molecule-tests.sh \
  -me "$(which minikube)" \
  -ce "$(which kubectl)" \
  -ir "" \
  -at "token-test header-auth-test openid-test"
```

The latest molecule test runs on minikube are here: [token-test](https://github.com/jmazzitelli/kiali-molecule-test-logs/blob/minikube/molecule-tests-2022-01-27_04-00-01/token-test.log#L289) , [header-auth-test](https://github.com/jmazzitelli/kiali-molecule-test-logs/blob/minikube/molecule-tests-2022-01-27_04-00-01/header-auth-test.log) , [openid-test](https://github.com/jmazzitelli/kiali-molecule-test-logs/blob/minikube/molecule-tests-2022-01-27_04-00-01/openid-test.log)

The token-test is run on openshift (the other two are not) - the test logs for that are [here](https://github.com/jmazzitelli/kiali-molecule-test-logs/blob/openshift/molecule-tests-2022-01-27_02-00-01/token-test.log#L296).

For the header-auth-test and the token-test, I believe this is the cause:
```
2022-01-27T15:19:36Z FTL signing key for sessions must be 16, 24 or 32 bytes length
```
But for the `token-test`, it looks like logging in is simply failing (it may be a problem in the server or in the test itself, I do not know).

**Comment by jmazzitelli** [comment]
cc @israel-hdez

**Comment by jmazzitelli** [comment]
I found that this fixes the header-auth-test, however, the same change does not fix the openid-test:
```diff
diff --git a/molecule/header-auth-test/kiali-cr.yaml b/molecule/header-auth-test/kiali-cr.yaml
index 1b436b1..755e75f 100644
--- a/molecule/header-auth-test/kiali-cr.yaml
+++ b/molecule/header-auth-test/kiali-cr.yaml
@@ -18,6 +18,3 @@ spec:
     image_version: "{{ kiali.image_version }}"
     namespace: {{ kiali.install_namespace }}
     service_type: {{ 'LoadBalancer' if is_kind else 'NodePort' }}
-  # if signing key is not 16, 24, or 32 chars, then openid "implicit flow" is used and what we test
-  login_token:
-    signing_key: "abc12345"
```

**Comment by israel-hdez** [comment]
Ough, I though molecules didn't break. But I think it was because of the outdated `:latest` images in quay.

> I found that this fixes the header-auth-test, however, the same change does not fix the openid-test:
It may need a small change in how dex is configured. I'll check.
