### ISSUE TITLE
Display traffic flow and distribution across pods

### ISSUE THREAD

**Issue by skunkr** [kiali/kiali#4688]
Hi,
I am sorry if its a case of a lack of knowledge on my side,  but i have the following situation.
A simple k8s deployment, with a replica of 3 pods number ( named backend).
( Istio, Kiali, Jeager - all up and running normally )
I see Kiali displaying the traffic to the "backend" k8s svc,  but i cannot see a way of displaying how the traffic is distributed across the pods  within the deployment - for a more granular observability of traffic flow.
In the "Workloads" section, selecting the service I can see all three pods displayed under "Pods" section. But they are not also displayed  on the "Graph" 
My questions is:
Is this is something expected, or is there something else I need to configure to be able to graphically disaply the pods and traffic coming to them as well in the Kiali Graph ? 
Please let me know if any thoughts.
Thank you in advance,

Leo

**Comment by jshaughn** [comment]
This is expected, Kiali does not deal with traffic at the pod level.  The smallest granularity for traffic is the workload.  The more dynamic nature, and possibly high number, of pods doesn't lend well to the graph.  For that type of granularity you may want to look more at setting up some Grafana queries, or something like that.

**Comment by jmazzitelli** [comment]
> This is expected, Kiali does not deal with traffic at the pod level. The smallest granularity for traffic is the workload.

Correct me if I'm wrong - but isn't this a limitation of the Istio telemetry itself? I didn't think Istio telemetry provided metrics down to the individual pod (and hence why Kiali can't deal with pod-level traffic)

**Comment by israel-hdez** [comment]
> > This is expected, Kiali does not deal with traffic at the pod level. The smallest granularity for traffic is the workload.
> 
> Correct me if I'm wrong - but isn't this a limitation of the Istio telemetry itself? I didn't think Istio telemetry provided metrics down to the individual pod (and hence why Kiali can't deal with pod-level traffic)

From [this comment](https://github.com/kiali/kiali/issues/2477#issuecomment-593938889), I see `pod_name` is a label in `istio_requests_total`. So, I think it's more a design decision.

**Comment by jshaughn** [comment]
Closing this as out of scope.
