### ISSUE TITLE
Improve crossnamespace Istio Gateways query in ServiceDetailsPage

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#4692]
As part of the big epic defined at https://github.com/kiali/kiali/issues/4382 the cross-namespace queries have been improved with new flags "AllNamespaces" to use the Istio Registry to fetch all configuration using a single query.

There is a particular case in the ServiceDetailsQuery that iterates over all namespaces to collect all the Istio Gateways present in the cluster. This query is required to populate the Service Wizard to let the user select an existing gateway while creating/updating Istio configuration.

This loop could be reduced with a single query as in scenarios with a large number of namespaces this may introduce performance overhead.

**Comment by hhovsepy** [comment]
@lucasponce can you please add the link of code you found that iteration? cannot find it.

**Comment by lucasponce** [comment]
Sure, it's in the frontend code:
https://github.com/kiali/kiali-ui/blob/master/src/pages/ServiceDetails/ServiceDetailsPage.tsx#L86

There is a first call to fetch all namespaces and then it iterates on them to fetch the gateways per namespace.
With all the work there is in place, I think it can be improved.

Also, on the Overview page, there are similar discussions that may be improved as well, but those would deserve a separate issue as the refactoring could buffer can be larger.
