### ISSUE TITLE
Add prerequisites in quick-start kiali.io to try kiali

### ISSUE THREAD

**Issue by aljesusg** [kiali/kiali#4703]
In the https://kiali.io/docs/installation/quick-start/ section the instructions are :

1.  kubectl apply -f ${ISTIO_HOME}/samples/addons/kiali.yaml

**_We should add prerequisites to be able to use kiali like having istio and prometheus installed_**

# Error reported

https://kiali.io/docs/installation/quick-start/

kubectl apply -f ${ISTIO_HOME}/samples/addons/kiali.yaml
This gives me a Kiali pod 
kubectl get pods -n istio-system
NAME                                    READY   STATUS    RESTARTS   AGE
istio-egressgateway-5457479458-zxl6h    1/1     Running   0          22m
istio-ingressgateway-7655767668-npx92   1/1     Running   0          22m
istiod-9cbc77d98-p5kcm                  1/1     Running   0          22m
kiali-c9d6f75d5-qll62                   1/1     Running   0          20m

but I get a number of errors in the Kiali console like so
Cannot load the graph: Post "http://prometheus.istio-system:9090/api/v1/query": dial tcp: lookup prometheus.istio-system on [10.96.0.10:53](http://10.96.0.10:53/): no such host

I think the bug is in the docs as the end-user also needs to have executed

kubectl apply -f ${ISTIO_HOME}/samples/addons/prometheus.yaml

**Comment by lucasponce** [comment]
I don't think this is a bug.
![image](https://user-images.githubusercontent.com/1662329/152317290-ea98c1bc-4859-4b1d-bfdd-d6cb7b890080.png)

The quickstart assumes that users have downloaded and installed Istio (with the addons too).

A comment in the quick start may help.

**Comment by jmazzitelli** [comment]
I always thought it was a "given" that people would understand you need to first install Istio (and that includes its telemetry storage, i.e. Prometheus). But, apparently, some people are not aware that Istio is a prerequisite of Kiali. So, yes, at the top of:

https://kiali.io/docs/installation/quick-start/

we should put a blurb that indicates this. We might even want to make it super-clear at the top of the prereq page (https://kiali.io/docs/installation/installation-guide/prerequisites/) that you must install Istio first.

The blurb could say something like,

```
Before you install Kiali you must have already installed Istio along 
with its telemetry storage addon (i.e. Prometheus)
and (optionally) its tracing addon (i.e. Jaeger).
```

**Comment by jshaughn** [comment]
For things like this I recommend just creating a PR for kiali.io and work out the details in the PR review.  @aljesusg or @jmazzitelli , perhaps one of you can take care of this quickly, so it goes into the next release (tomorrow).
