### ISSUE TITLE
fix grammar in error message "user has not permissions"

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#4704]
"User has not permissions" is not entirely correct English. Should be `User does not have permission`

These need to be fixed:
* https://github.com/kiali/kiali-ui/blob/master/src/components/IstioActions/IstioActionsNamespaceDropdown.tsx#L81
* https://github.com/kiali/kiali-ui/blob/master/src/components/IstioActions/IstioActionsDropdown.tsx#L78
* https://github.com/kiali/kiali-ui/blob/master/src/components/IstioWizards/ServiceWizardDropdown.tsx#L284
* https://github.com/kiali/kiali-ui/blob/master/src/pages/IstioConfigNew/IstioConfigNewPage.tsx#L162

**Comment by aljesusg** [comment]
Hi @Faraaz2633 ,

Welcome to kiali community. Feel free to address this issue. I just change the sentence that @jmazzitelli indicate in the description.

Here you have the guide about the project https://github.com/kiali/kiali
and here the contribution guide https://github.com/kiali/kiali#contributing

Please do not hesitate to ask what you need.

Thanks

**Comment by jmazzitelli** [comment]
This is already being addressed in https://github.com/kiali/kiali-ui/pull/2297

There are other "good first issues" you should look at.

**Comment by aljesusg** [comment]
no @jmazzitelli I removed this change from https://github.com/kiali/kiali-ui/pull/2297 to let new community members address it

**Comment by jmazzitelli** [comment]
Well, I noticed that bad grammar in that PR in more places than just the four I found. We should correct it now since sprint release is tomorrow. There are other good first issues - I only added that label because I didn't realize you were going to fix it in that other PR :)

**Comment by Xunzhuo** [comment]
Done in https://github.com/kiali/kiali-ui/pull/2302. PTAL thanks.
