### ISSUE TITLE
kiali CRD is different between the kiali-operator repo and helm chart

### ISSUE THREAD

**Issue by mischka** [kiali/kiali#4709]
The kiali CRD is different or not up to date between the kiali-operator repo and the corresponding helm chart.
So a serverside validation is not possible.

https://github.com/kiali/kiali-operator/blob/master/crd-docs/crd/kiali.io_kialis.yaml
vs.
https://github.com/kiali/helm-charts/blob/master/kiali-operator/crds/crds.yaml

And after installing the kial-operator via helm the crd is not complete
```bash
$ k get crd kialis.kiali.io -oyaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: "2021-09-03T10:18:34Z"
  generation: 1
  name: kialis.kiali.io
  resourceVersion: "9193667"
  uid: 01a12974-7362-4e1f-af68-36a8866554b2
spec:
  conversion:
    strategy: None
  group: kiali.io
  names:
    kind: Kiali
    listKind: KialiList
    plural: kialis
    singular: kiali
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: Kiali
    listKind: KialiList
    plural: kialis
    singular: kiali
  conditions:
  - lastTransitionTime: "2021-09-03T10:18:34Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2021-09-03T10:18:34Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1alpha1
```

**Comment by jmazzitelli** [comment]
This is not a bug. What you see here: https://github.com/kiali/kiali-operator/blob/master/crd-docs/crd/kiali.io_kialis.yaml is only for generating our kiali.io docs (it was recently introduced a few days ago - see: https://github.com/kiali/kiali/issues/4684 and https://github.com/kiali/kiali-operator/pull/480 for example) and for our validation tool (see https://staging.kiali.io/docs/configuration/kialis.kiali.io/#validating-your-kiali-cr)

We are not deploying that CRD with the schema. What you see in the helm chart is what we are deploying.

So, this is all expected.

**Comment by mischka** [comment]
@jmazzitelli but without the schema, server-side validation of the kiali CR is not possible and e.g. in my case terraform will always replace the CR

**Comment by nrfox** [comment]
> @jmazzitelli but without the schema, server-side validation of the kiali CR is not possible

That's correct @mischka, Kiali does not support server side validation of kiali CRs. There is purposefully no published CRD with an openapi schema other than the one that is included in the helm chart. The CRD [here](https://github.com/kiali/kiali-operator/blob/master/crd-docs/crd/kiali.io_kialis.yaml) is just a reference and can also be used in validating _client side_ your CR with the tool that @jmazzitelli mentioned.

> in my case terraform will always replace the CR

Not sure what you mean. The kube terraform providers clobbers your Kiali CR without the validation?

**Comment by jmazzitelli** [comment]
> without the schema, server-side validation of the kiali CR is not possible

The Kiali CRD that ships with the Kiali OLM metadata and the operator helm chart has a valid schema. Granted, [the schema](https://github.com/kiali/helm-charts/blob/v1.45.0/kiali-operator/crds/crds.yaml#L20-L23) is minimum, but it is a valid schema and will be validated server-side:
```
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
```

This is how Kiali has been since the beginning.

We have a validation tool (that uses that CRD with schema that we used for documentation generation) should you wish to validate the Kiali CR against that more strongly typed schema.

There are reasons why Kiali does not ship with a full strongly-typed schema in the CRD; there are no plans to do so in the future. But to help people check the validity of their Kiali CR, we now provide that validation tool along with full documentation generated from that schema.

**Comment by mischka** [comment]
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # module.k8s_istio.kubernetes_manifest.kiali_istio must be replaced
-/+ resource "kubernetes_manifest" "kiali_istio" {
      ~ object   = {
          ~ metadata   = {
              - finalizers = [
                  - "kiali.io/finalizer",
                ] -> null
                # (2 unchanged elements hidden)
            }
            # (3 unchanged elements hidden)
        } # forces replacement
        # (1 unchanged attribute hidden)
    }

Plan: 1 to add, 0 to change, 1 to destroy.
╷
│ Warning: This custom resource does not have an associated OpenAPI schema.
│ 
│   with module.k8s_istio.kubernetes_manifest.kiali_istio,
│   on module/k8s-istio/main.tf line 166, in resource "kubernetes_manifest" "kiali_istio":
│  166: resource "kubernetes_manifest" "kiali_istio" {
│ 
│ We could not find an OpenAPI schema for this custom resource. Updates to this resource will cause a forced replacement.
╵
```

**Comment by mischka** [comment]
@jmazzitelli without the OpenAPI schema, terraform always detects changes in the manifest  

> Not sure what you mean. The kube terraform providers clobbers your Kiali CR without the validation?

@nrfox the CR is applied correctly, but the following warning is displayed each time.
I am currently trying to fix this behaviour with the ignore_changes configuration. Because otherwise, every time a terraform resource is changed, the kiali CR is also replaced.

```bash
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # module.k8s_istio.kubernetes_manifest.kiali_istio must be replaced
-/+ resource "kubernetes_manifest" "kiali_istio" {
      ~ object   = {
          ~ metadata   = {
              - finalizers = [
                  - "kiali.io/finalizer",
                ] -> null
                # (2 unchanged elements hidden)
            }
            # (3 unchanged elements hidden)
        } # forces replacement
        # (1 unchanged attribute hidden)
    }

Plan: 1 to add, 0 to change, 1 to destroy.
╷
│ Warning: This custom resource does not have an associated OpenAPI schema.
│ 
│   with module.k8s_istio.kubernetes_manifest.kiali_istio,
│   on module/k8s-istio/main.tf line 166, in resource "kubernetes_manifest" "kiali_istio":
│  166: resource "kubernetes_manifest" "kiali_istio" {
│ 
│ We could not find an OpenAPI schema for this custom resource. Updates to this resource will cause a forced replacement.
╵
```

**Comment by jmazzitelli** [comment]
> We could not find an OpenAPI schema for this custom resource

There must be a problem with Terraform then, because there is an OpenAPI schema for that custom resource. It's right here: https://github.com/kiali/helm-charts/blob/master/kiali-operator/crds/crds.yaml#L20-L23
