### ISSUE TITLE
Support Istio external control plane

### ISSUE THREAD

**Issue by litong01** [kiali/kiali#4729]
When istio is deployed as external control plane, Istio workload will be running in a different cluster from the istio control plane, since kiali can only access one cluster, there is no way currently for kiali to access istiod and at the same time to load workload status.

If kiali can be enhanced to do the following, then this problem can be resolved.
1. Add detection when /kiali-remote-secret/kiali exists, this indicates that istio workload is remote and so is the control plane.
2. When istio control plane is not found, kiali should look for the istiod running incluster which basically follow the path when /kiali-remote-secret/kiali does not exist.

Doing this while kiali try to access istiod will have very small impact to Kiali but truly support Istio external control plane.

**Comment by Xunzhuo** [comment]
Hi, thanks for your report. 

This direction is what I am working on. Actually for now, I think the support for external control plane in Kiali needs more discussions and details.

When you read some parts of codes, you will see that some methods are assuming that Kiali and Istiod are deployed in the same cluster. So code changes will be big and we should find the best way to solve this problem and make it backwards compatible:)

**Comment by litong01** [comment]
@Xunzhuo hmmm, not really sure if it will require a lot of code changes. Currently based on the the experimental remote cluster support, I think when the istiod cannot be located from remote cluster, kiali can fall back looking for in-cluster api server (of course serviceAccount has to be also configured which it is normally), the problem is that i think it is now exclusive, either in-cluster or remote, I do not think it has to be that way, we can add a bit logic to also look for information in the cluster where kiali lives (which will be the exact case for external control plane). That way, there should not be much of code change, all needed is a method to get in-cluster k8s client (which kiali already does) and look for the information which is obviously not available from remote cluster. all other logic stay totally the same.
