### ISSUE TITLE
new debug message getting logged twice

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#4742]
When debug logging is enabled, I see this:

```
        "2022-02-17T15:31:01Z DBG Detected Istio version [1.13.0-75ee7514615d3a642a7eabaa0ad7c22cea1a1ed0-Clean]",
        "2022-02-17T15:31:01Z DBG Detected Istio version [1.13.0-75ee7514615d3a642a7eabaa0ad7c22cea1a1ed0-Clean]",
```

We should not be logging this twice. One time is good enough.

cc @Xunzhuo (I think this came in as part of your recent PR that was merged)

**Comment by Xunzhuo** [comment]
Hi @jmazzitelli, I have started a PR to fix this, please take some time to review it thanks:)
