### ISSUE TITLE
 Reduce the number of requests to fetch health data on list pages

### ISSUE THREAD

**Issue by aljesusg** [kiali/kiali#4748]
Epic: https://github.com/kiali/kiali/issues/4611

List in Kiali-UI have a lot of requests to health. Case of Workloads.

If the List is filtered (for example only one) Kiali fetch health for all workloads instead filtered
If the List is filtered with N namespaces kiali fetch health for N x W (workloads per namespaces)

![Screenshot from 2022-02-21 09-04-17](https://user-images.githubusercontent.com/3019213/154928447-8734c9e0-182d-48a0-8c93-eefb533b48cc.png)
![Screenshot from 2022-02-21 08-56-48](https://user-images.githubusercontent.com/3019213/154928486-61b5627c-b769-4293-b0ad-0db543942ee0.png)

Proposals:

- Check health when we fetch workloads x namespace
- Add filter options to this endpoints to make the request faster in the backend and not in the front.

**Comment by Xunzhuo** [comment]
I am +1 for this too. I think we should reduce the number of requests, especially bring heavy pressure to both front-end and backend in large scale.
