### ISSUE TITLE
consolidate version checking

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#4759]
We recently had a community contribution to check version compatibility.

It turns out, we had the same feature (only more simplified) already.

We need to consolidate all of this code. Rip out duplicate features, and consolidate what we want to keep. We now have 2 places to update version compatibility (and we couldn't even remember to update the one we already had - now we have 2 places).

See: https://github.com/kiali/kiali/discussions/4750#discussioncomment-2246862

**Comment by Xunzhuo** [comment]
I would like to assign this :)

**Comment by jshaughn** [comment]
I haven't looked but I think we'd want to keep the new approach.
