### ISSUE TITLE
Getting UI errors while rasponse is taking longer

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#4767]
Happens when debugging the Kiali Config list and have brakepoints in backend.

UI fails while waiting for response:
![Screenshot from 2022-03-01 13-35-51](https://user-images.githubusercontent.com/604313/156170129-47fe4092-51f8-40b0-930d-739bbb520733.png)

**Comment by hhovsepy** [comment]
![Screenshot from 2022-03-01 13-46-17](https://user-images.githubusercontent.com/604313/156171439-420ae099-d7f1-4b9a-8699-0ca70c7d315a.png)

**Comment by lucasponce** [comment]
Not sure if this should be a normal bug.
But it sounds right to set up also a timeout in the Axios/client-side, to prevent some corner case, like the response never finishes.

I think, there is a default one, so perhaps this error is also due to the dev environment.
