### ISSUE TITLE
Istio Config:  Preview button is disabled in Authorizationpolicy Deny Rule

### ISSUE THREAD

**Issue by pbajjuri20** [kiali/kiali#4771]
Steps to reproduce:

1. Deploy Upstream Istio + Bookinfo
2. open the Kiali_UI
3. Click on "Istio_Config" (left-side panel)
4. Click on "Actions" (right-side panel)
5. Create an "AuthorizationPolicy" 
6. Follow the below screenshot Parameters to create "Authorizationpolicy" -->   Preview button is Disabled 

![preview_button](https://user-images.githubusercontent.com/55099523/156255988-ffe89300-82dd-4131-a729-9d9b13748c7e.png)

**Comment by aljesusg** [comment]
Hi @pbajjuri20 you have a warning message that says that you need to add the rule. Did tou click to the + button?

**Comment by pbajjuri20** [comment]
@aljesusg : Thanks for the clarity, I have verified with the rule. I'm able to see "preview"
