### ISSUE TITLE
Misconfigured `istiod_deployment_name` causes a panic

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#4788]
When `istiod_deployment_name` in the kiali CR != actual istiod deployment name the kiali server panics. [Here](https://github.com/kiali/kiali/blob/master/business/services.go#L289) the return value can be nil even if err is nil causing a panic when trying to access `cluster.Name`. The error should be handled gracefully instead of panicing.

Steps to reproduce:
1. Deploy kiali with an alternate `.spec.external_services.istio.istiod_deployment_name` that does not match the actual deployment name (by default `istiod`).

**Comment by Xunzhuo** [comment]
I would like to assign and fix this :)

**Comment by nrfox** [comment]
Sure that'd be great
