### ISSUE TITLE
Reduce the number of requests to fetch health data on detail pages

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#4790]

**Comment by nrfox** [comment]
Done as part of https://github.com/kiali/kiali/pull/4772. Closing this as a duplicate.

**Comment by lucasponce** [comment]
Is this a duplicate? I'm talking with @aljesusg about it at https://github.com/kiali/kiali/pull/4763#issuecomment-1066641178 ?

**Comment by aljesusg** [comment]
The point is that we thought that in detail pages we are fetiching so times the health endpoints and we saw that not.

But we can address the comment that @lucasponce said @nrfox . What do you think?

**Comment by lucasponce** [comment]
> The point is that we thought that in detail pages we are fetiching so times the health endpoints and we saw that not.

I think in the details pages there are two types of calls: 
- The ones that come from the minigraph that are already addressed in @israel-hdez's work.
- A separated call in the Overview tab to populate the health icon.

The calls from the minigraph are being worked on in that effort, but then we will have a pending call for the overview.

With that, then we can move the health endpoints to an internal point and also improve the overall performance.

**Comment by israel-hdez** [comment]
Yes, we didn't see wrong a single call to fetch health. I think that was the reason why we closed this.
But we certainly can embed health to the app/workload/service detail endpoints to make it an internal service.

The overview page would be a different issue to this one, I think.

**Comment by nrfox** [comment]
Embedding the health into the app/workload/service endpoints would require moving some of the health calculations from the UI side to the server side wouldn't it? iirc we weren't planning on doing that with the initial refactoring.

**Comment by israel-hdez** [comment]
> would require moving some of the health calculations from the UI side to the server side wouldn't it?

I was thinking more into embedding whatever JSON the health endpoint returns to the app/workload/service endpoints.
It is the same approach that we have taken for lists and the graph.

**Comment by lucasponce** [comment]
Duplicated of https://github.com/kiali/kiali/issues/4748
