### ISSUE TITLE
Excessive Memory consumption by Kiali-Operator

### ISSUE THREAD

**Issue by prary** [kiali/kiali#4792]
We are running Kiali-Operator deployment with 2 replicase in k8s cluster and each one has a resource limit of 10Gi and 8 CPU.
Only one Kiali custom resouce has being deployed and we are seeing frequent restarts for the operator pod due to OOMKilled.
Have also noticed additional thing we have around 1800 ns in that cluster.

```
kubectl -n spyder-kiali-operator top po
NAME                                     CPU(cores)   MEMORY(bytes)
kiali-operator-557b4bfc5f-lsjf2   9m           9915Mi
kiali-operator-557b4bfc5f-wd5mt   1389m        9337Mi

```

Operator & kiali version used is v1.32.0. 
Can anyone help us setting the right limits for the operator pod so that we don't see OOMKilled and is there a way to optimise the resources allocated to it 10Gi seems extremely heavy.

**Comment by jmazzitelli** [comment]
That does seem really heavy. I don't think we've had anyone report the operator needing over 10GB memory. Something seems wrong. Have you tried a newer version of the operator? 1.32 is fairly old - we are up to 1.47 now. If the newer version still has the issue, we'll want to talk to the ansible operator SDK folks about this since the Kiali Operator is nothing more than some ansible scripts running in the operator SDK container.

I guess I should ask - how big is the cluster that Kiali is observing? How many namespaces specifically? And are you asking the operator to give Kiali access to a specific list (i.e. what is your Kiali CR's `spec.deployment.accessible_namespaces`)?

Also, when you install the operator (which I assume you did using the helm chart) what is the `resources` setting you provided (if any) when you installed it via helm? I am referring to this: https://github.com/kiali/helm-charts/blob/master/kiali-operator/values.yaml#L16-L19

**Comment by prary** [comment]
Hi @jmazzitelli 

Number of namespaces - 1722
Number of spec.deployment.accessible_namespace - 2 namespaced being observed

resources:
  limits:
    cpu: "8"
    memory: "10Gi"
  requests:
    cpu: "500m"
    memory: "500Mi"


Latest operator image has few CVE's, once those CVE's are fixed will definitely try to update it

**Comment by jmazzitelli** [comment]
OK, it is possible with that huge number of namespaces, it is causing a problem. I do remember a while back we did some performance enhancements regarding large number of namespaces. I would be curious what happens with a newer operator.

Also, I would just make sure you really are setting spec.deployment.accessible_namespaces (make sure there is no typos and its value is a list of strings). After the operator finishes, it will create a `status` field in the Kiali CR that tells you what accessible namespaces it uses (so look at the Kiali CR's `status` field and look for the `accessibleNamespaces` setting. Though it is possible that isn't there in v1.32 of the operator - that was a relatively new addition to the status field).

**Comment by prary** [comment]
Hi @jmazzitelli ,

Here is the `kubectl describe kiali`
```
Status:
  Accessible Namespaces:  ns1,ns2
  Conditions:
    Ansible Result:
      Changed:             17
      Completion:          2022-03-10T15:04:30.985961
      Failures:            0
      Ok:                  177
      Skipped:             84
    Last Transition Time:  2022-03-08T04:11:58Z
    Message:               Awaiting next reconciliation
    Reason:                Successful
    Status:                True
    Type:                  Running
  Progress:
    Duration:  0:02:07
    Message:   17. Finished
Events:        <none>
```

**Comment by prary** [comment]
Hi @jmazzitelli any updates on this?

**Comment by jmazzitelli** [comment]
> I do remember a while back we did some performance enhancements regarding large number of namespaces. I would be curious what happens with a newer operator.

no updates. Did you upgrade and try the latest operator?

**Comment by jmazzitelli** [comment]
Another useful thing you could do to help track this down - turn on the profiler in the operator. Once you turn it on, get the operator to perform another reconciliation that shows high memory usage (edit the CR or create a new one), and then look at the profiler report in the operator pod logs (which are printed out at the end of the log after the reconciliation is done). It might be useful to see if there are specific ansible tasks the operator is spending a lot of time in.

To turn on the profiler, set the `debug.enableProfiler` helm value to `true` when you install the operator: https://github.com/kiali/helm-charts/blob/master/kiali-operator/values.yaml#L30-L34

If you want to turn on/off the profiler in an already installed operator without using helm, you can do this: https://kiali.io/docs/faq/installation/#operator-configuration -- specifically set the ANSIBLE_CONFIG env var... note it says, `ANSIBLE_CONFIG: must be /etc/ansible/ansible.cfg or /opt/ansible/ansible-profiler.cfg. If set to /opt/ansible/ansible-profiler.cfg a profiler report will be dumped in the operator logs after each reconciliation run.`

**Comment by jshaughn** [comment]
Closing, as it's not clear what further action to take and there have been many updates to the operator since this was reported.
