### ISSUE TITLE
"Could not fetch services list" Error

### ISSUE THREAD

**Issue by AlexanderSarson** [kiali/kiali#4793]
We get "Could not fetch services list" Error in namespaces where we have serviceEntry but no services. 
I can see if i press f12 and under network tab that it receives services just fine.
If i add an empty service to the namespace it fixes the issue. For example:
kubectl create service clusterip test --clusterip="None" -n test

Steps to reproduce:
Create new namespace
Create a serviceEntry
Try to get services from that namespace

Versions:
Kiali Server v1.46.0
Istio v 1.12.1

**Comment by lucasponce** [comment]
Thanks.
I'd say it looks like a case/edge not managed with all the refactoring through the Istio registry.
cc @hhovsepy

**Comment by hhovsepy** [comment]
The fix will be release with Kiali v1.48.
