### ISSUE TITLE
Kiali and Kiali Operator Image Vulnerabilities

### ISSUE THREAD

**Issue by Vineeth-varma** [kiali/kiali#4809]
Have observer few Critical and High Vulnerabilities for Kiali Operator and Kiali Images.

How to resolve these Vulnerabilities, If there is by any chance I can fix these please help me out.

**Comment by lucasponce** [comment]
Hi @Vineeth-varma thanks for the issue.
I've removed the list of vulnerabilities to a private list as the proper way to report security issues is as described under:
https://github.com/kiali/kiali/blob/master/SECURITY.md

I'm going to comment them with the team.

**Comment by lucasponce** [comment]
Closing.
Vulnerabilities should be reported through the SECURITY channels and those are being addressed in the following updates.
