### ISSUE TITLE
add the ability to add annotations to configmap.yaml

### ISSUE THREAD

**Issue by ceastman-r7** [kiali/kiali#4814]
please add something like:

{{- with .Values.annotations }}
  annotations:
{{ toYaml . | indent 4 }}

to the metadata section:
apiVersion: v1
kind: ConfigMap
metadata:

this will allow people to add annotations to a values.yaml override file.

**Comment by ceastman-r7** [comment]
For me it is so I can tell spinnaker to not create versions of the config map via:

annotations:
  'strategy.spinnaker.io/versioned': 'false'

**Comment by jmazzitelli** [comment]
PRs that will implement this (still WIP; PRs are in draft mode - I'm in the middle of testing. But so far it looks like its working)
* https://github.com/kiali/kiali-operator/pull/503
* https://github.com/kiali/helm-charts/pull/128

**Comment by jmazzitelli** [comment]
PRs are done and tested. The operator PR has a molecule test that shows it passing. The helm chart PR I tested by doing the provided test procedures found in [this PR comment](https://github.com/kiali/helm-charts/pull/128#issuecomment-1072843289).
