### ISSUE TITLE
Include more settings to clear when resetting to factory settings

### ISSUE THREAD

**Issue by leandroberetta** [kiali/kiali#4817]
Today the factory reset button only affects on the Graph toolbar (the top part) but is not resetting the layout, namespace layout and the new edge options.

This issue is for add this capabilities to the factory reset button.

The configuration to add are in:

![graph_reset](https://user-images.githubusercontent.com/1286393/158888355-b70cbac0-3d12-400a-8982-e5787389b8f7.png)

**Comment by jshaughn** [comment]
This seems straightforward on the surface, but proved difficult  A few attempts to add this feature caused problems for the graph hide feature (note that the Edge hiding options use graph hide under the covers).  The code is not currently designed to handle multiple state changes and graph updates atthe same time.  In this case the work is likely not worth the feature.  And so I am closing this as "Won't Do".   If we get community demand for this enhancement we can revisit.
