### ISSUE TITLE
Transfer frontend repo into kiali repo

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#4825]
Discussion started several months ago:
https://github.com/kiali/kiali/discussions/4587

The goal is to have a single repo where changes (backend, frontend, e2e test, and UI test) can be atomically reducing the "churn".

This will affect Kiali 1.49.x+ version and future, older versions will remain unchanged until end-of-support.

Taking the https://github.com/openshift/console as an example, we can introduce a "frontend" folder that will contain the "kiali-ui" repo as a first step.

This will require to review of the "make" targets and pipelines, both in upstream and downstream systems.

**Comment by jmazzitelli** [comment]
Going to affect some of the hack scripts and Makefiles.

**Comment by jmazzitelli** [comment]
FWIW: I believe we should create a UI Makefile in "make/Makefile.ui" that will perform the "yarn install && yarn run build" (this will follow the pattern of everything else). I just requires a new `include` in the main Makefile and a section for the help - see: https://github.com/kiali/kiali/blob/v1.48.0/Makefile#L167-L170

Then we can trigger the UI build as a dependency of the main build target if we want (or just leave the main server build targets alone and let the user run "make ui" separately if they need the UI built.

This is going to affect the Jenkins scripting, so @israel-hdez should be involved in this effort, too.
