### ISSUE TITLE
Improve the upstream pipelines

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#4827]
In parallel to the efforts of improving the testing scenarios, one epic could be to review our current pipelines based on Github actions.

For historical reasons, the project uses external Jenkins systems to perform some testing and builds.

The goal of this Epic is to study how to move all the upstream pipelines from private systems to Github actions and also how to better organize the current flows to have a better picture of the tasks performed.

Also, there is a parallel goal to include the e2e and future cypress UI testing on the pipelines, so a better organization would help to scale on these scenarios as well.

Github actions allow defining flows that can help to understand the logic, an example like this (from another related project) may help as inspiration:

![image](https://user-images.githubusercontent.com/1662329/159447486-bdc6a77c-8799-41fb-abd5-afb4a3d076ab.png)

Compared with our current flow:

![image](https://user-images.githubusercontent.com/1662329/159447546-b6b7eef3-92f8-4194-8448-c34610f211d1.png)

**Comment by leandroberetta** [comment]
The release pipelines were modified to being triggered on the following Monday after the end of the sprint.
