### ISSUE TITLE
Review data caching of health endpoints

### ISSUE THREAD

**Issue by israel-hdez** [kiali/kiali#4829]
As noted in #4611, data caching of health endpoints should be reviewed. If possible, new data should be cached to memory in order to improve response times of health calculations.

Some points to take into accounts:
* It is OK if health indicators are no longer "real-time". Having "near real-time" health is OK as long as performance increase is significant.
* If needed, some logic in the front-end may be migrated to the back-end.
* The amount of memory usage is probably not a concern.

**Comment by lucasponce** [comment]
Could you elaborate on this issue?
The Prometheus queries used for health calculation are already cached.

**Comment by lucasponce** [comment]
It's interesting but I think it's a change of paradigm as related to the discussion of a "model" that is being stored in the backend and updated asynchronously.

I think this idea can be related to those efforts instead to be addressed separately.

**Comment by israel-hdez** [comment]
> related to the discussion of a "model" that is being stored in the backend and updated asynchronously.

Right, this probably belongs to that discussion.

**Comment by jshaughn** [comment]
Closing this, it can be revisited as part of future optimization work.
