### ISSUE TITLE
Hack script to create a Kind cluster in CI

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#4833]
Probably [this script](https://github.com/kiali/kiali/blob/master/hack/ci-kind-molecule-tests.sh) can be reused without the molecule parts since this script is already:
- Creating a Kind cluster
- Installing Istio
- Installing bookinfo
~- Installing the Kiali operator~
- Installing Kiali

Epic: https://github.com/kiali/kiali/issues/4827

**Comment by jmazzitelli** [comment]
we have this too - it creates two clusters but code can be stolen. https://github.com/kiali/kiali/blob/master/hack/istio/multicluster/start-kind.sh

**Comment by nrfox** [comment]
We'll need to take into account linked PRs even when the front-end and back-end repos are combined. When there's a kiali config change that requires an operator change, we'll need to deploy the right version of the operator to run the CI tests against. We usually link these with comments on the PR discussion like: `Operator PR: #PR-Num`. Perhaps we can formalize that where if an issue contains a "required-operator" label then we'll search for the operator PR link in the comments and run that version of the operator. It looks like the ci-kind script [has support](https://github.com/kiali/kiali/blob/master/hack/ci-kind-molecule-tests.sh#L338-L350) for something similar already, we'll just need to agree on a convention and add support for getting the label info and PR from the github API.

**Comment by lucasponce** [comment]
Note that for the e2e in upstream we don't even need to build the UI or the operator.
Just create the cluster (with Istio and the demos), open a proxy, and launch a Kiali backend process pointing to it.
That would help to cover all the e2e testing, and probably would be faster than the current pipelines.

The pipelines building the UI and the operator are good but are slow and they can't run on every PR (but can be used for daily testing).

**Comment by jmazzitelli** [comment]
> we don't even need to build the UI or the operator.

Right - for these e2e backend api tests, there is really no need to build the operator and install via the operator (and it will be quicker to run the tests if you don't).

We have molecule testing that will catch any operator errors.

**Comment by nrfox** [comment]
> Note that for the e2e in upstream we don't even need to build the UI or the operator.

I'm assuming this hack script will be used for both the e2e API tests _and_ the e2e front end tests using cypress. In both cases you'll need the same environment setup. You're right, we don't need to deploy/test the operator here and it'll make things simpler to deploy kiali independently.

> The pipelines building the UI and the operator are good but are slow and they can't run on every PR (but can be used for daily testing).

The molecule tests do take awhile and we can probably get similar/better coverage with running the e2e but imo we should also run the UI cypress integration tests against every PR. Setting up the environment takes only 5-10 minutes from what I've seen. I've never run the e2e suite before but those are hopefully quick. The cypress tests should be relatively fast as well. Potentially we can run both the e2e suite and the cypress tests in parallel as separate workflows.
