### ISSUE TITLE
fatal error: concurrent map writes

### ISSUE THREAD

**Issue by FilipB** [kiali/kiali#4842]
During our perf test suite following error was thrown to kiali pod log and the pod was restarted:
```
fatal error: concurrent map writes
fatal error: concurrent map writes

goroutine 775 [running]:
runtime.throw({0x1cfc0ce, 0xc000ac9ea4})
	/usr/local/go/src/runtime/panic.go:1198 +0x71 fp=0xc00157b1f0 sp=0xc00157b1c0 pc=0x4349f1
runtime.mapassign_faststr(0x1a39ce0, 0xc0003f10e0, {0x1cee197, 0xc})
	/usr/local/go/src/runtime/map_faststr.go:294 +0x38b fp=0xc00157b258 sp=0xc00157b1f0 pc=0x412fcb
github.com/kiali/kiali/status.Put(...)
	/home/fedora/go/src/github.com/kiali/kiali/status/status.go:87
github.com/kiali/kiali/status.istioVersion()
	/home/fedora/go/src/github.com/kiali/kiali/status/versions.go:264 +0x2e7 fp=0xc00157b400 sp=0xc00157b258 pc=0x15a7027
github.com/kiali/kiali/status.getVersionComponent(...)
	/home/fedora/go/src/github.com/kiali/kiali/status/versions.go:83
github.com/kiali/kiali/status.getVersions()
	/home/fedora/go/src/github.com/kiali/kiali/status/versions.go:78 +0x1b8 fp=0xc00157b4b8 sp=0xc00157b400 pc=0x15a5e58
github.com/kiali/kiali/status.Get()
```

Full pod's log is attached.
I don't have repro steps but I will try to add more details if I manage to reproduce.
[kiali-666fc6c49f-sbqpz-kiali.log](https://github.com/kiali/kiali/files/8341079/kiali-666fc6c49f-sbqpz-kiali.log)

OCP  4.10.4

Kiali UI
    1.49.0 (3c6a422344504f6771ca774bb458df4db0ac667f)
Kiali Server
    v1.49.0-SNAPSHOT (06558edfe99da98ff98f4b3baa73635f7a30e573)
Kiali Container
    v1.49.0-SNAPSHOT

Components

Istio
    1.13.2 
Prometheus
    2.31.1 
Kubernetes
    v1.23.3+e419edf

**Comment by jmazzitelli** [comment]
This is triggered by the new code added by @Xunzhuo for the version matrix check. It came in as part of this PR: https://github.com/kiali/kiali/pull/4690

Looks like we need to add concurrency checks around Put() here: https://github.com/kiali/kiali/blob/v1.48.0/status/status.go#L84-L89

**Comment by Xunzhuo** [comment]
Should we add a lock here?

**Comment by jmazzitelli** [comment]
> Should we add a lock here?

Yes. Definitely need a RW lock here.

**Comment by jmazzitelli** [comment]
backport PR: https://github.com/kiali/kiali/pull/4846

**Comment by FilipB** [comment]
Re-opening, it seems there is one more place to be fixed or the fix did not help:
```
github.com/kiali/kiali/status.istioVersion()
	/home/fedora/go/src/github.com/kiali/kiali/status/versions.go:258 +0x1aa fp=0xc000dd9400 sp=0xc000dd9258 pc=0x15a70ca
github.com/kiali/kiali/status.getVersionComponent(...)
	/home/fedora/go/src/github.com/kiali/kiali/status/versions.go:83
github.com/kiali/kiali/status.getVersions()
	/home/fedora/go/src/github.com/kiali/kiali/status/versions.go:78 +0x1b8 fp=0xc000dd94b8 sp=0xc000dd9400 pc=0x15a6038
github.com/kiali/kiali/status.Get()
	/home/fedora/go/src/github.com/kiali/kiali/status/status.go:107 +0xbe fp=0xc000dd9570 sp=0xc000dd94b8 pc=0x15a5c9e
github.com/kiali/kiali/handlers.getStatus({0x1f9b980, 0xc00b544318}, 0x1c0c7a047252)
```
Attaching full kiali pod
[kiali-pod.log](https://github.com/kiali/kiali/files/8349347/kiali-pod.log)

**Comment by Xunzhuo** [comment]
It seems like there is one more place to fix, thanks for testing this

**Comment by Xunzhuo** [comment]
A PR will be sent to fix this.

**Comment by Xunzhuo** [comment]
Hi @FilipB , can you help test if fatal occurs on this PR?

**Comment by FilipB** [comment]
@Xunzhuo running tests against https://github.com/kiali/kiali/pull/4856
It will take some time, the issue is not always visible. I need to run it multiple times to be sure.

**Comment by jmazzitelli** [comment]
backport PR: https://github.com/kiali/kiali/pull/4858
