### ISSUE TITLE
docs: update dev setup since merged kiali-ui

### ISSUE THREAD

**Issue by Xunzhuo** [kiali/kiali#4844]
See: https://github.com/kiali/kiali/blob/master/make/Makefile.build.mk#L3

Should we update here: https://github.com/kiali/kiali#developer-setup ?

Replace:

```
# Build the back-end and run the tests
cd $KIALI_SOURCES/kiali
make build test

# Build the front-end and run the tests
cd $KIALI_SOURCES/kiali/frontend
yarn && yarn build && yarn test
```

With:
```
# Build the back-end and run the tests
cd $KIALI_SOURCES/kiali
make build test

# Build the front-end and run the tests
make build-ui
```

**Comment by jmazzitelli** [comment]
Note that the README also talks about running the tests - `build-ui` doesn't do that. So perhaps we need to keep the instructions here for "yarn test" for those people that want to run the test. We might want to also have a `build-ui-test` target, now what I think about it.

**Comment by Xunzhuo** [comment]
Yes, so do I. I would like to send a PR to do this :)
