### ISSUE TITLE
docs: add missing required metrics

### ISSUE THREAD

**Issue by Xunzhuo** [kiali/kiali#4845]
See: https://kiali.io/docs/faq/general/#which-istio-metrics-and-attributes-are-required-by-kiali

According to https://github.com/kiali/kiali/blob/master/graph/telemetry/istio/istio.go#L149

Kiali required these two metrics in grpc traffic:
+ "istio_request_messages_total"
+ "istio_response_messages_total"

**Comment by jmazzitelli** [comment]
cc @jshaughn

**Comment by jshaughn** [comment]
This was updated in https://github.com/kiali/kiali.io/pull/541.
