### ISSUE TITLE
Logout-login loop for OpenShift authentication

### ISSUE THREAD

**Issue by israel-hdez** [kiali/kiali#4848]
When using OpenShift authentication it is potentially possible to enter in a "logout-login loop":

While already logged into Kiali, when using the "Logout" option in the masthead Kiali will properly invalidate the OpenShift token and, then, it will do a redirection to the authorization endpoint of the OpenShift OAuth server. Possibly, this redirection to the OAuth endpoint was done with the expectation that the OpenShift OAuth server would show the login form and this would help a little the user to reduce the amount of steps to re-login (i.e. no need to click "Login with OpenShift" in the Kiali-UI).

However, if the user is somehow already logged into OpenShift (i.e. when using a 3rd party SSO), the OAuth server may re-use that previous session and will simply redirect back to Kiali with a _fresh_ access token without asking for any credentials. Kiali will, then, re-login the user immediately. This can happen quite fast and gives the perception that Kiali is not doing logout properly.

**Comment by israel-hdez** [comment]
Honestly, I don't know.
This behavior is seen on IBM Cloud.

My thought is that it does not make sense to show a "Logout" button when OpenShift is using a 3rd party system for authentication. I'm not sure if it is possible to detect that.

**Comment by jshaughn** [comment]
This can serve to document the behavior.  Closing this for now, as there is no clear step forward, nor a complaint.
