### ISSUE TITLE
Kiali image builds in Github Actions

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#4850]
Build and push Kiali container images to quay.io in Github Actions. The build/push job should be triggered when a new release is created and the images should be tagged with the version of that release. This is currently happening in Jenkins but it should be moved to Github Actions.

Epic: https://github.com/kiali/kiali/issues/4827

**Comment by Xunzhuo** [comment]
I am happy to help to make this happen, please assign this to me :)
BTW, if we want this, we need to set some github secrets for ci to read:
+ secrets.QUAY_USERNAME 
+ secrets.QUAY_TOKEN

**Comment by lucasponce** [comment]
Hi, @Xunzhuo I think @leandroberetta has started to work on this as part of the https://github.com/kiali/kiali/issues/4827 (thanks @nrfox for creating the subtask.

We have another big epic coming which is to improve the UI testing as we are incorporating the "cypress" framework.

That task would require a nice collaboration and it would be really nice if you'd like to help us with that.

(I'm going to create the Epic, it was on my to-do list for this week).

**Comment by Xunzhuo** [comment]
Hi @lucasponce, thanks for commenting, if @leandroberetta has started, I am also willing to help on improving the UI testing, some details can be discussed in https://github.com/kiali/kiali/issues/4854

**Comment by leandroberetta** [comment]
Hi everyone, as @lucasponce mentioned I started last friday with this one!.

**Comment by leandroberetta** [comment]
This issue will be resolved by https://github.com/kiali/kiali/pull/4980.
