### ISSUE TITLE
README - Developer setup part contains incorrect go lang verision

### ISSUE THREAD

**Issue by FilipB** [kiali/kiali#4853]
Following part https://github.com/kiali/kiali#developer-setup contains:
`Currently, Kiali releases are built using Go 1.16. Although Kiali may build correctly using other versions of Go, it’s suggested to use version 1.16.2 for development to ensure replicatable builds. Makefiles will require this minimum version of Go.`
But makefile actually requires at least '1.17.7'

**Comment by jmazzitelli** [comment]
someone already reported this and is fixing - see: https://github.com/kiali/kiali/pull/4852

**Comment by FilipB** [comment]
Sorry, I missed that. Closing. Thank you.
Duplicate of (https://github.com/kiali/kiali/issues/4851)
