### ISSUE TITLE
Kiali and Istio validation messages should be placed together

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#4864]
This is an improvement of the sidepanel in the Istio Config details.

I think that the "KIA0301" message should be also be referenced in the "Configuration Analysis" section on the side panel.

The current inline warning is good, this issue is an enhancement to place them together in the side panel.

![image](https://user-images.githubusercontent.com/1662329/160378651-7747ac3e-3a8a-41e6-b67d-40b79ce92f80.png)

Perhaps with this change, the validation icon on the resource name:
![image](https://user-images.githubusercontent.com/1662329/160378944-c5dee8b4-c442-45d9-b3af-1eac9eaaa50c.png)

is not necessary if we are going to list the validation issues.

**Comment by hhovsepy** [comment]
Hi @lucasponce, can you still see the "Configuration Analysis" section in side panel?

**Comment by lucasponce** [comment]
The configuration analysis messages are not enabled by default, those are defined at the mesh level at the installation phase (I think). 

I typically setup my cluster with these flags:

```
# --set values.global.istiod.enableAnalysis=true
# --set values.pilot.env.PILOT_ENABLE_STATUS=true
```

to enable them
