### ISSUE TITLE
Kiali shows "networking.istio.io/v1alpha3" apiVersion even though we are using "networking.istio.io/v1beta1"

### ISSUE THREAD

**Issue by unixmind** [kiali/kiali#4894]
**Istio shows "v1alpha3" version :**

![istio-wrong-apiversion](https://user-images.githubusercontent.com/19151638/161499317-c9897f95-8769-4bd3-90a1-520b01aee084.jpg)

**But we use "v1beta1" version:**
``` sh
# kubectl -n istio-google get virtualservices frontend -o jsonpath="{$.apiVersion}{'\n'}"
networking.istio.io/v1beta1
```

**Comment by lucasponce** [comment]
Thanks for the issue.
Yes, the kind/apiVersion is not returned by default and that data should be in sync with the Istio version.

Just to confirm, which Istio + Kiali version are using?

**Comment by unixmind** [comment]
Hi,

We're using those images:

* Kiali
quay.io/kiali/kiali:v1.48.0

* Istio
docker.io/istio/pilot:1.13.2
docker.io/istio/proxyv2:1.13.2

Regards.

**Comment by lucasponce** [comment]
Thanks! I'll review the Istio client used for this.

**Comment by lucasponce** [comment]
I think this code could easily go into the "frontend" one ?
![image](https://user-images.githubusercontent.com/1662329/162715255-077cf5a7-8b7a-45eb-9495-4dc04e914d9e.png)
![image](https://user-images.githubusercontent.com/1662329/162715365-e629a5b7-5a41-481d-97d0-b6d09c6980e5.png)

Is it a check of a value in two files, I don't think it requires launching another VM for it.

In any case @leandroberetta is organizing the structure of the flows so, let's wait until he comments.

**Comment by lucasponce** [comment]
As commented in https://github.com/kiali/kiali/pull/4938#issuecomment-1102540303 the API machinery doesn't use one version or another, the default behavior is to use the latest one even if you have created a resource using the v1alpha3 (as it's shown in the example with kubectl).

Now Kiali would be in sync with regular usage and we will be updating these APIs as soon as they bump up versions.
