### ISSUE TITLE
Kiali UI and Kiali Server can point to a single commit

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#4895]
I think splitting the commits in the backend/frontend in the "about" modal is no longer necessary:
![image](https://user-images.githubusercontent.com/1662329/161504819-8829b617-0c83-4515-a28b-6b88a24d2aab.png)

It can point now to the last commit of the built.

**Comment by aljesusg** [comment]
You think not....is no necessary :) +1 on this !
