### ISSUE TITLE
Add outboundTrafficPolicy value to overview istio-system card 

### ISSUE THREAD

**Issue by ceastman-r7** [kiali/kiali#4896]
This would be helpful to see what the current outboundTrafficPolicy is set to.

<img width="516" alt="Screen Shot 2022-04-04 at 8 05 16 AM" src="https://user-images.githubusercontent.com/97614291/161550532-ee073408-d8f8-451c-a82f-5e6cd9135378.png">

**Comment by lucasponce** [comment]
Thanks! Yes, +1, I agree.
This namespace overview summary is focused on the "inbound traffic" but it makes all sense to offer both.

**Comment by hhovsepy** [comment]
One idea of UX is to add a Traffic direction dropdown in Overview toolbar to show 'Outbound' or "Inbound" traffics:
![Screenshot from 2022-05-24 17-20-03](https://user-images.githubusercontent.com/604313/170073026-77f310c1-f5fe-4059-95db-68f4bf0597e2.png)

**Comment by lucasponce** [comment]
cc @andrew-ronaldson

**Comment by andrew-ronaldson** [comment]
There needs to be some padding following the Apps dropdown before traffic direction text. Could I see a screenshot with the full screen, please. Thanks

**Comment by hhovsepy** [comment]
padding sure will be added, screenshot of the suggested solution:
![Screenshot from 2022-05-24 22-53-12](https://user-images.githubusercontent.com/604313/170130284-6e6052f3-97de-45c9-a774-397c030f219d.png)

**Comment by andrew-ronaldson** [comment]
what is the "ops" below applications? If it is an axis label for the chart there should be some padding between the list and the chart

**Comment by leandroberetta** [comment]
> what is the "ops" below applications? If it is an axis label for the chart there should be some padding between the list and the chart

Yes, it is the axis label. Do you mean bring the "ops" closer to the chart, separating it a little bit of the other section?. 

Another comment not related direclty with this issue but, would be better to change ops for req (requests)?.

**Comment by andrew-ronaldson** [comment]
If there was a vertical line on the chart it would be clearer that ops is the label on that axis. With the ops and outbound traffic on the same if you add some space above it would help break up the content in the card.

**Comment by hhovsepy** [comment]
The OutBoundTrafficPolicy.Mode will be shown in Overview page when configured:
![Screenshot from 2022-06-24 12-29-04](https://user-images.githubusercontent.com/604313/175648701-8b91782b-caa6-4b3e-9e44-e91c6e2f2b89.png)

**Comment by hhovsepy** [comment]
The feature will be released in upcoming Kiali v1.53.
