### ISSUE TITLE
Report resource usage for the mesh

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#4897]
On the "mesh" page, it would be helpful for Kiali to report resource overhead (CPU and memory) for the mesh. This includes resources for both the controlplane (istiod/gateways) as well as the sidecars. Kiali should already have access to this information and these are useful metrics to know.

![Screenshot from 2022-04-04 09-38-06](https://user-images.githubusercontent.com/6226732/161556346-8aefa70f-2a25-4d44-a2bd-843962686065.png)

**Comment by lucasponce** [comment]
This is part of the whole discussion about this https://github.com/kiali/kiali/issues?q=is%3Aissue+is%3Aopen+explicit

**Comment by lucasponce** [comment]
And note that this information is available today under the overview page -> Control plane actions

**Comment by nrfox** [comment]
> And note that this information is available today under the overview page -> Control plane actions (special Grafana links for the control plane)

Ah Kiali links to a Grafana page that shows this information? Probably why I've never seen it :)

**Comment by jshaughn** [comment]
This mem/cpu info is now displayed on the Control Plane Card. Closing as Done.
