### ISSUE TITLE
Feature Request: Remember filter settings in graph view.

### ISSUE THREAD

**Issue by denniseffing** [kiali/kiali#494]
**General remarks**
As of now, Kiali doesn't remember filter settings of the graph view.

**Versions used**
Kiali: v0.6
Istio: v1.0.2
Kubernetes flavour and version: Kubernetes 1.10

**To Reproduce**
1. Go to Graph view in Kiali Dashboard
2. Click on any dropdown filter menu and set the filter of your choice (must vary from the default setting for obvious reasons). 
3. Go to any other view in the Kiali Dashboard (e.g. Workloads or Services).
4. Go back to Graph view.
5. Filter settings are reset to default.

**Expected behavior**
Filter settings of the graph view are persisted and restored when viewing the graph again.

**Comment by denniseffing** [comment]
Thanks for your fast reply. I have to admit that I didn't check the JIRA tracker (and didn't even know about it to be honest). 
However, it seems like your issue only addresses the namespace selection and it would be very convenient to remember every filter setting, not just the chosen namespace.

**Comment by pilhuhn** [comment]
That's a good point. And I recall that we discussed that already. 
https://issues.jboss.org/browse/KIALI-1400 should have this covered.

**Comment by pilhuhn** [comment]
Both Jiras have been resolved in release 0.9 and 0.10.
@denniseffing Could you try with 0.10 and report back if this now works?

**Comment by pilhuhn** [comment]
Closing as being old. Please reopen if this is still an issue.
