### ISSUE TITLE
optimize(ci): pass through some changes without triggering workflows

### ISSUE THREAD

**Issue by Xunzhuo** [kiali/kiali#5017]
Some changes are non-related to code changes, these changes should not trigger weighted workflow to run.

I list some files, which I think there is no need to trigger kiali ci:
+  `design/**`
+  `**/*.md`
+ `**/*.adoc`

We can add it after:

+ https://github.com/kiali/kiali/blob/master/.github/workflows/kiali-ci.yml#L8
+ https://github.com/kiali/kiali/blob/master/.github/workflows/kiali-ci.yml#L6

with:

``` yaml
    paths-ignore:
      - 'design/**'
      - '**/*.md'
       - '**/*.adoc'
```

**Comment by jmazzitelli** [comment]
I like this idea. cc @leandroberetta since he just did a bunch of work on the CI stuff so he will know what to do.

**Comment by leandroberetta** [comment]
Sure, I like it too. Go ahead!
