### ISSUE TITLE
add creation of olm metadata to the new github release workflow

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#5025]
For epic: #4827 

see https://github.com/kiali/kiali-operator/pull/523 - we forgot to create the last release's OLM metadata.

We should add this step to our release workflow. After we release, we should have new metadata created so the next sprint can have them (in case new permissions need to be added, for example). Then, when the next sprint is released, those metadata will be inside the release branch for archival purposes. We will use this metadata to release the operator to OperatorHub.io.

This step should be relatively easy to add to the release workflow. To create the new metadata, you run these commands from within the operator repo:

```
cd manifests
./create-new-version.sh -nv <next sprint's release version> -ov <version being released> -om kiali-upstream/
./create-new-version.sh -nv <next sprint's release version> -ov <version being released> -om kiali-community/
```

We can do this at the same time (even in the same commit) when we update the Makefile to the next sprint SNAPSHOT version.

So, for example, during our last sprint, we released `1.50.0` and will now prepare to work on our next release which is `1.51.0`. So the commands we should run in our release workflow in that case is:

```
cd manifests
./create-new-version.sh -nv 1.51.0 -ov 1.50.0 -om kiali-upstream/
./create-new-version.sh -nv 1.51.0 -ov 1.50.0 -om kiali-community/
```

This will create a 1.51.0 set of metadata that we can modify as appropriate during our 1.51 work. We would then release 1.51.0 metadata to OperatorHub.io at the end of the 1.51. sprint.

**Comment by leandroberetta** [comment]
@jmazzitelli do we require this changes for patch releases too?.
