### ISSUE TITLE
Schedule release pipelines

### ISSUE THREAD

**Issue by leandroberetta** [kiali/kiali#5029]
The new GitHub actions pipelines run manually for the last release but they need to be scheduled to start in a similar way the Jenkins pipelines started in the past.

Schedule:

- After any PR merged, with no testing, quick latest container
- Minor release on the end of the sprint

For epic: #4827

**Comment by jmazzitelli** [comment]
Frankly, I don't see the value in the snapshot builds. I can honestly say I have NEVER installed a snapshot build. What is the purpose of those? Who uses them? And if they are using snapshot builds, why don't they use "latest" instead? The snapshot builds are nothing more than obsolete "latest" builds :) We don't guarantee any functionality works in the snapshot builds, just like latest.

We are just polluting our quay repo with these snapshot builds, IMO. In fact, I think someone should go through quay and delete all those old snapshot.X images.

So, my comment would be - don't do those friday snapshot builds - no one uses them that I know of, and it's just more code we have to maintain in our github action workflow.

**Comment by leandroberetta** [comment]
I'm OK stop generating snapshots. 

A latest build after a PR merged sounds ok.

**Comment by israel-hdez** [comment]
> What is the purpose of those?

I think the purpose was to provide something in-between a release and an `edge` image.

But, honestly, 3 weeks is not that much time and I think most people simply wait for the formal release.
