### ISSUE TITLE
Configure Kiali with Kiali

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#5033]
As an admin user, you should be able to configure Kiali using the Kiali UI itself. This would apply to any of the server settings (anything that shows up in the kiali configmap) but would not apply to any of the operator/deployment specific settings. This would be especially useful for configuring external services such as jaeger/prometheus/grafana. The status of these services from Kiali's perspective should be shown, basically whatever is returned by `/api/grafana` for example.

The Kiali API can update the `kiali` configmap directly or if there's an ownerref and/or `primary-resource` annotation, the Kiali API can update the Kiali CR instead.

**Comment by jmazzitelli** [comment]
> The Kiali API can update the `kiali` configmap directly or if there's an ownerref and/or `primary-resource` annotation, the Kiali API can update the Kiali CR instead.

I wonder if the user will have the permissions to do that? I can't think off the top of my head about a specific case, but I have to believe the user logged into Kiali might not have permissions to edit the Kiali CR/ConfigMap (or, the reverse - the user might have permission but the admin who created the Kiali CR doesn't want the user to have permissions).

**Comment by nrfox** [comment]
> I wonder if the user will have the permissions to do that? I can't think off the top of my head about a specific case, but I have to believe the user logged into Kiali might not have permissions to edit the Kiali CR/ConfigMap (or, the reverse - the user might have permission but the admin who created the Kiali CR doesn't want the user to have permissions).

Whether or not the user has permissions to edit the configmap or Kiali CR is something the Kiali server could check for and enable/disable editing within the UI. Same goes for readonly mode.

**Comment by lucasponce** [comment]
I don't think there is a good tradeoff for this.

The operator has the responsibility for the configuration of the Kiali server, for demo purposes, other methods such as the helm charts should be responsible.

I agree that the configuration can be improved, and the current documentation lacks tutorials/demos for recommendations about "how to install Kiali in production" and the users need to navigate from scattered resources to learn about it.

But I don't think the right solution should be to enable a new use case in the Kiali UI to configure the external services (that is a one-time step).

That would require introducing more complexity in profiles (read-write, read-only), and also how to deal with potential reconciliation situations.

A different situation would be if we want to introduce new use cases (i.e. more flexibility in the definition of the health thresholds, or similar), then probably we want to progress on these use cases but as regular features that Kiali should handle.

**Comment by jshaughn** [comment]
I really like that this issue is motivated by trying to resolve a recurring problem for users.  But I think it's best to not introduce a new mechanism for making these sorts of updates.

I think we need to create a tutorial that makes it clear and can be repeatedly referenced for how to configure Kiali [for production].  The recent improvements on kiali.io as a reference for configuration are excellent, this would be the next step.

**Comment by Xunzhuo** [comment]
+1, a complete document of how to install and configure Kiali may be the solution to this issue.

**Comment by nrfox** [comment]
Agreed that better docs are needed and are a higher priority. I don't believe it replaces this issue though as knowing what to configure and making it easier to configure are two different things. Having a page that lets you edit the Kiali configuration _and_ shows you the status of external services in a more meaningful way than a notification would be useful. There might be some issues with letting Kiali edit it's own configuration and external tooling though. If you've deployed Kiali through helm and then edit the config through Kiali, the helm chart and Kiali config would diverge.

Probably the more useful feature here is showing the status of the external services in a more meaningful way than a notification. These are core to how Kiali functions and their status potentially changes over time causing Kiali to become degraded. Showing the status wouldn't require any API changes and could possibly be incorporated into the current "mesh" page.

**Comment by israel-hdez** [comment]
> Showing the status wouldn't require any API changes and could possibly be incorporated into the current "mesh" page.

That's something that would be nice. To use that "Mesh" page to clearly show details of the mesh status and have some place to show current configuration rather having to inspect logs...
