### ISSUE TITLE
Investigate testing demos scripts on upstream + OpenShift platform

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#5045]
I've changed from "minishift" -> OpenShift for local development and I had some issues deploying the testing apps used in the pipelines.

I'm going to review these scripts to see what could be improved to reduce the troubleshooting.

Note, I'm looking at these scripts from the upstream perspective, like a normal user that wants to install the upstream project in the platform, and they follow the upstream recommendations for OpenShift environments in particular:

https://istio.io/latest/docs/setup/platform-setup/openshift/

(This is unrelated to any product-agnostic aspect)

P.S.: Note this could help to minimize the time we spend investigating problems in the pipeline.

**Comment by lucasponce** [comment]
Environment tested:

```
$ oc version
Client Version: 4.10.3
Server Version: 4.10.3
Kubernetes Version: v1.23.3+e419edf

Installed from OpenShift CRC:

crc setup
crc start

eval $(crc oc-env)

oc config use-context crc-admin
```
Istio 1.13.3 installed from https://istio.io/latest/docs/setup/platform-setup/openshift/

Demo tests installed via hack scripts:

```
eval $(crc oc-env)
$KB/hack/istio/install-testing-demos.sh -c "oc"
```

Kiali is exposed under "http://localhost:3000" as the standard development environment.

With this environment, I only see one potential test that have failed that perhaps it may depend of platform configuration:

![image](https://user-images.githubusercontent.com/1662329/167381376-9f0557e0-d0da-4af5-9cbb-389171642e95.png)

![image](https://user-images.githubusercontent.com/1662329/167382418-1b7c7a6d-0a3b-4ae4-b9bb-b499cf6c7dc2.png)

But the rest of the testing looks solid and non-related to platform aspects, so when we have some massive error in some pipeline, the maintainer of the pipeline should review that the installation/configuration is done under the expected parameters.

For upstream, the Github actions pipeline should be the reference in case the other pipeline should mimic the configuration and steps.

Please, @israel-hdez, would you mind taking a look at that test, it was always the same that failed in my env (thanks).

**Comment by jmazzitelli** [comment]
You need to ensure you install Istio following the OpenShift specific docs.

We have a hack script that does this for you (I've been using it since forever on my local OpenShift machine) -- https://github.com/kiali/kiali/blob/master/hack/istio/install-istio-via-istioctl.sh

If you look in there, you will see that script does several specific things when installing on OpenShift.

Therefore, when installing demos and CI testing environments, it is recommended to use that hack script - it should work to installing Istio on K8s (including Minikube and Kind) and OpenShift (including CRC env).

**Comment by lucasponce** [comment]
> it is recommended to use that hack script - it should work to installing Istio on K8s (including Minikube and Kind) and OpenShift (including CRC env).

+1

**Comment by lucasponce** [comment]
I've updated my script to use the "install-istio-via-istioctl.sh", this is how I setup my local env:

```
echo "=== STOP and DELETE previous CRC ==="

crc stop
crc cleanup

echo "=== CREATE new OPENSHIFT (CRC) cluster ==="

crc setup
crc start

eval $(crc oc-env)

oc config use-context crc-admin

echo "=== Install Istio ==="

$KB/hack/istio/install-istio-via-istioctl.sh

echo "=== Starting localhost PROXIES ==="

proxy-stop
proxy-start
```

And you can see that even the flaky test about logs is gone (sorry for the noise @israel-hdez)

![image](https://user-images.githubusercontent.com/1662329/167410540-d1562bea-0f00-476a-be68-f979d2a30837.png)

So, in short, I don't see issues in the tests we are updating with the OpenShift platform.

And any non-synced pipeline should be aligned with the upstream one.

**Comment by lucasponce** [comment]
Closing this.
