### ISSUE TITLE
Unable to Browse Kiali dashboards from IE11

### ISSUE THREAD

**Issue by balan2002cbe** [kiali/kiali#507]
Getting white screen when browsing the dashboards/graphs which are created using kiali. Any help appreciated.

**Comment by mtho11** [comment]
Ah good find @balan2002cbe, @jshaughn can you take a look at this: https://issues.jboss.org/browse/KIALI-1574

**Comment by mwringe** [comment]
The underlying frameworks we are using do not support IE. We have updated the documentation to specify which browsers are supported by Kiali: https://www.kiali.io/documentation/prerequisites/#_browser_requirements

This doesn't mean we wont accept PRs to make things work better in IE, but its not something we are testing or making sure will function.

**Comment by Zegendary** [comment]
Hi @mwringe , may I ask which underlying framworks you are using that do not support IE11? I'd like to see whether I can find any solutions to it. 😃

**Comment by mtho11** [comment]
Hi @Zegendary, we are using Patternfly React 4: https://patternfly-react.surge.sh/# based on: https://www.patternfly.org/v4/.
I hope this helps you...

**Comment by Zegendary** [comment]
Thx @mtho11 .
 So can I support ie11 in the old version of kiali which using Patternfly React 3? 
Is there any suggestion? 😂

**Comment by jshaughn** [comment]
I'm afraid IE has never been supported for Kiali, and only the last two versions of Kiali.  See [here for more].(https://kiali.io/documentation/latest/getting-started/#_prerequisites)
