### ISSUE TITLE
[cypress] Sidecar injection tests sometimes fail

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#5076]
There's been a few failures with sidecar injection during unrelated test runs: 
https://github.com/kiali/kiali/runs/6429314093?check_suite_focus=true
https://github.com/kiali/kiali/runs/6411393150?check_suite_focus=true

The cause for the flakiness should be investigated and fixed.

**Comment by lucasponce** [comment]
I noticed this as well.
Added to the backlog and project, not a blocker but it's close to as it's preventing the CI to finish correctly.

**Comment by jshaughn** [comment]
Is it possible that the kebab menu item is not always visible and perhaps we need to scroll up to ensure it's on-screen?  I think cypress is supposed to actually scroll for you, but just wondering why we have this issue.  Interactively the kebab menu items are not always visible given where the list view is scrolled to.  Maybe the card view would work better.  We need to fix this, or disable the test.
