### ISSUE TITLE
Enable github pipeline to run integration tests with token auth enabled

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#5082]
Auth should be enabled by default in the e2e testing environment to make the tests more realistic to a production deployment of Kiali. Probably the most straightforward form of auth to enable for e2e environment is token auth.

**Comment by lucasponce** [comment]
I think this one is already in place cc @hhovsepy here

**Comment by hhovsepy** [comment]
Right, e2e integration tests support token for auth.
but seems this issue is about env, also '[cypress]' which confuses me

**Comment by jmazzitelli** [comment]
FWIW: our molecule tests do some basic testing of our auth -- openid, token, header, and openshift auth. One thing we do not test is the authentication flow of openid (there is a github issue on this IIRC - unless @israel-hdez did that already and I forgot :)).

**Comment by israel-hdez** [comment]
> FWIW: our molecule tests do some basic testing of our auth -- openid, token, header, and openshift auth. 

Yes, it's only basic tests.

> One thing we do not test is the authentication flow of openid (there is a github issue on this IIRC - unless @israel-hdez did that already and I forgot :)).

It is still in the list: https://github.com/kiali/kiali/issues/3287 :slightly_smiling_face:

**Comment by lucasponce** [comment]
I put it in the backlog to not forget.
The scope of this issue is just the API tests or the cypress ones?

**Comment by nrfox** [comment]
This issue is for enabling auth in the e2e CI environment which currently runs in anonymous mode: https://github.com/kiali/kiali/blob/master/hack/setup-kind-in-ci.sh#L153 for both the frontend and the backend tests. I think the "login" command in cypress will need to be updated to support token auth. It sounds like the backend tests already support token auth.

**Comment by ScriptingShrimp** [comment]
Can you please explain why frontend UI test should support backend authentication method?

**Comment by jshaughn** [comment]
@nrfox @ScriptingShrimp @israel-hdez , is this still something that should be on the sprint backlog?

**Comment by nrfox** [comment]
It'd be good to do this still to make the cypress tests more similar to a production environment. There are sometimes subtle ways the tests can fail when auth is enabled that we want to catch as well.

**Comment by israel-hdez** [comment]
Right, I remember we had an issue that was only reproducible with auth turned on. So, this issue was created to catch those kind of issues.

That said, what I remember is that the issue was in the tests rather than in Kiali, and the issue got fixed. I do think this is still valid, although I don't think it is of high priority.

**Comment by ScriptingShrimp** [comment]
@nrfox if I quote you 
> Auth should be enabled by default in the e2e testing environment
What do you mean by that environment?

**Comment by nrfox** [comment]
> What do you mean by that environment?

In the Github actions CI pipeline, Kiali runs in anonymous auth mode. This issue is about enabling auth for the Github actions CI pipeline.
