### ISSUE TITLE
Update font color on green/red labels for trace details

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#5092]
After the PF4 update, some styles would need an adjustment, this issue is to track a minor change in the trace details labels:

![image](https://user-images.githubusercontent.com/1662329/169293901-4ddfad07-765c-4ecb-8006-2999bab1ec60.png)
![image](https://user-images.githubusercontent.com/1662329/169293955-4c1d8dae-18c1-47e2-b7b1-54b9a3cb7717.png)

On green/red labels, the font color should have better contrast (white?).

This issue is also filled for new comers :-), as it can be a good one to start adding minor changes.

**Comment by MThabsheer7** [comment]
Hey @lucasponce, can I do this?

**Comment by lucasponce** [comment]
@MThabsheer7 sure, feel free to add a PR ! Thanks

**Comment by jshaughn** [comment]
@MThabsheer7 Is there a PR coming for this?

**Comment by jshaughn** [comment]
@MThabsheer7, you seem busy.  I'm going to reassign this one.  We still hope you can find time for a contribution going forward!

**Comment by josunect** [comment]
It seems pf adds a wrapper span in the label:

https://github.com/patternfly/patternfly-react/issues/2320
