### ISSUE TITLE
rename OC_COMMAND to CLIENT_EXE

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#5093]
I see the new `make test-integration` takes `OC_COMMAND` option. We call this `CLIENT_EXE` everywhere else in our make/hack scripts. We should rename OC_COMMAND to be CLIENT_EXE to be consistent with all our other tools.

OC_COMMAND: https://github.com/kiali/kiali/search?q=OC_COMMAND

See where CLIENT_EXE is what we use everywhere else: https://github.com/kiali/kiali/search?l=Shell&q=CLIENT_EXE

Assigning to @hhovsepy because I think he knows the OC_COMMAND stuff and where else it might be used (was added in this [PR](https://github.com/kiali/kiali/commit/a5bc17f6e2ba2a04f6e8275f2fcf7ca3ec42632b))

**Comment by josunect** [comment]
Done in PR 5107
https://github.com/kiali/kiali/pull/5107
