### ISSUE TITLE
Invalid certificate for https://kiali.io 

### ISSUE THREAD

**Issue by tiffon** [kiali/kiali#510]
**Describe the bug**

Visiting https://kiali.io  and see a security warning (screenshot below).

<img width="903" alt="screen shot 2018-09-20 at 6 56 32 pm" src="https://user-images.githubusercontent.com/2304337/45851130-3cf65f00-bd07-11e8-98a8-783b7f9752b3.png">

No issue when viewing http or https www.kiali.io, only when viewing https://kiali.io.

**To Reproduce**
1. Go to https://kiali.io

**Expected behavior**
Same as https://www.kiali.io

**Comment by jmazzitelli** [comment]
Known issue that was/is being discussed on the mailing list:

https://groups.google.com/d/topic/kiali-dev/IoLb15loxY4/discussion

**Comment by jmazzitelli** [comment]
Dup issue here: https://github.com/kiali/kiali.io/issues/37

**Comment by pilhuhn** [comment]
I am closing this in favour of the linked issue.
