### ISSUE TITLE
Validations missing for few keys of authorization policy conditions

### ISSUE THREAD

**Issue by prth** [kiali/kiali#5109]
`Condition Key not supported` validation error for the following keys is displayed --
1. `remote.ip`
2. `request.auth.claims`

Here is the relevant Istio document: https://istio.io/latest/docs/reference/config/security/conditions/
Out of the 13 supported keys, the validation support is missing for those two.

-----

Some screenshots of the validation errors:
<img width="1264" alt="image" src="https://user-images.githubusercontent.com/3371270/170174326-c70bb242-cb34-433f-a0cd-bc9de27b333f.png">
<img width="1259" alt="image" src="https://user-images.githubusercontent.com/3371270/170174370-c88761e7-810a-4db7-8660-dfe1eabe3503.png">
<img width="1260" alt="image" src="https://user-images.githubusercontent.com/3371270/170174404-2003a58b-1ccf-4579-84e8-a5115f962a72.png">

-----

I want to contribute to fixing this issue. I will raise a pull request. Help me with the review!

**Comment by prth** [comment]
Here are some screenshots of the result with the changes in this PR #5110 

<img width="784" alt="image" src="https://user-images.githubusercontent.com/3371270/170180351-734c6b60-2250-4814-9218-8cc54f8c4f4d.png">

**Comment by prth** [comment]
Here is screenshot of the result with the changes of PR #5110 

<img width="784" alt="image" src="https://user-images.githubusercontent.com/3371270/170180487-23774606-baad-46fe-b013-56c11105d7e1.png">

**Comment by prth** [comment]
Here are some screenshots of the result with the changes of PR #5110 

<img width="1411" alt="image" src="https://user-images.githubusercontent.com/3371270/170180991-9d2c6b3a-6260-4d7e-aad1-39d8b831e15d.png">

<img width="1416" alt="image" src="https://user-images.githubusercontent.com/3371270/170180830-a09382fa-24de-40a1-b614-000548d1174d.png">

<img width="1415" alt="image" src="https://user-images.githubusercontent.com/3371270/170180865-ddc03465-0701-44c8-b3d7-58d5b0134bfc.png">

<img width="722" alt="image" src="https://user-images.githubusercontent.com/3371270/170180942-e5d268a6-287e-4229-835a-27738d3daae4.png">

**Comment by lucasponce** [comment]
Thanks for filling the issue and the pull request @prth
