### ISSUE TITLE
Improve Thanos documentation

### ISSUE THREAD

**Issue by flockoftanks** [kiali/kiali#5118]
Hello,

I see that there are some settings that I can configure in my kiali-operator (installed with rancher-istio) to use Thanos:
https://github.com/kiali/kiali/issues/4303 and https://github.com/kiali/kiali-operator/blob/master/crd-docs/cr/kiali.io_v1alpha1_kiali.yaml

However, when I configure it to use Thanos (setting Thanos to 'true' and changing 'url' to point to my thanos query service), the only namespaces available are in a single cluster, not all the clusters that are represented by Thanos. These available docs appear to be written from the perspective of someone who knows Thanos, Kiali, and Prometheus really well, but that is definitely not me. Does anyone have more specific instructions or a tutorial available to configure Kiali to work with Thanos?

After switching "url" to point to my Thanos endpoint, I also notice that the graph tab continues looking in the default Prometheus endpoint which doesn't exist. Is this a bug or a side-effect to my misconfiguration?

TIA!

**Comment by flockoftanks** [comment]
I did make some progress, here. I realized none of my settings were taking hold because I had to restart my deployment and get a fresh pod. That said, I'm still unclear about the health check URL. I've read all the docs but haven't really discerned what to do with it.

**Comment by israel-hdez** [comment]
Hi @flockoftanks 

There is also some formal doc here: https://kiali.io/docs/configuration/p8s-jaeger-grafana/#compatibility-with-prometheus-like-servers . Although, I reckon it is short.

What I remember is that those settings under `thanos_proxy` are the ones that are required when using Thanos. If I remember correctly, the health check URL can be left unset for Thanos case. I think Kiali will simply try to contact Thanos at the base url and if it replies with an HTTP Status code that is on the 2xx range, it will take it as healthy.

**Comment by flockoftanks** [comment]
Thanks @israel-hdez , I did see that formal doc but you're right, it's pretty short. I'll keep playing with this and update if I find an optimal settings.
