### ISSUE TITLE
[cypress] Test to measure graph loading time

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#5143]
A cypress test to visit the graph page and wait for the graph to fully load.

This is separate from the other cypress testing efforts and more relates to scalability. As such, it does not need a feature file and can be written in the standard cypress syntax.

**Comment by josunect** [comment]
tests/perf

**Comment by ScriptingShrimp** [comment]
On client side, we can use [performance.getEntries()](https://developer.mozilla.org/en-US/docs/Web/API/Performance/getEntries). I can imagine some tests on top of that in Cypress - this kind of snapshot can give us base line if we start tune API or application code. I do expect various environments to perform differently - but could be really easy to implement.

If we want to take things more seriously:
- Lighthouse can be used (even in console/headless mode) https://web.dev/lighthouse-ci/
- Playwright could be weapon of choice [with some library ](https://dev-tester.com/check-your-sites-performance-with-artillery-and-playwright/) (need to take a look more in depth)
