### ISSUE TITLE
Tunable dimensions for performance tests

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#5144]
Performance testing should be run across a number of dimensions. Namely we want to run performance tests with:
- Varying number of namespaces
- Varying number of workloads
- Varying cluster age
- Varying traffic rates between workloads

**Comment by lucasponce** [comment]
I guess it's implicit in the description, but as part of this task, it would require a follow-up of https://github.com/kiali/kiali/issues/5142 to deploy the test applications (based on https://github.com/kiali/demos) to simulate heterogeneous and rich scenarios.

Worth to use most of the demo apps to combine all types of traffic (gRPC, HTTP), errors, and potentially ServiceEntry traffic (but this one I'm less sure about as it can introduce undesired elements in the perf environment).

**Comment by nrfox** [comment]
This has been partially completed. The perf cluster script includes creation of a variable number of workloads but not all of the demos are being used and the auto-generated workloads are limited to a single namespace.

To finish this up, I'd say we:
1. Deploy additional demo apps as part of the perf script
2. Add additional options to the perf script to change the number of namespaces/traffic rates.

**Comment by nrfox** [comment]
Going to close this issue as done. Not all of the demo apps have been deployed but many of the parameters are tunable using the hack perf script.
