### ISSUE TITLE
[scalability] How to thin metrics to those required only by Kiali

### ISSUE THREAD

**Issue by jshaughn** [kiali/kiali#5151]
Investigate providing a configuration that limits Istio to generating only the Prometheus metrics required by Kiali.   For users that may only need the metrics to run Kiali, this would potentially make it easy to significantly reduce metric storage, and to avoid unnecessary processing of unused metrics.  Users could of course modify the configuration to support custom dashboards etc...  This would also avoid users removing required metrics or attributes that would break Kiali.

This would also allow us to analyze the impact of such changes on performance.

**Comment by Xunzhuo** [comment]
This is a good idea, one of the problems we meet in production is that the metrics storage  is very large, istio provides many metrics in default besides istio_xxxx metrics. Cutting off the extra unused metrics can save a lot of storage in Promethues, and reduce its pressure.

**Comment by lucasponce** [comment]
Side comment, Kiali use also some native envoy metrics for the "Workload -> Envoy -> Metric" dashboard.
As part of this work, perhaps that dashboard could be revisited and reviewed if the default ones are good/relevant ones or it can be revisited.

**Comment by jshaughn** [comment]
> Side comment, Kiali use also some native envoy metrics for the "Workload -> Envoy -> Metric" dashboard.

Yes, I recently captured this in my update to kiali.io [required metrics FAQ.](https://staging.kiali.io/docs/faq/general/#which-istio-metrics-and-attributes-are-required-by-kiali)  I did the update as a first step to this effort.  Feel free to review that new content!

**Comment by jshaughn** [comment]
There may be other things we can do in this area, but work is at a reasonable first milestone, and so closing this infavor of new issues as needed.
