### ISSUE TITLE
Research Istio Config Validations Optimization.

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#5153]
Currently Istio Config validations on Kiali side are triggered per request, even though Istio Config objects are loaded from Istio registry, the validations still take some time to process, and is done every time Istio configs are listed. This takes too much resources to recalculate the same unchangeable validation results per each request.

Research task is created to analyze the possibility of optimization of validations, is possible to have the results in a cache and trigger validations per Istio registry change in parallel.

A discussion was created to this topic in past: https://github.com/kiali/kiali/discussions/4514

This one is also related to https://github.com/kiali/kiali/issues/4832

**Comment by lucasponce** [comment]
Thanks, @hhovsepy, I'm +1 with this research.
Validation is an area that is sensitive to scalability, especially on the "Overview" page, also during the TLS validation and using the cross-namespace area.

My walkthrough for this work would be also to link it with the scalability efforts and also to capture data for those endpoints.

Also, during the big refactoring to use the Istio registry instead direct k8s calls we identified areas where the calls to the registry were done in an upper call, instead to repeat calls; that would be also a good area to review.

And perhaps, we can also use this task to review if all the checkers are valid in the context of Istio 1.13 and beyond, as some of the logic is already in place in the Istio code, and perhaps Kiali could remove those ones.

But I see this task as an "open research" to capture data and trigger discussions about potential designs.

**Comment by hhovsepy** [comment]
It calls validation service per namespace in Overview page, but in fact the validation service checks all configs and services in registry.
So validation service can be optimized to do validation for all namespaces, and from Overview page there will be only one request to return validations for all namespaces.
