### ISSUE TITLE
External link to Traces is not working

### ISSUE THREAD

**Issue by dimitarshenkov** [kiali/kiali#5181]
![image](https://user-images.githubusercontent.com/99493924/172831316-0d7d0425-9ab8-46ad-b3cc-f704d0d1a0a9.png)
![image](https://user-images.githubusercontent.com/99493924/172831362-7cf61c17-c476-4a4b-88b5-6c215cab2697.png)
Kiali version v1.40.0
Jaeger all-in-one:1.20

**Comment by lucasponce** [comment]
Could you check if in the external URL? (The public one that should point from the browser to jaeger service)
It seems it's missing the "/jaeger" path
![image](https://user-images.githubusercontent.com/1662329/172832186-9896cf8a-5b56-4154-8bca-c248962fcedd.png)

**Comment by dimitarshenkov** [comment]
That was it thanks!
