### ISSUE TITLE
404 external link in kiali.io

### ISSUE THREAD

**Issue by josunect** [kiali/kiali#5192]
make validate-site in kiali.io shows an external broken link: 

```
- ./public/docs/features/istio-component-status/index.html
  *  External link https://istio.io/latest/docs/tasks/security/cert-management/dns-cert/ failed: 404 No error

HTML-Proofer found 1 failure!
```

**Comment by jshaughn** [comment]
@josunect Thanks for detecting the problem.  For small issues on kiali.io, it is totally fine to just generate a fix PR and avoid the additional overhead of a github issue.  Probably the issue can be fixed faster than the issue can be created :-)   Having said that, it is still OK to generate an issue if it makes sense to fix the issue at a later time.

**Comment by jshaughn** [comment]
This has been fixed.
