### ISSUE TITLE
[CI] Test Flake - TestCreateSessionNoChunks

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#5197]
See: https://github.com/kiali/kiali/runs/6861149294?check_suite_focus=true for an example

>  --- FAIL: TestCreateSessionNoChunks (0.02s)
    session_persistor_test.go:58: 
        	Error Trace:	session_persistor_test.go:58
        	Error:      	"5WVbSMsyrn1SABmGm+k3P0t+PHlCDPfxt6SbVmNlyH9BXcjPZKZfOn1v/cxr1PHFoozyLgAteMxb9QTq8DXeCT8hI6vR3Q2hnEBjr1KQjGg86obOQ/R65/i3oD/aer5tqsNCk4nFCWslzYkaT37RayIJ5DCknbo=" should not contain "Foo"
        	Test:       	TestCreateSessionNoChunks

**Comment by amantayal5** [comment]
Hi @nrfox 
I want to work on this issue! Can you explain the bug to me?

**Comment by nrfox** [comment]
@amantayal5 sure! From here: https://github.com/kiali/kiali/blob/master/business/authentication/session_persistor_test.go#L53-L59, it looks like the test is checking that the cookie doesn't contain "Foo" to ensure that text actually got encrypted however you can randomly get "Foo" as part of the encrypted text hence the test flake/failure here. @israel-hdez can confirm but perhaps you can just update the assertion from an `assert.NotContains` to an `assert.NotEquals`?

**Comment by israel-hdez** [comment]
It is just a little bit more complicated that just doing `assert.NotEquals`. In case it happens to be plain text, it would be a string of a JSON document. Something like `{ "firstField": "Foo" }`. I was trying to avoid that "dance" of parsing the JSON string. Perhaps if parsing, succeeds may that would be enough to conclude it is in plain text and finish with failure? (i.e. no need to check the contents of the json doc?)

**Comment by jshaughn** [comment]
@amantayal5, are you working this issue?

**Comment by amantayal5** [comment]
@jshaughn Not exactly! I am unable to do setup Kiali in my system right now!

**Comment by nrfox** [comment]
> @nrfox CI seems stable at the moment, did this go away?

No I think it's just a relatively rare flake since the encrypted text is unpredictable and has to contain `Foo` in order to trigger a failure.

**Comment by jshaughn** [comment]
@matejnesuta , would you be able to take this one?  It's not urgent but I'd like to see it get cleaned up.

**Comment by ScriptingShrimp** [comment]
@jshaughn unfortunately me and Matej have no golang expertise, so cannot help here. Anyways,
These are unit tests inside business folder?

**Comment by jshaughn** [comment]
No problem, someone else can take it.  I don't actually know the details.
