### ISSUE TITLE
Wrong engine node version in package.json

### ISSUE THREAD

**Issue by aljesusg** [kiali/kiali#5208]
After upgrade node to the latest one I got the message that node engine must be >=12.22.0 and < 16. this is great because we set in the [package.json](https://github.com/kiali/kiali/blob/master/frontend/package.json#L143):

  **"node": ">=12.22.0 && <16"**

So I installed the latest 15.X 15.14.0  (latest one of 15) and I got :

`error npmlog@6.0.2: The engine "node" is incompatible with this module. Expected version "^12.13.0 || ^14.15.0 || >=16.0.0". Got "15.14.0"`

So I installed 14.19.3 (latest one of 14) and worked ...So we need to change the node engine to  ">=12.22.0 && <15"

**Comment by h20220025** [comment]
@aljesusg i would like to work on this issue.

**Comment by jshaughn** [comment]
@h20220025 , It seems @marwanjuna has abandoned this issue, you can reference [his PR](https://github.com/kiali/kiali/pull/5559) or start a new one.

**Comment by jshaughn** [comment]
@h20220025 , do you still have interest?

**Comment by ferhoyos** [comment]
The error says that expected version is "^12.13.0 || ^14.15.0 || >=16.0.0", so our compatible node version in package.json should be "^12.13.0 || ^14.15.0" (node v13 is incompatible too).

**Comment by ferhoyos** [comment]
Playing with node versions I have found two more incompatible messages:

* error eslint@8.12.0: The engine "node" is incompatible with this module. Expected version "^12.22.0 || ^14.17.0 || >=16.0.0". 

* error @badeball/cypress-cucumber-preprocessor@12.2.0: The engine "node" is incompatible with this module. Expected version ">=14.14.0"

Along with the npmlog incompatible message at the top of the issue, our compatible node version in package.json should be:

**"node": "^14.17.0"**
