### ISSUE TITLE
Changing graph type issue

### ISSUE THREAD

**Issue by ChristofferNicklassonLenswayGroup** [kiali/kiali#522]
**Versions used**
    kiali-ui 0.7.2 (45da0c22819e4ca94a403ffd3a7336e1aca6a10e)
    kiali v0.7.2 (78b4d01bde56e2ceeeaa09250d66aca2041f131a)
    Components
    Istio 1.0.2
    Prometheus 2.3.1
    Kubernetes v1.11.3

1. Go to console/service-graph/<namespace>
2. Click on 'Graph type'
3. Scroll down to 'Any'
4. See error: view is destroyed.
see attached image.
![skarmbild fran 2018-09-27 11-09-10](https://user-images.githubusercontent.com/33247910/46140348-2729f200-c251-11e8-8b88-9a397293b665.png)

**Comment by jshaughn** [comment]
I guess by 'Any' graph type you just mean switching from any one to any other.   This looks like the layout gets confused.  Changing the layout (under Graph Settings) would likely resolve the issue.  I would expect that a browser refresh would also resolve the layout issue.  Does this happen every time or intermittently?  Also, which layout are you using when this happens (should be one of dagre, cola, cose)?

**Comment by jshaughn** [comment]
Please let us know if this is still something you see using 0.8.0.  There have been many improvements to the  graph.

**Comment by pilhuhn** [comment]
@ChristofferNicklassonLenswayGroup Is this still an issue?

**Comment by pilhuhn** [comment]
Closing as being old. Please reopen if this is still an issue.
