### ISSUE TITLE
[CI] Test flake - timeout looking for traces tab

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#5222]
Originally found here: https://github.com/kiali/kiali/pull/5141#discussion_r891638062.
![Screenshot from 2022-06-07 15-16-20](https://user-images.githubusercontent.com/6226732/174152007-c2e989d1-837c-449f-9766-672d3e588dee.png)

> You can see from the screenshot that the traces have loaded and it's clicking the right thing but it's still failing. I think the trace is outside of the chart and clicking anywhere outside the chart doesn't do anything. I can reproduce this outside this test as well. In other words, it's kind of a bug since all the data on the chart should be clickable and rendered inside the chart. Not sure if this is a problem with Kiali or with the chart lib.

**Comment by jshaughn** [comment]
So cypress tests found a bug!  Are you sure that the trace actually exists, meaning is it possible the dot is in the chart bur not reflecting a real trace?

**Comment by nrfox** [comment]
Yes! This seems like a legit bug.

> Are you sure that the trace actually exists, meaning is it possible the dot is in the chart bur not reflecting a real trace?

I'm fairly sure the trace exists because if you mouse a little outside the dot but still around it you can click on the trace. I haven't investigated it yet but my guess is that some graph bounds are not being set properly in Kiali or else it's a problem in the graph lib.

**Comment by jmazzitelli** [comment]
that's a legit failure. Cypress wins a cookie :D
