### ISSUE TITLE
[CI] Test flake - The degraded status of a service is reported in the list of service

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#5226]
See: https://github.com/kiali/kiali/runs/6940511722?check_suite_focus=true for an example.

![image](https://user-images.githubusercontent.com/6226732/174355459-68881c72-240f-4932-9b59-b489e6e1c2a0.png)

**Comment by israel-hdez** [comment]
Hmm... OK, I've been thinking a while.

So.... the test is flaky, but from the screenshot it is evident that the environment caused the issue for that specific run. The test is expecting degraded health on `y-server`, but the env is giving error health despite the demo app is designed to give degraded health.

The easiest thing that comes into my mind is to use our [Traffic Health config](https://kiali.io/docs/configuration/health/) to flag `y-server` service as degraded even if 100% of the traffic is failing... I will try that and hope that this test is never going to fail again.
