### ISSUE TITLE
custom dashboard discovery not using correct prometheus timeseries labels

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#5231]
Today, when trying to discover custom dashboards, the Kiali server queries Prometheus looking for specific labels in metric timeseries.  Two labels are always used in the lookup - the app and version labels (technically, the names of the labels are whatever is configured in `spec.istio_labels.app_label_name` and `spec.istio_labels.version_label_name`). This is done here: https://github.com/kiali/kiali/blob/v1.52.0/business/dashboards.go#L566-L570

```go
filters[cfg.IstioLabels.AppLabelName] = app
if version != "" {
	filters[cfg.IstioLabels.VersionLabelName] = version
}
runtimes = in.discoverDashboards(namespace, filters)
```

*[update from jshaughn: the synopsis below is wrong, keep reading the thread comments for more...]*

The problem is - the actual kubernetes labels on the pods are NOT identical to the Prometheus labels. For example, today, Istio (by default) stores Prometheus labels called something like "service_istio_io_canonical_name" and "service_istio_io_canonical_revision" and their values are the values of the kubernetes labels used for app and version.

We need a way for the dashboard discovery to be told "map the app name A to the prometheus label P1 and map the version V to the prometheus label P2".

This may affect more than just discovery, but right now that's what is currently known to be wrong.

This problem was detected while work was being done for https://github.com/kiali/kiali/issues/5151

**Comment by jshaughn** [comment]
As an immediate workaround/fix for built-in dashboards, without the need for configuration support,  we can change the default values used to be the "canonical" prom labels expected to exist in the istio and istio-proxy-envoy metrics.  But for custom dashboards around runtimes, I'm not sure.

**Comment by jmazzitelli** [comment]
I need to backtrack a little. It is not true to say, "the actual kubernetes labels on the pods are NOT identical to the Prometheus labels." at least not in the case where the labels are either "app"/"version" or "app.kubernetes.io/name","app.kubernetes.io/version" - because in those cases it does appear Istio is emitting metrics with those prometheus label names (albeit with the invalid prom label characters converted to "_").

Here's my bookinfo details timeseries in prometheus:

```
istio_requests_total{app_kubernetes_io_name="details", app_kubernetes_io_version="v1", connection_security_policy="mutual_tls", destination_app="unknown", destination_canonical_revision="v1", destination_canonical_service="details", destination_cluster="cluster-default", destination_principal="spiffe://cluster.local/ns/bookinfo/sa/bookinfo-details", destination_service="details.bookinfo.svc.cluster.local", destination_service_name="details", destination_service_namespace="bookinfo", destination_version="unknown", destination_workload="details-v1", destination_workload_namespace="bookinfo", instance="172.17.0.16:15020", job="kubernetes-pods", namespace="bookinfo", pod="details-v1-76cd66df8c-rch47", pod_template_hash="76cd66df8c", reporter="destination", request_protocol="http", response_code="200", response_flags="-", security_istio_io_tlsMode="istio", service_istio_io_canonical_name="details", service_istio_io_canonical_revision="v1", source_app="productpage", source_canonical_revision="v1", source_canonical_service="productpage", source_cluster="cluster-default", source_principal="spiffe://cluster.local/ns/bookinfo/sa/bookinfo-productpage", source_version="v1", source_workload="productpage-v1", source_workload_namespace="bookinfo", topology_istio_io_network="network-default"}
```

Notice it DOES have `app_kubernetes_io_name="details"` and `app_kubernetes_io_version="v1"` labels that correspond to the k8s labels on the pod.

This is why dashboard discovery works in my case.

But IF you strip those labels off the timeseries (using prometheus features) then dashboard discovery will fail.

Therefore, this probably isn't a bug.

**Comment by jmazzitelli** [comment]
As another test, I renamed the "app.kubernetes.io" labels into "mazz" labels ("mazz/app" and "mazz/version"). I see Istio will create prometheus labels to match those k8s labels (so I do see "mazz_app" and "mazz_version" in my prometheus time series).

However, I do notice `destination_app="unknown"` and `destination_version="unknown"`. And I went back and also noticed the same "unknown" values for these when using the app.kubernetes.io labels (see the timeseries I documented in the previous comment).

Here's my timeseries in prometheus:
```
istio_requests_total{connection_security_policy="mutual_tls", destination_app="unknown", destination_canonical_revision="latest", destination_canonical_service="details-v1", destination_cluster="cluster-default", destination_principal="spiffe://cluster.local/ns/bookinfo/sa/bookinfo-details", destination_service="details.bookinfo.svc.cluster.local", destination_service_name="details", destination_service_namespace="bookinfo", destination_version="unknown", destination_workload="details-v1", destination_workload_namespace="bookinfo", instance="172.17.0.16:15020", job="kubernetes-pods", mazz_app="details", mazz_version="v1", namespace="bookinfo", pod="details-v1-6bc8c899d9-mhrvj", pod_template_hash="6bc8c899d9", reporter="destination", request_protocol="http", response_code="200", response_flags="-", security_istio_io_tlsMode="istio", service_istio_io_canonical_name="details-v1", service_istio_io_canonical_revision="latest", source_app="productpage", source_canonical_revision="v1", source_canonical_service="productpage", source_cluster="cluster-default", source_principal="spiffe://cluster.local/ns/bookinfo/sa/bookinfo-productpage", source_version="v1", source_workload="productpage-v1", source_workload_namespace="bookinfo", topology_istio_io_network="network-default"}
```

**Comment by jmazzitelli** [comment]
These k8s labels get into the timeseries through a prometheus server config... I believe it is this:

```
- action: labelmap
  regex: __meta_kubernetes_pod_label_(.+)
```

**Comment by lucasponce** [comment]
I'm catching up with the discussion.
Perhaps I'm missing some context but there are two things with the custom dashboards:
- One is how to discover, fetch and show, which should be fully customizable by the user as remember, these are application metrics (please use the demos we have for these scenarios, not "bookinfo", I'm afraid that if you don't use those, you'll miss important aspects).
- The second aspect, is that the "app"/"version" labels are used to link those metrics with the proper app/workload/service. This is something that can be modified.

So, not sure if this should be in sync with the metrics of is, that's confusing and/or needs context from my side.

Also, it's perfectly ok that these data may live in a different server, the key here is to know which query it should perform, and which attributes would identify them with the proper app/workload/service.

But I see the telemetry of istio and the custom dashboards like two different domains.

**Comment by jmazzitelli** [comment]
> * The second aspect, is that the "app"/"version" labels are used to link those metrics with the proper app/workload/service. This is something that can be modified.

That's the important point wrt this issue.

<tl;dr> In the end, I believe me and Jay came to the conclusion there isn't a bug here. Let me explain below </tl;dr>

Here's where the confusion was.

Take a look at the code here: https://github.com/kiali/kiali/blob/v1.52.0/business/dashboards.go#L566-L570

```go
filters[cfg.IstioLabels.AppLabelName] = app
if version != "" {
	filters[cfg.IstioLabels.VersionLabelName] = version
}
runtimes = in.discoverDashboards(namespace, filters)
```

Notice it gets the k8s label names that Istio/Kiali will use for app/version and then uses those label names for Prometheus queries. Therefore, this code assumes there are prometheus timeseries labels with the same names as the workload's kubernetes labels (with the caveat that prometheus illegal characters such as "." and "/" found in the k8s label names are converted to "_" when the prom query is made).

Jay and I were under the impression that the prom labels in the Istio telemetry did NOT necessarily match the k8s labels. But it turns out through my investigation that Prometheus is normally configured to add all k8s labels from pods that it scrapes to the Prometheus timeseries. Thus, the Istio telemetry WILL have labels that match the k8s labels (which include the Istio app/version labels.

The only issue left that I can see is @jshaughn needs to confirm that the Kiali code no longer inspects or queries on `destination_app` and `destination_version` prometheus labels when it queries prometheus. This is because these values appear to be set by Istio to `unknown` when there is no `app` and `version` k8s labels on the pods.

**Comment by lucasponce** [comment]
Adding the documentation for reference:
https://kiali.io/docs/configuration/custom-dashboard/#prometheus-configuration
![image](https://user-images.githubusercontent.com/1662329/175034254-b5ce12ef-10f9-4eda-aee8-0b8725670400.png)

I don't think there is a bug, but in any case, we have demos for these features in case we'd like to change some behavior (i.e. some app metrics use a different mapping), but that's like an enhancement from the existing set of features.

**Comment by jshaughn** [comment]
OK, thanks @jmazzitelli and @lucasponce, things are more clear and we can now see that pod labels do in fact become prometheus labels through the defined labelmapping.

The confusion started because I was dropping **seemingly unnecessary** labels as part of the #5151 investigation.  The spirit of that effort is to eliminate as many metrics and metric attributes as possible, without breaking Kiali.  This is to reduce the pressure on prometheus, both from a query and storage perspective, for users that are primarily only storing metrics to be able to use Kiali.  The mechanism should also make it fairly easy to add back anything needed but non-Kiali tooling.

The custom dashboards must continue to work.  As such we need to be careful with what we do.

My question is can we move dashboards to use the `canonical` fields` that have been introduced more recently into Istio.   `service_istio_io_canonical_name` and `service_istio_io_canonical_revision` are reliably set, despite various labeling schemes, and could eliminate the need for maintaining several labels in the metrics.

**Comment by jshaughn** [comment]
Looking more, I'm not sure we can leverage the "canonical" fields; other than the core istio metrics, this label won't be found (e.g. the `go_*`, `kiali_*` metrics), so probably best to leave the dashboard logic as-is, and leverage the pod label mapping.

**Comment by jshaughn** [comment]
I'm going to close this.  Perhaps in a future round of prometheus optimization we may want to revisit the labels used for built-in dashboards.
