### ISSUE TITLE
openid strategy should not show login page: where are kiali's autologin options?

### ISSUE THREAD

**Issue by Morriz** [kiali/kiali#5232]
Hi, when `server.auth.strategy: openid` is chosen, it only allows for one openid provider, so why show a login screen? Marketing? It is unnecessary from the users perspective, and at the minimum it should be made configurable to automatically login imo.

**Comment by jshaughn** [comment]
It's not marketing :-)  Just sort of the way it is.   If this is easy to fix (also true for `anonymous`) then let's make the change.
