### ISSUE TITLE
Document ability to set default Kiali CR image_name in operator from helm charts

### ISSUE THREAD

**Issue by amantayal5** [kiali/kiali#5238]
We want to add ability to set default Kiali CR image_name in operator using some env variables and use this env variable in helm chart while deploying. Currently, default image_version which operator tries is "quay.io/kiali/kiali" (which is hardcoded), we want to parameterise it so that we can configure(point) it to our container registry during operator deployment.

**Comment by jmazzitelli** [comment]
I'm changing this to a "docs" issue - we should probably document this feature on kiali.io somewhere.

**Comment by jmazzitelli** [comment]
I submitted a PR to document this feature in the kiali.io doc site. See: https://github.com/kiali/kiali.io/pull/549

@amantayal5 In the meantime, you can read the new docs here - this will explain how to do what you are asking for: https://deploy-preview-549--kiali.netlify.app/docs/installation/installation-guide/advanced-install-options/#change-the-default-image

**Comment by amantayal5** [comment]
@jmazzitelli thanks for the documentation but we need little bit more help around this.
So I used this documentation to set default image name. It is getting properly populated in env variable but when it is trying to use that image to create Kiali resource, I am getting error:

` message: 'Secret kiali-signing-key: Failed to create object: b''{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Secret
        \\"kiali-signing-key\\" is invalid: metadata.labels: Invalid value: \\"<my-registry>/<my-env>/quay.ioXXX\\":
        a valid label must be an empty string or consist of alphanumeric characters,
        \''-\'', \''_\'' or \''.\'', and must start and end with an alphanumeric character
        (e.g. \''MyValue\'',  or \''my_value\'',  or \''12345\'', regex used for validation
        is \''(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?\'')","reason":"Invalid","details":{"name":"kiali-signing-key","kind":"Secret","causes":[{"reason":"FieldValueInvalid","message":"Invalid
        value: \\"<my-registry>/<my-env>/quay.ioXXX\\":
        a valid label must be an empty string or consist of alphanumeric characters,
        \''-\'', \''_\'' or \''.\'', and must start and end with an alphanumeric character
        (e.g. \''MyValue\'',  or \''my_value\'',  or \''12345\'', regex used for validation
        is \''(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?\'')","field":"metadata.labels"},{"reason":"FieldValueInvalid","message":"Invalid
        value: \\"<my-registry>/<my-env>/quay.ioXXX\\":
        a valid label must be an empty string or consist of alphanumeric characters,
        \''-\'', \''_\'' or \''.\'', and must start and end with an alphanumeric character
        (e.g. \''MyValue\'',  or \''my_value\'',  or \''12345\'', regex used for validation
        is \''(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?\'')","field":"metadata.labels"}]},"code":422}\n'''`

I am setting my default image to: `<my-registry>/<my-env>/quay.io/kiali/kiali`
Can you suggest a workaround for this?
