### ISSUE TITLE
Milliseconds precision for sorting log entries in the Logs tab

### ISSUE THREAD

**Issue by israel-hdez** [kiali/kiali#5246]
In the logs tab, Kiali is sorting log entries with second precision, leading to an undefined order for entries written in the same second. If the pod has more than one container and if the containers are writing timestamp on their logs, it is somewhat confusing to see the log lines without the right order. So, using millisecond precision may give better ordering in the unified view.

## Example

![image](https://user-images.githubusercontent.com/23639005/175378354-1dc3f8d3-22ba-4bf7-b591-17d280854b40.png)

In the previous image, it can be seen that there are two containers in the pod: `istio-proxy` (the sidecar) and `w-server`. By meticulously looking at the timestamps, it can be perceived that entries are _almost_ in the right order, but not exactly in the right order.

## The confusion

What the previous screenshot is showing is what the containers are logging. It happens that both the `istio-proxy` and the `w-server` containers are writing timestamps on its logs. This leads to a confusion, because those timestamps are not being used by Kiali. Also, those timestamps cannot be parsed since the format is unknown. The exception is the `istio-proxy` container that has a well known format and Kiali is parsing it. So, with the exception of the `istio-proxy` container, Kiali is not using those timestamps for giving the unified log view.

Moreover, not all containers give timestamps in the logs. For example, this is the productpage-v1 workload:

![image](https://user-images.githubusercontent.com/23639005/175380002-31c0d501-48a5-442a-80d5-01f4f3d22687.png)

To see the timestamps that Kiali is using for sorting, in the Kebab menu (below the tail-lines dropdown) click on _Show Timestamps_ option. Kiali will show the timestamps it "knows". Notice that Kiali has up to seconds precision only, which means that lines logged at the same second have an undefined sorting order:

![image](https://user-images.githubusercontent.com/23639005/175380330-3915bef3-fb39-4280-bc59-673a9d91c670.png)

## The issue/fix

Kuberentes does not guarantee to give milliseconds in the timestamps. So, in the past, it was chosen to drop the milliseconds to normalize timestamps. It is probably better to normalize taking into account the milliseconds (if possible) and fill milliseconds with zeros if not available.

**Comment by jshaughn** [comment]
As explained above, k8s is not providing ms granularity, and just because an application may include a ms-timestamp in its log entry test, it's arbitrary and not something that can be parsed out.  The k8s timestamp is what is available, and as stated, I don't think it guarantees ms, and that is likely why things are like they are.  But, of ms may be provided, even in some cases, and can be reliably parsed, I do think we should make that enhancement, defaulting to .000 as needed.

**Comment by israel-hdez** [comment]
@josunect In case your backlog gets empty, this is an issue you can take.

**Comment by josunect** [comment]
Thank you, @israel-hdez ! I will have a look.
