### ISSUE TITLE
Terminated in Another Window color doesn't look like the PF warning title color

### ISSUE THREAD

**Issue by pbajjuri20** [kiali/kiali#5255]
The Color for Terminated in another window in in orange below may not meet the Accessibility requirement for high contrast.

for reference: 
![image (1)](https://user-images.githubusercontent.com/55099523/176039227-d2e61856-d31e-4540-a09b-ce8e77aec67c.png)

**Comment by tsze-redhat** [comment]
Step to reproduce:
Log in to Kiali.
Wait for a while (couple of hours?)
Go back to the tab and you should see the warning text mentioned.

It may not meet accessibility contrast requirements.
