### ISSUE TITLE
[CI] Molecule tests no longer work with kube 1.24+

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#5258]
Some molecule tests rely on the default service account token secret to be present when dealing with token auth. As of kube 1.24+, these secrets are no longer created by default and have to be created manually.

See: https://github.com/kiali/kiali/runs/7086748946?check_suite_focus=true for an example of the failing molecule tests.

**Comment by jmazzitelli** [comment]
While fixing this, we should look into fixing a couple hack scripts, too, which also rely on secrets being in SAs:

* https://github.com/kiali/kiali/blob/v1.52.0/hack/run-kiali.sh#L566
* https://github.com/kiali/kiali/blob/v1.52.0/hack/istio/multicluster/install-everything.sh#L59

**Comment by jmazzitelli** [comment]
I did this for the make targets so they no longer rely on the SA secret - but I don't think its solution is relevant. I am just documenting it here as an fyi: https://github.com/kiali/kiali/pull/5402

**Comment by jmazzitelli** [comment]
docs that may help: https://access.redhat.com/solutions/6964710

**Comment by jmazzitelli** [comment]
For this issue, I'm not going to do the https://github.com/kiali/kiali/blob/v1.52.0/hack/istio/multicluster/install-everything.sh#L59 script - we'll save that for another day if someone wants it. AFAIK, no one is using that multicluster scripting anyway.

**Comment by jmazzitelli** [comment]
PRs for this issue:
* https://github.com/kiali/kiali/pull/5405
* https://github.com/kiali/kiali-operator/pull/560
