### ISSUE TITLE
Improve the Envoy metrics tab

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#5272]
This is a follow-up task about the planned improvements in the Envoy tab located under the Workload details.
One of the features shipped is to provide a minimal "Envoy" metrics dashboard with some data about the proxy.

This dashboard has not been reviewed for quite a time. Kiali is revisiting some of its features to identify what information is useful to help users to understand what's happening in the mesh and what information is just adding more overload to all the data.

As part of this work, this dashboard can be investigated to check if it's valid or if it may require a redesign.

Also, there are several parallel efforts related to this context (reduce the number of metrics for performance, improvements in logs, etc) that should be all coordinated.

**Comment by jshaughn** [comment]
Hi @aljesusg , Did you mean to close this issue?  I don't see any PRs or comments?

**Comment by jshaughn** [comment]
Reopening this until I know whether there is work to do or if we are closing.

**Comment by aljesusg** [comment]
We did the PR related with this https://github.com/kiali/kiali/pull/5249 Maybe we can do some more improvement here but I didn't see it weeks ago
