### ISSUE TITLE
Support Telemetry and WasmPlugin Istio objects

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#5274]
Kiali supports Istio configuration, but two new resources are not yet added:

```
  {
    group: 'extensions.istio.io',
    version: 'v1alpha1',
    kind: 'WasmPlugin',
  },
  {
    group: 'telemetry.istio.io',
    version: 'v1alpha1',
    kind: 'Telemetry',
  },
```

This issue would add them to the regular Istio Config visualization, but the basic editing features.

Kiali Validations are not part of the scope of this task.

**Comment by josunect** [comment]
@lucasponce just to be sure, the new resources will be added here, right?

![image](https://user-images.githubusercontent.com/49480155/183424798-2885bf51-478d-4608-a180-50e2780498c5.png)

**Comment by josunect** [comment]
https://istio.io/latest/docs/reference/config/proxy_extensions/wasm-plugin/
https://istio.io/latest/docs/reference/config/telemetry/

**Comment by lucasponce** [comment]
Yes, @josunect; this issue provides "basic" support to the Kiali standalone to Istio resources.
Worth to sync with @hhovsepy here, as some changes depend on the context (fetching list, details, kiosk mode, etc), and Hayk is working on this in case you'd need more context.

**Comment by josunect** [comment]
Thanks, @lucasponce ! I will catch up with Hayk
