### ISSUE TITLE
mTLS traffic should be included in the Traffic tab

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#5275]
This task should continue the enhancements on the mTLS information in the details pages.

Now, Istio metrics have a "Connection Security Policy" filter that allow to easily visualize that info:
![image](https://user-images.githubusercontent.com/1662329/176672686-b430d2f3-87d9-424f-a6a6-7b74b3cc4007.png)

Minigraph has information about the mTLS edges:
![image](https://user-images.githubusercontent.com/1662329/176672515-bd74e459-5630-4e11-8575-dd7dea703eed.png)

But the Traffic tab doesn't show that information, and mTLS edges are one of the first aspects that users would like to see
![image](https://user-images.githubusercontent.com/1662329/176672553-fa513ba9-5368-4fcf-93a1-8d1444e53e7e.png)

As the backend data for minigraph and the traffic data is the same, this information should be available.

**Comment by josunect** [comment]
How can this information be shown? I can think in:

- Add a lock icon if mTLS is enabled || Add a new column, mTLS, with the percentage of mTLS traffic (But if will be blank if mTLS is disabled)
- The table has enough space to add, near the icon, the percentage of mTLS traffic || Can be shown when hover over the icon
