### ISSUE TITLE
Sidecar with no workloadSelector in two separate namespaces are marked as conflicting...

### ISSUE THREAD

**Issue by diranged** [kiali/kiali#5310]
We have a`istio-system/default` Sidecar with no workloadSelector, and then the majority of our other apps use `Sidecar` resources that are scopd to their workload (and also launched in their namespace). We have one other namespace though where the `Sidecar` has no workload selector in it and that is causing Kiali to throw an error `KIA0002` about two conflicting resources ... but they don't conflict, because they are in different namespaces:

![image](https://user-images.githubusercontent.com/768067/179305580-8a70c1df-345e-4e5d-b4c2-e97679d2ea7d.png)
![image](https://user-images.githubusercontent.com/768067/179305598-60c1ccf0-a095-43af-a783-474530cf447b.png)

Slack Thread: https://istio.slack.com/archives/CJVRXB09F/p1657895790021149

**Comment by hhovsepy** [comment]
Thank you @diranged for logging this issue, the fix will be included in upcoming Kiali v1.55 release.

**Comment by diranged** [comment]
Thank you!
