### ISSUE TITLE
Change default value of spec.external_services.istio.config_map_name in Kiali CR from Kiali Operator

### ISSUE THREAD

**Issue by amantayal5** [kiali/kiali#5311]
Can we create an environment variable for updating the default value of spec.external_services.istio.config_map_name in Kiali CR from Kiali Operator like we do for Kiali CR image name and version?

**Comment by jmazzitelli** [comment]
No. This is what the Kiali CR is for - you indicate what your Istio control plane settings are. The proposed environment variable being set on the operator will now lock it into a single control plane with a specific config map name, possibly breaking multi-tenancy support. Plus, that isn't the only thing that is unique to a control plane - so soon you will need additional environments, until the number of env vars explode and start duplicating Kiali CR settings, which completely defeats the design of the operator and the Kiali CR.

The ability to fix the Kiali image name and version is independent of the control plane and the purpose for those settings is security related. The admin installing the operator may want to fix what binary is deployed in the cluster when a user creates a Kiali CR. Being able to fix the image allows the admin complete control over what binaries are executed in the cluster if they so choose. So its use case is much different than what is bring proposed here.
