### ISSUE TITLE
Kiali Service Entries

### ISSUE THREAD

**Issue by dimitarshenkov** [kiali/kiali#5315]
### Discussed in https://github.com/kiali/kiali/discussions/5301

<div type='discussions-op-text'>

<sup>Originally posted by **dimitarshenkov** July 13, 2022</sup>
We have same Service Entries for the Vault and Redis but Kiali shows them like separated points  , is it normal , can it be fixed ?
![image](https://user-images.githubusercontent.com/99493924/178716226-60e13e7b-8548-4e5a-af95-fd79d37ccdc8.png)

</div>

**Comment by jshaughn** [comment]
@dimitarshenkov , I think this was explained in the related discussion.  If that is satisfactory please close this issue.
