### ISSUE TITLE
Move QPS and Burst parameters to config

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#532]
There are a couple of parameters fixed as constants that can be moved and read them from the config package:

https://github.com/kiali/kiali/blob/c1c9551daf6cf8eea3053ac42056ac5fd3b1c14a/kubernetes/client.go#L26

**Comment by lucasponce** [comment]
JIRA reference:
https://issues.jboss.org/browse/KIALI-1669

**Comment by lucasponce** [comment]
@abonas I think it's enough just adding the hacktoberfest label, isn't it ?
It's how I see other projects are doing.

**Comment by abonas** [comment]
> @abonas I think it's enough just adding the hacktoberfest label, isn't it ?
> It's how I see other projects are doing.
yes, typically it is, however @theute asked all hacktoberfest issues to be in a separate repo, not to confuse users going forward because we use JIRA for issues in day to day activities and not github.

**Comment by aljesusg** [comment]
Let me create the issue in Hacktoberfest for this. Thanks @lponce @abonas

**Comment by aljesusg** [comment]
https://github.com/kiali/hacktoberfest18/issues/8

**Comment by aljesusg** [comment]
Moved to https://github.com/kiali/hacktoberfest18/issues/8
