### ISSUE TITLE
Add dates in chart tooltips

### ISSUE THREAD

**Issue by israel-hdez** [kiali/kiali#5320]
Charts have tooltips showing the time of each datapoint:

![image](https://user-images.githubusercontent.com/23639005/180027490-52d825ed-e035-4759-a266-cfe064b60983.png)

However, like in the previous image, when the data of the resulting chart covers more than one day, it is not possible to distinguish where each data point lives, making it harder to diagnose problems (i.e. it is not possible to manually adjust the duration to "zoom-in").

Perhaps, in the _Dashboards_ the x-axis labels can be used to find the day. However, all Kiali charts are affected. So, for example, the graph side-panel and the overview page charts don't offer x-axis legends.

In the given example the chosen duration guarantees that the resulting charts will span several days. However, even shorter durations can potentially lead to charts covering more than one day. Probably, dates should be shown *only* if the data points span over more than one day.

**Comment by lucasponce** [comment]
I think that the implementation doesn't have this flexibility in the x-axis. Also, consider that the labels are dynamic, meaning that on different "width" resolutions, the amount of info is hidden to give a good overview to the user.

But it sounds like the tooltip can be improved on these scenarios as well, showing not only the time but the date on these cases (that several days are involved), but I think a major change in the x-asis legend would have more non-desire side effects.

**Comment by israel-hdez** [comment]
I indeed was thinking on targeting the tooltip for the enhancement and leave untouched the axis. But after re-reading my comment, I see I didn't give any clue that I'm talking about the tooltips :-)
