### ISSUE TITLE
[Cypress] graph_find and graph_hide input validation 

### ISSUE THREAD

**Issue by matejnesuta** [kiali/kiali#5329]
- When I visit the /console/graph/namespaces/ 
- I unselect all the namespaces
- Both the graph find and graph hide text fiels will evaluate any string as valid.

![image](https://user-images.githubusercontent.com/45061792/180415035-8d6b5c6c-1ddd-4453-a935-f52c0b94ae26.png)
![image](https://user-images.githubusercontent.com/45061792/180415181-4f735a54-cd12-404c-91f9-2268538ab0ad.png)

Expected result was to see the string not valid when nothing is selected. Is this a bug, or a feature?

**Comment by jmazzitelli** [comment]
I suspect that is a bug. @jshaughn would know what the expected behavior should be.

**Comment by jshaughn** [comment]
I would say it's a "quirk" :-)  A minor bug due to the fact that find/hide is not actually applied when there is no graph.  I'll set this as "help wanted", if it's important to you we'd happily guide a contribution PR.
