### ISSUE TITLE
[helm] be able to specify custom annotations on the Kiali CR

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#5334]
(requested by @oreonl) This would allow specifying custom annotations on the kiali cr when it is created by the helm chart. I specifically need this so that I can tell Argo CD to have it in a later sync wave so during a delete operation the cr is removed before the operator.

(This has already been [implemented](https://github.com/kiali/helm-charts/pull/155) - but we want a github issue documenting the request - for one reason, issues are required in order for the auto-generation script to get issues into the release notes)

**Comment by jshaughn** [comment]
> This has already been https://github.com/kiali/helm-charts/pull/155

@jmazzitelli Can we close the issue?

**Comment by jmazzitelli** [comment]
yes. this has been implemented and shipped with 1.54
