### ISSUE TITLE
Istio Config editor - error reporting in messaging center 

### ISSUE THREAD

**Issue by ScriptingShrimp** [kiali/kiali#5340]
Given I open `Istio Config > Namespace: bookinfo > VirtualService > bookinfo`
And I have `0` notifications in Message Center 
![image](https://user-images.githubusercontent.com/86114326/180977539-5afed8ed-f893-4489-bc75-2ad9a3252d0c.png)

When I change in YAML editor port nuber on non existent i.e. `90800` 
![image](https://user-images.githubusercontent.com/86114326/180977643-47d29bb2-0ac5-4536-9de1-26af86459954.png)

And I hit `Save`
Then I receive notification in UI (red banner)
![image](https://user-images.githubusercontent.com/86114326/180977925-754fbf51-543c-4590-9067-19c1ce2da500.png)

And I receive event in Message Center
![image](https://user-images.githubusercontent.com/86114326/180978589-0d37aae2-d00d-4caf-8ac2-68e5aacf0379.png)

And on line no. 1 in YAML editor I can see propagated error
![image](https://user-images.githubusercontent.com/86114326/180978478-9d14759a-2222-426b-8195-ea67a9f759f8.png)

And I can see network event in dev console 
```error	"admission webhook \"validation.istio.io\" denied the request: configuration is invalid: port number 90800 must be in the range 1..65535"```

so far so good
now I change port back to `9080`
and create another error, i.e. deleting host in destination route (line no. 64): 
![image](https://user-images.githubusercontent.com/86114326/180981352-22944782-08a8-4d0a-ab4d-c2fc7ed97ee0.png)

I hit save
I do receive notification in Messaging Center 
![image](https://user-images.githubusercontent.com/86114326/180979695-30e623ad-33d4-4380-ad67-8829d870facb.png)
Error in YAML editor looks OK for now 
![image](https://user-images.githubusercontent.com/86114326/180980829-60871005-fb47-4bd5-8768-b37ced3fc066.png)
network tab showing only one error received, thats also OK
```error	"admission webhook \"validation.istio.io\" denied the request: configuration is invalid: empty domain name not allowed"``` 

**possible problems:**
1. I do not receive notification in UI (red popup, see screenshot above) on second try (I guess its because of 2)
2. The message in Message Center is same as before, second (different event) was aggregated wrongly under previous message see (2 events in 10 mins)
![image](https://user-images.githubusercontent.com/86114326/180980051-0127ecbd-cb1a-44c6-b7ae-3b5c068c5832.png)
3. when 2 happens, context of last message (empty domain name not allowed) is lost in messaging center

**Comment by jshaughn** [comment]
If I understand correctly, the Message Center seems to be operating as it should.  Repeated messages correctly get aggregated, increasing the counter, without generating individual toast messages.   The question seems to be whether the new message, "empty domain...", was somehow  suffocated, and not sent to the message center.  Is that correct?

**Comment by ScriptingShrimp** [comment]
> Repeated messages correctly get aggregated
No, they do not in this case. I created 2 different events/messages and they both get aggregated under single event. It should be obvious from steps how to reproduce
> new message ... suffocated
Yes, but it increased counter on the previous message, so context was lost

**Comment by jshaughn** [comment]
What I'm saying is that the MC may be getting sent the wrong message.  It should become clear when investigated.

**Comment by israel-hdez** [comment]
There is this note in the code:

https://github.com/kiali/kiali/blob/f93a113d62afa3faef6f6339bd1b8c54a66fd6c9/frontend/src/reducers/MessageCenter.ts#L86-L91

So, errors have 2 parts: the main message (which is what is shown in the toast when a new message is logged), and the detail (which can be somewhat technical) that is shown in the gray textarea.

Only the main message is used to check for repeated messages, because the details may vary only subtly. But this is a case when such assumption does not hold.

Probably, the Message Center should keep the same method for finding duplicates, but show the detail of the last replica rather than the first replica.

**Comment by jshaughn** [comment]
> Probably, the Message Center should keep the same method for finding duplicates, but show the detail of the last replica rather than the first replica.

+1, that seems like a decent enhancement.  Update with the most recent detail.
