### ISSUE TITLE
Overview istio-config doesn't match details kiali 1.49

### ISSUE THREAD

**Issue by ceastman-r7** [kiali/kiali#5342]
The overview page shows 10 istio config objects analyzed (no issues found) but the details page only shows 3 valid files:

Kiali
v1.49.0 (9bad8de83d2ff207e10c6df1720013a8d5ccf909)

<img width="513" alt="Screen Shot 2022-07-27 at 10 39 22 AM" src="https://user-images.githubusercontent.com/97614291/181289928-2bc0bb4a-c352-4505-abc9-c22183f714be.png">
<img width="1564" alt="Screen Shot 2022-07-27 at 10 39 33 AM" src="https://user-images.githubusercontent.com/97614291/181289932-5c36a8eb-e3cd-4e37-b890-edd0ba684e76.png">

fyi: same cluster used for https://github.com/kiali/kiali/issues/5343

**Comment by hhovsepy** [comment]
The fix will be released within upcoming Kiali v1.55
