### ISSUE TITLE
Overview istio-config doesn't match details kiali 1.54

### ISSUE THREAD

**Issue by ceastman-r7** [kiali/kiali#5343]
The overview page shows 10 istio config objects analyzed (7 issues found) but the details page only shows 3 valid files:

Kiali
v1.54.0 (2d2eceebd5827548e9eb5ad9948988b31d390bc3)

<img width="1569" alt="Screen Shot 2022-07-26 at 3 26 52 PM" src="https://user-images.githubusercontent.com/97614291/181291005-6fa2f6e9-0a9f-4afe-ae58-b1661df053ad.png">
<img width="516" alt="Screen Shot 2022-07-26 at 3 26 15 PM" src="https://user-images.githubusercontent.com/97614291/181291009-73d5b7de-ea95-4e44-a3ea-2f082de7694e.png">

fyi: same cluster used for issue: https://github.com/kiali/kiali/issues/5342

**Comment by hhovsepy** [comment]
The fix will be released within upcoming Kiali v1.55
