### ISSUE TITLE
[CI] Test flake - Service details page

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#5358]
Failure in the service details test during the `See span info after selecting a span` test.

Output from CI failure:
```
   Kiali Service Details page
    ✓ See details for productpage (2670ms)
    ✓ See details for service (1065ms)
    ✓ See minigraph for details app. (604ms)
    ✓ See Traffic information (1038ms)
    ✓ See Inbound Metrics for productspage service details (9020ms)
    ✓ See Graph data for productspage service details Inbound Metrics graphs (1599ms)
    ✓ See graph traces for productspage service details (2635ms)
    1) See span info after selecting a span


  7 passing (1m)
  1 failing

  1) Kiali Service Details page
       See span info after selecting a span:
     CypressError: Timed out retrying after 40050ms: `cy.click()` failed because this element is detached from the DOM
```

Link to CI run: https://github.com/kiali/kiali/runs/7617242496?check_suite_focus=true

Screenshot from test failure:
![Kiali Service Details page -- See span info after selecting a span (failed)](https://user-images.githubusercontent.com/6226732/182219165-767c6d6f-4f34-4d34-86b8-b10375994218.png)

**Comment by josunect** [comment]
What about adding a retry configuration to prevent failing the CI due to any flaky test? 

This is suggested in the cypress documentation: 
https://docs.cypress.io/guides/dashboard/flaky-test-management

Aside from reviewing these tests, but it could help.
