### ISSUE TITLE
JS Error: Can't perform a React state update on an unmounted component

### ISSUE THREAD

**Issue by josunect** [kiali/kiali#5361]
JS Error: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.

Steps to reproduce: 

- Navigate to workloads 
- Click on a workload to see the details
- Navigate throw the tabs (Overview, Traffic, etc.) 

![image](https://user-images.githubusercontent.com/49480155/182325246-02f018f1-cb30-470d-b89d-a12000dba54c.png)

Epic https://github.com/kiali/kiali/issues/4789

**Comment by josunect** [comment]
There are some ways for fixing this error:

- Check if the component is unmounted is considered an anti pattern 
- Use of Useeffect
- Use of AbortController API to cancel the queries. 

Some references: https://medium.com/doctolib/react-stop-checking-if-your-component-is-mounted-3bb2568a4934

React is going to remove this warning in future versions: https://github.com/facebook/react/pull/22114
To avoid false positives. The memory leak can be caused setting the state after the component was unmounted, but it also can be triggered by awaiting a promise, which is a false positive.

**Comment by lucasponce** [comment]
Hi @josunect, it sounds that perhaps there is some promise that is on the fly and updating the tracing component when it's not being used.

I think we had a helper to cancel them that perhaps it's not working here; let me take a look at the code to help you with the approach; perhaps to fix this, we don't need to perform any significant change but just to organize these promises when tab changes.

**Comment by lucasponce** [comment]
I couldn't reproduce the issue in master
![image](https://user-images.githubusercontent.com/1662329/182829856-6e594b94-1513-41ad-8ce9-a2379a7dcb6a.png)

Is this something you always see in your side?

I mean, if it's that the case, it's ok to lower the priority of this one, I think

**Comment by josunect** [comment]
I see the error happening when you quickly click in different tabs, but not just with the trace Tab. 
[Screencast from 04-08-22 12:00:39.webm](https://user-images.githubusercontent.com/49480155/182831542-3d69fa53-581c-42aa-9ccb-1d08a047bf4e.webm)

But yes, it look a bit random so I'm agree in put the priority lower.
