### ISSUE TITLE
Document Kiali Istio registry requirements

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#5375]
Kiali uses the Isito registry to gather information about the mesh. It'd be helpful to document exactly which registry endpoints are used by Kiali e.g. `/debug/registryz` and what, if any, are the auth requirements.

**Comment by jshaughn** [comment]
@nrfox I think maybe this can be closed with the introduction of no-istiod support, and the associated docs about what is degraded in Kiali when the /deug endpoints are not available?
