### ISSUE TITLE
Architecture is outdated - direct istio dependency

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#5376]
The [Kiali architecture section and diagram](https://kiali.io/docs/architecture/architecture/#kiali-architecture) both suggest that istio/istiod are indirect dependencies but now Kiali does directly rely on and communicate with istio/istiod to gather information about workloads and services.

**Comment by jshaughn** [comment]
Adding to backlog, this should be updated as part of the deployment model updates we are currently working on.

**Comment by josunect** [comment]
@jshaughn @nrfox Do you know if the original diagram is uploaded somewhere? (Not as an image) So we don't have to draw it from scratch

**Comment by jshaughn** [comment]
@nrfox Please include this as part of what you are doing for https://github.com/kiali/kiali.io/pull/657.
