### ISSUE TITLE
Debug information autoscroll when copying from the text field

### ISSUE THREAD

**Issue by matejnesuta** [kiali/kiali#5384]
Found this one during the "Help" dropdown testing.

When I open the Help dropdown and choose the "View Debug Info", I am presented with a modal, which includes two text fields. It's entire content gets copied after a single click or with the "Copy" button. 

The issue is that it scrolls automatically all the way to the bottom when the content is copied either with the button, or with the click. It's confusing visually and if I wanted to read it's content, one accidental click could ruin it. 

Before copying:
![image](https://user-images.githubusercontent.com/45061792/184929337-d31c4c61-6a98-4eaa-b9b4-2655bf145a3c.png)

After copying:
![image](https://user-images.githubusercontent.com/45061792/184929529-4a26768b-35b9-468d-a748-5ed36c3f0efa.png)

The "Health config" behaves differently even though it looks exactly the same as the bottom field, which is a little confusing as well. 

Not sure, if bug or a feature.

**Comment by jmazzitelli** [comment]
I have always hated that separate "health config" text box at the top. Why is "health config" special? It is already in the debug yaml. This just duplicates the output and makes this page more complicated and confusing than it needs to be.

I say we take this opportunity to collapse this dialog window so it only shows the full "Please include this information" text area and removes that health yaml which, as I understand, is nothing more than a subset of what you see in the full yaml text area.

**Comment by jshaughn** [comment]
I agree about those two sections, I never really understood that.  Also, don't we use a nice YAML editor in other places, why not here?  Having said all that, this is pretty low priority.  I'll add to the backlog but also a "Good First issue", maybe we can get a contribution.

**Comment by jmazzitelli** [comment]
> Also, don't we use a nice YAML editor in other places, why not here?

+1... that's a good idea.

**Comment by jshaughn** [comment]
Closing as this page has now been redesigned.
