### ISSUE TITLE
 Error running install-testing-demos.sh in OpenShift 4.11

### ISSUE THREAD

**Issue by josunect** [kiali/kiali#5394]
Error running install-testing-demos.sh, as error-rates-demo won't start. Many warnings:

`Warning: would violate PodSecurity "restricted:v1.24": allowPrivilegeEscalation != false (container "a" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "a" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "a" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "a" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
`

Pods are unable to start: 

![image](https://user-images.githubusercontent.com/49480155/185634151-040bdbe8-ac1e-49aa-b15e-2fb1c7674590.png)

The problem seems to be related the security constraint: 

![image](https://user-images.githubusercontent.com/49480155/185634271-bc3df3d2-52c6-4970-8c4b-7d4e6400f45b.png)

### Environment

```
CRC version: 2.7.1+a8e9854
OpenShift version: 4.11.0
Podman version: 4.1.1
```

### Notes 

- Moving the securityContextConstraints before applying the yaml, removes all the warnings. 
- applying the following removes the issue:

`$CLIENT_EXE adm policy add-scc-to-user privileged -z default -n ${NAMESPACE_ALPHA}`

**Comment by jshaughn** [comment]
cc @jmazzitelli

**Comment by josunect** [comment]
Most workloads can be made compliant by the following simple changes: https://github.com/openshift/cluster-openshift-controller-manager-operator/pull/240/files (random simple example)

**Comment by jmazzitelli** [comment]
@josunect for my benefit, what changed in 4.11? Do we no longer get the default service account? Or do we need something in addition now?

**Comment by josunect** [comment]
> @josunect for my benefit, what changed in 4.11? Do we no longer get the default service account? Or do we need something in addition now?

The k8s API for the Pod security policy has changed and it has been replaced by the Pod Security Admission, so it looks like we need something in addition now in the SCC definitions. 

This is a discussion related to the operator changes that may be helpful for the operator changes: https://github.com/redhat-openshift-ecosystem/community-operators-prod/discussions/1417
