### ISSUE TITLE
Create liveliness and ready probes for Kiali pod (hacktober fest)

### ISSUE THREAD

**Issue by vnugent** [kiali/kiali#540]
**Describe the bug**
Create liveliness and ready probes for Kiali pod
Health probes documentation: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/

Kiali pod definition:
- Kubernetes:  https://github.com/kiali/kiali/blob/master/deploy/kubernetes/kiali.yaml
- OpenShift: https://github.com/kiali/kiali/blob/master/deploy/openshift/kiali.yaml

**Comment by aljesusg** [comment]
@vnugent I don't know if you set (hacktoberfest) for the event...in that case you should create this issue here https://github.com/kiali/hacktoberfest18/issues and set a JIRA related.

**Comment by vnugent** [comment]
Sorry wrong place.  I'll try to move this over there.
