### ISSUE TITLE
[Cypress] kiali tests are using oc instead kubectl in tests

### ISSUE THREAD

**Issue by ScriptingShrimp** [kiali/kiali#5423]
There is request to interchange `kubectl` command for `oc` command in cypress tests in specific pipelines.
i.e. https://github.com/kiali/kiali/blob/e2e90ed90f9f0d7b719f7dcf1504f3ff77adaeae/frontend/cypress/integration/common/istio_config.ts#L123

concern of our client is that kiali is tested with OCP platform

**Comment by jshaughn** [comment]
Closing as obsolete.
