### ISSUE TITLE
Improvement to refresh k8s token when it changes

### ISSUE THREAD

**Issue by josunect** [kiali/kiali#5430]
This is an improvement for #5070 
Remove TODO in [kubernetes/token.go](https://github.com/kiali/kiali/pull/5386/files#diff-6e5cc46de4acd4f2fbdf18019eb4d8114aa3b7fefa56561dfd1f9e13ece8902a)

See @nrfox comments https://github.com/kiali/kiali/pull/5386#discussion_r959841332

**Comment by jshaughn** [comment]
Closing, this optimization has not been a problem for users.
