### ISSUE TITLE
Review install demos scripts to check if work in OpenShift 4.11

### ISSUE THREAD

**Issue by josunect** [kiali/kiali#5431]
Some of the demos were already validated:

- https://github.com/kiali/kiali/issues/5394 Testing demos used by QE (bookinfo, error rates and sleep), and Travel demo

There are others that also would need to be validated:  

- [x] electronic shop
- [x] fraud detection
- [x] music store
- [x] runtimes
- [x] scale-mesh
- [x] service spawner
- [x] topology generator

**Comment by jmazzitelli** [comment]
This issue is related: https://github.com/kiali/kiali/issues/5426

**Comment by jshaughn** [comment]
If the demos don't work that's bad.  We will need to run through these on OCP 4.11 or later.
