### ISSUE TITLE
[CI] Test flake - Sidebar toggle

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#5437]
Sidebar toggle test fails when login flash page flashes. My guess is that when the login page flashes the navbar is unmounted where it previously existed causing the query to fail.

https://github.com/kiali/kiali/runs/8183621567?check_suite_focus=true

Screenshot:
![Sidebar toggle -- Open the sidebar (failed)](https://user-images.githubusercontent.com/6226732/188677267-6ca45b3f-463d-42df-9a8c-26b553524fc7.png)

**Comment by jshaughn** [comment]
Note that @josunect is working https://github.com/kiali/kiali/issues/5232, so the flash may go away and therefore fix this flake.

**Comment by nrfox** [comment]
> Note that @josunect is working https://github.com/kiali/kiali/issues/5232, so the flash may go away and therefore fix this flake.

I don't think the two are related. In this case the tests just need to wait for the page to settle and finish loading before starting. We're seeing this fail in the OCP pipeline often which doesn't use anonymous auth so my initial guess about the login page flashing was probably wrong.

This needs to be added to the backlog though because of the frequency of the flakes.
