### ISSUE TITLE
[hack] setup kind in ci finalising with error

### ISSUE THREAD

**Issue by josunect** [kiali/kiali#5441]
See last actions from today: 
- https://github.com/kiali/kiali/actions/runs/3006919268
- https://github.com/kiali/kiali/actions/runs/3006995189

The error: 

```
resource mapping not found for name: "controller" namespace: "" from "https://raw.githubusercontent.com/metallb/metallb/v0.12.1/manifests/metallb.yaml": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
deployment.apps/controller created
ensure CRDs are installed first
resource mapping not found for name: "speaker" namespace: "" from "https://raw.githubusercontent.com/metallb/metallb/v0.12.1/manifests/metallb.yaml": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
ensure CRDs are installed first
Error: Process completed with exit code 1.
```

https://kubernetes.io/docs/reference/using-api/deprecation-guide/

Looks like is using version 1.25: 

```
Creating cluster "ci" ...
 • Ensuring node image (kindest/node:v1.25.0)
```

As a workaround can we force the use of 1.24. 
Or, review if there is any compatible version in from the load balancer.

**Comment by nrfox** [comment]
We can use the workaround for now to fix the pipeline but we'll also want to fix the issue long term so that we can keep testing with the latest kube versions.
