### ISSUE TITLE
Move Kiali<->Istio version checks to the "About" dialog

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#5457]
We, yet again, screwed up the compatibility matrix for the latest release. Someone installed 1.56.1 on Istio 1.14 (which should work) but got a warning in the UI.

I call for a vote. We need to do one of two things:

1. Get serious about the compat. matrix in the code (and by serious, I suggest we automate updating the compat matrix file in the code during the build/release CI workflow)

or 

2. Get rid of it.

Right now, it isn't working. It is a maintenance headache to get right. Everytime Istio or kiali does a release, it screws up. No one is taking the lead on making sure it is correct/testing it.

**Comment by jmazzitelli** [comment]
but that is not what our docs say https://kiali.io/docs/installation/installation-guide/prerequisites/#version-compatibility
```
1.14	1.50.0 or later	
1.13	1.45.1 to 1.49.x	
1.12	1.42.0 to 1.44.x	
```

**Comment by jmazzitelli** [comment]
> Or, we could avoid UI messaging completely and defer to log messages only. Andthen if someone reports an issue we can ask them to check the logs.

I would be ok if we at least reduce the noise and make this a log message only.

**Comment by israel-hdez** [comment]
> Or, we could avoid UI messaging completely and defer to log messages only. Andthen if someone reports an issue we can ask them to check the logs.

I don't know... I think that will reduce a lot the value of the feature. Even for us, it is going to be easier to ask people for versions of Kiali and Istio and reply back with incompatibilities (if any), like we've been doing. I know that other apps use logs for this, but we still need to ask for version numbers to know if issues are already fixed in newer versions. So, for our specific case, asking to check logs may end up being an unneeded extra hop.

That leads to my suggestion: Since we usually ask people to check the about modal to find the versions, maybe the about dialog is a better place for such warning. Another option could be the debug dialog.

**Comment by jshaughn** [comment]
I think I'd be OK with the about box as opposed to the message center.

**Comment by israel-hdez** [comment]
BTW, Mazz is asking for a vote.

I'm +1 to removing the compat matrix from the code. If vote to keep, then what is important is to fix the maintenance issue, which is already mentioned.

I'm OK if we want to reduce the noise for now. But then, I'm wondering what's the goal of that? To me, sounds like that we want to keep the matrix, yet we don't want people to see the warning (or at least we would be making it hard to notice it). If people won't see the warning, I don't see any value of maintaining the matrix in the code and maintaining docs should be preferred (which are much easier to fix).

Don't get me wrong. I agree that there is value on having such matrix. We are delivering it in the form of version checks and also in the docs. The docs are fine, however version checks loose its value if they are going to be less prominent.

**Comment by Xunzhuo** [comment]
I am Ok with this, but question is that how do we maintain version compatibility matrix after removing this? Just by doc references? This will need to be updated too when releasing new versions of kiali and istio.

**Comment by leandroberetta** [comment]
I'm +1 to removing the compat matrix from the code. Not from docs.

**Comment by israel-hdez** [comment]
@kiali/maintainers this needs more of your input.

**Comment by nrfox** [comment]
I'm in favor of moving it to the about modal and logging a warning message in the Kiali server. It does somewhat reduce the value of the feature but it doesn't make it worthless. It's reasonable to expect people to check Kiali logs for warning/error messages if they are having issues. In addition, having the version compatibility message next to the Kiali version info in the about modal seems like an intuitive place for it even if it is more hidden than the current notification.

I also think we should have a manual step in the release process to keep the compatibility matrix in the docs and/or code up to date. It will need to be manually checked for accuracy somewhere so making it part of the (pre)release process seems like the best place to do this.

**Comment by josunect** [comment]
I wouldn't keep the compatibility matrix if this is making more noise than help. 

Said that, I think this is useful information and I vote for look for an easiest way to maintain it, and keep the matrix. Moving it to a box instead of the message center would be ok, it is not so intrusive.

**Comment by jmazzitelli** [comment]
That is an interesting idea - to move the information to the About Box.

**Comment by jshaughn** [comment]
+1 to moving to about box and possibly a log message.  I'm not for removing the matrix; we have had some reports of invalid warnings but we don't know whether valid warning may have helped some users.  And we added the feature for a reason.  I don't think the compat check is bad, I think we need to introduce better release procedures, especially for manual steps like checking this matrix and generating release notes.

**Comment by israel-hdez** [comment]
OK, let's move the warning to the about box.
Perhaps, next time we forget updating this, we should consider automating it, which I don't think it's hard to do.

**Comment by ScriptingShrimp** [comment]
I'm wondering if we can write some sort of test - verify that there are no error messages displayed if we have correct versions of kiali + isito depoyed.

**Comment by israel-hdez** [comment]
There are a few units here: https://github.com/kiali/kiali/blob/2c0007cddebcc2f4a61ca00c6432a8b7840974e1/status/versions_test.go

In Cypress I think the best we can do it to assume that the env is using compatible versions and check that there is no warning message. I'd expect it to break as releases happen. It wouldn't be a deterministic test, so I don't know if that would be OK because a red trial would need manual review rather than immediately concluding a failure in Kiali.
