### ISSUE TITLE
[CI] Test flake - Kiali Graph page - Find/Hide

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#5465]
Looks like the info menu has closed for some reason. Probably there's a race condition between the initial graph loading and the menu being open. You can somewhat reproduce this locally by throttling requests in your browser on the graph page then quickly opening the info icon before the requests have finished loading.

Error from CI:
> CypressError: Timed out retrying after 40050ms: `cy.click()` failed because the center of this element is hidden from view:

Screenshot from CI:
![Kiali Graph page - FindHide -- Show Graph FindHide help menu (failed)](https://user-images.githubusercontent.com/6226732/190208512-aa250c74-762b-4874-b99e-f540cdc96fe1.png)

Run: https://github.com/kiali/kiali/actions/runs/3053859672/jobs/4925225844

**Comment by jshaughn** [comment]
afaik, this will be resolved as part of the work in https://github.com/kiali/kiali/pull/5463.  Assigning to @nrfox as he owns that one as well.

**Comment by jshaughn** [comment]
@nrfox Did #5463 solve this issue?

**Comment by nrfox** [comment]
I haven't seen it again personally and I haven't been able to reproduce locally. Closing for now.
