### ISSUE TITLE
Duration query parameter not working in kiosk mode for application view

### ISSUE THREAD

**Issue by larhauga** [kiali/kiali#5469]
It looks like the ?duration query parameter is not respected when kiosk query parameter is set to true: `?kiosk=true` and the page is for application. It then defaults to 60 seconds.

Could this be a bug since the datepicker is not present on the page in kiosk mode? Is there a workaround for this?

**Comment by jshaughn** [comment]
Hi @larhauga , can you please supply version information?

**Comment by larhauga** [comment]
> Hi @larhauga , can you please supply version information?

Hi @jshaughn, we are running the following version:

Kiali v1.55.0 (f1c32fc6abb0ad590cd75715b94054622a98d8f3)
Kiali Container v1.55.0

**Comment by jshaughn** [comment]
Hi @larhauga , I think this is true for kiosk mode, for the reasons you mention above.  But there has recently been some work done in this area, to bring the duration/refresh control into kiosk mode.  It will be in v1.57, to be released on Sep 26, and I think it will solve your problem.  See https://github.com/kiali/kiali/pull/5412 for the details.  Let us know if that doesn't solve your issue.

**Comment by larhauga** [comment]
Thanks @jshaughn :). Appreciate it! Closing this issue, and looking forward to the release!
