### ISSUE TITLE
[CI] Test flake - Service Details Traces - Spans

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#5499]
https://github.com/kiali/kiali/actions/runs/3134707511/jobs/5089689440

`Kiali Service Details page
 See span info after selecting a span:
 CypressError: Timed out retrying after 40050ms: cy.click() failed because this element is detached from the DOM.`

**Comment by jshaughn** [comment]
This is the same one we have tried to fix several times now.  Personally, I don't think this test needs to click that menu to prove this page is working.  I think the issue has something to do with scrolling but we can't seem to nail it down and it's not particularly relevant to the test.  I'm just going to remove the click and be satisfied with the menu existence.
