### ISSUE TITLE
[helm] install warning about missing seccompProfile

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#5517]
Installing the operator via helm chart on OpenShift 4.11:

```
helm install --set image.tag=v1.57.0 --namespace kiali-operator --create-namespace kiali-operator kiali/kiali-operator
```

results in this warning (however, the operator starts OK):

```
W0930 10:14:03.644628 3070538 warnings.go:70] would violate PodSecurity "restricted:v1.24": seccompProfile (pod or container "operator" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
```

I solved this by adding the `seccomProfile.type=RuntimeDefault` to the securityContext. Here's how it would change:

```diff
diff --git a/kiali-operator/templates/deployment.yaml b/kiali-operator/templates/deployment.yaml
index 87204b9..87e2031 100644
--- a/kiali-operator/templates/deployment.yaml
+++ b/kiali-operator/templates/deployment.yaml
@@ -48,6 +48,8 @@ spec:
         {{- if .Values.securityContext }}
         {{- toYaml .Values.securityContext | nindent 10 }}
         {{- else }}
+          seccompProfile:
+            type: RuntimeDefault
           allowPrivilegeEscalation: false
           privileged: false
           runAsNonRoot: true
```

I thought I did this before and under certain environments, this failed. I don't remember. But whoever works on this, needs to test the solution on different environments, specifically at least k8s 1.24 or 1.25 as well as OpenShift 4.10 and 4.11.

Interestingly, I don't see this when I install the server using the server helm chart. I don't know why, but I suspect it is because the istio-system namespace was given some SCC or something of the sort that bypasses the warning. Because if I install the server in some random/new namespace, I do see the warning:

```
$ helm install --set auth.strategy=anonymous --namespace mazz --create-namespace kiali-server kiali/kiali-server
W0930 10:31:57.076237 3075768 warnings.go:70] would violate PodSecurity "restricted:v1.24": seccompProfile (pod or container "kiali" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
...
```

So the same solution for the operator change will probably also need to be implemented/tested in the server chart also. And we may need to change the operator's templates so when it installs the server it sets this field, also. Again, I am pretty sure I played with this setting before and saw different behavior across different clusters (openshift vs k8s, and across different versions such as between 4.10 and 4.11). So thorough testing will be needed here.

**Comment by jmazzitelli** [comment]
The difference is that istio-system somehow got the "baseline" pod security profile, but a new namespace that is created seems to get "restricted" by default:

```
$ kubectl get ns istio-system  -o jsonpath={.metadata.labels} | jq
{
  "kubernetes.io/metadata.name": "istio-system",
  "pod-security.kubernetes.io/audit": "baseline",
  "pod-security.kubernetes.io/audit-version": "v1.24",
  "pod-security.kubernetes.io/warn": "baseline",
  "pod-security.kubernetes.io/warn-version": "v1.24",
  "topology.istio.io/network": ""
}

$ kubectl get ns mazz -o jsonpath={.metadata.labels} | jq
{
  "kubernetes.io/metadata.name": "mazz",
  "pod-security.kubernetes.io/audit": "restricted",
  "pod-security.kubernetes.io/audit-version": "v1.24",
  "pod-security.kubernetes.io/warn": "restricted",
  "pod-security.kubernetes.io/warn-version": "v1.24"
}
```

**Comment by jshaughn** [comment]
No obvious work to do here, closing.
