### ISSUE TITLE
How Kiali identifies Ambient

### ISSUE THREAD

**Issue by josunect** [kiali/kiali#5535]
How Kiali can identify if Istio is running in ambient mode. 

- It is a istio-proxy ambient pod? It has the vars ISTIO_META_AMBIENT_TYPE = ztunnel
- If a pod is part of an ambient mesh, it should be labeled with ambient-type=Component (Ex. workload, etc)

**Comment by israel-hdez** [comment]
Have you inspected Istio's ConfigMap?
Sometimes, some configs are also there.

**Comment by josunect** [comment]
> Have you inspected Istio's ConfigMap? Sometimes, some configs are also there.

Thanks for the idea, @israel-hdez ! I was thinking in using a label to check whether a pod is part of an Ambient mesh.

**Comment by josunect** [comment]
> > I was thinking in using a label to check whether a pod is part of an Ambient mesh.
> 
> Well, that's different :-) I was thinking on the global config. But checking if a pod is on "ambient mode" is something that probably can only be done by inspecting the pod :-)

Yes, sorry, it was not very detailed in the description. 
Maybe this is also something good to know, and add it into the GUI somewhere. 

Ambient is experimental at this point, but at the moment, if we setup Istio with Ambient profile, we can inject sidecars, so maybe is not so relevant at a global point of view to see if we are not running Ambient or not?

**Comment by josunect** [comment]
In the Istio Configmap: 

![image](https://user-images.githubusercontent.com/49480155/194833767-8f646fd2-3da1-4959-bd2c-93d76223a37e.png)
