### ISSUE TITLE
CVEs in latest distroless image due to 1.17.10 of go

### ISSUE THREAD

**Issue by zhech2** [kiali/kiali#5538]
REMOVED details of CVEs
Looks like upgrading to go 1.17.13 would fix these.  Is this a change that can be made?

**Comment by jmazzitelli** [comment]
Do any of these affect Kiali? I don't know if this is considered a bug unless someone can show Kiali is affected. For example, https://github.com/advisories/GHSA-2v97-2cxm-mvp4 - Kiali doesn't even use the API in question. So that is irrelevant in the context of Kiali.

**Comment by jmazzitelli** [comment]
Also, please note: https://github.com/kiali/kiali/blob/master/SECURITY.md#reporting-a-vulnerability
