### ISSUE TITLE
remove kiali_api.md

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#5544]
The Kiali API is not for public use, is not supported for public use, and can change from version to version with no guarantee or promise of backward compatibility.

So why do we have [kiali_api.md](https://github.com/kiali/kiali/blob/v1.57.1/kiali_api.md) in the repo?

We even ripped out the auto-generation of that file via swagger a while ago. There is no way we are going to manage to keep that file up to date if we have to manually do it, and people might see it and think (a) it is up to date and accurate and (b) they can use the API outside of the Kiali UI.

Thus, we should delete kiali_api.md entirely.

 Comments?

**Comment by josunect** [comment]
I think kiali_api file can be useful for developers. So I would say, keep it if the cost of maintenance is not high.
If we keep it, I think it should be renamed to something like kiali_internal_api to avoid misunderstanding on its purpose

**Comment by jshaughn** [comment]
+1 to @josunect , keep it as I also think it can be useful, but make it more clear that it is unsupported by naming it something like kiali_internal_api, kiali_api_internal, kiali_api_unsupported, ...
