### ISSUE TITLE
Use Opentelementry Exporter instead of Jaeger

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#5569]
For debugging Kiali itself, Kiali currently uses [the Jaeger exporter](https://github.com/kiali/kiali/blob/master/observability/tracing.go#L39-L42). We should migrate to the [Opentelemetry Exporter](https://pkg.go.dev/go.opentelemetry.io/otel/exporters/otlp/otlptrace#Exporter) to be compatibile with any otel backend.

**Comment by krishnaindani** [comment]
hey, what changes are supposed to be made in order to migrate to otel? Would like to lean more and maybe attempt to solve this issue

**Comment by israel-hdez** [comment]
The OTEL collector supports ingesting Jaeger traces and sending them to any OTEL compatible back-end.

What would be the benefit of migrating to the OTEL exporter if we still would need a Jaeger (or Jaeger compatible) back-end?

**Comment by Xunzhuo** [comment]
I think this can make kiali more compatible to other tracing systems, right? @nrfox

**Comment by nrfox** [comment]
@krishnaindani thanks for the interest. The work involved will be replacing the jaeger client here: https://github.com/kiali/kiali/blob/master/observability/tracing.go#L39-L42 with the otelhttp client: https://pkg.go.dev/go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp. You may also need to update or add some options to the kiali config: https://github.com/kiali/kiali/blob/master/config/config.go#L85-L91 depending on the format of the url that the otlptracehttp lib expects.

> What would be the benefit of migrating to the OTEL exporter if we still would need a Jaeger (or Jaeger compatible) back-end?
>
> I think this can make kiali more compatible to other tracing systems, right? @nrfox

Yes we can export traces from the kiali server to more backends without needing the collector and the Jaeger clients are deprecated: https://www.jaegertracing.io/docs/1.38/client-libraries/#deprecating-jaeger-clients. Although I'm not sure if that includes the otel jaeger exporter that Kiali currently uses.

**Comment by jshaughn** [comment]
@krishnaindani We're still looking for a contribution if you're interested.

**Comment by jshaughn** [comment]
cc @aljesusg , does this play into the Tempo work at all?

**Comment by aljesusg** [comment]
Yes @jshaughn I am going to assign this myself until we check
