### ISSUE TITLE
Show Kiali configuration in the application

### ISSUE THREAD

**Issue by leandroberetta** [kiali/kiali#5588]
The motivation of this is to have a section to display the Kiali config map in a nice and simple way.

It's ok to see the configmap using CLI but it should be easier to see it in Kiali directly.

**Comment by jmazzitelli** [comment]
We should do this in conjunction with fixing that About->Debug box where we have a separate pane with just the health config, which I don't understand. We should make that  About->Debug window better.

**Comment by josunect** [comment]
Where to show this information? 

Maybe it could be added as a new Help item, "Configuration": 
![image](https://user-images.githubusercontent.com/49480155/199092213-9952d35e-9c92-41e7-84fa-a093efdad889.png)

I'm agree to work at the same time improving the view for Debug box, both could have a similar style

**Comment by jshaughn** [comment]
> The motivation of this is to have a section to display the Kiali config map in a nice and simple way.

This would duplicate something you can already do in the OS console, so it would be for upstream only, right?  @leandroberetta, what motivated you to create this RFE?

**Comment by leandroberetta** [comment]
It's true that you have it on the OS console, but it's useful for upstream like you mentioned. Also, even if you have it in console, it's a YAML full of noise (status, definitions, schema). I was thinking to have only the important part (spec). I think it would be super nice to see the configuration spec translated to a more human friendly version, but with the spec part of the yaml I think it's enough, for now.

**Comment by jmazzitelli** [comment]
Yes, only have the `spec`. And consolidate the Debug info - get rid of that health-only config box.

**Comment by israel-hdez** [comment]
If this will go forward, perhaps think a little bit in security.

I know some of the configs are exposed through the `/api/config`. But exposing the whole Kiali ConfigMap, sounds like something that should be done only if the user has the right privileges.

**Comment by josunect** [comment]
Related to https://github.com/kiali/kiali/issues/5384
