### ISSUE TITLE
Remove option to disable kube caching

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#5599]
Caching has been enabled by default for some time now. This issue is to remove the option to disable kube caching. Kiali may still query the kube api directly in some cases but will largely rely on the local cache. Some supported kube types are not currently cached like `CronJob` but these should be added as well.

This is a followup to #5319 and #4678.

**Comment by nrfox** [comment]
Rather than blocking making the cache mandatory on refactoring all the backend unit tests, @israel-hdez had the idea of removing the external config option while keeping the internal cfg option that the unit tests can still set. I think this is a better way forward and we should do this while the test refactoring is on-going.

@israel-hdez I'm assigning you to this task but feel free to unassign yourself or assign someone else.

**Comment by israel-hdez** [comment]
Transferring this issue to @leandroberetta as the new Ωwner.
