### ISSUE TITLE
fix Nightly CI workflow in kiali-operator repo

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#5606]
Ran the Nightly CI job in the kiali-operator repo and got this warning. Guess we need to fix this before it breaks.

```
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

Check other CI workflows in case the same thing needs to be fixed elsewhere.

**Comment by Xunzhuo** [comment]
I am going to fix this.

**Comment by Xunzhuo** [comment]
Close it since it is fixed.
