### ISSUE TITLE
Include an option to hide the control plane card in the Overview Page

### ISSUE THREAD

**Issue by leandroberetta** [kiali/kiali#5607]
Today the Overview Page shows kind of two sections, the control plane and the data plane, being the first, always the first card with a complete different style and set of information. I think it should be good to have a check on the toolbar to quickly filter the control plane card for the user who is for a given moment just interested in the data plane cards.

![image](https://user-images.githubusercontent.com/1286393/199790332-d3413a14-24db-4c89-b996-eebfdd5411d2.png)

Epic: #4435

**Comment by jshaughn** [comment]
Not sure, but if we evolve into having a "Mesh" view then the control plane card may migrate to there completely?

**Comment by leandroberetta** [comment]
It's a good question, I think we should keep some kind of overview for the control plane in the Overview Page... but I also think that we are reaching the limit in terms of space, so every new thing, should be targetted to the new section.

**Comment by jshaughn** [comment]
Closing in favor of migrating control plane card/information to Mesh page.  If we want to keep it as a standard namespace card in Overview that is fine.
