### ISSUE TITLE
Investigate automated e2e testing of multicluster

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#5619]
The e2e testing suites (cypress and API) run in CI against a single cluster deployment. Kiali will need e2e testing for multi-cluster specific features requiring both a way to separate multi-cluster from single cluster tests and a multi-cluster setup in CI to run those tests against. There will probably be resource constraints for multicluster with the current CI env so some investigation is needed to determine the options available.

**Comment by hhovsepy** [comment]
I can work on this one.

**Comment by Xunzhuo** [comment]
Thanks @hhovsepy. I will keep an eye on this too. I had some experiences on e2e multicluster.

**Comment by nrfox** [comment]
@hhovsepy are you still working on this one?

**Comment by nrfox** [comment]
Since there will be at least a few tasks related to e2e testing, I'm going to create a separate umbrella issue for e2e multi-cluster testing and make this one part of it.

**Comment by hhovsepy** [comment]
@nrfox have not worked on this task

**Comment by nrfox** [comment]
> @nrfox have not worked on this task

I've been doing some related work and can work on this investigation task as part of that if you don't mind?
