### ISSUE TITLE
Feature Request: Make kiali graph installable by npm

### ISSUE THREAD

**Issue by clyang82** [kiali/kiali#562]
**Requirement - what kind of business use case are you trying to solve?**

Kiali is the UI for Istio, we are currently integrating the kiali into our portal.

We want to show the information provided by Kiali --> Graph. the user can see the relationship for different service/deployment and HTTP traffic.

Actually we do not want to expose the whole kiali ui, because there are some kiali concepts (e.g.: application/worklad) which are different from our concepts. if expose all kiali ui and our concepts, it may make the end user confusion. But kiali graph is very great feature, we do not want to build by ourselves again.

**Problem - what in Jaeger blocks you from solving the requirement?**

We can't integrate components of Kiali Graph So we are using external links to the Kiali-ui in a new tabs.

**A clear and concise description of what you expected to happen.**
1. make kiali graph as a standard react component can be used by react app
2. the links and graph  type can be customized. see the pic below
![graph](https://user-images.githubusercontent.com/7711311/46956235-64063d80-d0c7-11e8-8760-fd681e306252.PNG)
for example:
Application --> Deployment (link can be customized as well)
Workload --> Pod (link can be customized as well)

**Comment by clyang82** [comment]
@lucasponce & @aljesusg any comments? Thanks.

**Comment by israel-hdez** [comment]
@clyang82 Let me understand your requirement.
When you say that you need it installable by npm, do you mean that you want to install it as a dependency in your project to be able to use the graph? Or do you mean installing it globally and run it as standalone app so that it will be easier for you to make customizations?

**Comment by clyang82** [comment]
Yes. I want to install it as a dependency in my project to be able to use the graph.

**Comment by israel-hdez** [comment]
@clyang82 I'll raise this tomorrow. It is in our plans to do integrations, but UI codebase doesn't have the structure to allow this yet. I'll let you know how soon this can be done.

**Comment by mtho11** [comment]
We had this as a jira request a long time ago: https://issues.jboss.org/browse/KIALI-178
Looks like we need to reopen that jira

**Comment by mtho11** [comment]
This shouldn't be difficult, just need to create a valid npm module that can be pulled into a node project.

**Comment by israel-hdez** [comment]
@clyang82 Although we are interested in integrations, this is not in our priority. So, we won't do this anytime soon.
If you need this feature, my suggestion is that you work on it and place a PR. We will be happy to accept your contribution.

**Comment by clyang82** [comment]
@israel-hdez Thanks for your update. Let me raise this issue in our team to see if we can put some efforts on it.
