### ISSUE TITLE
Update Istio 1.16 to Kiali 1.59

### ISSUE THREAD

**Issue by jshaughn** [kiali/kiali#5627]
We need to update the new Istio release to a newer version of the Kiali add-on.  To do this:

- Ensure the Kiali version compatibility matrix is updated
  - config/version-compatibility-matrix.yaml
  - status/versions_test.go
- If necessary, release an upstream point release of Kiali with the updated version compatibility information.
- Update the web site's version compatibility information
  - content/en/docs/Installation/installation-guide/prerequisites.md
  - two prs: `staging` and backport to `current`
- Generate PR for Istio in their release branch
  - draft PR already created - once 1.59.1 is released, we need to run "gen.sh" and commit the updated kiali yaml to that draft PR and change it to an actual PR: https://github.com/istio/istio/pull/41984

**Comment by jmazzitelli** [comment]
compat matrix PRs:
* master: https://github.com/kiali/kiali/pull/5628
* v1.59 branch: https://github.com/kiali/kiali/pull/5629

**Comment by jmazzitelli** [comment]
kiali.io docs PRs:
* staging: https://github.com/kiali/kiali.io/pull/596
* current: https://github.com/kiali/kiali.io/pull/597

**Comment by jshaughn** [comment]
@jmazzitelli  This is done, right?

**Comment by jmazzitelli** [comment]
complete
