### ISSUE TITLE
Multicluster demos

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#5632]
Create multi-cluster demos that can be used for demoing functionality and automated testing for multi-cluster scenarios. Should support multiple deployment models.

**Comment by Xunzhuo** [comment]
I am assigning myself on it.

**Comment by jshaughn** [comment]
@nrfox , Is the current tutorial for MC travels sufficient here?

**Comment by nrfox** [comment]
Yes the multicluster travels demo covers how to install kiali in a multicluster environment: https://kiali.io/docs/tutorials/multicluster/. It doesn't show every istio deployment model but the multicluster setup for kiali will largely remain the same regardless of which istio deployment model you choose.

A future demo could show how to configure kiali with oidc in a multicluster environment but even that will largely be the same as the single cluster oidc configuration.

Regarding testing automation, kiali already has [hack scripts](https://github.com/kiali/kiali/blob/master/hack/run-integration-tests.sh) to setup a multicluster environment for testing including [some that use oidc](https://github.com/kiali/kiali/blob/master/hack/istio/multicluster/install-multi-primary.sh). I'd say that is good enough for now unless it is asked for.
