### ISSUE TITLE
Kiali heatmap tooltips are too compute-heavy

### ISSUE THREAD

**Issue by jshaughn** [kiali/kiali#5634]
Related to #5584 

The fix for #5584 solved an issue where the frontend could launched large numbers of concurrent requests when a user was mousing over the trace scatter chart.  The result was a frozen UI and a possible OOM in Prometheus.  The change limited the UI to one backend request at a time.

The fix for #5584 did not completely solve the user's issue.  The backend request is responsible for gathering the data required to show a trace's heatmap.  The heatmap is then displayed in the tooltip to help a user understand if a particular trace may represent a problematic request.  It looks now like even one of these backend requests can put undo load on prometheus and potentially timeout for the user.

**Comment by jshaughn** [comment]
After some investigation, it is pretty intensive to generate a heatmap.  For each span (up to 10 spans in one backend request), we generate 3 query-requests (for 3 different time ranges).  And for each query-request we generate a Prom query for 3 percentiles (p50,p95,p99) and an avg.    So that's 12 prom queries per span!  If your trace has say 4 spans thats 48 queries, all launched simultaneously as gofuncs!  So that's between 12 and 120 prom queries per heatmap!

Interestingly, we have not really seen an issue reported before this, or noticed a problem locally.  So despite the intensity, it may take an environment where Prom is already under pressure or resource-constrained to really see the problem.  Note that Prom does already have some built-in throttling.


So it's not totally clear what we want to do here to solve the problem.  We do want to keep the heat maps in the tooltips because otherwise users will not have an easy way to determine if a particular trace may be useful to click on.  But we do need to make this more lightweight.

I think maybe we should do two things:
1. Instead of the full heatmap we should generate a lighter heatmap (instead of 3x4 perhaps 2x3).  That should maybe be enough for a decent indicator.
2. Reduce the gofunc concurrency, possible even to fully sequential, but maybe per-span (so at most 2x3=6 queries)

**Comment by jshaughn** [comment]
https://github.com/Myeongseok-Kim, Please retry your scenario with vKiali v1.60 when it is released (Monday, Nov 28).  The changes for this issue will hopefully improve the situation, please let us know.

**Comment by Myeongseok-Kim** [comment]
Deployed v1.60 and tested.

OOM no longer occurs, but the first lookup takes time.
In a stage environment with relatively low traffic, it responds very quickly.

Does the query on the heatmap query all workloads, not just the ones I selected?


---Stage env
![image](https://user-images.githubusercontent.com/54100684/204450087-d208458d-091c-40ce-b19e-763d56c35276.png)


---Production env
![image](https://user-images.githubusercontent.com/54100684/204449695-cae5359d-14f5-47ab-9a68-59ae7b98fd52.png)

**Comment by jshaughn** [comment]
The new heatmaps require significantly less compute but are still fairly intensive and perform multiple prom queries for different percentiles against different time periods.  They are limited to metrics backing the relevant trace spans.  Percentiles are some of the most intensive prom queries (histogram queries), and can definitely slow down given large amounts of prom time-series.  I don't see a way to further optimize the situation without completely compromising the usefuleness of what Kiali is trying to provide here.  I think at this point it's more about environmental issues around your prom or networking, perhaps you could investigate adding resources or possibly optimizing in some way.  Take a look at our page on prometeus tuning for some possible help: https://kiali.io/docs/configuration/p8s-jaeger-grafana/prometheus/#prometheus-tuning
