### ISSUE TITLE
Link to trace does not always open trace details

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#5635]
Links to traces/span details are included in the logs viewer and on the metric charts. When you click on this link, you are redirected to the traces tab and the trace along with the trace details should be highlighted. This does not always work and sometimes you are redirected to the traces tab but with nothing open. Happens anywhere there's a link to an individual trace. Could be a disconnect between the traces/spans shown in the link vs. what is fetched from Kiali when you navigate to the traces tab.

**Comment by jshaughn** [comment]
@josunect , With a lot of work lately in Tracing, can you please see if this can be re-produced?
