### ISSUE TITLE
kiali-operator deletes ingress even if that one was not created by it

### ISSUE THREAD

**Issue by mkyc** [kiali/kiali#5637]
Situation: 
 - I have everything kiali-related in `kiali` namespace
 - I create ingress named `kiali` with terraform
 - I have `kiali-operator` version `1.59.1 in that namespace as well
 - when I create `Kiali` CR with `spec.deployment.ingress.enabled = false` or without `ingress` section at all, `kiali-operator` will remove ingress even if that is not resource it created. 

Is there workaround not to remove ingress?

**Comment by jmazzitelli** [comment]
Let me confirm what you see. You created your own custom Ingress, correct? Can I assume you named it `kiali` (or, more specifically, you named it the same as the kiali instance name - the default of which is `kiali`?). If so, that is why. The operator will delete the Ingress found in the Kiali deployment namespace named the same as the kiali instance name if ingress is disabled. See the code here: https://github.com/kiali/kiali-operator/blob/master/roles/default/kiali-deploy/tasks/kubernetes/k8s-main.yml#L52-L61

The workaround is to name the Ingress with your own name - do not use the name the operator would use. Name your Ingress something like `my-custom-ingress` or `kiali-custom` or something like that, and the operator should not delete it.

**Comment by mkyc** [comment]
That is correct workaround. Thanks! 

I'd like to just point, that removal should use additional labels on resources created by operator. Relying just on names will cause problems such as mine and labels are perfect for this use case.
