### ISSUE TITLE
Investigate the possibility to get istio configs with no istiod access

### ISSUE THREAD

**Issue by josunect** [kiali/kiali#5645]
REF #5626 

This is an issue to investigate the possibility of getting the Istio configurations when there is no access to istiod.

As a first stage for #5626, we can just show a message indicating that Istiod is not available so the configurations are not available, but, to get Kiali working more independently of Istio, I think it would be interesting the idea of investigate the possibility and the cost of getting the Istio configurations with no istiod access. 

With no istiod access is possible to create different configurations, but not listed them.

**Comment by hhovsepy** [comment]
It possible to modify the https://github.com/kiali/kiali/blob/master/business/istio_config.go#L154 so when Istio is not accessible, to continue reading from either from Kiali cache, or directly query from K8s.
IstioConfigDetails is designed to work in this way.

**Comment by hhovsepy** [comment]
Change commits from PR were cherry-picked.
