### ISSUE TITLE
when istio service entry is static type and k8s svc also exist, Kiali only show service entry node

### ISSUE THREAD

**Issue by yankunsam** [kiali/kiali#5656]
<img width="740" alt="image" src="https://user-images.githubusercontent.com/16130147/204701025-b83a75e6-ce5e-469d-89dc-c84160206c70.png">

```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  creationTimestamp: "2022-07-14T16:14:48Z"
  generation: 591
  labels:
    manager: Aeraki
    registry: consul
    service-name: lb-portfolio-clearing
  name: lb-portfolio-clearing.prod.service.consul
  namespace: skopos
  resourceVersion: "397087563"
  uid: 7f68ecc2-f642-43a6-bc98-ab708b3d83e5
spec:
  endpoints:
  - address: 172.22.57.254
    labels:
      cluster: staging-eks-1
      env: prod
      port: "8080"
    locality: staging-eks-1
    ports:
      grpc-8080: 8080
  - address: 172.22.57.193
    labels:
      cluster: staging-eks-1
      env: prod
      port: "8080"
    locality: staging-eks-1
    ports:
      grpc-8080: 8080
  hosts:
  - lb-portfolio-clearing.prod.service.consul
  location: MESH_INTERNAL
  ports:
  - name: grpc-8080
    number: 8080
    protocol: GRPC
  resolution: STATIC
```

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"lb-portfolio-clearing","namespace":"core"},"spec":{"ports":[{"name":"grpc-server","port":8080,"protocol":"TCP","targetPort":8080}],"selector":{"app":"portfolio-clearing"}}}
  creationTimestamp: "2022-09-13T15:30:46Z"
  name: lb-portfolio-clearing
  namespace: core
  resourceVersion: "305964591"
  uid: 13ed9bc7-85c5-4e82-976d-f32c4b92f81d
spec:
  clusterIP: 172.20.7.66
  clusterIPs:
  - 172.20.7.66
  ports:
  - name: grpc-server
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: portfolio-clearing
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

BTW, in metric, there is no information related with lb-portfolio-clearing.prod.service.consul

**Comment by jmazzitelli** [comment]
IIRC, technically, Kiali doesn't graph k8s Services in the main graph. It only graphs what is in Istio telemetry utilizing the service names specified in telemetry.

@jshaughn can correct me if I'm wrong. But if I'm right, this isn't a bug. It's just that the graph doesn't show and never shows k8s services per se.

So, we need @jshaughn to chime in on this as he is most familiar with the graph generator.

**Comment by yankunsam** [comment]
Okay, Kiali will convert k8s's service to Kiali's service model, And it will also convert Istio's service from Istiod. So in this graph, service's name is the same as serviceEntry, not k8s service's name.

**Comment by jshaughn** [comment]
The Kiali graph is actually replacing the service node in the graph with the service-entry node, based on the "host matching".  So, yes, I think your statement above is correct.

**Comment by yankunsam** [comment]
@jshaughn  Thanks for you replay. As the above code, my ServcieEntry's host is "lb-portfolio-clearing.prod.service.consul". After converting, in Kiali's service node, it's service name is lb-portfolio-clearing? Even I have a k8s service, it's name is lb-portfolio-clearing in core namespace.

**Comment by jshaughn** [comment]
Sorry, @yankunsam , I think we dropped this conversation.  Your service entry host  `lb-portfolio-clearing.prod.service.consul` is matching the service ` lb-portfolio-clearing` because Kiali is matching on the first segment of the service entry host.  We do this because in general it's the right thing to do.  I think you are suggesting that we should not match, but I'm not sure we have a way around it.

**Comment by yankunsam** [comment]
@jshaughn thanks for you replay. Actually we use serviceEntry synced from Consul. And now we plan to switch consul to k8s service. So Kiali prefer to serviceEntry is the answer. Thanks.
