### ISSUE TITLE
Test the new native stats runtime by setting TELEMETRY_USE_NATIVE_STATS to "true" in istiod

### ISSUE THREAD

**Issue by jshaughn** [kiali/kiali#5660]
From @kyessenov on upstream Istio:

_Kiali folks, once 1.16 is out, could you test the new native stats runtime by setting TELEMETRY_USE_NATIVE_STATS to "true" in istiod? I'm looking for feature gaps (I know a couple, attributegen and BlackHole, but want to find out others)._ 

I think this task is mainly to enable the option, which changes from using a compiled WASM extension to an Envoy extension for reporting stats.  And then sanity checking what Kiali produces, especially regarding the graph and charts.  And to run all of our CI.

**Comment by jshaughn** [comment]
I was just linking Kuat, that's his github handle.  He made the request.  The setting is an environment var, see https://drive.google.com/drive/folders/1mEER1CtHxpV6OND_IMYTnMA2YRs_sitm?usp=share_link.  It would be set like the way we set other env vars, I guess in the settings we set in the container command line?

**Comment by jmazzitelli** [comment]
@kyessenov feel free to provide any info you want the Kiali team to know here in this issue.

**Comment by jshaughn** [comment]
From the 1.16 release notes:

`Updated Telemetry API to use a new native extension for Prometheus stats instead of the Wasm-based extension. This improves CPU overhead and memory usage of the feature. Custom dimensions no longer require regex and bootstrap annotations. If customizations use CEL expressions with Wasm attributes, they are likely to be affected. This change can be disabled by setting the control plane feature flag TELEMETRY_USE_NATIVE_STATS to false.
`

**Comment by jmazzitelli** [comment]
ok, so is this an env var that is used by the proxy sidecar (so we'd need to define it in the sidecar container of the app pod)? How do you set a custom env var for a proxy that gets auto-injected into the pod?

**Comment by kyessenov** [comment]
The environment variable is on istiod. To verify it took effect, we can take a config_dump on proxy and check that "istio.stats" filter is not using Wasm.

**Comment by jmazzitelli** [comment]
> The environment variable is on istiod.

Ah, ok. That's easy then.

**Comment by jmazzitelli** [comment]
This doesn't look right.

First, I know I have 1.16.0 installed:

```
$ kubectl get pods -l app=istiod -n istio-system -o jsonpath='{.items[0].spec.containers[0].image}'
gcr.io/istio-release/pilot:1.16.0
```

And I see I did correctly set the env var  on istiod -- it is `true`:

```
$ kubectl get pods -l app=istiod -n istio-system -o jsonpath='{.items[0].spec.containers[0].env[?(@.name=="TELEMETRY_USE_NATIVE_STATS")].value}'
true
```

After I set that env var, I installed the bookinfo demo and waited for the pods to start. But then when I look at the Envoy config of bookinfo's `details-v1` workload within Kiali's Envoy tab (http://localhost:20001/kiali/console/namespaces/bookinfo/workloads/details-v1?envoyTab=config&tab=envoy) I see this:
```json
                    "filters": [
                      {
                        "name": "istio.stats",
                        "typed_config": {
                          "@type": "type.googleapis.com/udpa.type.v1.TypedStruct",
                          "type_url": "type.googleapis.com/envoy.extensions.filters.network.wasm.v3.Wasm",
                          "value": {
                            "config": {
                              "configuration": {
                                "@type": "type.googleapis.com/google.protobuf.StringValue",
                                "value": "{\n  \"debug\": \"false\",\n  \"stat_prefix\": \"istio\"\n}\n"
                              },
                              "root_id": "stats_outbound",
                              "vm_config": {
                                "code": {
                                  "local": {
                                    "inline_string": "envoy.wasm.stats"
                                  }
                                },
                                "runtime": "envoy.wasm.runtime.null",
                                "vm_id": "tcp_stats_outbound"
                              }
                            }
                          }
                        }
```

>  check that "istio.stats" filter is not using Wasm.

So this check looks like the `istio.status` filter is still using Wasm, correct? And that isn't what we want.

@kyessenov am I doing this wrong? What should I be doing to get this to work?

**Comment by kyessenov** [comment]
Yes, it's still using Wasm for some reason.

I have the following working configuration on `istiod` deployment:
 
```
        - name: CLUSTER_ID
          value: Kubernetes
        - name: TELEMETRY_USE_NATIVE_STATS
          value: "true"
        image: docker.io/istio/pilot:1.16.0-rc.0
```

Can you show snippet from your pod manifest?  Not sure what went wrong for you.

**Comment by jmazzitelli** [comment]
@kyessenov here's my yaml for the istiod pod -- results of `kubectl get pods -l app=istiod -n istio-system -o yaml`

[istiod.yaml.txt](https://github.com/kiali/kiali/files/10157910/istiod.yaml.txt)

**Comment by kyessenov** [comment]
Ah, sorry I got confused. You are not using Telemetry API which is why this is not taking effect. We'd need to use EnvoyFilter way for non-API configuration.  This has been done 1.17 (https://github.com/istio/istio/blob/master/manifests/charts/istio-control/istio-discovery/templates/telemetryv2_1.17.yaml). Can you send me stats-filter-1.16 and tcp-stats-filter-1.16 EnvoyFilter configs in istio-system, I can manually edit them and send back.

**Comment by jmazzitelli** [comment]
> Can you send me stats-filter-1.16 and tcp-stats-filter-1.16 EnvoyFilter configs

[stats-filter-1.16.yaml.txt](https://github.com/kiali/kiali/files/10157962/stats-filter-1.16.yaml.txt)
[tcp-stats-filter-1.16.yaml.txt](https://github.com/kiali/kiali/files/10157964/tcp-stats-filter-1.16.yaml.txt)

**Comment by kyessenov** [comment]
Modified in-place. Updating with these should turn it on.
[tcp-stats-filter-1.16.yaml.txt](https://github.com/kiali/kiali/files/10158071/tcp-stats-filter-1.16.yaml.txt)
[stats-filter-1.16.yaml.txt](https://github.com/kiali/kiali/files/10158072/stats-filter-1.16.yaml.txt)

**Comment by kyessenov** [comment]
The environment variable is for Telemetry API. If you don't have any "telemetry" resources, it doesn't matter.

**Comment by jmazzitelli** [comment]
Looks better:
```json
                    "filters": [
                      {
                        "name": "istio.stats",
                        "typed_config": {
                          "@type": "type.googleapis.com/udpa.type.v1.TypedStruct",
                          "type_url": "type.googleapis.com/stats.PluginConfig",
                          "value": {}
                        }
                      },
                      {
                        "name": "envoy.filters.network.tcp_proxy",
                        "typed_config": {
                          "@type": "type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy",
                          "access_log": [
                            {
                              "name": "envoy.access_loggers.file",
                              "typed_config": {
                                "@type": "type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog",
                                "log_format": {
                                  "text_format_source": {
                                    "inline_string": "[%START_TIME%] \"%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%\" %RESPONSE_CODE% %RESPONSE_FLAGS% %RESPONSE_CODE_DETAILS% %CONNECTION_TERMINATION_DETAILS% \"%UPSTREAM_TRANSPORT_FAILURE_REASON%\" %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% \"%REQ(X-FORWARDED-FOR)%\" \"%REQ(USER-AGENT)%\" \"%REQ(X-REQUEST-ID)%\" \"%REQ(:AUTHORITY)%\" \"%UPSTREAM_HOST%\" %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME% %ROUTE_NAME%\n"
                                  }
                                },
                                "path": "/dev/stdout"
                              }
                            }
                          ],
                          "cluster": "outbound|15012||istiod.istio-system.svc.cluster.local",
                          "stat_prefix": "outbound|15012||istiod.istio-system.svc.cluster.local"
                        }
                      }
                    ]
```

**Comment by jmazzitelli** [comment]
Here are the commands we can use to quickly bring up a minikube cluster that contains istio 1.16 with the native stats enabled so we can test with Kiali:

To install minikube and Istio 1.16 with native stats enabled:

1. hack/istio/download-istio.sh -iv 1.16.0
2. hack/k8s-minikube.sh start
3. hack/k8s-minikube.sh istio
4. kubectl apply -n istio-system -f [https://github.com/kiali/kiali/files/10167047/native-stats-filter-1.16.yaml.txt](https://github.com/kiali/kiali/files/10167047/native-stats-filter-1.16.yaml.txt)
5. kubectl apply -n istio-system -f [https://github.com/kiali/kiali/files/10167048/native-tcp-stats-filter-1.16.yaml.txt](https://github.com/kiali/kiali/files/10167048/native-tcp-stats-filter-1.16.yaml.txt)
6. kubectl delete pod -n istio-system -l app=istiod
7. hack/k8s-minikube.sh bookinfo

To install and run Kiali so we can test (make sure the operator and helm chart git repos are cloned locally):

1. make -e CLUSTER_TYPE=minikube build build-ui cluster-push operator-create kiali-create
2. hack/kiali-port-forward.sh
3. xdg-open http://localhost:20001/kiali/console

**Comment by jmazzitelli** [comment]
If I query prometheus with `istio_requests_total{source_cluster='Kubernetes'}` then that returns everything. If I do `!=` "Kubernetes" then nothing returns. So that looks good
