### ISSUE TITLE
Kiali may prevent istiod from becoming ready on initial startup of istiod pod

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#5669]
Kiali port forwards to the istiod pod in order to get info from the debug endpoints. When Kiali is already running and an istiod pod first comes online, Kiali may flood the istiod pod with requests before the istiod pod can become ready.

**Comment by luksa** [comment]
This is the Kiali version that display this issue: Kiali: Version: 1.48.3, Commit: 269fa3d1352c7e39432fbfd9322df7f769d7396f

**Comment by jshaughn** [comment]
I would expect that this problem extends to all recent versions.  Any ideas of a way to mitigate the problem?  A way to throttle requests, or wait for readiness?

**Comment by nrfox** [comment]
> Any ideas of a way to mitigate the problem? A way to throttle requests, or wait for readiness?

There needs to be some form of backoff for port forwarding requests. Since the `KialiCache` is the only resource that is shared across requests, I think it needs to happen there in the registry cache and in the proxy cache since those are the two services that do the port forwarding.

**Comment by luksa** [comment]
FYI: the mesh where this issue happened had ~30 member namespaces, with 101 pods. I see that Kiali is performing a separate port-forward for every pod. That explains the extraordinarily high number of port-forward requests.

I've also noticed a problem in the `GetPodProxyStatus()` function (https://github.com/kiali/kiali/blob/34202811d72b0a6a0579cd7e7476a3355626cced/business/proxy_status.go#L17). If the cache is stale, it tries to get the status via the port-forward, but if that fails, it doesn't update the cache in any way, which means that the next call to the function will again bypass the cache. So, if the cache is stale, each invocation of `GetPodProxyStatus` results in a request to istiod.

I see multiple such requests for the same pod in the same second. If there are a large number of pods in the system, this leads to a very large of requests being performed.

**Comment by nrfox** [comment]
> If the cache is stale, it tries to get the status via the port-forward, but if that fails, it doesn't update the cache in any way, which means that the next call to the function will again bypass the cache. So, if the cache is stale, each invocation of `GetPodProxyStatus` results in a request to istiod.

Thanks for digging into this more. You're right, the proxy status service gets called per pod: https://github.com/kiali/kiali/blob/master/business/workloads.go#L1136 which normally just pulls that info from the cache but if there's a cache miss then the proxy service does a port forward to the istiod pod to get that info. There's a bit of an interface mismatch because the proxy info that gets returned from istiod is for the whole mesh but the proxy status service accepts a ns/pod because it assumes that info will come from the cache. Really this needs to change. I think what was intended was to only connect to istiod once, cache the info, and return the info from cache for some period of time. And given that, I don't see why we need to wait for the proxy service to be called to scrape the istiod debug endpoints. Having a background process that periodically scrapes the istiod debug endpoints and populates the proxy/registry caches will give us more control over how often we connect to istiod. Even with a few retries, we shouldn't need to hit those endpoints more than a handful of times for as long as the cache is valid (it's tied to the namespace token duration which is configurable but defaults to 10 seconds).

**Comment by nrfox** [comment]
After some investigation, it appears that the number of portforwarding requests (attempts by Kiali to connect to istiod) scales with the number of namespaces. Previously the portforwarding requests also scaled with the number pods in the selected namespaces but after #5674 this is no longer the case. The remaining requests to istiod are for the `/registryz`, `/configz`, and `/endpointz` endpoints and still scale with the number of selected namespaces when istiod is unreachable. Changing this behavior will need to account for refreshing the cache when an object (workload/service/istio config) gets updated through Kiali.

**Comment by jshaughn** [comment]
Closing as resolved by https://github.com/kiali/kiali/pull/5674.  Futher work can be done via new issues.
