### ISSUE TITLE
Kiali CR definition to allow the use of appProtocol in the service configuration

### ISSUE THREAD

**Issue by teerakarna** [kiali/kiali#5670]
I would like to deploy Kiali in an environment where appProtocol is being enforced for services by Gatekeeper.

It would also make sense for Kiali to accommodate this configuration to be in-line with Istio:
https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/

**Comment by jmazzitelli** [comment]
PRs:
* operator: https://github.com/kiali/kiali-operator/pull/597
* helm chart: https://github.com/kiali/helm-charts/pull/185

**Comment by jmazzitelli** [comment]
appProtocol is available and stable on K8s versions 1.20+.

The operator will ensure the appProtocol field is specified only when creating the service on k8s 1.20+.

The helm chart will always create the appProtocol field.

**Comment by jmazzitelli** [comment]
Test procedures for the operator: https://github.com/kiali/kiali-operator/pull/597#issuecomment-1355451498
Test procedures for the helm chart: https://github.com/kiali/helm-charts/pull/185#issuecomment-1353808681
