### ISSUE TITLE
Istio Validations when "istio_api_enabled: false"

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#5676]
Kiali Istio validations require Services from Istio Registry, which is unavailable when Istio API is disabled.

This RFE requires to load Services from K8s API when "istio_api_enabled: false" and convert them into "kubernetes.RegistryService" to be used in Istio Config Validations by Kiali.

**Comment by jshaughn** [comment]
Before we support doing validations in different ways we should consider whether it may be OK for validations to be disabled if `istio_api_enabled=false`.

**Comment by jmazzitelli** [comment]
+1 to what @jshaughn just said... That might not be a bad idea - just disable validations if we can't get to istiod . I think this is fair - we need the istio registry in order to effectively perform validations so this is just one of those features customers lose if they deploy Kiali in a mesh that does not provide istiod access.

**Comment by hhovsepy** [comment]
@jshaughn we can notify to the user that without istiod the validations are not available, so editing configs can cause hidden problems.
We should also consider, that even if Kiali validations are available when `istio_api_enabled=false` (retrieving services from k8s), the Istio webhook validations are not available anyway.

**Comment by jshaughn** [comment]
@josunect , @hhovsepy , I think with Josune's PR we are warning aboy no validation in this use case, so I think we can close this issue.  Do you agree?

**Comment by hhovsepy** [comment]
+1 to close this issue

**Comment by jshaughn** [comment]
@josunect if you disagree let us know, but assuming you agree, so closing.

**Comment by josunect** [comment]
> @josunect if you disagree let us know, but assuming you agree, so closing.

I'm agree with closing the issue too
