### ISSUE TITLE
Kiali could not fetch Istio objects lists

### ISSUE THREAD

**Issue by MollyH1391** [kiali/kiali#5682]
Istio, Kiali version in use: 
Istio version: 1.14.3
Kiali version: kiali-server-1.54.0
image: quay.io/kiali/kiali:v1.54.0

We are using Istio as the service mesh for anthos cluster and use Kiali for the traffic visibility. The problem we are facing is that the inbound/outbound flow is visible but an error message keep displayinf[1]. 
We are wondering if anyone else has this problem? And how to slove it? 

[1]Could not fetch Istio objects list: the server could not find the requested resource (get workloadgroups.networking.istio.io)

The logs of kiali pod:

❯ k logs kiali-95856bf4b-stkx4
2022/12/28 10:20:44 maxprocs: Leaving GOMAXPROCS=8: CPU quota undefined
2022-12-28T10:20:44Z INF Kiali: Version: v1.53.0, Commit: 4953758c752a806a4803db8e48a7e1b485742c6f

2022-12-28T10:20:44Z INF Using authentication strategy [anonymous]
2022-12-28T10:20:44Z WRN Kiali auth strategy is configured for anonymous access - users will not be authenticated.
2022-12-28T10:20:44Z INF Some validation errors will be ignored [KIA1201]. If these errors do occur, they will still be logged. If you think the validation errors you see are incorrect, please report them to the Kiali team if you have not done so already and provide the details of your scenario. This will keep Kiali validations strong for the whole community.
2022-12-28T10:20:44Z INF Mesh Name: [Istio], Mesh Version: [1.14.3]
2022-12-28T10:20:44Z INF Server endpoint will start at [:20001/kiali]
2022-12-28T10:20:44Z INF Server endpoint will serve static content from [/opt/kiali/console]
2022-12-28T10:20:44Z INF Starting Metrics Server on [:9090]
2022-12-28T10:20:44Z INF Initializing Kiali Cache
2022-12-28T10:20:44Z INF Kiali Cache is active for namespaces [.*]
2022-12-28T10:20:44Z INF Adding a RegistryRefreshHandler for [anthos-identity-service]
2022-12-28T10:20:44Z INF Waiting for Kiali cache for [namespace: anthos-identity-service] to sync
W1228 10:20:44.664348       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1beta1.WorkloadGroup: the server could not find the requested resource (get workloadgroups.networking.istio.io)
E1228 10:20:44.664393       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1beta1.WorkloadGroup: failed to list *v1beta1.WorkloadGroup: the server could not find the requested resource (get workloadgroups.networking.istio.io)
W1228 10:20:46.218812       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1beta1.WorkloadGroup: the server could not find the requested resource (get workloadgroups.networking.istio.io)
E1228 10:20:46.218837       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1beta1.WorkloadGroup: failed to list *v1beta1.WorkloadGroup: the server could not find the requested resource (get workloadgroups.networking.istio.io)
W1228 10:20:48.170930       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1beta1.WorkloadGroup: the server could not find the requested resource (get workloadgroups.networking.istio.io)
E1228 10:20:48.170957       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1beta1.WorkloadGroup: failed to list *v1beta1.WorkloadGroup: the server could not find the requested resource (get workloadgroups.networking.istio.io)
W1228 10:20:52.023943       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1beta1.WorkloadGroup: the server could not find the requested resource (get workloadgroups.networking.istio.io)
E1228 10:20:52.023984       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1beta1.WorkloadGroup: failed to list *v1beta1.WorkloadGroup: the server could not find the requested resource (get workloadgroups.networking.istio.io)

**Comment by nrfox** [comment]
> We are using Istio as the service mesh for anthos cluster and use Kiali for the traffic visibility. 

To my knowledge, Kiali does not work with Anthos, at least not the managed Istio service, since Kiali needs access to the istiod debug endpoints and even if Kiali reach them, those are not part of the public API. See [this](https://github.com/kiali/kiali/issues/5404) issue for more details. There's some ongoing work to add an option to disable istiod access: https://github.com/kiali/kiali/issues/5626. Without the istiod requirement, Kiali may work better with Anthos.

All that being said, your actual error looks like the v1beta1 `WorkloadGroup` kind doesn't exist in your cluster.

**Comment by MollyH1391** [comment]
@nrfox Thank you for your reply. We have temporarily solve the problem. The crd workloadgroups.networking.istio.io yaml file is shown below. We add the v1beta1 `WorkloadGroup` manually and Kiali is able to display Istio config now. However, it is not sure whether this method clould work stably. Beside, We would try to migrate to a newer version of Istio and Kiali to see if this problem still exists.

> kubectl get crd workloadgroups.networking.istio.io -o yaml

kind: CustomResourceDefinition
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apiextensions.k8s.io/v1","kind":"CustomResourceDefinition","metadata":{"annotations":{},"creationTimestamp":"2022-08-30T02:44:43Z","generation":2,"labels":{"app":"istio-pilot","chart":"istio","heritage":"Tiller","release":"istio"},"name":"workloadgroups.networking.istio.io","resourceVersion":"95386326","uid":""},"spec":{"conversion":{"strategy":"None"},"group":"networking.istio.io","names":{"categories":["istio-io","networking-istio-io"],"kind":"WorkloadGroup","listKind":"WorkloadGroupList","plural":"workloadgroups","shortNames":["wg"],"singular":"workloadgroup"},"scope":"Namespaced","versions":[{"additionalPrinterColumns":[{"description":"CreationTimestamp is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC. Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata","jsonPath":".metadata.creationTimestamp","name":"Age","type":"date"}],"name":"v1alpha3","schema":{"openAPIV3Schema":{"properties":{"spec":{"description":"Describes a collection of workload instances. See more details at: https://istio.io/docs/reference/config/networking/workload-group.html","properties":{"metadata":{"description":"Metadata that will be used for all corresponding `WorkloadEntries`.","properties":{"annotations":{"additionalProperties":{"type":"string"},"type":"object"},"labels":{"additionalProperties":{"type":"string"},"type":"object"}},"type":"object"},"probe":{"description":"`ReadinessProbe` describes the configuration the user must provide for healthchecking on their workload.","oneOf":[{"not":{"anyOf":[{"required":["httpGet"]},{"required":["tcpSocket"]},{"required":["exec"]}]}},{"required":["httpGet"]},{"required":["tcpSocket"]},{"required":["exec"]}],"properties":{"exec":{"description":"Health is determined by how the command that is executed exited.","properties":{"command":{"description":"Command to run.","items":{"type":"string"},"type":"array"}},"type":"object"},"failureThreshold":{"description":"Minimum consecutive failures for the probe to be considered failed after having succeeded.","format":"int32","type":"integer"},"httpGet":{"properties":{"host":{"description":"Host name to connect to, defaults to the pod IP.","type":"string"},"httpHeaders":{"description":"Headers the proxy will pass on to make the request.","items":{"properties":{"name":{"type":"string"},"value":{"type":"string"}},"type":"object"},"type":"array"},"path":{"description":"Path to access on the HTTP server.","type":"string"},"port":{"description":"Port on which the endpoint lives.","type":"integer"},"scheme":{"type":"string"}},"type":"object"},"initialDelaySeconds":{"description":"Number of seconds after the container has started before readiness probes are initiated.","format":"int32","type":"integer"},"periodSeconds":{"description":"How often (in seconds) to perform the probe.","format":"int32","type":"integer"},"successThreshold":{"description":"Minimum consecutive successes for the probe to be considered successful after having failed.","format":"int32","type":"integer"},"tcpSocket":{"description":"Health is determined by if the proxy is able to connect.","properties":{"host":{"type":"string"},"port":{"type":"integer"}},"type":"object"},"timeoutSeconds":{"description":"Number of seconds after which the probe times out.","format":"int32","type":"integer"}},"type":"object"},"template":{"description":"Template to be used for the generation of `WorkloadEntry` resources that belong to this `WorkloadGroup`.","properties":{"address":{"type":"string"},"labels":{"additionalProperties":{"type":"string"},"description":"One or more labels associated with the endpoint.","type":"object"},"locality":{"description":"The locality associated with the endpoint.","type":"string"},"network":{"type":"string"},"ports":{"additionalProperties":{"type":"integer"},"description":"Set of ports associated with the endpoint.","type":"object"},"serviceAccount":{"type":"string"},"weight":{"description":"The load balancing weight associated with the endpoint.","type":"integer"}},"type":"object"}},"type":"object"},"status":{"type":"object","x-kubernetes-preserve-unknown-fields":true}},"type":"object"}},"served":true,"storage":true,"subresources":{"status":{}}},{"additionalPrinterColumns":[{"description":"CreationTimestamp is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC. Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata","jsonPath":".metadata.creationTimestamp","name":"Age","type":"date"}],"name":"v1beta1","schema":{"openAPIV3Schema":{"properties":{"spec":{"properties":{"metadata":{"description":"Metadata that will be used for all corresponding `WorkloadEntries`.","properties":{"annotations":{"additionalProperties":{"type":"string"},"type":"object"},"labels":{"additionalProperties":{"type":"string"},"type":"object"}},"type":"object"},"probe":{"description":"`ReadinessProbe` describes the configuration the user must provide for healthchecking on their workload.","oneOf":[{"not":{"anyOf":[{"required":["httpGet"]},{"required":["tcpSocket"]},{"required":["exec"]}]}},{"required":["httpGet"]},{"required":["tcpSocket"]},{"required":["exec"]}],"properties":{"exec":{"description":"Health is determined by how the command that is executed exited.","properties":{"command":{"description":"Command to run.","items":{"type":"string"},"type":"array"}},"type":"object"},"failureThreshold":{"description":"Minimum consecutive failures for the probe to be considered failed after having succeeded.","format":"int32","type":"integer"},"httpGet":{"properties":{"host":{"description":"Host name to connect to, defaults to the pod IP.","type":"string"},"httpHeaders":{"description":"Headers the proxy will pass on to make the request.","items":{"properties":{"name":{"type":"string"},"value":{"type":"string"}},"type":"object"},"type":"array"},"path":{"description":"Path to access on the HTTP server.","type":"string"},"port":{"description":"Port on which the endpoint lives.","type":"integer"},"scheme":{"type":"string"}},"type":"object"},"initialDelaySeconds":{"description":"Number of seconds after the container has started before readiness probes are initiated.","format":"int32","type":"integer"},"periodSeconds":{"description":"How often (in seconds) to perform the probe.","format":"int32","type":"integer"},"successThreshold":{"description":"Minimum consecutive successes for the probe to be considered successful after having failed.","format":"int32","type":"integer"},"tcpSocket":{"description":"Health is determined by if the proxy is able to connect.","properties":{"host":{"type":"string"},"port":{"type":"integer"}},"type":"object"},"timeoutSeconds":{"description":"Number of seconds after which the probe times out.","format":"int32","type":"integer"}},"type":"object"},"template":{"description":"Template to be used for the generation of `WorkloadEntry` resources that belong to this `WorkloadGroup`.","properties":{"address":{"type":"string"},"labels":{"additionalProperties":{"type":"string"},"description":"One or more labels associated with the endpoint.","type":"object"},"locality":{"description":"The locality associated with the endpoint.","type":"string"},"network":{"type":"string"},"ports":{"additionalProperties":{"type":"integer"},"description":"Set of ports associated with the endpoint.","type":"object"},"serviceAccount":{"type":"string"},"weight":{"description":"The load balancing weight associated with the endpoint.","type":"integer"}},"type":"object"}},"type":"object"},"status":{"type":"object","x-kubernetes-preserve-unknown-fields":true}},"type":"object"}},"served":true,"storage":false,"subresources":{"status":{}}}]},"status":{"acceptedNames":{"categories":["istio-io","networking-istio-io"],"kind":"WorkloadGroup","listKind":"WorkloadGroupList","plural":"workloadgroups","shortNames":["wg"],"singular":"workloadgroup"},"conditions":[{"lastTransitionTime":"2022-08-30T02:44:43Z","message":"no conflicts found","reason":"NoConflicts","status":"True","type":"NamesAccepted"},{"lastTransitionTime":"2022-08-30T02:44:43Z","message":"the initial names have been accepted","reason":"InitialNamesAccepted","status":"True","type":"Established"}],"storedVersions":["v1alpha3"]}}
  creationTimestamp: "2022-08-30T02:44:43Z"
  generation: 3
  labels:
    app: istio-pilot
    chart: istio
    heritage: Tiller
    release: istio
  name: workloadgroups.networking.istio.io
  resourceVersion: "125606131"
  uid: 
spec:
  conversion:
    strategy: None
  group: networking.istio.io
  names:
    categories:
    - istio-io
    - networking-istio-io
    kind: WorkloadGroup
    listKind: WorkloadGroupList
    plural: workloadgroups
    shortNames:
    - wg
    singular: workloadgroup
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: 'CreationTimestamp is a timestamp representing the server time
        when this object was created. It is not guaranteed to be set in happens-before
        order across separate operations. Clients may not set this value. It is represented
        in RFC3339 form and is in UTC. Populated by the system. Read-only. Null for
        lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata'
      jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha3
    schema:
      openAPIV3Schema:
        properties:
          spec:
            description: 'Describes a collection of workload instances. See more details
              at: https://istio.io/docs/reference/config/networking/workload-group.html'
            properties:
              metadata:
                description: Metadata that will be used for all corresponding `WorkloadEntries`.
                properties:
                  annotations:
                    additionalProperties:
                      type: string
                    type: object
                  labels:
                    additionalProperties:
                      type: string
                    type: object
                type: object
              probe:
                description: '`ReadinessProbe` describes the configuration the user
                  must provide for healthchecking on their workload.'
                oneOf:
                - not:
                    anyOf:
                    - required:
                      - httpGet
                    - required:
                      - tcpSocket
                    - required:
                      - exec
                - required:
                  - httpGet
                - required:
                  - tcpSocket
                - required:
                  - exec
                properties:
                  exec:
                    description: Health is determined by how the command that is executed
                      exited.
                    properties:
                      command:
                        description: Command to run.
                        items:
                          type: string
                        type: array
                    type: object
                  failureThreshold:
                    description: Minimum consecutive failures for the probe to be
                      considered failed after having succeeded.
                    format: int32
                    type: integer
                  httpGet:
                    properties:
                      host:
                        description: Host name to connect to, defaults to the pod
                          IP.
                        type: string
                      httpHeaders:
                        description: Headers the proxy will pass on to make the request.
                        items:
                          properties:
                            name:
                              type: string
                            value:
                              type: string
                          type: object
                        type: array
                      path:
                        description: Path to access on the HTTP server.
                        type: string
                      port:
                        description: Port on which the endpoint lives.
                        type: integer
                      scheme:
                        type: string
                    type: object
                  initialDelaySeconds:
                    description: Number of seconds after the container has started
                      before readiness probes are initiated.
                    format: int32
                    type: integer
                  periodSeconds:
                    description: How often (in seconds) to perform the probe.
                    format: int32
                    type: integer
                  successThreshold:
                    description: Minimum consecutive successes for the probe to be
                      considered successful after having failed.
                    format: int32
                    type: integer
                  tcpSocket:
                    description: Health is determined by if the proxy is able to connect.
                    properties:
                      host:
                        type: string
                      port:
                        type: integer
                    type: object
                  timeoutSeconds:
                    description: Number of seconds after which the probe times out.
                    format: int32
                    type: integer
                type: object
              template:
                description: Template to be used for the generation of `WorkloadEntry`
                  resources that belong to this `WorkloadGroup`.
                properties:
                  address:
                    type: string
                  labels:
                    additionalProperties:
                      type: string
                    description: One or more labels associated with the endpoint.
                    type: object
                  locality:
                    description: The locality associated with the endpoint.
                    type: string
                  network:
                    type: string
                  ports:
                    additionalProperties:
                      type: integer
                    description: Set of ports associated with the endpoint.
                    type: object
                  serviceAccount:
                    type: string
                  weight:
                    description: The load balancing weight associated with the endpoint.
                    type: integer
                type: object
            type: object
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}
  - additionalPrinterColumns:
    - description: 'CreationTimestamp is a timestamp representing the server time
        when this object was created. It is not guaranteed to be set in happens-before
        order across separate operations. Clients may not set this value. It is represented
        in RFC3339 form and is in UTC. Populated by the system. Read-only. Null for
        lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata'
      jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1beta1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              metadata:
                description: Metadata that will be used for all corresponding `WorkloadEntries`.
                properties:
                  annotations:
                    additionalProperties:
                      type: string
                    type: object
                  labels:
                    additionalProperties:
                      type: string
                    type: object
                type: object
              probe:
                description: '`ReadinessProbe` describes the configuration the user
                  must provide for healthchecking on their workload.'
                oneOf:
                - not:
                    anyOf:
                    - required:
                      - httpGet
                    - required:
                      - tcpSocket
                    - required:
                      - exec
                - required:
                  - httpGet
                - required:
                  - tcpSocket
                - required:
                  - exec
                properties:
                  exec:
                    description: Health is determined by how the command that is executed
                      exited.
                    properties:
                      command:
                        description: Command to run.
                        items:
                          type: string
                        type: array
                    type: object
                  failureThreshold:
                    description: Minimum consecutive failures for the probe to be
                      considered failed after having succeeded.
                    format: int32
                    type: integer
                  httpGet:
                    properties:
                      host:
                        description: Host name to connect to, defaults to the pod
                          IP.
                        type: string
                      httpHeaders:
                        description: Headers the proxy will pass on to make the request.
                        items:
                          properties:
                            name:
                              type: string
                            value:
                              type: string
                          type: object
                        type: array
                      path:
                        description: Path to access on the HTTP server.
                        type: string
                      port:
                        description: Port on which the endpoint lives.
                        type: integer
                      scheme:
                        type: string
                    type: object
                  initialDelaySeconds:
                    description: Number of seconds after the container has started
                      before readiness probes are initiated.
                    format: int32
                    type: integer
                  periodSeconds:
                    description: How often (in seconds) to perform the probe.
                    format: int32
                    type: integer
                  successThreshold:
                    description: Minimum consecutive successes for the probe to be
                      considered successful after having failed.
                    format: int32
                    type: integer
                  tcpSocket:
                    description: Health is determined by if the proxy is able to connect.
                    properties:
                      host:
                        type: string
                      port:
                        type: integer
                    type: object
                  timeoutSeconds:
                    description: Number of seconds after which the probe times out.
                    format: int32
                    type: integer
                type: object
              template:
                description: Template to be used for the generation of `WorkloadEntry`
                  resources that belong to this `WorkloadGroup`.
                properties:
                  address:
                    type: string
                  labels:
                    additionalProperties:
                      type: string
                    description: One or more labels associated with the endpoint.
                    type: object
                  locality:
                    description: The locality associated with the endpoint.
                    type: string
                  network:
                    type: string
                  ports:
                    additionalProperties:
                      type: integer
                    description: Set of ports associated with the endpoint.
                    type: object
                  serviceAccount:
                    type: string
                  weight:
                    description: The load balancing weight associated with the endpoint.
                    type: integer
                type: object
            type: object
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: false
    subresources:
      status: {}
status:
  acceptedNames:
    categories:
    - istio-io
    - networking-istio-io
    kind: WorkloadGroup
    listKind: WorkloadGroupList
    plural: workloadgroups
    shortNames:
    - wg
    singular: workloadgroup
  conditions:
  - lastTransitionTime: "2022-08-30T02:44:43Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2022-08-30T02:44:43Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1alpha3

**Comment by jshaughn** [comment]
Hi @MollyH1391.  Just an update that Kiali v1.63 will have better support for when the istiod API can not be accessed by Kiali (https://github.com/kiali/kiali/issues/5626 has been completed).  Although some Kiali features will be disabled, Kiali should still function without error.  This may help the Anthos situation.

I'm going to close this issue since I don't see a further action item at the moment.  Feel free to re-open or open something new, as needed.
