### ISSUE TITLE
References for K8s Gateways

### ISSUE THREAD

**Issue by josunect** [kiali/kiali#5708]
Epic #5501 

Analysis of the objects in the k8s Gateways to point to other objects. 

![image](https://user-images.githubusercontent.com/49480155/212044757-d1c78988-7912-4be8-8f8d-9e86af4efeb7.png)

For a k8s Gateway, it can reference: 

- Services.

A Gateway is autogenerated when a k8s GW is created. The GW will have a reference to the k8s GW. Ex.

`internal.istio.io/parents: Gateway/gw/test.bookinfo`

**Comment by leandroberetta** [comment]
Hi @josunect , I've been working on this issue and I think that for the K8s Gateways, we can show the HTTPRoutes that has associated, for example:

![image](https://user-images.githubusercontent.com/1286393/213763433-3fb19b3c-5507-4f95-af41-6789da8a61a1.png)

The services, are shown then by the HTTPRoutes:

![image](https://user-images.githubusercontent.com/1286393/213763537-fb51551b-fee5-4242-a7ef-612b09ef9f3f.png)

What do you think?.

**Comment by hhovsepy** [comment]
+1 to show HTTPRoutes

**Comment by josunect** [comment]
> Hi @josunect , I've been working on this issue and I think that for the K8s Gateways, we can show the HTTPRoutes that has associated, for example:
> 
> ![image](https://user-images.githubusercontent.com/1286393/213763433-3fb19b3c-5507-4f95-af41-6789da8a61a1.png)
> 
> The services, are shown then by the HTTPRoutes:
> 
> ![image](https://user-images.githubusercontent.com/1286393/213763537-fb51551b-fee5-4242-a7ef-612b09ef9f3f.png)
> 
> What do you think?.

I think it is a great idea!
