### ISSUE TITLE
Improve KIA0301 (more than one gateway warning) to treat a single * as not a warning

### ISSUE THREAD

**Issue by ldemailly** [kiali/kiali#5711]
Summary: Change  KIA0301 so "*" doesn't end up conflicting with every other entry (as it doesn't actually conflict for istio) - or an option to do so

We use * in some shared gateway because it's needed for routing some health checks that come with no host entry as well as a catch up for for doing https redirect but the more specific entries like foo.bar.blah are marked as KIA0301 even though they really aren't in conflict: istio uses the most specific if there is a match and * is just the fallback so not an error/warning

In our use case we don't want to ignore real errors, but do want to not count * as it doesn't actually conflict (so ignoring KIA0301 entirely isn't what we need)

Can we make it configurable or an option to ignore * ? (or tbh the default behavior to match 'real' conflicts - like if more than 1 gateway had * that would be an error but not if there is only 1 and more specific hosts in others - for a given ingress)

Thanks!

(came up first in https://github.com/kiali/kiali/issues/5213#issuecomment-1219937078 but asked to make a separate issue)

ref: https://kiali.io/docs/features/validations/#kia0301---more-than-one-gateway-for-the-same-host-port-combination

**Comment by jshaughn** [comment]
@hhovsepy , any comments on this one?

**Comment by ldemailly** [comment]
to note I offered to give it a try but didn't find the time yet (and won't be this week so maybe if anyone gets to it first, all the better)

**Comment by hhovsepy** [comment]
A new option "skip_wildcard_gateway_hosts" is added in Kiali CR to set it 'true' (by default 'false') to skip "KIA0301 More than one Gateway for the same host port combination" validation for Gateways with wildcard in hostname.
Will be available with release Kiali v1.65
