### ISSUE TITLE
Kiali view-only mode allows changing proxy log-level

### ISSUE THREAD

**Issue by jshaughn** [kiali/kiali#5714]
Originally reported in https://issues.redhat.com/browse/OSSM-2371

Despite Kiali being configured as "view-only", a user can change the proxy logging level via the Workload details' Logs tab's kebab menu.  This should be prevented as it updates the existing workload configuration.

**Comment by jshaughn** [comment]
I'm not sure if we hide or disable options when view-only is configured.  We should be consistent.

**Comment by josunect** [comment]
I'm agree with being consistent. I will made the changes.

**Comment by josunect** [comment]
> In view-only or not aavailable modes we disable the options, in kiosk mode we hide them.

Good point, @hhovsepy ! Thank you
