### ISSUE TITLE
We need to add gcc require in Developer setup

### ISSUE THREAD

**Issue by aljesusg** [kiali/kiali#5728]
In https://github.com/kiali/kiali#developer-setup we need to add the requirement of gcc .

When we execute **make test** 

cgo: C compiler "gcc" not found: exec: "gcc": executable file not found in $PATH

**Comment by ferhoyos** [comment]
This requirement should be added to https://kiali.io/docs/contribution-guidelines/development-environment/ too.

**Comment by premkirank** [comment]
@ferhoyos please assign this to me. Would like to work on this
