### ISSUE TITLE
KIA0106 false positive with wildcard

### ISSUE THREAD

**Issue by Unichron** [kiali/kiali#5729]
Hi!

If you have a wildcard in source.principal (e.g. in a AuthorizationPolicy) then Kiali will report a false positive KIA0106. Could be there are other issues with wildcards, didn't check anything else.

![2023-01-18_14-59](https://user-images.githubusercontent.com/17097232/213190734-5e9c9840-0ead-45e7-9651-d522bf156345.png)

It's 100% false positive because it works in Istio.

Also see https://istio.io/latest/docs/reference/config/security/authorization-policy/#Rule

> Any string field in the rule supports Exact, Prefix, Suffix and Presence match:
> Exact match: “abc” will match on value “abc”.
> Prefix match: “abc*” will match on value “abc” and “abcd”.
> Suffix match: “*abc” will match on value “abc” and “xabc”.
> Presence match: “*” will match when value is not empty.

**Comment by jshaughn** [comment]
cc @hhovsepy

**Comment by hhovsepy** [comment]
thanks for reporting @Unichron , I confirm this bug, it's in our backlog now

**Comment by hhovsepy** [comment]
Issue is fixed, will be released with the Kiali v1.63 release. Also will be included on next v1.57.6 release.
