### ISSUE TITLE
Multicluster - data models support multiple clusters

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#5736]
Kiali's data models assume a single cluster for workloads/services/apps. A [workload](https://github.com/kiali/kiali/blob/master/models/workload.go) for example has no way to track the cluster(s) it resides in. These need to be revisited for multicluster.

Part of this issue will be determining how or if these models need to change.

Part of: #5618

**Comment by leandroberetta** [comment]
The first thing I think when looking at this is to add a cluster field in the WorkloadListItem (for the workloads case). 

@nrfox is there anything on your mind, to me it will basically the majority of the work, but maybe I'm missing something.

**Comment by jshaughn** [comment]
> The first thing I think when looking at this is to add a cluster field in the WorkloadListItem (for the workloads case).

I think this is exactly right, we need to add Cluster to all models, as an additional discriminator to Namespace.  Note that there is nothing really blocking this today, as everything already has a cluster, we have just implicitly assumed that it is the same cluster as the cluster for Kiali (with the exception of the graph, which is already cluster-aware to some degree).  We could add it and set it today, defaulting to the "home" cluster.  Note that cluster defaults to the name "kubernetes" in Istio.

**Comment by nrfox** [comment]
> we need to add Cluster to all models, as an additional discriminator to Namespace

There might be more to it than that. Some things like services can span multiple clusters but istio will load balance requests between the clusters as if they were the same service. Then there's some exceptions to that like with cluster local settings: https://istio.io/latest/docs/ops/configuration/traffic-management/multicluster/#keeping-traffic-in-cluster. Other objects like istio configuration do not span clusters afaik.

If Kiali doesn't do any kind of aggregation on the backend then it will most likely need to do it on the frontend along with handling exceptions for things like cluster local settings. If we can align kiali's models with Istio's models I think we'll be in better shape but other parts of Kiali like the graph might also be affected by any model changes if we try to say link a graph node to the kube service that it represents.

**Comment by leandroberetta** [comment]
@nrfox the only model change I've been thinking is to add the "cluster" field to the models. I think I'm follow what you're saying, but I'm not sure this change will affect the graph or other parts. But maybe I'm not seeing something, is ok for you if at least the cluster field is added?.

**Comment by leandroberetta** [comment]
Probably we need to close this issue because all the model work is done by the other issues affecting the lists. The applications list PR is touching the model it needs to touch and the others are doing the same.

Also, because of this, I'm closing the following PR: https://github.com/kiali/kiali/pull/5914.
