### ISSUE TITLE
Kiali still referencing removed networking.k8s.io/v1beta1.Ingress in ansibleResult

### ISSUE THREAD

**Issue by mariusandersen** [kiali/kiali#5747]
When using kubernetes v1.23.5, istio 1.16.1, installing kiali-operator (v1.62.0, latest release) with Kiali CR, it "fails" complaining like this

```
status:
  conditions:
    - lastTransitionTime: '2023-01-21T19:21:00Z'
      message: Running reconciliation
      reason: Running
      status: 'False'
      type: Running
    - ansibleResult:
        changed: 1
        completion: '2023-01-21T19:22:22.6009'
        failures: 1
        ok: 68
        skipped: 74
      lastTransitionTime: '2023-01-21T19:22:22Z'
      message: >-
        Failed to find exact match for networking.k8s.io/v1beta1.Ingress by
        [kind, name, singularName, shortNames]
      reason: Failed
      status: 'True'
      type: Failure
```

networking.k8s.io/v1beta1.Ingress was removed in kubernetes v1.22

The kiali type gets stuck in status "Processing" in ArgoCD and every time I want to remove it I have to manually remove the finalizers.

FYI kiali get's installed OK ignoring this issue.

Is this a bug? 

Alternativly is there a way to stop Ansible from complaining about this?

**Comment by jmazzitelli** [comment]
This is not a bug, or shouldn't still be. This was fixed last year. See:

- https://github.com/kiali/kiali/issues/3706
- https://github.com/kiali/kiali-operator/pull/252/files

I don't know why it fails in your situation - there must be something behind the scenes that we don't know about. Perhaps the operator fails to even see `networking.k8s.io/v1.Ingress` API (you DO have that API in your cluster, correct)? This is the kind of test the operator does to properly configure the Ingress api_version: https://github.com/kiali/kiali-operator/blob/master/roles/default/kiali-deploy/templates/kubernetes/ingress.yaml#L1

There are a couple things you can do:
1. Confirm `networking.k8s.io/v1.Ingress`exists on your cluster. If not, get it on there. This error will be the result.
or
2. Disable the Ingress generation so the kiali operator doesn't create it - in that case you can create your own. To disable Ingress, see: https://kiali.io/docs/configuration/kialis.kiali.io/#.spec.deployment.ingress.enabled

**Comment by jmazzitelli** [comment]
Giving us the operator logs where that error occurs (and the surrounding log messages) would help determine where this is failing. I don't know why or where this would fail EXCEPT, as I said earlier, in the case the operator can't determine if the cluster has the new v1 API (in which case it falls back to the older one). But knowing where the failure occurs would help determine that.

**Comment by mariusandersen** [comment]
Sorry I found the issue, my fault. 

I am using the [helmchart](https://github.com/kiali/helm-charts) and used the latest [github release](https://github.com/kiali/helm-charts/releases) to determine what version I put in Chart.yaml (1.30) . This is wrong. It seems like there is a 1-to-1 sync between kiali-operator and kiali CR versioning.

Chart.yaml

```
dependencies:
  - name: kiali-operator
    version: 1.30.0
    repository: https://kiali.org/helm-charts
```

Should be

```
dependencies:
  - name: kiali-operator
    version: 1.62.0
    repository: https://kiali.org/helm-charts
```

Thanks for the fast response

**Comment by jmazzitelli** [comment]
> It seems like there is a 1-to-1 sync between kiali-operator and kiali CR versioning.

Correct. This is mentioned in the Kiali documentation:

https://kiali.io/docs/installation/installation-guide/advanced-install-options/#installing-a-kiali-server-of-a-different-version-than-the-operator

```
When you install the Kiali Operator, it will be configured to install a Kiali Server that
is the same version as the operator itself. For example, if you have Kiali Operator
v1.34.0 installed, that operator will install Kiali Server v1.34.0. If you upgrade (or
downgrade) the Kiali Operator, the operator will in turn upgrade (or downgrade)
the Kiali Server.
```

I know this isn't your use-case, but note the caveat if you do want the operator to install different kiali versions, you must ensure that custom kiali version is supported by the operator (you are not guaranteed the operator will be able to install a different version)... so, yes, 1-to-1 operator-to-kiali is typically what you want:

https://kiali.io/docs/configuration/kialis.kiali.io/#.spec.deployment.image_version

```
If you set this to a specific version (i.e. you do not leave it as the default
empty string), you must make sure that image is supported by the operator.
```
