### ISSUE TITLE
Update each business layer to read from each configured backend kube cluster

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#5764]
Each business layer service needs to aggregate kube config across the different clusters kiali is connected to. Reads should come from the kiali cache ~and writes should be done using the user's token client.~ writes can be handled in #5765 or a separate issue.

~This issue can probably be broken down even further to update each business service individually.~

The following business layers should be modified:

- [ ] Services
- [ ] Workloads
- [ ] Configs
- [ ] Applications
- [ ] Graph
- [ ] Filter by Cluster name

**Comment by matejnesuta** [comment]
Adding the test-add-coverage label just to mark this issue for a re-visit later

**Comment by nrfox** [comment]
Moving this to #5919 which encompasses both frontend and backend changes for the list view. This issue only focused on the backend.
