### ISSUE TITLE
Update the namespace cache which caches the user token per namespace to support multicluster

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#5766]
The namespaces cache saves a user's token and the namespaces they can access so that multiple requests to `GetNamespaces` don't need to be repeatedly made. This cache should support caching namespaces by cluster/namespace.

https://github.com/kiali/kiali/blob/b3310862c6fa8ce90e0f0a6e37dac72545d1dddf/kubernetes/cache/cache.go#L62-L67

I will link the proposal:
https://github.com/kiali/kiali/blob/master/design/KEPS/multicluster/proposal.md#api

**Comment by josunect** [comment]
As a first approach getting the namespace list: 

![image](https://user-images.githubusercontent.com/49480155/218532574-a4b5c388-ff36-449d-a8fa-d7d076ab8478.png)

The ajax call returns the following: 
`
[{"name":"bookinfo","labels":{"istio-injection":"enabled","kubernetes.io/metadata.name":"bookinfo"},"annotations":{},"cluster":"_kiali_home"},{"name":"default","labels":{"kubernetes.io/metadata.name":"default"},"annotations":{},"cluster":"_kiali_home"},{"name":"ingress-nginx","labels":{"app.kubernetes.io/instance":"ingress-nginx","app.kubernetes.io/name":"ingress-nginx","kubernetes.io/metadata.name":"ingress-nginx"},"annotations":{},"cluster":"_kiali_home"},{"name":"istio-system","labels":{"kubernetes.io/metadata.name":"istio-system","topology.istio.io/network":"network-east"},"annotations":{},"cluster":"_kiali_home"},{"name":"keycloak","labels":{"kubernetes.io/metadata.name":"keycloak","name":"keycloak"},"annotations":{},"cluster":"_kiali_home"},{"name":"metallb-system","labels":{"app":"metallb","kubernetes.io/metadata.name":"metallb-system"},"annotations":{},"cluster":"_kiali_home"},{"name":"bookinfo","labels":{"istio-injection":"enabled","kubernetes.io/metadata.name":"bookinfo"},"annotations":{},"cluster":"west"},{"name":"default","labels":{"kubernetes.io/metadata.name":"default"},"annotations":{},"cluster":"west"},{"name":"ingress-nginx","labels":{"app.kubernetes.io/instance":"ingress-nginx","app.kubernetes.io/name":"ingress-nginx","kubernetes.io/metadata.name":"ingress-nginx"},"annotations":{},"cluster":"west"},{"name":"istio-system","labels":{"kubernetes.io/metadata.name":"istio-system","topology.istio.io/network":"network-west"},"annotations":{},"cluster":"west"},{"name":"kiali-access-ns","labels":{"kubernetes.io/metadata.name":"kiali-access-ns"},"annotations":{},"cluster":"west"},{"name":"metallb-system","labels":{"app":"metallb","kubernetes.io/metadata.name":"metallb-system"},"annotations":{},"cluster":"west"}]`

**Comment by josunect** [comment]
Thanks for clarifying, @jshaughn !

**Comment by jshaughn** [comment]
I hope I'm right, @josunect  :-)  Others should correct me if they expect something else.  But my understanding is that the user selects the namespaces, just like today, and the backend code is then responsible for knowing which clusters those namespaces cover.  The UI presents the results for all of the accessible clusters, possibly showing the cluster, or clusters where appropriate.

**Comment by josunect** [comment]
> I hope I'm right, @josunect :-) Others should correct me if they expect something else. But my understanding is that the user selects the namespaces, just like today, and the backend code is then responsible for knowing which clusters those namespaces cover. The UI presents the results for all of the accessible clusters, possibly showing the cluster, or clusters where appropriate.

I linked the MC Proposal as I think it also has some clarification and it goes in that direction. But, my first question was, What happen when you have the same namespace in different clusters? In that case it is expected that the business layer aggregates the data and returns information about both.

**Comment by jshaughn** [comment]
Let's say namespace `Foo` is found on clusters `A` and `B` and `Foo` is selected in the Namespace selector for the `Services` list page.  And the user has access to `A` and 'B'.   I think what you would see is the aggregated list of services for both clusters.  The list would have a new `Cluster` column (when the install is MC) and so you'd see the cluster information for the services.  If service `MySvc` exists on both clusters I *think* it would mean two rows in the table but its something to discuss.  We need to decide how we want to handle the detail views, meaning, a single detail page for `MySvc` that shows all of the clusters, or a cluster-specific detail page.

**Comment by josunect** [comment]
> Let's say namespace `Foo` is found on clusters `A` and `B` and `Foo` is selected in the Namespace selector for the `Services` list page. And the user has access to `A` and 'B'. I think what you would see is the aggregated list of services for both clusters. The list would have a new `Cluster` column (when the install is MC) and so you'd see the cluster information for the services. If service `MySvc` exists on both clusters I _think_ it would mean two rows in the table but its something to discuss. We need to decide how we want to handle the detail views, meaning, a single detail page for `MySvc` that shows all of the clusters, or a cluster-specific detail page.

I think it makes sense, following the principle of namespaces sameness. 
I like the idea about defining different views when the install is MC. I think we should decide if it would be explicit (Like using a configuration item) or not (It can be detected when we have, at least, one remote cluster)

**Comment by jmazzitelli** [comment]
> I think we should decide if it would be explicit (Like using a configuration item) or not (It can be detected when we have, at least, one remote cluster)

We do not need to have an explicit setting. We can figure this out during runtime automatically.

Take a look at how the "Mesh" left-hand nav menu item dynamically shows up or is hidden - that's the code we can reuse (or more likely we will want to enhance it). Currently, it shows up if Istio is configured with a Mesh ID (and that could be true even with a single cluster). We could enhance it to look at something like one of these things:

* ClientFactory.GetClusterNames (https://github.com/kiali/kiali/blob/master/kubernetes/client_factory.go#L382) - if that returns more than 1 name, we know we have remote clusters
* kubernetes.GetRemoteClusterInfos (https://github.com/kiali/kiali/blob/master/kubernetes/cluster_secret.go#L58) - if we get 1 or more remote cluster infos, then we know we have remote clusters
