### ISSUE TITLE
HTTP server library used in Kiali server is archived

### ISSUE THREAD

**Issue by ferhoyos** [kiali/kiali#5786]
HTTP router library used in Kiali (gorilla/mux - https://github.com/gorilla/mux) has been archived on Dec 9, 2022. This means that is no longer under active maintainenance. Although it is currently working as-is, to avoid security problems Kiali should migrate to another HTTP router library in the mid-long term.

Some alternatives for gorilla/mux library:
- Gin (https://github.com/gin-gonic/gin)

- Chi (https://github.com/go-chi/chi)

- Standard http.ServeMux (https://pkg.go.dev/net/http#ServeMux)

**Comment by jshaughn** [comment]
@ferhoyos It's almost a year later, should we make this a priority?

**Comment by ferhoyos** [comment]
Sometimes it is good to wait for this kind of migrations... It turns out that new contributors have started to work on this project, so it is not longer archived (new version 1.8.1 was released two months ago).

More info here:
https://gorilla.github.io/blog/2023-07-17-project-status-update/
https://www.reddit.com/r/golang/comments/14xyido/the_gorilla_web_toolkit_project_is_being_revived/

Closing the issue since the gorilla library is not longer in archive mode.
