### ISSUE TITLE
Build Kiali with a newer minor version of Golang

### ISSUE THREAD

**Issue by israel-hdez** [kiali/kiali#5799]
Kiali is currently being built with Golang 1.18. However, Go 1.20 was released recently, which means that Go1.18 should be considered as deprecated and would not receive patches anymore.

Kiali should switch to be built using a newer/maintained Golang version. Perhaps, using golang v1.19 rather than the newest is a fair target for stability and compatibility reasons.

**Comment by jshaughn** [comment]
@aljesusg , I assigned you to help https://github.com/MRafaydev with his contribution, as needed.
