### ISSUE TITLE
K8s Gateway wizard hostname is valid in frontend but rejected in Kiali server

### ISSUE THREAD

**Issue by ferhoyos** [kiali/kiali#5802]
If you set a hostname value in K8s gateway wizard with pattern "string/string.string", the value is set as valid in frontend wizard:

![image](https://user-images.githubusercontent.com/122779323/216951314-521c9c8c-7690-493e-aa05-3b13be2b2432.png)

But Kiali server returns error with following message:
{"error":"Gateway.gateway.networking.k8s.io \"test\" is invalid: spec.listeners.hostname: Invalid value: \"test/test.test\": spec.listeners.hostname in body should match '^(\\*\\.)?[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$'"}

![image](https://user-images.githubusercontent.com/122779323/216951180-c92cca0c-b5ab-4c54-80a6-0a1f45324eff.png)

The same validation should be both in frontend wizard and server backend.

**Comment by ferhoyos** [comment]
According to https://istio.io/latest/docs/reference/config/networking/gateway/, gateway hosts have namespace/dnsName with namespace optional.

According to https://gateway-api.sigs.k8s.io/v1alpha2/references/spec/#gateway.networking.k8s.io/v1beta1.Hostname, k8sGateway hosts have only dnsName.

The issue is that both Gateways and K8sGateways are using the same validation at frontend: isGatewayHostValid from IstioConfigUtils.ts. This validation is fine with Gateways but not with K8sGateways, so new isK8sGatewayHostValid method needs to be created.

**Comment by hhovsepy** [comment]
@ferhoyos right, +1 for new method
