### ISSUE TITLE
Remove @webcomponents/custom-elements from package.json since Firefox ESR supports it natively

### ISSUE THREAD

**Issue by ferhoyos** [kiali/kiali#5805]
Library @webcomponents/custom-elements was added to polyfill window.customElements since it was required for Firefox ESR (Extended Support Release) some time ago. According to https://developer.mozilla.org/en-US/docs/Web/API/Window/customElements, window.customElements is supported from Firefox version 62 and current Firefox ESR version is 102. Then this library is no longer needed since Firefox ESR supports this feature natively.

**Comment by jshaughn** [comment]
This work is actually being done by a comunity member, https://github.com/MRafaydev.  @ferhoyos , I assigned you to help make sure this contribution moves forward.
