### ISSUE TITLE
Consistent way to resolve Kiali version from Istio version

### ISSUE THREAD

**Issue by sspaeth-r7** [kiali/kiali#5823]
In reference to the [thread on Slack](https://istio.slack.com/archives/CJVRXB09F/p1675794599769689), we'd like a way to consistently determine which version of Kiali will work for a given version of Istio in an automated fasion. We were previously using the compatibility matrix that was [removed a few days ago](https://github.com/kiali/kiali/commit/a6b6fe0ecdf164d7539fc6a91c2d06468980c9d2#diff-a95cce4b184f43f541db267baeda9922b7aa186a09fd3574a79060e3ca6a702e).

I understand that maintaining this is an additional layer to y'all's release process that can easily be forgotten. The separate and more consumable markdown file sounds like a good idea @jmazzitelli.

If it would help I would be happy to throw up PRs for this though since y'all would ultimately be maintaining the docs I figure you might know better that I would how you'd like it setup.

Thanks for any help with this, and appreciate all y'all do for Kiali!

**Comment by jmazzitelli** [comment]
@jshaughn I think we could split this one up: https://github.com/kiali/kiali.io/blob/staging/content/en/docs/Installation/installation-guide/prerequisites.md

So we could have a file with all that text but then a separate file we could link to that would contain a more easily consumable table. We wouldn't want to have it less human readable I wouldn't think. So we'd need a good balance here - a good way for automation to consume it, but a good format for humans to be able to read as well. I don't have any suggestions as yet as to what it would look like. But that's where we'd start - refactoring that prerequisites.md file.

@sspaeth-r7 if you have suggestions, by all means let us know.

**Comment by sspaeth-r7** [comment]
Thanks John! Parsing it by splitting on the pipe character seems fairly easy to do. There's more complex markdown table parsers, but don't want to over-engineer anything on our end. It's just that the layout of the table would have to be pretty much set in stone when it's created. I guess the most important part would just be that the Istio and Kiali version columns stayed in the same place, and the wording separating min version and max version stayed the same (or better yet, split into separate columns if y'all are ok with it).

I briefly looked over [this](https://github.com/github/markup/blob/master/README.md#markups) doc showing GitHub's supported doc formats (like markdown), and didn't see any alternatives that were easier to parse, other than those which were language-specific, like Perl or Ruby. It'd be great if GitHub could display a CSV table visually to check both boxes, but unfortunately this doesn't seem to exist.

Keeping it in markdown seems like it'll work the best. Thanks for being open and I'll shout if I come up with a better solution anytime soon.

**Comment by jshaughn** [comment]
I know how to split out the table, let me do that now and see if it's helpful.

**Comment by sspaeth-r7** [comment]
I actually thought of a better idea shortly after closing my windows from earlier - linked in PR https://github.com/kiali/kiali.io/pull/633. Sorry to shoot this off right after we implemented another solution 😁 but I think this will be easier to automate, and personally speaking, better than maintaining it solely in MD as the table syntax starts looking awkward as columns expand and contract. Thanks for the consideration and I'm open to ways to improve it.
