### ISSUE TITLE
Internal server error when creating a Gateway with a duplicate name in the Istio Config Wizard

### ISSUE THREAD

**Issue by matejnesuta** [kiali/kiali#5830]
This is related to the #5811 issue. When I create a Gateway object, everything behaves as expected. When I try to create another Gateway object with the same name, an error message "Could not create Istio Gateway objects." is displayed, which also seems reasonable. However, a 500 code internal server error is also what I receive, which is confusing, because I expected a 400 return code instead. Is this the expected behaviour? 
![image](https://user-images.githubusercontent.com/45061792/217904410-6f5d4f89-05a8-44a4-96e2-127faae90602.png)

**Comment by jshaughn** [comment]
@matejnesuta `Help Wanted` is for when are asking for a community contribution.  This sounds like a bug the maintainers should handle.

**Comment by matejnesuta** [comment]
@jshaughn Sorry, my bad. For some unknown reason, I thought I should use it, when I am not sure, if it really is a bug. 

Anyways, just found out that something like this produces the very same outcome as described before.
![image](https://user-images.githubusercontent.com/45061792/217910690-789286f5-9531-4915-88fe-42f2b79eb5d7.png)

**Comment by hhovsepy** [comment]
@matejnesuta it shows error message in notification center, that name already exists:
![Screenshot from 2023-02-10 07-59-30](https://user-images.githubusercontent.com/604313/218024049-b853f17b-6ce5-4039-b708-53c908aed4a5.png)

**Comment by hhovsepy** [comment]
The creation of new configs in Kiali is designed in a way, that it does not check the existence of the name and directly calls k8s API for creation of new objects, and the API call returns error, Internal Server Error 500 is returned to user.
The 400 error stands for bad request, when request cannot be parsed.

**Comment by matejnesuta** [comment]
So everything is probably good I suppose. Should I close this issue? @hhovsepy
