### ISSUE TITLE
Duplicate IDs for the text inputs + high port value breaks the UI (Istio Config wizard page)

### ISSUE THREAD

**Issue by matejnesuta** [kiali/kiali#5834]
Some things I noticed while I was working today on the #5811 issue.

On the wizard page for ServiceEntry, I wanted to do a test on a 2 port specification with a same port name on the Istio Config wizard page. The issue here is that when multiple port specifications are present, the IDs in the HTML code for the text inputs and selects of the same category are identical. 
![image](https://user-images.githubusercontent.com/45061792/218164221-589299a6-e0e7-438f-923f-bac4f16c5a78.png)

On the wizard page for the Gateway, a port number little higher than 65535 will break the UI.
![image](https://user-images.githubusercontent.com/45061792/218168551-44617011-9084-42f8-b286-db81222c00f7.png)

**Comment by matejnesuta** [comment]
> I'm not sure on this one, is it a problem to duplicate ids under different parents? Maybe I am seeing it wrong.

Well, not sure from a practical point of view. It is usually expected for an ID attribute to be present only once in the whole HTML document. That's why I noticed it in the first place. I suppose those ids are there for testing purposes?

**Comment by hhovsepy** [comment]
yes those IDs are for cypress tests, so we can make them "${id}#n" incremental

**Comment by hhovsepy** [comment]
and the port numbers are limited to the range 0 to 65536, so this is by intention, as http requires

**Comment by matejnesuta** [comment]
The input and the button behaves normally for valid port numbers. The thing I screenshoted happens when 65536 or small increments of that numbers are inserted in the input. The input is red, but the button is still active and can be clicked on. For example, something like port 80000 will disable the button as expected.

**Comment by hhovsepy** [comment]
Thanks @matejnesuta  I confirm the issue, port number is invalid 65599, but the Preview button is available:
![Screenshot from 2023-02-13 18-50-54](https://user-images.githubusercontent.com/604313/218534357-aa165520-8c3b-47c8-8746-bc49aa52e348.png)

**Comment by hhovsepy** [comment]
cc @josunect

**Comment by josunect** [comment]
@matejnesuta , I've added an unique identifier like input0, input1 (Including a number per row). Let me know if that helps! 
You can try it in the related PR https://github.com/kiali/kiali/pull/5840. 

Thanks!
