### ISSUE TITLE
Check Tempo works with kiali with jaeger-query

### ISSUE THREAD

**Issue by aljesusg** [kiali/kiali#5848]
Check Tempo works with kiali with jaeger-query

Related with https://github.com/kiali/kiali/issues/4278#issuecomment-980638393

**Comment by iblancasa** [comment]
I can help with this

**Comment by jshaughn** [comment]
@iblancasa Are you still planning to help here?

**Comment by iblancasa** [comment]
Yes Jay. I’ll add some documentation this week.

Sorry for the delay.
Thanks!

**Comment by jshaughn** [comment]
Thanks @iblancasa!  @aljesusg, how should we proceed here, documentation on the steps necessary to use Tempo, or something more formal?

**Comment by jshaughn** [comment]
Hi @iblancasa , I think what we will want to do is turn this information into content for kiali.io.  Probably in this section: https://kiali.io/docs/configuration/p8s-jaeger-grafana/jaeger/.

**Comment by iblancasa** [comment]
Awesome. In that case, I'll create a PR to the [kiali.io repository](https://github.com/kiali/kiali.io) as soon as I can :)

**Comment by jshaughn** [comment]
Sounds great, if you need any guidance let us know.

**Comment by Hronom** [comment]
Please can we add it?

**Comment by Hronom** [comment]
Finally manage it to work https://github.com/kiali/kiali/issues/5849#issuecomment-1624311897

**Comment by caerulescens** [comment]
I managed to get this all working with the latest version of the `tempo-distributed` chart by working from @Hronom and @iblancasa instructions. Thanks guys

**Comment by aljesusg** [comment]
Thabks to verify.
Anyway @josunect did a demo in kiali.io you will see it soon

You can check the preview here https://deploy-preview-686--kiali.netlify.app/docs/tutorials/tempo/

Please feel free to add more information about it 🙏

**Comment by caerulescens** [comment]
Sure thing. I looked over the docs, and that's about the same thing I had to do. Create a PVC for MinIO and connect Tempo. Although, I'm doing it all through Helm managed by ArgoCD.

**Comment by aljesusg** [comment]
Great !!! If you find some problem with argocd please let us know it or if you prefer we can help you to contribute in the project with a tutorial about it 🤗

**Comment by aljesusg** [comment]
Added tutorial to kiali.io
