### ISSUE TITLE
Failed CI (possibly related to the Istio 1.17.0?)

### ISSUE THREAD

**Issue by matejnesuta** [kiali/kiali#5854]
So, my CI run failed almost instantly due to this. It was rebased against this PR (https://github.com/kiali/kiali/pull/5847). I am honestly not sure if it means anything or not, but there has been troubles due to the new Istio version (https://github.com/kiali/kiali/issues/5846), so I think it's worth the issue. 
https://github.com/kiali/kiali/actions/runs/4197218825/jobs/7279387344#step:7:94

**Comment by jmazzitelli** [comment]
that error shows it is still trying to download 1.17.

```
Downloading istio-1.17.0 from https://github.com/istio/istio/releases/download/1.17.0/istio-1.17.0-linux-amd64.tar.gz ...
```

That will fail until upstream istio publishes 1.17 on gcr.io

**Comment by jmazzitelli** [comment]
and I see there is no ISTIO_VERSION passed to the script - are you sure the PR is rebased on master?

```
Run hack/setup-kind-in-ci.sh
  hack/setup-kind-in-ci.sh
  shell: /usr/bin/bash -e {0}
  env:
    TARGET_BRANCH: master
    AUTH_STRATEGY: token
=== SETTINGS ===
DORP=docker
ISTIO_VERSION=
```

**Comment by jmazzitelli** [comment]
looks like it is rebased correctly, and istio 1.16.2 is being installed now. https://github.com/kiali/kiali/actions/runs/4197218825/jobs/7279682550

I think you can close this as not-a-bug.
