### ISSUE TITLE
Error page could be more than just a text message

### ISSUE THREAD

**Issue by ferhoyos** [kiali/kiali#5862]
When there is an error, just unstyled small text message is shown at the top:

![image](https://user-images.githubusercontent.com/122779323/220310768-8aca2dd3-549f-451a-b376-72881e67cf69.png)

A custom error component could be created with some warning icon or image, styled error text message and even a refresh button.

**Comment by jshaughn** [comment]
I'll be honest, I think the real problem is the crash :-)  Is this something reproducible?

**Comment by ferhoyos** [comment]
I'm investigating it, I will create an issue when I can reproduce it. In the meantime I think it would be good to have a prettier error message for these cases :-)

**Comment by ferhoyos** [comment]
@jshaughn I can reproduce the error. Issue #5864 created.
