### ISSUE TITLE
Application crash when accessing service from K8s Gateway

### ISSUE THREAD

**Issue by ferhoyos** [kiali/kiali#5864]
After creating a K8s Gateway (e.g. the one created by Cypress test), the application crashes when the user accesses the service details associated to K8s Gateway.

![image](https://user-images.githubusercontent.com/122779323/220376400-914dfb36-1f87-4712-98b4-30cda0fb0e39.png)

![image](https://user-images.githubusercontent.com/122779323/220376497-30808da8-fcd7-4a2d-922e-56cca1a86bd3.png)

![image](https://user-images.githubusercontent.com/122779323/220376746-eae962d2-4322-4c08-9417-ad396532d40d.png)

I think it is related with new annotations feature added by @aljesusg. The error happens because server returns null for service annotations and the following code cannot map a null value throwing the error (WizardAnnotations.tsx):

```
convertAnnotationsToMap = () => {
    const m = new Map();
    Object.keys(this.props.annotations).map((value, index) => m.set(index, [value, this.props.annotations[value]]));
    return m;
  };  
```

**Comment by aljesusg** [comment]
O.o the value should not be null, must be empty, this error must be fixed in the backend
