### ISSUE TITLE
envoy listeners tab - match column shows does not show correct dest port when destination_port is specified

### ISSUE THREAD

**Issue by rsalmond** [kiali/kiali#5872]
When a Listener contains a filter_chain_match which specifies a destination port, the Match column on the Envoy Listeners tab displays a giant number instead of the value assigned to `destination_port`. 

<img width="925" alt="image" src="https://user-images.githubusercontent.com/4367945/221436996-0cef497f-e14c-46da-a2cb-9bb0676e334b.png">

Corresponding Listener config

![image](https://user-images.githubusercontent.com/4367945/221437007-97fb4303-8aba-40c1-8ccd-f8d844042397.png)

I'm not much of a Go programmer and I don't have the build environment set up to test this guess, but it looks like maybe we don't want to dereference a pointer on line 114 (notice line 112 doesn't deref).

https://github.com/kiali/kiali/blob/master/models/config_dump.go#L112-L114

**Comment by jshaughn** [comment]
Thanks @rsalmond , we'll look into it!
