### ISSUE TITLE
Does Kiali support displaying custom content in graph data?

### ISSUE THREAD

**Issue by mark8s** [kiali/kiali#5901]
Hello everyone, I have a question.

I would like to ask if kiali can support displaying custom content in the picture?
In my current environment, some indicators of prometheus have `request_header` related content. Is there a way to display these data in kiali?

like:

![image](https://user-images.githubusercontent.com/47961301/223985740-bcf0baa2-97e8-4f2a-9962-8ce3d861bf5a.png)

Is there a way to include `request_headers="details:9080` data in the graph data of kiali?

**Comment by jmazzitelli** [comment]
Not sure if this would help, but read about the Operation Nodes support in the graph:

https://kiali.io/docs/features/topology/#operation-nodes

which is related to Istio's Request Classification feature:

https://istio.io/latest/docs/tasks/observability/metrics/classify-metrics/

**Comment by mark8s** [comment]
@jmazzitelli Thanks, I'll take a look first

**Comment by mark8s** [comment]
@jmazzitelli I don't seem to understand much, kiali does not need to do additional configuration? ? ?

**Comment by jmazzitelli** [comment]
> kiali does not need to do additional configuration? 

Kiali does not need additional configuration if you are using that Istio feature that I linked to (request classification). If you classify your requests (which it seems like that is what you want to do), then Kiali "will just work" with it. It will show the Operation Nodes based on the metric classifications. Just enable the display of operation nodes:
![image](https://user-images.githubusercontent.com/2029470/224002826-7e5dad8a-01d1-45de-aaae-ce327ff820c7.png)

**Comment by mark8s** [comment]
@jmazzitelli Thank you very much, I will test it myself first~

**Comment by mark8s** [comment]
@jmazzitelli  Hi, I tried it, but it doesn't seem to work. Can you take a look for me?

I set the request classification for the reviews service, and I can also see the data of different classifications from the results of prometheus, but kiali does not display it.

![image](https://user-images.githubusercontent.com/47961301/224237666-e5938961-72ec-4e43-90e9-9d5c5c34e5da.png)

![image](https://user-images.githubusercontent.com/47961301/224237720-3397bd1e-6107-4378-b746-dbba5eed7831.png)

![image](https://user-images.githubusercontent.com/47961301/224237798-72912908-b9cf-43af-ac60-17e36cf793be.png)

![image](https://user-images.githubusercontent.com/47961301/224237954-31e16db6-189f-4664-b789-7a88318109af.png)

I feel that my configuration is correct, why is kiali displayed incorrectly? ? ? ?

**Comment by mark8s** [comment]
@jmazzitelli I know, kiali has a requirement for the indicator name, which can only be `request_operation`. Thank you very much for your previous help~

**Comment by jshaughn** [comment]
@mark8s If you have any other feedback for the operation nodes feature please let us know.  I don't think it is a widely used feature but it can be useful!

**Comment by mark8s** [comment]
@jmazzitelli okok~
