### ISSUE TITLE
Remove yarn for npm

### ISSUE THREAD

**Issue by aljesusg** [kiali/kiali#5906]
# Introduction

Working in Plugin (https://github.com/kiali/openshift-servicemesh-plugin/issues/109) effort we checked that there is some stuff related with yarn in kiali-ui. 

Since the latest changes to use npm we should change Makefiles, workflows and are the stuff to use npm instead yarn

https://github.com/kiali/kiali/blob/f3f431063e067dd58c0906008e9a4c915e75a6e4/frontend/package.json#L32-L35

# Why

Sometimes stuff isntalled with yarn differs from npm, ts configurations etc... So it makes no sense use both.

**Comment by aljesusg** [comment]
Well, there is no problem about use yarn like engine because is going to call to the same commands.
The point is that since npm was introduced we have been living with both engines...and it would be great to move it to npm because for example our tsconfig throw errors with yarn install/build and not with npm  (https://github.com/kiali/kiali/actions/runs/4405837352/jobs/7717257150)

```bash
TS2769: No overload matches this call.
  Overload 1 of 2, '(props: ProviderProps<KialiAppAction> | Readonly<ProviderProps<KialiAppAction>>): Provider<KialiAppAction>', gave the following error.
    Type '{ children: Element; store: Store<KialiAppState, KialiAppAction>; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Provider<KialiAppAction>> & Readonly<ProviderProps<KialiAppAction>>'.
      Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Provider<KialiAppAction>> & Readonly<ProviderProps<KialiAppAction>>'.
  Overload 2 of 2, '(props: ProviderProps<KialiAppAction>, context: any): Provider<KialiAppAction>', gave the following error.
    Type '{ children: Element; store: Store<KialiAppState, KialiAppAction>; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Provider<KialiAppAction>> & Readonly<ProviderProps<KialiAppAction>>'.
      Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Provider<KialiAppAction>> & Readonly<ProviderProps<KialiAppAction>>'.
    109 |   render() {
    110 |     return (
  > 111 |       <Provider store={store}>
```

and the app is working in both cases ...so...

**Comment by jshaughn** [comment]
Sounds good.  I suppose where possible we should use `yarn` command more consistently, instead of `npm`.  It can be changed as we go...
