### ISSUE TITLE
Update of yarn.lock makes UI build fails

### ISSUE THREAD

**Issue by ferhoyos** [kiali/kiali#5909]
When yarn.lock is updated (e.g. a new library is added), UI build fails due to typescript tslint issues:

```sh
TS2769: No overload matches this call.
  Overload 1 of 2, '(props: ProviderProps<KialiAppAction> | Readonly<ProviderProps<KialiAppAction>>): Provider<KialiAppAction>', gave the following error.
    Type '{ children: Element; store: Store<KialiAppState, KialiAppAction>; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Provider<KialiAppAction>> & Readonly<ProviderProps<KialiAppAction>>'.
      Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Provider<KialiAppAction>> & Readonly<ProviderProps<KialiAppAction>>'.
  Overload 2 of 2, '(props: ProviderProps<KialiAppAction>, context: any): Provider<KialiAppAction>', gave the following error.
    Type '{ children: Element; store: Store<KialiAppState, KialiAppAction>; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Provider<KialiAppAction>> & Readonly<ProviderProps<KialiAppAction>>'.
      Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Provider<KialiAppAction>> & Readonly<ProviderProps<KialiAppAction>>'.
    109 |   render() {
    110 |     return (
  > 111 |       <Provider store={store}>
```

How to test:
1. Delete yarn.lock file
2. Execute `yarn` within frontend folder
3. Execute `make clean-all build-ui` on root folder

**Comment by aljesusg** [comment]
Well. This fail when we upgrade specific libraries that can impact to the actual code. We should check the tslint version compatible like we did with typescript https://www.npmpeer.dev/packages/tslint/compatibility

But IMO this is not a bug.

**Comment by ferhoyos** [comment]
It seems that some of the libraries get more recent versions of react, react-dom and react-redux types that are not compatible with current code. Add three of them to resolutions with specific version makes the trick. Besides @types/react-router library is needed too.

Not sure if it is really a bug or not because yarn.lock is the one that rules the dependencies, but I don't like having such inconsistencies between package.json and yarn.lock.

**Comment by jshaughn** [comment]
I don't think it's a good idea to delete yarn.lock...

**Comment by ferhoyos** [comment]
Closing the ticket since kiali ui will work while yarn.lock is not massively updated or deleted. This is something that probably will be faced in the future when React, react-dom or react-router libraries need to be upgraded.
