### ISSUE TITLE
Can't load "Workloads" view for k8s StatefulSet

### ISSUE THREAD

**Issue by RaiAnandKr** [kiali/kiali#5918]
So we have couple of StatefulSet deployment and trying to access the "Workloads" tab for both of them shows `Sorry, there was a problem. Try a refresh or navigate to a different page.`
![Screenshot 2023-03-16 at 12 26 33 PM](https://user-images.githubusercontent.com/21973868/225538996-a0ebef3b-181c-4cba-a515-d43a523b3553.png)

I tried multiple reloads and it's all the same. I can load the "Workloads" tab for any other deployment. Even for these StatefulSet deployments, I can access the corresponding `Applications` and `Services` view and just not the `Workloads` view. There isn't much showing up in Kiali logs too and it's making me wonder if StatefulSet workloads are unsupported in Kiali itself.

I am running Kiali `v1.64.0` and Istio `v1.16.3`

**Comment by josunect** [comment]
Thanks for the report @RaiAnandKr, it could be possible to get the Kiali logs and the debug information?

- Click the '?' on the right top button menu
- Select "View Debug Info"
- Select "Additional State" 
- Copy de information

**Comment by jshaughn** [comment]
I don't think this has to do specifically with StatefulSets.  I am able to render a StatefulSet in the Workloads list and in the Workload detail.  Given the error information this may have something to do with annotations you have assigned to the workload.  I've tried a variety of annotations and can not yet reproduce, can you share the annotations on your stateful set workload?

**Comment by jshaughn** [comment]
@RaiAnandKr, This issue is fixed in Kiali v1.65 (https://github.com/kiali/kiali/pull/5865).  It was fixed as part of https://github.com/kiali/kiali/issues/5864.  Sorry for the slow turnaround, I didn't see that the code had been changed recently.
