### ISSUE TITLE
Multicluster List Views 

### ISSUE THREAD

**Issue by josunect** [kiali/kiali#5919]
- Add a new cluster column in the List Views
- Add a new cluster filter:
  - The filter will no be propagated between views
  - The namespace selector depends on the cluster selector? (Dynamically changes based on the namespaces from the selected cluster) 
  - Not visible in single cluster view 
- Namespace filter: Won't show duplicated namespaces 
- Affected views: Applications, Workloads, Services and Istio Configs

Example with cluster filter and cluster column: 
![app list](https://user-images.githubusercontent.com/49480155/226981477-d41fce50-6d63-4c81-94d8-c91b7d7fcbaf.jpg)

It looks like the clusters badge is represented with a "C" in blue: 

![image](https://user-images.githubusercontent.com/49480155/227943963-2afc5885-6c7d-4bf0-9e0d-109512477c9f.png)

Ref. #5620 

- [x] #5959
- [x] #5960
- [x] #5961
- [x] #5962

**Comment by jshaughn** [comment]
@josunect Is this an Epic in itself?  I think Hayk may have already started this for `Workloads` with https://github.com/kiali/kiali/pull/5903

**Comment by josunect** [comment]
> @josunect Is this an Epic in itself? I think Hayk may have already started this for `Workloads` with #5903

That's right! That is specific to workloads, not sure if we can use this one to define the UI for all the lists views or close it and add the information there?

**Comment by hhovsepy** [comment]
We had an epic to rework backend to read workload/service/app/config objects from multicluster.
I did started on workloads, the scope of changes is so big that having all 4 types of w/s/a/c lists changed in one PR would be endless work and review.

**Comment by josunect** [comment]
@andrew-ronaldson I've seen in the ACM plugin that the cluster badge is shown as a C with a blue background: 

![image](https://user-images.githubusercontent.com/49480155/228583212-06f0d11a-de7d-4c58-8e4d-2c642861f9ce.png)

Does it looks right for you? 
Thanks!

**Comment by leandroberetta** [comment]
All list views are completed now, closing.
