### ISSUE TITLE
Multicluster - details Views

### ISSUE THREAD

**Issue by josunect** [kiali/kiali#5920]
- Define how to visualize the cluster view in the details views. 
- Not visible in single cluster 
- Affected views: Services, workloads, applications, Istio configs

An example for details views: 
![image (3)](https://user-images.githubusercontent.com/49480155/225613589-5fdb85de-8215-4e0e-8dfa-585ebd32bfed.jpg)
![image (2)](https://user-images.githubusercontent.com/49480155/225613627-2a7ed3bb-9c75-47e2-bc21-24477c5446b0.jpg)

- [x] #5964
- [x] #5965
- [x] #5966
- [x] #5967
- [x] #6059
- [x] https://github.com/kiali/kiali/issues/6062
- [x] https://github.com/kiali/kiali/issues/6152

Ref. #5620

**Comment by leandroberetta** [comment]
Closing as all sub tasks are resolved.
