### ISSUE TITLE
Multicluster view for graph page

### ISSUE THREAD

**Issue by josunect** [kiali/kiali#5922]
- Include a filter by cluster? 
- Cluster boxes are enabled by default (Actual behavior)

Cluster boxes: 
![image](https://user-images.githubusercontent.com/49480155/225615759-1ba4d6c9-d80a-4049-b67f-116af86076e0.png)

Example with cluster filter: 
![image (4)](https://user-images.githubusercontent.com/49480155/226981954-8c59dd47-1fa6-4df0-a8c8-0ccd2a1981d8.jpg)

Ref. #5620

**Comment by jshaughn** [comment]
I'm not sure there is work to do here.  We already have the `cluster` operand for Find/Hide, which should satisfy the filter requirement.  We will need to ensure that links are correct, they may need to add cluster as a query param.

**Comment by jshaughn** [comment]
> I think we need to show the same cluster box for cluster west as we are showing for cluster east

The clusters are directly related to the traffic for the requested namespaces.  I don't think we want the cluster selector as seen in the the screenshot from @josunect, instead just the usual Namespace Selector and Find/Hide.   You should see East and West Clusters as much as necessary given the traffic into, out of, and within the requested namespaces.  This should happen automatically as long as we have unified metrics for the two clusters.

> When right clicking on some service, there is no menu today

This is expected until we add Multi-Cluster support to the graph.  Today it likely ignores clusters other than the "home" cluster.  But it will need to realize that items for any of the configured clusters are available.

**Comment by leandroberetta** [comment]
> > I think we need to show the same cluster box for cluster west as we are showing for cluster east
> 
> The clusters are directly related to the traffic for the requested namespaces. I don't think we want the cluster selector as seen in the the screenshot from @josunect, instead just the usual Namespace Selector and Find/Hide. You should see East and West Clusters as much as necessary given the traffic into, out of, and within the requested namespaces. This should happen automatically as long as we have unified metrics for the two clusters.

I was referring just to the box, meaning, how cluster east looks like with all namespaces inside. 

I agree that probably the cluster selector is something we don't want.

**Comment by jshaughn** [comment]
> Replace the parenthesis for the cluster badge:

I am working on this one in https://github.com/kiali/kiali/issues/6123

**Comment by josunect** [comment]
This task involves several task. 

Closed by:

- https://github.com/kiali/kiali/issues/6123 
- https://github.com/kiali/kiali/issues/6150 
- https://github.com/kiali/kiali/issues/6062
