### ISSUE TITLE
[CI] Test flake - Service details gateway api

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#5936]
Test
> Service Details Wizard: K8s Gateway API Routing - See a HTTPRoute generated

Example: https://github.com/kiali/kiali/actions/runs/4480586005

Screenshot:
![Service Details Wizard K8s Gateway API Routing -- See a HTTPRoute generated (failed)](https://user-images.githubusercontent.com/6226732/226950261-ba1088f5-4571-4049-8608-d6f1d0b5621a.png)

**Comment by jshaughn** [comment]
I have not seen this happen recently and we have made some changes in this test code since reported.  Closing.
