### ISSUE TITLE
Multicluster - Set up a time out for each remote cluster call

### ISSUE THREAD

**Issue by josunect** [kiali/kiali#5941]
Ref. #5766

https://github.com/kiali/kiali/pull/5851#discussion_r1143332153

Use a timeout for each cluster call so a single cluster error doesn't blocks the whole calls. 
The kube client needs to accept the context with the specified time out.

**Comment by jshaughn** [comment]
@josunect , @nrfox , is this still relevant?  It's labeled as sub-task but not formally connected to an Epic.

**Comment by josunect** [comment]
> @josunect , @nrfox , is this still relevant? It's labeled as sub-task but not formally connected to an Epic.

I think this is still relevant as I don't see the context is propagated. 

This is part of an epic subtask already closed, https://github.com/kiali/kiali/issues/5701, so maybe it can reference the main epic? https://github.com/kiali/kiali/issues/5618

**Comment by nrfox** [comment]
This is still relevant but yes it should reference the main epic. I'll update it. It's more of a perf / quality of life improvement.

**Comment by nrfox** [comment]
I think we should instead do #7188 in lieu of this issue. Closing...
