### ISSUE TITLE
[make]Error to create operator pull secret

### ISSUE THREAD

**Issue by ferhoyos** [kiali/kiali#5945]
When I try to create operator with `make operator-create` command on Openshift CRC cluster, I receive following error at the end of the process:

```
error: failed to create secret Secret "kiali-operator-pull-secret" is invalid: data[.dockerconfigjson]: Invalid value: "<secret contents redacted>": invalid character 'S' looking for beginning of value
```

This is the version of my oc client:
```
Client Version: 4.12.4
Kustomize Version: v4.5.7
Server Version: 4.12.0
```

**Comment by jmazzitelli** [comment]
This needs to be fixed in the kiali repo and openshift-servicemesh-plugin repo:
* https://github.com/kiali/kiali/blob/v1.65.0/make/Makefile.operator.mk#L18
* https://github.com/kiali/openshift-servicemesh-plugin/blob/20453c1f7e81bc6e3133f39298497a24d6cb6f9b/make/Makefile.cluster.mk#L33
