### ISSUE TITLE
Multi-cluster list view - Applications

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#5961]
Applications list page pulls applications from all configured clusters.

**Comment by josunect** [comment]
Probably the concept of application is a bit different than a workload or a service. As described in [apps.go](https://github.com/kiali/kiali/blob/master/business/apps.go):

> AppService deals with fetching Workloads group by "app" label, which will be identified as an "application"

For what we can see now, probably application doesn't need to be tied to a particular cluster: 

![image](https://user-images.githubusercontent.com/49480155/228812138-485fbc49-0afb-416d-a1fe-a6343e4dde5d.png)

An application can be the logical view of a subset of workloads from different clusters.
In that case, probably we would want to remove the cluster column from that view, and include the cluster name in the application details. 

Does it makes more sense, or do we want to keep splitting also this view by cluster?

**Comment by jshaughn** [comment]
Hmm, it is an interesting question.
  In the graph the app and service nodes are still delimited by cluster.  Reviews-East is distinct from Reviews-West.  I think probably we should maintain that distinction in the list and detail views, but I'm not 100% sure.

 The thing is, for a detail page mini-graph you would always get a graph showing the app on all clusters (unless we make a change)
.
 My general guidance is that a single app or service that is deployed on different clusters may behave differently on a specific cluster, and a user may want to see it specifically for that cluster.   Meaning, the workloads for that App, for example, would be limited to the specific cluster.
