### ISSUE TITLE
Missing horizontal scrollbar when seeing logs

### ISSUE THREAD

**Issue by im-Amitto** [kiali/kiali#5989]
Kiali Info: 
<img width="601" alt="Screenshot 2023-04-04 at 5 44 51 PM" src="https://user-images.githubusercontent.com/29653282/229788431-72814d65-94e1-4e77-a8c4-cbb5ccd4d6d3.png">

There is no horizontal scrollbar when checking workload logs so there is no way to see long logs

<img width="601" alt="Screenshot 2023-04-04 at 5 45 00 PM" src="https://user-images.githubusercontent.com/29653282/229788796-0a7ddaf9-947a-402f-b23b-252afc78c195.png">

**Comment by im-Amitto** [comment]
FYI:
If you have more than a page of logs in current page then the horizontal bar does appear as well along with vertical one.

**Comment by hhovsepy** [comment]
Thanks for logging @im-Amitto , I confirm the issue.

**Comment by jshaughn** [comment]
That;s definitely some sort of regression. @im-Amitto, can you confirm your Browser type and version?

**Comment by im-Amitto** [comment]
I forgot to drop this last time but i think the culprit is the `hidden` overflow on `x-axis` for the log grid.
```
<div aria-label="grid" aria-readonly="true" class="ReactVirtualized__Grid ReactVirtualized__List" role="grid" tabindex="0" style="box-sizing: border-box; direction: ltr; height: 10px; position: relative; width: 1209px; will-change: transform; overflow: hidden auto;">
```

**Comment by im-Amitto** [comment]
@hhovsepy @jshaughn 
I was just checking out the codebase and realised that `List` from `react-virtualized` is being used to render logs which is causing this issue. `List` component does not have a `horizontal scrollbar` and is a implementation of `Grid` component which actually have the scrollbar we need.

One thing we can do is simply replace the `List` Component with a `Grid` Component.

Let me know if i should raise a PR for this.

**Comment by hhovsepy** [comment]
@im-Amitto thank you for the research, feel free to send a PR with the solution, just in this case assign this issue to you.
