### ISSUE TITLE
Wrong IstioObject field types

### ISSUE THREAD

**Issue by ferhoyos** [kiali/kiali#6011]
According to https://kubernetes.io/docs/reference/kubernetes-api/common-definitions/object-meta/, there are some field types wrong in Kubernetes Metadata and OwnerReference interfaces:

export interface K8sMetadata {
  name: string;
  generateName?: string;
  namespace?: string;
  selfLink?: string;
  uid?: string;
  resourceVersion?: string;
  generation?: string;  --> It is a number
  creationTimestamp?: string;
  deletionTimestamp?: string;
  deletionGracePeriodSeconds?: string;  --> It is a number
  labels?: { [key: string]: string };
  annotations?: { [key: string]: string };
  ownerReferences?: K8sOwnerReference[]; 
  initializers?: K8sInitializers[];
  finalizers?: string[];
  clusterName?: string;
}
export interface K8sOwnerReference {
  apiVersion?: string; --> It is required
  kind?: string;  --> It is required
  name?: string;  --> It is required
  uid?: string;  --> It is required
  controller?: string;
  blockOwnerDeletion?: string;
}

**Comment by jshaughn** [comment]
@ferhoyos Is this something you want added to the backlog?

**Comment by ferhoyos** [comment]
Yes, but with low priority since it does not affect kiali runtime. I had to fix it on the plugin because some dynamic openshift console sdk got in conflict with these interfaces.
