### ISSUE TITLE
Multicluster - Health calculation for workload/app/svc

### ISSUE THREAD

**Issue by josunect** [kiali/kiali#6026]
Should we include the cluster parameter for the calculation of the health service/app? 

The desired behavior is filter the cluster so we get the metrics for a specific name for a cluster and a namespace, but this is breaking the 
health calculations, at least for cypress tests.

Ref. MC Services List: https://github.com/kiali/kiali/pull/5998#pullrequestreview-1381147997
Ref. https://github.com/kiali/kiali/pull/5990

**Comment by jshaughn** [comment]
If I understand the question, I think health would be cluster-specific.  A service on cluster-A could behave differently than the same service on Cluster-B.  What do others think?

**Comment by leandroberetta** [comment]
I think we can split health in at least two groups:

1. Application/service/workload health
2. Namespace health for applications/services/workloads

If you're ok, we can use this issue for the first group.

Related to the work I'm doing with the overview page and the mesh page, I will require the second one, so I can start working on it. I will create the issue for namespace health.

**Comment by leandroberetta** [comment]
I started working on the issue related to the namespace health: https://github.com/kiali/kiali/issues/6028
