### ISSUE TITLE
Multicluster - Disable writes to remote clusters

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#6033]
Until the frontend supports selecting specific clusters in which to write istio/kube config objects, Kiali needs to disable writes on "remote" clusters.

**Comment by Xunzhuo** [comment]
Assign myself on this sub-task

**Comment by Xunzhuo** [comment]
Hey @nrfox can you point me where the target codes ? I did not take part in the previous multi-cluster support tasks, missed some contexts on it.

For now, we enable writes to remote clusters in default?

**Comment by josunect** [comment]
> Hey @nrfox can you point me where the target codes ? I did not take part in the previous multi-cluster support tasks, missed some contexts on it.
> 
> For now, we enable writes to remote clusters in default?

Hi, @Xunzhuo, I'm working on a similar issue and I think it would be easier to address this changes in this PR, https://github.com/kiali/kiali/pull/6060, if that sounds good. 

Thanks!

**Comment by josunect** [comment]
Closed by https://github.com/kiali/kiali/pull/6060
