### ISSUE TITLE
Multicluster - External controlplane support

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#6036]
Support the external controlplane deployment model.

**Comment by Xunzhuo** [comment]
I can work on it : )

**Comment by nrfox** [comment]
Technically this is supported already as an "experimental" feature but afaik it is only documented on [Kiali's Github page](https://github.com/kiali/kiali#observing-a-remote-cluster) and there's no automated e2e testing for this deployment model.

To move this feature out of experimental, imo we at least need some automated testing around this and documentation on Kiali.io. Testing should be fairly simple since the Kiali binary just needs to be run outside the cluster and some basic validation performed. Running kiali outside the cluster is already supported for dev envs (see https://github.com/kiali/kiali#running-standalone) but iirc that uses a different code path than the "external cluster" setup for whatever reason. That dev env setup should be merged with this one.

**Comment by jshaughn** [comment]
@Xunzhuo , will you do this or should I assign to someone else?

**Comment by nrfox** [comment]
Support has been added by #7168
