### ISSUE TITLE
Multicluster - Token per cluster

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#6037]
Associate a token per user per cluster. Kiali can assume that the user credentials will remain the same across clusters but the backend will still need to authenticate with those credentials to each kube cluster to offer a SSO experience with multicluster.

**Comment by jmazzitelli** [comment]
Here's one place where we would need to update: https://github.com/kiali/kiali/blob/v1.67.0/business/namespaces.go#L268-L269

**Comment by nrfox** [comment]
This may need to be a config option of some kind since it will depend on the platform as to whether or not Kiali should associate a single token across all clusters for a single user or have a separate token for each cluster.
