### ISSUE TITLE
Multicluster - Update details pages with cluster badge and cluster name

### ISSUE THREAD

**Issue by josunect** [kiali/kiali#6059]
The details pages should include the Cluster name in the description: 

- Workloads
- Applications
- Services

The style of the badge should look like: 

![image](https://user-images.githubusercontent.com/49480155/234284412-4e1836b3-8e0c-4e04-bdd6-ca0ed66054bf.png)

Please note, this screenshot is not updated, but the color should be blue: 

![image](https://user-images.githubusercontent.com/49480155/234284878-fed07c93-318f-4995-9460-1633db458819.png)

The cluster name should appear just when you are in Multi Cluster mode. 

Ref. https://github.com/kiali/kiali/issues/5920

**Comment by jshaughn** [comment]
I think perhaps the Cluster badge should be "CL" as opposed to "C".  We already have a "C" for Container.  Or, we could make Container "CO".  I have seen both of these badges on the same page, so it can be a little bit confusing.

**Comment by josunect** [comment]
I thought in leave just the "C" to keep consistency with what it is in ACM. For the other side, I think it could be confusing if both are using the same color, also...
