### ISSUE TITLE
Header Authentication using NGINX Reverse Proxy.

### ISSUE THREAD

**Issue by shailshroff** [kiali/kiali#6061]
Once configured with header authentication method, token passed in url is not passed to subsequent calls to `/api/authenticate`

Kiali Configuration:
```
strategy: header
header:
  name: Authorization
  prefix: Bearer
```

Ingress Nginx Annotations:
```
  nginx.ingress.kubernetes.io/configuration-snippet: |
    proxy_pass_header Authorization;
    proxy_set_header Authorization "Bearer $arg_token";
```
Request URL:
https://hello-world.info/kiali/console?token=<value>

First Request:
![image](https://user-images.githubusercontent.com/97452978/234290624-efd255b1-edaa-4f02-bc9f-3c90c4d7a941.png)

After manual authentication:
https://hello-world.info/kiali/api/authenticate?token=<value>
![image](https://user-images.githubusercontent.com/97452978/234291913-d4e82d62-4137-41c0-a888-0bf7880bf4b2.png)

Couldn't find any documentation in [Kiali Docs](https://kiali.io/docs/configuration/authentication/header/)

Setup:
Kubernetes version - 1.22.3
Minikube with Ingress Addon.
Kiali configuration file from istio-1.15.2

**Comment by jmazzitelli** [comment]
@shailshroff can you post the relevant portions of the server pod logs that show the error and logs surrounding it?

The header auth strategy / reverse proxy support  was originally added by a community member (see PR https://github.com/kiali/kiali/pull/3568) ... Perhaps @mlbiam knows if this is really a bug or if it is a misconfiguration.

**Comment by mlbiam** [comment]
Been a while but from what I remember the only endpoint that cares about the `Authorization` header is the `/api/authenticate` because after that there's a cookie that's used for all API security.  This is all in the javascript though.  Is the cookie not making it back-and-forth?

**Comment by jshaughn** [comment]
@shailshroff A couple of questions for you above ^^^.

**Comment by shailshroff** [comment]
Hi @jmazzitelli, @jshaughn  and @mlbiam,
Sorry for the delayed response.
Logs are available [here](https://pastebin.com/yCmEYbu6).
It does show some error logs like `AES Cookie is missing.`
I've also added values from Local Storage and Cookies from browser.

**Comment by jmazzitelli** [comment]
> It does show some error logs like `AES Cookie is missing.`

sounds like the proxy isn't forwarding the cookie that contains the aes token.

**Comment by shailshroff** [comment]
I think so yes, that might be the issue.

You can find the logs [here](https://gist.github.com/shailshroff/2942b323de762c4e47822ce3193e0ec5).

**Comment by jshaughn** [comment]
Closing as stale, re-open as needed.
