### ISSUE TITLE
Fix tests in Istio Config Wizard failing on subsequent runs

### ISSUE THREAD

**Issue by matejnesuta** [kiali/kiali#6073]
This issue is related [this featureFile](https://github.com/kiali/kiali/blob/master/frontend/cypress/integration/featureFiles/wizard_istio_config.feature) only, as far as I know. The issue is that there are multiple gateway and service objects created and these do not get deleted after the test run. This does not affect the CI or the OCP pipelines, because the demoapps are usually deleted altogether right after the whole suite finishes. However when you don't reinstall the demoapps, half of the test might break and the only solution right now is to delete the objects manually, either in the Kiali UI or in the terminal. This is especially annoying when debugging/creating new tests locally.

Affected tests:
[Scenario: Create a K8s Gateway scenario](https://github.com/kiali/kiali/blob/53a52ea68bafcaef827b8e3b0d077fd0ca335429/frontend/cypress/integration/featureFiles/wizard_istio_config.feature#L14)
[Scenario: Create a Gateway scenario](https://github.com/kiali/kiali/blob/53a52ea68bafcaef827b8e3b0d077fd0ca335429/frontend/cypress/integration/featureFiles/wizard_istio_config.feature#L44)
[Scenario: Create a Gateway with TLS](https://github.com/kiali/kiali/blob/53a52ea68bafcaef827b8e3b0d077fd0ca335429/frontend/cypress/integration/featureFiles/wizard_istio_config.feature#L124)
[Scenario: Create a ServiceEntry without ports specified](https://github.com/kiali/kiali/blob/53a52ea68bafcaef827b8e3b0d077fd0ca335429/frontend/cypress/integration/featureFiles/wizard_istio_config.feature#L162)
[Scenario: Create a ServiceEntry with ports specified](https://github.com/kiali/kiali/blob/53a52ea68bafcaef827b8e3b0d077fd0ca335429/frontend/cypress/integration/featureFiles/wizard_istio_config.feature#L188)
[Scenario: Create multiple K8s Gateways with colliding hostnames and port combinations and check for a reference](https://github.com/kiali/kiali/blob/53a52ea68bafcaef827b8e3b0d077fd0ca335429/frontend/cypress/integration/featureFiles/wizard_istio_config.feature#L219)

Some of these tests only need a quick teardown, however there are also 2 tests, which are already dependent on these tests. These 2 tests are expecting the gateway object to be already created. They don't fail because of the issue already mentioned, but it would be nice to reworked them a little in the process as well. 

These are:
[Scenario: Create a Gateway with duplicate name](https://github.com/kiali/kiali/blob/53a52ea68bafcaef827b8e3b0d077fd0ca335429/frontend/cypress/integration/featureFiles/wizard_istio_config.feature#L94), which has dependency on the "Create a Gateway scenario" test
[Scenario: Delete one of the K8s Gateways and check that the reference is removed](https://github.com/kiali/kiali/blob/53a52ea68bafcaef827b8e3b0d077fd0ca335429/frontend/cypress/integration/featureFiles/wizard_istio_config.feature#L251), which has dependency on the "Create multiple K8s Gateways" test

This means that most of the tests need a simple teardown, while the 2 tests with dependencies need more complex approach.

**Comment by matejnesuta** [comment]
@ScriptingShrimp

**Comment by jshaughn** [comment]
Maybe the dependent tests can just be merged into the tests they depend on.
