### ISSUE TITLE
Improve Grafana integration documentation

### ISSUE THREAD

**Issue by leandroberetta** [kiali/kiali#6082]
There is a need to improve the Grafana integration documentation. We need more clarity on when the "View in Grafana" link appears and what needs to be configured for that to happen, more discussion in https://github.com/kiali/kiali/issues/5988

**Comment by 1vinodsingh1** [comment]
Thanks for creating the issue. Yes, we need documentation improvement to add grafana dashboard details in Kiali configmap.

**Comment by jmazzitelli** [comment]
> to add grafana dashboard details in Kiali configmap.

Just to be clear - this isn't talking about documenting how to add things to the Kiali *ConfigMap*. Users should NEVER modify the resources directly created by the operator (or by the helm chart if installing via helm) including the Kiali ConfigMap. The ConfigMap should be off limits - see https://kiali.io/docs/configuration/kialis.kiali.io/#.spec where it says, `All of these settings will be stored in the Kiali ConfigMap. Do not modify the ConfigMap; it will be managed by the Kiali Operator. Only modify the Kiali CR when you want to change a configuration setting.`.

To make these changes, you add the configuration to the Kiali CR from which the Kiali Operator will determine what needs to get into the ConfigMap. For the helm chart, it is configuring the templates via either `--set` options or values.yaml.
