### ISSUE TITLE
Error getting istio-cni-config configmap: configmaps "istio-cni-config" not found

### ISSUE THREAD

**Issue by mdfaizsiddiqui** [kiali/kiali#6111]
Hey 👋 

Recently I see this error popping in for kiali pods -

```
Error getting istio-cni-config configmap: configmaps "istio-cni-config" not found
```

Probably related to the change made on this PR - https://github.com/kiali/kiali/pull/5952

My environment details and FYI I'm not using istio-cni or ambient mesh -

<img width="558" alt="image" src="https://user-images.githubusercontent.com/65137316/236489853-894f4f9e-9582-49b2-93c1-7bba345037b4.png">

**Comment by josunect** [comment]
Thanks, @mdfaizsiddiqui 

Thanks right, that message should have a different log level. It was updated to debug in the PR: https://github.com/kiali/kiali/pull/6104

**Comment by jmazzitelli** [comment]
@josunect has the correct answer. closing.
