### ISSUE TITLE
Support K8s native sidecars

### ISSUE THREAD

**Issue by howardjohn** [kiali/kiali#6130]
Kubernetes is adding support for native sidecars. I have implemented support in Istio in https://github.com/istio/istio/pull/44835, pending upstream merging.

I suspect Kiali will need changes - a few of our tools did as they always expected the sidecar to be a `container` but its now an `initContainer`.

If you'd like to try it today you can pull down my PR. Note youll also need a custom `kind` image and FeatureGate, which are both in the PR.

**Comment by howardjohn** [comment]
Yes. K8s then treats it differently and resolves a lot of lifecycle issues like pod startup and shutdown ordering, connectivity of other init containers, Job termination, etc. But from kiali perspective I would think only moving to init container matters

**Comment by hhovsepy** [comment]
Kiali will support sidecars in initContainer from Kiali v1.75 release.
