### ISSUE TITLE
UI - Styling in the Overview page in the UI for cards with long namespace names pushes out kebab menu into adjacent card

### ISSUE THREAD

**Issue by msdolbey** [kiali/kiali#6133]
In the Kiali UI
On the Overview page
If you have some namespaces that are relatively long (for example: `capi-kubeadm-control-plane-system` or something like that)
The kebab menu action button for that card
Is pushed out and flows into the adjacent card.

*Browser version* – Most recent chrome

*App area* – Overview page in the Kiali UI

*Version information* – I believe this is image: quay.io/kiali/kiali:v1.57.1

*Expected Behavior*
The kebab menu button will stay in the card that it is for

*Actual behavior* 
The kebab menu button is getting pushed out to the left if the namespaces are long

_Steps to Reproduce_
- Install Kiali
- Have some long namespaces that you're going to be looking at in Kiali
- View the overview page in the UI

**Screen capture:
https://github.com/kiali/kiali/assets/5703649/435c3bad-135f-4ae2-9cc8-a2d371b8db6f

I'm not familiar with the styling all that much for this project, but I did see that if I added this locally it seemed to address this issue (though it may not be the best solution, just something I've found):

```css

.pf-c-title.pf-m-lg {
    display: flex;
    overflow: hidden;
    margin-right: -200px;
}
```

**Comment by jshaughn** [comment]
Thanks for the report, @msdolbey!
