### ISSUE TITLE
edge colors get "stuck" as yellow / red after service health recovers

### ISSUE THREAD

**Issue by rsalmond** [kiali/kiali#6138]
I ran a test which generated 500's and correctly saw the edges between the ingressgateway and the faulty service displayed as red. I then stopped the traffic that produced 500's and kept only 2xx traffic going to through, and while the side panel correctly shows 100% OK the edges between the services and workloads involved did not recover.

![image](https://github.com/kiali/kiali/assets/4367945/3dcdb3ff-1f5f-4c3d-8757-174b16d38739)

Prom data for the same time frame:

<img width="1254" alt="image" src="https://github.com/kiali/kiali/assets/4367945/a1e37776-d8be-4bea-ab54-5f648a18c8f0">

Pressing the Kiali reload button in the upper right didn't have any impact but reload the whole page immediately produces green edges.

![image](https://github.com/kiali/kiali/assets/4367945/3741f605-072f-4906-91fb-2c4704ad78a4)

**Comment by jshaughn** [comment]
Hmmm, that doesn't sound good.  Will try to reproduce.

**Comment by jmazzitelli** [comment]
@rsalmond can you provide some replication steps - specifically, did you create any fault injection rules that you can share so we can try to replicate what you are seeing?

**Comment by jmazzitelli** [comment]
I can pretty easily reproduce this. Steps to reproduce:

1. Install bookinfo demo, using the kiali traffic generator to push requests every second: `hack/istio/install-bookinfo-demo.sh -c kubectl -tg`
2. Get the graph to show all green so we know its all working
3. Delete the review pods: `kubectl delete pods -n bookinfo -l app=reviews`
4. See the edges go red, as expected.
5. Check the review pods are back up:
```
$ kubectl get pods -n bookinfo
NAME                             READY   STATUS    RESTARTS   AGE
details-v1-6997d94bb9-x8298      2/2     Running   0          30m
kiali-traffic-generator-hfsrb    2/2     Running   0          26m
productpage-v1-d4f8dfd97-qzzp8   2/2     Running   0          30m
ratings-v1-b8f8fcf49-4hlw8       2/2     Running   0          30m
reviews-v1-5896f547f5-h5r55      2/2     Running   0          4m2s
reviews-v2-5d99885bc9-zwdpf      2/2     Running   0          4m2s
reviews-v3-589cb4d56c-2djm8      2/2     Running   0          4m2s
```
6. Notice the graph is still showing unhealthy edges, even though you can see the review pods have been up for several minutes (side panel shows everything is ok):
![image](https://github.com/kiali/kiali/assets/2029470/4c043a49-eb7e-47b7-9e22-77b0fcec791e)
7. Hit the refresh button in the top right - does nothing to affect the unhealthy edges.
8. Refresh the entire page via F5 - page refreshes and graph immediately goes green

**Comment by jmazzitelli** [comment]
Here's the [graph json](https://github.com/kiali/kiali/files/11510772/graph.json.txt) for this graph:

![image](https://github.com/kiali/kiali/assets/2029470/31d0def4-b2e8-4b83-ba5c-eb696d50a2c3)

Here's some review edges:

```json
      {
        "data": {
          "id": "406d2cca8f1dde85710e56914854db0f",
          "source": "6d56f1d333f1df5be1332a09c0866dd7",
          "target": "582a5e548c2511d13bc0e15cdeacf25f",
          "traffic": {
            "protocol": "http",
            "rates": {
              "http": "0.33",
              "httpPercentReq": "32.6"
            },
            "responses": {
              "200": {
                "flags": {
                  "-": "100.0"
                },
                "hosts": {
                  "reviews.bookinfo.svc.cluster.local": "100.0"
                }
              }
            }
          }
        }
      },
      {
        "data": {
          "id": "311226f62878ee93e501c39e0f2f7e7a",
          "source": "6d56f1d333f1df5be1332a09c0866dd7",
          "target": "b2f57800ff71b31035a226dca93d7ec0",
          "traffic": {
            "protocol": "http",
            "rates": {
              "http": "0.36",
              "httpPercentReq": "34.8"
            },
            "responses": {
              "200": {
                "flags": {
                  "-": "100.0"
                },
                "hosts": {
                  "reviews.bookinfo.svc.cluster.local": "100.0"
                }
              }
            }
          }
        }
      },
      {
        "data": {
          "id": "f26f9372c4ac32141a508f614fd02e65",
          "source": "6d56f1d333f1df5be1332a09c0866dd7",
          "target": "be64cf1064d2d8d853979c25ab5d6dfe",
          "traffic": {
            "protocol": "http",
            "rates": {
              "http": "0.33",
              "httpPercentReq": "32.6"
            },
            "responses": {
              "200": {
                "flags": {
                  "-": "100.0"
                },
                "hosts": {
                  "reviews.bookinfo.svc.cluster.local": "100.0"
                }
              }
            }
          }
        }
      },
```

**Comment by jmazzitelli** [comment]
@rsalmond thanks for the report - this should be fixed in the next release. PR with the fix is here: https://github.com/kiali/kiali/pull/6165
