### ISSUE TITLE
Failed to update kiali-server helm chart value view_only_mode in standalone Kiali installation

### ISSUE THREAD

**Issue by ayaranga** [kiali/kiali#6139]
Once Kiali is installed using kiali-server helm chart, if we want to update the helm chart value deployment.view_only_mode, the helm upgrade fails with the below error as Kubernetes role bindings are immutable:
```
$ helm install --set kiali_feature_flags.clustering.autodetect_secrets.enabled=false --set auth.strategy=anonymous --namespace istio-system kiali-server ./kiali-server
NAME: kiali-server
LAST DEPLOYED: Thu May 11 08:10:25 2023
NAMESPACE: istio-system
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Welcome to Kiali! For more details on Kiali, see: https://kiali.io/

The Kiali Server [v1.67.0] has been installed in namespace [istio-system]. It will be ready soon.

(Helm: Chart=[kiali-server], Release=[kiali-server], Version=[1.67.0])

$ helm get values --namespace istio-system kiali-server --all | grep -i view
  view_only_mode: false

$ helm upgrade --set kiali_feature_flags.clustering.autodetect_secrets.enabled=false --set auth.strategy=anonymous --set deployment.view_only_mode=true --namespace istio-system kiali-server ./kiali-server/
Error: UPGRADE FAILED: cannot patch "kiali" with kind ClusterRoleBinding: ClusterRoleBinding.rbac.authorization.k8s.io "kiali" is invalid: roleRef: Invalid value: rbac.RoleRef{APIGroup:"rbac.authorization.k8s.io", Kind:"ClusterRole", Name:"kiali-viewer"}: cannot change roleRef
```

The proposal is to change the clusterrolebinding name based on the view_only_mode configuration. With this, the view_only_mode configuration can be successfully updated after the installation as well.
```
--- a/kiali-server/templates/rolebinding.yaml
+++ b/kiali-server/templates/rolebinding.yaml
@@ -2,7 +2,11 @@
 apiVersion: rbac.authorization.k8s.io/v1
 kind: ClusterRoleBinding
 metadata:
+  {{- if or (.Values.deployment.view_only_mode) (ne .Values.auth.strategy "anonymous") }}
+  name: {{ include "kiali-server.fullname" . }}-viewer
+  {{- else }}
   name: {{ include "kiali-server.fullname" . }}
+  {{- end }}
   labels:
     {{- include "kiali-server.labels" . | nindent 4 }}
 roleRef:
```

**Comment by jmazzitelli** [comment]
There is an existing workaround for this issue - simply uninstall and then reinstall Kiali Server with the desired deployment view_only_mode value.

Question - what happens if you do the suggested solution, but then attempt to uninstall the Kiali Server using helm uninstall?

I haven't tried but it seems like this might now require the user to be forced to know (and explicitly specify on the command line) the value of the deployment view only mode. In other words, if I want to uninstall Kiali, I have to know what value this setting was the last time I updated the server... otherwise, how does it know to delete the clusterrolebinding with the name "kiali" or "kiali-viewer"?

**Comment by ayaranga** [comment]
@jmazzitelli Thanks for looking at this issue. I would like to contribute the above proposed fix to kiali-server helm chart. Will the current label suffice to make the contribution? As per https://github.com/kiali/kiali/blob/master/CONTRIBUTING.md, I see that the issue should be added to the backlog before contributing. Should I wait until the issue is added to the backlog?

**Comment by jmazzitelli** [comment]
@ayaranga you can submit a PR. No need to wait.
