### ISSUE TITLE
When kiosk=console is set, the jump link in the page does not work properly

### ISSUE THREAD

**Issue by pantianying** [kiali/kiali#6159]
version：1.57

<img width="1440" alt="截屏2023-05-18 14 54 53" src="https://github.com/kiali/kiali/assets/20589945/f6de3c76-602f-40f2-bf75-4d3f8626b3c6">

**Comment by pantianying** [comment]
uri:   /console/overview?duration=60&refresh=900000&kiosk=console

**Comment by hhovsepy** [comment]
Hi @pantianying,
the param 'kiosk=console' is used only in OpenShift Console plugin, where the redirection of links is done,
for regular kiosk mode the 'kiosk=true' param should be used.
Can you try with "kiosk=true" and see if your issue is resolved?

**Comment by pantianying** [comment]
> Hi @pantianying,
> the param 'kiosk=console' is used only in OpenShift Console plugin, where the redirection of links is done,
> for regular kiosk mode the 'kiosk=true' param should be used.
> Can you try with "kiosk=true" and see if your issue is resolved?

ths for your answer , it works
