### ISSUE TITLE
need to document the auth.openshift settings

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#6176]
There are some auth.openshift settings that were added last year (see [PR 5021](https://github.com/kiali/kiali/pull/5021)) that never got documented. If someone puts them in their Kiali CR and tries to [validate their CR with our validation tool](https://kiali.io/docs/configuration/kialis.kiali.io/#validating-your-kiali-cr), it will fail. Also, users have no documentation for these values.

So we need to document these.

https://github.com/kiali/kiali/blob/v1.67.0/config/config.go#L333-L338 :
```go
type OpenShiftConfig struct {
	AuthTimeout    int    `yaml:"auth_timeout,omitempty"`
	ClientIdPrefix string `yaml:"client_id_prefix,omitempty"`
	ClientId       string `yaml:"client_id,omitempty"`
	ServerPrefix   string `yaml:"server_prefix,omitempty"`
	UseSystemCA    bool   `yaml:"use_system_ca,omitempty"`
	CustomCA       string `yaml:"custom_ca,omitempty"`
}
```

https://github.com/kiali/kiali-operator/blob/v1.67.0/crd-docs/cr/kiali.io_v1alpha1_kiali.yaml#L52-L56 :

```yaml
    openshift:
      auth_timeout: 10
      client_id_prefix: "kiali"
      #token_inactivity_timeout:
      #token_max_age:
```

Those four are documented in the CRD [here](https://github.com/kiali/kiali-operator/blob/v1.67.0/crd-docs/crd/kiali.io_kialis.yaml#L183-L198) but 4 from config.go are not (`ClientId`, `ServerPrefix`, `UseSystemCA`, `CustomCA`)

We need to document these missing ones in the CRD and CR example. Also, these docs are incorrect: https://kiali.io/docs/configuration/authentication/openshift/ (notice it says, `The openshift strategy doesn’t have any additional configuration.`)

(I noticed all of this when trying to figure out if openshift auth could be configured to workaround this [bug](https://issues.redhat.com/browse/OSSM-3993)).

**Comment by jmazzitelli** [comment]
@israel-hdez @libesz could I ask if you two could comment here and give a little burb on these four settings that are missing in the docs? I'll update the Kiali docs where it needs to be, but I would just like to hear it from you what these do since you both were involved in adding these new features last year (see https://github.com/kiali/kiali/pull/5021), but we forgot to document them and put them in our CRD schema so the validation tool will work with them.

Here's what I *think* they do:

* `ClientID`: (string, default is unset) If this defined, client_id_prefix is ignored. This is the string used by OAuth to identify the client.
* `ServerPrefix`: (string, default is https://kubernetes.default.svc/) Not really a server prefix, more like a URL-prefix because it contains the protocol and full hostname. This is the https://hostname portion of the URL used to communicate with OpenShift during OAuth handshake.
* `UseSystemCA`: (boolean, default is false) When false, the serviceaccount CA is used during OpenShift OAuth. When true, the system CA is used. This is ignored if `CustomCA` is specified.
* `CustomCA`: (string, default is unset) When set, this is the base64-encoded CA cert used for OpenShift OAuth.

**Comment by jmazzitelli** [comment]
PRs:
* https://github.com/kiali/kiali-operator/pull/648
* https://github.com/kiali/kiali.io/pull/656

**Comment by nrfox** [comment]
> IMHO, I think it is still OK to left those settings as undocumented because Kiali is most-likely still not stable under such configuration (lots of errors in the UI after login), _unless_ some recent work (uhm, multi-cluster?) has made it stable.

That's not a configuration we've targeted or tested for the multi-cluster work so it's definitely not stable but we're probably closer to supporting that deployment model. One could just provide Kiali with a remote cluster secret and maybe it would just work if all the auth knobs already work and are supported. Like I said though, that's not stable or supported yet but it could be added to the multi-cluster roadmap to run an external Kiali.

**Comment by israel-hdez** [comment]
> That's not a configuration we've targeted or tested for the multi-cluster work so it's definitely not stable but we're probably closer to supporting that deployment model.

IIRC, the original goal was to provide Kiali as a managed service. And that was the motivation to run Kiali outside the user-cluster, so that they don't do any hacking to it. It is not multi-cluster, but smells like it :slightly_smiling_face: 

Mentioning it for you to keep it in mind and choose if it somehow fits on the M/C work, or just keep this aside.

**Comment by jmazzitelli** [comment]
I hate half-baked features that we leave rotting on the vine. Can we just remove some of this? This is just technical debt that gets in the way when we are debugging things and trying to fix things.

If things don't work, and no one is fixing it so it becomes stable, then we should just get rid of it.

**Comment by israel-hdez** [comment]
> Can we just remove some of this? This is just technical debt
> 

Why not? I thought about suggesting it.

Maybe nothing of this is useful?. If so, just do `git revert` to the merge (if it works).

**Comment by libesz** [comment]
Hey! Some updates from my side as I brought this use-case and implementation last year. The meaning of the parameters are correct as @israel-hdez [described](https://github.com/kiali/kiali/issues/6176#issuecomment-1559731438).
Yes, the use-case is to be able to run Kiali outside the observed cluster, as a managed service i.e. with Hypershift installed Openshift clusters. Istio already supports the external control-plane, so kiali would follow with this change.

Unfortunately the managed service that I worked on (that would use these new kiali params) never made it to GA/Production, that's why I am not submitting any further issues/PRs.
I believe the new parameters are generic enough to be part more, similar use-cases in the future, but I don't have any up-to-date information what would be missing besides the auth part.
I am happy to help reviewing the missing docs, but I am also fine to just remove these for now.

**Comment by jmazzitelli** [comment]
I can see the CA stuff maybe having  some generic utility. We'll have to think about this some more.

**Comment by israel-hdez** [comment]
> I can see the CA stuff maybe having some generic utility. We'll have to think about this some more.

Yes and no. This is constrained to requests to the ClusterAPI. If Kiali out-of-cluster is  not going to be a supported config, I'm not sure it is really useful to keep. Some work may be needed to make this generic and be applicable to other HTTP requests.

For M/C you may already be getting the CAs of remote clusters via kubeconfig secrets or some other means, to properly check the secure connection (@nrfox may confirm).

Besides that, Kiali don't do a lot of connections to other things. Maybe it is connections to Prometheus, Jaeger, Grafana, OpenID server, ¿etc? But, I think all these have their own CA configurations.

The truly generic approach was requested in #1675. It was closed by confusion, but the reporter user was happy with #4050 and wasn't reopened. So, it looks like it didn't gain traction.

Just commenting for a broader view around CAs.

**Comment by jmazzitelli** [comment]
OK, since this is an incomplete and stale feature, I will close my suggested PR to update the public docs. We'll want to consider reverting some or all of PR https://github.com/kiali/kiali/pull/5021
