### ISSUE TITLE
Multicluster - Marketing/Blog/Demo materials

### ISSUE THREAD

**Issue by josunect** [kiali/kiali#6182]
- Demos:
  - [x] How to set up Multi cluster https://github.com/kiali/kiali/issues/6236
  - [ ] ...
- Blog post 
  - [x] Multi cluster support in Kiali https://github.com/kiali/kiali/issues/6214
  - [ ] ...

Graphics: 
https://docs.google.com/presentation/d/1_JpK4ncl0XsN_1AslNWZb8504BF3y_plhGogeCRWE-Q

Ref. #5618

**Comment by leandroberetta** [comment]
Closing as complete we have demo, videos and docs. We should tweet the videos with some cadence.
