### ISSUE TITLE
Graph - hiding an entire namespace or cluster keeps the namespace/boxes

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#6184]
When you use the graph hide feature to hide an entire namespace or cluster the app/workload/service nodes disappear but empty namespace/cluster boxes remain.

![empty_boxes](https://github.com/kiali/kiali/assets/6226732/293856ba-54c4-4319-a6d4-668a1836e7ca)

**Comment by jshaughn** [comment]
Sorry, @nrfox I thought I had assigned myself to this because I knew where the fix had to go.  I reassigned to myself.
