### ISSUE TITLE
Multi-cluster graph - error when user lacks access to remote cluster

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#6185]
Given two clusters, `east` and `west`, with a `bookinfo` namespace in both and a user that has access to `bookinfo.east` but not `bookinfo.west`, Kiali sometimes shows the graph and sometimes shows an access error. There seems to be some access check that is performed but the exact cluster that it is performed against varies. The graph should only show namespaces to the user that they have access to but should not throw an error when that namespace exists on both clusters.

![namespace_access_error](https://github.com/kiali/kiali/assets/6226732/021b2905-400f-45f7-bb05-2e313585653c)

**Comment by nrfox** [comment]
The minigraphs suffer from the same issue.

**Comment by jshaughn** [comment]
Well that's not good.  Definitely something to fix for MC-alpha.
