### ISSUE TITLE
Multicluster - Unknown cluster in traffic

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#6202]
In bookinfo's 'kiali-traffic-generator' workload Traffic tab, the Cluster column has 'unknown' value.
![Screenshot from 2023-05-25 10-49-10](https://github.com/kiali/kiali/assets/604313/10e45b5e-de33-426f-a757-debc699f65b8)

**Comment by jshaughn** [comment]
@hhovsepy I think this may be correct behavior for the implicit PassthroughCluster.  It should probably be the local cluster but I don't believe it's set that way in Telemetry.  The same would be true for traffic to Unknown or BlackHoleCluster.

**Comment by jshaughn** [comment]
I would probably just leave it as "unknown", because it will be shown as "unknown" in the graph.  I don't like an empty value because then it just looks like it may be a bug, and I'm not sure a dash or anything else is any better than "unknown".
