### ISSUE TITLE
Unable to access kiali on Kubernetes by LoadBalancer

### ISSUE THREAD

**Issue by sh-miyoshi** [kiali/kiali#621]
I deploy kiali by the command `make k8s-deploy` to my kubernetes cluster.

But, I can access to kiali by only `type: NodePort`
*) Please see (line 17 at deploy/kubernetes/kiali.yaml)

I want to access by `type: LoadBalancer` or `type: ClusterIP`(because of accessing by Ingress)

**Comment by lucasponce** [comment]
Hi @sh-miyoshi 
I guess you would need to expose the kiali service from istio-system with your LoadBalancer.

I haven't tried as I use locally a route in openshift, but did you give a try following the steps ?

https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/

Any problem after that ?
Thanks

**Comment by sh-miyoshi** [comment]
Hi @lucasponce , Thanks your comment.
I can expose by LoadBalancer.
But, I have to change native yaml(like following) in order to expose by LoadBalancer.

```
# cd /path/to/kiali
# vim deploy/kubernetes/kiali.yaml
   *) edit type: NodePort -> type: LoadBalancer
# make k8s-deploy
```

I want to use LoadBalancer without changing yaml.
(e.g. use environment valiable, or use helm)

Example 1. (use environment valiable)
```
# cd /path/to/kiali
# SERVICE_TYPE=LoadBalancer make k8s-deploy
``` 
Example 2. (use helm)
```
# cd /path/to/kiali
# vi values.yaml
# helm install ...
```

**Comment by lucasponce** [comment]
@sh-miyoshi I will cc @jmazzitelli and @gbaufake to take a look to this, perhaps this is something it can be parametrized in the helm install process.

**Comment by xeor** [comment]
Any progress here? Still looks like `NodePort` is hardcoded.. I want to use `ClusterIP` and take care of the exposure myself

**Comment by jmazzitelli** [comment]
We've recently converted over to the new Kiali Operator. Nothing has been done, however, to change the  k8s deployment. See: https://github.com/kiali/kiali/blob/master/operator/roles/kiali-deploy/templates/kubernetes/service.yaml#L10

We can make this configurable. I just created an enhancement request: https://issues.jboss.org/browse/KIALI-2723

**Comment by jmazzitelli** [comment]
feel free to review/test: https://github.com/kiali/kiali/pull/1013

**Comment by jmazzitelli** [comment]
Support for this and more has been added. You can tell the operator what service type to use, as well as provide additional service yaml to support other types.. see the docs on these two settings here:

service type: https://github.com/kiali/kiali/blob/master/operator/deploy/kiali/kiali_cr.yaml#L129-L132
additional service yaml: https://github.com/kiali/kiali/blob/master/operator/deploy/kiali/kiali_cr.yaml#L93-L100
