### ISSUE TITLE
Update Kiali to build with Go 1.20

### ISSUE THREAD

**Issue by aljesusg** [kiali/kiali#6218]
Changes:

- Update the build scripts to specify Go 1.20 as the target version.
- Test the build process and application functionality with Go 1.20.
- have tested these changes on multiple platforms and confirmed that Kiali builds and works as expected with Go 1.20

Related issues:

- https://go.dev/issue/57855
- https://pkg.go.dev/vuln/GO-2023-1571
- https://groups.google.com/g/golang-announce/c/V0aBFqaFs_E

**Comment by jshaughn** [comment]
All PRs are merged.
