### ISSUE TITLE
Cannot load the graph: <component> is forbidden: User "system:serviceaccount:istio-system:kiali-service-account" cannot list <component> in the namespace "<namespace>"

### ISSUE THREAD

**Issue by geekosphere-net** [kiali/kiali#623]
**Describe the bug**
Followed instructions to install Minikube, Istio, Kiali and then used kiali [_hack_ ](https://github.com/kiali/kiali/blob/master/hack/istio/install-bookinfo-demo.sh) script to install the Bookinfo demo app into the `bookinfo` namespace. Everything seems to work, I am able to submit requests to the `productpage` and see the service graph created in **Kiali**.
Navigate to the `Services` tab and click on any service and then see this error:
```
Could not fetch Service Details., Error: [ replicasets.apps is forbidden: User "system:serviceaccount:istio-system:kiali-service-account" cannot list replicasets.apps in the namespace "bookinfo" ]
```
![kialierror](https://user-images.githubusercontent.com/7292206/47921481-12adca80-de8b-11e8-8e9b-9c8f565c8634.png)

**Versions used**
From the Kiali About menu:
```
kiali-ui 0.9.0 (da1f565257a249dd6f483d99e62a6cb2ca667765)
kiali v0.9.0 (b11bc05013df2457e479eb381c52e924e27db19d)
Components
  Istio 1.0.3
  Prometheus 2.3.1
  Kubernetes v1.10.0
```
Other components 
```
% minikube version
minikube version: v0.30.0
% helm version
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
% kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:54:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**To Reproduce**

0. Start with empty CentOS VM `centos-release-7-3.1611.el7.centos.x86_64`
1. Use attached script [1_startMiniKube.sh.txt](https://github.com/kiali/kiali/files/2542994/1_startMiniKube.sh.txt) to install minikube, kubectl and helm
2. Add helm service account `kubectl apply -f install/kubernetes/helm/helm-service-account.yaml`
3. Install Istio `helm install install/kubernetes/helm/istio --name istio --namespace istio-system --set gateways.istio-ingressgateway.type=NodePort --set gateways.istio-egressgateway.type=NodePort --set grafana.enabled=true --set servicegraph.enabled=true --set tracing.enabled=true --set kiali.enabled=true`
4. Updated the services for Kiali, Prometheus, Jaeger and Grafana in `istio-system` from `CluserIP` to `NodePort` so I could access directly 
5. Install the Bookinfo demo `./install-bookinfo-demo.sh --istio-dir ~/istio-1.0.3 --client-exe kubectl --namespace bookinfo`
6. Convert the `productpage` service from `ClusterIP` to `NodePort`
6. Generated traffic with `curl -ski http://minikube.host.com:30006/productpage` in a loop
8. Open the Kiali Console, click on `Graph` tab to see a cool graph of the bookinfo app
9. click on `Applications` tab and see nothing
9. click on `Workloads` tab and see nothing
9. click on `Services` tab and see a list of services
9. click on the `productpage` service 
9. error pops up 

**Expected behavior**
View details of services

**Comments**
Guessing this is a _RBAC_ issue and have tried playing with the `ClusterRoleBindings` but with no luck. 

Thanks in advance!!

**Comment by victorboissiere** [comment]
Well it has already been fixed in the helm chart of the Istio master branch 4 days ago:
https://github.com/istio/istio/commit/3bcf7514c5c948b964447af6aa9a88f770c4b0a1#diff-c8d606f98a06073a3c2123478fadd85c

**Comment by jmazzitelli** [comment]
This is in master and has been for a couple months: https://github.com/kiali/kiali/commit/392f55d32b1770bed0990d6cf54d7e4ee3910294#diff-308d3815e1e602e6fc01d05f671ea344

We only recently realized we had to fix the helm charts - it went into upstream master and release-1.1 branch last week - there is a PR for the istio release 1.0 branch but has not been merged yet.

**Comment by jmazzitelli** [comment]
the helm charts are fixed in these PRs upstream:
master: https://github.com/istio/istio/pull/9444
release-1.1: https://github.com/istio/istio/pull/9608
release-1.0 (not merged yet): https://github.com/istio/istio/pull/9718

**Comment by jmazzitelli** [comment]
Here's the command to workaround the problem (run this after Istio and Kiali v0.9 are installed):

```
curl -s https://raw.githubusercontent.com/kiali/kiali/v0.9/deploy/kubernetes/kiali.yaml | tail -n +109 | head -n 71 | VERSION_LABEL=v0.9 envsubst | kubectl apply -n istio-system -f -
```

**Comment by geekosphere-net** [comment]
@jmazzitelli I applied that `ClusterRole` update and it resolved my issue, thanks!!

**Comment by aishvaryaps** [comment]
I have Bookinfo application installed in default namespace. I see bookinfo graph in kiali. When I install bookinfo application in another namespace (eg: bookinfo). I dont see graphs. where in kaili i need to mention namespce ??

**Comment by jmazzitelli** [comment]
> I have Bookinfo application installed in default namespace. I see bookinfo graph in kiali. When I install bookinfo application in another namespace (eg: bookinfo). I dont see graphs. where in kaili i need to mention namespce ??

Is this related at all to this closed issue? Sounds like a user question unrelated to this issue - you should ask user questions either on istio slack or the [kiali-users Google groups mailing list ](https://groups.google.com/forum/#!forum/kiali-users) or on the #kiali IRC freenode chat room.
