### ISSUE TITLE
[Multicluster] provide links to external Kialis without requiring istio secrets

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#6243]
Today Kialis in "single cluster" mode require secrets to create links to external kialis. This is effectively putting the Kiali instance in "multi cluster" mode. There needs to be a way to for Kiali to generate links to external Kialis without requiring access to external clusters. This can be a simple as adding a config value that Kiali would use to generate these links. Something like `externalKialis: {"name": ..., "url": ...}`.

**Comment by jshaughn** [comment]
That seems reasonable.  Did the former secrets do anything for us other than establish the link?  Users would still have to log into the remote Kiali, etc, right?

**Comment by jmazzitelli** [comment]
> Did the former secrets do anything for us other than establish the link?

AFAIK, that's all the old secrets did for us. It told us the name of the remote cluster and helped us determine the remote kiali URL.

**Comment by jshaughn** [comment]
So how would we handle the situation that someone was already using the experimental feature and has secrets already, but isn't trying to set up our new MC ability?  Just documentation/release notes to delete the secrets and optionally add this proposed config?

**Comment by jmazzitelli** [comment]
They still need the istio secrets - those are required for istio MC to work. They just need the kiali secrets so kiali can work.

**Comment by nrfox** [comment]
This isn't working like I would expect. I want to use this feature for Kiali to show multiple clusters on the "mesh" page without giving access to those clusters. My kiali config in the "east" cluster looks like:
```
kiali_feature_flags:
  clustering:
    kiali_urls:
      - cluster_name: west
        instance_name: kiali
        namespace: istio-system
        url: kiali-west.io
```

but still I just see "east"
![Screenshot from 2023-12-05 21-01-35](https://github.com/kiali/kiali/assets/6226732/44211538-31ce-4bbe-919a-3a853db34186)

**Comment by hhovsepy** [comment]
The `url` param here expects a protocol as well.

**Comment by hhovsepy** [comment]
@nrfox right, this feature was implemented partly, I saw your PR, so assigning this to you, thank you.
