### ISSUE TITLE
Unwanted "fit" on refresh

### ISSUE THREAD

**Issue by aljesusg** [kiali/kiali#6248]
There is a bad behaviour in replay mode. When we focus in the graph the "next step" refresh all the graph to the initial state (without zoom, layout...). See demo

![graph](https://github.com/kiali/kiali/assets/3019213/98b118ee-1e93-4692-a0d3-19b52157e8fa)

**Comment by jshaughn** [comment]
This was initially reported against Graph Replay, but I'm now seeing similar behavior in the main graph.
