### ISSUE TITLE
[Multi-cluster] Some pages are broken when meshID is not set

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#6249]
When the meshID is not set, the istio api does not populate the `clusters` field on the `/config` response. The frontend looks for this clusters field to determine whether or not Kiali is in "multi-cluster mode".

**Comment by jshaughn** [comment]
if `meshID` is not set does it have some default value or is it simply unset?  IIrc it's just unset and so `clusters` would not be returned and I think Istio is assuming a single cluster, and I guess we should as well?

**Comment by nrfox** [comment]
> if `meshID` is not set does it have some default value or is it simply unset?

At least in the env I tested in and where Kiali is reading this in the default config, it is unset.
https://github.com/kiali/kiali/blob/ecd24d32d10a3da2747a70997afd8ba409c92ce0/business/mesh.go#L173-L181

Yeah I think the clusters field was populated based on "best effort" but for better or worse some parts of Kiali use that field like `if clusters > 1: do MC things else do single cluster things`. This is used on the frontend to hide the cluster column for example and I think it's used on the backend too. When the clusters field is empty or == 1 then kiali assumes singlecluster. The cache, on the other hand, does not look at this clusters field and correctly starts talking to the remote clusters when there's a remote secret added.

**Comment by jmazzitelli** [comment]
Right - that MeshID istio config is the key to turning on the Mesh page/left-hand-menu item.

**Comment by jshaughn** [comment]
This is a little confusing, is meshID required for Istio itself to be MC?  If so then it seems that we should honor what it tells us in `/config`.  It would be a little strange that Kiali would assume MC, based on secrets, when Istio itself doesn't think it's MC.

**Comment by nrfox** [comment]
> This is a little confusing, is meshID required for Istio itself to be MC? If so then it seems that we should honor what it tells us in `/config`. It would be a little strange that Kiali would assume MC, based on secrets, when Istio itself doesn't think it's MC.

I think it's only required if you have multiple meshes and want to distinguish between them. It also may be emitted by telemetry for these purposes. In other words, I don't think setting the `meshID` enables MC in istio.

**Comment by jshaughn** [comment]
I think meshID may actually be injected into the telemetry for cross-mesh traffic (I think there is a default value related to the trust domain), although Kiali does not handle cross-mesh at this time.

Anyway, it sounds like we need to trust our secrets and report the clusters that way.
