### ISSUE TITLE
Kiali Operator - Configurable Kiali Service Account Annotations

### ISSUE THREAD

**Issue by calumrees99** [kiali/kiali#6277]
I'm looking at adding an annotation to the service account that the kiali operator deploys. My specific scenario is that I need to add an AWS IRSA annotation, so that the kiali pod can Authenticate/Authorize to my remote Prometheus (AWS managed Prometheus). 

This is my first time looking through this codebase, but I believe I can see an similar thing been done with the "kiali_vars.deployment.service_annotations"
![image](https://github.com/kiali/kiali/assets/81469431/88e1e217-c077-4415-8ea6-7588f6d3a16e)

This seems like it can be configured through the CR like so:
![image](https://github.com/kiali/kiali/assets/81469431/3c791426-5752-4cb4-9b73-90dabcedc365)

In contrast, looking at the serviceAccount.yaml, it doesn't look like these annotations can be configured:
![image](https://github.com/kiali/kiali/assets/81469431/e652698e-0061-4e68-99ca-febecf3e15cb)

PR for the proposed changes should be fairly small and I'm happy to make the required changes, I just need confirmation that I'm looking in the right place and whether anyone has any other suggestions 😄

**Comment by calumrees99** [comment]
I may have jumped the gun on this one for my use case! Does Kiali have the capability to integrate with AWS managed Prometheus?

**Comment by jmazzitelli** [comment]
Here's the docs on prom config: https://kiali.io/docs/configuration/p8s-jaeger-grafana/prometheus/

And there are additional settings that allow you to configure Kiali to authenticate with an external Prometheus - see: https://kiali.io/docs/configuration/kialis.kiali.io/#.spec.external_services.prometheus.auth

I don't know if anyone is using Kiali with AWS managed prom but we do have people using it in AWS so I would assume some people are also using the AWS managed prom.

**Comment by jmazzitelli** [comment]
@calumrees99 @vazkarvishal Do you think this is something that is still needed for Kiali to support AWS-managed Prometheus, or did you figure out the problem without needing additional features in Kiali?

**Comment by calumrees99** [comment]
We didn't find an alternative solution. I believe any external resource that communicates with Amazon managed Prometheus needs Sigv4 authentication, which I don't believe Kiali can handle? So instead I looked at injecting the AWS sigv4 proxy sidecar: 
https://github.com/aws-observability/aws-sigv4-proxy-admission-controller 

Unfortunately I didn't get the time to fully ticker with it, but my understanding was that the proxy container would add the required authentication for Kaili to communicate with amp.

**Comment by jmazzitelli** [comment]
> So instead I looked at injecting the AWS sigv4 proxy sidecar:

Interesting. So it sounds like an alternative would be for kiali to support this, and you just use it to inject the aws sidecar into the kiali pod: https://github.com/kiali/kiali/issues/5028

**Comment by jshaughn** [comment]
@calumrees99 , @jmazzitelli , Is there anything to do here?

**Comment by guitmz** [comment]
@calumrees99 I believe you are correct, this needs to be added to the spec and to the chart as you exemplified. I can also open a PR if you don't have time. I just stumbled upon this while trying to achieve AMP connection via AWS sigv4 sidecar proxy

**Comment by jshaughn** [comment]
@guitmz Any intention of submitting a PR?

**Comment by jshaughn** [comment]
Closing as Stale.
