### ISSUE TITLE
Using LISTENER_FILTER within an EnvoyFilter leads to a cache error

### ISSUE THREAD

**Issue by pseudonator** [kiali/kiali#6285]
Using `1.69.0` noticing the following error message when building the cache for `EnvoyFilter`.

```
2023-06-21T03:57:41Z INF Initializing Kiali Cache
2023-06-21T03:57:41Z INF Adding a RegistryRefreshHandler
2023-06-21T03:57:41Z INF [Kiali Cache] Waiting for cluster-scoped cache to sync
W0621 03:57:41.091097       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167: failed to list *v1alpha3.EnvoyFilter: unknown value "\"LISTENER_FILTER\"" for enum istio.networking.v1alpha3.EnvoyFilter.ApplyTo
E0621 03:57:41.091115       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167: Failed to watch *v1alpha3.EnvoyFilter: failed to list *v1alpha3.EnvoyFilter: unknown value "\"LISTENER_FILTER\"" for enum istio.networking.v1alpha3.EnvoyFilter.ApplyTo
```

This is due to the fact that we have used `LISTENER_FILTER` which was introduced in version of Istio `1.17` APIs.
However notice that [deps](https://github.com/kiali/kiali/blob/master/go.mod#LL27C1-L28C28) still point to `1.15.2`.

Any work to get these deps updated ?

**Comment by jshaughn** [comment]
@nrfox If we are going to backport this I think it would be to v1.66, the highest version for Istio 1.17 in the compat chart.  But I think we may be OK just providing the fix in 1.70 as it was reported against 1.69.  I'll leave it up to you.

**Comment by nrfox** [comment]
I think it'd be good to backport to v1.66 to have this fixed in a version of Kiali that fits into the compatibility matrix for istio 1.17.

**Comment by pseudonator** [comment]
Thanks for the quick turn around on this fix team !
