### ISSUE TITLE
Kiali Operator won't launch Kiali instance due error: request() got an unexpected keyword argument 'chunked'

### ISSUE THREAD

**Issue by joelcomp1** [kiali/kiali#6319]
I have tried this with both Kiali 1.65 and 1.68 and get the same issue so I suspect it's something on my end.  I am running K8s 1.27 on RKE2 and Kiali Operator is throwing this error constantly:

{"level":"error","ts":"2023-06-28T17:05:51Z","logger":"runner","msg":"Traceback (most recent call last):\n  File \"/usr/local/lib/python3.8/site-packages/ansible_runner/__main__.py\", line 866, in main\n    res = run(**run_options)\n  File \"/usr/local/lib/python3.8/site-packages/ansible_runner/interface.py\", line 260, in run\n    r.run()\n  File \"/usr/local/lib/python3.8/site-packages/ansible_runner/runner.py\", line 119, in run\n    self.status_callback('starting')\n  File \"/usr/local/lib/python3.8/site-packages/ansible_runner/runner.py\", line 107, in status_callback\n    ansible_runner.plugins[plugin].status_handler(self.config, status_data)\n  File \"/usr/local/lib/python3.8/site-packages/ansible_runner_http/events.py\", line 35, in status_handler\n    status = send_request(plugin_config['runner_url'],\n  File \"/usr/local/lib/python3.8/site-packages/ansible_runner_http/events.py\", line 18, in send_request\n    return session.post(url_actual, headers=headers, json=(data))\n  File \"/usr/local/lib/python3.8/site-packages/requests/sessions.py\", line 635, in post\n    return self.request(\"POST\", url, data=data, json=json, **kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/requests/sessions.py\", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/requests/sessions.py\", line 701, in send\n    r = adapter.send(request, **kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/requests/adapters.py\", line 486, in send\n    resp = conn.urlopen(\n  File \"/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 790, in urlopen\n    response = self._make_request(\n  File \"/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 496, in _make_request\n    conn.request(\nTypeError: request() got an unexpected keyword argument 'chunked'\n","job":"2238350836631459930","name":"installer","namespace":"","error":"exit status 1","stacktrace":"github.com/operator-framework/operator-sdk/internal/ansible/runner.(*runner).Run.func1\n\t/workspace/internal/ansible/runner/runner.go:269"}
{"level":"error","ts":"2023-06-28T17:05:52Z","logger":"reconciler","msg":"Unable to mark error to run reconciliation","job":"2238350836631459930","name":"installer","namespace":"","error":"namespaces \"installer\" is forbidden: User \"system:serviceaccount:kiali:kiali-kiali-kiali-operator\" cannot update resource \"namespaces/status\" in API group \"\" in the namespace \"installer\"","stacktrace":"github.com/operator-framework/operator-sdk/internal/ansible/controller.(*AnsibleOperatorReconciler).Reconcile\n\t/workspace/internal/ansible/controller/reconcile.go:224\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:122\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:323\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:235"}

**Comment by jmazzitelli** [comment]
```
namespaces "installer" is forbidden: User "system:serviceaccount:kiali:kiali-kiali-kiali-operator" cannot update resource "namespaces/status" in API group "" in the namespace "installer""
```

Sounds like the operator's SA is incorrect and does not have the proper permissions.

How did you install the operator? Did you use the published Kiali helm charts, OLM, or some custom method?

**Comment by jmazzitelli** [comment]
Let me guess... Rancher? :)

Try an experiment - install the operator using the Kiali-provided helm charts: 

https://kiali.io/docs/installation/installation-guide/install-with-helm/#adding-the-kiali-helm-charts-repository

If you don't get the same error and Kiali server installs fine, then the problem is in the helm charts you are using.

If you get the same error, I would wonder if the cluster has some locked down security. I actually don't know what "status" permission it would need on the namespace - that's a new one to me.

**Comment by joelcomp1** [comment]
Ha no good guess though, actually from Platform One, it had worked before so I had thought it was maybe a k8s version thing as I had moved from 1.25 to 1.27 but that doesnt seem to be it.  I used the helm chart from the link you provided and worked great, i'll dig into it more on my side, thanks for the help!
