### ISSUE TITLE
Graph IdleNodes option is broken

### ISSUE THREAD

**Issue by jshaughn** [kiali/kiali#6331]
The graph's IdleNode Display option broke at some point during the multi-cluster work.

**Comment by jmazzitelli** [comment]
This may still be broken. Turn off "service nodes" and you get the "empty graph" message again:

![image](https://github.com/kiali/kiali/assets/2029470/3e705a03-63c3-4e8e-b310-12287b5baf25)

turn on "service nodes" and now I see the idle nodes:

![image](https://github.com/kiali/kiali/assets/2029470/3a65da73-4e5b-49c7-9848-842c92288bb3)

**Comment by jshaughn** [comment]
> This may still be broken. Turn off "service nodes" and you get the "empty graph" message again:

This is unrelated to this bug and this bug fix.   For better or for worse, we don't look for unused services unless it's a service graph or the Show Service Nodes option is selected.  It's been this way for 4 years, so not going to make a change unless a real user complains.
