### ISSUE TITLE
Multicluster - unbound variable in kiali-deploy

### ISSUE THREAD

**Issue by josunect** [kiali/kiali#6366]
When running the `istio/multicluster/install-primary-remote.sh` script with the following arguments: 

`istio/multicluster/install-primary-remote.sh -c kubectl -kudi true -kshc ~/dev/kiali_sources/helm-charts/_output/charts/kiali-server-1.72.0-SNAPSHOT.tgz`

It fails with the following error: 

```
Preparing remote cluster secret for single Kiali install in multicluster mode.
/home/jcordoba/dev/kiali_sources/kiali/hack/istio/multicluster/deploy-kiali.sh: line 88: remote_url_flag: unbound variable
```

**Comment by jmazzitelli** [comment]
@josunect try this: https://github.com/kiali/kiali/pull/6367
