### ISSUE TITLE
Incorrect save commit may be triggered while editing yaml

### ISSUE THREAD

**Issue by pantianying** [kiali/kiali#6374]
<img width="1278" alt="image" src="https://github.com/kiali/kiali/assets/20589945/356757b7-a3ef-4562-89e9-7952528a740d">

I found this error so do delete the wrong subset.

<img width="1280" alt="image" src="https://github.com/kiali/kiali/assets/20589945/9a5e00da-60bd-41f9-bffc-b431b9a2ded4">

when saving ,reported the mistake:
<img width="1235" alt="image" src="https://github.com/kiali/kiali/assets/20589945/f8cbbf03-21a6-4364-b1e2-a4fb426b5eed">

this is request body , null should be removed
<img width="1160" alt="image" src="https://github.com/kiali/kiali/assets/20589945/071704e5-4f80-4699-9045-17b293363a49">

**Comment by pantianying** [comment]
I suspect that when editing yaml, all array deletions are problematic

**Comment by jshaughn** [comment]
Thanks for the report, @pantianying , we'll take a look.
