### ISSUE TITLE
Data race when accessing `IsGatewayAPI`

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#6387]
`IsGatewayAPI` is accessed concurrently which causes data race warnings in CI:
![Screenshot from 2023-07-20 12-35-37](https://github.com/kiali/kiali/assets/6226732/ac5e705a-f646-4da8-9b6a-0657d98807e6)

CI job: https://github.com/kiali/kiali/actions/runs/5613355064/job/15209536954?pr=6385

It needs some kind of lock around it.

**Comment by jmazzitelli** [comment]
To run these tests locally, run `hack/run-integration-tests.sh --test-suite backend`

You could then re-run this specific test:
```
export URL="http://$(kubectl get svc istio-ingressgateway -n istio-system -o=jsonpath='{.status.loadBalancer.ingress[0].ip}')/kiali"
go test tests/integration/tests/applications_test.go
```

Though I have been unable to replicate this error locally.

**Comment by jmazzitelli** [comment]
Here you can see IsGatewayAPI being called concurrently in two go-funcs:
https://github.com/kiali/kiali/blob/v1.72.0/business/istio_config.go#L411-L422

I didn't examine it yet, but clearly something in IsGatewayAPI needs to be protected against concurrent access.

```go
	go func(ctx context.Context, errChan chan error) {
		defer wg.Done()
		if userClient.IsGatewayAPI() && criteria.Include(kubernetes.K8sGateways) {
			var err error
			istioConfigList.K8sGateways, err = kubeCache.GetK8sGateways(criteria.Namespace, criteria.LabelSelector)
			if err != nil {
				errChan <- err
			}
		}
	}(ctx, errChan)

	go func(ctx context.Context, errChan chan error) {
		defer wg.Done()
		if userClient.IsGatewayAPI() && criteria.Include(kubernetes.K8sHTTPRoutes) {
			var err error
			istioConfigList.K8sHTTPRoutes, err = kubeCache.GetK8sHTTPRoutes(criteria.Namespace, criteria.LabelSelector)
			if err != nil {
				errChan <- err
			}
		}
	}(ctx, errChan)
```

**Comment by jmazzitelli** [comment]
Yeah, the priviate *bool var needs to be protected... 

https://github.com/kiali/kiali/blob/v1.72.0/kubernetes/kubernetes.go#L214-L229

**Comment by jmazzitelli** [comment]
While we are at it... IsIstioAPI is also unprotected and probably needs to be also.

https://github.com/kiali/kiali/blob/v1.72.0/kubernetes/kubernetes.go#L232-L246
