### ISSUE TITLE
K8s Gateway API - Appenders in Graph

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#6397]
Add detection of Graph appenders for traffic-routing on K8s Gateway and HTTPRoute objects.

**Comment by jshaughn** [comment]
On istio.io some features now show how to configure it using Istio's Virtual Service AND also K8s Gateway API and HTTPRoute objects.  The expectation would be for more and more people to opt for the more standard Gateway API approach.  Kiali graph badging needs to take this into account.

I'm not exactly sure how we want to handle things.  My first impression is that we can keep the same set of visual badges but that the badge may represent different implementations, and be able to make it clear which are being used.  In that way users get a consistent visual experience as then introduce or migrate from VS to K8s GA.

**Comment by jshaughn** [comment]
@hhovsepy Right, this is a good example.   My concern here was that we would not detect request routing implemented via HTTPRoute.   The basic idea is that when we see an [Istio feature that could be implemented via VS or GA](https://istio.io/latest/docs/tasks/traffic-management/request-routing/#route-to-version-1), that we can detect it either way.  For example, we can still show the same Request Routing badge on the graph, and the side panel should also still show RR information, regardless of whether it is configured by VS or GA.
