### ISSUE TITLE
Kiali health check

### ISSUE THREAD

**Issue by daparthi001** [kiali/kiali#643]
Unable to get proper information on health ,its showing us error rate for all applications.Any help on this issue ?what is the path its looking on ?

**Comment by jmazzitelli** [comment]
Need more info. Do you have browser console logs? Do you have screenshots to help explain what you are seeing? What version of Kiali are you running (copy-paste the UI's About box content)? Did you install via helm or some other mechanism?

**Comment by pilhuhn** [comment]
Closing as being old. Please reopen if this is still an issue.
