### ISSUE TITLE
Show mesh configuration per controlplane

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#6431]
Kiali has assumed that there's just one controlplane in the mesh. Things like the "About page" which shows "Istio version", the  "Mesh mTLS lock" which shows if your mesh is secured with mTLS based on some mesh config settings from the controlplane, etc. all assume that there's a single controlplane. However even with single cluster, if you use istio revisions, there can be multiple controlplanes that Kiali should take into account for these various features. This is especially true for multi-primary.

This coincides with #5913 as much of the info mentioned above may move to that page and be shown per controlplane.

**Comment by jshaughn** [comment]
I changed the Epic for this from Multicluster to new-Mesh-page.

**Comment by jshaughn** [comment]
I think the idea here would be to move this information to the side panel when selecting an istiod node in the mesh graph.
