### ISSUE TITLE
Remote cluster istio-system namespace card show data from primary control plane

### ISSUE THREAD

**Issue by leandroberetta** [kiali/kiali#6437]
When using the primary-remote multicluster setup, the istio-system card from the remote, should not show data related to metrics (in fact, is showing information from the primary).

Epic: https://github.com/kiali/kiali/issues/5618

**Comment by hhovsepy** [comment]
Probably the `clusterName` param is send wrongly or lost somewhere.

**Comment by leandroberetta** [comment]
> Probably the `clusterName` param is send wrongly or lost somewhere.

Not really, this is happening because in the code, the control plane metrics are fetch when the namespaces matches de "Istio" namespace, but we have two of them, resulting on the same metrics being fetched for both of them.

I can distinguish between primary and remote istio-system namespaces with an annotation called topology.istio.io/controlPlaneClusters (today, Kiali is not adding all the annotations to the Namespace object, it is trimming them to have just the Kiali's dashboards ones, we might need to allow other annotations too).

I might also need to add a new field in the frontend to distinguish between a primary control plane namespace and a remote one.

I'm doing some testing.
