### ISSUE TITLE
Error reported after following installation guide from Istio preliminary docs

### ISSUE THREAD

**Issue by emmayang** [kiali/kiali#644]
**Describe the bug**
Followed installation from Istio preliminary doc here: https://preliminary.istio.io/docs/tasks/telemetry/kiali/, and after logged in, graph cannot be rendered, and reports error: ```replicasets.apps is forbidden: User "system:serviceaccount:istio-system:kiali-service-account" cannot list resource "replicasets" in API group "apps" in the namespace "istio-system"```

**Versions used**
kiali-ui 0.9.1 (5e47f0ff6429f1b4b9794a40f37ac492213ab234)
kiali v0.9.1 (94794d4525ad891184eccbbe4b8c4d9f59e9e518)
Istio: 1.0.3
Kubernetes flavour and version: Kubernetes v1.12.2 (kubeadm)
Prometheus 2.3.1

**To Reproduce**

1. Install istio with helm, and enable Kiali with command (I skipped the update secret part and use default admin/admin credential.):
```
helm install install/kubernetes/helm/istio --name istio --namespace istio-system \
    --set grafana.enabled=true \
    --set tracing.enabled=true \
    --set tracing.jaeger.enabled=true \
    --set kiali.enabled=true
```

2. Deploy bookinfo in `bookinfo` namespace:
3. Expose the Kiali service, and access from browser
4. Go to "Graph" section from left side menu
5. With "all" selected in namespaces dropdown, page shows empty (which shouldn't, since I have bookinfo deployed and injected)

6. Then I clicked the "Display unused nodes" button, and saw error like below screenshot
![screen shot 2018-11-09 at 13 44 09](https://user-images.githubusercontent.com/7776218/48245742-60947680-e427-11e8-8feb-21ebad11b058.png)

**Expected behavior**
Should load service dependencies at first, and no errors expected.

**Comment by jmazzitelli** [comment]
This is a dup of: https://github.com/kiali/kiali/issues/623 

Known issue:

https://groups.google.com/forum/#!msg/kiali-users/C6pYX8HdZSw/UNjBE2OKAgAJ
https://issues.jboss.org/browse/KIALI-1860 

To work around the problems, run this single command from the command line: 

```
curl -s https://raw.githubusercontent.com/kiali/kiali/v0.9/deploy/kubernetes/kiali.yaml | tail -n +109 | head -n 71 | VERSION_LABEL=v0.9 envsubst | kubectl apply -n istio-system -f - 
```

No need to re-start or re-install Kiali - the changes should take effect immediately and the UI should work better. 

The fix to the yaml has already been applied to the istio release-1.0, release-1.1, and master branches, so next Istio releases will have this corrected.

**Comment by emmayang** [comment]
Got it, thanks a lot, and sorry for dup, didn't catch the issue title in the list...

**Comment by pilhuhn** [comment]
On 9 Nov 2018, at 10:18, Emma Yang wrote:

> Got it, thanks a lot, and sorry for dup, didn't catch the issue title 
> in the list...

Thank you Emma. Better reporting a dup than not reporting
at all. This way we can look at the issue and fix it.

**Comment by xeviknal** [comment]
@emmayang no problem! agree with @pilhuhn :) this issue is shown in multiple ways! thanks for the notification!
