### ISSUE TITLE
Add to readme documentation about to check patternfly versions

### ISSUE THREAD

**Issue by aljesusg** [kiali/kiali#6454]
There is a command to check if there is a new version. This command is going to update patternfly libraries automatically.

```bash
npx npm-check-updates -t latest -f '/^@patternfly/'
```

So it would be great to add this the docs like "**_procedure_**"

1. Launch command `npx npm-check-updates -t latest -f '/^@patternfly/'`
2. Launch `yarn install` to update the **yarn.lock**
3. Add to the commit **package.json** and **yarn.lock**

**Comment by premkirank** [comment]
@aljesusg can I pick this up?

**Comment by aljesusg** [comment]
Assigned ! Thanks for your great energy
