### ISSUE TITLE
"Kiali Istio Config page -- KIA0104 validation (failed)" failure

### ISSUE THREAD

**Issue by matejnesuta** [kiali/kiali#6460]
This test has been failing consistently both on our upstream OCP and on my local setup when using KinD. I think this might indicate a bug in Kiali, because it doesn't look like a test flake to me, but I am not able to investigate further.
![image](https://github.com/kiali/kiali/assets/45061792/ef47734f-f9f1-4cc0-9a1f-1cfecc62a08d)

**Comment by hhovsepy** [comment]
The validation KIA0104 also is checking hosts in VS, in your testing env you have a 'bookinfo' VS with host '*', so this host is considered as a match for a AP's host 'missing.hostname'.
This needs to be documented in kiali.io.
The test should remove any VS before execution.
