### ISSUE TITLE
Multicluster - Automated testing for list pages

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#6474]
Test for presence of `cluster` column in multi-cluster mode on the different list pages:

- Applications
- Services
- Istio config
- Workloads

**Comment by matejnesuta** [comment]
We might want to extend the scenarios further by testing this: https://github.com/kiali/kiali/issues/6028.

**Comment by jshaughn** [comment]
@leandroberetta Any opinion on @matejnesuta 's suggestion?
