### ISSUE TITLE
Multicluster - Automated testing for multi-cluster scenarios for the overview page

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#6477]
Test for multi-cluster specific features of overview page such as:

- Namespace cards for each cluster (east and west)
- Cluster badge has correct cluster name
- Namespace card - kebab menu shows updating/deleting traffic policies for east/west cluster.

**Comment by matejnesuta** [comment]
In the Multicluster demo for the Overview page, Josune showed this (https://youtu.be/m9PjljC99nA?t=152). However, this feature is not enabled on the cluster-wide Bookinfo installation. Do we want to alter the demoapp?
