### ISSUE TITLE
Multicluster - Automated testing for wizards in multi-cluster scenarios

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#6478]
Test that you can create/edit/update objects in the "primary" cluster in multi-cluster mode. Ensure you can't edit istio config for "remote" clusters in multi-cluster mode.

**Comment by matejnesuta** [comment]
The PR above doesn't test clusterrolebindings in this specific PR (#6060), because it needs more setup (if we are going to test for it in the first place).

**Comment by nrfox** [comment]
Closing since #7045 has been merged
