### ISSUE TITLE
Use 'clusterNameFromQuery' in graph/options

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#6486]
Currently graph/options.go https://github.com/kiali/kiali/blob/master/graph/options.go#L142 is directly taking params from query. For instance the 'clusterName' as well.
Will be better to make a refactoring and move options parsing into handler, like in other object handlers, but it will require a big refactoring.

**Comment by jshaughn** [comment]
@hhovsepy Do you still think this work would be worth the effort?

**Comment by hhovsepy** [comment]
@jshaughn I think that efforts of refactoring will require too much time. Probably we can close this issue.
