### ISSUE TITLE
Can support kiosk mode like grafana?

### ISSUE THREAD

**Issue by jeremyxu2010** [kiali/kiali#651]
**Describe the bug**
I want embed kiali's web page into my system. I know grafana has the kiosk mode, which only show content area(the title bar and nav bar are be hidden). The kiosk mode is what i need.

For UI issues please also add a screenshot that shows the issue.

**Versions used**
Kiali: v0.9
Istio: 1.0.3
Kubernetes flavour and version:  1.10

**Comment by pilhuhn** [comment]
I am closing this as the PR was merged.
