### ISSUE TITLE
remove all usage / mention of kiali-bot

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#6515]
There is a kiali-bot user that will soon be rendered unusable because 2FA is not enabled on it (and github is requiring users to all have 2FA enabled).

I don't think this is used anyway so we should get rid of it.

There is also a kiali-ui-bot that also should be removed.

**Comment by jmazzitelli** [comment]
all mention of kiali-bot can be seen here: https://github.com/search?q=org%3Akiali%20kiali-bot&type=code

**Comment by yuluo-yx** [comment]
Hi, team. I want to try. if it need to solve, pls assign to me.

**Comment by jmazzitelli** [comment]
@yuluo-yx this task is already complete. There is one final [PR](https://github.com/kiali/kiali/pull/7037) that needs some additional research, but the work has been completed already.

**Comment by jshaughn** [comment]
https://github.com/FreelancingTwin, Will you be able to finish the work in https://github.com/kiali/kiali/pull/7037?

**Comment by yuluo-yx** [comment]
> @yuluo-yx这个任务已经完成了。最终的[PR](https://github.com/kiali/kiali/pull/7037)需要一些额外的研究，但这项工作已经完成。

got it.

**Comment by yuluo-yx** [comment]
> @yuluo-yx this task is already complete. There is one final [PR](https://github.com/kiali/kiali/pull/7037) that needs some additional research, but the work has been completed already.

got it.

**Comment by jmazzitelli** [comment]
this is done

**Comment by jmazzitelli** [comment]
I am wrong - this isn't completely done. There is still some reviewing to be done here: https://github.com/kiali/kiali/pull/7037
