### ISSUE TITLE
Support auto login using url query params

### ISSUE THREAD

**Issue by jeremyxu2010** [kiali/kiali#652]
**Describe the bug**
I want embed kiali's web page into my system. So i need auto login using url query params. eg. i use 
`http://kiali.k8s.local/console/graph/namespaces?layout=dagre&duration=60&edges=hide&graphType=versionedApp&injectServiceNodes=false&username=admin&password=admin` link to view graph page directly(skip login page).

For UI issues please also add a screenshot that shows the issue.

**Versions used**
Kiali: v0.9
Istio: 1.0.3
Kubernetes flavour and version: 1.10

**Comment by pilhuhn** [comment]
As discussed in https://github.com/kiali/kiali-ui/pull/813 this is too dangerous. So I am closing the request.

**Comment by jmazzitelli** [comment]
See https://github.com/kiali/kiali-ui/pull/830 - I believe that will do what you want.
