### ISSUE TITLE
Improve check for detection of workload in Ambient Mesh

### ISSUE THREAD

**Issue by josunect** [kiali/kiali#6523]
It was reported that Kiali was marking as "Out of Mesh" workloads included in an Ambient Namespace. 

Tested with Rollouts, Deployments and DaemonSets from 1 to N replicas. On an EKS cluster. And Istio 1.19.0-beta.0, 1.18

Maybe it would be enough to just check the namespace label? But for sidecars, there are more than one check, it actually checks for the existence of the sidecar. What happen if the namespace is annotated but for some reason the workload was not redirecting the traffic? I guess it would be useful to have some way to detect and alert for this situation. 

[istio.io/dataplane-mode=ambient](http://istio.io/dataplane-mode=ambient) -> namespace label, will include or exclude a namespace.
[ambient.istio.io/redirection=enabled](http://ambient.istio.io/redirection=enabled) = pod label, indicates the pod "is captured" - adding a namespace label instructs the node agent to capture all pods in the labeled namespace, and label each "captured" pod with this.
Unlabeleing the namespace reverses this process, and (after the agent processes/uninjects a given pod) unlabels the pods.
[ambient.istio.io/redirection=disabled](http://ambient.istio.io/redirection=disabled)  = can be manually applied to a pod to opt it out

Ref. https://github.com/kiali/kiali/issues/5476

**Comment by josunect** [comment]
That might be the reason: https://github.com/istio/istio/blob/master/pilot/pkg/serviceregistry/kube/controller/ambientindex_external.go#L409 

`For VMs we use Labels instead of an Annotations since we don't have access to the top level WorkloadEntry object.`

**Comment by jshaughn** [comment]
One thing I notice in the current [Getting Started With Ambient Mesh](https://istio.io/latest/docs/ops/ambient/getting-started/#addtoambient) Istio docs is that they only talk about the namespace labeling.  There is no discussion about how to label/annotate individual pods to somehow override the namespace label for a particular pod.  So, maybe for now Kiali should just defer to the namespace label and assume all pods in the namespace are in-mesh if there is no label/annotation?

**Comment by josunect** [comment]
> One thing I notice in the current [Getting Started With Ambient Mesh](https://istio.io/latest/docs/ops/ambient/getting-started/#addtoambient) Istio docs is that they only talk about the namespace labeling. There is no discussion about how to label/annotate individual pods to somehow override the namespace label for a particular pod. So, maybe for now Kiali should just defer to the namespace label and assume all pods in the namespace are in-mesh if there is no label/annotation?

This is something internal that Istio does, so I've thought that, instead of just checking that the namespace is labeled, we could also check if Istio internally have added those labels. As it could detect some issues as the one that I mentioned here https://github.com/kiali/kiali/issues/6523#issuecomment-1695870350 (The namespace was labeled but for some reason - in this case the cni is not supported - the workloads where not added to the mesh, as Istio failed to add the pods to the Ambient Mesh)

**Comment by jshaughn** [comment]
I agree that it's better to use the label and/or annotation, because it could catch an unexpected situation.  My only concern is that we need to make sure we have every scenario covered correctly.  In the use case for this issue it seems that Istio did not apply the expected label or annotation, but the workload was still being considered in-mesh?

**Comment by josunect** [comment]
> I agree that it's better to use the label and/or annotation, because it could catch an unexpected situation. My only concern is that we need to make sure we have every scenario covered correctly. In the use case for this issue it seems that Istio did not apply the expected label or annotation, but the workload was still being considered in-mesh?

The workload was not considered in mesh - But I was not able to verify if Istio applied the label/annotation. I've found there is one scenario not covered: when Istio adds the label instead of the annotation ( Working on this PR https://github.com/kiali/kiali/pull/6528 )

**Comment by jshaughn** [comment]
@josunect This has been sitting in the sprint in-progress state but it seems stalled.  I'll move it back to the backlog for now.

**Comment by josunect** [comment]
I think this can be closed based on this: https://github.com/kiali/kiali/pull/7162
