### ISSUE TITLE
Update Releasing doc

### ISSUE THREAD

**Issue by aljesusg** [kiali/kiali#6526]
In [./RELEASING.md](RELEASING.md)we need to change the release.yaml schedule, it says Fridays when the action is configured with this:

schedule:
  # Every Monday at 07:00 (UTC)
  - cron: '00 7 * * MON'

**Comment by leviosacz** [comment]
Hey @aljesusg 
Here is the PR: #6530 
Could you please take a look and see if I missed something?
Thanks!
