### ISSUE TITLE
Auth header present when Token is used

### ISSUE THREAD

**Issue by rohitsakala** [kiali/kiali#6533]
We enabled the Token Strategy of Kiali and using that to login into kiali, but the authenticate API is sending the token in the payload and in addition to that it is also sending ":" in Authorisation header since username and password are empty. We feel like this is a bug since if the username and password is empty, there is no need of sending the Auth header as just ":".

**Comment by jmazzitelli** [comment]
> The empty Auth header should not be sent when using Token strategy

Were you seeing an error here? What is the error?  Please provide replication procedures and logs that show the problem.
