### ISSUE TITLE
Validation needs to support new mechanism for subsetting

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#6539]
There is some work underway to push users away from using subsets and towards using services with a version suffix instead of subsets. Subsets will not go away, but just a new way of doing it is going to be introduced for better integration with Gateways API.

See: https://docs.google.com/document/d/1TpovrMTnwHFPFi2-l6rT6yVEeoGKn-JWymAJJbfGYQM/

```
All features of DR will continue to be supported with Sidecars,
for the few advanced users who require them - but the docs
and ‘best practices’ should recommend the ‘standard’-friendly
model, and Ambient may only support the standard-aligned
model, with Sidecars used for the workloads that require the
advanced but rarely used features of DR. 
...
In the new K8S Gateway API, the community consensus was
to use a dedicated Service object for each version. This is already
supported by Istio -  by using the subset service ( reviews-v2)
instead of service (reviews) and subset (v2).

The proposal is to update all the docs - and eventually validators
to recommend the new mechanism for subsetting. 
```

**Comment by hhovsepy** [comment]
The Gateway API support in Kiali is already include services per version.
We need to include a new subsection in https://kiali.io/docs/features/validations/#destinationrules to recommend users using separate Services per versions.

**Comment by jshaughn** [comment]
Do you guys think Gateway API support maybe deserves a dedicated section on Kiali.io, or is it best to just distribute the knowledge like we have today?  Either way, I'll add this to the backlog...

**Comment by hhovsepy** [comment]
I think we can have a new section about GWAPI support. Then keep the validations as it is.
