### ISSUE TITLE
Multicluster Test job uses release version of Kiali and not master

### ISSUE THREAD

**Issue by matejnesuta** [kiali/kiali#6547]
Found this on accident, when some of my Cypress tests failed due to different versions of Patternfly in each environment. It looks like the Helm chart in the related script is using the release version of Kiali and not the master branch. 

https://github.com/kiali/kiali/blob/08134da30b2cf42149c841bdbee90dfb81afd619/hack/istio/multicluster/deploy-kiali.sh#L139

**Comment by jmazzitelli** [comment]
But if you are telling the script to use dev images, it will pull the master builds.. see:

https://github.com/kiali/kiali/blob/master/hack/istio/multicluster/deploy-kiali.sh#L83

The option to enable this is https://github.com/kiali/kiali/blob/master/hack/istio/multicluster/env.sh#L324-L328

The comment says it only works with minikube, but I think it might work (or can be made to work) now with KinD.

**Comment by matejnesuta** [comment]
So, I did some digging around and I managed to manually deploy a locally built Kiali using Kind in an MC setup, mainly by repurposing commands and Helm charts for single cluster in the `setup-kind-in-ci.sh`. I might send a draft PR later this week.
