### ISSUE TITLE
Kiali and Amazon Managed Service for Prometheus (agent mode)

### ISSUE THREAD

**Issue by cokegen** [kiali/kiali#6550]
We've setup our Prometheus in agent mode, forwarding to a managed Prometheus in AWS.

When trying to get a graph for an application we're getting these messages logged:

```
2023-08-31T16:01:33Z ERR Failed to fetch Prometheus configuration: client_error: client error: 404
2023-08-31T16:01:33Z ERR Failed to fetch Prometheus flags: client_error: client error: 404
```
And reading comments for another non-related issue, I've found that the queries towards:
```
GET /api/v1/status/config
GET /api/v1/status/flags
```
To retrieve the configuration and flags works on a "normal" (non-agent) Prometheus, but not in our case since those paths (or features) are not being made available by AWS.

I guess my question is if Kiali + AWS Managed Prometheus is a compatible combo or not. In other words, if not having those API endpoints will make stuff (like showing the Graphs, and possible other stuff) to fail.

The same setup we have works if we switch Prometheus to NOT be in agent mode (logging to a "local" EBS) which has those API endpoints available (since we don't connect to the managed service), but to a local more "normal" Prometheus. Maybe something can be configured, tweaked or reformulated to make this to work ?

Any insights on this will be terribly appreciated.

Thanks !

**Comment by jmazzitelli** [comment]
sounds like this might be something similar to a Thanos proxy setup. There is a feature in Kiali where you can provide the config flags in the Kiali CR (rather than have Kiali look them up by hitting those Prometheus endpoints)... try to set this in your Kiali CR and see if it helps.

https://kiali.io/docs/configuration/kialis.kiali.io/#.spec.external_services.custom_dashboards.prometheus.thanos_proxy

**Comment by jshaughn** [comment]
Closing as stale. Re-open as needed.

**Comment by nrfox** [comment]
This actually looks somewhat related: https://github.com/kiali/kiali/issues/5734. Probably some managed prometheus services do not expose those endpoints. I wonder if Kiali _can_ work without getting info from these:
```
GET /api/v1/status/config
GET /api/v1/status/flags
```
It should probably be documented what prom endpoints Kiali requires so users can check if their managed offering will work or not.
