### ISSUE TITLE
Align d3 library with PF5

### ISSUE THREAD

**Issue by ferhoyos** [kiali/kiali#6564]
Currently Kiali uses `d3` library with version ^5.16.0 while PF5 react-topology library uses version ^7.8.0. Since `d3` is used only to support PF5 topology component, I think this library should be aligned with PF5 to avoid inconsistencies and reduce application size (both versions are loaded at runtime).

**Comment by jshaughn** [comment]
Yes, I think it's used only for that hack to perform the "Raise" on hover for the labels.  The intent is to use the same version as PFT.

**Comment by ferhoyos** [comment]
I have found that `d3` dependency can be directly removed from package.json since it is a direct dependency of `@patternfly/react-topology`. In that case you don't have to update version of `d3`library each time you update PF.

The same happens for other PF related libraries: `victory`and `@patternfly/react-tokens`.
