### ISSUE TITLE
Document how to create kind cluster in README

### ISSUE THREAD

**Issue by ferhoyos** [kiali/kiali#6597]
Current README has following statement in **Create a Kubernetes cluster and install a Service Mesh** section
```
You can also use kind, however we don’t have a script to create a kind cluster.:
```

This is not true since [hack/start-kind.sh](https://github.com/kiali/kiali/blob/2c064ac610c13aa89734e1ac88817e7270070a84/hack/setup-kind-in-ci.sh) hack script was recently made to create a single node KinD cluster with metallb enabled for testing Kiali against a real environment.

Then README should be corrected and include how to create kind cluster (similar way we already do with Openshift and Minikube clusters).

**Comment by milinddethe15** [comment]
Hi, I want to work on this. Assign it to me.

**Comment by ferhoyos** [comment]
Hi @milinddethe15! Thank you for colaborating in Kiali project. Assigned

**Comment by ferhoyos** [comment]
Closing this ticket since completed via #6697
