### ISSUE TITLE
prune old operator versions from OLM

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#6604]
We have a single stable channel that is published to the Red Hat Community Channel (as well as OperatorHub.io). It has about 70 versions now, and we continue pressing forward, releasing new versions every 3-week sprint. Process works fine. However, the very old versions are obsolete, are no longer supported, and we'd like to remove them because, for one reason, as we add new versions it takes longer and longer for the tests to run.

I am referring to these operator versions:
* https://github.com/redhat-openshift-ecosystem/community-operators-prod/tree/main/operators/kiali
* https://github.com/k8s-operatorhub/community-operators/tree/main/operators/kiali

(FWIW: we started adding skipRange since v1.47)

According to someone knowledgeable, all we have to do is submit a PR that removes the old versions that we don't want to keep, making sure the upgrade graph is still valid for all channels (i.e. all remaining bundles in the channel have a valid path to get to the current channel head).

I think deleting all versions prior to 1.47 will be good.

**Comment by jshaughn** [comment]
I think it's possible people are running version of Kiali older than 1.47, but I doubt very much they installed using the community operator.
