### ISSUE TITLE
Multicluster - Kiali sometimes doesn't show the graph for the remote cluster

### ISSUE THREAD

**Issue by matejnesuta** [kiali/kiali#6626]
There is a small chance (in my case it's about 20%) that the Graph page doesn't show the remote cluster. Kiali also shows the remote apps/workloads as degraded/failure. 

Restarting the remote istio-eastwestgateway pod works as a workaround, but this could be a problem in the future. However, I am not sure if this happens anywhere outside of KinD, so I am not sure, if this is affecting our CI only, or not. 

istio-eastwestgateway also reports unsynced proxy on both clusters, it might be related to this issue. 
![image](https://github.com/kiali/kiali/assets/45061792/974e84d4-5a1a-40e4-aea1-0376dcc2dfbf)

Making sure this issue is documented.

**Comment by jshaughn** [comment]
Anything in logs when this happens?

**Comment by matejnesuta** [comment]
Honestly, I have not seen this failure for a while now and I am also not sure how to reproduce it. I am thinking about closing this issue.

**Comment by jshaughn** [comment]
Closing as obsolete.  Can be re-opened as needed.
