### ISSUE TITLE
Requesting Clarification regarding Minimum Kiali Verion Supported with Istio `v1.17`

### ISSUE THREAD

**Issue by mooneeb** [kiali/kiali#6628]
Hello 👋 👋 

I was just going through your amazingly-detailed documentation when I came across the Version Compatibility matrix defined for Kiali ([source](https://kiali.io/docs/installation/installation-guide/prerequisites/#version-compatibility)). 

![image](https://github.com/kiali/kiali/assets/61288038/dc96b992-08e0-48a1-896e-07efd6fdce03)

In it I noticed that Kiali `v1.63.2` is supported with both Istio `v1.16` and `v1.17`. I just wanted to clarify if that's really the case (aka the version is supported with both Istio version) or if this is just an unfortunate typo. 

Thank you 😃

**Comment by jmazzitelli** [comment]
It is correct.

See [this PR](https://github.com/kiali/kiali.io/pull/630/files) for when this change was made and why. In short, the Kiali team fixed a regression in 1.63.0 and 1.63.1 and released 1.63.2 which is applicable for both Istio 1.16 and 1.17

**Comment by mooneeb** [comment]
Ahhhh apologies. I Just wanted to make sure, but going through the PR it makes sense now. 

Thank you! 😃 Marking this issue as resolved.
