### ISSUE TITLE
Breadcrumb click on Istio Type filter - Filter type is reset

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#6632]
Happen on Kiali master.

Go to any Istio config details page.
Click on Breadcrumb's Istio Config Type.
Should load Istio Configs filteret by particular type, but in fact filter is not set.
Also sorting by 'Type' field is not working.

This is because 'istiotype' param is used instead of 'type'.

**Comment by jshaughn** [comment]
Thanks for spotting this, @hhovsepy.  Looks like I missed something in the recent PR around the type filtering.
