### ISSUE TITLE
Bug after v1.72.0 release with oAuth2 strategy when DisableRBAC is true

### ISSUE THREAD

**Issue by AlexDexsoon** [kiali/kiali#6677]
Look like there was a mistake in condition for this logic:

https://github.com/kiali/kiali/blob/master/kubernetes/client_factory.go#L224

The second part of condition, looks wrong:
```
		if (cfg.Auth.Strategy != kialiConfig.AuthStrategyAnonymous) ||
			(cfg.Auth.Strategy == kialiConfig.AuthStrategyOpenId && cfg.Auth.OpenId.DisableRBAC) {
			remoteConfig.BearerToken = authInfo.Token
		}
```
Should be something like:
```
		if (cfg.Auth.Strategy != kialiConfig.AuthStrategyAnonymous) &&
			(cfg.Auth.Strategy == kialiConfig.AuthStrategyOpenId &&  !cfg.Auth.OpenId.DisableRBAC) {
			remoteConfig.BearerToken = authInfo.Token
		}
``` 
No Goland developer, sorry.

**Comment by AlexDexsoon** [comment]
@nrfox Can you help please? 
[@[nrfox](https://github.com/kiali/kiali/commits?author=nrfox)
nrfox](https://github.com/kiali/kiali/pull/6279)

**Comment by nrfox** [comment]
You're right this was a bug introduced by that change. Thanks for opening the issue and providing a fix.

**Comment by jshaughn** [comment]
@nrfox A fix should likely be backported to all subsequent versions?  Minimally, 1.73.

**Comment by jmazzitelli** [comment]
Looks like this was already done. See PRs:
* https://github.com/kiali/kiali/pull/6679
* https://github.com/kiali/kiali/pull/6779

@nrfox Can you confirm if we can close this issue now?

**Comment by nrfox** [comment]
> @nrfox Can you confirm if we can close this issue now?

Yes, closing
