### ISSUE TITLE
Service Details - Loads full workloads info in backend

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#6686]
In 'business/services.go GetServiceDetails' method, it calls `in.businessLayer.Workload.fetchWorkloadsFromCluster` to load workloads related to that service, which loads full info about workloads, but only very few info is used as overview of Workloads in Service Details page.

TODO: Optimize the `fetchWorkloadsFromCluster` to load only overview information when necessary, or create another lighter method to load Workloads overview information and use in 'GetServiceDetails'.

**Comment by jshaughn** [comment]
Maybe it should utilize `WorkloadCriteria`?

**Comment by hhovsepy** [comment]
After more research of `in.businessLayer.Workload.fetchWorkloadsFromCluster` method and it's usage, the loaded full information are pods and  'ServiceAccounts' which are coming with pods and used in a tooltip:
![Screenshot from 2023-11-03 09-01-52](https://github.com/kiali/kiali/assets/604313/7e6e5e59-5bbd-4b47-b4bd-34c5af1bee39)
So closing this issue as won't resolve.
