### ISSUE TITLE
when I get Graph from remote cluster on kiali, I got this crash!  by the way, "Kubernetes" is not my remote cluster name;

### ISSUE THREAD

**Issue by EdisonFu** [kiali/kiali#6696]
2023-10-09T11:49:45Z ERR Error fetching Workloads per namespace travel-agency: Cluster [Kubernetes] is not found or is not accessible for Kiali
2023-10-09T11:49:45Z ERR Cluster [Kubernetes] is not found or is not accessible for Kiali: goroutine 80648 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.20.5/x64/src/runtime/debug/stack.go:24 +0x65
github.com/kiali/kiali/handlers.handlePanic({0x23946e0, 0xc000c36888})
        /home/runner/work/kiali/kiali/handlers/graph.go:86 +0x219
panic({0x1c764a0, 0xc003e185f0})
        /opt/hostedtoolcache/go/1.20.5/x64/src/runtime/panic.go:884 +0x213
github.com/kiali/kiali/graph.CheckError(...)
        /home/runner/work/kiali/kiali/graph/util.go:38
github.com/kiali/kiali/graph/telemetry/istio/appender.getWorkloadList({0xc001a29900, 0xa}, {0xc001a29930, 0xd}, 0xc001e7c3c0)
        /home/runner/work/kiali/kiali/graph/telemetry/istio/appender/appender.go:345 +0x40a
github.com/kiali/kiali/graph/telemetry/istio/appender.getAppWorkloads({0xc001a29900, 0xa}, {0xc001a29930, 0xd}, {0xc001a298f2, 0x7}, {0xc001a298f0, 0x2}, 0x1?)
        /home/runner/work/kiali/kiali/graph/telemetry/istio/appender/appender.go:373 +0x14c
github.com/kiali/kiali/graph/telemetry/istio/appender.(*MeshCheckAppender).applyMeshChecks(0xc002c78af0, 0x33b0840?, 0x7f84ae49e1c0?, 0xc002ac3f20)
        /home/runner/work/kiali/kiali/graph/telemetry/istio/appender/mesh_check.go:73 +0x254
github.com/kiali/kiali/graph/telemetry/istio/appender.MeshCheckAppender.AppendGraph({0xc001e7c150}, 0x9?, 0xc0018be738?, 0x12?)
        /home/runner/work/kiali/kiali/graph/telemetry/istio/appender/mesh_check.go:34 +0x3e
github.com/kiali/kiali/graph/telemetry/istio.BuildNamespacesTrafficMap({_, _}, {0xc001e7c150, {0x0, {0xc002df3d40, 0x6, 0x6}}, 0x0, 0x1, 0xc001e7c090, ...}, ...)
        /home/runner/work/kiali/kiali/graph/telemetry/istio/istio.go:80 +0x6a3
github.com/kiali/kiali/graph/api.graphNamespacesIstio({_, _}, _, _, {{0x20913a6, 0x9}, {0x208b994, 0x5}, {{0xc002252f79, 0x15}, ...}, ...})
        /home/runner/work/kiali/kiali/graph/api/api.go:52 +0x126
github.com/kiali/kiali/graph/api.GraphNamespaces({_, _}, _, {{0x20913a6, 0x9}, {0x208b994, 0x5}, {{0xc002252f79, 0x15}, {0xdf8475800, ...}}, ...})
        /home/runner/work/kiali/kiali/graph/api/api.go:33 +0x2fb
github.com/kiali/kiali/handlers.GraphNamespaces({0x23946e0, 0xc000c36888}, 0xc003285500)
        /home/runner/work/kiali/kiali/handlers/graph.go:51 +0x165
net/http.HandlerFunc.ServeHTTP(0x2099919?, {0x23946e0?, 0xc000c36888?}, 0x7f84aec5f3a0?)
        /opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2122 +0x2f
github.com/kiali/kiali/routing.metricHandler.func1({0x23a34a0?, 0xc002085b90}, 0xc000c31d01?)
        /home/runner/work/kiali/kiali/routing/router.go:145 +0x13b
net/http.HandlerFunc.ServeHTTP(0x23a48d8?, {0x23a34a0?, 0xc002085b90?}, 0xc000c31d00?)
        /opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2122 +0x2f
github.com/kiali/kiali/handlers.AuthenticationHandler.Handle.func1({0x23a34a0, 0xc002085b90}, 0xc003285300)
        /home/runner/work/kiali/kiali/handlers/authentication.go:79 +0x3fd
net/http.HandlerFunc.ServeHTTP(0x23a48d8?, {0x23a34a0?, 0xc002085b90?}, 0x2377ba8?)
        /opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2122 +0x2f
github.com/kiali/kiali/server.plainHttpMiddleware.func1({0x23a34a0?, 0xc002085b90?}, 0xc0025c9e60?)
        /home/runner/work/kiali/kiali/server/server.go:157 +0x65
net/http.HandlerFunc.ServeHTTP(0xc003285200?, {0x23a34a0?, 0xc002085b90?}, 0x2?)
        /opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2122 +0x2f
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000138540, {0x23a34a0, 0xc002085b90}, 0xc003285100)
        /home/runner/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
github.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1({0x23a3350, 0xc002e7b960}, 0x0?)
        /home/runner/go/pkg/mod/github.com/!n!y!times/gziphandler@v1.1.1/gzip.go:336 +0x24e
net/http.HandlerFunc.ServeHTTP(0xc003765500?, {0x23a3350?, 0xc002e7b960?}, 0x40d92a?)
        /opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2122 +0x2f
net/http.(*ServeMux).ServeHTTP(0xc002252f20?, {0x23a3350, 0xc002e7b960}, 0xc003285100)
        /opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2500 +0x149
net/http.serverHandler.ServeHTTP({0xc0025c9c80?}, {0x23a3350, 0xc002e7b960}, 0xc003285100)
        /opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2936 +0x316
net/http.(*conn).serve(0xc000867a70, {0x23a48d8, 0xc0011aa300})
        /opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:1995 +0x612
created by net/http.(*Server).Serve
        /opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:3089 [+0x5ed[](url)]([url](url))

<img width="1740" alt="image" src="https://github.com/kiali/kiali/assets/22769471/487088bf-2390-4b1a-aa8f-c91b0d8fefe4">

**Comment by nrfox** [comment]
Hi @EdisonFu, thanks for opening the bug report. A few questions for ya:

What version of Istio/Kiali are you using?

Is this single or multicluster?

You should see a log line like this: `2023-10-10T13:31:56Z INF [Kiali Cache] Kube cache is active for cluster: [Kubernetes]`, what does that say?

Is this just the graph page or do other pages give similar errors? Can you also check what is reported as the `source_cluster` / `destination_cluster` in metrics for traffic in your mesh?

**Comment by EdisonFu** [comment]
@nrfox Thanks for your reply!
source_cluster / destination_cluster is also "Kubernetes";

Now, I have fix this bug, I forgot to set  istio remote cluster name; 
So remote cluster use default name "Kubernetes";
