### ISSUE TITLE
Kiali UI cannot support  multi language i18n 

### ISSUE THREAD

**Issue by osswangxining** [kiali/kiali#670]
**General remarks**

**Describe the bug**
Kiali UI cannot support  multi language i18n, this is very necessary for non-english users.

**Versions used**
Kiali: 0.9
Istio: 1.0.3
Kubernetes flavour and version: (e.g. OpenShift Origin 3.9)

**To Reproduce**

**Expected behavior**
Need to enable i18n

**Comment by pilhuhn** [comment]
This has been entered into our Jira as https://issues.jboss.org/browse/KIALI-1963

**Comment by osswangxining** [comment]
> https://issues.jboss.org/browse/KIALI-1963

Thanks @pilhuhn  I am not familiar with React i18n but would like to provide the Chinese wording.

**Comment by abonas** [comment]
I think it's worth to keep this open, no? @pilhuhn

**Comment by israel-hdez** [comment]
I think we can keep this closed to avoid duplication, since we have https://issues.jboss.org/browse/KIALI-1963 and both entries are cross referenced. We can track progress in Jira and report back here when it is done.
