### ISSUE TITLE
Envoy is duplicated across both clusters

### ISSUE THREAD

**Issue by matejnesuta** [kiali/kiali#6711]
Envoy tab is duplicated for both workloads (east cluster workload is in the left browser, west in the right one). However, there is no details workload in the west cluster. 
![image](https://github.com/kiali/kiali/assets/45061792/88db3e86-123d-49f4-b81c-440d433e5602)

**Comment by hhovsepy** [comment]
Hi @matejnesuta, I was not able to reproduce this error, can you provide more info how did you setup your environment?

**Comment by matejnesuta** [comment]
Hello Hayk. I used the `./hack/run-integration-tests.sh --test-suite frontend-multi-cluster -so true` to setup the KinD multicluster environment.
