### ISSUE TITLE
Traffic tab in Apps details is duplicated for both clusters

### ISSUE THREAD

**Issue by matejnesuta** [kiali/kiali#6712]
The traffic tab for app details is duplicated for both clusters. This is the detail of west productpage and it feels odd, because there are no graphs of inbound/outbound metrics, nor the minigraph. 
![image](https://github.com/kiali/kiali/assets/45061792/17e84bf4-158a-4075-abdc-cea9fbc5482c)
When I click the "View metrics" link, it shows me a page with no metrics visible. There is also no clusterName parameter in the URL.
![image](https://github.com/kiali/kiali/assets/45061792/6c6f049c-0133-48f6-923a-bae031884c16)

**Comment by jshaughn** [comment]
Maybe same issue as https://github.com/kiali/kiali/issues/6711

**Comment by hhovsepy** [comment]
It seems to be a valid issue to implement, the 'clusterName' param is missing in backend requests for Traffic in Workload, Services and Apps pages.
