### ISSUE TITLE
Replace strings with correct concatenation

### ISSUE THREAD

**Issue by aljesusg** [kiali/kiali#6736]
There are multiple sentences in code with old concatenation, replace them with the new one \`\<string\>\` (**Require template literals instead of string concatenation**):

## Rule:

In ES2015 (ES6), we can use template literals instead of string concatenation.

```ts
var str = "Hello, " + name + "!";
```

```ts
var str = `Hello, ${name}!`;
```

## Example in **kiali** code:

https://github.com/kiali/kiali/blob/efd78c68454efdca5e0baca87d5166766f254163/frontend/src/types/Health.ts#L276

that would be great to replace with
```ts
text: `${prefix}:${thresholdStatus.status === NA ? 'No requests' : `${thresholdStatus.value.toFixed(2)}%`}`
```

More information: http://eslint.org/docs/rules/prefer-template

**Comment by jshaughn** [comment]
I agree that the new way is better, and I would encourage the change as we work on the code, but I'm -1 for a straight refactor unless there is some benefit other than just nicer looking code.  I do already change this when I see it, but you have to be careful not to make a mistake.

**Comment by aljesusg** [comment]
Well...the point is that I am doing these changes for backstage effort, I must do it by repo rules (logically methods and some components with material-ui instead pf are identical - copy/paste).

I agree that it makes no sense make all the changes and I opened the issue looking for a contributor. If you want we can close it.

**Comment by jmazzitelli** [comment]
I believe this is getting taken care of with the linter stuff we now have in  place. I'm seeing PRs that are getting created with these changes. So this issue may be getting implemented as time marches forward and the linter forces devs to make these changes.
