### ISSUE TITLE
Gateway badge is not being applied to gateways in the graph

### ISSUE THREAD

**Issue by jshaughn** [kiali/kiali#6740]
It looks like the server is not reporting the Gateway hosts, which makes the UI think it's not a gateway.  Looks like this has been an issue for several releases...

**Comment by lonnixrdc** [comment]
Here is an example: in the setup shown below there are actually 2 gateways using the same istio-ingressgateway deployment but the UI doesn't show anything about either of them 
![image](https://github.com/kiali/kiali/assets/108305018/f1ed1474-73d2-4d8b-8aaf-229d1c3d207c)

**Comment by jshaughn** [comment]
We should backport this to 1.73 (careful of the icon name change, that may not be necessary).

**Comment by aljesusg** [comment]
Needed the backport to 1.73 then we can close this one

**Comment by jshaughn** [comment]
It's not really necessary to have the original issue open to perform the backport.  But thanks for the reminder!
