### ISSUE TITLE
Add cluster_name support for run-kiali.sh hack script

### ISSUE THREAD

**Issue by jshaughn** [kiali/kiali#6742]
`run-kiali.sh` is not working well if Istio is installed with an unset cluster name.  In this scenario I had to locally update `hack/run-kiali-config-template.yaml` with:

```
kubernetes_config:
  cluster_name: "Kubernetes"
```

`run-kiali.sh` should handle the default cluster name scenario, or be configurable.

**Comment by jshaughn** [comment]
I think what is happening is we may be querying Istio itself and it is probably returning an empty cluster_name.  In general we, Kiali, then default to "Kubernetes" (as does Istio for things like telemetry), but for this run-kiali scenario we were not inserting the default.  Setting the variable is working, though.

**Comment by nrfox** [comment]
> I think what is happening is we may be querying Istio itself and it is probably returning an empty cluster_name. In general we, Kiali, then default to "Kubernetes" (as does Istio for things like telemetry), but for this run-kiali scenario we were not inserting the default. Setting the variable is working, though.

That sounds like a bug then. We should still be able to detect the cluster name even when running outside the cluster and we should still default to `Kubernetes` when we can't. Kiali "detects the cluster name" by looking at the istiod deployment and looking for a `CLUSTER_ID` env var. From what I've seen, this still gets set even when you do not provide a value for cluster id in the mesh config.
