### ISSUE TITLE
Inbound Metrics tab for the Service detail is duplicated for services in different clusters

### ISSUE THREAD

**Issue by matejnesuta** [kiali/kiali#6745]
![image](https://github.com/kiali/kiali/assets/45061792/38cab8bb-e4b8-4571-b2a4-483cdce7f9f6)

**Comment by jshaughn** [comment]
@hhovsepy I saw another "duplication" issue was closed.  Is this one releated?

**Comment by hhovsepy** [comment]
> @hhovsepy I saw another "duplication" issue was closed. Is this one releated?

@jshaughn this one is a separate issue, I decided to have another issue, as different tabs should be handled differently.
