### ISSUE TITLE
setup-kind-ci.sh script fails if it is not executed from root folder

### ISSUE THREAD

**Issue by ferhoyos** [kiali/kiali#6750]
The script setup-kind-ci.sh fails if it is executed from any folder except kiali root:

![image](https://github.com/kiali/kiali/assets/122779323/8ee0c9a4-4da0-4ba5-a714-c004661578c9)

Path to hack/istio/download-istio.sh should be absolute and not relative.

**Comment by jmazzitelli** [comment]
the way we typically handle this in the easiest way is to put a couple lines at the top - find the directory where the script is found, then cd to that directory. At that point, every path in the script can be coded to assume that location (so it doesn't matter where you run the script from, its CWD will always be the location where the script is located).

e.g.
* https://github.com/kiali/kiali/blob/master/hack/ci-minikube-molecule-tests.sh#L12-L14
* https://github.com/kiali/kiali/blob/master/hack/run-kiali.sh#L66-L69

**Comment by aljesusg** [comment]
Needed the backport to 1.73 then we can close this one
