### ISSUE TITLE
Validate kiali and Istio Ambient 1.20

### ISSUE THREAD

**Issue by josunect** [kiali/kiali#6757]
Istio 1.20 is in active development. 
Validate with Istio Ambient.

**Comment by josunect** [comment]
Not working with minikube: 

minikube start --cni=kindnet --driver=docker

✘ CNI encountered an error: failed to wait for resource: resources not ready after 5m0s: context deadline exceeded

Testing with kind: 

Detected Ambient, but no inbound traffic: 
![image](https://github.com/kiali/kiali/assets/49480155/e0f2b18d-d691-433e-bf83-bb0581b8957a)

Graph now look right! 

![image](https://github.com/kiali/kiali/assets/49480155/a894c64d-b2bf-4954-8a6a-93129119c464)

(Reported as tcp traffic). 

Detected Istio ztunnel: 

![image](https://github.com/kiali/kiali/assets/49480155/deee4fb9-7fc1-49d8-8104-d9f73ef964eb)

No traces: 

![image](https://github.com/kiali/kiali/assets/49480155/adcac181-de04-4563-81af-d243fe55feaf)

Waypoint proxy: 

![image](https://github.com/kiali/kiali/assets/49480155/48665aa4-e4bb-43f7-9848-a10a81b245dd)

![image](https://github.com/kiali/kiali/assets/49480155/932a32af-82bf-49eb-ab58-1e518181b440)

**Comment by josunect** [comment]
Kiali validation error KIA1504 for the istio-waypoint gatewayClassName. 

![image](https://github.com/kiali/kiali/assets/49480155/1f46573c-b2d0-4a2c-bce9-91a6ff27dfc2)

After create a waypoint proxy: 

`istioctl x waypoint apply -n bookinfo`

Not sure if this should be an exception in the list? @hhovsepy

**Comment by hhovsepy** [comment]
Hi @josunect, sorry for the late response. The validation for `gatewayClassName` field checks the existence of configured 'gateway_api_classes' in configmap, so the configmap should be like: 
```    
external_services:
  istio:
    gateway_api_classes:
     - name: Waypoint
       class_name: istio-waypoint
     - name: Istio
       class_name: istio  
``` 
By default, the Kiali validations consider "istio" gateway class in configuration, but if any 'gateway_api_classes' specified into configmap, then the default 'istio' also should be specified if it is still used, as in parallel there can be several gateway implementation supported.

**Comment by josunect** [comment]
> Hi @josunect, sorry for the late response. The validation for `gatewayClassName` field checks the existence of configured 'gateway_api_classes' in configmap, so the configmap should be like:
> 
> ```
> external_services:
>   istio:
>     gateway_api_classes:
>      - name: Waypoint
>        class_name: istio-waypoint
>      - name: Istio
>        class_name: istio  
> ```
> 
> By default, the Kiali validations consider "istio" gateway class in configuration, but if any 'gateway_api_classes' specified into configmap, then the default 'istio' also should be specified if it is still used, as in parallel there can be several gateway implementation supported.

Thank you for your response, @hhovsepy ! I will open a related issue to include it as a default.
