### ISSUE TITLE
Graph generation - only fetch workloads for known clusters

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#6769]
As seen in: https://github.com/kiali/kiali/discussions/6761. There can be multiple clusters in telemetry but Kiali may not have access to them. Rather than trying to fetch workloads from these clusters and erroring out, Kiali should just skip clusters that it does not have access to in graph generation.

**Comment by jshaughn** [comment]
Whoops, I didn't see this before converting the Discussion to an issue. Closing as duplicate.
