### ISSUE TITLE
[operator] Custom dashboard yaml parsing incorrectly

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#6771]
Custom dashboard configuration does not work when using the kiali operator. The issue is that the custom dashboard config expects the yaml to be in `camelCase` but the operator converts everything to `snake_case`: https://kiali.io/docs/configuration/custom-dashboard/#declaring-a-custom-dashboard.

**Comment by jmazzitelli** [comment]
adding backport-needed label
