### ISSUE TITLE
Info icon in yaml editor's overview panel is not aligned properly

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#6773]
In the istio config yaml editor, the info icon on the right hand side overview panel is not vertically aligned properly with the rest of the elements.

![Screenshot from 2023-10-24 16-48-25](https://github.com/kiali/kiali/assets/6226732/cd204a9b-d374-4149-8b69-5ad1c71248c6)

IMO this info icon can be removed entirely because it's only purpose is showing a tooltip when you hover over it that merely duplicates the information that can already be seen from the istio config editor namely "creationTimestamp" and "resourceVersion":

![Screenshot from 2023-10-24 16-48-04](https://github.com/kiali/kiali/assets/6226732/7c20abe2-e7cd-4930-9cf2-c8f568827afa)

If Kiali should duplicate this info on the overview panel, then IMO it should just be plaintext on the panel rather hidden in an "info" icon/tooltip.

**Comment by ferhoyos** [comment]
Not only this icon, almost all info icons are not aligned properly after PF5 upgrade. I have fixed some of them in Table upgrade PR (https://github.com/kiali/kiali/pull/6695) and I will check the rest after upgrading PF to version 5.1 (https://github.com/kiali/kiali/issues/6768).

**Comment by ferhoyos** [comment]
Fixed with PR #6836
