### ISSUE TITLE
[e2e] Tests should check status code before attempting to unmarshal into json

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#6777]
Many e2e tests attempt to unmarshal the kiali api response before checking the status code resulting in an unmarshalling error. This can mask the response from the server making it harder to debug the tests. The status code should first be checked before unmarshalling.

See: https://github.com/kiali/kiali/actions/runs/6413559944/job/18045431679 for an example of the error.

**Comment by PrinsonF77** [comment]
Hey, is this issue solved yet?

**Comment by jshaughn** [comment]
hi @PrinsonF77 , I'm going to say no just based on the fact that this is Open, still in the Backlog there are no PRs...   Did you want to contribute here?

**Comment by PrinsonF77** [comment]
Yes. Can you assign it to me?
Also according to what I've seen at https://github.com/kiali/kiali/blob/master/tests/integration/tests/kiali_urls_test.go , 
`func TestGrafana(t *testing.T)` already implements this. Something similar has to be done for the tests that do not do this check right?

**Comment by nrfox** [comment]
Sure the issue is here inside of the `Grafana()` call (and everywhere else this happens): https://github.com/kiali/kiali/blob/9cb961f10a7e7c9ce98765b4094402ee95abaa7b/tests/integration/utils/kiali/kiali_client.go#L605-L616

Until we check the status code, we can't safely unmarshal into `status := new(models.GrafanaInfo)` since the server response for 404s for non 200 is usually just a string. When the unmarshal fails, it masks the actual error message from the server that resides in the response.Body.

What we need is to stop unmarshaling non-200 responses inside of the client calls. It looks like some tests still need to check the status code so I wouldn't return an error here for non-200 responses. It doesn't appear that anything uses the response body directly though so you can simply log the string of `response.Body` for non-200 responses.

**Comment by PrinsonF77** [comment]
Thanks for the explanation. Will start working on it

**Comment by nrfox** [comment]
The kiali client methods can now use this method: https://github.com/kiali/kiali/blob/470b68b0909efc0e1adf75b1675efc20b39f1f42/tests/integration/utils/kiali/kiali_client.go#L647-L663 which will check the status code before unmarshaling. We just need to update the kiali client methods to use this new method.

**Comment by PrinsonF77** [comment]
Hey @jshaughn @nrfox . Will be taking this up. Sorry for the delay.
@nrfox since `getRequestandUnmarshallInto` only returns the error right now, there is no way to get the status code as well, which is supposed to be returned from the kiali client methods. Will be modifying this function to also return the code. Does that sound good?

**Comment by nrfox** [comment]
@PrinsonF77 I would say just update the methods that _don't_ return a status code to use that `getRequestAndUnmarshalInto` function and leave the methods that already return a status code as they are. I'm guessing the status code is being returned because some tests _want_ to check for a non-200 status. Probably there should be some lower level method like `DoRequest` that doesn't do any unmarshaling that those tests should use instead of one of the "client methods". If you're feeling very ambitious you can try to implement that otherwise just update the existing client methods that don't return a status to use `getRequestAndUnmarshalInto`.

**Comment by PrinsonF77** [comment]
@nrfox Most of the kiali client methods return a status code. Even the Grafana method that was given as an example in https://github.com/kiali/kiali/issues/6777#issuecomment-1819667034 . 
By modifying `getRequestAndUnmarshalInto` to also return the code, I can rewrite the `Grafana()` and other methods as such

**Comment by nrfox** [comment]
> I think this would allow for most of the kiali client methods to be rewritten in this way which reduces the redundancy and helps with returning better error messages. 

That sounds good.
