### ISSUE TITLE
[UI] Modal of the Custom time range doesn't overlap some of the text from the Inbound/Outbound tab

### ISSUE THREAD

**Issue by matejnesuta** [kiali/kiali#6781]
Probably a nitpick, but when browsing Kiali with a smaller screen (for example my laptop), this can occur. 
![image](https://github.com/kiali/kiali/assets/45061792/6ae25958-5ac4-4bb9-97ab-f05494ef0538)

**Comment by jshaughn** [comment]
looks like a minor z-index issue.
