### ISSUE TITLE
No Kiali Helm Chart 1.75.1 

### ISSUE THREAD

**Issue by rohitsakala** [kiali/kiali#6794]
404 error on  https://kiali.org/helm-charts/kiali-server-1.75.1.tgz

**Comment by jmazzitelli** [comment]
v1.75.1 was a hot fix to the Kiali Server container image that moves to Go 1.20.10 to pick up the fix to the http2 DDoS CVE. It is published on [quay.io](https://quay.io/repository/kiali/kiali?tab=tags). A v1.75.1 Server Helm chart was not released; the v1.75.0 Server Helm chart can be used to install the v1.75.1 Kiali Server container (see below for instructions).

The Server Helm chart v1.76.0 is scheduled to be released in a few days - Monday, October 30, 2023 to be exact. That will pull in Kiali Server v1.76.0 by default, which will also contain this upgrade to Go 1.20.10.

To install the Kiali Server container image v1.75.1 using the already released v1.75.0 Server Helm chart, you simply use the Helm value `--set deployment.image_version=v1.75.1` to bump up the container image version that the Helm charts will deploy.

For example:

```
helm install --namespace istio-system --set deployment.image_version=v1.75.1 kiali-server kiali/kiali-server
```

Once that command completes, the Kiali Server v1.75.1 is running as confirmed by the following:

```
$ kubectl get pods -n istio-system -l app.kubernetes.io/name=kiali -o jsonpath='{..spec.containers..image}{"\n"}'
quay.io/kiali/kiali:v1.75.1
```

and

```
$ kubectl logs -n istio-system -l app.kubernetes.io/name=kiali --tail=-1 | head -n2
{"level":"info","time":"2023-10-27T23:52:36Z","message":"Adding a RegistryRefreshHandler"}
2023-10-27T23:52:36Z INF Kiali: Version: v1.75.1, Commit: 0e91b8dd97e634b5bfd4e18051c7d40973277553, Go: 1.20.10
```
