### ISSUE TITLE
Workload logs - improve appearance of checkboxes

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#6811]
This might just be personal preference but the appearance of the checkboxes doesn't look great and doesn't fit the style of other checkboxes in the UI:

![Screenshot from 2023-11-02 09-07-59](https://github.com/kiali/kiali/assets/6226732/3d9a3188-449d-4c7a-9432-6b54cc4d99b8)

Compare to the metrics page checkboxes:

![Screenshot from 2023-11-02 09-10-42](https://github.com/kiali/kiali/assets/6226732/9030f153-b699-4488-8494-454e56c01339)

This is probably just a matter of getting rid of the background highlighting.

**Comment by nrfox** [comment]
I haven't looked into what it takes to change this but it's probably simple and this would be a good first issue.

**Comment by jshaughn** [comment]
It doesn't match the others because it's acting as a legend for the integrated logs.  The colors represent the same colors as in the log entry screen.  Any alternative would need to solve that issue.

**Comment by ferhoyos** [comment]
Backport needed to 1.73 to improve appearance of checkboxes in OSSMC
