### ISSUE TITLE
Minor misalignments related to the remote Istio Control plane

### ISSUE THREAD

**Issue by matejnesuta** [kiali/kiali#6852]
This happens on the Overview page when the browser is squashed.
![image](https://github.com/kiali/kiali/assets/45061792/653398fb-79b8-4165-82dd-a7fd4dd11ff8)

**Comment by sakshamcodes01** [comment]
@matejnesuta is this issue still open?

**Comment by jshaughn** [comment]
@sakshamcodes01, I think this is now obsolete given changes to the Overview page and the introduction of the Mesh page.  I am going to close it.  Would you like to try https://github.com/kiali/kiali/issues/7550?

**Comment by sakshamcodes01** [comment]
Sure. Giving it a look. @jshaughn
