### ISSUE TITLE
[Kiali-operator Helm Chart] Mount /tmp instead of /tmp/ansible-operator/runner as emptyDir to enable read-only root filesystem

### ISSUE THREAD

**Issue by eli-gc** [kiali/kiali#6888]
I came across an issue when trying to enable read-only root filesystem for Kiali-operator. The operator tries to write to kubeconfig in /tmp directory of the root filesystem. There is an existing emptyDir mount for /tmp/ansible-operator/runner for the ansible logging volume. I am proposing that /tmp be mounted to this emptyDir instead. This should preserve previous functionality of the Ansible logging volume while also enabling read only root filesystem. 

This work is related to #5810 

I'm going to test this and will make a PR if no one has any objections.

**Comment by eli-gc** [comment]
I'm testing the mounting but I am having trouble with ansible trying to write to /opt/ansible/.ansible/tmp. Anyone know if there is a way to change this path?

**Comment by eli-gc** [comment]
I tried to set DEFAULT_LOCAL_TMP = /tmp and I confirmed this env variable is set in my container, but Ansible is still writing to /opt/ansible/.ansible/tmp

**Comment by jmazzitelli** [comment]
I don't know the answer; sounds like a good question to ask the ansible operator SDK folks here: https://github.com/operator-framework/ansible-operator-plugins/issues/new?assignees=&labels=&projects=&template=support-question.md&title=

**Comment by jmazzitelli** [comment]
Here's the answer I was told:

```
DEFAULT_LOCAL_TMP is the configuration name;
the env var is ANSIBLE_LOCAL_TEMP
https://docs.ansible.com/ansible/latest/reference_appendices/config.html#default-local-tmp
```

**Comment by eli-gc** [comment]
I tried it and it works! Thank you so much!

From: John Mazzitelli ***@***.***>
Date: Tuesday, November 28, 2023 at 7:28 PM
To: kiali/kiali ***@***.***>
Cc: Eric Li ***@***.***>, Author ***@***.***>
Subject: Re: [kiali/kiali] [Kiali-operator Helm Chart] Mount /tmp instead of /tmp/ansible-operator/runner as emptyDir to enable read-only root filesystem (Issue #6888)
Caution: This is an external email and has a suspicious subject or content. Please take care when clicking links or opening attachments. When in doubt, contact your IT Department


Here's the answer I was told:

DEFAULT_LOCAL_TMP is the configuration name;

the env var is ANSIBLE_LOCAL_TEMP

https://docs.ansible.com/ansible/latest/reference_appendices/config.html#default-local-tmp

**Comment by eli-gc** [comment]
I tried it and it works! Thank you so much!

**Comment by jmazzitelli** [comment]
Thanks, @eli-gc ... looks good... All merged!
