### ISSUE TITLE
React-scripts replacement

### ISSUE THREAD

**Issue by ferhoyos** [kiali/kiali#6889]
Kiali project was created with CRA tool (Create React APP), which provides a set of scripts (react-scripts) to bundle and develop React applications with opinionated configuration and dependencies (using webpack). Although react-scripts works fine in Kiali application, these scripts seem deprecated (last release was 2 years ago), producing dependency outdates that are hard to solve.

The idea is to replace react-scripts with more modern tool (Vite, Next.js, Remix) that is actively maintained by the community.

**Comment by ferhoyos** [comment]
After some investigation I think there is no good candidate to replace react-scripts in Kiali project:

- Vite is an awesome build tool but it does not support many things already implemented in Kiali:
  - Vite is ESM only, so it does not support `require` statements. Currently we have 2 `requires` in Kiali: `js-yaml` and `cy-node-html-label` (https://www.github.com/vitejs/vite/issues/3409)
  - Vite does not support global variable (https://www.github.com/vitejs/vite/issues/2618) 
  - Vite does not allow to have non-existing imports (there is one bogus import in react-virtualized library -> https://www.github.com/bvaughn/react-virtualized/issues/1632)
  - Although the above issues have workarounds (some of them would take some time), the most important disadvantage is that Vite uses ESBuild (dev) and Rollup (prod) as bundler tools. However, OSSMC, as a dynamic plugin of Openshift, must use Webpack. In this case I think it is preferred to use same bundle tool to avoid any current or future incompatibility (95% of OSSMC code comes from Kiali repository).

- Next.js and Remix are more than build tools, they are React frameworks for building web applications. They are great to build React applications from scratch because they provide multiple stuff out of the box (data fetching, routing, etc.), but on the other hand it would be very hard and time consuming to migrate such a big and complex application like Kiali to their structure.

Therefore we will continue with react-scripts. Its dependencies will be updated in an indirect way like we did in https://github.com/kiali/kiali/pull/6568 (although it takes some extra time due to react-scripts deprecation). If in the future we need a major update of any of react-script dependencies, we can always `eject` the react-script configuration and handle all webpack configuration by ourselves (https://create-react-app.dev/docs/available-scripts/#npm-run-eject).

**Comment by jshaughn** [comment]
@ferhoyos Thanks for doing this investigation.  I agree that we should remain with react-scripts until a better option emerges, or we are forced to eject.

**Comment by jshaughn** [comment]
small update: we no longer use `cy-node-html-label`

**Comment by ferhoyos** [comment]
Two years is a long time in the frontend world. Currently, there is a new tool called Rsbuild, which is similar to react-scripts but uses Rspack, a modern Rust-based web bundler. The advantage is that Rspack is compatible with Webpack, which could address the OSSMC compatibility limitations we face (since OSSMC must maintain Webpack as the only supported bundler for OpenShift console plugins). Let's reopen this issue and investigate if Rsbuild can replace react-scripts

**Comment by nrfox** [comment]
It's written in rust it must be superior. That does sound promising though.

**Comment by jshaughn** [comment]
Adding to the sprint backlog but priority is less than overview page work.
