### ISSUE TITLE
Go Panic when Grafana returns 401 Unauthorized

### ISSUE THREAD

**Issue by leosunmo** [kiali/kiali#689]
**General remarks**
I've encountered a Go panic when running Kiali against a password protected Grafana instance as the Grafana handler doesn't check for HTTP response code and doesn't marshal in to a struct, but rather uses type assertion.

**Describe the bug**
When trying to connect the my Grafana instance Kiali panics with the following:
```
2018/11/29 20:07:25 http: panic serving 172.22.10.163:56216: interface conversion: interface {} is map[string]interface {}, not []interface {}
goroutine 136363 [running]:
net/http.(*conn).serve.func1(0xc4203f9680)
	/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/net/http/server.go:1697 +0xd0
panic(0x11ca4a0, 0xc420e68240)
	/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/runtime/panic.go:491 +0x283
github.com/kiali/kiali/handlers.findDashboardPath(0xc420551660, 0x20, 0x133b5dd, 0x1b, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/kiali/kiali/handlers/grafana.go:102 +0x578
github.com/kiali/kiali/handlers.getGrafanaInfo(0x13ae390, 0x13ae388, 0xc420391da0, 0x1c17100, 0x19ff4faa164b, 0xbef82f9f65a9aad8)
	/home/travis/gopath/src/github.com/kiali/kiali/handlers/grafana.go:66 +0x316
github.com/kiali/kiali/handlers.GetGrafanaInfo(0x1bb9280, 0xc4207840e0, 0xc4200f6600)
	/home/travis/gopath/src/github.com/kiali/kiali/handlers/grafana.go:24 +0x3d
net/http.HandlerFunc.ServeHTTP(0x13ae2b8, 0x1bb9280, 0xc4207840e0, 0xc4200f6600)
	/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/net/http/server.go:1918 +0x44
github.com/kiali/kiali/routing.metricHandler.func1(0x1bb9280, 0xc4207840e0, 0xc4200f6600)
	/home/travis/gopath/src/github.com/kiali/kiali/routing/router.go:73 +0x97
net/http.HandlerFunc.ServeHTTP(0xc4203bd680, 0x1bb9280, 0xc4207840e0, 0xc4200f6600)
	/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/net/http/server.go:1918 +0x44
github.com/kiali/kiali/config.AuthenticationHandler.func1(0x1bb9280, 0xc4207840e0, 0xc4200f6600)
	/home/travis/gopath/src/github.com/kiali/kiali/config/authentication.go:31 +0x3ad
net/http.HandlerFunc.ServeHTTP(0xc4203c9200, 0x1bb9280, 0xc4207840e0, 0xc4200f6600)
	/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/net/http/server.go:1918 +0x44
github.com/kiali/kiali/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc420367a40, 0x1bb9280, 0xc4207840e0, 0xc4200f6600)
	/home/travis/gopath/src/github.com/kiali/kiali/vendor/github.com/gorilla/mux/mux.go:162 +0xed
net/http.(*ServeMux).ServeHTTP(0x1c16860, 0x1bb9280, 0xc4207840e0, 0xc4200f6200)
	/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/net/http/server.go:2254 +0x130
net/http.serverHandler.ServeHTTP(0xc42031d110, 0x1bb9280, 0xc4207840e0, 0xc4200f6200)
	/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/net/http/server.go:2619 +0xb4
net/http.(*conn).serve(0xc4203f9680, 0x1bb9dc0, 0xc420053040)
	/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/net/http/server.go:1801 +0x71d
created by net/http.(*Server).Serve
	/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/net/http/server.go:2720 +0x288
```

The culprit seems to be https://github.com/kiali/kiali/blob/v0.10/handlers/grafana.go#L102 which expects a slice of interfaces, but in my case receives a map[string]interface{} because Grafana returns `{"message":"Unauthorized"}`.

Grafana sets the correct HTTP status code, so we should be able to check for that and provide a proper message to the front-end.
Curl:
```
[root@kiali-5c79c7679f-smmpq kiali]# curl -i grafana.monitoring.svc.cluster.local:3000/api/search?query=Istio%20Workload%20Dashboard
HTTP/1.1 401 Unauthorized
Cache-Control: no-cache
Content-Type: application/json; charset=UTF-8
Expires: -1
Pragma: no-cache
Set-Cookie: grafana_sess=2d3a50a4d0b8b4a4; Path=/; HttpOnly
Date: Thu, 29 Nov 2018 20:29:19 GMT
Content-Length: 26

{"message":"Unauthorized"}
```

Grafana provides a nice way to handle API tokens (http://docs.grafana.org/http_api/auth/) which we should be utilising.

**Versions used**
Kiali: v0.10.1
Istio: 1.0.4
Kubernetes flavour and version: AWS EKS version v1.10.3-eks

**To Reproduce**
1. Use any kind of Authorization on your Grafana instance
2. Configure a correct Grafana URL in `external_services.grafana.url`
3. Start Kiali and load the first page (https://kiali.example.org/console/overview)
4. Tail container logs in Kubernetes (you get a "bad gateway" in the UI)

**Expected behavior**
Ideally we'd check for the HTTP status code response and bubble up a good error message to the front-end as well as avoid a Go panic.

The next step would obviously be to give us the option to use Grafana API tokens properly.

**Comment by abonas** [comment]
cc @jotak

**Comment by jotak** [comment]
@leosunmo thanks for the detailed description, I'm on it

**Comment by jotak** [comment]
I'll provide a fix for the panic issue, and also create another ticket for feature request about Grafana authentication (not for very short term)

**Comment by pilhuhn** [comment]
@leosunmo Do you think you would be able to provide a fix or a patch for the authentication needed?

**Comment by jotak** [comment]
Feature request added here: https://issues.jboss.org/browse/KIALI-2050

**Comment by leosunmo** [comment]
@pilhuhn @jotak Quickly threw this together https://github.com/kiali/kiali/pull/711. Hopefully it's not too messy!

**Comment by jotak** [comment]
Closing as PRs are merged. Thanks again @leosunmo for your contrib
