### ISSUE TITLE
Apply new eslint rules only to edited files

### ISSUE THREAD

**Issue by ferhoyos** [kiali/kiali#6893]
Due to Kiali application size it is very hard to introduce new eslint rules like https://github.com/kiali/kiali/issues/6736 (the number of errors after applying the eslint rule to whole Kiali application is so high that is impossible to handle correctly). For this reason I think we could apply new eslint rules only to edited files where developer is working (`yarn lint:precommit` command). 

With this approach the new eslint rule is applied little by little to Kiali applicatiion. After some time these eslint rules could be incorporated to general eslint configuration when the number of errors is manageable.

**Comment by jshaughn** [comment]
This seems like a fair compromise, especially now that the PF5 update is complete.  Although we may still need to skip that precommit hook on wide PRs, like the I18N PR, for example.

**Comment by ferhoyos** [comment]
If it is just for special big PRs like i18n we can disable the precommit lint with the wide PR and immediately enable it with another PR when merged.

**Comment by jshaughn** [comment]
I think with this we can probably close #6736.
