### ISSUE TITLE
Ambient - Envoy logs

### ISSUE THREAD

**Issue by josunect** [kiali/kiali#6898]
How Envoy logs will be visualized in Kiali? 

Example of ztunnel logs from the istio-system namespaces: 
![image](https://github.com/kiali/kiali/assets/49480155/8ba517b9-688e-40dd-a364-cab6182081b0)

- It is possible to associate these logs with a specific workload? It is possible to filter? 
- The performance will be good? 
- Why is shown as istio-proxy? 

Waypoint proxy logs: 

![image](https://github.com/kiali/kiali/assets/49480155/d36e27c4-bb38-48fe-ab2b-aed0f43a76db)

**Comment by jshaughn** [comment]
Moving to sprint backlog, I think we need to start figuring out how ambient, the lack of sidecar proxy logs, the new waypoint proxy logs, will impact our log views.

**Comment by josunect** [comment]
I think we could focus first in the ztunnel logs. 

At the moment, the ztunnel logs are looking like this (INFO): 

```
2024-04-04T07:16:36.301267Z  INFO proxy{uid=66fe00fe-93a1-45b9-a966-5e4b9d3ea4cf}: ztunnel::proxy::inbound_passthrough: accepted connection source=10.244.0.7:39864 destination=10.244.0.15:9080 component="inbound plaintext"
2024-04-04T07:16:36.302922Z  INFO proxy{uid=66fe00fe-93a1-45b9-a966-5e4b9d3ea4cf}: ztunnel::proxy::inbound_passthrough: connection complete source=10.244.0.7:39864 destination=10.244.0.15:9080 component="inbound plaintext"
```

It would be possible to correlate the logs with the service IP/Port. 
The workload is correlated with the service now. 

Regarding visualization, that could be seen as the Envoy proxy, filtering by IP: 

![image](https://github.com/kiali/kiali/assets/49480155/105c36ee-0af6-4971-909e-c71015cbf208)

Other options: 

- Which information is available in DEBUG/TRACE? The filtering could be different. But I guess Kiali shouldn't/cannot change the default value? 
- Other ways to obtain this information? 
- Visualization: Use a new ztunnel tab with ztunnel logs and other info (Like the envoy)
