### ISSUE TITLE
Deprecate and remove Jaeger exporter

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#6908]
Kiali exports traces to help debug/monitor Kiali itself: https://kiali.io/docs/configuration/kialis.kiali.io/#.spec.server.observability.tracing.

Kiali currently supports both the jaeger and the otel exporter. Since jaeger itself can ingest otel traces and exporting otel grants more flexibility for where those traces can be sent, Kiali should just remove the jaeger exporter and use the otel one.

Note that this will probably also involve removing: https://kiali.io/docs/configuration/kialis.kiali.io/#.spec.server.observability.tracing.collector_url in favor of different config opts where you provide the `hostname:port` and/or `path` since that is the format that the otel sdk expects. Kiali should by default send traces to the otel endpoint rather than the jaeger one: `http://jaeger-collector.istio-system:4318/v1/traces`.

**Comment by jshaughn** [comment]
I'm +1 to this but we will need to officially deprecate in the release notes (via kiali.io PR).  I'd say try to minimize CRD changes.
