### ISSUE TITLE
Use client-go's service account token client refresh

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#6924]
### What do you want to improve?

This is a "tech debt" issue. To address: https://github.com/kiali/kiali/issues/5070, the ability to watch the service account token file and refresh Kiali's kube client/cache was added. It turns out this functionality already exists in the kubernetes go client. In order for this to work however, when you create the `rest.Config` you need to set the `TokenFile` field per: https://github.com/kubernetes/client-go/blob/84a6fe7e4032ae1b8bc03b5208e771c5f7103549/transport/round_trippers.go#L283-L302

The way that Kiali is constructing the `rest.Config`, Kiali does not set this. 
https://github.com/kiali/kiali/blob/9a11e24d993ef34be0de7fbad3d6df946a530bfa/kubernetes/client_factory.go#L88-L93

Kiali should only set this for the Kiali Service Account Client but once that field is set, the client should be able to refresh itself which would simplify the client and cache.

### What is the new behavior?

Token refresh works by relying on the underlying client-go to do the refresh.

**Comment by jmazzitelli** [comment]
> In order for this to work however, when you create the `rest.Config` you need to set the `TokenFile` field per:

I believe you mean `BearerTokenFile` as declared here: https://github.com/kubernetes/client-go/blob/v12.0.0/rest/config.go#L74-L77
