### ISSUE TITLE
patternfly graph not showing node decorators

### ISSUE THREAD

**Issue by jshaughn** [kiali/kiali#6926]
The patternfly graph is no longer showing node decorators, it seems like a regression in PFT with PF5.  The issue in our code is [here](https://github.com/kiali/kiali/blob/master/frontend/src/pages/GraphPF/GraphPFElems.tsx#L162-L164): 

This used to work, but surrounding the decorator with a Tooltip now stops the decorator from rendering:
```
    <Tooltip content={!!tooltip ? tooltip : icon.text}>
      <Decorator x={x} y={y} radius={DEFAULT_DECORATOR_RADIUS} showBackground icon={React.createElement(icon.icon)} />
    </Tooltip>
```

We can do this, but we lose the tooltip, and the tooltip is important in order to explain what the decorator means.
```
      <Decorator x={x} y={y} radius={DEFAULT_DECORATOR_RADIUS} showBackground icon={React.createElement(icon.icon)} />
```

@leandroberetta , should we ask Jeff whether this is expected or if there is a workaround?

**Comment by jshaughn** [comment]
We should test this for 1.73/ossmc because it may only be a problem using PF5.

**Comment by leandroberetta** [comment]
This is not happening on OSSMC where PF4 is used. This seems to be an issue with PF5, for now, I created the following PR to remove the tooltips:

https://github.com/kiali/kiali/pull/6933

**Comment by jeff-phillips-18** [comment]
PatternFly 5 updated tooltips to wrap the content in a `<div>` which breaks  when used in an `<svg>`. To avoid the div creation set the `triggerRef` on the tooltip to be the ref of the content element. See https://github.com/patternfly/react-topology/blob/main/packages/module/src/components/DefaultCreateConnector.tsx#L59-L73 as an example.

**Comment by leandroberetta** [comment]
@jeff-phillips-18 thanks for the help!. 

@jshaughn I updated the PR to include Jeff's suggestions and now it's working again.
