### ISSUE TITLE
Scrollbar in Workloads Logs view

### ISSUE THREAD

**Issue by josunect** [kiali/kiali#6982]
### Describe the bug

There is no horizontal scrollbar in Firefox: 

![image](https://github.com/kiali/kiali/assets/49480155/9b07df34-bb98-416f-98ea-7dc069781149)

Which makes impossible to read large lines. 

The behavior in Chrome is different. There are vertical/horizontal scrollbar, but if we zoom in, a double scrollbar appears, which makes it confusing (It looks like the scrollbar is not working because the second one is hidden): 

![image](https://github.com/kiali/kiali/assets/49480155/7937146b-6003-4ebd-a7da-6ee483cd2473)

### Expected Behavior

- I think there should be horizontal scrollbar in Firefox, and no double scrollbars in Chrome. 

### What are the steps to reproduce this bug?

1. Go to a workload, and click in the log tabs.
2. Zoom in with Chrome

### Environment
*Learn about how to determine versions [here](https://kiali.io/docs/faq/general/#how-do-i-determine-what-version-i-am-running).*

- **Kiali version:** Running Kiali from master
- **Istio version:** Istio 1.20
- **Kubernetes impl:** 
- **Kubernetes version:** 
- **Other notable environmental factors:**

**Comment by ferhoyos** [comment]
Issue not present in 1.73 branch, so no backport is needed.
