### ISSUE TITLE
Extra padding in long namespace names

### ISSUE THREAD

**Issue by josunect** [kiali/kiali#6998]
### Describe the bug
In the Overview page, there is an extra padding in long namespace names. An example: 

![image](https://github.com/kiali/kiali/assets/49480155/71f6e29e-639a-42da-a54b-b41d9a5be6e9)

### Expected Behavior
No extra padding for long namespace names

### What are the steps to reproduce this bug?

1. Create a long namespace name, ex. `kubectl create ns this-is-a-long-namespace`
2. Go to the overview page

### Environment
*Learn about how to determine versions [here](https://kiali.io/docs/faq/general/#how-do-i-determine-what-version-i-am-running).*

- **Kiali version:** 1.78 (Dev version from master)
- **Istio version:** 1.21
- **Kubernetes impl:** 
- **Kubernetes version:** 
- **Other notable environmental factors:**

**Comment by ferhoyos** [comment]
If the namespace name is too long, the ellipsis truncate does not work well:

![image](https://github.com/kiali/kiali/assets/122779323/00aabafa-ceb8-4a57-bb77-895ed4f22998)
