### ISSUE TITLE
support scripts exclusive for Openshift only

### ISSUE THREAD

**Issue by ScriptingShrimp** [kiali/kiali#7004]
https://github.com/kiali/kiali/blame/f443264c281751286777d30bf6e3e9593fa4efc2/hack/istio/wait-for-namespace.sh#L3C7-L3C7

This script does support only Openshift environment, since there is only `oc` command used , not `kubectl`. Moreover I can't see any reference in GitHub actions to this file.

**Comment by jshaughn** [comment]
@ScriptingShrimp Can you or Matej ensure that the 1.73 work is also applied to master?

**Comment by mkralik3** [comment]
@jshaughn The (#6997 ) is not applied to master since the fix was only Maistra related ( which was already removed from master )

**Comment by jshaughn** [comment]
@ScriptingShrimp Can this be closed?
