### ISSUE TITLE
Potential runtime error in kube_cache.GetK8sGateways

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#7006]
Happens on Kiali master.
Start the Kiali when K8s GW CRDs are not created.
Apply K8s GW CRDs.
Immediately refresh the Kiali page.
Runtime panic nil pointer error in logs, on any of those methods `kube_cache.GetK8sGateways`.

This is because the `userClient.IsGatewayAPI()` return 'true' when the CRDs exist, but in fact the `k8sgatewayLister` was not created while starting the Kiali first time.
https://github.com/kiali/kiali/blob/master/kubernetes/cache/kube_cache.go#L397
![Screenshot from 2024-01-05 09-52-45](https://github.com/kiali/kiali/assets/604313/a7621bb9-cd07-4043-9829-79cf8e975632)

And any call to `k8sgatewayLister` causes nil error.
https://github.com/kiali/kiali/blob/master/kubernetes/cache/kube_cache.go#L1504
![Screenshot from 2024-01-05 09-55-57](https://github.com/kiali/kiali/assets/604313/5187cc66-1637-459d-a61f-699e4934c804)

**Comment by jshaughn** [comment]
@hhovsepy , I think this issue should have been closed by https://github.com/kiali/kiali/pull/7008, no?  I'll close, please re-open if I am wrong.
