### ISSUE TITLE
cypress - migrate to `cy.session` for login/auth

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#7018]
### What do you want to improve?

[cy.session](https://docs.cypress.io/api/commands/session) seems to be the preferred way to preserve session state (cookies) across test runs. We should migrate to using it eventually in the custom `login` command.

- [x] upstream: kind, crc
- [ ] downstream: OCP, cloud (AWS) a IBM, interop
- [x] additionally for ROSA cluster there is no my_htpasswd_provider provider 
- [ ] other cluster in our infra have my_htpasswd_provider enabled (or similar and its configurable via  `export CYPRESS_OC_IDP` this must be tested right after merge
- [ ] obtain CSRF token for Openshift needed? Isn't this already covered by `cy.session`?
- [ ] one global `cy.session` for whole suite that should work in all conditions mentioned above

**Comment by nrfox** [comment]
@matejnesuta is this one completed now?

**Comment by matejnesuta** [comment]
Hello. I think so.
