### ISSUE TITLE
Error fetching Istio deployment status of the remote control plane in the Primary remote deployment

### ISSUE THREAD

**Issue by matejnesuta** [kiali/kiali#7053]
### Describe the bug

There is a 500 return code and an error notification for every refresh in Kiali. 
![image](https://github.com/kiali/kiali/assets/45061792/9db2171d-e404-4cf2-8064-e4adf0c3e7d2)

### Expected Behavior
No error notification about remote istio deployment status should be displayed to user, as this is the Primary remote setup 

### What are the steps to reproduce this bug?

I used the `./hack/run-integration-tests.sh --test-suite frontend-primary-remote -so true` to run the Primary Remote with KinD

### Environment
Kiali v1.80.0-SNAPSHOT (f64891551a399aa35850ab552215a241294cf0bf)
Kiali Container v1.80.0-SNAPSHOT
Service Mesh Istio 1.20.2
Prometheus 2.41.0
Kubernetes v1.27.3

**Comment by nrfox** [comment]
This will need to get backported to v1.79 as well
