### ISSUE TITLE
Kiali Performance and Scalability testing

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#7058]
This is an Epic for all Performance and Scalability  tasks and sub-epics to do for Kiali project.

One of the requirements from Kiali customers is the performance of the Kiali from UI/UX perspective, with a load of many namespaces/workloads/services and a metrics loaded for several days.

TODO: Add requirements and subtasks.

- [x] #7088
- [x] Testing environment preparation.
- [x] #7174
- [ ] #7699
- [x] #7076
- [x] #7097
- [x] #7397
- [ ] #7479

**Comment by nrfox** [comment]
Does this epic cover scalability improvements or is it only for testing?

**Comment by hhovsepy** [comment]
I think we need to include all the improvements in this epic as sub-epics, so right both 1. and 2. points are valid subtasks here.

**Comment by jmazzitelli** [comment]
Now that we have pprof integrated in the Kiali server (to turn it on, set `spec.server.profiler.enabled` to `true` in Kiali CR), it would be a good thing to learn how to use and analyze the pprof data. Here's a blog post on a quick tutorial: https://go.dev/blog/pprof

**Comment by hhovsepy** [comment]
Most tasks of this epic are done. The remaining subtasks are logged as separate issues and can be tracked outside of this epic.
