### ISSUE TITLE
[MC] Visual bug on the Overview page upon refresh

### ISSUE THREAD

**Issue by matejnesuta** [kiali/kiali#7063]
### Describe the bug

When refreshing in the Primary-Remote/Multi-Primary deployment, both cards are firstly loaded with the same stats, then the second one gets refreshed with right stats. This is mostly visible when refresh is set on 10 seconds and multiple namespaces are visible on the Overview page.
[Screencast from 2024-01-29 09-45-59.webm](https://github.com/kiali/kiali/assets/45061792/2949a47c-4d88-4800-af3b-45a34d699442)

### Environment
Kiali v1.80.0-SNAPSHOT (37ae912f08cab4d81849d10cfde5f1cc76fb31c4)
Istio 1.20.2
Prometheus 2.41.0
Kubernetes v1.27.3

**Comment by jshaughn** [comment]
I'm not sure this is the only issue with multi-cluster and the Overview page.  Will add to the general backlog, for now, but deferring until we further evaluate MC and Overview.

**Comment by jshaughn** [comment]
I would like this re-tested given the large number of MC changes that have gone in in the last 6 months.

**Comment by hhovsepy** [comment]
I still see this issue.

**Comment by jshaughn** [comment]
> I still see this issue.

Thanks for verifying, @hhovsepy .  We will leave this on the sprint backlog.
