### ISSUE TITLE
Cypress testsuite for performance tests. All list and details pages including all table. Read only tests.

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#7067]

**Comment by nrfox** [comment]
There's already some (very basic) tests written for this purpose [here](https://github.com/kiali/kiali/blob/bf9448055daf31dfc7d56bcef40bfe04595ef178/frontend/cypress/perf/Graphload.spec.ts). More on how to run them [here](https://github.com/kiali/kiali/tree/bf9448055daf31dfc7d56bcef40bfe04595ef178/frontend/cypress#performance-tests).

**Comment by hhovsepy** [comment]
Duplicate of https://github.com/kiali/kiali/issues/7088
