### ISSUE TITLE
Applications-view:  sidecar-injected labels not visible

### ISSUE THREAD

**Issue by SebastianJ91** [kiali/kiali#7079]
### Describe the bug

I want to switch the `istio_labels.app_label_name` to the automatically injected label `"service.istio.io/canonical-name"`.

Istio-Sidecar-Injector is adding this label automatically to pod-templates. 

When manually adding the label to the pod-metadata, before it is manipulated by the injector, the label is shown in the Applications-view.
When the label is added by the injector, the resulting pod-manifest is looking the same. But the injected label is not visible in the Applications-view.

Also other injected istio-system-labels are not visible.

After switching app_label_name` to `"service.istio.io/canonical-name"` kiali is not showing Applications where the label was injected, but only applications where the label was manually defined.

Are automatically injected istio-labels ignored by purpose? Or is the source of the Application-view some data, which is created before injecting is happening?

### Expected Behavior

Kiali is showing all istio-system-labels independent, if they are defined manually or added by the sidecar-injector.

### What are the steps to reproduce this bug?

1. Create a deployment including pod-metadata `service.istio.io/canonical-name` label
2. Create another deployment without the label `service.istio.io/canonical-name`
3. Check kiali-Application-view
4. One application is showing the label and the other one is missing it, although it is present in both resulting pod-manifests.

### Environment

- **Kiali version: 1.57.7**
- **Istio version: OpenShift Service Mesh 2.3.3**
- **Kubernetes impl: Openshift** 
- **Kubernetes version: v1.23.17+16bcd69**

**Comment by jshaughn** [comment]
Hi @SebastianJ91, I'm not aware of a reason why Kiali would not show the labels unless it maybe has to do with the handling of app and version labels.  Kiali expects that one app and version label-set are applied consistently to your resources.  By default, Kiali expects the `app` and `version` labels.  But some users prefer to use `app.kubernetes.io\name` and `app.kubernetes.io\version`.  You should also be able to use `service.istio.io/canonical-name` and `service.istio.io/canonical-revision`.   If not using the defaults you need to tell Kiali which pairing you are using.   In the Kiali CR you can set [spec.istio_labels.app_label_name](https://kiali.io/docs/configuration/kialis.kiali.io/#.spec.istio_labels.app_label_name) and [spec.istio_labels.version_label_name](https://kiali.io/docs/configuration/kialis.kiali.io/#.spec.istio_labels.version_label_name).

Can you take a look and see if that may be a reason for the behavior?

**Comment by SebastianJ91** [comment]
Hi @jshaughn,

I have already tried to set [spec.istio_labels.app_label_name](https://kiali.io/docs/configuration/kialis.kiali.io/#.spec.istio_labels.app_label_name) to `service.istio.io/canonical-name`.

After doing this, all apps were missing in the application view, if the label was only injected by Istio Injector.

This is consistent with the behaviour, that all injected `service.istio.io/...` labels are missing in the application view labels column, if they were not manually set by me in the manifest, no matter what `spec.istio_labels.app_label_name` is set.

If I add the label manually, everything works as expected. But other  `service.istio.io/...` labels are still missing.

Can you see the `service.istio.io/...` labels in the labels column of the application view on your side, if you don't add them yourself?

Is it possible that Kiali is somehow using the original manifest instead of the live manifest, before it was edited by the injector?

**Comment by jmazzitelli** [comment]
The app label is supposed to be set by the app deployer. Because "application" is a nebulous concept in Istio (there is no fixed definition of WHAT an application is - it is up to the person deploying the "application" in Istio), you should be setting the application label in your deployments/pods to declare which deployments/pods belong to which of your applications. Istio cannot determine which deployments/pods belong to which applications (as defined by the user who deployed those applications), and Kiali also has no fixed way to determine what is an application other than examining this label.

> If I add the label manually, everything works as expected.

As it should be. This is how it is supposed to work.

See docs
* https://istio.io/latest/docs/ops/deployment/requirements/

>Pod labels: We recommend __explicitly declaring pods with an application identifier and version by using a pod label__. These labels add contextual information to the metrics and telemetry that Istio collects.

* https://kiali.io/docs/architecture/terminology/concepts/#application

>Application - Is a logical grouping of Workloads defined by the application labels __that users apply__ to an object.

**Comment by jshaughn** [comment]
> Is it possible that Kiali is somehow using the original manifest instead of the live manifest, before it was edited by the injector?

I think the issue is an expectation that Kiali is grabbing information from pods. But Kiali, for the most part, ignores pods and focuses on the configuration.

**Comment by jshaughn** [comment]
@SebastianJ91 Any further input?  Currently we have no action to take here.
