### ISSUE TITLE
Kiali tracing URLs don't work with Grafana 10+

### ISSUE THREAD

**Issue by thomaspurchas** [kiali/kiali#7086]
### Describe the bug

Grafana 10 changed the URL schema for deep linking into the explore tab, breaking the Kiali deeplinks (they just end up on the default explore page, with all their parameter wiped. A new URL schema has been introduce and documented [here](https://grafana.com/docs/grafana/latest/explore/#generating-explore-urls-from-external-tools).

### Expected Behavior

Clicking on "View Trace Details" or "View Span Details" links directly to the trace or span in Grafana.

### What are the steps to reproduce this bug?

1. Setup Grafana 10 + Tempo backend
2. View Tempo traces/spans in Kiali dashboard
3. Navigate to trace or span detail in Kiali
4. Click triple dots, and select "View details" link
5. Observe that Grafana opens, but trace and span data is lost
6. 
### Environment
*Learn about how to determine versions [here](https://kiali.io/docs/faq/general/#how-do-i-determine-what-version-i-am-running).*

- **Kiali version: v1.78.0**
- **Istio version: 1.20.0**
- **Kubernetes impl: GKE** 
- **Kubernetes version:  v1.27.7-gke.1121002** 
- **Other notable environmental factors:**

**Comment by josunect** [comment]
@thomaspurchas thanks for report this, we will try with that specific version. 
At the meantime, have you tried the native integration with Tempo? It uses a more specific Grafana URL: https://kiali.io/docs/configuration/p8s-jaeger-grafana/tracing/tempo/#set-up-a-tempo-datasource-in-grafana

**Comment by thomaspurchas** [comment]
@josunect yeah I’m using the native Tempo integration right now, so Kiali is generating the more specific Grafana URLs, it’s just that Grafana no longer seems to recognise them.

**Comment by josunect** [comment]
> @josunect yeah I’m using the native Tempo integration right now, so Kiali is generating the more specific Grafana URLs, it’s just that Grafana no longer seems to recognise them.

Thanks @thomaspurchas, I was able to replicate it. I will investigate further the best way to solve it.

**Comment by thomaspurchas** [comment]
@josunect i already have a PR (#7085) open to help with this issue. It doesn’t provide a complete solution, but it does at least do some ground work in preparation for a proper solution. I would recommend reading the commit messages, as they describe my reasoning and intentions behind the changes. I’ve also tested that my proposed solution generates correct URLs for Grafana 10, but you need to hardcode in some missing config to get that working.

**Comment by josunect** [comment]
> @josunect i already have a PR (#7085) open to help with this issue. It doesn’t provide a complete solution, but it does at least do some ground work in preparation for a proper solution. I would recommend reading the commit messages, as they describe my reasoning and intentions behind the changes. I’ve also tested that my proposed solution generates correct URLs for Grafana 10, but you need to hardcode in some missing config to get that working.

Thanks, @thomaspurchas ! I will have a look

**Comment by jshaughn** [comment]
Closing as https://github.com/kiali/kiali/pull/7085 is merged, thanks @thomaspurchas !
