### ISSUE TITLE
Observability section

### ISSUE THREAD

**Issue by germain05** [kiali/kiali#7109]
### Describe the bug
metrics_enabled and metrics_port where moved to observability in the values.yaml and was not updated in deployment and sevice

### Expected Behavior
Update the service and deployment file to reflect the change in the value
### What are the steps to reproduce this bug?

- **Kiali version:*1.19.0*
- **Istio version:*1.20.2*
- **Kubernetes impl:** 
- **Kubernetes version:*1.27.7* 
- **Other notable environmental factors:**

**Comment by germain05** [comment]
Yeah, typo in the version. 1.79.0(the latest)

**Comment by nrfox** [comment]
I'll fix this one and @jmazzitelli can review
