### ISSUE TITLE
Inbound / Outbound metrics not visible from remote cluster in multi-cluster setup

### ISSUE THREAD

**Issue by rkadam-infracloud** [kiali/kiali#7129]
### Describe the bug

I have setup kiali as multi-cluster setup where kiali is installed using a helm chart on cluster A, cluster B is having a service account, cluster role and binding. A secret is created on cluster A which has kubeconfig to authenticate to cluster B.

In graphs section (Home page -> Graph from left panel) I am able to see the graphs from remote cluster when i select correct namespace name. So i think this proves the multi-cluster setup is done properly. Also, I have done Prometheus federation to provide single source of data to Kiali.

However, when i go to Applications -> Select namespace which is present on remote cluster -> Select an app -> on this screen Graph / traffic, Inbound/Outbound metrics all are coming blank. 

### Expected Behavior
Kiali should show I/O metrics for apps in remote cluster too.

### What are the steps to reproduce this bug?
1. Setup Kiali multi-cluster
2. Make sure an app is working in remote cluster that kiali is able to track
3. Check if Applications screen is showing appropriate output for this app.

### Environment
*Learn about how to determine versions [here](https://kiali.io/docs/faq/general/#how-do-i-determine-what-version-i-am-running).*

- **Kiali version: v1.77.0 (2c2c3d04da5ffe496b6e9d512e732e1feba87acc)**
- **Istio version: 1.20.2**
- **Kubernetes impl: v1.29.0-eks-c417bb3** 
- **Kubernetes version: v1.29.0**
- **Other notable environmental factors: AWS EKS**

**Comment by rkadam-infracloud** [comment]
More info: I am using this helm chart and version 1.77.0 -
https://kiali.org/helm-charts

Let me know if more info is needed.

**Comment by rkadam-infracloud** [comment]
Also, while checking logs i see this 
`2024-02-19T08:43:08Z INF Error fetching Applications for cluster Kubernetes: namespaces "xxxx" not found`
where xxxx is a namespace on remote cluster and not on the cluster where kiali is installed, which confirmed that kiali is only checking local cluster for namespace we select in application screen even if its a multi-cluster setup

**Comment by jmazzitelli** [comment]
I'm pretty sure one of the assumptions Kiali makes is that all namespaces exist on all clusters. i.e.  Kiali won't understand if you have namespace A on the remote cluster but there is no namespace A on the local cluster (or vise-versa).

This should be in our documentation somewhere, but I'm not sure where (and if it isn't, it should be).

**Comment by jshaughn** [comment]
@jmazzitelli I'm not sure that's a correct statement.  Kiali's namespace handling should be "cluster-aware".  But, multi-cluster support is new and there may be bugs.  From what I can tell, @rkadam-infracloud:
- Has a namespace that is on the remote cluster but not on Kiali's home cluster.
- The Namespace dropdown is correctly showing the Namespace as an option
- The Applications list is behaving fine, and showing the Application on the remote cluster
- The detail view for the selected application is not showing information for the mini-graph or traffic-related tabs.

@rkadam-infracloud Is that correct?  Is it only the Application Detail, or do you see similar behavior for a Workload detail, Service Detail?

**Comment by rkadam-infracloud** [comment]
@jmazzitelli @jshaughn 
1. Namespace must be present on both cluster - I don't think that is correct, because i do have one namespace on both clusters in which when I send traffic on remote cluster app I still see same behavior, that is the graphs shows up in left panel -> graph, however under left panel -> application no graph or inbound / outbound metrics.
2. Same is happening in workload and service section. Traffic and inbound / outbound metrics are not visible for namespaces on remote cluster. Although i do see the logs from the app under workload section.

**Comment by rkadam-infracloud** [comment]
I think its important to ask here -

Is multi-cluster setup of Istio mandatory for Kiali to work properly in multi-cluster setup?

We dont have Istio multi-cluster and its working separately on each cluster, however some of the features are working in kiali multi-cluster so just want to be sure we are good from pre-requisite pov

**Comment by rkadam-infracloud** [comment]
Yes, so I have 2 EKS clusters, both have separate istio running, both have separate Prometheus but they are unified with prometheus federation. Kiali is installed in cluster A, cluster B has service account, cluster role and binding, kubeconfig of cluster B with auth token is provided as a secret to cluster A.
As of now I am able to see namespaces from both clusters, and as mentioned above Graph section shows graphs too from both clusters. However inbound / outbound metrics are not visible from remote cluster. Is this expected if istio is not setup in multi-cluster mode?

**Comment by jmazzitelli** [comment]
> However inbound / outbound metrics are not visible from remote cluster. Is this expected if istio is not setup in multi-cluster mode?

Remember - multi-cluster is not the same thing as multi-mesh.

Kiali is expected to be showing data for a single mesh (whether it is in a single cluster or spread across multiple clusters).

If you have TWO different meshes in separate clusters, expect issues in the Kiali UI because that is not the design goal of Kiali to support multi-mesh (i.e. Kiali is not designed nor implemented to view data across multiple MESHES).

To view multiple meshes, install one Kiali for each mesh you have. Each Kiali should look at a single control plane.

**Comment by J4sonZ** [comment]
I use a single istiod master and multiple remote clusters. All clusters are planned as a service grid. I found that the metrics of the kiali remote cluster cannot be displayed normally.
![image](https://github.com/user-attachments/assets/1d3ab0bd-71ec-4132-b1ee-cfdd8e7c56c0)
Normally
![image](https://github.com/user-attachments/assets/5fe1922f-c413-424b-bfb1-a3b646ca1444)
Wrong
![image](https://github.com/user-attachments/assets/cb4cd5a5-5bbc-4ef2-ab04-667a6865474c)

**Comment by J4sonZ** [comment]
@jshaughn jshaughn @jmazzitelli jmazzitelli
master
![image](https://github.com/user-attachments/assets/b271a345-6b37-4d1e-a81b-e398df26e161)
worker
![image](https://github.com/user-attachments/assets/1225e530-29cc-40ac-b23f-433f1fb76b44)

**Comment by jshaughn** [comment]
@J4sonZ , my first guess is that the metrics from the remote cluster are not actually being ingested to the Prometheus instance configured for Kiali.  Kiali can only handle a single Prometheus, and so the metrics from multiple clusters must all be in that single Prometheus instance.  The alternative is to deploy multiple Kiali instances, one per cluster, configured for that cluster's prometheus instance.  But it will only be able to see the metrics for that one cluster.
