### ISSUE TITLE
[Flake] Integration test flake - TestServiceDiscoverDR

### ISSUE THREAD

**Issue by jshaughn** [kiali/kiali#7134]
```
=== RUN   TestServiceDiscoverDR
{"level":"error","time":"2024-02-19T14:25:49Z","message":"Err: 'exit status 1'. stderr: 'Error from server (InternalError): error when creating \"/home/runner/work/kiali/kiali/tests/integration/assets/bookinfo-destination-rule-reviews.yaml\": Internal error occurred: failed calling webhook \"validation.istio.io\": failed to call webhook: Post \"[https://istiod.istio-system.svc:443/validate?timeout=10s\](https://istiod.istio-system.svc/validate?timeout=10s\)": dial tcp 10.96.189.243:443: connect: connection refused\n'."}
    services_test.go:135: 
        	Error Trace:	/home/runner/work/kiali/kiali/tests/integration/tests/services_test.go:135
        	Error:      	Should be true
        	Test:       	TestServiceDiscoverDR
{"level":"error","time":"2024-02-19T14:25:49Z","message":"exit status 1"}
--- FAIL: TestServiceDiscoverDR (0.65s)
FAIL
exit status 1
FAIL	github.com/kiali/kiali/tests/integration/tests	364.944s
Error: Process completed with exit code 1.
```

**Comment by jshaughn** [comment]
May be gone, tracking for one more sprint.

**Comment by nrfox** [comment]
> {"level":"error","time":"2024-02-19T14:25:49Z","message":"Err: 'exit status 1'. stderr: 'Error from server (InternalError): error when creating \"/home/runner/work/kiali/kiali/tests/integration/assets/bookinfo-destination-rule-reviews.yaml\": Internal error occurred: failed calling webhook \"validation.istio.io\": failed to call webhook: Post \"[https://istiod.istio-system.svc:443/validate?timeout=10s\](https://istiod.istio-system.svc/validate?timeout=10s\)": dial tcp 10.96.189.243:443: connect: connection refused\n'."}

This seems like the controlplane is actually not healthy yet. Maybe need to revisit how we check if the istiod is healthy in the test before proceeding.

**Comment by ferhoyos** [comment]
This test flake has arisen again: https://github.com/kiali/kiali/actions/runs/8983429993/job/24674669551

**Comment by jshaughn** [comment]
Again today.
