### ISSUE TITLE
[docs] how to integrate with OpenShift user workload monitoring

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#7143]
### What do you want to improve?

Tell me how to integrate OpenShift's user workload monitoring (that is, using OpenShift's own prometheus to consume Istio telemetry and have Kiali use that Prometheus for its queries).

### What is the current documentation?

Nothing.

### What is the new documentation?

We want to explain what this hack script is doing - that's how you integrate with OCP prometheus: https://github.com/kiali/kiali/blob/master/hack/use-openshift-prometheus.sh

**Comment by nrfox** [comment]
@jmazzitelli looking at this line: https://github.com/kiali/kiali/blob/faca4e4d81a38d30e31e2c446ca2dd012be0630b/hack/use-openshift-prometheus.sh#L297

Does this mean all logged in users will use that one user's token to query?

**Comment by jmazzitelli** [comment]
> Does this mean all logged in users will use that one user's token to query?

Yes. We are configuring OCP user monitoring to allow the kiali SA to query the OCP Prometheus.  It's the same thing we have today with Maistra (Maistra Operator puts a single set of credentials (a set that Maistra creates) in the Kiali CR so Kiali can query the Maistra provided Prometheus).

**Comment by jmazzitelli** [comment]
(totally separate issue - I noticed `openshift_secret_name` variable [in the scrip](https://github.com/kiali/kiali/blob/faca4e4d81a38d30e31e2c446ca2dd012be0630b/hack/use-openshift-prometheus.sh#L157)t is named wrong - it really is the namespace where openshift stores user monitoring secrets that it uses. We should probably rename that (at least we shouldn't use that name in the docs - should be `openshift_secret_namespace`

**Comment by jshaughn** [comment]
Can we link to the OSSM docs for this OpenShift-specific content?

**Comment by jmazzitelli** [comment]
> Can we link to the OSSM docs for this OpenShift-specific content?

Yeah. The docs for that is here: https://docs.openshift.com/container-platform/4.14/service_mesh/v2x/ossm-observability.html#ossm-integrating-with-user-workload-monitoring_observability

 In fact, the script itself has a comment at the top that refers to those OpenShift and OSSM docs -- https://github.com/kiali/kiali/blob/master/hack/use-openshift-prometheus.sh#L5-L8

So maybe we don't have to do anything?

**Comment by jshaughn** [comment]
@jmazzitelli So, are we done here, nothing to do?  Or shall we add a link in the upstream docs?

**Comment by jmazzitelli** [comment]
I say, nothing to do here.
