### ISSUE TITLE
Add the ability to modify the dnsconfig for the kiali deployment in kubernetes

### ISSUE THREAD

**Issue by ceastman-r7** [kiali/kiali#7150]
### What do you want to improve?
Allow the ability to add a dnsconfig option to the deployment spec

mainly to have the following:
`dnsConfig:
    options:
      - name: ndots
        value: "1"
`

### What is the current behavior?
current behavior is to have ndots default to 5

From the resolv.conf man:

ndots:n

sets a threshold for the number of dots which must appear in a name before an initial absolute query will be made. The default for n is 5, meaning that if there are any dots in a name, the name will be tried first as an absolute name before any search list elements are appended to it

in aws kubernetes the typically resolv.conf is as follows:
search apps.svc.cluster.local svc.cluster.local cluster.local us-east-2.compute.internal
nameserver 172.20.0.10
options ndots:5

### What is the new behavior?
All the default dnsconfig to be overridden to allow ndots: 1

**Comment by jshaughn** [comment]
@jmazzitelli Can you follow up with @ceastman-r7 and make sure we better understand the ask here?

**Comment by jmazzitelli** [comment]
@ceastman-r7 what are looking for here? Is this to be an additional setting in the Kiali CR's `spec.deployment` section ?

This part of your issue description is confusing me:

```
mainly to have the following:
dnsConfig: options: - name: ndots value: "1" 
```

**Comment by jshaughn** [comment]
@ceastman-r7 Can you answer the question above?

**Comment by ceastman-r7** [comment]
For instance the ask is to have the ability to add a configuration so that the pod yaml looks like the following:
`      dnsConfig:
        options:
        - name: ndots
          value: "1"
      dnsPolicy: ClusterFirst
`

**Comment by jshaughn** [comment]
@jmazzitelli Does that give you enough context?

**Comment by ceastman-r7** [comment]
```
      dnsConfig:
        options:
        - name: ndots
          value: "1"
      dnsPolicy: ClusterFirst
```

**Comment by jmazzitelli** [comment]
This is ready for review. This new feature should be available in the next sprint release due in about 3 weeks.

PRs:
* https://github.com/kiali/kiali-operator/pull/768
* https://github.com/kiali/helm-charts/pull/260
