### ISSUE TITLE
Gateway API class from Env variables

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#7167]
### What do you want to improve?
Allow custom Gateway API class names from Environment variables, like in Istio: https://github.com/istio/istio/pull/48056

### What is the current behavior?
Currently the custom Gateway API class names are configured in Kiali CR under 'external_services: istio: gateway_api_classes:', and when not set, the hardcoded "istio" is used.

### What is the new behavior?
When Kiali CR does not have the configuration, try to use env variable 'PILOT_GATEWAY_API_DEFAULT_GATEWAYCLASS_NAME' and only then use "istio" as hardcoded default.

**Comment by jmazzitelli** [comment]
Are we sure we want to do this?
1. We don't do this anywhere else that I am aware of (istio env variables as defaults). Is there a reason this setting/env var is special in this way?
2. How do we propose people set env variables in the server pod? There is no way to do it other than manually "kubectl patch" or something like that
