### ISSUE TITLE
kiali doesnt show default namespace

### ISSUE THREAD

**Issue by jsloyer** [kiali/kiali#719]
**Describe the bug**
In kiali the default namespace is not shown.  I have an app (the bookinfo) sample from Istio running in the default namespace.  

For UI issues please also add a screenshot that shows the issue.
![image](https://user-images.githubusercontent.com/154126/49553021-d1626d80-f8c3-11e8-8ed4-d6fb00239993.png)

**Versions used**
kiali-ui 0.9.1-helmfix (12c76a2fb46407944084f8e453b2fd2ee52e8c13)
kiali v0.9.1.helmfix (8444e016515f1f48b685594a0c7616130a2b6fdc)
Components
Istio 1.0.4
Prometheus 2.3.1
Kubernetes v1.10.11+IKS

**To Reproduce**
1. Login to Kiali
2. Goto the overview tab
3. See the missing namespace `default`

**Expected behavior**
Adding support to show the `default` namespace.

**Comment by jmazzitelli** [comment]
closing... this is fixed already since v0.10:

https://github.com/kiali/kiali/pull/638
https://issues.jboss.org/browse/KIALI-1877

**Comment by vsrathod10** [comment]
Hi jsloyer,

I am facing the same issue I am able to only get istio-system namespace but my application is running in default.
if you had solved can you please help.

Thanks

**Comment by jshaughn** [comment]
If istio-system is the only namespace in your dropdown then it may mean you are logging into Kiali as a user that only has access to the istio-system namespace.  In general you should see all accessible namespaces in the dropdown selector.

**Comment by jotak** [comment]
@vsrathod10 also which version of Kiali are you running?

**Comment by vsrathod10** [comment]
Istio 1.0.4 and kiali :  0.9.1 @jotak 

I logged in as admin access but I install kiali in istio-system namespace and my application running in the default namespace.

**Comment by jotak** [comment]
@vsrathod10 ok so maybe look at Kiali's ConfigMap, if I remember correctly there was a setting that lists excluded namespaces and the "default" namespace was part of that list at some point. You may have to restart kiali after modifying the config map.
This is a quite old version of Kiali, you should probably not see this issue in more recent versions.

**Comment by jmazzitelli** [comment]
That's a really old kiali - back then we were ignoring the default namespace. We removed that in later versions.

**Comment by jmazzitelli** [comment]
Sorry - I should have read the entire issue here before replying :)
Looks like I already mentioned this back in December in this comment: https://github.com/kiali/kiali/issues/719#issuecomment-444703705
