### ISSUE TITLE
Remove `verbose_mode` configuration setting

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#7208]
### What do you want to improve?

There's a [verbose_mode](https://kiali.io/docs/configuration/kialis.kiali.io/#.spec.deployment.verbose_mode) config setting but it is deprecated and seems to be broken so it should just be removed. Instead users should specify log level with `deployment.logger.log_level`.

**Comment by jmazzitelli** [comment]
PRs ready for review and merge (test procedures documented in the PRs):

* server: https://github.com/kiali/kiali/pull/7209
* operator: https://github.com/kiali/kiali-operator/pull/753
* helm chart: https://github.com/kiali/helm-charts/pull/251
