### ISSUE TITLE
Namespace selector order is random

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#7227]
### Describe the bug

Namespace selector ordering is random.

![namespaceselector](https://github.com/kiali/kiali/assets/6226732/7e18163f-1e63-4037-beac-add0cd450464)

### Expected Behavior

Namespace selector should be sorted alphabetically.

### What are the steps to reproduce this bug?

1. Open/close namespace selector repeatedly

### Environment
*Learn about how to determine versions [here](https://kiali.io/docs/faq/general/#how-do-i-determine-what-version-i-am-running).*

- **Kiali version: v1.82.0**
- **Istio version:  1.21**
- **Kubernetes impl: vanilla** 
- **Kubernetes version: 1.28** 
- **Other notable environmental factors:**

**Comment by jshaughn** [comment]
This could actually merit a patch release.  Is it only a 1.82 regression?

**Comment by nrfox** [comment]
> This could actually merit a patch release. Is it only a 1.82 regression?

Yes I believe so. I'm guessing it got introduced with #7200.
