### ISSUE TITLE
automaxprocs removed from kiali

### ISSUE THREAD

**Issue by antoinedeschenes** [kiali/kiali#7254]
### Describe the bug

In clusters with large nodes, Kiali creates many more processes than set by our limits.cpu and causes high CPU throttling.

### Expected Behavior

Given #4579 was added, I'd expect Kiali to adjust GOMAXPROCS automatically according to the CPU limits.

It looks like automaxprocs was removed in #6100 without explanation.

**Comment by jmazzitelli** [comment]
> It looks like automaxprocs was removed in #6100 without explanation.

That was likely unintentional

**Comment by jmazzitelli** [comment]
It was removed in this commit over in that PR: 

https://github.com/kiali/kiali/pull/6100/commits/99ba75e2bd7fcba4a73079b006541d71a13035d5#diff-a0c270f708064531f39882e8d88e4fbf3d0a2e9f9adf7a034903ed036518ac79L38

I suspect this is one of those cases where an IDE thought it was doing the right thing by removing what looks like an unused import and in fact it should just leave things alone.

**Comment by antoinedeschenes** [comment]
https://github.com/kiali/kiali/pull/7255
