### ISSUE TITLE
[CI] Flake - graph_context_menu nodes undefined

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#7256]
### Describe the bug

CI flake involving the following test:
![Screenshot from 2024-04-04 18-59-13](https://github.com/kiali/kiali/assets/6226732/b0ccc631-082e-4e17-bb2b-662ee8916eee)

Screenshot of cypress at time of failure:
![Kiali Graph page - Context menu actions -- Actions in context menu for a service node with existing traffic routing (failed)](https://github.com/kiali/kiali/assets/6226732/e69ec831-c2ad-48a9-8f6d-3486dda17f65)

From run: https://github.com/kiali/kiali/actions/runs/8560404196/job/23459494170#step:8:861

**Comment by nrfox** [comment]
I can't say for sure but I think this is the line that is failing: https://github.com/kiali/kiali/blob/5f59bc2c2f56dc70065b948657892b9cf925154e/frontend/cypress/integration/common/graph_context_menu.ts#L35-L37

**Comment by jshaughn** [comment]
Will monitor for one more sprint.
