### ISSUE TITLE
Request for spec.deployment.use_istio_discovery_selectors (to disable)

### ISSUE THREAD

**Issue by alt-dima** [kiali/kiali#7262]
### What do you want to improve?
Optionally disable Istio's discoverySelectors behaviour in Kiali
https://github.com/kiali/kiali/issues/3914#issuecomment-1412199993

### What is the current behavior?
Istio's discoverySelectors are always being used.
https://github.com/kiali/kiali/issues/3914#issuecomment-1412609342

### What is the new behavior?
If  `spec.deployment.use_istio_discovery_selectors = false`, then use only `accessible_namespaces`

### The reason/case
We have two namespaces:
1. `default` with legacy workloads without envoy sidecar and `kong-api-gateway` with envoy sidecar. Istio MeshConfig discovery disabled.
2. `mesh` with new workloads always in mesh (with envoy sidecar). Istio MeshConfig discovery enabled.

Istio sidecar configured to intercept/forward only to/from port 3001
`kong-api-gateway` forwards traffic to port 3000 to the legacy workloads in default ns and to port 3001 (via istio-envoy-sidecar) in `mesh` ns.
In this case, we significant reduced amount of endpoint (EDS) in Istio (to populate only from mesh ns). Even in `kong-api-gateway` in default ns!
Istio works as expected, but in Kiali we:
1. Do not see `default` ns (to see the traffic at `kong-api-gateway`) - it displayed as external seervice
2. Errors KIA0106 (Service Account not found for this principal) in AuthorizationPolicy in `mesh` for principals from `default` ns like `cluster.local/ns/default/sa/kong-api-gateway`

Priority very low for this request, because not critical at all, we have the visibility on the services in `mesh` ns

**Comment by jshaughn** [comment]
@alt-dima , I understand the request but I don't think we will go forward with this one.  When Discovery Selectors are defined, we think it makes sense for Kiali to honor them and to exclude namespaces that Istio itself considers outside of the mesh.  This option would further complicate the namespace accessibility code,  which is already complicated :-)
