### ISSUE TITLE
Hiding waypoints gives "Can not create edge" error

### ISSUE THREAD

**Issue by howardjohn** [kiali/kiali#7278]
```
Danger alert:There was an error when rendering the graph: Can not create edge `990857dddff62dc1cf70fab54ff74a5c` with nonexistant target `16cc3d3b199b2a91437a00fd84cf7bff`, please try a different layout
```

I get ^ error anytime I uncheck the "Waypoint proxies" button on the graph UI. Tested on Istio master and kiali 1.82 and 1.83

**Comment by josunect** [comment]
I've tried with the latest Istio 1.22 alpha build, (e.x. istio-1.22-alpha.5e5ceeeee474748f4a9c235eea952a35f2168e42) And I'm not able to see any L7 telemetry for bookinfo (Just for istio-system):
 
![image](https://github.com/kiali/kiali/assets/49480155/8c088840-74d6-45cd-b7f5-5c9548d94418)

![image](https://github.com/kiali/kiali/assets/49480155/de1f060a-c473-4f79-a42a-d69c1b8e96e7)

With a waypoint applied to the namespace bookinfo: 
![image](https://github.com/kiali/kiali/assets/49480155/6d35218c-239c-4b81-8064-dc79a125f757)

How could we reproduce it?

**Comment by jshaughn** [comment]
Wait to proceed until v1.22 release.

**Comment by josunect** [comment]
This should be fixed by https://github.com/kiali/kiali/pull/7345

**Comment by jshaughn** [comment]
Closing as I believe this error is resolved.  But, we are still working on the `Show Waypoints" option, it's not crashing but it's also not working the way we want it to work.
