### ISSUE TITLE
Barely visible color choice for "Not Ready" icon in dark-mode

### ISSUE THREAD

**Issue by ishitharaj** [kiali/kiali#7317]
### Describe the bug

When you select dark-mode in Kiali, "Not Ready" icon barely visible. You have to have workloads in Not Ready state to see this.
![Screenshot 2024-04-27 at 13 58 14](https://github.com/kiali/kiali/assets/38528963/4e488bc4-b209-40aa-b6bf-56cba0a0e162)

### Expected Behavior

"Not Ready" icon is properly visible in both light/dark theme

### What are the steps to reproduce this bug?

1. Deploy Kiali and open UI
2. Make sure that you have workloads in "Not Ready" state
3. Change theme to dark mode and check workloads list. Icons are visible in Health column.

### Environment
*Learn about how to determine versions [here](https://kiali.io/docs/faq/general/#how-do-i-determine-what-version-i-am-running).*

- **Kiali version: 1.78**

**Comment by ishitharaj** [comment]
label should be [enhancement][good first issue]. Not bug.

**Comment by Densentrated** [comment]
Hey! do you mind if I take this one on?

**Comment by ishitharaj** [comment]
> Hey! do you mind if I take this one on?

Sure.. No problem..

**Comment by jshaughn** [comment]
I think @Densentrated was asking the maintainers :-)  But the answer is the same!  Thanks!

**Comment by jshaughn** [comment]
Hi @Densentrated , any updates?

**Comment by Densentrated** [comment]
Hey!, I forgot that I had AP Tests the week after I asked to take this on, but now that they are over, I will be on top of this!

**Comment by jshaughn** [comment]
NP, hope the tests went well!

**Comment by jshaughn** [comment]
@Densentrated Any progress?

**Comment by Devanxh** [comment]
Hi @jshaughn , can i take this up?

**Comment by jshaughn** [comment]
@Devanxh Please do!

**Comment by jshaughn** [comment]
@Devanxh any progress?
