### ISSUE TITLE
The tracing service should not try to connect indefinitely 

### ISSUE THREAD

**Issue by josunect** [kiali/kiali#7332]
### What do you want to improve?

The tracing service should not try to connect indefinitely 

### What is the current behavior?

The tracing service is trying to connect indefinitely 

### What is the new behavior?

The tracing service should try to connect a limited number of times after some period of time and after some retries, it should stop trying to connect. 
The log messages should be info messages until it finishes the retries, then there should be one error message if it is not able to connect.

**Comment by jshaughn** [comment]
I'm reclassifying this as a bug.  It's come up a couple of times and I want to increase the priority.

**Comment by josunect** [comment]
I was reviewing the behavior of the tracing service, and I think it could be difficult to distinguish when the error should be silent or not (The error could be expected when the tracing service is enabled and it has an outage for some reason).

Kiali creates the tracing service but it does not check it's availability. It does it, every time that one of the pages is refreshed to show the status for the enabled services: 

![image](https://github.com/kiali/kiali/assets/49480155/749b3b9a-f165-4467-9f38-6906d58ec168)

Every time the tracing service is not available, it shows an error in the Kiali logs: 

`2024-07-03T09:26:59+01:00 ERR Error fetching availability of the tracing service: Get "http://localhost:3200/api/services": dial tcp 127.0.0.1:3200: connect: connection refused`

Which is expected is the tracing service is really enabled but is not available. 

An alternative could be that the tracing client does some retries during the startup and set an internal variable like auto_disabled, the behavior of Kiali should be then the same as if the client was disabled by the user (Not checking the status of tracing, hiding the trace tab). Maybe it could be doing some query to get some traces (Like 3 queries every minute). If the 3 of them doesn't return a 200, the set the auto_disabled setting to true.

**Comment by jmazzitelli** [comment]
If `external_services.tracing.enabled` is `false`, I assume Kiali doesn't do anything with the tracing client. At least, it shouldn't. Can we change the code such that if that setting is false, Kiali will never check for tracing availability and that component status should never look for tracing status?

**Comment by josunect** [comment]
> If `external_services.tracing.enabled` is `false`, I assume Kiali doesn't do anything with the tracing client. At least, it shouldn't. Can we change the code such that if that setting is false, Kiali will never check for tracing availability and that component status should never look for tracing status?

Yes, this is how is actually working: if tracing is disabled, you won't see any error messages, and Kiali won't look at the tracing status:

![image](https://github.com/kiali/kiali/assets/49480155/4a607092-f610-412c-93a0-c1182fe5589c)

**Comment by jmazzitelli** [comment]
I think its fine to change the default to `false` and in our release notes we call out the change in default values.

**Comment by jshaughn** [comment]
> I think its fine to change the default to false and in our release notes we call out the change in default values.

I agree, it should not be assumed that people are using tracing.   I think if they are going to go in and define a URL and other settings then it would make sense for them to set it to `enabled: true`.  For the Istio add-on, I'm not sure in that demo env, maybe we would want it configured `true`.

**Comment by nrfox** [comment]
> For the Istio add-on, I'm not sure in that demo env, maybe we would want it configured `true`.

FWIW the istio kiali addon already disables tracing because of this very issue: https://github.com/istio/istio/blob/91af022f3d320d2562fe6e57ccf22149636dd294/manifests/addons/values-kiali.yaml#L13-L16.

**Comment by josunect** [comment]
Closed by https://github.com/kiali/kiali/pull/7508
