### ISSUE TITLE
K8s GW API 1.1 Support

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#7355]
### What do you want to improve?
K8s Gateway API v1.1.0 is released https://github.com/kubernetes-sigs/gateway-api/releases/tag/v1.1.0
GRPCRoute is GA now.

- [x] GRPCRRoute to v1.1
- [x] Add support of GRPCRoute in Wizards. https://github.com/kiali/kiali/issues/7223
- [x] HTTPRoute can now have a Service as a parentRef. Update validations.

**Comment by jshaughn** [comment]
@hhovsepy I force-merged PRs for this, but was unsure whether this issue itself was complete.  Please update as needed.
