### ISSUE TITLE
kiali-server helm chart: Do not create ClusterRole if not needed

### ISSUE THREAD

**Issue by capuche2412** [kiali/kiali#7357]
### What do you want to discuss?

In the kiali-server Helm Chart, the clusterRole `kiali-server.fullname` is still created even if it is not used by the deployment. To stay with the KISS philosophy, I think it is better to not create it if `.Values.deployment.view_only_mode` is `true`.

### What does it improve / What problem does it solve?

This avoids creating useless clusterRole. In my case, I do not want to create a clusterRole I don't use

### What is the recommended proposal?

Just modify the chart to implement, a condition to not create it.

If you agree with this statement, I can write the PR.

**Comment by jmazzitelli** [comment]
That sounds reasonable. Submit a PR. Thanks.

**Comment by jmazzitelli** [comment]
PR merged. Closing issue.
