### ISSUE TITLE
Facing frontend test issues on ppc64le architecture.

### ISSUE THREAD

**Issue by vinodk99** [kiali/kiali#7382]
### Describe the bug

While executing frontend tests facing issue.

### Expected Behavior
Tests need to be passed 

### Environment
*Learn about how to determine versions [here](https://kiali.io/docs/faq/general/#how-do-i-determine-what-version-i-am-running).*

- **Kiali version:v1.84.0

Below are the logs:

`Summary of all failing tests
 FAIL  src/pages/Overview/__tests__/OverviewPage.test.tsx (42.095 s)
  ● Overview page › renders all without filters

    thrown: "Exceeded timeout of 5000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      126 |   });
      127 |
    > 128 |   it('renders all without filters', done => {
          |   ^
      129 |     FilterSelected.setSelected({ filters: [], op: DEFAULT_LABEL_OPERATION });
      130 |     Promise.all([
      131 |       mockNamespaces(['a', 'b', 'c']),

      at src/pages/Overview/__tests__/OverviewPage.test.tsx:128:3
      at Object.<anonymous> (src/pages/Overview/__tests__/OverviewPage.test.tsx:87:1)

  ● Overview page › filters failures match

    expect(received).toHaveLength(expected)

    Expected length: 3
    Received length: 1
    Received object: {}

      141 |       mounted!.update();
      142 |       // All 3 namespaces rendered
    > 143 |       expect(mounted!.find('Card')).toHaveLength(3);
          |                                     ^
      144 |       done();
      145 |     });
      146 |     mountPage();

      at src/pages/Overview/__tests__/OverviewPage.test.tsx:143:37

Test Suites: 1 failed, 76 passed, 77 total
Tests:       2 failed, 11 skipped, 399 passed, 412 total
Snapshots:   52 passed, 52 total
Time:        44.787 s, estimated 46 s
Ran all test suites matching /__tests__/i.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`

**Comment by jshaughn** [comment]
@vinodk99 Are you still seeing an issue with v1.86.0, released today?
