### ISSUE TITLE
Simplify i18n support 

### ISSUE THREAD

**Issue by ferhoyos** [kiali/kiali#7394]
### What do you want to improve?

Recently I discovered a simple way to perform i18n translations in React classes and external functions. This approach uses the function `getI18n().t` from `react-i18next` directly, instead of adding the `t` property to React classes with the `withTranslation` HOC function. I successfully applied this approach on the mesh page, so it should be propagated to the rest of the Kiali application and the corresponding documentation should be modified..

### What is the current documentation?

https://github.com/kiali/kiali/blob/master/frontend/README.adoc#internationalization-i18n

Currently there are 4 different use cases for i18n translation (React hooks, React classes, external functions and variables)

### What is the new documentation?

With the new approach, we simplify the i18n translation to only 2 different use cases (React hooks and everything else).

**Comment by jshaughn** [comment]
@ferhoyos , moving to project.  We should get this done quickly in the case that we get attention from our Chinese contributors.
