### ISSUE TITLE
use Dive to examine our images for inefficiencies

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#7430]
We should use https://github.com/wagoodman/dive to examine our server and operator images for potential places to prune. There might be things we can do to reduce the image sizes; Dive will help with that.

BTW: Dive is an abandoned project

**Comment by jmazzitelli** [comment]
`docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock wagoodman/dive:latest quay.io/kiali/kiali:latest`

All layers show 99% efficient. So not sure there is much to do in the server.

**Comment by jshaughn** [comment]
I guess 2.0 is probably a good time time to give this a go.

**Comment by jmazzitelli** [comment]
Analyzed v2.2.0 of the server, operator, and OSSMC.

Server is at 99.9994% efficiency... nothing to do here.

Operator: Dive reports the operator has 600MB of wasted space (57% efficiency). Note the operator base image has 347MB wasted space(72% efficiency), so we are doing something that wastes more space.

The OSSMC plugin is in the middle - wasted space of 130MB (82% efficiency).

```
$ for i in quay.io/kiali/kiali:v2.2.0 quay.io/kiali/kiali-operator:v2.2.0 quay.io/kiali/ossmconsole:v2.2.0 quay.io/operator-framework/ansible-operator:v1.35.0; do echo "$i" && docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock wagoodman/dive:latest --ci $i | grep -E '(efficiency|wastedBytes):'; done
quay.io/kiali/kiali:v2.2.0
  efficiency: 99.9994 %
  wastedBytes: 1652 bytes (1.7 kB)
quay.io/kiali/kiali-operator:v2.2.0
  efficiency: 57.1156 %
  wastedBytes: 599692298 bytes (600 MB)
quay.io/kiali/ossmconsole:v2.2.0
  efficiency: 82.2935 %
  wastedBytes: 129588557 bytes (130 MB)
quay.io/operator-framework/ansible-operator:v1.35.0
  efficiency: 71.8881 %
  wastedBytes: 346941049 bytes (347 MB)
```

**Comment by jmazzitelli** [comment]
I can't figure out how to dive consistently successful. Sometimes I get errors. And it is abandoned so if I'm hitting some bug, it isn't getting fixed. Not sure what to do here. Maybe someone else can try to address shrinking the image and looking at the dive results.

**Comment by jmazzitelli** [comment]
I tried re-arranging some of the dockerfile, but it doesn't really help. Drops a little but not by much.

```dockerfile
ARG OPERATOR_BASE_IMAGE_VERSION
ARG OPERATOR_BASE_IMAGE_REPO
FROM ${OPERATOR_BASE_IMAGE_REPO}:${OPERATOR_BASE_IMAGE_VERSION}

COPY roles/ ${HOME}/roles
COPY playbooks/ ${HOME}/playbooks
COPY watches-k8s.yaml \
     watches-os.yaml \
     watches-k8s-ns.yaml \
     watches-os-ns.yaml \
     requirements.yml \
     ${HOME}/

RUN ansible-galaxy collection install -r ${HOME}/requirements.yml \
 && chmod -R ug+rwx ${HOME}/.ansible \
 && cp /etc/ansible/ansible.cfg ${HOME}/ansible-profiler.cfg && echo "callbacks_enabled = profile_tasks" >> ${HOME}/ansible-profiler.cfg

USER root
# Re: jmespath install - needed for json query functionality in Ansible
# Re: yum remove - see https://github.com/operator-framework/operator-sdk/issues/5745
RUN python3 -m pip install jmespath \
    && yum remove -y subscription-manager python3-subscription-manager-rhsm \
    && yum update -y \
    && yum clean all
USER ${USER_UID}
```
 
The size of the base image is 681MB. If I do nothing in the Dockerfile, that's the size we get.
If I only do all the COPY commands, its 682MB.
When I then add the ansible collections, it goes up to 704MB (I also added the profiler cfg file creation too - no difference).
When I then pip install jmespath, it stays at 704MB.
When I remove the two subscription managers, interestingly, it goes up to 731MB.
When I do the yum update, it then goes up to 897MB (so this is where the bulk of the disk usage comes from, aside from the base image itself).
When I do a yum clean after the update, it goes down to 888MB.

Our 2.2 release is 902MV - so reordering things and reducing the amount of RUN commands saved a minuscule amount (14MB),

**Comment by jmazzitelli** [comment]
I think we should close this - I don't see where there is any room for improvement, other than manually start deleting things that we don't need from the container, but who knows what the base image/operator needs or doesn't need??

**Comment by jshaughn** [comment]
+1.
