### ISSUE TITLE
Traces/Graph under "Services" shows no data

### ISSUE THREAD

**Issue by kovaxur** [kiali/kiali#7440]
### Describe the bug

Under the "Services" menu, when I select a service, I don't see any traces. When I checked the incoming queries on the trace collector (Grafana tempo), I see that the service name is not included in the query:

`query-frontend level=info ts=2024-06-17T12:46:22.851037983Z caller=search_handlers.go:178 msg="search request" tenant=single-tenant query="{ .service.name = \".test2\"  } && {  } select(status, .service_name, .node_id, .component, .upstream_cluster, .http.method, .response_flags, resource.hostname)" range_seconds=600 limit=100 spans_per_spanset=10  `

![image](https://github.com/kiali/kiali/assets/9846259/d80c76f8-4324-4e53-8e7c-b0fdcd5f5b74)

![image](https://github.com/kiali/kiali/assets/9846259/9337a882-5d1a-4b45-9854-dc20e874607f)

(The Graph for the overview works fine.)

### Expected Behavior

The query should contain the name of the application postfixed with .<namespace>

### Environment
*Learn about how to determine versions [here](https://kiali.io/docs/faq/general/#how-do-i-determine-what-version-i-am-running).*

- **Kiali version:** v1.85.0
- **Istio version:** 1.22.1
- **Kubernetes impl:**  EKS
- **Kubernetes version:** 1.29.4-eks-036c24b
- **Other notable environmental factors:** Grafana tempo: 2.5.0

**Comment by josunect** [comment]
@kovaxur what is the name of the service that you are looking for? It is not `test2`? 
Kiali uses by default the configuration `tracing.namespace_selector=true` so it will include the service namespace in the query. 
I see you might have set that configuration to false, so the namespace is not included. 

Could you check in the Grafana Tempo datasource if the service name is saved as namespace scoped?
![image](https://github.com/kiali/kiali/assets/49480155/c876e3d6-8f68-4caa-be8e-bccd7a0803de)

**Comment by kovaxur** [comment]
test2 is the namespace, the k8s service name is "core-data-api", app.kubernetes.io/name is set to "core-data" on both the service and pods.

![image](https://github.com/kiali/kiali/assets/9846259/98f7ef5e-3c78-415c-93f6-a2b87e7df745)

In Grafana I can see the core-data.test2 service:

![image](https://github.com/kiali/kiali/assets/9846259/1320e793-b107-40d4-b155-50453cb1e432)

Kiali logs for the tempo query:

```
2024-06-17T15:59:26Z DBG Prepared Tempo API query: http://tempo-query-frontend.monitoring-ns.svc.cluster.local:3100/api/search?end=1718639966&limit=100&q=%7B+.service.name+%3D+%22.test2%22++%7D+%26%26+%7B++%7D+%7C+select%28status%2C+.service_name%2C+.node_id%2C+.component%2C+.upstream_cluster%2C+.http.method%2C+.response_flags%2C+resource.hostname%29&spss=10&start=1718639366 
```

Thanks

**Comment by josunect** [comment]
Thank you for the information provided, @kovaxur 

In order for the tracing service to get properly the service name, it uses the selector `app=service-name` (Which in your case, would be `app=core-data`. Could you confirm if the service has the app selector? If not, could you try to add it and check the results? 

Thanks,

**Comment by kovaxur** [comment]
I have added the app=core-data label, but it is still the same, I have the following settings set in the helm chart of Kiali:

```
cr:
  create: true
  name: kiali
  namespace: "istio-system"

  spec:
    istio_labels:
      app_label_name: "app.kubernetes.io/name"
      version_label_name: "cdk8s.io/metadata.addr"
```

The service also has these labels.

Thanks

**Comment by josunect** [comment]
Thank you, @kovaxur 

Is that label as a label selector?
![image](https://github.com/kiali/kiali/assets/49480155/3932c70b-b81d-4465-b164-48c8d7120f1b)

**Comment by kovaxur** [comment]
It was missing from the service, I added it and it started to work :)

```
query-frontend level=info ts=2024-06-18T07:51:38.238230892Z caller=handler.go:133 tenant=single-tenant method=GET traceID=6f0d62a4cda2d669 url="/api/search?end=1718697098&limit=100&q=%7B+.service.name+%3D+%22core-data.test2%22++%7D+%26%26+%7B++%7D+%7C+select%28status%2C+.service_name%2C+.node_id%2C+.component%2C+.upstream_cluster%2C+.http.method%2C+.response_flags%2C+resource.hostname%29&spss=10&start=1718697017" duration=167.4142ms response_size=10072 status=200  
```

Thanks!

**Comment by josunect** [comment]
Great to know! Thanks for the feedback
