### ISSUE TITLE
Mesh page throws error when one of the clusters is inaccessible

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#7455]
### Describe the bug

When the user does not have access to one of the clusters in the mesh, the mesh page throws an error instead of displaying the graph:

![image](https://github.com/kiali/kiali/assets/6226732/1a9c29a2-118d-4cdb-960f-db3cf0b3c380)

### Expected Behavior

Mesh page does not throw an error when user does not have access to one of the clusters.

### What are the steps to reproduce this bug?

1. Deploy multi-cluster environment with RBAC enabled: 
     ```
     hack/run-integration-tests.sh --test-suite frontend-multi-primary --setup-only true
     ```
2. Disable access for the logged in user to the `west` cluster
    ```
    kubectl delete clusterrolebindings --context kind-west kiali-testing-user
    ```
3. Visit mesh page

### Environment
*Learn about how to determine versions [here](https://kiali.io/docs/faq/general/#how-do-i-determine-what-version-i-am-running).*

- **Kiali version: latest**
- **Istio version: 1.22.1**
- **Kubernetes impl: vanilla** 
- **Kubernetes version: 1.27.3**

**Comment by josunect** [comment]
@nrfox I'm trying to reproduce this but I can see the Mesh page: 

![image](https://github.com/kiali/kiali/assets/49480155/0efd2cd2-93d1-43ee-baeb-07ca479e1261)

But in the graph, I see the following: 

![image](https://github.com/kiali/kiali/assets/49480155/46bcf52a-7e0c-4563-bd73-03062d0fbaf8)

This is what I see in the Overview: 

![image](https://github.com/kiali/kiali/assets/49480155/e23388f2-2d0a-4eb2-b948-4a359e64aab1)

So, is the Traffic graph that would need to be fixed? Or maybe I'm not reproducing this correctly (Or another PR fixed this particular issue)

**Comment by nrfox** [comment]
@josunect sorry I included the wrong test suite in the setup instructions. Only the multi-primary suite has openid auth enabled. I think the behavior did change recently because I'm now seeing a different error when I click on the west cluster after removing access for the kiali test user: 
![Screenshot from 2024-07-09 10-07-23](https://github.com/kiali/kiali/assets/6226732/819ab0ca-7a1a-4f96-ad8f-d6407eaa9f08)

**Comment by josunect** [comment]
> @josunect sorry I included the wrong test suite in the setup instructions. Only the multi-primary suite has openid auth enabled. I think the behavior did change recently because I'm now seeing a different error when I click on the west cluster after removing access for the kiali test user: ![Screenshot from 2024-07-09 10-07-23](https://private-user-images.githubusercontent.com/6226732/346989128-819ab0ca-7a1a-4f96-ad8f-d6407eaa9f08.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MzQ0OTIsIm5iZiI6MTcyMDUzNDE5MiwicGF0aCI6Ii82MjI2NzMyLzM0Njk4OTEyOC04MTlhYjBjYS03YTFhLTRmOTYtYWQ4Zi1kNjQwN2VhYTlmMDgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDlUMTQwOTUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODVjNTE1OTdmNjI2N2FjNGM0NjhlMzgxNTE3ZjZiMzU1MDRjZWQ5ODg1Zjc0ODQxNTVhYTk5MjVjODY4N2RjMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.bATTLQmtQQv9PWDSvT_8CGUPbd0DVFWAEv-9fBliQ2M)

Thanks, @nrfox ! I'll check in that test suite.

**Comment by josunect** [comment]
> @josunect sorry I included the wrong test suite in the setup instructions. Only the multi-primary suite has openid auth enabled. I think the behavior did change recently because I'm now seeing a different error when I click on the west cluster after removing access for the kiali test user: ![Screenshot from 2024-07-09 10-07-23](https://private-user-images.githubusercontent.com/6226732/346989128-819ab0ca-7a1a-4f96-ad8f-d6407eaa9f08.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MzQ0OTIsIm5iZiI6MTcyMDUzNDE5MiwicGF0aCI6Ii82MjI2NzMyLzM0Njk4OTEyOC04MTlhYjBjYS03YTFhLTRmOTYtYWQ4Zi1kNjQwN2VhYTlmMDgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDlUMTQwOTUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODVjNTE1OTdmNjI2N2FjNGM0NjhlMzgxNTE3ZjZiMzU1MDRjZWQ5ODg1Zjc0ODQxNTVhYTk5MjVjODY4N2RjMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.bATTLQmtQQv9PWDSvT_8CGUPbd0DVFWAEv-9fBliQ2M)

@nrfox but this could also be tested with the token strategy?
