### ISSUE TITLE
Mesh page - controlplanes have an edge to every dataplane

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#7458]
### Describe the bug

On the mesh page, dataplanes have an edge to every controlplane.

### Expected Behavior

dataplanes should only be associated with the controlplanes that are managing them.

### What are the steps to reproduce this bug?

1. Deploy kiali + istio
    ```
    hack/run-integration-tests.sh --test-suite backend --setup-only true
    ```
2. Install a second revision 
    ```
    istioctl install --set revision=canary
    ```
3. Navigate to mesh page and notice that there's an edge from each controlplane going to all the dataplanes despite the fact that the `canary` revision does not manage any dataplane.
    ![image](https://github.com/kiali/kiali/assets/6226732/75f8bf66-8617-43b3-a60a-61c322bc931f)

### Environment
*Learn about how to determine versions [here](https://kiali.io/docs/faq/general/#how-do-i-determine-what-version-i-am-running).*

- **Kiali version: latest**
- **Istio version: 1.22**

**Comment by jshaughn** [comment]
I feel like this was working when each revision managed at least one namespace.  Hopefully it's a simple bug...

**Comment by ferhoyos** [comment]
The same occurs for multi-primary deployment:

![image](https://github.com/kiali/kiali/assets/122779323/74f44ea6-97ff-40dc-9936-e4b5f1be9d63)

Is this also a bug? Should dataplanes only be associated with the controlplanes of their own cluster?

**Comment by nrfox** [comment]
> Is this correct? Or should dataplanes only be associated with the controlplanes of their own cluster?

You can have controlplanes manage namespaces in remote clusters but in this multi-primary setup it is probably a bug.

**Comment by ferhoyos** [comment]
For primary-remote deployments, for sure, but the question is about multi-primary deployment. I think the restriction here is that a data plane should be handled by only one control plane in any case. Is that assumption correct @nrfox?

**Comment by nrfox** [comment]
> I think the restriction here is that a data plane should be handled by only one control plane in any case.

Yes the controlplane will still connect to the other cluster to get the endpoints for the workloads but shouldn't be managing the config for the other cluster.

**Comment by nrfox** [comment]
Also there should technically be a line from kiali to each istiod
