### ISSUE TITLE
Mesh page - Display full yaml from `istio` configmap

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#7459]
### Describe the bug

When you visit the mesh page and click on an istiod to see it's configuration, you only see a fraction of what is stored in the `istio` configmap:

![Screenshot from 2024-06-20 13-22-00](https://github.com/kiali/kiali/assets/6226732/5eddeace-2e9f-4f0a-b670-2f90105cbed3)

```
$ kubectl get configmaps -n istio-system istio -o yaml

data:
  mesh: |-
    accessLogFile: /dev/stdout
    defaultConfig:
      discoveryAddress: istiod.istio-system.svc:15012
      meshId: mesh-default
      tracing:
        sampling: 100
        zipkin:
          address: zipkin.istio-system:9411
    defaultProviders:
      metrics:
      - prometheus
    enableAutoMtls: true
    enablePrometheusMerge: true
    enableTracing: true
    extensionProviders:
    - envoyOtelAls:
        port: 4317
        service: opentelemetry-collector.observability.svc.cluster.local
      name: otel
    - name: skywalking
      skywalking:
        port: 11800
        service: tracing.istio-system.svc.cluster.local
    - name: otel-tracing
      opentelemetry:
        port: 4317
        service: opentelemetry-collector.observability.svc.cluster.local
    rootNamespace: istio-system
    trustDomain: cluster.local
  meshNetworks: 'networks: {}'

```

### Expected Behavior

Expected to see the full istio configuration.

### What are the steps to reproduce this bug?

1. Deploy istio + kiali
2. Navigate to mesh page and click on the `istiod` node.
3. Compare with the `istio` configmap: `kubectl get configmaps -n istio-system istio -o yaml`

The mesh page's istiod component is currently displaying the internal kiali configuration object which doesn't contain all the values from the configmap. Kiali gets the configmap data and could just send the raw yaml to the frontend rather than the internal configuration object. Kiali could also just display the raw yaml from the configmap rather than reformatting it as a table.

"Configuration" might even be a little misleading here since I think there are some settings that are present on the helm chart values but I don't think they make into the `istio` configmap. I'm not positive but I think what is in the configmap is only the global mesh options: https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/.

**Comment by josunect** [comment]
Should this be visible for users that does not have access to the istio-system namespace?
