### ISSUE TITLE
Mesh page - Hide mesh page for non istio-system users

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#7527]
### What do you want to improve?

The new mesh page shows information about the istio controlplane but should be hidden for users who don't have read access to the `istio-system` namespace.

### What is the current behavior?

Mesh page can be seen by all users.

### What is the new behavior?

Mesh page is hidden for users without read access to `istio-system`.

`/api/mesh/graph` checks for read access to `istio-system`.

**Comment by josunect** [comment]
Apart from these changes, maybe it should not check the istio component status:

![image](https://github.com/user-attachments/assets/6b718e2d-4d30-4c4a-baa9-6f6158eb999e)
