### ISSUE TITLE
Using "sh" to run the install script fails due to invalid comparison operator

### ISSUE THREAD

**Issue by cisco-** [kiali/kiali#756]
**Describe the bug**
When following the instructions at https://www.kiali.io/gettingstarted/#_getting_started_on_kubernetes I'm asked to run the install script through "sh" 

```
curl -L http://git.io/getLatestKialiKubernetes | sh
```

But "sh" doesn't seem to like the "==" comparison operator giving me: 

```
sh: 71: [: lastrelease: unexpected operator
sh: 81: [: lastrelease: unexpected operator
```

Running it through bash seems to work better: 

```
curl -L http://git.io/getLatestKialiKubernetes | bash
```

Either update the documentation to use bash or replace the == operator in the comparisons with =

**Versions used**
Kiali: v0.11.0

**To Reproduce**
1. Run "curl -L http://git.io/getLatestKialiKubernetes | sh" 

**Expected behavior**
The script should not abort with the parsing error

**Comment by jmazzitelli** [comment]
We can either change the code (PR https://github.com/kiali/kiali/pull/757) or the docs (PR https://github.com/kiali/kiali.io/pull/86)

If we change the code so it runs in sh, we should change the header to `#!/bin/sh` and we need to change both install scripts (there is one for k8s and one for OS - see `deploy/{kubernetes,openshift}` directories.

**Comment by jmazzitelli** [comment]
FWIW: I'm leaning towards making sure these two scripts support sh (along with bash). I don't have a system with a true bourne shell, so @cisco- I'll need your help to test that we don't break anything :)

**Comment by jmazzitelli** [comment]
OK, talking on #kiali about this - we're just going to change the docs. The scripts already say #!/bin/bash and since most modern systems (all?) have bash, we should be good.

**Comment by jmazzitelli** [comment]
@cisco- thanks for finding this! I updated the docs to say `| bash`. It will get published soon.

**Comment by jmazzitelli** [comment]
Docs have been published - it now tells people to run the script with `bash`... again, thanks to @cisco- for finding and reporting this bug.

**Comment by cisco-** [comment]
Perfect! Thanks!
