### ISSUE TITLE
Support for additional environment variables in deployment

### ISSUE THREAD

**Issue by arenfitch** [kiali/kiali#7569]
### What do you want to improve?
Support for additional environment variables, we have a zero-trust network model where all the egress traffic should go through proxy.
We use  Grafana cloud's Prometheus which is hosted outside of our network.

Ideally it will be nice to have a feature to provide additional environmental variables to deployment, specifically in my case: HTTP_PROXY, HTTPS_PROXY, NO_PROXY

### What is the current behavior?
Unable to add new environmental variables to deployment

### What is the new behavior?
To be able to add new environmental variables to deployment

**Comment by jmazzitelli** [comment]
You can already tell Kiali what custom external URLs to use when talking to Prometheus, Grafana, Jaeger, etc. in the external services section of the config. Is that not working?

**Comment by arenfitch** [comment]
Are you saying to add proxy endpoint in external URL's?
With curl I do this, passing a proxy endpoint 
` curl -s -u "xxxx:yyyyy" https://<promethues_endpoint>.grafana.net/api/prom/api/v1/label/__name__/values -x  http://<PROXY>`

**Comment by jmazzitelli** [comment]
I was thinking you can provide an accessible URL in the external_services sections of the Kiali CR. But if you must use a proxy to get to the outside, maybe not.

I'm not sure if even setting those env vars on the kiali pod is going to help. Did you try it? Manually modify the Kiali Deployment and add those env vars that you need and see if it works.

**Comment by arenfitch** [comment]
Yes, I did give it a try and seems to be working.

**Comment by jshaughn** [comment]
I'm not exactly sure why this hasn't been necessary for other users, but it doesn't seem like bad feature for unexpected situations.  @arenfitch , would you be interested in contributing this enhancement?

**Comment by jmazzitelli** [comment]
this is essentially the same feature request of https://github.com/kiali/kiali/issues/6386

**Comment by jmazzitelli** [comment]
I'm going to work on this. Someone provided the [server helm chart work](https://github.com/kiali/helm-charts/pull/291), and since we have now had several people ask for this, its time to implement it.

**Comment by jmazzitelli** [comment]
PRs:
* operator: https://github.com/kiali/kiali-operator/pull/829
* server helm chart: https://github.com/kiali/helm-charts/pull/291
