### ISSUE TITLE
Multi-cluster ServiceEntry Routing

### ISSUE THREAD

**Issue by zodiac12k** [kiali/kiali#7589]
### Describe the bug

We are experiencing an issue with Kiali's multi-cluster functionality. Specifically, it appears that ServiceEntry routing is not functioning as expected. In our setup, we have two clusters, e.g., `a1` and `a2`, with identical ServiceEntry configurations for the same host. However, the traffic seems to be incorrectly routed to the ServiceEntry of the other cluster, as depicted in the attached Kiali graph.

### Expected Behavior

Each cluster's workloads should route traffic to their respective ServiceEntry resources.

### What are the steps to reproduce this bug?

1. Set up two clusters (`a1` and `a2`).
2. In both clusters, create identical ServiceEntry resources for the same host, e.g., `a.example.com`.
3. Deploy workloads in both clusters that should use their respective ServiceEntry resources.
4. Observe the traffic flow in Kiali.

### Environment
*Learn about how to determine versions [here](https://kiali.io/docs/faq/general/#how-do-i-determine-what-version-i-am-running).*

- **Kiali version:** 1.85.0
- **Istio version:** 1.21.3
- **Kubernetes impl:** Openshift
- **Kubernetes version:** 1.23.17
- **Other notable environmental factors:**

**Comment by jshaughn** [comment]
@zodiac12k Canyou attach the graph?

**Comment by zodiac12k** [comment]
@jshaughn  Here is the graph you requested. I've attached the screenshot, and I've redacted sensitive information for confidentiality. Please let me know if you need any additional details.

![image](https://github.com/user-attachments/assets/747dbe14-9351-4aba-9dbb-fd0f52b51fad)

**Comment by jshaughn** [comment]
I haven't yet spotted a problem in the code.  One thing I am curious about is whether it's possible Istio is in fact making a cross-cluster request.  Are you able to query Prometheus (see https://kiali.io/docs/faq/graph/#queryprom)?  I'd be curious in the result of:

 `sum(istio_requests_total{source_cluster="your-cluster-2-name",source_workload_namespace="your-namespace-name",source_canonical_service="core-api-latest"}) by (destination_cluster, destination_service_name)`

replacing `your-cluster-2-name` and `your-namespace-name` as needed.  If we see destination traffic to cluster-1 then it would explain your graph.  If the destination traffic is all to cluster-2, then I'll keep looking :-)

**Comment by zodiac12k** [comment]
I ran the Prometheus query, and the result shows that the destination_cluster is marked as unknown. Could this be related to the issue we're seeing?

![image](https://github.com/user-attachments/assets/09464db3-6069-4621-b2cb-da4f881644c2)

**Comment by jshaughn** [comment]
Thanks for running the query.  Thinking more on this, `destination_cluster="unknown"` may make sense here, as the destination is actually a remote host, to be reached via the service entry, right?  Do all of those `destination_service_name` values match hosts defined for the service entry on cluster `a2` (the right side of your screenshot)?

**Comment by jshaughn** [comment]
Can you do me a favor and perform the following Prom query?  I have a theory about what may be the issue here, and I want to see if your data backs it up:

`sum(istio_requests_total{source_canonical_service="core-api-latest"}) by (source_cluster, source_workload_namespace,destination_cluster, destination_service_namespace, destination_service_name)`

**Comment by zodiac12k** [comment]
> Can you do me a favor and perform the following Prom query? I have a theory about what may be the issue here, and I want to see if your data backs it up:
> 
> `sum(istio_requests_total{source_canonical_service="core-api-latest"}) by (source_cluster, source_workload_namespace,destination_cluster, destination_service_namespace, destination_service_name)`

I have run the additional Prometheus query you requested:

![image](https://github.com/user-attachments/assets/51278540-29ad-43c2-8139-6b64afd1caca)

**Comment by zodiac12k** [comment]
> Thanks for running the query. Thinking more on this, `destination_cluster="unknown"` may make sense here, as the destination is actually a remote host, to be reached via the service entry, right? Do all of those `destination_service_name` values match hosts defined for the service entry on cluster `a2` (the right side of your screenshot)?

The configuration is correct. In my opinion, whether destination_cluster is unknown or a1, the workload in a1 should use the ServiceEntry in a1, so it makes sense that the arrow would point to the ServiceEntry in a1.

**Comment by jshaughn** [comment]
I don't quite understand the query results, I would have expected some `core-api` time-series to have a `source_cluster="a2"`, as your original graph shows that as the problem, the `a2`  `core-api` has an edge to the `a1` service entry.

Regardless, I have done some work based on our discussion so far,  and I think it will resolve your issue.  You can wait for the next Kiali release to test it, or you can use the next nightly build image (will be built around 12 hours from now) found here: https://quay.io/repository/kiali/kiali?tab=tags

**Comment by zodiac12k** [comment]
The original graph was a snapshot of a specific moment, but in reality, the core-api in cluster a1 sometimes points to the ServiceEntry in cluster a2, and the opposite also occurs. Once the Kiali version with the expected fix is released, I will update to that version, test it, and let you know the results. Thank you for your efforts in resolving this issue.

**Comment by jshaughn** [comment]
This fix should be backported to v1.89 for release in v1.89.x.
