### ISSUE TITLE
Inconsistent ServiceEntry Display in Multi-Namespace Environment

### ISSUE THREAD

**Issue by zodiac12k** [kiali/kiali#7590]
### Describe the bug

We are experiencing an issue with the Kiali graph displaying ServiceEntry connections incorrectly in a multi-namespace environment. Our Istio global mesh config is set with `defaultServiceExportTo` as `"."`. We have the same host's ServiceEntry registered in two different namespaces. However, intermittently, the Kiali graph shows traffic routing to the ServiceEntry in the other namespace. When we explicitly set `exportTo` as `"."` in the ServiceEntry, it displays correctly, routing traffic within the same namespace.

### Expected Behavior

Each namespace's workloads should route traffic to their respective ServiceEntry resources, as specified by the global mesh config setting.

### What are the steps to reproduce this bug?

1. Configure Istio global mesh config with `defaultServiceExportTo: "."`.
2. Create two namespaces.
3. In each namespace, create a ServiceEntry for the same host.
4. Deploy workloads in each namespace that use the ServiceEntry.
5. Observe the traffic flow in Kiali.

### Environment
*Learn about how to determine versions [here](https://kiali.io/docs/faq/general/#how-do-i-determine-what-version-i-am-running).*

- **Kiali version:** 1.85.0
- **Istio version:** 1.21.3
- **Kubernetes impl:** Openshift
- **Kubernetes version:** 1.23.17
- **Other notable environmental factors:**

**Comment by jmazzitelli** [comment]
This sounds like this might be a duplicate. Please see these issues and see if they are related:

* https://github.com/kiali/kiali/issues/7537
* https://github.com/kiali/kiali/issues/7153

This comment is one I think may be related: https://github.com/kiali/kiali/issues/7537#issuecomment-2234052694

**Comment by zodiac12k** [comment]
> This sounds like this might be a duplicate. Please see these issues and see if they are related:
> 
> * [Kiali Graph showing incorrectly when we create Multiple Service entry with same hosts and different port #7537](https://github.com/kiali/kiali/issues/7537)
> * [[graph] ServiceEntry ExportTo is not handled correctly #7153](https://github.com/kiali/kiali/issues/7153)
> 
> This comment is one I think may be related: [#7537 (comment)](https://github.com/kiali/kiali/issues/7537#issuecomment-2234052694)

@jmazzitelli Thank you for your reply
It seems in your comment the ports are different, but in our case, the ports are the same.

**Comment by jshaughn** [comment]
> Our Istio global mesh config is set with defaultServiceExportTo as "."

It may be that this default isn't honored by Kiali.  The the SE definition doesn't specify `exportTo` the typical default is "all namespaces".  And I think that's the assumption we make in the code.

@hhovsepy , I see you are assigned, have you looked at this?

**Comment by hhovsepy** [comment]
> > Our Istio global mesh config is set with defaultServiceExportTo as "."
> 
> It may be that this default isn't honored by Kiali. The the SE definition doesn't specify `exportTo` the typical default is "all namespaces". And I think that's the assumption we make in the code.
> 
> @hhovsepy , I see you are assigned, have you looked at this?

Yes, I saw that we miss 'defaultServiceExportTo' and other default export to configs from mesh to consider when SE, DR and VS do not have set own 'ExportTo'. Adding them now.

**Comment by jshaughn** [comment]
The fix should be backported to v1.89 branch.
