### ISSUE TITLE
Istio Gateway pod detected being having an issue

### ISSUE THREAD

**Issue by bangau1** [kiali/kiali#760]
Hi,

Using kiali version `v0.9.1`, the `istio-ingressgateway`'s pod is detected to have an issue:
<img width="659" alt="screen shot 2018-12-27 at 13 50 53" src="https://user-images.githubusercontent.com/352737/50469416-ddcb7900-09de-11e9-9628-ec9835aa12d6.png">

I think this is not a bug. But istio-ingressgateway is expected to not having a side-car proxy either, since the main container is basically istio-proxy itself. Probably it is worth to have whitelist mechanism to exclude the ingress/egress pod?

What do you think?

**Comment by aljesusg** [comment]
Hi @bangau1, thanks for open this issue. We have a topic to discuss about this.

Anyway you can exclude the namespaces related with the Istio installation and not with your environment in Kiali.


https://github.com/kiali/kiali/blob/master/README.adoc#environment-variables

---

API_NAMESPACES_EXCLUDE

An optional list of namespaces/projects excluded from the list of namespaces provided by the API and UI. Regex is supported. This does not affect explicit namespace access.
---
```yaml
api:
  namespaces:
    exclude:
    - namespacePattern1
    - namespacePattern2
    - etc..
```

**Comment by bangau1** [comment]
Hi @aljesusg thanks for the reply.

> We have a topic to discuss about this.

May I know whether it is an internal discussion or is there any public github issue discussion?

Also, your recommendation for now it to exclude the `istio-system` namespace, right? After some thought, i think this is okay, since all the pods in this `istio-system` is basically doesn't need side-car proxy. 
However, in my multi-tenant k8s cluster, we do provision a dedicated istio ingress gateway to certain namespace other than `istio-system`. So perhaps, other than namespace exclusion, i think using `label` selector is more fine grain approach?

**Comment by aljesusg** [comment]
Sorry I had a typo, we discussed it.

The JIRA was: https://issues.jboss.org/browse/KIALI-1812
The PR was: https://github.com/kiali/kiali/pull/580

So Yes istio-system namespace have all the pods of the installation and they don't need istio-sidecar ,I personally would exclude it but this is an optional configuration you can ignore the warnings inside istio-system namespace.

**Comment by jshaughn** [comment]
I actually think excluding the istio-system namespace is overkill.  It can be useful to inspect istio-system.  I think in this case Kiali should better handle the istio-system namespace as a special case, perhaps explicitly omitting it from the failing validation checks.

**Comment by aljesusg** [comment]
I think that we can close this.
