### ISSUE TITLE
Upgrade OSSMC api from v1alpha1 to v1

### ISSUE THREAD

**Issue by mkralik3** [kiali/kiali#7622]
### Describe the bug

OSSMC doesn't work on OCP 4.17 
```
Failed to create object: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"conversion webhook for console.openshift.io/v1alpha1, Kind=ConsolePlugin failed: Post \\"https://webhook.openshift-console-operator.svc:9443/crdconvert?timeout=30s\\": service \\"webhook\\" not found","code":500}\n'
```
The `v1alpha1` api is going to be removed. It should be safe to upgrade to `v1` api in the [templates](https://github.com/kiali/kiali-operator/blob/master/roles/default/ossmconsole-deploy/templates/openshift/consoleplugin.yaml#L1) since it is available from OCP 4.12+ (https://docs.openshift.com/container-platform/4.12/rest_api/console_apis/consoleplugin-console-openshift-io-v1.html)

Backport to 1.73 and 1.86 are needed as well

**Comment by jmazzitelli** [comment]
This is all that needs to be done:

In the master branch of the operator (https://github.com/kiali/kiali-operator), change "v1alpha1" to "v1" in the first line of these three templates:

- https://github.com/kiali/kiali-operator/blob/master/roles/default/ossmconsole-deploy/templates/openshift/consoleplugin.yaml#L1
- https://github.com/kiali/kiali-operator/blob/v1.73/roles/default/ossmconsole-deploy/templates/openshift/consoleplugin.yaml#L1
- https://github.com/kiali/kiali-operator/blob/v1.86/roles/default/ossmconsole-deploy/templates/openshift/consoleplugin.yaml#L1

Then backport to the 1.73 branch and 1.86 branch:

- https://github.com/kiali/kiali-operator/tree/v1.73
- https://github.com/kiali/kiali-operator/tree/v1.86

**Comment by jmazzitelli** [comment]
PRs:

* master branch: https://github.com/kiali/kiali-operator/pull/802
* 1.73 branch: https://github.com/kiali/kiali-operator/pull/803
* 1.86 branch: https://github.com/kiali/kiali-operator/pull/804

**Comment by jmazzitelli** [comment]
Looks like there is more work to be done:

```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to create object: 
b'{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":
{},\"status\":\"Failure\",\"message\":\"ConsolePlugin.console.openshift.io \\\\\"ossmconsole\\\\\" is invalid: 
[spec.proxy[0].endpoint: Required value, spec.backend: Required value]\",\"reason\":\"Invalid\",\"details\":
{\"name\":\"ossmconsole\",\"group\":\"console.openshift.io\",\"kind\":\"ConsolePlugin\",\"causes\":
[{\"reason\":\"FieldValueRequired\",\"message\":\"Required value\",\"field\":\"spec.proxy[0].endpoint\"},
{\"reason\":\"FieldValueRequired\",\"message\":\"Required value\",\"field\":\"spec.backend\"}]},\"code\":422}\\n'", 
"reason": "Unprocessable Entity"}
```

**Comment by jmazzitelli** [comment]
The PRs get the Console Plugin resource with the proper YAML, but now the plugin cannot talk to Kiali. We need to figure out what changes were made in v1 so we can update correctly. This is what happens now:
![image](https://github.com/user-attachments/assets/326228e2-1ea5-41fd-9a82-d6e3b9ba17ac)

server logs has this:
```
2024-08-13T19:03:36Z ERR Failed to clean a stale session: logout problem: no session exists.
2024-08-13T19:03:36Z ERR Failed to clean a stale session: logout problem: no session exists.
2024-08-13T19:03:36Z ERR Failed to clean a stale session: logout problem: no session exists.
2024/08/13 19:03:36 http: TLS handshake error from 10.217.0.43:50304: EOF
2024/08/13 19:03:36 http: TLS handshake error from 10.217.0.43:50308: EOF
2024-08-13T19:03:36Z ERR Failed to clean a stale session: logout problem: no session exists.
2024-08-13T19:03:36Z ERR Failed to clean a stale session: logout problem: no session exists.
2024-08-13T19:03:37Z ERR Failed to clean a stale session: logout problem: no session exists.
```

**Comment by jmazzitelli** [comment]
Assigning to @ferhoyos since I think he knows better than most how the plugin is configured to talk to the Kiali server.

**Comment by jmazzitelli** [comment]
He got it figured out.. just a few more fields changed in v1 that needs to be incorporated. That's done. My smoke testing shows it working. I will run the ossmc molecule tests now.

**Comment by jmazzitelli** [comment]
molecule tests now pass.. these PRs are ready for merge:

```
=====================
=== TEST RESULTS: ===
=====================

          ossmconsole-config-values-test... success [2m 10s]
                     ossmconsole-default... success [1m 56s]
```
