### ISSUE TITLE
[v1.57][v1.65] Remove openssl-legacy-provider like master

### ISSUE THREAD

**Issue by aljesusg** [kiali/kiali#7632]
### Describe the bug

After upgrade to nodejs 20  we need to remove the openssl-legacy-provider

### Expected Behavior

Run builds without problem

### Created by

https://github.com/kiali/kiali/pull/7613
https://github.com/kiali/kiali/pull/7612

### Related 

https://github.com/kiali/kiali/pull/6568

**Comment by jshaughn** [comment]
@aljesusg Is there more work here, it looks like both PRs are merged?

**Comment by aljesusg** [comment]
It's done I don't know why is open. I was hoping it would close by itself.
