### ISSUE TITLE
Issue querying Grafana Mimir for metrics

### ISSUE THREAD

**Issue by JDuskey** [kiali/kiali#7651]
### Describe the bug

When using Mimir as the backing datasource, we get lots of logs like this:
```
Error getting Prometheus version: invalid character 'p' after top-level value
```

It looks like this is caused by Kiali checking a `/version` endpoint that is as far as I can find scarcely documented. Mimir offers the same `/api/v1/status/buildinfo` that prometheus has documented, but there seems to be no way to force this to be used. Furthermore, if I could get it to be used, the format of the JSON is different than what is provided by `/version`, so it wouldn't be parseable. I originally added a PR to add this to the thanos_proxy configs similar to the other overrides that are already provided, but closed that PR out to have a discussion here instead.

Ideally this `/version` endpoint also isn't harcoded, but I'd like to at least use what is documented in the Prometheus project:
https://prometheus.io/docs/prometheus/latest/querying/api/#:~:text=GET%20/api/v1/status/buildinfo

### What are the steps to reproduce this bug?

1. Configure Kiali to use Mimir for metrics
2. Look at logs for Prometheus version errors

**Comment by jmazzitelli** [comment]
Sounds like we could add some kind of setting in the Prometheus external_services to tell it where the version endpoint is. We have something similar for Istio -- see https://kiali.io/docs/configuration/kialis.kiali.io/#.spec.external_services.istio.url_service_version

We could add something for prometheus... something similar to the health_check_url we already have: https://kiali.io/docs/configuration/kialis.kiali.io/#.spec.external_services.prometheus.health_check_url

(BTW: @JDuskey did you set the xternal_services.prometheus.health_check_url? Maybe that does what you need already?)

**Comment by nrfox** [comment]
I suspect that `/version` is an older endpoint and `/api/v1/status/buildinfo`  is "newer". I don't even see `/version` documented anywhere in the current docs. IMO we should just use `/api/v1/status/buildinfo`. 

https://prometheus.io/docs/prometheus/latest/querying/api/#build-information

> It looks like this is caused by Kiali checking a /version endpoint that is as far as I can find scarcely documented.

There's some info on what endpoints Kiali requires from prom [here](https://kiali.io/docs/configuration/p8s-jaeger-grafana/prometheus/#compatibility-with-prometheus-like-servers) but you're right it doesn't include `/version`  and I don't think it's exhaustive. We should update to the docs to spell out what all the endpoints are exactly.

**Comment by jmazzitelli** [comment]
Sounds like as part of this we need to change the default endpoint... we should be getting this from the [buildinfo](https://prometheus.io/docs/prometheus/latest/querying/api/#build-information) endpoint of Prometheus, not `/version` - since it sounds like that might be the more "standard" way to do it. I don't even see `/version` documented there.

**Comment by JDuskey** [comment]
The location of that endpoint is the same on Mimir and prometheus IIRC. I can push a PR to refactor this to use the buildinfo endpoint instead and allow an optional value to configure that endpoint's location for any non-standard installs if that is agreeable.

**Comment by JDuskey** [comment]
>There's some info on what endpoints Kiali requires from prom [here](https://kiali.io/docs/configuration/p8s-jaeger-grafana/prometheus/#compatibility-with-prometheus-like-servers) but you're right it doesn't include /version

Thanks for addressing this, I was trying to say that that endpoint was missing from the prometheus documentation, but yes some docs in Kiali as well wouldn't hurt.

**Comment by jshaughn** [comment]
As long as the APi exists in the supported versions of Prom, Thanos and Mimir I think we're good just changing to use the new endpoint.

**Comment by JDuskey** [comment]
Did some research first just to have it documented that the major metrics stores were checked for compatibility with the `/api/v1/status/buildinfo` endpoint before pushing up a PR:

- Prometheus has this [documented](https://prometheus.io/docs/prometheus/latest/querying/api/#build-information)

-  Mimir also has this documented in the [HTTP API docs](https://grafana.com/docs/mimir/latest/references/http-api/#build-information)

- VictoriaMetrics makes just the version available in the API(https://github.com/VictoriaMetrics/VictoriaMetrics/blob/535a9ed0596e897a9dfd5bea5add324e6c81b21a/app/vmselect/main.go#L547), but that should be all we need. Previously, the revision was pulled into the struct as well, but not used anywhere. We only use the version info for the status check.

Thanos appears to have this at the same location: https://github.com/onprem/thanos/blob/23ca39de4fffc1e42f3ce0a0a57b3e87da3b107d/pkg/api/api.go#L152

I think this should be a safe change given this info.

**Comment by jshaughn** [comment]
I'm good with @JDuskey making the change, @jmazzitelli ?

**Comment by jmazzitelli** [comment]
> I'm good with @JDuskey making the change, @jmazzitelli ?

Looking forward to reviewing a PR :)

**Comment by Ayatallah** [comment]
@JDuskey how did you get Kiali to work with Mimir at the end? I still get Prometheus unreachable in Kiali UI and see the same logs you see with the following:
```
    external_services:
      grafana:
        enabled: true
        in_cluster_url: "http://grafana.grafana:80/"
      prometheus:
        url: "http://mimir-gateway.mimir/prometheus"
        custom_headers:
          X-Scope-OrgID: header-value
```

**Comment by jshaughn** [comment]
@Ayatallah , @JDuskey , any luck here?
