### ISSUE TITLE
stop namespace-scoped kube cache on namespace delete

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#7655]
As part of the [discovery selector work](https://github.com/kiali/kiali/issues/7546), I came across the need for our internals to shutdown namespace-scoped kube caches for namespaces that have been deleted.

This is ONLY a concern when `cluster_wide_access` is `false`.

**Comment by jmazzitelli** [comment]
I had a discussion with @nrfox offline. I want to post that discussion here as it contains some ideas and thoughts that we bounced around that I did not want to lose.

---

_mazz_: just take a quick look at this and tell me what you think: https://github.com/kiali/kiali/pull/7629 (the important commit is this one: https://github.com/kiali/kiali/pull/7629/commits/bc6f38cf096ae8c5f99f5b13f6e69d122dbcff80). I think it actually does what I was hoping for... but I'm thinking to myself it can't be this easy, and I must be missing something. The idea is - when a namespace is deleted, we want to stop watching the resources from that namespace because the watcher is just going to continue to flood the logs with errors saying it is forbidden from seeing all the resources. This stops the namespace cache when this condition is detected.

_nfox_: That does seem like it could work but I also don't know enough about the inner workings of the informers to know if there would be any weird side effects from it. This comment on the signature gives me pause:
```
	// The handler is intended for visibility, not to e.g. pause the consumers.
	// The handler should return quickly - any expensive processing should be
	// offloaded.
```
Might be some edge cases like what happens when a namespace is deleted and then recreated?
We can ask someone else who knows more about the informer internals. There has to be prior art on stopping watches when namespaces no longer exist.

Thinking out loud you would almost want a separate thread that watches namespaces and then starts/stops the informer when the namespace gets created or deleted but you can't do this in the server because you don't have cluster wide access to watch all namespaces. That's what the operator already does in fact. Maybe we just need a way to update the list of namespaces we're watching without restarting the kiali pod? You could have the operator write the list of namespaces to a separate configmap that the Kiali server watches and then will start/stop informers based off that?

_mazz_: I thought we could just poll all existing namespaces, but we can't because when cluster_wide_access is false the server will not have LIST permission. I'm going to think about this some more. there has to be a good way to do this in the server itself without requiring the operator. Then again, the operator has to be involved with cluster_wide_access is false because it needs to create the Role... so... i dunno. when cluster_wide_access is true, maybe doing this makes sense.

I need to look to see what happens when cluster_wide_access is true and still have defined discovery selectors - and then delete a namespace that originally matched a selector when the server started up (ok, just tried that.. nothing unusual, which makes sense since its a cluster-wide informer so it doesn't care that a namespace was removed or not) 

_nfox_: Yeah for cluster_wide_access = true it doesn't matter because it's only ever a single cluster scoped watch so we never need to stop/restart it. And like you said, the operator needs to create the Role and it needs to keep the list of namespaces up to date. The server doesn't have permissions to do either one of those but the server can stop/start the informers when the list gets updated. It just so happens that right now when you update the list the server pod gets restarted but if we can change it so that the list can get updated and the server can read the list without restarting the pod then I think we're good?

_mazz_: for NEW namespaces, we already have things working (albeit requires the server pod to restart - meh, OK, not great, but we still work). It's the deletion of namespaces that we need to fix. But here's my bug-a-boo about that - for the operator to watch for deletion of namespaces, it requires the operator to attach a finalizer on the namespace. And putting a finalizer on a namespace scares me because if something happens to the operator and it fails to properly process it, that finalizer is going to screw the user up because now that namespace will not be able to be deleted unless someone goes in an manually removes the finalizer. And then people are going to say, "wth is this kiali thing and why is it blocking my namespace from getting deleted". I haven't tested watching for namespaces to be deleted in the operator, but I'm 90% sure that's how it is going to work and that's my fear - the finalizer doesn't get cleaned up (for whatever odd reason) and people start to hate us. On the flip side, it has to be easy to clean these informers up for a deleting namespace. I mean, that little bit of code I have seems to already do the bulk of it. The only question is - is the informer still consuming resources that we need to clean up? But how hard could that be?

_nfox_: Why would you need to put a finalizer on the namespace?

_mazz_: its just the way the ansible operator works when processing deleted resources: https://sdk.operatorframework.io/docs/building-operators/ansible/reference/finalizers/

_nfox_: but sometimes it is necessary to perform more complex operations (for example, when your action performed against a third party API needs to be undone). This makes it sounds optional to me

_mazz_: It is all about how to tell the ansible operator to watch for namespaces to be deleted.

_nfox_: The operator also isn't creating the namespaces. It's only watching them. There's no owner ref/label to the Kiali CR on the namespace

I'm guessing it's doing it already unless you can filter on specific events. There's three type of watch events (create, update, delete).

_mazz_:  https://github.com/kiali/kiali-operator/blob/master/watches-k8s-ns.yaml#L15-L24 -- that's how we tell it "watch for new namespaces" ... that's how you do it in ansible operator-ese; add a "finalizer" section, and that tells the ansible operator SDK to then watch for "Delete"

_nfox_: Are you sure that playbook doesn't get run when you delete a namespace as well?

_mazz_: I am 99% sure. https://sdk.operatorframework.io/docs/building-operators/ansible/reference/watches/ - I've never seen it run on deletion, and the docs say the deletion event is added with the "finalizer" configuraton. I will run a quick test right now to make me 100% sure.

_nfox_: Shouldn't this be true: watchClusterScopedResources for namespaces?

_mazz_: So, here's what happens. Create a namepace, and that playbook runs as expected. DELETE the namespace, and the ansible core DOES get the event, it just does nothing with it:
```
{"level":"info","ts":"2024-08-16T13:15:36Z","logger":"reconciler","msg":"Resource is terminated, skipping reconciliation","job":"7599630160767539858","name":"mazz","namespace":""}
{"level":"info","ts":"2024-08-16T13:15:41Z","logger":"reconciler","msg":"Resource is terminated, skipping reconciliation","job":"4987928099095599759","name":"mazz","namespace":""}
```
That's because (I'm assuming) there is no finalizer section in my watches operator config file. But if I configure the operator with that finalizer section, that it will run the playbook on delete.

_nfox_: Ok and that kind of makes sense: https://github.com/operator-framework/ansible-operator-plugins/blob/42b5d80c75f1ddda8f2dbe1629b9454d366a8d6a/internal/ansible/controller/reconcile.go#L104-L118

Well I agree that putting finalizers on namespaces is a bad idea. Maybe you don't even need "watches". Instead what you should be able to do is have something that periodically (every 10s?) gets the list of namespaces and tells the server about them. It's ok if we miss some that get created or deleted because every 10s it'll be up to date and that's probably good enough. Like setting this: reconcilePeriod: 10s ... with no watches.

_mazz_: I just tried to see what would happen if I did add a finalizer and... we don't even give the operator permission apparently:
```
{"level":"error","ts":"2024-08-16T13:21:50Z","logger":"reconciler","msg":"Unable to update cr with finalizer","job":"867440488337933985","name":"istio-system","namespace":"","error":"namespaces \"istio-system\" is forbidden: User \"system:serviceaccount:kiali-operator:kiali-operator\" cannot update resource \"namespaces\" in API group \"\" in the namespace \"istio-system\"","stacktrace":"github.com/
```
So, yeah, I don't want to mess with finalizers on namespaces

_nfox_: Yeah people would definitely complain about that

_mazz_: I could play with a reconcilePeriod, yeah. hmmm.. lemme ponder on that.

**Comment by jmazzitelli** [comment]
> Maybe you don't even need "watches". Instead what you should be able to do is have something that periodically (every 10s?) gets the list of namespaces

I thought we could do this on namespaces themselves, but that's not good. I just ran a test to make sure what I thought would happen actually does happen. If we configure the watches yaml file with a reconcilePeriod of 10s for Namespaces, every 10 seconds FOR EVERY namespace, the playbook is invoked. So if you have 10 namespaces, every 10 seconds the playbook will run 10 times. For 100 namespaces, 100 times.... etc. etc. Way too much and people will most definitely complain that the operator is spinning too much and consuming resources. So that isn't a good solution.

There is no "timer" mechanism that the ansible operator SDK provides, so it isn't like we can just say "run this playbook every 10 seconds" (well, there is nothing that I know of; I'm asking around to see if its even possible; I do not think it is). That might be an interesting enhancement request we submit to the ansible operator SDK folks, but it likely isn't a feature available today or in the near-to-midterm future, even if we propose this enhancement.

**Comment by jmazzitelli** [comment]
I did add this for the new discovery selector docs: https://deploy-preview-807--kiali.netlify.app/docs/configuration/namespace-management/#operator-namespace-watching

We _could_ tell users that if they want namespaces (new ones or ones that are deleted) to be detected, they can simply set the reconcile period on the Kiali CR itself. Then, every X seconds, the operator will process that Kiali CR and will detect new namespaces added and old namespaces removed and will do the proper thing (create Roles and set the correct discovery selectors in the ConfigMap). It will restart the Kiali Pod, which is something we ideally would like to avoid if possible, but it isn't horrible having to restart the Kiali pod. The only issue is if the discovery selectors are constantly detecting new namespaces, or namespaces that used to match are constantly deleted, then the kiali pod will constantly be going up and down. That's why we ideally would like to avoid restarting the kiali pod if possible.

**Comment by jshaughn** [comment]
If we were to ask for an enhancement we should ask for a non-finalizer way to reconcile on namespace-delete.  If not stopping the watcher-on-delete generates a bunch of errors for us (because the ns isn't there), maybe we should defer to the server to detect it and stop watching?  (sorry if you've already been through this line of thinking)

**Comment by jmazzitelli** [comment]
> maybe we should defer to the server to detect it and stop watching?

That's exactly what this does - I really think this is 90% there.. just need to cleanup the k8s client to make sure it isn't consuming any resources anymore

>_mazz_: just take a quick look at this and tell me what you think: #7629 (the important commit is this one: [bc6f38c](https://github.com/kiali/kiali/commit/bc6f38cf096ae8c5f99f5b13f6e69d122dbcff80)).

**Comment by nrfox** [comment]
> If we were to ask for an enhancement we should ask for a non-finalizer way to reconcile on namespace-delete.

I think it's valid use case. We still want to run the playbook even if the object no longer exists but we don't need to perform any actions on the object before it gets deleted like you would with a finalizer.

Do we even need ansible-operator for this? A cronjob that runs every 30s would do.

My only two concerns with having the server do it is that 1. when namespaces get deleted and/or recreated they won't get picked back up by Kiali which will confuse people and 2. I don't know what the side effects of stopping the cache in that handler are and the comment on it specifically says that it's "not for pausing consumers" which I think is what we're doing here. Might still be ok but I don't know enough to say one way or other.

**Comment by nrfox** [comment]
> Do we even need ansible-operator for this? A cronjob that runs every 30s would do.

Maybe another container in the operator pod that just does:
```
allNamespaces := kubectl get ns
for kialis:
  kiali.configmap.discoverySelectors = allNamespaces - kiali.discoverySelectors
```

**Comment by nrfox** [comment]
You probably wouldn't want something other than the Kiali operator writing to the Kiali CR's resources though.

**Comment by jmazzitelli** [comment]
> I don't know what the side effects of stopping the cache in that handler are and the comment on it specifically says that it's "not for pausing consumers" which I think is what we're doing here. Might still be ok but I don't know enough to say one way or other.

Take a look at my PR for this issue. I did more investigation and added another commit to do this. When that code stops our cache, we are closing the channel - the same channel [we gave the informers](https://github.com/kubernetes/client-go/blob/v0.31.0/informers/factory.go#L251) and that [the informers use](https://github.com/kubernetes/client-go/blob/v0.31.0/informers/factory.go#L160). Following the informer code, this is the right thing to do. That ends up stopping the informers. And we know it is stopping them because it immediately halts all those error messages we see that the watchers log when getting errors.

The only question now is the first point:  `1. when namespaces get deleted and/or recreated they won't get picked back up by Kiali which will confuse people` ... I'm thinking about the solution to this. I believe the operator will already handle this - if it is already watching namespaces, then it will see the recreated namespace. I talk about this at the bottom of my PR comment here: https://github.com/kiali/kiali/pull/7629#issuecomment-2302888479

**Comment by jmazzitelli** [comment]
I just ran a test. I added this annotation on the Kiali CR:
```
    ansible.sdk.operatorframework.io/reconcile-period: 10s
```

I deleted the namespace and re-created the namespace. In each case, the operator restarted the server pod and provided it the correct namespaces. So that can solve the problem.

If we instead turn on watching for (new) namespaces in the operator and the user doesn't opt to put that annotation on the Kiali CR, things will still work (this is an option for users today, BTW) - and IMO work nicer from the Kiali POV. Because the server pod can survive namespace deletions (that PR handles that). No need to restart the server pod. But when the namespace is re-created, the operator should detect it and restart the pod. I'm going to test that next.

**Comment by jmazzitelli** [comment]
> But when the namespace is re-created, the operator should detect it and restart the pod. I'm going to test that next.

OK, a funny thing happened on the way to the market :)

So, because in the "delete then re-create" namespace in the operator-namespace-watching scenario, the kiali configmap doesn't change (the discovery selectors remain the same), the server pod isn't restarted by the operator. So that's bad. Because we need the server to restart the kube cache that it shutdown when the namespace was deleted, and the only way for that to happen (today) is to restart the pod and get it to run its initialization of caches.

If you then go to the Kiali UI, accessing the namespace cache (which the server still tries to access) causes the server to core dump because the kube cache is shutdown. But then, kubernetes immediately restarts the server pod due to the crash, and things immediately start working again because the server pod re-initializes the kube caches upon startup. So all is well at that point. The only issue here is the user will see an error message in the UI for that first request, the server pod crashes, and only then restarts and works. That is "less than ideal" behavior :)

So let me figure something out for this scenario. We can do one of two things - the operator can somehow be smart enough to know to restart the server when this happens (I'm not sure how to do this -- perhaps if the operator sees that it created a new Role then it should know it needs to restart the pod, that is probably relatively easy to do) OR the second thing is have the server itself be smart enough to initialize the kube cache the first time it tries to access a once-missing or once-unknown namespace. This would actually be kinda nice - because I think it means we could just have the server smart enough to lazy-load the caches only when it needs them (rather than immediately upon start up, have it sync every namespace cache).

I will think more about both of these solutions.

**Comment by jshaughn** [comment]
It irks me that we get a reconciliation on namespace create and not on namespace delete.  I feel like ansible could solve this problem easily by just doing that for us, with no need for a finalizer.

Assuming we don't get that, or not in any timely way, this remains a problem, and we're going through a lot of trouble to solve it.  The main issue is what, log spamming?  Or are we worried about perf here?  If it's just log spamming I think maybe we could just stop logging (maybe one message saying we're shutting it off because we think the namespace is gone), but just keep processing like the namespace exists.  If it comes back, great.  At that point we'd reconcile anyway, and logging would be restored.

**Comment by jmazzitelli** [comment]
> The main issue is what, log spamming? Or are we worried about perf here? If it's just log spamming I think maybe we could just stop logging (maybe one message saying we're shutting it off because we think the namespace is gone), but just keep processing like the namespace exists. If it comes back, great.

It isn't just log spamming. And it isn't our logging, its the k8s client informer spitting out the logs. But the logs are telling us the informers are still watching a now-deleted namespace, which we do not want. We need to shut them down, which I do in the PR (and it is very little code, not a problem).

Yes, the server will see the namespace come back - the problem is we need to restart the informers if/when that happens, which (today) only happens on restart. Otherwise, the server crashes (today).. see my comments above. If we solve that problem, I think things will work.

**Comment by nrfox** [comment]
> This would actually be kinda nice - because I think it means we could just have the server smart enough to lazy-load the caches only when it needs them (rather than immediately upon start up, have it sync every namespace cache).

The server used to do some version of this but it made the first request that used that namespace rather slow since you have to wait until the cache syncs for the response to return. Especially if the request involved multiple namespaces that had to start.

**Comment by jmazzitelli** [comment]
I got it working. See my comments and test procedures in the PR: https://github.com/kiali/kiali/pull/7629#issuecomment-2305772910

There is an unoptimized behavior here - due to the way we run concurrent go funcs to get all the different resources in a namespace, sometimes you might see the informers created and destroyed multiple times (up to as many concurrent go funcs that occur in that one call to things like fetchWorkloadsFromCluster). I tried using a sync lock in the place that would prevent this, but it was hitting deadlocks for a reason I could not figure out. So I had to add deadlock avoidance code in a spot that works, but causes that issue where it might restart the informers multiple times quickly in succession before going into steady state. Note this only happens if you delete a namespace and then restart it with cluster_wide_access=false. In this case, the kiali server pod doesn't restart, and can self-heal, it just might create then destroy informers a few times in a row before settling down (it doesn't happen all the time; at least that's what I've seen).

Anyway, I have the basics working here. I want to do more manual testing and debugging to see if I can find any holes in this solution. So far, though, so good. I'll also see if I can optimize that informer restart issue.

**Comment by jmazzitelli** [comment]
>There is an unoptimized behavior here - due to the way we run concurrent go funcs to get all the different resources in a namespace, sometimes you might see the informers created and destroyed multiple times

> I'll also see if I can optimize that informer restart issue.

The latest comment corrects this. This should not happen, or at least is highly mitigated.

**Comment by jmazzitelli** [comment]
The implementation of this is getting moved over to be incorporated into the larger discovery selectors PR https://github.com/kiali/kiali/pull/7592
