### ISSUE TITLE
User management for kiali console - Openshift memberships sync

### ISSUE THREAD

**Issue by bsuro10** [kiali/kiali#766]
Hey guys,
just wondering if there are any thoughts related to user management for the Kiali console?

When using Openshift with Istio I want every project's admin to gain the capability to watch their own namespace on Kiali dashboard and prevent them from logging as admin, especially when Kiali will become manageable (And not just dashboard to view).
I had thoughts to sync the users/memberships with Openshift itself which can be awesome.

**Comment by jmazzitelli** [comment]
> just wondering if there are any thoughts related to user management for the Kiali console?

yes, there are thoughts :)

- https://issues.jboss.org/browse/KIALI-566
- https://issues.jboss.org/browse/KIALI-1663
- https://issues.jboss.org/browse/KIALI-1185
