### ISSUE TITLE
[molecule] flaky test - affinity-tolerations-resources-test

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#7716]
It seems ever since the [HPA fix](https://github.com/kiali/kiali-operator/pull/800), there has been flakiness in the molecule test `affinity-tolerations-resources-test`. If I run it individually, it always passes.  Sometimes if I run it with the previous test (`accessible-namepaces-test`) it passes. But most of the time during the nightly run of the full molecule test suite, it fails. I'm not sure why. Nothing seems wrong with the actual code; there is likely some issue inside the test code itself.

**Comment by jmazzitelli** [comment]
I started CRC on my local box, installed Istio, built and pushed the dev images:

```sh
hack/crc-openshift.sh start -p ~/bin/downloads/openshift-pull-secret.txt \
  && oc login -u kiali -p kiali --server https://api.crc.testing:6443 \
  && podman login --tls-verify=false -u kiali -p $(oc whoami -t) default-route-openshift-image-registry.apps-crc.testing
  && hack/istio/install-istio-via-istioctl.sh -c oc
  && make build build-ui cluster-push
```

Then ran the first two molecule tests (these are always the first two that are run, with the second one having the flake):

```sh
hack/run-molecule-tests.sh --client-exe "$(which oc)" -dorp podman --cluster-type openshift -udi true -at "accessible-namespaces-test affinity-tolerations-resources-test"
```

and of course, all passed :)

```
=====================
=== TEST RESULTS: ===
=====================

              accessible-namespaces-test... success [6m 49s]
     affinity-tolerations-resources-test... success [3m 36s]
```

Not sure how to replicate the test failure; it is definitely not repeatable.

**Comment by jmazzitelli** [comment]
I'm seeing flaky failures but only on my basemen machine that is old and slow. It's probably due to simply resource limitations on the test box. It could be useful to test with this change in the molecule code, just to see what the pods are when checking them, but I'm not sure if it is worth investigating further.

```diff
diff --git a/molecule/asserts/pod_asserts.yml b/molecule/asserts/pod_asserts.yml
index 974b315..9eef66d 100644
--- a/molecule/asserts/pod_asserts.yml
+++ b/molecule/asserts/pod_asserts.yml
@@ -1,6 +1,10 @@
 # This will assume the pod is already running and there is only one.
 # If you expect more than one pod, set "kiali_expected_replicas"
 # Use common/wait_for_kiali_running.yml if you want to wait for this condition to occur.
+- name: Print the Kiali pods that are known
+  debug:
+    msg: "{{ kiali_pod }}"
+
 - name: Assert Kiali Pod(s) are Running
   assert:
     that:
```

**Comment by jshaughn** [comment]
Closing, can re-open as needed.
