### ISSUE TITLE
Bookinfo example shows HTTPRoute missing service that isn't actually missing

### ISSUE THREAD

**Issue by TaylorMutch** [kiali/kiali#7749]
### Describe the bug

When viewing the Kiali dashboard after installing and running the Bookinfo example, after verifying that the Bookinfo renders correctly, the dashboard shows that the `productpage` Service is missing, when it in fact is not.

<img width="1023" alt="Screenshot 2024-09-16 at 3 25 36 PM" src="https://github.com/user-attachments/assets/5fa1a98a-993d-476f-b48f-7cf78fa64ddd">

Also verified that `productpage` service is visible.

### What are the steps to reproduce this bug?

1. Run through the getting started example for Istio, install the Kiali addons
2. [Open the route for bookinfo](http://localhost:20001/kiali/console/namespaces/default/istio/k8shttproutes/bookinfo?list=yaml)
3. See that it renders a configuration analysis error

### Environment
*Learn about how to determine versions [here](https://kiali.io/docs/faq/general/#how-do-i-determine-what-version-i-am-running).*

- **Kiali version:** 1.87.0
- **Istio version:** 1.23.1
- **Kubernetes impl:** v1.30.4
- **Kubernetes version:** v1.30.4
- **Other notable environmental factors:** Running on EKS v1.30.4-eks-a737599

**Comment by TaylorMutch** [comment]
Might be a dupe of https://github.com/kiali/kiali/issues/6948, validating

**Comment by TaylorMutch** [comment]
Unforunately, still appears for me on v1.89.3 of Kiali

**Comment by hhovsepy** [comment]
Hi @TaylorMutch , can you confirm please that the `HTTPRoute` and the `productpage` Service are in the same namespace?

**Comment by hhovsepy** [comment]
I will need more detailed steps to reproduce please, as I went through the Istio getting started guide and did not see that error:
![Screenshot from 2024-09-17 18-38-35](https://github.com/user-attachments/assets/6d4d20c4-c394-4cd3-a8e7-d6abdda63225)

**Comment by jshaughn** [comment]
@TaylorMutch Any other reproduction steps you can provide, we can't move forward with this one.

**Comment by jshaughn** [comment]
Closing as we don't have enough to move forward.  Can be re-opened with more information.
