### ISSUE TITLE
support namespaces that just have numbers in their name

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#7773]
### Describe the bug

Create a namespace whose name has only numerals (no non-numeric characters). In the Kiali CR, set cluster-wide-access to false so the operator creates roles for the server to access namespaces. Create a discovery selector so the numeric namespace is selected. See the operator fail to create the role, with this error resulting:

```
"Failed to create object: b'{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":
{},\"status\":\"Failure\",\"message\":\"Role in version \\\\\"v1\\\\\" cannot be handled as a Role:
json: cannot unmarshal number into Go struct field ObjectMeta.metadata.namespace of type 
string\",\"reason\":\"BadRequest\",\"code\":400}\\n'"
```

### Expected Behavior

No errors - support the edge case where a namespace has only numerals in its name.

#### Operator

1. Create a namespace with just numerals in its name: `kubectl create ns 12345`
2. In the Kiali CR, select that namespace in the discovery selectors with CWA=false:
```yaml
spec:
  deployment:
    cluster_wide_access: false
    discovery_selectors:
      default:
      - matchLabels:
          kubernetes.io/metadata.name: "12345"
```
3. Wait for error to be reported by the operator in the Kiali CR status field. Kiali pod will be created but fail to start successfully.

#### Helm Chart

1. `kubectl create ns 12345`
2. `helm install --namespace 12345 kiali-server kiali/kiali-server`

Results in:
```
helm install --namespace 12345 kiali-server kiali/kiali-server
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: unable to decode "": json: cannot unmarshal number into Go struct field ObjectMeta.metadata.namespace of type string
```

**Comment by jmazzitelli** [comment]
We will want to backport this to 1.73 and 1.89.

**Comment by jshaughn** [comment]
I think you only need to backport to Operator 1.89 to support the latest patch release, and the OSSM operator.

**Comment by jmazzitelli** [comment]
PRs:

- operator (master): https://github.com/kiali/kiali-operator/pull/822
- helm-charts (master): https://github.com/kiali/helm-charts/pull/284
- operator (backport to v1.89): https://github.com/kiali/kiali-operator/pull/824

**Comment by jmazzitelli** [comment]
dev work is done. test procedures are in the PRs.
