### ISSUE TITLE
[pft graph] remove node kebab menus in favor of secondary-click contextual menu

### ISSUE THREAD

**Issue by jshaughn** [kiali/kiali#7803]
There is no need for the kebab now that we have secondary-click feature to pop up the context menu.  This simplifies and shortens the node labels, and will be a straight carryover from the cytoscape behavior.

**Comment by jshaughn** [comment]
@ferhoyos I thought this would be fairly easy, but I'm not seeing an easy way to hide the kebab without disabling the context menu completely.  The kebab and the right-click are both built into the withContextMenu feature.   Maybe there is some way to override things that I don't see.  There is a  `labelClassName?` prop on DefaultNode that gets passed down to `NodeLabel`, but I don't know i that could possibly be used to hide the embedded kebab.

**Comment by ferhoyos** [comment]
@jshaughn, looking at the `patternfly-topology` code, I think it is not possible to remove the node kebab since it is inherently tied to the `onContextMenu` action:

```
{textSize && onContextMenu && (
        <>
          <line
            className={css(styles.topologyNodeSeparator)}
            x1={contextStartX}
            y1={0}
            x2={contextStartX}
            y2={height}
            shapeRendering="crispEdges"
          />
          <LabelContextMenu
            ref={contextRef}
            x={contextStartX}
            y={0}
            height={height}
            paddingX={paddingX}
            paddingY={paddingY}
            onContextMenu={onContextMenu}
            contextMenuOpen={contextMenuOpen}
          />
        </>
      )}
```

However, we can use some CSS tricks to hide the kebab menu :slightly_smiling_face:

![image](https://github.com/user-attachments/assets/12c35c7f-8e02-46fd-8c08-0287603c1697)
