### ISSUE TITLE
kiali doesn't show connection from ambient to sidecar injected namespace as mTLS

### ISSUE THREAD

**Issue by yyardeng** [kiali/kiali#7811]
### Describe the bug

the scenario is as follows:

- two fresh namespaces - no peer authentication object defined, no network policy defined
- namespace A labeled with istio.io/dataplane-mode=ambient
- namespace B labeled with istio-injection=enabled
- sleep pod with curl installed in namespace A
- ratings pod installed in namespace B
- curl issued from sleep pod in namespace A to ratings pod in namespace B
- response returned, ztunnel logs show the connection as mTLS
- traffic graph in kiali does not show the connection as mTLS
- the same scenario has been tested in different settings: ambient -> sidecar, sidecar -> ambient, ambient -> ambient, sidecar -> sidecar. the only setting where kiali doesn't show the connection as mTLS is in an ambient -> sidecar situation.

curl command:
![image](https://github.com/user-attachments/assets/9667ca35-7562-4303-83ec-961e400b3cf4)

ztunnel logs:
![image](https://github.com/user-attachments/assets/8beb0a55-7f69-4b3a-b61e-b769491ab7f8)

traffic graph in kiali:
![image](https://github.com/user-attachments/assets/fe223a07-779b-4900-969d-826845bec981)

![image](https://github.com/user-attachments/assets/f9afc6dd-9edb-4178-bf6f-73b1ba726b05)

### Expected Behavior

assuming the ztunnel logs confirm the connection is mTLS, the traffic graph in kiali should show the same.

### What are the steps to reproduce this bug?

follow along with the scenario above to reproduce.

### Environment
*Learn about how to determine versions [here](https://kiali.io/docs/faq/general/#how-do-i-determine-what-version-i-am-running).*

- **Kiali version:** 1.89.7
- **Istio version:** 1.23.1
- **Kubernetes impl:** gardener
- **Kubernetes version:** 1.30.5
- **Other notable environmental factors:**

**Comment by jshaughn** [comment]
@yyardeng Next week we will release Kiali 2.0 and the ambient graph support will be enhanced.  We may still have a problem here, but I'd ask that you try it on the new version and report back.  If you don't want to wait, you could try it against the latest nightly build (`latest` tag), found at https://quay.io/repository/kiali/kiali?tab=tags

**Comment by josunect** [comment]
@yyardeng we have been able to reproduce this issue and we are going to have a look.
