### ISSUE TITLE
Unable to navigate between workloads using the minigraph

### ISSUE THREAD

**Issue by ferhoyos** [kiali/kiali#7839]
### Describe the bug

From any workload details page, the user cannot navigate to another workload. Although the user is briefly routed to the new workload, it immediately returns to the previous one.

### Expected Behavior

The user should be able to navigate from one workload to another through the minigraph.

### What are the steps to reproduce this bug?

1. Go to any workload details page (e.g., productpage)
2. In the minigraph, selects another workload node (e.g., reviews-v3) 
3. Verify that the application does not navigate to the selected workload node.

![image](https://github.com/user-attachments/assets/f0b80e8e-c71d-4170-b33a-490170e0b9c0)

### Environment

- **Kiali version:** master
- **Istio version:** 1.23.2
- **Kubernetes impl:** kind
- **Kubernetes version:** 1.29

**Comment by jshaughn** [comment]
This is a tricky issue. It has to do with the fact that when we navigate from one workload to another, the WorkloadDetailsPage component does not get recreated/remounted etc.  Note that we have the same problem navigating from a service to a service.  That in itself should probably not be a problem, but it seems to surface an issue in the way we are dealing with the graph datasource in the detail pages.  I am continuing to look at it, I think we will need to change how things are done and ensure we have more discrete GraphData objects.  I think what is happening is that we re-use the same GraphDataSource, and it updates at unexpected times, causing a mismatch of property data.
