### ISSUE TITLE
[ambient] When the graph nodes are inaccesible, the graph has duplicated edges (From L4 and L7)

### ISSUE THREAD

**Issue by josunect** [kiali/kiali#7843]
### Describe the bug

When the graph nodes are inaccesible, the graph has duplicated edges (From L4 and L7):
![image](https://github.com/user-attachments/assets/e19ac9b1-aef9-4ea6-8308-c42a60a94a48)

When disabling service nodes: 

![image](https://github.com/user-attachments/assets/a4ea90f0-55ca-4346-9e0a-c579eecf75da)

### Expected Behavior
The expected graph would be similar to when disabling the services nodes (Or the same but with the locked nodes if the graph is accessible) 

### What are the steps to reproduce this bug?

1. Install bookinfo in an Ambient mesh with a waypoint proxy: `istio/install-bookinfo-demo.sh -c kubectl -ai false -tg -w true`
2. Set an incorrect name for the cluster: 
```kubernetes_config:
  cluster_name: newcluster ```
4. View the graph

### Environment
*Learn about how to determine versions [here](https://kiali.io/docs/faq/general/#how-do-i-determine-what-version-i-am-running).*

- **Kiali version:** Latest master kiali
- **Istio version:** 1.23.2
- **Kubernetes impl:** 
- **Kubernetes version:** 
- **Other notable environmental factors:**

**Comment by jshaughn** [comment]
This is pretty interesting, there is probably an issue with the waypoint service-injection prevention.  But more than that, we need to figure out if a user should even be able to see most of this graph, inaccessible nodes are typically supposed to be leaf nodes.

**Comment by josunect** [comment]
> This is pretty interesting, there is probably an issue with the waypoint service-injection prevention. But more than that, we need to figure out if a user should even be able to see most of this graph, inaccessible nodes are typically supposed to be leaf nodes.

Maybe this situation happens only when there is an incorrect cluster_name set, but this situation could happen.

**Comment by josunect** [comment]
> @josunect, This happens because we can't identify waypoints when the waypoint node is inaccessible. This is because our waypoint detection depends on matching telemetry with config, but if the config is inaccessible we can't perform the match. This is why we can't prevent the service injection and the show-waypoints option has no effect.
> 
> I'm not sure we can do anything about this problem unless [istio/ztunnel#1128](https://github.com/istio/ztunnel/issues/1128) is addressed on the Istio side, or if we want to go back to using the very weak approach of looking for "waypoint" in the "name".
> 
> I think the best workaround is to ensure Kiali has access to all relevant waypoints.
> 
> Do you think I should close this or set it to Waiting External, and return it to the backlog?

Thank you, @jshaughn 
I think we can close this. I'm not sure if it would make sense to include it in some FAQ?

**Comment by jshaughn** [comment]
Thanks, @josunect.  I'll close.  I'll let this issue service as a source of information.  We can wait on a FAQ until someone actually asks the question :-)
