### ISSUE TITLE
[ambient] External service shown as unknown

### ISSUE THREAD

**Issue by linsun** [kiali/kiali#7875]
### Describe the bug
Using latest Istio code base (as of yesterday) and Kiali , I found my external service (httpbin.org) is shown as unknown.

### Expected Behavior

External service shown as the service defined in SE.

### What are the steps to reproduce this bug?

How I installed Istio using istioctl of the dev build below:

```
TAG=1.24-alpha.6a458274241dd51fbd6e015e7f439a29e8beb07f

istioctl install --set tag=$TAG --set hub=gcr.io/istio-testing --set profile=ambient --skip-confirmation  --set meshConfig.accessLogFile=/dev/stdout --set values.pilot.env.PILOT_ENABLE_IP_AUTOALLOCATE=true --set  values.cni.ambient.dnsCapture=true

kubectl get crd gateways.gateway.networking.k8s.io &> /dev/null || \
  { kubectl apply -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.2.0/standard-install.yaml }

ISTIO_DOWNLOAD_DIR=~/src/github.com/istio/istio/
kubectl apply -f $ISTIO_DOWNLOAD_DIR/samples/addons/prometheus.yaml
kubectl apply -f $ISTIO_DOWNLOAD_DIR/samples/addons/kiali.yaml
kubectl apply -f $ISTIO_DOWNLOAD_DIR/samples/addons/grafana.yaml
```

Steps to recreate is using John's blog:

https://www.solo.io/blog/egress-gateways-made-easy/

Generate a bunch of traffic from client to httpbin.org.  Launch the kiali dashboard and see the external traffic going through egress waypoint as unknown.

### Environment
*Learn about how to determine versions [here](https://kiali.io/docs/faq/general/#how-do-i-determine-what-version-i-am-running).*

- **Kiali version:**
- **Istio version:**
- **Kubernetes impl:** 
- **Kubernetes version:** 
- **Other notable environmental factors:**

**Comment by linsun** [comment]
cc @jshaughn

**Comment by jmazzitelli** [comment]
I'm going to guess @jshaughn is going to ask what your telemetry in prometheus looks like :)

Did you look at the telemetry in Prom to make sure it makes sense (i.e. there are no "unknown" destinations in there?)

**Comment by jshaughn** [comment]
@jmazzitelli , I talked to @linsun a bit in Slack before this, I think we need to try and do the repro steps ourselves and take a look.  Lin, if you have a screenshot of the unexpected "unknown" node, that would be great.

**Comment by josunect** [comment]
kubectl exec "$(kubectl get pod -l app=ratings -n bookinfo -o jsonpath='{.items[0].metadata.name}')" -c ratings -n bookinfo -- curl httpbin.org/get

![image](https://github.com/user-attachments/assets/afb61c13-cbba-4163-a9ca-ef0d7fc8817f)
![image](https://github.com/user-attachments/assets/73f1211c-54e8-46e4-b994-12ebff342055)
![image](https://github.com/user-attachments/assets/2c975c9c-05fb-4e44-8e91-9503f2f0ab6b)

When I've applied the steps from the blog: 
![image](https://github.com/user-attachments/assets/e83559af-89d9-49bb-9fc6-48573cb66938)

Note: Following the steps I missed to include istio-egress in Ambient, I did it after applying the waypoint, so I didn't get the traffic redirected to Envoy. 

```
< Connection: keep-alive
< Server: gunicorn/19.9.0
```

After label the namespace with ambient label first:

```
< content-length: 379
< server: istio-envoy
```

@jshaughn it is expected to have an unknown external service if the traffic is going throw the service entry and not the waypoint?

**Comment by jshaughn** [comment]
Hi @linsun , looking at the investigation by @josunect , it seems the issue may be that in John's blog he doesn't explicitly enroll the `istio-egress` into the ambient mesh.  I'm not sure it that is an oversight. After creating the namespace and before adding the waypoint, can you:

  `kubectl label namespace istio-egress istio.io/dataplane-mode=ambient`

and see if that affects the results?

**Comment by linsun** [comment]
Hi @josunect thanks for trying to reproduce.  I'm using kiali from Istio's master:  image: "quay.io/kiali/kiali:v2.0".

Yes, I did enable istio-egress namespace to ambient @jshaughn.  That is required to get stuff working.

I was able to reproduce this in my env today:

<img width="1653" alt="image" src="https://github.com/user-attachments/assets/bac61122-07f4-4de2-90c1-b34e192a3eea">


and my prometheus metrics:

```
istio_tcp_sent_bytes_total{connection_security_policy="mutual_tls", destination_app="unknown", destination_canonical_revision="unknown", destination_canonical_service="unknown", destination_cluster="Kubernetes", destination_principal="unknown", destination_service="httpbin.org", destination_service_name="httpbin.org", destination_service_namespace="istio-egress", destination_version="unknown", destination_workload="unknown", destination_workload_namespace="unknown", gateway_istio_io_managed="istio.io-mesh-controller", gateway_networking_k8s_io_gateway_name="waypoint", instance="10.244.1.29:15020", istio_io_dataplane_mode="none", job="kubernetes-pods", namespace="istio-egress", node="llm-worker", pod="waypoint-679f5f79b9-4shmg", pod_template_hash="679f5f79b9", reporter="waypoint", request_protocol="tcp", response_flags="-", service_istio_io_canonical_name="waypoint", service_istio_io_canonical_revision="latest", sidecar_istio_io_inject="false", source_app="client", source_canonical_revision="latest", source_canonical_service="client", source_cluster="Kubernetes", source_principal="spiffe://cluster.local/ns/default/sa/client", source_version="latest", source_workload="client", source_workload_namespace="default"}
```

**Comment by linsun** [comment]
Another update, if I send http to httpbin.org, it does show up in the graph.  Seems only an issue if I sent https from my client or if I use TLS origination from the egress waypoint.

<img width="1643" alt="image" src="https://github.com/user-attachments/assets/26bf8dd5-f887-4f7e-9406-5d641302c373">

**Comment by josunect** [comment]
Thanks for the steps to reproduce it @linsun 

I see this connection with https is not in the graph because the `reporter="waypoint"`.

**Comment by linsun** [comment]
Nice, thanks for sending a fix @josunect !!
