### ISSUE TITLE
Make gateways optional in istio status

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#7882]
### What do you want to improve?

Kiali has an Istio health check in the masthead. As part of that health check, by default, Kiali checks if there's an ingress and egress gateway installed in the `istio-system` namespace. If you haven't installed a gateway or if you installed your gateways in a different namespace, Kiali will show an error in the masthead until you [manually configure](https://kiali.io/docs/configuration/kialis.kiali.io/#.spec.external_services.istio.component_status) Kiali to ignore these errors or look for the gateways in a different namespace.

### What is the new behavior?

By default, Kiali shouldn't show an error in the masthead if the gateways are not installed or are not installed in the `istio-system` namespace. Instead, Kiali should look for gateways across all accessible namespaces and only show an error if the gateway is unhealthy. If no gateways are found, this should not be an error.

**Comment by jshaughn** [comment]
Adding to the sprint backlog, this has been questioned multiple times by users.

**Comment by xSAVIKx** [comment]
Just wanted to add that it is also common to have more than one ingress in a separate namespace multiple ingresses in different namespaces
