### ISSUE TITLE
In ambient mode, graph not contain gateway traffic

### ISSUE THREAD

**Issue by erikwoo** [kiali/kiali#7937]
### What do you want to discuss?
ingressgateway contain prom metrics istio_request_totoal with reporter=source
When istio is ambient, kiali would query with filter reporter=~destination|waypoint. 

### What does it improve / What problem does it solve?
Should we remove the reporter promql filter so that kiali graph can still display gateway traffic?

**Comment by jshaughn** [comment]
@erikwoo , the graph querying approach is fairly complex and any changes need to be heavily considered. To start, please just supply some replication steps, so we can confirm exactly what you are seeing. Thanks!

**Comment by josunect** [comment]
@erikwoo I was trying to reproduce this in Ambient mesh and Kiali is showing the ingress traffic: 

![image](https://github.com/user-attachments/assets/87bb03de-51d6-483d-9729-fcf291d90cee)
![image](https://github.com/user-attachments/assets/e4ee79b1-ec4b-4100-a76a-7b386bdc5534)

![image](https://github.com/user-attachments/assets/2228e30a-4d8d-4af7-91cc-a5b14ba2041b)

Another example with Ambient and Gateway traffic: 
![image](https://github.com/user-attachments/assets/77426092-0e43-488e-9710-56e7f0006e4c)


It would be really helpful if you can send us some replication steps for this issue, thank you!

**Comment by erikwoo** [comment]
@josunect thank you for your replying.
![image](https://github.com/user-attachments/assets/33ed2df8-8b03-4d3b-90b2-6ac6879dd836)

try filtering with only http traffic

**Comment by josunect** [comment]
> @josunect thank you for your replying. ![image](https://private-user-images.githubusercontent.com/5202318/393112916-33ed2df8-8b03-4d3b-90b2-6ac6879dd836.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3NjI4MzAsIm5iZiI6MTczMzc2MjUzMCwicGF0aCI6Ii81MjAyMzE4LzM5MzExMjkxNi0zM2VkMmRmOC04YjAzLTRkM2ItOTBiMi02YWM2ODc5ZGQ4MzYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDlUMTY0MjEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjRhZTFiODhjZDFjZTJiNWI5MjEzZjJiNWNmOWE2NjVhNTYzZTlkOTBjNjUwMzNjNjdiNDk2YjVjMzRkYTk1NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.LkYwhqFqYbVSPSDMR0VLIRXntggnSi-RghPVfDaUYMs)
> 
> try filtering with only http traffic

Thank you, @erikwoo , I think I was able to reproduce this. 

Following this [Istio guide](https://istio.io/latest/docs/tasks/traffic-management/ingress/ingress-control/), I've created two different Ambient namespaces, one with ingress traffic (Ambient-demo), another with traffic from a Kubernetes Gateway (ambient), and that's the difference: 

![image](https://github.com/user-attachments/assets/6a57c7d2-7767-43a2-b3b3-2cf4d43428fa)

We've noticed that, it is possible to see this http traffic when you have selected the namespace where the traffic is coming from. 

We are going to have a look into this. But, as a workaround, you can select the namespace where the gateway is deployed and you should be able to see the http traffic: 

![image](https://github.com/user-attachments/assets/7bea3f85-78f8-4eeb-9f8a-dbbfbe6fa12d)

![image](https://github.com/user-attachments/assets/ca0cc9d8-71ea-4c8b-a7e4-152488035a27)
