### ISSUE TITLE
Add podSecurityContext for deployment

### ISSUE THREAD

**Issue by jshaughn** [kiali/kiali#7987]
The operator and/or helm charts may need additional support for podSecurityContext.

This issue is provided as the place to discuss the PR generated by https://github.com/brainstorm82.  https://github.com/brainstorm82, thanks for the potential contribution, in the future please make sure to create an issue for any PR submission.  It gives us a place for stating the motivation/use case, and any ensuing discussion. It is also required for our tracking, release notes, etc.

One question, after reading the PR comments, what does this do past what we have already.  See @jmazzitelli : [already a security context you can set on the container](https://github.com/kiali/helm-charts/blob/master/kiali-operator/values.yaml#L24) which [contain some default constraints when not set](https://github.com/kiali/helm-charts/blob/master/kiali-operator/templates/deployment.yaml#L53-L64).

**Comment by jmazzitelli** [comment]
I'm closing as a dup - mine is more verbose :) 

See https://github.com/kiali/kiali/issues/7988
