### ISSUE TITLE
KIA1104 should only shows when there is one route destination but has explicit weight assigned and less than 100 on tcp/tls route

### ISSUE THREAD

**Issue by zirain** [kiali/kiali#8000]
### Describe the bug

<img width="1360" alt="image" src="https://github.com/user-attachments/assets/668687ed-c037-43aa-92d0-f5d0b8c4d595" />

### Expected Behavior

should not report this warning

### What are the steps to reproduce this bug?

1. install istio and kiali
2. apply tcp-echo demo
3. apply `samples/tcp-echo/tcp-echo-all-v1.yaml`, then check 

### Environment
*Learn about how to determine versions [here](https://kiali.io/docs/faq/general/#how-do-i-determine-what-version-i-am-running).*

- **Kiali version:** v2.2
- **Istio version:** master
- **Kubernetes impl:**  
- **Kubernetes version:** 
- **Other notable environmental factors:**

**Comment by hhovsepy** [comment]
Thank you for logging and the fix @zirain
