### ISSUE TITLE
Irregular metrics loading error 

### ISSUE THREAD

**Issue by dan-m8t** [kiali/kiali#8025]
### Describe the bug

I updated Kiali from 1.89 to 2.3.0 in my test environment. As some changes happened to namespace access I migrated to discoverySelectors as the documentation said. I use Istio 1.23.3 in ambient mode.

When I put some traffic onto my workloads I can sometimes see metrics and sometimes not, I am not sure what causes this behaviour.
It just says: 
```
 Error loading metrics: Cannot access namespace data: Namespace [my-namespace] in cluster [Kubernetes] is not accessible to Kiali
```
![grafik](https://github.com/user-attachments/assets/4d3ebd71-9504-409c-ba2f-05553ff07dd3)

When I click on "refresh" inside the graph view metrics are displayed again. I cannot see any log entries here, I enabled debug logging for kiali but it states no errors.

All I get is this, regardless of Kiali UI throws an error or not:

```
{"level":"debug","time":"2024-12-27T13:04:14Z","message":"Scraping istiod for debug info"}
{"level":"debug","time":"2024-12-27T13:04:19Z","message":"[ValidationsReconciler] Started reconciling "}
{"level":"debug","time":"2024-12-27T13:04:19Z","message":"[ValidationsReconciler] Finished reconciling in 3ms"}
{"level":"debug","time":"2024-12-27T13:04:19Z","message":"Reading session cookie: kiali-token-Kubernetes"}
{"level":"debug","time":"2024-12-27T13:04:19Z","message":"Reading session cookie: kiali-token-Kubernetes"}
{"level":"debug","time":"2024-12-27T13:04:19Z","message":"Reading session cookie: kiali-token-Kubernetes"}
{"level":"debug","time":"2024-12-27T13:04:19Z","message":"Reading session cookie: kiali-token-Kubernetes"}
{"level":"debug","time":"2024-12-27T13:04:19Z","message":"Reading session cookie: kiali-token-Kubernetes"}
{"level":"debug","time":"2024-12-27T13:04:19Z","message":"Grafana is disabled in Kiali by configuration"}
{"level":"debug","time":"2024-12-27T13:04:19Z","message":"Tracing is disabled in Kiali by configuration"}
{"level":"debug","time":"2024-12-27T13:04:20Z","message":"Reading session cookie: kiali-token-Kubernetes"}
{"level":"debug","time":"2024-12-27T13:04:20Z","message":"Reading session cookie: kiali-token-Kubernetes"}
{"level":"debug","time":"2024-12-27T13:04:20Z","message":"Reading session cookie: kiali-token-Kubernetes"}
{"level":"debug","time":"2024-12-27T13:04:20Z","message":"Reading session cookie: kiali-token-Kubernetes"}
{"level":"debug","time":"2024-12-27T13:04:20Z","message":"Reading session cookie: kiali-token-Kubernetes"}
{"level":"debug","time":"2024-12-27T13:04:20Z","message":"Reading session cookie: kiali-token-Kubernetes"}
{"level":"debug","time":"2024-12-27T13:04:20Z","message":"Reading session cookie: kiali-token-Kubernetes"}
```

Rarely I get this message:
```
{"level":"error","time":"2024-12-27T13:04:55Z","message":"Namespace [my-namespace] in cluster [Kubernetes] is not accessible to Kiali"}
```

But this does not happen everytime when the UI throws the error?!

Here is my discoverySelectors config:
```
    cluster_wide_access: true
    discovery_selectors:
      default:
      - matchExpressions:
        - key: istio-enabled
          operator: Exists
```
I played around with `cluster_wide_access` `true` or `false` but this does not make a difference in the UI or logs, I also removed the discovery_selectors entry with the same issue afterwards.

I can see that the discovery_selectors works fine in the overview:

![grafik](https://github.com/user-attachments/assets/b1c9f975-c4c2-4a35-8f14-54234353f5b9)

So I'd assume that this works as intended.

I also tried all kiali versions from 2.0.X on to see if this maybe a bug in 2.3.0 but this behaviour is in all release of 2.x - in 1.89 this worked as expected.

### What are the steps to reproduce this bug?

Not sure how to reproduce to be honest. As I said, get Traffic graph, click on a service/app, get error mentioned, click on refresh in the traffic graph, metrics are now shown for a short amount of time, then suddenly face the error again.

### Environment
*Learn about how to determine versions [here](https://kiali.io/docs/faq/general/#how-do-i-determine-what-version-i-am-running).*

- **Kiali version:*2.3.0*
- **Istio version:*1.23.3*
- **Kubernetes impl:*OKD 4.14* 
- **Kubernetes version:*v1.27.9+5c56cc3* 
- **Other notable environmental factors:*tried FF and Chrome, same result*

**Comment by dan-m8t** [comment]
Additional information:

I also got the problem in Mesh overview, when I click below Data plane on '3 Namespaces' (see picture) 
![grafik](https://github.com/user-attachments/assets/70bc5da7-bfdf-443f-87fb-261dfae624c6)

I get the overview of the namespaces that are part of the Data Plane, when I want to expand one of the entries I get either the full data of the namespace or again the error that kiali cannot access the namespace.

![grafik](https://github.com/user-attachments/assets/62047513-3a8d-4389-890d-c53188c37e53)

after refreshing the page:

![grafik](https://github.com/user-attachments/assets/ce2b91b9-a3ff-48ff-9c55-08f5365b500d)

**Comment by josunect** [comment]
@dan-m8t I think what it might be confusing for kiali is to have `cluster_wide_access` to true and also `discovery_selectors`. 

`In order to restrict the Kiali Server so that it only has access to certain namespaces on the local cluster, it must first have its cluster-wide access disabled. ` (See https://kiali.io/docs/configuration/namespace-management/#cluster-wide-access-mode)

If you change `cluster_wide_access` to false, are you also facing the same issue?

**Comment by dan-m8t** [comment]
Thanks for your reply. Yes I tried both, `cluster_wide_access` to `true` without `discovery_selectors`, this then just show all the namespaces, regardless if they are part of the mesh. Same behaviour. And the docs states this:

>  You can still use discovery selectors (explained below) to limit what Kiali will make visible in the UI while cluster_wide_access remains true. You would want to do this for the performance benefits it provides the Kiali Server. But with this, the Kiali Server will be granted ClusterRole permissions rather than individual Role permissions per namespace. In other words, it will have access to all namespaces, but will not make all of them visible. 

So `cluster_wide_access = true` AND `discovery_selectors` still gives kiali access to all the namespaces, but it limits what is visible in kiali itself.

**Comment by josunect** [comment]
> Thanks for your reply. Yes I tried both, `cluster_wide_access` to `true` without `discovery_selectors`, this then just show all the namespaces, regardless if they are part of the mesh. Same behaviour. And the docs states this:
> 
> > You can still use discovery selectors (explained below) to limit what Kiali will make visible in the UI while cluster_wide_access remains true. You would want to do this for the performance benefits it provides the Kiali Server. But with this, the Kiali Server will be granted ClusterRole permissions rather than individual Role permissions per namespace. In other words, it will have access to all namespaces, but will not make all of them visible.
> 
> So `cluster_wide_access = true` AND `discovery_selectors` still gives kiali access to all the namespaces, but it limits what is visible in kiali itself.

You are right, @dan-m8t , thanks for the information provided. I was able to reproduce this issue.

**Comment by dan-m8t** [comment]
This fixed my issue, thanks!

**Comment by josunect** [comment]
> This fixed my issue, thanks!

Thanks for the feedback, @dan-m8t !
