### ISSUE TITLE
Pilot warnings for sidecar and version label

### ISSUE THREAD

**Issue by kramvan1** [kiali/kiali#805]
![image](https://user-images.githubusercontent.com/5861591/51712706-449b7c80-1ff5-11e9-83b9-36b0f779fb67.png)

Trying to understand if this is an issue with Kiali (v0.10) or something wrong with my Istio setup (1.0.5).

Warnings are about Pod has no Istio sidecar and Pod has no version label.

Are these Warnings generated by Kiali?   and are they valid and should be fixed in Istio?

**Comment by abonas** [comment]
@aljesusg

**Comment by aljesusg** [comment]
Hi @kramvan1, thanks for report this issue.

The pods from istio-system environment not need istio sidecar or these labels.

Our advise is handle the istio environment as a special case excluding it is overkill. It could be useful see the istio-system in kiali to check that the environment is OK

Anyway FYI you can exclude the namespaces related with the Istio installation and not with your environment in Kiali.
https://github.com/kiali/kiali/blob/master/README.adoc#environment-variables

We have another issue related with this here https://github.com/kiali/kiali/issues/760

**Comment by kramvan1** [comment]
@aljesusg thx for the reply, closing.
