### ISSUE TITLE
ServiceEntry not refelected in Graph UI

### ISSUE THREAD

**Issue by iftachsc** [kiali/kiali#823]
Kialia 0.14
Istio 1.03-gke.3

**Comment by pilhuhn** [comment]
I moved this over to the Kial repo, as the design repo is meant for UxD questions, while you apparently face some issue with the running Kiali instance.

Can you please post an example of your ServiceEntry config that is failing to show?

**Comment by iftachsc** [comment]
sure. first this is the service traffic from the istio dashbaord:
![image](https://user-images.githubusercontent.com/28829551/52178106-fc3d4500-27d2-11e9-8bc6-f45a39d4b17c.png)
the name is the same as it apears on the serviceentry as follows:
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  creationTimestamp: 2019-01-29T11:38:56Z
  generation: 1
  name: dnb-main
  namespace: auto-staging
  resourceVersion: "8145256"
  selfLink: /apis/networking.istio.io/v1alpha3/namespaces/auto-staging/serviceentries/dnb-main
  uid: 7653ded0-23ba-11e9-9f2c-42010a040009
spec:
  hosts:
  - dnb-main.restricted-company-data.internal
  ports:
  - name: http
    number: 8080
    protocol: HTTP

the graph itself shows the internal regualr injectcted services that the same traffic produce. the external service is accessed by them. so its the same traffic
![image](https://user-images.githubusercontent.com/28829551/52178133-52aa8380-27d3-11e9-874f-a5a91cbb12aa.png)

**Comment by pilhuhn** [comment]
So you have no 'resolution' and 'location' fields in the spec? Can you try adding them and report back what happens? See https://istio.io/docs/reference/config/istio.networking.v1alpha3/#ServiceEntry

**Comment by iftachsc** [comment]
resolution defaults to DNS if i am not mistaken. anyway i added both and it works now :) well its not a must for istio but is for kiali! thank u so muich for the super amazing fast response. ill delete this thread because it contains photos with info on our internals.

**Comment by pilhuhn** [comment]
Can you please - if you delete this - open a new issue and adding that the Service Entry is not shown if those are missing (even if optional) ?

**Comment by iftachsc** [comment]
ill keep this but remoeve images.

**Comment by pilhuhn** [comment]
@jmazzitelli @jshaughn Can you please have a look so that we don't key on optional entries?

**Comment by jmazzitelli** [comment]
I think "Location" is the important one. If it is missing, we do not identify as a service entry - I guess we need another way. See: https://github.com/kiali/kiali/blob/37b3ffe1a07cf1ba6cb6612f649a88d3c0440276/graph/appender/service_entry.go#L76

**Comment by jmazzitelli** [comment]
I think the fix in kiali/graph/appender/service_entry.go is as follows (we should support the case where location is not specified):

```go
for _, entry := range istioCfg.ServiceEntries {
  if entry.Spec.Hosts != nil {
    location = "MESH_EXTERNAL" // TODO: IS THIS THE ISTIO DEFAULT??
    if (entry.Spec.Location == "MESH_EXTERNAL" || entry.Spec.Location == "MESH_INTERNAL") {
      location = entry.Spec.Location.(string)
    }
    for _, host := range entry.Spec.Hosts.([]interface{}) {
      globalInfo.ServiceEntries[host.(string)] = location
    }
  }
}
```

**Comment by jshaughn** [comment]
@jmazzitelli +1, I'll open a Jira for this change.  Looking at this [Istio code snippet](https://github.com/istio/api/blob/master/networking/v1alpha3/service_entry.pb.go#L437-L441) I think MESH_EXTERNAL can be considered the default.

**Comment by jshaughn** [comment]
Fixed, closing.
