### ISSUE TITLE
Kiali not working with microk8

### ISSUE THREAD

**Issue by natraj09** [kiali/kiali#826]
**Describe the bug**
I have installed kubernetes and Istio using [microk8](https://microk8s.io/).  I followed the instructions to install Kiali by running ` bash <(curl -L http://git.io/getLatestKialiKubernetes)` command.  I verified kiali service and deployment by executing following command

> `kubectl get svc -n istio-system | grep kiali`
> kiali                      NodePort       10.152.183.215   <none>        20001:31217/TCP

> `kubectl get deploy -n istio-system | grep kiali`
> kiali 1/1     1            1           57m

**Versions used**
Kiali: Latest version
Istio: 1.0.0
Kubernetes flavour and version: microk8

**To Reproduce**
1. Go to 'http://<host>:31217/kiali` on Chrome / firefox
2. Page doesn't respond. 
```This page isn’t working 10.148.189.207 sent an invalid response.
ERR_INVALID_HTTP_RESPONSE```

**Expected behavior**
A clear and concise description of what you expected to happen.

**Comment by jmazzitelli** [comment]
First, Istio 1.0.0 is old - latest 1.0.x is 1.0.5.

But I doubt that matters much in this case.

Sounds like Kiali isn't exposed via the istio ingress properly? I don't think we've tried on microk8 - not sure if there is anything weird that is required for that platform.

Did you try over https? Kiali is exposed via the ingress gateway over https (secured with Kiali's Citadel cert)

**Comment by natraj09** [comment]
Thanks @jmazzitelli for the quick response. I tried over `https` works magically!
