### ISSUE TITLE
Graph layout incorrect

### ISSUE THREAD

**Issue by DanTulovsky** [kiali/kiali#846]
Hi.

(I am new to istio and kiali, so if I am just holding it wrong, do let me know...)

[this is all on gke]

kiali-ui 0.15.0-snapshot.1 (351cee6da551fd942bbebe1e94fec9135903095e)
kiali v0.15.0-snapshot.1 (5e5ddce1745e9bba3c788d543ecf2bcd53882047)

Prometheus 2.3.1
Kubernetes v1.11.7-gke.4
JaegerURL http://localhost:16686/jaeger
GrafanaURL http://localhost:3000

I have a simple app that works like this:

[internet browser] --(http)--> [frontend] --(grpc)-->[backend]

There is a frontend service, and some pods behind it.
There is a backend service, and some pods behind it.

frontend talks to backend via cluster dns.  Everything works fine from the app's perspective.

This is what I see in kiali:

![capture](https://user-images.githubusercontent.com/509887/52905977-d1aaad80-3210-11e9-9b94-348868bbc982.png)

Whereas the picture should be as above.  In fact, it used to be correct, but at some point changed.  I think it was when I created a ServiceEntry to allow components to talk to the internet. It looked liked this:

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-http
spec:
  hosts:
  - '*.com'
  ports:
  - number: 80
    name: http-port
    protocol: HTTP
  - number: 443
    name: https
    protocol: HTTPS
  resolution: NONE
```

I've since deleted it, but the graph didn't fix itself.  Both frontend and backend containers do talk to the internet (to stackdriver for metrics reporting).  Of course I would then expect the arrow to go the other way.

Here's the debug info from kiali, if that helps.  My understanding is that it's getting this data from prometheus, right?  How would I go about debugging this type of issue?

(I was on kiali .12, but upgraded to the latest one, wondering if it might solve the issue.. which it didn't.)

Thank you
Dan

```
{
  "currentURL": "http://localhost:20001/kiali/console/graph/namespaces/?edges=requestsPercentOfTotal&graphType=workload&namespaces=playground&injectServiceNodes=true&duration=60&pi=15000&layout=dagre",
  "reduxState": {
    "authentication": {
      "token": null,
      "username": null,
      "error": false,
      "message": "",
      "logged": true,
      "logging": false,
      "sessionTimeOut": 1550373225407
    },
    "globalState": {
      "loadingCounter": 0,
      "isPageVisible": true
    },
    "grafanaInfo": {
      "url": "http://localhost:3000",
      "serviceDashboardPath": "/d/LJ_uJAvmk/istio-service-dashboard",
      "workloadDashboardPath": "/d/UbsSZTDik/istio-workload-dashboard",
      "varNamespace": "var-namespace",
      "varService": "var-service",
      "varWorkload": "var-workload"
    },
    "graph": {
      "cyData": {
        "updateTimestamp": 1550356625084,
        "cyRef": null
      },
      "isLoading": false,
      "isError": false,
      "graphDataDuration": 60,
      "graphDataTimestamp": 1550356624,
      "graphData": {
        "nodes": [
          {
            "data": {
              "id": "2be366abf12e0d075abb5cbeac3b0c04",
              "nodeType": "service",
              "namespace": "playground",
              "app": "playground",
              "service": "playground-backend",
              "destServices": {
                "playground-backend": true
              },
              "hasVS": true
            }
          },
          {
            "data": {
              "id": "271e676096576ffc9e54b7bed04e457a",
              "nodeType": "service",
              "namespace": "playground",
              "app": "playground",
              "service": "playground-frontend",
              "destServices": {
                "playground-frontend": true
              },
              "hasVS": true
            }
          },
          {
            "data": {
              "id": "702481e9449ab2445856b07f5a245ce9",
              "nodeType": "workload",
              "namespace": "playground",
              "workload": "frontend",
              "app": "playground",
              "version": "2019021600",
              "destServices": {
                "playground-frontend": true
              }
            }
          },
          {
            "data": {
              "id": "a3f26facdda54a0f70498102104d2120",
              "nodeType": "workload",
              "namespace": "playground",
              "workload": "backend",
              "app": "playground",
              "version": "2019021601",
              "destServices": {
                "playground-backend": true
              }
            }
          },
          {
            "data": {
              "id": "b30b0078325bf2e1adb4d57c4c0c2665",
              "nodeType": "unknown",
              "namespace": "unknown",
              "workload": "unknown",
              "app": "unknown",
              "version": "unknown",
              "isInaccessible": true,
              "isRoot": true
            }
          }
        ],
        "edges": [
          {
            "data": {
              "id": "039d5a6882659f6e515a0c5b85d7958b",
              "source": "271e676096576ffc9e54b7bed04e457a",
              "target": "702481e9449ab2445856b07f5a245ce9",
              "traffic": {
                "protocol": "http",
                "rates": {
                  "http": "35.07",
                  "httpPercentReq": "100.0"
                }
              }
            }
          },
          {
            "data": {
              "id": "220b715d04dee3737245e3aa9af07625",
              "source": "2be366abf12e0d075abb5cbeac3b0c04",
              "target": "a3f26facdda54a0f70498102104d2120",
              "traffic": {
                "protocol": "grpc",
                "rates": {
                  "grpc": "35.22",
                  "grpcPercentReq": "100.0"
                }
              }
            }
          },
          {
            "data": {
              "id": "6c4521a421e9ae97743e871269f7f0ab",
              "source": "b30b0078325bf2e1adb4d57c4c0c2665",
              "target": "271e676096576ffc9e54b7bed04e457a",
              "traffic": {
                "protocol": "http",
                "rates": {
                  "http": "35.07",
                  "httpPercentReq": "100.0"
                }
              }
            }
          },
          {
            "data": {
              "id": "8c7c48b9ee66f8843530ed10e00ed64b",
              "source": "b30b0078325bf2e1adb4d57c4c0c2665",
              "target": "2be366abf12e0d075abb5cbeac3b0c04",
              "traffic": {
                "protocol": "grpc",
                "rates": {
                  "grpc": "35.22",
                  "grpcPercentReq": "100.0"
                }
              }
            }
          }
        ]
      },
      "layout": {
        "name": "dagre",
        "fit": false,
        "nodeDimensionsIncludeLabels": true,
        "rankDir": "LR"
      },
      "summaryData": {
        "summaryType": "graph",
        "summaryTarget": null
      },
      "filterState": {
        "edgeLabelMode": "requestsPercentOfTotal",
        "findValue": "",
        "graphType": "workload",
        "hideValue": "",
        "showCircuitBreakers": true,
        "showFindHelp": false,
        "showLegend": false,
        "showMissingSidecars": true,
        "showNodeLabels": true,
        "showSecurity": false,
        "showServiceNodes": true,
        "showTrafficAnimation": false,
        "showUnusedNodes": false,
        "showVirtualServices": true
      }
    },
    "messageCenter": {
      "nextId": 0,
      "groups": [
        {
          "id": "systemErrors",
          "title": "Open issues",
          "messages": [],
          "showActions": false,
          "hideIfEmpty": true
        },
        {
          "id": "default",
          "title": "Notifications",
          "messages": [],
          "showActions": true,
          "hideIfEmpty": false
        }
      ],
      "hidden": true,
      "expanded": false,
      "expandedGroupId": "default"
    },
    "namespaces": {
      "activeNamespaces": [
        {
          "name": "playground"
        }
      ],
      "isFetching": false,
      "items": [
        {
          "name": "ambassador"
        },
        {
          "name": "cert-manager"
        },
        {
          "name": "default"
        },
        {
          "name": "gogs"
        },
        {
          "name": "istio-system"
        },
        {
          "name": "monica"
        },
        {
          "name": "playground"
        },
        {
          "name": "static-web"
        }
      ],
      "lastUpdated": "2019-02-16T22:34:30.170Z",
      "filter": ""
    },
    "serverConfig": {
      "istioNamespace": "istio-system",
      "istioLabels": {
        "AppLabelName": "app",
        "VersionLabelName": "version"
      },
      "prometheus": {
        "globalScrapeInterval": 15,
        "storageTsdbRetention": 21600
      }
    },
    "statusState": {
      "status": {
        "Istio mTLS": "error",
        "Kiali console version": "0.15.0-snapshot.1",
        "Kiali core commit hash": "5e5ddce1745e9bba3c788d543ecf2bcd53882047",
        "Kiali core version": "v0.15.0-snapshot.1",
        "Kiali state": "running"
      },
      "components": [
        {
          "name": "Prometheus",
          "version": "2.3.1"
        },
        {
          "name": "Kubernetes",
          "version": "v1.11.7-gke.4"
        },
        {
          "name": "Jaeger",
          "url": "http://localhost:16686/jaeger"
        },
        {
          "name": "Grafana",
          "url": "http://localhost:3000"
        }
      ],
      "warningMessages": []
    },
    "userSettings": {
      "interface": {
        "navCollapse": false
      },
      "duration": 60,
      "refreshInterval": 15000
    },
    "_persist": {
      "version": -1,
      "rehydrated": true
    }
  }
}
```

**Comment by DanTulovsky** [comment]
Small clarification, the ServiceEntry has nothing to do with this, as it was never used.  I instead set the `global.proxy.includeIPRanges` setting to my cluster range to allow outgoing traffic.

I just turned it off again to see if it fixes the graph, will report back.

**Comment by DanTulovsky** [comment]
So, yes, once I set:

```
- "[[ annotation .ObjectMeta `traffic.sidecar.istio.io/includeOutboundIPRanges`  "*"  ]]"
```

in the istio-sidecar-injector config again, to disallow all traffic externally, the graph is correct again:

![capture2](https://user-images.githubusercontent.com/509887/52907312-56a3c000-322d-11e9-8cd6-bf14c833cf79.png)

Any ideas here? Is this expected?

**Comment by jmazzitelli** [comment]
The best way to debug something that looks "strange" in the Kiali graph that you do not expect is to look directly at the Prometheus data to confirm what you expect. I will say that 99% of the time, Kiali is correctly displaying the data found in Prometheus and either you are erroneously expecting the graph to look a different way or you have found [a bug in Istio](https://github.com/istio/istio/issues/11151) (I'll hedge my bets and reserve a 1% chance that it is a Kiali bug :-). Take a look at that Istio issue as an example of how to debug something like this - you will see in that issue that we saw the Kiali graph was "correct" but by doing a Prometheus query, we identified an Istio bug that was storing bad data in Prometheus.

**Comment by jshaughn** [comment]
As @jmazzitelli points out, what you are seeing in the graph is typically just a reflection of what the telemetry is reporting.   Without that annotation it seems that the traffic generated from the frontend workload can not assign the detailed source information for the backend requests.  As such it looks like "unknown" is assigned, and makes it look like the "internet" is sending requests to both the frontend and backend workloads in your original graph.  In the second graph it seems the source_workload is getting assigned.   Note that your original graph is a "workload" graph type and the second one is a "versioned app" graph type.   In the second one we can see that you may have a labeling issue.  It seems both workload "frontend" and "backend" are labeled with app="playground".  That's maybe not what you want to do although it's totally up to you.  Istio recommends a different app label for each deployment:

"Deployments with app and version labels: It is recommended that pods deployed using the Kubernetes Deployment have an explicit app label and version label in the deployment specification. Each deployment specification should have a distinct app label with a value indicating something meaningful, with version indicating the version of the app that the particular deployment corresponds to. The app label is used to add contextual information in distributed tracing. The app and version labels are also used to add contextual information in the metric telemetry collected by Istio."  (see https://istio.io/docs/setup/kubernetes/spec-requirements/)

**Comment by DanTulovsky** [comment]
Thanks Jay.  I've been wondering what "App" should be, and it looks like
each micro service is an app.  I was thinking of an app as an entire
service, with all the different parts.

(Note that while the graphs in the screenshots may be different - workload
or versioned - the problem is the same if both are workload or versioned.)

**Comment by jshaughn** [comment]
Right, the problem would be the same in either graph type, I was just pointing out the difference.  If you think the generated telemetry is wrong you may want to create an Istio telemetry issue and see if they have an opinion.
