### ISSUE TITLE
Fail to deploy on GKE with istio addon: error when deploying clusterrole

### ISSUE THREAD

**Issue by raffomartini** [kiali/kiali#870]
**Describe the bug**
Attempting to install on GKE with Istio add-on fails: error when deploying clusterrole.yaml
Full error message below, possibly RBAC related.
```
Error from server (Forbidden): error when creating "STDIN": clusterroles.rbac.authorization.k8s.io "kiali" is forbidden: attempt to grant extra privileges:
[
{[get] [networking.istio.io] [virtualservices] [] []} 
{[list] [networking.istio.io] [virtualservices] [] []} 
{[patch] [networking.istio.io] [virtualservices] [] []} 
{[watch] [networking.istio.io] [virtualservices] [] []} 
{[create] [authentication.istio.io] [policies] [] []} 
{[delete] [authentication.istio.io] [policies] [] []} 
{[get] [authentication.istio.io] [policies] [] []} 
{[list] [authentication.istio.io] [policies] [] []} 
{[patch] [authentication.istio.io] [policies] [] []} 
{[watch] [authentication.istio.io] [policies] [] []} 
{[create] [authentication.istio.io] [meshpolicies] [] []} 
{[delete] [authentication.istio.io] [meshpolicies] [] []} 
{[get] [authentication.istio.io] [meshpolicies] [] []} 
{[list] [authentication.istio.io] [meshpolicies] [] []} 
{[patch] [authentication.istio.io] [meshpolicies] [] []} 
{[watch] [authentication.istio.io] [meshpolicies] [] []} 
{[create] [rbac.istio.io] [clusterrbacconfigs] [] []} 
{[delete] [rbac.istio.io] [clusterrbacconfigs] [] []} 
{[get] [rbac.istio.io] [clusterrbacconfigs] [] []} 
{[list] [rbac.istio.io] [clusterrbacconfigs] [] []} 
{[patch] [rbac.istio.io] [clusterrbacconfigs] [] []} 
{[watch] [rbac.istio.io] [clusterrbacconfigs] [] []} 
{[create] [rbac.istio.io] [serviceroles] [] []} 
{[delete] [rbac.istio.io] [serviceroles] [] []} 
{[get] [rbac.istio.io] [serviceroles] [] []} 
{[list] [rbac.istio.io] [serviceroles] [] []} 
{[patch] [rbac.istio.io] [serviceroles] [] []} 
{[watch] [rbac.istio.io] [serviceroles] [] []} 
{[create] [rbac.istio.io] [servicerolebindings] [] []} 
{[delete] [rbac.istio.io] [servicerolebindings] [] []} 
{[get] [rbac.istio.io] [servicerolebindings] [] []} 
{[list] [rbac.istio.io] [servicerolebindings] [] []} 
{[patch] [rbac.istio.io] [servicerolebindings] [] []} 
{[watch] [rbac.istio.io] [servicerolebindings] [] []} 
{[get] [monitoring.kiali.io] [monitoringdashboards] [] []}]
user=&{<redacted>
[system:authenticated] 
map[user-assertion.cloud.google.com:[AKUJVpnduVpEJSpT7rEDTKJVJ2equ/mvMNTSPXHGu0lX1vahoZ1Hrqji+hJLypk4yN718POnlspYNabZtKYaSQVnQ2V/fbuy86zjj5VCt9dxJXeYx1sRXazt6GWZDBwigo8WQxBg6DJtIKgJ6lGvKSW9YeHYnzo9KnT8iZAtiL69iYT3i1QksMn0j+cEx8F45+tfvEM19K9S1NtUR8XWcKRzv+sgsUad6i2ukyBnle1K]]} 
ownerrules=[{[create] [authorization.k8s.io] [selfsubjectaccessreviews selfsubjectrulesreviews] [] []} {[get] [] [] [] [/api /api/* /apis /apis/* /healthz /openapi /openapi/* /swagger-2.0.0.pb-v1 /swagger.json /swaggerapi /swaggerapi/* /version /version/]}] 
ruleResolutionErrors=[]
```
**Versions used**
Kiali: v0.15.0 (latest)
Istio: 1.0.3-gke.3
Kubernetes flavour and version: (e.g. OpenShift Origin 3.9)
1.11.7-gke.4

**To Reproduce**
Deploy kiali as seen on the docs:
`bash <(curl -L http://git.io/getLatestKialiKubernetes)`

**Comment by aljesusg** [comment]
Hi @raffomartini Thanks for the issue. Did you deploy istio from the releases or have you selected the istio default installation in GKE console? In both cases you should do this step https://preliminary.istio.io/docs/setup/kubernetes/platform-setup/gke/ and grant cluster administrator (admin) permissions to the current user. To create the necessary RBAC rules for Istio, the current user requires admin permissions.

```bash
$ kubectl create clusterrolebinding cluster-admin-binding \
    --clusterrole=cluster-admin \
    --user=$(gcloud config get-value core/account)
```

You must grant cluster-admin to your current identity we don't know in your environment what kind of security you have, by default permissions is granted in all the namespace istio-system (https://preliminary.istio.io).This is the latest release of Isito https://github.com/istio/istio/releases/tag/1.1.0-rc.0

**Comment by raffomartini** [comment]
That did the trick indeed!
Maybe it is wort mentioning it in the [docs](https://www.kiali.io/gettingstarted/#_install_kiali_2) ?

**Comment by gbaufake** [comment]
@raffomartini 

It is been described on GKE specifics (https://preliminary.istio.io/docs/setup/kubernetes/platform-setup/gke/)

**Comment by aljesusg** [comment]
That is a specific setup for GKE maybe we should link in the docs to the setup environments docs of the Istio website but this setup should be done before the Kiali installation so maybe the problem is in the Istio default installation in GKE

**Comment by pilhuhn** [comment]
Yes, we should mention it.
@raffomartini You could open a PR against https://github.com/kiali/kiali.io with your findings (?)

**Comment by raffomartini** [comment]
Done thanks: https://github.com/kiali/kiali.io/issues/103
