### ISSUE TITLE
istio multi cluster kiali bookinfo demo reviews-v3 error

### ISSUE THREAD

**Issue by kisterov** [kiali/kiali#896]
Hello Guys! 
I created istio multi cluster with single control plane, then i 
deployed bookinfo demo ( reviews-v1 and reviews-v2 ) to first cluster, then deployed ( reviews-v3 ) to second cluster. Istio and demo app work fine! 
But KIALI don't show ( reviews-v3 ), KIALI called him unknown
What should need do that KIALI will show clusters correct?
Plz answer it is a bug or You not have this functional on this moment?

my istioctl ps
PROXY                                                  CDS        LDS        EDS               RDS          PILOT                            VERSION
details-v1-6764bbc7f7-krg45.default                    SYNCED     SYNCED     SYNCED (100%)     SYNCED       istio-pilot-79f5f46dd5-dh5km     1.0.2
istio-egressgateway-864444d6ff-845mr.istio-system      SYNCED     SYNCED     SYNCED (100%)     NOT SENT     istio-pilot-79f5f46dd5-dh5km     1.0.2
istio-ingressgateway-694576c7bb-nqwpl.istio-system     SYNCED     SYNCED     SYNCED (100%)     SYNCED       istio-pilot-79f5f46dd5-dh5km     1.0.2
productpage-v1-54b8b9f55-r5qcj.default                 SYNCED     SYNCED     SYNCED (100%)     SYNCED       istio-pilot-79f5f46dd5-dh5km     1.0.2
ratings-v1-7bc85949-d2pcx.default                      SYNCED     SYNCED     SYNCED (100%)     SYNCED       istio-pilot-79f5f46dd5-dh5km     1.0.2
reviews-v1-fdbf674bb-xh2bp.default                     SYNCED     SYNCED     SYNCED (100%)     SYNCED       istio-pilot-79f5f46dd5-dh5km     1.0.2
reviews-v2-5bdc5877d6-lrdgv.default                    SYNCED     SYNCED     SYNCED (100%)     SYNCED       istio-pilot-79f5f46dd5-dh5km     1.0.2
reviews-v3-5469468cff-lrxm8.default                    SYNCED     SYNCED     SYNCED (100%)     SYNCED       istio-pilot-79f5f46dd5-dh5km     1.0.2

![screen shot 2019-03-06 at 1 58 45 pm](https://user-images.githubusercontent.com/47747919/53901290-4ff7b400-4047-11e9-81bf-7d4af8a4c170.png)

**Comment by abonas** [comment]
AFAIK multicluster is not supported by Kiali at the moment. to make sure - @mwringe @lucasponce?

**Comment by mwringe** [comment]
Kiali doesn't currently support multicluster.

**Comment by kisterov** [comment]
Thanks for the quick response!
We will wait for the expansion of the functional
Success in development!
Kiali - The Best !
