### ISSUE TITLE
Graph nodes don't appear

### ISSUE THREAD

**Issue by andrebriggs** [kiali/kiali#898]
**Describe the bug**
The graph nodes don't appear in the graph view. I do see the edges (arrows). Below is a screenshot of what I see. I have added blue boxes to signify where I expected to see node

<img width="1148" alt="screen shot 2019-03-07 at 12 02 35 pm" src="https://user-images.githubusercontent.com/3119513/53936863-57fc3600-40d1-11e9-9d80-7e64d6d9de82.png">
 
**Versions used**

- kiali-ui 0.12.0 (356ea85ab943d34e30ccca50152dde5f901c927a)
- kiali v0.12.0 (2a44b37707bec1b0a954dd5d71f5687ad0672935)
- Istio 1.0.6
- Prometheus 2.7.2
- Kubernetes v1.12.5 (via Azure Kubernetes Services)
- JaegerURL http://jaeger-query.jaeger.svc.cluster.local
- GrafanaURL http://grafana.grafana.svc.cluster.local

**To Reproduce**
1. Go to `http://127.0.0.1:20001/console/graph/namespaces/?edges=trafficRatePerSecond&graphType=service&namespaces=default&injectServiceNodes=true&duration=86400&pi=900000&layout=cose-bilkent`

Here are the logs from the Kiali pod when I refresh the page
`
I0307 06:38:27.509652       1 versions.go:146] DEBUG: Detected Istio version [root@464fc845-2bf8-11e9-b805-0a580a2c0506-docker.io/istio-1.0.6-98598f88f6ee9c1e6b3f03b652d8e0e3cd114fa2-dirty-Modified]
I0307 06:38:27.814803       1 graph.go:87] DEBUG: Build [service] graph for [1] namespaces [map[default:{default 21h30m34s}]]
I0307 06:38:27.814856       1 graph.go:93] DEBUG: Build traffic map for namespace [{default 21h30m34s}]
I0307 06:38:27.814931       1 graph.go:986] DEBUG: Graph query:
round(sum(rate(istio_requests_total{reporter="destination",source_workload="unknown",destination_service_namespace="default",response_code=~"[2345][0-9][0-9]"} [77434s])) by (source_workload_namespace,source_workload,source_app,source_version,destination_service_namespace,destination_service_name,destination_workload,destination_app,destination_version,response_code),0.001)@time=2019-03-07 06:38:27 (now=2019-03-07 06:38:27, 1551940707)
I0307 06:38:27.863872       1 graph.go:986] DEBUG: Graph query:
round(sum(rate(istio_requests_total{reporter="source",source_workload_namespace!="default",source_workload!="unknown",destination_service_namespace="default",response_code=~"[2345][0-9][0-9]"} [77434s])) by (source_workload_namespace,source_workload,source_app,source_version,destination_service_namespace,destination_service_name,destination_workload,destination_app,destination_version,response_code),0.001)@time=2019-03-07 06:38:27 (now=2019-03-07 06:38:27, 1551940707)
I0307 06:38:27.891536       1 graph.go:986] DEBUG: Graph query:
round(sum(rate(istio_requests_total{reporter="source",source_workload_namespace="default",response_code=~"[2345][0-9][0-9]"} [77434s])) by (source_workload_namespace,source_workload,source_app,source_version,destination_service_namespace,destination_service_name,destination_workload,destination_app,destination_version,response_code),0.001)@time=2019-03-07 06:38:27 (now=2019-03-07 06:38:27, 1551940707)
I0307 06:38:27.914532       1 graph.go:986] DEBUG: Graph query:
round(sum(rate(istio_tcp_sent_bytes_total{reporter="destination",source_workload="unknown",destination_workload_namespace="default"} [77434s])) by (source_workload_namespace,source_workload,source_app,source_version,destination_workload_namespace,destination_service_name,destination_workload,destination_app,destination_version),0.001)@time=2019-03-07 06:38:27 (now=2019-03-07 06:38:27, 1551940707)
I0307 06:38:27.916845       1 graph.go:986] DEBUG: Graph query:
round(sum(rate(istio_tcp_sent_bytes_total{reporter="source",source_workload_namespace!="default",source_workload!="unknown",destination_service_namespace="default"} [77434s])) by (source_workload_namespace,source_workload,source_app,source_version,destination_service_namespace,destination_service_name,destination_workload,destination_app,destination_version),0.001)@time=2019-03-07 06:38:27 (now=2019-03-07 06:38:27, 1551940707)
I0307 06:38:27.919329       1 graph.go:986] DEBUG: Graph query:
round(sum(rate(istio_tcp_sent_bytes_total{reporter="source",source_workload_namespace="default"} [77434s])) by (source_workload_namespace,source_workload,source_app,source_version,destination_service_namespace,destination_service_name,destination_workload,destination_app,destination_version),0.001)@time=2019-03-07 06:38:27 (now=2019-03-07 06:38:27, 1551940707)
I0307 06:38:27.954365       1 graph.go:959] DEBUG: Generating config for [cytoscape] service graph...
I0307 06:38:27.954512       1 graph.go:972] DEBUG: Done generating config for [cytoscape] service graph.
I0307 06:38:28.111949       1 client.go:157] Rest perf config QPS: 175.000000 Burst: 200
E0307 06:38:28.118204       1 grafana.go:27] services "grafana" not found
I0307 06:38:28.577335       1 client.go:157] Rest perf config QPS: 175.000000 Burst: 200
I0307 06:38:28.578895       1 client.go:157] Rest perf config QPS: 175.000000 Burst: 200
I0307 06:38:28.581987       1 health.go:255] DEBUG: Rate interval for namespace default was adjusted to 77435s (original = 86400s, query time = 2019-03-07 06:38:28.576499047 +0000 UTC m=+953.442801354, namespace created = 2019-03-06 09:07:53 +0000 UTC)
I0307 06:38:28.583094       1 health.go:255] DEBUG: Rate interval for namespace istio-system was adjusted to 77024s (original = 86400s, query time = 2019-03-07 06:38:28.577531399 +0000 UTC m=+953.443833706, namespace created = 2019-03-06 09:14:44 +0000 UTC)
I0307 06:38:28.592802       1 metrics.go:121] DEBUG: [extractMetricsQueryParams] Requested query start time: 2019-03-06 06:38:27 +0000 UTC
I0307 06:38:28.592835       1 metrics.go:126] DEBUG: [extractMetricsQueryParams] Query start time set to: 2019-03-06 09:55:53 +0000 UTC
I0307 06:38:28.598994       1 metrics.go:121] DEBUG: [extractMetricsQueryParams] Requested query start time: 2019-03-06 06:38:27 +0000 UTC
I0307 06:38:28.599038       1 metrics.go:126] DEBUG: [extractMetricsQueryParams] Query start time set to: 2019-03-06 09:55:53 +0000 UTC
`
**Expected behavior**

- I should see nodes in the graph. Not just edges
- I should see labels of the app, service, or workload

**Comment by pilhuhn** [comment]
@andrebriggs 0.12 is relatively old - but should nevertheless show the nodes. Could you check the browser console if there are any errors?

You could try to upgrade to 0.15 or :latest, but this will require installing additional settings for the service account etc.

**Comment by andrebriggs** [comment]
@pilhuhn this is what I see in Safari 
<img width="1201" alt="image" src="https://user-images.githubusercontent.com/3119513/53941873-4b7eda00-40df-11e9-8c7f-e67f90b2c0be.png">

I've been ignoring the Grafana error that seems related to #865 
<img width="239" alt="image" src="https://user-images.githubusercontent.com/3119513/53941956-8aad2b00-40df-11e9-8185-3e523d5b8891.png">

**Comment by abonas** [comment]
Do you see the entities in the other pages? (services, workloads, etc)
What browser are you using?

**Comment by jshaughn** [comment]
I see this is a Service graph type.  Do you have a similar issue with any other graph type (i.e. App, Versioned App, Workload)?  Note that Kiali 0.15 did include a fix specifically for service graphs.

Also, does changing the layout make any difference?  It seems you have "Cose" selected, there is also Dagre or Cola (you change this via in the bottom left toolbar by clicking a layout icon).

**Comment by jshaughn** [comment]
@andrebriggs Any updates?
