### ISSUE TITLE
Unknown Istio implementation version 

### ISSUE THREAD

**Issue by wansuiye** [kiali/kiali#911]
**General remarks**
![image](https://user-images.githubusercontent.com/11864894/54246978-0a207b80-4572-11e9-8f04-a83b0c9ba675.png)

**Describe the bug**

the pilot is recompiled, the kiali report the warning

For UI issues please also add a screenshot that shows the issue.

**Versions used**
Kiali:v0.12
Istio:1.0.6
Kubernetes flavour and version: (e.g. OpenShift Origin 3.9)
v1.11.2
**To Reproduce**

**Expected behavior**

**Comment by jotak** [comment]
@wansuiye Kiali warns that a self-made version of istio isn't recognized, which is true indeed, so it cannot guarantee that nothing is broken.
What is exactly your issue / expectation?

**Comment by jmazzitelli** [comment]
> Kiali warns that a self-made version of istio isn't recognized, which is true indeed, so it cannot guarantee that nothing is broken.

I +1 this. If you have a custom built Istio - a version Kiali is not aware of - it cannot guarantee that it will function correctly (indeed, lots of things changed just in telemetry alone from some Istio 1.0.x versions to the latest Istio 1.1 - and those older, non-backward-compatible changes are something Kiali does not support). Without recognizing the version of Istio that is being run, Kiali has no idea which Istio implementation this is - so Kiali here is simply warning you of that fact. Hence the warning message

`Unknown Istio implementation version ### is not recognized and thus not supported.`

**Comment by jotak** [comment]
Closing this ticket. @wansuiye please re-open if you have more information / expectation to bring.
