### ISSUE TITLE
Kiali doesn't understand Prometheus retention period described in days/weeks/years.

### ISSUE THREAD

**Issue by zendai** [kiali/kiali#916]
**General remarks**
Kiali fails to understand Prometheus' `storage.tsdb.retention` policy when it's described as days.

**Describe the bug**
When I start Kiali, I get this:
```
config.go:98] Invalid storage.tsdb.retention [60d]: time: unknown unit d in duration 60d
```

This is because my retention policy is described in days, `60d` (even the default is 15d) and Kiali appears to use [time.ParseDuration](https://github.com/kiali/kiali/blob/v0.16.0-snapshot.1/handlers/config.go#L86) to parse my time string, which [doesn't understand](https://golang.org/pkg/time/#ParseDuration) time flags beyond hour:
```
Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".
```

**Versions used**
Kiali: `1.15.0`, but it appears that's true even for the latest `v0.16.0-snapshot.1` as well.
Istio: `1.0.6`
Kubernetes flavour and version: `v1.10.12`

**To Reproduce**
Start Kiali, my log level was 5.

**Expected behavior**
Not sure how Kiali use this parameter, but I guess Kiali should be able to understand the time flags Prometheus supports in their duration format including `d`, `w` and `y` for day, week, and year.

**Comment by lucasponce** [comment]
Thanks for reporting the issue.
I've opened a technical JIRA
https://issues.jboss.org/browse/KIALI-2557

To follow this one closely.

**Comment by jotak** [comment]
FWIW I'm pretty sure there's an exported function that exists in prom's go client that we can (and should) reuse for that.

**Comment by jshaughn** [comment]
Fixed, will be in the next release.  Thanks @zendai !   Closing.
