### ISSUE TITLE
Kiali 0.16 doesn't work with non-default base root

### ISSUE THREAD

**Issue by zendai** [kiali/kiali#927]
**General remarks**
Kiali 0.16 won't work when I set a non-default base root

**Describe the bug**
When I set `web_root: /kiali` in the config file, kiali won't load anymore. The reason is because you are setting the base href to whatever the webroot `URL` + `'/'`, and you are [changing](https://github.com/kiali/kiali/blob/2b140465055d31218bab5f9ee48271d2344d8c3e/kiali.go#L251) the `./console/index.html` [file in place](https://github.com/kiali/kiali/blob/2b140465055d31218bab5f9ee48271d2344d8c3e/kiali.go#L250), but you are using an incorrect pattern to search and replace, so you leave the file untouched, even if I have webroot set.

As you can see [here](https://github.com/kiali/kiali/blob/2b140465055d31218bab5f9ee48271d2344d8c3e/kiali.go#L259):
```
	searchStr := `<base href="/">`
	newStr := `<base href="` + webRootPath + `/">`
	newHTML := strings.Replace(html, searchStr, newStr, -1)
```

 you are searching for `<base href="/">` and the actual pattern you have in your `index.html` is `<base href="/"/>` (look at the closing extra slash before the bracket close).

Here is your full index file:
```html
<!doctype html><html lang="en"><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no"/><meta name="theme-color" content="#000000"/><base href="/"/><script type="text/javascript" src="./env.js"></script><link re
l="manifest" href="./manifest.json"/><link rel="shortcut icon" href="./kiali_icon_lightbkg_16px.png"/><title>Kiali Console</title><link href="./static/css/main.57535d24.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscri
pt><div id="root"></div><script type="text/javascript" src="./static/js/main.f15fe5d6.js"></script></body></html>
```  

Formatted HTML:
```html
<!doctype html>
<html lang="en">
   <head>
      <meta charset="utf-8"/>
      <meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no"/>
      <meta name="theme-color" content="#000000"/>
      <base href="/"/>
      <script type="text/javascript" src="./env.js"></script>
      <link rel="manifest" href="./manifest.json"/>
      <link rel="shortcut icon" href="./kiali_icon_lightbkg_16px.png"/>
      <title>Kiali Console</title>
      <link href="./static/css/main.57535d24.css" rel="stylesheet">
   </head>
   <body>
      <noscript>
      You need to enable JavaScript to run this app.</noscript>
      <div id="root"></div>
      <script type="text/javascript" src="./static/js/main.f15fe5d6.js"></script>
   </body>
</html>
```

Also, would prefer to [write error](https://github.com/kiali/kiali/blob/2b140465055d31218bab5f9ee48271d2344d8c3e/kiali.go#L264) log here instead of just return, true though this wouldn't have caught this one as we don't have any errors here, just the search and replace looking for a pattern that doesn't exist in the file.

**Versions used**
Kiali: `0.16`
Istio: `1.0.6`
Kubernetes flavour and version: (e.g. OpenShift Origin 3.9) `1.10.12`

**To Reproduce**
Just start Kiali with a config where you have
```
server:
  web_root: /kiali
```
set, and Kiali will fail to load, as all the relative files will be relative to `/` since the base is left `/`.

**Expected behavior**
If you properly search and replace the `index.html` file, the initial files will load properly from the alternative webroot and Kiali will start to function.

**Comment by jmazzitelli** [comment]
I *just* ran into this myself.

**Comment by jmazzitelli** [comment]
I don't know how this could have changed - I don't think we altered any functionality in this area (but I guess we did).

**Comment by jmazzitelli** [comment]
Yes, apparently, that was changed here: https://github.com/kiali/kiali-ui/commit/e2eb6dbd45ebb4884167ebb64c75900d88fb0695#diff-528c3923d718a8860f5d8c05c3931c55R7

I'm going to fix. Stay tuned for the PR

**Comment by jmazzitelli** [comment]
fixed: https://github.com/kiali/kiali/pull/928
the "latest" image should work.
Will try to update the v0.16 image to point to a new v0.16.1 that we will release - that's what we'll use for upstream istio helm charts since it needs this feature to work

**Comment by zendai** [comment]
@jmazzitelli thank you

**Comment by jmazzitelli** [comment]
@zendai this should be fixed now. Docker hub has the new v0.16.1 and the image v0.16 is now pointing to that latest patch release. I just did a quick smoke test and its working.

If you can confirm it works, we can close this issue.

**Comment by zendai** [comment]
@jmazzitelli can confirm, it works.

Thank you,
sendai
