### ISSUE TITLE
Docker Swarm Support

### ISSUE THREAD

**Issue by gabrieligbastos** [kiali/kiali#932]
First of all, congratuliations for the project. The tool is really impressive and amazin! 

Here we user Docker Swarm as orchestrator for microservices. Is there any plan to support Docker Swarm?

**Comment by jmazzitelli** [comment]
There are no plans to support Docker Swarm. We are concentrating efforts on Kubernetes and its downstream derivatives (e.g. OpenShift, GKE, etc).

**Comment by jotak** [comment]
@gabrieligbastos anyway, before having Kiali supporting docker swarm you would need Istio to support docker swarm and as far as I know it's not the case (or is it?)
Kiali depends heavily on kubernetes, so even if there was a community initiative to start that work, that would be a huge refactor in Kiali I think, and probably it would be best to consider a fresh start from scratch instead.

**Comment by israel-hdez** [comment]
@jotak I see that Istio can be installed without a cluster, using bare Docker: https://istio.io/docs/setup/consul/install/
I guess this means that you can use those instructions as a base to deploy to Docker Swarm.

But Istio relies on the API server and uses a customized one for bare Docker. Perhaps by using Istio's api-server the Kiali support may be doable.
