### ISSUE TITLE
Helm template install Service "kiali" is invalid: spec.ports[1].name : Duplicate value: "http-kiali"

### ISSUE THREAD

**Issue by shawnstout** [kiali/kiali#937]
**General remarks**

> Please delete this section including header before submitting
>
> This form is to report bugs. For general usage questions refer to 
>       [Kiali-users](https://groups.google.com/forum/#!forum/kiali-users) mailing list.
>
> For general Kiali-development questions refer to 
>       [Kiali-dev](https://groups.google.com/forum/#!forum/kiali-dev) mailing list.

**Describe the bug**

For UI issues please also add a screenshot that shows the issue.

**Versions used**
Kiali:
Istio:
Kubernetes flavour and version: (e.g. OpenShift Origin 3.9)

**To Reproduce**

**Expected behavior**

**Comment by jmazzitelli** [comment]
I am completely confused what this is. The description is nothing but the template, am I missing something?

**Comment by shawnstout** [comment]
Sorry, when deploying out the helm template, the above error shows up on multiple re-deploys after.  You have to manually delete out the kiali service in order for the helm template to work again without giving the above error.

**Comment by jmazzitelli** [comment]
OK, sounds like this is related to the Istio 1.1 helm charts (there are no helm charts managed/maintained in this kiali repo - that's all done upstream).

If so, it would be best to open an issue upstream in the istio project - that's where the helm charts live and where the helm charts are maintained:

https://github.com/istio/istio/issues

Recommend when you create an issue, that you fill in the description - e.g. replication procedures, commands you used, etc. If you read your description of this issue - it's nothing but the template text.
