### ISSUE TITLE
Question: Not seeing traffic to serviceEntries

### ISSUE THREAD

**Issue by Karnich** [kiali/kiali#945]
**Describe the bug**

Pretty basic. Ive been toying a lot with Istio, Kiali and CNIs over the past week.

When i have Calico, Istio and Istio-CNI up and running. I have seen a Service Entry popup. But now im no longer using any CNI. Since it broke stuff. But i am no longer seeing traffic to "external sites"

What is required for this? Im allowing all traffic out. Do i need to force it through a service entry?

```
  outboundTrafficPolicy:
    mode: ALLOW_ANY
```

**Versions used**
Kiali: v0.16.2
Istio: 1.1.0
Kubernetes flavour and version: v1.12.5-gke.5

**Comment by jshaughn** [comment]
Are you seeing the traffic at all?  Meaning, do you see the outgoing requests reflected in the graph with any sort of destination node type reflecting the service entry (square app node, circle workload node)?   If you see no traffic at all it would typically mean that Istio is not even generating the telemetry.  That could possible be due to no sidecar injected in the source pod.   If you are seeing the traffic but the node isn't reflected as a service entry then perhaps we're not identifying the SE correctly.

**Comment by Karnich** [comment]
@jshaughn im seeing plenty of traffic internally. But im not seeing any SE or traffic to them. I actually tried enabling REGISTRY_ONLY but that didnt really change anything.

**Comment by jshaughn** [comment]
@Karnich Ah, so you're saying that the service entry requests are not even making it to the outside world.  That would be more of an Istio question.  Although, I would have expected Kiali to show you those SE requests in the graph, unless they are 1) not actually being generated or 2) the source workload does not have a sidecar (envoy proxy container) injected.   I'm not an expert on ServiceEntry config, maybe someone else can chime in, or maybe follow up in the [Istio forums](https://discuss.istio.io/).

**Comment by Karnich** [comment]
@jshaughn im actually not seeing the sidecar capturing the outbound traffic to external sources?
hmm

any way of whitelisting so that the sidecar would not capture it?

Im saying that outbound traffic to external sites work just fine but do not seem to be captured by the sidecar.. so you obviously cant log it i guess

**Comment by pilhuhn** [comment]
@Karnich This screenshot is with a SE 'bla-service-ratings.bookinfo' , so traffic from an internal WL to an external SE is recorded here. And I can see that the external app, this is pointing to, is receiving traffic

![Bildschirmfoto 2019-03-25 um 15 36 37](https://user-images.githubusercontent.com/208246/54928374-13b3c700-4f14-11e9-80b8-62c26ad2e377.png)

Can you perhaps post your VS/SE config?

**Comment by israel-hdez** [comment]
@jshaughn @pilhuhn I think that the question is more related with the external traffic policy that @Karnich has in place:

> What is required for this? Im allowing all traffic out. Do i need to force it through a service entry?
> ```
>   outboundTrafficPolicy:
>   mode: ALLOW_ANY
> ```

With these setup, external traffic is allowed by default. So, there is no need for SE to be created.
I reported this a month ago in https://issues.jboss.org/browse/KIALI-2441. Priority was changed to minor, so I guess we won't look at that Jira soon.

@Karnich If you tried with REGISTRY_ONLY, as @pilhuhn asks, can you share an example of one of your VS/SE configs? Perhaps there is something we aren't considering.

**Comment by israel-hdez** [comment]
Hi, @Karnich 
Reading the docs at https://istio.io/docs/tasks/traffic-management/egress/ this paragraph is an important note:

> Note that if you configure Istio with allowed access to external services this way, you lose Istio monitoring on traffic to external services: the calls to external services will not appear in the Mixer log, for example. To start monitoring access to external services, follow the steps in configure access to external services (no need to update Istio).

So, when using `ALLOW_ANY` for external traffic policy, Kiali won't be able to show the requests because they are not monitored by Istio.

If you want to have monitoring enabled for external traffic, you will need to use `REGISTRY_ONLY` and, also, create the relevant ServiceEntries (else, traffic will be blocked). Then, Kiali should show the external traffic.

**Comment by pilhuhn** [comment]
Good find @israel-hdez 

I think we should somehow indicate this setting in Kiali. Masthead seems overkill, but at least the About box. I think the "debug Info" is not "parseable" for mere mortals

**Comment by israel-hdez** [comment]
@pilhuhn I agree that there should an indicator for the setting. I also agree that the masthead may not be the place. The about box sounds OK, but also a bit hidden. I just created a Jira (https://issues.jboss.org/browse/KIALI-2646) to discuss there how to show it and focus this thread on the reported issue.

**Comment by Karnich** [comment]
@israel-hdez Yeah i suspected as much. Ive fought a battle with istio when trying to use the CNI on GKE. Ive decided to back out of that battle and that makes me see more clearly what is causing what... Its a shame those that it does not log external traffic even with `ALLOW_ALL`because that would make it way easiere to spot what would get blocked, before blocking it.

Also when you read this line you would expect it to be captured regardless of other settings:
```
# istio egress capture whitelist
    # https://istio.io/docs/tasks/traffic-management/egress.html#calling-external-services-directly
    # example: includeIPRanges: "172.30.0.0/16,172.20.0.0/16"
    # would only capture egress traffic on those two IP Ranges, all other outbound traffic would
    # be allowed by the sidecar
    includeIPRanges: "*"
```

The funny thing i saw when toying with the CNI was that i was external traffic in Kiali going to one of my ServiceEntrys when i had the Istio CNI enabled.. even with `ALLOW_ANY`

But with CNI enabled my application basically didnt work because it depends on RabbitMQ and RabbitMQ didnt work with the CNI -.-

Thanks for the help guys.

One more thing tho :P im seeing an "Unknown" ping one of my apps very frequently. Its still Unknown even with all Namespaces enabled. But i cant enable `kube-system` since it doesnt show up in the dropdown. i dont know if its plausible that something there would be polling my app tho.

**Comment by mkjoerg** [comment]
@Karnich do you have Kubernetes Helm Checks enabled? I guess the Kube API Server could be the source of these requests and due to the fact, that it is not part of the mesh, the traffic seems to be of unkown source.
