### ISSUE TITLE
Question: Can use more than one label to group my app?

### ISSUE THREAD

**Issue by HeathLee** [kiali/kiali#954]
https://github.com/kiali/kiali/blob/25707c3a2fb00aa12bd93083668cb64df208a7b0/config.yaml#L44
I want use two label to identify my app, is this possible?

**Comment by jotak** [comment]
This is not currently possible. To better understand your request, do you want to use two labels interchangeably ( `app1=foo` or `app2=foo` ) or do you want to have a combination of labels to identify the app? (`app1=foo && app2=bar`)

**Comment by jmazzitelli** [comment]
Note, this isn't possible with out-of-the-box Istio either - you would need to alter the metrics where the telemetry comes from in order to even get Prometheus to store data for apps that use multiple labels. So this would require changes to both Kiali and Istio.

**Comment by abonas** [comment]
at the moment Istio is taking into account the app and the version labels (app label can be configured to a different one in Kiali), but indeed as Joel asked above, it's important to understand what use case are you looking for.

**Comment by HeathLee** [comment]
I  want have a combination of labels to identify the app? `app1=foo && app2=bar`

**Comment by HeathLee** [comment]
My apps provide rest api and grpc both. I labeld them with `app=foo tier=api` or `app=foo tier=rpc`

**Comment by jmazzitelli** [comment]
> My apps provide rest api and grpc both. I labeld them with `app=foo tier=api` or `app=foo tier=rpc`

If you label your apps that way (and assuming you are using Istio telemetry definitions that come out of the box), and you look in the Istio telemetry (look in Istio's Prometheus) you will see that all your tiers (api and rpc) will be aggregated into a single app=foo. So even Istio won't be splitting out the telemetry between your different tiers like you want. And Kiali just displays what Istio stores in telemetry (in Prometheus) - so it will so the aggregated Istio telemetry.

Perhaps one workaround for this could be having three labels "app=foo-api" along with "base-app=foo" and "tier=api" -- this will still give you the separate labels in case you want to do your own querying (base-app and tier) but provides the combined app label for Istio (and thus Kiali) to use.
