### ISSUE TITLE
Checks failed when use k8s cluster based internal FQDN

### ISSUE THREAD

**Issue by sunadm** [kiali/kiali#975]
**Describe the bug**

Kiali UI report "Not all checks passed!" when Virtual Service use k8s cluster based internal FQDN and destination host FQDN doesn't in Gateway's same namespace.
Error message: "DestinationWeight on route doesn’t have a valid service (host not found)"
https://github.com/kiali/kiali/blob/master/business/checkers/virtual_services/no_host_checker.go
![image](https://user-images.githubusercontent.com/5113279/55539528-70249c80-56f3-11e9-9ef2-d2268e06c299.png)

**Versions used**
Kiali: v0.14.0
Istio: 1.1.1
Kubernetes flavour and version: AliCloud v1.12.6-aliyun.1

**Comment by lucasponce** [comment]
Thanks for reporting this @sunadm 

cc @burmanm I remember there was a full fqdn check here, perhaps this is a bug ?

**Comment by lucasponce** [comment]
JIRA created to track the work on this
https://issues.jboss.org/browse/KIALI-2672

**Comment by burmanm** [comment]
For the original reporter, the FQDN itself is not the issue, but that we don't support validating VirtualService hosts cross-namespace at the moment. It might make sense to annotate this in the error message..

**Comment by JohannesEH** [comment]
@lucasponce related to this the template validation seems to be having issues validating a virtual-service using the following syntax:

```
  gateways:
    - istio-system/istio-gateway
```

**Comment by lucasponce** [comment]
@JohannesEH right
It sounds that format is not yet supported in Kiali.

Thanks for the pointer.

cc @burmanm

**Comment by lucasponce** [comment]
@JohannesEH I think this use case is included in latest releases.
Please, let us know if that confirms your scenario.

**Comment by JohannesEH** [comment]
@lucasponce Thanks for the fix, unfortunately I'm not able to test it in the foreseeable future. Sorry.

**Comment by lucasponce** [comment]
@JohannesEH I think @burmanm 's fix worked here.
Going to close this one.
Please, don't hesitate to re-open it if there is anything else to address.
Thanks
