### ISSUE TITLE
Kiali graph not showing traffic to some services of the mesh

### ISSUE THREAD

**Issue by codependent** [kiali/kiali#984]
**Describe the bug**
I have a mesh consisting of 4 services, one of them aggregates calls to the other 3 ones. The Kiali UI graph shows a green arrow from the istio-ingressgateway to the first one (global-position-service), but it doesn't show traffic to the others although the mesh is working fine:

<img width="723" alt="Screenshot 2019-04-07 at 12 26 43" src="https://user-images.githubusercontent.com/6399869/55682249-4658b900-5931-11e9-8ae6-2bc10492fa3f.png">

**Versions used**
Kiali: 0.7.2
Istio: 1.0.2
Kubernetes flavour and version: OpenShift 3.10

**To Reproduce**
Gateway configuration:
```apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: insuranceinc-gateway
  namespace: istio-insuranceinc
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"```
Virtual service configuration:
```apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: insuranceinc
  namespace: istio-insuranceinc
spec:
  hosts:
  - "*"
  gateways:
  - insuranceinc-gateway
  http:
  - match:
    - uri:
        prefix: /insuranceinc
    rewrite:
      uri: " "
    route:
    - destination:
        host: global-position-service
        port:
          number: 8080
```

Every service has its associated k8s service, e.g.:

```
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: 2019-04-06T16:40:18Z
    labels:
      app: global-position-service
      template: springbootembedded-build
      version: 1.0.0
    name: global-position-service
    namespace: istio-insuranceinc
    resourceVersion: "88666"
    selfLink: /api/v1/namespaces/istio-insuranceinc/services/global-position-service
    uid: a9b92f9a-588a-11e9-aae1-66e73c3101a7
  spec:
    clusterIP: 172.30.90.0
    ports:
    - name: tcp-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentconfig: global-position-service
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: 2019-04-06T17:05:18Z
    labels:
      app: home-policy-service
      template: springbootembedded-build
      version: 1.0.0
    name: home-policy-service
    namespace: istio-insuranceinc
    resourceVersion: "91455"
    selfLink: /api/v1/namespaces/istio-insuranceinc/services/home-policy-service
    uid: 2777627a-588e-11e9-9a01-66e73c3101a7
  spec:
    clusterIP: 172.30.240.85
    ports:
    - name: tcp-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentconfig: home-policy-service
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
```

**Expected behavior**
I should see traffic to all services

**Comment by jmazzitelli** [comment]
> Kiali: 0.7.2
> Istio: 1.0.2
> Kubernetes flavour and version: OpenShift 3.10

You have a super-old version of Kiali, a very old version of Istio, and an old version of OpenShift :)

(Let me guess - you are using knative?)

That version of Kiali is really outdated - so much has changed since then. It wouldn't surprise me if it's a bug in that old Kiali that has since been fixed. I would recommend to move up to the latest Kiali, but I'm not even sure how much changed in the Istio's telemetry since Istio 1.0.2 so it may not work. But that's what you should try. You might even want to try some later version of Kiali, even if not the latest.

**Comment by codependent** [comment]
Actually I'm using minishift, I installed Istio, and thus Kiali, following their documentation: https://github.com/minishift/minishift-addons/tree/master/add-ons/istio

I'll try to start from scratch installing Istio and Kiali without the minishift addon which, as you say, seems to be outdated.

**Comment by codependent** [comment]
I have upgraded to Istio 1.1.1 Kiali 0.14.0 and Minishift with Openshift 3.11.0. 

The same is happening, the first application displays green status but the downstream services don't:

<img width="1114" alt="Screenshot 2019-04-08 at 10 41 23" src="https://user-images.githubusercontent.com/6399869/55710520-1241ce80-59eb-11e9-8d8f-a328d7e921f6.png">

Selecting car-policy-service, at the right side we can see no HTTP traffic logged

<img width="1423" alt="Screenshot 2019-04-08 at 10 41 52" src="https://user-images.githubusercontent.com/6399869/55710545-208fea80-59eb-11e9-810d-b027d96c6169.png">

Turning on traffic animation it shows there's actual traffic reaching car-policy-service:

<img width="1436" alt="Screenshot 2019-04-08 at 10 44 43" src="https://user-images.githubusercontent.com/6399869/55710679-6d73c100-59eb-11e9-97e5-8e6d9c83716b.png">

What could be the reason why downstream services don't show a green status and don't log request information?

**Comment by jshaughn** [comment]
Global-position-service-1 and car-policy-service-1 don’t have the Istio sidecar containjected in the pod

**Comment by codependent** [comment]
@jshaughn They do have it:

<img width="1425" alt="Screenshot 2019-04-08 at 15 38 15" src="https://user-images.githubusercontent.com/6399869/55728483-7036dc00-5a14-11e9-9d88-8e52448440e2.png">

**Comment by codependent** [comment]
I've found the problem. I have changed the service definition from
```
    spec:
      ports:
        - name: "tcp-8080"
          protocol: "TCP"
          port: 8080
          targetPort: 8080
```
to
```
    spec:
      ports:
        - name: "http"
          protocol: "TCP"
          port: 8080
          targetPort: 8080
```

And it started working as expected

<img width="1453" alt="Screenshot 2019-04-08 at 15 56 08" src="https://user-images.githubusercontent.com/6399869/55729669-d886bd00-5a16-11e9-8d3b-2d5a9a498a75.png">

**Comment by jshaughn** [comment]
Sorry, I didn’t mean to close the issue earlier.  Glad you found the fix.  Not sure why we saw the missing sidecar badges in the above graph.  I’ll re-open but if you are satisfied feel free to close.

**Comment by codependent** [comment]
No worries 😉. Maybe an explanation of this behaviour in the docs could clear it up.
