### ISSUE TITLE
Investigate Kiali support for proposed Istio "Telemetry Lite"

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#990]
Today's Istio Policies and Telemetry WG meeting discussed a propsed "telemetry lite" feature/PR possibly going into Istio (either 1.1 and 1.2). The idea is to reduce the amount of telemetry flowing through the system - this means the istio_* metrics that Kiali uses would not be populated, but most of the data can be found in some envoy_* metrics that Kiali could use.

@mandarjog asked if Kiali could be able to produce a "degraded graph" - if it sees there is no istio_* telemetry, switch over to show a degraded graph (won't be able to show everything we do now, but show SOMETHING to at least indicate where possible problems are in the mesh).

See this document and PR:

https://docs.google.com/document/d/1N7aWrFq0AICsibTGVSdMLvHXdCkBQZofHiL3Ywb1cmg/edit#

https://github.com/istio/istio/pull/12928

It is possible this feature/PR is NOT going to be merged into Istio. And it may (even if it does go in) go away in 1.3 if the new Mixer is as performant/scalable as hoped. But we should at least be proactive and think about what work would be needed in order to support something like this, just in case it is needed for Kiali to support this.

**Comment by jshaughn** [comment]
The entire graph, including side panels, response times, security, mtls, etc, is derived from the Istio metrics.  I believe most of the metrics as well.  I'm not sure about impact to health calculations.  Kiali would be very much crippled in this scenario.  I think we could potentially perform some sort of health, and continue to show non-metric details.  It would still be a lot of work to be able to degrade to something usable/useful.  I don't know much about what we'd need to do to generate some sort of traffic map/graph using Envoy metrics but I would guess it would be close to starting over.

**Comment by monkeymorgan** [comment]
Is there an envoy_ equivalent for each istio_ metric @jmazzitelli ?

If so would it be possible via making the metric names used by kiali configurable ?

I ask for a somewhat different but related motive.  Internally in our company we have a standard set of RED metrics from our http apps which are a superset of the istio_ metrics kiali uses so I wondered if it would be possible to use kiali without istio as long as we used the same tags on these metrics. There would be no istio CRDs obviously so some of the vizualisations would not work but the killer feature we see is the live topology with http error rates and the service to service metrics pages. If that alone worked it would be worth deploying for us.

The metrics I see kiali depends on are 

```
istio_requests_total
Istio_request_duration_seconds_bucket
istio_request_bytes
istio_response_bytes
istio_tcp_sent_bytes_total
istio_tcp_received_bytes_total
```

We would also have to use the same concepts (workload/service) and the same tags. I haven't done a full audit of the tags but they include : 
 
```
[destination|source]_workload
[destination|source]_workload_namespace
[destination|source]_namespace
[destination|source]_app
reporter=”source” or “destination”
response_code
```

If support for envoy metrics is likely - please consider making the metrics generally configurable. Although perhaps I should create a separate issue ?

**Comment by jmazzitelli** [comment]
> Is there an envoy_ equivalent for each istio_ metric @jmazzitelli ?

As I understand it, no. "Telemetry Lite" IIRC is just a temporary solution the Istio folks thought about doing until the Mixer V2 comes online. Because of the temporary status (and the crippling effect it would have on visualization tools like Kiali) we've decided to not attempt right now to support "Telemetry Lite."

**Comment by jotak** [comment]
@monkeymorgan however what you described is something that could be interesting, regardless what we can do with the envoy metrics.
Actually there's already been some preliminary work to go in that direction : https://github.com/kiali/kiali/pull/1068 , but we haven't any generic support for metrics at the moment.

If you want to contribute, you're welcome!

**Comment by jshaughn** [comment]
@monkeymorgan I don't think there is an Envoy equivalent for the Istio metrics.  Istio combines some info from different sources to populate its metrics.

If you do have metrics that could replace the Istio metrics we could look into making the metric names configurable.  Those metric substitutions would have to be applied not only to the graph topology generation but also our backend metrics API, which helps power the side panels and other pages.

But to truly run without Istio there could be other issues, as nothing that calls the Istio APIs would be available.  The UI is the main concern.  As @jotak mentions above, we have just started looking at making it easier to extend the backend.  Input or contributions appreciated.

Although not near-term, there is also the new SMI spec released.  If that generates momentum it could be a way for different folks to plug in by providing an SMI adapter for their backend.
