### ISSUE TITLE
Feature request: Envoy Filter

### ISSUE THREAD

**Issue by Buri** [kiali/kiali#995]
**Describe the bug**
Istio has support for [EnvoyFilter](https://istio.io/docs/reference/config/networking/v1alpha3/envoy-filter/), but Kiali has not. Is it possible to add type EnvoyFilter to config section, so it is possible to edit it from UI?

**Versions used**
Kiali: 0.16.2
Istio: 1.1.1
Kubernetes flavour and version: AWS EKS v1.11.8-eks-7c34c0

**To Reproduce**
1. Go to 'Istio Config'
2. Click on 'Istio type selector'
3. EnvoyFilter is not present

**Expected behavior**
Be able to select EnvoyFilter

**Comment by pilhuhn** [comment]
Thank you for your suggestion. Displaying the presence of such filters and potentially their details may be "easily" doable. 
How do you envision the editing - especially as the actual filter config seems not to be simple yaml or json to just show, but some more complex data type.
Would you be able to help us on this?

**Comment by Buri** [comment]
I think that for now it would be enough to just show yaml editor for now, especially since there is some ongoing discussion over at Istio about changes that are coming to Envoy Filters (Envoy is deprecating some functionality on their end).

**Comment by israel-hdez** [comment]
@Buri Looks like the team has been busy :)
If you have the time to prepare a PR to implement this, we will be more than happy to incorporate your feature.

I see that "Gateways" have the same behavior you describe about showing the YAML with no overview page, so the involved code could bring some guidance about how to implement this.

**Comment by Buri** [comment]
Might aswell give it a shot :)

**Comment by lucasponce** [comment]
Thanks @Buri, indeed the EnvoyFilter is the missing resource to be added to Kiali.

If you like to work on this feature, please let me know and I can assign this issue to you.

Also happy to help you to jump into the project, it should be easy to implemented as there are only needed a couple of changes in backend/frontend.

Please, feel free to contact us at anytime and we can help you on this.

**Comment by josejulio** [comment]
@Buri If you are still interested in adding support for `EnvoyFilter`, you can check the PRs that added support for the `Sidecar` resource.

https://github.com/kiali/kiali/pull/1108
https://github.com/kiali/kiali/pull/1130
https://github.com/kiali/kiali-ui/pull/1230

**Comment by lucasponce** [comment]
Hi @Buri, I'm reviewing this issue.
Would you like to work on it ?
Please, let us know and we can help to jump into the project.

**Comment by lucasponce** [comment]
Kiali has now support to Sidecars. EnvoyFilter is the missing config entity to be managed from Kiali.
